### ISSUE TITLE
picture at top of drawer

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/MaterialDrawer#1]
Please make it adjustable to set a picture at the top of the drawer.

**Comment by mikepenz** [comment]
@Rainer-Lang is theoretically already possible. 

Get the ListView from the Drawer.Result and pass a HeaderView to the list

Will simplify this :D

**Comment by mikepenz** [comment]
@Rainer-Lang in :D Or at least a sample in the sample app.
