### ISSUE TITLE
ToolBar title.

### ISSUE THREAD

**Issue by Grozny** [mikepenz/MaterialDrawer#100]
Initial toolbar title withSelectedItem name

**Comment by mikepenz** [comment]
@Grozny the toolbar and it's content should be managed by the dev. (just implement this in the `withOnDrawerItemClickListener` method) You can even set the drawer to initially fire an event for this case.

**Comment by Grozny** [comment]
@mikepenz <https://github.com/mikepenz> thank you for looking into this!
I use this code to set the drawer to initially fire an event for this case.

 .withSelectedItem(0)
                .withOnDrawerItemClickListener(new
Drawer.OnDrawerItemClickListener() {
                    @Override
                    public void onItemClick(AdapterView<?> parent, View
view, int position, long id, IDrawerItem drawerItem) {
                        if (drawerItem != null) {
                            if (drawerItem instanceof Nameable) {
                                toolbar.setTitle(((Nameable)
drawerItem).getNameRes());
                            }
                        }
                    }
                })
                .withFireOnInitialOnClick(true)

but doesn't work

2015-03-13 17:29 GMT+00:00 Mike Penz <notifications@github.com>:

**Comment by mikepenz** [comment]
have you set the toolbar as supportActionBar?

**Comment by Grozny** [comment]
yeh

2015-03-13 17:43 GMT+00:00 Mike Penz <notifications@github.com>:

**Comment by mikepenz** [comment]
try. getSupportActionBar().setTitle("sometitle");

**Comment by Grozny** [comment]
with this line getSupportActionBar().setTitle("sometitle");
DONE.

2015-03-13 18:03 GMT+00:00 Mike Penz <notifications@github.com>:
