### ISSUE TITLE
Profile Icon URL not working

### ISSUE THREAD

**Issue by bkawakami** [mikepenz/MaterialDrawer#1000]
Hi :)

I tried insert a URL in Profile Icon, how is said in this link: https://github.com/mikepenz/MaterialDrawer/issues/966

But I just see a blank image :(

Here my code:

```kotlin
val login = LoginRepository.getCurrentLogin()

val profile = ProfileDrawerItem()
                .withName(login?.name)
                .withEmail(login?.email)
                .withIcon(login?.picture) // here the url

val headerResult = AccountHeaderBuilder()
                .withActivity(activity)
                .withHeaderBackground(R.drawable.header_profile)
                .addProfiles(profile)
                .build()
```

Someone know what the problem?

**Comment by mikepenz** [comment]
@bkawakami you also have checked this: https://github.com/mikepenz/MaterialDrawer#load-images-via-url ?

**Comment by bkawakami** [comment]
Yes, but I do not quite understand how it should be used or instantiated. I saw examples and did not understand very well :(

You have any tutorial or more complete example?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java

The sample application is complete

**Comment by dreamcatcha** [comment]
Where do you load the profile image in the activity? excuse my ignorance

**Comment by mikepenz** [comment]
@dreamcatcha you do the above. and then you just define the url for the `ProfileDrawerItem`
