### ISSUE TITLE
cannot resolve method with 'withSubItems()'

### ISSUE THREAD

**Issue by CeJienAJPC** [mikepenz/MaterialDrawer#1002]
Hi Mike,
Firstly thanks for maintaining this awesome lib.

I intend to build a drawer with collapsable menu item
like, 
"item
   subItem1
   subItem2"

So here is my piece of code
.addDrawerItems(
new  SecondaryDrawerItem().withIcon(R.drawable.icon_language).withName(R.string.drawer_subtitle_language).withSubItems(
                                new SecondaryDrawerItem().withIcon(R.drawable.icon_theme).withName(R.string.drawer_subtitle_theme).withLevel(2),
                                new SecondaryDrawerItem().withIcon(R.drawable.icon_font_size).withName(R.string.drawer_subtitle_font_size).withLevel(2)),

However, android studio is unable to resolve the method 'withSubItems()'. I am unable to identify the issue. Am I missing something?

Regards

**Comment by mikepenz** [comment]
@CeJienAJPC v5.0.0 is not yet released. Still in testing: https://github.com/mikepenz/MaterialDrawer/issues/920
