### ISSUE TITLE
SwitchColor

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/MaterialDrawer#1003]
I'm using MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus and I want to change the switch color, colorAccent is set, but the color remains the same

**Comment by mikepenz** [comment]
@EpsilonOrionis that is out of scope of my theme. You can use my theme as parent, and change the color attributes in your theme then

**Comment by EpsilonOrionis** [comment]
...

**Comment by mikepenz** [comment]
@EpsilonOrionis I'm sorry. The theme works starting with API 10 and has to be fine for all default cases. If you want to change the different details this will require you to use this one as `parent` and define the details for your application.
