### ISSUE TITLE
RTL layout

### ISSUE THREAD

**Issue by soheilserver** [mikepenz/MaterialDrawer#1005]
how is it possible to position the icon of items to the right side of the text and the badge to the left (for rtl fonts)?
note: I have already found an answer here #980, but it is not a very well solution as it limits me so much(requires API +17). isn't there any other solution ?! 
thank u so much for ur awesome library ;)

**Comment by soheilserver** [comment]
#980

**Comment by mikepenz** [comment]
@soheilserver RTL support on Android was added in API 17. 

As an alternative you could theoretically create your own `CustomDrawerItem` which has a reversed layout. Or you overwrite the default layout. But this also won't change that the Hamburger icon is on the right.

**Comment by soheilserver** [comment]
+1, good and easy solution. thanx
