### ISSUE TITLE
problem with PersistentHeader Drawer and ViewPager

### ISSUE THREAD

**Issue by jfloresB** [mikepenz/MaterialDrawer#1006]
The problem is that only need the sliding area is the size of the mini drawer, not entire screen, to be able to use the screen with a view pager. Thanks for the library.

**Comment by mikepenz** [comment]
@jfloresB could you please add more details. I am not quite sure what is wrong, or what causes troubles on your side

**Comment by jfloresB** [comment]
as it is not a problem, what I need is that the area of the slide is the size of minidrawer, not to interfere with the operation of view pager, because by making the gesture to the right the menu is displayed and not the view slides pager (as should naturally), thanks for the help.

**Comment by mikepenz** [comment]
@jfloresB just add the following to your `Crossfader` `.withGmailStyleSwiping()`. This should enable that the `Crossfader` only takes the touch if it is on the view of the `MiniDrawer`

**Comment by jfloresB** [comment]
thank you very much for your help, it is an excellent library.

**Comment by mikepenz** [comment]
Thanks ;)
