### ISSUE TITLE
Drawer toggle gives null pointer exception

### ISSUE THREAD

**Issue by dj9975** [mikepenz/MaterialDrawer#1008]
I have written the following lines after the drawer is set and opened 
```java
getSupportActionBar().setDisplayHomeAsUpEnabled(false);
result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);
```

But this gives me null pointer exception for the result line. If I dont write these two lines my code works perfect but the only issue is that hamburger icon is not shown on the title bar. In order to open drawer again I need to swipe

**Comment by mikepenz** [comment]
@dj9975 I expect you do not provide your `Toolbar` to the `DrawerBuilder` without the `Toolbar` it can not initialize the `ActionBarDrawerToggle` for you

**Comment by dj9975** [comment]
cant I use actionbar ?

**Comment by mikepenz** [comment]
@dj9975 then you will have to handle this on your own, as the `ActionBarDrawerToggle` can't be used with an `ActionBar`. I highly recommend switching to the `Toolbar`
