### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Grozny** [mikepenz/MaterialDrawer#101]
In my tablet (Nexus 9), the email account header appears cut off (vertical).
ProfileDrawerItem view alson cut off (horizontal).

**Comment by mikepenz** [comment]
@Grozny can you please post a screenshot?

**Comment by Grozny** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6436843/6644493/2f727096-c9ac-11e4-8b04-234383ce8e5b.png)

**Comment by mikepenz** [comment]
@Grozny thanks. this is perhaps fixed in the next version. not sure yet can't test it :/

**Comment by Grozny** [comment]
As previously reported the ProfileDrawerItem list view (name) are cut off
horizontally. In some cases appears only two letters of the name.
Probably the problem is in the layout promaterial_drawer_item_profile.xml.

Best regards.

2015-03-14 15:47 GMT+00:00 Mike Penz <notifications@github.com>:

**Comment by mikepenz** [comment]
@Grozny isn't it working with v2.5.0? I extended the space and it was even working with large font on my phone?

**Comment by Grozny** [comment]
Yes, isn't it working with v2.5.0. I think isn't necessary extend the space.
try match_parent a parent view of name/email view.

2015-03-16 17:49 GMT+00:00 Mike Penz <notifications@github.com>:

**Comment by mikepenz** [comment]
@Grozny oh sorry you mean the DrawerItem. Have you set a badge or an icon or anything special? What is the android version of your nexus 9?

**Comment by Grozny** [comment]
I didn't set a badge or an icon or anything special.
Lollipop 5.0.1

2015-03-16 18:28 GMT+00:00 Mike Penz <notifications@github.com>:

**Comment by mikepenz** [comment]
I've changed it to match_parent did not realize i had a wrap_content there. We'll see if it is fixed in the next release ;)

**Comment by Grozny** [comment]
Ok, thanks.

Best regards.

2015-03-16 18:55 GMT+00:00 Mike Penz <notifications@github.com>:
