### ISSUE TITLE
Suggestion: Improving the Expandable List

### ISSUE THREAD

**Issue by CeJienAJPC** [mikepenz/MaterialDrawer#1012]
Hi Mike,
I have started using Expandable list from the new version. It's working great.

I would like to suggest few improvements (not sure if they have been already implemented - correct me if i have missed something).

1. One would find it difficult to distinguish between the expandable and the non-expandable items. Adding a drop-down arrow feature to the end of the item could make it easy to identify the expandable list.
2. Adding a divider to the top and bottom of the expanded section will make it much more distinguishable.

For Reference : [http://imgur.com/a/z35Zf](url)

Regards

**Comment by mikepenz** [comment]
@CeJienAJPC adding a `ExpandableDrawerItem` including an arrow + animation is already planned, and will come in the next update. 

The `divider` line can be added via the `DividerDrawerItem` if you want?

**Comment by CeJienAJPC** [comment]
Yes, the divider can be added with DividerDrawerItem. But, I was mentioning about the dividers (top and bottom dividers) surrounding the Expandable list. This is to alienate/differentiate the expanded list from the drawer.

A much better way to alienate the expanded list would be to provide a pale background for the expanded list

**Comment by Rainer-Lang** [comment]
@CeJienAJPC Set the background of the items.

**Comment by mikepenz** [comment]
@CeJienAJPC I will look of adding an `ExpandableItem` with the correct animation. For the highlighting I highly suggest the solution @Rainer-Lang added. Just define a different background for the sub-items

**Comment by mikepenz** [comment]
With v5.0.2 I will add a new `ExpandableItem` with the animating arrow as specified in the guidelines
