### ISSUE TITLE
Help,I can't use it in gradle

### ISSUE THREAD

**Issue by JesseBlackman** [mikepenz/MaterialDrawer#1014]
when I use 
`compile('com.mikepenz:materialdrawer:5.0.0@aar') {
        transitive = true
    }`
it seems to conflict with the android.support.design and android.support.v4.

when I use
`compile 'com.mikepenz:materialdrawer:5.0.0@aar'`
it turns out 
`com.mikepenz.materialdrawer.AccountHeader`
 cant be found

**Comment by mikepenz** [comment]
@JesseBlackman the `MaterialDrawer` uses the latest `support` libraries **23.1.1**, and so it also requires you to have `compileSdkVersion = 23`

**Comment by JesseBlackman** [comment]
thanks for your reply.
I already use `compileSdkVersion = 23`
here is my build.gradle file:
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.0"

    defaultConfig {
        applicationId "com.letter"
        minSdkVersion 11
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'com.android.support:support-v4:23.0.0'
    compile 'com.android.support:design:23.0.0'
    compile 'com.android.support:recyclerview-v7:23.0.0'
    compile 'com.android.support:cardview-v7:23.0.1'
    compile 'org.apache.commons:commons-lang3:3.0'
    compile('com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.8.0@aar') {
        transitive = true
    }
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp:okhttp:2.3.0'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.4'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'in.srain.cube:ultra-ptr:1.0.10'
    compile 'de.hdodenhof:circleimageview:1.3.0'
    compile 'me.relex:circleindicator:1.1.8@aar'

    compile('com.mikepenz:materialdrawer:5.0.0@aar') {
        transitive = true
    }

    compile project(':weibosdk')
}
`

**Comment by mikepenz** [comment]
@JesseBlackman but your `support` libraries are **v23.0.0** and will conflict with **v23.1.1**

**Comment by mikepenz** [comment]
@JesseBlackman you either can exclude the support libs from the `MaterialDrawer` so you can use your version (I can't give support in this case as they may differ and cause bugs) or you update yours. 
And I highly suggest you use the latest version, as Google does a great job of adding bugfixes to the support libs, ...

;)
