### ISSUE TITLE
Updating custom layout not working

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/MaterialDrawer#1015]
Hi.
i made a custom layout for the drawer and it displays OK, however i cant seem to update it.

i have a TextView in this custom layout, and during runtime i need to update its text.
after i change the text (using myTextView.setText("some new text")) the change does not reflect in the drawer (still showing the old text).

this is a mockup of my code:

```java
//this works - myText is not null
//assume it has the text "old text"
myText = (TextView) (getLayoutInflater().inflate(R.layout.test, null).findViewById(R.id.myTextView)); 

drawerBuilder.withCustomView(getLayoutInflater().inflate(R.layout.test, null)); 

myDrawer = drawerBuilder.buildView();

myText.setText("some new text");

myDrawer.getAdapter().notifyAdapterDataSetChanged();
```

however, the text displayed in the drawer wont update and is still "old text".
i also tried myDrawer.getAdapter().notifyDataSetChanged() but that doesn't work either.
i am using the latest 5.0.0 version (also checked on previous version and didn't work either)

thanks in advanced for your help

**Comment by EW01th** [comment]
It looks like you're making two separate instances of the view. Try this:
View v = getLayoutInflater().inflate(R.layout.test, null;
myText = (TextView) v.findViewById(R.id.myTextView);
drawerBuilder.withCustomView(v);
myText.setText("some new text");

**Comment by mikepenz** [comment]
@EW01th thank you so much for answering.

**Comment by or-dvir** [comment]
@EW01th i guess i misunderstood something about how LayoutInflater works...
i did what you said and it worked!

thanks for helping me learn something new :+1:
