### ISSUE TITLE
ProfileSettingDrawerItem - withOnDrawerItemClickListener not fired on v5.0.0

### ISSUE THREAD

**Issue by alessandrotorres** [mikepenz/MaterialDrawer#1016]
Hi Mike,

after upgrading to v5.0.0 listener setted withOnDrawerItemClickListener for ProfileSettingDrawerItem seems not fuctions anymore.. with v4.6.4 all ok.
What am I doing wrong?
Thanks.

AccountHeader is setted as:
```java
accountHeader = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.header)
                .build();
```

And later:
```java
accountHeader.addProfiles(
                    new ProfileDrawerItem().withName(loggedUser.getFullName()).withEmail(loggedUser.getEmail()).withIcon(new IconicsDrawable(this, GoogleMaterial.Icon.gmd_face).color(Color.BLACK).sizeDp(20)),
                    new ProfileSettingDrawerItem()
                            .withName(this.getResources().getString(R.string.menu_user_logout))
                            .withIcon(FontAwesome.Icon.faw_sign_out)
                            .withIdentifier(20)
                            .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                                @Override
                                public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                                    openDialogLogout();
                                    return false;
                                }
                            })
            );
```

**Comment by mikepenz** [comment]
@alessandrotorres will the listener on the `DrawerBuilder` fire? 

You use the listener via the item at the moment. (just for debugging) 

Seems like I do not fire the item's listener anymore. Have to test it

**Comment by alessandrotorres** [comment]
Yes, on the `DrawerBuilder ` the listener fire, on `ProfileSettingDrawerItem` not.
Thanks

**Comment by mikepenz** [comment]
@alessandrotorres yes you understood me correctly. Thanks for this quick test.

I might not be able to check this until next week. But expect a new version at least on Monday. 

Best,
Mike

**Comment by alessandrotorres** [comment]
Thank you Mike!

Meanwhile I'll rollback to 4.6.4.

Have a nice day,
Alessandro
