### ISSUE TITLE
Drawer blinking when header is changed

### ISSUE THREAD

**Issue by mtrakal** [mikepenz/MaterialDrawer#1017]
We use two-pane tablet mode with still shown MaterialDrawer.
Problem is, when we want to change AccountHeader background to correspond second pane toolbar, AccountHeader blink everytime. I searched for this issue http://stackoverflow.com/questions/29331075/recyclerview-blinking-after-notifydatasetchanged
but does not have effect. In https://code.google.com/p/android/issues/detail?id=177517#c7 wrote that items should be using stable IDs, but it is not possible here or is it?

Is there some solution how to change background/header data without blinking?

Thanks

```java
public void setHeaderBackgroundColor(@ColorInt int headerBackgroundColor) {
        mHeaderBackgroundColor = headerBackgroundColor;
        disableBlinking(mDrawer.getRecyclerView());
        mDrawer.setHeader(getAccountHeader().getView());
    }

private void disableBlinking(RecyclerView recyclerView) {
        recyclerView.getItemAnimator().setChangeDuration(0);
        // disable blinking effect after notifyDatasetChange: http://stackoverflow.com/a/32227316/4024146
        RecyclerView.ItemAnimator animator = recyclerView.getItemAnimator();
        if (animator instanceof SimpleItemAnimator) {
            ((SimpleItemAnimator) animator).setSupportsChangeAnimations(false);
        }
    }
private AccountHeader getAccountHeader() {

        Drawable drawable = ResourcesCompat.getDrawable(mMainActivity.getResources(), R.drawable.nav_header_gb, null);
        if (drawable != null) {
            drawable.setColorFilter(mHeaderBackgroundColor, PorterDuff.Mode.OVERLAY);
        }

        AccountHeaderBuilder accountHeaderBuilder = new AccountHeaderBuilder()
                .withActivity(mMainActivity)
                .withCompactStyle(true)
                .withHeaderBackground(drawable)
                .withSavedInstance(mSavedInstanceState)
                .withSelectionListEnabled(false)
                .addProfiles(getProfile());
        return accountHeaderBuilder.build();
    }
```

**Comment by mikepenz** [comment]
@mtrakal what you are doing is you set a new header, which will then play the normal item animation. What I suggest (for just updating the background) that you get the `View` from the `Header` via:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L268 
and you change the background. so no `itemChange` is triggered on the `RecyclerView`

**Comment by mtrakal** [comment]
Thank you, you are best! :)

I should take a rest, how clean and easy solution :).
Thank you
