### ISSUE TITLE
Clear selection on List of users

### ISSUE THREAD

**Issue by candeiasdan** [mikepenz/MaterialDrawer#1018]
Is there any option similar to:
```
result.setSelection()
````

but for the list of users? 

I need to have the list of users, but i don't want any user highlighted (not even the current), not even when i select a different user. All users should be available to click.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L227

No highlighting at all? :/
Never had this case, but I think `withSelectable(false)` could also work here.

**Comment by candeiasdan** [comment]
if i set `withSelectable(false)` in each user the header does not show any user or email selected.
If then i set: `header.setActiveProfile(indetifier);` i get the header working as expected (name and email) but the list of users is with the user selected (highlighted).

I know this is not a normal scenario/flow. :/

**Comment by mikepenz** [comment]
Hmmm if you create a custom profile drawerItem which is basically the same
just without the selected states of the text and background? Will be the
easiest solution

candeiasdan <notifications@github.com> schrieb am Do., 18. Feb. 2016, 16:21:

> if i set withSelectable(false) in each user the header does not show any
> user or email selected.
> If then i set: header.setActiveProfile(indetifier); i get the header
> working as expected (name and email) but the list of users is with the user
> selected (highlighted).
>
> I know this is not a normal scenario/flow. :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikepenz/MaterialDrawer/issues/1018#issuecomment-185771334>
> .
>
-- 
Mike Penz
__________________________________________
*Mike Penz*
Android | Backend | Open Source | Web Developer
mikepenz.com
lanora.io

**Comment by candeiasdan** [comment]
How can i achieve that? How can i create a custom profile drawerItem?

**Comment by mikepenz** [comment]
@candeiasdan the same as you would create a `CustomDrawerItem` but in your case just copy paste the `ProfileDrawerItem` name the class different, and alter the `bindView` method to do not have the `selected` state on the text, and background
