### ISSUE TITLE
Upgrading to 5.0.0 results in crash when trying to updateBadge

### ISSUE THREAD

**Issue by jonathan-caryl** [mikepenz/MaterialDrawer#1019]
I've written a small test app [here](https://github.com/jonathan-caryl/MaterialDrawerTest) to illustrate the problem: when we use `withFooter` in the `DrawerBuilder` and then subsequently try to call `updateBadge` on the `Drawer` then it crashes. Without the `withFooter` it's ok.

**Comment by mikepenz** [comment]
@jonathan-caryl thanks for the sample app to showcase the issue. 
I will need til Monday to check (and fix) it, as I am rather busy this week. I hope that's ok.

**Comment by jonathan-caryl** [comment]
No problem!

**Comment by jonathan-caryl** [comment]
Thanks for the fix

**Comment by mikepenz** [comment]
@jonathan-caryl will be in the next update. I hope I can release it today
