### ISSUE TITLE
Drawer stay opened after an item was clicked

### ISSUE THREAD

**Issue by dipici** [mikepenz/MaterialDrawer#1020]
Hi Mike,

although I have set drawer.withCloseOnClick(true) that doenst work for me (v5.0.0). The drawer stay opened although an item was clicked.

**Comment by mikepenz** [comment]
@dipici what do you return in your `onItemClick`-listener?

**Comment by dipici** [comment]
Sorry my mistake,
I have returned true. 
Thx
