### ISSUE TITLE
SubItems being selected even if withSelectable(false)

### ISSUE THREAD

**Issue by bignadad** [mikepenz/MaterialDrawer#1021]
I have have a primary drawer item setup like this

```java
 new PrimaryDrawerItem().withName(R.string.drawer_categories).withIcon(R.drawable.app_ic_categories).withIdentifier(300).withSelectable(false).withSubItems(subItems),
```

Then my subItems are setup like this

```java
new SecondaryDrawerItem().withName(mCats.get(i).getCategoryName()).withLevel(2).withIcon(mCats.get(i).getCategoryIcon()).withIdentifier(i).withSetSelected(false);
```

However when i expand the primary and click a secondary they are selected. Can i disable that?

Also is there a way to collapse the group after a sub item is selected?

**Comment by mikepenz** [comment]
@bignadad you should also set `withSelectable(false)` on your sub item

You will get the click event in the listener, and there you can collapse the item
