### ISSUE TITLE
Expanded items duplicates

### ISSUE THREAD

**Issue by westman2000** [mikepenz/MaterialDrawer#1022]
if drawer has expandable items, and they are expanded.
And show/hide Accounts view in drawer, after that - all expanded item - duplicates

https://dl.dropboxusercontent.com/u/43856909/steps.jpg

**Comment by mikepenz** [comment]
@westman2000 thanks. I will look into it and fix it as soon as possible

**Comment by mikepenz** [comment]
can you please be a bit more specific?

**Comment by brunolopes446** [comment]
Sure.

At position number 4, I have an expandable list with two subitems:

From within a fragment, I update the badge number successfully:
`first.withBadge("8");
second.withBadge("9");
result.getAdapter().notifyAdapterSubItemsChanged(result.getPosition(4));`

But if I perform that action with the items expanded, they become duplicated:

![sem titulo](https://cloud.githubusercontent.com/assets/5794906/15826907/541604e0-2c01-11e6-8432-f81d0bbd5f30.png)

**Comment by brunolopes446** [comment]
solved it by calling `result.getAdapter().collapse(4, true);
`

**Comment by mikepenz** [comment]
@brunolopes446 great that yuo solved it. but still notifyAdapterSubItemsChanged should not result in them being duplicated

**Comment by brunolopes446** [comment]
It only happens if the items are expanded when updating the badges. That's why I called `collapse ` instead
