### ISSUE TITLE
Status bar color in API<21

### ISSUE THREAD

**Issue by MasterzYuri** [mikepenz/MaterialDrawer#1024]
I just updated to v5.0.0, mostly because I want to implement collapsable items and now I can't find a way to change the status bar color.
Adding this line `<item name="android:windowTranslucentStatus">true</item>` in v19 styles will do the trick, but if I do that then the status bar will overlap the drawer layout, like so:
http://blog.raffaeu.com/wp-content/uploads/Android-and-the-transparent-status-bar_1146A/image_4.png

I also tried to use SystemBarTintManager, no success though:
```
SystemBarTintManager tintManager = new SystemBarTintManager(this);
        tintManager.setTintColor(Color.parseColor("#2d5d82"));
        tintManager.setStatusBarTintEnabled(true);
        tintManager.setNavigationBarTintEnabled(true);
```
Any ideas?

**Comment by rubengees** [comment]
Concerning overlap: I had the exact same issue. See this:

https://github.com/mikepenz/Materialize/issues/8

**Comment by mikepenz** [comment]
@MasterzYuri there is no longer support for coloring the `StatusBar` on **API < 21**. On API's >21 you can change the `StatusBarColor` from theme, via code you can do the thing @rubengees mentioned. 

( @rubengees thanks )
