### ISSUE TITLE
Header not clickable, withHeaderClickable unused?

### ISSUE THREAD

**Issue by Aeefire** [mikepenz/MaterialDrawer#1025]
Hey guys,

I want my normal header (not account header) to be clickable. However, although I set withHeader(ressource) and withHeaderClickable(true), neither the onDrawerNavigationListener, nor the OnDrawerItemClickListener fire any kind of event. I then looked up the event and it seems mHeaderClickable is completely unused. Is this intended?

**Comment by westman2000** [comment]
maybe you need to set withOnAccountHeaderSelectionViewClickListener

**Comment by Aeefire** [comment]
@westman2000  There is no such a method, as I am not using an AccountHeader.

**Comment by mikepenz** [comment]
@Aeefire the header view is no normal `DrawerItem` so the listener won't fire here. If you need a clickable area on your header, just set a normal `onClickListener` for that view.

**Comment by Aeefire** [comment]
Okay thanks, this works. However, why is withHeaderClickable here then? It basically has no effect at all? A bit misleading.

**Comment by mikepenz** [comment]
`mHeaderClickable` will be removed in the next release. Missed to delete this method with the newest version.
