### ISSUE TITLE
How to disable drawer hiding on touch outside?

### ISSUE THREAD

**Issue by AndreyGrowl** [mikepenz/MaterialDrawer#1027]
Now tapping outside opened drawer closes it. Is it possible to make disable this function? I need let user interact with screen while navigation drawer is opened.

Sorry if this question is silly but I didn't find any suggestion yet. 
Thanks anyway.

**Comment by mikepenz** [comment]
@AndreyGrowl I don't think so. This function is done from the `DrawerLayout` may you could overwrite the `DrawerLayout` and providing consuming the touch in this area, but I am not sure if the `DrawerLayout` allows this...
