### ISSUE TITLE
Custom Background for DrawerItems in the StickyFooter do not work

### ISSUE THREAD

**Issue by bignadad** [mikepenz/MaterialDrawer#1028]
I implemented a customer primary drawer item as mentioned in your example

```java
package com.backdrops.wallpapers.util.ui;

import com.mikepenz.materialdrawer.holder.ColorHolder;
import com.mikepenz.materialdrawer.model.PrimaryDrawerItem;

public class CustomPrimaryDrawerItemPro extends PrimaryDrawerItem {

    private ColorHolder background;

    public CustomPrimaryDrawerItemPro withBackgroundColor(int backgroundColor) {
        this.background = ColorHolder.fromColor(backgroundColor);
        return this;
    }

    public CustomPrimaryDrawerItemPro withBackgroundRes(int backgroundRes) {
        this.background = ColorHolder.fromColorRes(backgroundRes);
        return this;
    }

    @Override
    public void bindView(ViewHolder holder) {
        super.bindView(holder);

        if (background != null) {
            background.applyToBackground(holder.itemView);
        }
    }
}
```

I then added it to my DrawerBuilder

```java
.addStickyDrawerItems(new CustomPrimaryDrawerItemPro().withBackgroundRes(R.color.accent2).withIcon(R.drawable.ic_drawer_pro).withIconColorRes(R.color.primary).withIconTintingEnabled(true).withName("Go Pro").withIdentifier(555))
```

However the background will not change. It stays the same color as the rest of the drawer. The icon color changes like it should, but not the background for the drawer item.

**Comment by mikepenz** [comment]
@bignadad this item is exactly for this use case. It is meant that it keeps the color even when selected. 

What do you need? Don't you just want the default `PrimaryDrawerItem`-behavior?

**Comment by mikepenz** [comment]
@bignadad instead of the `ColorHolder` I suggest that you just remember the `Drawable` for your background, and for the selected background. And inside the `bindView` you will then just define a `StateListDrawable` for the `itemView`

Creating a `StateListDrawable` which will automatically change depending on the state is as easy as this:
```
StateListDrawable stateListDrawable = new StateListDrawable();
stateListDrawable.addState(new int[]{android.R.attr.state_selected}, selectedBackground);
stateListDrawable.addState(new int[]{}, background);
```

**Comment by bignadad** [comment]
Tried this but still doesn't affect

public class CustomPrimaryDrawerItemPro extends PrimaryDrawerItem {

    private Drawable background;

    public CustomPrimaryDrawerItemPro withBackgroundColor(Drawable backgroundColor) {
        this.background = backgroundColor;
        return this;
    }

    @Override
    public void bindView(ViewHolder holder) {
        super.bindView(holder);



        if (background != null) {
            StateListDrawable stateListDrawable = new StateListDrawable();
            stateListDrawable.addState(new int[]{android.R.attr.state_selected}, background);
            stateListDrawable.addState(new int[]{}, background);
            //background.applyToBackground(holder.itemView);
            holder.itemView.setBackgroundDrawable(background);
        }
    }
}

**Comment by mikepenz** [comment]
@bignadad 2 things. 

First you define the same drawable for the selected, and for the general state. 
Second you set the background as `Drawable` for the `itemView` not the `stateListDrawable`

Here's a simplified variant:
```java
public class CustomPrimaryDrawerItemPro extends PrimaryDrawerItem {
    @Override
    public void bindView(ViewHolder holder) {
        super.bindView(holder);

        StateListDrawable stateListDrawable = new StateListDrawable();
        //define the color we want to use for the selected state (this is the default one defined via theme and is defined via the material design guidelines)
        stateListDrawable.addState(new int[]{android.R.attr.state_selected}, new ColorDrawable(getSelectedColor(holder.itemView.getContext())));
        //define the color which is used for the general state
        stateListDrawable.addState(new int[]{}, new ColorDrawable(Color.RED));
        //set the color for the view
        holder.itemView.setBackgroundDrawable(stateListDrawable);
    }
}
```
