### ISSUE TITLE
AccountHeader w/ only 1 profile still has touch behavior

### ISSUE THREAD

**Issue by inktomi** [mikepenz/MaterialDrawer#103]
It is currently not possible to totally disable the account switching behavior and include a single account using the app. 

In this use case, we would have a single Profile set in an AccountHeader. If a user sets withSelectionListEnabled(false) as well as withProfileImagesClickable(false) we would expect that the profile images and the text in the AccountHeader do not have any click behavior enabled. 

However, this is not the case. The mAccountHeaderTextSection in AccountHeader still has UI elements which react to touch because of the android.R.attr.selectableItemBackground which is added to their background. 

Furthermore, it appears that the the IconicsDrawable in setImageOrPlaceholder() also adds touch states to the UI. 

Would it be possible to have a way to turn these off if people want the AccountHeader, but only want a single account without any touch interactivity?

**Comment by mikepenz** [comment]
Try setting `.withSelectionListEnabledForSingleProfile(false)` so this will disable the list if you have only one item.

without any touch. even on the accountheader. this would create quite some extra methods. :D

**Comment by inktomi** [comment]
.withSelectionListEnabledForSingleProfile(false) is a great help for sure, thank you for that - however even with that set I'd like to see the click actions removed on the text areas and icon. 

Maybe you can piggyback on that boolean flag for the selected states?

**Comment by mikepenz** [comment]
@inktomi i see your point. Not sure yet. perhaps i'll also remove the on-touch feedback if there's no action :D

**Comment by mikepenz** [comment]
@inktomi will be in v2.5.0 you should then use the above method in combination with the `withProfileImagesClickable(false)` to completely disable the touch feedback

**Comment by mikepenz** [comment]
So this is currently available in the snapshot repo. it would be great if you can test it and let me know what you think:


Just add the snapshot repository to your repositories within the main `build.gradle` under 'allprojects`
```javascript
maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
```

After this add the following compile dependency:

```javascript
compile('com.mikepenz.materialdrawer:library:2.5.0-SNAPSHOT@aar') {
        transitive = true
}
```

**Comment by inktomi** [comment]
Wow, that was fast! I'll try it out as soon as possible.

**Comment by mikepenz** [comment]
Yeah. :D

**Comment by inktomi** [comment]
Setting ```withProfileImagesClickable(false)``` works wonderfully. Thank you!
