### ISSUE TITLE
Question. How correctly insert item below expandableItem

### ISSUE THREAD

**Issue by westman2000** [mikepenz/MaterialDrawer#1030]
1. How correctly insert item below expandableItem? Because item can be expanded and than new item will be inserted in middle of expandable list... 

2. just wondering... new ExpandableDrawerItem implements IExpandable? And we still need this:
```java
if (((IExpandable) drawerItem).getSubItems() != null) {
   result.getAdapter().toggleExpandable(position);
   //we consume the event and want no further handling
   return true;
}
```
Why you not do it inside library?

**Comment by mikepenz** [comment]
@westman2000 at the moment the code is required yes. I plan to improve this in an update soon. 

Regarding the insertion of new items. If you expand an item with sub-items it will add the items to the list. so the positions will also move. I have to check how the performance will be, and how much sense it will make if the count of sub items is removed when adding new items, as the "subitems" should be not "visible" for the dev

**Comment by mikepenz** [comment]
@westman2000 ok I took a deeper look at this issue. It is not possible to ignore the **subitems** by default, but I have added a new method to the `FastAdapter` which allows to get the count of `subitems` items before a specific position. So you can easily calculate the correct position you want to update. 

You can use this method via:
```java
result.getItemAdapter().getExpandedItemsCount(0, the position of your item)
```
