### ISSUE TITLE
the drawer is not work with appbar scroll flag 

### ISSUE THREAD

**Issue by JasonHezz** [mikepenz/MaterialDrawer#1032]
I use the version of  5.0.4,and I find some wrong if drawer works with applayout which its child has layout flags.Here is my code below:
[tabWithAppbarLayout.txt](https://github.com/mikepenz/MaterialDrawer/files/143923/tabWithAppbarLayout.txt)

BTW,it's possible to has a dynamic menu with data of servers send?

**Comment by mikepenz** [comment]
@JasonHezz you have already checked out the `CollapsingToolbar` sample? 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CollapsingToolbarActivity.java

The `MaterialDrawer` will just add a `DrawerLayout` to the root of your activity. So I don't see why this should not work.

You can build the `Drawer` and afterwards you can add / remove items as you want

**Comment by JasonHezz** [comment]
Sorry for my poor description ,the drawer actually can work,the problem is the toolbar's scroll event.I set toolbar can scroll but TabLayout can't .The first one I used native Component NavigationView and the second one is MaterialDrawer
 
![appbarscrollstate](https://cloud.githubusercontent.com/assets/15358765/13278937/339a92c8-db0f-11e5-8854-261d30c7e618.png)
![appbarscrollnoramlstate](https://cloud.githubusercontent.com/assets/15358765/13278940/385bbb16-db0f-11e5-9ac8-c6b64c2af688.png)

**Comment by mikepenz** [comment]
@JasonHezz may you could send a sample showcasing the working solution via the `NavigationView` and the one via the `MaterialDrawer`

**Comment by JasonHezz** [comment]
Here is my  [link](https://github.com/JasonHezz/MaterialDrawerTest)
I have tested several times,It occurs at attribute **fitsSystemWindows = true ** 
when you set it false at my demo file named activity_material_drawer.xml,it works.Did It  mentioned before?

**Comment by mikepenz** [comment]
@JasonHezz thanks will have a look this evening

**Comment by mikepenz** [comment]
@JasonHezz just set `android:fitsSystemWindows="false"` (**false**) for the `CoordinatorLayout`
