### ISSUE TITLE
(MiniDrawer) Selected item row_selector sometimes not shown

### ISSUE THREAD

**Issue by androideveloper** [mikepenz/MaterialDrawer#1033]
Try to click on the same row several times quickly and the selector will hide.
And of course, this is MiniDrawer related issue)))

**Comment by androideveloper** [comment]
![1](https://cloud.githubusercontent.com/assets/1249919/13278928/9cb90ae0-daed-11e5-8c03-229ae1fde076.png)
![2](https://cloud.githubusercontent.com/assets/1249919/13278929/9cba33e8-daed-11e5-9309-4dcc5a995763.png)

**Comment by androideveloper** [comment]
There is also another issue related to selectore. Please see this attached screenshot
![3](https://cloud.githubusercontent.com/assets/1249919/13278955/c3673126-daed-11e5-8da8-6f8989edaa9e.png)

**Comment by mikepenz** [comment]
@androideveloper can't reproduce this with the `MiniDrawer` of the sample app

**Comment by androideveloper** [comment]
Hm, have you enabled background .withEnableSelectedMiniDrawerItemBackground(true) ?

**Comment by androideveloper** [comment]
I can post full code

**Comment by androideveloper** [comment]
` DrawerBuilder builder = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(mToolbar)
                .withTranslucentStatusBar(false)
                .withAccountHeader(mAccountHeader)
                .addDrawerItems(drawerItems)
                .withSelectedItemByPosition(INITIAL_SELECTED_POSITION)
                .withSavedInstance(savedInstanceState);

 mMiniDrawer = new MiniDrawer()
                .withEnableSelectedMiniDrawerItemBackground(true)
                .withDrawer(mDrawer)
                .withAccountHeader(mAccountHeader)
                .withEnableProfileClick(false);`

**Comment by mikepenz** [comment]
@androideveloper can you reproduce this in the sample?

**Comment by androideveloper** [comment]
Yes, please seen attached video (tried on your sample).
Just double-click on the row in MiniDrawer

https://youtu.be/j3gTcrEYZ9s

**Comment by androideveloper** [comment]
Video related to the first case in screenshots. To get try to enable background for MiniDrawer .withEnableSelectedMiniDrawerItemBackground(true)

**Comment by parviz-93** [comment]
I also have problems when creating CrossfadeDrawer. Selected item  sometimes not shown in Samsung mobile phone(node4,s6) but when I testing in huawei mobile phone like p7  or android emulator it is working without problem

**Comment by androideveloper** [comment]
Hi @mikepenz . Thanks. This fixed minidrawer selection, but there are 2 issues left now:
1. When you double click (or fast click) on MiniDrawer item, Minidrawer selection doesn't dissapear (cause you fixed it now), but when you open full drawer with swipe, selection is gone.
2. I have two pages that use Minidrawer. When I open second page, two rows are selected at the same time! I will post this case more detailed as a new issue
