### ISSUE TITLE
[Question] Alternative to withHeaderClickable(true)

### ISSUE THREAD

**Issue by alirezaaa** [mikepenz/MaterialDrawer#1034]
Hi,

I'm migrating from v4 to v5 and I don't know what's the alternative method of `withHeaderClickable(true)`.

**Comment by mikepenz** [comment]
@alirezaaa what do you need it for?

**Comment by alirezaaa** [comment]
I was using that method and now it's deprecated. I want to know is there any alternative method that should I replace or its function is implemented already and I don't need to declare it anymore.

**Comment by mikepenz** [comment]
@alirezaaa my question was, why you used it. Because with v5.0.0 this method had no use anymore, and I think it is not necessary. The header view you can provide is clickable by the default, and as far as I remember it never resulted in a callback of the `onItemClickListener`

**Comment by alirezaaa** [comment]
That's what I wanted to know. The header view you can provide is clickable by the default. Thanks dear Mike.
