### ISSUE TITLE
Minor problem with the arrow icon of ExpandableDrawerItem

### ISSUE THREAD

**Issue by vanniktech** [mikepenz/MaterialDrawer#1035]
Steps to reproduce:

- Click on an ExpandableDrawerItem
- It shows the subitems and the arrow points up :white_check_mark: 
- Press on it again and the subitems are not shown and the arrow points down :white_check_mark: 
- Press on it again, still everything works :white_check_mark: 
- Now collapse it using `mDrawer.getAdapter().collapse(MY_ID)` and the arrow does not get updated and still points up :red_circle: 

Using 5.0.4

**Comment by mikepenz** [comment]
@vanniktech yes that is true as the item won't be notified and updated via the click listener. 

Will have a closer look at it

**Comment by mikepenz** [comment]
@vanniktech ok just checked this. It is not possible to handle this within the `FastAdapter` as the collapse, and expande methods are used in general for this operation. If I would notify the adapter about the change within this method it will crash if you click on a `ExpandableItem` as the same item will be notified about its change twice, causing a inconsistent state for the animator. 

In this case it is recomended that you just call,
```
mDrawer.getAdapter().notifyItemChanged(pos);
```

(oh and the collapse method takes the position not the ID)

**Comment by vanniktech** [comment]
Alright thanks!
