### ISSUE TITLE
FooterDrawerItem

### ISSUE THREAD

**Issue by Aeefire** [mikepenz/MaterialDrawer#1036]
Hey guys, once more it's me:

I am looking for a DrawerItem implementation which has its item actually sticking to the bottom of the drawer. I've been looking through the repository and it seems that a method existed, called addFooterItem or something similar. 

However this seems to have been replaced by a method taking a simple view. 

Is there an existing approach that I've missed, or do I have to go with a view / layout ?

**Comment by mikepenz** [comment]
@Aeefire you are searching for `StickyFooterItems`?
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/AdvancedActivity.java#L101

**Comment by Aeefire** [comment]
Worked. Again, the name is a bit misleading, so I didn't even care to try it. I guess I need to be more exploratory :)
