### ISSUE TITLE
Transition name for ProfileDrawerItem pic

### ISSUE THREAD

**Issue by danielgomezrico** [mikepenz/MaterialDrawer#1039]
Is there any way to set the transition name and use a shared transition from the profile drawer item pic to another view?

**Comment by mikepenz** [comment]
@danielgomezrico in the `onProfileClick` listener you get the `View` https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L89 
This will allow you to set the `transitionName` on the `ImageView`
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_profile.xml#L22
