### ISSUE TITLE
Updating description of SwitchDrawerItem

### ISSUE THREAD

**Issue by CombatEvolved** [mikepenz/MaterialDrawer#1040]
Seems like I can easily set a description when creating the `SwitchDrawerItem` (via `.withDescription("")`), but does not reflect new values set with `switchDrawerItem.withDescription("new description")` followed by a call to `drawer.updateItem(switchDrawerItem)`

**Comment by mikepenz** [comment]
@CombatEvolved just tried it, and it works in the sample. 

You have inserted this `SwitchDrawerItem` via the `DrawerBuilder`?
Does this `SwitchDrawerItem` define an `identifier` via `withIdentifier()`? (Should not be necessary as it also works without an identifier in the sample)

Which version do you use?

**Comment by CombatEvolved** [comment]
Yep, using it with `.withIdentifier()` and adding it with `DrawerBuilder`.   Looked up some debug, pretty sure I'm calling either `.updateItem()` or `.withDescription` from a non-ui thread, which would be a problem.  False alarm.

**Comment by mikepenz** [comment]
@CombatEvolved oh ok. Updating and notifiying the adapter from a non-ui thread is always fatal :D (and updateItem() just calls `notifyItemChanged` in the background)
