### ISSUE TITLE
create RTL Drawer

### ISSUE THREAD

**Issue by HamedGh** [mikepenz/MaterialDrawer#1042]
hello,
how can I create a drawer like below?

![xxhdpi-drawer](https://cloud.githubusercontent.com/assets/3388482/13378125/f81c021a-de0e-11e5-89fe-1c48b3a01397.jpg)

**Comment by mikepenz** [comment]
@HamedGh if your app is in RTL mode this will happen automatically. Just the header will stay the same (that's the same as the Google apps do)

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/1044
