### ISSUE TITLE
onProfileChanged() return true will still close drawer

### ISSUE THREAD

**Issue by bingjiang** [mikepenz/MaterialDrawer#1043]
After update to 5.0.7, during callback to onProfileChanged(), when the method returns true, it will still close the drawer. Previously, in 4.6.4, only when returning false will close the drawer

**Comment by mikepenz** [comment]
@bingjiang just checked the code. It should work as before. 

What exactly do you do where it doesn't respect your return value?

**Comment by bingjiang** [comment]
@mikepenz Found out what is the problem, it is not onProfileChanged() return value that is causing the drawer to close. It is the setSelectionAtPosition() behaviour that has changed from 4.6.4 to 5.0.7. Previously in 4.6.4, calling this method will not cause the drawer to close

@Override
	public boolean onProfileChanged(View view, IProfile profile, boolean current) {

		// simulate a LoaderManager callback 1 second later whenever a profile is changed to load new list of PrimaryDrawerItem
		handler.postDelayed(new Runnable() {

			@Override
			public void run() {

				drawer.addItem(new PrimaryDrawerItem().withName("drawer item " + ++autoIncrement));

				/**
				 * this is the method call that causing the drawer to close. In 4.6.4, it doesn't do that
 				 */
				drawer.setSelectionAtPosition(1);
			}
		}, 1000);

		return true;
	}

I attached the sample project here. Change the app build.gradle version of materialdrawer to see the difference
[materialdrawersample.zip](https://github.com/mikepenz/MaterialDrawer/files/150225/materialdrawersample.zip)

**Comment by mikepenz** [comment]
@bingjiang I debugged it, and you are right. Will be fixed in the next version
