### ISSUE TITLE
Right to Left drawer

### ISSUE THREAD

**Issue by msroid** [mikepenz/MaterialDrawer#1044]
hi,
i am using this library and it's really awesome!
i have two question:
1- how can i move "3 line" icon in toolbar from left side to right side?
2- i am using crossfadedrawer with an accountheader and some other primary items.
it works with no problem until i use withDrawerGravity(GravityCompat.END). and then it just shows the minidrawer. i figure out the main drawer will be open if i touch screen from left to right but my drawer is in the right side. so what i have to do...??

sorry for my poor english and really thanks for your help.

**Comment by mikepenz** [comment]
@msroid the **burger**-icon is not handled by the drawer. This is android default. If your application is in RTL mode it will be automatically on the right. 

You can enable RTL via the `AndroidManifest.xml` (on the application)
```xml
android:supportsRtl="true"
```
and activate it within the `Activity` via:
```java
getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
```

2. This is a bug, and I will fix this in the next version of the `CrossfadeDrawerLayout`

**Comment by msroid** [comment]
Thank you for your prompt reply.

**Comment by t4kstar** [comment]
How do open Nav Drawer below the Toolbar ?

**Comment by mikepenz** [comment]
@t4kstar unrelated to this question. Just check out the sample app it showcases this requirement

**Comment by t4kstar** [comment]
i started Android a few days.
i searched very on google and your solution
So, i used this Codes 
.withTranslucentStatusBar(false)
.withDisplayBelowStatusBar()
.getActionBar().setDisplayHomeAsUpEnabled(true);
But Nav Drawer don't open below Toolbar :(

My Drawer code and show : 

`result = new DrawerBuilder()
                .withActivity(this)


                .withAccountHeader(headerResult) //set the AccountHeader we created earlier for the header
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("Home").withIcon(FontAwesome.Icon.faw_home).withIdentifier(1),
                        new PrimaryDrawerItem().withName("Free Play").withIcon(FontAwesome.Icon.faw_gamepad),
                        new PrimaryDrawerItem().withName("Custom").withIcon(FontAwesome.Icon.faw_eye),
                        new SectionDrawerItem().withName("Section Header"),
                        new SecondaryDrawerItem().withName("Settings").withIcon(FontAwesome.Icon.faw_cog),
                        new SecondaryDrawerItem().withName("Help").withIcon(FontAwesome.Icon.faw_question).withEnabled(false),
                        new SecondaryDrawerItem().withName("Source").withIcon(FontAwesome.Icon.faw_github),
                        new SecondaryDrawerItem().withName("Contact").withIcon(FontAwesome.Icon.faw_bullhorn)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        if (drawerItem != null && drawerItem.getIdentifier() == 1) {
                        }

                        if (drawerItem instanceof Nameable) {
                            assert toolbar != null;
                            toolbar.setTitle(((Nameable) drawerItem).getName().getText(MainActivity2.this));
                        }

                        return false;
                    }
                })
                .withSavedInstance(savedInstanceState)

                .withTranslucentStatusBar(false)


                .withDrawerGravity(Gravity.END)

                .build();`

**Comment by mikepenz** [comment]
@t4kstar you might need to get a bit more comfortable with android first. 

Just once again. Everything you want to do is shown in the sample application

**Comment by irshadir7** [comment]
how can change PrimaryDrawerItem icon Left side?
