### ISSUE TITLE
Toggle ExpandableDrawerItem

### ISSUE THREAD

**Issue by rsd-raul** [mikepenz/MaterialDrawer#1046]
Good evening Mike,

Just did the switch to 5.0+ due to the
````
android:windowSoftInputMode="adjustResize"
````
problem on Android, still haven't implemented the multiselection though, I'll get back to you if I find any problem there :D

Now I have a doubt regarding the new ExpandableDrawerItem, is there any way to expand the expandable items programatically??

One of my drawers has an item that expands "onDrawerOpened", that means I can make the onCreate method lighter by not introducing the items the first time and only doing that on user request or "onDrawerOpened",.

Is there something like that? will be on the future?

I tried the:
````
mMainDrawer.setSelection([id],[fireOnClick]);
````
method, but no joy.

**Comment by mikepenz** [comment]
@rsd-raul ok great. 

If you need to set it programmatically you can set the `DrawerItem` expanded on creation. If you want to do this at a later time you can do this via 
```java
result.getAdapter().expand(int position)
```
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L987

**Comment by rsd-raul** [comment]
Great, thanks Mike.

That position I'm assuming corresponds with the item in the RecyclerView??

Because I have 3 expandable items in one of the drawers, the second expandable one might be the "position 7" if the first expandable is closed but the "position 18" if it's opened. I can calculate that position based on the items on the first item and so on, but well, it's not that fun xD

**Comment by mikepenz** [comment]
@rsd-raul 

yes the position is always the global position. Meaning the exact position within the `RecyclerView` this also moves if an expandable item before this position is expanded. or if you add a header (which is also just one item in the RV)

There is a method helping you: `getExpandedItemsCount` you can call this on the `FastAdapter` (result.getAdapter()`
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L580
