### ISSUE TITLE
animation

### ISSUE THREAD

**Issue by soheilserver** [mikepenz/MaterialDrawer#1048]
is it possible to add an item to Material Drawer with an entrance animation?
and is it possible to change its width at run time with an animation?
thank u so mush

**Comment by mikepenz** [comment]
@soheilserver you can just provie an `Animator` to the `RecyclerView`
Which width? Of an Item? If you respect the limitations of an `RecyclerView` yes

**Comment by soheilserver** [comment]
the width of material drawer

**Comment by soheilserver** [comment]
so does material drawer use RecyclerView? and if yes, so haw may i access that?

**Comment by mikepenz** [comment]
@soheilserver of the `MaterialDrawer` ok so you will have to animate the width of the `slider`-view. Which you can get from the `Drawer`

Yes it uses it. `Drawer.getRecyclerView()`
