### ISSUE TITLE
Can't use MiniDrawer with fitsSystemWindows = true

### ISSUE THREAD

**Issue by dstd** [mikepenz/MaterialDrawer#1049]
Hello, Mike!

When using MiniDrawer with an activity that has `fitsSystemWindows = true` I getting status-bar's shadow at the top of the drawer (expanded one). But that drawer is below the toolbar, so it looks ugly :worried:

And it looks like this issue takes the place since Android Support Library 23.2.0. Because MDv5.0.5 + ASLv23.1.1 works perfect, but MDv5.0.5 + ASLv23.2.0 gives me that shadow.

Is it possible to solve this without making `fitsSystemWindows = false`?

P.S. Here is a minimal sample project with this issue - https://github.com/dstd/DrawerTest

![unexpected-shadow](https://cloud.githubusercontent.com/assets/1444844/13411944/0d9b48e2-df51-11e5-86c0-a050dcc53aa7.jpg)

**Comment by mikepenz** [comment]
@dstd can you also please let me know what you want achieve? Because the `MiniDrawerActivity` of the sample is also below the `Toolbar` and does not have the shadow. 

Also why do you need `fitsSystemWindows=true` when your drawer is below the `Toolbar`?

**Comment by dstd** [comment]
That's because I have different layout for phone/tablet configurations: for phones – ordinary drawer, for tablets – mini-drawer.

If I use `MaterialDrawerTheme` for the activity, as in your MiniDrawerActivity sample, then I have to make a whole tree of cases with configuration qualifiers. Like `statusBarColor = transparent` only for v21/phone layout, but not for others.

So `fitsSystemWindows = true` looks most easiest way to conform to all configurations.

Probably I'm not that good in theming and using it in wrong way :confused:

**Comment by mikepenz** [comment]
@dstd then simply create a layout for tablet and a layout for phones. And for phones you do not set the `fitsSystemWindows` in this case?

**Comment by dstd** [comment]
@mikepenz thanks for your replies. I already had separate layouts for required configurations. But found mistake in my code only now :blush: (I did configure `AccountHeaderBuilder.withTranslucentStatusBar(!useMiniDrawer)` but missed that `DrawerBuilder.withTranslucentStatusBar(false)`, and that resulted into non-transparent status-bar in the phone configuration).
So my issue seems to be solved.

But what if one needs to use a drawer under the toolbar with `fitsSystemWindows = true`, for some reason? Or such a case could happen only when one makes something in the wrong way?
