### ISSUE TITLE
Translucent status bar not able to have color changed?

### ISSUE THREAD

**Issue by drinfernoo** [mikepenz/MaterialDrawer#105]
I think I'm having a similar issue to #18, but my problem is that I'd like to use both the translucent status bar (which I've achieved by using MaterialDrawerTheme.Light.TranslucentStatus), and be able to set the color of the status bar as well. It seems that the status bar is locked on colorPrimaryDark.

I'm trying to set the color with Window#setStatusBarBackgroundColor.

If I use just MaterialDrawerTheme.Light, I can change the status bar color, but there is a status bar-sized gap between the actual status bar and my toolbar, that is also colorPrimaryDark.

Is there any way to do this?

**Comment by mikepenz** [comment]
@drinfernoo you can use the v2.5.0-SNAPSHOT version which will be out (hopefully) on sunday. This version include the option to color the statusbar :)

https://github.com/mikepenz/MaterialDrawer/issues/103#issuecomment-79558279

(`drawer.withStatusBarColor()`)

**Comment by drinfernoo** [comment]
Would this be something that could be called on a Drawer.Result, in order to set it dynamically?

**Comment by mikepenz** [comment]
@drinfernoo in the first version just on  the builder. Do you need it dynamically?

**Comment by mikepenz** [comment]
@drinfernoo ok added the method to the source. will be in the final v2.5.0

**Comment by drinfernoo** [comment]
That was my goal, so that I can set it based on which section is being selected from the drawer. I'm having trouble getting the snapshot version to work with a local repo, though :( I also have Iconics, but can the snapshot versions coexist in he same repo as release builds?

**Comment by mikepenz** [comment]
i'm not quite sure about the local repo. 

you have to add the snapshot repository to your build.gradle (just keep the previous entries too) and then it should automatically detect that this version is from the snapshot repo. and as soon as i release v2.5.0 to the official maven central just change the version and you are fine. 

Android-Iconics is automatically fetched through the MaterialDrawer dependency if you add the transistive true thing described in the README

**Comment by drinfernoo** [comment]
I'll just hold out for the official drop :) I'm stuck in a position of having to use a local repo, and pulling assets from the server manually, so things like that are really tricky :(

**Comment by mikepenz** [comment]
@drinfernoo sounds bad. But i think i will release it tomorrow

**Comment by drinfernoo** [comment]
@mikepemz, sounds great :) I'm loving the library already.
