### ISSUE TITLE
ClassCastException when not using my own DrawerLayout

### ISSUE THREAD

**Issue by drinfernoo** [mikepenz/MaterialDrawer#1050]
I'm getting this error:

http://pastebin.com/4uNyCM29

And all I've done is this:

    mDrawer = new DrawerBuilder()
			.withActivity(this)
			.withToolbar(mToolbar)
			.build();

What am I missing?

**Comment by mikepenz** [comment]
@drinfernoo your custom `DrawerLayout` still has to `extend DrawerLayout` you can't pass a `LinearLayout`
