### ISSUE TITLE
Display Drawer Below Status Bar

### ISSUE THREAD

**Issue by patelakshay13890** [mikepenz/MaterialDrawer#1051]
How to display drawer below StatusBar ??
In previous versions it was working fine..
And How can i have only Right Side Sliding Drawer ??

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java

Just define the gravity, but then you can't use the `ActionbarDrawerToggle` as this only supports left side drawers

**Comment by patelakshay13890** [comment]
I want to have Drawer Content below Status Bar but this not working..!!

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/NonTranslucentDrawerActivity.java

Have you ever tried the sample?

**Comment by mikepenz** [comment]
@patelakshay13890 so what exactly do you want. Can you please try the sample application and tell me which sample is exactly what you need?

If you found the sample which fits your needs, make sure you use the same theme, define the same settings, have a similar layout.

**Comment by patelakshay13890** [comment]
My Code For Displaying Drawer is

View leftSlidingView = getLayoutInflater().inflate(
R.layout.expandable_list, null);
leftResult = new DrawerBuilder().withActivity(this)
.withTranslucentStatusBar(true).withToolbar(toolbar)
.withCustomView(leftSlidingView)
.withDisplayBelowStatusBar(true)
.withActionBarDrawerToggleAnimated(true)
.withDrawerWidthPx(HBData.getDeviceDimens(mContext, true) - 36)
.withDrawerGravity(Gravity.START).build();

**Comment by Rainer-Lang** [comment]
@patelakshay13890 Please let @mikepenz help you and PLEASE answer his questions.
