### ISSUE TITLE
Theme.AppCompat.DayNight

### ISSUE THREAD

**Issue by alorma** [mikepenz/MaterialDrawer#1052]
Hi @mikepenz will you create a theme that extends day / night app compat theme?

So it can make the drawer beeing light / dark authomatically

**Comment by mikepenz** [comment]
@alorma will add it as soon as the bugs in the `DayNight` themes are fixed. Probably with v23.2.1 of the support libs

**Comment by nitecafe** [comment]
Is the day night theme still on the road map?

**Comment by mikepenz** [comment]
you can already get this really easy by having your own theme which uses the light theme during day and the dark theme during night
