### ISSUE TITLE
hide account icon?

### ISSUE THREAD

**Issue by TheLoyalCruel** [mikepenz/MaterialDrawer#1053]
hi 
how to hide account icon? I mean profile icon?
how to increase account header height?

thanks...

**Comment by mikepenz** [comment]
```java
withProfileImagesVisible(false)
```

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L166

**Comment by Rainer-Lang** [comment]
@TheLoyalCruel Look in the excellent sample - therefore it was created! :)

**Comment by TheLoyalCruel** [comment]
@mikepenz God bless you :)
thank you.. very nice :+1:

**Comment by TheLoyalCruel** [comment]
@Rainer-Lang of course :) thanks ;)
