### ISSUE TITLE
Taps on account header work differently for 21+ and older devices

### ISSUE THREAD

**Issue by dstd** [mikepenz/MaterialDrawer#1056]
Hi Mike!

There is some inconsistency in handling of taps on the account header in [AccountHeaderBuilder](https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L724).
For API level >= 21 whole `mAccountHeaderContainer` can emit `OnAccountHeaderSelectionViewClickListener`, but for older devices only `mAccountHeaderTextSection` handles the taps.

I'm curious what rationale behind this decision?

**Comment by mikepenz** [comment]
@dstd this decision was made, because on API <21 there is no `ripple`, and it does not look good if the whole header gets a solid color set, as the selection area does.

**Comment by dstd** [comment]
@mikepenz on my nexus@6.0 I also getting solid color area, a lighter than selection color on pre-21, but not a circular ripple like on other controls.
And this difference across devices looks like a bug for testers and users.

In my project I need to handle clicks on account header (profile image, account/name and all area of the header). Currently I managed this by this code:
```
accountHeader.getView().findViewById(R.id.material_drawer_account_header).setOnClickListener
```
But dependencies on implementation details is not a good practice at all.
