### ISSUE TITLE
Expandable Drawer List not working post AppCompat update

### ISSUE THREAD

**Issue by CeJienAJPC** [mikepenz/MaterialDrawer#1057]
Before updating the AppCompat to V23.2.0, the expandable list was working fine. However, post update, although the expandable list title is still getting displayed and the arrow icon is getting animated, the subitems ae not getting displayed. Any Idea???

Regards

**Comment by mikepenz** [comment]
@CeJienAJPC in the sample it is still working with v23.2.0. You may try the sample on your device and check if it also works. If yes you may post some more details on how you implemented it?

**Comment by CeJienAJPC** [comment]
After some digging found the problem.

The problem is not because of my updating to V23.2.0 but upgrading to
compile('com.mikepenz:materialdrawer:5.0.9@aar')

Initially, I used the dependency 5.0.3. Everything worked fine by then. Post upgrade to 5.0.9 the expandables went kaput.

**Comment by mikepenz** [comment]
@CeJienAJPC oh ok that makes sense. I expect you still have the logic for toggling the `Expandable` item in your code. This was removed and is now done automatically by the library. 

See the updated `DrawerActivity`.

the cahnges is also seen in this diff: https://github.com/mikepenz/MaterialDrawer/commit/88e9bdf8cccaac5aaf567ac6ffe682aeccba4f29
