### ISSUE TITLE
How to set the selection

### ISSUE THREAD

**Issue by Heri14** [mikepenz/MaterialDrawer#1059]
How can I update the selected state of the navigation drawer on back press?

**Comment by mikepenz** [comment]
@Heri14 you want to select a different item?

Just use the `setSeleciton` method
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L216

**Comment by Heri14** [comment]
No, I want to update selection on back press since selection state remains the same

**Comment by mikepenz** [comment]
@Heri14 so use the method on top, which sets the selection. 
Handling back press is nothing MaterialDrawer specific.

**Comment by Heri14** [comment]
How do I implement it since I have five fragments?
`

import android.annotation.TargetApi;
import android.app.Activity;
import android.app.ActivityManager;
import android.app.Fragment;
import android.app.FragmentManager;
import android.app.FragmentTransaction;
import android.content.Intent;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.drawable.ColorDrawable;
import android.os.Build;
import android.support.annotation.NonNull;
import android.support.v4.view.GravityCompat;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.app.ActionBarDrawerToggle;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.RecyclerView;
import android.support.v7.widget.Toolbar;
import android.view.Gravity;
import android.view.MenuItem;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.Toast;


import com.mikepenz.materialdrawer.AccountHeader;
import com.mikepenz.materialdrawer.AccountHeaderBuilder;
import com.mikepenz.materialdrawer.Drawer;
import com.mikepenz.materialdrawer.DrawerBuilder;
import com.mikepenz.materialdrawer.model.DividerDrawerItem;
import com.mikepenz.materialdrawer.model.PrimaryDrawerItem;
import com.mikepenz.materialdrawer.model.ProfileDrawerItem;
import com.mikepenz.materialdrawer.model.interfaces.IDrawerItem;
import com.mikepenz.materialdrawer.model.interfaces.IProfile;
import com.ms.square.android.etsyblur.EtsyActionBarDrawerToggle;

import java.io.FileDescriptor;
import java.io.PrintWriter;

public class Main extends AppCompatActivity {

    View child;
    String TITLES[] = {"Newspaper", "Gossip", "Entertainment", "Sports", "International"};
    String stackName;
    int ICONS[] = {R.drawable.newspaper, R.drawable.gossip, R.drawable.entertainment, R.drawable.sports, R.drawable.international};
    String TITLESF[] = {"About", "Exit"};
    int ICONSF[] = {R.drawable.about, R.drawable.exit};
    Long pos;

    //Similarly we Create a String Resource for the name and email in the header view
    //And we also create a int resource for profile picture in the header view
    Boolean isDrawerOpen = true;
    FragmentTransaction ft;
    Intent start;
    private Toolbar toolbar;
    DrawerLayout drawer;// Declaring the Toolbar Object

    int app_icon = R.mipmap.kenya;
    // Declaring Layout Manager as a linear layout manager
    // DrawerLayout Drawer;
    Drawer result;
    RecyclerView.ViewHolder holder;
    RecyclerView.ViewHolder vholder;
    // Declaring DrawerLayout
   String frName;
    ActionBarDrawerToggle mDrawerToggle;

    @TargetApi(Build.VERSION_CODES.LOLLIPOP)
    @Override
    protected void onCreate(Bundle savedInstanceState) {

        // getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN | View.SYSTEM_UI_FLAG_LAYOUT_STABLE);
        super.onCreate(savedInstanceState);


        setContentView(R.layout.activity_main);

        toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setHomeButtonEnabled(false);

        //getWindow().setStatusBarColor(Color.parseColor("#E601101A"));
        Fragment news = new Newspaper();
        ft = getFragmentManager().beginTransaction();
        ft.replace(R.id.container, news);
        ft.commit();


        int versionCode = BuildConfig.VERSION_CODE;
        String versionName = BuildConfig.VERSION_NAME;
        Bitmap bm = BitmapFactory.decodeResource(getResources(), app_icon);
        ActivityManager.TaskDescription td = new ActivityManager.TaskDescription(getString(R.string.app_name), bm, getResources().getColor(R.color.colorPrimary));
        this.setTaskDescription(td);

        //if you want to update the items at a later time it is recommended to keep it in a variable
        PrimaryDrawerItem item1 = new PrimaryDrawerItem().withName(R.string.title_activity_news).withIcon(R.drawable.newspaper).withIdentifier(1);
        //  SecondaryDrawerItem item2 = new SecondaryDrawerItem().withName(R.string.title_activity_about).withIcon(R.drawable.about);
        AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withSelectionListEnabledForSingleProfile(false)
                .withHeaderBackground(R.drawable.kenya_back)


                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                        return false;
                    }
                })
                .build();
//create the drawer and remember the `Drawer` result object
        result = new DrawerBuilder()
                .withAccountHeader(headerResult)
                .withFullscreen(true)

                .withActivity(this)
                .withActionBarDrawerToggleAnimated(true)

                        //.withTranslucentStatusBar(true)
                .withToolbar(toolbar)
                .addDrawerItems(
                        item1, new PrimaryDrawerItem().withName(R.string.title_activity_gossip).withIcon(R.drawable.gossip).withIdentifier(2),
                        new PrimaryDrawerItem().withName(R.string.title_activity_entertainment).withIcon(R.drawable.entertainment).withIdentifier(3),
                        new PrimaryDrawerItem().withName(R.string.title_activity_sports).withIcon(R.drawable.sports).withIdentifier(4),
                        new PrimaryDrawerItem().withName(R.string.title_activity_international).withIcon(R.drawable.international).withIdentifier(5),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem().withName(R.string.title_activity_about).withIcon(R.drawable.about).withSelectable(false).withIdentifier(6),
                        new PrimaryDrawerItem().withName(R.string.title_activity_exit).withIcon(R.drawable.exit).withSelectable(false).withIdentifier(7)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        // do something with the clicked item :D


                        if (drawerItem.getIdentifier() == 1) {
                            result.closeDrawer();
                            Fragment news = new Newspaper();
                            ft = getFragmentManager().beginTransaction();
                            ft.replace(R.id.container, news, "newsF");
                            ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
                            ft.addToBackStack("newsF");
                            ft.commit();
                            //getSupportActionBar().setIcon(R.drawable.newspaper);
                        } else if (drawerItem.getIdentifier() == 2) {

                            result.closeDrawer();

                            Fragment gossip = new Gossip();
                            ft = getFragmentManager().beginTransaction();
                            ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
                            ft.replace(R.id.container, gossip, "gossipF");
                            ft.addToBackStack("gossipF");
                            ft.commit();
                            //getSupportActionBar().setIcon(R.drawable.gossip);


                        } else if (drawerItem.getIdentifier() == 3) {

                            result.closeDrawer();

                            Fragment ent = new Entertainment();

                            ft = getFragmentManager().beginTransaction();
                            ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
                            ft.replace(R.id.container, ent, "entF");
                            ft.addToBackStack("entF");
                            ft.commit();
                            //getSupportActionBar().setIcon(R.drawable.entertainment);
                        } else if (drawerItem.getIdentifier() == 4) {
                            result.closeDrawer();

                            Fragment sport = new Sports();
                            ft = getFragmentManager().beginTransaction();
                            ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
                            ft.replace(R.id.container, sport, "sportF");
                            ft.addToBackStack("sportF");
                            ft.commit();


                        } else if (drawerItem.getIdentifier() == 5) {
                            result.closeDrawer();

                            Fragment inter = new International();
                            ft = getFragmentManager().beginTransaction();
                            ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
                            ft.replace(R.id.container, inter, "interF");
                            ft.addToBackStack("interF");
                            ft.commit();
                            //getSupportActionBar().setIcon(R.drawable.international);

                        } else if (drawerItem.getIdentifier() == 6) {
                            result.closeDrawer();

                            start = new Intent(getBaseContext(), About.class);

                            startActivity(start);
                        } else {
                            finish();
                        }


                        return true;
                    }

                })
                .withSavedInstance(savedInstanceState)
                .withShowDrawerOnFirstLaunch(false)
                .build();
       


        result.getDrawerLayout().setDrawerShadow(new ColorDrawable(0x99000000), GravityCompat.START);
        result.getDrawerLayout().setStatusBarBackgroundColor(Color.parseColor("#01101A"));


    }


    public static void setWindowFlag(Activity activity, final int bits, boolean on) {
        Window win = activity.getWindow();
        WindowManager.LayoutParams winParams = win.getAttributes();
        if (on) {
            winParams.flags |= bits;
        } else {
            winParams.flags &= ~bits;
        }
        win.setAttributes(winParams);
    }


    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();
        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return false;
        }

        return super.onOptionsItemSelected(item);
    }
public void setSelectioN()
{
   // Toast.makeText(getApplicationContext(),String.valueOf(),Toast.LENGTH_SHORT).show();
    pos = result.getCurrentSelection();

}
    public void back()
    {}

    @Override
    public void onBackPressed() {
        if (result.isDrawerOpen()) {
            result.closeDrawer();
        } else {
            int count = getFragmentManager().getBackStackEntryCount();
            if (count == 0) {
                super.onBackPressed();
            } else {
                getFragmentManager().popBackStack();

                android.support.v4.app.FragmentManager fm =  getSupportFragmentManager();


                stackName = null;
                for(int entry = 0;entry<fm.getBackStackEntryCount();entry++)
                {
                    stackName = fm.getBackStackEntryAt(entry).getName();
                }

                if(stackName == "newsF")
                {
                    result.setSelection(1);
                }
                else if(stackName == "gossipF")
                {
                    result.setSelection(2);
                }
                else if(stackName == "entF")
                {
                    result.setSelection(3);
                }
                else if(stackName == "sportF")
                {
                    result.setSelection(4);
                }
                else if(stackName == "interF")
                {
                    result.setSelection(5);
                }


                //Toast.makeText(getApplicationContext(),String.valueOf(result.getCurrentSelection()),Toast.LENGTH_SHORT).show();


            }

        }


    }
}`

**Comment by Heri14** [comment]
Thanks.

**Comment by cinemidia** [comment]
I am using SlidingTabLayout so i am setSelection of navegation Drawer's items but is not working... help me please

**Comment by mikepenz** [comment]
@cinemidia more details please

**Comment by Naeemullah832** [comment]
hy , first of all thanks , for creating such a great drawer , how ever , i am facing some problems , if you can help
the problem is i have multiple activities in my app and i am facing problem in what was selected in the previous activity , basically the state of the drawer

**Comment by Naeemullah832** [comment]
i am using expandible drawer items , and in the second activity i want to set the same expanded states
