### ISSUE TITLE
Swipeable AccountSwitcher?

### ISSUE THREAD

**Issue by xiprox** [mikepenz/MaterialDrawer#106]
Hello, are there any plans on making the AccountSwitcher swipeable like in most of the latest Google apps?

**Comment by mikepenz** [comment]
@xiprox not really. But if someone creates it i'm open for pull requests.

**Comment by xiprox** [comment]
I see. Thanks for the info.

Well, the crossfade effect on the background image, moving avatars, and fading text are all pretty cool if you ask me.

I've been working on this for some time now. I got a swipeable switcher (though with bugs) like a week ago. I decided to write everything from scratch. Will see where I can get with this. If I manage to get something nice and functional, I'll be sure to share it.

**Comment by mikepenz** [comment]
@xiprox nice. Perhaps the base can be used to bring a google like swipe head switcher in here too. But yeah.

thanks. just add a comment here if you get something ;)
