### ISSUE TITLE
not able to get subitem with identifier

### ISSUE THREAD

**Issue by ohpoloha** [mikepenz/MaterialDrawer#1061]
```java
drawer = drawerBuilder
                .withActivity(this)
                .withToolbar(toolbar)
                .withAccountHeader(drawerHeader)
                .addDrawerItems(
                        new ExpandableDrawerItem().withName("list").withSelectable(false).withIdentifier(1).withSubItems(
                                new PrimaryDrawerItem().withName("sub1").withIdentifier(2).withLevel(2)
                        ))
                .build();
        IDrawerItem item1 = drawer.getDrawerItem(1); // gives me the "list" item
        IDrawerItem item2 = drawer.getDrawerItem(2); // gives me null
```

Hi,
I was trying to badge the subitem but no effect. I then realized that I'm not able to get subitem with identifier, but withOnDrawerItemClickListener is able to catch the click event for subitem and also gives the correct identifier. I'm guessing this is a bug?

**Comment by mikepenz** [comment]
@ohpoloha no sub items are not resolved via identifier, as they may not be part of the list when you try to get them. 
You should just get the parent item and search for the identifier in its subitems.

**Comment by ohpoloha** [comment]
@mikepenz I see what you mean. Thanks for the clarification!
in that case, how can I badge subitem?

as the following won't work.
```
drawer.updateBadge(2, new StringHolder("10"));
```

what I currently have is I added another method like what you had for updateBadge, but instead of asking for identifier, I ask for IDrawerItem. then basically does the same thing. 
or if there's another approach?

**Comment by mikepenz** [comment]
@ohpoloha the best approach here is that you either keep the `DrawerItem` already global in your class and you alter the object when you want to change the badge. Or you get the `DrawerItem` from the parent `DrawerItem` 

```java
List list = ((ExpandableDrawerItem)drawer.getDrawerItem(1)).getSubItems();
PrimaryDrawerItem pdi = //get the item
//update the badge
```

Now as you update the item you have to notify the drawer about the changed element
```java
drawer.getAdapter(). notifyAdapterSubItemsChanged(result.getPosition(1));
```

**Comment by ohpoloha** [comment]
@mikepenz yea, I'm keeping the `DrawerItem` in my class now, so I can utilize the `updateBadge()` method. 
cool, thanks! I'll make sure to notify drawer.

**Comment by mikepenz** [comment]
@ohpoloha `updateBadge()` is wrong. with change the badge I meant just set the badge like
```java
//set new badge value
item.withBadge("newvalue");
//notify about the changed subitems
drawer.getAdapter(). notifyAdapterSubItemsChanged(result.getPosition(1));
```

**Comment by ohpoloha** [comment]
@mikepenz aha! i see. i'm seeing the pretty badge now :) 
thank you!
