### ISSUE TITLE
Compact account header - single profile - onClick not working

### ISSUE THREAD

**Issue by rafakob** [mikepenz/MaterialDrawer#1063]
Hello,
I'm using compact account header with only one profile:

```java
AccountHeader accountHeader = new AccountHeaderBuilder()
            .withActivity(this)
            .withCompactStyle(true)
             .withProfileImagesVisible(false)
             .withDividerBelowHeader(true)              
             .withSelectionListEnabledForSingleProfile(false
             .addProfiles(new ProfileDrawerItem().withName(getString(R.string.drawer_item_account)).withEmail("mymail@gmail.com"))
                .build();
```

I want to add OnClickListener to the whole header view:
```java
accountHeader.getView().setClickable(true);
accountHeader.getView().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(v.getContext(), "Header click", Toast.LENGTH_SHORT).show();
            }
        });
```

It's not working on preLollipop devices - simply nothing happens when I tap the header. On Lollipop and Marshmallow it's working fine.

**Comment by mikepenz** [comment]
@rafakob you define a custom `OnClickListener` direct on the view, but there is already the listener provided by the library:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L533

**Comment by rafakob** [comment]
Thanks for the reply. I've kinda got lost in all those builder methods :) It's working.
