### ISSUE TITLE
disable sliding of mini drawer in pull left/right

### ISSUE THREAD

**Issue by Debjyotinath** [mikepenz/MaterialDrawer#1064]
Hi Mike,
I have implemented the mini drawer in my app, but now i don't want to open the drawer on pull to right.  I have implemented hamberg with https://github.com/balysv/material-menu(as suggested by you in one of my earlier question)
So i don't need the slide to open feature, user will click the hamberg icon to open and close. Also it is creating problem with tabbed fragment and sliders. 
So my question is is there any way to disable the sliding effect when i swipe left or right anywhere else other the menu itself.

**Comment by mikepenz** [comment]
@Debjyotinath there are 2 different modes of sliding for the `MiniDrawer` the default one, and the "gmail-like" one. The default one allows to slide left by draging the right content view too, the second mode allows just to slide if you touch the `MiniDrawer` itself. 
https://github.com/mikepenz/Crossfader/blob/develop/library/src/main/java/com/mikepenz/crossfader/Crossfader.java#L52

**Comment by Debjyotinath** [comment]
Thanks a lot.It worked!!!!
