### ISSUE TITLE
Material Drawer restricts ability to draw under Status Bar

### ISSUE THREAD

**Issue by jhmacdon** [mikepenz/MaterialDrawer#1067]
So I spent a few hours trying to draw underneath the status bar with an ImageView. The solution, it turned out, was disabling the Navigation Drawer. Is there a workaround for this problem?

**Comment by mikepenz** [comment]
@jhmacdon the `MaterialDrawer` creates a normal `DrawerLayout` with the `fitsSystemWindows` flag set to true. So this is done with the system default behavior. 

You might want to check out the `FullScreenActivity` of the sample showing how you can get to use the area below the `StatusBar` too

**Comment by jhmacdon** [comment]
Ah, excellent. To summarize for future readers:

When building, user `.withFullscreen(true)` and afterwards call `result.getDrawerLayout().setFitsSystemWindows(false);`
