### ISSUE TITLE
.WithActionDrawerToggle doesn't have any effect

### ISSUE THREAD

**Issue by easycheese** [mikepenz/MaterialDrawer#107]
Last time it appears to work is in 1.0.2.  I'm pretty sure I'm using the right themes and I don't see anything specific about it in the wiki.

**Comment by mikepenz** [comment]
Hi. You use a toolbar with your activity? If yes do you pass it to the Drawer?

**Comment by easycheese** [comment]
Yes I passed the Toolbar.  

Actually you can mark this as resolved, 2.5.0 works just fine.

**Comment by mikepenz** [comment]
@easycheese thanks :)
