### ISSUE TITLE
Not firing a setSelection on 5.1.0

### ISSUE THREAD

**Issue by LaQuay** [mikepenz/MaterialDrawer#1072]
Hi Mike,

I've just updated my from 'com.mikepenz:materialdrawer:5.0.9@aar' to 'com.mikepenz:materialdrawer:5.1.0@aar' and my _setSelection_ stopped working.

```
drawer.setOnDrawerItemClickListener(this);
drawer.setSelection(1, true);
```

On 5.0.9 works perfectly, on 5.1.0 does not works, it does not fire.

I have checked your last commit and I guess that the checking should be "position > 0" instead of "position < 0", isn't it?

[https://github.com/mikepenz/MaterialDrawer/commit/69ea27ef5267b5b0e3112e6fae71ce85cd0b4a98](url)

Thanks!

**Comment by mikepenz** [comment]
@LaQuay oh yes you are totally right. Tested it and changed the statement afterwards again. 
Sorry for the issue. Pushed a new version fixing this. v5.1.1
