### ISSUE TITLE
How to setup my own font into the drawer

### ISSUE THREAD

**Issue by mrneiverth** [mikepenz/MaterialDrawer#1073]
Hello! :)

I must use a specific font into the drawer. I searched for some method to do it, but I didn't find :P . There is a method to do it ? if not, there is a way to put my font ?

**Comment by mikepenz** [comment]
@mrneiverth if you want a custom font you may also want it everywhere else in your app. So you might check https://github.com/chrisjenx/Calligraphy 
Most elements of the drawer also allow you to pass a `Typeface` so this might be what you are searching for

**Comment by mrneiverth** [comment]
Oh, thanks! 

great job as always :100:
