### ISSUE TITLE
Loosing header background on profile change

### ISSUE THREAD

**Issue by ateodor1** [mikepenz/MaterialDrawer#1074]
I setup the header using:

```java
headerResult = new AccountHeaderBuilder()
                        .withActivity(MainActivity.this)
                        .withHeaderBackground(R.drawable.header)
```

I have a list of profiles, which I generate a new Drawer when it is clicked, but using the same headerResult. It was working ok on version 4.6.4 but for the current version when I change the profile, I loose the header background. If I slide the menu, it shows the header properly again...

**Comment by mikepenz** [comment]
@ateodor1 you must not `.build` a `Drawer` more than once per activity. 
After the drawer was built you just should update it afterwards via the methods the `Drawer` offers

**Comment by ateodor1** [comment]
ok. Tks for the lib and for the so quick support!
