### ISSUE TITLE
5.1.1 No resource found when integrated the library to the project

### ISSUE THREAD

**Issue by njt28** [mikepenz/MaterialDrawer#1075]
Hi,

I pasted this to the app build.gradle file
```gradle
compile('com.mikepenz:materialdrawer:5.1.1@aar') {
        transitive = true
    }
```

but Android Studio said: 

```
Error:(1600) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme'.
Error:(1624) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar'.
Error:(1648) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar.TranslucentStatus'.
Error:(1672) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light'.
Error:(1695) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.ActionBar'.
Error:(1718) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.ActionBar.TranslucentStatus'.
Error:(1741) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar'.
Error:(1764) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.ActionBar'.
Error:(1787) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.ActionBar.TranslucentStatus'.
Error:(1810) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.TranslucentStatus'.
Error:(1833) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.TranslucentStatus'.
Error:(1856) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.TranslucentStatus'.
```

Can you please help? Thanks

**Comment by koesie10** [comment]
Same problem (version 5.1.1):

```
:app:processDebugResources
app\build\intermediates\res\merged\debug\values\values.xml:1540: AAPT: Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme'.

app\build\intermediates\res\merged\debug\values\values.xml:1564: AAPT: Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar'.

app\build\intermediates\res\merged\debug\values\values.xml:1588: AAPT: Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar.TranslucentStatus'.

app\build\intermediates\res\merged\debug\values\values.xml:1612: AAPT: Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light'.

app\build\intermediates\res\merged\debug\values\values.xml:1635: AAPT: Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.ActionBar'.

app\build\intermediates\res\merged\debug\values\values.xml:1658: AAPT: Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.ActionBar.TranslucentStatus'.

app\build\intermediates\res\merged\debug\values\values.xml:1681: AAPT: Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar'.

app\build\intermediates\res\merged\debug\values\values.xml:1704: AAPT: Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.ActionBar'.

app\build\intermediates\res\merged\debug\values\values.xml:1727: AAPT: Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.ActionBar.TranslucentStatus'.

app\build\intermediates\res\merged\debug\values\values.xml:1750: AAPT: Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.TranslucentStatus'.

app\build\intermediates\res\merged\debug\values\values.xml:1773: AAPT: Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.TranslucentStatus'.

app\build\intermediates\res\merged\debug\values\values.xml:1796: AAPT: Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.TranslucentStatus'.

:app:processDebugResources FAILED

FAILURE: Build failed with an exception.
```

**Comment by njt28** [comment]
@koesie10 : Do you know how to solve this problem?

**Comment by mikepenz** [comment]
Hmmm seems as the bintray upload missed that file. 

You might add the sub dependencies manually
//for the theme and ui util classes
https://github.com/mikepenz/Materialize#using-maven
//for the icon font support (just the core included by default)
https://github.com/mikepenz/Android-Iconics#1-provide-the-gradle-dependency
//to fill the list with the drawer items
https://github.com/mikepenz/FastAdapter#using-maven

**Comment by njt28** [comment]
Thanks @mikepenz 

I added these and see it's working now:

compile('com.mikepenz:fastadapter:1.2.3@aar') {
        transitive = true
    }
    compile('com.mikepenz:materialize:0.8.5@aar') {
        transitive = true
    }
    compile 'com.mikepenz:iconics-core:2.5.8@aar'
    compile('com.mikepenz:materialdrawer:5.1.1@aar') {
        transitive = true
    }

**Comment by Spiderbezno** [comment]
This is the final solution add all this dependincies or will be a fixed??

**Comment by LaQuay** [comment]
Same here, works fine in 5.1.0. but it does not in 5.1.1.

**Comment by mikepenz** [comment]
I will fix this as soon as I come home. It seems that this just happened because the gradle publish job did not upload the *.pom file. Sorry for the inconvenience

**Comment by seba123neo** [comment]
same here

**Comment by alessandrotorres** [comment]
Hi Mike,
same issues on 5.1.1

Thanks,
Ale

**Comment by mikepenz** [comment]
Ok. Just republished to JCenter. Doesn't seem to be the missing pom file as it is also not part of v5.0.9 or v5.1.0 

I have the weird feeling that this may be caused by the new build tools.

**Comment by mikepenz** [comment]
Ok after more tries. It might also be a bintray issue, and it now occurs for most users as I missed to publish the maven central release. I published it now, perhaps this solves the issue for everyone (will take a while to sync) 

Strange enough it still seems that bintray can't resolve the sub dependencies

**Comment by rubengees** [comment]
I had these issues sometimes already when I updated to the most recent version.
Did you ever thought about publishing through [JitPack](https://jitpack.io/)?
This would eliminate all custom upload scripts and users could use specific commits.

**Comment by mikepenz** [comment]
@rubengees yeah I assume the bintray upload is not completely working. 

No I won't switch to `JitPack` as it is not built, neither signed from my side, and I do not want that people using my libs are vulnerable for maleware.

**Comment by rubengees** [comment]
Whoa okay didn't know that. But how would a attacker upload malicious content? The dependency is exclusive for the repo of the developer of the lib as far as is know.

**Comment by mikepenz** [comment]
@rubengees if the attacker gets between you and jitpack, or if jitpack gets infected, there are a few scenarios. It might be not that critical as it requires real effort from the hackers side, but just to be save I prefer signed archives.

**Comment by rubengees** [comment]
Okay, thanks for the info! This is very interesting for me as I am using JitPack :+1:

**Comment by mikepenz** [comment]
@rubengees as mentioned it might be just a worst case scenario, and it might never happen. But still the fact that the archives via maven central are signed makes me feel a bit better

**Comment by mikepenz** [comment]
Maven Central should be synced now. So it should work now. I'm still investigating in how to properly upload it to bintray

**Comment by alessandrotorres** [comment]
Hi Mike,

I confirm, after your fix works fine adding `mavenCentral()` to `allprojects `section.
If leave only `jcenter()` compile errors occours.

```
allprojects {
    repositories {
        jcenter()
        mavenCentral()
    }
}
```

Thanks,
Ale

**Comment by Spiderbezno** [comment]
The erros is still happen

**Comment by mikepenz** [comment]
@Spiderbezno with jcenter. You can either add the sub dependencies manually as stated above, or you fetch the lib from mavenCentral.

I tried to resolve this for a few hours yesterday, but I was not able to upload the pom to jcenter.

**Comment by koesie10** [comment]
The POM is now also on JCenter it seems, it worked after I ran:
```
gradlew clean assembleDebug --refresh-dependencies
```

**Comment by mikepenz** [comment]
@koesie10 oh I think that might be because JCenter syncs over from maven central too
