### ISSUE TITLE
A lot of erros in a definition of theme in the file values

### ISSUE THREAD

**Issue by Spiderbezno** [mikepenz/MaterialDrawer#1076]
Error:(2491) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme'.

 **<style name="MaterialDrawerTheme" parent="MaterialTheme">**

Error:(2515) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar'.
**
<style name="MaterialDrawerTheme.ActionBar" parent="MaterialTheme.ActionBar">**

**Comment by mikepenz** [comment]
Related to https://github.com/mikepenz/MaterialDrawer/issues/1075
