### ISSUE TITLE
latest version seems not working in my studio (materialdrawer:5.1.1)

### ISSUE THREAD

**Issue by kswen** [mikepenz/MaterialDrawer#1077]
there`s an error always when i try to use :
Error:(1742) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme'.
Error:(1416) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar'.
Error:(1440) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar.TranslucentStatus'.
Error:(1464) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light'.
Error:(1487) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.ActionBar'.
Error:(1510) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.ActionBar.TranslucentStatus'.
Error:(1533) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar'.
Error:(1556) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.ActionBar'.
Error:(1579) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.ActionBar.TranslucentStatus'.
Error:(1602) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.TranslucentStatus'.
Error:(1625) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.TranslucentStatus'.
Error:(1648) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.TranslucentStatus'.

**Comment by LaQuay** [comment]
Check this issue #1075
