### ISSUE TITLE
How to use a custom layout as secondaryDrawerItem (Question)

### ISSUE THREAD

**Issue by amineMpdam** [mikepenz/MaterialDrawer#1078]
Well i'm trying to extend your SecondaryDrawerItem Class so tht i would inflate a custom layout as a drawer item

i've tried looking around your source code and the sample app, but unfortunatly it was beyond my grasp i suppose.

thank you in advance for your help

**Comment by mikepenz** [comment]
@amineMpdam so what is your issue?

If you create a new class which extends the `SecondaryDrawerItem` and overwrite the method which defines the layout, and the one which defines the type you should be fine.
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/SecondaryDrawerItem.java#L55

**Comment by amineMpdam** [comment]
Thank you for responding this quickly.
So basically i should override the methods getType() and getResLayout() ?

**Comment by mikepenz** [comment]
@amineMpdam yes.

**Comment by amineMpdam** [comment]
Great thank you very much!!
Ps:great library by the way :)

**Comment by mikepenz** [comment]
@amineMpdam thanks

**Comment by skmlcd** [comment]
I'm trying to do the same thing. getLayoutRes() should be my custom XML layout located in my layout package directory?

What about getType()? What exactly is this?

Is there any simple example of really simple custom item? For example adding more padding or something like that? Or imageview being above textview?

After you created your CustomDrawerItem, how do you setup it? Something like that?
```java
CustomDrawerItem item10 = new CustomDrawerItem()
					.withName("Testing")
					.withDescription("Lorem ipsum")
					.withIcon(GoogleMaterial.Icon.gmd_album)
					.withSelectable(false);
```

This throws an error and it wants to convert the type.
```CustomDrawerItem item10 = (CustomDrawerItem) new CustomDrawerItem()```

**Comment by skmlcd** [comment]
In the end I would like to achieve something like this.

![final](https://cloud.githubusercontent.com/assets/10860015/14058176/b5811106-f318-11e5-9da2-282069048052.png)

**Comment by mikepenz** [comment]
@skmlcd I think you should better open a new issue for this so your question can be answered independenly.

`getType()` returns the `identifier` used by the `RecyclerView` to identify this view and to cache it correctly. So you must define a new identifier for your custom item.

`getLayoutRes` should be your custom layout yes.

Regarding the cast issue. I assume you missed to change the `generic` declaration in the top of your new `CustomDrawerItem` class

**Comment by skmlcd** [comment]
@mikepenz Alright, thank you. I will look into it and submit new issue if necessary.
