### ISSUE TITLE
Can we have the ability to draw on top of the account icon?

### ISSUE THREAD

**Issue by MiralDesai** [mikepenz/MaterialDrawer#1079]
I'm looking into customising my drawer now that I have it in place. One big thing I am looking at doing is having an image overlay on top of the avatar. However everytime I try it, the image ends up going behind the avatar.

I have copied the layout from your library to customise it, but it doesn't allow for a lot because of the use of custom views like your BezelImageView. I can see the benefits to this but I was wondering if there was room here for customisation? 

Would I have to fork, and customise your library to achieve this or could support be built in? Happy to contribute towards this with PRs if this sounds like a good idea.

**Comment by mikepenz** [comment]
@MiralDesai why not just use the Drawable and modify the drawable itself?

**Comment by MiralDesai** [comment]
I'm not sure I follow. I'm not tinting the drawable or anything like that.
I'm adding stars to the bottom of it to signify the type of user they are.
It partially overlays the account icon, but keeps going behind it.

**Comment by mikepenz** [comment]
@MiralDesai I thought of something like this: http://stackoverflow.com/questions/6264543/draw-on-drawable

**Comment by MiralDesai** [comment]
Thanks, I'll give it a try and see what I find.

**Comment by MiralDesai** [comment]
It worked. Nice solution thanks.
