### ISSUE TITLE
Mini Drawer isDrawerOpen() is always false

### ISSUE THREAD

**Issue by utkarshns** [mikepenz/MaterialDrawer#1080]
Mini Drawer doesn't work with `isDrawerOpen()` and always returns `false` with both: the mini view and full view.

This makes `onBackPressed()` not close the drawer and go to previous activity if the drawer is in full view.

**Comment by mikepenz** [comment]
@utkarshns that's correct as there is no `DrawerLayout` if you use the `MiniDrawer` you can the current state via the `Crossfader` which is used in this case. 

https://github.com/mikepenz/Crossfader/blob/develop/library/src/main/java/com/mikepenz/crossfader/Crossfader.java#L347

**Comment by utkarshns** [comment]
Thanks for the immediate response.
