### ISSUE TITLE
Hamburger Menu and Back Button on Toolbar with Mini Drawer

### ISSUE THREAD

**Issue by utkarshns** [mikepenz/MaterialDrawer#1081]
Currently, the mini drawer can only be open or closed by dragging the drawer itself.
It would be great if the Hamburger menu button could be made to work with the mini drawer.
Tapping the hamburger would expand the drawer and turn the button itself to the back arrow, which would close the drawer.

This way the experience would be a bit more predictive and universal.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/943#issuecomment-172958437

**Comment by utkarshns** [comment]
Thanks for the immediate response.
