### ISSUE TITLE
MiniDrawer issue

### ISSUE THREAD

**Issue by Alex293** [mikepenz/MaterialDrawer#1082]
Hi, 

The mini drawer have an issue with the cross fader, i don't know if it come from the drawer or the cross fader.

When for the first time you build those, the click listener will be active for the items on the drawer (pane) even if its closed. The bug only appear the first tim i.e. if you open then close the pane everything works at it should. You can reproduce the bug on your demo its not coming from me bad using your lib.

I tried to open then close the pane by code it but it only work by swipe.

**Comment by mikepenz** [comment]
@Alex293 seems to be an issue of the `Crossfader` please open your issue there again ;)

**Comment by sarvajeet294** [comment]
I am also experiencing the same issue. The demo app also has this issue.

**Comment by mikepenz** [comment]
@sarvajeet294 use the latest `Crossfader`

**Comment by sarvajeet294** [comment]
Can you please tell me where will I get that Crossfader code? Is it updated in the git?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/Crossfader

**Comment by sarvajeet294** [comment]
Thank you so much!! :)
