### ISSUE TITLE
Update from MaterialDrawer 5.0.5 to a newer version with Android Support Library 23.2.0 is causing an exception on Pre-Lollipop devices

### ISSUE THREAD

**Issue by sdeff** [mikepenz/MaterialDrawer#1083]
Hi,

If I'm using MaterialDrawer with the new 23.2.0 Support Library on Pre-Lollipop devices I'm getting the same exception as described here:

http://stackoverflow.com/questions/35622438/update-android-support-library-to-23-2-0-cause-error-xmlpullparserexception-bin

and here:

http://stackoverflow.com/questions/35663413/xmlpullparserexception-binary-xml-file-line-17vector-tag-requires-viewportwid?lq=1

I already tried to fix it with adding "vectorDrawables.useSupportLibrary = true" to my build.gradle file. As soon as I switch back to MaterialDrawer 5.0.5 (Using the previous 23.1.1 Support Library) everything is working fine.

Right now I couldn't find a fix or a workaround so I switched back to version 5.0.5.

**Comment by mikepenz** [comment]
@sdeff sorry this is not `MaterialDrawer` issue but a **android support library** issue. Nothing I can do regarding this. For the time beeing you could exclude the support libs from the `MaterialDrawer` and provide your own version for them. 

Excluding is described here: http://stackoverflow.com/a/20016971/325479

**Comment by sdeff** [comment]
Thanks for your reply. In case you didn't know yet. Android Support Library 23.2.1 has just been released. I guess/hope they fix the issue.

**Comment by mikepenz** [comment]
@sdeff I already start to update the libs ;)
