### ISSUE TITLE
How to don't set the Selected Drawer Item behavior ?

### ISSUE THREAD

**Issue by mrneiverth** [mikepenz/MaterialDrawer#1084]
Hello
I don't wont any item selected in the drawer. Using WithSelectable(false) in the first item it doest work.
```java
new SecondaryDrawerItem().withName("Benefícios").withIcon(R.mipmap.ic_beneficios).withSelectable(false),
new SecondaryDrawerItem().withName("Salas").withIcon(R.mipmap.ic_salas).withSelectable(false),
```
And the result https://goo.gl/photos/TfkrrfxuaNwQysFN7. How can I fix it ?

**Comment by mrneiverth** [comment]
oks, but then, when I click in some item it doesn't get the beautiful event "selecting". Or, when my activities start and when I return to the main activity the drawer keep the last item selected. Maybe I expressed myself in a bad way in the first post :P

**Comment by mikepenz** [comment]
@mrneiverth not really sure. you already set the items to `withSelectable(false)` which means they do not get the selected background state

**Comment by mrneiverth** [comment]
In fact, my problem is when I return to main activity, and then if I open the drawer again, the last item what was selected is still selected. The event to select background state I think is usefull for the user check where he is clicking. 

I want to clean the drawer state when I return to the main activity. Without previews selected itens.

**Comment by mrneiverth** [comment]
I will try explain, sorry for being a bit confuse.

I have some itens into my drawer, which each one start a new activity when called. In my mainActivity, there is some scrolling tabs, which are not called in the drawer (there is no linkage for this tabs). 
So, when I call some of these activities (which are in the drawer) I want the background click event (that beatifull magic when clicked), and then, when I return to main acitivity and when I open the drawer again, the last acessed activity is still selected. What I want is unselect the last item clicked in the drawer.

I tried this, but the selected item is still selected when I open the drawer after all the process.
`@Override
            public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                ViewPager viewPager = (ViewPager) findViewById(R.id.viewpager);
                switch (position) {
                    //drawer -> salas
                    case 1:
                        drawerBuilder.withSelectedItem(-1);
                        Intent salasMain = new Intent(getApplicationContext(), Tela_Salas.class);`

Hope to be clear this time

**Comment by mikepenz** [comment]
@mrneiverth `withSelectable(false)` will still fire the event and it will launch the activity. The only thing different is that it won't draw the selected background for this item, and will stay with the previous one. 
This won't also disable the ripple and click highlight if you touch the item.

That's can also be seen in the sample app, the items which launch an activity are `withSelectable(false)` and the others not. So the other items can be selected as they do not launch an activity. Normaly this is done for items which switch fragments.

**Comment by mrneiverth** [comment]
I need to debug it, looking over I found nothing. When I get what is happening I will return here to tell you. 

Thanks :D

**Comment by mikepenz** [comment]
@mrneiverth maybe I just do not get the correct thing :D So probably a few images will help here ;)

**Comment by mrneiverth** [comment]
sorry for my late, I'm a little busy in life. Anyway, I looked at your code and didn't find my bug :(

I want the same behavior of your drawer in the _DrawerActivity_ , which the itens are just selected when the click is happening (the background click event). If I open the drawer again, the item is not selected anymore. 

Here is my code:
```
 headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.icon_logo)
                .build();

        result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withAccountHeader(headerResult)
                .withTranslucentStatusBar(false)
                .withCloseOnClick(true)
                .withDelayOnDrawerClose(100)
                .addDrawerItems(
                        new SecondaryDrawerItem().withName("Salas").withIcon(R.mipmap.ic_salas).withTypeface(gotham_light).withSelectable(false),
                        new SecondaryDrawerItem().withName("Benefícios").withIcon(R.mipmap.ic_beneficios).withTypeface(gotham_light).withSelectable(false),
                        new SecondaryDrawerItem().withName("Agenda").withIcon(R.mipmap.ic_agenda).withTypeface(gotham_light).withSelectable(false),
                        new SecondaryDrawerItem().withName("Mapa").withIcon(R.drawable.ic_action_map).withTypeface(gotham_light).withSelectable(false),
                        new SecondaryDrawerItem().withName("Gestão").withIcon(R.drawable.ic_people).withTypeface(gotham_light).withSelectable(false),
                        new SecondaryDrawerItem().withName("Dicas").withIcon(R.mipmap.ic_dicas).withTypeface(gotham_light).withSelectable(false),
                        new SecondaryDrawerItem().withName("Sobre").withIcon(R.drawable.ic_action_info).withTypeface(gotham_light).withSelectable(false))
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        if(drawerItem != null) {
                            ViewPager viewPager = (ViewPager) findViewById(R.id.viewpager);
                            Intent intent = null;
                            switch (position) {
                                //drawer -> salas
                                case 1:
                                    intent = new Intent(getApplicationContext(), Tela_Salas.class);
                                    break;
                                //drawer -> Beneficios
                                case 2:
                                    intent = new Intent(getApplicationContext(), Beneficios_fragment.class);
                                    break;
                                //drawer -> agenda
                                case 3:
                                    intent = new Intent(getApplicationContext(), Agenda_fragment.class);
                                    break;
                                //drawer -> predios
                                case 4:
                                    intent = new Intent(getApplicationContext(), Mapa_fragment.class);
                                    break;
                                case 5:
                                    intent = new Intent(getApplicationContext(), Gestao_fragment.class);
                                    break;
                                case 6:
                                    intent = new Intent(getApplicationContext(), Dicas_Activity.class);
                                    break;
                                case 7:
                                    intent = new Intent(getApplicationContext(), Sobre_fragment.class);
                                    break;
                                default:
                                    viewPager.setCurrentItem(0);
                                    break;
                            }
                            if(intent != null){
                                startActivity(intent);
                            }
                        }
                        return false;
                    }
                })
                .withSavedInstance(savedInstanceState)
                .build();
```
Maybe there is something related to Bundle data ?

**Comment by mikepenz** [comment]
@mrneiverth and you should prevent the default selection of the first element with:
https://github.com/mikepenz/MaterialDrawer#how-can-i-create-a-drawer-without-a-default-selection

Hmmm looks correct. 

You might also considering to have the delay not for the drawer closing event but for the click listener to be fired. 

As an addition if you still mean the touch highlight. You may use a wrong theme combination so the ripple is not visible?

**Comment by mrneiverth** [comment]
I'm using the `Base.Theme.DesignDemo`. And yes, is the problem is the theme. If I change for your theme `MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus">` my drawer work right as yours in `DrawerActivity`.

There is some way to workround using the designDemo ?

**Comment by mikepenz** [comment]
@mrneiverth to be honest. I do not know this `DesignDemo` theme. I would highly recommend that you base your theme on one of the provided themes from the `MaterialDrawer` alternative you should add all `material_drawer_*` attributes to your theme

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/values/styles.xml#L230

**Comment by mrneiverth** [comment]
I will make this change. 

Thanks a lot for your time!

 My small little contribution to your library: 
`        if (savedInstanceState == null) {
            // set the selection to the item with the identifier **11**
            result.setSelection(**21**, false);`
At DrawerAcitivity.

Anyway, Great Library!
