### ISSUE TITLE
MultiDrawer and CrossFadeDrawerLayout together

### ISSUE THREAD

**Issue by mneckoee** [mikepenz/MaterialDrawer#1085]
Hi, thank for your great library.
I want MultiDrawer (one at left and one at right) in my app. And the left should be a crossFadeDrawer(2 step drawer). I implement the CrossFadeDrawer like in ypur sample app the I build another simple drawer and append it to the first one. But touches dont work fine and the first drawer dont get to its second step( I always see a minidrawer). the second drawer isn't opened on touch.

**Comment by mneckoee** [comment]
I solve it!! I didn't use append. I set the first drawer gravity to left and the second to right and it worked fine. thank you again

**Comment by mneckoee** [comment]
Why 2-step drawer has an unusual shadow? see the screenshot!
![device-2016-03-12-094250](https://cloud.githubusercontent.com/assets/16606340/13721309/558d0642-e837-11e5-832e-384318836f72.png)

**Comment by mikepenz** [comment]
@mneckoee I assume this happens because of this: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1542

You should use `START` and `END` as gravity so the RTL support works

**Comment by mikepenz** [comment]
@mneckoee have you tried my suggestion?

**Comment by mneckoee** [comment]
yes it worked. but another problem!! `.withSetSelected(false)` doesn't work!!
I set the drawer `withMultiChoice`. For having a `RadioGroup` behavior I want for example if item 6 clicked then item 7 `setSelected` to false but it doesn't work. 
this is my code:

`
leftDrawer = new DrawerBuilder()
                .withActivity(this)
                .withMultiSelect(true)
                .addDrawerItems(                        PrimaryDrawerItem().withName("متاهل").withIcon(R.drawable.married).withIdentifier(6).withTypeface(ResourceManager.iranTF).withSelectable(true),
                        new PrimaryDrawerItem().withName("مجرد").withIcon(R.drawable.button_single).withSelectedIcon(R.drawable.button_single).withIdentifier(7).withTypeface(ResourceManager.iranTF).withSelectable(true)
                ) 
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        if (drawerItem == null)
                            return false;
                        long clickedDrawerItemId = drawerItem.getIdentifier();
                        Log.d(TAG, "onItemClick>> identifier:" + clickedDrawerItemId);
                        if (clickedDrawerItemId == 6) {
                            leftDrawer.getDrawerItem(7).withSetSelected(false);
                            Log.d(TAG, "onItemClick>> set 7 selected false");
                        }
                        return true;
                    }
                })
                .withCloseOnClick(false)
                .withDrawerGravity(Gravity.START)
                .build();
`

**Comment by mikepenz** [comment]
@mneckoee in this case I highly recommend to directly use the `API` of the underlaying `FastAdapter` 
https://github.com/mikepenz/FastAdapter

You can get it by calling `leftDrawer.getAdapter()`. This allows you to deselect, select, ...
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L797
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L762

**Comment by mneckoee** [comment]
worked!! thank you
