### ISSUE TITLE
custom widget in drawer

### ISSUE THREAD

**Issue by mneckoee** [mikepenz/MaterialDrawer#1086]
Hello again, How Can I have RadioGroup and RadioButtons in drawer?

**Comment by mikepenz** [comment]
@mneckoee you can create your own `CustomDrawerItem`s but that's up to you. You will also have to keep track of which button is activated and deactivate all others. 

http://stackoverflow.com/questions/32066618/materialdrawer-customdraweritem
http://stackoverflow.com/questions/31030595/how-to-customize-the-draweritem-using-the-lib-mikepenz-materialdrawer/32542999#32542999
