### ISSUE TITLE
RecyclerView notifyItemChanged Prevent Scroll

### ISSUE THREAD

**Issue by grishko188** [mikepenz/MaterialDrawer#1088]
Hello! First of all thanks for the greate library.
I found the critical issue after updating support library to 23.2.1. Every time when menu item set selected RecyclerView scrolls to top.
I discovered that the problem is inside method handleSelection. The method notifyItemChanged must be called in UI thread. 
http://stackoverflow.com/questions/26704680/recyclerview-notifyitemchanged-prevent-scroll
Please help! 

And one more issue. There no way to use method withAdapter(FastAdapter adapter), beacause mAdapter is always not null. He creates inside constructor.

**Comment by Rainer-Lang** [comment]
@grishko188 I don't see this issue as "critical". It's not nice but it's even not critical. You can also provide a PR. :+1:

**Comment by Rainer-Lang** [comment]
You could use a previous version...

**Comment by mikepenz** [comment]
@grishko188 hi.

As the `MaterialDrawer` nor the `FastAdapter` calls methods on any other thread, than the thread you call these methods the issue is somewhere in your application. Make sure you set the selection on the correct thread. 

The `withAdapter` method can only be used before the `Drawer` was built, and before items were added. You should call this method directly after you provided the activity like:
```java
new DrawerBuilder().withActivity(this).withAdapter(...)...
```

**Comment by mikepenz** [comment]
I also want to add, that it is not necessary to send 3 e-mails just to get an anser on an issue. I really understand that some bugs are "critical" in some special circumstances and need a fast repsone. But you also have to remember that this is an Open Source project which is supported and done all in my free time. Today is saturday, so it's weekend. I have a normal day time job where I work between 38,5 - 50 hours a week. I spent about 10-20 hours a week answering questions, and supporting my libs. Everything for free. I assume that the app you want to release is paid or you get money for it. I do not get money for the library (I do not do open source for money, but just to clarify this). I am not sure how bugs or issues are handled in your company. But I have many years experience in a global successful agency and I know how support tickets are handled in big companies. Most companies have contracts which state that a support ticket has about 5 days to be solved and first response within the same working day. And that's for companies which call for 150€ or more for a single hour. Please keep this in mind when sending 3 mails to an open source dev the next time. You might ask via one e-mail after a day (if you got no response) but don't expect an answer and solution within a few minutes. 

(And in your case. I answered in less than 3 hours which is a better service than most companies will offer...)

**Comment by Rainer-Lang** [comment]
@grishko188 I hope that you as a COMPANY will do something good for @mikepenz 
Many other "normal" people make donations for open source devs. He's doing such great work (development and support) and helps to save development time.

**Comment by grishko188** [comment]
@mikepenz  I am realy sorry about this situation. =( 
And I had no idea that you would send e-mail. 
I just posted a link to the bug report for my clienat as proof that we are doing everything possible in order not to disrupt the release. 
So I apologize again and again.

**Comment by grishko188** [comment]
@mikepenz  If you do not mind I have a comment on your answer.
1)`FastAdapter` calls `notifyItemChanged` inside method `select` and `deselect` wich calls inside `handleSelection` and this method calls in `onClick(final View v)` for viewHolder item.

2) `

    /**
     * Construct a Drawer by passing the activity to use for the generation
     *
     * @param activity current activity which will contain the drawer
     */
    public DrawerBuilder(@NonNull Activity activity) {
        this.mRootView = (ViewGroup) activity.findViewById(android.R.id.content);
        this.mActivity = activity;
        this.mLayoutManager = new LinearLayoutManager(mActivity);
        getAdapter();
    }
    /**
     * default constructor
     */
    public DrawerBuilder() {
        getAdapter();
    }
`
This is both youк constructors. And they both creates adapters inside them. So after constructor were called we dont have a chance to set custom FastAdapter.

Thanks one more time for your response, and sorry one more time! 
Clients sometimes do very terrible and unwise things =((

**Comment by mikepenz** [comment]
@grishko188 don't take me wrong. I really love to support my libs, and I always try to give best support as possible. But people need to understand that everything I do happens in my freetime and I really spend a lot of freetime for this. 

1.) Yeah you are right the deselect still needs the notifyItemUpdated because I do not have the view available anymore. But once again the `onClick` itself always happens on the UI-Thread. so everything in there happens on the UI-Thread. 
If this really blocks the release of the app you should really consider of using a previous version of the support libraries. I can't change any issues / behaviors of the `RecyclerView`. You might want to open a platform bug on http://b.android.com/ if it seems to be an support library issue. 

2.) Yeah I see your point. Will adjust this in an update. Missed this when checking from my phone. 
Just for curiosity, what have you changed for your `FastAdapter`? 

I know, I work a lot with clients

**Comment by grishko188** [comment]
1)I am beginning to be convinced that this is a bug in RecyclerView =( If i remove `notifyItemChanged` in `deselect(final int position, Iterator<Integer> entries)` it stops jumping but also dosent unselect items. And even if try to do `runOnUiThread` he still jumps. And only in deselected. `select` use `notifyItemChanged` too, but bug not reproduce for this method.

2) I would like to override all the methods select and deselect , and call them directly in the UI thread. That was bad idea) But i found the issue))) 

support library release 23.2.0 and 23.2.1 its a real nightmare((

**Comment by mikepenz** [comment]
1.) `select` is not called by default from the `onClick` (https://github.com/mikepenz/FastAdapter/blob/4d33dc516c668f875d2f15e8fb9d6657c0d9cdaf/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L709) just the `deselect()` 

2.) I just built `5.1.4-SNAPSHOT` for you which contains the following commit https://github.com/mikepenz/MaterialDrawer/commit/8acc78a24cebb8717f602cbd4dafa2c0f078b078 and uploaded it to the SNAPSHOT maven repo You need to add this to your root build.gradle (`maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }`)
Which issue have you found?

Yeah they are really new and changed a huge amount of things, so they are still a bit unstable.

**Comment by grishko188** [comment]
Many many thanks for your help! If I find a solution or get an answer from the support I write here. You are the best)

**Comment by mikepenz** [comment]
Ok great.
