### ISSUE TITLE
[MiniDrawer] Anyway I can adjust the distance of the icons from the extreme left of the screen?

### ISSUE THREAD

**Issue by utkarshns** [mikepenz/MaterialDrawer#1090]
I want to reduce the width of the mini drawer in closed position, doing this is easy but the icons in closed state get clipped. I want to be able to adjust the draw distance from the left. 
Thanks in advance.

objective: to give more screen real-estate to content on the left while also preserving the quick access buttons on the mini drawer

**Comment by mikepenz** [comment]
@utkarshns can you please add a screenshot? Or a photo describing your requirement a bit more? 

If you want to modify paddings, etc from the `MiniDrawerItem` and `MiniProfileDrawerItem` you can do the following

Extend the two items, or create them new (you can also copy paste them and alter their code):
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/MiniDrawerItem.java
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/MiniProfileDrawerItem.java
(You want to take a closer look at this here too, required for compatiblity https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/MiniDrawerItem.java#L161)

Then you also alter the layouts so the paddings fit your needs: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_mini.xml
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_mini_profile.xml

And afterwards you have to `extend` the `MiniDrawer` and overwrite the following two methods to allow you custom `MiniDrawerItem` and `MiniProfileDrawerItem` to be used:

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L240
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L259

**Comment by utkarshns** [comment]
That is right, I need to adjust the padding.
Screenshot: https://goo.gl/photos/Lc5Yae56wKAFx5Fh7

I will look into the solutions.

Thanks

**Comment by mikepenz** [comment]
@utkarshns yes this will require the steps as written above. It is a bit more complicated (but possible) because the `MaterialDrawer` and all of its components focus to follow the **Material Design Guidelines**.

**Comment by utkarshns** [comment]
Yes, the guidelines are important. Perhaps I will reconsider using the defaults and sticking to the guidelines so as to provide the best user experience across all devices.

**Comment by mikepenz** [comment]
@utkarshns to exactly stick to the guideliens. You should consider using the `MiniDrawer` only on tablets, and not on phones.

**Comment by utkarshns** [comment]
@mikepenz 
You are quick as a bot. *claps*
`MiniDrawer` was liked on phones by everyone in the team and target devices have pretty huge screens, sort of phablets.

**Comment by mikepenz** [comment]
@utkarshns who knows :D 

Oh well then its fine :). If its on phones with huge screens it might work. Always be careful with such concepts. But as you will also make it a bit smaller (might consider just doing this on phones and not on tablets) it doesn't consume to much space from the content area

**Comment by utkarshns** [comment]
@mikepenz 
Thanks for the tips, will keep them in mind for sure.

**Comment by mikepenz** [comment]
@utkarshns just for curiosity did this problem occur on Android N? Or just on API <= 23?

**Comment by utkarshns** [comment]
Haven't tried on Android N. I have an N5, sadly google ditched us for the preview. :(

**Comment by mikepenz** [comment]
@utkarshns just had the chance to test the Android N preview on a Nexus 6 and the settings application from Google had exactly the same issue. Always jumped to top when an item was updated. Seems like the recyclerview of the support libraries has an issue here.

**Comment by utkarshns** [comment]
@mikepenz 
This maybe super OT but how do I highlight the 'MiniDrawer' icon other than the first one. 

Case:
I plan to click the closed 'MiniDrawer' icon and go to another activity with 'MiniDrawer, now in the 'SecondActivity' I would want to highlight the 'SecondActivity' icon rather than the default top most icon so it indicates the current activity in the 'MiniDrawer' also.

**Comment by mikepenz** [comment]
@utkarshns if you have improvements. I am always open for a pull request

**Comment by utkarshns** [comment]
@mikepenz 
If I can, I sure as hell would bombard the lib with pull requests of improvements.
I got a lot to learn and the lib lacks any bugs as such.
