### ISSUE TITLE
[MiniDrawer] How do I change the default highlight?

### ISSUE THREAD

**Issue by utkarshns** [mikepenz/MaterialDrawer#1091]
How can I change the default highlight in closed 'MiniDrawer' ?
The icon on the top gets the highlight at all times.

Case:
I plan to click the closed 'MiniDrawer' icon and go to another activity with 'MiniDrawer, now in the 'SecondActivity' I would want to highlight the 'SecondActivity' icon rather than the default top most icon so it indicates the current activity in the 'MiniDrawer' also.

What do I do?

**Comment by mikepenz** [comment]
@utkarshns the highlighted item is connected with the normal selection. Just select a different item. 
https://github.com/mikepenz/MaterialDrawer#selecting-an-item

**Comment by utkarshns** [comment]
Thanks!

**Comment by utkarshns** [comment]
'result.setSelection(1);' before the 'buildView();' crashes the app.
after the 'buildView();' it freezes the app.

What worked for me was '.withSelectedItem(item_indentifier)' with 'buildView()'

Thanks for the awesome lid and support.

**Comment by mikepenz** [comment]
@utkarshns yeah because `result` is `null` before `buildView()` was called.

Your app freezes? Just tried this does not happen in the sample app. 

But I was wrong, you have to set the selection for the `MiniDrawer` and normal `Drawer`
```java
result.setSelection(identifier);
miniResult.setSelection(identifier);
```

**Comment by utkarshns** [comment]
`.withSelectedItem(item_indentifier)`
works like a charm for me as intended.
Thanks

**Comment by abhay7030** [comment]
@utkarshns Can you alson help me with the same problem. My issue is #1766.
I want to know how you did the MiniDrawerItem selection. Because in my case the expanded drawer works fine but the focus of MiniDrawer is always on the first item.
