### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by jaycho19** [mikepenz/MaterialDrawer#1092]
D:\Android\Android-Drawer\DesignSupportLibraryExamples-master\DesignSupportLibraryExamples-master\NavigationViewDemo\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.2.1\res\drawable\abc_textfield_search_material.xml

Error:(21, 29) No resource found that matches the given name (at 'drawable' with value '@drawable/abc_textfield_search_default_mtrl_alpha').

Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Administrator\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe'' finished with non-zero exit value 1

plz help, many thanks

**Comment by mikepenz** [comment]
@jaycho19 the latest version of the `MaterialDrawer` requires the latest support libraries, and has to be compiled with compileSdk 23
https://github.com/mikepenz/MaterialDrawer/blob/develop/build.gradle#L21
