### ISSUE TITLE
SwitchDrawerItem issue

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/MaterialDrawer#1094]
I'm using SwitchDrawerItem and I noticed that withSelectable(false) does not work.

**Comment by mikepenz** [comment]
@EpsilonOrionis the question it what do you expect this method will do?

**Comment by EpsilonOrionis** [comment]
To not select the item

**Comment by mikepenz** [comment]
@EpsilonOrionis just tried it with the sample app. `withSelectable(false)` works. It prevents the item of having a selected state. Which does not mean that you can toggle the `Switch`, this can be handled with `withSwitchEnabled(false)` or `withEnabled(false)`
