### ISSUE TITLE
Use a button as a hamburger icon 

### ISSUE THREAD

**Issue by kazisrabon** [mikepenz/MaterialDrawer#1095]
hi mike, 
how can i use a button instead of hamburger icon to open the drawer?
is it possible to use both embedded and mini map and both will open at same side. if i click hamburger embedded will open and if i click an item embedded will be closed and mini will be appeared. how could i do that?

**HELP NEEDED**

**Comment by mikepenz** [comment]
@kazisrabon sorry your questions are really confusing. 

Yes you can open the drawer and close it via the `Drawer` object
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L123

**Comment by kazisrabon** [comment]
thnx @mikepenz
