### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/MaterialDrawer#1098]
What do you think about adding for the avatar icon and the header background a feature that sets an Image if the icon passed in the method (e.g
withIcon()) raise a FileNotFoundException? I'm using Glide and they provide with the method .error() such a thing.

**Comment by mikepenz** [comment]
@EpsilonOrionis as the avatar icon is loaded via the `DrawerImageLoader` this is already possible. And as the `Header` background can be set directly on the `ImageView` this is also possible ;)
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L56

**Comment by EpsilonOrionis** [comment]
Examples?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java#L40
https://github.com/mikepenz/MaterialDrawer#load-images-via-url

For the `ImageView` I think no example is required.

**Comment by EpsilonOrionis** [comment]
Now it loads the placeholder, but the image exists

**Comment by EpsilonOrionis** [comment]
I'm building the logic, right?

**Comment by EpsilonOrionis** [comment]
No it isn't working

**Comment by mikepenz** [comment]
@EpsilonOrionis as you mentioned that `glide` provides the `.error()` function. I do not force any image loading behavior here. I just offer the listeners and you can implement any image loading lib you want. 

For the header you can directly do it on the `ImageView`

**Comment by EpsilonOrionis** [comment]
Please an example

**Comment by mikepenz** [comment]
@EpsilonOrionis sorry I can't give support for external libraries. 

Seems to be something glide specific. As mentioned the **MaterialDrawer** does not force any logic here. Everything is up to the dev.

as of the documentation:
```java
Glide  
    .with( context )
    .load(UsageExampleListViewAdapter.eatFoodyImages[0])
    .listener( requestListener )
    .error( R.drawable.cupcake )
    .into( imageViewPlaceholder );
```
