### ISSUE TITLE
Account switcher arrow is still taking up space when disabled

### ISSUE THREAD

**Issue by dejarno** [mikepenz/MaterialDrawer#1099]
Hey

First of all great library!

I noticed a small bug, is it possible to set the visibility of the account switcher arrow to `gone` instead of `invisible`? Right now it is still taking up space when disabled.

See this example:
<img width="289" alt="screen shot 2016-03-15 at 11 52 28" src="https://cloud.githubusercontent.com/assets/2677077/13775437/c76c429a-eaa4-11e5-81c2-0a50694bce57.png">

Thanks!
Jarno

**Comment by mikepenz** [comment]
Starting with v5.1.4 the padding is removed when the arrow is hidden

**Comment by dejarno** [comment]
Hey Mike,
Thanks for the quick response but the issue isn't fixed yet. As long as the arrow is set to `invisible` it will keep taking up space and the text field isn't able to span to whole width...

This is a screenshot with the view inspector:
![screen shot 2016-03-17 at 09 17 15](https://cloud.githubusercontent.com/assets/2677077/13840184/1c9ccc4e-ec21-11e5-8126-1fa7bb713cec.png)

Thanks
Jarno

**Comment by mikepenz** [comment]
@dejarno oh well you are right. Totally missed that the compact header has a slightly different layout here.

**Comment by dejarno** [comment]
Thanks man :+1:
