### ISSUE TITLE
Drawer width

### ISSUE THREAD

**Issue by Bene8493** [mikepenz/MaterialDrawer#11]
Hi,
can someone tell me how to adjust the drawer width? As it is now, it always takes about 80% of the screen, which is ok for phones, but doesn't look so good in landscape or on tablets.

Other than that, it's great, good job ;)

**Comment by mikepenz** [comment]
@Bene8493 that's a great question. 

right now the only option would be to define it by code. definitely need to changes this. 
I'll add a custom dimen definition so you can easily change it.

```xml
<!-- Definition for the Drawer Slider margin right -->
<dimen name="material_drawer_margin">0dp</dimen>
```

**Comment by Bene8493** [comment]
And how would I do that by code?
I tried
drawerResult.getDrawerLayout().getLayoutParams().width = getResources().getDimensionPixelSize(R.dimen.navigation_drawer_width);

but that is changing the drawers parents width. How do I get the drawer? :/

Googles Design Guidlines say:
Width = screen width - app bar height (max 400dp)

Thanks for your quick response.

**Comment by mikepenz** [comment]
currently i'm working with margin. so you can set the margin of the slider:

```java
result.getSlider()
```

at the moment i'm thinking if it's better to be able to define a margin. or a width
I'll probably just add a maxWidth of 400dp

**Comment by Bene8493** [comment]
Why margin?
This works, thanks you:
drawerResult.getSlider().getLayoutParams().width = getResources().getDimensionPixelSize(R.dimen.navigation_drawer_width);

**Comment by mikepenz** [comment]
yeah because on smaller devices google states to use 56dp margin

**Comment by Bene8493** [comment]
Ah ok, I'll just take the minimum of this value and 400dp.

**Comment by mikepenz** [comment]
v0.9.2 includes a method to set the drawerWidth
and/or you can overwrite a custom margin value ;)

Thanks for the report.

**Comment by Bene8493** [comment]
That was fast! Nice job :)

**Comment by mikepenz** [comment]
@Bene8493 as soon as maven central is synced you can use v0.9.2 or you can use v0.9.3-SNAPSHOT right now ;).

**Comment by Bene8493** [comment]
Awesome, thank you ;)
