### ISSUE TITLE
Account header Image 

### ISSUE THREAD

**Issue by taimur97** [mikepenz/MaterialDrawer#1101]
Hi! 

Is it possible to set an ImageView as the header background and change the image in imageview whenever I want? 

I want to get the image from url and set it as the header background the problem is I can't fetch the image in Application class and until the activity is displayed. If it is not possible then Can I add a custom view inside the drawer I don't want to change the whole layout only add a  custom view above primaryItems which would take place of account header

**Comment by mikepenz** [comment]
@taimur97 just get the already existing `ImageView` of the background and alter the image
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L56

**Comment by taimur97** [comment]
Thanks it worked now I want to listen for when the header background is clicked. I have not added any profile. 
I tried the method withOnHeaderListener but it didn't work 
I also tried 
headerResult.getHeaderBackgroundView().setOnClickListener(listener)

And it also didn't work 

How can I listen when the header background is clicked so I can perform some action?
