### ISSUE TITLE
Sticky Footer elevation

### ISSUE THREAD

**Issue by Punchieo** [mikepenz/MaterialDrawer#1106]
Is there any way you can expose the sticky footer shadow size? The default may not be suitable for all situations.

**Comment by mikepenz** [comment]
@Punchieo no easy solution to do this. The defined shadow size is the correct one as defined in the `Google Material Design Guidelines`

**Comment by mikepenz** [comment]
The shadow is handled within this `if`
https://github.com/mikepenz/MaterialDrawer/blob/befb20bc6dc3e14740ef9f5bec402d73555b56a2/library/src/main/java/com/mikepenz/materialdrawer/DrawerUtils.java#L312

**Comment by mikepenz** [comment]
will be in the next version configurable via the dimens.xml
