### ISSUE TITLE
Secondary Switch Drawer Item color

### ISSUE THREAD

**Issue by armoun** [mikepenz/MaterialDrawer#1107]
how i can change color SecondarySwitchDrawerItem ?

**Comment by mikepenz** [comment]
@armoun which color?

**Comment by armoun** [comment]
![shohada-03-done-80](https://cloud.githubusercontent.com/assets/14873327/13877715/de27f5b8-ed21-11e5-8da9-3214223bf8df.png)

i want change color switch drawer item, how i can change ? thanks :)

**Comment by mikepenz** [comment]
@armoun this color is not managed by the `MaterialDrawer` it is defined by your theme. Read more here:
http://stackoverflow.com/a/26715076/325479

If you need to change this one programmatically, you will have to implement a `CustomDrawerItem` which allows you to define this color. 

You can find some info regarding this here:
http://stackoverflow.com/a/32542999/325479
http://stackoverflow.com/a/32543209/325479

**Comment by armoun** [comment]
thanks :+1:
