### ISSUE TITLE
Only one item expanded at the tiem

### ISSUE THREAD

**Issue by fliespl** [mikepenz/MaterialDrawer#1108]
Hi Mike,
is it possible to use multiple ExpandableDrawerItems (with subitems), but force it to only allow one of those to expanded at one time?

I have tried something like this and this worked only with one of two items (probably internal position problem)
```java
        result.getAdapter().withOnPreClickListener(new FastAdapter.OnClickListener<IDrawerItem>() {
            @Override
            public boolean onClick(View v, IAdapter<IDrawerItem> adapter, IDrawerItem item, int position) {
                if(item instanceof ExpandableDrawerItem) {
                    result.getAdapter().collapse();
                }
                return false;
            }
        });
```

**Comment by mikepenz** [comment]
I will evaluate this as an addition to the `FastAdapter` (https://github.com/mikepenz/FastAdapter/issues/79)

It is already possible if you use the provided APIs of the `FastAdapter`

**Comment by fliespl** [comment]
Thanks. I will go with below workaround for now.

```
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        if (drawerItem != null) {
                            Intent intent = null;

                            if(drawerItem instanceof ExpandableDrawerItem) {
                                boolean expanded = ((ExpandableDrawerItem) drawerItem).isExpanded();

                                if(expanded) {
                                    for(int expandedPosition : result.getAdapter().getExpandedItems()) {
                                        if(expandedPosition != result.getPosition(drawerItem)) {
                                            result.getAdapter().collapse(expandedPosition);
                                        }
                                    }
                                }
                            }

```

**Comment by mikepenz** [comment]
@fliespl it's no workaroung ;). It is a proper implementation, and if I decide to implement it into the `FastAdapter` I will go with a similar code

**Comment by fliespl** [comment]
I might be wrong, but my guts tell me that collapsing should happen on adapter before onItemClick is triggered. 

In my example I collapse items "after" new item is already expanded (internally) - notice `if(expanded)` logic.

**Comment by mikepenz** [comment]
@fliespl you can hook onto the `onPreClickListener` of the `FastAdapter`
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L95

```java
result.getAdapter(). withOnPreClickListener(...)
```
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L222

**Comment by fliespl** [comment]
Mike - sure, but it didn't work in my tests (new item was not expanded).

It is probably because onPreClickListener changed current drawer item position internally and OnClick event was triggered with the old one (which is not there).

**Comment by mikepenz** [comment]
@fliespl oh yeah I think you are right. 
I have created this feature request on the `FastAdapter` repo. Let me see how it makes the most sense ;)
