### ISSUE TITLE
MaterialNavigationDrawer to the gradle lib

### ISSUE THREAD

**Issue by danielgomezrico** [mikepenz/MaterialDrawer#111]
Can you add please the MaterialNavigationDrawer to the gradle lib?

**Comment by mikepenz** [comment]
@danielgomezrico what do you mean?

**Comment by R0ns3n** [comment]
Just copy this part
```
compile('com.mikepenz.materialdrawer:library:2.5.3@aar') {
        transitive = true
 }
```
into your gradle file.

**Comment by mikepenz** [comment]
I'll close this for now. I'm still not sure what is meant by the issue. There's a gradle dependency as @R0ns3n answered.
