### ISSUE TITLE
Problem with CoordinatorLayout

### ISSUE THREAD

**Issue by carmas123** [mikepenz/MaterialDrawer#1111]
If I use CoordinatorLayout I got this problem:
![error](https://cloud.githubusercontent.com/assets/6574219/13899884/0bb72486-edf9-11e5-9c20-f42ee26965e3.jpg)

**Comment by carmas123** [comment]
This is my activity XML:

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <android.support.design.widget.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:theme="@style/AppTheme.AppBarOverlay">

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="?attr/colorPrimary" />

        </android.support.design.widget.AppBarLayout>

        <FrameLayout
            android:id="@+id/left_drawer"
            xmlns:android="http://schemas.android.com/apk/res/android"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <FrameLayout
                android:id="@+id/fragmentContainer"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

        </FrameLayout>
    </LinearLayout>


</android.support.design.widget.CoordinatorLayout>

```

ad I use it with this code:

 ```
       mDrawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(mToolbar)
                .withRootView(R.id.left_drawer)
                .withActionBarDrawerToggle(true)
                .withActionBarDrawerToggleAnimated(true)
                .withOnDrawerListener(new Drawer.OnDrawerListener() {
                    @Override
                    public void onDrawerOpened(View drawerView) {

                    }

                    @Override
                    public void onDrawerClosed(View drawerView) {

                    }

                    @Override
                    public void onDrawerSlide(View drawerView, float slideOffset) {

                    }
                })
                .build();

```

**Comment by mikepenz** [comment]
@carmas123 please see the `CollapsingToolbar` example as reference
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CollapsingToolbarActivity.java

**Comment by carmas123** [comment]
The problem is not this!
All work fine if I do not use "withRootView" (also without CoordinatorLayout) I got this problem...
This problem is with margin.

**Comment by mikepenz** [comment]
@carmas123 the drawer does not set any margins. 

Just to get a bit more of an idea what you are trying. Why do you provide the `withRootView`? The `DrawerLayout` should be in the root, (which is the case automatically) and the `CoordinatorLayout will be a child from it. You can see this is working in the sample app

**Comment by carmas123** [comment]
I think that the rootView will need to design a tablet and smartphone layouts. Or not?

**Comment by carmas123** [comment]
If I add
`android:layout_marginTop="32dp"`
in FrameLayout (that make as rootView), all work :)

**Comment by carmas123** [comment]
This is the result:

WITH MARGIN TOP:
![with](https://cloud.githubusercontent.com/assets/6574219/13903811/017a084e-ee8a-11e5-9cf5-972b3078cf8d.jpg)

WITHOUT:
![without](https://cloud.githubusercontent.com/assets/6574219/13903812/08b5cd14-ee8a-11e5-8e76-c53b5d5c7794.jpg)

**Comment by carmas123** [comment]
The best value are 31dp in Portrait and 22dp in landscape

**Comment by mikepenz** [comment]
@carmas123 you want your drawer below the `Toolbar` this is something completely different. For this you should check the `CustomContainerActivity` of the sample app:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java

**Comment by carmas123** [comment]
Ok now it work but with this I cannot use CoordinatorLayout...however it's ok :) thanks
