### ISSUE TITLE
Strange language change behavior with latest support libraries

### ISSUE THREAD

**Issue by androideveloper** [mikepenz/MaterialDrawer#1115]
Hi Mike,

I have a very very strange behavior after update to 5.1.3.
I have 2 languages in my app, that user can set. 
After update to mentioned version there is an issue: when I rotate device, language in my list becomes mixed (some of items of MiniDrawer are in English,some of them in Armenian).
It seems that this bug comes from support library 23.2.1.
Can you please help to identify it?

I have created sample app, that uses NavigationDrawer(from design library) for first page and MaterialDrawer(your library) for second page. This bug is present only in second page.

Screenrecord of bug: https://youtu.be/Ifn6rpC99zM
Source code:  https://www.dropbox.com/s/8q1jf0fx3l44m0p/TestLanguageIssue.zip?dl=0

**Comment by mikepenz** [comment]
@androideveloper I can't really fix or provide support for the support libraries from Google 

I recommend that you just try to exclude the support libraries of the drawer in your project and go back to a previous version of the support libraries

**Comment by androideveloper** [comment]
@mikepenz I haven't said that you could fix Google's library)) In my example, I have native navigation drawer and navigation drawer from your library, both use the same version of support library. But this bug is present only in your library. So I want to understand if this library bug or Google bug?

**Comment by mikepenz** [comment]
@androideveloper ok fine. will have a closer look later

**Comment by androideveloper** [comment]
@mikepenz ok,great! thanks!

**Comment by mikepenz** [comment]
@androideveloper might also be related to `android:configChanges="orientation|screenSize"` in your manifest

**Comment by androideveloper** [comment]
I don't want my activity to be recreated after rotate so i hav set this flag. This flag was always present in my project and worked fine. I think that there is an issue with support library after update, but don't know exactly the one and how to describe it. As I know there are some changes in 23.2.0 or 23.2.1 related to Resources, someone mentioned that this class is now singleton.

**Comment by mikepenz** [comment]
@androideveloper really weird. I just want to note that you may want to change this as activity recreation is the prefered solution and is fully supported (including saving the state) inside the MaterialDrawer. 

I still have to close this as I have no possibility inside this project to solve your issue. 

You can exclude the support libraries from the drawer via this:
http://stackoverflow.com/questions/20008525/best-way-to-manage-android-gradle-dependencies/20016971#20016971

**Comment by androideveloper** [comment]
@mikepenz Ok, I know. For now, I have to use previous version of library. I have created an issue on Android project site. [https://code.google.com/p/android/issues/detail?id=204708](url)

**Comment by androideveloper** [comment]
I can confirm that this bug is fixed in version  23.3.0 of support library.
