### ISSUE TITLE
Recommended way of handling onBackPressed and Menu selection

### ISSUE THREAD

**Issue by fliespl** [mikepenz/MaterialDrawer#1116]
Hi again Mike,
I am curious - what is the recommended way to keep menu selection and fragment changes (i.e. onBackPressed) in sync?

Currently it doesn't work out of the box (or I don't know how to use it properly).

Would you recommend mapping fragments to specific drawer items identifier (and triggering `result.setSelection(id, false);` or some other way?

**Comment by mikepenz** [comment]
@fliespl the drawer can't handle this, as it is not aware (and should not be aware) of the current defined fragment and so on. 

So the optimal solution is to have each item mapped to a specific fragment via an `identifier`. If you go back you should just set the selection again. 

Most devs handle the complete navigation and fragment commiting via the `onItemClick` event. So you can even just write

`result.setSelection(identifier)` inside your onBack method which will then trigger the listener and set back the correct fragment
