### ISSUE TITLE
Drawer Header and translucent Status Bar

### ISSUE THREAD

**Issue by otteros** [mikepenz/MaterialDrawer#1117]
If I set a AccountHeader with
```java
accountHeaderBuilder.withDrawer(getDrawer());
```
I get the following Image:

![drawer](https://cloud.githubusercontent.com/assets/17988397/13926867/829f9d3a-ef8e-11e5-840e-eafba700814e.png)

I fixed the problem with:
```
getDrawer().getRecyclerView().setPadding(getDrawer().getRecyclerView().getPaddingLeft(), 0, getDrawer().getRecyclerView().getPaddingRight(), getDrawer().getRecyclerView().getPaddingBottom());
```
![drawer2](https://cloud.githubusercontent.com/assets/17988397/13926954/eef8b804-ef8e-11e5-8f01-91107b62f83b.png)

**Comment by mikepenz** [comment]
@otteros please just follow the sample app. Build the `AccountHeader` and then provide it to the `DrawerBuilder`

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L116

**Comment by otteros** [comment]
My app design don't allow me to do that.
I expect, that if I set a Header after the Drawer is build, it is displayed as expected.

**Comment by mikepenz** [comment]
@otteros ok. So no header by default, just at a later time?

So I think your current solution is fine.

**Comment by otteros** [comment]
I write a library for some projects and they can add a header at build time of the drawer by implementing an `onDrawerBuild(DrawerBuilder)` Method. But I don't want to use it in the second library that adds Account management (to prevent, that the using project must call its super implementation).
I think my solution for this problem ist only a hotfix (found by browsing the source). If it is possible to add/change a Header after build time it should be presented as expected and not with a padding at the top.

**Comment by mikepenz** [comment]
You write a open source library wrapping around the `MaterialDrawer`? or company specific?

I will have a closer look if it is save to add it to the lib itself

**Comment by otteros** [comment]
It should be save to add this, it is just 1 line to add in `Drawer.setHeader(View, boolean, boolean)`.
At the current time the library (and projects that us it) is only for myself, but eventually (if they accept it) it is for use in an organization like a fire department.

**Comment by mikepenz** [comment]
will be in v5.1.6
