### ISSUE TITLE
Use with  fragment stack and back button

### ISSUE THREAD

**Issue by carmas123** [mikepenz/MaterialDrawer#1118]
Hi, I want to use the Drawer in my first fragment (Home) and show the back button when the second or other fragment is visible.
I show the back button with this code:

`mDrawer.getActionBarDrawerToggle().setDrawerIndicatorEnabled(isFirstFragment());`

and it work, but when I click on the back button the drawer is showed :(

**Comment by mikepenz** [comment]
Please see the following:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/AdvancedActivity.java#L174

And to get back to the hamburger:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/AdvancedActivity.java#L179

**Comment by carmas123** [comment]
Ok, you are the best, all work.
But can I have the hamburger to arrow animation or not?

**Comment by mikepenz** [comment]
I don't think this is possible with the `ActionBarDrawerToggle` from the support libs
