### ISSUE TITLE
Sample code illustrating SwitchDrawerItem and Shared Preferences

### ISSUE THREAD

**Issue by CeJienAJPC** [mikepenz/MaterialDrawer#1119]
Hi Mike,
I know this is quite basic to ask you for. I have been trying to use SwitchDrawerItem with Shared Prefs. Unfortunately, I am confused and not able to proceed.

Some sample code/reference would be of great help

**Comment by mikepenz** [comment]
@CeJienAJPC I'm not quite sure what's confusing here. 

You create the item with the listener:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L141

Inside the listener you update the `SharedPreference`
(The  listener) https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L227

and during the activity creation you just read the value of the preference, and set the current state to the item.
