### ISSUE TITLE
Request - Sample Apk

### ISSUE THREAD

**Issue by TurKurT656** [mikepenz/MaterialDrawer#112]
Hi
TnQ for this great library. I loved it
Can u upload the apk of sample app?

**Comment by mikepenz** [comment]
@TurKurT656 thank you. If you just want to see how it looks like in action you can try wall:splash. else just download the project and run it ;)

Will upload the apk later today :D Makes sense for quick testing.

**Comment by mikepenz** [comment]
* is now added to the release https://github.com/mikepenz/MaterialDrawer/releases

**Comment by TurKurT656** [comment]
TnQ Bro, You Are Awesome :+1:

**Comment by mikepenz** [comment]
@TurKurT656 no problem ;)
