### ISSUE TITLE
Custom item to mini drawer

### ISSUE THREAD

**Issue by dstd** [mikepenz/MaterialDrawer#1120]
I have a custom item in the drawer, but it is not visible in the mini drawer.
I've looked into a control flow of the mini drawer and looks like it can handle only PrimaryDrawerItem, SecondaryDrawerItem and ProfileDrawerItem, with no support for customization. 

Is there any chance to put the custom item into the mini drawer?
Thanks

**Comment by mikepenz** [comment]
you can follow more or less the following guide: https://github.com/mikepenz/MaterialDrawer/issues/1090#issuecomment-195913322

**Comment by dstd** [comment]
@mikepenz thanks for pointing to this issue, but I can't see anything about instantiation of such `MyMiniDrawer`. I found two places where instance of `MiniDrawer` is creating - [in Drawer.getMiniDrawer()](https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L179) and [in DrawerBuilder.buildView()](https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1458). While first method is quite simple and looks good to override, the second one contains some internal logic, and I'm confused about it.

**Comment by mikepenz** [comment]
@dstd oh missed that the `MiniDrawer` in the sample is created through the  `DrawerBuilder` 

Here's the previous source of the `MiniDrawerActivity` showing the manual creation of the `MiniDrawer`

https://github.com/mikepenz/MaterialDrawer/blob/fba4d8e2fa44eef392195573630c83f1f73c52ca/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java

**Comment by dstd** [comment]
@mikepenz yep, it works. thanks!
