### ISSUE TITLE
Question: Badge a textview from my app

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/MaterialDrawer#1121]
Hi, my question is, is posible to use the clases from the materialdrawer to create a badge in a textview from my app ?, is a textview in the activity.

Thanks.

**Comment by mikepenz** [comment]
@seba123neo yeah why not?

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/utils/BadgeDrawableBuilder.java

**Comment by seba123neo** [comment]
Works perfect, Thanks Mike !!!!
