### ISSUE TITLE
Top most Item on the drawer is not visible

### ISSUE THREAD

**Issue by smtrz** [mikepenz/MaterialDrawer#1122]
Hi,
I am facing a weird issue,the top most item of the drawer is not visible on Samsung galaxy note3 and note4 .
any idea why this might be happening   ?

**Comment by mikepenz** [comment]
@smtrz do you have an `ActionBar` instead of a `Toolbar` which might overlap?

**Comment by smtrz** [comment]
yes i am using an actionbar.
But the drawer is fine in all other screen sizes such as 4.0,4.3,4.7,5.0 inches

**Comment by mikepenz** [comment]
@smtrz the problem is that it seems like the `ActionBar` overlays the drawer. So it also seems like your content moves below the `ActionBar` somehow? 

The provided code shouldn't have any affect on the `ActionBar`. 

Have you checked this sample:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/ActionBarActivity.java

**Comment by smtrz** [comment]
@mikepenz 
Mike,
I have used the same snippet from the sample link.
the only difference is i am displaying it below status bar.
` result = new DrawerBuilder()
                .withActivity(this)
                .withTranslucentStatusBar(false)
                .withDisplayBelowStatusBar(true)
                .withActionBarDrawerToggle(false)`

**Comment by mikepenz** [comment]
@smtrz and your theme?

**Comment by smtrz** [comment]
@mikepenz 
` <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>`

**Comment by mikepenz** [comment]
@smtrz could you please try the following theme:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/AndroidManifest.xml#L31

Please also try the sample app if it gives you the same exception?

**Comment by smtrz** [comment]
@mikepenz No luck !

**Comment by smtrz** [comment]
First Item of the Drawer is never shown.

**Comment by mikepenz** [comment]
@smtrz so it is also wrong in the sample app on your device?

**Comment by mikepenz** [comment]
@smtrz otherwhise I highly recommend that you switch to the `Toolbar` which is way better, and allows far more customizations. 

If this is no option, please confirm this also happens in the sample, if not please provide a smalls maple which allows me to debug the issue.
