### ISSUE TITLE
Embedded list has extra top margin

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/MaterialDrawer#1123]
Hi, when i embedded a drawer in a Framelayout works perfect, the list items shows perfect (without the header, only the list items), but it has a extra top margin, it has a margin like 16dp or so... 

How eliminate the extra margin ?

Thanks.

**Comment by mikepenz** [comment]
@seba123neo what do you mean with embedded drawer? If you have a different container just see the `CustomContainerActivity`
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java

**Comment by seba123neo** [comment]
Yes, i embedded the drawer inside a framelayout, like your example in the activity EmbeddedDrawerActivity.java, works fine.

in my layout only i have a toolbar and the framelayout below.

but when i remove the header from the drawer, the first item of the list is far away from the toolbar like "16dp" or some extra margin.

thanks.

**Comment by mikepenz** [comment]
@seba123neo please post a screenshot

**Comment by seba123neo** [comment]
Look the space between the toolbar and the first item.

**Comment by seba123neo** [comment]
![2016-03-23 20 19 48](https://cloud.githubusercontent.com/assets/9873666/14003937/39014c66-f135-11e5-8b4c-53a4507e6686.jpg)

Look the space between the blue toolbar and the first item

**Comment by mikepenz** [comment]
@seba123neo oh ok seems like you have an app similar to the `EmbeddedDrawerActivity`. I have tested it with a removed `Header` and this then requires also the following line:
```java
.withDisplayBelowStatusBar(false)
```


Resulting in:
```java
result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withTranslucentStatusBar(false)
                .withDisplayBelowStatusBar(false)
                .addDrawerItems(
                        ...
                )
                .withSavedInstance(savedInstanceState)
                .buildView();
```

**Comment by seba123neo** [comment]
Thanks mike, works perfect.
