### ISSUE TITLE
Account header profiles

### ISSUE THREAD

**Issue by silaskaggwa** [mikepenz/MaterialDrawer#1124]
How do I disable the AccountHeader from being clickable. I want to disable showing the list of profiles when someone clicks on the account header. I also want to remove the down pointing arrow in the account header

**Comment by mikepenz** [comment]
@silaskaggwa if you just have one account you can do the following:
```java
withSelectionListEnabledForSingleProfile(false)
```

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L547
