### ISSUE TITLE
Navigation drawer toolbar

### ISSUE THREAD

**Issue by readbeard** [mikepenz/MaterialDrawer#1126]
Hi,
when adding (following your guidelines and your files inside repository) a navigation drawer  the toolbar i defined in my activity xml is shown under the status bar, as you can see in the screen. I'm also using your other library, Fastadapter.

I tried to see if your answers on closed issues on in the FAQs could solve this but i couldn't find a fix. Can you please help me?
![device-2016-03-25-130615](https://cloud.githubusercontent.com/assets/6012118/14043958/4d124df6-f282-11e5-98af-0a2845bfeb98.png)

**Comment by mikepenz** [comment]
@readbeard which theme are you using?

**Comment by readbeard** [comment]
The one you suggested in the other library:
```xml
<style name="CustomTheme" parent="MaterialDrawerTheme.Light">
        <!-- CAB :D -->
        <item name="windowActionModeOverlay">true</
</style>
```
I also tried to change this with some of the ones you suggest in the README of this repo (e.g.: MaterialDrawerTheme.Light.ActionBar) but it crashes...

**Comment by mikepenz** [comment]
@readbeard and how do you setup the drawer? as you can see in the sample app the `Toolbar` is not behind the `StatusBar`. 

Which layout do you have? Perhaps you have a `fitsSystemWindows` defined wrong..

**Comment by readbeard** [comment]
The layout of my activity is the following. I didn't define a layout for the drawer. I don't know, i'm not using firsystemwindows and the code looks very similar to the one of your sample...
```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center">

    <android.support.v7.widget.Toolbar
        android:id="@+id/multiselect_toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        android:elevation="4dp" />

    <RelativeLayout
        android:id="@+id/frame_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/multiselect_toolbar">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/multiselect_recyclerview"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </RelativeLayout>
</RelativeLayout>
```

**Comment by mikepenz** [comment]
@readbeard so how do you setup the drawer? the layout seems fine, the theme is fine.

**Comment by readbeard** [comment]
The code is the following...i tried to add/remove some ```.withXXX()``` methods but nothing. As you can see from the screen, it seems the drawer starts from the beginning of the screen (now that there is no header it was clearer to me)
![device-2016-03-25-150733](https://cloud.githubusercontent.com/assets/6012118/14045540/f4c5a66e-f292-11e5-8a95-9ae87a02ac23.png)

```java
 Drawer result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withSavedInstance(savedInstanceState)
                .withDisplayBelowStatusBar(false)
                .withTranslucentStatusBar(false)
                .addDrawerItems(
                        item1,
                        new DividerDrawerItem(),
                        item2,
                        new SecondaryDrawerItem().withName("secondary item")
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        // do something with the clicked item :D
                        return true;
                    }
                })
                .build();
```

**Comment by mikepenz** [comment]
You don't need those:
```java
.withDisplayBelowStatusBar(false)
.withTranslucentStatusBar(false)
```

Can you use a `TranslucentStatus` theme?
```xml
MaterialDrawerTheme.Light.TranslucentStatus
```

**Comment by readbeard** [comment]
Ok, now it's a little bit better, but it's not fixed yet. In fact, the toolbar is still under the status bar while the drawer is ok:
![device-2016-03-25-151518](https://cloud.githubusercontent.com/assets/6012118/14045671/067827f0-f294-11e5-9491-d115300a5702.png)

**Comment by mikepenz** [comment]
ok weird enough. 

Which version of the drawer do you use?

**Comment by readbeard** [comment]
the one you suggest in the README: `com.mikepenz:materialdrawer:5.1.6@aar`

**Comment by mikepenz** [comment]
@readbeard ok so the latest version. 
Could you provide a zip with a cleaned sample so i can debug and find the configuration issue?

**Comment by mikepenz** [comment]
@readbeard without the drawer in your activity will the `Toolbar` also move below the `StatusBar`? 

Otherwhise this needs a small sample app I can test and debug in. So I can provide you with the solution. 

This is no bug as far as I can tell as in the sample app everything is fine.

**Comment by readbeard** [comment]
I found that, if i use a custom layout for the drawer identical to yours, in which the flag `fitsSystemWindows` is set to false the problem is fixed but there is another one with the color of the status bar, as you can see from the screen. The code of the layout is the following (just edited the last line of file `material_drawer.xml` ):
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/custom_drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="false" />
```

![statusbar](https://cloud.githubusercontent.com/assets/6012118/14105301/4a79a272-f59a-11e5-80e8-eb0a3d80487a.png)

**Comment by mikepenz** [comment]
@readbeard no the `fitsSystemWindows` is fine. 
Could you please just provide a small sample app with the issue on your side so I can debug it for you. The issue does not occur in the sample app so something else is causing it

**Comment by readbeard** [comment]
Hurrah! Fixed it! I set the flag `witTranslucentStatusBar(false)` when creating the navigation drawer object. Well, it now works fine, but i can't understand why i have to use my custom drawer layout only to change that `fitsSystemWindows` line...Isn't there a way to set it manually at execution time? 
By the way, thanks for your help and availability :+1: :) ! Hope it will be useful for further releases

**Comment by mikepenz** [comment]
@readbeard to be honest, those steps should not be necessary. (And aren't necessary in the sample app, and also not in the apps I have developed with the MaterialDrawer) 

If you find time for the sample it would be great, I would really love to find out why it has a different behavior than in the samples...

Thanks.

**Comment by RafaG** [comment]
I think I have the same problem. Maybe I made something wrong. Only in Android 6 is working incorrectly, for other versions is Ok.
![captura](https://cloud.githubusercontent.com/assets/10325478/15801258/fdd42494-2a8f-11e6-9cb1-67c96be02dd9.PNG)
I am using "Theme.AppCompat.Light.NoActionBar" and "withTranslucentStatusBar(false) & withActionBarDrawerToggle(true)"

**Comment by mikepenz** [comment]
@RafaG what do you want to achieve? The picture shows exactly what you have configured. Drawer below the `StatusBar` as you have set `withTranslucentStatusBar(false)`

**Comment by RafaG** [comment]
Sorry, I think I don't explain me well. Please, compare the original image and the imagen show by drawer. In Android < 6 I see the image complete below the status bar, in Android 6 is not show complete.
![taxi_alerta_320x180](https://cloud.githubusercontent.com/assets/10325478/15802374/f706fa22-2aaf-11e6-9748-f550526a25e9.jpg)

**Comment by RafaG** [comment]
Anyone have an idea what I am doing wrong?

**Comment by mikepenz** [comment]
@RafaG just tried your sample for a while, but saw that it is just a module. Can you provide a whole project so I can open it with Android Studio?

**Comment by RafaG** [comment]
I send a complete project, I'll resend in a few minutes. Thanks!

**Comment by mikepenz** [comment]
@RafaG ok I checked it. In general the `AccountHeader` or all `Header`s go below the `StatusBar` this comes from the `fitsSystemWindow`s flag. (And also forced here: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerUtils.java#L239) 
In general this is fine 99% because people have headers which can be behind the `StatusBar` 

So as this is not the case in your application you have the easy option to just call:
```java
drawer.getRecyclerView().setPadding(drawer.getRecyclerView().getPaddingLeft(), activity.getResources().getDimensionPixelSize(R.dimen.materialize_statusbar), drawer.getRecyclerView().getPaddingRight(), drawer.getRecyclerView().getPaddingBottom());
```
at the end of your `MiDrawer` ctor. This will add the needed padding at the top of the `RecyclerView`. Please also make sure that you wrap it in a `if` to just be apply it for devices starting with Android 6.0.0

**Comment by RafaG** [comment]
@mikepenz Thanks for your support, now I see my image below status bar equal in all platforms, ¡Great!. Don't you think should be an improvement for next version of Material Drawer? If I remember well, in previous versions of Material Drawer it works ok.
