### ISSUE TITLE
Using VectorDrawableCompat for icons

### ISSUE THREAD

**Issue by fncapps** [mikepenz/MaterialDrawer#1127]
Is there any chance of using `VectorDrawableCompat` for drawer icons instead of drawables?

**Comment by mikepenz** [comment]
@fncapps as you can provide `Drawable`s yes. :D

**Comment by fncapps** [comment]
Could you show me how to do it with a simple example please?

**Comment by mikepenz** [comment]
I don't know what's the issue here. Just pass the `VectorDrawableCompat` as it `extends Drawable` 

Getting a `VectorDrawableCompat` is nothing lib specific

**Comment by fncapps** [comment]
You are right, I was doing something wrong. I've solved the problem.
Thanks!
