### ISSUE TITLE
Account header does not select the right profile

### ISSUE THREAD

**Issue by maxoumime** [mikepenz/MaterialDrawer#1128]
Hey guys !

First of all, nice work with this library, really easy to use it !

But I'm having an issue with the AccountHeader, when I select a profile in the dropdown list, it isn't chosen. See the gif right after.
![drawer_profile_change_bug](https://cloud.githubusercontent.com/assets/3897798/14059042/3e82891a-f334-11e5-9d65-987b76848977.gif)

I tried to force change the active profile, but it didn't work.

```java
final AccountHeaderBuilder headerResultBuilder = new AccountHeaderBuilder()
      .withActivity(this)
      .withTranslucentStatusBar(true)
      .withHeightPx(UIUtils.getActionBarHeight(this))
      .withAccountHeader(R.layout.drawable_header)
      .withTextColor(Color.BLACK)
      .withTextColorRes(android.R.color.white)
      .withProfileImagesVisible(true)
      .withOnlyMainProfileImageVisible(true)
      .withOnlySmallProfileImagesVisible(true)
      .withThreeSmallProfileImages(false)
      ;

int identifier = 100;
for (Item item : items) {
    headerResultBuilder.addProfiles(
            new ProfileDrawerItem()
                    .withIdentifier(i++)
                    .withName(item.getName())
    );
}

headerResultBuilder.addProfiles(
    new ProfileDrawerItem()
            .withName(getResources().getString(R.string.add_account))
            .withIdentifier(9000)
            .withIcon(new IconicsDrawable(this, GoogleMaterial.Icon.gmd_add).actionBar().paddingDp(5).colorRes(R.color.material_drawer_primary_text))
            .withSelectable(false)
);

headerResultBuilder.withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
    @Override
    public boolean onProfileChanged(View view, IProfile profile, boolean current) {
        if (profile.getIdentifier() == 9000) {
            startActivity(new Intent(MyAwesomeActivity.this, AddAccountActivity.class));
        }
        return true;
    }
});
```

I am using the latest version of MaterialDrawer (5.1.6).

Do you have any idea of why I get this behaviour ?

Thanks !

**Comment by mikepenz** [comment]
@maxoumime I can't reproduce this in the sample app. Could you please send me a small sample app (just remove all the code not issue related) so I can debug this in Android Studio?

**Comment by maxoumime** [comment]
I made a small app reproducing the error (you will have to slide left to right because I didn't implemented the "open" button).
[MaterialDrawerError.zip](https://github.com/mikepenz/MaterialDrawer/files/190457/MaterialDrawerError.zip)

**Comment by mikepenz** [comment]
@maxoumime oh it seems it is caused by the following line:
```
.withOnlySmallProfileImagesVisible(true)
```

Just remove it. I will have a closer look why this is causing such a weird behavior, later today

**Comment by maxoumime** [comment]
Indeed ! Now it works great thanks @mikepenz  ! :D
