### ISSUE TITLE
Can you put a Jar file too?

### ISSUE THREAD

**Issue by yooneskh** [mikepenz/MaterialDrawer#1129]
Hi.

Yes i know gradle is the thing for dependency management and such, but can you please put the jar file of this library too? there are circumstances that it can help a lot.

Thank you very much. ^_^

**Comment by mikepenz** [comment]
@yooneskh no not possible. **JAR**s can't contain the ressources needed by this library. This is why `Android` has created the special **aar** archive's which contain styles, ressources etc.. Sorry for this.

**Comment by yooneskh** [comment]
Huh, good to know what aar is for. ^_^ thank you for this.

but i have seen that it is possible to make aar files and reference them locally, as in calligraphy library. 
https://github.com/chrisjenx/Calligraphy
http://kevinpelgrims.com/blog/2014/05/18/reference-a-local-aar-in-your-android-project/

and i have done it for calligraphy myself. it would be very nice if you could make a local aar build of your library for local references. 

thank you very much again.

**Comment by mikepenz** [comment]
You can just download it from maven central yourself: http://search.maven.org/#artifactdetails%7Ccom.mikepenz%7Cmaterialdrawer%7C5.1.6%7Caar

**Comment by yooneskh** [comment]
Thank you!
