### ISSUE TITLE
getDrawerItem return null

### ISSUE THREAD

**Issue by dexion** [mikepenz/MaterialDrawer#1131]
`getDrawerItem` return `null` when I try get drawer item by identifier from sticky drawer items group (which at the bottom of whole drawer). Getting item from srolled section of drawer return right item.

**Comment by mikepenz** [comment]
@dexion `getDrawerItem` does not return items from the `StickyFooter` as those are not managed by the `Adapter` so it can't find those. The `StickyFotter` items are managed manually within an additional section at the bottom below the `RecyclerView` 

You should keep a reference to those so you can update them later.
