### ISSUE TITLE
How can I implement Swipe Items for more than one action on a item?

### ISSUE THREAD

**Issue by truonguit2010** [mikepenz/MaterialDrawer#1133]
Hi all,

How can I implement Swipe Items for more than one action on a item?

I want a item look like this: https://github.com/daimajia/AndroidSwipeLayout

Thanks.

**Comment by mikepenz** [comment]
@truonguit2010 nothing `MaterialDrawer` related. 

Create your own `CustomDrawerItem` and add this functionality. 

Also this does not make sense in the `Drawer` as a drawer is already opened / closed by swipe. 



Questions regarding `CustomDrawerItem`s
https://github.com/mikepenz/MaterialDrawer/issues?utf8=%E2%9C%93&q=CustomDrawerItem
