### ISSUE TITLE
Two problems in API 21 and API 16

### ISSUE THREAD

**Issue by carmas123** [mikepenz/MaterialDrawer#1136]
Hi Mike and sorry for my always stupid questions, but I think that you library is very usefull and I want to use it...but I've always some problems to use it. :(

In API 21 I use "Theme.AppCompat.Light.NoActionBar" as base theme with my custom colors, and I've a simple XML for my activity like this:

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:minHeight="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        app:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/left_drawer"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/toolbar">

        <FrameLayout
            android:id="@+id/fragmentContainer"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </FrameLayout>

</RelativeLayout>
```

the problem is this: 
![api21](https://cloud.githubusercontent.com/assets/6574219/14109645/50a0198c-f5c3-11e5-8698-6b547b7a205d.jpg)

in API 16 with MaterialDrawer I've this problem:
![api16](https://cloud.githubusercontent.com/assets/6574219/14109665/6fc20028-f5c3-11e5-9da7-414b5d2a1115.jpg)

please help me, I'm try to solve it for some days :(

**Comment by carmas123** [comment]
I solved the first problem (API 21) with this:
```

    public int getStatusBarHeight() {
        int result = 0;
        int resourceId = getResources().getIdentifier("status_bar_height", "dimen", "android");
        if (resourceId > 0) {
            result = getResources().getDimensionPixelSize(resourceId);
        }
        return result;
    }

```

by setting the Support Toolbar padding by code like this:
` mToolbar.setPadding(0, getStatusBarHeight(), 0, 0);`

**Comment by mikepenz** [comment]
@carmas123 this should not be necessary. 

Have you checked out the sample app? I do not have anything like this included.

**Comment by carmas123** [comment]
I've see it but I try all combination for 2 days :( 
this is my code:

```
        mDrawer = new DrawerBuilder()
                .withActivity(this)
                .withRootView(R.id.left_drawer)
                .withToolbar(mToolbar)
                .withDisplayBelowStatusBar(false)
                .withActionBarDrawerToggle(true)
                .withActionBarDrawerToggleAnimated(true)
                .withSavedInstance(savedInstanceState)
                .withOnDrawerNavigationListener(new Drawer.OnDrawerNavigationListener() {
                    @Override
                    public boolean onNavigationClickListener(View clickedView) {
                        // Gestione onBack
                        onBackPressed();
                        return true;
                    }
                })
                .withOnDrawerListener(new Drawer.OnDrawerListener() {
                    @Override
                    public void onDrawerOpened(View drawerView) {
                        isDrawerOpened = true;
                    }

                    @Override
                    public void onDrawerClosed(View drawerView) {
                        isDrawerOpened = false;
                    }

                    @Override
                    public void onDrawerSlide(View drawerView, float slideOffset) {

                    }
                })
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("CIAO").withIdentifier(1)
                )
                .build();
```

**Comment by mikepenz** [comment]
Do you have the `fitsSystemWindows` in your layout? 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/activity_sample_custom_container_dark_toolbar.xml#L5

**Comment by mikepenz** [comment]
@carmas123 you also should depend on one of the `MaterialDrawer` themes (as described in the README) those also depend on the Appcompat theme

**Comment by mikepenz** [comment]
You might also provide a small sample showcasing the issue so I can debug it

**Comment by carmas123** [comment]
I use `fitsSystemWindows`.
So, if you want I can send you all my project.

**Comment by mikepenz** [comment]
@carmas123 yeah just send a project showcasing the above issue you have. So I can have a look at it later today

**Comment by carmas123** [comment]
I've send an email to you

**Comment by mikepenz** [comment]
@carmas123 thanks i'll check it now

**Comment by mikepenz** [comment]
@carmas123 ok after a closer look at your application. Here's the proper solution (and it will also simplify things) to fix the first issue:

Use a proper theme provided by the `MaterialDrawer` as base:
```
<style name="AppTheme.Base" parent="MaterialDrawerTheme.Light.DarkToolbar">
```
No need for the API-21 theme, as we do not need a `TranslucentStatus` theme. This is automatically handled by the `DrawerLayout` and the `fitsSystemWindows` flag. 

Remove the `materializeNow()` method. You do not need this any longer. 
So you can also remove the `getStatusBarHeight()` method. 

For the second issue. 
Took around 100 hundred years to get an ARM emulator with API 16 running :D, but i can't reproduce the issue you show in your screenshot.

**Comment by carmas123** [comment]
:) you are the best...I try it now...for API 16 I use genymotion.

**Comment by mikepenz** [comment]
@carmas123 I do my best :D Weird. I used the original Android API 16 ARM emulator from Android.

**Comment by carmas123** [comment]
I've tested the API16 also on Android Emulator and the result is same:
![screenshot_20160331-131255](https://cloud.githubusercontent.com/assets/6574219/14174100/81dcb886-f742-11e5-91be-e930fd3e2bde.png)

**Comment by mikepenz** [comment]
@carmas123 how do you get it running in genymotion. It gives me an exception during installation because it is no ARM emulator, the same for Android Studio so I specially downloaded the ARM emulator (which is endless slow :D)

**Comment by carmas123** [comment]
I use Genymotion in Windows simply...do you use Windows, MacOSX or Linux to develop?
I use Genymotion Nexus S - 4.1.1 - API16 image.

**Comment by mikepenz** [comment]
I use MacOSX.

**Comment by mikepenz** [comment]
As discussed on skype. It works on a real device. And seems to be caused by a weird combination of the native libs and so on. 


Just in case someone has something similar. Here the `DrawerBuilder` defines the shadow for pre 21 devices
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1541

If you overwrite this drawable with an empty `.png` you can remove the shadow at all (and also the black bar)
