### ISSUE TITLE
openDrawer() not working

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/MaterialDrawer#1138]
Hi.
I am using mini drawer and i want to have the "big drawer" opened when i first start the activity, so im calling drawer.openDrawer() from onCreate(), but its not working - the drawer remain closed (im seeing the mini drawer).

tested on asus zenpad 10 running android 5.0.2.
using material drawer version 5.1.3

this is my code (this function is called from onCreate):

```java
    private void makeDrawer()
    {
        DrawerBuilder drawerBuilder = new DrawerBuilder();

        drawerBuilder.withActivity(this);

        //noinspection deprecation
        drawerBuilder.withSliderBackgroundColor(getResources().getColor(R.color.navyGrey));

        drawerBuilder.withCustomView(mCustomDrawerLayout);

        drawerBuilder.withFullscreen(true);

        drawerBuilder.withGenerateMiniDrawer(true);

        Drawer drawer = drawerBuilder.buildView();

        drawer.setSelection(-1, false);

        MiniDrawer miniDrawer = drawer.getMiniDrawer();

        Configuration config = getResources().getConfiguration();

        int firstWidth;

        int secondWidth;

        //sw720dp layouts
        if (config.smallestScreenWidthDp >= 720)
        {
            firstWidth = (int) UIUtils.convertDpToPixel(300, this);

            secondWidth = (int) UIUtils.convertDpToPixel(72, this);
        }

        //regular phone layout
        else
        {
            firstWidth = (int) UIUtils.convertDpToPixel(150, this);

            secondWidth = (int) UIUtils.convertDpToPixel(72, this);
        }

        Crossfader crossFader = new Crossfader()
                .withContent(findViewById(R.id.RelativeLayoutContainerActivityMain))
                .withFirst(drawer.getSlider(), firstWidth)
                .withSecond(miniDrawer.build(this), secondWidth)
                .build();

        miniDrawer.withCrossFader(new CrossfadeWrapper(crossFader));

        **drawer.openDrawer();**
    }
```

please help

**Comment by ZinoKader** [comment]
Try doing that in a onPostResume(), like so:

` @Override
    protected void onPostResume() {
        super.onPostResume();
        drawer.openDrawer();
    }`

**Comment by mikepenz** [comment]
@or-dvir you do `buildView()` which will just build a `view` for the drawer but will not add a `DrawerLayout` as `.build()` would do. 

You might want to do `crossFader.crossfade()`

**Comment by or-dvir** [comment]
@mikepenz i changed the last line from "drawer.openDrawer();" to "crossfader.crossfade()" but it's still not working - im still seeing the mini drawer and not the "big drawer".

i also tried "miniDrawer.getCrossFader().crossfade();" - not working.

maybe i need to write this line somewhere else in the code?

**Comment by mikepenz** [comment]
@or-dvir it will crossfade. It will need a bit a delay to crossfade if you want to do it in the `onCreate`

Here the following will help:
```java
new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                crossFader.crossFade();
            }
        }, 50);
```

**Comment by or-dvir** [comment]
@mikepenz not working :(
it's definitely being called though (i added a log entry) but the "big drawer" remains closed

**Comment by or-dvir** [comment]
i (almost) found a solution!

if i use "crossFader.getCrossFadeSlidingPaneLayout().openPane()", the drawer is opened.
however, it is empty! only if i start dragging the drawer, the views inside it become visible.

if after this line i add "crossfader.crossfade" it doesn't work at all - the drawer remains closed.

i thought i could try to invoke a method like "on touch event" or "on drag event" but i cant get it to work...

any thoughts?
