### ISSUE TITLE
Request/Proposal - set account header arrow (account_header_drawer_text_switcher) gravity to CENTER_VERTICAL

### ISSUE THREAD

**Issue by enginegl** [mikepenz/MaterialDrawer#114]
Screenshot from Gmail app attached:
![screenshot_2015-03-16-18-26-32](https://cloud.githubusercontent.com/assets/3976062/6669447/034ee642-cc0a-11e4-958d-e264cb222b9f.png)

ps. Awesome lib!

**Comment by mikepenz** [comment]
@enginegl haha just had a pull request doing this. Please read the conversation there :D. This is against the Google Material Design Guidelines ;). 

https://github.com/mikepenz/MaterialDrawer/pull/116

Further reading:
http://www.google.com/design/spec/patterns/navigation-drawer.html

**Comment by enginegl** [comment]
lol :D 
thanks)

**Comment by mikepenz** [comment]
(if you really want it to be centered you can overwrite the layout in your app :D )
