### ISSUE TITLE
temporarily disable drawer\miniDrawer?

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/MaterialDrawer#1141]
Hi!
i am using mini drawer and i was wondering if it is possible to **temporarily** hide it.

explanation:
in my activity i have a video view, and i would like to hide the mini drawer while the video is playing, and enable it again after the video finished playing.

i tried looking in the API/source code but i could not find any "setVisibility" (or similar) method.

is it even possible?

thanks!

**Comment by mikepenz** [comment]
@or-dvir the only solution woudl be that you hide (set the view to gone) which contains the `Crossfader`. The `Crossfader` is a `SlidingPaneLayout` and I am not sure if this allows it. 

maybe showing the video in fullscreen should be a separate layer or even a completely new activity?

**Comment by mikepenz** [comment]
@or-dvir if you really need it, you could theoretically do it with the following code:
```java
        SlidingPaneLayout.LayoutParams lp = (SlidingPaneLayout.LayoutParams) crossFader.getCrossFadeSlidingPaneLayout().getChildAt(0).getLayoutParams();
        lp.width = 0;
        crossFader.getCrossFadeSlidingPaneLayout().getChildAt(0).setLayoutParams(lp);

        lp = (SlidingPaneLayout.LayoutParams) crossFader.getCrossFadeSlidingPaneLayout().getChildAt(1).getLayoutParams();
        lp.rightMargin = 0;
        lp.leftMargin = 0;
        crossFader.getCrossFadeSlidingPaneLayout().getChildAt(1).setLayoutParams(lp);
```

**Comment by or-dvir** [comment]
> @or-dvir if you really need it, you could theoretically do it with the following code:
> 
> SlidingPaneLayout.LayoutParams lp = (SlidingPaneLayout.LayoutParams) crossFader.getCrossFadeSlidingPaneLayout().getChildAt(0).getLayoutParams();
> lp.width = 0;
> crossFader.getCrossFadeSlidingPaneLayout().getChildAt(0).setLayoutParams(lp);
> 
> lp = (SlidingPaneLayout.LayoutParams) crossFader.getCrossFadeSlidingPaneLayout().getChildAt(1).getLayoutParams();
> lp.rightMargin = 0;
> lp.leftMargin = 0;
> crossFader.getCrossFadeSlidingPaneLayout().getChildAt(1).setLayoutParams(lp);

THIS WORKS!
THANK YOU!
