### ISSUE TITLE
[MiniDrawer] ListView item can't change color text

### ISSUE THREAD

**Issue by tankvn** [mikepenz/MaterialDrawer#1143]
It is still #757575

I can change background, bold style but can't change color

Please help me!

**Comment by tankvn** [comment]
my build.gradle:
    compile 'com.android.support:appcompat-v7:24.0.0-alpha1'
    compile 'com.android.support:support-v4:24.0.0-alpha1'

Issue is fixed with downgrade to 23

**Comment by mikepenz** [comment]
@tankvn at the moment the `MaterialDrawer` is based on the support libs v23.2.1 and I assume that v24.0.0-alpha1 will cause conflicts. 

Until v24 is not final I can't support it, and you might have to exclude the support libraries on your own. 
http://stackoverflow.com/a/20016971/325479

(as additional info. v24.0.0-alpha1 is based on v23.2.0 which had really bad issues and it is not recommended at all to use it for any release build)
