### ISSUE TITLE
Transparent status bar issue in collaboration with MaterialDrawer

### ISSUE THREAD

**Issue by orcchg** [mikepenz/MaterialDrawer#1145]
![opaque_systembar_x](https://cloud.githubusercontent.com/assets/1728123/14204079/c007b05e-f812-11e5-874d-ddded3f2fc92.png)
![transparent_systembar_x](https://cloud.githubusercontent.com/assets/1728123/14204078/c0059f94-f812-11e5-8d19-56ec5c80befe.png)

There is still an issue with transparency of status bar. MaterialDrawer breaks the transparency.
This Activity uses "Theme.AppCompat.Light.NoActionBar" and "<item name="android:statusBarColor">#88000000</item>" (semitransparent colour, but it doesn't work for 100% transparent as well).

Options such as .withFullscreen(true) and / or .withTranslucentNavigationBarProgrammatically(false) do not help. I've faced the issue both in Activity using CollapsingToolbarLayout (CoordinatorLayout as a root + AppBarLayout + NestedScrollView) and in Activity with simple FrameLayout as a root. In both cases there is the issue. When I turn off the MaterialDrawer (simply not invoking .build() method on resulting DrawerBuilder), status bar becomes (semi)transparent as expected.

Could somebody please explain what kind of internal blocks in MD implementation could cause the issue? Thank You!

**Comment by mikepenz** [comment]
@orcchg starting with v5.x.x the `MaterialDrawer` no longer manages paddings or sets any UI flags to do so. Everything is now handled and managed from the Android built in flag `fitsSystemWindows` and is so forwarded to the different layouts. 

For a `CollapsingToolbar` there is also a sample activity:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CollapsingToolbarActivity.java

Showcasing how the CollapsingToolbar is handled.

**Comment by orcchg** [comment]
@mikepenz Thank You. I'm using 5.1.6 and checked MD works with cheesessquare application. I'm actually using fitsSystemWindows="true" on Coordinator and AppBarLayout, and this works well in case MD is absent. Something in MD forces such top margin on my layout.

One can remove fitsSystemWindows="true" from AppBarLayout still leaving it on CoordinatorLayout enabled, and this entails AppBarLayout to have top offset (24dp). One can scroll it vertically to collapse as usual and notice AppBarLayout's top border moves behind the translucent status bar. The CoordinatorLayout is in charge here.

On the other hand, omitting fitsSystemWindows="true" in CoodinatorLayout itself makes statusbar completely opaque and static, AppBarLayout does no longer move behind it and has a top margin (24dp) at beginning.

So, when I try to add MD to my environment, I've exactly the same behaviour as described above - when CoordinatorLayout has no fitsSystemWindows="true" attribute set. I guess something in MD implementation may intercept such CoodrinatorLayout's responsibilities ?

**Comment by orcchg** [comment]
I've figured out that the issue is caused with the following conditions. I have a the following XML layout for my Activity:

<DrawerLayout>
    <CoordinatorLayout> ... content of Activity ... </CoordinatorLayout>

    <FrameLayout /> - container for fragment
</DrawerLayout>

Note the FrameLayout with serves as a container for a fragment I add programmatically. In onCreate() of this fragment I actually build the Material Drawer (here I invoke withActivity(getActivity()). This actually causes the issue. When I create MD directly in the hosting Activity, everything is OK.

This is similar to StackOverflow [discussion](http://stackoverflow.com/questions/20822418/android-4-4-translucent-status-navigation-bars-fitssystemwindows-cliptopaddi).

Could You please advice something? Could we use MD within a programmatically added fragments? Thank You!

**Comment by mikepenz** [comment]
@orcchg can't you just build the drawer in the activity and fill it's items from within the fragment?

**Comment by mikepenz** [comment]
@orcchg any update?

**Comment by orcchg** [comment]
@mikepenz The issue is caused with a FrameLayout which acts as a root of the rest layout of the Activity. I have a BaseActivity class with overriden setContentView() method, which sets pre-defined layout which looks like:

<FrameLayout>

    *** Activity-specific layout is passed here ***
   
    <pre-defined content>

</FrameLayout>

My Activity has standard layout (with Coordinator + AppBar + CollapsingToolbar etc, as usual), but then it's view hierarchy is entirely added into wrapping root FrameLayout, which also has some component common to all Activities inheriting BaseActivity. But such 'wrapping' causes the issue with status bar transparency. When I do not wrap - everything is okay. But I have to provide common components to each Activity. I'm investigating the solution.

Thank You. No issue with your MD.
