### ISSUE TITLE
Pre - lollipop tint problem 

### ISSUE THREAD

**Issue by w3b5urf3r** [mikepenz/MaterialDrawer#1146]
On A PrimaryDrawerItem if i set a different icon for selected state  like this : 

```java
                .withName(R.string.drawer_list_offline_string)
                .withIcon(ContextCompat.getDrawable(context, R.drawable.drawableRes))
                .withSelectedIcon(ContextCompat.getDrawable(context, R.drawable.drawableRes2))
                .withIconTintingEnabled(true)
                .withIconColor(ContextCompat.getColor(context, R.color.color1)
                .withSelectedIconColor(ContextCompat.getColor(context, R.color.color2));
```

The tint works only for lollipop devices and above, it doesn't work for pre lollipop devices, although i can see whenever i'm switching from items in the drawer that the tint is visible on the selected drawable just for the very second i'm switching to another item. Not on the touch down event but on the touch UP event. 
Curious thing i tried to tint the drawable directly without using tint mode from the drawer and it still doesn't work for pre lollipop device in the drawer while this method perfectly works on other views. 
Ty

**Comment by mikepenz** [comment]
will be fixed in the next version
