### ISSUE TITLE
Custom Profile

### ISSUE THREAD

**Issue by denebchorny** [mikepenz/MaterialDrawer#1147]
Hi sir,

Sorry for bother you as always. At this time I want to know something that could be simple (maybe).

I want to customize the profiles in the drawer. I mean, I want to add information and if there is a posibility to remove the email in the profile list.

Let me show you an example to be more clear.

![sin titulo](https://cloud.githubusercontent.com/assets/13120695/14210111/59ee57da-f7f1-11e5-804a-c2d6e7332046.png)

Do not you worry about the color or the aspect of the text because I made the drawing in paint to make it fast. What matters to me is the ability to display a customized information as you see, the full name, the company name, an estatus, whatever but more information.

Thanks in advance.

Deneb Chorny.

**Comment by mikepenz** [comment]
@denebchorny creating a custom `ProfileDrawerItem`  is as simple, as creating a normal custom `DrawerItem` 

For your usecase I would recommend that you `extend ProfileDrawerItem` and just add the additional line which is required for your usecase. 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java

So you will `extend ProfileDrawerItem`
Then you `Override` `getType()`
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L185
Then you `Override` `getLayoutRes()`
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L191
Then you `Override` `bindView()` 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L196
Make sure you call `super.bindView()` here. So you can keep the already existing logic, and you just add the binding for the additinal `TextView` you have.
We also have to `Override` `getFactory()` 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L252
And provide a different `ViewHolder` with support for the additional field
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L262
And last also a new `ItemFactory` which will create the `ViewHolder` for the `Drawer`
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L256

(In case the above steps seem to confusing, just copy and paste the `ProfileDrawerItem` and just add the additional `TextView` you have, and the additional property. And change the `Type` and `LayoutRes`)

**Comment by denebchorny** [comment]
Mr. Penz, you Rocks...

Let me try it. If I have any problem I will tell you. Reading your solution looks pretty clear. I just can say THANK YOU SIR...

I'll notice you as soon as I try.

**Comment by jemsnaban** [comment]
so, the new ViewHolder must extends ProfileDrawerItem.ViewHolder ? but the super() has private access.
