### ISSUE TITLE
BottomBar, FAB, and Toolbar not fading

### ISSUE THREAD

**Issue by ofirmiron** [mikepenz/MaterialDrawer#1148]
For some reason every element that has an elevation property is not faded when the drawer is opened. This includes BottomBar, FloatingActionButton, and the Toolbar (the status bar does get faded).

![screenshot_20160402-222854 1](https://cloud.githubusercontent.com/assets/17969689/14230924/562ab670-f922-11e5-810a-9967934b6f26.png)

**Comment by mikepenz** [comment]
@ofirmiron nothing the **MaterialDrawer** can change. The `DrawerLayout` from the supportlib (which is used from the MaterialDrawer) adds the fading. You might find an issue regarding this on StackOverFlow.

**Comment by ofirmiron** [comment]
Thanks for your help. I ended up falling back to the stock drawer. As for the BottomBar, I was able to fix it by attaching it to the root view (in my case, relative layout) rather than the activity itself.
