### ISSUE TITLE
 Ever Expanding StatusBar (2.5.0-SNAPSHOT)

### ISSUE THREAD

**Issue by inktomi** [mikepenz/MaterialDrawer#115]
If I pause and resume my app over and over, causing the menu to be setup again and again, we continually push the app content down. 

The code I'm using to setup the panel is here, and it's called from onResume because some of the options can change between launches. The expected behavior, I think, is that since the side panel is totally being reset it does not continue to push the content down each time it's launched.

https://gist.github.com/inktomi/4111d570baeef267eb4d

I have a video uploaded here, which may explain this better. 
https://drive.google.com/file/d/0B_mnp5s6MRbzUHVkcTM2ZFlESHM/view?usp=sharing

The same code does not reproduce this bug in version 2.0.8.

**Comment by mikepenz** [comment]
@inktomi thanks for the detailed description. :D really interesting finding. I'll try to reproduce it now :)

**Comment by mikepenz** [comment]
@inktomi oh there'S also v2.5.0 final already but i think this did not change since then

**Comment by mikepenz** [comment]
Ok it happened with v2.0.8 too but it was not visible.

**Comment by inktomi** [comment]
What is the proper way to update an already existing Drawer, if creating a new one leads to nested drawers and wasted memory?

I don't see easy .rebuild() or .update() methods?

**Comment by mikepenz** [comment]
@inktomi no fixed this with the new version :D but still just create the drawer within your onCreate() method and remember the Drawer.Result.

you can then add the profiles on the result object. it will auto udpate everything for you :)
