### ISSUE TITLE
Sub items selection

### ISSUE THREAD

**Issue by smtrz** [mikepenz/MaterialDrawer#1151]
Hi @mikepenz ,
Kindly let me know how can i show selection of subitems which are expanded from a primary drawer item.
I tried using `withSelectedItemByPosition(x)` but its doesnt seems to work.
Kindly guide.
Thanks 
Tahir

**Comment by mikepenz** [comment]
@smtrz I am not quite sure what you try to do? You want to programmatically set the selection on a subItem?

**Comment by smtrz** [comment]
yes i added 3 sub items to a primary drawer item,how can set the selection on a sub item pro grammatically yes.

Kindly guide.

**Comment by mikepenz** [comment]
@smtrz you can set the selection via the `Drawer` object. Just use the identifier of the element you want to select: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L471

**Comment by smtrz** [comment]
sorry but whats the identifier of the element ?

**Comment by mikepenz** [comment]
you define it via `withIdentifier()` when you create the `item`. It is automatically defined if you don't and you can get it via `getIdentifier()` from your item

**Comment by smtrz** [comment]
okay i did that .
Then where should i pass that identifier ? 
**Please note that i want selection on a particular subitem in the drawer.

**Comment by mikepenz** [comment]
each item can have an identifier. And you can then set the selection to an item with an identifier. 

Everything shown in the sample:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L216

**Comment by smtrz** [comment]
Okay great i did that but it is not working for sub items.

**Comment by mikepenz** [comment]
@smtrz I just tried it in the sample. 
First I expand the `ExpandableItem` (you can only select sub items if they are visible)
```java
result.getAdapter().expand(result.getPosition(19));
```
and then I set the selection:
```java
result.setSelection(2000, false);
```

and it selects the sub item
