### ISSUE TITLE
Wrong selected states

### ISSUE THREAD

**Issue by rubengees** [mikepenz/MaterialDrawer#1152]
I just updated to the latest MaterialDrawer version and the state of the selected items are totally messed up.
My code worked fine previously, but I also set withSelectable to true for every Item now as said in the release notes of FastAdapter.  
What exactly happens is that a clicked icon doesn't become selected or that the selection disappears completely.

**Comment by mikepenz** [comment]
@rubengees looking into it. 
You are always one of the fastest updater :D

**Comment by rubengees** [comment]
Whoa that was fast!
Works perfectly again. 
On a side note: The color of the unselected icons changed to a lighter gray. Is that intended?

**Comment by mikepenz** [comment]
@rubengees yeah was missing my own upgrade notes of the `FastAdapter`. :/

I think it's now the correct color as of the android material design guidelines. with prior versions it was not possible to have the icons properly colored on android devices pre 21.

**Comment by rubengees** [comment]
Hmm, I didn't look up the colors the lib uses (Design specs say 54% transparent black) but they look a bit off:

![designspecs](https://cloud.githubusercontent.com/assets/8021265/14262838/cfed2b1e-fab7-11e5-8fad-aed794061180.png)  

Taken from the [Navigation Drawer](https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-specs spec) spec

![my](https://cloud.githubusercontent.com/assets/8021265/14262839/d2fa7820-fab7-11e5-9574-9ae67753848f.png)  

How it looks in my App

**Comment by mikepenz** [comment]
Which device do you have? On my device it is still the same color as on the screenshots in the README

**Comment by rubengees** [comment]
I have a OnePlus 2 with Marshmallow. I'm currently starting an emulator and will have a look at other Api levels.

**Comment by mikepenz** [comment]
I tested it on a Nexus 6P with Android 6.0.1. 

Have you done a clean build?

**Comment by rubengees** [comment]
Yes did a clean build.
Could reproduce it with a Nexus 5 Api 23 emulator, but not with a Nexus 5 Api 16 emulator.

**Comment by rubengees** [comment]
Any news on this? I already updated to the newest versions.

**Comment by mikepenz** [comment]
might should be opened as separate issue. as I was not yet able to reproduce it.
