### ISSUE TITLE
Disable click in account header image

### ISSUE THREAD

**Issue by nhudinh2103** [mikepenz/MaterialDrawer#1153]
I want to disable click event in left image (because when you click, image has blue color and drawer will close).
How can I do that?

**Comment by NateShoffner** [comment]
You can disable profile image clicking by setting `withProfileImagesClickable(false)` in the AccountHeaderBuilder.

**Comment by nhudinh2103** [comment]
Thanks

**Comment by mikepenz** [comment]
@NateShoffner thanks for answering
