### ISSUE TITLE
Blank screen after rotating the screen in 5.1.8

### ISSUE THREAD

**Issue by robertmathew** [mikepenz/MaterialDrawer#1154]
I am getting a blank screen after rotating the device and the drawer item selected is also set to default.

**Comment by mikepenz** [comment]
@robertmathew not reproduceable in the sample app. Has to be related to your implementation. 

What are you trying to do?

**Comment by robertmathew** [comment]
After switching fragment to android.support.v4.app.Fragment. It works fine.
