### ISSUE TITLE
Is there any round badges?

### ISSUE THREAD

**Issue by beta** [mikepenz/MaterialDrawer#1155]
Using `PrimaryDrawerItem#withBadge` will add a badge with text inside to the drawer item. However I want to add a badge without text, which looks like a round red dot. Is there any way to implement this?

**Comment by beta** [comment]
I've tried to use a `BadgeStyle` with a large enough corner radius and a little min width & padding, but the badge is still a big circle. Hope there's some way to use a custom view or drawable for the badge.

**Comment by JasonHezz** [comment]
Although we are both Chinese,I still use English...
For the first one ,without text,using 
`item1.withName("A new name for this drawerItem").withBadge(" ").withBadgeStyle(new BadgeStyle().;`

As for corners and custom drawable ,do like this
`item1.withName("A new name for this drawerItem").withBadge(" ").withBadgeStyle(new BadgeStyle().withBadgeBackground(@drawable resource).withCornersDp(int radius).
withPadding(int paddingValues).withMinWidth(int minWidth);`

**Comment by beta** [comment]
@JasonHezz I've tried both the two ways, but like I've mentioned above the badge is a rather big one, and I'm unable to make it smaller. Now I've switched to a normal badge with a number inside.
