### ISSUE TITLE
disable selected item 

### ISSUE THREAD

**Issue by vasiledoe** [mikepenz/MaterialDrawer#1156]
I am using `drawer.setSelection(position);` for selecting an option for a custom position, but is there a way to disable selected item?

I was trying `drawer.withSelectedItem(-1);` bu get an error `Could not resolve method`, have to mention that I am using version `4.6.1`

**Comment by mikepenz** [comment]
@vasiledoe sorry I only can give support for the latest version. It may be the case that this was not yet working in the prior version

**Comment by mikepenz** [comment]
@vasiledoe oh and I think the method was named differently in your version. Just look for a method with equal the functionality. 
This one might work: http://static.javadoc.io/com.mikepenz/materialdrawer/4.6.1/com/mikepenz/materialdrawer/Drawer.html#setSelectionAtPosition-int-
or this one: 
http://static.javadoc.io/com.mikepenz/materialdrawer/4.6.1/com/mikepenz/materialdrawer/Drawer.html#setSelection-int-
