### ISSUE TITLE
Dynamic background color in custom items

### ISSUE THREAD

**Issue by Antilamer1709** [mikepenz/MaterialDrawer#1157]
Hi Mike,
I have a problem with changing background colors. I want make every item with different color which i will be getting from database.
Here i have my CustomDrawerItem:
```java
public class CustomItem extends PrimaryDrawerItem {

    private ColorHolder background;

    public CustomItem withBackgroundColor(int backgroundColor) {
        this.background = ColorHolder.fromColor(backgroundColor);
        return this;
    }

    public CustomItem withBackgroundRes(int backgroundRes) {
        this.background = ColorHolder.fromColorRes(backgroundRes);
        return this;
    }

    @Override
    public void bindView(ViewHolder holder) {
        super.bindView(holder);

        if (background != null) {
            background.applyToBackground(holder.itemView); - probably problem is here
        }
    }
}
```

Here is class where i creating my items: 
```java
public class DrawerItemsInitializer {

    Activity activity;

    public DrawerItemsInitializer(Activity activity) {
        this.activity = activity;
    }

    public Drawer initItems(Drawer drawer) {
        DataBaseAssetsHelper helper = new DataBaseAssetsHelper(activity.getApplicationContext());
        SQLiteDatabase sdb = helper.getReadableDatabase();
        //create query and args.
        Cursor baseCursor = sdb.query(DataBaseHelper.DATABASE_BEERS_TABLE, new String[]{DataBaseHelper.ID, DataBaseHelper.NAME,
                        DataBaseHelper.DESCRIPTION, DataBaseHelper.COLOR, DataBaseHelper.IMAGE},
                null, null, null, null, null);

        if (baseCursor.getCount() > 0) {

            baseCursor.moveToFirst();
            while (!baseCursor.isAfterLast()) {
                ColorHolder colorHolder = new ColorHolder();
                colorHolder.setColorRes(baseCursor.getInt(baseCursor.getColumnIndex(DataBaseHelper.COLOR)));

                PrimaryDrawerItem item = new CustomItem()
                        .withBackgroundRes(colorHolder.getColorRes())
                        .withName(baseCursor.getString(baseCursor.getColumnIndex(DataBaseHelper.NAME)))
                        .withIcon(R.drawable.cakeimage)
                        .withTextColor(activity.getResources().getColor(R.color.md_dark_primary_text));
                drawer.addItem(item);

                baseCursor.moveToNext();
            }
        }
        baseCursor.close();
        sdb.close();

        return drawer;
    }
}
```
If in method withBackgroundRes() will be resource (R.color.*) it's work fine, but in that case i have only one color.

And here method where i initialize my drawer:
```java
private void initDrawer() {

        toolbar = (Toolbar) activity.findViewById(R.id.toolbar_actionbar);
        toolbar.setTitle(R.string.test);
        toolbar.setTitleTextColor(activity.getResources().getColor(R.color.toolbarTextColor));

        drawer = new DrawerBuilder(activity)
                .withShowDrawerOnFirstLaunch(true)
                .withSelectedItemByPosition(currentPosition)
                .withTranslucentStatusBar(true)
                .withToolbar(toolbar)
                .build();

        DrawerItemsInitializer itemsInitializer = new DrawerItemsInitializer(activity);
        drawer = itemsInitializer.initItems(drawer);

        setItemClickListner();
    }
```
But it dosen't work, how i can solve it?

**Comment by mikepenz** [comment]
@Antilamer1709 
first you should also reset the background if no `background` var was defined. Because the view is reused and if you only set the color if a res was applyed this will cause issues.

What I do not really understand. Why do you create a `ColorHolder` andthen you create the `Item` with `colorHolder.getColorRes()`? Just apply the color direct with `baseCursor.getInt(baseCursor.getColumnIndex(DataBaseHelper.COLOR))`. So you do not create unnecessary object instances.

Everything else looks fine. And you are sure that you get different colors from your db? 
The issue is 100% related to the creation of the item. Everything else is fine.

**Comment by Antilamer1709** [comment]
@mikepenz i only wanted to change color in this loop, and i wanted use ColorHolder like some container for color becouse when i used color from db - it's dosent worked, all colors was white. I checked colors in db - it's fine.
What you mean about reset the background?

**Comment by mikepenz** [comment]
@Antilamer1709 but you don'T use the `ColorHolder` you extract the color from the `ColorHolder` again without really using any of it's functionality in your loop. It's fine in the `Item`

Views are reused if you do not reset the background color it will use the color the previous item which reuses the view had. 
So the item should have something like:
```java
if (background != null) {
    background.applyToBackground(holder.itemView); - probably problem is here
} else {
   holder.itemView.setBackgroundColor(//your default color if no background was set);
}
```

You might provide a small sample app so I can test your implementation and fix it if you want

**Comment by Antilamer1709** [comment]
@mikepenz huge thanks! I already solve this problem by rejection from database, but now i understand where was my mistake. I try it later, now i have some trobles with new version of Android Studio =)

**Comment by mikepenz** [comment]
@Antilamer1709 did it work?

**Comment by Antilamer1709** [comment]
@mikepenz no, it dosen't. App crushes with Resources$NotFoundException. =(

**Comment by mikepenz** [comment]
@Antilamer1709 seems like you mix up ColorRes and ColorInt. Make sure you get the correct color from the db, and use the correct methods to set the color

**Comment by Antilamer1709** [comment]
@mikepenz yes, you are right, now it's work! Thank you for your help!
