### ISSUE TITLE
Make it easier to find documentation for older versions of the library

### ISSUE THREAD

**Issue by MarkOSullivan94** [mikepenz/MaterialDrawer#1161]
Hi Mike,

I was reading over the documentation and didn't realise that you had renamed some of your classes for the library. I managed to quickly make the changes in my app but it might be useful for those who don't have the time to make updates to their app if you could keep a wiki page which links to the different versions of the library.

Would be great if you could specify what changes have been made within the wiki pages as well. Just for people like me who are generally interested and don't want to have to go through all the commit messages :smile: 

Thanks!

**Comment by mikepenz** [comment]
@MarkOSullivan94 all versions of the javadoc are available here:
http://www.javadoc.io/doc/com.mikepenz/materialdrawer/5.1.9

Also the `releases` section of github always states what was changed. 

And one more thing. You can always switch the github source (including the readme) to a specific tag in the past to get the information and sample app for that version.

**Comment by MarkOSullivan94** [comment]
Never knew you had javadoc for the project, nice work!

Apologies for raising this issue, turns out I missed the release section of the repository! :blush:
