### ISSUE TITLE
some options not working on header

### ISSUE THREAD

**Issue by defaultbr** [mikepenz/MaterialDrawer#1162]
```
 .withAlternativeProfileHeaderSwitching(false)
                .withThreeSmallProfileImages(false) 
``` 
Still show the two images on top of header, instead of using this 2 options above, is better to use this one ->               `  .withOnlyMainProfileImageVisible(true)` but this doesnt hide the small profile images on the list =(

and this                ` .withSelectionListEnabledForSingleProfile(false)` still show the dropdown

and using the same topic, is there any way to add all the accounts from device (i can using the Accounts) BUT how to add the profile image and full name??

and, is there any way to add a "No Profile Selected"? for the first run of the application?!?

sorry que questions =x

**Comment by mikepenz** [comment]
@defaultbr the above two lines will only set that the `AccountHeader` shows two small icons, and that the ordering is a bit different.

`.withSelectionListEnabledForSingleProfile(false)` will only hide the selecitn list if there is just a single profile. (as the name states). it will disable the toggle to the profile list. 

`.withOnlyMainProfileImageVisible(true)` what do you mean with it is not working?

Filling the list with accounts can be done with any source. It is not part of the library to provide those. The library just provides the api to add them. You might need to search some other sources to find out how to get the name, and image from the profiles on your device. 

You can define a hard coded text if you want for the first and second line.

**Comment by defaultbr** [comment]
I got it for the withSelectionListEnabledForSingleProfile, the name states this, sorry!

for the ` .withOnlyMainProfileImageVisible(true)` i was waiting for something to hide the icon for the accounts at the "Account Lists"(when you click in the arrow and it show the account list at the Drawer), so, i can add icon but the `.withOnlyMainProfileImageVisible(true)` handle if it shows or not the icon(show for the main/selected only)


and for the hard coded text, i cant use this, because if i hardcode it, i CAnt choose another profile, try this:
create the header with this lines:

```
headerResult = .....

     .withSelectionFirstLine("Select one Account")
                .withSelectionSecondLine("Click Here")
....
.build();
```


and than add the accounts

   ```
   headerResult.addProfiles(new ProfileDrawerItem().withName("AccountOne").withEmail("email1@").withIcon(getResources().getDrawable(R.drawable.ic_download))); //Remember to change to ResourcesCompat
        headerResult.addProfiles(new ProfileDrawerItem().withName("AccountTwo").withEmail("email2@").withIcon(getResources().getDrawable(R.drawable.ic_download)));
        headerResult.addProfiles(new ProfileDrawerItem().withName("AccountThree").withEmail("email3@").withIcon(getResources().getDrawable(R.drawable.ic_download)));
```

you can choose another account, but the first and second line will be the same forever just the image will change



another approach i`ve tried:

1) remove the .withSelection first and second line;

create the Objects

```
ProfileDrawerItem noAccountProfile = new ProfileDrawerItem().withName("Select one Profile").withEmail("Click Here").withIcon(getResources().getDrawable(R.drawable.ic_download));
        ProfileDrawerItem account1 = new ProfileDrawerItem().withName("AccountOne").withEmail("email1@").withIcon(getResources().getDrawable(R.drawable.ic_download));
        ProfileDrawerItem account2 = new ProfileDrawerItem().withName("AccountTwo").withEmail("email2@").withIcon(getResources().getDrawable(R.drawable.ic_download));
        ProfileDrawerItem account3 = new ProfileDrawerItem().withName("AccountThree").withEmail("email2@").withIcon(getResources().getDrawable(R.drawable.ic_download));
```

add and then check if the profile was previsoly selected (maybe using sharefpreferences), if not, than add all and set the Active One to the noAccountProfile:


the same behaviour, you cant change the first/second line to the selected profile, just the image


im doing it correctly?

**Comment by mikepenz** [comment]
@defaultbr yes :D

No the `withOnlyMainProfileImageVisible(true)` you just control the `AccountHeader` not the list of the profiles. If you do not want th eicon to be shown in the list of profiles, you will have to create a `CustomProfileDrawerItem` as the default behavior is to show the icon if one is provided. 

You still can do this. Set the text for the first and second line. And as soon as a profile get's choosen you have to set the first and second line text to `null` again so the default behavior gets active again.
(https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L132)

**Comment by defaultbr** [comment]
yep, i got it working perfectly, thanks, but i had to remove all the accounts from header and implemented the AccountPicker at the HeaderClick,  since its impossible to show all the profile images before the user can pick the account... anyway im facing some issues on imageLoading, i will post another topic, thanks
