### ISSUE TITLE
Returning null on MiniProfileDrawerItem#withName(String)

### ISSUE THREAD

**Issue by meNESS** [mikepenz/MaterialDrawer#1163]
Hi Mike,

Why you returned `null` inside the following method?!

```
public MiniProfileDrawerItem withName(String name) {
        return null;
}
```

Maybe because of `withCompactStyle(boolean)`.

**Comment by mikepenz** [comment]
@meNESS because those methods are required by the `IProfile` interface, but the `MiniProfileDrawerItem` does not need those properties.

**Comment by meNESS** [comment]
@mikepenz Thanks Mike. Please add documentation to your source code because there are lots of things that I (and maybe more people) don't know about your codes and it takes sometimes one hour to build desired one.

**Comment by mikepenz** [comment]
@meNESS I have javadoc for almost everything. There are just a few parts missing. 
Especially default behavior is documented very well and also shown in the sample app. 

Many more complex custom things were already discussed some day in the issues section. It is always a good hint to filter issues for the tag **good to know** ;)
