### ISSUE TITLE
[bug] miniDrawer not update icon state on mini item clicked

### ISSUE THREAD

**Issue by sosite** [mikepenz/MaterialDrawer#1165]
When I clicked on miniDrawer item `onItemClick` are called but miniDrawer item state aren't updated while normal drawer has correct item state. Bug is also reproducible in your demo.

I also see a delay between big drawer item click and mini drawer icon update. Update is triggered at the end of cross fade animation. Little irritating :wink:

- Android 4.4.2
- MaterialDrawer 5.1.9
- Crossfader 1.3.7

**Comment by sosite** [comment]
Using `miniDrawer.createItems()` in `onItemClick` causes two miniDrawer items selected (proper item and item below) when normal drawer items are selected properly (only proper item).

**Comment by mikepenz** [comment]
@sosite I have found the bug. It will be fixed in the next version.
