### ISSUE TITLE
Disable click on the header

### ISSUE THREAD

**Issue by meNESS** [mikepenz/MaterialDrawer#1166]
Hi Mike,

How can I disable click on the header?

```
AccountHeader headerBuilder = new AccountHeaderBuilder()
                .withCompactStyle(true)
                .withDividerBelowHeader(false)
                .withHeaderBackground(R.drawable.header)
                .withActivity(this)
                .withDividerBelowHeader(false)
                .withSelectionListEnabledForSingleProfile(false)
                .build();
```

**Comment by mikepenz** [comment]
@meNESS what do you want to disable? the toggle for the profile list?

**Comment by mikepenz** [comment]
You can disable the selection list in general with:
```java
.withSelectionListEnabled(false)
```

**Comment by meNESS** [comment]
@mikepenz No, I want to disable click on the header background. I just want a simple image with no clickable option.

**Comment by mikepenz** [comment]
Yeah so you just need to set a header. 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MultiDrawerActivity.java#L43

no `AccountHeader` needed..
