### ISSUE TITLE
[feature] Fragment as custom drawer content

### ISSUE THREAD

**Issue by sosite** [mikepenz/MaterialDrawer#1168]
I want to display various info / statistic / etc. on the right drawer. The simplest way to achieve this will be used custom fragment in place of standard RecyclerView. Any chances to add this feature? :wink:

**Comment by mikepenz** [comment]
@sosite I don't think this is `MaterialDrawer` related. You could add an additional slider to the `DrawerLayout` and fill it with the content you need.

**Comment by mikepenz** [comment]
You can also use the `withCustomView` method which allows you to define any view for the `Slider` you want. In your case a fragment

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L287
