### ISSUE TITLE
Drawer Background pattern or image issue

### ISSUE THREAD

**Issue by bakcay** [mikepenz/MaterialDrawer#117]
Hello
I tried many times for "material_drawer_background" assign drawable but i failed. How can i assign it ? or only color ?

**Comment by mikepenz** [comment]
@bakcay the `material_drawer_background` is only a color. The methods also only allow a color for the background of the drawer. 

You need a drawable there? Shouldn't the background be a solid color?

**Comment by bakcay** [comment]
Yes i need to assign a drawable(image) for background image below http://prntscr.com/6hm176 (green area should be a gradient  bg-image or drawable)

**Comment by bakcay** [comment]
By the way is there any way to change font ?

**Comment by mikepenz** [comment]
@bakcay ok i see. i'll add a new method to the builder to pass a background drawable to the slider ;). 

Changing the font is not possible, and the only option to get this working would be to create custom DrawerItem implementations for you. 
Ok you also could iterate over the view hirachy and change the font for all textviews but this is a bit inefficient :D

**Comment by bakcay** [comment]
options for set font , changing badge background or making border makes this drawer number1 in my opinion :)
