### ISSUE TITLE
I already have a left menu drawer, How can I open a drawer on right side on filter option menu selected? 

### ISSUE THREAD

**Issue by alpeshrathod25** [mikepenz/MaterialDrawer#1170]

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MultiDrawerActivity.java

**Comment by alpeshrathod25** [comment]
Thank You @mikepenz
