### ISSUE TITLE
PrimaryDrawerItem - Drawer Icon

### ISSUE THREAD

**Issue by JImmyBhavsar** [mikepenz/MaterialDrawer#1171]
How to increase drawer icon size ? 
There is property to set icon via withIcon in PrimaryDrawerItem. 
It sets the fix size icon. Is there any way to increase the icon size ?

**Comment by mikepenz** [comment]
@JImmyBhavsar you will have to implement your own `CustomDrawerItem`
the default drawerItems follow the `Material Design Guidelines` and are exactly created for those
