### ISSUE TITLE
Re-sizing header

### ISSUE THREAD

**Issue by meNESS** [mikepenz/MaterialDrawer#1172]
Hi Mike,

How can I re-size the header? 

```java
new DrawerBuilder(this)
        .withHeader(R.layout.drawer_header)
        .build();
```

```xml
<ImageView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:contentDescription="@null"
    android:src="@drawable/header"/>
```

![screenshot_20160412-123549](https://cloud.githubusercontent.com/assets/7955356/14453617/276e603a-00ab-11e6-817b-c52b013ea494.png)

**Comment by mikepenz** [comment]
@meNESS your header has to define the height itself. It will be added as normal item within the list, no size is handled by the Drawer itself here.

See the header from the sample:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/header.xml#L5
