### ISSUE TITLE
Is that possible to show both name and e-mail in AccountHeader choose list?

### ISSUE THREAD

**Issue by kswen** [mikepenz/MaterialDrawer#1173]
it`s not easy to identify with email id when we have many accounts in account header list, can drawer display both name and email in list, or can set to decide show name or email?

**Comment by mikepenz** [comment]
@kswen just enable this on the `ProfileDrawerItem`
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L96
