### ISSUE TITLE
The latest version 5.2.0 will cause TextInputLayout hint text to right side

### ISSUE THREAD

**Issue by kswen** [mikepenz/MaterialDrawer#1174]
use 5.1.6 is fine, but the latest version 5.2.0 will make hint text to right side if set EditText gravity to right.

e.g:

    <android.support.design.widget.TextInputLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/txn_amt_wrapper"
        >
        <EditText
            android:id="@+id/txn_amt"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="test hint"
            android:imeActionLabel="test hint"
            android:enabled="false"
            android:gravity="right"
            android:textAppearance="?android:textAppearanceLarge"
            android:textColor="@color/accent"
            />

    </android.support.design.widget.TextInputLayout>

use 5.1.6, it display like:

test hint
______________edit text value_

use 5.2.0, it display like:
                                       test hint
______________edit text value_

**Comment by mikepenz** [comment]
Not related to the `MaterialDrawer`. I assume this is an issue with the `support libraries` v23.3.0. Update was done with v5.1.9
https://github.com/mikepenz/MaterialDrawer/releases/tag/v5.1.9
