### ISSUE TITLE
Account header Profile Picture size

### ISSUE THREAD

**Issue by vishwathm** [mikepenz/MaterialDrawer#1175]
Is it possible to increase the size of the profile picture displayed in account header.

**Comment by mikepenz** [comment]
@vishwathm there is not api for this. But you can overwrite the used layout and modify it:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml

**Comment by vishwathm** [comment]
Thank you.
