### ISSUE TITLE
SecondaryDrawerItem vs PrimaryDrawerItem

### ISSUE THREAD

**Issue by Debjyotinath** [mikepenz/MaterialDrawer#1176]
Hi Mike,
I have a small question
What is the purpose of SecondaryDrawerItem when we have PrimaryDrawerItem?
I check the code they are the same in both the classes.
So can you tell me the difference in them?

**Comment by mikepenz** [comment]
@Debjyotinath the `SecondaryDrawerItem` is smaller so has a different height. And it also has a different font size. It's a second default item beside the `PrimaryDrawerItem` to provide some more flexibility from the default items. 

In the past it also was different as it had no badge and so on. But you are right I just checked it now just differs in the layout, and I think it should be possible to extend the `SecondaryDrawerItem` from the `PrimaryDrawerItem` and just overwrite the layout and id. 

Thanks

**Comment by mikepenz** [comment]
Will be improved in the next version
