### ISSUE TITLE
SectionDrawerItem withTypeface no result

### ISSUE THREAD

**Issue by JohnGeorgiou** [mikepenz/MaterialDrawer#1177]
Hi , and a big thank you for the library.

I try to change the typeface of a `SectionDrawerItem`
```
new SectionDrawerItem()
                .with...
                .withTypeface( myTypeFace )
                .with...
```
and I have no result.

The .withTypeface( myTypeFace ) works ok to all other items ProfileSettingDrawerItem, SwitchDrawerItem, PrimaryDrawerItem etc

Can you check it out please?

**Comment by mikepenz** [comment]
@JohnGeorgiou the `Typeface` is correctly set on the `TextView`:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/SectionDrawerItem.java#L122
