### ISSUE TITLE
Question about activity switch and drawer close

### ISSUE THREAD

**Issue by Windfarer** [mikepenz/MaterialDrawer#1178]
As we know that we can use intent in onItemClick method to start a new activity, and if this method return false, the drawer will be closed after click. But the new activity appearing will be prior to drawer closing. So that the transaction seems not that smooth. Is there any callback method or something else can make me close the drawer first, then switch activity? 
Thank you.

**Comment by mikepenz** [comment]
@Windfarer you can delay the `drawer` close or you can delay the `onItemClick` event (the later will prevent you from preventing the drawer to close)

http://static.javadoc.io/com.mikepenz/materialdrawer/5.2.0/com/mikepenz/materialdrawer/DrawerBuilder.html#withDelayOnDrawerClose-int-
http://static.javadoc.io/com.mikepenz/materialdrawer/5.2.0/com/mikepenz/materialdrawer/DrawerBuilder.html#withDelayDrawerClickEvent-int-

**Comment by Windfarer** [comment]
OK, it works well! thanks a lot.
