### ISSUE TITLE
Question - Ripple Effect Support

### ISSUE THREAD

**Issue by TurKurT656** [mikepenz/MaterialDrawer#118]
I realized that there is no ripple effect support for android below API21.
Can u add it?

**Comment by mikepenz** [comment]
@TurKurT656 Sorry no this is not included. Google added the ripple effect only for API21+. I have no plans to add an extra library to bring this to lower apis (which is in many ways hacky and not as performant). There's a reason why google does not provide it on via the support libraries ;).
