### ISSUE TITLE
Multilevel Navigation

### ISSUE THREAD

**Issue by dominicsavb** [mikepenz/MaterialDrawer#1182]
Hi Mike,

How to make multi level navigation like image below?

Thank you
![img-20160415-wa0006](https://cloud.githubusercontent.com/assets/6405946/14550659/c101e4ba-02f4-11e6-8fdb-d9b8ce4649b0.jpg)

**Comment by mikepenz** [comment]
@dominicsavb that requires a lot of custom behavior. And I am not sure if it makes sense for you to use the `MaterialDrawer` for this
