### ISSUE TITLE
Showing two status bars when using fragment drawer

### ISSUE THREAD

**Issue by vish30** [mikepenz/MaterialDrawer#1184]
The fragment drawer is in the "Products" fragment in the navigation drawer of Dashboard activity. In marshmallow devices, two status bars are shown. You'll be able to see the second status bar below the toolbar when you open the navigation drawer from right to left.

The main navigation drawer is the Google standard drawer, and the fragment drawer is a sliding menu from right to left a and is made using @mikepenz Material Drawer library.

This second status bar problem appears only in marshmallow devices. I don't know how is this second status bar coming. Please help ASAP.

Here is the link to my Github Repo: https://github.com/vish30/lokacart.git

**Comment by mikepenz** [comment]
@vish30 ok thanks. I just tried it. First problem. I do not have the login data to login. 

So I just had a closer look at your source code. And I have the feeling you use the `MaterialDrawer` wrong. 

Your `DashboardActivity` already hosts a `DrawerLayout` but this acitvity also hosts the `Fragment` which will then have the `MaterialDrawer` if you do it like this it will break in many ways, and the `MaterialDrawer` is not meant like this. You should really have the `MaterialDrawer` in the `Activity` and fill it with the items, depending on the scope you are. You can even lock the drawer, so it can't be opened, if you switch to a `fragment` which should not have a `Drawer`

**Comment by vish30** [comment]
@mikepenz I am sorry as I used mixed the simplified file repo with the original one. Here is the link to the simplified file repo. You wont be needing any login creds here.

Link: https://github.com/vish30/lokacartapp.git

I have to use the fragment drawer inside this fragment only as, everytime the fragment is opened, the data of the drawer will be fetched dynamically. It works perfect in other devices, but in API level 23 only its showing extra status bar. Please solve this bug. It'll be of great help. Waiting for your reply.

**Comment by mikepenz** [comment]
@vish30 ok thanks. 

Yeah still you can update the items of the `MaterialDrawer` at any time later, you can clear the current items, add new ones, update existing ones and so on. I remember a issue from the `DrawerLayout` and the use inside a `Fragment` which exactly sounds like the issue you have currently. But I can't find it right now. 

I still highly recommend that you do not have 2 `DrawerLayouts` in your application. (It might seems to work, but it has weird side effects)

**Comment by vish30** [comment]
@mikepenz we have to use two nav drawers in our application, as we will be using the fragment drawer to set filters for products. 

What if I change the layout of the Dashboard Activity to RelativeLayout and use your material drawer instead of the standard DrawerLayout as the parent layout for the Activity. Will that help ?

As, this app has two nav drawers and is exactly the same as we want: https://play.google.com/store/apps/details?id=com.ajnsnewmedia.kitchenstories&hl=en

**Comment by mikepenz** [comment]
@vish30 the `MaterialDrawer` allows you to have a slider on the right and on the left. 
See the `MultiDrawerActivity` 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MultiDrawerActivity.java

**Comment by vish30** [comment]
@mikepenz I will have the fragment drawer only in the ProductFragment, as i'll fethching the content of the drawer dynamically from the server. So, I can't use the MultiDrawerActivity as both the drawers are attached to the activity.

You can see that I've already implemented your Fragment drawer and it is working fine in Pre marshmallow devices, there is just a small bug which I'm not able to figure out that why are two statusbars shown.

**Comment by mikepenz** [comment]
@vish30 you can use it. as you can **LOCK** a specific side of the drawer, so it is not accessible at the other states. It will also make your view hirachy more flat

http://developer.android.com/reference/android/support/v4/widget/DrawerLayout.html#setDrawerLockMode(int, int)


EDIT: will answer the second part later

**Comment by vish30** [comment]
@mikepenz It worked by using material drawer instead of Android's DrawerLayout and changing the parent layout of DashboardActivity from CoordinatorLayout to RelativeLayout. Everything is working fine.

Thank you so much for your support.
