### ISSUE TITLE
scrollview inside material drawer

### ISSUE THREAD

**Issue by soheilserver** [mikepenz/MaterialDrawer#1185]
I have made made my own drawerItem witch extends BaseDrawerItem and has a ScrollView inside itself. but when I add this to my MaterialDrawer, the ScrollView doesn't scroll and instead the recyclerview scrolls. how to solve the problem?
thanx

**Comment by mikepenz** [comment]
@soheilserver this is nothing related to the `MaterialDrawer`. You might have to search android specific how a scrollvie will work within a `RecyclerView` and how both work together. I do not know this. And I also do not recommend to have a structure like this. It's really no good UX

**Comment by mikepenz** [comment]
http://stackoverflow.com/search?q=scrollview+inside+recyclerview
