### ISSUE TITLE
withTextColor() withTextColorRes() not working on ProfileDrawerItem()

### ISSUE THREAD

**Issue by power-alex** [mikepenz/MaterialDrawer#1186]
I cannot seem to change text color of account name and account email - it is always white

new ProfileDrawerItem().withSelectedColor(Color.BLACK)
                .withName(user.username)
                .withEmail(user.email)

**Comment by power-alex** [comment]
Never mind. Managed to work it out.
used .withSelectedColor() on AccountHeaderBuilder() instead of ProfileDrawerItem()

sorry to bother. Great work with the lib btw!

**Comment by ProfPh** [comment]
Mistype above, it is meant to be used on `AccountHeaderBuilder()`
