### ISSUE TITLE
building a drawer sets layout's padding to 0

### ISSUE THREAD

**Issue by power-alex** [mikepenz/MaterialDrawer#1187]
I have a 
android:padding="16dp"
on my root LinearLayout of the activity
adding drawer removes this padding. What can be causing this?

**Comment by mikepenz** [comment]
@power-alex why do you need this padding?

**Comment by mikepenz** [comment]
Just tried it inside the `DrawerActivity` of the sample and it is working fine

![screenshot_20160415-155841](https://cloud.githubusercontent.com/assets/1476232/14563615/1fead2d8-0323-11e6-9df5-74a9eb5c5b32.png)

**Comment by power-alex** [comment]
Well, your TextView is in the center, so we can't really see.
Try setting a padding to parent layout and gravity to top|left to the TextView. Will there be padding? If yes, could you share exactly how you build your drawer?

**Comment by mikepenz** [comment]
@power-alex we can see as the `padding` is above the `Toolbar` 

All the source code is available in the sample app repo. As said I just added `paddingTop=40dp` to the root view inside the layout used in the `DrawerActivity` sample

**Comment by power-alex** [comment]
I solved this by placing my layout into a FrameLayout, so that padding is not on the root view but on an inner view.
I'm not sure what the problem is.

**Comment by mikepenz** [comment]
@power-alex ok great you solved it. but weird enough that it had a different behavior on your side
