### ISSUE TITLE
AppCompay.DayNight as parent theme

### ISSUE THREAD

**Issue by DJafari** [mikepenz/MaterialDrawer#1190]
in v22 and later of support library, google introduced daylight theme for automatic change to day / night theme .

in this library how can use `AppCompat.DayNight` as parent theme ?

thanks

**Comment by mikepenz** [comment]
@DJafari If you do not depend on a `MaterialDrawer` theme you will have to provide the correct attributes for the day theme and the night theme. (they are split into 2 separate styles.xml on system side) 

The required attributes are shown here:
https://github.com/mikepenz/MaterialDrawer#custom-style---stylesxml

**Comment by DJafari** [comment]
thanks @mikepenz
