### ISSUE TITLE
Install MaterialDrawer offline

### ISSUE THREAD

**Issue by MBehtemam** [mikepenz/MaterialDrawer#1191]
I have problem with my network and i can't install MaterialDrawer from internet with gradle.so how can i download MaterialDrawer from github and then install it .

**Comment by mikepenz** [comment]
@MBehtemam sorry but this is no library specific issue. All ressources are available, and there are enough tutorials out describing how you can use libraries as module, or how to use an aar from the fileystem

**Comment by Rainer-Lang** [comment]
@MBehtemam I suggest to fix your network. You will other "problems" too.
