### ISSUE TITLE
rtl problem

### ISSUE THREAD

**Issue by DJafari** [mikepenz/MaterialDrawer#1192]
in rtl mode, items layout incorrect .
icons must located at right side of text .

see image :
![screen shot 2016-04-17 at 14 50 43](https://cloud.githubusercontent.com/assets/1963047/14586394/ea797a52-04ab-11e6-8a1a-f81a20df1353.png)

**Comment by mikepenz** [comment]
@DJafari is your application in real RTL mode? API > 17 and rtl mode enabled?

**Comment by DJafari** [comment]
yes, all of my application is rtl 
i add `android:layoutDirection="rtl"` in main layout to force RTL mode .

i check `layout/material_drawer_item_primary.xml`, it's not rtl support fully, i will edit it and give you at next reply

**Comment by mikepenz** [comment]
@DJafari I have tested it, and it worked in the past. Since then I did not modify the layout of the items. 
If you set this line it's still wrong:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L56
?

**Comment by DJafari** [comment]
without `getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);` OR `android:layoutDirection="rtl"` application switched to rtl only when language of phone is rtl, but i want force my users to rtl mode even phone language is ltr, and must be set it in my layouts.

**Comment by mikepenz** [comment]
No I meant if it works when you set it programmatically. As I do when testing (I just have it commented out in the github code as I normally don't use it)

**Comment by DJafari** [comment]
you say right, i test it, it's ok

i add `android:layoutDirection="rtl"` in root view of `activity_main.xml` but your library wrap activity layout in DrawerLayout . 

if possible add method `withRTL(boolean b)` in DrawerBuilder, and set it automatically in your library

**Comment by mikepenz** [comment]
I think the above snippet:
```java
getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
``` 
will do the job. I think I will just point it out if people ask
