### ISSUE TITLE
Lollipop fullscreen activity statusbar

### ISSUE THREAD

**Issue by rafakob** [mikepenz/MaterialDrawer#1195]
I have a _floating_ activity - setup with 9png background, it suppose to look similiar to DialogFragment:
```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    android:id="@+id/root_layout"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/shadow">

    <FrameLayout
        android:id="@+id/fragment_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/white"/>
</FrameLayout>
```

Now I want to show drawer _inside_ that `root_layout`. I've managed to this with following builder, it works great:
```java
mDrawer = new DrawerBuilder(this)
                .withRootView(rootLayout) ...
```
The problem is that on Lollipop devices drawer _enforces_ to show status bar.

**Lollipop - without drawer**

![](http://i.imgur.com/mgfYdbJ.png)

**Lollipop - with drawer**

![](http://i.imgur.com/HkfG7Zy.png)

The problem might not have been directly related with MaterialDrawer but I've decided to ask you anyway. I've read your FAQ, tried different settings and I can't figure this out. What am I missing here?

**Comment by mikepenz** [comment]
Interesting behavior. 

You might want to provide a small sample which allows me to try this out and provide a working solution for you

**Comment by rafakob** [comment]
Thanks, here's a sample project  that shows described behavior -> https://github.com/rafakob/SampleDrawer

**Comment by mikepenz** [comment]
@rafakob the `MaterialDrawer` des not handle the insets of the view, nor does it handle any paddings. This is all handled by the Android system. So as you do not want the android system to handle this in your case, as we are already below the `Toolbar` just add the following to your builder

```java
.withDrawerLayout(R.layout.material_drawer_fits_not)
```
