### ISSUE TITLE
Cannot set transparent statusbar for collapsing toolbar

### ISSUE THREAD

**Issue by henorek** [mikepenz/MaterialDrawer#1196]
Hi there!
My issue is very similar to this one #698, I have:
`activity_main.xml` which hosts a default Toolbar (the one shared between fragment without it's own Toolbar) and an FrameLayout for displaying Fragments. It is defined with below *.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:fitsSystemWindows="true"
    android:layout_height="match_parent">

  <include
      layout="@layout/toolbar_static"
      android:id="@+id/toolbar"/>

  <FrameLayout
      android:id="@+id/fragmentContainer"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:layout_below="@+id/toolbar"/>

</RelativeLayout>
```
`fragmentContainer` is inflated with:
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

  <include layout="@layout/app_bar_homescreen"/>

  <FrameLayout
      android:id="@+id/test"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      app:layout_behavior="@string/appbar_scrolling_view_behavior">

    <include layout="@layout/view_loading"/>
    <include layout="@layout/view_error"/>

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/contentView"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

      <android.support.v4.widget.NestedScrollView
          android:id="@+id/nestedScrollView"
          android:layout_width="match_parent"
          android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

         //content

        </LinearLayout>
      </android.support.v4.widget.NestedScrollView>
    </android.support.v4.widget.SwipeRefreshLayout>

  </FrameLayout>
```

The problem is that it seems impossible to make AppBarLayout's background ImageView to be viewed under translucent status bar while it is hosted by Fragment with CollapsngToolbarLayout. Using fitsSystemWindows flag throughout the view hierarchy seems to be not working.

Fragment hosts CollapsibleToolbarLayout which is replacing default toolbar in Activity by using:
```
//region DrawerHost
  @Override
  public void setDrawerToolbar(Toolbar foreignToolbar) {
    toolbar.setVisibility(View.GONE);
    setSupportActionBar(foreignToolbar);
    drawer.setToolbar(this, foreignToolbar, true);
  }

  @Override
  public void resetDrawerToolbar() {
    toolbar.setVisibility(View.VISIBLE);
    setSupportActionBar(toolbar);
    drawer.setToolbar(this, toolbar, true);
  }
  //endregion
```

![](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/309291/3323760/rHkGSHeMssPZLnF/Zrzut%20ekranu%202016-04-18%2013.02.21.png)

![](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/309291/3323760/dQjPnKJTnwor3TL/Zrzut%20ekranu%202016-04-18%2012.53.40.png)

**Comment by mikepenz** [comment]
Have you check out the `CollapsingToolbarActivity` https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CollapsingToolbarActivity.java ?

**Comment by henorek** [comment]
Yup, sample is working perfectly but in my case i need CollapsingToolbarLayout to be hosted by Fragment that is hosted inside Activity. Would it be a problem for you to provide such sample?

**Comment by mikepenz** [comment]
@henorek as of another issue (I don't find it right now) it is not really possible to host the `DrawerLayout` within a `Fragment` as it will somehow prevent the translucent statusbar. But I am not 100% sure anymore what the exact cause was

**Comment by mseroczynski** [comment]
@mikepenz 
I've been working on similar solution too and also couldn't get it to work. DrawerLayout in (as I guess both mine and henorek's cases) is hosted by Activity, not Fragment - only the Toolbar is unsuccesfully(? - it can't be fullscreen anymore, like in CollapsingToolbarActivity sample) replaced.

**Comment by henorek** [comment]
@mikepenz yes, @mseroczynski is right, my DrawerLayout is hosted by activity, not fragment so I renew my question, would it be a problem for you to provide sample for my (our?) case?

**Comment by mikepenz** [comment]
@henorek @mseroczynski I think this is related to the fact that your `FrameLayout` which is the fragment container does not pass the `fitsSystemWindows` forward. You need a layout which passes the insets forward so this will work. A fast google resulted into this:
https://gist.github.com/cbeyls/ab6903e103475bd4d51b

You might also want to try the `ScrimInsetsFrameLayout` the `Materialize` library (which i have as dependency) contains. 

Beside the above, this is not a MaterialDrawer issue, but more a general handling of the `fitsSystemWindows` flag inside fragmetns
