### ISSUE TITLE
How to update burger icon badge?

### ISSUE THREAD

**Issue by cardovaeric** [mikepenz/MaterialDrawer#1198]
Hi there, i want to know if it's possible to add badge on the hamburger icon,
is there any way to do this?

**Comment by mikepenz** [comment]
@cardovaeric sorry this is not related to the MaterialDrawer. The `ActionBarDrawerToggle` is part from the support libraries of Android. You should google if there is a possibility to have a badge on the `ActionBarDrawerToggle` or if you need a custom component for this
