### ISSUE TITLE
Unable to Load Android 6.0 - Material Drawer Issue

### ISSUE THREAD

**Issue by troy21688** [mikepenz/MaterialDrawer#1199]
I recently updated Android Studio and posted information here on the error I am receiving. I am unsure what is causing the error, but thought that the NavDrawer library could be part of the root as I saw a reference to it in the StackTrace:

http://stackoverflow.com/questions/36724732/android-6-0-stuck-on-first-activity

**Comment by mikepenz** [comment]
@troy21688 no this issue is not related to the `MaterialDrawer` the warniing you get here:

```
04-19 12:46:57.615 1316-1316/com.sourcey.materialloginexample W/dalvikvm: Unable to resolve superclass of Lcom/mikepenz/materialdrawer/view/BezelImageView$CustomOutline; (2232)
04-19 12:46:57.615 1316-1316/com.sourcey.materialloginexample W/dalvikvm: Link of class 'Lcom/mikepenz/materialdrawer/view/BezelImageView$CustomOutline;' failed
04-19 12:46:57.615 1316-1316/com.sourcey.materialloginexample E/dalvikvm: Could not find class 'com.mikepenz.materialdrawer.view.BezelImageView$CustomOutline', referenced from method com.mikepenz.materialdrawer.view.BezelImageView.onSizeChanged
04-19 12:46:57.615 1316-1316/com.sourcey.materialloginexample W/dalvikvm: VFY: unable to resolve new-instance 5293 (Lcom/mikepenz/materialdrawer/view/BezelImageView$CustomOutline;) in Lcom/mikepenz/materialdrawer/view/BezelImageView;
04-19 12:46:57.615 1316-1316/com.sourcey.materialloginexample D/dalvikvm: VFY: replacing opcode 0x22 at 0x000a
0
```

is no issue. It's just a warning because there is no `Outline` support on devices pre API 21.

**Comment by troy21688** [comment]
I actually removed the implementation of your NavDrawer and my app now works. Do you know of issues with Android 6.0 and the latest support libraries?

`public class MainActivity extends AppCompatActivity implements HomePollsFragment.OnFragmentInteractionListener {

    private Toolbar toolbar;

    private Firebase mPollsRef;
    private ViewPager mPager;

    private ScreenSlidePagerAdapter mPagerAdapter;
    private DateFormat mDateFormat;
    private Date mDate;
    private String mCurrentDateString;
    private ValueEventListener v;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_home);
        toolbar = (Toolbar) findViewById(R.id.tool_bar);
        setSupportActionBar(toolbar);
         //        createNavDrawer();
         Firebase.setAndroidContext(this);

        mPollsRef = FirebaseUtil.FIREBASE.child("Polls");

        // TODO: Add Fragment Code to check if savedInstanceState == null; add at Activity Level?
        // Check that the activity is using the layout version with
        // the fragment_container FrameLayout


        //set up viewpager for current day
        mPager = (ViewPager) findViewById(R.id.home_polls_viewpager_fragment_container);
        mPagerAdapter = new ScreenSlidePagerAdapter(getSupportFragmentManager());
        mPager.setAdapter(mPagerAdapter);


        //get current date to apply to Viewpager
        mDateFormat = new SimpleDateFormat("MM-dd-yyyy");
        mDate = new Date();
        mCurrentDateString = mDateFormat.format(mDate);

            // TODO: Checkn if AuthStateListenerNecessary
            //Determine whether necessary to use an AuthStateListener here
            //        mUserRef.addAuthStateListener(new Firebase.AuthStateListener() {
            //            @Override
            //            public void onAuthStateChanged(AuthData authData) {
            //                if (authData == null) {
            //                    Intent backToSignIn = new Intent(getApplication(), SignupActivity.class);
            //                    startActivity(backToSignIn);
            //                    finish();
            //                }
           //            }
            //        })

                }


    @Override
    protected void onStart() {
        super.onStart();

        v = new ValueEventListener() {
            //testing methodology of adding children
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                int pollsAvailable = (int) dataSnapshot.child(mCurrentDateString).getChildrenCount();
                mPagerAdapter.setPollsAvailable(pollsAvailable);
                Log.i("TAG", "There are " + String.valueOf(pollsAvailable) + " children in today's poll count.");
            }

            @Override
            public void onCancelled(FirebaseError firebaseError) {

            }
        };

        mPollsRef.addValueEventListener(v);

    }

    @Override
    protected void onStop() {
        super.onStop();
        mPollsRef.removeEventListener(v);

    }

    @Override
    public void onFragmentInteraction(Uri uri) {

    }

    class ScreenSlidePagerAdapter extends FragmentStatePagerAdapter {
        private int pollsAvailable = 0;

        //fragment adapter constructor
        public ScreenSlidePagerAdapter(FragmentManager fm) {
            super(fm);
        }

        @Override
        public Fragment getItem(int position) {
            return HomePollsFragment.newInstance(position);
        }

        @Override
        public int getCount() {
            return pollsAvailable;
        }

        public void setPollsAvailable(int pollsAvailable) {
            this.pollsAvailable = pollsAvailable;
            this.notifyDataSetChanged();
        }
    }


    private void createNavDrawer() {

        final PrimaryDrawerItem item1 = new PrimaryDrawerItem().withName(R.string.drawer_item_home).withIdentifier(1);
        SecondaryDrawerItem item2 = new SecondaryDrawerItem().withName(R.string.drawer_item_previous_polls).withIdentifier(2);
        SecondaryDrawerItem item3 = new SecondaryDrawerItem().withName(R.string.drawer_item_request_poll).withIdentifier(3);
        SecondaryDrawerItem item4 = new SecondaryDrawerItem().withName(R.string.drawer_item_suppport).withIdentifier(4);
        SecondaryDrawerItem item5 = new SecondaryDrawerItem().withName(R.string.drawer_item_logut).withIdentifier(5);

        AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.ic_facebook)
                .addProfiles(
                        new ProfileDrawerItem().withEmail("bob@gmail.com").withIcon(getResources().getDrawable(R.drawable.logo))
                )
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                        return false;
                    }
                })
                .build();


        Drawer result = new DrawerBuilder()
                .withAccountHeader(headerResult)
                .withActivity(this)
                .withToolbar(toolbar)
                .addDrawerItems(
                        item1,
                        new DividerDrawerItem(),
                        item2,
                        item3,
                        item4,
                        item5
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        drawerItem.withSetSelected(true);
                        switch ((int) drawerItem.getIdentifier()) {
                            case 1:
                                Intent toHomeActivity = new Intent(getApplicationContext(), MainActivity.class);
                                startActivity(toHomeActivity);
                                finish();
                                break;
                            case 2:
                                Intent toPreviousActivity = new Intent(getApplicationContext(), PreviousActivity.class);
                                startActivity(toPreviousActivity);
                                break;
                            case 3:
                        }

                        return false;
                    }
                })
                .build();
        result.setSelection(1);
    }


    @Override
    public void onBackPressed() {
        super.onBackPressed();
        if (mPager.getCurrentItem() == 0) {
            // If the user is currently looking at the first step, allow the system to handle the
            // Back button. This calls finish() on this activity and pops the back stack.
            super.onBackPressed();
        } else {
            // Otherwise, select the previous step.
            mPager.setCurrentItem(mPager.getCurrentItem() - 1);
        }
        }
    }
`

**Comment by mikepenz** [comment]
@troy21688 no there is no issue with Android 6.0. You can even try the sample app on Android 6.0.1 and it will work without any issues. There must be something else causing your issue. 

Your provided code sample looks fine. Can't tell from this one what possibly could go wrong

**Comment by mikepenz** [comment]
I temporary close this until new details were added

**Comment by troy21688** [comment]
Thanks Mike, I am going to delete my StackOverflow post saying that your
drawer doesn't work, as I don't want to adversely impact your software.
However, I did have issues and after removing the NavDrawer, the issues
were no longer existent.

On Fri, Apr 22, 2016 at 12:59 PM, Mike Penz <notifications@github.com>
wrote:

> I temporary close this until new details were added
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mikepenz/MaterialDrawer/issues/1199#issuecomment-213530521>
>



-- 
Troy Chuinard, CPA

**Comment by mikepenz** [comment]
@troy21688 I have seen it. And I would really love to investigate it. As already mentioned the `MaterialDrawer` always runs with the latest version of the support libraries. And is tested on API 10 - API 23 (Android N also works -> preview 2 has tiny issues with andorid iconics, but does not impact the drawer) 

Your described issues are really new and were not reported so I assume some other combination must somehow result in this
