### ISSUE TITLE
Hide keyboard automatically

### ISSUE THREAD

**Issue by tral** [mikepenz/MaterialDrawer#12]
Hello! 
First of all let me express my appreciation for the useful lib!
While using, I noticed an issue: if the software keyboard is shown and you open the drawer - keyboard doesn't disappear:
![screenshot](http://i.imgur.com/M7hyjTF.png)

If we take any Google App (Google Play app for example) and open a drawer there while keyboard is showing - the keyboard closes automatically after 0.5-1 seconds.

Can you implement the same behaviour? Or I should implement in my code?

**Comment by mikepenz** [comment]
@tral you should implement it in your code. with the next version there'll be a onDrawerListener which notifies you onDrawerOpened or onDraewrClosed.

**Comment by tral** [comment]
Works perfect now!
```
public static void hideSoftKeyboard(Activity activity) {
    InputMethodManager inputMethodManager = (InputMethodManager) activity.getSystemService(Activity.INPUT_METHOD_SERVICE);
    inputMethodManager.hideSoftInputFromWindow(activity.getCurrentFocus().getWindowToken(), 0);
}

@Override
public void onDrawerOpened(View drawerView) {
  hideSoftKeyboard(MainActivity.this);
}

```

Thanks!
