### ISSUE TITLE
Settings & Support sticky footer

### ISSUE THREAD

**Issue by drinfernoo** [mikepenz/MaterialDrawer#120]
First of all, I'm loving this library! It seems to be the closest I've found to the MD spec, while still being very easy-to-use and feature-rich.

I wanted to suggest a feature where we could add sections into a separate sticky footer, as described by [http://www.google.com/design/spec/patterns/navigation-drawer.html](Settings and Support). Even a sticky header in this form might be interesting ;)

**Comment by mikepenz** [comment]
@drinfernoo the current implementation supports a sticky footer. you can just drop views into it. (you can also use a DrawerItem's logic (theoretically) to add this there) 

If you talk about items which are stick depending on the screen height, i think this is a bit more complex. And i think this is not quite possible (without a lot of hacking) to add such items.

**Comment by drinfernoo** [comment]
How would you go about doing this? Can I get a `BaseDrawerItem`s as a View?

**Comment by mikepenz** [comment]
you can theoretically use the `convertView` method of specific DrawerItem implementations like the `PrimaryDrawerItem` but yeah as i said this is only a method to get one item :D. You then would have to implement a layout which contains those items and is added into a StickyFooter

**Comment by drinfernoo** [comment]
Then my feature request is not to have to do that ;)

**Comment by mikepenz** [comment]
Yeah lot of functions are already in. So if you have time to implement this complex feature i'm open for pull request ;)

**Comment by drinfernoo** [comment]
Sounds good :)
