### ISSUE TITLE
Different Drawer Layout on orientation change

### ISSUE THREAD

**Issue by fliespl** [mikepenz/MaterialDrawer#1201]
Hi Mike,
I would like to create different drawers based on the orientation (but keep expanded items, selection on orientation change) - some items positions would change etc.

Unfortunately with current implementation is won't work since adapter is using drawer items positions and would select wrong items. 

Is it something that should be handled directly by me and I should skip passing savedInstance bundle to builder?

What are your thoughts on that: should I recreate all drawer items from last view and remove/add missing ones after restoring from orientation change? Or simply skip using savedinstance null?

**Comment by mikepenz** [comment]
@fliespl yeah that something you have to handle on your side, as it is a really special use case. The drawer can't detect if items, and positions, and possible even identifier change. 

Depending on how complex your behavior is I would recommend that you remember the current position (with position I might mean the current section which is selected) and you just select the correct item after orientation change. 

For the expanded items you also have to do the same, but it is a bit more complex depending on how many expandable sectiosn you have
