### ISSUE TITLE
Sometimes icons disappear

### ISSUE THREAD

**Issue by carmelo-ruota** [mikepenz/MaterialDrawer#1205]
I use CustomUrlPrimaryDrawerItem and there are some items that, when clicked, launch a new activity.
Sometimes happens that the icons of some items (seem randomly) disappear and, after clicking some others items, are showed again.

**Comment by carmelo-ruota** [comment]
The problem seems to come because there is an item without icon

**Comment by mikepenz** [comment]
@carmelo-ruota you use the following one:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomUrlPrimaryDrawerItem.java
?

**Comment by carmelo-ruota** [comment]
Yes, but I don't know if CustomUrlPrimaryDrawerItem is the cause

**Comment by mikepenz** [comment]
@carmelo-ruota no I was just asking which item you use so I can try to reproduce your issue

**Comment by mikepenz** [comment]
Found your issue and fixed it: 
https://github.com/mikepenz/MaterialDrawer/commit/a2013e7d9e34f4960364f1562033e383744c41cd
