### ISSUE TITLE
[Lollipop] Profile header image was not loaded, just showed red place holder

### ISSUE THREAD

**Issue by nhudinh2103** [mikepenz/MaterialDrawer#1208]
I got a problem when use your library to display my navigation.
 
**Profile header image was loaded in my phone (Kitkat API 19)**

![kitkat](https://cloud.githubusercontent.com/assets/17499217/14724585/5e3cd482-0841-11e6-83a8-8acf0297481a.png)

**But when run in emulator (Lollipop API 22) it just showed red place holder.** (Other images are OK) 

![lollipop](https://cloud.githubusercontent.com/assets/17499217/14724581/57ca2ec4-0841-11e6-8a68-3523e011d2cc.png)

Here is my code to build account header

```
AccountHeader accountHeader = new MyAccountHeaderBuilder()
                         .withSelectionListEnabledForSingleProfile(false)
                         .withDividerBelowHeader(false)
                         .withActivity(activity)
                         .withAccountHeader(headerLayout)
                         .withHeightRes(heightLayoutDimen)
                         .withHeaderBackground(R.drawable.ic_header_background_navigation_drawer)
                         .withProfileImagesClickable(false)
                         .addProfiles(profile)
                         .build();

```
MyAccountHeaderBuilder Class (to customize a little bit for what i need)

>     @Override
>     public AccountHeader build() {
>         AccountHeader customizeHeader = super.build();
>         int curHeight = 275;
>         setHeaderBackgroundHeight(curHeight);
>         return customizeHeader;
>     }
> 
>     public void setHeaderBackgroundHeight(int height) {
>         if (mAccountHeaderContainer != null) {
> 
>             View accountHeader = mAccountHeaderContainer.findViewById(com.mikepenz.materialdrawer.R.id.material_drawer_account_header);
>             if (accountHeader != null) {
>                 ViewGroup.LayoutParams params = accountHeader.getLayoutParams();
>                 params.height = height;
>                 accountHeader.setLayoutParams(params);
>             }
>         }
>     }

**Comment by nhudinh2103** [comment]
Very strange but when I rerun now, it worked like a charm. Sorry for wasting your time

**Comment by mikepenz** [comment]
probably an instant run exception?

**Comment by nhudinh2103** [comment]
No, I have rebuild project before and no instant run. After afk a few hours, I rerun it and everything was fine. I think it was some emulator problems.
