### ISSUE TITLE
How to insert items and footer item on bottom of the drawer

### ISSUE THREAD

**Issue by meNESS** [mikepenz/MaterialDrawer#1209]
Hi Mike,

How can I insert items and footer item on bottom of the drawer?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

**Comment by meNESS** [comment]
@mikepenz I'm using `.withFooter(drawerFooterView)` but it won't be placed at the bottom of the drawer.

**Comment by mikepenz** [comment]
@meNESS you want the `StickyFooter` ;)

**Comment by swapnilsaha2010** [comment]
How to add multiple items using StickyFooter ?

**Comment by meNESS** [comment]
@swapnilsaha2010 I think you have to create custom layout for multiple items at footer.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L989

**Comment by swapnilsaha2010** [comment]
But when I use it, it shows "cannot resolve method addStickyDrawerItems". How to solve it?

**Comment by mikepenz** [comment]
which version of the drawer do you use?

**Comment by swapnilsaha2010** [comment]
5.2.2

**Comment by mikepenz** [comment]
@swapnilsaha2010 probably you are doing it on the `Drawer` instead the `DrawerBuilder`?
