### ISSUE TITLE
AddItem replaces Item at position

### ISSUE THREAD

**Issue by mikepenz** [mikepenz/MaterialDrawer#121]
With the current verison the `addItem(IDrawerItem drawerItem, int position)` replaces the item at the given position instead of adding it inbetween

**Comment by Rainer-Lang** [comment]
Mike, what about:
1) addItem(IDrawerItem drawerItem, int position) -> adds the item at position and all items behind are getting (position+1)
2) replaceItem(IDrawerItem drawerItem, int position) -> replaces the item at this position

"add" is "add" and "replace" is "replace" ;-)

**Comment by mikepenz** [comment]
I have planned to keep the addItem for adding, and setItem to set an item at a specific position. This is the way you set or add items within Arrays ;)

**Comment by mikepenz** [comment]
Fixed in v2.5.3
