### ISSUE TITLE
MiniDrawer doesn't update selection from Expanded Drawer

### ISSUE THREAD

**Issue by toastking42** [mikepenz/MaterialDrawer#1210]
When I select an item in the MiniDrawer, it's correctly being highlighted in the MiniDrawer as well as the expanded full-size drawer. However, when I select an item in the expanded Drawer, this item is not being highlighted in the MiniDrawer (the MiniDrawer keeps the old selection).

Also, there are some inconsistencies with the expanded and mini drawer regarding the behaviour of enabling / disabling items. I was able to create situations where the MiniDrawer would have all the items disabled while the expanded Drawer has all items enabled. Is it not allowed to set the enabled state of DrawerItems after the initial creation of the Drawer?

**Comment by mikepenz** [comment]
@toastking42 if you just set the enabled state this will not really work. you should always use the methods from the drawer to select an item. `result.setSelection()` ( and fire the event so everything is passed to the `MiniDrawer`)

you create everthing as shown in the sample? it should correctly forward the events to the `MiniDrawer` and in the opposite way

**Comment by toastking42** [comment]
It doesn't. If the user selects an item in the full expanded drawer in the UI, the MiniDrawer ignores that event. At the moment I'm not disabling any items, it's just regular usage of the Drawer/MiniDrawer like in the example.
I also just realized that the MiniDrawer is ignoring drawer.setSelection(); completely. It's only visible in the full drawer.

**Comment by toastking42** [comment]
My mistake :) I didn't realize that I have to set the selection for both of the drawer, so it's like this:
`        miniDrawer.setSelection(1L);
        drawer.setSelection(1L, false);`

That's perfectly fine for me (although it's a bit weird to be honest).
Is there any way for me to disable both the expanded as well as the mini drawer (i.e. all items in them) for a period of time? I don't want the user to click menu items while an asynchronous request is runnning.

**Comment by mikepenz** [comment]
@toastking42 and if you set the selection and trigger the event:
```java
drawer.setSelection(1L, true)
```

It may seem a bit weird, but the thing is that the `MiniDrawer` is not depply wired into the `Drawer` and both more or less work independent from each other. They just communicate with each other via the events which are triggered. 

You can disable it in the `Drawer`. Notify the drawer about the changed item, and then you just recreate the items in the `MiniDrawer``
```java
miniDrawer.createItems()
```
