### ISSUE TITLE
Customize Header 

### ISSUE THREAD

**Issue by kenk11** [mikepenz/MaterialDrawer#1211]
When I build drawer, I wanna add Facebook Login button into Header of Drawer 
Can I do this ? If I can, can u show me how do it ?
Thanks @mikepenz

**Comment by mikepenz** [comment]
Could you please specify which header you mean? You use an `AccountHeader` or the normal header?

**Comment by kenk11** [comment]
Oh sorry @mikepenz , I mean `AccountHeader`
If user not logged, there will be facebook login or another login button
And when user logged, there will be display user info

**Comment by mikepenz** [comment]
@kenk11 do you want to display those buttons directly in the header or just in the account list as those two elements in the `DrawerActivity`

**Comment by kenk11** [comment]
Ya, i want to display login button (Facebook or something else) in `AccountHeader` area not in account list and my app only have 1 user so I disable multi account feature

When user logged, I will rebuild `AccountHeader` with info

**Comment by mikepenz** [comment]
@kenk11 you can overwrite the layout used in the `AccountHeader` which will allow you to provide your additional button. You can then just get the reference to the view from the `AccountHeader` object and set your listener on it or whatever you need. 

You will then just need to define a profile, notify the header about the change and it will show the infos. You will also have to hide the login buttons then

**Comment by kenk11** [comment]
Let me try,
I will give u response when done
Thanks @mikepenz

**Comment by mikepenz** [comment]
This answer might also help you: https://github.com/mikepenz/MaterialDrawer/issues/992#issuecomment-181354255

**Comment by kenk11** [comment]
Thank you so much @mikepenz :)

**Comment by mikepenz** [comment]
If you need more help regarding this let me know

**Comment by kenk11** [comment]
Thanks @mikepenz 
It worked :)
