### ISSUE TITLE
withStickyFooterDivider(false) seems doesn't work

### ISSUE THREAD

**Issue by meNESS** [mikepenz/MaterialDrawer#1212]
Hi Mike,

There's no difference between `withStickyFooterDivider(true)` and `withStickyFooterDivider(false)`. I think this method doesn't work correctly.

**Comment by mikepenz** [comment]
@meNESS it makes a difference. It will add a tiny line at the top of the `StickyFooter` it is just a tiny bit but noticeable with the correct colors and so on.

**Comment by meNESS** [comment]
@mikepenz So, how can I remove the top horizontal line (divider line) which is created by default?

**Comment by mikepenz** [comment]
@meNESS just tested. `withStickyFooterDivider(true)` will correctly add a `1px` high line at the top of the `StickyFooter` to divide it a bit more from the normal list. (it is disabled by default)

This will not remove the shadow, which is enabled by default. You can change it with:
`.withStickyFooterShadow(false)`

You might need to be a bit more specific what you want to achieve as I have the assumption you talk about something else?
