### ISSUE TITLE
Toolbar getting clipped

### ISSUE THREAD

**Issue by smeegoan** [mikepenz/MaterialDrawer#1214]
Hi,

I am trying to add the drawer inside a fragment in a TabLayout. The problem I am having is the toolbar gets clipped as soon as I add the drawer.
![image](https://cloud.githubusercontent.com/assets/1608175/14763254/3e10bf96-0988-11e6-873c-91b09590dd64.png)

I have made severall tries and experiments but I cannot understand why this happens. Can you take a look at this sample project?

[https://cld.pt/dl/download/7ca7e65d-2a84-472d-b00f-689c57b5da21/testcase.zip](https://cld.pt/dl/download/7ca7e65d-2a84-472d-b00f-689c57b5da21/testcase.zip)

**Comment by mikepenz** [comment]
@smeegoan your zip is not accessible

**Comment by smeegoan** [comment]
I updated the comment. The text was correct but the markdown had "url" as the link :\

**Comment by mikepenz** [comment]
@smeegoan just checked your code. It is not related to the `MaterialDrawer` as you use it within the fragment, so it does not modify anything from the tab layout. (I also suggest not to host the drawer within the fragment. It should be full height outside the fragment) With the current implementation you have you won't be able to open the drawer via swipe. 

Beside this. It is really easy to fix your issue. Just add `android:fitsSystemWindows="true"` to your `CoordinatorLayout`, `AppBarLayout` and `Toolbar`. Also change your `Toolbar` to:
```java
<android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="?attr/colorPrimary"
            android:fitsSystemWindows="true"
            app:layout_collapseMode="pin"
            app:layout_scrollFlags="scroll|enterAlways|snap"
            app:popupTheme="@style/AppTheme.PopupOverlay" />
```

If you want to change your `Drawer` to fit the guidelines, and make it `MATCH_PARENT` just check out the `CollapsingToolbarActivity` of the sample app
