### ISSUE TITLE
Custom Container Drawer with FAB(Floating Action Button)

### ISSUE THREAD

**Issue by alexsilvadoprado** [mikepenz/MaterialDrawer#1215]
Hi, I found a little problem, when I use a Custom Container Drawer along with a android.support.design.widget.FloatingActionButton, the Drawer is above the Floating Action Button when opened. This is my layout.xml:

```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/cord_layout"
    android:fitsSystemWindows="true"
    tools:context=".activity.Principal">

    <android.support.design.widget.AppBarLayout
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        android:theme="@style/Theme.MyTheme.AppBarOverlay">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            app:popupTheme="@style/Theme.MyTheme.PopupOverlay" />

    </android.support.design.widget.AppBarLayout>

    <FrameLayout
        android:id="@+id/drawer_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <FrameLayout
            android:id="@+id/frame_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <include layout="@layout/content_principal" />

        </FrameLayout>

    </FrameLayout>
    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|right|end"
        android:layout_marginRight="@dimen/fab_margin_right"
        android:layout_marginEnd="@dimen/fab_margin_right"
        android:layout_marginBottom="@dimen/fab_margin_bottom"
        android:src="@android:drawable/ic_dialog_email"/>
</android.support.design.widget.CoordinatorLayout>
```

**Comment by mikepenz** [comment]
@alexsilvadoprado where is the root of the drawer?
In general I think that's nothing drawer related, but more related to the hirachy how you have structured your layout. 

I also have in mind that this is normal behavior of the `DrawerLayout` nothing the `MaterialDrawer` can alter or modify

**Comment by alexsilvadoprado** [comment]
Yes, I believe it may be related to hierarchy, when I put the Floating Action Button inside the FrameLayout with id = frame_container it is below the Navigation Drawer, but from what I could understand the FAB must be a child of the root CoordinatorLayout, I may be mistaken.

**Comment by mikepenz** [comment]
@alexsilvadoprado why do you have the `drawer` inside a custom container? 

Perhaps this SO question helps: http://stackoverflow.com/a/32549026/325479?

**Comment by alexsilvadoprado** [comment]
I used an example of its application MaterialDrawer, I chose to use the example of CustomContainer because I wanted the Navigation Drawer stay below the toolbar to make visible the animation of hamburguer icon to arrow icon.

**Comment by alexsilvadoprado** [comment]
this SO question does not use your library, use the manual and native implementation, so analyzed, how to implement using your library uses different elements in the layout file.

**Comment by mikepenz** [comment]
@alexsilvadoprado ok. But the Material Design Guidelines do not suggest this, and I also highly recommend that you stay with those guidelines. 

It uses the `DrawerLayout` but the `MaterilaDrawer` also just uses the `DrawerLayout`. If you keep the default behavior the `DrawerLayout` will be in the root (as in the SO question) with `fitsSystemWindows=true`

**Comment by mikepenz** [comment]
I assume this is no issue related to the `MaterialDrawer` but more to the hirachy how it's set up and the default behavior of the `DrawerLayout` from google
