### ISSUE TITLE
Custom View

### ISSUE THREAD

**Issue by jhmacdon** [mikepenz/MaterialDrawer#1216]
Hi,

I am trying to create a custom layout for a sticky footer and having some troubles. I followed the help you gave in #1078, but the links you gave to stackoverflow answers do not work either (http://stackoverflow.com/a/32542999/3704560, http://stackoverflow.com/a/32543209/3704560) getting problems such as "AbstractDrawerItem" taking two arguments not just one. Also the method "getType" should return an Int, not a String? 

Thanks

**Comment by mikepenz** [comment]
@jhmacdon yeah those changed slightly but in general it's the same. Just have a look at any implement `Item` of the drawer.
https://github.com/mikepenz/MaterialDrawer/tree/develop/library/src/main/java/com/mikepenz/materialdrawer/model
https://github.com/mikepenz/MaterialDrawer/tree/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems

Beside this. You can also just provide any view or layout to the `StickyFooter` it must not be an item

**Comment by jhmacdon** [comment]
Yes I tried just passing a different layout to the stickyfooter but it expanded to fill the parent, even when giving it a height of 50dp.

**Comment by mikepenz** [comment]
Weird. :/

Also with a layout like this one: https://github.com/lh123/volunteer/blob/cad083101a698489e0cb92299888c7f35243db4f/app/src/main/res/layout/navigation_foot.xml ?
