### ISSUE TITLE
Sticky footer's padding

### ISSUE THREAD

**Issue by shimika** [mikepenz/MaterialDrawer#1218]
I try to set sticky footer with custom layout.

This is my xml's rendering result.

![2016-04-25 17 38 47](https://cloud.githubusercontent.com/assets/4963314/14778445/f231492e-0b0d-11e6-808d-84e64f2cd966.png)

But result is this.

<img width="345" alt="2016-04-25 17 47 14" src="https://cloud.githubusercontent.com/assets/4963314/14778458/fcd32474-0b0d-11e6-8731-3dedbec81ba5.png">

Summary: I want to set two text fit to left, but drawer make padding inside.
but root layout's background color is fully filled.

My xml is like this.

```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/layout_manager"
        android:layout_width="match_parent"
        android:layout_height="71dp"
        android:background="@color/gray">
  <View
          android:layout_width="match_parent"
          android:layout_height="1dp"
          android:background="@color/light"
          android:alpha="0.3"/>
  <RelativeLayout
          android:layout_marginTop="1dp"
          android:layout_width="match_parent"
          android:layout_height="70dp">
    <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            android:layout_toEndOf="@+id/layout_avatar"
            android:layout_toStartOf="@+id/image_setting"
            android:layout_marginEnd="10dp"
            android:layout_marginTop="15dp">
      <TextView
              android:id="@+id/manager_name"
              android:layout_width="wrap_content"
              android:layout_height="wrap_content"
              android:text="Hello"
              android:textColor="@color/white"
              android:singleLine="true"
              android:textStyle="bold"
              android:textSize="15sp"/>
      <TextView
              android:id="@+id/channel_manager_name"
              android:layout_width="wrap_content"
              android:layout_height="wrap_content"
              android:layout_marginTop="2dp"
              android:alpha="0.5"
              android:text="Hello"
              android:singleLine="true"
              android:textColor="@color/white"
              android:textSize="14sp"/>
    </LinearLayout>
    <ImageView
            android:id="@+id/image_setting"
            android:layout_width="24dp"
            android:layout_height="24dp"
            android:layout_alignParentEnd="true"
            android:layout_marginTop="22dp"
            android:layout_marginEnd="20dp"
            android:layout_marginBottom="24dp"
            android:src="@drawable/settings_w_50"/>
  </RelativeLayout>
</RelativeLayout>
```

RelativeLayout's android:background="@color/gray" is fully rendered, but
content has a margin that I don't want to have.

I try to get LayoutParams and set margin 0, and itemView.setPadding to 0 but not effected.

**Comment by mikepenz** [comment]
@shimika you have created a custom `DrawerItem` or do you provide a xml resource, or view to the `StickyFooter`?

**Comment by shimika** [comment]
@mikepenz I make a custom DrawerItem extends BaseDrawerItem

**Comment by shimika** [comment]
If I put DrawerItem to addDrawerItems not addStickyDrawerItems, It seems perfectly.

**Comment by mikepenz** [comment]
@shimika yes there is a method in the `MaterialDrawer` setting the padding for drawerItems in the footer because Material Design Guidelines state 8dp. This method is required as API 17 has a bug and looses the padding otherwise. 

the only solution here is that you do not provide your item as `DrawerItem` but just the layout, or view

**Comment by shimika** [comment]
I make a ViewGroup and solve the problem.
Thanks

**Comment by mikepenz** [comment]
Oh great :) Good point. Thanks
