### ISSUE TITLE
ProfileDrawerItem icon resized incorrectly

### ISSUE THREAD

**Issue by rubengees** [mikepenz/MaterialDrawer#1219]
When I built the sample App for the other Bug(?) I reported, I noticed something else which might be of interest for you. I don't know if this belongs to Iconics or MaterialDrawer but here is what happens:

![screenshot_20160425-191836](https://cloud.githubusercontent.com/assets/8021265/14792551/0cd0160e-0b1b-11e6-913d-b443a945f6c4.png)
![screenshot_20160425-191841](https://cloud.githubusercontent.com/assets/8021265/14792550/0ccd7d90-0b1b-11e6-8e39-72e8e164090e.png)

As you can see, the image resizes when I open the account settings.

The `PrimaryDrawerItem` is instantiated as follows:

```java
new ProfileDrawerItem()
    .withName("Guest")
    .withIcon(new IconicsDrawable(context, GoogleMaterial.Icon.gmd_person)
                  .colorRes(R.color.md_white_1000))
    .withIdentifier(HEADER_ID_GUEST));
```

This does not happen in any real life Apps of me, but if you are interested nevertheless I can upload the sample App.

**Comment by mikepenz** [comment]
@rubengees it might come because you have not defined a size for the `Icon` you should always define an explicit size for the `IconicsDrawable`

**Comment by rubengees** [comment]
Ah okay makes sense. Maybe thats something were the api could be expanded.
I did create a IconicsDrawable myself because I wanted to customize color. If that is not possible maybe something like `withIconColor` would be good?

**Comment by rubengees** [comment]
Nevermind, did not read your answer correctly.
Thanks for the quick answer as always!

**Comment by mikepenz** [comment]
Oh ok :D just was in the progress of answering. 

No problem ;)
