### ISSUE TITLE
With MiniDrawer and profile item, main drawer item may goes into disabled state

### ISSUE THREAD

**Issue by yunarta** [mikepenz/MaterialDrawer#1221]
I have a mini drawer and profile item.
The steps are:
1. From mini drawer, click profile item
2. Main drawer is shown with account selection
3. Press arrow up to close account menu
4. Main drawer is not showing PrimaryDrawerItem
5. But they are not clickable

After tracing with Android Monitor, i found that all the PrimaryDrawerItem LayoutManager are disabled.

Quick fix right now is adding
`viewHolder.view.setEnabled(true);`

While it does work, I still wonder if i do the right thing.
Let me know what you think.

**Comment by mikepenz** [comment]
@yunarta you just use default items? 

For 4. are the PrimaryDrawerItems showing or not? I am a bit confused because of the 'but' in 5.

**Comment by mikepenz** [comment]
@yunarta just tried this in the smaple app and is reproduceable. Will debug this one tomorrow

**Comment by yunarta** [comment]
Oh. Forgive me for the confusing coming from typo.
4. Main drawer is now showing PrimaryDrawerItem
5. But they are not clickable

:)

While i have the fix by setting setEnabled in PrimaryDrawerItem, but i still wondering where the setEnabled(false) is happening.

That's the reason i don't create pull request for this one yet.

**Comment by mikepenz** [comment]
@yunarta I found the reason for this issue. It comes from here: 
https://github.com/mikepenz/Crossfader/blob/develop/library/src/main/java/com/mikepenz/crossfader/view/CrossFadeSlidingPaneLayout.java#L69 
Were I will disable all views of the normal drawer as content area of the `Crossfader` would otherwhise pass trough the click events, and trigger actions on the drawer. 

I also found a good solution for this and will include it in the next update
