### ISSUE TITLE
prevent the closure of the drawer on item click

### ISSUE THREAD

**Issue by soheilserver** [mikepenz/MaterialDrawer#1222]
when i click on one of the items, the drawer gets closed, but i don't want such behavior. how to prevent the closure of the drawer on item click?
thanx

**Comment by mikepenz** [comment]
@soheilserver you can disable it for all. Otherwhise you just return `true` inside the click listener to **consume** the event.

**Comment by soheilserver** [comment]
I return true but it gets closed. why?

**Comment by soheilserver** [comment]
> @soheilserver you can disable it for all. Otherwhise you just return true inside the click listener to consume the event.
so how is it possible to disable it for all? thank you

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1042

**Comment by soheilserver** [comment]
thanx ;)
