### ISSUE TITLE
bring icon in right of text in rtl drawer

### ISSUE THREAD

**Issue by RezaOruji** [mikepenz/MaterialDrawer#1223]
is there any way to bring icon in right of text in drawer when using `withDrawerGravity(Gravity.RIGHT)` in drawer ?

**Comment by mikepenz** [comment]
@RezaOruji no. The icon will only be in the right in true `RTL` mode. If you want the icon on the right you will have to implement your own `CustomDrawerItem` 

https://github.com/mikepenz/MaterialDrawer/issues?utf8=%E2%9C%93&q=CustomDrawerItem
http://stackoverflow.com/questions/32066618/materialdrawer-customdraweritem/32543209#32543209
http://stackoverflow.com/questions/31030595/how-to-customize-the-draweritem-using-the-lib-mikepenz-materialdrawer/32542999#32542999

(Note the stackoverflow questions have the old interface of the `IDrawerItem`. You will also see a few custom ones in the sample app: https://github.com/mikepenz/MaterialDrawer/tree/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems)
