### ISSUE TITLE
MaterialDrawer with tabLayout

### ISSUE THREAD

**Issue by moderateepheezy** [mikepenz/MaterialDrawer#1225]
I have been able to succesfully use the library in my project, but i get the error, how cani fix it 

 java.lang.ClassCastException: android.support.v4.widget.DrawerLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams

**Comment by mikepenz** [comment]
@moderateepheezy please provide a bit more information. Or the full crash log. With the above I can't really say anything

**Comment by moderateepheezy** [comment]
I have been able to fix the issue, however i need something else.

how can i add image from url with Glide in this method 

.addProfiles(
                        new ProfileDrawerItem().withName(fullnames).withEmail(emails).withIcon(getResources().getDrawable(R.drawable.placeholder))
                )

**Comment by mikepenz** [comment]
@moderateepheezy you can either define an `url` for the `ProfileDrawerItem` or a drawable, there is no possibility for both. You can define the placeholder in a differnet location. 

Please see here:
https://github.com/mikepenz/MaterialDrawer#load-images-via-url
