### ISSUE TITLE
How to set selected profile when creating AccountHeader?

### ISSUE THREAD

**Issue by rmunk** [mikepenz/MaterialDrawer#1226]
When creating `AccountHeader` using `AccountHeaderBuilder` there is no `withSelectedItem()` method like in `DrawerBuilder`. 
I tried creating `ProfileDrawerItem` list and setting selected item using `withSetSelected(true)` to only second item but when the drawer is created first profile in the list is always selected by default regardless of `mSelected` field values.

**Comment by mikepenz** [comment]
@rmunk there is the `setSelectedProfile` method on the `AccountHeader`
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L181

Just select the correct profile after building:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L216

**Comment by rmunk** [comment]
Thanks, I don't know how I missed that 👍
