### ISSUE TITLE
Can not make it working in compile 'com.android.support:design:23.1.1'

### ISSUE THREAD

**Issue by Mahmudul531** [mikepenz/MaterialDrawer#1230]
It not build when my support design level is 23.1.1. 
Always it checking 23.3.0 
Can you please check this and let inform me how to fix without upgrade my design level.

**Comment by mikepenz** [comment]
@Mahmudul531 because the library depends on **v23.3.0** of the support libraries. 

If you want to use previous versions I do not give support if bugs occur. And you should also check Stackoverflow on how to exclude a specific dependency of a library..

http://stackoverflow.com/a/20016971/325479

**Comment by Mahmudul531** [comment]
@mikepenz  Thank you. I've got it working on your suggestion.
