### ISSUE TITLE
[MiniDrawer][withOnAccountHeaderListener] Updating drawer items within withOnAccountHeaderListener

### ISSUE THREAD

**Issue by sarvajeet294** [mikepenz/MaterialDrawer#1231]
When drawer is closed, icons of drawer items doesn't seem to be changed even if the list of drawer items is changed
When I try to remove/add drawer items within withOnAccountHeaderListener, items are seems to be changed when the drawer is open. But as soon as the drawer is closed, all the previous icons are shown. 

I would appreciate if you can provide an example which shows this kind of thing done.

```java
.withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean current) {
                        //sample usage of the onProfileChanged listener
                        //if the clicked item has the identifier 1 add a new profile ;)
                        /*if (profile instanceof IDrawerItem && ((IDrawerItem) profile).getIdentifier() == PROFILE_SETTING) {
                            IProfile newProfile = new ProfileDrawerItem().withNameShown(true).withName("Batman").withEmail("batman@gmail.com").withIcon(getResources().getDrawable(R.drawable.profile5));
                            if (headerResult.getProfiles() != null) {
                                //we know that there are 2 setting elements. set the new profile above them ;)
                                headerResult.addProfile(newProfile, headerResult.getProfiles().size() - 2);
                            } else {
                                headerResult.addProfiles(newProfile);
                            }
                        }*/
                        if(profile.getIdentifier()==1){
                            result.removeAllItems();
                            result.addItem(new PrimaryDrawerItem().withName(R.string.drawer_item_compact_header).withIcon(GoogleMaterial.Icon.gmd_sun).withIdentifier(1));
                            result.addItem(new PrimaryDrawerItem().withName(R.string.drawer_item_action_bar_drawer).withIcon(FontAwesome.Icon.faw_home).withBadge("22").withBadgeStyle(new BadgeStyle(Color.RED, Color.RED)).withIdentifier(2).withSelectable(false));
                        }
                        else {
                            result.removeAllItems();
                            result.addItem(new PrimaryDrawerItem().withName(R.string.drawer_item_multi_drawer).withIcon(FontAwesome.Icon.faw_gamepad).withIdentifier(3));
                            result.addItem(new SecondaryDrawerItem().withName(R.string.drawer_item_contact).withIcon(GoogleMaterial.Icon.gmd_format_color_fill).withTag("Bullhorn"));
                        }



                        //false if you have not consumed the event and it should close the drawer
                        return true;
                    }
                })
```

**Comment by mikepenz** [comment]
@sarvajeet294 the issue is in the `MiniDrawer`? Or does the normal drawer show wrong items? 

If it's the `MiniDrawer` you just need to call the following method:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L401

This will recreate the `MiniDrawer` with the new items from the main `Drawer`

**Comment by sarvajeet294** [comment]
Thank you so much. It worked.

**Comment by sarvajeet294** [comment]
Another quick question,
Can you point me in the right direction to update the data from database in the views of a fragment, when we change the Profile Item (Account Header)?

**Comment by mikepenz** [comment]
@sarvajeet294 sorry this is not related to this library. You have the listeners and then you can do whatever action is needed  in your app.

**Comment by sarvajeet294** [comment]
No problem. Thanks

**Comment by OuterObsessionSoftware** [comment]
> @sarvajeet294 the issue is in the `MiniDrawer`? Or does the normal drawer show wrong items?
> 
> If it's the `MiniDrawer` you just need to call the following method:
> https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L401
> 
> This will recreate the `MiniDrawer` with the new items from the main `Drawer`

If anyone is reading this now, the method to call is createItems();

For example myMiniDrawer.createItems();

It should work the same in Kotlin but I haven't tested.

Also if you aren't removing any items you can just use updateItem(identifier); instead :)
