### ISSUE TITLE
CrossfadeDrawerLayout Class is not available

### ISSUE THREAD

**Issue by TurKurT656** [mikepenz/MaterialDrawer#1232]
hi, i tried to implement CrossFader just like your sample app:
CrossfadeDrawerLayout cfdl = (CrossfadeDrawerLayout) result.getDrawerLayout();

but there is no such class.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/build.gradle#L70

It's an external library. Which is used here.
