### ISSUE TITLE
.withXyz returns false object

### ISSUE THREAD

**Issue by auchri** [mikepenz/MaterialDrawer#1233]
After upgrading to 5.2.1, all `.withXXX` methods (e.g. `withIdentifier`) are returning the false object for the SecondaryDrawerItem.

`SecondaryDrawerItem test = new SecondaryDrawerItem().withIdentifier(4);`

-> Error, `withIdentifier` returns `PrimaryDrawerItem` instead of `SecondaryDrawerItem`

**Comment by mikepenz** [comment]
@auchri the `SecondaryDrawerItem()` extends from the `PrimaryDrawerItem()` and has the same methods. Will it crash or fail on your side?

**Comment by auchri** [comment]
No, but I was using something like this:

`SecondaryDrawerItem test = new SecondaryDrawerItem().withIdentifier(4);`

which was broken after the update (of course).

I changed my code and it's working now.

**Comment by mikepenz** [comment]
@auchri and if you cast it?
