### ISSUE TITLE
wrong height for header/sticky header

### ISSUE THREAD

**Issue by multivoltage** [mikepenz/MaterialDrawer#1236]
I tried some solutions to show an header. I call:
`View v = getLayoutInflater().inflate(R.layout.my_lin_layout,null);`

This xml has a simple LinearLayout (200dp height), with an ImageView inside it.
Drawer header become bigger at runtime. I tried also withStickyHeader, but there is same problem

**Comment by mikepenz** [comment]
@multivoltage if you define those 200dp for the `LinearLayout` and `ImageView` will it then work? You can also just provide the `R.layout.my_lin_layout` no need to get the view first

**Comment by multivoltage** [comment]
Yes it works. Maybe I wrong some params in xml, or maybe because of support lib. Today with a little update I noticed a lot of changes/bugs.
