### ISSUE TITLE
how can handle click on disabled items

### ISSUE THREAD

**Issue by DJafari** [mikepenz/MaterialDrawer#1237]
hi
i want handle click on disabled items to show reason of disabled to user, how can do it ?

thanks

**Comment by mikepenz** [comment]
@DJafari disabled items do not trigger the listener so can't be done. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BasePrimaryDrawerItem.java#L66

You would have to implement your own item which does not get disabled, so you still get the event and then you could handle that action

**Comment by DJafari** [comment]
ok thanks for your quick reply 👍
