### ISSUE TITLE
Customizing the "burger" icon

### ISSUE THREAD

**Issue by Goobb** [mikepenz/MaterialDrawer#1240]
Hi,
I have some images for the different icons including the drawable's burger.
They all have the same shape, size, colors.
The problem is that even if the resources have the exact same size, the burger icon is merely twice as large as the other icons of the actionbar (menu items on the right of the ActionBar)

How can i manage the burger icon size please ?

**Comment by mikepenz** [comment]
@Goobb sorry this is not related to this library. The `ActionBarDrawerToggle` comes from google and is just used in this project. 

You can disable to use the `ActionBarDrawerToggle` just by removing the `withToolbar()` from the `DrawerBuilder` but then you will have to handle open/close completely on your own. 

You might find enough answers on StackOverFlow on how to modify the Hamburger icon

**Comment by Goobb** [comment]
ok, then maybe i can customize it without removing your library's use of it ? (it would be a shame to rewrite the thing you've already done ^^)
this is really a graphical "issue" , i'll seek a solution 4 that
and good job for the lib ^^

**Comment by mikepenz** [comment]
@Goobb I don't think that the `ActionBarDrawerToggle` can be custimized to show a different icon.
