### ISSUE TITLE
Account header image fails to load URL and displays the default drawable

### ISSUE THREAD

**Issue by beta** [mikepenz/MaterialDrawer#1241]
When the account header is clicked, the user will be navigated to an EditInfoActivity and edit his/her info. After returning back from that activity, the user's info will be fetched again and the account header will be updated. However sometimes the header image fails to load from the avatar URL (which is a valid URL) and displays a default drawable. Here's a screenshot:

![Screenshot](https://cloud.githubusercontent.com/assets/5000910/14976719/b22889da-1140-11e6-8057-63f596f8425e.jpg)

I'm holding the sole `ProfileDrawerItem` as a field of the activity for easily updating. Here's how I'm updating the header:

```java
if (profileDrawerItem == null) {
    profileDrawerItem = new ProfileDrawerItem()
            .withName(currentUser.nickName)
            .withEmail(currentUser.userName);
    
    if (currentUser.avatarUrl != null) {
        profileDrawerItem.withIcon(currentUser.avatarUrl);
    } else {
        profileDrawerItem.withIcon(getResources().getDrawable(R.color.grey_200));
    }
    
    drawerAccountHeader.clear();
    drawerAccountHeader.addProfiles(profileDrawerItem);
} else {
    profileDrawerItem.withName(currentUser.nickName)
            .withEmail(currentUser.userName);
    
    if (currentUser.avatarUrl != null) {
        profileDrawerItem.withIcon(currentUser.avatarUrl);
    } else {
        profileDrawerItem.withIcon(getResources().getDrawable(R.color.grey_200));
    }
    
    drawerAccountHeader.updateProfile(profileDrawerItem);
}
```

The image won't always fail to load. Actually it's very rare, but once it fails it will never display the avatar since then unless the app is exited and run again. The name and email fields of the header will always update to the latest value correctly, but the image just won't. Anyone got any idea how to debug and solve this problem?

PS: the DrawerImageLoader is initialized with Glide in the application class and I'm wondering where the default drawable (a pink person icon on the blue background) is loaded:

```java
DrawerImageLoader.init(new AbstractDrawerImageLoader() {
    @Override
    public void cancel(ImageView imageView) {
        Glide.clear(imageView);
    }
    
    @Override
    public Drawable placeholder(Context context, String tag) {
        return new ColorDrawable(context.getResources().getColor(R.color.grey_200));
    }
    
    @Override
    public void set(ImageView imageView, Uri uri, Drawable placeholder) {
        Glide.with(imageView.getContext()).load(uri).placeholder(placeholder).into(imageView);
    }
});
```

**Comment by mikepenz** [comment]
@beta seems like a behavior from glide, as the `MaterialDrawer` itself does not manage or handle the images. It just links through the different callbacks. 

Reasons why it may fail sometimes:
- image to large and can't be applied
- phone connection bad
- server connection issues

The process for updating is correct. For the fallback behavior you could use the "placeholder" function of the `DrawerImageLoader` which will get called before the web image is loaded.


The default image is here configured:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/util/DrawerUIUtils.java#L90

And is used by default in the `AbstractDrawerImageLoader` here:
https://github.com/mikepenz/MaterialDrawer/blob/355f1dd99484192c7fbdb228ea94fb3cef585b1f/library/src/main/java/com/mikepenz/materialdrawer/util/AbstractDrawerImageLoader.java#L22

**Comment by beta** [comment]
@mikepenz Glide works perfectly and something strange happened. Every time I click on a drawer item and switch to another fragment, and navigate to another activity and come back (so that `drawerAccountHeader.updateProfile(profileDrawerItem)` is called), the header image will just get lost (I've never tested this way before).

So I traversed up the code and found something in class [`ImageHolder`](https://github.com/mikepenz/Materialize/blob/develop/library/src/main/java/com/mikepenz/materialize/holder/ImageHolder.java#L96):

```
public boolean applyTo(ImageView imageView, String tag) {
    if (mUri != null) {
        imageView.setImageURI(mUri);
        /*
        if ("http".equals(mUri.getScheme()) || "https".equals(mUri.getScheme())) {
            DrawerImageLoader.getInstance().setImage(imageView, mUri, tag);
        } else {
        }
        */
```

**Comment by beta** [comment]
But I'm not quite sure why the error will happen only after I perform a fragment switch. `drawerAccountHeader.updateProfile(profileDrawerItem)` should be called whenever navigated back from another activity. I'll have a look at the fragment switch to find if there's anything wrong with it.

**Comment by beta** [comment]
Well I think I've solved the problem. As I've mentioned above clicking on drawer items will perform a fragment switch which will make the `imageView.getContext()` in the `DrawerImageLoader`'s initialization confused. IMHO the detached fragment interferes with the image loader but I'm not sure why. After changing it to `getApplicationContext()` the header image will never disappear.

**Comment by sandeeplondhe** [comment]
this is crap. the image is showing everywhere in the app but not in drawer header due to this crap code.
