### ISSUE TITLE
Prevent auto-selection of clicked items

### ISSUE THREAD

**Issue by toastking42** [mikepenz/MaterialDrawer#1242]
When a drawer item is selected, the corresponding DrawerItemClickedListener is called and the clicked item is highlighted to mark it as 'selected'.

I have a 'share' button as one of my DrawerItems and I don't want this specific item to be highlighted when it's being selected by the user. Instead, I want the last drawer item that was highlighted to keep being highlighted. But I do need the DrawerItemClickedListener to be called to create the share intent.

How do I achieve this behavior without having to manually keep the last selected item position in a class member? Unfortunately, the 'share' drawer item is being selected before the onclick-method is called, so I can't get the 'current state' of the drawer and therefore I don't know which item has been selected prior to the click on the 'share' button (I would only be able to achieve that if I track every click).

**Comment by mikepenz** [comment]
@toastking42 have you checked the sampe application? It has exactly this behavior for all items which launch an activity. 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L118

Just define `withSelectable(false)`
