### ISSUE TITLE
how to change default toolbar icon ?

### ISSUE THREAD

**Issue by RezaOruji** [mikepenz/MaterialDrawer#1243]
i want to assign a button in toolbar to material drawer toggle instead of default hamburger icon.
is there any way to do that ?
thanks

**Comment by mikepenz** [comment]
@RezaOruji I use the default `ActionBarDrawerToggle` by default. This does not allow you to define a different icon. You can stop providing the `Toolbar` to the `DrawerBuilder` so I won't handle this for you, and you will be able to implement any open/close logic, and any icon in the `Toolbar` you want and need
