### ISSUE TITLE
After changing status bar color, status bar on drawer is no longer translucent

### ISSUE THREAD

**Issue by Sekhmet** [mikepenz/MaterialDrawer#1247]
Hi,
after launching app status bar on drawer is translucent, but after I change color of it with `Window.setStatusBarColor` drawer is no longer translucent and has that color even when opened.
Is there a way to reload drawer so it will be translucent again?

Thanks.

**Comment by mikepenz** [comment]
@Sekhmet you should not set the `StatusBarColor` on the `Window` you can do that on the `DrawerLayout` which is accessible via the `Drawer` object

**Comment by Sekhmet** [comment]
It works like a charm!
I thought that is the proper way of doing it. Sorry and thanks for help and amazing project.
