### ISSUE TITLE
Close ExpandableDrawerItem()

### ISSUE THREAD

**Issue by RafaelCamarda** [mikepenz/MaterialDrawer#1248]
Hey Mike there is anyway to close a expandable? 

Always when I open the drawer, open the expandable and close the drawer, the next time I open the drawer the expandable item is openned.

**Comment by mikepenz** [comment]
@RafaelCamarda There is no way to automatically close it via a property if you ask for this. But you can hook intot he `DrawerListener` and `collapse` all expanded items when the drawer closes. 

The method to collapse all items can be found here:
`Drawer.getAdapter().collapse()`

**Comment by RafaelCamarda** [comment]
That is exactly what I want.

Thanks so much!

**Comment by mikepenz** [comment]
No problem :)
