### ISSUE TITLE
Custom header height

### ISSUE THREAD

**Issue by visualfanatic** [mikepenz/MaterialDrawer#1249]
This is my custom header layout:
```xml
<FrameLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	android:id="@+id/top"
	android:layout_width="match_parent"
	android:layout_height="50dp"
	android:background="#35383d">

	<TextView
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		android:gravity="center_vertical"
		android:textColor="#999"
		android:text="Test" />

</FrameLayout>
```

... and this is how I want to use it in my drawer:
```java
new DrawerBuilder()
	.withActivity(this)
	.withHeader(R.layout.header)
	.build();
```

As you can see, the root view has `50dp` height, but it is ignored by the library. To get the results I want, I either have to set height on `TextView` (I don't want that, because if there are going to be more views, I don't want to divide height for each view) or nest the `TextView` in another view and give it height, but this should work without using an additional view.

**Comment by mikepenz** [comment]
@visualfanatic you either have to set the height to the `TextView` or you create a different structure. I do not know why the `RecyclerView` can't calculate the height for those items.

**Comment by mikepenz** [comment]
@visualfanatic you can also set the header via the `Drawer` after building as this allows you to explicitely set the height. (with the next update you can also set the height via the DrawerBuilder)
