### ISSUE TITLE
Secondary Text as detailed info

### ISSUE THREAD

**Issue by ivangag** [mikepenz/MaterialDrawer#125]
Hi,
first of all thanks for the great work.
It would be nice to have the chance to enable a secondary text in the DrawerItem. I'm currently using another library and it allows this, even though i'm trying your library which i prefer..
Here an example:

![drawerwithsecondarytext](https://cloud.githubusercontent.com/assets/4865385/6712012/b4b06c0e-cd8a-11e4-89e5-2ff3ba4c8621.png)

Is there some chance to have that in the future?
Thanks.

**Comment by mikepenz** [comment]
@ivangag you can create any drawerItems you want :) The interface of the MaterialDrawer will allow you to create any list item you need or you prefer. 

So if you use the layout of the ProfileDrawerItem you will be able to create a PrimaryDrawerItemWithDescription ;). (I think the ProfileDrawerItem is only different to the normal items because it has a different height)
Just take a look at any of the pre-defined items. If you need help let me know.

**Comment by ivangag** [comment]
Thanks for a so fast enhancement!

**Comment by mikepenz** [comment]
@ivangag the new item is called PrimaryDescriptionDrawerItem ;)

**Comment by ivangag** [comment]
@mikepenz clear! Did you already put it in maven or i have to include it in my local repo?

**Comment by mikepenz** [comment]
@ivangag yeah it's in the newest version ;) v2.5.4

**Comment by ivangag** [comment]
@mikepenz nice i have just downloaded and included in my app!! Thanks

**Comment by ivangag** [comment]
@mikepenz i just tried your modification and i'm facing with text description size. 
if you agree you could modify the name of description text dimension in order to be different that primary text, let's me say for instance:

```
....
@dimen/material_drawer_item_profile_description_text
.....
```
In this way i can override that and change the text size of the description field only.
Thanks!

**Comment by mikepenz** [comment]
The font has a different type in the second line. 

So does it work with the above line?

**Comment by ivangag** [comment]
I mean to have the chance to modify only the size of description text, for instance having the name size 14sp and description size 12sp. Currently this is not possible. 
Thanks
