### ISSUE TITLE
Make sticky header shadow optional

### ISSUE THREAD

**Issue by visualfanatic** [mikepenz/MaterialDrawer#1250]
[This line](https://github.com/mikepenz/MaterialDrawer/blob/dffea0dad8f34423c8f047a91212744a5c02a521/library/src/main/java/com/mikepenz/materialdrawer/DrawerUtils.java#L206) makes setting the background for the sticky header's root view impossible without wrapping children with another view. I think the sticky header could have a flag, just like sticky footer has, for enabling/disabling the shadow underneath. Also I think it would be great to have an additional option to enable/disable divider below sticky header.

**Comment by mikepenz** [comment]
@visualfanatic you can modify the color via a theme, or if you overwrite the color. 

For the shadow and the divider I will have a look.
