### ISSUE TITLE
Drawer with a drawable Background

### ISSUE THREAD

**Issue by jehad-suliman** [mikepenz/MaterialDrawer#1251]
Thank you for this awesome Library 
 i only want to change the background of the Drawer and keep every thing else as it is.

i suggest 
`drawer.getDrawerLayout().getBackground().setBackgroundResource(R.drawable.dinner);`

**Comment by mikepenz** [comment]
Or you just use the method on the `DrawerBuilder`
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L384

**Comment by jehad-suliman** [comment]
Lolipop 5.0 this way is making the drawer slow and the background disappear sometimes 

OpenGLRenderer: Trying to scale down bitmap for texture 
Allocation failed for scaled bitmap

the UI stops 

the background size is 38.9 KB 

Can i load the background using Picasso ??

**Comment by mikepenz** [comment]
@jehad-suliman you can use picasso or anything else to set the `background` for the `DrawerLayout` 

You have the reference already via: `drawer.getDrawerLayout()`
