### ISSUE TITLE
Wrong api condition given for setForeGround() 

### ISSUE THREAD

**Issue by rranjithkumar100** [mikepenz/MaterialDrawer#1253]
In AccountHeaderBuilder.java -> handleSelectionView() method
//wrong condition here
```
 if (Build.VERSION.SDK_INT >= 21) {
       mAccountHeaderContainer.setForeground(UIUtils.getCompatDrawable(mAccountHeaderContainer.getContext(), mAccountHeaderTextSectionBackgroundResource));
}
```
**for other views setForeground available from above 23.** framelayout available from api 1.

so change this condtion to,
```

 if (Build.VERSION.SDK_INT >= 23) {
mAccountHeaderContainer.setForeground(UIUtils.getCompatDrawable(mAccountHeaderContainer.getContext(), mAccountHeaderTextSectionBackgroundResource));
....
....
}
```

**Comment by mikepenz** [comment]
@rranjithkumar100 no it is correct as implemented. The API decision here is not made because of the API level for ForeGround but for the API level of the `RippleDrawable`

**Comment by rranjithkumar100** [comment]
@mikepenz app crashed for me in lollipop 5.0.2. with this api condition.

**Comment by mikepenz** [comment]
Have you modified the header?

rranjithkumar100 <notifications@github.com> schrieb am Mo., 9. Mai 2016,
14:07:

> @mikepenz <https://github.com/mikepenz> app crashed for me in lollipop
> 5.0.2. with this api condition.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mikepenz/MaterialDrawer/issues/1253#issuecomment-217846833>
>
-- 
Mike Penz
__________________________________________
*Mike Penz*
Android | Backend | Open Source | Web Developer
mikepenz.com
lanora.io

**Comment by rranjithkumar100** [comment]
@mikepenz I am not modify anything.. App crashed at **setForeground(..)** line.

so I check that.. setForeground() available from api 23.

so after change this condition.. crashing issue fixed. 

so I am confused.

**Comment by mikepenz** [comment]
@rranjithkumar100 but this is a `FrameLayout`:
https://github.com/mikepenz/MaterialDrawer/blob/45bc7390cf8bca0e58ba4c51b2d92b9544e4fd23/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L728

**Comment by rranjithkumar100** [comment]
@mikepenz In framelayout setForeGround() available from API 1.

reference - http://developer.android.com/reference/android/view/View.html#setForeground%28android.graphics.drawable.Drawable%29

Then why  this following condition?

if (Build.VERSION.SDK_INT >= 21) {
}
