### ISSUE TITLE
By default first item is selected, though the item was created `withSelectable(false)`

### ISSUE THREAD

**Issue by rupeshsasne** [mikepenz/MaterialDrawer#1257]
If one does not calls `result.setSelection` explicitly, (referring to [this)](https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L213), by default the first item is being selected though it was created with `.withSelectable(false)`, is it a bug or I am using it wrong?

**Comment by mikepenz** [comment]
@rupeshsasne it is no bug. Programmatically you can still select each item in the list. `withSelectable(false)` will just prevent the user from selecting this item via a click. 

You should have a look here:
https://github.com/mikepenz/MaterialDrawer#how-can-i-create-a-drawer-without-a-default-selection
(You can also just define a different selection)
