### ISSUE TITLE
Is it possible to add fine prints below icons on mini drawer layout?

### ISSUE THREAD

**Issue by ruifeng2357** [mikepenz/MaterialDrawer#1258]
Is it possible to add fine prints below icons on a mini drawer as the screenshot?
Looking forward to your help. Thanks
Best Regards
![screenshot](https://cloud.githubusercontent.com/assets/10039825/15193629/731b02b0-17f1-11e6-9bbf-7e7eb450ad94.jpg)

**Comment by mikepenz** [comment]
@ruifeng2357 you can implement `CustomMiniDrawerItems` which look like the one in your screenshot. 

I think this answer: https://github.com/mikepenz/MaterialDrawer/issues/1150#issuecomment-205445293 and the answer linked in this one will help you

**Comment by ruifeng2357** [comment]
Ah, That makes sense. Thank you, @mikepenz
