### ISSUE TITLE
If onlye one item in drawer, this item is selected

### ISSUE THREAD

**Issue by alorma** [mikepenz/MaterialDrawer#126]
If i have only one item in the drawer, it's selected by default, but that'snot what i want.

![device-2015-03-18-165205](https://cloud.githubusercontent.com/assets/887462/6712882/49c35910-cd8f-11e4-90b6-2b734b9e08e4.png)

Any workaround that i can make to unselect this item, but still have it enabled to click?

**Comment by wildfatduck** [comment]
Similar question: is there some right way to init drawer with all items unselected? At the moment I am using .withItemSelected(some_big_int). By default selected item with id 0.

**Comment by alorma** [comment]
uuhmm, thanks

**Comment by mikepenz** [comment]
@alorma @wildfatduck yeah you can set the selection at the init with -1. This will deselect all items.

**Comment by wildfatduck** [comment]
@mikepenz I tried -1 to unselect all with setSelectionByIdentifier(), app is FC.

**Comment by mikepenz** [comment]
@wildfatduck ok will take a look. sorry that this causes a fc

**Comment by mikepenz** [comment]
@wildfatduck ok just saw you use the method setSelecitonByIdentifier. Try using the method 
`.withSelectedItem(-1)` on the builder.

**Comment by wildfatduck** [comment]
@mikepenz thanks!

**Comment by mikepenz** [comment]
@wildfatduck no problem ;)

**Comment by alorma** [comment]
Well... can it be considered as close? We need a workaround (use Integer.MAX_VALUE, seems to be a good option). But having .withItemSelectedByDefault(boolean) looks pretty :)

Sent by Gitskarios app

**Comment by mikepenz** [comment]
I think yes. Setting something with `-1` to disable it is a common pattern. So i would also give you the advice to do following: `.withSelectedItem(-1)`

**Comment by alorma** [comment]
Ok.

Maybe add this to README?

**Comment by mikepenz** [comment]
@alorma yes will add it to the README. So many functions :D Still a few are missing within the sample or the README but i try to improve it all the time. 

Thank you.
