### ISSUE TITLE
How to add, remove or update items in expandable subItems?

### ISSUE THREAD

**Issue by rezawm** [mikepenz/MaterialDrawer#1260]
Hey @Mikepenz, There is addItem(s) but how about Items in expandable? how to modify(Add, remove or update) them? I googled for it but I don't find any solution!

**Comment by rezawm** [comment]
Sorry Mike, I found it:
```
ExpandableDrawerItem myExpandable = new ExpandableDrawerItem().withName("Expandable Section").withSubItems();
Drawer myMaterialDrawer = new DrawerBuilder()
                .withActivity(this)
                .addDrawerItems( dariExpandable )
                .build();
myExpandable.getSubItems().add( new PrimaryDrawerItem().withName("SubItem Title") );
```
I really liked your library :+1:

**Comment by mikepenz** [comment]
@rezawm hi. 

Just get your parent item, add / remove / change the sub items, and then you can call the `notify` method on the adapter. 

The adapter can be retrieved via `Drawer.getAdapter()`

Here's the method you should call: `notifyAdapterSubItemsChanged(int globalPosition)`
https://github.com/sathishmscict/FastAdapter/blob/master/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1231

**Comment by sajon-cu** [comment]
I am using GenericFastItemAdapter class and here i didn't get the method notifyAdapterSubItemsChanged(int globalPosition)
