### ISSUE TITLE
item getName return null if item withName String set from String.xml!

### ISSUE THREAD

**Issue by rezawm** [mikepenz/MaterialDrawer#1261]
Dear @Mikepenz If I set primary item name from string xml file then my getName return null:
```java
myMaterialDrawer = new DrawerBuilder()
                .withActivity(this)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName( R.string.allNews )
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        if ( drawerItem instanceof PrimaryDrawerItem ){
                            PrimaryDrawerItem item = (PrimaryDrawerItem) drawerItem;
                            StringHolder itemName = item.getName();
                        }
                        return false;
                    }
                }).build();

```
But if I set withName for PrimaryDrawerItem a String, getName return the StringHolder, is it a bug or it's my coding problem?!

**Comment by mikepenz** [comment]
@rezawm that's weird. You are sure the event is not fired by something else? 

The code correctly sets the `StringHolder` no matter if you provide it via `String` or `int`-res

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDrawerItem.java#L99

**Comment by rezawm** [comment]
I checked withName with debugger:
```
    public T withName(@StringRes int nameRes) {
        this.name = new StringHolder(nameRes);
        return this;
    }
```
nameRes have value but name get null value after new StringHolder ... !

**Comment by mikepenz** [comment]
@rezawm to be honest. I do not know how this can be possible. because a `ctor` can't return null. it has to be set. do you overwrite it somewhere?

**Comment by mikepenz** [comment]
Haha I know probably know why you are confused. 

The `getName()` returns the `StringHolder` and it's `toString()` method returns "null" in this case, as it can't resolve the string without a `Context` 

If you do the following:
```java
((PrimaryDrawerItem) drawerItem).getName().getText(view.getContext())
```
You get the correct name
