### ISSUE TITLE
REMOVE MenuDrawer margin

### ISSUE THREAD

**Issue by Hassan99** [mikepenz/MaterialDrawer#1265]
http://stackoverflow.com/questions/37168281/remove-left-margin-from-materialdrawer

**Comment by mikepenz** [comment]
The drawer adds this `padding` because it is default for all items inside the `Material Design Guidelines`. As there is an issue with API 17 I have to set this programatically in this line:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BasePrimaryDrawerItem.java#L104

You might also want to post the `DrawerItem`s you use, as the screenshot does not look like you use the default items. 

If you already create your own `CustomDrawerItem` you just want to set the padding to 0px again (If you extend from the `BasePrimaryDrawerItem`) If you do not extend from it you should be fine. 

The drawer does not set this padding on the items anywhere else than here.

**Comment by Hassan99** [comment]
`public class SecondaryDrawerItemCentered extends BaseSecondaryDrawerItem<SecondaryDrawerItemCentered, SecondaryDrawerItemCentered.ViewHolder> implements ColorfulBadgeable<SecondaryDrawerItemCentered> {
    protected StringHolder mBadge;
    protected BadgeStyle mBadgeStyle = new BadgeStyle();
    protected int selected;

    public boolean visibleOrHide(View view) {
        if (selected > Constants.UNSELECTED && view != null) {
            return true;
        } else  {
            return false;
        }
        return false;
    }


    @Override
    public SecondaryDrawerItemCentered withBadge(StringHolder badge) {
        this.mBadge = badge;
        return this;
    }

    @Override
    public SecondaryDrawerItemCentered withBadge(String badge) {
        this.mBadge = new StringHolder(badge);
        return this;
    }

    public SecondaryDrawerItemCentered withSelected(int selected) {
        this.selected = selected;
        return this;
    }

    @Override
    public SecondaryDrawerItemCentered withBadge(@StringRes int badgeRes) {
        this.mBadge = new StringHolder(badgeRes);
        return this;
    }

    @Override
    public SecondaryDrawerItemCentered withBadgeStyle(BadgeStyle badgeStyle) {
        this.mBadgeStyle = badgeStyle;
        return this;
    }

    public int getWithSelected(int pos) {
        return this.selected;
    }

    public StringHolder getBadge() {
        return mBadge;
    }

    public BadgeStyle getBadgeStyle() {
        return mBadgeStyle;
    }

    @Override
    public int getType() {
        return R.id.lnrSecond_menu;
    }

    @Override
    @LayoutRes
    public int getLayoutRes() {
        return R.layout.second_menu_item;
    }

    @Override
    public void bindView(ViewHolder viewHolder) {
        Context ctx = viewHolder.itemView.getContext();
        bindViewHelper(viewHolder);
        boolean badgeVisible = StringHolder.applyToOrHide(mBadge, viewHolder.badge);
        boolean indicatorVisibility = visibleOrHide(viewHolder.view);

        if (badgeVisible) {
            mBadgeStyle.style(viewHolder.badge, getTextColorStateList(getColor(ctx), getSelectedTextColor(ctx)));
            viewHolder.badgeContainer.setVisibility(View.VISIBLE);
        } else {
            viewHolder.badgeContainer.setVisibility(View.GONE);
        }

        if (indicatorVisibility) {
            viewHolder.view.setVisibility(View.VISIBLE);
        } else {
            viewHolder.view.setVisibility(View.INVISIBLE);
        }


        if (getTypeface() != null) {
            viewHolder.badge.setTypeface(getTypeface());
        }

        onPostBindView(this, viewHolder.itemView);
    }

    @Override
    public ViewHolderFactory<ViewHolder> getFactory() {
        return new ItemFactory();
    }

    public static class ItemFactory implements ViewHolderFactory<ViewHolder> {
        public ViewHolder create(View v) {
            return new ViewHolder(v);
        }
    }

    protected static class ViewHolder extends BaseViewHolder {
        private View badgeContainer;
        private TextView badge;
        private View view;

        private ViewHolder(View view) {
            super(view);
            this.view = view.findViewById(R.id.view);
            this.badgeContainer = view.findViewById(R.id.material_drawer_badge_container);
            this.badge = (TextView) view.findViewById(R.id.txtMenuBadge);
        }
    }

}
`

this is the draweritem.

**Comment by mikepenz** [comment]
Your item still extends from the `BaseSecondaryDrawerItem` which will in the end also extend from the `BasePrimaryDrawerItem` which defines the padding at the end:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BasePrimaryDrawerItem.java#L104

You have to set the padding to 0dp after the `bindViewHelper(viewHolder);` 

```java
viewHolder.view.setPadding(0, 0, 0, 0);
```
