### ISSUE TITLE
Wrong header position when using withHeader/withStickyHeader

### ISSUE THREAD

**Issue by roughboy** [mikepenz/MaterialDrawer#1268]
I have compiled an example app from repo. I've slightly modified drawer builder in activity NonTranslucentDrawerActivity.java, just by adding header into it. The result is, the header is partly obscured with status bar - it should be positionod right below status bar. 
The problem was discovered in version 5.2.6. 
I  previously was using version 4.6.4 and everything was ok. 

![device-2016-05-15-191711](https://cloud.githubusercontent.com/assets/6866304/15275652/be4ff0dc-1ad1-11e6-8c68-bd622dbe1435.png)

Drawer builder code:
```java
    result = new DrawerBuilder()
            .withActivity(this)
            .withTranslucentStatusBar(false)
            .withHeader(R.layout.item_header)
            .addDrawerItems(
                    new PrimaryDrawerItem().withName(R.string.drawer_item_home).withIcon(FontAwesome.Icon.faw_home),
                    new PrimaryDrawerItem().withName(R.string.drawer_item_free_play).withIcon(FontAwesome.Icon.faw_gamepad),
                    new PrimaryDrawerItem().withName(R.string.drawer_item_custom).withIcon(FontAwesome.Icon.faw_eye),
                    new SectionDrawerItem().withName(R.string.drawer_item_section_header),
                    new SecondaryDrawerItem().withName(R.string.drawer_item_settings).withIcon(FontAwesome.Icon.faw_cog),
                    new SecondaryDrawerItem().withName(R.string.drawer_item_help).withIcon(FontAwesome.Icon.faw_question).withEnabled(false),
                    new SecondaryDrawerItem().withName(R.string.drawer_item_open_source).withIcon(FontAwesome.Icon.faw_github),
                    new SecondaryDrawerItem().withName(R.string.drawer_item_contact).withIcon(FontAwesome.Icon.faw_bullhorn)
            )
            .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                @Override
                public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                    if (drawerItem instanceof Nameable) {
                        Toast.makeText(NonTranslucentDrawerActivity.this, ((Nameable) drawerItem).getName().getText(NonTranslucentDrawerActivity.this), Toast.LENGTH_SHORT).show();
                    }
                    return false;
                }
            })
            .withSelectedItemByPosition(2)
            .withSavedInstance(savedInstanceState)
            .build();
```
The header layout:
```xml
    <?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content"
                  android:clickable="true"
                  android:orientation="vertical">

        <TextView
            android:id="@+id/name"
            android:layout_width="match_parent"
            android:layout_height="56dp"
            android:fontFamily="sans-serif-medium"
            android:gravity="center_vertical|start"
            android:lines="1"
            android:text="Header"
            android:paddingLeft="@dimen/material_drawer_vertical_padding"
            android:paddingRight="@dimen/material_drawer_vertical_padding"
            android:singleLine="true"/>

    </LinearLayout>
```

**Comment by mikepenz** [comment]
@roughboy what's the thame you are using?

**Comment by roughboy** [comment]
I didnt modified the theme its theme from the example. In manifest i see:

    <activity
        android:name=".NonTranslucentDrawerActivity"
        android:theme="@style/MaterialDrawerTheme" />
    <activity

MaterialDrawerTheme extends from MaterialTheme.

**Comment by mikepenz** [comment]
@roughboy you do not want the drawer to go below the `StatusBar` right?

should be fine. in the sample app it's done exactly like this:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/NonTranslucentDrawerActivity.java

**Comment by roughboy** [comment]
I want the header to go below the status bar. The problem is that the header is being partially covered by status bar  - that's an obvious error. I mark my actual header with the red line. My suspictions is that the height at which header should be drawn is wrongly defined somewhere in the library. Should be yellow height, and is green height - see attached screenshot.

![covered-header](https://cloud.githubusercontent.com/assets/6866304/15283257/6643330e-1b49-11e6-9c9e-4554a2a57697.jpg)

The sample app is not using header/sticky header - just add it to https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/NonTranslucentDrawerActivity.java and you will see the issue.

**Comment by mikepenz** [comment]
so just remove this: `.withTranslucentStatusBar(false)`

**Comment by roughboy** [comment]
I don't agree. In 4.6.4 it was working correctly, even with .withTranslucentStatusBar(false), so it is an OBVIOUS bug introduced between 4.6.4 and 5.2.6. If such configuration is forbidden, then it should be disabled somehow from the API level.

**Comment by mikepenz** [comment]
@roughboy with v5.0.0 there was a huge change in most behaviors as the MaterialDrawer no longer manages those paddings. This is done via the `fitsSystemWindows` flag which is handled by the system...

**Comment by roughboy** [comment]
Hey @mikepenz!
I found the root cause of the problem. It is caused be setting wrong padding, for sticky header and recyclerview in method:
    
    DrawerUtils.handleHeaderView(DrawerBuilder drawer) 

Can you fix it in the next release? I will be grateful!
The correct method should look like this:

        public static void handleHeaderView(DrawerBuilder drawer) {
        //use the AccountHeader if set
        if (drawer.mAccountHeader != null) {
            if (drawer.mAccountHeaderSticky) {
                drawer.mStickyHeaderView = drawer.mAccountHeader.getView();
            } else {
                drawer.mHeaderView = drawer.mAccountHeader.getView();
                drawer.mHeaderDivider = drawer.mAccountHeader.mAccountHeaderBuilder.mDividerBelowHeader;
                drawer.mHeaderPadding = drawer.mAccountHeader.mAccountHeaderBuilder.mPaddingBelowHeader;
            }
        }

        //sticky header view
        if (drawer.mStickyHeaderView != null) {
            //add the sticky footer view and align it to the bottom
            RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.MATCH_PARENT, RelativeLayout.LayoutParams.WRAP_CONTENT);
            layoutParams.addRule(RelativeLayout.ALIGN_PARENT_TOP, 1);
            drawer.mStickyHeaderView.setId(R.id.material_drawer_sticky_header);
            drawer.mSliderLayout.addView(drawer.mStickyHeaderView, 0, layoutParams);

            //now align the recyclerView below the stickyFooterView ;)
            RelativeLayout.LayoutParams layoutParamsListView = (RelativeLayout.LayoutParams) drawer.mRecyclerView.getLayoutParams();
            layoutParamsListView.addRule(RelativeLayout.BELOW, R.id.material_drawer_sticky_header);
            drawer.mRecyclerView.setLayoutParams(layoutParamsListView);

            //set a background color or the elevation will not work
            drawer.mStickyHeaderView.setBackgroundColor(UIUtils.getThemeColorFromAttrOrRes(drawer.mActivity, R.attr.material_drawer_background, R.color.material_drawer_background));

            // ==================FIXED===========================
            // ==================================================
            // top padding of sticky header should be set to the current padding of recycler view
            drawer.mStickyHeaderView.setPadding(0, drawer.mRecyclerView.getPaddingTop(), 0, 0);
            
            if (drawer.mStickyHeaderShadow) {
                //add a shadow
                if (Build.VERSION.SDK_INT >= 21) {
                    drawer.mStickyHeaderView.setElevation(UIUtils.convertDpToPixel(4, drawer.mActivity));
                } else {
                    View view = new View(drawer.mActivity);
                    view.setBackgroundResource(R.drawable.material_drawer_shadow_bottom);
                    drawer.mSliderLayout.addView(view, RelativeLayout.LayoutParams.MATCH_PARENT, (int) UIUtils.convertDpToPixel(4, drawer.mActivity));
                    //now align the shadow below the stickyHeader ;)
                    RelativeLayout.LayoutParams lps = (RelativeLayout.LayoutParams) view.getLayoutParams();
                    lps.addRule(RelativeLayout.BELOW, R.id.material_drawer_sticky_header);
                    view.setLayoutParams(lps);
                }
            }

            //remove the padding of the recyclerView again we have the header on top of it
            drawer.mRecyclerView.setPadding(0, 0, 0, 0);
        }

        // set the header (do this before the setAdapter because some devices will crash else
        if (drawer.mHeaderView != null) {
            if (drawer.mRecyclerView == null) {
                throw new RuntimeException("can't use a headerView without a recyclerView");
            }

            if (drawer.mHeaderPadding) {
                drawer.getHeaderAdapter().add(new ContainerDrawerItem().withView(drawer.mHeaderView).withHeight(drawer.mHeiderHeight).withDivider(drawer.mHeaderDivider).withViewPosition(ContainerDrawerItem.Position.TOP));
            } else {
                drawer.getHeaderAdapter().add(new ContainerDrawerItem().withView(drawer.mHeaderView).withHeight(drawer.mHeiderHeight).withDivider(drawer.mHeaderDivider).withViewPosition(ContainerDrawerItem.Position.NONE));
            }
            //set the padding on the top to 0
            // ==================FIXED===========================
            // ==================================================
            // changed top padding from 0 to drawer.mRecyclerView.getPaddingTop(), basicaly below line should be all removed
            drawer.mRecyclerView.setPadding(drawer.mRecyclerView.getPaddingLeft(), drawer.mRecyclerView.getPaddingTop(), drawer.mRecyclerView.getPaddingRight(), drawer.mRecyclerView.getPaddingBottom());
        }
    }

**Comment by mikepenz** [comment]
Hi @roughboy I just checked your code. It might work for your application, but this is not the proper solution for the MaterialDrawer. 

For the **StickyHeader** you explicitely set the padding of the `RecyclerView` also for the header which is not good, as the **StickyHeaderView** is completely independent from the `RecyclerView` and those paddings are not tight together. 

For the second padding you changed. Your line of code is unnecessary as you just set the padding of the `RecyclerView` back to the same values. The other thing is that it is correct to have 0dp padding for a normal header as the header should go up to the top of the `RecyclerView` the `RecyclerView` shouldn't go beyond the `StatusBar` if the `fitsSystemWindows` flags are set correctly

**Comment by mikepenz** [comment]
Close as you solved it for your case. In general the behavior shouldn't be such a problem
