### ISSUE TITLE
First item text and icon gone when setting selection programmatically. 

### ISSUE THREAD

**Issue by shalevmo** [mikepenz/MaterialDrawer#1269]
I have drawer that contains:
Custom header
A few items (6 to be precise) 
A sticky footer. 

The last item in the menu has logic, so sometimes if it's selected and it shouldn't be, I want to set the selection back to last item. 
I saved the last item identifier, and when I'm calling result.setSelection(lastItemIdentifier, false) the first item becomes blank (the text and icon are gone and the selection color isn't shown, just a white rectangle). 
It works good with the other items, the bug is just with the first item.

**Comment by mikepenz** [comment]
that sounds really strange. you just use normal `DrawerItems`?

**Comment by shalevmo** [comment]
Yes, but I changed the layout a bit if it matters.

**Comment by mikepenz** [comment]
Hmmm shouldn't necessarily. Can you provide some code to showcase your issue or provide a sample application?

**Comment by mikepenz** [comment]
@shalevmo close until new details are provided.
