### ISSUE TITLE
Material Drawer like gmail.

### ISSUE THREAD

**Issue by Grozny** [mikepenz/MaterialDrawer#127]
In gmail when I select the current profile, expands the list of profiles, right?
This profile no longer listed.
Is this possible?

**Comment by mikepenz** [comment]
@Grozny in gmail the active profile is not listed right. I think it makes more sense if the active profile is visible but selected. But should not be to much work to get both working.

**Comment by Grozny** [comment]
In the new method withCurrentProfileHiddenInList(true) of AccountHeader causes all items disappear. Please can you fix this bug.
You have done an excellent job.
Thanks.

**Comment by mikepenz** [comment]
@Grozny oh sorry. It worked on my phone. Will check it again.

**Comment by mikepenz** [comment]
Haha that was a stupid one. Tested it on my device was working. after that i built the `if` to do it :D Bad that i mixed up a `continue` with a `return` :D
