### ISSUE TITLE
public DrawerBuilder withSelectedItem(int selectedItemIdentifier) should use Long

### ISSUE THREAD

**Issue by roshakorost** [mikepenz/MaterialDrawer#1270]
`AbstractDrawerItem` has builder that uses long as identifier:
```java
public T withIdentifier(long identifier) {
        this.mIdentifier = identifier;
        return (T) this;
}
```
but drawer builder uses int as identifier, so you can set id bigger that max Int (less than max Long) to item and would be not able to select it using the builder.

**Comment by mikepenz** [comment]
@roshakorost you might want to do a pull request for this change

**Comment by roshakorost** [comment]
yes, I will do it.

**Comment by mikepenz** [comment]
Ok great. Thank you. I will merge as soon as I'm back from IO
