### ISSUE TITLE
Is it possible to disable drawer temporary for some page?

### ISSUE THREAD

**Issue by crestf** [mikepenz/MaterialDrawer#1272]
I want to ask something,
My app has condition which when in page A, the drawer is enabled and accessible with burger button in toolbar.
Then, when I move to page B, I want the drawer to temporary disabled (will not appear when I slide the edge of screen, or by pressing burger button/arrow button), and burger button will change into back arrow.
If then I move back to page A, the drawer will again enabled as it is before.
Changes from page A and B only replace fragments, and not changing activity, thus the drawer codes is not changed.

As for now, I managed to disable drawer lock mode, change the burger button into back arrow, but when I press the back arrow, it still shows navigation drawer.

Can I achieve this behavior?

Thanks and regards!

**Comment by mikepenz** [comment]
@crestf you are searching for the `DrawerLayout` feature called `LockMode` you can set a `LockMode` for a `Slider`-`View` or `Gravity` on the `DrawerLayout` which then blocks the user from opening it.

Here's the documentation for it:
https://developer.android.com/reference/android/support/v4/widget/DrawerLayout.html#setDrawerLockMode(int, int)

Ok just read that you already came along with the `LockMode` for the **Back-Arrow** to still toggle the `NavigationDrawer` how do you switch it to the `BackArrow`? You might want to check out the AdvancedSample which also switches from `Hamburger` to `Arrow` and the `Arrow` will close the activity in this case.
