### ISSUE TITLE
customize manage account section

### ISSUE THREAD

**Issue by HamedGh** [mikepenz/MaterialDrawer#1274]
Hello,
How can I customize the list that is shown when I click on the triangle icon? for example I don't want to see the current user's email( mikepenz@gmail.com) in the list.
![screen shot 2016-05-17 at 10 30 57](https://cloud.githubusercontent.com/assets/3388482/15312741/d77cbe28-1c1b-11e6-80ee-b57d559070bb.png)

**Comment by mikepenz** [comment]
@HamedGh for your question you can achieve this with the following setting:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L216

What else do you want to adjust?

**Comment by HamedGh** [comment]
thanks, I overrided the xml file and set it's height to 0dp :)) , now I should remove it!

**Comment by HamedGh** [comment]
I also want to add divider to this section. what should I do? I can't use `new DividerDrawerItem()`

**Comment by mikepenz** [comment]
@HamedGh hmmm to get a `Divider` inside the `Profile`s section the easiest would be to create an `item` similar to the `DividerDrawerItem` but it should also implement `IProfile`  so you can add it to the accounts too, and you just need to make it not selectable so it won't show up in the list

**Comment by HamedGh** [comment]
I try this code but it doesn't work!
`public class AccountDividerDrawerItem extends AbstractDrawerItem<ProfileDrawerItem, AccountDividerDrawerItem.ViewHolder> implements IProfile<ProfileDrawerItem>{
    @Override
    public int getType() {
        return com.mikepenz.materialdrawer.R.id.material_drawer_item_divider;
    }

    @Override
    @LayoutRes
    public int getLayoutRes() {
        return com.mikepenz.materialdrawer.R.layout.material_drawer_item_divider;
    }

    @Override
    public void bindView(ViewHolder viewHolder) {
        Context ctx = viewHolder.itemView.getContext();

        //set the identifier from the drawerItem here. It can be used to run tests
        viewHolder.itemView.setId(hashCode());

        //define how the divider should look like
        viewHolder.view.setClickable(false);
        viewHolder.view.setEnabled(false);
        viewHolder.view.setMinimumHeight(1);
        ViewCompat.setImportantForAccessibility(viewHolder.view,
                ViewCompat.IMPORTANT_FOR_ACCESSIBILITY_NO);

        //set the color for the divider
        viewHolder.divider.setBackgroundColor(UIUtils.getThemeColorFromAttrOrRes(ctx, com.mikepenz.materialdrawer.R.attr.material_drawer_divider, com.mikepenz.materialdrawer.R.color.material_drawer_divider));

        //call the onPostBindView method to trigger post bind view actions (like the listener to modify the item if required)
        onPostBindView(this, viewHolder.itemView);
    }

    @Override
    public ViewHolderFactory<ViewHolder> getFactory() {
        return new ItemFactory();
    }

    @Override
    public ProfileDrawerItem withName(String name) {
        return null;
    }

    @Override
    public StringHolder getName() {
        return null;
    }

    @Override
    public ProfileDrawerItem withEmail(String email) {
        return null;
    }

    @Override
    public StringHolder getEmail() {
        return null;
    }

    @Override
    public ProfileDrawerItem withIcon(Drawable icon) {
        return null;
    }

    @Override
    public ProfileDrawerItem withIcon(Bitmap bitmap) {
        return null;
    }

    @Override
    public ProfileDrawerItem withIcon(@DrawableRes int iconRes) {
        return null;
    }

    @Override
    public ProfileDrawerItem withIcon(String url) {
        return null;
    }

    @Override
    public ProfileDrawerItem withIcon(Uri uri) {
        return null;
    }

    @Override
    public ProfileDrawerItem withIcon(IIcon icon) {
        return null;
    }

    @Override
    public ImageHolder getIcon() {
        return null;
    }

    public static class ItemFactory implements ViewHolderFactory<ViewHolder> {
        public ViewHolder create(View v) {
            return new ViewHolder(v);
        }
    }

//    protected static class ViewHolder extends RecyclerView.ViewHolder {
//        private View view;
//        private ImageView profileIcon;
//        private TextView name;
//        private TextView email;
//        private View divider;
//
//        private ViewHolder(View view) {
//            super(view);
//            this.view = view;
//            this.divider = view.findViewById(com.mikepenz.materialdrawer.R.id.material_drawer_divider);
//            this.profileIcon = (ImageView) view.findViewById(com.mikepenz.materialdrawer.R.id.material_drawer_profileIcon);
//            this.name = (TextView) view.findViewById(com.mikepenz.materialdrawer.R.id.material_drawer_name);
//            this.email = (TextView) view.findViewById(com.mikepenz.materialdrawer.R.id.material_drawer_email);
//        }
//    }

    protected static class ViewHolder extends RecyclerView.ViewHolder {
        private View view;
        private View divider;

        private ViewHolder(View view) {
            super(view);
            this.view = view;
            this.divider = view.findViewById(com.mikepenz.materialdrawer.R.id.material_drawer_divider);
        }
    }
}
`

**Comment by mikepenz** [comment]
@HamedGh it is nearly correct. Just 2 things. First your item should also have the proper generic type defined for the `AbstractDrawerItem` which i have fixed for you here:

```java
public class AccountDividerDrawerItem extends AbstractDrawerItem<AccountDividerDrawerItem, AccountDividerDrawerItem.ViewHolder> implements IProfile<AccountDividerDrawerItem> {
    @Override
    public int getType() {
        return com.mikepenz.materialdrawer.R.id.material_drawer_profile_item_divider;
    }

    @Override
    @LayoutRes
    public int getLayoutRes() {
        return com.mikepenz.materialdrawer.R.layout.material_drawer_item_divider;
    }

    @Override
    public void bindView(ViewHolder viewHolder) {
        Context ctx = viewHolder.itemView.getContext();

        //set the identifier from the drawerItem here. It can be used to run tests
        viewHolder.itemView.setId(hashCode());

        //define how the divider should look like
        viewHolder.view.setClickable(false);
        viewHolder.view.setEnabled(false);
        viewHolder.view.setMinimumHeight(1);
        ViewCompat.setImportantForAccessibility(viewHolder.view,
                ViewCompat.IMPORTANT_FOR_ACCESSIBILITY_NO);

        //set the color for the divider
        viewHolder.divider.setBackgroundColor(UIUtils.getThemeColorFromAttrOrRes(ctx, com.mikepenz.materialdrawer.R.attr.material_drawer_divider, com.mikepenz.materialdrawer.R.color.material_drawer_divider));

        //call the onPostBindView method to trigger post bind view actions (like the listener to modify the item if required)
        onPostBindView(this, viewHolder.itemView);
    }

    @Override
    public ViewHolderFactory<ViewHolder> getFactory() {
        return new ItemFactory();
    }

    @Override
    public AccountDividerDrawerItem withName(String name) {
        return null;
    }

    @Override
    public StringHolder getName() {
        return null;
    }

    @Override
    public AccountDividerDrawerItem withEmail(String email) {
        return null;
    }

    @Override
    public StringHolder getEmail() {
        return null;
    }

    @Override
    public AccountDividerDrawerItem withIcon(Drawable icon) {
        return null;
    }

    @Override
    public AccountDividerDrawerItem withIcon(Bitmap bitmap) {
        return null;
    }

    @Override
    public AccountDividerDrawerItem withIcon(@DrawableRes int iconRes) {
        return null;
    }

    @Override
    public AccountDividerDrawerItem withIcon(String url) {
        return null;
    }

    @Override
    public AccountDividerDrawerItem withIcon(Uri uri) {
        return null;
    }

    @Override
    public AccountDividerDrawerItem withIcon(IIcon icon) {
        return null;
    }

    @Override
    public ImageHolder getIcon() {
        return null;
    }

    public static class ItemFactory implements ViewHolderFactory<ViewHolder> {
        public ViewHolder create(View v) {
            return new ViewHolder(v);
        }
    }

    protected static class ViewHolder extends RecyclerView.ViewHolder {
        private View view;
        private View divider;

        private ViewHolder(View view) {
            super(view);
            this.view = view;
            this.divider = view.findViewById(com.mikepenz.materialdrawer.R.id.material_drawer_divider);
        }
    }
}
```

And a second thing you might notice. I have chagned the `identifier` within the `getType()` method, because this has to be unique and can't be reused accross items. (Internal cache handling of the `RecyclerView`) Afterwards it works fine ;)

**Comment by HamedGh** [comment]
Thanks, It works 👍 ,I should mention( for who ever wants to use this code) that `com.mikepenz.materialdrawer.R.id.material_drawer_profile_item_divider;` is not exist and must replace with an arbitrary local `identifier` .

**Comment by HamedGh** [comment]
create `ids.xml` file in values directory and add this line to that:
`    <item name="material_drawer_profile_item_divider" type="id" />
`

**Comment by meddd** [comment]
Hi, It is posible to show only ADD ACCOUNT and MANAGE ACCOUNT describe in this issue

**Comment by mikepenz** [comment]
@meddd sure

**Comment by meddd** [comment]
Using .withCurrentProfileHiddenInList I only could hide first item.
When I have 3 profile, I couldnt hide second and third profile. I need to show fourth (ADD ACCOUNT) and fives (MANAGE).

**Comment by mikepenz** [comment]
You want to have the "add" in the header?

**Comment by meddd** [comment]
I woluld like to have in header only profile image, but when I choose arrow to switch account, i would like to get only ADD and MANAGE

**Comment by mikepenz** [comment]
you can set static values for the lines in the header, and just add no profiles at all to the account list.

**Comment by meddd** [comment]
thank you, I think about that.

**Comment by iToxicDeveloper** [comment]
@mikepenz hello mike, thanks for the awesome MaterialDrawer, how can i add items to the accounts list ? like the one Add account and Manage account ? mine is empty with a a single profile (current profile), 
and if its possible ,, how can i edit them ? to a Sign out and edit Email + and more items? i'm a begginner so please don't mind my silly questions :D and yeah a click listener would be fine too XD

**Comment by mikepenz** [comment]
@iToxicDeveloper please check out the sample application
