### ISSUE TITLE
Can we have both left and right drawer?

### ISSUE THREAD

**Issue by Shajeel-Afzal** [mikepenz/MaterialDrawer#1276]
Hi!

I want the activity to have both left and right navigation drawer, is that possible? Another question is that, can we set custom fragment on the navigation drawer item?

Thanks in Advance.

**Comment by mikepenz** [comment]
@Shajeel-Afzal 

Yes you can have a left and you can have a right `Drawer`. See the **MultiDrawerActivity** Sample for this:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MultiDrawerActivity.java

Yes you can also have a custom view on one of those drawers, obtain it and commit a fragment on it.
