### ISSUE TITLE
Mini drawer with multiple tabs

### ISSUE THREAD

**Issue by ArunPandiyan** [mikepenz/MaterialDrawer#1278]
I'm using mini drawer along side with fragment which opens a new fragment. (exactly as Gmail in Tablets) but when swiping in the tablayout or dragging the second fragment opens the mini-drawer.
How to make minidrawer to listen only on drawer?

**Comment by mikepenz** [comment]
@ArunPandiyan there is a different mode inside the `Crossfader` which can exactly do what you are searching for: https://github.com/mikepenz/Crossfader/blob/develop/library/src/main/java/com/mikepenz/crossfader/Crossfader.java#L52
