### ISSUE TITLE
Bug - Icon Colors

### ISSUE THREAD

**Issue by TurKurT656** [mikepenz/MaterialDrawer#128]
According to Material Design guidelines the icon colors should have an alpha value of 54% (#000000).
so this color must be default color of icons: #727272

**Comment by mikepenz** [comment]
@TurKurT656 right now the default set color is wrong that's true. you can overwrite it via code already :)

So 54% black would be: #8A000000

This post contains all `A`RGB values 
http://stackoverflow.com/a/25170174/325479
