### ISSUE TITLE
StatusBar Isn't Showing - Solved

### ISSUE THREAD

**Issue by Abo-Hani** [mikepenz/MaterialDrawer#1280]
Hello, I've just added this library, and taken the " DrawerActivity.java " class from the sample, along with the theme in the AndroidManiFest, and i'm having this weird problem where there's a big margin above the layout, and there's only a toolbar without a SystemBar. what the reason and how to solve this ?

* Margin problem solved, not library related.
* When adding TopMargin : 25dp the statusbar is shown ( as full view ) .

Image : http://i.imgur.com/aqFYCr1.png

**Comment by Abo-Hani** [comment]
It was caused by the FullScreen set flags, after removing them it's solved.

**Comment by mikepenz** [comment]
@Abo-Hani great that you solved your issue
