### ISSUE TITLE
Switching Activites Without Opening & Switching To Them

### ISSUE THREAD

**Issue by Abo-Hani** [mikepenz/MaterialDrawer#1281]
Hi again,
Using an old way for Material Drawer i was able to switch between Fragments / Activities without fully opening them, for example, i don't need to open that activity with the intent and a add MaterialDrawer builder to it. 

Yes, i'm too noobie in this library. I've 4 activites, already added to the Drawer, now to switch between them I have to add intent, and add Drawer builder to every activity, and whenever an item ( activity ) is clicked, there will be an ugly / un-smooth way to open it, which in my opinion is a wrong way to switch between actvities .

Can anyone hint me to the perfect way using this library ?

**Comment by mikepenz** [comment]
@Abo-Hani in general you should just have 1 drawer in your fist activity (only in some cases it makes sense to have drawers in sub activities) So in general your drawer should switch between `Fragments` if you want to keep everything in the upper hierarchy. If this shouldn't be the case in your application you can launch activities. 

So for the general "un-smooth" animation when opening activity and closing the drawer, you have to options to delay one of the two things. Either you can delay the drawer close so it is not visible at all, or you delay the activity open to only happen after the drawer finished closing. 

You can do those things via:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1085
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1102

**Comment by Abo-Hani** [comment]
Thanks! yup that's my point, making a one Drawer with fragments, previously i had a custom PreferenceFragment that did the job along with a Drawer that use List<Obj> ( param Fragment ), that's what i want. Switching between fragments, if you can include a guide / hint / class sample it would be awesome.

**Comment by ismail-s** [comment]
@Abo-Hani At the risk of confusing you, my app has one activity, one drawer, and switches between fragments. The important code for this is https://github.com/ismail-s/JTime/blob/master/JTime-android/src/main/java/com/ismail_s/jtime/android/activity/MainActivity.kt (written in kotlin, which is similar to java). If it helps you at all.

**Comment by mikepenz** [comment]
@Abo-Hani having `Fragment`s is nothing **MaterialDrawer** specific, you just have to set / "commit" your fragment as soon as the event is called. There are a few open source projects available which do this using the `MaterialDrawer` I also think this was already asked / answered a while back

@ismail-s thanks for adding yours here too ;)

**Comment by Polluxs** [comment]
Maybe this example can help?
**Java**:
`@Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        // do something with the clicked item :D
                        FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
                        switch(position){
                            case 1:
                                ResearchFragment researchFragment = new ResearchFragment();
                                transaction.replace(R.id.fragment_container_teacher_main, researchFragment);
                                transaction.addToBackStack(null);
                                transaction.commit();
                                break;
                            case 2:
                                ResearchersFragment researchersFragment = new ResearchersFragment();
                                transaction.replace(R.id.fragment_container_teacher_main, researchersFragment);
                                transaction.addToBackStack(null);
                                transaction.commit();
                                break;
                            case 4:
                                ImagesFragment imagesFragment = new ImagesFragment();
                                transaction.replace(R.id.fragment_container_teacher_main, imagesFragment);
                                transaction.addToBackStack(null);
                                transaction.commit();
                                break;
                        }
                        return true;
                    }`

**XML**:
`<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/fullscreen_content_teacher_main"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    tools:context="com.polluxs.spraakhulp.spraakhulp.TeacherMain"
    >
    
    <android.support.v7.widget.Toolbar
        android:layout_width="match_parent"
        android:layout_height="?android:attr/actionBarSize"
        android:id="@+id/toolbarMainTeacher"
        android:background="@color/colorPrimary"
        app:titleTextColor="@color/white">

    </android.support.v7.widget.Toolbar>

    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/fragment_container_teacher_main"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="?attr/actionBarSize"/>

</android.support.constraint.ConstraintLayout>
`

**Comment by Abo-Hani** [comment]
Holy moly.. taking up the days when i used to ask stupid questions without knowing what a Fragment is. after like a month from my comment i was able to code it without any issues.
