### ISSUE TITLE
Set DrawerItem and Drawer width and height

### ISSUE THREAD

**Issue by ApotheoKing** [mikepenz/MaterialDrawer#1284]
Is there a way I can set the width and height of each item? I would like to create drawer items with large square icons.

Is there a way to set the drawer width as "wrap_content"? (Just wondering on this one)

**Comment by mikepenz** [comment]
@ApotheoKing you can provide any custom `DrawerItems` you want. Just search for **"CustomDrawerItem"** in the issues here in GitHub or on Stackoverflow this was asked already a few times ;)

No I don't think the `DrawerLayout` will allow you to have "wrap_content" as it needs an exact width to calculate all the things. You can set the width dynamically via code though.

**Comment by ApotheoKing** [comment]
I know you closed this, but I just wanted to ask a question about the method I made.

`public int withWidth (ViewHolder viewHolder, int height){

     Context context = viewHolder.itemView.getContext();
     viewHolder.itemView.setMinimumHeight(height);

return R.id.drawer_item;
}`

idk what to pass through as the viewHolder, sorry, I'm about a week new to this
I just don't know what to pass through as the view

**Comment by ApotheoKing** [comment]
protected DimenHolder mHeight;

     public SquareDrawerItem withHeightDp (int heightDp) {
         this.mHeight = DimenHolder.fromDp(heightDp);
         return this;
     }

     public SquareDrawerItem withHeightPx (int heightPx){
         this.mHeight = DimenHolder.fromPixel(heightPx);
         return this;
     }

     public DimenHolder getHeight(){
         return mHeight;
     }


and this inside the onBind method before the onPostBindView method.
     //set the height
     viewHolder.itemView.setMinimumHeight(1);

      if(mHeight!= null){
            RecyclerView.LayoutParams lp = (RecyclerView.LayoutParams)  viewHolder.itemView.getLayoutParams();
            lp.height = mHeight.asPixel(ctx);
            viewHolder.itemView.setLayoutParams(lp);
        }

I used this to be able to change the size of my custom primary drawer item. Everything else is the same. How would I go about making the icons inside the item larger and centered? Do I do this through java, or xml? I have already looked at the questions posted, and I have tried some of the ways you suggested, but it didn't work for me. I've been messing with the xml code a lot for the item itself, but it changes nothing. Do I have to make a custom drawer too?
