### ISSUE TITLE
drawer on tablet 'openDrawer' issue/question

### ISSUE THREAD

**Issue by digital-prime** [mikepenz/MaterialDrawer#1285]
Hello! I have a question about your drawer!
I have an app on phone, it works good.

This app on tablets must be with always lock and opened. But there is one menu item, on which i must unlock drawer and close it, and after that - show fullscreen content.

Smth like this:
![2016-05-20 13 46 14](https://cloud.githubusercontent.com/assets/13558483/15425542/99ffa6e6-1e91-11e6-8b5f-c86d1653978b.png)

BUT! Problem is with methods `drawer.open()` and `drawer.close()`!
They didn't work!
At first time they didn't work because of `drawer.getDrawerLayout()` return null.

After that i try to use drawerBuilder.setDrawerLayout(-1) - but this always throws Exception : "Caused by: java.lang.IllegalArgumentException: No drawer view found with gravity LEFT".

After that I've changed full layout files of menu and add `my drawer_layout.xml`:
```
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/drawer_layout"

    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <FrameLayout
        android:id="@+id/fullScreenContainer"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <FrameLayout
        android:id="@+id/menu_drawer_container"
        android:layout_width="@dimen/navigation_drawer_width"
        android:layout_height="match_parent"
        android:layout_gravity="left"/>

</android.support.v4.widget.DrawerLayout>
```

And use it in layout of my "menu.xml" inside <include> tag:
```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/tabletMain"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/photo_back"
    android:orientation="horizontal">

    <include layout="@layout/drawer_layout"/>

    <LinearLayout
        android:id="@+id/halfScreenContainer"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginLeft="@dimen/navigation_drawer_width_plus_offset"
        android:background="@android:color/white"
        android:orientation="vertical">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/dark_blue"
            android:orientation="horizontal">

            <ImageView
                android:id="@+id/tabletIconView"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_vertical"
                android:paddingLeft="20dp"
                android:paddingTop="20dp"
                android:src="@drawable/ic_svo" />

            <android.support.v7.widget.Toolbar
                android:id="@+id/menu_toolbar"
                style="@style/AppBarTop"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/dark_blue"
                android:minHeight="?attr/actionBarSize"
                android:theme="@style/AppTheme.AppBarOverlay" />
        </LinearLayout>

        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@android:color/white">

            <ImageView
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:layout_gravity="right"
                android:scaleType="fitXY"
                android:src="@drawable/side_line" />

            <FrameLayout
                android:id="@+id/fragment_container"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

        </FrameLayout>
    </LinearLayout>
</FrameLayout>
```

But the problem still remained! 
On start of app drawer is not visible - i must open it by finger motion from left to right.
But I.m doing drawer.open. drawer lock mode=open and many many others thing(

Please tell me. why can i have this problem with open/close methods ?

PS - in code I initialize drawer like this:
```
final DrawerBuilder drawerBuilder = new DrawerBuilder().withActivity(view)
                                                               .withHasStableIds(true)
                                                               .withItemAnimator(new AlphaCrossFadeAnimator())
                                                               .withStickyHeader(notificationHeaderId)
                                                               .withToolbar(toolbar)                                                               .withSliderBackgroundDrawable(ContextCompat.getDrawable(context, R.drawable.pattern))
                                                               .withDrawerItems(items)
                                                               .withOnDrawerItemClickListener(this)
                                                               .withSavedInstance(savedInstanceState)
                                                               .withShowDrawerOnFirstLaunch(true)
.withDrawerLayout(R.layout.drawer_layout);

        Drawer drawer = drawerBuilder.buildView();;
--------------
final View view = findViewById(R.id.menu_drawer_container);
        if (drawer != null && view != null) {
            ((ViewGroup) view).addView(drawer.getSlider());
        }

        if (drawer.getDrawerLayout() != null) {
            drawer.getDrawerLayout().setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_OPEN, Gravity.LEFT);
            drawer.getDrawerLayout().setDrawerShadow(android.R.color.transparent, Gravity.LEFT);
            drawer.getDrawerLayout().openDrawer(Gravity.LEFT);
        }
```

**Comment by digital-prime** [comment]
i've solved some of my problems after use methods of `open`, `close`  with arguments `view` like this:
```
drawer.getDrawerLayout().openDrawer(view);
drawer.getDrawerLayout().closeDrawer(view);

```
where view was : 

```
final View view = findViewById(R.id.menu_drawer_container);
        if (drawer != null && view != null) {
            ((ViewGroup) view).addView(drawer.getSlider());
        }
```

But I still have one problem - with LOCK MODE. This doesn't work:
`drawer.getDrawerLayout().setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_OPEN, view);
`

When I do this - i still can swipe drawer on left (close) and open it. Any ideas about it?)

**Comment by mikepenz** [comment]
@digital-prime sorry for the late answer. I was at the Google IO so I was a bit limited to GitHub. 

I see a few problems with your issue / solution. 

The first issue is. You do not use the default behavior when creating the `Drawer` you use the `.buildView()` method which won't inflate and add the `DrawerLayout` for you. So the `Drawer` does not know about the `DrawerLayout` and it won't handle it for you. 

If you want a `DrawerLayout` in the root of your activity I suggest to use the `.build()` method which will then result in everything being handled for you automatically. You will also be able to call `Drawer.getDrawerLayout()` then to retrieve the managed `DrawerLayout` 

as of `openDrawer()` and `closeDrawer()` those methods are meant to open and close it. Not to lock it. 

After that you will be able to `LOCK` /  `UNLOCK` the `Slider` of the `Drawer` using the platform methods. You may need to use the `GravityCompat.START` to get the correct view locked. 

You may want to check the different lock modes here:
https://developer.android.com/reference/android/support/v4/widget/DrawerLayout.html#LOCK_MODE_LOCKED_CLOSED

**Comment by digital-prime** [comment]
@mikepenz , but If I will use standard `build` - all of my content on the right half of screen will be disable and 'shadowed' because of drawer will be always opened(/or lock)!

**Comment by digital-prime** [comment]
so. i solved all my problems when i start to use not `Drawer drawer` object, but standard `drawerlayout` from xml to open and lock it like this:
```
drawerContainerView = findViewById(R.id.menu_drawer_container);
drawerLayout = (DrawerLayout) findViewById(R.id.drawer_layout);
drawerLayout.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_OPEN, drawerContainerView);
drawerLayout.openDrawer(drawerContainerView);
```

**Comment by mikepenz** [comment]
Ah ok I see. Great that you solved it

**Comment by sandeshsk** [comment]
Hello How to make drawer open always. I have tried By setlockmode but it is locking the main UI. I have used build method to create drawerLayout. Is there any solution?
