### ISSUE TITLE
Vector drawable support

### ISSUE THREAD

**Issue by danielgomezrico** [mikepenz/MaterialDrawer#1286]
Will be great to have vector drawable support for drawer items, maybe something like setVectorIcon(id)

```
new PrimaryDrawerItem().withName(R.string.title_fragment_orders)
                  .withVectorIcon(R.drawable.ic_access_time_black_24dp)
```

Or is there any way to use those?

**Comment by mikepenz** [comment]
@danielgomezrico you can provide `Drawables` and there is a `VectorDrawableCompat` which should do the job:
https://developer.android.com/reference/android/support/graphics/drawable/VectorDrawableCompat.html?utm_campaign=android_launch_supportlibrary23.2_022216&utm_source=anddev&utm_medium=blog
