### ISSUE TITLE
How to change the Navigation Drawer icon 

### ISSUE THREAD

**Issue by Shajeel-Afzal** [mikepenz/MaterialDrawer#1288]
Hi!

How can I change the default navigation (hamburger) icon? I have tried the following but it does not change

```
        getSupportActionBar().setHomeButtonEnabled(true);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        toolbar.setNavigationIcon(R.drawable.ic_menu_black_24dp);
```

I have also tried changing it in the style as

`<item name="android:homeAsUpIndicator">@drawable/ic_menu_black_24dp</item>`

Thanks

**Comment by ismail-s** [comment]
@Shajeel-Afzal If it helps at all, the code for setting the nav icon in my app is https://github.com/ismail-s/JTime/blob/master/JTime-android/src/main/java/com/ismail_s/jtime/android/activity/MainActivity.kt#L120.

When I was working on that code, I had to change the order of the lines of code a few times until it magically started working.

Also, before you ask, my app is written in kotlin, which has very similar syntax to java (but is more concise).

**Comment by mikepenz** [comment]
@Shajeel-Afzal if you provide the `Toolbar` to the `MaterialDrawer` it will automatically use the `ActionBarDrawerToggle` from Google which can't be changed. You will have to remove the `withToolbar()` part and handle opening / closing etc on your own. You may then also be able to define different icons, behaviors etc. 

@ismail-s thanks for answering here ;)
