### ISSUE TITLE
Request - Typeface

### ISSUE THREAD

**Issue by TurKurT656** [mikepenz/MaterialDrawer#129]
can u add setTypeface method for sections?

**Comment by mikepenz** [comment]
@TurKurT656 do you talk about the SectionDrawerItem or all DrawerItems?

**Comment by TurKurT656** [comment]
i'm talking about a typeface on all DrawerItems.

**Comment by mikepenz** [comment]
Oh i see :D. Just checked will take a while to add the methods but yeah will be in one of the next versions ;)

**Comment by TurKurT656** [comment]
TnQ man, You have the best navigation drawer lib.

**Comment by yaserseyedi** [comment]
Hi,
SectionDrawerItem().withTypeface()
does not apply the typeface
