### ISSUE TITLE
Overriding RecyclerView

### ISSUE THREAD

**Issue by gmltA** [mikepenz/MaterialDrawer#1290]
Hi.

Mike, can you please give me an example of overriding drawer's inner RecyclerView?

**Comment by mikepenz** [comment]
@gmltA you can provide any `RecyclerView` you want with `withRecyclerView()`. This will then be picked. 

See what's done automatically otherwhise:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1576

**Comment by gmltA** [comment]
I think I started from the wrong side of the problem.
Let me ask the original question that led me to RecyclerView overload.

I want to add padding at the top of the drawer content. How can I achieve that? The only way I discovered is to create new RecyclerView with padding-top set to desired value and then set it as drawer's view.

It this really the best way to achieve desired appearance? Even if it is, I still can't figure out how to properly define new RecyclerView in my activity to provide it to drawer. Can you please create an example snippet for this?

**Comment by mikepenz** [comment]
@gmltA you can also just retrieve the `RecyclerView` from the built drawer and alter the padding afterwards

**Comment by gmltA** [comment]
@mikepenz that's much better. Thanks
