### ISSUE TITLE
Difficult to import as a module or as a library

### ISSUE THREAD

**Issue by manojkumarmeerut** [mikepenz/MaterialDrawer#1292]
Hi,
    your library difficult to import as a module or as a library. I tried my many time every time fail. Finally I have to import your library as project and then I have to implement in that.
How to resolve this problem.
Please help.

**Comment by mikepenz** [comment]
@manojkumarmeerut I am not sure what's your problem.

If you want to use it as library just follow the README:
```gradle
compile('com.mikepenz:materialdrawer:5.2.7@aar') {
    transitive = true
}
```

Done.

**Comment by Aeefire** [comment]
May I reopen this question?
I am experiencing the same problems and I think it's related to the newest support libraries.

my build.gradle dependencies:
   ```
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.android.support:design:23.2.0'
    compile('com.mikepenz:materialdrawer:5.2.7@aar') {
        transitive = true
    }
```

while gradle itself doesn't complain, basic classes like com.mikepenz.materialdrawer.model.SecondaryDrawerItem; cannot be resolved. 

Are there any special requirements in support library or gradle versions?

**Comment by mikepenz** [comment]
@Aeefire no not really. the latest support libs are already used in this lib. 

what repository have you in your root build.gradle?

**Comment by Aeefire** [comment]
Jcenter, jitpack.io and mavenCentral

**Comment by mikepenz** [comment]
if you have mavenCentral first?

**Comment by manojkumarmeerut** [comment]
Hi Mike,
As you told me before ,your library is working fine as you told. I resolved
this problem that time.

**Comment by Aeefire** [comment]
mavenCentral() on Top, as well as removing gradle cache, build.gradle dependency cache etc. has not resolved the issue. If noone else is having this issue, it's probably on my side anyway. Thanks for your help so far, though :)

**Comment by mikepenz** [comment]
@Aeefire normally this sounds like you miss the `transitive` part?
https://github.com/mikepenz/MaterialDrawer#1-provide-the-gradle-dependency

But as you posted above you have it in your project. 

Perhaps you can send me a zip with the project and I try it?

**Comment by Aeefire** [comment]
Hey,

I am not really fine with sending you my project, although it's currently oonly a hobby project (my tiem is really constraint... hence the really late answer here too...).

BUT it seems like Androdi Studio's newest update 2.2 Preview 4 seems to have somehow resolved the issue and everything works again. Thanks for trying to help!

**Comment by mikepenz** [comment]
@Aeefire great that it's working now
