### ISSUE TITLE
Remove Right Shadow

### ISSUE THREAD

**Issue by initru** [mikepenz/MaterialDrawer#1293]
Is there any way to remove shadow on the right? 
As i understand this part of code must be changed ?
https://github.com/mikepenz/MaterialDrawer/blob/692639061b4041bcc8092fe703554d4d7483e3a2/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1568

withInnerShadow(false) didnt help

**Comment by mikepenz** [comment]
@initru yes the right shadow is automatically set and can't be removed as it is an essential part of the `Material Design Guidelines` 

What may could work (I have not tested it) if you add a drawable which is transparent only to your project and name it like this:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/drawable/material_drawer_shadow_right.9.png

Otherwhise this needs a change in the drawer itself.

**Comment by initru** [comment]
@mikepenz  yeah, it work. Thx.
