### ISSUE TITLE
[Feature Request] ProfileDrawerItem add ImageView next to name with OnClickListener

### ISSUE THREAD

**Issue by vanniktech** [mikepenz/MaterialDrawer#1294]
It'd be nice if one could set an image next to the name with an onclicklistener. Basically we want to achieve this:

![screen shot 2016-05-25 at 11 31 32](https://cloud.githubusercontent.com/assets/5759366/15535152/61d69e9e-226c-11e6-8bea-567e02aad22e.png)

Right now we're looking for the corresponding TextView and set the right Drawable and also set the layout params to `WRAP_CONTENT` and change the drawable padding. Unfortunately we can't have an OnClickListener only on the icon (that's a limitation of TextView though).

**Comment by mikepenz** [comment]
@vanniktech if you really need such a custom behavior which is not in the design guidelines you still have the option to overwrite the `xml` used for the `AccountHeader` add this view, and build everything as normal. You then just have to get the view of the `AccountHeader` search for the `Icon` set it and place an `onClickListener` on it (which still has the issue that the touch target of this icon is far to small)

**Comment by vanniktech** [comment]
Fair enough. Didn't know that you could customize it in this way. If you're not considering taking this into the the library feel free to close this issue. Thanks again 👍

**Comment by mikepenz** [comment]
@vanniktech yeah you can alter nearly everything. I have planned to keep the library features as far as possible to the material design guideliens
