### ISSUE TITLE
ClickListener on Primary setting drawer item.

### ISSUE THREAD

**Issue by susylPearl** [mikepenz/MaterialDrawer#1295]
I want to perform certain actions on click of primary setting drawer item like "Add Account" .But I am unable to do that.Can anyone help. Please...

**Comment by mikepenz** [comment]
The events of the `ProfileSettingDrawerItem` in the account section are also triggered via the `onProfileChanged` event:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L89

**Comment by susylPearl** [comment]
Thanks a lot, it really helps. #cheers
