### ISSUE TITLE
Shadow issue on pre Lollipop devices.

### ISSUE THREAD

**Issue by DearDhruv** [mikepenz/MaterialDrawer#1297]
Hello @mikepenz 
I'm having one issue with Drawer Shadow with pre-Lollipop Devices.
I think it is related to this Line may be: https://github.com/mikepenz/MaterialDrawer/blob/692639061b4041bcc8092fe703554d4d7483e3a2/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1566
 Or may be this 9 patch drawable is creating issue: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/drawable/material_drawer_shadow_right.9.png

Here is >21 Device [WORKING]
Snaps: 
#### nexus_6_android_N
![nexus_6_android_N_material_drawer] (http://i.imgur.com/cRpzjTJ.png)
It also works with galaxy_s4_android_5.0.1

But for <21 devices [NOT WORKING]
Snaps:
#### galaxy_s3_android_4.3
![galaxy_s3_android_4.3_material_drawer_1] (http://i.imgur.com/M0MU7cB.png)
![galaxy_s3_android_4.3_material_drawer_2] (http://i.imgur.com/pZdg1ko.png)
![galaxy_s3_android_4.3_material_drawer_3] (http://i.imgur.com/t3DvdSs.png)

#### sony_xperia_android_4.1.2
![sony_xperia_android_4.1.2_material_drawer] (http://i.imgur.com/joHRvUv.png)

Here is my code: 
``` java
        nav_header_main = (ViewGroup) getLayoutInflater().inflate(R.layout.nav_header_main, null);
        nav_footer_main = (ViewGroup) getLayoutInflater().inflate(R.layout.nav_footer_main, null);

        mDrawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(mToolbar)
                .withTranslucentStatusBar(false)
                .withDisplayBelowStatusBar(true)
                .withActionBarDrawerToggle(true)
                .withActionBarDrawerToggleAnimated(true)
                .withStickyHeader(nav_header_main)
                .withHeaderDivider(true)
                .withStickyFooter(nav_footer_main)
                .withFooterDivider(false)
                .withStickyFooterShadow(false)
                .withOnDrawerItemClickListener(this)
                .withInnerShadow(false)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.str_nav_my_settings),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem().withName(R.string.str_nav_show_ad),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem().withName(R.string.str_nav_create_search_agent),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem().withName(R.string.str_nav_fav),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem().withName(R.string.str_nav_recently_seen_ad)
                )
                .withSavedInstance(savedInstanceState)
                .build();
```

Also as you can see in snaps that selection also gives some bad effect.

Can you please help me what I'm missing here?
Or is there something missing in lib?
Thanks.

**Comment by mikepenz** [comment]
Can you clean your project and install it again? 

Seems like some resources may be mixed up in your project. 

Have you modified any images or anything else?

**Comment by DearDhruv** [comment]
@mikepenz Just tried cleaning project, even removed dependency and added again. 
Here is my gradle.build file
``` gradle
apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'io.fabric'

repositories {
    jcenter()
    mavenCentral()
    maven { url 'https://maven.fabric.io/public' }
}

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.XXXX"
        multiDexEnabled true
        minSdkVersion 15
        targetSdkVersion 23

        versionCode 6
        versionName "1.5-beta"

        // Facebook app id
        manifestPlaceholders = [facebook_app_id: "XXXXXXXXX"]

    }

    signingConfigs {
        release {
            storeFile file('..XXXXXX')
            storePassword 'XXXXX'
            keyAlias 'XXXXX'
            keyPassword 'XXXXX'
            v2SigningEnabled true
        }
    }


    productFlavors {
        // Define separate dev and prod product flavors.
        dev {
            // dev utilizes minSDKVersion = 21 to allow the Android gradle plugin
            // to pre-dex each module and produce an APK that can be tested on
            // Android Lollipop without time consuming dex merging processes.
            minSdkVersion 15
        }
        prod {
            // The actual minSdkVersion for the application.
            minSdkVersion 15
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//            debuggable false
            zipAlignEnabled true
        }
    }

    dexOptions {
        jumboMode = true
        preDexLibraries = false
        javaMaxHeapSize "4G"
        // incremental true
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.google.android.gms:play-services-analytics:9.0.0'
    compile 'com.google.code.gson:gson:2.6.2'
    //
    compile 'org.apache.httpcomponents:httpcore:4.4.4'
    compile 'com.squareup.okhttp3:logging-interceptor:3.2.0'
    compile 'com.squareup.retrofit2:retrofit:2.0.2'
    compile('com.squareup.retrofit2:converter-simplexml:2.0.2') {
        exclude module: 'stax'
        exclude module: 'stax-api'
        exclude module: 'xpp3'
    }
    //
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
    compile('com.mikepenz:materialdrawer:5.2.7@aar') {
        transitive = true
    }
    //
    compile 'com.jakewharton:butterknife:8.0.1'
    apt 'com.jakewharton:butterknife-compiler:8.0.1'
    //
    compile 'de.greenrobot:eventbus:3.0.0-beta1'
    provided 'de.greenrobot:eventbus-annotation-processor:3.0.0-beta1'
    //
    compile 'com.facebook.android:facebook-android-sdk:4.9.0'
    compile 'com.github.rey5137:material:1.2.2'
    compile 'com.auron:permission-manage:1.0.9'
    //
    compile supportDependencies.appCompat
    compile supportDependencies.cardView
    compile supportDependencies.recyclerView
    compile supportDependencies.design
    //
}

apply plugin: 'com.google.gms.google-services'
```

And no I've not modified anything.

**Comment by DearDhruv** [comment]
Well, It might not relate to this but I also Invalidated the cache from the Android Studio, but no success.

**Comment by mikepenz** [comment]
@DearDhruv your issue looks really weird and I am not sure if this is related to the MaterialDrawer at all. It seems like the default android system selector drawables are somehow broken. (those do not come from the the MaterialDrawer) 

The selected drawable of an item and the selected drawable for the ActionBarDrawerToggle are both the normal `selectedItemBackground` which is an Android ressource / appcompat ressource and nothing handled from me

**Comment by DearDhruv** [comment]
I've tried many things but no success for now.
I'll try creating new project with same lib and import all the project there if things go ok.

**Comment by mikepenz** [comment]
When you run the sample app do you have any issues?

DearDhruv <notifications@github.com> schrieb am Do., 26. Mai 2016, 14:34:

> I've tried many things but no success for now.
> I'll try creating new project with same lib and import all the project
> there if things go ok.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mikepenz/MaterialDrawer/issues/1297#issuecomment-221858255>
>
-- 
Mike Penz
__________________________________________
*Mike Penz*
Android | Backend | Open Source | Web Developer
mikepenz.com
lanora.io

**Comment by DearDhruv** [comment]
I tried on new sample project and it did work fine. 
May be some styles went wrong. 
You can close the issue.

**Comment by mikepenz** [comment]
Might be related to this lib:
```
compile 'com.github.rey5137:material:1.2.2'
```

**Comment by DearDhruv** [comment]
I've checked the same lib. But still needs to go in deep as I'm not using/applying this lib on views except radio/buttons.
I'll comment what was the issue once fixed.

Thanks for support.
