### ISSUE TITLE
IProfile doesn't update

### ISSUE THREAD

**Issue by JesseBlackman** [mikepenz/MaterialDrawer#1298]
hi,
I call updateProfile in MainActivity.onActivityResult() after user Edit his profile in AnotherActivity(it is started from MainActivity using startActivityForResult).

There three step in MainActivity.onActivityResult() :
1.new IProfile using the same id;
2.headerResult.updateProfile(profile);
3.headerResult.setActiveProfile(profile);

but the profile doesn't update.

**Comment by mikepenz** [comment]
@JesseBlackman what do you mean with it doesn't get updated. Will it stay the old profile, or doesn't it get the selection? The identifier is correct for sure?

**Comment by JesseBlackman** [comment]
@mikepenz it stay the old proflie,but I have changed it's value.

**Comment by mikepenz** [comment]
I am not sure why it should not work. But if you check the following of the sample app: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/AdvancedActivity.java#L169

This works

**Comment by JesseBlackman** [comment]
@mikepenz 
I just missed add profile to AccountHeaderBuilder().
I think using
`if (savedInstanceState == null) {
            headerResult.setActiveProfile(profile);
        }`
is enough by mistake.but it actually works ok before I met the problem.

thank u!
