### ISSUE TITLE
Open drawer only when swipe on left side not on hole screen in tablet

### ISSUE THREAD

**Issue by anand-agrawalglobant** [mikepenz/MaterialDrawer#1299]
Is their any way that i can open the drawer only when swipe in left panel.I am using the viewpager in right panel.When i swipe the viewPager the drawer opens/close.I want open the drawer only when i swipe from left to right on area as shown in attached image, not on whole screen.
![screenshots2](https://cloud.githubusercontent.com/assets/16498823/15572667/9aebc09e-235f-11e6-97a1-1d196da8db7a.jpg)

**Comment by sondangpangaribuan** [comment]
are you solve this ???
