### ISSUE TITLE
Font size for Name and Email in AccountHeader

### ISSUE THREAD

**Issue by rohithn** [mikepenz/MaterialDrawer#1300]
Is it possible to change the font size of Name and Email in an AccountHeader?

**Comment by mikepenz** [comment]
@rohithn you can overwrite the default values if you need. But I do not recommend this as those are the correct ones defined in the Material Design Guidelines. And It may make it look worse. 

Just set the following value in your `dimen.xml`
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/values/dimens.xml#L25
