### ISSUE TITLE
Item Selected Color gradient?

### ISSUE THREAD

**Issue by vuminhkhang1995** [mikepenz/MaterialDrawer#1302]
Hi, 

I have found the way to set the color for the selected item. However, I don't know whether we can set a gradient color for a selected item like this:

![alt tag](http://i.imgur.com/F9lkpLY.png)

**Comment by mikepenz** [comment]
You can set a `Drawable` as background. You should find on StackOverflow how to create a https://developer.android.com/reference/android/graphics/drawable/GradientDrawable.html in Android

**Comment by vuminhkhang1995** [comment]
Maybe you misunderstand my question. The point is I cannot find the way to set the background of selected item using `Drawable` as background. I can only set the background as solid color from colors.xml.

Sorry I forgot to mention the way I set the color of the selected item. I'm just able to do that by setting custom colors in colors.xml file. Doing this way only allows me to set solid colors. I have already tried creating my own Style in styles.xml, but it looks like it does not work. I do not know where to adapt my custom style.

**Comment by mikepenz** [comment]
@vuminhkhang1995 ah yeah you are right. Sorry I missed that this is part of the default behavior as the default items are created to fit the `Material Design Guidelines` 

You would need to create a `CustomDrawerItem` which allows you to set any background you want. 
It does not have to be as complicated as the default items are, but just in case here's where I set the background:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BasePrimaryDrawerItem.java#L81

Here are some samples of `CustomDrawerItems`
https://github.com/mikepenz/MaterialDrawer/tree/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems

**Comment by vuminhkhang1995** [comment]
Thank you, I'll try it out.
