### ISSUE TITLE
Drawer items texts font style is inconsistent

### ISSUE THREAD

**Issue by jahirfiquitiva** [mikepenz/MaterialDrawer#1304]
For some reason, some items in the drawer appear with bold font, or a little bigger and so.

Here's a screenshot.

![screenshot_20160530-164158](https://cloud.githubusercontent.com/assets/10360816/15654306/b8a5f248-2658-11e6-8966-b8069463bde6.png)

**Comment by mikepenz** [comment]
@jahirfiquitiva that's quite weird. Do you set your own font or typeface anywhere?

**Comment by jahirfiquitiva** [comment]
@mikepenz No, I don't set any custom font nor typeface. Everything is system default.

**Comment by mikepenz** [comment]
Which makes it even weird, as those are all the same items. 

Which device are you on? Which android version?

**Comment by jahirfiquitiva** [comment]
Yeah, all those are the same items...
The code can be found [here](https://github.com/jahirfiquitiva/IconShowcase/blob/master/showcase/src/main/java/jahirfiquitiva/iconshowcase/activities/ShowcaseActivity.java#L784).

Device: Moto G 2nd Gen ... Android 6.0.1

**Comment by mikepenz** [comment]
@jahirfiquitiva if you do a clean install (without instant run)?

**Comment by jahirfiquitiva** [comment]
I don't have Instant Run enabled, and I have tried clean installations, but still the same.

**Comment by mikepenz** [comment]
@jahirfiquitiva will this look like this instantly upon launch or only after clicking and selecting some items?

**Comment by jahirfiquitiva** [comment]
Just right after opening the app...

One thing I have seen is if I choose item 2 (just as an example), and then choose item 3, the text in item 2 will stay bold.

If I choose items that are immediately next, like: 2-->3, 3-->4, 4-->3 ... the previously selected item stays with bold font.

But happens sometimes only.. I mean, I tried to switch between multiple items and sometimes they have the bold fonts, and sometimes doesn't.

Also, the first item always has the bold fonts even when pressing other items multiple times.

This is really weird and I can't tell an exact way to reproduce it, because as I said, happens randomly.

**Comment by mikepenz** [comment]
@jahirfiquitiva can you please send an `apk` of the app so I can test it on my device?

The weird thing is I do not set any typeface or anything depending on the state of the item. So the font is just defined within the `material_drawer_item_primary.xml` 

I have no clue why it happens in your app, can't reproduce it in any of mine.

**Comment by jahirfiquitiva** [comment]
https://play.google.com/store/apps/details?id=com.zavukodlak.candycons

**Comment by jahirfiquitiva** [comment]
@mikepenz I have a new apk where the issue seems to be more noticeable, can I send it to you via Hangouts?

**Comment by mikepenz** [comment]
@jahirfiquitiva yes you can also send it via hangouts

**Comment by mikepenz** [comment]
@jahirfiquitiva on a Nexus 6P with Android N this is not noticeable at all :/

**Comment by jahirfiquitiva** [comment]
This seems to happen only with custom roms... if you see no one else experience the issue, you could close it if you want to.

**Comment by mikepenz** [comment]
@jahirfiquitiva it's weird. As mentioned no font style or something is defined programatically all comes from the xml. So perhaps they have some wrong binaries and render text wrong? 

I also have seen that your icon template still uses the old version of `Android-Iconics` please update to the latest to fix the Android N Preview 2 & Preview 3 alignment issue.

**Comment by zayn1991** [comment]
@mikepenz is there method for changing item style? As "bold/regular/italic"? I did item size 16dp and they got bold style. I wanted to remove style "bold", if it contains

**Comment by mikepenz** [comment]
well it is the default. you can modify the layouts or create a CustomDrawerItem if you need custom look and feel
