### ISSUE TITLE
SwitchDrawerItem rendering issue

### ISSUE THREAD

**Issue by xsorifc28** [mikepenz/MaterialDrawer#1305]
I've looked for a similar issue but could not find one (I apologize if this is a duplicate).

The SwitchDrawerItem is not rendering properly:

![untitled-1](https://cloud.githubusercontent.com/assets/5721836/15654805/3157aec8-2665-11e6-93c4-105b13484702.jpg)
Here is the code:
```java
    SwitchDrawerItem drawerLocationToggleItem = (SwitchDrawerItem) new SwitchDrawerItem()
                .withName(R.string.show_location)
                .withIcon(CommunityMaterial.Icon.cmd_crosshairs_gps)
                .withChecked(prefs.getBoolean(PrefConst.SHOW_LOCATION, false))
                .withOnCheckedChangeListener(onCheckedChangeListener)
                .withSelectable(false)
                .withIdentifier(LOCATION_TOGGLE);
```

**Comment by mikepenz** [comment]
@xsorifc28 does this also happen in the `SampleApp`?

**Comment by xsorifc28** [comment]
On the latest sample app, the switches look fine. Could be an issue with the latest AppCompat libraries?

**Comment by mikepenz** [comment]
@xsorifc28 the sample app uses the latest `AppCompat` libraries so it should be fine. Have you done a clean run (clean build)? 

Any other libraries which may alter the styles of a `Switch`?

**Comment by xsorifc28** [comment]
I'm not aware of any libraries that would alter the switch, but I have quite a few libraries so interference is possible. I'll see what I can find.

**Comment by mikepenz** [comment]
@xsorifc28 yeah I assume that something alters with the general `Switch` so I expect that your issue is not related to this lib. Just try to place a `android.support.v7.widget.SwitchCompat` somewhere else in the app and look how it behaves.

**Comment by xsorifc28** [comment]
I was using version 9.0.1 for the below libraries:    

    compile 'com.google.android.gms:play-services-base:8.4.0'
    compile 'com.google.android.gms:play-services-maps:8.4.0'
    compile 'com.google.android.gms:play-services-gcm:8.4.0'
    compile 'com.google.android.gms:play-services-location:8.4.0'
    compile 'com.google.android.gms:play-services-analytics:8.4.0'
    compile 'com.google.android.gms:play-services-appindexing:8.4.0'

and 
    
    classpath 'com.android.tools.build:gradle:2.1.0'

/ Google Cloud Messaging
		classpath 'com.google.gms:google-services:2.1.0'

**Comment by mikepenz** [comment]
hmmm if you just change the build tools? would this make a difference?

**Comment by xsorifc28** [comment]
Built tools 2.1.0 works fine, can update everything else fine.

**Comment by mikepenz** [comment]
so you may should report this or look if this was already reported in the android bugtracker
