### ISSUE TITLE
Combining Functions of Two DrawerItems?

### ISSUE THREAD

**Issue by s-p-a-r-k** [mikepenz/MaterialDrawer#1306]
Is there a way to combine the arrow of ExpandableDrawerItem and the switch of SwitchDrawerItem?
I would like to make an ExpandableDrawerItem that has a switch or a check box that would turn on and off all of its sub items.

**Comment by mikepenz** [comment]
@s-p-a-r-k you can implement any `CustomDrawerItem` that you want. You can have a look at the source code of both, and just combine their functionality. (remember the default items are very very flexible so they have many features in which you may not need for you application)
