### ISSUE TITLE
Working with AppCompatDelegate  ?

### ISSUE THREAD

**Issue by misoza** [mikepenz/MaterialDrawer#1307]
Is there any way to get your great component use with old ListActivity ? , i have an older app with more activities, and cant change it to AppCompatActivity. 
there is AppCompatDelegate which can simulate Compat functions on non CompatActions . 

Should be this  be this working ? 
any advice ? :)

**Comment by mikepenz** [comment]
There is this guide how to properly use the `AppCompatDelegate` with normal activites;

The `DrawerBuilder` itself should not require anything `AppCompatActivity` specific

https://medium.com/google-developer-experts/how-to-add-toolbar-to-an-activity-which-doesn-t-extend-appcompatactivity-a07c026717b3#.t28mgccfy

**Comment by misoza** [comment]
Hi Mike
Thanks for reply,

I am web coder , but new to android.
I try to add your component to one older app
where is more complex ListActivities. and dont want refactor whole app.

So your component will work also with
ListActivity and Activity besed classes ?
I hope for that :), but still not trying.

Thanks a lot
Juraj Misovych

**Comment by mikepenz** [comment]
@misoza I don't see why it wouldn't work. AppCompat dependency is required for the `DrawerLayout` but should work with the `AppCompatDelegate` as shown in the link description. Which will also allow the toolbar ;). 

I hope it helps.

If it does not work. You still can just decide to only change this Activity, and switch to a normal `AppCompatActivity` and move all the "list" behavior of the `ListActivity` to a normal `ListView` (just for this activity)
