### ISSUE TITLE
How to make text size of drawer items bigger?

### ISSUE THREAD

**Issue by roher-roher** [mikepenz/MaterialDrawer#1308]
Hello!
I have implemented your MaterialDrawer in my project. Everything is good except one thing: the text size of Drawer Items is very small. How can I make it bigger?
P.S.: I din't override any style or typeface of the items, using them just OOB.

**Comment by mikepenz** [comment]
@roher-roher I do not recommend to change the text size as it is correct as of the `Google Material Design Guidelines`. It will adjust to the phones settings as it is defined in `sp` 

If you really want to change the size (breaking the guidelines) you can do this by overwriting the text size values via your `dimens.xml` file.

Here's the text size defined for the `PrimaryDrawerItem` 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/values/dimens.xml#L37

**Comment by roher-roher** [comment]
Thanks!
