### ISSUE TITLE
Divider in accounts header

### ISSUE THREAD

**Issue by olmur** [mikepenz/MaterialDrawer#1309]
Could you please tell if it possible to put divider into account header between profile drawer items and profile setting drawer items?

**Comment by mikepenz** [comment]
@olmur could you please add a screenshot to describe a bit more what you want to achieve?

**Comment by olmur** [comment]
@mikepenz sure. I want to achieve something like this
<img width="364" alt="screen shot 2016-05-31 at 21 22 49" src="https://cloud.githubusercontent.com/assets/16815979/15685775/ea30243c-2775-11e6-9412-f2bda8b72c4e.png">

Account header is extended and there is a divider between profiles (user) and profile setting (log out). I just can't find any divider for account header. Is it possible to do with your library?

**Comment by mikepenz** [comment]
@olmur there is no default item included in the library doing this. But there is already a `CustomDrawerItem` (source code provided via the sample) available: https://github.com/mikepenz/MaterialDrawer/commit/b1d0e37254d18a908b2a6a75be8a005924fffd4a

Just add it to your project, name it as you need it and use it as normal. ;). 

Funny enough this came up only past week :D First time after a few years xD
See the following question :D https://github.com/mikepenz/MaterialDrawer/issues/1274
