### ISSUE TITLE
Congratulations for the library !!!

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/MaterialDrawer#131]
I just created this issue, to congratulate Mike on his excellent library, and its constant improvement.

It is the BEST library of this kind by far, I've tried them all and this is the best.

continue improving !!!

you can close this issue.

Greetings !!!

**Comment by simonckenyon** [comment]
i've just moved a project from the "traditional" navigation drawer and this library is a vast improvement over what i was using before.
i too would like to thank mike.

**Comment by mikepenz** [comment]
@seba123neo @simonckenyon thank you so much for the nice words :) something special to just hear someone say thanks ;). 

But now i have an issue :D how can i fix this? ...



Just kidding ;). Thanks.
