### ISSUE TITLE
How to setup a custom icon for the drawer?

### ISSUE THREAD

**Issue by jahirfiquitiva** [mikepenz/MaterialDrawer#1310]
Hi Mike,

I would like to know if is possible to set a custom icon for the drawer which currently is something like [this one](https://materialdesignicons.com/icon/menu).

If not possible, would you mind adding it as an option in a future release?

Thanks in advance. :)

**Comment by mikepenz** [comment]
@jahirfiquitiva what do you mean. Where do you want to use this icon?

**Comment by jahirfiquitiva** [comment]
I want to set a custom drawable to the drawer icon that appears in toolbar.

**Comment by mikepenz** [comment]
@jahirfiquitiva that is not possible and can't be added to the `MaterialDrawer` 

The MaterialDrawer uses the `ActionBarDrawerToggle` provided from the `Appcompat` library. This one has a fixed style and can't be modified. There are open source projects which offer you a separate icon or style like the following:
https://github.com/balysv/material-menu
But using this or any custom icons you define as the `NavigationIcon` will require that you will have to handle the open / close events on your own. 

So you won't provide the `toolbar` and then you will hook on the general navigation listeners and if the users click you can then open / close the `Drawer`

**Comment by jahirfiquitiva** [comment]
Thanks for the info and explanation. I think I will stick with the current icon :)

**Comment by mikepenz** [comment]
Ok ;)
