### ISSUE TITLE
CompatHeaderDrawer menu broken with RTL

### ISSUE THREAD

**Issue by mtrakal** [mikepenz/MaterialDrawer#1311]
CompatHeader menu is broken with enabled RTL in sample app.
- Missing email and username
- Image is not in circle border

![device-2016-06-01-110748](https://cloud.githubusercontent.com/assets/1458891/15704079/31bddb14-27e9-11e6-877d-e72ca5103b13.png)
![device-2016-06-01-111210](https://cloud.githubusercontent.com/assets/1458891/15704171/b64ac950-27e9-11e6-8f5e-d92f5220c5ca.png)

**Comment by mikepenz** [comment]
@mtrakal on which device did you test?

**Comment by mikepenz** [comment]
@mtrakal which android device? and which library version?

Working in Android N 

![screenshot_20160601-220557](https://cloud.githubusercontent.com/assets/1476232/15723962/231e5140-2845-11e6-8ec5-1f918416a75f.png)

**Comment by mikepenz** [comment]
Ok it is only on API17

**Comment by mtrakal** [comment]
Thanks, yes, it was on Android 4.2.1, so API 17.
