### ISSUE TITLE
How to add  Shopping cart icon with notification 

### ISSUE THREAD

**Issue by zeeshan4971** [mikepenz/MaterialDrawer#1312]
http://i.stack.imgur.com/aYUQl.jpg
I am using your Material Drawer library

**Comment by mikepenz** [comment]
@zeeshan4971 that is not related to the `MaterialDrawer`. Please search on google how to set menu items.

(In your case you are lucky that I have another lib doing exactly this :D) 
Follow here: https://github.com/mikepenz/Android-ActionItemBadge
(Android-Iconics (which is also a dependency of the ActionItemBadge) is already included in the MaterialDrawer so no need to add this dependency again) 

For icons provided by Android-Iconics follow here:
https://github.com/mikepenz/Android-Iconics

**Comment by zeeshan4971** [comment]
i included your library and using 
@Override
public boolean onCreateOptionsMenu(Menu menu){
  Log.i("test","test log");

        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu, menu);

        if (badgeCount == 0) {
            ActionItemBadge.hide(menu.findItem(R.id.item_samplebadge));
        } else {
            ActionItemBadge.update(this, menu.findItem(R.id.item_samplebadge), FontAwesome.Icon.faw_android, style, badgeCount);
        }
        if (badgeDrawableCount == 0) {
            ActionItemBadge.hide(menu.findItem(R.id.item_sampleBadge_drawable));
        } else {
            ActionItemBadge.update(this, menu.findItem(R.id.item_sampleBadge_drawable), UIUtil.getCompatDrawable(this, R.drawable.ic_notification), style, NumberUtils.formatNumber(badgeDrawableCount));
        }
        new ActionItemBadgeAdder().act(this).menu(menu).title("Sample").itemDetails(0, SAMPLE2_ID, 1).showAsAction(MenuItem.SHOW_AS_ACTION_ALWAYS).add(bigStyle, 1);
        return true;
    }

on the activity i want the icon to appear on it and i does not show any error my app compiles but there are no errors in them. what should i do

**Comment by mikepenz** [comment]
@zeeshan4971 is the item in the menu? or is it behind the overflow button?

**Comment by hiteshcla00** [comment]
Plseeeee solve this
https://stackoverflow.com/questions/53425400/android-menu-badge-onclicklistener-working-only-once-how-i-can-solve-it
