### ISSUE TITLE
ProfileDrawerItem keep old behaviour?

### ISSUE THREAD

**Issue by BartRongen** [mikepenz/MaterialDrawer#1313]
I am updating my app's materialdrawer library from 2.9.0 to 5.2.8 and i stumbled upon the following:

version 2.9.0:
![version 2 9 0](https://cloud.githubusercontent.com/assets/9169358/15710311/d22da5a0-2809-11e6-80fb-2710c5031358.png)

version 5.2.8
![version 5 2 8](https://cloud.githubusercontent.com/assets/9169358/15710316/d4bd2944-2809-11e6-9444-4cdc06fbf32c.png)

The problem is that in version 5.2.8 the text in the header dissapears. This is caused by the fact that there is no ProfileDrawerItem added to the header if a user is not logged in. In version 2.9.0 it seemed that if this is the case, then a ProfileSettingDrawerItem would be used to fill in the text. However in version 5.2.8 this does not seem the case.

When the users logs in a ProfileDrawerItem is added to the header so then old behaviour is kept.

However I want to keep old behaviour when the user is not logged in (so when no ProfileDrawerItem is added to the header, only ProfileSettingDrawerItem), is this possible to achieve?

**Comment by mikepenz** [comment]
@BartRongen you are right this behavior changed in the meantime. 

You have 2 possibilities. 

1. you just set the text for the first and second line manually via the 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L272
and 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L284
So those two lines will have the defined text, and you can interact on the action when the user clicks (perhaps directly showing a dialog or whatever) 

2. you make the `ProfileDrawerItem` selectable (This is possible starting in v5.2.9 again) so it will be shown in the list. (Don't forget to set `withSelectable(false)` again as soon as there are profiles)
