### ISSUE TITLE
Shadows in Fullscreen Activity

### ISSUE THREAD

**Issue by leisim** [mikepenz/MaterialDrawer#1314]
Hi,

This is my `Drawer` configuration:
```java
new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withActionBarDrawerToggleAnimated(true)
                .withHeader(header)
                .withHeaderDivider(false)
                .withFooter(R.layout.drawer_footer)
                .withFooterDivider(true)
                .withRootView(R.id.drawerLayout)
                .withFullscreen(true)
```

And here is my `Activity` view:
```XML
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/colorPrimary"/>

    <FrameLayout
        android:id="@+id/drawerLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
</LinearLayou>
```

My `Activity` is in immersive fullscreen mode and I want the drawer to be diplayed below the `Toolbar`
But it looks like this: ![device-2016-06-01-185626](https://cloud.githubusercontent.com/assets/13610195/15718276/e5a98d76-282a-11e6-83f0-085c95ab3b50.png)

There are shadows top and bottom, something that looks like a StatusBar below the `Toolbar` and the content of the `Activity` has a bottom margin with the height of the NavigationBar.

Thanks for your help 👍 

Simon

**Comment by mikepenz** [comment]
@leisim the shadows normally come from the `fitsSystemWindows` flag. Have you checked the `FullscreenActivity` of the sample app?

**Comment by leisim** [comment]
@mikepenz I don't use this flag...
Yes I did but I don't want the `Drawer` to be fullscreen but the entire `Activity`.

**Comment by mikepenz** [comment]
@leisim this partly solves your issue: 
https://github.com/mikepenz/MaterialDrawer/commit/3e04973b196f4a2ec2ab7b52c95220ae54ef352c

but I am not sure why I can't remove the shadow from the `Slider` somewhere there is still the `fitsSystemWindows` kicking in, in some layout... :/

**Comment by homedevs** [comment]
For me it creates space above of RecycleView . Space is just a shadow. Happening with Android 5.0 >  device. It works fine with 4.4

**Comment by mikepenz** [comment]
yeah that's why it only solves it partially. I have no idea where the `fitsSystemWindows` comes in too. It is really hard. The problem which also occurs is that changing `fitsSystemWindows` programmatically results in different things than doing it via XML. 

In my opinion the `fitsSystemWindows` flag is really hard to control. :/

Today I might try it again to find a 100% working solution. 

the MaterialDrawer itself does no longer set the shadows or margins or paddings which was done on versions prior 4.x.y. As it now depends 100% on the system built in functionality.

**Comment by homedevs** [comment]
Hi,

I always see shadow . It exactly start from below of toolbar / appbarlayout. Attaching image which has been taken from Android 5.0 device but this works fine in Android 4.4

I have tried your above [solution ](https://github.com/mikepenz/MaterialDrawer/commit/3e04973b196f4a2ec2ab7b52c95220ae54ef352c) but it isn't working , after applying it I see it I see toolbar overlaps status bar.

I am following simple one activity and Fragments model. My MainActivity has a drawer . On each drawer item click I am replacing it with Fragments.

Let me know if you need anything.

Attaching image

![bug_drawer](https://cloud.githubusercontent.com/assets/11264134/15780934/82a833b0-29c1-11e6-9ff1-6b8996024275.png)

**Comment by mikepenz** [comment]
@homedevs I know that the `StatusBar` overlaps the `Toolbar` as the initial reporter stated he wants to have the drawer below the `Toolbar` in `Fulllscreen` mode (I didn't activate immersive mode in the test)

If you don't need fullscreen just check out the `CustomContainerActivity` of the sample.

**Comment by leisim** [comment]
@mikepenz Thanks for your help but I changed my layout and don't need fullscreen anymore ;)

**Comment by mikepenz** [comment]
@leisim oh ok great. ;) So it's fine for you now?

**Comment by mikepenz** [comment]
I think I can close this as this behavior only happens if you want to have the drawer below the `Toolbar` and in `Fullscreen`. And this is something I can't control in the drawer as the paddings / shadows are added by the `fitsSystemWindow`s flag. 

If I can help with something let me know?

**Comment by homedevs** [comment]
I have followed this **CustomContainerActivity** and Just replaced CoordinatorLayout with RelativeLayout and it all works fine now.

**Comment by stultusstudio** [comment]
I think I'm having a related problem. There is no toolbar, but the user can configure whether they want a status bar or not. I've looked around, including at this answer https://github.com/mikepenz/MaterialDrawer/issues/1350

I love your library, but when I recently upgraded from 4.6.4 to 5.3.3 a toolbar now appears because of the drawer. Thanks for your help!

![screenshot_2016-07-04-15-47-51](https://cloud.githubusercontent.com/assets/20275787/16552199/5c00b0bc-4202-11e6-895b-70833da5358d.png)
![screenshot_2016-07-04-15-48-00](https://cloud.githubusercontent.com/assets/20275787/16552201/5dc162fc-4202-11e6-98c6-2d31de6794bd.png)

This is my drawer config:

```

public static Handler timerHandler = new Handler();
    void loadDrawer()
    {
        AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.header)
                .withProfileImagesVisible(false).addProfiles(
                        new ProfileDrawerItem().withName(getResources().getString(R.string.app_name)).withEmail("Stultus Studios")

                ).withSelectionListEnabled(false)
                .build();


        mDrawerLayout =new DrawerBuilder().withAccountHeader(headerResult).withActivity(this).withTranslucentStatusBar(true)
                .addStickyDrawerItems(
                        new CustomPrimaryDrawerItem().withBackgroundRes(R.color.md_red_50).withIdentifier(1).withName(getResources().getString(R.string.title_activity_store)).withIcon(GoogleMaterial.Icon.gmd_shopping_cart)
                )
                .addDrawerItems(
                new PrimaryDrawerItem().withIdentifier(2).withName(getResources().getString(R.string.rateapp)).withIcon(GoogleMaterial.Icon.gmd_thumb_up),
                new PrimaryDrawerItem().withIdentifier(9).withName(getResources().getString(R.string.shareapp)).withIcon(GoogleMaterial.Icon.gmd_share),
                new DividerDrawerItem(),
                new PrimaryDrawerItem().withIdentifier(3).withName(getResources().getString(R.string.title_activity_favourites)).withIcon(GoogleMaterial.Icon.gmd_favorite),
                new PrimaryDrawerItem().withIdentifier(4).withName(getResources().getString(R.string.title_activity_history)).withIcon(GoogleMaterial.Icon.gmd_history),
                new PrimaryDrawerItem().withIdentifier(5).withName(getResources().getString(R.string.title_activity_themes)).withIcon(GoogleMaterial.Icon.gmd_grade),
                new DividerDrawerItem(),
                new PrimaryDrawerItem().withIdentifier(6).withName(getResources().getString(R.string.title_activity_settings)).withIcon(GoogleMaterial.Icon.gmd_settings),
                new PrimaryDrawerItem().withIdentifier(7).withName(getResources().getString(R.string.title_activity_about)).withIcon(GoogleMaterial.Icon.gmd_info_outline),
                new PrimaryDrawerItem().withIdentifier(8).withName(getResources().getString(R.string.sendfeedback)).withIcon(GoogleMaterial.Icon.gmd_announcement)
                )
                .withDelayOnDrawerClose(500)
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, final IDrawerItem drawerItem) {
                        if (drawerItem != null) {
                            Intent intent = null;
                            if (drawerItem.getIdentifier() == 1) {
                                launchStore();
                            } else if (drawerItem.getIdentifier() == 2) {
                                launchRate();
                            } else if (drawerItem.getIdentifier() == 3) {
                                launchFavourites();
                            }
                            else if (drawerItem.getIdentifier() == 4) {
                                launchHistory();
                            }
                            else if (drawerItem.getIdentifier() == 5) {
                                launchThemes();
                            }
                            else if (drawerItem.getIdentifier() == 6) {
                                launchSettings();
                            }
                            else if (drawerItem.getIdentifier() == 7) {
                                launchAbout();
                            }
                            else if (drawerItem.getIdentifier() == 8) {
                                launchFeedback();
                            }
                            else if (drawerItem.getIdentifier() == 9) {
                                launchShare();
                            }
                        }
                        return false;

                    }
                })
                .build();
    }

```

And this is a snippet of my activity view:

```

<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:ads="http://schemas.android.com/apk/res-auto"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:orientation="vertical"
    android:background= "@null"
    android:layout_gravity="bottom"
    android:weightSum="700"
    >
</LinearLayout>
```

**Comment by mikepenz** [comment]
@stultusstudio looks like you have some `fitsSystemWindows` flags to much or to less somewhere

**Comment by stultusstudio** [comment]
I'm similar to OP in that I don't use fitsSystemWindows either
