### ISSUE TITLE
Custom drawer items drawables are not being colored properly

### ISSUE THREAD

**Issue by jahirfiquitiva** [mikepenz/MaterialDrawer#1315]
I'm not sure if the library does this, but, I thought that when setting a drawable as the icon of a drawer item, it would be tinted with the right color.

I mean, I have done it, and it keeps the color defined in the xml of the drawable (is a vector drawable).

Is there any way to make it tint with the right color the library already includes? or do I have to set the color manually?

Thanks

**Comment by Polyterative** [comment]
One way can be using this library: https://github.com/mikepenz/Android-Iconics from the same author of MaterialDrawer.
They are integrated and you don't have to specify the color
A simple call can be this:
```Java
Ionicons.Icon.ion_share
```
in a context like this
```Java
PrimaryDrawerItem drawer_share = new PrimaryDrawerItem()
                .withName(R.string.lbl_share_app)
                .withIcon(Ionicons.Icon.ion_share)
                ;
```

**Comment by jahirfiquitiva** [comment]
I need them to be drawables. Thanks anyways.

**Comment by mikepenz** [comment]
@jahirfiquitiva I do not know the code of your `CustomDrawerItem` the default ones allow you to enable tinting. It depends if you kept this functionality?

Why do you need drawables?

**Comment by jahirfiquitiva** [comment]
@mikepenz

I meant custom drawables. I'm still using PrimaryDrawerItem as the items...

How do I enable tinting with such items? Thanks

**Comment by mikepenz** [comment]
by using the `withIconTintingEnabled`. I also use this in the `AdvancedActivity`

https://github.com/mikepenz/MaterialDrawer/blob/355f1dd99484192c7fbdb228ea94fb3cef585b1f/app/src/main/java/com/mikepenz/materialdrawer/app/AdvancedActivity.java#L88

**Comment by jahirfiquitiva** [comment]
@mikepenz

That's all I needed. Thank you so much :)
