### ISSUE TITLE
navigation up on toolbar issue with multiple fragments

### ISSUE THREAD

**Issue by riten7** [mikepenz/MaterialDrawer#1316]
I was trying to show drawer with swipe only when there are multiple fragments in backstack. But whenever i click on the navigation up button, the drawer shows up and i could not navigate back to previous fragments.Can u help me on that...

**Comment by mikepenz** [comment]
@riten7 how do you handle `hamburger` and `arrow` state of the `ActionBarDrawerToggle`?

**Comment by riten7** [comment]
hamburger icon turns into back arrow icon while going through fragments.but back arrow only works when navigation drawer is not attached.And I am unable to customize actionbartoggle with this drawer.

**Comment by mikepenz** [comment]
Switching between arrow and hamburger can be done as shown here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/AdvancedActivity.java#L173

All the things the library does for you is it will link together an `ActionBarDrawerToggle` with the `DrawerLayout` so everything is as it would be done from you

**Comment by riten7** [comment]
Thanks for the help.I will try and get back to you.

**Comment by rodgarcialima** [comment]
Hi @mikepenz , lock only disable the swipe, not button click. Any tips?
