### ISSUE TITLE
Getting error on click on any drawer item

### ISSUE THREAD

**Issue by harishvishwakarma** [mikepenz/MaterialDrawer#1318]
Attempt to invoke virtual method 'int com.mikepenz.fastadapter.adapters.FastItemAdapter.getItemCount()' on a null object reference
when I click any drawer item. Was not happening until yesterday. Don't know what went wrong

**Comment by mikepenz** [comment]
@harishvishwakarma you made any update?

**Comment by harishvishwakarma** [comment]
Nope. Can you tell me a way I could put that code block in a try catch?

**Comment by mikepenz** [comment]
@harishvishwakarma no no no. There should not be anything in an try catch. Can you debug? Does it happen in your debug application or in the live application in the store?

You used instant run? Perhaps a clean install helps?

**Comment by harishvishwakarma** [comment]
It happened in a live application. Looking at the causes. I am starting to debug it.

**Comment by mikepenz** [comment]
@harishvishwakarma that'S weird. any line where that happens? or a full stacktrace?

**Comment by harishvishwakarma** [comment]
Hey, it was an error from our side. I see a developer removed minidrawer and forgot to remove ".withGenerateMiniDrawer(true)". This caused the error. It is working again after removing the line.

Thanks for your help Mike.

**Comment by mikepenz** [comment]
Oh great ;).

**Comment by wykeenjenga** [comment]
> Attempt to invoke virtual method 'int com.mikepenz.fastadapter.adapters.FastItemAdapter.getItemCount()' on a null object reference
> when I click any drawer item. Was not happening until yesterday. Don't know what went wrong

same issue to me
