### ISSUE TITLE
profile name and email color?

### ISSUE THREAD

**Issue by TheLoyalCruel** [mikepenz/MaterialDrawer#1319]
Hi
how to change name and email color in header? its always white!
and `.withTextColor()` deos not change it!

and...
I also have this problem:
https://github.com/mikepenz/MaterialDrawer/issues/1297
it works fine in version 5.2.2 but not in 5.2.9!

thanks in advance... :)

**Comment by mikepenz** [comment]
@TheLoyalCruel 

`.withTextColor` should work. I just looked at the code and it is used correctly. You have to provide it as resolved color. 

for the below issue. Must be somehow related to the support libraries, no ressource changes on my side.

**Comment by TheLoyalCruel** [comment]
ok thanks... 5.2.2 is still ok for me...
is it possible to change the strings(profile names, drawer item names) programmatically?
I mean after within the app after some actions?

**Comment by mikepenz** [comment]
@TheLoyalCruel I meant that you should have the latest support libraries with the latest version of the materialdrawer, also using the latest build tools etc. I have no problems with drawables or anything. 

you can change profileItems and drawerItems at any time. you just need to notify the AccountHeader or Drawer about the udpated item

**Comment by TheLoyalCruel** [comment]
I have the lastest and I dont know whats the problem on for example androdi 4.3
    buildToolsVersion "23.0.3"
    com.android.support - 23.4.0
    gradle:2.1.0

and how to notify the AccountHeader or Drawer about the udpated item?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer 
similar for the `AccountHeader`

hmmm weird. I use the latest version on my own in some apps with many users and there are no issues. I also test the library itself on all the versions all the time and there are no issues. 

there may be some issues with any other lib you use

**Comment by TheLoyalCruel** [comment]
thanks a million :)
you are a great man :+1:  

you can fix this:
in my 5.2.2 version `updateName(long identifier, StringHolder name)` only support StringHolder!
I think the method with `String name` is forgotten ... probably.
