### ISSUE TITLE
AccountHeader: Prevent / revert account switching in AccountHeaderListener

### ISSUE THREAD

**Issue by toastking42** [mikepenz/MaterialDrawer#1320]
Hello Mike,

under certain conditions, I don't want my users to switch the email account in the application. However, while I'm able to create an AlertDialog in the AccountHeaderListener.onProfileChanged of the AccountHeader, I'm unable to prevent the drawer from actually switching the accounts, i.e. showing the newly selected email account in the AccountHeader. I've tried changing the return value of onProfileChanged, but it doesn't make a difference.

What I'd like to achieve is, for example, if a user has two mailaccount EMAIL1 and EMAIL2, and EMAIL2 is the currently active account. Then I want to somehow intercept when the user changes to EMAIL1 in the account header and, depending on if the action is valid at the moment or not, either let your navigation drawer change the account (like it does right now) or prevent it from doing that (i.e. keep EMAIL2 as the active account).

Is there any possible way to do this? I could imagine that this is a fairly regular use case.

Thanks!

**Comment by mikepenz** [comment]
@toastking42 if you have an `OnAccountHeaderListener` you can just return `true` to tell the `AccountHeader` that the event was consumed and no further action should be done. So also not switching the profile:

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L385

**Comment by toastking42** [comment]
Thanks @mikepenz, I'm going to try that :) I think my mistake was that I returned false (thinking that it would have the effect that returning true actually has).

**Comment by toastking42** [comment]
Hi @mikepenz , unfortunately, it doesn't work. It doesn't matter if I return true or false in onProfileChanged, the header will always switch to the account the user has selected. Is this a bug?

**Comment by mikepenz** [comment]
@toastking42 oh sorry you are totally right. In the `AccountHeader` the profile is already switched when this event is fired. I totally missed this part. 

With `true` you consume the event and prevent the drawer from being closed.

so what else you could do is to disable the profiles from being `selectable` (`withSelectable(false)`) or you disable the possibility that the user opens the `AccountSelection` so he can't change the profile.

**Comment by toastking42** [comment]
Okay, thanks. That's less convenient for me, it would have been easier to be able to decide 'on demand' if the user is allowed to switch accounts instead of having to determine it beforehand. However, it's not really a big issue. Thanks Mike!

**Comment by mikepenz** [comment]
@toastking42 yeah in some rare cases a `preChangeListener` would be helpful here
