### ISSUE TITLE
need to update the Account header item's on certain event

### ISSUE THREAD

**Issue by mwshubham** [mikepenz/MaterialDrawer#1322]
I have changed certain listener to make the single profile in account header.

using this
In general it is enough if you look at this method: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L1347 (which handles the toggling from one list to the other
and this one:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L1389

![device-2016-06-06-190822](https://cloud.githubusercontent.com/assets/8881480/15823918/70a6d97c-2c1a-11e6-9c80-b57d12f661bd.png)

This image is showing the main drawer item.

![device-2016-06-06-190846](https://cloud.githubusercontent.com/assets/8881480/15824157/6b3fce52-2c1b-11e6-8e06-c6fc6a91676c.png)

This image is showing theAccount header profile.

Simple Account header code:

```java
  mAccountHeader = new AccountHeaderBuilder()
                    .withActivity(this)
                    .withTranslucentStatusBar(true)
                    .withHeaderBackground(R.drawable.navigation_drawer_header_bg)
                    .withSelectionListEnabled(false)
                    .withAccountHeader(R.layout.material_drawer_header)
//                  .withCompactStyle(true)
//               TODO::: NO MULTIPLE ICONS AVAILABLE FOR MYORDER
                    .addProfiles(
                            getIProfile()
                    )
                    .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                        @Override
                        public boolean onProfileChanged(View view, IProfile profile, boolean current) {
                            //false if you have not consumed the event and it should close the drawer
                            if (!customerDataShared.getBoolean("isLoggedIn", false)) {
                                if (mDrawer != null && mDrawer.isDrawerOpen()) {
                                    mDrawer.closeDrawer();
                                }
                                startActivity(new Intent(MainActivity.this, LoginActivity.class));
                            }
                            return true;
                        }
                    })
                    .withSavedInstance(savedInstanceState)
                    .build();
```

Simple Drawer Code:

```java
  mDrawer = new DrawerBuilder()
                    .withActivity(this)
                    .withToolbar(toolbar)
                    .withHasStableIds(true)
                    .withItemAnimator(new AlphaCrossFadeAnimator())
                    .withAccountHeader(mAccountHeader) //set the AccountHeader we created earlier for the header
                    .addDrawerItems(
                            mProfileDrawerItem
                    ) // add the items we want to use with our Drawer
                    .withOnDrawerItemClickListener(myPrimaryOnDrawerItemClickListener)
                    .withSavedInstance(savedInstanceState)
                    .withShowDrawerOnFirstLaunch(true)
                    .build();
```

But the problem is **i want to update some Account Header profile.** let say i have 4 profile some time and no profle. How can i implement this.

I have created a new account header and updated the drawer like this. 

```java
 mDrawer.setHeader(mAccountHeader.getView());
 mAccountHeader.setDrawer(mDrawer);
```

But my profle section is empty i don't know the reason. Please provide some solution.

**_Thanks_**

**Comment by mikepenz** [comment]
@mwshubham what exactly do you want to update. You want to update the list of items dispalyed in the `AccountHeader` selection?

**Comment by mwshubham** [comment]
yes i want to update the  list of items dispalyed in the AccountHeader selection

**Comment by mwshubham** [comment]
sorry for the trouble but the problem was that 
This is where we add account section profile but i was not updating profileDrawerItems.
mDrawer.switchDrawerContent(mySecondaryOnDrawerItemClickListener, null, profileDrawerItems, 0);

How ever it will be very helpful if you share any piece of code you have in which drawer item or account section items update within the application? e.g. some menu are visible in login mode but not in logged out mode.

**Comment by mwshubham** [comment]
Please close the issue @mikepenz  as the problem is solved for now.

**Comment by mikepenz** [comment]
@mwshubham if you want to update the list of elements in the `AccountHeader` you can use the methods provided via the `AccountHeader` object:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L284
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L298
