### ISSUE TITLE
SectionHeader with withEnableSelectedMiniDrawerItemBackground(true)

### ISSUE THREAD

**Issue by NirujanSuresh** [mikepenz/MaterialDrawer#1324]
I basically modified the MiniDrawerActivity so that I set withEnableSelectedMiniDrawerItemBackground(true) and I added a sectionheader as the first draweritem. When I click an item on the minidrawer, it gets selected and the background changes accordingly. However when you rotate it, two minidrawer items gets the "selected" background color change.

**Comment by NirujanSuresh** [comment]
adding a sectiondraweritem in between primarydraweritems seems to mess up with the minidrawer selected item background (primaryitems after the sectiondraweritem, it works fine for items before it)

**Comment by mikepenz** [comment]
could you please add  a small sample app so I can reproduce this

**Comment by NirujanSuresh** [comment]
https://www.dropbox.com/s/7fidqa4njmq18rh/MaterialDrawer.zip?dl=0

Go to the minidrawer, select the gamepad icon, rotate the device and notice both the gamepad and eye icon are selected on the minidrawer. But dragging to see the full drawer, only the gamepad drawer item is selected. Let me know if you need anything else. 

Thanks
