### ISSUE TITLE
Issue with compiling 5.3.0

### ISSUE THREAD

**Issue by NirujanSuresh** [mikepenz/MaterialDrawer#1325]
I get the following error:

Error:(1471) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar.TranslucentStatus'.
Error:(1447) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar'.
Error:(1423) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme'.
Error:(1495) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light'.
Error:(1518) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.ActionBar'.
Error:(1541) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.ActionBar.TranslucentStatus'.
Error:(1564) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar'.
Error:(1587) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.ActionBar'.
Error:(1610) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.ActionBar.TranslucentStatus'.

It seems like these styles are missing on 5.3.0. The previous version (5.2.9) works fine.

**Comment by mikepenz** [comment]
@NirujanSuresh it may be related that it's still only available on jCenter and mavenCentral still needs some time syncing. 

Otherwhise everything is correct, as I also used it in an app already

**Comment by NirujanSuresh** [comment]
I'll give it some more time but I get the same error now.

**Comment by mikepenz** [comment]
Do you have a different version of the appcompat library in?

**Comment by NirujanSuresh** [comment]
23.4.0

Its the same version I used with 5.2.9 and it worked fine

**Comment by mikepenz** [comment]
@NirujanSuresh weird. normally it should be synced now already. nothing else changed.

**Comment by NirujanSuresh** [comment]
yeah I saw the commits and they seem like it would have nothing to do with this problem

Here's the sample project if you want to look into it. I'll continue investigating as well
https://www.dropbox.com/s/oszm3h03ugmd2pf/Test.zip?dl=0

**Comment by mwshubham** [comment]
@NirujanSuresh  please update your project level build file

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
        classpath 'com.google.gms:google-services:3.0.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by NirujanSuresh** [comment]
adding mavenCentral to allprojects did the trick. thank you @mwshubham
