### ISSUE TITLE
Using MaterialDrawer and Fragment with Tabs

### ISSUE THREAD

**Issue by fncapps** [mikepenz/MaterialDrawer#1327]
I have a drawer with some items that replace the container with different fragments. I need one of them to have a `TabLayout` and a `ViewPager`.

I managed to achieve all of that, but I am not able to make the `TabLayout` look like if it was integrated with the  `Toolbar`. I mean, I cannot remove this shadow in between both of them:

![drawer tabs](https://cloud.githubusercontent.com/assets/9203317/15912344/f1ab47d2-2dd3-11e6-960b-99653dc3a4a8.jpg)

Is there any way to fix this?

**Comment by mikepenz** [comment]
@fncapps that's not related to the `MaterialDrawer` (especially if you use the normal behavior where the drawer is full height). The shadow comes from the `Toolbar` you may just set `elevation=0dp`

**Comment by fncapps** [comment]
I'm using `MaterialDrawer` and I don't know how to set `elevation=0dp` that's why I was posting it here. If you could help me out it would be great. 

Sorry for the inconvenience.

**Comment by mikepenz** [comment]
@fncapps the `Toolbar` or `ActionBar` is not handled by the `MaterialDrawer`. So nothing library related

**Comment by fncapps** [comment]
@mikepenz sorry, you are completely right. My fault. Here's the solution just in case anyone get lost as I did:


        ActionBar toolbar = ((AppCompatActivity) getActivity()).getSupportActionBar();
        if(toolbar != null) {
            toolbar.setElevation(0);
        }
