### ISSUE TITLE
Request - BottomDrawerItem

### ISSUE THREAD

**Issue by TurKurT656** [mikepenz/MaterialDrawer#133]
I want to have a bottom section for settings. is there a way to add this?
the position of this item must be the bottom of the screen

**Comment by Rainer-Lang** [comment]
This is possible. Please read the docu.

**Comment by TurKurT656** [comment]
@Rainer-Lang  how is that possible?
I've read the documentations on MaterialWiki but i couldn't find anything!!!

**Comment by Rainer-Lang** [comment]
It's possible - believe me. 
But you right - nothing in the wiki. 
Could you look at the examples included at github?

**Comment by TurKurT656** [comment]
There is no implementation of this kind of DrawerItem on sample app :(

**Comment by Rainer-Lang** [comment]
Sorry i think for now you can add a view at the bottom. 
Sorry.

**Comment by TurKurT656** [comment]
tnQ for helping :)

**Comment by khammami** [comment]
@TurKurT656  I think you're talking about a sticky footer

if so, search wiki for "withStickyFooter(View stickyFooter)"

**Comment by mikepenz** [comment]
@Rainer-Lang @khammami thanks for helping ;)

@TurKurT656 i think you search for a default option to get such pinned drawer items at the bottom. at the moment you can do this be creating your layout as sticky footer. for the future i will see if there's an easier method how to provide this.

**Comment by TurKurT656** [comment]
@mikepenz TnQ
I don't know how to make a custom drawer item. I couldnt find documentation about this.

**Comment by mikepenz** [comment]
Just take a look at any of the provided drawerItems they all implement the same IDrawerItem interface
