### ISSUE TITLE
how to put icon to the right of text ?

### ISSUE THREAD

**Issue by masepehr** [mikepenz/MaterialDrawer#1331]
I set the `.withDrawerGravity(Gravity.END)` and the problem is i want drawer item icon be in the right of the text. is that possible? 
and the second, i want to put my actionbar icon in the left of the toolbar . is that possible?

**Comment by mikepenz** [comment]
@masepehr the drawer will be in RTL mode automatically if your application is in RTL (please look up Stackoverflow how to create an application in RTL layout) otherwhise you will have to create your own `CustomDrawerItem` with a switched layout.
