### ISSUE TITLE
I'm getting Empty Drawer

### ISSUE THREAD

**Issue by maravilhosinga** [mikepenz/MaterialDrawer#1332]
I put this code in my Activity and i'm getting empty Drawer Dark

Help please

new DrawerBuilder().withActivity(this).build();

**Comment by mikepenz** [comment]
@maravilhosinga you do not add items to it :D But as you already have an empty drawer now it works fine ;) (so with the above you just create the drawer, now you have to fill it too)

https://github.com/mikepenz/MaterialDrawer#additional-setup
