### ISSUE TITLE
Second drawer status bar is not translucent

### ISSUE THREAD

**Issue by mockitoo** [mikepenz/MaterialDrawer#1335]
i have two drawer. the right one appends left drawer. on kitkat right drawer is not translucent.
this is my config : 
```java
private Drawer buildDrawer() {
        headerResult = createAccountHeader(R.drawable.header);
        loginDrawerItem = createLoginDrawerItem();
        return new DrawerBuilder()
                .withActivity(getActivity())
                .withAccountHeader(headerResult)
                .addDrawerItems(navigationItemHolder.getDrawerItems())
                .addStickyDrawerItems(loginDrawerItem)
                .withOnDrawerItemClickListener(new DrawerItemClickListener())
                .withFooter(R.layout.navigation_drawer_footer)
                .withDrawerGravity(Gravity.START)
                .withOnDrawerListener(this).build();
    }

    private Drawer buildRightDrawer() {
        return new DrawerBuilder()
                .withActivity(getActivity())
                .withAccountHeader(createAccountHeader(R.drawable.newspaper_glasses))
                .withOnDrawerItemClickListener(new RightDrawerItemClickListener())
                .withDrawerWidthDp(250)
                .withDrawerGravity(Gravity.END)
                .append(drawer);
    }
```

![screenshot from 2016-06-13 19-17-34](https://cloud.githubusercontent.com/assets/16718247/16014822/9172e69c-319b-11e6-939a-993cd19ac307.png)

![screenshot from 2016-06-13 19-17-48](https://cloud.githubusercontent.com/assets/16718247/16014840/a10a096e-319b-11e6-9822-d507bb50bd50.png)

**Comment by mockitoo** [comment]
main_activity layout configuration file which is drawer attached to

layout-v19 : 
`<?xml version="1.0" encoding="utf-8"?>
<android.support.design.internal.ScrimInsetsFrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/fragment_container"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />`

layout-v21:
`<android.support.design.internal.ScrimInsetsFrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/fragment_container"
    android:fitsSystemWindows="true"
    android:background="@android:color/white"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />`

and style configuration:

`<style name="AppTheme.Base" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimary">@color/color_primary</item>
        <item name="colorPrimaryDark">@color/color_primary_dark</item>
        <item name="colorAccent">@color/color_accent</item>
        <item name="android:textColorPrimary">@color/color_primary_text</item>
        <item name="android:textColorSecondary">@color/color_secondary_text</item>
        <item name="colorButtonNormal">@color/color_primary</item>
       <item name="android:windowTranslucentStatus">true</item>
  </style>`

i could not resolve this issue, what is the mistake ?

**Comment by mikepenz** [comment]
@mockitoo I can't see the mistake instantly. But If I run the `MultiDrawerActivity` and just remove the following line
```java
.withDisplayBelowStatusBar(true)
```
of the second drawer and add the following
```java
.withHeader(R.layout.header)
```
then it is working fine.

**Comment by mikepenz** [comment]
Hmmm some things which may help to solve your issue. 
- Try to depend on one of the `MaterialDrawer` themes which also depend on the `AppCompat` themes, but set the correct values
- Try to remove the `ScrimInsetsFrameLayout` with a normal `RelativeLayout` as its also used in the `MultiDrawerActivity`

**Comment by mockitoo** [comment]
@mikepenz  thanks for your help but none of above didn't work. 
changed base style to MaterialDrawer.Light => didn't work
replaced ScrimInsetsLayout with RelativeLayout or FrameLayout => didn't work
also i changed header layout or removed completely, but unfortunutely didn't work

only it works when i build second drawer as standalone instead of append to primary drawer, but this time primary drawer  translucent status bar disappears :(

this is my complete navigation drawer manager class : 


`import android.app.Activity;
import android.content.Context;
import android.content.pm.PackageManager;
import android.graphics.drawable.Drawable;
import android.net.Uri;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentTransaction;
import android.support.v7.app.ActionBar;
import android.support.v7.app.AppCompatActivity;
import android.view.Gravity;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;

import com.mikepenz.fontawesome_typeface_library.FontAwesome;
import com.mikepenz.iconics.typeface.IIcon;
import com.mikepenz.materialdrawer.AccountHeader;
import com.mikepenz.materialdrawer.AccountHeaderBuilder;
import com.mikepenz.materialdrawer.Drawer;
import com.mikepenz.materialdrawer.DrawerBuilder;
import com.mikepenz.materialdrawer.holder.StringHolder;
import com.mikepenz.materialdrawer.model.AbstractDrawerItem;
import com.mikepenz.materialdrawer.model.BaseDrawerItem;
import com.mikepenz.materialdrawer.model.PrimaryDrawerItem;
import com.mikepenz.materialdrawer.model.ProfileDrawerItem;
import com.mikepenz.materialdrawer.model.interfaces.IDrawerItem;
import com.mikepenz.materialdrawer.model.interfaces.Nameable;
import com.mikepenz.materialdrawer.util.AbstractDrawerImageLoader;
import com.mikepenz.materialdrawer.util.DrawerImageLoader;
import com.mikepenz.materialdrawer.util.KeyboardUtil;


import org.apache.commons.lang3.StringUtils;

import java.util.List;


public class NavigationDrawerManager implements Drawer.OnDrawerListener {

    private static final int LOGIN_LOGOUT_DRAWER_ITEM_IDENTIFIER = 0;
    private static final int USER_PROFILE_IDENTIFIER = 1;
    NavigationItemHolder navigationItemHolder = new NavigationItemHolder();

    private final AppCompatActivity activity;
    private AccountHeader headerResult;
    private PrimaryDrawerItem loginDrawerItem;

    private Drawer drawer;
    private Drawer rightDrawer;

    public NavigationDrawerManager(AppCompatActivity activity) {
        this.activity = activity;
        DrawerImageLoader.init(new ImageLoader());
        buildNavigationDrawer();
    }

    public void buildNavigationDrawer() {
        this.drawer = buildDrawer();
        this.rightDrawer = buildRightDrawer();
        setVersionInformationAtFooter();
    }

    private Drawer buildDrawer() {
        headerResult = createAccountHeader(getActivity(),R.drawable.header);
        loginDrawerItem = createLoginDrawerItem();
        return new DrawerBuilder()
                .withActivity(getActivity())
                .withAccountHeader(headerResult)
                .addDrawerItems(navigationItemHolder.getDrawerItems())
                .addStickyDrawerItems(loginDrawerItem)
                .withOnDrawerItemClickListener(new DrawerItemClickListener())
                .withFooter(R.layout.navigation_drawer_footer)
                .withOnDrawerListener(this).build();
    }

    private Drawer buildRightDrawer() {
        return new DrawerBuilder()
                .withActivity(getActivity())
                .withAccountHeader(createAccountHeader(getActivity(),R.drawable.newspaper_glasses))
                .withOnDrawerItemClickListener(new RightDrawerItemClickListener())
                .withDrawerWidthDp(250)
                .withDrawerGravity(Gravity.END)
                .append(drawer);
    }

    public static AccountHeader createAccountHeader(Activity activity,int headerBackgroundRes) {
        return new AccountHeaderBuilder()
                .withActivity(activity)
                .withCompactStyle(true)
                .withCloseDrawerOnProfileListClick(false)
                .withCurrentProfileHiddenInList(true)
                .withHeaderBackground(headerBackgroundRes)
                .withHeaderBackgroundScaleType(ImageView.ScaleType.CENTER_CROP)
                .build();
    }

    private void setVersionInformationAtFooter() {
        try {
            Context context = getActivity().getApplicationContext();
            String versionName = context.getPackageManager()
                    .getPackageInfo(context.getPackageName(), 0).versionName;
            TextView textView = (TextView) drawer.getFooter().findViewById(R.id.textViewVersionInfo);
            textView.setText(textView.getText().toString().replace("{versionName}", versionName));
        } catch (PackageManager.NameNotFoundException e) {
            throw new RuntimeException(e);
        }
    }

    private PrimaryDrawerItem createLoginDrawerItem() {
        return new PrimaryDrawerItem()
                .withName(R.string.login)
                .withIcon(FontAwesome.Icon.faw_sign_in)
                .withIdentifier(LOGIN_LOGOUT_DRAWER_ITEM_IDENTIFIER);
    }

    private Fragment replaceFragment(AbstractDrawerItem drawerItem, int layoutContainerId) {
        Fragment fragment = createFragment(drawerItem);
        FragmentTransaction fragmentTransaction = getActivity().getSupportFragmentManager().beginTransaction().replace(layoutContainerId, fragment);
        fragmentTransaction.commit();
        getActivity().getSupportFragmentManager().executePendingTransactions();
        return fragment;
    }

    private AppCompatActivity getActivity() {
        return activity;
    }

    private Fragment createFragment(AbstractDrawerItem drawerItem) {
        return navigationItemHolder.createFragment(drawerItem);
    }


    protected void onClickDoLogin() {

    }

    protected void onClickDoLogout() {

    }


    public ActionBar getSupportActionBar() {
        return getActivity().getSupportActionBar();
    }

    protected void onDrawerItemClicked(IDrawerItem drawerItem, int position) {
        // replace fragment
        if (drawerItem instanceof AbstractDrawerItem && navigationItemHolder.isFragmentDrawerItem((AbstractDrawerItem) drawerItem)) {
            AbstractDrawerItem abstractDrawerItem = (AbstractDrawerItem) drawerItem;
//            setActionBarTitle(drawerItem);
            replaceFragment(abstractDrawerItem, R.id.fragment_container);
        }
    }

    public void setActionBarTitle(IDrawerItem drawerItem) {
        ActionBar supportActionBar = getSupportActionBar();
        if (supportActionBar == null) {
            return;
        }

        if (drawerItem != null && drawerItem instanceof Nameable) {
            StringHolder name = ((Nameable) drawerItem).getName();
            if (name.getText() != null && !name.getText().isEmpty()) {
                supportActionBar.setTitle(name.getText());
            } else if (name.getTextRes() > 0) {
                supportActionBar.setTitle(getActivity().getResources().getString(name.getTextRes()));
            }
        }
    }

    public void selectDrawerItemByResourceId(int resourceId) {
        int drawerItemPositionByName = navigationItemHolder.getDrawerItemByName(resourceId);
        if (drawerItemPositionByName != -1) {
            drawer.setSelectionAtPosition(drawerItemPositionByName + 1);
        }
    }

    public void selectDrawerItem(IDrawerItem drawerItem) {
        List<IDrawerItem> drawerItems = drawer.getDrawerItems();

        int position = 0;
        for (IDrawerItem drawerItem1 : drawerItems) {
            if (drawerItem.getTag().equals(drawerItem1.getTag())) {
                drawer.setSelectionAtPosition(position + 1);
            }
            position++;
        }
//        drawer.setSelection(drawerItem);
    }

    public void openNavigationDrawer() {
        drawer.openDrawer();
    }

    public void toggleRightDrawer() {
        if (rightDrawer.isDrawerOpen()) {
            rightDrawer.closeDrawer();
        } else {
            rightDrawer.openDrawer();
        }
    }

    @Override
    public void onDrawerOpened(View view) {
        KeyboardUtil.hideKeyboard(getActivity());
    }

    @Override
    public void onDrawerClosed(View view) {

    }

    @Override
    public void onDrawerSlide(View view, float v) {

    }

    public List<IDrawerItem> getDrawerItems() {
        return drawer.getDrawerItems();
    }

    protected void changeDrawerItemName(int identifier, String name) {
        IDrawerItem drawerItem = drawer.getDrawerItem(identifier);
        if (drawerItem instanceof Nameable) {
            ((Nameable) drawerItem).withName(name);
        }
    }

    protected void changeDrawerItemProperties(int identifier, String name, IIcon icon) {
        IDrawerItem drawerItem = drawer.getDrawerItem(identifier);
        if (icon != null && drawerItem instanceof BaseDrawerItem) {
            ((BaseDrawerItem) drawerItem).withIcon(icon);
        }

        if (name != null && drawerItem instanceof Nameable) {
            ((Nameable) drawerItem).withName(name);
        }

        drawer.updateItem(drawerItem);
    }


    public void setProfile(String email, String photoUrl) {
        String name = StringUtils.substringBefore(email, "@");
        ProfileDrawerItem profile = new ProfileDrawerItem()
                .withIdentifier(USER_PROFILE_IDENTIFIER).withEmail(email).withName(name);

        if (StringUtils.isNotBlank(photoUrl)) {
            profile.withIcon(photoUrl);
        } else {
            profile.withIcon(R.drawable.user);
        }

        headerResult.addProfiles(profile);
        headerResult.setActiveProfile(profile);

        toggleLoginLogoutDrawerItem();
    }

    private void toggleLoginLogoutDrawerItem() {
        if (R.string.login == loginDrawerItem.getName().getTextRes()) {
            loginDrawerItem
                    .withName(R.string.drawer_item_logout)
                    .withIcon(FontAwesome.Icon.faw_sign_out);
        } else {
            loginDrawerItem
                    .withName(R.string.login)
                    .withIcon(FontAwesome.Icon.faw_sign_in);
        }

        drawer.updateStickyFooterItem(loginDrawerItem);
    }

    private class ImageLoader extends AbstractDrawerImageLoader {
        @Override
        public void set(ImageView imageView, Uri uri, Drawable placeholder) {
            if (uri == null) {
                imageView.setImageResource(R.drawable.unknown_user);
            } else {
                ImageDownloader.instance.displayImage(uri.toString(), imageView);
            }

        }
    }

    public void setRightDrawerItems(List<IDrawerItem> drawerItems) {
        rightDrawer.removeAllItems();
        rightDrawer.addItems(drawerItems.toArray(new IDrawerItem[0]));
    }

    class DrawerItemClickListener implements Drawer.OnDrawerItemClickListener {

        @Override
        public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
            if (drawerItem == null) {
                return true;
            }

            // login-logout drawer item
            if (drawerItem == loginDrawerItem) {
                if (loginDrawerItem.getName().getTextRes() == R.string.login) {
                    onClickDoLogin();
                } else {
                    onClickDoLogout();
                    headerResult.removeProfileByIdentifier(USER_PROFILE_IDENTIFIER);
                    toggleLoginLogoutDrawerItem();
                }
                return false;
            }

            onDrawerItemClicked(drawerItem, position);
            return false;
        }
    }

    class RightDrawerItemClickListener implements Drawer.OnDrawerItemClickListener {

        @Override
        public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
            EventBus.publish(new RightDrawerItemSelectedEvent(drawerItem, position));
            return false;
        }
    }
}`

**Comment by mikepenz** [comment]
@mockitoo hmmm :( If you want you can send me the app (just remove everything specific if you are scared) via email and I will take a look and let you know what to change.

**Comment by mockitoo** [comment]
ok @mikepenz, i'm preparing the zip file but it will take some time, i need to remove too many file. i will send to mikepenz@gmail.com  when it is ready. thanks again

**Comment by mikepenz** [comment]
Don't worry. Will have a look tomorrow.

Ok great. Thanks :)

mockitoo <notifications@github.com> schrieb am Sa., 18. Juni 2016, 22:26:

> ok @mikepenz <https://github.com/mikepenz>, i'm preparing the zip file
> but it will take some time, i need to remove too many file. i will send to
> mikepenz@gmail.com when it is ready. thanks again
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mikepenz/MaterialDrawer/issues/1335#issuecomment-226963158>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABaGiFQZmrTwjcd0ux66rCHb2BgsqIe7ks5qNFSDgaJpZM4I0f0y>
> .
>
-- 
Mike Penz
__________________________________________
*Mike Penz*
Android | Backend | Open Source | Web Developer
mikepenz.com
lanora.io

**Comment by mockitoo** [comment]
Hi @mikepenz. i've just created a sample project that produces to same result.
 [Here is the repository](https://github.com/mockitoo/SampleApp). Good luck with that

**Comment by mikepenz** [comment]
@mockitoo hmmm in Android N it works fine. But API 19 it breaks. It doesn't seem to be padding related, because if I set the padding to 0 on all views it still has the space on top. 

(I recommend you to update to v5.3.1 as it will fix the shadow issue)

**Comment by mikepenz** [comment]
@mockitoo I haven't yet found anything new. :/

**Comment by mikepenz** [comment]
@mockitoo have you found out anything?

**Comment by mockitoo** [comment]
unfortunately i could not find any solution. i think it is related to
fitSystemWindows=true and ScrimInsetsLayout as you mention before.

**Comment by mikepenz** [comment]
@mockitoo is it still an issue on your side.

**Comment by mockitoo** [comment]
yes, status bar still looks weird when right drawer opens on kitkat.

**Comment by mikepenz** [comment]
@mockitoo ok after some more digging I have found out some additional information. 

The point is that you force the translucent statusbar on API 19 which does not yet fully support (and correctly) support the `fitsSystemWindows` flag in combination with the translucent statusbar. You will also notice that I do no longer allow this behavior in the library (and have disabled it in the themes) as it requires a lot of custom handling. This was possible prior to v5 which handled paddings etc manually. 

You either can also remove the translucent statusbar for API 19, 
keep the issue with API 19
or go back to a v4 drawer with no support and losing some functionality

**Comment by mockitoo** [comment]
hi @mikepenz, thank you for your first effort. 

i'm very happy with MaterialDrawer v5 so i can't go back to v4 because i need some features of v5. 
Also i need to use translucent status bar, so i will keep this issue with API 19. I have no other choice. 

Thanks again, you're doing a great job

**Comment by mikepenz** [comment]
@mockitoo I am sorry for this. I also had many troubles when doing the choice to go with `fitsSystemWindows` for v5 as I had to remove the translucentStatusbar feature for API 19. 

but `fitsSystemWindows` is the way to go as we should try to use as much from the system as possible.

thank you
