### ISSUE TITLE
ProfileDrawerItem Icon refreshes every time

### ISSUE THREAD

**Issue by javalnanda** [mikepenz/MaterialDrawer#1337]
Whenever I click on Account Header to switch accounts, the accounts in the list view always refresh icon and the default icon is visible for some time. This happens even if the icons were downloaded previously and cached. Sometimes it even fails to load icon when switching between menu options and account view even thought the icon was downloaded and visible previously

**Comment by mikepenz** [comment]
@javalnanda which image loading library do you use?

**Comment by javalnanda** [comment]
@mikepenz I am using Picasso library. Your direction would be helpful to analyze the root cause.

**Comment by mikepenz** [comment]
@javalnanda the sample uses `glide` so you might want to try it with glide too. 
The first time it's ok because it has to resize the icon, but afterwards there should be no "loading" visible anymore

**Comment by javalnanda** [comment]
@mikepenz Thanks, with glide it works fine !!!

**Comment by mikepenz** [comment]
@javalnanda seems like `picasso` does not really cache the image performant enough
