### ISSUE TITLE
Header Customization

### ISSUE THREAD

**Issue by maravilhosinga** [mikepenz/MaterialDrawer#1339]
Hello, its possible to customize de Drawer Header, i want to make it look very particular.
Any help please

**Comment by mikepenz** [comment]
@maravilhosinga please add some screenshots, so I can tell you if this sort of customization is possible

**Comment by mikepenz** [comment]
@maravilhosinga 
https://github.com/mikepenz/MaterialDrawer/issues/992#issuecomment-181354255
https://github.com/mikepenz/MaterialDrawer/issues/617#issuecomment-137166976
