### ISSUE TITLE
Request - Settings pinned to bottom 

### ISSUE THREAD

**Issue by mseroczynski** [mikepenz/MaterialDrawer#134]
Hey there @mikepenz. Are you planning to add possibility to glue "Settings" item to the bottom of the drawer? Personally, I find this ux pattern most useful way to present settings and i'm really looking forward to see it in your awesome lib :)

**Comment by TurKurT656** [comment]
Hi, I've Requested This in #133 issue

**Comment by mikepenz** [comment]
@mseroczynski this is a duplicate :D i close this one. further discussion in the ticket #133
