### ISSUE TITLE
Can't seem to Import a bunch of classes

### ISSUE THREAD

**Issue by ayush1252** [mikepenz/MaterialDrawer#1340]
Import for following classes doesn't work for me and hence I am not able to implement CrossFadeDrawerLayout

import com.mikepenz.crossfadedrawerlayout.view.CrossfadeDrawerLayout;
import com.mikepenz.fontawesome_typeface_library.FontAwesome;

import com.mikepenz.materialdrawer.AccountHeader;
import com.mikepenz.materialdrawer.AccountHeaderBuilder;

import com.mikepenz.materialdrawer.MiniDrawer;
import com.mikepenz.materialdrawer.holder.BadgeStyle;
import com.mikepenz.materialdrawer.interfaces.ICrossfader;

**Comment by mikepenz** [comment]
@ayush1252 make sure you follow the instructions:
https://github.com/mikepenz/MaterialDrawer#1-provide-the-gradle-dependency

perhaps also make sure that `mavenCentral()` comes before `jCenter()` in your root build.gradle
