### ISSUE TITLE
Removing the Account Change Icon

### ISSUE THREAD

**Issue by mtwn105** [mikepenz/MaterialDrawer#1341]
How to remove the account change "arrow" and just want one profile with email and a pic. Likes shown below.
![screenshot_20160615-111319 1](https://cloud.githubusercontent.com/assets/12975481/16069207/4f4712fc-32ea-11e6-95d3-ef41d786d3dc.jpg)

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/615
