### ISSUE TITLE
OnDrawerItemClickListener not always called (CrossfadeDrawerLayout)

### ISSUE THREAD

**Issue by codeAbode** [mikepenz/MaterialDrawer#1345]
Sometimes when I press on a drawer item, the listener is not called and the item needs to be pressed again. Below is my drawer click listener:

```java
.withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        Log.d(TAG, "onItemClick: "+position);
                            switch(position){
                                case 1:
                                    if(context.getClass() !=  MainActivity.class){
                                        Intent s = new Intent(context, MainActivity.class);
                                        context.startActivity(s);
                                    }
                                    break;
```

And this is a snippet of my drawer builder:

```java
 final Drawer drawer = new DrawerBuilder()
                .withActivity((Activity) context)
                .withHasStableIds(true)
                .withToolbar(toolbar)
                .withDrawerLayout(R.layout.crossfade_drawer)
                .withSliderBackgroundColor(ContextCompat.getColor(context, R.color.darkgrey))
                .withDrawerWidthDp(72)
                .withDelayDrawerClickEvent(-1)
                .withAccountHeader(headerResult) //set the AccountHeader we created earlier for the header
                .withCloseOnClick(true)
                .addDrawerItems(
                        new PrimaryDrawerItem()
                                .withName(R.string.home_drawer_title)
                                .withSelectedColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected))
                                .withTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_text))
                                .withSelectedTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected_text))
                                .withIcon(GoogleMaterial.Icon.gmd_home).withIconColor(ContextCompat.getColor(context, R.color.grey))
                                .withIconColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_icon))
                                .withSelectedIconColor(ContextCompat.getColor(context, R.color.colorPrimary))
```

**Comment by mikepenz** [comment]
@codeAbode are you sure you click correctly and don't move the finger out of the view or moved the view? Never experienced anything similar. 

On which device with which android version did you get this issue?

Anyhow reproduceible?

**Comment by codeAbode** [comment]
Thanks for the quick response. I am using this on api 23 and its quite a regularly occurence. Seems to work fine on my emulator but on my galaxy s7 it doesn't work. Note this is only the case when the draw is fully expanded. When it is a mini drawer all the clicks work all the time

**Comment by codeAbode** [comment]
This also happens when the drawer icon is clicked. Sometimes it doesn't register and it must be clicked twice.

**Comment by codeAbode** [comment]
This is my full implementation for creating the drawer


public static Drawer createDrawer(final Context context, Toolbar toolbar, int position) {
        final IProfile profile = new ProfileDrawerItem().withIcon(R.drawable.mysepta_icon_round);

        // Create the AccountHeader
        final AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity((Activity) context)
                .withHeaderBackground(R.drawable.mysepta_banner_photo)
                .withProfileImagesClickable(false)
                .withProfileImagesClickable(false)
                .addProfiles(
                        profile
                )
                .build();

        //Create the drawer
        final Drawer drawer = new DrawerBuilder()
                .withActivity((Activity) context)
                .withHasStableIds(true)
                .withToolbar(toolbar)
                .withDrawerLayout(R.layout.crossfade_drawer)
                .withSliderBackgroundColor(ContextCompat.getColor(context, R.color.darkgrey))
                .withDrawerWidthDp(72)
                .withDelayDrawerClickEvent(-1)
                .withAccountHeader(headerResult) 
                .withCloseOnClick(true)
                .addDrawerItems(
                        new PrimaryDrawerItem()
                                .withName(R.string.home_drawer_title)
                                .withSelectedColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected))
                                .withTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_text))
                                .withSelectedTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected_text))
                                .withIcon(GoogleMaterial.Icon.gmd_home).withIconColor(ContextCompat.getColor(context, R.color.grey))
                                .withIconColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_icon))
                                .withSelectedIconColor(ContextCompat.getColor(context, R.color.colorPrimary))
                                .withIdentifier(1),
                        new PrimaryDrawerItem()
                                .withName(R.string.alerts_drawer_title)
                                .withSelectedColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected))
                                .withTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_text))
                                .withSelectedTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected_text))
                                .withIcon(FontAwesome.Icon.faw_exclamation_triangle).withIconColor(ContextCompat.getColor(context, R.color.grey))
                                .withIconColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_icon))
                                .withSelectedIconColor(ContextCompat.getColor(context, R.color.colorPrimary))
//                                .withBadge("22")
//                                .withBadgeStyle(new BadgeStyle(Color.RED, Color.RED).withTextColor(Color.WHITE))
                                .withIdentifier(2),
                        new PrimaryDrawerItem()
                                .withName(R.string.smooch_drawer_title)
                                .withDescription(R.string.smooch_drawer_title_description)
                                .withSelectedColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected))
                                .withTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_text))
                                .withSelectedTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected_text))
                                .withIcon(GoogleMaterial.Icon.gmd_message)
                                .withIconColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_icon))
                                .withSelectedIconColor(ContextCompat.getColor(context, R.color.colorPrimary))
                                .withIdentifier(3),
                        new PrimaryDrawerItem()
                                .withName(R.string.septa_drawer_title)
                                .withSelectedColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected))
                                .withTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_text))
                                .withSelectedTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected_text))
                                .withIcon(ContextCompat.getDrawable(context, ic_twitter))
                                .withIconColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_icon))
                                .withSelectedIconColor(ContextCompat.getColor(context, R.color.white))
                                .withIdentifier(4),

                        new SectionDrawerItem()
                                .withName(context.getString(R.string.drawer_section_header))
                                .withTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_header_selection_text)),

                        new SecondaryDrawerItem()
                                .withName(R.string.settings_drawer_title)
                                .withDescription(R.string.settings_description)
                                .withSelectedColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected))
                                .withTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_secondary_text))
                                .withSelectedTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected_text))
                                .withIcon(GoogleMaterial.Icon.gmd_settings)
                                .withIconColor(ContextCompat.getColor(context, R.color.grey))
                                .withSelectedIconColor(ContextCompat.getColor(context, R.color.colorPrimary))
                                .withIdentifier(6),
                        new SecondaryDrawerItem()
                                .withName(R.string.about_drawer_title)
                                .withSelectedColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected))
                                .withTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_secondary_text))
                                .withSelectedTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected_text))
                                .withIcon(FontAwesome.Icon.faw_book)
                                .withIconColor(ContextCompat.getColor(context, R.color.grey))
                                .withSelectedIconColor(ContextCompat.getColor(context, R.color.colorPrimary))
                                .withIdentifier(5)
                ) // add the items we want to use with our Drawer
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        Log.d(TAG, "onItemClick: "+position);
                            switch(position){
                                case 1:
                                    if(context.getClass() !=  MainActivity.class){
                                        Intent s = new Intent(context, MainActivity.class);
                                        context.startActivity(s);
                                    }
                                    break;
                                case 2:
                                    if(Utility.isNetworkAvailable(context)){
                                        Intent a = new Intent(context, AlertsActivity.class);
                                        context.startActivity(a);
                                    }else{
                                        Toast.makeText(context, context.getString(R.string.no_internet_connection), Toast.LENGTH_LONG).show();
                                    }
                                    break;
                                case 3:
                                    ConversationActivity.show(context);
                                    break;
                                case 4:
                                    Intent twitter = new Intent(context, TwitterActivity.class);
                                    context.startActivity(twitter);
                                    break;
                                case 6:
//                                    Intent settings = new Intent(context, SettingsActivity.class);
//                                    context.startActivity(settings);
                                    break;
                                case 7:
                                    Intent about = new Intent(context, AboutActivity.class);
                                    context.startActivity(about);
                                    break;

                            }
                        return false;
                    }
                })
                .withOnDrawerListener(new Drawer.OnDrawerListener() {
                    @Override
                    public void onDrawerOpened(View drawerView) {

                    }

                    @Override
                    public void onDrawerClosed(View drawerView) {
                        headerResult.addProfiles(profile);
                    }

                    @Override
                    public void onDrawerSlide(View drawerView, float slideOffset) {
                        headerResult.removeProfile(0);
                    }
                })
                .withShowDrawerOnFirstLaunch(true)
                .build();

        if(toolbar == null){
            drawer.setSelectionAtPosition(position, false);
        }
        //get the CrossfadeDrawerLayout which will be used as alternative DrawerLayout for the Drawer
        //the CrossfadeDrawerLayout library can be found here: https://github.com/mikepenz/CrossfadeDrawerLayout
        final CrossfadeDrawerLayout crossfadeDrawerLayout =  (CrossfadeDrawerLayout) drawer.getDrawerLayout();

        //define maxDrawerWidth
        crossfadeDrawerLayout.setMaxWidthPx(DrawerUIUtils.getOptimalDrawerWidth(context));
        //add second view (which is the miniDrawer)
        final MiniDrawer miniResult = drawer.getMiniDrawer();
        //build the view for the MiniDrawer
        View view = miniResult.build(context);
        //set the background of the MiniDrawer as this would be transparent
        view.setBackgroundColor(UIUtils.getThemeColorFromAttrOrRes(context, com.mikepenz.materialdrawer.R.attr.material_drawer_background, com.mikepenz.materialdrawer.R.color.material_drawer_dark_background));
        //we do not have the MiniDrawer view during CrossfadeDrawerLayout creation so we will add it here
        crossfadeDrawerLayout.getSmallView().addView(view, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);

        //define the crossfader to be used with the miniDrawer. This is required to be able to automatically toggle open / close
        miniResult.withCrossFader(new ICrossfader() {
            @Override
            public void crossfade() {
                boolean isFaded = isCrossfaded();
                crossfadeDrawerLayout.crossfade(400);

                //only close the drawer if we were already faded and want to close it now
                if (isFaded) {
                    drawer.getDrawerLayout().closeDrawer(GravityCompat.START);
                }
            }

            @Override
            public boolean isCrossfaded() {
                return crossfadeDrawerLayout.isCrossfaded();
            }
        });

        return drawer;
    }
}

**Comment by codeAbode** [comment]
This is full implementation

public static Drawer createDrawer(final Context context, Toolbar toolbar, int position) {
        final IProfile profile = new ProfileDrawerItem().withIcon(R.drawable.mysepta_icon_round);

        final AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity((Activity) context)
                .withHeaderBackground(R.drawable.mysepta_banner_photo)
                .withProfileImagesClickable(false)
                .withProfileImagesClickable(false)
                .addProfiles(
                        profile
                )
                .build();

        final Drawer drawer = new DrawerBuilder()
                .withActivity((Activity) context)
                .withHasStableIds(true)
                .withToolbar(toolbar)
                .withDrawerLayout(R.layout.crossfade_drawer)
                .withSliderBackgroundColor(ContextCompat.getColor(context, R.color.darkgrey))
                .withDrawerWidthDp(72)
                .withDelayDrawerClickEvent(-1)
                .withAccountHeader(headerResult)
                .withCloseOnClick(true)
                .addDrawerItems(
                        new PrimaryDrawerItem()
                                .withName(R.string.home_drawer_title)
                                .withSelectedColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected))
                                .withTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_text))
                                .withSelectedTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected_text))
                                .withIcon(GoogleMaterial.Icon.gmd_home).withIconColor(ContextCompat.getColor(context, R.color.grey))
                                .withIconColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_icon))
                                .withSelectedIconColor(ContextCompat.getColor(context, R.color.colorPrimary))
                                .withIdentifier(1),
                        new PrimaryDrawerItem()
                                .withName(R.string.alerts_drawer_title)
                                .withSelectedColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected))
                                .withTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_text))
                                .withSelectedTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected_text))
                                .withIcon(FontAwesome.Icon.faw_exclamation_triangle).withIconColor(ContextCompat.getColor(context, R.color.grey))
                                .withIconColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_icon))
                                .withSelectedIconColor(ContextCompat.getColor(context, R.color.colorPrimary))
                                .withIdentifier(2),
                        new PrimaryDrawerItem()
                                .withName(R.string.smooch_drawer_title)
                                .withDescription(R.string.smooch_drawer_title_description)
                                .withSelectedColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected))
                                .withTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_text))
                                .withSelectedTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected_text))
                                .withIcon(GoogleMaterial.Icon.gmd_message)
                                .withIconColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_icon))
                                .withSelectedIconColor(ContextCompat.getColor(context, R.color.colorPrimary))
                                .withIdentifier(3),
                        new PrimaryDrawerItem()
                                .withName(R.string.septa_drawer_title)
                                .withSelectedColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected))
                                .withTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_text))
                                .withSelectedTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected_text))
                                .withIcon(ContextCompat.getDrawable(context, ic_twitter))
                                .withIconColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_primary_icon))
                                .withSelectedIconColor(ContextCompat.getColor(context, R.color.white))
                                .withIdentifier(4),

                        new SectionDrawerItem()
                                .withName(context.getString(R.string.drawer_section_header))
                                .withTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_header_selection_text)),

                        new SecondaryDrawerItem()
                                .withName(R.string.settings_drawer_title)
                                .withDescription(R.string.settings_description)
                                .withSelectedColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected))
                                .withTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_secondary_text))
                                .withSelectedTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected_text))
                                .withIcon(GoogleMaterial.Icon.gmd_settings)
                                .withIconColor(ContextCompat.getColor(context, R.color.grey))
                                .withSelectedIconColor(ContextCompat.getColor(context, R.color.colorPrimary))
                                .withIdentifier(6),
                        new SecondaryDrawerItem()
                                .withName(R.string.about_drawer_title)
                                .withSelectedColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected))
                                .withTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_secondary_text))
                                .withSelectedTextColor(ContextCompat.getColor(context, com.mikepenz.materialdrawer.R.color.material_drawer_dark_selected_text))
                                .withIcon(FontAwesome.Icon.faw_book)
                                .withIconColor(ContextCompat.getColor(context, R.color.grey))
                                .withSelectedIconColor(ContextCompat.getColor(context, R.color.colorPrimary))
                                .withIdentifier(5)
                ) 
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        Log.d(TAG, "onItemClick: "+position);
                            switch(position){
                                case 1:
                                    if(context.getClass() !=  MainActivity.class){
                                        Intent s = new Intent(context, MainActivity.class);
                                        context.startActivity(s);
                                    }
                                    break;
                                case 2:
                                    if(Utility.isNetworkAvailable(context)){
                                        Intent a = new Intent(context, AlertsActivity.class);
                                        context.startActivity(a);
                                    }else{
                                        Toast.makeText(context, context.getString(R.string.no_internet_connection), Toast.LENGTH_LONG).show();
                                    }
                                    break;
                                case 3:
                                    ConversationActivity.show(context);
                                    break;
                                case 4:
                                    Intent twitter = new Intent(context, TwitterActivity.class);
                                    context.startActivity(twitter);
                                    break;
                                case 6:
                                    break;
                                case 7:
                                    Intent about = new Intent(context, AboutActivity.class);
                                    context.startActivity(about);
                                    break;

                            }
                        return false;
                    }
                })
                .withOnDrawerListener(new Drawer.OnDrawerListener() {
                    @Override
                    public void onDrawerOpened(View drawerView) {

                    }

                    @Override
                    public void onDrawerClosed(View drawerView) {
                        headerResult.addProfiles(profile);
                    }

                    @Override
                    public void onDrawerSlide(View drawerView, float slideOffset) {
                        headerResult.removeProfile(0);
                    }
                })
                .withShowDrawerOnFirstLaunch(true)
                .build();

        if(toolbar == null){
            drawer.setSelectionAtPosition(position, false);
        }
        
        final CrossfadeDrawerLayout crossfadeDrawerLayout =  (CrossfadeDrawerLayout) drawer.getDrawerLayout();

        crossfadeDrawerLayout.setMaxWidthPx(DrawerUIUtils.getOptimalDrawerWidth(context));
        final MiniDrawer miniResult = drawer.getMiniDrawer();
        View view = miniResult.build(context);
        view.setBackgroundColor(UIUtils.getThemeColorFromAttrOrRes(context, com.mikepenz.materialdrawer.R.attr.material_drawer_background, com.mikepenz.materialdrawer.R.color.material_drawer_dark_background));
        crossfadeDrawerLayout.getSmallView().addView(view, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);

        miniResult.withCrossFader(new ICrossfader() {
            @Override
            public void crossfade() {
                boolean isFaded = isCrossfaded();
                crossfadeDrawerLayout.crossfade(400);

                if (isFaded) {
                    drawer.getDrawerLayout().closeDrawer(GravityCompat.START);
                }
            }

            @Override
            public boolean isCrossfaded() {
                return crossfadeDrawerLayout.isCrossfaded();
            }
        });

        return drawer;
    }
}

**Comment by codeAbode** [comment]
Sorry for all the comments. 

As for reproducing it use your demo Material Drawer app. It has the same issues with the CrossFadeDrawerLayout.

**Comment by mikepenz** [comment]
@codeAbode thank you for the comments you made, and for the effort you put into providing all the comments. 

But I am afraid I have to give you an answer you do not really want to hear. 

I assume that your issue is a device (or OS (samsung)) related one, as you have the same issue for the drawer icon. Which is not handled by the `MaterialDrawer`. 

It's the `ActionBarDrawerToggle` directly from the appcompat libs. 

For the items in the drawer itself, they have a normal `OnClickListener` set on the `itemView` nothing which can be changed there. So if the `listener` is not called, it's an OS issue. So maybe a issue from Samsung, or yeah. perhaps also the device screen or the touch is broken?

**Comment by codeAbode** [comment]
@mikepenz 

This may be an issue I should have posted in the CrossfadeDrawerLayout. I have not looked a lot into your code but I think its an issue with the drawer closing. 

If the crossfade drawer is expanded it registers a touch event as if you were sliding the drawer so the OnItemClick is never triggered. You have to play with it a bit but basically whatever is capturing the drawer to slide back to a compact state is taking control over an OnItemClick event.

**Comment by mikepenz** [comment]
@codeAbode seems like your assumption with the `CrossfadeDrawerLayout` is right. Weird enough is that I have not modified the original `closeDrawers` function and just call this one, after the item was clicked. Which should theoretically do the same as the drawer does internally. 

One thing could be really true, that you may slide a bit so it is not detected as click. But it is really hard to reproduce this one. 

Its a lot easier to reproduce the `ActionBarDrawerToggle` not fireing issue, just select an item in the normal drawer, and it won't work. but it works if the mini drawer is clicked.

**Comment by mikepenz** [comment]
To be honest I have no idea why it reacts like this. I tried to close the drawer inside a `handler` tried to sync the state of the `ActionBarDrawerToggle` tried to set the full drawers view to INVISIBLE instead of GONE. Tried to close the drawer via different APIs and so on. Nothing really changes the behavior.

**Comment by codeAbode** [comment]
I'll dive into your code and trying playing with it over the next week

**Comment by mikepenz** [comment]
@codeAbode yes. :/ I can't describe what possibly could go wrong here.

**Comment by mikepenz** [comment]
@codeAbode we may should move this to the `CrossfadeDrawerLayout`

**Comment by mikepenz** [comment]
This issue was moved to mikepenz/CrossfadeDrawerLayout#15
