### ISSUE TITLE
VectorDrawable icons not showing in pre-lollipop devices.

### ISSUE THREAD

**Issue by jahirfiquitiva** [mikepenz/MaterialDrawer#1346]
Hi

I'm setting a XML VectorDrawable as icon for draweritems, but they are not being shown in Android KitKat and below.

**Comment by jahirfiquitiva** [comment]
Accidentally closed it, sorry.

**Comment by mikepenz** [comment]
@jahirfiquitiva I am not sure what this has to do with the `MaterialDrawer`. Where do you set the XML `VectorDrawable`?

**Comment by jahirfiquitiva** [comment]
@mikepenz 

I was using `.withIcon(R.drawable.icon)`

and if it was a VectorDrawable, the icon would not appear.

I fixed it using this code:
```java
public static Drawable getVectorDrawable(@NonNull Context context, @DrawableRes int drawable) {
	Drawable vectorDrawable;
	try {
		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
			vectorDrawable = ContextCompat.getDrawable(context, drawable);
		} else {
			vectorDrawable = VectorDrawableCompat.create(context.getResources(), drawable, null);
			if (vectorDrawable != null) {
				vectorDrawable = DrawableCompat.wrap(vectorDrawable);
			}
		}
	} catch (Resources.NotFoundException ex) {
		vectorDrawable = ContextCompat.getDrawable(context, R.drawable.iconshowcase_logo);
	}
	return vectorDrawable != null ? vectorDrawable : null;
}
```

Thanks anyways

**Comment by mikepenz** [comment]
@jahirfiquitiva yes the above makes sense, as I can't decide if an icon is a normal drawable or a `VectorDrawable`
