### ISSUE TITLE
Option to show a shadow in drawer header texts

### ISSUE THREAD

**Issue by jahirfiquitiva** [mikepenz/MaterialDrawer#1347]
Hi Mike,

I was wondering if there's something to make drawer header texts have a shadow so they become more visible when the drawer header picture is too light.

If there isn't, would you mind adding an option for it? 
Thanks.

**Comment by mikepenz** [comment]
@jahirfiquitiva you can just get the reference to the `TextView` and apply whatever you want. 


https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L47
This will return the view. 

And here's the layout so you know the identifiers of the different views:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml

**Comment by jahirfiquitiva** [comment]
Ok, thanks for the info.
