### ISSUE TITLE
README.md examples improvement suggestion, withIndentifier()

### ISSUE THREAD

**Issue by skmlcd** [mikepenz/MaterialDrawer#1349]
Hey, I had a problem with updating my badge after certain action was performed.

```
navigationDrawer.updateBadge(2, new StringHolder(unreadNotifications));
```

This code didn't work. I thought that the first parameter is the same number as position of ```Drawer.OnDrawerItemClickListener```. Please correct me if I'm wrong because I'm only guessing here, in order to update certain item (name/badge) or remove specific item you need to specify withIndentifier, right?

So my code was:

```
 PrimaryDrawerItem itemNotifications = new PrimaryDrawerItem()
                .withName(R.string.drawer_notifications)
                .withIcon(GoogleMaterial.Icon.gmd_notifications_active)
                .withBadge(unreadNotifications)
                .withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.colorPrimary))
                .withSelectable(false);
```
and updateBadge method just didn't work, until I added ```.withIdentifier(2)```

Final code:

```
 PrimaryDrawerItem itemNotifications = new PrimaryDrawerItem()
                .withIdentifier(2)
                .withName(R.string.drawer_notifications)
                .withIcon(GoogleMaterial.Icon.gmd_notifications_active)
                .withBadge(unreadNotifications)
                .withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.colorPrimary))
                .withSelectable(false);
```

Can you please add some kind of example in the README.md so it's a bit less confusing. I know there are examples in the source code, but as a beginner it took me about an hour to figure that out. Thanks.

**Comment by mikepenz** [comment]
@skmlcd I don't think this needs to be mentioned in the README as the whole project has javadoc, and the javadoc states that the `updateBadge` method asks for the `identifier`
http://static.javadoc.io/com.mikepenz/materialdrawer/5.3.1/com/mikepenz/materialdrawer/Drawer.html#updateBadge-long-com.mikepenz.materialdrawer.holder.StringHolder-

**Comment by skmlcd** [comment]
Yeah, but from that alone I thought that ```indentifier``` was auto assigned somehow, since it is not in the examples. All I'm saying is that it would be a lot easier to simply add something like this to example in README.md:

```
item1.("A new name for this drawerItem").withBadge("19").withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.md_red_700));
```
add .withIdentifier(6), so it becomes:

```
//modify an item of the drawer
item1.withIdentifier(6).("A new name for this drawerItem").withBadge("19").withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.md_red_700));
//notify the drawer about the updated element. it will take care about everything else
result.updateItem(item1);

//to update only the name, badge, icon you can also use one of the quick methods
result.updateName(6, "A new name");
```

This example becomes very obvious that the identifier is manually set and it can save some research time for other people.

I know this is not necessary, but it makes it a lot easier to understand. :)

**Comment by skmlcd** [comment]
Also I think that link you provided is not in README.md. That would also be convenient. Thanks!

**Comment by skmlcd** [comment]
Thanks man! :+1:
