### ISSUE TITLE
setting drawer after onSaveIstance produce empty status bar

### ISSUE THREAD

**Issue by multivoltage** [mikepenz/MaterialDrawer#1350]
I fi call normale code like:

```java
result = new DrawerBuilder(this)
                .withActivity(this)
                .withToolbar(toolbar)
                .withDisplayBelowStatusBar(true)
                .withTranslucentStatusBar(true)
                        .withSliderBackgroundColorRes(R.color.md_white_1000)
                //.withSliderBackgroundDrawable(ContextCompat.getDrawable(getApplicationContext(), R.drawable.semi_volto_mac_resized))
                //.withHeader(imageView)
                .addDrawerItems(...
```

all work very well. My app call onSavedIstanceState because of Social login. After that if I call the same code above, Drawer show well, but all actiivty procude a empty space in status bar.

If I remove drawer this do not happend

**Comment by mikepenz** [comment]
@multivoltage can you please add some screenshot?

**Comment by multivoltage** [comment]
Maybe I fix it. I removed "android:fitsSystemWindows="true" from root CordinatorLayout and then I have to override auto-generated values-21 style in this way:

`<style name="AppTheme.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:statusBarColor">@color/md_orange_400</item>
    </style>`

**Comment by mikepenz** [comment]
@multivoltage sounds like it may be an issue with the original system behavior. but really weird.

**Comment by multivoltage** [comment]
I don' t know. After 1 or 2 second android redraw all and layout become normal

**Comment by mikepenz** [comment]
@multivoltage oh that's the problem. you must not do UI manipulation on a non UI thread

**Comment by multivoltage** [comment]
I didn't know that. Ho I can solve? I tried to find a method to block drawer but the only method that can help me is to put and if statement inside position click listener and notice user (Snask or Toast) he can't user there part of app without login. I think to remove hamburger icon, but drawer exist

**Comment by mikepenz** [comment]
If you have to do this in a thread you can move your code to a handler. 

You can read some information about this here:
https://developer.android.com/training/multiple-threads/communicate-ui.html

**Comment by multivoltage** [comment]
A countdown timer is the same. It call onFinish on the MainThread. So the problem isn' t thread.

**Comment by mikepenz** [comment]
@multivoltage I also answered your issue here: http://stackoverflow.com/a/37931254/325479

You say it works if you create the `Drawer` in the `onCreate` so just create it there, and fill in the items after your countdown timer has finished

**Comment by multivoltage** [comment]
Thanks so much Mike. :) You can close
