### ISSUE TITLE
Keep Mini drawer Hidden

### ISSUE THREAD

**Issue by SamSalman** [mikepenz/MaterialDrawer#1351]
Hello Mike,

I must say "great work".

I would like to keep Mini drawer hidden on start of an activity but when user slide on right or click on hamburger icon then Mini drawer should appear similarly what we have in normal Material Drawer . 
I wonder if its possible through your library?

Thank you in advance.
Regards,
Salman

**Comment by mikepenz** [comment]
@SamSalman thank you. 

Do you just want the `MiniDrawer` and no normal full size drawer?

**Comment by SamSalman** [comment]
Yes just MiniDrawer and no full size drawer.

**Comment by mikepenz** [comment]
@SamSalman have you already tried the `CrossfadeDrawerLayout` if that's not a behavior you want, it will require a bit more work from your side to get the `MiniDrawer` as single behavior. 

You will have to create the `DrawerLayout` on your own, handle it on your own, and then just add the `MiniDrawer` view into it after creation

**Comment by SamSalman** [comment]
Thanks Mike. I think CrossfadeDrawerLayout could do the work. But I need label with icons in mini drawer as shown in image. 
![167894061](https://cloud.githubusercontent.com/assets/3371099/16229901/8b4995a4-37c7-11e6-986d-730e9f36cfbf.png)

Could It be possible?

**Comment by mikepenz** [comment]
@SamSalman It will get hard to get exactly the above view as you also have a `StickyButton` there. 

But see this answer for CustomMiniDrawerItems;
https://github.com/mikepenz/MaterialDrawer/issues/1258

In your case you might simply just use a normal `DrawerLayout` add it on your own and create your own layouts, don't think it is necessary to use the `MaterialDrawer` here

**Comment by SamSalman** [comment]
Hello again,

Thank you for the comment.

I have done customMiniDrawerItems as you suggested and it seems fine. I tried to set the width of mini drawer as suggested [#588](https://github.com/mikepenz/MaterialDrawer/issues/588). It works but when I slide mini drawer left or right then it goes back to default width as can be seen in below images.
![screenshot_2016-06-23-16-51-51](https://cloud.githubusercontent.com/assets/3371099/16307164/f0f68b3a-3968-11e6-82ef-d19d4142616a.png)
![screenshot_2016-06-23-17-11-49](https://cloud.githubusercontent.com/assets/3371099/16307163/f0efc2d2-3968-11e6-9f5b-4141679cd95d.png)

How can I fix this issue? Beside how can I change background image and bring blur effect on right panel of mini drawer as shown in earlier uploaded image.

Thank you in advance

**Comment by mikepenz** [comment]
@SamSalman there is nothing like a `Blur` effect in the `DrawerLayout` you will have to implement something like this on your own. Not sure if there are already libraries which apply such a blur on a view. 

You want to change the width of the `MiniDrawer` in general? 

So you might want to provide a small sample app where I can try out this behavior you have at the moment

**Comment by SamSalman** [comment]
Hello Mike,

Thank you again for the comment.

Is it possible to change right panel background Image? So that I case just use blur background image there instead of implementing blur effect over it.

Actually I also tried CrossfadeDrawerLayoutActvitiy of your sample app and I changed this line of code to increase the width of miniDrawer:
withDrawerWidthDp(72) to withDrawerWidthDp(100)

It works but it has the similar effect that when I slide it either left or right then it goes back to default width.

Thank you in advance.

**Comment by mikepenz** [comment]
@SamSalman 

not that I know. That comes from the original `DrawerLayout` 
you might be able to just have a different view in the background somewhere which you use for this but that's not related to the `MaterialDrawer`

Ok I will have a look.

**Comment by SamSalman** [comment]
Hello @mikepenz 

I am also trying to listen the click event when user click on profile icon in CrossfadeDrawerLayoutActvitiy in miniDrawer but for some reason I can't get it working. So far I have tried following Listeners:
.withOnAccountHeaderListener
.withOnAccountHeaderSelectionViewClickListener

So all I want when user click on profile icon in miniDrawer I need to open profile activity of user. 

Thank you once again.

**Comment by mikepenz** [comment]
@SamSalman you also have to define the `minWidth` of the `CrossfadeDrawerLayout` like this:
```java
crossfadeDrawerLayout.setMinWidthPx((int) UIUtils.convertDpToPixel(100, this));
```

**Comment by SamSalman** [comment]
Hello @mikepenz 

Thank you for your solutions.

Finally minWidth of the CrossfadeDrawerLayout works with the piece of code your shared.

However, it seems after a pull request still I can't figure it out to listen profile click event. I have tried following ways so far:

        final MiniDrawer miniResult = result.getMiniDrawer();

        miniResult.withOnMiniDrawerItemOnClickListener(new FastAdapter.OnClickListener<IDrawerItem>() {
        @Override
            public boolean onClick(View v, IAdapter<IDrawerItem> adapter, IDrawerItem item, int position) {

                System.out.println("salman ++"); => DrawerItem event fires here but not Profile
                return false;
            }
        });

        miniResult.withOnMiniDrawerItemClickListener(new MiniDrawer.OnMiniDrawerItemClickListener() {
         @Override
         public boolean onItemClick(View view, int position, IDrawerItem drawerItem, int type) {
             System.out.println("profile ++"); => This one never fires
             return false;
         }
     });

Would you please guide me what I am doing wrong.

**Comment by mikepenz** [comment]
@SamSalman 
```java
miniResult.withOnMiniDrawerItemClickListener(new MiniDrawer.OnMiniDrawerItemClickListener() {
     @Override
     public boolean onItemClick(View view, int position, IDrawerItem drawerItem, int type) {
         System.out.println("profile ++"); => This one never fires
         return false;
     }
 });
```
is correct. You just have to remove the previous listener:
Please see the Javadoc for the description why the first one does not fire when the second one is defined: https://github.com/mikepenz/MaterialDrawer/commit/7e069530ed7d3f62245b93e4b21d1d5edbdce6d2#diff-55bb5b525aaae9074580e302b40a9f07R177

**Comment by SamSalman** [comment]
@mikepenz thank you for quick response.

As you suggested, I have removed previous listener. Now, drawer item click event fires but still when I click profile image nothing happens.

**Comment by mikepenz** [comment]
what do you mean with nothing happens. you have to open the dialog or whatever you need there. You can even `return true` to prevent any default behavior

**Comment by SamSalman** [comment]
Sorry, it was my bad.. Its working finally.. Thank you once again.
