### ISSUE TITLE
Disable profile selection in AccountHeader

### ISSUE THREAD

**Issue by mrz** [mikepenz/MaterialDrawer#1352]
Hi Mike, good job on the great library!

I'd like to know if I can disable profile selection in the AccountHeader. I worked around it by disabling the Header altogether and adding a (disabled) ProfileDrawerItem as first item in my Drawer, but it's kinda kludgy and I'd rather have a full fledged AccountHeader. I support only one profile in my application and the profile chooser feels confusing.

**Comment by mikepenz** [comment]
@mrz https://github.com/mikepenz/MaterialDrawer/issues/615
