### ISSUE TITLE
How to expand account header when drawer is closed?

### ISSUE THREAD

**Issue by mortezasun** [mikepenz/MaterialDrawer#1353]
Hi mike 
How to expand account header when drawer is closed?
In fact, I want to know how to expand or close account header programmatically?
Thanks

**Comment by mikepenz** [comment]
Use this method:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L101
