### ISSUE TITLE
java.Lang.VerifyError on withActivity(this)

### ISSUE THREAD

**Issue by ParhamAhmadi** [mikepenz/MaterialDrawer#1354]
Thank For Your Great Lib

when I pass the activity to  material drawer in this way : 

new DrawerBuilder().withActivity(this).build();

force stop occurs.

in my logCat i see a error : 
java.Lang.VerifyError on line # new DrawerBuilder().withActivity(this).build();

how i do it ?

**Comment by mikepenz** [comment]
@ParhamAhmadi which version of Android do you use? Which build tools? Which Android Studio? Which Java API level?

**Comment by ParhamAhmadi** [comment]
java.lang.VerifyError: com/mikepenz/materialdrawer/DrawerBuilder

I Use AndroidStudio 2.1.2.0
Target API 24 , (LL 5.1.1)  on My Phone 
Java 1.8.0.66

![image](https://cloud.githubusercontent.com/assets/16632457/16261569/5c992caa-3881-11e6-8149-3777e0e24f53.png)
 Build Tools 24

**Comment by mikepenz** [comment]
@ParhamAhmadi which libs do you have in your gradle? have you done a clean build?

**Comment by ParhamAhmadi** [comment]
No Libs But it
Yes I have done a Clean Build but DOESN'T EFFECT :|
I Really Need It
Please Help Me

**Comment by ParhamAhmadi** [comment]
@mikepenz

**Comment by ParhamAhmadi** [comment]
What I Should Do EXACTLY?

**Comment by mikepenz** [comment]
@ParhamAhmadi It somehow must be related to your setup. You can download the repository open the sample app in Android Studio and it will run.

**Comment by ParhamAhmadi** [comment]
@mikepenz

**Comment by mikepenz** [comment]
Can you please just create a small sample project showcasing this issue, I am sure this is not related and comes from some missconfiguration

**Comment by mikepenz** [comment]
Sorry without a sample application showcasing this issue I can not solve it
