### ISSUE TITLE
Drawer is not added

### ISSUE THREAD

**Issue by zolbayars** [mikepenz/MaterialDrawer#1355]
Even I've added the following line, nothing shows up in the activity. 
`new DrawerBuilder().withActivity(this).build();`

_I am using Android Studio 2.1.2 with Gradle plugin 2.1.2_

**Comment by mikepenz** [comment]
@zolbayars if you swipe from the left edge to right the empty drawer will open. You still have to fill it with items and you might want to pass the `Toolbar` but it will work already

**Comment by zolbayars** [comment]
Wow, it was there indeed. I was expecting some kind of 'sandwich menu' on the top left corner. 
Thanks BTW.

**Comment by mikepenz** [comment]
@zolbayars that will show up as soon as you provide the `Toolbar`
