### ISSUE TITLE
How to save user's preference

### ISSUE THREAD

**Issue by s-p-a-r-k** [mikepenz/MaterialDrawer#1356]
When user turns off one of the switches on the material drawer, I would like that switch to remain turned off when the user re-opens the app. I thought adding .withSavedInstance(savedInstanceState) on the drawer and overrinding onSaveInstanceState method would do it, but it does not work. Is there a way to store user's action?

**Comment by s-p-a-r-k** [comment]
`    @Override
    protected void onSaveInstanceState(Bundle savedInstanceState) {
        savedInstanceState = menuDrawer.saveInstanceState(savedInstanceState);
        super.onSaveInstanceState(savedInstanceState);
    }`

This is my code for onSavedInstanceState method.

**Comment by mikepenz** [comment]
@s-p-a-r-k I only can remember the selected position and the general state of the `Drawer` states of the items itself have to be stored on your side with a normal `SharedPreference` or else. 

Just store it when the listener is called, and load it during initialization of the drawer
