### ISSUE TITLE
Error when sync Gradle in MaterialDrawer Sample

### ISSUE THREAD

**Issue by mehdiAbbaspour** [mikepenz/MaterialDrawer#1357]
<img width="575" alt="screen shot 2016-06-23 at 4 56 28 am" src="https://cloud.githubusercontent.com/assets/4215921/16288228/f58f8440-38fe-11e6-9414-3952f2e72045.png">

**Comment by mikepenz** [comment]
@mehdiAbbaspour please update your google support repository. Seems like you don't have 24.0.0 available yet

**Comment by mehdiAbbaspour** [comment]
thank you
it's right
