### ISSUE TITLE
onDrawerOpened not called after executing drawer.openDrawer()

### ISSUE THREAD

**Issue by localhostEU** [mikepenz/MaterialDrawer#1359]
subj.

**Comment by mikepenz** [comment]
@localhostEU perhaps an issue of the `DrawerListener` from the support libs. as `openDrawer` just uses the original `DrawerLayout` methods, and the `DrawerListener` is also the original implementation

**Comment by mikepenz** [comment]
@localhostEU thanks for the addition. Perhaps you can just call the listener yourself or the stuff which should happen in this case. 

So hopefully this will by fixed by Google themself
