### ISSUE TITLE
How to make that the profile list was to close by default?

### ISSUE THREAD

**Issue by astakhovr** [mikepenz/MaterialDrawer#1360]
Hello Mike,
I use MiniDrawer and account header with only one profile. 
I set parameters:
     .withSelectionListEnabledForSingleProfile(false)
     .withCurrentProfileHiddenInList(true)

After click on ico account header, open drawer with empty list. 
**How to make that the profile list was to close by default?**

**Comment by mikepenz** [comment]
@astakhovr you want to prevent that the click on the `Profile` in the `MiniDrawer` toggles to the profile list of the normal drawer? 

That's currently not really possible as it will automatically toggle to the `profileList`

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L477

**Comment by astakhovr** [comment]
No, click has to remain. 

1. Click
![1](https://cloud.githubusercontent.com/assets/20141194/16382410/6393e674-3c89-11e6-9e8f-fb1c56d4da7c.jpg)

2. Open
![2](https://cloud.githubusercontent.com/assets/20141194/16382419/67f40a28-3c89-11e6-879a-dd2d25efde3d.jpg)

Thanks.

**Comment by mikepenz** [comment]
@astakhovr you probably can trigger a `toggleSelectionlist()` when the user clicks the profile picture in the `MiniDrawer`?
