### ISSUE TITLE
DrawerItem selectable but no selected Color

### ISSUE THREAD

**Issue by RezaOruji** [mikepenz/MaterialDrawer#1361]
is it possible to prevent some drawer items to get highlighted when they are selected ?
for example , in one of the drawer items i want to show a dialog , so i don't want to change the selected drawer item.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L118
`withSelectable(false)`
