### ISSUE TITLE
Reload Header after User Login

### ISSUE THREAD

**Issue by mitsus** [mikepenz/MaterialDrawer#1362]
Hi,
firsty compliments for your prject..it's great.
I've a question.
When my app start firt time, i haven't a profile load, so i don't show anything into header of MaterialDrawer.
I've anther activity where i do Login or Signup...after thet i close this activity and go into onResume of Main Activity that sow your Material Drawer.
I've try to reload header adding logger user infos...but it doesn't work. 
```java
    @Override
        public void onResume(){
            super.onResume();
             Log.i("MainActivity","Start onResume()");
             if (dbUser.isThereAnUser()){
                 Log.i("MainActivity","OnResume...There is a profile!");


            HashMap<String, String> user = dbUser.getUserDetails();
            Log.i("MainActivity","onResume() User: " + user.get("uname"));
            profile_user = new ProfileDrawerItem().withName(user.get("uname")).withEmail(user.get("email"));
            if (user.get("avatar") == null){
                profile_user.withIcon(ContextCompat.getDrawable(this, R.drawable.profile5));
            }else{
                profile_user.withIcon(user.get("avatar"));
            }
            headerResult.updateProfile(profile_user);
        }
    }
```
Please can you help me to solve this problem?

Thanks a lot

**Comment by mikepenz** [comment]
@mitsus `updateProfile` will just update an existing profile using it's `identifier` as you create a new profile, you have to add it first.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L268
