### ISSUE TITLE
How to change the avatar by a ID? / How to change badge in a function

### ISSUE THREAD

**Issue by PedroBarbosaPT** [mikepenz/MaterialDrawer#1363]
Hi,
First of all, great job!

I want to update the avatar later on, by using this code:
```java
        Picasso.with(getBaseContext())
                .load(socialPerson.avatarURL)
                .into();
```
But i don't know what goes in ."into()"

___

And in a function I want to change the badge, and I don't know how:
Like this:

    public void changeBadge(int number){
        Drawer_withNumber.withBadge("12").withBadge(number).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes((R.color.md_blue_700)));
    }
But it says:
Cannot resolve symbol, can you show me a exemple of this?
Thanks

Edit:
I figured the last question:
        result.updateBadge(IDENTIFIER, new StringHolder(number + ""));

**Comment by mikepenz** [comment]
@PedroBarbosaPT just provide the `url` to the `ProfileDrawerItem` and follow these steps:
https://github.com/mikepenz/MaterialDrawer#load-images-via-url

If you change a element in the drawer you have to notify the drawer about the update:
https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

And yes `updateBadge` will change the badge number and notify the drawer about the update at once
