### ISSUE TITLE
Account Profile Name and Picture RTL support

### ISSUE THREAD

**Issue by shaikansaar** [mikepenz/MaterialDrawer#1364]
@mikepenz 

Hi,

Thanks for the great library.

I am running my application in RTL and the drawer is appearing on right side perfectly. However,  the account profile icon and name are not appearing on the right side.

Any idea how to achieve this? Attached snapshot for reference.

Regards,
Shaik

![image](https://cloud.githubusercontent.com/assets/4800397/16478747/be25a5d0-3eac-11e6-8d0e-dcca336d9028.png)

**Comment by mikepenz** [comment]
@shaikansaar that's the same as the google apps do. 

If you really need to change this you would have to provide a separate header layout for RTL:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml

(copy it and modify it to fit for rtl and put it into an rtl layout folder)

**Comment by shaikansaar** [comment]
@mikepenz

Thanks for replying so quickly. I will check and let you know if it works.

Regards
Shaik Ahmed
