### ISSUE TITLE
Building the Drawer with Dynamic Toolbar

### ISSUE THREAD

**Issue by acosti** [mikepenz/MaterialDrawer#1366]
Hello,

I'd like to have two options: one - building an ordinary drawer. The second - building a drawer with a toolbar.

How would you go about building a basic drawer, and THEN adding the toolbar on top of it after usage?

I'm trying to avoid c/p'ing the builder code, so essentially there would have to be two separate builder instructions.

Hope that's clear enough.
Thanks.

**Comment by mikepenz** [comment]
@acosti I am not quite sure what you are going to try. 

In general you can split up the building. 

first you have the basic `DrawerBuilder builder = new DrawerBuilder() ....` code. 
and then you can `.build()` it once directly and in the other case you also add the `Toolbar` and `.build()` afterwards

**Comment by acosti** [comment]
@mikepenz Great. Much appreciated. The answer as well as the library :+1: 

Just because I didn't leave too much information, allow me to explain:
I'd like my activity's navigation to be wholly dynamic. 
That is, a set of prior instructions determine each activity's separate navigation type.
So you could have Activity A with a pretty Drawer, while Activity B would have Tabs, and Activity C would have a pretty Drawer AND a toolbar.
That's it... just so you know. And if by chance you can think of any tips for such usage I'd love to know. 

Again, thanks for this great lib!
