### ISSUE TITLE
Adjust margins in RecyclerView for translucent navigation bar

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/MaterialDrawer#1368]
When the navigation bar is transparent and the layout fullscreen, I want to be able to reach the last item in the drawer... 

Is there a reason to not adjust this margin automatically? I currently correct it manually like following:

	boolean useTranslucentNavBar = ...;
	if (useTranslucentNavBar)
	{
		int bottomOffset = Tools.getNavigationBarHeight(getActivity());
		RelativeLayout.LayoutParams lp = (RelativeLayout.LayoutParams)mDrawerLeft.getRecyclerView().getLayoutParams();
		lp.bottomMargin = bottomOffset;
	}

**Edit**

I just saw, that you are adding some space in the adapter itself... Still, the above solution would result in the edge effect not happening behind the translucent navigation bar... Which looks somehow weird..

**Comment by mikepenz** [comment]
@MFlisar I add the spacing as `padding` on the `RecyclerView` which is the correct way of doing this. 

Perhaps you come across the following issue:
https://github.com/mikepenz/MaterialDrawer/commit/fd38c040096b619fca212c9342cdb6e37ab392e4

**Comment by mikepenz** [comment]
Just tested again with many different emulator versions. in the `FullScreenActivity` sample and it works for all
