### ISSUE TITLE
Change icon size (or auto scale) on MiniDrawer

### ISSUE THREAD

**Issue by emanuelbalea** [mikepenz/MaterialDrawer#1372]
Hi @mikepenz, awesome projects love your work.
I've started to integrate this into my own app which unfortunately has to run on a old tablet device where the default sizes/dpi settings OS wide are just horrible and hard to read, especially when the devices are mounted in vehicles.

Is there any way to easily change the icon size in the MiniDrawer or make it scale as if you were to increase the width of the mini drawer? Same question again but open mode of the mini drawer.

If not would it be enough to implement my own mini drawer item layout or would I have to extend mini drawer as well? Any hints and tips would be appreciated as to where to look in code to make it behave as I wish.

Oh and btw I've also created Xamarin/MonoDroid bindings for a lot of your stuff as my apps are build in Xamarin. Let me know if you'd like to have them or if I can publish them on Nuget/GitHub. I know another person had one or two of them but they were quite old and missing lots of the new shiny stuff.

Thanks in advance :)

**Comment by mikepenz** [comment]
@emanuelbalea in general the `MiniDrawer` is not the easiest component to change. It was built to perfectly work with the 72dp. If you want to go with a different width, you will not only have to create custom `MiniDrawerItems` but also extend the `MiniDrawer` to allow those new custom `MiniDrawerItems` 
The most detailed instrucitons are found here: 
https://github.com/mikepenz/MaterialDrawer/issues/1090#issuecomment-195913322

Regarding your second question. 
Yes you can publish them on Nuget and Github. Just keep credits. 

Best,
Mike

**Comment by mikepenz** [comment]
@emanuelbalea any more details you need?

**Comment by emanuelbalea** [comment]
No, thanks for the help. I'll contact you if I get stuck :)
