### ISSUE TITLE
Hamburger Icon

### ISSUE THREAD

**Issue by emreaktrk** [mikepenz/MaterialDrawer#1373]
I am trying to make a basic implementaion of drawer.

I have troubles about showing hamburger icon.
Does library has function about it?

**Comment by mikepenz** [comment]
@emreaktrk the hamburger icon is no specific function of the `Drawer` and is independent of it. But if you provide the `Toolbar` to the drawer it can "manage" it for you and add the `ActionBarDrawerToggle` automatically to the `Toolbar`

**Comment by emreaktrk** [comment]
Thanks for the help. I added custom toolbar to let the library manage it :)
