### ISSUE TITLE
Custom drawer class

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/MaterialDrawer#1374]
For using Chris Banes `PhotoView` (https://github.com/chrisbanes/PhotoView) he suggests to override the `onInterceptTouchEvent(MotionEvent ev)` of the DrawerLayout, if the `PhotoView` is used inside it.

Could you add a possibility to set a custom class `CustomDrawerLayout extends DrawerLayout` to the builder?

**Comment by mikepenz** [comment]
@MFlisar there is an easy way to do this. As showcased in the `CrossfadeDrawerLayoutActivity` sample:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CrossfadeDrawerLayoutActvitiy.java#L67

Just create a layout like this one with your drawer implementation:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/crossfade_drawer.xml

And provide it to the builder. 

You can also provide the `DrawerLayout` via this method:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L306

**Comment by MFlisar** [comment]
Thanks
