### ISSUE TITLE
Fixed min drawer

### ISSUE THREAD

**Issue by MrThiago** [mikepenz/MaterialDrawer#1376]
HI, is there a way to make the mini drawer fixed to only the icons and not allowing on swipe to extent ? 
thanks

**Comment by mikepenz** [comment]
@MrThiago you can use the `MiniDrawer` without a `DrawerLayout` too. Remember that it has to be filled with a `DrawerBuilder` 

So just use the `DrawerBuilder` as you would normally do, and just skip the `.build()` part. Provide the builder to the `MiniDrawer` and build it. you will get the `View` which you can add somewhere in your view hirachy
