### ISSUE TITLE
How to set background color to minidrawer

### ISSUE THREAD

**Issue by kkokate** [mikepenz/MaterialDrawer#1377]
How to set background color to minidrawer.i am able to do while drawer is in expanded mode but not able to do while in collapsed mode

**Comment by mikepenz** [comment]
@kkokate the `MiniDrawer` itself has no background color. It just uses the background of the `DrawerLayout` as the normal drawer does. 

How do you set the color at the moment? and what do you mean it only works in expened mode?

**Comment by kkokate** [comment]
@mikepenz thank you for quick reply :)

Below is the image attached with the query inlined..
![screenshot_20160704-174047](https://cloud.githubusercontent.com/assets/18045006/16560248/d2f6e986-420f-11e6-976b-a94ca3203e6d.png)

**Comment by mikepenz** [comment]
@kkokate to set the background when using the `Crossfader` I recommend to set it on the first and the second view separately:

```java
crossFader.getFirst().setBackgroundColor(Color.BLUE);
crossFader.getSecond().setBackgroundColor(Color.BLUE);
```

**Comment by kkokate** [comment]
@mikepenz thanks mike.its working fine
