### ISSUE TITLE
  How to recover ExpandableDrawerItem?

### ISSUE THREAD

**Issue by HouLeiGD** [mikepenz/MaterialDrawer#1378]
How to recover ExpandableDrawerItem?

**Comment by mikepenz** [comment]
@HouLeiGD what do you mean?

**Comment by HouLeiGD** [comment]
Pack up the menu

**Comment by mikepenz** [comment]
you want to collapse the element again programmatically.

You get the `Adapter` from the `Drawer` and call `collapse(int position)` 
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1167

also mentioned here:
https://github.com/mikepenz/MaterialDrawer/issues/1248#issuecomment-217662651
