### ISSUE TITLE
ContainerDrawerItem item click doesn't fire "withOnDrawerItemClickListener"

### ISSUE THREAD

**Issue by MhzDev** [mikepenz/MaterialDrawer#1379]
I have created multiple ContainerDrawerItem and added to the drawer, but they don't fire che withOnDrawerItemClickListener callback. 
The only thing i can do is put a manual "onClickListener" on their view 
```java
ContainerDrawerItem menu1 = new ContainerDrawerItem().withDivider(false).withView(XXXX);
menu1.getView().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //Something
            }
        });
```
But doing that, the drawer doesen't handle the selected state of the element.
The code is this:
```java
new DrawerBuilder().withActivity(this).build();

ContainerDrawerItem menu1MyOlo = new ContainerDrawerItem().withDivider(false).withView(R.layout.view1);
ContainerDrawerItem menu2Msg = new ContainerDrawerItem().withDivider(false).withView(R.layout.view1);

        drawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .addDrawerItems(
                        header,
                        menu1MyOlo,
                        menu2Msg
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        Log.d(TAG, "onItemClick: DRAWER" + drawerItem.toString());
                        //Never Called
                        return true;
                    }
                })
                .build();
```

**Comment by mikepenz** [comment]
@MhzDev that's the correct behavior as you catch the `click` event via the `ClickListener` on the `View` 

Remove the `ClickListener` on `menu1.getView().setOnClickListener`. Also make sure your item is clickable, and does not prevent clicks. Also check if it is enabled.

**Comment by MhzDev** [comment]
Thank you for the fast reply.
The `menu1.getView().setOnClickListener` was only an example of a workaround.
The only code i use is
```java
new DrawerBuilder().withActivity(this).build();

ContainerDrawerItem menu1MyOlo = new ContainerDrawerItem().withDivider(false).withView(R.layout.view1);
ContainerDrawerItem menu2Msg = new ContainerDrawerItem().withDivider(false).withView(R.layout.view1);

        drawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .addDrawerItems(
                        menu1MyOlo,
                        menu2Msg
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        Log.d(TAG, "onItemClick: DRAWER" + drawerItem.toString());
                        //Never Called
                        return true;
                    }
                })
                .build();
```
I also tried to make the custom view clickable and selectable, but it doesen't work jet.

**Comment by mikepenz** [comment]
I would also need the view you provide to the `ContainerDrawerItem` as I think that this causes the problem. 

Just for curiosity, why do you use the ContainerDrawerItem, instead of implementing your own Custom DrawerItem

**Comment by mikepenz** [comment]
Also one more thing about your implementation. You can't just get the veiw and set the `OnClickListener` on it, as this will not work properly when you scroll and the view is recycled. 

Please head over here on how to implement a proper `CustomDrawerItem`:
http://stackoverflow.com/a/32543209/325479
http://stackoverflow.com/a/32542999/325479

You might also find some answers here:
https://github.com/mikepenz/MaterialDrawer/issues?utf8=%E2%9C%93&q=CustomDrawerItem

Or you check out custom drawer item implementations here:
https://github.com/mikepenz/MaterialDrawer/tree/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems
