### ISSUE TITLE
Back button with MiniDrawer

### ISSUE THREAD

**Issue by iHandy** [mikepenz/MaterialDrawer#1382]
Incorrect work of detecting drawer state when use drawer with mini drawer.
This bug also reproduced in your sample app.
Steps (for sample app):
1. Open navigation drawer and choose MiniDrawer
2. Expand drawer
3. Press "Back" (hard button, for ex.)
Actual result: MiniDrawerActivity closed.
Expected result: by first "back" only drawer should be closed.

**Comment by mikepenz** [comment]
@iHandy the sample app was not intended to do this, but yeah nice idea. Changed it to work properly

**Comment by iHandy** [comment]
Thank you. I used your fix for my implementation.
