### ISSUE TITLE
I want to show drawer animation partly

### ISSUE THREAD

**Issue by shimika** [mikepenz/MaterialDrawer#1383]
Drawer is closed when several cases.

1. Touch empty place on right.
2. Select item.

I want to animate in first case, but I don't want show animation when second case.
Because, when select item, my application switch fragment and cause very laggy.

Can I do this?

**Comment by mikepenz** [comment]
@shimika the animation is automatically played by the `DrawerLayout` when it is closed. 

Getting rid of the animation is not easy: http://levibostian.com/android-navigation-drawer-animation-duration/

What you can do is that you modify the behavior when the drawer closes. You have 2 options. You can delay the click event of the listener. or you can delay the close of the drawer:

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1118
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1101

setting one of both to about 150ms should make the animations good

**Comment by shimika** [comment]
Thanks!
