### ISSUE TITLE
Question: use MD as a PreferenceActivity replacement

### ISSUE THREAD

**Issue by frmz** [mikepenz/MaterialDrawer#1384]
I am already using MD as my main app drawer and works great, i was thinking to also replace the Settings activity based on Android preferences since i need to use my own storage backend, i just need a full screen MD and creating different drawer items with larger icons and a description. Do you see any issue with this approach?

**Comment by mikepenz** [comment]
@frmz no issue with this approach as I go the same approach with `wallsplash` (a wallpaper app I have created) There I have created a settings activity based on the `MaterialDrawer` for muzei.

**Comment by mikepenz** [comment]
@frmz if it is just about filling a list with items you may also look at the underlaying `FastAdapter` which is the base for the `MaterialDrawer` (https://github.com/mikepenz/FastAdapter)

Having the `MaterialDrawer` fullscreen is in the sample application. Creating `CustomDrawerItem`s can also be easily done and is also showcased in the sample

**Comment by frmz** [comment]
Good tip, probably i can just use the FastAdapter since i need to create my own "card" layout, thanks!

**Comment by mikepenz** [comment]
@frmz yes. makes sense
