### ISSUE TITLE
Toolbar overlaps Statusbar

### ISSUE THREAD

**Issue by harso121** [mikepenz/MaterialDrawer#1387]
Once I build the drawer, the toolbar is overlapping my statusbar.
When I comment out the drawer code, it works just fine(but without the drawer of course so not an option).

Drawer Code:

```Java
 AccountHeader headerResult = new AccountHeaderBuilder()
                            .withActivity(MainActivity.this)
                            .withCompactStyle(true)
                            .withHeaderBackground(R.drawable.headerprofile2)
                            .addProfiles(
                                    new ProfileDrawerItem().withName(fullname).withEmail(classP).withIcon(getResources().getDrawable(R.drawable.profile))
                            )
                            .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                                @Override
                                public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                                    return false;
                                }
                            })
                            .build();

                            PrimaryDrawerItem item1 = new PrimaryDrawerItem().withIdentifier(1).withName("Home");
                    Drawer drawer = new DrawerBuilder()
                            .withActivity(MainActivity.this)
                            .withAccountHeader(headerResult)
                            .withToolbar(toolbar)
                            .addDrawerItems(
                                    item1,
                                    new DividerDrawerItem(),
                                    new SecondaryDrawerItem().withName(R.string.action_settings)
                            )
                            .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                                @Override
                                public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                                    return true;
                                }
                            }).build();
```

Toolbar-XML:
```XML
 <android.support.v7.widget.Toolbar
        app:popupTheme="@style/ToolbarOptions"
        android:id="@+id/toolbar"
        android:minHeight="?attr/actionBarSize"
        android:background="#1ab394"
        android:textColor="@color/white"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
    </android.support.v7.widget.Toolbar>

```

@style/ToolbarOptions:
```XML
    <style name="ToolbarOptions" parent="ThemeOverlay.AppCompat.Light">
        <item name="android:colorBackground">@color/md_white_1000</item>
        <item name="android:textColor">@color/md_black_1000</item>
    </style>

```

Used AppThemes:
```XML
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.NoActionBar">
        <item name="android:windowBackground">@color/white</item>
        <item name="android:textColor">@color/white</item>
        <item name="android:windowActionBar">false</item>
        <item name="android:windowNoTitle">true</item>
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
    </style>

    <style name="ClassnetBase" parent="Theme.AppCompat.NoActionBar">
        <item name="android:windowBackground">@color/white</item>
        <item name="android:textColor">@color/white</item>
        <item name="android:windowActionBar">false</item>
        <item name="android:windowNoTitle">true</item>
    </style>
```

Screenshot:
![screenshot_20160712-152013](https://cloud.githubusercontent.com/assets/14226197/16768541/0741d1ac-4845-11e6-8995-4906bab49f9b.png)

**Comment by harso121** [comment]
By the way, just saw you live in Linz.

Ich lebe in Pasching (gleich neben Linz), also wenn du willst, kannst du mir auch in Deutsch antworten :)

**Comment by mikepenz** [comment]
@harso121 oh cool :D but I generally keep conversations in english so other people can also use the answers :D

Regarding your issue. I really recommend that you don't handle those things in your theme
```xml
 <item name="android:windowActionBar">false</item>
<item name="android:windowNoTitle">true</item>
<item name="windowActionBar">false</item>
<item name="windowNoTitle">true</item>
```

And that you follow the instructions noted here: https://github.com/mikepenz/MaterialDrawer#androidmanifestxml to use one of the `MaterialDrawer` themes as base (those already set the above params correctly for all android versions and also depend on the appcompat theme)

**Comment by harso121** [comment]
Hmm.. out of all the options, translucent worked, only problem is, now the textcolor of the toolbar is black and the statusbar is completely white.

But hey, making progress, it doesn't seem to overlap anymore :D

![screenshot_20160712-165822 1](https://cloud.githubusercontent.com/assets/14226197/16771739/ea14771c-4851-11e6-964d-9ea6dbfec105.png)

**Comment by mikepenz** [comment]
@harso121 because you set your `windowBackground` to white 
```xml
<item name="android:windowBackground">@color/white</item>
```

If you have "darkToolbar" the proper way is to set the theme as shown here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/activity_sample_dark_toolbar.xml#L13

I assume that you still have your own theme so you should follow this here:
https://github.com/mikepenz/MaterialDrawer#custom-style---stylesxml especially the first three lines are important for apps

**Comment by harso121** [comment]
Is there any way you could show me what to do exactly, I've been tinkering for 10 minutes now, but the most I got was, that the "Classnet" changed to White instead of black.

Sorry, I'm still pretty new at Android, my login system works perfectly(don't ask me how I managed that lol), but this is making me crazy.

I'm used to CSS and HTML - styling like they're told, u create the attribute and done. This? I don't know why I can't figure it out, it's like shooting blanks, I change a setting that's supposed to change the text color or the background, but nothing changes.

**Comment by mikepenz** [comment]
@harso121 I sent you the exact line what you need to add:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/activity_sample_dark_toolbar.xml#L13

**Comment by harso121** [comment]
Tried that, but it's just as in the first picture, only that now, the 3 lines are in black instead of white.
Even with  one of the MaterialDrawer themes as base. -> @style/MaterialDrawerTheme.Light

@style/MaterialDrawerTheme.Light.TranslucentStatus produces the second picture (with https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/activity_sample_dark_toolbar.xml#L13 now just that the 3 lines are black and the text is white)

**Comment by mikepenz** [comment]
also if you define the colors for primary etc in your theme? as linked above? So that at least the statusbar color is right?

You always have to differ which themes to use. You can check in the sample app which theme fits yours. 

You can also check out the different things I have done in the sample apps of my libs. `Android-Iconics` has white text as you want it to be.
https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/AndroidManifest.xml#L10

and define this to get the white hamburger icon:
https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/res/values/styles.xml#L7

and set the colors to get the correct styling:
https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/res/values/colors.xml#L5

and as already mentioned for the text. The toolbar definition:
https://github.com/mikepenz/Android-Iconics/blob/develop/app/src/main/res/layout/activity_main.xml#L29

**Comment by harso121** [comment]
Even if I change everything to EXACTLY as it is in the Android-Ionics project, the toolbar still overlaps with the statusbar, although:

The Text(+ the three lines) are in white, but now the options menu is in the dark style.

**Comment by mikepenz** [comment]
@harso121 sounds like you have some weird setup. Could you please send me the project (just remove everything not issue related from it) via e-mail and I will have a look.

**Comment by mikepenz** [comment]
@harso121 I just launched your application and instantly a few tiny things. 

the import for the `Toolbar` should be
```java
android.support.v7.widget.Toolbar
```

also the `MaterialDrawer` always comes with the latest version of the support libraries, so you also have to use them. 

If you change those to v24.0.0 it should work
```java
compile 'com.android.support:appcompat-v7:24.0.0'
compile 'com.android.support:design:24.0.0'
```

after those changes I have run the app you sent me and it's fine

**Comment by harso121** [comment]
Thank you for all the help, I really appreciate it!

I'm currently not on my PC, but once I am, I'll report back :)
