### ISSUE TITLE
Set Menu as drawer item

### ISSUE THREAD

**Issue by Jspascal** [mikepenz/MaterialDrawer#1388]
Please how can i set a menu as a Drawer Item, so that my menu items fill the drawer.

**Comment by mikepenz** [comment]
@Jspascal this is shown here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MenuDrawerActivity.java

(this does not allow as much flexibility as doing it by code will give you. it is also slower as it has to parse the menu.xml (this is also the case for all other things which happen in android) doing things programatically is in general faster)
