### ISSUE TITLE
AccountHeader imageview not update after Picasso download from URI

### ISSUE THREAD

**Issue by JaldeepAsodariya** [mikepenz/MaterialDrawer#1389]
Once Picasso get image from URI that only update imageview of Accounts(Profiles) list which is open when we click  on Profilename (for changing account) and then if we change account profile on that time it's update AccountHeader imageview.
I have attached 3 screenshot, please review this and let me know what i need to add, change or update code for autoupdate AccountHeader profile image after Picasso get image from URI.
(Thanks a lot @mikepenz , you have develop awesome library. Great Job.)

![1_firstlaunch](https://cloud.githubusercontent.com/assets/16114199/16801728/1634719e-491a-11e6-8803-490694dcc07b.png)
![2_afterpicassoloadimage](https://cloud.githubusercontent.com/assets/16114199/16801752/3451c726-491a-11e6-8f4f-ed4f5bbd4b72.png)
![3_afterchangeaccount](https://cloud.githubusercontent.com/assets/16114199/16801756/39136832-491a-11e6-9c20-7878ff91e49d.png)

**Comment by mikepenz** [comment]
@JaldeepAsodariya have you followed the implementation as shown in the sample app:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java#L27

Do you set the url to the profile at the beginning or at a later point? If at a later point do you notify the `AccountHeader` about the updated profile?

**Comment by mikepenz** [comment]
@JaldeepAsodariya in my applications I use glide which works without similar problems.

**Comment by JaldeepAsodariya** [comment]
Yes, i have set url to the profile at the beginning.

`IProfile profile1 = new ProfileDrawerItem().withName("JD Patel")
.withEmail(getString(R.string.surgeon_sml)).withIcon(uri).withIdentifier(101);`

and i have also try 2nd method (set url later and then notify AccountHeader for update profile) but same issue is there.

Ok. No problem.
Thanks for suggestion, i will try glide in my application.

**You have build such a good and very useful library**
Thanks again.

**Comment by mikepenz** [comment]
@JaldeepAsodariya thank you. 

So you have the same loading logic as mentioned above? Seems odd, in the past I also used picasso without issues.

Thanks ;)
