### ISSUE TITLE
I can't see the badge updates (v 2.5.5)

### ISSUE THREAD

**Issue by appmath** [mikepenz/MaterialDrawer#139]
Hello Mike,
I have also noticed the same issue inside your MaterialDrawer codebase which I modified to reproduce the issue. I know that you are insanely busy and I decided to take a look at the root cause.

Inside MultiDrawerActivity, AdapterView passes a 1-indexed position to 

```java
withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
@Override
public void onItemClick(AdapterView<?> parent, View view, int position, long id, IDrawerItem        drawerItem) {.....
```

But Drawer's updateBadge method assumes that position is 0-indexed.

I (temporarily) solved my issue by subtracting 1 from position: result.updateBadge(String.valueOf(badge - 1), position -1); 

To fix it globally, some methods need to be updated.
```java
        /**
         * Update the badge of a drawer item if its an instance of badgeable
         *
         * @param badge
         * @param position
         */
        public void updateBadge(String badge, int position) {
            int index = position - 1;
            if (mDrawer.checkDrawerItem(index, false)) {
                IDrawerItem drawerItem = mDrawer.mDrawerItems.get(index);

                if (drawerItem instanceof Badgeable) {
                    ((Badgeable) drawerItem).setBadge(badge);
                }

                mDrawer.mDrawerItems.set(index, drawerItem);
                mDrawer.mAdapter.notifyDataSetChanged();
            }
        }
```

Thanks and have a great weekend.

**Comment by mikepenz** [comment]
@appmath i see the the confusion here. but it's correct :D

the thing is the position returned by the onItemClick method and other methods is the position in the list. the list's position includes the header. this means with header the index is higher. a better solution for the whole thing is to add methods like updateBadge(String badge, int identifier) :D
