### ISSUE TITLE
Drawer selected item on back pressed #question

### ISSUE THREAD

**Issue by JimVercoelen** [mikepenz/MaterialDrawer#1390]
Hi,

Using this drawer repo (which is awesome btw) on my own app
and having troubles controlling the selected item on back pressed.

Using this 'DashboardActivity' which is parent over a few fragments and using the same drawer over the app which is created in the DashboardActivity.

For each drawer item clicked a different fragment will appear, and on clicking makes the clicked item as selected one.

Now facing a trouble if the user presses the back button which will show the previous fragment but won't 'reset' the selected drawer item belonging to that fragment.

Is there anyway the selected drawer item can be managed? 

Couldn't find it in any of your examples thats why I am asking this way.

This is a question (as you already noticed) and no issue but don't know how to label as 'question'.

Thanks

**Comment by mikepenz** [comment]
@JimVercoelen you can easily set the selection via the `setSelection` method on the `Drawer` object
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L498 (in your case you might want to disable the fireing of the onClick event again as the fragment is already switched at this state) note that you have to provide the identifier in this method. 

This one would be for setting the selection with the position:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L553

**Comment by JimVercoelen** [comment]
@mikepenz Big thanks for helping me out here!
