### ISSUE TITLE
Build error in 5.3.6

### ISSUE THREAD

**Issue by RJFares** [mikepenz/MaterialDrawer#1393]
Just updated to 5.3.6 and received build error :
Error:(1786) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme'.
Error:(1810) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar'.
[...]

My compile sdk is 24 and supporting down to api 16 (if it's relevant)
I reverted back to 5.3.5 until we check the problem.

**Comment by mikepenz** [comment]
@RJFares as I just released v5.3.6 it might not yet be synced to the `mavenCentral` servers. this takes a few minutes sometimes.
