### ISSUE TITLE
Load profile Image from facebook don't fit correctly

### ISSUE THREAD

**Issue by adriamt** [mikepenz/MaterialDrawer#1394]
First of all I'm sure that this is not an issue but I not able to figure how to configure to work properly.

I'm coding and app where you log in using facebook or google account and I use the profile photo to fill the account profile image. When I log with google all works well but when I log throught facebook the photo don't fit correctly the circle of the profile image.

I've used Picasso as Image Loader Library.

This Image is using google profile photo.
![screenshot_20160715-173202 1](https://cloud.githubusercontent.com/assets/11394100/16879866/d1377b1e-4ab2-11e6-873b-adde2c069521.png)

And this Image is using facebook profile photo.
![screenshot_20160715-173153 1](https://cloud.githubusercontent.com/assets/11394100/16879880/dc15ddf0-4ab2-11e6-8e91-bbeaa5770fa4.png)

Any clue how to fix that ?

**Comment by mikepenz** [comment]
@adriamt  that's the behavior of the `BezelImageView. You have two options either you overwrite the layout and set a different `scaleType` to the view. Or you add a `transformator` (or how this feature is called for the specific image loading lib you use) which creates a square image out of an rectangle one. 

You can also read some discussion here:
https://github.com/mikepenz/MaterialDrawer/issues/1217

**Comment by adriamt** [comment]
Thanks @mikepenz  I finally solved the issue modifing the scaletype of the layouts as you mention.
