### ISSUE TITLE
Styling SwitchDrawerItem

### ISSUE THREAD

**Issue by adriamt** [mikepenz/MaterialDrawer#1395]
I'm using a SwitchDrawerItem and it didn't style like others items (PrimaryDrawer o Secondary)

My question is how I should Style the SwitchDrawerItem to look like a PrimaryDrawerItem?

This Image it's how actualy looks it.
![screen shot 07-15-16 at 06 16 pm](https://cloud.githubusercontent.com/assets/11394100/16881046/78b19db6-4ab8-11e6-841b-bbb8086a05aa.PNG)

**Comment by mikepenz** [comment]
@adriamt I don't really understand what you want to change, as the `SwitchDrawerItem` is exactl the same as a normal `PrimaryDrawerItem` just with the additional `Switch` on the right. You can also set an icon to it, as for the others. 

If you still want to change it. Just create a `CustomDrawerItem` based on the `SwitchDrawerItem` and change it's style etc. Just look in the sample app, it comes with a few `CustomDrawerItems`

**Comment by adriamt** [comment]
Sorry @mikepenz , I've seen my mistake. I've thought that the default style  for a normal PrimaryDrawerItem was gray letters instead of black and my SwitchDrawerItem was not showing the icon (but this was solved by cleaning the project)
