### ISSUE TITLE
The gap between the icon and the title

### ISSUE THREAD

**Issue by jidesoft** [mikepenz/MaterialDrawer#1396]
I just noticed using your MeterialDrawer, the gap between the toolbar's title and the menu icon on the left is large. Is there a way to reduce it? I tried toolbar.setTitleMargin but it doesn't have any effect. Thanks in advance for your answer.

**Comment by mikepenz** [comment]
@jidesoft that'S nothing related to the `MaterialDrawer` that's normal `Toolbar` + `ActionbarDrawerToggle` behavior. Please look it up on google how to change this.
