### ISSUE TITLE
[Question] Using Custom Views

### ISSUE THREAD

**Issue by mtwn105** [mikepenz/MaterialDrawer#1397]
How to use custom views in the Drawer such as,
I have a listview in a layout resource `listview.xml` and I want to show that list in the drawer, how to do it?

**Comment by mikepenz** [comment]
@mtwn105 that's not how the `MaterialDrawer` should be used and I higly recommend not to do that. Also the `MaterialDrawer` has a `RecyclerView` which you can already fill with items.
