### ISSUE TITLE
Gray border below custom header

### ISSUE THREAD

**Issue by tomlobato** [mikepenz/MaterialDrawer#1398]
Hello,
I am struggling on it. Already checked and I`m sure it is not in my custom header xml. Any ideas on how to remove it? Thanks.
 
<img width="352" alt="captura de tela 2016-07-16 as 4 52 54 pm" src="https://cloud.githubusercontent.com/assets/1187704/16895442/71bada18-4b76-11e6-875c-0159579362fe.png">

    private void setupDrawer(){
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);

        drawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withHeader(R.layout.common_menu_header)
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        onNavigationItemSelected(drawerItem);
                        return true;
                    }
                })
                .build();

        setupDrawerHeader(drawer.getHeader());

        int i = 0;

        for (WedMenuItem wedMenuItem: WedMenuItem.itemsToShow(wedding)) {
            final int _i = i; i++;

            PrimaryDrawerItem item = new PrimaryDrawerItem() {
                @Override
                public void onPostBindView(IDrawerItem drawerItem, View view) {
                    super.onPostBindView(drawerItem, view);
                    view.setBackgroundColor(btnColor(_i));
                }
            };

            item.withName(wedMenuItem.title())
            .withIdentifier(wedMenuItem.ordinal())
            .withTextColor(Color.WHITE);

            drawer.addItem(item);
        }
    }

    private int btnColor(int position){
        String c = null;
        switch ((position) % 10) {
            case 0:  c = "#708C92"; break;
            case 1:  c = "#95BBC2"; break;
            case 2:  c = "#ACC7CC"; break;
            case 3:  c = "#97E1F0"; break;
            case 4:  c = "#00B2D8"; break;
            case 5:  c = "#0086A3"; break;
            case 6:  c = "#8A5175"; break;
            case 7:  c = "#B76D9D"; break;
            case 8:  c = "#DDB8CF"; break;
            case 9:  c = "#E0D3AA"; break;
            case 10:  c = "#708C92"; break;
        }
        if (c == null) c = "#c0c0c0";
        return Color.parseColor(c);
    }

    protected void setupDrawerHeader(View header){
        CircleImageView _menu_header_avatar_fiance0 = (CircleImageView) header.findViewById(R.id.menu_header_avatar_fiance0);

        Picasso.with(this)
                .load(wedding.fiance0.avatarUrl)
                .into(_menu_header_avatar_fiance0);

        CircleImageView _menu_header_avatar_fiance1 = (CircleImageView) header.findViewById(R.id.menu_header_avatar_fiance1);

        Picasso.with(this)
                .load(wedding.fiance1.avatarUrl)
                .into(_menu_header_avatar_fiance1);

        TextView _wdate = (TextView) header.findViewById(R.id.wdate);
        _wdate.setText(wedding.coverDate);
    }

common_menu_header.xml:

    <?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/common_menu_header"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:paddingBottom="20dp"
        android:paddingLeft="20dp"
        android:paddingRight="20dp"
        android:paddingTop="35dp">
    
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            >
            <de.hdodenhof.circleimageview.CircleImageView
                android:id="@+id/menu_header_avatar_fiance0"
                android:layout_width="50dp"
                android:layout_height="50dp"
                />
    
            <de.hdodenhof.circleimageview.CircleImageView
                android:id="@+id/menu_header_avatar_fiance1"
                android:layout_marginLeft="-5dp"
                android:layout_width="50dp"
                android:layout_height="50dp"
                />
    
        </LinearLayout>
    
        <TextView
            android:id="@+id/wdate"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="0dp"
            android:textSize="40dp"
            android:textColor="@color/blue2C"
            style="@style/FontHelloBeautiful"
            />
    
    
    </LinearLayout>

**Comment by tomlobato** [comment]
Solved...

                .withHeaderDivider(false)
                .withHeaderPadding(false)

**Comment by mikepenz** [comment]
Great that you solved it :)
