### ISSUE TITLE
Lack of examples

### ISSUE THREAD

**Issue by kamilj** [mikepenz/MaterialDrawer#1399]
I know that you support the concept of using nawigation drawer only with fragments, 
but why you have not created a single example of how you use it ?

Is this API supports the nd with activities ?

**Comment by mikepenz** [comment]
@kamilj I don't see the point why this needs an example. There are the details about the listener, which is called when you click an item. After this it's up to you what you want to do with the click event. You can whatever you want. The `MaterialDrawer` is not limited to any behavior. 

Within the listener you can do everything: https://github.com/mikepenz/MaterialDrawer#add-items-and-adding-some-functionality

**Comment by kamilj** [comment]
Sadly, this can't be done in most cases.
Is it works in some complex application?
Maybe there is some open source project?

It looks like the conceptual issue.

**Comment by kamilj** [comment]
Thx Mike!
