### ISSUE TITLE
How can I determine whether drawer is opened or closed?

### ISSUE THREAD

**Issue by tral** [mikepenz/MaterialDrawer#14]
Couldn't find a corresponding method :(

**Comment by tral** [comment]
According to Google Design guidelines, drawer has to close when you press the system back button.

```
  @Override
    public void onBackPressed(){
        if(isDrawerOpen()){
            drawerResult.closeDrawer();
        }
        else{
            super.onBackPressed();
        }
    }
```

So, in this method I need to know whether it's opened or not.
Now I store the drawer's state in the global variable, but it's not the best decision though...

**Comment by mikepenz** [comment]
Hi. 

Yeah you are right, there is no direct method call to check this. 

You can do following:
```java
result.getDrawerLayout().isDrawerOpen(Gravity.START)
```

with the next version you can do it like this:

```java
result.isDrawerOpen()
```

**Comment by tral** [comment]
thanks!

**Comment by mikepenz** [comment]
@tral no problem :). 

At least in v1.0.0 everything which is required for a standard project should be in ;)
