### ISSUE TITLE
Request - withIcon without calling getResources

### ISSUE THREAD

**Issue by TurKurT656** [mikepenz/MaterialDrawer#140]
Hi, i'm using this code to add a profile to Navigation Drawer:

final IProfile appIcon = new ProfileDrawerItem().withName("Saman")
.withIcon(getResources().getDrawable(R.drawable.ic_call_chart))
.withEmail("turkurt656@yahoo.com");

but AndroidStudio says that getDrawable is depricated :|
can u add a method that we use withIcon method without calling getDrawable? for example:

.withIcon(R.drawable.ic_call_chart)

**Comment by raghunandankavi2010** [comment]
The getDrawable(id) is deprecated in api 22. You should use getResources().getDrawable(R.drawable.profile, getTheme()) instead. Source : http://developer.android.com/reference/android/content/res/Resources.html#getDrawable%28int%29

**Comment by mikepenz** [comment]
@TurKurT656 see the answer of @raghunandankavi2010 

about the .withIcon without calling getResources. i think this is not necessary. in 95% of all usecases you would load the profile header images by code so you don't have them as resource
