### ISSUE TITLE
Click highlighting

### ISSUE THREAD

**Issue by AccessTlt** [mikepenz/MaterialDrawer#1400]
Hi Mike.
What is a simple way to disable highlighting on click items?

**Comment by mikepenz** [comment]
@AccessTlt on press or after selecting it?

**Comment by AccessTlt** [comment]
On press item.
(I override selected item colors by style)

**Comment by mikepenz** [comment]
@AccessTlt this comes by the defined ripple. If you want to get rid of it, your would have to create a `CustomDrawerItem`. The `BasePrimaryDrawerItem` sets the ripple backgroudn here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BasePrimaryDrawerItem.java#L81

If you extend from the `BasePrimaryDrawerItem` like the `PrimaryDrawerItem` (https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/PrimaryDrawerItem.java) just set your own background after the `bindViewHelper`

**Comment by AccessTlt** [comment]
Thanks for quick responce.
I'm novice in android coding, but i wil try.

**Comment by AccessTlt** [comment]
Sorry for question.
I create CustomPrimaryDrawerItem extends BasePrimaryDrawerItem
How can i set selectable background in bindView method?

**Comment by mikepenz** [comment]
@AccessTlt you can look at the implementatoin of the `PrimaryDrawerItem` You just have to provide a line like the following as addition: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BasePrimaryDrawerItem.java#L81 and set your own background which has no touch effect. Might just a drawable with a selected state and a non selecteds tate

**Comment by AccessTlt** [comment]
I understand that it is too difficult ))
I try to create custom item:
```
public class CustomPrimaryDrawerItem extends PrimaryDrawerItem {
            @Override
            public void bindView(ViewHolder holder) {
                super.bindView(holder);
                    Context ctx = holder.itemView.getContext();
                    UIUtils.setBackground(holder.itemView, UIUtils.getSelectableBackground(ctx, R.drawable.item_not_pressed, true));
            }
        }
```
and apply background:
``` 
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_pressed="true"
        android:color="@android:color/transparent"/> <!-- pressed -->
</selector>
```
but this change color of selected items and take no effect to disable highlighting (

I fill drawer by dynamicaly data and update drawer by clicking on items.
I use multiply select and locked drawer. Excess highlighted blinking only spoil the visual representation (

Is there an easy way to implement?

**Comment by mikepenz** [comment]
@AccessTlt in your code. you do not have to use the `UIUtils` to set your drawable then. 

I would recommend that you create a drawable with all states, including enabled, pressed, disabled, selected etc. then it should work. 

this should also directly work without notifying the adapter about an item update. all other solutions via code will require the item to be updated via the notify method which would trigger the animation (also flashing) to be done via the itemanimator. 

so there are multiple solutions. In general these things work like they do in a normal adapter / recyclerView setup and are not really specific to the `FastAdapter`
