### ISSUE TITLE
RTL ISSUE in material_drawer_header

### ISSUE THREAD

**Issue by mwshubham** [mikepenz/MaterialDrawer#1402]
There might be a little problem in material_drawer_header. The username and password clashes with material_drawer_account_header_text_switcher.

Please check is there any similar rtl issue in the latest version of library.

note: the same problem occured in 5.0.X but was fixed in 5.2.X AFAIK.

Here are samples:

![3](https://cloud.githubusercontent.com/assets/8881480/16909426/560aba6a-4cf0-11e6-87c2-484da94c928c.png)
![device-2016-07-18-135629](https://cloud.githubusercontent.com/assets/8881480/16909427/560dab76-4cf0-11e6-981d-ea96c9c372b7.png)

**Comment by mikepenz** [comment]
@mwshubham which version of the drawer are you using. This can't really happen with the `compactHeader` as it uses a `LinearLayout` and the arrow is to the right of the lines for the text?

**Comment by mikepenz** [comment]
@mwshubham I may have identified a problem with the normal `AccountHeader` but none for the compact header

**Comment by mwshubham** [comment]
Sorry for the trouble mike its seem that on different client project i was using different Material drawer version. It seems to be fixed now. You can close it if you want. I will reopen it with more info if there is any problem. Thanks mike.

**Comment by mikepenz** [comment]
oh ok great :)
