### ISSUE TITLE
Inconsistent drawer Items font face 

### ISSUE THREAD

**Issue by shaikansaar** [mikepenz/MaterialDrawer#1403]
@mikepenz

Hi,

I am running my application in RTL and displaying text in arabic with the font face (fonts/ar/DroidKufi-Regular.ttf) I have noticed that some of the drawer items does not apply this font face uses the default font.  Please find attached snapshot.

![image](https://cloud.githubusercontent.com/assets/4800397/16909588/ca0650de-4ce4-11e6-851a-326a5d8515b8.png)

Here is the code to draw the items:

```java
 // Draw section, then draw it's sub items
                SectionDrawerItem sectionItem = new SectionDrawerItem()
                        .withTypeface(SCUtil.getSCFont(lang)).withName(item.getLabel());

                result.addItem(sectionItem);


                for (int x = 0; x < item.getItems().size(); x++) {
                    SCMenuItem subItem = item.getItems().get(x);
                    PrimaryDrawerItem menuItem = new PrimaryDrawerItem()
                            .withTypeface(SCUtil.getSCFont(lang))
                            .withIdentifier(subItem.getId()).withIcon(icons.get(subItem.getId()))
                            .withName(subItem.getLabel());

                    result.addItem(menuItem);
```

Your help will be appreciated. Thanks.

Regards,
Shaik

**Comment by mikepenz** [comment]
Both items have the same `fontFamily` set (https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_primary.xml#L35) 

and also get the typeface applied:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BasePrimaryDrawerItem.java#L93
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/SectionDrawerItem.java#L123

It might be related to the different font size?

**Comment by shaikansaar** [comment]
@mikepenz 

Hi Mike,

Thanks for the quick response. The version we have is v4.0.5 and in this version the setTypeface is not set in SectionDrawerItem.

Is there a work around to set this font face or do we have to upgrade to latest version?

Thanks
Shaik

**Comment by mikepenz** [comment]
@shaikansaar sorry no support for older versions than the latest.

You might can create a `CustomDrawerItem` which fixes it for you.
