### ISSUE TITLE
MiniDrawer with ViewPager in content frame

### ISSUE THREAD

**Issue by marbat87** [mikepenz/MaterialDrawer#1404]
Hi,

I used you sample implementation of MiniDrawer.
In the app content I have a frameLayout: it sometimes contains a fragment with a ViewPager.
Unfortunately it is quite unusable, because when I try to swype the viewpager from left to right, the minidrawer always get open, although I swype on the frame and not on the drawer.
Is there any workaround in order to avoid this behaviour?
Is would be nice if the minidrawer get open only when user swypes on the drawer itself and not on the frame content.

Thanks in advance
Marcello

**Comment by mikepenz** [comment]
@marbat87 there is a different "behavior" available for the `MiniDrawer` which might does the job for you: https://github.com/mikepenz/Crossfader/blob/develop/library/src/main/java/com/mikepenz/crossfader/Crossfader.java#L52 

just add `withGmailStyleSwiping` to your `Crossfader`

**Comment by marbat87** [comment]
Great! I will check it and will let you know!

**Comment by marbat87** [comment]
It works perfectly.
Many thanks.
