### ISSUE TITLE
add .withDisableText method

### ISSUE THREAD

**Issue by AngleV** [mikepenz/MaterialDrawer#1405]
Hi Mike. How's life ?

is it possible to add a method to getDrawerItem so that to change text when item is disabled ?

e.g

```
drawer.getDrawerItem(2).withDisabledText('mpla mpla mpla');
```
Thank you

**Comment by mikepenz** [comment]
@AngleV nothing for the default behavior, but you can do this easily be extending the `PrimaryDrawerItem` and create your custom `DrawerItem` which also changes text when disabled. But in general the easiest would already be that you just set the text when you disable the item, as you have to do this anyway

**Comment by AngleV** [comment]
hehe just wanted to avoid extra work...  :-)
Anyway thank you

**Comment by mikepenz** [comment]
Haha. Nice try :D But I can't add everything :P

**Comment by AngleV** [comment]
in case someone else is looking for something.

https://gist.github.com/AngleV/400377184386193c985d905bd97f2d40

**Comment by mikepenz** [comment]
@AngleV might wanna add an FAQ entry? https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md

A new section "CustomDrawerItem's" and adding a yours as first item?

**Comment by AngleV** [comment]
for sure mate !!!

**Comment by mikepenz** [comment]
thank you :)
