### ISSUE TITLE
AccountHeader's Name Stuck to Edges

### ISSUE THREAD

**Issue by acosti** [mikepenz/MaterialDrawer#1407]
Hello,

I'm attempting to center the AccountHeader's Name & Email fields.
I have used my own "material_drawer_header.xml" and am attempting to center said fields, preferably via their layout (LinearLayout).
However, no matter the gravity that I set nor the layout_horizontal or layout_centerInParent -- they stick to their original position (left usually, or right in RTL). 

Is there any explanation for this? What am I doing wrong?

**Comment by mikepenz** [comment]
@acosti I can't really give support for general android layouts, or for such a custom behavior. 
The drawer allows you to do so, but it's still custom behavior. 

You have to remember that you can't positioning the `LinearLayout` itself as its inside a `RelativeLayout` which already defines its position. I think it's much easier if you directly change the `TextView`s or might add an additional layout inbetwean

**Comment by acosti** [comment]
Thank you. I'll go ahead and close.
