### ISSUE TITLE
Is it possible to add Fragments dynamically?

### ISSUE THREAD

**Issue by icoolguy1995** [mikepenz/MaterialDrawer#1408]
When i was using NavigationDrawer from android.support:design, i got this done by **SharedPreferences**, like this:

```
mNavigationView.setNavigationItemSelectedListener(new NavigationView.OnNavigationItemSelectedListener() {
    @Override
    public boolean onNavigationItemSelected(MenuItem menuItem) {
       mDrawerLayout.closeDrawers();
       if (savedPreferences.getBoolean("add_frag", true)) {
             if (menuItem.getTitle() == "frag") {
             FragmentTransaction xfragmentTransaction = mFragmentManager.beginTransaction();
             xfragmentTransaction.replace(R.id.containerView, new fragFragment()).commit();
       }
    }
}
```

Now how can i do the same with this library? As `getTitle` doesn't work with this library, what are the alternatives? I have tried using 'if (position ==1)' but this doesn't work at all.

Thanks for helping! And creating this wonderful library.

**Comment by mikepenz** [comment]
http://stackoverflow.com/a/38450730/325479
