### ISSUE TITLE
Persistent Drawer - open menu button

### ISSUE THREAD

**Issue by aprzybylo** [mikepenz/MaterialDrawer#1409]
I use the persistent drawer. Is it possible to add in mini drawer a icon that open a big drawer? Like that: 
![view_small](https://cloud.githubusercontent.com/assets/3522036/16953112/1f905ec2-4dcc-11e6-87c8-99aa62d3b17f.png)

In big drawer the same icon should close the menu:
![big_view](https://cloud.githubusercontent.com/assets/3522036/16953172/54ecc150-4dcc-11e6-9dea-5ad811fd94f7.png)

**Comment by mikepenz** [comment]
@aprzybylo that's a very custom behavior. I think adding this to the `MiniDrawer` will require some work, as it is not built to include custom views on top. You might be able to add it as first element inside the `MiniDrawer` above the header. 
You can obtain the root container view of the `MiniDrawer` by doing the following:
```
((LinearLayout)miniDrawer.getRecyclerView().getParent())
```
you can add there a new view at the position, which will be your hamburger. 

For the normal  `MaterialDrawer` I suggest that you overwrite the layout of the header, add the hamburger button, and add a listener to it after the drawer was built by getting the header from the `Drawer` object and searching for the view which is your button.
The normal header layout for the `AccountHeader` is the following:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml
(copy paste this to your project and modify it (don't remove any views or it will crash), it will automatically overwrite the layout from the lib)
