### ISSUE TITLE
Feature request: Expandable items

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/MaterialDrawer#141]
I need something like this:
http://stackoverflow.com/questions/23195740/how-to-implement-android-navigation-drawer-like-this

Do you think it's possible?

**Comment by mikepenz** [comment]
@Rainer-Lang i'm afraid this is not as easy at it seems. Not sure if i like the idea of adding an ExpandableListView here.

**Comment by jasonborja** [comment]
Mike, Really like your work.  I too need a drawer item that expands to reveal other drawer items (i.e. similar to the profile selector in the accountheader section). Any chance you're rethinking your initial position on this?  OR can you provide directions on how we could extend your library to support this type of functionality?

**Comment by mikepenz** [comment]
@jasonborja you can still implement the logic that if you click on a DrawerItem it adds new items to the list, and you remove them on a second click. This will work.

**Comment by Rainer-Lang** [comment]
@mikepenz And what about an animation for opening or closing? Does MaterialDrawer have animations for add or remove items? Is this a feature of the newly implemented recyclerview?

**Comment by mikepenz** [comment]
@Rainer-Lang the RecyclerView allows to interact as any RecyclerView you used. You can provide and define everything you need. The BaseAdapter also uses the correct notify methods
