### ISSUE TITLE
set StatusBar color programmatically

### ISSUE THREAD

**Issue by marbat87** [mikepenz/MaterialDrawer#1411]
Hi,

I need to use the withTranslucentStatusBar(true) option on both drawer and header.
I have a problem because I have a dynamic themes management (theme colors are set to view trough java code).
But with the option mentioned above It seems that it is not possible to change the status bar color by code, indeed it picks up automatically the colorPrimaryDark from theme also if I try to override the statusbarcolor by code.

If I set withTranslucentStatusBar(false) in the drawer it picks up my custom color, but the visual effect is not good.

Any workaround for this?

Thanks in advance,
Marcello

**Comment by mikepenz** [comment]
@marbat87 you can change the `StatusBar` color programmatically via the `DrawerLayout` as this one controlls the insets.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/1247#issuecomment-217641415
