### ISSUE TITLE
How do I get the drawer to appear above the actionbar?

### ISSUE THREAD

**Issue by caralin3** [mikepenz/MaterialDrawer#1412]

**Comment by mikepenz** [comment]
@caralin3 not possible above an `ActionBar`. That's just possible with a `Toolbar`.

**Comment by mikepenz** [comment]
@caralin3 please rever to one of the samples using a `Toolbar` it's really simple and the change can be done within a few minutes

**Comment by caralin3** [comment]
I converted to a Toolbar thanks!
