### ISSUE TITLE
LOCK_MODE_LOCKED_CLOSED in 6.0

### ISSUE THREAD

**Issue by socialvanana** [mikepenz/MaterialDrawer#1413]
drawer.getDrawerLayout().setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);

after this code, still can be opened.

I can slide to left and right.

Is lockmode working on above 6.0 ?

**Comment by mikepenz** [comment]
@socialvanana `LockMode` comes from `DrawerLayout` and is not implemented nor modified by the `MaterialDrawer` please search on Google / StackOverFlow for answers.

**Comment by socialvanana** [comment]
Oh, my fault, ok I will.
Thanks for the fast.
