### ISSUE TITLE
Looking to set an overlay on the drawer view

### ISSUE THREAD

**Issue by ashwinbhaskar** [mikepenz/MaterialDrawer#1414]
Hi, I have been trying to add an overlay on top of the drawer view. I tried to add
`
withDrawerLayout(R.layout.my_drawer_layout)`

**my_drawer_layout**

```
<android.support.v4.widget.DrawerLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/d_drawer_layout_root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    >

  <FrameLayout
      android:id="@+id/d_drawer_layout_content"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:alpha="0.5"
      >
    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/blocker_image"
        android:layout_gravity="center"
        />

  </FrameLayout>
</android.support.v4.widget.DrawerLayout>

```

But the image comes in the center of the full activity. I want it to come on the center of the drawer view. Can this be done with the existing library?

**Comment by mikepenz** [comment]
@ashwinbhaskar you have to take a closer look on how a `DrawerLayout` works. It contains 2 basic views (or more) first the `slider` and second the `content` area. 

In the above case you have just defined the content which is the center. as it seems you want to define a `overlay` for the slider. 

You can get a reference to the `Slider` via the `Drawer` object. Which is a `ScrimInsetsRelativeLayout` and you can just add a childview programatically in there.

**Comment by ashwinbhaskar** [comment]
thanks mike.
