### ISSUE TITLE
What is the best way to update badge before the drawer is opened

### ISSUE THREAD

**Issue by jidesoft** [mikepenz/MaterialDrawer#1415]
I know I can update DrawerItem with badge but I would like to do it just before the drawer is opened. Is there a listener for it? Such as onDrawerOpening, onDrawerClosing etc. Thanks. Awesome library!

**Comment by mikepenz** [comment]
@jidesoft there is no real listener for this. You may can use one of the  `DrawerListener`s which gives you the callback when the drawer is moving (opening / closing) 
--> https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L1071

in general the best way is to update the item when the value changes. as it will trigger the notify of the item, which shouldn'T yet cause a drawing as the drawer is not visible.
