### ISSUE TITLE
How to use this in my app 

### ISSUE THREAD

**Issue by gauravzuse** [mikepenz/MaterialDrawer#1416]
please can you tell me how to use this library in my app i imoprted this in my project but dont know how to use it . am a beginner .

**Comment by mikepenz** [comment]
@gauravzuse sorry I can't give general android support. 

Here you can find the required steps to add the library to your project:
https://github.com/mikepenz/MaterialDrawer#1-provide-the-gradle-dependency

And then you can use the later parts of the readme to find out what you can do, or you head over to the sample project and check out it's source

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java
