### ISSUE TITLE
status bar is overlying on the drawer

### ISSUE THREAD

**Issue by mackagy1** [mikepenz/MaterialDrawer#1417]
Hello.

My English is poor. I'm sorry.

i’m putting the drawer in my page.
however, status bar is overlying on the drawer.

i do not want to do that status bar is overlying on the drawer.
therefore i tried to use withDisplayBelowStatusBar(true) and false,but i couldn’t do this.

could you tell me why this situation is ?

this is codesnipet

```
DrawerBuilder drawerBuilder = new DrawerBuilder()
                .withActivity(activity)
                .withHeader(headerView)
                .withFooter(footerView)
                .withToolbar(toolbar)
                .withTranslucentStatusBar(false)
                .withDisplayBelowStatusBar(false/true)
                .withActionBarDrawerToggle(drawerToggle)
                .withOnDrawerItemClickListener((view, position, drawerItem) -> {
                     // code....
                });
```
(version 5.3.6)

**Comment by mikepenz** [comment]
@mackagy1 which theme are you using? can you also please add a screenshot how it looks right now and what you want to achieve?

**Comment by mikepenz** [comment]
You can also check out the sample app on how it's done there. It is also always important to use the correct theme

**Comment by mackagy1** [comment]
I've checked out the sample code.
And a result of reading the source, the problem has been corrected.
thank you! :)
