### ISSUE TITLE
Dynamic header background

### ISSUE THREAD

**Issue by sebastianmacarescu** [mikepenz/MaterialDrawer#1418]
Is it possible to load with picaso an image for the drawer header background?

**Comment by mikepenz** [comment]
@sebastianmacarescu yes. Just get the `View` from the `AccountHeader` after the `Drawer` was built.

```java
AccountHeader.getHeaderBackgroundView()
```

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L65
