### ISSUE TITLE
Possible bug? Updating Item's data during drawer's animation messes up selection

### ISSUE THREAD

**Issue by Polyterative** [mikepenz/MaterialDrawer#1419]
I don't know if it's a known bug or regular behavior but if you try to update an item **while** the drawer is scrolling to left the selection on the item becomes only partial (_no bg underline_).
Solved by updating the item's badge  by using `.updateBadge()` **only** if the drawer is _closed_

_Anyway just wanted to say that this is a really good library, it's a pleasure building my drawer with this, great dev, great community!_

**Comment by mikepenz** [comment]
@Polyterative I am quite sure that comes by Android getting confused of animating and drawing 2 different things. First the item, with the changed badge, and second the closing animation. 
Nothing I can do about those. Animation from the closing is done by the  `DrawerLayout` and redrawing the item by the `RecyclerView`.

Thank you .
