### ISSUE TITLE
Refresh the whole menu

### ISSUE THREAD

**Issue by JJSarrasin** [mikepenz/MaterialDrawer#1421]
I have some cases in my app where I need to refresh the whole menu. It could be improved in a second step, but for now I would like to refresh it.

There is no problem if I rebuild the whole drawer, but if the drawer is already open, the changes won't be displayed until it's closed and reopened. Is there a workaround for this ?

Thanks !

**Comment by mikepenz** [comment]
@JJSarrasin if you update items you have to notify the drawer about the changes. Normally you do this via:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L594
or
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L652
