### ISSUE TITLE
setSelection method leaves previous drawer item's icon highlighted

### ISSUE THREAD

**Issue by olmur** [mikepenz/MaterialDrawer#1422]
Hi, Mike! 
I use this method to select drawer item setSelection() it works fine but previously selected item's icon is still highlighted. I tried to use deselect method first and setSelection(-1) but it didn't help. Could you please help me with this issue? Bug was on Marshmallow.

Here is image

![img_2016-07-27 15 20 32](https://cloud.githubusercontent.com/assets/16815979/17174963/b02e41a0-540d-11e6-98a5-ff1ba05c74bd.jpg)

Also I have another similar issue. After I select first drawer item and then open and close accounts header drawer item's icon became unhighlighted. And this happened only with first drawer item. If I will select second one and then open-close accounts header everything is fine.

Here is image

![img_2016-07-27 15 26 43](https://cloud.githubusercontent.com/assets/16815979/17175160/8f7a6e1a-540e-11e6-8d13-d854cb4c826c.jpg)

**Comment by mikepenz** [comment]
@olmur how do you set the icons?

**Comment by olmur** [comment]
@mikepenz 
` return new PrimaryDrawerItem()
                .withName(getString(titleRes))
                .withIconTintingEnabled(true)
                .withIcon(IconUtil.getIconByRes(this, iconRes, R.color.navigation_drawer_secondary_text_color))
                .withSelectedIconColorRes(colorRes)
                .withSelectedTextColorRes(colorRes)
                .withIdentifier(id)
                .withTypeface(TextHelper.getFontWithType(getAssets(), TextHelper.FONT_500))
                .withBadgeStyle(new BadgeStyle()
                        .withBadgeBackground(getResources().getDrawable(R.drawable.navigation_drawer_badge_circle))
                );`

**Comment by mikepenz** [comment]
@olmur I used your code, and modified the sample to use it, and was not able to repoduce this issue, neither with a phone or an emulator. could you please provide a sample app to showcase the issue, so I might be able to reproduce it=

**Comment by olmur** [comment]
@mikepenz Hi Mike! Sorry that answering to late. I found solution to my problem! 
The cause was in this method withIconTintingEnabled(true), after I deleted it icons selection works as expected.

**Comment by mikepenz** [comment]
Great ;).
