### ISSUE TITLE
[Question] how to update opened drawer?

### ISSUE THREAD

**Issue by oleynikd** [mikepenz/MaterialDrawer#1426]
Hi,

Please help! How can I update existing opened drawer? I need to change profiles and items and get instant redraw...

Thanks.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

**Comment by oleynikd** [comment]
@mikepenz Thanks. I know I can update simple item, but how do I update `ProfileDrawerItem`?

**Comment by mikepenz** [comment]
Oh sorry misunderstood it. For the profiles it's exactly the same but with the `AccountHeader` object.

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L244

**Comment by oleynikd** [comment]
@mikepenz OK, understood! Thank you!!!
Could you please also help me on how to add view above the drawer? Can I somehow declare the position of drawer in xml?

Thank you!

**Comment by oleynikd** [comment]
Aha, `.withRootView(R.id.coordinator)`, never mind! Thank you a lot!!!!!!

**Comment by mikepenz** [comment]
@oleynikd you can also find this in the sample app ;)

**Comment by oleynikd** [comment]
Dear @mikepenz could you please help me with one more issue?

After implementing `MaterialDrawer` into my App I got issue with fullscreen mode. My app is a video playback app. The user is in Landscape mode video is displayed fullscreen. After inserting `MaterialDrawer` my video as well as UI gets clipped by system UI placeholder...

Here's the video preview:
https://www.dropbox.com/s/gdj307yazbox37o/device-2016-08-03-162724.mp4?dl=0

As you can see I get black margins (crops) of video and UI. Also drawer gets white right margin while app is in fullscreen mode.

I tried playing with `fitsSystemWindows` but no success.

How can I fix this?
Thanks in advance!

**Comment by mikepenz** [comment]
You might take a look here: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/FullscreenDrawerActivity.java

**Comment by oleynikd** [comment]
@mikepenz you are GENIUS!!!
This fixed issue with video and UI but drawer still has those strange white margins while in fullscreen:
https://www.dropbox.com/s/79zyua2l4dpsl02/device-2016-08-03-165927.mp4?dl=0

**Comment by mikepenz** [comment]
those margins are scary :D somehow resulted from the `fitsSystemWindows` flag somewhere :/ I do not set any paddings or so. and they have to be related to the system reacting to this flag
