### ISSUE TITLE
Adding user profiles dynamically

### ISSUE THREAD

**Issue by aishacharya** [mikepenz/MaterialDrawer#1427]
I am trying to create an account switcher that enables user to enter the name and email-id on a pop when clicked on "add another account".
I have used: `new ProfileSettingDrawerItem().withName("Add Another Member")` , but i havent come across a "Onclick" method that allows me to do so.
All i could find was `withOnAccountHeaderItemLongClickListener()`, but this applies onclick properties to the whole list(including the profiles).

**Comment by mikepenz** [comment]
@aishacharya yes you should have the normal listener for the whole list, and you just decide based on the identifier (which you should define for items) which item was clicked and which logic you should execute

**Comment by mikepenz** [comment]
Probably similar to this `if`
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L157

**Comment by aishacharya** [comment]
The only "onclick" listener that is provided is Longpress..Is there an alternative for a shortclick? 
withOnAccountHeaderItemLongClickListener() doesn't blend well with my application.

**Comment by aishacharya** [comment]
And since the list is dynamically added , i cant assign a stagnant identifier to "add account", is there a work around for this?

**Comment by aishacharya** [comment]
Thanx for the help...i kind of figured it out!...we can fix an identifier for a particular drawer item and apply any method on its click!
withOnAccountHeaderListener() does the required for me, it changes the profile as well as handles the list item click.

**Comment by mikepenz** [comment]
Great that you solved it for your case
