### ISSUE TITLE
Update user profile image icon

### ISSUE THREAD

**Issue by GutoMartins019** [mikepenz/MaterialDrawer#1428]
Hi Mike,

First of all, thanks for your amazing job!
I am trying to use the method `drawer.updateIcon(id, image in bitmap)`.
But the image don't update. I checked the image and is correct.

I tried update using the header object, but not work too.

There is any library that is necessary for this to work?

I can't find a solution.

Thanks again.

**Comment by mikepenz** [comment]
@GutoMartins019 you had an image prior to setting the bitmap? 

And your item has an identifier set?

**Comment by GutoMartins019** [comment]
Yes, i had a image before update, it was setted on create. My item have a identifier, a int value.

This is how i made:
`new ProfileDrawerItem()
                                .withName(user.getFirstName())
                                .withEmail(user.getEmail())
                                .withIcon(user.getProfileImageInBitmap())
                                .withIdentifier(3)`

Added this ProfileDrawerItem to my AccountHeaderBuilder
Build my drawer on create activity:
`drawer = new DrawerBuilder().withAccountHeader(headerResult)`

I now i want to update the profile imagem like this:

` if (drawer != null) {
            User user = new UserService().getUser();
            drawer.updateIcon(3, new ImageHolder(user.getProfileImageInBitmap()));
        }`

**Comment by mikepenz** [comment]
@GutoMartins019 you are mixing drawer and header. 

If you want to update a profile (an item of the `AccountHeader`) you have to use the `AccountHeader` specific methods to update it's elements. 

Which would result in something like this, to update the icon:

```java
profile5.withIcon(BitmapFactory.decodeResource(getResources(), R.drawable.leak_canary_icon));  
headerResult.updateProfile(profile5);
```

**Comment by GutoMartins019** [comment]
@mikepenz Thanks for help me!

Sorry for mixing things =/.

Now its working perfect!
