### ISSUE TITLE
Request - Radio and Toggle Buttons

### ISSUE THREAD

**Issue by sonovice** [mikepenz/MaterialDrawer#143]
Hey there @mikepenz. Are there any plans on adding Radio and Toggle Buttons (or Checkboxes) to the list of supported Drawer Items? Example from Google Play Movies (see "Downloaded only"): http://i.stack.imgur.com/cvCjb.png
I like your Drawer a lot and would be very grateful for having this feature.

**Comment by mikepenz** [comment]
@sonovice you can create custom DrawerItems if you like :) a really easy task. 

Will add some documentation on how you can create a custom DrawerItem soon ;). 

But adding those makes some sense ;)

**Comment by sonovice** [comment]
Thank you very much! Maybe it would make sense to merge the Description-Text-Part from the PrimaryDescriptionDrawerItem into the BaseDrawerItem and "activate" it with some kind of .withDescription function. Otherwise the list of possible DrawerItems could explode in the long run... (PrimaryDescrpitionDrawerItem, PrimaryDescriptionCheckboxDrawerItem, PrimarySchießMichTot etc.)

**Comment by mikepenz** [comment]
@sonovice yeah i think you are right :D will take a look at it later. 

"SchießMichTot ... :D Na klar. Da hört man die Deutschsprachigen wieder raus :D. Übrigens Hallo)

**Comment by sonovice** [comment]
@mikepenz Please don't punch me in the face, but could you maybe add another DrawerItem with an actual CheckBox? Google advises to use them if having more than one option in the context.

And while I already ask for way too much: Would be great to be able to set the color of the checkboxes :D

**Comment by mikepenz** [comment]
@sonovice color of the checkboxes must be overwriten by the style. if this is no option you will have to implement your own custom draweritem which is really easy :P

can you show me the specific definition by google would love to see some examples

**Comment by sonovice** [comment]
@mikepenz Take a look at http://www.google.com/design/spec/components/switches.html#switches-checkbox. Would be nice to have them for multiple options.
```
If you have multiple on/off options appearing in a list, checkboxes are a good way to preserve space.
If you have a single on/off option, avoid using a checkbox and use an on/off switch instead.
```

**Comment by mikepenz** [comment]
But as far as i see no use within a drawer. I meant a Google Definition for
it within drawers. If it's something you need for your app, you need
to define a CustomDrawerItem which is really easy.
