### ISSUE TITLE
Problem in adding header in custom container layout drawer

### ISSUE THREAD

**Issue by sirens** [mikepenz/MaterialDrawer#1431]
I am implementing custom container drawer as depicted in the sample app. I want to add header on the top of it also but when I try to add header in the layout it gives me error. It would be great if you could tell me how to use it. Find code snippets below.

**Activity where I want drawer**

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/colorPrimary"
    android:fitsSystemWindows="true"
    android:orientation="vertical"
    tools:context=".activities.Celebrities">

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@android:color/transparent"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

        <android.support.v7.widget.Toolbar xmlns:app="http://schemas.android.com/apk/res-auto"
            android:id="@+id/toolbar_celebrities"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="@color/colorPrimary"
            app:popupTheme="@style/ThemeOverlay.AppCompat.Dark" />

    </android.support.design.widget.AppBarLayout>

    <FrameLayout
        android:id="@+id/drawer_container_celebrity"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <ScrollView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/colorPrimary"
                android:focusableInTouchMode="true"
                android:orientation="vertical">

                <android.support.v7.widget.RecyclerView
                    android:id="@+id/celebrities_recyclerview"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:scrollbars="vertical" />
            </LinearLayout>
        </ScrollView>
    </FrameLayout>

</LinearLayout>
```

**Drawer layout**

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="200dp"
    android:background="@drawable/theme_color">

</LinearLayout>
```

**Function to header in the corresponding activity**

```
private void setDrawer(Bundle savedInstanceState) {
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar_celebrities);
        setSupportActionBar(toolbar);
        setTitle("Celebrities");

        result = new DrawerBuilder(this)
                .withRootView(R.id.drawer_container_celebrity)
                .withToolbar(toolbar)
                .withDisplayBelowStatusBar(false)
                .withActionBarDrawerToggleAnimated(true)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("Movies").withIcon(R.drawable.ic_local_movies),
                        new PrimaryDrawerItem().withName("TV").withIcon(R.drawable.ic_tv_white),
                        new PrimaryDrawerItem().withName("Celebrities").withIcon(R.drawable.ic_people),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem().withName("Watchlist").withIcon(R.drawable.ic_bookmark),
                        new PrimaryDrawerItem().withName("Reminders").withIcon(R.drawable.ic_alarm),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem().withName("Settings").withIcon(R.drawable.ic_settings),
                        new PrimaryDrawerItem().withName("Exit").withIcon(R.drawable.ic_exit_to_app)
                ).withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {

                        switch (position) {
                            case 0: {

                                Intent i = new Intent(Celebrities.this, Films.class);
                                i.putExtra("popularMovieJsonData", popularMoviesJsonData);
                                i.putExtra("popularTVJsonData", popularTVJsonData);
                                startActivity(i);
                            }
                            break;
                            case 1: {
                                Intent i = new Intent(Celebrities.this, TV.class);
                                i.putExtra("popularMovieJsonData", popularMoviesJsonData);
                                i.putExtra("popularTVJsonData", popularTVJsonData);
                                startActivity(i);
                            }
                            break;
                            case 2: {

                            }
                            break;
                            default: {
                                Toast.makeText(Celebrities.this, ("Invalid Choice " + position), Toast.LENGTH_SHORT).show();
                            }
                        }
                        return false;
                    }
                })
                .withSavedInstance(savedInstanceState).withSelectedItemByPosition(2)
                .build();
    }
```

**Comment by mikepenz** [comment]
@sirens please also add the error you get

**Comment by sirens** [comment]
@mikepenz Thanks for replying. There is no error. It is just not appearing. It produces a grey line one the top of the drawer.

Here is the code which I'm using while creating the header.

` private void setDrawer(Bundle savedInstanceState) {
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar_celebrities);
        setSupportActionBar(toolbar);
        setTitle("Celebrities");

        result = new DrawerBuilder(this)
                .withRootView(R.id.drawer_container_celebrity)
                .withHeader(R.layout.drawer_header)
                .withToolbar(toolbar)
                .withDisplayBelowStatusBar(false)
                .withActionBarDrawerToggleAnimated(true)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("Movies").withIcon(R.drawable.ic_local_movies),
                        new PrimaryDrawerItem().withName("TV").withIcon(R.drawable.ic_tv_white),
                        new PrimaryDrawerItem().withName("Celebrities").withIcon(R.drawable.ic_people),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem().withName("Watchlist").withIcon(R.drawable.ic_bookmark),
                        new PrimaryDrawerItem().withName("Reminders").withIcon(R.drawable.ic_alarm),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem().withName("Settings").withIcon(R.drawable.ic_settings),
                        new PrimaryDrawerItem().withName("Exit").withIcon(R.drawable.ic_exit_to_app)
                ).withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {

                        switch (position) {
                            case 0: {

                                Intent i = new Intent(Celebrities.this, Films.class);
                                i.putExtra("popularMovieJsonData", popularMoviesJsonData);
                                i.putExtra("popularTVJsonData", popularTVJsonData);
                                startActivity(i);
                            }
                            break;
                            case 1: {
                                Intent i = new Intent(Celebrities.this, TV.class);
                                i.putExtra("popularMovieJsonData", popularMoviesJsonData);
                                i.putExtra("popularTVJsonData", popularTVJsonData);
                                startActivity(i);
                            }
                            break;
                            case 2: {

                            }
                            break;
                            default: {
                                Toast.makeText(Celebrities.this, ("Invalid Choice " + position), Toast.LENGTH_SHORT).show();
                            }
                        }
                        return false;
                    }
                })
                .withSavedInstance(savedInstanceState).withSelectedItemByPosition(2)
                .build();
    }`

Rest of the stuff is in previous query.

**Comment by mikepenz** [comment]
@sirens no I meant which stacktrace is written in the log?

**Comment by sirens** [comment]
@mikepenz I am new into development, I don't know much debugging. Here is the verbose 

`08-01 17:40:07.674 29607-29607/sadboy.pickflick W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
08-01 17:40:07.984 29607-29728/sadboy.pickflick D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-01 17:40:07.997 29607-29607/sadboy.pickflick D/Atlas: Validating map...
08-01 17:40:08.052 29607-29728/sadboy.pickflick I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.00.02.042.016_msm8610_LA.BF.1.1.1_RB1__release_AU ()
                                                              OpenGL ES Shader Compiler Version: E031.25.03.00
                                                              Build Date: 02/11/15 Wed
                                                              Local Branch: 
                                                              Remote Branch: quic/LA.BF.1.1.1_rb1.10
                                                              Local Patches: NONE
                                                              Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.00.02.042.016 + 62ca4eb + acd831d + 9f8b442 + e027a02 + cba30ba + 53c303a + a649d79 + 23e16f8 + 5e97da7 + cbd2a44 + 33d072a + 7aacf06 + 72b33e7 + 28f6f60 + b4c13d8 +  NOTHING
08-01 17:40:08.054 29607-29728/sadboy.pickflick I/OpenGLRenderer: Initialized EGL, version 1.4
08-01 17:40:08.074 29607-29728/sadboy.pickflick D/OpenGLRenderer: Enabling debug mode 0
08-01 17:40:09.468 29607-29607/sadboy.pickflick I/Choreographer: Skipped 61 frames!  The application may be doing too much work on its main thread.
08-01 17:40:09.583 29607-29607/sadboy.pickflick W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
08-01 17:40:09.708 29607-29607/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-01 17:40:09.709 29607-29607/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-01 17:40:09.709 29607-29607/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-01 17:40:09.709 29607-29607/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-01 17:40:09.984 29607-29607/sadboy.pickflick I/Choreographer: Skipped 30 frames!  The application may be doing too much work on its main thread.
08-01 17:40:10.203 29607-29607/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-01 17:40:10.203 29607-29607/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-01 17:40:10.203 29607-29607/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-01 17:40:10.203 29607-29607/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-01 17:40:10.897 29607-29625/sadboy.pickflick I/art: Background sticky concurrent mark sweep GC freed 4052(343KB) AllocSpace objects, 17(3MB) LOS objects, 18% free, 16MB/20MB, paused 22.869ms total 46.632ms
`

Error part

`08-01 17:40:09.708 29607-29607/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-01 17:40:09.709 29607-29607/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-01 17:40:09.709 29607-29607/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-01 17:40:09.709 29607-29607/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-01 17:40:10.203 29607-29607/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-01 17:40:10.203 29607-29607/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-01 17:40:10.203 29607-29607/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-01 17:40:10.203 29607-29607/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
`

**Comment by sirens** [comment]
If this is not working out it would be great if you could tell how to use the drawer **under the toolbar with toggling back button and header**. 

**Everything inside the class**

`private Drawer result = null;
    private String popularMoviesJsonData;
    private String popularTVJsonData;
    private AsyncDownloader downloader1;
    private Snackbar snackbar;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_celebrities);


        Log.e("***** Init *****", "Calling drawer function");
        setDrawer(savedInstanceState);

        Intent i = getIntent();
        popularMoviesJsonData = i.getStringExtra("popularMovieJsonData");
        popularTVJsonData = i.getStringExtra("popularTVJsonData");

        snackbar = Snackbar
                .make(findViewById(R.id.celebrity_activity), "No Internet Connection", Snackbar.LENGTH_INDEFINITE)
                .setAction("CLOSE", new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        finish();
                    }
                });

        snackbar.setActionTextColor(Color.WHITE);

        checkConnection();
    }

    public void setUrls() {

        DatabaseUrl url = DatabaseUrl.getInstance();

        String popularPeople = url.getPopularPersons();
        downloader1 = new AsyncDownloader(this);
        downloader1.execute(popularPeople);

    }

    @Override
    public void setJsonData(String jsonData) {

        setPopularPeople(jsonData);
        downloader1.cancel(true);

    }


    private void populateRecyclerView(RecyclerView recyclerView, List<Person> celebs) {

        CelebrityAdapter adapter = new CelebrityAdapter(this, celebs);
        recyclerView.setAdapter(adapter);

        RecyclerView.LayoutManager layoutManager = new LinearLayoutManager(this);
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setHasFixedSize(true);
    }

    public void setPopularPeople(String jsonData) {
        List<Person> celebs;
        JSONObject jsonResponse;
        try {
            jsonResponse = new JSONObject(jsonData);

            JSONArray results = jsonResponse.getJSONArray("results");
            int dataSize = results.length();
            celebs = new ArrayList<>(dataSize);

            for (int i = 0; i < dataSize; i++) {

                JSONObject jsonFilm = results.getJSONObject(i);

                Person celeb = new Person();

                celeb.setName(jsonFilm.getString("name"));
                celeb.setProfilePath(jsonFilm.getString("profile_path"));

                JSONArray tempArray = jsonFilm.getJSONArray("known_for");
                JSONObject knownFor = tempArray.getJSONObject(0);

                if (knownFor.getString("media_type").equals("movie")) {
                    celeb.setKnownForFilm(knownFor.getString("original_title") + ", " + knownFor.getString("release_date").substring(0,4));

                }

                if (!celeb.getProfilePath().equals("null"))
                    celebs.add(celeb);

            }

            RecyclerView recyclerView = (RecyclerView) findViewById(R.id.celebrities_recyclerview);

            DisplayMetrics displaymetrics = new DisplayMetrics();
            getWindowManager().getDefaultDisplay().getMetrics(displaymetrics);

            int a =  (displaymetrics.heightPixels*90)/100;

            recyclerView.getLayoutParams().height =a - 30;
            populateRecyclerView(recyclerView, celebs);

        } catch (JSONException e) {
            e.printStackTrace();
        }
    }

    private void setDrawer(Bundle savedInstanceState) {

        Log.e("***** Init *****", "Setting up the drawer");

        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar_celebrities);
        setSupportActionBar(toolbar);
        setTitle("Celebrities");

        result = new DrawerBuilder(this)
                .withRootView(R.id.drawer_container_celebrity)
                .withHeader(R.layout.drawer_header)
                .withToolbar(toolbar)
                .withDisplayBelowStatusBar(false)
                .withActionBarDrawerToggleAnimated(true)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("Movies").withIcon(R.drawable.ic_local_movies),
                        new PrimaryDrawerItem().withName("TV").withIcon(R.drawable.ic_tv_white),
                        new PrimaryDrawerItem().withName("Celebrities").withIcon(R.drawable.ic_people),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem().withName("Watchlist").withIcon(R.drawable.ic_bookmark),
                        new PrimaryDrawerItem().withName("Reminders").withIcon(R.drawable.ic_alarm),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem().withName("Settings").withIcon(R.drawable.ic_settings),
                        new PrimaryDrawerItem().withName("Exit").withIcon(R.drawable.ic_exit_to_app)
                ).withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {

                        switch (position) {
                            case 0: {

                                Intent i = new Intent(Celebrities.this, Films.class);
                                i.putExtra("popularMovieJsonData", popularMoviesJsonData);
                                i.putExtra("popularTVJsonData", popularTVJsonData);
                                startActivity(i);
                            }
                            break;
                            case 1: {
                                Intent i = new Intent(Celebrities.this, TV.class);
                                i.putExtra("popularMovieJsonData", popularMoviesJsonData);
                                i.putExtra("popularTVJsonData", popularTVJsonData);
                                startActivity(i);
                            }
                            break;
                            case 2: {

                            }
                            break;
                            default: {
                                Toast.makeText(Celebrities.this, ("Invalid Choice " + position), Toast.LENGTH_SHORT).show();
                            }
                        }
                        return false;
                    }
                })
                .withSavedInstance(savedInstanceState).withSelectedItemByPosition(2)
                .build();

        Log.e("***** Init *****", "Result" + result);
    }

    @Override
    public void onBackPressed() {
        if (result != null && result.isDrawerOpen()) {
            result.closeDrawer();
        } else {
            super.onBackPressed();
        }
    }

    private void checkConnection() {
        boolean isConnected = ConnectivityReceiver.isConnected();
        showSnack(isConnected);
    }

    private void showSnack(boolean isConnected) {

        if (isConnected) {

            setUrls();

            if (snackbar.isShown()) {
                snackbar.dismiss();
            }
        } else {

            if (downloader1 != null ) {
                downloader1.cancel(true);
            }


            View sbView = snackbar.getView();
            sbView.setBackgroundColor(getResources().getColor(R.color.colorAccent));
            snackbar.show();
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
        MyApplication.getInstance().setConnectivityListener(Celebrities.this);
    }

    @Override
    public void onNetworkConnectionChanged(boolean isConnected) {
        showSnack(isConnected);
    }`


**Log**


08-02 00:08:40.545 32315-32315/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-02 00:08:40.545 32315-32315/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-02 00:08:40.545 32315-32315/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-02 00:08:40.545 32315-32315/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-02 00:08:43.927 32315-32315/sadboy.pickflick E/***** Init *****: Calling drawer function
08-02 00:08:43.927 32315-32315/sadboy.pickflick E/***** Init *****: Setting up the drawer
08-02 00:08:43.949 32315-32315/sadboy.pickflick E/***** Init *****: Resultcom.mikepenz.materialdrawer.Drawer@2c7a13da
08-02 00:08:43.998 32315-32315/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout
08-02 00:08:44.105 32315-32315/sadboy.pickflick E/RecyclerView: No adapter attached; skipping layout

**Comment by mikepenz** [comment]
@sirens the easiest solution to have a layout above the drawer is to use the `.withStickyHeader(R.layout.header)` method which will add a view above the drawer which is always visible. No custom handling. 

Just check the `CustomContainerActivity` of the sample app and add the single line and you will have the desired result

**Comment by sirens** [comment]
I tried it but it's not working. Nothing appears on the top. I build this on the code you provided itself.

**Comment by mikepenz** [comment]
I tried exactly what I mentioned above. I just added the above line to the `CustomContainerActivity` of the sample app, and it shows the header. 

Perhaps your header layout is different and has no size defined?

**Comment by sirens** [comment]
@mikepenz 

I am using this

**Header layout**

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="200dp"
    android:background="@drawable/theme_color">

</LinearLayout>`

**theme_color**

`<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <gradient
        android:angle="135"
        android:startColor="#2979ff"
        android:centerColor="#00b0ff"
        android:endColor="#00e5ff" />
</shape>`

**Comment by mikepenz** [comment]
@sirens it might is not able to resolve the height from the `LinearLayout` could you try something like this:

```xml
<ImageView xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:src="@drawable/header"
    android:adjustViewBounds="true"
    android:scaleType="fitCenter"></ImageView>
```

(which is used in the sample)

**Comment by mikepenz** [comment]
If it is working. You may try to wrap your header inside another `View` both with the 200dp defined, so it might be able to calculate the correct height

**Comment by sirens** [comment]
Thanks. You are my new favorite person. I am using this for now, where image is a transparent image.

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="200dp"
    android:background="@drawable/theme_color">

    <ImageView xmlns:android="http://schemas.android.com/apk/res/android"
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:src="@drawable/overlay"
        android:scaleType="centerCrop"
        android:background="#00ffffff" />

</RelativeLayout>
```
