### ISSUE TITLE
NonTranslucentDrawer below toolbar

### ISSUE THREAD

**Issue by xtonousou** [mikepenz/MaterialDrawer#1432]
How could I place NonTranslucentDrawer below toolbar?

    mDrawer = new DrawerBuilder()
                .withActivity(this)
                .withDisplayBelowStatusBar(true)
                .withTranslucentStatusBar(false)
                .addDrawerItems(
                        new SectionDrawerItem().withName(R.string.categories).withDivider(false),
                        new PrimaryDrawerItem().withName(R.string.all).withIcon(FontAwesome.Icon.faw_cog),
                        new PrimaryDrawerItem().withName(R.string.animals).withIcon(FontAwesome.Icon.faw_question),
                        new PrimaryDrawerItem().withName(R.string.funny).withIcon(FontAwesome.Icon.faw_github),
                        new PrimaryDrawerItem().withName(R.string.games).withIcon(FontAwesome.Icon.faw_bullhorn),
                        new PrimaryDrawerItem().withName(R.string.movies).withIcon(FontAwesome.Icon.faw_bullhorn),
                        new PrimaryDrawerItem().withName(R.string.nsfw).withIcon(FontAwesome.Icon.faw_bullhorn),
                        new PrimaryDrawerItem().withName(R.string.personal).withIcon(FontAwesome.Icon.faw_bullhorn),
                        new SectionDrawerItem().withName(R.string.setting).withDivider(false),
                        new SecondaryDrawerItem().withName(R.string.all).withIcon(FontAwesome.Icon.faw_music),
                        new SecondaryDrawerItem().withName(R.string.all).withIcon(FontAwesome.Icon.faw_gamepad),
                        new SecondaryDrawerItem().withName(R.string.all).withIcon(FontAwesome.Icon.faw_eye)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        return false;
                    }
                })
                .withSelectedItemByPosition(1) // Default All Sounds
                .withSavedInstance(instance)
                .build();

**Comment by mikepenz** [comment]
Please check the `CustomContainerActivity`

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java
