### ISSUE TITLE
Header Background Relative

### ISSUE THREAD

**Issue by mortezasun** [mikepenz/MaterialDrawer#1433]
Hi Mike!
When i used Header background (specially use a logo) , I Want  put a  profile section  (this id :
" material_drawer_account_header_text_section " )
below the header background
 Could you add this attribute to your Library? :)

**Comment by mikepenz** [comment]
@mortezasun you can just copy paste the xml to your project and overwrite it with whatever values you need. (just don't remove existing views with their id's)
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml

The android compiler will automatically pick up your modified version
