### ISSUE TITLE
Not able to run with targetSdkVersion 22

### ISSUE THREAD

**Issue by arashzz** [mikepenz/MaterialDrawer#1434]
Hi 

I'm trying to use this library in my project and my **targetSdkVersion** is set to **22**, after adding the library into the gradle and syncing, it throws some error messages as:

> Error:(5) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.

which was found at this path:

> /home/arash/AndroidStudioProjects/Tyche/app/build/intermediates/res/merged/debug/values-v23/values-v23.xml

Can you please help me how to fix this?

Please note that I don't want to change **targetSdkVersion** to **23** since that only works for 64bit systems while mine is 32bit.

Thank you in advance for your help

**Comment by mikepenz** [comment]
@arashzz please make sure your support library version is equal to the one used in the `MaterialDrawer` currently:
https://github.com/mikepenz/MaterialDrawer/blob/develop/build.gradle#L8

If you have a different version, you have to exclude the support libraries from the `MaterialDrawer` so it uses your (older) version:
http://stackoverflow.com/a/21765656/325479
(see the second sample)
