### ISSUE TITLE
Profile icon is not working !!?

### ISSUE THREAD

**Issue by amineMpdam** [mikepenz/MaterialDrawer#1436]
Well must say great library dude cheers. :)
after that being said, i was  trying you sample, but for some reason the .withIcon() method is not setting an image in the drawer, i tried passing both Uri object, and a string url but i always end up with the place holder instead.
any help ?!
ps: i've checked the image uri and it's fine.
[image uri](https://scontent.xx.fbcdn.net/v/t1.0-1/p100x100/13502097_1445733655452029_2091025019075368779_n.jpg?oh=89586be18e401fd62293e64d9782a2b8&oe=5818C4B0)

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#load-images-via-url
