### ISSUE TITLE
REQUEST "add withDisplayBelowToolbar method"

### ISSUE THREAD

**Issue by ParhamAhmadi** [mikepenz/MaterialDrawer#1438]
Hello @mikepenz 

Is it possible to add a method like "withDisplayBelowToolbar" ?

it'll be so good .

Thanks .

**Comment by mikepenz** [comment]
@ParhamAhmadi no plans to do so as it is against the guidelines and already possible with the current implementation

**Comment by ParhamAhmadi** [comment]
How Can I implement this?
@mikepenz

**Comment by ParhamAhmadi** [comment]
@mikepenz  Please Help Me

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java
