### ISSUE TITLE
Navigation Drawer displayed bad

### ISSUE THREAD

**Issue by Java-Help** [mikepenz/MaterialDrawer#144]
Hello. Sorry for my bad english (I'm using Google Translate). When I call the method .withDisplayBelowToolbar (true) Navigation Drawer displayed bad. Here's a screenshot : http://hkar.ru/zKaW. That's not all . At that time, when I pull the sidebar icon - burger is not moving , and turns into an arrow until the end , without a transition animation .

**Comment by mikepenz** [comment]
@Java-Help about the arrow. there is not animation because this is not default. this is disabled within the code. you can enable it by calling `.withActionBarDrawerToggleAnimated(true)`

about the misaligned toolbar. i will look at it. seems i've broken some things with the update to the ScrimsInsetLayout

**Comment by mikepenz** [comment]
@Java-Help yeah i had a small issue on my side. as an additional thing why do you need to display it below the toolbar? this is not a default behavior. also using an actionbar helps with the dark shadow above the ui which is automatically drawn by the drawer

**Comment by Java-Help** [comment]
Thanks for the quick reply , but that's not all . When I call the method .withTranslucentStatusBar (true), then I have bad displayed Toolbar, it becomes thicker than normal
![fhfjmd7drcm](https://cloud.githubusercontent.com/assets/10331350/6788435/71ad1230-d1aa-11e4-9dd4-e434287ee8b1.jpg)
![hmsfbp6dquw](https://cloud.githubusercontent.com/assets/10331350/6788436/73cb3b0a-d1aa-11e4-98ef-745514c02148.jpg)

**Comment by mikepenz** [comment]
@Java-Help do you have any custom theme or anything applied?

I will try. What is your android version?

**Comment by mikepenz** [comment]
@Java-Help fixed these issues in v2.5.6

**Comment by Java-Help** [comment]
When I turn the screen Drawer displayed as bad as before. And take away , please blackout Toolbar, when the Drawer is displayed below the Toolbar. It looks very ugly and introduces the user to a standstill.
![jlaco2axf6q](https://cloud.githubusercontent.com/assets/10331350/6800943/61889dd6-d234-11e4-9e02-ff09f8cdc611.jpg)

**Comment by mikepenz** [comment]
you let it recreate the drawer on screen orientation change?

**Comment by mikepenz** [comment]
just for people who find this issue. remove the shadow with_

```java
 result.getDrawerLayout().setScrimColor(Color.TRANSPARENT);
```

**Comment by mikepenz** [comment]
@Java-Help there is now a new function to really support this behavior. See the new sample https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java
