### ISSUE TITLE
No resource found that matches the given name 'MaterialTheme'.

### ISSUE THREAD

**Issue by mahdimortazavi** [mikepenz/MaterialDrawer#1442]
![2016-08-04_10-48-53](https://cloud.githubusercontent.com/assets/10667180/17392263/766a18ac-5a31-11e6-8572-5a7c7f2d64d7.jpg)
![2016-08-04_10-49-43](https://cloud.githubusercontent.com/assets/10667180/17392262/760b4700-5a31-11e6-834b-7f676e221c48.jpg)

min android must be 14

**Comment by mikepenz** [comment]
@mahdimortazavi  seems as it does not load the sub dependencies.

Could it be that you have the `jcenter` repository before the `mavenCentral` one?

Anyway, it will work when you provide the sup dependencies too:

```java
 // used to base on some backwards compatible themes
    // contains util classes to support various android versions, and clean up code
    // comes with the awesome "Holder"-Pattern
    // https://github.com/mikepenz/Materialize
    compile 'com.mikepenz:materialize:0.9.0@aar'

    // used to provide out of the box icon font support. simplifies development,
    // and provides scalable icons. the core is very very light
    // https://github.com/mikepenz/Android-Iconics
    compile 'com.mikepenz:iconics-core:2.7.2@aar'

    // used to fill the RecyclerView with the DrawerItems
    // and provides single and multi selection, expandable items
    // https://github.com/mikepenz/FastAdapter
    compile 'com.mikepenz:fastadapter:1.6.1@aar'
```

**Comment by mahdimortazavi** [comment]
thanks very much :+1:  :)

**Comment by honjiaxuan** [comment]
i have the same issue and solved with the same solution also. Thank you

**Comment by msneujink** [comment]
same issue here, adding the dependencies solved the problem

**Comment by rubengees** [comment]
Might there be a solution without specifying the dependencies manually? I mean it's Gradles job to resolve those and that are 3 (in my case 2 as I use Iconics at other places) dependencies more the user would have to maintain...

**Comment by mikepenz** [comment]
Should work already. mavenCentral will serve it correctly

**Comment by rubengees** [comment]
Ah you're right. Worked after deleting all Gradle caches and redownloading.

**Comment by Mygod** [comment]
This problem is occurring again. I cleaned all my cache and the error just popped up. I don't want to add extraneous dependencies. :/

**Comment by mikepenz** [comment]
@Mygod the dependencies are just the minimum. just follow the instructions in the readme

**Comment by Mygod** [comment]
But I didn't use those additional features?
