### ISSUE TITLE
how to rtl drawer menu?

### ISSUE THREAD

**Issue by mahdimortazavi** [mikepenz/MaterialDrawer#1443]
how to create rtl drawer menu without use
 layout direction in toolbar and
getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL)
because min android 14 and this statment not support api 14.
![device-2016-08-04-120336](https://cloud.githubusercontent.com/assets/10667180/17394279/87dd53ea-5a3d-11e6-98ac-f8851a45df27.png)
![screenshots1](https://cloud.githubusercontent.com/assets/10667180/17394280/87e1a2d8-5a3d-11e6-841d-31676697e797.jpg)

**Comment by amorenew** [comment]
RTL is from 17 and below is only 7% devices
https://developer.android.com/about/dashboards/index.html
also try use arabic text and check alignment or use recycleview to the drawer
new DrawerBuilder().**withRecyclerView**(your view)

**Comment by mahdimortazavi** [comment]
I have  api 14 I use.
anyway ، Here it is said that the api 14 and the RTL support.
![2016-08-04_12-53-20](https://cloud.githubusercontent.com/assets/10667180/17395279/e15a404a-5a42-11e6-8d31-7e9349b03c90.jpg)

**Comment by amorenew** [comment]
yes RTL support here is mean **when it is available** by system
the only way is to use recyclerview

**Comment by mikepenz** [comment]
@mahdimortazavi as @amorenew already correctly mentioned. RTL support is included but as Android only supports it starting with API 17 I can't do anything to bring it prior to API 17.

You still have the option to overwrite all layouts and alter them to look RTL, and to put the drawer on the right side, but this won't change the `Hamburger` icon to the right side, and it's rather hacky.

**Comment by mrzkhalifeh8** [comment]
@mikepenz by using below code in activity before calling `setContentView`  or in application class the   `Hamburger ` icon goes to the right. 
```
        Configuration configuration = getResources().getConfiguration();
        configuration.setLocale(new Locale("fa"));
```

**Comment by sadeghgaga** [comment]
@mrzkhalifeh8 WOW! Thanks.
