### ISSUE TITLE
build failed after update library to 5.4.0

### ISSUE THREAD

**Issue by anasanasanas** [mikepenz/MaterialDrawer#1446]
> Error:(1545) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme'.
Error:(1569) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar'.
Error:(1593) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar.TranslucentStatus'.
Error:(1617) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light'.
Error:(1640) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.ActionBar'.
Error:(1663) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.ActionBar.TranslucentStatus'.
Error:(1686) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar'.
Error:(1709) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.ActionBar'.
Error:(1732) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.ActionBar.TranslucentStatus'.
Error:(1755) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.TranslucentStatus'.
Error:(1778) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.TranslucentStatus'.
Error:(1801) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.TranslucentStatus'.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/1442
