### ISSUE TITLE
.withDisplayBelowToobar() not working enymore ?

### ISSUE THREAD

**Issue by takirow** [mikepenz/MaterialDrawer#1447]
I need my Drawer below the Toobar, how can I do this now ?

**Comment by mikepenz** [comment]
Please see this sample: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java

**Comment by takirow** [comment]
My code is exactly the same.

http://imgur.com/a/5KSLb



        mNavegationDrawer =  new DrawerBuilder(this)
                .withToolbar(mToolbar)
                .withDisplayBelowStatusBar(false)
                .withActionBarDrawerToggleAnimated(true)
                .withSavedInstance(savedInstanceState)
                .withSelectedItem(0)
                .build();

        mNavegationDrawer.addItem(new PrimaryDrawerItem().withName("Dolar").withIcon(R.drawable.ic_action_dolar));

**Comment by mikepenz** [comment]
@takirow oops sorry mixed up statusbar and toolbar. 
In general you need the proper theme to be set. Which theme do you use?

**Comment by takirow** [comment]
MaterialDrawerTheme.Light ?

**Comment by mikepenz** [comment]
should be fine. could you remove the `withDisplayBelowStatusBar` and check this sample: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L111

it's the default and general correct one.
