### ISSUE TITLE
Stricky item's badge doesn't update at runtime

### ISSUE THREAD

**Issue by Polyterative** [mikepenz/MaterialDrawer#1448]
The only way it updates is through the builder with `.withBadge(R.string.myString)` (or by putting a String method there) and **I wasn't able** to update it in any way _through_ `.updateBadge(drawer_item.getIdentifier(),StringHolder(myString));` . 

Just asking if it's a bug, my fault or just impossible.
Putting the item back in `.addDrawerItems()` makes it work well, but I need the item to be sticky.

____
Thank you

**Comment by mikepenz** [comment]
@Polyterative the `StickyItem`s are not part of the normal `RecyclerView` so all normal methods won't work on those, they are basically just the same views put into a `LinearLayout`

You should just change the item itself, update the badge, and then call this method:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L778

**Comment by Polyterative** [comment]
Thank you
