### ISSUE TITLE
Demo Application to Start Using MaterialDrawer

### ISSUE THREAD

**Issue by santhosh-kumar** [mikepenz/MaterialDrawer#1449]
Hello,

I am figuring out how to use this library in my project. Is there a demo app (source code) that uses this library? 

I am running into errors while following the instructions provided in the README.md.

Error:(1307) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme'.
Error:(1331) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar'.
Error:(1355) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar.TranslucentStatus'.
Error:(1379) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light'.
Error:(1402) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.ActionBar'.
Error:(1425) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.ActionBar.TranslucentStatus'.
Error:(1448) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar'.
Error:(1471) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.ActionBar'.
Error:(1494) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.ActionBar.TranslucentStatus'.
Error:(1517) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.TranslucentStatus'.
Error:(1540) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.TranslucentStatus'.
Error:(1563) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.TranslucentStatus'.
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/../../Library/Android/sdk/build-tools/23.0.2/aapt'' finished with non-zero exit value 1

FYI: I am starting with an EmptyActivity project in Android Studio.

Thanks.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/1442
