### ISSUE TITLE
Bug: Name does not get updated

### ISSUE THREAD

**Issue by sonovice** [mikepenz/MaterialDrawer#145]
Hey @mikepenz, I've encountered a bug:
```java
public void onItemClick(AdapterView<?> parent, View view, int position, long id, IDrawerItem drawerItem) {
    result.updateName("FooBar", position); // result is the actual Drawer Object
}
```
The name does not get updated this way. I have no problem doing the same thing with the badge. The basic project was just a modified version of your examples.

Offtopic:
Ebenfalls Hallo, hatte gesehen, dass du aus Österreich kommst, herzlichen Gruß zurück aus dem Nachbarland. ;-)

**Comment by mikepenz** [comment]
@sonovice i think i know what this issue is. It is linked to https://github.com/mikepenz/MaterialDrawer/issues/139 i have small problems with the fact that the list has different index with a header set or not. i'll rework this logic soon to always return the 0 based index no matter if there is a header or not

**Comment by sonovice** [comment]
@mikepenz I'm not sure wether it is the same problem. Even if I have multiple elements in the drawer and touch one in the middle of them, no element gets its name changed, neither before nor after that particular element. As I wrote, updating badges works flawlessly in my case.

**Comment by mikepenz** [comment]
@sonovice just checked the code. there is no difference how this works. I will debug it on my side. i hope i can give you some feedback soon.

**Comment by mikepenz** [comment]
@sonovice another idea. do you set the name by res with the builder? if yes the res name is still used and not the new set name (by string)

**Comment by hungdm9999** [comment]
I found the reason why Drawer.updateName is not working.
Look at detail of the method,
 public void updateName(String name, int position) {
        if (mDrawerBuilder.checkDrawerItem(position, false)) {
            IDrawerItem drawerItem = mDrawerBuilder.mDrawerItems.get(position);

            if (drawerItem instanceof Nameable) {
                ((Nameable) drawerItem).setName(name);
                ((Nameable) drawerItem).setNameRes(-1);
            }

//            mDrawerBuilder.mDrawerItems.set(position, drawerItem);
            mDrawerBuilder.mAdapter.notifyDataSetChanged();
        }
    }

after setting the name, then the drawer try to set nameRes to -1, this line causes error.
Just comment "((Nameable) drawerItem).setNameRes(-1);" on Drawer.java, line 598, then it will update your new name.
Cheer,

**Comment by mikepenz** [comment]
@hungdm9999 oh i do it in the wrong order. resetting the nameRes is required as i do not know if the user switches from resource to String. thanks for the input

**Comment by hungdm9999** [comment]
i will uncomment and set the right order too.
Thanks for great library.
