### ISSUE TITLE
'MaterialTheme'  - Resource Not found

### ISSUE THREAD

**Issue by 0ngsh** [mikepenz/MaterialDrawer#1450]
![capture](https://cloud.githubusercontent.com/assets/20467816/17456955/03ff3e60-5c06-11e6-8faf-98df5ebc0b51.PNG)

Where should I declare this resource ?

**Comment by server102** [comment]
check this link on how to fix it.
https://github.com/mikepenz/MaterialDrawer/issues/1442

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/1442

Thanks @server102 for answering

**Comment by server102** [comment]
@mikepenz you're welcome

**Comment by 0ngsh** [comment]
Thank you very much server102
