### ISSUE TITLE
Complete RTL Support

### ISSUE THREAD

**Issue by SAFatemi** [mikepenz/MaterialDrawer#1451]
Salam.
Excuse me for my bad English.
I want to use your great library in my application that support RTL completely.
I saw your example that open drawer from right, but with some issues.
Menu icons must show at right and menu label at left of layout, also some change positions for header layout items and ... 
I try to resolve these issues and send final library code in ZIP path that attached with this issue submit.
You can see result of my try that any thing is in it's place.
![untitled](https://cloud.githubusercontent.com/assets/13508325/17461347/b7c1f15c-5c9e-11e6-89b3-65804d15e982.jpg)

Complete source of library with changes in this ZIP file:

[MaterialDrawer.zip](https://github.com/mikepenz/MaterialDrawer/files/405382/MaterialDrawer.zip)

**Note 1:** these changes are applied on **v5.3.6**
**Note 2:** file "layout-ldrtl\material_drawer_item_overflow_menu_primary.xml" in the root of ZIP file, must use in example app to make submenu for menu item (look at example app in "Advanced Drawer") and not defined inside library.

I suggest you add this edits to your final release that RTL languages developer use from this library with complete and native RTL support.
Thanks again from your nice work.

**Comment by SAFatemi** [comment]
Excuse me, I sent wrong ""

[material_drawer_item_overflow_menu_primary.zip](https://github.com/mikepenz/MaterialDrawer/files/405381/material_drawer_item_overflow_menu_primary.zip)

**Comment by mikepenz** [comment]
@SAFatemi sorry I can't extract the file. 

First thanks for the changes. 

The decision not being different was made after checking the google apps which also do not change their header. 

You may want to open a pull request directly so we see the changes which were made. which makes it easier to decide what to integrate
