### ISSUE TITLE
keep list of item expanded when open the drawer ?

### ISSUE THREAD

**Issue by devabir93** [mikepenz/MaterialDrawer#1452]
i am using ExpandableDrawerItem(), can i expand the list all the time ?

**Comment by mikepenz** [comment]
@devabir93 you can expand the item after creating the drawer. 

Get the `Adapter` from the `Drawer` https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L223

and then expand the item. 
https://github.com/mikepenz/FastAdapter/blob/develop/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1320
(note that this takes the position)
