### ISSUE TITLE
notification bar color changed from default colorPrimaryDark to transparent

### ISSUE THREAD

**Issue by jitendrajswl1990** [mikepenz/MaterialDrawer#1454]
Hi,
I am using drawer on my 'HomeActivity' which is changing the color of my notification bar to transparent.

Implementation :-
1) I am loading the image from server whose URL is stored in the shared Preference.
2) i wrote logic to download the file using picasso as mentioned in your read.me in oncreate()

    DrawerImageLoader.init(new DrawerImageLoader.IDrawerImageLoader() {
            @Override
            public void set(ImageView imageView, Uri uri, Drawable placeholder) {
                imageView.setScaleType(ImageView.ScaleType.FIT_XY);
                Picasso.with(imageView.getContext()).load(uri).placeholder(placeholder).into(imageView);
            }

            @Override
            public void cancel(ImageView imageView) {
                Picasso.with(imageView.getContext()).cancelRequest(imageView);
            }

            @Override
            public Drawable placeholder(Context ctx) {
                return null;
            }

        });

3) finally i created a function createDrawer() which i am calling from onCreate() and onResume()

    private void createDrawer(){

        //drawer module
        AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.color.colorPrimary)
                .withSelectionListEnabled(false)
                .withTranslucentStatusBar(true)
                .addProfiles(
                        new ProfileDrawerItem().withName("Hi! " + firstName).withEmail(email).withIcon(user.get(UserSessionManager.KEY_IMAGE_URL))
                )
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                                                 @Override
                                                 public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                                                     Toast.makeText(HomeActivity.this, "clicked image", Toast.LENGTH_LONG).show();
                                                     Intent startCartActivity = new Intent(HomeActivity.this, ProfileActivity.class);
                                                     startActivity(startCartActivity);
                                                     return false;
                                                 }
                                             }
                )
                .build();
        result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withAccountHeader(headerResult)
                .withActionBarDrawerToggleAnimated(true)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("Home").withIcon(R.mipmap.home),
                        new DividerDrawerItem(),
                        new SecondaryDrawerItem().withName("Orders").withIcon(R.mipmap.order),
                        new SecondaryDrawerItem().withName("Payment").withIcon(R.mipmap.profile),
                        new SecondaryDrawerItem().withName("Cart").withIcon(R.mipmap.cart),
                        new SecondaryDrawerItem().withName("Refer").withIcon(R.mipmap.refer),
                        new SecondaryDrawerItem().withName("Reward").withIcon(R.mipmap.refer),
                        new SecondaryDrawerItem().withName("Logout").withIcon(R.mipmap.logout)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(AdapterView<?> parent, View view, int position, long id, IDrawerItem drawerItem) {
                        Log.e("drawer item","pos="+position+" item= "+drawerItem);
                        switch(position){
                            case 1: break;
                            case 2: Intent startPastOrderActivity = new Intent(HomeActivity.this, PastOrderActivity.class);
                                startActivity(startPastOrderActivity);
                                break;
                            case 3: Intent startProfileActivity = new Intent(HomeActivity.this, PaymentActivity.class);
                                startActivity(startProfileActivity);
                                break;
                            case 4: if (HomeActivity.orderList.size() > 0) {
                                Intent startCartActivity = new Intent(HomeActivity.this, CartActivity.class);
                                startActivity(startCartActivity);
                            } else {

                                Toast.makeText(HomeActivity.this, "Empty Cart ", Toast.LENGTH_SHORT).show();
                            }
                                break;
                            case 5: AppviralityUI.showGrowthHack(HomeActivity.this, AppviralityUI.GH.Word_of_Mouth);
                                break;
                            case 6: Intent startCartActivity = new Intent(HomeActivity.this, RewardsActivity.class);
                                startActivity(startCartActivity);
                                break;
                            case 7:  session.logoutUser();
                                //AppviralityAPI.LogOut(HomeActivity.this);
                                break;
                        }
                        return false;
                    }
                })
                .build();

    }

Note:- I am using 
    compile('com.mikepenz:materialdrawer:3.0.8@aar') {
        transitive = true
    }

![screenshot_2016-08-08-16-04-56-900](https://cloud.githubusercontent.com/assets/20902393/17477373/9c17a534-5d82-11e6-9770-a9e3035427db.jpeg)

![screenshot_2016-08-08-16-04-44-629](https://cloud.githubusercontent.com/assets/20902393/17477364/860e9d56-5d82-11e6-99d8-ce68b6073ee8.jpeg)

**Comment by mikepenz** [comment]
@jitendrajswl1990 sorry I can't support versions older than the latest version.

so what did you change that you get this exception now? updated support libraries?

**Comment by jitendrajswl1990** [comment]
I haven't updated support libraries.

I also tried to updating your library to the latest but getting errors while gradle sync.

    Error:(2461) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme'.
    Error:(2485) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar'.
    Error:(2509) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar.TranslucentStatus'.
    Error:(2533) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light'.
    Error:(2556) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.ActionBar'.
    Error:(2579) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.ActionBar.TranslucentStatus'.
    Error:(2602) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar'.
    Error:(2625) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.ActionBar'.
     Error:(2648) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.ActionBar.TranslucentStatus'.
    Error:(2671) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.DarkToolbar.TranslucentStatus'.
    Error:(2694) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.Light.TranslucentStatus'.
    Error:(2717) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.TranslucentStatus'.
    Error:Execution failed for task ':app:processDebugResources'.
    > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/admin/Android/Sdk/build-tools/23.0.3/aapt'' finished with non-zero exit value 1

**Comment by mikepenz** [comment]
@jitendrajswl1990 https://github.com/mikepenz/MaterialDrawer/issues/1442

**Comment by BobOtike** [comment]
Have a look at this: #1442

**Comment by jitendrajswl1990** [comment]
solved thanks.
