### ISSUE TITLE
I get bunch of errors, why?

### ISSUE THREAD

**Issue by sghazagh** [mikepenz/MaterialDrawer#1456]
....\app\build\intermediates\res\merged\debug\values\values.xml

Error:(1582) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme'.
Error:(1606) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar'.
Error:(1630) Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar.TranslucentStatus'.

and more ....

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/1442

**Comment by sghazagh** [comment]
Thanks it fixed the issue.
