### ISSUE TITLE
Drawer disables Translucent Status Bar

### ISSUE THREAD

**Issue by ashik94vc** [mikepenz/MaterialDrawer#1457]
I have a translucent status bar set from my fragment using 

```
Window window = getActivity().getWindow();
window.addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
```
The translucent status bar was working before adding the navigation drawer. Now the fragment view is below the status bar but the drawer is drawing behind the status bar

**Comment by mikepenz** [comment]
@ashik94vc that comes because the `DrawerLayout` has a `fitsSystemWindow`s
You might want to check the `FullScreenDrawerActivity`
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/FullscreenDrawerActivity.java

**Comment by ashik94vc** [comment]
Will try and revert today

**Comment by ashik94vc** [comment]
Yeah I tried setting it. The Drawer draws behind StatusBar but the main application view is now below status bar. Ill try building a sample app and will post the screens for further clearance on this.

**Comment by mikepenz** [comment]
@ashik94vc great. perhaps you can provide that sample app so I can test it too

**Comment by mikepenz** [comment]
you also set this:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/FullscreenDrawerActivity.java#L81
