### ISSUE TITLE
Horizontal Drawer items

### ISSUE THREAD

**Issue by raviteja786143** [mikepenz/MaterialDrawer#1458]
Hi,

This is not a issue :D
Is there is any way to add horizontal drawer items in single row to navigation drawer like this 
https://drive.google.com/open?id=0B6ni4nSlWyMGQTFycGJXX2NsdTA

**Comment by mikepenz** [comment]
@raviteja786143 looks like a single `CustomDrawerItem` which just has those buttons in. 

Please head over here on how to implement a proper CustomDrawerItem:
http://stackoverflow.com/a/32543209/325479
http://stackoverflow.com/a/32542999/325479

You might also find some answers here:
https://github.com/mikepenz/MaterialDrawer/issues?utf8=%E2%9C%93&q=CustomDrawerItem

Or you check out custom drawer item implementations here:
https://github.com/mikepenz/MaterialDrawer/tree/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems
