### ISSUE TITLE
Cannot fix the backgroundcolor of my actionbar

### ISSUE THREAD

**Issue by dupp** [mikepenz/MaterialDrawer#1460]
![14009886_1161137037311071_241606909_n](https://cloud.githubusercontent.com/assets/5398124/17555403/c3c58b8a-5f0f-11e6-88ec-146879e73762.png)

I have a little darker space in my actionbar. It is under my toolbar and i have set the sliderbackground a lighter one.. 

this is my code : 

```
drawer = new DrawerBuilder()    //https://github.com/mikepenz/MaterialDrawer
                .withActivity(activity)
                .withToolbar(toolbar)
                .withSliderBackgroundColor(Color.parseColor("#" + Customer.getInstance().settings.customerColor))
                .withRootView(R.id.drawer_layout)
                .withDrawerLayout(R.layout.material_drawer_fits_not)
                .withTranslucentStatusBar(true)
                .withActionBarDrawerToggle(true)
                .withActionBarDrawerToggleAnimated(true)
                .withSelectedItem(-1)
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        drawerClickListener(view, position);
                        return false;
                    }
                });
        addMenuItems();
        drawer.build();
    } 
```

I did not find any solution for this.. can you please help me ?

**Comment by mikepenz** [comment]
As you have your `Drawer` below the `Toolbar` please check out the following sample:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java#L34

**Comment by dupp** [comment]
![13957388_1161173540640754_2089021694_n](https://cloud.githubusercontent.com/assets/5398124/17557027/e316d934-5f15-11e6-89fa-6513ba9dfc42.png)

Yes, I have my drawer below the Toolbar.

Your way works much better but there is always the darker color.. just transparent. Do you have a solution for this problem too?

I changed my code in : 

        drawer = new DrawerBuilder()    //https://github.com/mikepenz/MaterialDrawer
                .withActivity(activity)
                .withToolbar(toolbar)
                .withDisplayBelowStatusBar(false)
                .withSliderBackgroundColor(Color.parseColor("#" + Customer.getInstance().settings.customerColor))
                .withRootView(R.id.drawer_layout)
                .withDrawerLayout(R.layout.material_drawer_fits_not)
                .withTranslucentStatusBar(true)
                .withActionBarDrawerToggle(true)
                .withActionBarDrawerToggleAnimated(true)
                .withSelectedItem(-1)
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        drawerClickListener(view, position);
                        return false;
                    }
                });
        addMenuItems();
        drawer.build();
    }

**Comment by mikepenz** [comment]
why do you have
`.withDrawerLayout(R.layout.material_drawer_fits_not)` ?

**Comment by mikepenz** [comment]
and you really need this:
`.withTranslucentStatusBar(true)`?

**Comment by dupp** [comment]
![13883730_1161733283918113_2056093221_n](https://cloud.githubusercontent.com/assets/5398124/17581455/44caa4f4-5fa6-11e6-863b-fe4b723456b7.png)
![13942521_1161733287251446_865958056_n](https://cloud.githubusercontent.com/assets/5398124/17581456/44cfa2e2-5fa6-11e6-91d6-cc14757b5549.png)



Thats when I comment out:  ".withDrawerLayout(R.layout.material_drawer_fits_not)" 

After that there is a red space in my ShopWebView.. it is as big as the space in the actionbar; just another color. 


My layout code : 
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/material_drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />

**Comment by mikepenz** [comment]
@dupp yeah it seems like the `fitsSystemWindows` flag from android is fooling us here. you might also have to set it on the `WebView` or the container layout for the webview, to prevent this behavior. 

But you still have the shadow on top. 

As you can see in the sample neither of the above happens. How is your general layout structured?


That's the one from the sample:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/activity_sample_custom_container_dark_toolbar.xml#L5

**Comment by dupp** [comment]
Thats my layout code : 

<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context=".ShopWebView">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <android.support.design.widget.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:theme="@style/AppTheme">

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="?attr/colorPrimary"
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light"/>

        </android.support.design.widget.AppBarLayout>

        <FrameLayout
            android:id="@+id/drawer_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <include layout="@layout/activity_embedded_shopwebview"/>

        </FrameLayout>
    </LinearLayout>

</android.support.design.widget.CoordinatorLayout>

**Comment by mikepenz** [comment]
@dupp I have the bad feeling that it is related to the `CoordinatorLayout` and `fitsSystemWindow`s playing together in a bad way. 

As of v5 of the `MaterialDrawer` all paddings etc is done via the android integrated feature via the `fitsSystemWindow`s flag. So the shadow or the padding you see is coming from it.

**Comment by dupp** [comment]
I think if found the problem. 

It is in my activity_embedded_shopwebvie layout.

<RelativeLayout android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:tools="http://schemas.android.com/tools"
    tools:context=".ShopWebView"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:fitsSystemWindows="true"
    tools:showIn="@layout/activity_instagram">

    <WebView
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:id="@+id/shopWV"
        android:layout_centerHorizontal="true"
        android:focusable="false"
        android:layout_alignParentTop="true" />

</RelativeLayout>



I set the layout_alignTarentTop = true.. and I included it in my ShopWebLayout. 
But I cannot fix it.

**Comment by mikepenz** [comment]
activity_embedded_shopwebview try to set the `fitsSystemWindows` flag to false. also try the same on the `coordinatorlayout`

**Comment by mikepenz** [comment]
@dupp any update?

**Comment by mikepenz** [comment]
I will close this for the time being. Will reopen as soon as new infos are added. Thank you

**Comment by dupp** [comment]
Oh sorry, i did not saw you reply an answer. 
Yeah I am German. 

It was a little tricky because I linked two layouts. So I have to change fitsSystemWindows in both to get a fluency surface. 

Your answer helps me very well. Thank you so much.
