### ISSUE TITLE
minidrawer default selected item

### ISSUE THREAD

**Issue by theAliAkhgar** [mikepenz/MaterialDrawer#1461]
I am using mini drawer but i cant set a default selected item for it, i use                         .withSelectedItemByPosition(1)
it selects the item, but it wont fire the OnClickListener so the Fragment is not loaded, help me please.

**Comment by mikepenz** [comment]
@theAliAkhgar you should enable the initial event fireing:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L782
