### ISSUE TITLE
Change Hamburger-Icon to custom icon

### ISSUE THREAD

**Issue by rafanereslima** [mikepenz/MaterialDrawer#1462]
![captura de tela 2016-08-10 as 16 45 19](https://cloud.githubusercontent.com/assets/11350616/17568398/fd13a89a-5f19-11e6-8ae5-44b6bb2eb6d0.png)

I'm trying to customize the Hamburger-Icon more 'm not getting .
How do I change this icon for a custom icon ?

**Comment by mikepenz** [comment]
@rafanereslima by default I use the `ActionbarDrawerToggle` which can't have a different icon. if you want a different icon you will have to handle the opening closing on your own. just use the corresponding methods provided by the `Drawer` if you don't want the `ActionbarDrawerToggle` simply don't provide the `Toolbar`. 

About setting a custom icon. Please visit StackoverFlow as this is not MaterialDrawer specific, but rather general android.

**Comment by rafanereslima** [comment]
Ok Thanks!
