### ISSUE TITLE
How I can change the color of "hambuger" in CollapsingToolbarLayout?

### ISSUE THREAD

**Issue by AlexanderArtemov** [mikepenz/MaterialDrawer#1463]
I can change the color of title with runtime methods:

> .setCollapsedTitleTextColor 
> .setExpandedTitleColor

But your material drawer is black. How I can change drawer's color from xml or runtime (xml better).

Screenshot: https://pp.vk.me/c631624/v631624287/44115/GSsk13tmmWM.jpg
Regards,
Alexander

**Comment by mikepenz** [comment]
The hamburger icon is nothing coming from the `MaterialDrawer`. The MaterialDrawer just sets the `ActionbarDrawerToggle` for you which is the default component for this. 

You will have to provide a proper theme on the toolbar for it to color.
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/activity_sample_dark_toolbar.xml#L13

You can find some more answers on this on `StackOverFlow`
