### ISSUE TITLE
Space for translucent navigation bar on device with hardware buttons

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/MaterialDrawer#1464]
I'm using following setup:

	DrawerBuilder drawerBuilderLeft = new DrawerBuilder()
			.withActivity(getActivity())
			.withDrawerLayout(R.layout.fixed_drawer)
			.withFullscreen(true)
			.withAccountHeader(mAccountHeader)
			.withSelectedItem(selectedIdentifier)
			.addDrawerItems(items.toArray(new IDrawerItem[items.size()]))
			.withOnDrawerItemClickListener(this)
			.withOnDrawerListener(new Drawer.OnDrawerListener()
			{
				// custom animationsss
			});

	if (PrefUtil.useTransparentNavBar(getActivity()))
		drawerBuilderLeft.withTranslucentNavigationBarProgrammatically(true);
	ThemeManager.get().themeDrawerBuilder(drawerBuilderLeft); // this only sets a background!!!
	mDrawerLeft = drawerBuilderLeft.build();
	mDrawerLeft.getDrawerLayout().setFitsSystemWindows(false);

**Problem**

On my device (Samsung S6 Edge), I see a space under the header items. This should not be present on this device. Weirdly, one single change in the code solves the problem:

If I change

    .withAccountHeader(mAccountHeader)`

to

    .withAccountHeader(mAccountHeader, true)

the Problem is gone.

I anyway want a sticky header, but still, there seems to be a problem somewhere. Am I overseeing something?

I'm using the newest version (v5.4.0)...

**Comment by mikepenz** [comment]
@MFlisar the space you see has exact the height of the `StatusBar`? It might be the same as discussed in a different ticket. And see what I have written there: https://github.com/mikepenz/MaterialDrawer/issues/1460#issuecomment-239096577

The `MaterialDrawer` does not set any paddings for those things. Everything comes from the `fitsSystemWindow`s flag

**Comment by MFlisar** [comment]
I'll check that... But the thing with the padding seems to be wrong, isn't it? We talked about that already once and back then, you said, you set the padding in the recycler view.

I checked the code and the current version still does this:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1616

**Comment by mikepenz** [comment]
Ah you mean this one. May you can add a screenshot?

You can also set `systemUiHidden` so no paddings are applied at all.

**Comment by MFlisar** [comment]
`.withSystemUIHidden(true)` solves it, but then I have to check, if the device has hardware buttons or software buttons myself to set `withSystemUIHidden` correctly... I thought, the lines (1610 - 1616) in https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java should handle this check...

Screenshot with non sticky header:

![screenshot_20160811-102438](https://cloud.githubusercontent.com/assets/2437726/17582832/feedf5e6-5fad-11e6-8b2a-f005047d7428.png)

**Comment by mikepenz** [comment]
@MFlisar they do in general. 

Why do you need to have the `withFullscreen` at all? wouldn't it be enough if you just have the translucent navigationbar?

**Comment by MFlisar** [comment]
Actually, the drawer IS fullscreen, my app as well... Removing `withFullscreen` solves the problem.

Still, I don't get the reason for `withFullscreen` then...

**Comment by mikepenz** [comment]
@MFlisar in some cases it is needed for some apps, especially as you see in the `FullScreenActivity` sample. But for normal translucent navigationbar etc is is not needed.
