### ISSUE TITLE
How I can remove/change margin bottom/top for first row?

### ISSUE THREAD

**Issue by AlexanderArtemov** [mikepenz/MaterialDrawer#1465]
I want to remove/change margin bottom and top for first line because it's link to Main Activity of my app. How I can do this?
Screenshot: https://pp.vk.me/c631624/v631624909/42eaa/p2__04ifReY.jpg (I'm going to add icon later)
Regards,
Alexander

**Comment by mikepenz** [comment]
@AlexanderArtemov the margins are the defaults as defined in the `Material Design Guidelines`

Perhaps the following is also already helping you: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L298

and also remember that the divider item you use also has small margins

You can create a new `CustomDrawerItem` for your requirement.
