### ISSUE TITLE
Sizable drawer ..

### ISSUE THREAD

**Issue by SAFatemi** [mikepenz/MaterialDrawer#1466]
Salam.
I think its good to add feature that user can change width of drawer by touch edge of drawer and drag to left and right.
What you think about this idea?
Can you implement it?

**Comment by mikepenz** [comment]
@SAFatemi no this is not possible as swiping left / right is already the closing / opening gesture. 
If you need this for your application you may be able to implement your own `DrawerLayout` by extending the original one. which you can then provide to the `MaterialDrawer`
