### ISSUE TITLE
MaterialTheme can't be found when using version 5.4.0

### ISSUE THREAD

**Issue by jahirfiquitiva** [mikepenz/MaterialDrawer#1467]
Hi Mike

I recently was going to update MaterialDrawer to 5.4.0, and started getting these errors in android studio

![material_drawer_error](https://cloud.githubusercontent.com/assets/10360816/17599555/51adb930-5fc5-11e6-8c6a-549cc959d3d1.png)

It doesn't happens on previous versions like 5.3.6 and older.

I already updated SDK to 24, and the Google libs too.

Thanks

**Comment by mikepenz** [comment]
please try it again. should work already

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/1442

**Comment by jahirfiquitiva** [comment]
Just tried and it's still happening

**Comment by mikepenz** [comment]
you might need to clear your gradle caches as noted in the other issue

**Comment by jahirfiquitiva** [comment]
I tried "Clean project" option. Deleted build folder. And "Invalidate caches / Restart" option too.

Still not working.
