### ISSUE TITLE
Failed to resole compile: 'com.mikepenz:fontawesome-typeface:x.y.z@aar'

### ISSUE THREAD

**Issue by AghaAsadKhan** [mikepenz/MaterialDrawer#1468]
Failed to resole compile: 'com.mikepenz:fontawesome-typeface:x.y.z@aar'

**Comment by mikepenz** [comment]
`x.y.z` is just a placeholder for a specific version. Either look on mavenCentral which verison is currently the newest, or you head over here: 
https://github.com/mikepenz/Android-Iconics

**Comment by AghaAsadKhan** [comment]
Thank You @mikepenz ! it is done! and sorry for asking this stupid question. but it was really disturbed me :( Thank You Again...
