### ISSUE TITLE
Close drawer on back button press

### ISSUE THREAD

**Issue by ProfPh** [mikepenz/MaterialDrawer#1469]
Hello,

Is there a way of handling back button press inside of the Drawer instead of:

```
    @Override
    public void onBackPressed() {
        if (drawer.isDrawerOpen()) {
            drawer.closeDrawer();
        } else {
            super.onBackPressed();
        }
    }
```

**Comment by mikepenz** [comment]
@ProfPh no it's not because the `onBackPressed` event is not forwarded to the drawer. In general you need those lines just once per app :D
