### ISSUE TITLE
Bad display

### ISSUE THREAD

**Issue by Java-Help** [mikepenz/MaterialDrawer#147]
When I turn the screen Drawer displayed as bad as before. And take away , please blackout Toolbar, when the Drawer is displayed below the Toolbar. It looks very ugly and introduces the user to a standstill.
![jlaco2axf6q](https://cloud.githubusercontent.com/assets/10331350/6800943/61889dd6-d234-11e4-9e02-ff09f8cdc611.jpg)

**Comment by mikepenz** [comment]
@Java-Help do you re-create the drawer? I think this is caused if you have disabled the recreation of the ui with the onConfigChange overwrite?

**Comment by Java-Help** [comment]
No, I'm not disable recreation of activity.

**Comment by Java-Help** [comment]
You follow my request about the blackout toolbar ?

**Comment by mikepenz** [comment]
@Java-Help i am not sure what you mean with the "blackout toolbar"

so the activity is recreated each time. and the drawer also? I just tried the sample on my device and it works. (this device had the same issue as shown in the screenshot with the v 2.5.5 too)

**Comment by Java-Help** [comment]
Please make sure that highlighted red rectangle area is not obscured 
![jlaco2axf6q](https://cloud.githubusercontent.com/assets/10331350/6813583/8805d14c-d287-11e4-9f7d-9ac273e52309.jpg)

**Comment by Java-Help** [comment]
![jlaco2axf6q](https://cloud.githubusercontent.com/assets/10331350/6813591/939834c8-d287-11e4-9f59-c511c30b2366.jpg)

**Comment by mikepenz** [comment]
@Java-Help it is only possible to deactivate the whole black shadow. This is a limitation of the DrawerLayout. 

removing the shadow is done by calling the following: 
```java
        result.getDrawerLayout().setScrimColor(Color.TRANSPARENT);
```

Oh and with the newest screenshot i see your issue with the toolbar :D it seems your toolbar is created wrong. see the sample for a correct implementation of the layout.
