### ISSUE TITLE
Cannot Update SwitcherDrawerIcon

### ISSUE THREAD

**Issue by marcodebarbosa** [mikepenz/MaterialDrawer#1471]
Hello,

I've been using this lib recently, but i am having problems updating the status of the SwitcherDrawerIcon.

I've been using this code, to update: 
mNavigationDrawer.updateItem(switchDrawerItem.withChecked(isChecked));

And it basically doesn't do pretty anything. I have also tried to create a new Switch, delete the previous one, and place this new one but it does exactly the same behavior. 

Am i doing something wrong?

**Comment by mikepenz** [comment]
@marcodebarbosa does your item have an identifier? Do you call the above code on the main thread?

**Comment by mikepenz** [comment]
Please provide additional details
