### ISSUE TITLE
Any way we can set selected item background from a drawable? 

### ISSUE THREAD

**Issue by n1schal** [mikepenz/MaterialDrawer#1472]

**Comment by mikepenz** [comment]
@n1schal the default items do not allow you to set a drawable as background. 

You will have to implement a `CustomDrawerItem` which allows you to do this. 

In the sample app I have already implemented an item which does quite a similar thing. 

Check it out here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomPrimaryDrawerItem.java

**Comment by n1schal** [comment]
thanks! hadn't taken a good look at the sample :3

**Comment by Shruti6293** [comment]
@mikepenz can we add drawable background for `Minidrawer `selected item ?

**Comment by mikepenz** [comment]
@Shruti6293 I remember there was an issue about having some custom `MiniDrawerItems` it is possible yes. But will require some custom handling, if you do not want to go with the default selected background
