### ISSUE TITLE
Remove sub item by identifier

### ISSUE THREAD

**Issue by kadhim-alawi** [mikepenz/MaterialDrawer#1474]
I am trying to remove a sub item of ExpandableDrawerItem using removeItem(identifier) function, but the function is removing a main item instead (based on the position of the sub item). Any workaround? Since I am using Java 7 and cannot use the .removeIf(predicate) function?

**Comment by mikepenz** [comment]
@kadhim-alawi you can't remove an item from the list using the identifier as it does only exist in the sub hirachy, which is linked to the specific item. You will have to know the sub items list of this item, and remove it there (maybe via position?)

**Comment by kadhim-alawi** [comment]
@mikepenz ok solved it by checking the identifier with the for loop, but now the list is not refreshing when it is already expanded, how can I fix this?

**Comment by mikepenz** [comment]
Please read this: https://github.com/mikepenz/MaterialDrawer/issues/1260#issuecomment-218735178
