### ISSUE TITLE
Mini drawer with sticky header

### ISSUE THREAD

**Issue by gtgray** [mikepenz/MaterialDrawer#1476]
Hello, Mike!

Is there a way to make header of mini drawer to become sticky as it is possible for main drawer by method: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L473

**Comment by mikepenz** [comment]
@gtgray no this is not possible. You can only have flexible items there. With some custom handling it might be possible but not out of the box.

**Comment by mikepenz** [comment]
So you can get the `RecyclerView` of the `MiniDrawer` and from that you can get it's parent. Which is a `LinearLayout` into which you can add the "sticky" view as first child. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L207

**Comment by gtgray** [comment]
Mike,
I followed the instruction above and achieved desired result.
Thanks
