### ISSUE TITLE
Using edittext 

### ISSUE THREAD

**Issue by azizarc88** [mikepenz/MaterialDrawer#1479]
Can i make an item edittext using your materialdrawer...?

**Comment by mikepenz** [comment]
@azizarc88 you can create any items you want, and add them the the `MaterialDrawer` . 

Read more here: https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md

**Comment by azizarc88** [comment]
but how, i still get stuck to doing this... :/

**Comment by mikepenz** [comment]
You create a `CustomDrawerItem` which has an `EditText`. 

You will create the items layout,
You create the CustomDrawerItem as shown above
You provide it to the drawer.

**Comment by azizarc88** [comment]
no, i mean the code, i'm still new to android...
please... :/

**Comment by mikepenz** [comment]
Sorry I can't help with this. Please refer to normal sites like StackOverflow etc. to get more knowhow in android, or programming.
