### ISSUE TITLE
Is it possible to inhibit the Drawer from closing?

### ISSUE THREAD

**Issue by ivangag** [mikepenz/MaterialDrawer#148]
Hi,
sorry but i wasn't able to found a response by myself...
Is there the way to disable/inhibit the Drawer from closing when a determined item is clicked? 
Thanks.

**Comment by Rainer-Lang** [comment]
Why?

**Comment by ivangag** [comment]
Why not? ;-)

Anyway... for instance to have an AppInfo showing version info 
or another item used to logout and when clicked showing a dialog without closing drawer, in order to be able to go back having drawer still opening...

![immagine](https://cloud.githubusercontent.com/assets/4865385/6807238/93ab4638-d24d-11e4-973b-9ca9670861b7.png)

**Comment by mikepenz** [comment]
I think you were searching for:
`withCloseOnClick(false)`

If you only want to disable this for specific elements see the methods like `withCheckable(false)` on a specific list item

**Comment by ivangag** [comment]
@mikepenz , thanks for the suggestion but i was looking for a more specific action: avoid to close the drawer if a particular item is clicked, in short a function with a mixed behavior of both 
```withCloseOnClick(false)``` and ```withCheckable(false)```, let me say **.withCloseDrawerOnClick(boolean closeDrawerOnClick)**

For instance we could have:
```
mDrawer.addDrawerItems(new PrimaryDescriptionDrawerItem()
....
...
.withCheckable(false)
.withCloseDrawerOnClick(false) => drawer won't be closed if this item is clicked
```
Thanks in advance

**Comment by mikepenz** [comment]
i think you can get this by setting the drawer to don't close onClick but in the listener method for the onClick event you call result.closeDrawer() for all items but the single one.

**Comment by ivangag** [comment]
it was  exactly workaround  what i was thinking  but it seemed to me more clean having an isolated method for the single item.. anyway thanks again
