### ISSUE TITLE
How to dynamically populate the value in "withName("dynamicName")"

### ISSUE THREAD

**Issue by bapisth** [mikepenz/MaterialDrawer#1480]
I want to populate the profile name dynamically.

**Comment by mikepenz** [comment]
@bapisth just define the text as normal. And if it changes, update the text in the `ProfileDrawerItem` and notify the `AccountHeader` about the update. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L244
