### ISSUE TITLE
condition for badge

### ISSUE THREAD

**Issue by bamdad01** [mikepenz/MaterialDrawer#1481]
Thanks for the library.
Is it possible to display badge just in a special condition ? For example when there are new blog posts .
I think there should be something like set visibility VISIBLE ...

**Comment by mikepenz** [comment]
@bamdad01 this is not necessary, as the badge will only be displyed when you set a text. And you can always remove it again by updating this item and setting a `null` text. (don't forget to notify the `Drawer` about the changed item
