### ISSUE TITLE
Selection Doesn't Update on Screen Change

### ISSUE THREAD

**Issue by acosti** [mikepenz/MaterialDrawer#1483]
Hey mike,

I'm not sure if this is a valid question because it might have to be managed by me. I haven't been able to find anything here so I'll ask anyway with the risk of being silly.

The problem I'm facing is that my drawer doesn't seem to save the state it's at.
For instance, on rotating the screen from portrait to landscape, the selected / highlighted component that appeared perfectly fine in portrait, would no longer appear once in landscape.

I am creating the drawer once, in the activity's onCreate, and passing to it the activity's savedInstanceState.

Is there anything I'm doing wrong?
Is this supposed to be managed by me?

Thanks
A Costi

**Comment by mikepenz** [comment]
@acosti do you also save the `InstanceState`:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L234 ?

**Comment by acosti** [comment]
yeah I think I'm doing the same. 
this is what I got in my activity:
1st bit is onCreate
2nd bit is initialization of the drawer
3rd bit is the onSaveInstanceState


```java
@Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        initDrawer(savedInstanceState);
    }
```

```java
private void initDrawer(Bundle savedInstanceState) {
        mDrawer = new DrawerBuilder()
                .withActivity(activity)
                .withToolbar(toolbar)
                .withSavedInstance(instanceState)
                .withAccountHeader(getAccountHeader(activity))
                .withDrawerItems(getMenuItems())
                .withFooter(getFooter(activity))
                .withFooterDivider(false)
                .build();
    }
```

```java
@Override
    public void onSaveInstanceState(Bundle outState, PersistableBundle outPersistentState) {
        outState = drawerWrapper.mDrawer.saveInstanceState(outState);

        outState = drawerWrapper.mHeader.saveInstanceState(outState);
        super.onSaveInstanceState(outState);
    }
```

**Comment by mikepenz** [comment]
@acosti your `menuItems` have an identifier set? 
In general it should be fine. You can try it in the sample app, which does not have this problem.

**Comment by acosti** [comment]
@mikepenz nope, they don't have an identifier set. don't know what that it.
I'll look into it and update. thanks

**Comment by mikepenz** [comment]
As shown in the readme:
https://github.com/mikepenz/MaterialDrawer#add-items-and-adding-some-functionality

```java
.withIdentifier(1)
```

**Comment by acosti** [comment]
hmm I can't tell what I'm doing wrong.

I've added a unique Id for each item using `.withIdentifier()`,
as well as added to the drawer initialization - `.withHasStableIds(true)` ...
but it doesn't seem to work.

If I select an item on portrait, it would deselect when changed to landscape.

**Comment by mikepenz** [comment]
@acosti your header also gets the `instanceState`? Just to be sure. You use the latest version too right?

Maybe you can provide a small sample project to showcase your issue, and I can debug it.

**Comment by acosti** [comment]
yeah I'm passing it to header as well. odd.

odds are that I'm doing something foolish.
let me debug if for a few and compare to all your samples before I give you anything to waste your time with. many thanks man. 

will keep this updated soon.

**Comment by mikepenz** [comment]
@acosti thank you

**Comment by acosti** [comment]
@mikepenz ok it works. my bad. :)

I was using the incorrect overload for `onSaveInstanceState.

in the activity implementing the drawer, I used the overload:
`public void onSaveInstanceState(Bundle outState, PersistableBundle outPersistentState)

instead, I should have used:
`public void onSaveInstanceState(Bundle outState)`

that's what happens when you blindly follow stuff without understanding first.

thanks for your time @mikepenz, you're a lifesaver. :+1:

**Comment by mikepenz** [comment]
@acosti ah ok :D great that you found the issue.
