### ISSUE TITLE
Can i open the drawer from rigth side ? is there any option ?

### ISSUE THREAD

**Issue by abumoallim** [mikepenz/MaterialDrawer#1484]

**Comment by mikepenz** [comment]
@abumoallim you can set the `Gravity` for the drawer. As you can do with a normal `DrawerLayout` too. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L445

**Comment by abumoallim** [comment]
Thanks Sir
