### ISSUE TITLE
Adding a SecondaryDrawerItem later

### ISSUE THREAD

**Issue by postacik** [mikepenz/MaterialDrawer#1485]
I have a list of secondary drawer items:

`private List<IDrawerItem> mBookmarkItems;`

I add these items to a primary drawer item during initialization:

```
mAyraclarGroup = new ExpandableDrawerItem().withName("Ayraçlar").withIcon(Typeicons.Icon.typ_bookmark).withIdentifier(1005).withSelectable(true);
mAyraclarGroup.withSubItems(mBookmarkItems);
```

What is the best way to add new items to the primary drawer item later?

I tried adding new items to "mBookmarkItems" but the new items are displayed in the drawer only when I collapse and expand the primary drawer item.

**Comment by mikepenz** [comment]
@postacik if you want to add more subitems. the best is that you retrive the parent item. And then just add the new subItem to the list of subItems. 

Don't forget that you have to notify the `Adapter` about the additional subitem:
https://github.com/mikepenz/MaterialDrawer/issues/1260#issuecomment-218735178

**Comment by postacik** [comment]
My parent item is mAyraclarGroup.

I add the new item and notify the adapter using the following code:

```
mAyraclarGroup.withSubItems(newItem);
mDrawer.updateItem(mAyraclarGroup);

```
mAyraclarGroup is collapsed after executing this code but the item is added to the end of the sub items.

However, this has an awkward side effect. The next primary drawer item below mAyraclarGroup disappears.

Perhaps I'm doing something wrong. Any idea?

**Comment by mikepenz** [comment]
@postacik so it is important that your `mAyraclarGroup` has an identifier defined. 

Then when you wan to add a new subItem just get the previous list and add the new one:
`mAyraclarGroup.getSubItems().add(newItem)`

After this call the method as describe din my first answer https://github.com/mikepenz/MaterialDrawer/issues/1260#issuecomment-218735178:

`Drawer.getAdapter().notifyAdapterSubItemsChanged(int globalPosition)`

you can't use the `udateItem` function here, as subitems work a bit different

**Comment by postacik** [comment]
Thanks but something is still awkward.
mAyraclarGroup is the first item in the drawer. 
After it there are several other items.
Here is my code. 

```
                        SecondaryDrawerItem newItem = new SecondaryDrawerItem();
                        newItem.withName(newName)
                                .withLevel(2)
                                .withIcon(Typeicons.Icon.typ_pin_outline)
                                .withIdentifier(3000 + itemIndex);
                        mAyraclarGroup.getSubItems().add(newItem);
                        mDrawer.getAdapter().notifyAdapterSubItemsChanged(0);

```

After I execute these lines, the new item is added but the first primary item after mAyraclarGroup disappears.

What am I doing wrong?

**Comment by postacik** [comment]
Hi,
Do you have any suggestions for my problem? What looks wrong in my code?

**Comment by mikepenz** [comment]
@postacik do you have a header? if yes the notify method has to be called on index (1) (global index is needed -> header is counted as 1 )

**Comment by postacik** [comment]
Yes, I have a header.

When I use the global index parameter as "1", it works without any problems.

Thank you very much for your help and this beautiful library.

**Comment by mikepenz** [comment]
Sorry for the late answer. Overlooked the question. 

Great that it works now :)
