### ISSUE TITLE
App Defined Styles

### ISSUE THREAD

**Issue by Onwa1kenobi** [mikepenz/MaterialDrawer#1486]
From the android app, there are some defined styles like the CrossFadeDrawerLayout, MiniDrawer, etc.
How do we implement something like that? For me, I want to implement the CrossFadeDrawer.

**Comment by mikepenz** [comment]
@Onwa1kenobi just follow the sample app's implementation. 

For the `CrossfadeDrawer` you need the additional libarary:
https://github.com/mikepenz/CrossfadeDrawerLayout

**Comment by Onwa1kenobi** [comment]
Thank you so much
