### ISSUE TITLE
Accounts list grows with subItems on select profile from list

### ISSUE THREAD

**Issue by alorma** [mikepenz/MaterialDrawer#1488]
![device-2016-08-20-230615](https://cloud.githubusercontent.com/assets/887462/17833883/bb907902-672a-11e6-98ae-bdddabc3344a.png)

When i have more than one profile set into `AccountHeader` and each of those profiles contains subItems, those items are shown in the account list, when i select account from the list (not happens when select from header)

**Comment by mikepenz** [comment]
Do you have expandable `ProfileDrawerItem`?

**Comment by mikepenz** [comment]
@alorma please check out the following. Should solve your problem. 
https://github.com/mikepenz/MaterialDrawer/blob/feature/%231488/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java

What I do. I change the main items list when a profile is selected. You can see this by the added / updated test items
