### ISSUE TITLE
[Feature] IDrawerImageLoader should contain name field

### ISSUE THREAD

**Issue by alorma** [mikepenz/MaterialDrawer#1489]
Now the imageloader contains only the URI to be loaded:

```java
public interface IDrawerImageLoader {
        void set(ImageView imageView, Uri uri, Drawable placeholder);

        void cancel(ImageView imageView);

        Drawable placeholder(Context ctx);

        /**
         * @param ctx
         * @param tag current possible tags: "profile", "profileDrawerItem", "accountHeader"
         * @return
         */
        Drawable placeholder(Context ctx, String tag);
    }
```

But i would be great if we can get the name, or even better, the `IDrawerItem` that is going to be loaded, so we can generate a better placeholders:

```java
public interface IDrawerImageLoader {
        void set(ImageView imageView, IDrawerItem drawerItem, Drawable placeholder);

        void cancel(ImageView imageView);

        Drawable placeholder(Context ctx);

        /**
         * @param ctx
         * @param tag current possible tags: "profile", "profileDrawerItem", "accountHeader"
         * @return
         */
        Drawable placeholder(Context ctx, String tag,  IDrawerItem drawerItem);
    }
```

What do you think about it?

**Comment by mikepenz** [comment]
@alorma this is a good idea. I will have a look into it. Even if it may be a breaking change.

**Comment by mikepenz** [comment]
@alorma I just checked the code. It would be a huge change to bring in this change, as currently all apply calls are done via the `ImageHolder` from the `Materialize` library which does not allow this. And then all the current usages have to be touched. 

Would it be already enough if I provide the `tag` in the set method too. (Similar as in the `placeholder` method)?

**Comment by alorma** [comment]
mmmm, yes i guess! (but tag should be name, can be done?)

**Comment by mikepenz** [comment]
the tag will be one of those:  "profile", "profileDrawerItem", "accountHeader"

**Comment by alorma** [comment]
mmmm, i can't generate a drawable from that :(

**Comment by mikepenz** [comment]
You generate a drawable? Why do you do that at loading time?

**Comment by mikepenz** [comment]
Sorry closed by commit.

**Comment by mikepenz** [comment]
I think can be closed as discussed on telegram
