### ISSUE TITLE
Disable item selection completely

### ISSUE THREAD

**Issue by paolomcgrath** [mikepenz/MaterialDrawer#149]
Hi @mikepenz ,

I can disable the default selected item with the following:
.withSelectedItem(-1)

And I can override the colors for the selected items with the following:
    <color name="material_drawer_selected"></color>
    <color name="material_drawer_selected_text"></color>

However, I can't seem to find a way to disable the item selection completely. Is this already available, or could it be included as an enhancement?
At present, if I select an item, then transition to a new activity, the item stays highlighted once I return to the main activity.

Let me know if I've missed something! :)

**Comment by mikepenz** [comment]
The method is called `withCheckable(false)` on a specific item. this will set the item that this one is not selected. or activated. please see the sample application for more infos about this method

**Comment by paolomcgrath** [comment]
Great, I must have missed that. Thank you!

**Comment by mikepenz** [comment]
@paolomcgrath no problem ;)
