### ISSUE TITLE
WithSelectedIcon not set when selected

### ISSUE THREAD

**Issue by abumoallim** [mikepenz/MaterialDrawer#1490]

**Comment by mikepenz** [comment]
@abumoallim can you please add some more details. How to you create the `DrawerItem` any other code which may could prevent this? Do you have tinting enabled. Or anything else?

**Comment by mikepenz** [comment]
Just tried this another time in the sample app this works

**Comment by abumoallim** [comment]
![see](https://cloud.githubusercontent.com/assets/14852095/17868102/ef798fc8-68ca-11e6-8aad-f08c575aff3b.png)
![see2](https://cloud.githubusercontent.com/assets/14852095/17868103/f0e04672-68ca-11e6-8e85-92e84837db64.png)

**Comment by abumoallim** [comment]
new PrimaryDrawerItem().withName("Admin").withTextColor(getResources().getColor(R.color.color3)).withSelectedIcon(getResources().getDrawable(R.drawable.admin)).withIdentifier(3).withSelectable(true).withSelectedTextColor(getResources().getColor(R.color.md_white_1000)).withSelectedColor(getResources().getColor(R.color.colorPrimary)).withIcon(getResources().getDrawable(R.drawable.adminfilled)),

**Comment by abumoallim** [comment]
new PrimaryDrawerItem().withName("Admin").withTextColor(getResources().getColor(R.color.color3))
.withSelectedIcon(getResources().getDrawable(R.drawable.admin))
.withIdentifier(3).withSelectable(true)
.withSelectedTextColor(getResources().getColor(R.color.md_white_1000))
withSelectedColor(getResources().getColor(R.color.colorPrimary))
.withIcon(getResources().getDrawable(R.drawable.adminfilled)),

**Comment by mikepenz** [comment]
@abumoallim but I see that the icon is correclty changed in your screenshot. The color is not changing. This is because you don't have `iconTinting` enabled. Nor do you define the `withSelectedIconColor` or the `withIconColor`. 

So you should enable
```
.withIconTintingEnabled(true)
```

and also define the colors you want to have by default or selected
