### ISSUE TITLE
Dawer gravity change issue

### ISSUE THREAD

**Issue by SarkenJ** [mikepenz/MaterialDrawer#1491]
Hi,
In my application I give the user the choice to change the drawer gravity of the drawer from left to right and vice-versa. When a gravity change is made then I notice that the drawer is now swipe-able from both left and right. In my case, to changing the gravity, I create a new drawer, I tried updating the old one but it doesn't work. My first question is how can one remove the old drawer object? Second, how can one update the drawer object with a new gravity value? Thanks

**Comment by mikepenz** [comment]
@SarkenJ the problem is when you create a new `Drawer` you will just end up with having 2 `DrawerLayouts` in your activity. 

You have to keep in mind that the `MaterialDrawer` is "just" a wrapper around the `DrawerLayout` and provides you some easy to use APIs which allow you to achieve a `Drawer` following the material design guidelines. 

So for your requirement. You just need to keep in mind that everything is a `DrawerLayout` with all the default behaviors behind. So you only have to get the `reference` to the `Slider` view which holds the `drawer` which you can slide out. 
You can easily to this by calling `Drawer.getSlider()` as the `DrawerLayout` manages the gravity just by this (the sliders) gravity. Just update the gravity for the `Slider` view and you should be good to go.

**Comment by Pareshoct7** [comment]
@mikepenz Sorry for the stupid question but can you write the syntax to update Slider gravity ? please give me example if possible. thanks

**Comment by mikepenz** [comment]
`Drawer.getSlider().setGravity()`

**Comment by Pareshoct7** [comment]
result.getSlider().setGravity(Gravity.RIGHT);

i applied this line but its not working

**Comment by mikepenz** [comment]
Oh sorry. Mixed up normal gravity with `LayoutGravity` please see the following:
http://stackoverflow.com/a/8049860/325479

The layoutparams. Note that the `Slider` has the `DrawerLayout.LayoutParams`

**Comment by Pareshoct7** [comment]
DrawerLayout.LayoutParams params = new DrawerLayout.LayoutParams(DrawerLayout.LayoutParams.WRAP_CONTENT, DrawerLayout.LayoutParams.FILL_PARENT);
        params.gravity = Gravity.RIGHT;

        result.getSlider().setLayoutParams(params);


use this import for layout params
import android.support.v4.widget.DrawerLayout;

Thanks it's works for me.

**Comment by SarkenJ** [comment]
Thank you for your fast answers, really kind of you. 
I tried to modify the gravity of the Drawer and it worked for the first time.

` DrawerLayout.LayoutParams params = new DrawerLayout.LayoutParams(DrawerLayout.LayoutParams.WRAP_CONTENT, DrawerLayout.LayoutParams.FILL_PARENT);
            params.gravity = gravity;
            result.getSlider().setLayoutParams(params);`

The slider changes position correctly, and I close the Drawer successfully. However, when changing gravity again and the Drawer is closed then the program crashes.

I checked the Drawer object gravity before and after changing gravity values for the first time, and it doesn't change despite that the slider changes position. So it appears as if the slider and the drawer (in the Drawerbuilder class) have separate gravity properties, or that changing the slider gravity doesn't change the drawer gravity property. When closing the drawer, the Drawerbuilder  uses it's gravity field which can't be set from outside.

Thank you.

> java.lang.IllegalArgumentException: No drawer view found with gravity LEFT
Process: com.example.sense.ContactManagment, PID: 26601
java.lang.IllegalArgumentException: No drawer view found with gravity LEFT
at android.support.v4.widget.DrawerLayout.closeDrawer(DrawerLayout.java:1715)
at android.support.v4.widget.DrawerLayout.closeDrawer(DrawerLayout.java:1701)
at com.mikepenz.materialdrawer.Drawer.closeDrawer(Drawer.java:135)
at com.example.sense.ContactManagment.Utilities.NavigationDrawerUtil$3$1.run										                                (NavigationDrawerUtil.java:190)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by mikepenz** [comment]
@SarkenJ yeah that makes sense as the internal methods from the `Drawer` would still use the gravity which was defined during the beginning. 

As a quick fix you can directly call the methods from the `DrawerLayout` to open and to close. I will add a method to set the gravity on the `Drawer` object, so you can also update the gravity in there, which should fix your issue.

**Comment by Pareshoct7** [comment]
@mikepenz  Sorry to ask you that but can you give the estimated time. when you are adding the method and releasing the new library with above correction ?

**Comment by SarkenJ** [comment]
Thank you Mike it works :). Best regards.

**Comment by mikepenz** [comment]
@Pareshoct7 perhaps today or tomorrow evening (CET)

**Comment by SarkenJ** [comment]
Hi, I updated the library, but can't access the setGravity(int gravity) from the Drawer  object.

**Comment by mikepenz** [comment]
@SarkenJ I was not yet able to publish the new release as I first want to update the `FastAdapter`.
