### ISSUE TITLE
AdjustPan

### ISSUE THREAD

**Issue by RuiHelderOliveira** [mikepenz/MaterialDrawer#1493]
In my Drawer layout i have a ContainerDrawerItem with EditText.
When keyboard is show the navigation bar appear like this

![captura de ecra 2016-08-22 as 17 43 21](https://cloud.githubusercontent.com/assets/6436843/17863068/0af1b306-6890-11e6-8533-fb0f0b3a1de1.png)
I'm using android:windowSoftInputMode="adjustPan" in activity tag manifest file.

it happens in Nexus 6P in landscape.

Please help me.

Thanks.

**Comment by mikepenz** [comment]
du you have any fullscreen flags or so set?

**Comment by mikepenz** [comment]
@RuiHelderOliveira please also add some code so I can have a closer look

**Comment by RuiHelderOliveira** [comment]
I think not.

2016-08-22 17:53 GMT+01:00 Mike Penz <notifications@github.com>:

**Comment by mikepenz** [comment]
@RuiHelderOliveira could you please add some more info, also some code would help. Best would be if you provide a small demo application with to showcase the issue.

**Comment by RuiHelderOliveira** [comment]
Activity code build Drawer:

// Handle Toolbar
assert getSupportActionBar() != null;
Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
toolbar.setTitleTextColor(Color.WHITE);
setSupportActionBar(toolbar);

AccountHeader headerResult = new AccountHeaderBuilder()
        .withActivity(this)
        .withProfileImagesVisible(false)
        .withCurrentProfileHiddenInList(true)
        .withHeaderBackground(R.drawable.img_drawer)
        .withSelectionListEnabledForSingleProfile(false)
        .addProfiles(new ProfileDrawerItem().withName("Rui
Oliveira").withEmail("rui***").withNameShown(false).withIdentifier(1))
        .build();

result = new DrawerBuilder()
        .withActivity(this)
        .withToolbar(toolbar)
        .withFullscreen(true)
        .withAccountHeader(headerResult)
        .withSliderBackgroundColorRes(android.R.color.white)
        .withActionBarDrawerToggle(true)
        .withDrawerItems(*buildDrawerItems**()*)
        .build();

getSupportActionBar().setDisplayHomeAsUpEnabled(false);


*buildDrawerItems()*: - ContainerDrawerItem with EditText like search
input and some items(custom views).

                    - DividerDrawerItem(),

                    - SecondaryDrawerItem


Activity layout:

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center">

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        android:elevation="4dp"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

    <FrameLayout
        android:id="@+id/fragment_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/toolbar">

        <ProgressBar
            android:id="@+id/progressBar"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"/>
    </FrameLayout>
</RelativeLayout>


2016-08-23 10:13 GMT+01:00 Mike Penz <notifications@github.com>:

**Comment by mikepenz** [comment]
@RuiHelderOliveira if you remove the following?
```java
.withFullscreen(true)
```

**Comment by RuiHelderOliveira** [comment]
already tested this


2016-08-23 11:16 GMT+01:00 Mike Penz <notifications@github.com>:

**Comment by RuiHelderOliveira** [comment]
Thanks in advance. It has been tireless in supporting


2016-08-23 11:20 GMT+01:00 Rui Oliveira <rui.helderoliveira@gmail.com>:

**Comment by mikepenz** [comment]
@RuiHelderOliveira hmmm ok. Which theme do you set on that activity?

**Comment by RuiHelderOliveira** [comment]
MaterialDrawerTheme.Light.DarkToolbar


2016-08-23 11:28 GMT+01:00 Mike Penz <notifications@github.com>:

**Comment by mikepenz** [comment]
Sounds also fine. Hmmm I somehow have the bad feeling that it may could be related to the `fitsSystemWindow`s flag somewhere, or it's an Android bug

**Comment by RuiHelderOliveira** [comment]
I test this in Nexus 6P with android marshmallow 6.0.1 with landscape
orientation.

2016-08-23 11:35 GMT+01:00 Mike Penz <notifications@github.com>:

**Comment by mikepenz** [comment]
I just tried to reproduce the issue in the following branch: https://github.com/mikepenz/MaterialDrawer/blob/feature/%231493/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java via the `DrawerActvitiy`but was not able to do so. 

Works on 6.0.1 and also on Android N

**Comment by RuiHelderOliveira** [comment]
Do you tried landscape orientation (navigation bar right side)?

2016-08-23 19:00 GMT+01:00 Mike Penz <notifications@github.com>:

**Comment by mikepenz** [comment]
@RuiHelderOliveira yes. Had the ui turned around to landscape

**Comment by RuiHelderOliveira** [comment]
Instead EditText using AutoCompleteTextView may affect?


2016-08-24 14:23 GMT+01:00 Mike Penz <notifications@github.com>:

**Comment by mikepenz** [comment]
May you provide a small sample app I can install and run in AS?

**Comment by mikepenz** [comment]
@RuiHelderOliveira it would be great if you could add additional details. close until then
