### ISSUE TITLE
Status Bar translucency 

### ISSUE THREAD

**Issue by vptcr** [mikepenz/MaterialDrawer#1495]
I think with the latest support lib update, the status bar transparency is broken. It always shows up in primary color.

**Comment by mikepenz** [comment]
@vptcr sorry nothing related to the library as I don't control the statusbar, or it's transparency

**Comment by valentinooo** [comment]
Hi, 

I'm a newbie on Android but i found a useful code to change the default primary color, just pust these lines when you create the toolbar and your statusbar will fill with your wanted color. 

Have a nice day and thanks for your great library !!

```
//before it's code to make Mikepenz MaterialDrawer

    Window window = this.getWindow();

// clear FLAG_TRANSLUCENT_STATUS flag:
            window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);

// add FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS flag to the window
            window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);

// finally change the color (blue grey was mine)
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                window.setStatusBarColor(ContextCompat.getColor(this,R.color.md_blue_grey_500));
            }
```
