### ISSUE TITLE
[Question] Support Some Item

### ISSUE THREAD

**Issue by mdtuyen** [mikepenz/MaterialDrawer#1496]
- In your library do you support group radio button element item and Listview ?

**Comment by mikepenz** [comment]
@mdtuyen no there is no support for a `ListView` as it uses a `RecyclerView`. 

Theoretically you can implement your own `CustomDrawerItem` with a radio button, but I think you will have to implement the logic about deselecting the others when one of those is selected on your own. (not sure about this part, but I don't think the RV + the RadioButtons do this on their own)

Read more about custom drawerItems in the FAQ:
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md
