### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by MostafaEbrahimi** [mikepenz/MaterialDrawer#1497]
Hello.
Failed to resolve this dependency
`compile 'com.mikepenz:materialdrawer:5.6.1'`
this is my dependencies

 

    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.android.support:design:24.1.0'

    // RecyclerView
    compile 'com.android.support:recyclerview-v7:24.1.1'

    // CardView
    compile 'com.android.support:cardview-v7:24.1.1'

    // Glide
    compile 'com.github.bumptech.glide:glide:3.7.0'

    compile 'com.afollestad.material-dialogs:core:0.9.0.1'

    compile 'com.mikepenz:materialdrawer:5.6.1'

`
all of dependencies resolved except drawer dependency.
I am using Jcenter() and android studio

**Comment by mikepenz** [comment]
@MostafaEbrahimi where did you find a version 5.6.1 of the `MaterialDrawer`? The latest release is 5.6.0

https://github.com/mikepenz/MaterialDrawer/releases

**Comment by MostafaEbrahimi** [comment]
Excuse me.it was a problem on my issue here .I use 5.6.0 but I can not resolve it.
Before adding this module I can resolve every dependency.But after adding this dependency get error on all of dependencies
`Error:Failed to resolve: com.android.support:design:24.2.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:C:/D/android/SongApp/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>`

**Comment by MostafaEbrahimi** [comment]
whats version of sdk needed this materialdrawer?

**Comment by mikepenz** [comment]
@MostafaEbrahimi the latest version of my libs allways use the latest build tools and latest support libraries. In this case v24.2.0
