### ISSUE TITLE
Attribute "alpha" has already been defined

### ISSUE THREAD

**Issue by Jierain** [mikepenz/MaterialDrawer#1498]
Attribute "alpha" has already been defined

**Comment by mikepenz** [comment]
@Jierain the materialdrawer does not define an attribute `alpha` please make sure you use the correct support library version in combination with the MaterialDrawer. 

The latest version will always depend on the latest support libs. in this case 24.2.0

**Comment by Jierain** [comment]
OK,  At last I used  <android.support.v4.widget.DrawerLayout/>.

**Comment by Jierain** [comment]
android.support.v4.widget.DrawerLayout
