### ISSUE TITLE
Accounts avatar from internet

### ISSUE THREAD

**Issue by alorma** [mikepenz/MaterialDrawer#150]
Hi.
How can i create ```ProfileDrawerItem``` with an image from internet?

Is there any way? I need to create my own AsyncDrawable?

**Comment by mikepenz** [comment]
@alorma sorry that there is no simple api or method to call for setting a drawable from the internet. 

the recommend implementation is to remember the profile item and update it as soon as you have the drawable. 

If you have an idea how to provide this without any additional dependencies let me know ;)

**Comment by alorma** [comment]
I forked the project, and will work on that.

Hope i can help on that :$

I supose that the best way is add a metod .withIcon("http..."), and add some method to auto load the image.

Next maybe add some "profile avatar loader", to provide comatibility with any library

**Comment by mikepenz** [comment]
@alorma sounds good. the important part here is to provide a generic api which will allow compatibility with any library as you said.

thanks for the help :)

**Comment by alorma** [comment]
I work in this branch:

https://github.com/alorma/MaterialDrawer/tree/profile_avatar_url

**Comment by mikepenz** [comment]
@alorma thanks. will check it for updates

**Comment by alorma** [comment]
I created a first implemenation using Picasso library, just as example.

What do you thik of how it's going?

**Comment by mikepenz** [comment]
@alorma just took a look and added some comments. it looks ok. But still it adds picasso as fixed dependency.

if we are able to eliminate the requirement of an lib within the MaterialDrawer and are able to provide this function via an interface it would be great.

**Comment by bohoffi** [comment]
As @mikepenz mentioned it would be great to get a dynamic solution instead of a fixed dependency. I personally prefer using Universal Image Loader.
Maybe there could be some callback method on the profile item to be called when the image is fully loaded to set the image to the view.

**Comment by alorma** [comment]
That is done in the https://github.com/mikepenz/MaterialDrawer/tree/profile_avatar_url

**Comment by mikepenz** [comment]
@alorma @bohoffi i will merge it back as soon as i have some time :D i really like the approach with the loader you can inject into the drawer :D so yeah.
