### ISSUE TITLE
Disable Sticky Item

### ISSUE THREAD

**Issue by sghazagh** [mikepenz/MaterialDrawer#1501]
Sorry a very basic question which I have stuck at!

How can I find a 'PrimaryDrawerItem' and visible or invisible it within my code?
How can I find the sticky item?

**Comment by mikepenz** [comment]
@sghazagh if you want to make it "invisible" you have to remove it from the drawer, and add it back at a later time. Just use the methods provided by the `Drawer` object you get from `.build()`

You can get the position, remove or add new sticky items. Just read the `Drawer` objects javadoc

**Comment by sghazagh** [comment]
Thanks Mike for your reply.
That's where I have stuck because I don't know how to find the item.
I think I can  get the PrimaryDrawerItem but not the sticky one.

Is it possible for you to guide me with a line of code how to dinf my sticky number which I identified as number 100?

I appreciate your help

Why I need this: I want to add Purchase item in Drawer and after purchase remove it.
Is this concept correct at all to use drawer for this purpose?

**Comment by mikepenz** [comment]
@sghazagh but why do you need to get it first? just delete this `Sticky` item by its position and re-add it later into the `Sticky`-Footer. You even have the item itself already as you had to pass it to the builder anyway. so it should not be to hard to reuse it

**Comment by sghazagh** [comment]
Ok I got what you mean!
So I'll try to add it whenever I need it and see if I can remove it the same way....
