### ISSUE TITLE
Any possibility to change the color of "ActionBarDrawerToggle" dynamically?

### ISSUE THREAD

**Issue by dupp** [mikepenz/MaterialDrawer#1503]
Its me again :D.

I wrote a method to readout the background color (if its dark or bright). 
How can i change the color, if ActionBarDrawerToggle is "true"?
This is the code of my DrawerBuilder:

```java
 drawer = new DrawerBuilder()    //https://github.com/mikepenz/MaterialDrawer
                .withActivity(activity)
                .withToolbar(toolbar)
                .withDisplayBelowStatusBar(false)
                .withRootView(R.id.drawer_layout)
                .withDrawerLayout(R.layout.material_drawer_fits_not)
                .withSliderBackgroundColor(Color.parseColor("#" + Customer.getInstance().settings.customerColor))
                .withActionBarDrawerToggle(true)
                .withActionBarDrawerToggleAnimated(true)
                .withSelectedItem(-1)
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        drawerClickListener(view, position);
                        return false;
                    }
                });
```

**Comment by dupp** [comment]
I will change it dynamically because I get the backgroundColor from my API.

**Comment by mikepenz** [comment]
@dupp in general the `ActionBarDrawerToggle` is a component from the support libraries, and I just add it to the `Toolbar` automatically. No other handling here. 

You can get the reference to the `ActionBarDrawerToggle` via the `Drawer` object at anytime again. 

But a quick google search showed this is not really possible. 
You might check out this answer: http://stackoverflow.com/a/33554037/325479 but it will also require you to handle the `ActionBarDrawerToggle` on your own. So just don't provide the `Toolbar` to the drawer then.

**Comment by dupp** [comment]
Yes.. i just saw it before. 

I thought there will be an easier way :). Thank you Mike.
