### ISSUE TITLE
hide drawer for some fragments 

### ISSUE THREAD

**Issue by jsnaruka** [mikepenz/MaterialDrawer#1506]
first thanks for giving such a great library .....i dont not this is silly problem or what?

i have one activity ,in which i m loading different fragment but in some fragment i dont want drawer. so please help me

**Comment by jsnaruka** [comment]
back arrow is coming and its working but when we slide for drawer it is coming...

**Comment by mikepenz** [comment]
You can lock the drawer when you don't want it. So you can set the drawer lock mode on the DrawerLayout which will disable the swipe. And you have to handle the ActionBarDrawerToggle also. But this independent of my lib. More a general DrawerLayout topic

**Comment by jsnaruka** [comment]
i m asking for your lib. is this possible to hide for some fragment ?

**Comment by jsnaruka** [comment]
thanks ....solved
result.getDrawerLayout().setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);
