### ISSUE TITLE
Navigation Drawer Translucent status with support for pre lollipop

### ISSUE THREAD

**Issue by spurdow** [mikepenz/MaterialDrawer#1507]
Navigation Drawer Translucent status with support for pre lollipop

Im having problem with my navigation drawer , I cant seem to reproduce its translucency, using my `theme.xml`

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="AppTheme" parent="AppTheme.Base"/>

    <style name="AppTheme.Base" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:windowNoTitle">true</item>
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
    </style>


    <style name="DrawerArrowStyle" parent="Widget.AppCompat.DrawerArrowToggle">
        <item name="color">@android:color/white</item>
    </style>


</resources>
```
this is the image , its gray it should be translucent , I tried adding some code 
  `.withTranslucentStatusBar(true)`
e code 
  `.withTranslucentStatusBar(true)`
![problem_with_material_design](https://cloud.githubusercontent.com/assets/3696283/18226200/41bd8954-7237-11e6-96ba-b3363b54a533.png)

I tried extending MaterialDrawerThemes but the problem is I need a `NoActionBar` Theme

Am I missing something?

**Comment by mikepenz** [comment]
The screenshot is correct. The drawer is below the statusbar. And it is also in the correct color of the DrawerLayout background.

**Comment by spurdow** [comment]
ok, so how do I remove the color of status bar color of navigation drawer?

**Comment by mikepenz** [comment]
@spurdow so you don't want the drawer to go below the `StatusBar`?
There is the `NonTranslucentDrawerActivity` sample for this: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/NonTranslucentDrawerActivity.java

**Comment by emerciercontexeo** [comment]
Hi,

I'm working with your Material drawer. I did a lot of thing successfully but now, I think I'm in the same situation than @spurdow 

To resume, i have on simple application with one Activity.
I use one of your Material Design theme : MaterialDrawerTheme.Light.TranslucentStatus

Here is my Activity onCreate method :

    super.onCreate(savedInstanceState);
        Log.i("MapActivity", "onCreate");
        setContentView(R.layout.activity_map);
        toolbar = (Toolbar) findViewById(R.id.activity_toolbar);
        drawer = new DrawerBuilder().withActivity(this).withToolbar(toolbar).build();

Here is the result, status bar is not translucent but blue and my toolbar is pull down : 
![with_drawer](https://cloud.githubusercontent.com/assets/8739777/18253447/02aa5a9e-7395-11e6-957f-4cb29d38aff5.png)

When the drawer is open, it is below the status bar as expected : 
![with_drawer_open](https://cloud.githubusercontent.com/assets/8739777/18253523/a563d526-7395-11e6-8296-37402f395157.png)


And here, the result without, the status bar is translucent and component are on the right place
    drawer = new DrawerBuilder().withActivity(this).withToolbar(toolbar).build();
![without_drawer](https://cloud.githubusercontent.com/assets/8739777/18253452/0f24c4b2-7395-11e6-8e0c-c557baeed38d.png)


At this point, I don't know if i missed something so I come to you.

Whatever, this library is a very good tool, thank you !

**Comment by mikepenz** [comment]
@emerciercontexeo so what's wrong with the third screenshot you posted?

You don't really have to set the `TranslucentStatusbar` programatically on the `DrawerBuilder`. 

Just to clear things up. The whole behind and below `StatusBar` handling, and also the shadows come from the `fitsSystemWindow`s flag. The `DrawerBuilder` will only use different layouts depending if some properties are set or not.

**Comment by emerciercontexeo** [comment]
@mikepenz In the last screen shot, the result is good but it's without drawer.

When i add the following line my main content is pull under the status bar (Img 1)

    drawer = new DrawerBuilder().withActivity(this).withToolbar(toolbar).build();

What I want is a mix between the second and the third image. Drawer AND the main content behind the status bar

I tried to add 
    drawer.getDrawerLayout().setFitsSystemWindows(false);
 but in this case, the status bar is not visible anymore.
![withfits](https://cloud.githubusercontent.com/assets/8739777/18254255/21711a42-739c-11e6-985c-fd5c890401e4.png)

**Comment by mikepenz** [comment]
ah ok. Could you please provide a small sample app with exact the case so i can debug it too?

**Comment by emerciercontexeo** [comment]
https://github.com/emerciercontexeo/MaterialDrawerTestApp/tree/Mike

It's the simple exemple possible. Thanks you again

**Comment by mikepenz** [comment]
Thank you. Will have a look

**Comment by mikepenz** [comment]
@emerciercontexeo https://github.com/emerciercontexeo/MaterialDrawerTestApp/pull/1

**Comment by emerciercontexeo** [comment]
Many thanks @mikepenz 

I will read a bit more about Coordinator Layout.

I made a litte change in your second solution if you want to see it.

I will take a look on your others projects

**Comment by spurdow** [comment]
@emerciercontexeo thanks for replicating the issue, i was so busy so sorry, @mikepenz wow so fast thanks a bunch.
