### ISSUE TITLE
Is it OK to create the Drawer inside the method onStart()?

### ISSUE THREAD

**Issue by AreaNovi** [mikepenz/MaterialDrawer#1509]
I'm using an abstract activity to share code between activities. The Drawer is one of the important parts I want to share. If I add the code to create the Drawer inside the onCreate() method of the Abstract Activity, it doesn't work, probably because it messes up with the code in the onCreate() method of the child Activity. It seems to work if I add the code for the Drawer inside the onStart() method of the Abstract Activity.
Do you think this is a good solution or there might be drawbacks?
Thanks

**Comment by mikepenz** [comment]
@AreaNovi yes this could cause some troubles. Read more here: http://stackoverflow.com/a/6812066/325479

Why not just move the code for the `Drawer` to a static util class where you init all, and you simply call this creation method in the `onCreate` methods of your activity?

**Comment by AreaNovi** [comment]
I did as you suggested and it seems to work fine.
Thank you very much. Great library.
