### ISSUE TITLE
why this error occured when i want to add the library to my project? 

### ISSUE THREAD

**Issue by KingEfan** [mikepenz/MaterialDrawer#1510]
Hi Mr.Penz ,
when i add
```gradle
compile('com.mikepenz:materialdrawer:5.6.0@aar') {
    transitive = true
}
```
to my gradle file in my android project when i synce it it shows me this error :

![screenshot 2](https://cloud.githubusercontent.com/assets/13975671/18237744/4c333942-734a-11e6-8a18-032415b2c317.png)

while my gradle file's code is :
```gradle
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"

    defaultConfig {
        applicationId "com.example.kingerfan_pc.game_sharing_androidproject"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.android.support:design:24.1.1'
    compile 'com.alirezaafkar:toolbar:1.1.0'
    compile('com.mikepenz:materialdrawer:5.6.0@aar') {
        transitive = true
    }
}
```

Could youu please help me with this problem ??
I should notice that when i add your library in my gradle dependencise it goes like this.

**Comment by mikepenz** [comment]
The error already describes what happens. It can't find the latest support libraries, because you have to update your android SDK. And the support repository. 

Please also make sure to use the same support libraries in your project as defined in the library. The latest will always target the latest support libraries. In this case 24.2.0

**Comment by KingEfan** [comment]
I 'm new in developing android . So Thanks .It workes.
