### ISSUE TITLE
How to set an action on drawer close.

### ISSUE THREAD

**Issue by MTersigni** [mikepenz/MaterialDrawer#1511]
I want to set a specif action when you click to close the drawer, how?
Or even better, how can I set the view under the drawer unclickable when the drawer is open? Because it seems I can click under the drawer.

Thanks in advance.
@mikepenz

**Comment by mikepenz** [comment]
@MTersigni you have a normal drawer? Where are you able to click through? 

You can provide a `OnDrawerListener` which will fire the `OnDrawerClosed` event:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L1086
