### ISSUE TITLE
profile logo 

### ISSUE THREAD

**Issue by jsnaruka** [mikepenz/MaterialDrawer#1512]
![636fee924ee0c6024b168df5431af8fa5775bbb76d2a997ec8 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/15357251/18250643/5219f4b0-73a2-11e6-914a-116b9ee6651d.jpg)
i m loading profile pic from fb using universal imageloader ..... in some cases whole profile pic is not in round shape.

**Comment by mikepenz** [comment]
The image set should be `square` either you transform it via the Imageloader (if you rimageloader can do this) or you have to change the `scaleType` defined for the image. 

Read more here: https://github.com/mikepenz/MaterialDrawer/issues/1394#issuecomment-233187311
