### ISSUE TITLE
Removing one sticky footer item removes all

### ISSUE THREAD

**Issue by Techwolf12** [mikepenz/MaterialDrawer#1515]
I observed an issue that when creating sticky footer items with identifiers: 

```java
drawerItemSec = new SecondaryDrawerItem()
                .withName("Magnetometer")
                .withDescription("Status: ok")
                .withIdentifier(200)
                .withEnabled(false)
                .withBadge(" ")
                .withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.md_green_700));

        disconnectButton = new SecondaryDrawerItem() {
            @Override
            public void onPostBindView(IDrawerItem drawerItem, View view) {
                super.onPostBindView(drawerItem, view);
                view.setBackgroundColor(getResources().getColor(R.color.button_color));
            }
        };

        disconnectButton
                .withTextColor(ContextCompat.getColor(this, android.R.color.white))
                .withName("Disconnect")
                .withIdentifier(300)
                .withEnabled(true);
```

They will both disappear when trying to remove drawerItemSec as such:

```java
            if (drawerItemSec != null) {
                long drawerMagnetometerIdentifier = drawerItemSec.getIdentifier();      
       drawer.removeStickyFooterItemAtPosition(drawer.getStickyFooterPosition(drawerMagnetometerIdentifier));
                drawerItemSec = null;
            }
```

Am I doing something wrong or is this a bug? Thanks for your time!

**Comment by Techwolf12** [comment]
It seems the position for both items is -1, removing one removes the other as well.
Currently we fixed it by adding the second item after removing all items, this is however not a desired situation.

```java
if (drawerItemSec != null) {
    drawer.removeAllStickyFooterItems();
    drawer.addStickyFooterItem(disconnectButton);
    drawerItemSec = null;
}
```

There seems to be a bug with the position of sticky menu items.

**Comment by mikepenz** [comment]
@Techwolf12 just tried to reproduce the issue. But does not happen in the `DrawerActivity` 

```java
        result.removeStickyFooterItemAtPosition(result.getStickyFooterPosition(12));
```
will remove the item in the footer with ID 12. 

Do your `items` have a identifier set with `withIdentifier()`?

**Comment by Techwolf12** [comment]
They have identifier's set as seen in my code example above. When I listen with `withOnDrawerItemClickListener` the position for both items is also -1. When it is less busy I will set some breakpoints and try to debug it

**Comment by mikepenz** [comment]
@Techwolf12 no the position being `-1` inside the `Listener` is fine. As I can't provide the position here, because those items are not part inside the `RecyclerView`

**Comment by mikepenz** [comment]
@Techwolf12 please provide additional details. close until then
