### ISSUE TITLE
How to add a custom view with animation

### ISSUE THREAD

**Issue by shaikansaar** [mikepenz/MaterialDrawer#1517]
Hi Mike,

Thanks for the awesome library.

I have a requirement to add a custom view (with some animation) to the right side of the account header. It is not another account to add instead just view and upon click i need to open another activity.

Please find below the snaphost:

![image](https://cloud.githubusercontent.com/assets/4800397/18349021/e6d944ea-75df-11e6-8c62-1da6a7552011.png)

Can you please suggest how to add this.

Thanks
Shaik Ahmed

**Comment by mikepenz** [comment]
@shaikansaar if you just have one profile you do not necessarily have to use the `AccountHeader` you simply can use your own view and do whatever you need with it. 

If you want to use the `AccountHeader` but want to add a view. You can overwrite and change the layout used by the `AccountHeader` (copy paste it to your project and modify it)
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml
(add your view (don't remove containing views)) 

You can later then just access it via the `AccountHeader.getView()` method.:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L47

Then simply animate / show / hide your view
