### ISSUE TITLE
Q - Logout?

### ISSUE THREAD

**Issue by LinkOut** [mikepenz/MaterialDrawer#1518]
How to logout? i mean once im logged in using accountheader... by pressing the "switch account arrow" is possible to set a logout there? I dont see that listener...thanks

EDIT: on this event: withOnAccountHeaderSelectionViewClickListener

**Comment by mikepenz** [comment]
@LinkOut you can listen for the click on the accountheader, or you just add a `Logout` item to your general drawer, or you add one to the accounts list. It's up to you. there are many many possibilities. 
But you were probably searching for: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L420
