### ISSUE TITLE
how to use the toolbar in java file?

### ISSUE THREAD

**Issue by KingEfan** [mikepenz/MaterialDrawer#1519]
Hi Mr.Penz,
Here I got another problem that when I want to use my toolbar's object in the java it says that : 
![screenshot 7](https://cloud.githubusercontent.com/assets/13975671/18352076/1eb32446-75f2-11e6-821e-07cbab730b27.png)
and here is my xml code : 
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/coordinator_Layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context="com.example.kingerfan_pc.game_sharing_androidproject.MainActivity">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <com.alirezaafkar.toolbar.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/colorPrimary"
            app:direction="rtl"
            app:optionsMenu="@menu/menu_main"
            app:font="@string/font_path"
            android:gravity="start"
            app:navigationIcon="@drawable/ic_menu"
            app:popupTheme="@style/AppTheme.PopupOverlay"
            app:title="@string/persian_name" />

    </LinearLayout>

</android.support.design.widget.CoordinatorLayout>
```

I had used this library [https://github.com/alirezaafkar/Toolbar](url) 
but as you see the .withToolbar() can not accept this do you know how can i solve it or do you know any better library to make my toolbar??
Thanks...

**Comment by mikepenz** [comment]
@KingEfan sorry the `MaterialDrawer` only accepts the original `Toolbar` from the support libs. Please use this one. 

Otherwise simply don't provide the `Toolbar` to the builder and create the `ActionBarDrawerToggle` (Hamburger icon)  on your own and just call the open / close methods of the drawer

**Comment by KingEfan** [comment]
Ok that get solved but now I habe a question that if i mmake a toggle for my toolbar MaterialDrawer would know it an get opened when i click that toggle??

**Comment by mikepenz** [comment]
You use call the open or close methods on the `Drawer` object..
