### ISSUE TITLE
Bug - Icon Colors

### ISSUE THREAD

**Issue by TurKurT656** [mikepenz/MaterialDrawer#152]
I had reported this bug before and you set this attr:
<item name="material_drawer_primary_icon">#8A000000</item>
but still bug is there. i think the alpha is not working for this. I've set this color: #727272 and the bug solved. note that #8A000000 has same appearance like #727272 according to this link:
http://www.materialpalette.com/

**Comment by mikepenz** [comment]
@TurKurT656 can you please also add some code. what you are trying and a screenshot how it is displayed?

The sample app shows the icons in the correct color.

**Comment by TurKurT656** [comment]
see the color of your icons in your screen shots:
https://github.com/mikepenz/MaterialDrawer
and this icon colors by google material design guidelines:
http://www.google.com/design/spec/patterns/navigation-drawer.html

if you notice they are grey but your colors are black

**Comment by TurKurT656** [comment]
See:
![screenshot1_small](https://cloud.githubusercontent.com/assets/7152030/6823003/b6dd8c92-d301-11e4-966c-ae9dd8b5b1dd.png)
![patterns_navdrawer_metrics1](https://cloud.githubusercontent.com/assets/7152030/6823004/b81d09c0-d301-11e4-99d5-6498723bada1.png)

**Comment by mikepenz** [comment]
@TurKurT656 so you just talk about the screenshots :D haha. the ample already has this change.d

**Comment by TurKurT656** [comment]
no I've tested your lib but with my own theme (not implemented MaterialDrawerTheme) and i have to add this line that solve the issue:
<item name="material_drawer_primary_icon">#727272</item>
all Im trying to say is that it had to be set default that when someone use this library with his/her custom theme ( for example Theme.AppCompat.Light.NoActionBar) the icons appear grey not black

But it's not a bug at all. if someone wants he/she has to set this value to his/her theme

**Comment by mikepenz** [comment]
@TurKurT656 sounds strange. Will have to check this with a non MaterialDrawerTheme

**Comment by TurKurT656** [comment]
yes, check it with Theme.AppCompat.Light.NoActionBar

**Comment by mikepenz** [comment]
@TurKurT656 you are using the newest version? and have cleaned everything? with a clean theme? 

Just used the sample application. set the default appCompat light theme for the application and it was workign.

![screenshot_2015-03-25-23-03-09](https://cloud.githubusercontent.com/assets/1476232/6836567/903eef58-d343-11e4-87ec-2707785accda.png)

**Comment by TurKurT656** [comment]
@mikepenz i don't know why this happening. yes i have tested the newest version with them.appcompat.light.noactionbar theme.

**Comment by mikepenz** [comment]
@TurKurT656 and no custom colors anywhere in the project?
 
I really can't say why there some difference. somewhere there must be anything..

**Comment by TurKurT656** [comment]
This is my styles.xml:

<style name="AppTheme.Base" parent="Theme.AppCompat.Light.NoActionBar">

</style>

    
    <style name="AppTheme" parent="AppTheme.Base">
        <item name="colorPrimary">@color/primary</item>
        <item name="colorPrimaryDark">@color/primaryDark</item>
        <item name="colorAccent">@color/accent</item>
        <item name="material_drawer_primary_icon">@color/black54</item>
    </style>

note that I've added last item to items be grey

**Comment by TurKurT656** [comment]
This is my colors:

<color name="black54">#727272</color>
<color name="primary">#673AB7</color>
<color name="primaryDark">#512DA8</color>
<color name="accent">#FF9800</color>

**Comment by mikepenz** [comment]
anywhere else something different set?
hmmm and as soon as you remove the icon color it will show black again?


just as a question why don't you use the provided theme?

**Comment by mikepenz** [comment]
@TurKurT656 have you included android-iconics as a dependency to your project?

**Comment by TurKurT656** [comment]
@mikepenz no i havent set any other thing to styles.
and yes when i remove the item its black again :|
no reason :) i have to set to your theme i think :D

**Comment by TurKurT656** [comment]
This is my dependencies:
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile 'com.android.support:recyclerview-v7:22.0.0'
    compile 'com.android.support:cardview-v7:22.0.0'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.daimajia.androidanimations:library:1.1.3@aar'
    compile 'com.jpardogo.materialtabstrip:library:1.0.9'
    compile 'com.github.ShogoMizumoto:ZDepthShadowLayout:1.0.4'
    compile 'com.afollestad:material-dialogs:0.6.4.7'
    compile('com.mikepenz.materialdrawer:library:2.5.7@aar') {
        transitive = true
    }

**Comment by mikepenz** [comment]
@TurKurT656 the strange thing is. if i use the appcompat theme in the sample app it works. so it'S really strange :O

I can't see anything wrong with your dependencies or anything else oO


yeah i really recommend to use the provided theme (the README states which theme is equal to which appcompat theme) because it manages a few things with backwards compatiblity.

**Comment by TurKurT656** [comment]
ok, i'll use ur theme :)

**Comment by TurKurT656** [comment]
i used ur theme but the problem isn't gone. in lollipop device problem gone but in htc sensation the problem hasn't gone

**Comment by mikepenz** [comment]
@TurKurT656 so probably it's an issue with the HTC Sensation. What's its android version?

**Comment by TurKurT656** [comment]
@mikepenz it's 4.1.2
but dont bother urself. i have set item attr and no need to fix :)

**Comment by mikepenz** [comment]
@TurKurT656 it's just really strange :D

**Comment by TurKurT656** [comment]
Yeap :P

**Comment by mikepenz** [comment]
@TurKurT656 i found the problem to the issue. it's the `StateListDrawable` which is used to allow different icons per state. this can't handle alpha values on pre api level 21 devices. tried a lot of different things now. and wasted 2 hours. so i gave up and decided that for now the only option is to use a non alpha value or people with older phones see it black

**Comment by TurKurT656** [comment]
@mikepenz you can set the color to #727272. see:
materialpalette.com
they choose this color as icon colors. it has the same color as alpha one :)

**Comment by mikepenz** [comment]
@TurKurT656 i know :D but it would be better if the StateListDrawable would not have those issues with alpha values

**Comment by TurKurT656** [comment]
@mikepenz you know the best :)
