### ISSUE TITLE
Fragment overlapping drawer

### ISSUE THREAD

**Issue by rims07** [mikepenz/MaterialDrawer#1520]
Hello,

I have a drawer and fragments, when i am trying to open the drawer one fragment is overlapping my drawer. How can i avoid this ? which method is called when the user try to open the drawer or swipe right to open the drawer ?

![image](https://cloud.githubusercontent.com/assets/8467629/18387958/2b96efe6-76bd-11e6-8138-d9a5b7cf4556.png)

**Comment by mikepenz** [comment]
@rims07 oh that's interesting. Does your fragment have any special view hirachy, or are those elements on a different `z` axis?
Where in your layout is this fragment commited?

The `MaterialDrawer` uses the normal `DrawerLayout` which will then handle the slide etc. So nothing I can change here. 

As of the callbacks which are called when the drawer gets opened: 
User the `OnDrawerListener` https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1132

**Comment by rims07** [comment]
hey thankyouuu so mcuh mike for replying :)
i did implement the Listener "implements Drawer.OnDrawerListener"
and added the following code but its not being called:

![image](https://cloud.githubusercontent.com/assets/8467629/18397080/304cd45c-76e4-11e6-9c70-793209854cac.png)

**Comment by rims07** [comment]
am i doing in the right way ?

**Comment by rims07** [comment]
Thankyou so much buddy for replaying, i solved my problem by calling the .withOnDrawerListener(new Drawer.OnDrawerListener()  and then stoping that game in those methods ..

Thanks aloottttttttttttttttttttttttttttttt :)

**Comment by mikepenz** [comment]
Awesome. Great that you solved it :)
