### ISSUE TITLE
Progress bar in menu

### ISSUE THREAD

**Issue by snijsure** [mikepenz/MaterialDrawer#1521]
I have case where some data is being downloaded in the background thread. Till that data is fully downloaded users can't use a menu option. So I was thinking of showing a "status" of data download that shows  % of data is currently downloaded. Is there a way to create a custom menu item that will show this value, and update it  as the progress update is received from background thread? I am familiar with Android progress bar etc. I am just not sure if I can create a custom menu item. If there an example I can look at that would be awesome.

**Comment by mikepenz** [comment]
@snijsure please have a look in the FAQ:
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md

**Comment by or-dvir** [comment]
@snijsure did you manage to create a custom progress item? i want to do the same
