### ISSUE TITLE
Url images not loaded on header profile

### ISSUE THREAD

**Issue by mariusgarcia** [mikepenz/MaterialDrawer#1524]
Congrats for such a good library !!
 
 I am trying to load a profile on the header but the image is not loading properly
```
 IProfile myProfile = new ProfileDrawerItem()
                .withName(nameProfile)
                .withEmail(emailProfile)
.withIcon("https://avatars3.githubusercontent.com/u/1476232?v=3&s=460");
```

  It is working when  use a resId or an icon from de fontset, but I cannot manage to get the image loaded when using a url. Am I doing something wrong ?

 `    compile('com.mikepenz:materialdrawer:5.6.0@aar') {  
        transitive = true
    }`

**Comment by mikepenz** [comment]
Please read the following:
https://github.com/mikepenz/MaterialDrawer#load-images-via-url

**Comment by mariusgarcia** [comment]
thanks, it worked

**Comment by ajithkpistar** [comment]
How to use this i coudnot able to load image through URL,pls provide some code sample

**Comment by TonyNikolov** [comment]
@ajithkpistar You just slap that method before you initialize the drawer for the first time. When you initialize it, just add the url as a string.
