### ISSUE TITLE
Want back button on Add account or Manage Account, and Want to show list of available accounts

### ISSUE THREAD

**Issue by namanjain1993** [mikepenz/MaterialDrawer#1525]
![14285573_1215483381851977_225165252_o](https://cloud.githubusercontent.com/assets/16480082/18502180/416bb9a0-7a73-11e6-8f39-e370d932965a.jpg)

Something like this image

**Comment by namanjain1993** [comment]
Waiting for any Hint
Thanks

**Comment by mikepenz** [comment]
@namanjain1993 you asked just 2 hours ago? It is no good behavior to push for an answer. This is open source no paid product. 😞

**Comment by namanjain1993** [comment]
mikepenz, apologies but no intention to push.
Just wanted a hint so that I could do some research.
Please don't take it otherwise.
Thanks

**Comment by mikepenz** [comment]
@namanjain1993 in general the `MaterialDrawer` and it's layout is built with the Material Design Guidelines in mind, so all those are exactly for the designs defined in the guidelines. 

As in your case. You want an arrow on the left. instead the small arrow on the right which is already there. 

You can alter the layout of the header, by overwriting it's layout. But as your header looks completely different it may be a better idea to just define a normal `Header` for the `MaterialDrawer` (not using the `AccountHeader`) and if the user clicks the view in it you will simply switch the contents of the drawer with the profiles he is allowed to choose. 

You can even use the methods defined for the `AccountHeader` to switch the list, but it's also possible without. 


https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L1390
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L1465

**Comment by namanjain1993** [comment]
@mikepenz i want to keep everything as it is(not changing header for full drawer implementation), just want to add functionality of above attached screen after user clicks on Add Account.

Thanks

**Comment by mikepenz** [comment]
You still can use the `AccountHeader` to show an `Add Account` text instead of the name and e-mail, and you can also use it to show the profiles the user can add. Just check out the `DrawerActivity` of the sample app it already shows elements in there which are no `ProfileDrawerItem`s. 

In addition you can set the first and second line of text in the `AccountHeader`

**Comment by namanjain1993** [comment]
I did used AccountHeader to show Add Account as Material Drawer shows, but after clicking on Add Account i want to change view of Drawer and set new elements and their listeners and and a back button to go to previous drawer state.

**Comment by namanjain1993** [comment]
I need to customise drawer view after Add Account click and on back button, get back default Material Drawer view and contents.
How to achieve that ?

**Comment by namanjain1993** [comment]
@mikepenz, u can ignore this request as I have come around a better solution for my usecase.
Being said that, thanks for quick replies and for maintaining this awesome library.

**Comment by mikepenz** [comment]
Great. Thank you ;)
