### ISSUE TITLE
Animate the ActionBarDrawerToggle

### ISSUE THREAD

**Issue by ArcanusEternal** [mikepenz/MaterialDrawer#1527]
Hi!

How to animate the ActionBarDrawerToggle to back arrow icon from the hamburger icon **without open/close** the drawer?

I used this code to show back arrow icon from hamburger icon:

`result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false);
getSupportActionBar().setDisplayHomeAsUpEnabled(true);`

When I use the code from above the animation missing, but the back arrow icon appear. Same issue in the other case (from back arrow to hamburger icon). The drawer opening/closing correctly animate the ActionBarDrawerToggle.

**Comment by mikepenz** [comment]
@ArcanusEternal this question is not related to the `MaterialDrawer` but it's a genral `ActionBarDrawerToggle` question. 

http://stackoverflow.com/questions/31255785/how-to-animate-the-hamburger-icon-to-back-arrow-while-using-design-support-libra

Probably you also just need the `syncState`
