### ISSUE TITLE
RecyclerView OnItemTouchListener -> OnitemLongClick() would still trigger sometimes when swiping in from the left to start MaterialDrawer

### ISSUE THREAD

**Issue by SandKierkegaard** [mikepenz/MaterialDrawer#1528]
I haven't narrowed down the cause of this bug to MaterialDrawer yet, so please bear with me while I describe it.

I use MaterialDrawer with my MainActivity which is simply 
```
<RelativeLayout>
    <Toolbar/>
    <FrameLayout>
      <RecyclerView>
          ...
```
and I followed [this guide](http://stackoverflow.com/questions/24471109/recyclerview-onclick/26826692#26826692) to implement the Touch/ClickListener for my RecyclerView.

Now, the bug I have is that when I swipe in from the left of the screen to start MaterialDrawer, if my swipe gesture started on an item in the RecyclerView, upon finishing the swipe, the OnItemLongClick would still trigger, even if the MaterialDrawer is now shown. 

I suspect that since my ClickListener overrides OnInterceptTouchEvent(), the swiping gesture first triggered my RecyclerView listener, even if it's meant to start the MaterialDrawer.
So I'm wondering whether there's some setting in MaterialDrawer that can prevent the (long)click listener from triggering?

**Comment by mikepenz** [comment]
@SandKierkegaard basically the `MaterialDrawer` uses the `DrawerLayout` form the appcompat library. There is no custom behavior in. 

I think the only solution to "prevent" the longclick is to either have an empty lonclicklistener or to set the listener to null during the event.

**Comment by SandKierkegaard** [comment]
Solution turns out to be trivial. I didn't have layout_marginLeft in my FrameLayout and once I added it, the bug can't be reproduced. Thank you for the attention tho!! you're awesome

**Comment by mikepenz** [comment]
@SandKierkegaard thanks :)
