### ISSUE TITLE
New application using MaterialDrawer

### ISSUE THREAD

**Issue by postacik** [mikepenz/MaterialDrawer#1529]
I've finished and published my new free application that uses your fantastic MaterialDrawer library. 

Being able to use font icons in the drawer helped me create a professional looking application quickly and easily.

It's an application that contains the Arabic script of the Holy Quran. Its Turkish name is "Kur'an Okuyorum" which can be translated as "I am reading Quran".

Can you add it to your "Apps using the MaterialDrawer" section?

Here is the Google Play link: https://play.google.com/store/apps/details?id=com.homemade.kuranokuma

**Comment by mikepenz** [comment]
@postacik please open a PR and add it at the end of the list ;)
