### ISSUE TITLE
Is not removable 

### ISSUE THREAD

**Issue by danielgomezrico** [mikepenz/MaterialDrawer#153]
I want to show a right drawer inside a fragment but it should be enabled only on that fragment, 
how can I do it?

I tried on `onStop` to call 

	if (refineDrawer != null) {           
	    refineDrawer.resetDrawerContent();
	    refineDrawer.closeDrawer();
	    refineDrawer = null;
	}

But it stay even on other views...
So, how can I remove it?

**Comment by mikepenz** [comment]
@danielgomezrico the drawer is inflated as layout within the activity. It works as any other drawer would in your application. I think there are methods which lock the drawer. Try to get the drawerLayout from the result object and look at the default DrawerLayout functions.

**Comment by danielgomezrico** [comment]
Ok thanks, yes, there are a method that actually lock it
