### ISSUE TITLE
replacing CustomView after DrawerBuilder.build()

### ISSUE THREAD

**Issue by Thore1954** [mikepenz/MaterialDrawer#1530]
Thanks for the great lib.
We're adding a Drawer with completely custom content using the following approach:

```java
    mDrawer = new DrawerBuilder()
                .withActivity(this)
                .withCustomView(getLayoutInflater().inflate(R.layout.drawer_content, null))
                .withSavedInstance(savedInstanceState)
                .build();
```

But we have two different contents that is shown to user at certain cases. (for example when he signs up) Is it possible to replace the whole CustomView at runtime?

**Comment by mikepenz** [comment]
@Thore1954 no this is not really possible. Can you work with views which you set `GONE` and / or `VISIBLE`?

**Comment by mikepenz** [comment]
It is also important to note that a drawer can't be built twice for one activity as it will do some stuff for you.

**Comment by Thore1954** [comment]
Thanks for paying attention mike. Yes, your approach is really nice but after taking a look at your own codes for adding the drawer to activity, I ended up with this solution:

```
...
private ViewGroup mDrawerContent;
...
@Override
protected void onCreate(Bundle savedInstanceState) {
        ...
        mDrawerContent = new FrameLayout(this);
        getLayoutInflater().inflate(R.layout.drawer_content, mDrawerContent, true);
        mDrawer = new DrawerBuilder()
                .withActivity(this)
                .withCustomView(mDrawerContent)
                .withSavedInstance(savedInstanceState)
                .build();
        ...
}
```

And later in code:

```
mDrawerContent.removeAllViews();
getLayoutInflater().inflate(R.layout.drawer_content_secondary, mDrawerContent, true);
```

Thanks again.

**Comment by mikepenz** [comment]
@Thore1954 if you also just want to modify everything around the `RecyclerView` which hosts the `DrawerItem`s you could also do this like shown in the `EmbeddedDrawer` sample.
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/EmbeddedDrawerActivity.java

This will require you to handle all the `DrawerLayout` stuff on your own though.
