### ISSUE TITLE
same MaterialDrawer for multiple ativities

### ISSUE THREAD

**Issue by MostafaEbrahimi** [mikepenz/MaterialDrawer#1535]
How can I set same MaterialDrawer for multiple activity?
can you give me a sample ?[In some issues you said by helper class but I don't know how]

**Comment by mikepenz** [comment]
@MostafaEbrahimi the `Drawer` object can't be reused. But the code can. So you will have a static util class which will host the code which is required to build the drawer, and takes the activity, the toolbar, the current selected item as argument. And you just call this method everywhere, where you need the drawer..

**Comment by Rainer-Lang** [comment]
@mikepenz Is thete a sample?

**Comment by MostafaEbrahimi** [comment]
@mikepenz thanks.I handle it using my implementation of navigation drawer and fragment.

**Comment by LOG-TAG** [comment]
is there any way to do like this https://github.com/ddekanski/BottomNavigationViewBetweenActivities ? I know navigation drawer and fragment is recommended but while working on the 4year old project update it's really helpful!

**Comment by MostafaEbrahimi** [comment]
it is not hard to convert activities to fragments.
I recommend you to using [FragNav](https://github.com/ncapdevi/FragNav)

**Comment by LOG-TAG** [comment]
@MostafaEbrahimi  completely agree with you! (it's actually client's demand to not complete rework on the app minor SDK updates, butterknife dependency update cousing lot of issue while we use child activities extending parent activity)
