### ISSUE TITLE
Toolbar title does not show if using Fragments

### ISSUE THREAD

**Issue by ishaan-khan** [mikepenz/MaterialDrawer#1536]
Hi,
Let me start by thanking you for this amazing library. Everything seems to be working fine if I work with activities but if I use a fragment the toolbar title as well as the drawer toggle icon disappears. I tried a few things like removing the toolbar from drawer, setting the toolbar title again but nothing seems to workout. Any ideas?

Much appreciated

**Comment by mikepenz** [comment]
@ishaan-khan the `MaterialDrawer` does not interact with the `Toolbar` the only thing it does is to set the `ActionbarDrawerToggle` on the `Toolbar` (if supplied). 

Perhaps you have to set the title on your own or so?
Do you have the toolbar within the fragment?


This issue is not library related

**Comment by ishaan-khan** [comment]
Appreciate your reply. You are right, there was something wrong with another class which was overriding the default Toolbar and its attribute, my bad :P.
Thanks again.
