### ISSUE TITLE
Account indicator not visible on API 16

### ISSUE THREAD

**Issue by rubengees** [mikepenz/MaterialDrawer#1538]
Consider the following screenshots:

![bildschirmfoto von 2016-09-20 15-14-36](https://cloud.githubusercontent.com/assets/8021265/18671606/0dda8a04-7f45-11e6-8349-25c0d48d9b2c.png)

How it should be: API 17

![bildschirmfoto von 2016-09-20 15-15-25](https://cloud.githubusercontent.com/assets/8021265/18671608/0f3e673a-7f45-11e6-87d9-a1a2f3725970.png)

Indicator missing: API 16

As you can see, the indicator is missing on API level 16. On everything above, it is there (I tested 17, 19 and 24).

I build my `AccountHeader` like this:

```java
new AccountHeaderBuilder()
        .withActivity(context)
        .withCompactStyle(true)
        .withHeaderBackground(R.color.colorPrimary)
        .withOnAccountHeaderListener(...)
        .withSavedInstance(savedInstanceState)
        .withProfiles(generateAccountItems(context))
        .build();
```

![bildschirmfoto von 2016-09-20 15-25-30](https://cloud.githubusercontent.com/assets/8021265/18671945/5709eb42-7f46-11e6-9fc7-6d83ddf4ba61.png)

As the layout bounds in this screenshot show, it seems to be there, but not showing.

**Comment by rubengees** [comment]
I investigated further and this just seems to happen on the x86 variant of the API 16 emulator. It does *not* happen on arm API 16 nor on a genymotion emulator.
Maybe a bug of the emluator?

**Comment by mikepenz** [comment]
@rubengees yes that could be the cause. Never saw this problem on a real device or on anything else. And I tested it (and others) quite a lot.

**Comment by rubengees** [comment]
I debugged the relevant code snippet and the `ImageView` is visible and has the image set (with height and width > 0). I think this can be safely ignored...

**Comment by mikepenz** [comment]
Ok great
