### ISSUE TITLE
Action Header in Navigation Drawer

### ISSUE THREAD

**Issue by MohitKhaitan** [mikepenz/MaterialDrawer#1539]
Hello Mike, thanks a lot for creating such a wonderful library. I want to know how can we fix the header and scroll the other navigation items under it. Please help !

**Comment by mikepenz** [comment]
@MohitKhaitan you want a `StickyHeader`. Just use the `withStickyHeader` or `withAccountHeader(..., true)` (https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L473) methods

**Comment by MohitKhaitan** [comment]
Thanks alot :)
