### ISSUE TITLE
Failed to resolve 'com.mikepenz.materialdrawer:library:2.5.7@aar'

### ISSUE THREAD

**Issue by laylizzlle** [mikepenz/MaterialDrawer#154]
Added compile('com.mikepenz.materialdrawer:library:2.5.7@aar') {
    transitive = true
}
To my dependencies and got this error

**Comment by mikepenz** [comment]
@laylizzlle the library is on maven central:
http://search.maven.org/#artifactdetails|com.mikepenz.materialdrawer|library|2.5.7|

perhaps you run in offline gradle mode? or anything else?
