### ISSUE TITLE
Custom colors for MaterialDrawer for dark theme are not working.

### ISSUE THREAD

**Issue by mddanishansari** [mikepenz/MaterialDrawer#1540]
I am opening this issue after a lot of experiments but the title suggests my problem "custom colors are not working". 

I have implemented 2 themes in my app(Light and Dark) and defined colors for MaterialDrawer for both the themes as guided in the repository. Colors for light theme works but when the user changes the app theme to dark the drawer remains light. Is there I am missing something ?

I know I am missing something minor but what is it ?
Ask me anything you want.
Thank you in advance @mikepenz

**Comment by mikepenz** [comment]
@mddanishansari if you change the theme during runtime the drawer would not reset all the colors again. 

How do you apply the changed style?

**Comment by mddanishansari** [comment]
Yes I'm changing the theme during runtime.

**Comment by mddanishansari** [comment]
I have a BaseActivity which extends AppCompatActivity and every other activity extend BaseActivity. It has the logic of toggling the app style.

**Comment by mddanishansari** [comment]
Also the parent in Dark style is MaterialDrawerTheme and the parent in Light style is MaterialDrawerTheme.Light.

**Comment by mikepenz** [comment]
@mddanishansari this does not work because the drawer loads the colors from the theme during initialization and not at a later time. You would have to "manually" update the colors, for the components which are not changed

**Comment by mddanishansari** [comment]
@mikepenz sir yes sir... 
ok last one what's the difference between withTextColorRes() and withTextColor().
What is that "Res" ? Resource ?

**Comment by mikepenz** [comment]
@mddanishansari yes. The `Res` takes the ressource identifier where the normal takes a the int value of a color already. 

for the items it should work if you just call `notifyItemsSetChanged` (or how it'S called)  on the adapter, just background and header color or so may be still an issue then

**Comment by mddanishansari** [comment]
@mikepenz thank you for your precious time sir. now you may close the portal I mean issue Lol..

**Comment by 7172** [comment]
need like nfc beem which can easily to make it activations
