### ISSUE TITLE
Using Fragments with Navigation Drawer

### ISSUE THREAD

**Issue by MohitKhaitan** [mikepenz/MaterialDrawer#1542]
Hello Mike, I wanted to open fragments on the click of the items in my navigation drawer, I am not able to figure out how to do it. Can you please help. how can I achieve it with your library.

**Comment by mikepenz** [comment]
@MohitKhaitan the MaterialDrawer gives you the events. You can then do whatever you want with them. 

Please look @ stackoverflow or so to read on how to handle fragments in android.

**Comment by MohitKhaitan** [comment]
Thank You Mike :)
