### ISSUE TITLE
Fragment not getting created after returning back from another activity

### ISSUE THREAD

**Issue by MohitKhaitan** [mikepenz/MaterialDrawer#1543]
Hi,
so, there in my Navigation Drawer I have several items. With some items i have attached a fragment and to some i have attached an activity. For eg, My Primary Nav Items are attached with Fragments and Secondary Nav Items are directed to respective activities. So, when i come back from the activity of secondary items, it shows a blank screen with the toolbar. What i want is to get back to the last fragment is was in or the home fragment. How can i achieve this. Please help !!

**Comment by mikepenz** [comment]
@MohitKhaitan you can first activate https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L782 which will trigger the listener when the `DrawerBuilder` is created. 

Afterwards. Why do you remove the fragment from the `Activity` when the `Activity` is paused? normally you do not have to re-commit the ragment for an activity `onResume`

but this is not related to the library. And you may ask the same question on StackOverflow with some code example.

**Comment by MohitKhaitan** [comment]
Yes I have already activated the function and also I am not removing the fragment. But still I am getting this blank screen

**Comment by mikepenz** [comment]
@MohitKhaitan as the Drawer does not manage the fragments, it has to be related to your code somewhere. Perhaps you can just try it out without the drawer, if it still happens head over to stackoverflow, if not then you should probably send some code so I can check what you are doing

**Comment by MohitKhaitan** [comment]
`navDrawer = new DrawerBuilder()
                .withActivity(this)
                .withSelectedItem(0)
                .withToolbar(toolbar)
                .withAccountHeader(accountHeader, true)
                .withShowDrawerOnFirstLaunch(true)
                .withTranslucentStatusBar(false)
                .withFireOnInitialOnClick(true)
                .addDrawerItems(
                        item0,
                        item1,
                        item2,
                        item3,
                        item4,
                        item5,
                        item6,
                        item7,
                        item8,
                        new SectionDrawerItem().withName("Information"),
                        item9,
                        item10,
                        item11,
                        item12
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {

                        Intent drawItem;

                        fragmentManager = getSupportFragmentManager();
                        fragmentTransaction = fragmentManager.beginTransaction();
                        fragmentTransaction.setCustomAnimations(android.R.anim.fade_in,android.R.anim.fade_out);
                        fragment = new Fragment();

                        switch (position) {
                            case 0:
                                fragment = new HomeFragment();
                                toolbar.setTitle("Home");
                                Toast.makeText(getApplicationContext(), "Home", Toast.LENGTH_SHORT).show();
                                break;
                            case 1:
                                fragment = new MessageFragment();
                                toolbar.setTitle("Message");
                                Toast.makeText(getApplicationContext(), "Messages", Toast.LENGTH_SHORT).show();
                                break;
                            case 2:
                                fragment = new EventFragment();
                                toolbar.setTitle("Events");
                                Toast.makeText(getApplicationContext(), "Events", Toast.LENGTH_SHORT).show();
                                break;
                            case 3:
                                fragment = new CabCarFragment();
                                toolbar.setTitle("Cab/Car");
                                Toast.makeText(getApplicationContext(), "Cab/Car", Toast.LENGTH_SHORT).show();
                                break;
                            case 4:
                                fragment = new GroupManagementFragment();
                                toolbar.setTitle("Group Management");
                                Toast.makeText(getApplicationContext(), "Group Management", Toast.LENGTH_SHORT).show();
                                break;
                            case 5:
                                fragment = new AddLocationFragment();
                                toolbar.setTitle("Add Location");
                                Toast.makeText(getApplicationContext(), "Add Location", Toast.LENGTH_SHORT).show();
                                break;
                            case 6:
                                fragment = new EmergencyServiceFragment();
                                toolbar.setTitle("Emergency");
                                Toast.makeText(getApplicationContext(), "Emergency Services", Toast.LENGTH_SHORT).show();
                                break;
                            case 7:
                                fragment = new ChatFragment();
                                toolbar.setTitle("Chat");
                                Toast.makeText(getApplicationContext(), "Chat", Toast.LENGTH_SHORT).show();
                                break;
                            case 8:
                                fragment = new ReportFragment();
                                toolbar.setTitle("Report");
                                Toast.makeText(getApplicationContext(), "Report", Toast.LENGTH_SHORT).show();
                                break;
                            case 10:
                                drawItem = new Intent(getApplicationContext(), SettingActivity.class);
                                startActivity(drawItem);
                                Toast.makeText(getApplicationContext(), "Settings", Toast.LENGTH_SHORT).show();
                                break;
                            case 11:
                                drawItem = new Intent(getApplicationContext(), AboutUsActivity.class);
                                startActivity(drawItem);
                                Toast.makeText(getApplicationContext(), "About Us", Toast.LENGTH_SHORT).show();
                                break;
                            case 12:
                                drawItem = new Intent(getApplicationContext(), PrivacyPolicyActivity.class);
                                startActivity(drawItem);
                                Toast.makeText(getApplicationContext(), "Privacy Policy", Toast.LENGTH_SHORT).show();
                                break;
                            case 13:
                                drawItem = new Intent(getApplicationContext(), ContactUsActivity.class);
                                startActivity(drawItem);
                                Toast.makeText(getApplicationContext(), "Contact Us", Toast.LENGTH_SHORT).show();
                                break;
                        }

                        fragmentTransaction.replace(R.id.flFragments, fragment);
                        fragmentTransaction.commitAllowingStateLoss();

                        return false;
                    }
                }).build();`

This is my Nav Drawer Code. Case 10,11,12,13 have intents, and the rest are associated with fragments. So when any case between 10-13 are triggered, a new activity opens and on pressing back button from the activity i get back to the main activity where i have my Nav Drawer, so there i want to show the HomeFragment, but i am getting a blank screen with the toolbar title of the last nav item pressed.

**Comment by mikepenz** [comment]
@MohitKhaitan it is really simple. you will commit an empty fragment if you launch an activity as 
```java
fragmentTransaction.replace(R.id.flFragments, fragment);
fragmentTransaction.commitAllowingStateLoss();
```
is always executed... (even if you just open an activity)

**Comment by MohitKhaitan** [comment]
Thank you Mike. I solved my problem. I created a fragment at the time of onResume(). So after coming back from an activity it points to my HomeFragment, which is what I wanted. 
Thank You for your help :)
