### ISSUE TITLE
MiniDrawer doesn't have a background color?

### ISSUE THREAD

**Issue by NickM-27** [mikepenz/MaterialDrawer#1544]
Hello, just starting to use the mini drawer and while the standard drawer has a white background, when I slide to the mini drawer it is completely transparent. Any easy option I'm missing or is this a bug?

Thanks!

**Comment by mikepenz** [comment]
@NickM-27 the `MiniDrawer` is normally shown in an activity which already has an background, and will only differ from it via the shadow. 

If you want it to have a different color you can should just set it on the `View` returned by `build`
