### ISSUE TITLE
How I can change the color of selection the icon?

### ISSUE THREAD

**Issue by AlexanderArtemov** [mikepenz/MaterialDrawer#1545]
How I can change this a little-blue color?

Regards,
Alexander
![b4ca3qdmjr0](https://cloud.githubusercontent.com/assets/20964877/18803141/30b388f6-81f6-11e6-88e6-5a3c2cd744d2.jpg)

**Comment by mikepenz** [comment]
@AlexanderArtemov the default placeholder icon is defined via the `DrawerImageLoader`. You can either overwrite it or keep the default. 

The default uses the accent and primary color.

https://github.com/mikepenz/MaterialDrawer/blob/b2260bf5b514c1cbdabbaf7eb39397b5e7d573fe/library/src/main/java/com/mikepenz/materialdrawer/util/DrawerUIUtils.java#L94
