### ISSUE TITLE
ExpandableDrawerItem-> onClick - > no auto scroll for Navigation Drawer

### ISSUE THREAD

**Issue by alok96** [mikepenz/MaterialDrawer#1548]
Hello Mike, hope you are doing well.
i have a custom setting option with expandable list in the end of the navigation drawer, when i click on settings arrow. it doesn't autoscroll to show the list items.
vice versa when i click on expandable arrow when list is expanded, it autoscrolls.

please try to resolve my issue
thank you

**Comment by alok96** [comment]
here i my code

new ExpandableDrawerItem().withArrowColorRes(R.color.white)
                                .withName("Settings")
                                .withLevel(1)
                                .withIdentifier(7)
                                .withTextColorRes(R.color.white)
                                .withSelectable(false)
                                .withSubItems(new SecondaryDrawerItem()
                                                .withName("Backroom")
                                                .withTextColorRes(R.color.white)
                                                .withLevel(8)
                                                .withIcon(R.drawable.ic_backroom)
                                                .withIdentifier(2000),
                                        new SecondaryDrawerItem()
                                                .withName("Profile")
                                                .withTextColorRes(R.color.white)
                                                .withLevel(8)
                                                .withIcon(R.drawable.ic_profile)
                                                .withIdentifier(2001)
                                )
                )

**Comment by mikepenz** [comment]
@alok96 the `MaterialDrawer` nor the `FastAdapter` has a feature built in which will autoscroll. If you need this. just use the `scrollTo` method from the `RecyclerView` and scroll to the wished position

**Comment by mikepenz** [comment]
https://www.google.at/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=off&q=scroll+to+recyclerview

**Comment by alok96** [comment]
Thank you Mike for your kindness :)
