### ISSUE TITLE
Allow android.widget.Toolbar as well as the support version.

### ISSUE THREAD

**Issue by Glurt** [mikepenz/MaterialDrawer#1549]
I'm probably in the minority here but my min sdk is high enough for me to be able to use the framework version of the Toolbar and not the support. The only issue is that the DrawerBuilder's .withToolbar() method only takes a support Toolbar, do you think there is room for both?

**Comment by mikepenz** [comment]
@Glurt the `MaterialDrawer` uses the support version of the `Toolbar` and also the `ActionBarDrawerToggle` from the support libraries. 

Providing the `Toolbar` is just a small helper so you don`t have to put the `ActionBarDrawerToggle` on your own. But in your case you can simply do this, and hook it together with the `RecyclerView`

A small side-note. Even if you have a high enough API level. It is still a good idea to use the support lib versions as those will get updates, and fixes and improvements. And the framework included components won't.

**Comment by Glurt** [comment]
> A small side-note. Even if you have a high enough API level. It is still a good idea to use the support lib versions as those will get updates, and fixes and improvements. And the framework included components won't.

Unfortunately the YouTube library has kind of forced my hand, I need to extend YouTubeBaseActivity which itself extends Activity so only the framework Toolbar is supported. My options are use the framework Toolbar, beg Google to add an AppCompat version or deal with AppCompatDelegate. 

Thanks for the advice though, I'll definitely consider using the support Toolbar.
