### ISSUE TITLE
Navbar and content position

### ISSUE THREAD

**Issue by iHombre** [mikepenz/MaterialDrawer#155]
Without MaterialDrawer:
![2015-03-26_125917](https://cloud.githubusercontent.com/assets/9828409/6843922/4b9bf8bc-d3b8-11e4-8d91-fd533c52df22.png)
But with him:
![2015-03-26_130106](https://cloud.githubusercontent.com/assets/9828409/6843923/4ba0d85a-d3b8-11e4-800c-20eb8f327f92.png)

**Comment by mikepenz** [comment]
@iHombre the MaterialDrawer injects the DrawerLayout to the root of your view hirachy. if you have any special attributes other than match_parent it will probably break. 

Can you add additional infos about your layout ?

**Comment by iHombre** [comment]
If set android:windowTranslucentNavigation to false (now true) then my layout work fine, but of course without transparent. layout_height,layout_width - match_parent. My layout here: http://pastebin.com/C347iVpi

**Comment by mikepenz** [comment]
@iHombre so it seems it's an issue with the translucentNavigation. I will try to reproduce it within the sample application

**Comment by R0ns3n** [comment]
Just updated to 2.6.0 and now my layout is incorrect.
My layout
```xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <android.support.v7.widget.Toolbar
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="?attr/colorPrimary"/>

        <FrameLayout
            android:id="@+id/frame_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
</LinearLayout>
```
Issue is the space between frame and bottom navigation bar
![screenshot_2015-03-27-09-56-30](https://cloud.githubusercontent.com/assets/5932065/6864942/8652c9a8-d468-11e4-8cfd-8628465c1c0e.png)

**Comment by mikepenz** [comment]
@R0ns3n  yeah i made a small mistake with the new option if you have a translucent navigationbar. missed to change the defaultvalue to false 

https://github.com/mikepenz/MaterialDrawer/issues/161

temp fix. set `withTranslucentNavigationBar(false)`

**Comment by R0ns3n** [comment]
Oh, thanks. I should better read the issues before posting. Sorry for that.
