### ISSUE TITLE
How to make the status bar  transparent fully when the drawer is pulled out?

### ISSUE THREAD

**Issue by VersaceSilva** [mikepenz/MaterialDrawer#1550]
I just want to make the status bar transparent fully when the drawer is pulled out,but how  to do this? Could you please tell me?

**Comment by mikepenz** [comment]
@VersaceSilva the shadow comes from the `fitSystemWindow`s flag automatically from the `DrawerLayout`. What result do you wanna get?

**Comment by VersaceSilva** [comment]
@mikepenz I just want to remove the shadow,is there a method?

**Comment by mikepenz** [comment]
As mentioned it is not related to the library. But on the way how the system handles the `fitsSystemWindow`s flag. 

This may help already: http://stackoverflow.com/questions/26745300/navigation-drawer-semi-transparent-over-status-bar-not-working
