### ISSUE TITLE
Id's for drawer items

### ISSUE THREAD

**Issue by alok96** [mikepenz/MaterialDrawer#1551]
Hello mike,
is there is anyway to set the ID's of drawer items

```java
new PrimaryDrawerItem()
                                .withName(R.string.personal_profile)
                                .withTextColorRes(R.color.white)
                                .withIcon(R.drawable.ic_personal_profile_menu)
                                .withIdentifier(1).withSelectable(false),
```

i want to set the id for the specific drawer item, i have to change the language of the string personal profile, without loading my view.
Thanks 
Alok

**Comment by mikepenz** [comment]
@alok96 I am not sure what you are trying. 

There is a section about updating `DrawerItem`s in an already built drawer in the README

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

**Comment by alok96** [comment]
Thanks Mike for your Kindness
