### ISSUE TITLE
Adding items on click of the spinner in AccountHeader

### ISSUE THREAD

**Issue by MohitKhaitan** [mikepenz/MaterialDrawer#1552]
Hello Mike, I have been trying to add a Logout button on the Nav Drawer after the user clicks on the spinner on the Account Header. By default, on clicking the Account Header I am only shown the email address of the user. I want to add items to that list as well. How can I do that ? Please Help !

**Comment by mikepenz** [comment]
You have to provide a `OnAccountHeaderSelectionViewClickListener` and listen to it's click. 

If you want to add items to the `AccountHeader` just use the provided methods as you would for the `Drawer`.

**Comment by MohitKhaitan** [comment]
Where do I provide the methods ? Like in Drawer we used `addDrawerItems()` and in here we pass the items. Like wise where should I pass the items in AccountHeader ?

**Comment by mikepenz** [comment]
the `AccountHeader` has similar methods adding the elements inside the list when you open the accounts. 

What do you mean?

**Comment by MohitKhaitan** [comment]
My query is solved Mike, Thank You. I wanted to use `ProfileSettingsDrawerItem()` . Your Library is totally fun to use. It can do wonders ;) :D

**Comment by mikepenz** [comment]
Awesome :)
