### ISSUE TITLE
How to allign long text to the bottom of the drawer?

### ISSUE THREAD

**Issue by sekeww** [mikepenz/MaterialDrawer#1554]
Hi, thank you for your library and FAQs.
I am just a newbee in github and android studio as well, but could you please help to find out how can I place a textView in the bottom of the Navigation drawer using your library? I tried to use SectionDrawerItem() but it cuts my long string and it is also not on the bottom. Thank you.
![image](https://cloud.githubusercontent.com/assets/20298879/18885906/7645faea-850f-11e6-99ac-553b336c170a.png)

**Comment by mikepenz** [comment]
@sekeww you should create a `CustomDrawerItem` for this. Similar to the `SectionDrawerItem` but which has a dynamic height. 

More infos here: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md

Thank you
