### ISSUE TITLE
[Question]  How to make sticky session item ?

### ISSUE THREAD

**Issue by mdtuyen** [mikepenz/MaterialDrawer#1555]
As I see in the library, we can make header sticky, footer sticky but I want session item sticky. Is it support ?
Example:
`new SectionDrawerItem().withName(R.string.drawer_item_section_header).withSticky(true)`

More:
I want content of actvity move to right when drawer slide to alway show navigation icon. May I make it easy with the lib ?

**Comment by mikepenz** [comment]
@mdtuyen 
I am not sure what you mean. What is a `session item`? There are no sticky section headers if you mean this. And there is no plan to support such

the later is not possible with the default `DrawerLayout` as far as I know. If there is an alternative `DrawerLayout` library you may can use this in combination with this lib.

**Comment by mdtuyen** [comment]
Hi @mikepenz 
If number of item in drawer too long, I think it is better is make each session (group of item) sticky same with Sticky Recycler

With second question, I see it in [sliding menu ](https://github.com/jfeinstein10/SlidingMenu).

**Comment by mikepenz** [comment]
@mdtuyen there is no option for sticky items. Just the header and footer. You can have expandable items?

The sliding menu is no `DrawerLayout` it is a custom `RelativeLayout` which is something else..

**Comment by mdtuyen** [comment]
Hi @mikepenz Thanks for your answers.
