### ISSUE TITLE
How to remove the image icon (account) from the navigation?

### ISSUE THREAD

**Issue by edesdan** [mikepenz/MaterialDrawer#1557]
Hi, I'm not using the navigation with an account so I would like to remove the image button. Is there a way? I would like just the background color.

<img width="365" alt="screenshot" src="https://cloud.githubusercontent.com/assets/5745049/18936937/c7da5ad4-85e3-11e6-9b73-f61c2077ca3a.png">

**Comment by mdtuyen** [comment]
Dont use AccountHeader, you can custom any View as header with `withHeader`  (not `withAccountHeader`)

**Comment by mikepenz** [comment]
@mdtuyen thanks for answering. 

@edesdan as pointed out. Please just use a normal header.

**Comment by edesdan** [comment]
OK I'll do that, thanks!
