### ISSUE TITLE
Could not find method publish() for arguments [....]

### ISSUE THREAD

**Issue by rajukiran** [mikepenz/MaterialDrawer#1562]
Hi,

I would like to configure the library what you designed to develop this MaterialDrawer. But i'm unable to import as a module to another application. Can you please help me to resolve this issue?

I got and error like below when i tried to import.

Error:Could not find method publish() for arguments [gradle_jcenter_push_2iqpn5evjxppvds7i5uj5jq7j$_run_closure1@612adc8b] on project ':library' of type org.gradle.api.Project.

Thanks & Regards.

**Comment by mikepenz** [comment]
It is not recommended to use the library as module. Please just use the gradle dependency. 

Otherwise you have to modify the build.Gradle. To be able to compile it as module in your project. I can't give support for this
