### ISSUE TITLE
Header Background Image memory error

### ISSUE THREAD

**Issue by kriskast** [mikepenz/MaterialDrawer#1563]
Hello Mike, first of all thanks for this great library :D

I just notices something from the device monitor. using `.withHeaderBackground(R.drawable.navigation)` where the drawable is a 800x450 541kb png file the app uses 30mb of ram, with that line commented out it uses 10mb of ram...

Is there something I can from my end to reduce this usage? as devices with small memory quickly get an oom exception

Thanks

**Comment by mikepenz** [comment]
@kriskast please make sure your image is small enough and in the correct size. If it is bigger. You might want to use a image loader like `Glide` which will handel this for you. 

The error is not related to this library.
