### ISSUE TITLE
Back button not working

### ISSUE THREAD

**Issue by jidesoft** [mikepenz/MaterialDrawer#1565]
I tried to enable the back button by calling the following two lines. I noticed an issue.
  
drawerBuilder.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false);                
actionBar.setDisplayHomeAsUpEnabled(true);

The back button is shown but tapping on the back button shows the drawer instead of triggering the android.R.id.home as the real back button. What's the API to set the back button action? Thanks.

**Comment by mikepenz** [comment]
@jidesoft the back button behavior has nothing to do with the `MaterialDrawer` that's completely independent and up to you. 

In general it makes sense to have something like this:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L243

And probably also like this:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MenuDrawerActivity.java#L49

**Comment by mikepenz** [comment]
Ah you want to have the back arrow shown instead the hamburger icon?

Then you need these two lines:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CompactHeaderDrawerActivity.java#L109

**Comment by jidesoft** [comment]
I debugged into your source code and found tapping on the back button still triggers toolbarNavigationListener defined in the handleDrawerNavigation method. Could it be the issue? As the button is now a back button, it should fire android.R.id.home menu action.

**Comment by mikepenz** [comment]
shouldn't be an issue

**Comment by ericsegovia** [comment]
I have the same issue as @jidesoft , the back button triggers the drawer.

**Comment by constantinoschristoforou** [comment]
Same issue here

**Comment by rtchagas** [comment]
One year later and same issue here. Did anybody find a workaround?

**Comment by mikeuv** [comment]
huh same problem

**Comment by ardevd** [comment]
Same issue

**Comment by griff-kodexx** [comment]
Found a solution to this here: https://stackoverflow.com/a/36677279
