### ISSUE TITLE
Update badge

### ISSUE THREAD

**Issue by tohasvs** [mikepenz/MaterialDrawer#1566]
Hi,

I use MiniDrawer, and i can't to update badge:

<img width="77" alt="update_badge" src="https://cloud.githubusercontent.com/assets/1631940/19151677/a87c002c-8bd6-11e6-8532-df077871fa14.png">

**Comment by mikepenz** [comment]
@tohasvs you have to notify the `MiniDrawer` that the item was changed:

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L425

**Comment by tohasvs** [comment]
Okay, thanks. But how to update icon ?
![image](https://cloud.githubusercontent.com/assets/1631940/19156501/c2765540-8bea-11e6-9d2a-0dbd76c763c3.png)

**Comment by mikepenz** [comment]
Should work via the same method. Otherwise use `createItems()`
