### ISSUE TITLE
Does Material Drawer have HTML support?

### ISSUE THREAD

**Issue by NickM-27** [mikepenz/MaterialDrawer#1567]
I set a primary drawer item with HTML but it doesn't show correctly on the drawer? Is there a way to enable this functionality? It is an integral part of my apps.

Thanks!

**Comment by mikepenz** [comment]
@NickM-27 no the default items do not support this. you can create a `CustomDrawerItem`  which takes html text and highlights it. 

Otherwise there are no plans to add something like this.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md
