### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by emreaktrk** [mikepenz/MaterialDrawer#1568]
Hi Mike,

Thanks for great library. I am a big fan of it.

I need assistance about an implementation which is opens like mini drawer (for example 50dp of drawer) when action bar toggle and goes default width when pan gesture.

Am i able to do that with this great library? If so how? The mini drawer layout is same as default drawers left side.

Cya

**Comment by mikepenz** [comment]
@emreaktrk please check the `MiniDrawerActivity` of the sample activity:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java

**Comment by mikepenz** [comment]
Thank you very much
