### ISSUE TITLE
MultiAccounts from AccountManager

### ISSUE THREAD

**Issue by alorma** [mikepenz/MaterialDrawer#157]
Hi.

Is there any plan to use the System Account, from AccountManager to get the accounts?

**Comment by mikepenz** [comment]
@alorma Yeah if we do not need to add those permissions (which are required for this feature) to the library and create it without any additional permissions this would be awesome :D

**Comment by badoualy** [comment]
@mikepenz Simple question here, this feature would be nice, wouldn't it be possible to do it using a test ? Having one entry point to fetch and add accounts from AccountManager IF the application has the permissions ? (this can be tested at runtime). And if the app does not have the permissions, throw an exception.

This way :
- The developer included the permissions inside his application manifest and can use the feature
- The developer doesn't care about this feature and doesn't add the permissions, and doesn't use the feature
- And if he tries to use them without the permissions, an exception will be thrown

**Comment by mikepenz** [comment]
@badoualy if you have some experience with the accountManager you can add a new helper to manage this as pull request if you like ;)

**Comment by badoualy** [comment]
@mikepenz By coincidence, I had to do some research on this for my work. From what i saw, the only things you can easily get is the account name (email for google etc). And if you want some extra data you have to get an authToken and make some calls.
This would also means include some external libraries in this one (like retrofit to fetch picture) and also implement a different code for each kind of accounts.

Sadly, i don't have the time to do all of this currently.

**Comment by githubbucah** [comment]
Hi, when I switch to another account, the info changes but account header stays the same. Can you say why? Thanks

**Comment by mikepenz** [comment]
@githubbucah you should open a separat issue for this.

**Comment by livotov** [comment]
Suppose we can use some kind of custom account header builder, which will build the profiles list with accounts, taken from the system. Most likely we'll be doing that in our app, so if there are no objectives from the @mikepenz , I can create a pull request then (when we're finished with this)

**Comment by mikepenz** [comment]
@livotov at the moment i have no plans. but sounds awesome ;)

Let me know if you have something

**Comment by Anatidae-Project** [comment]
In about a month, I'll be doing an OAuth using Google's login services. I'll try and do all my stuff in a stand-alone module and put it up for others. I'll be using this drawer (best repo out there, thanks Mike!).

**Comment by mikepenz** [comment]
@Anatidae-Project would be great if you could do it as additional modul here so more people will see it and it is easier to keep it up to date and in sync with the upstream MaterialDrawer

**Comment by raghunandankavi2010** [comment]
@mikepenz if we need to use this android.permission.GET_ACCOUNTS the we need permission from user. http://developer.android.com/guide/topics/security/permissions.html#normal-dangerous. 
I am also curious as I saw a issue posted by another user about animating profile icons when switching between accounts just like inbox. Have you come up with any idea??

**Comment by mikepenz** [comment]
@raghunandankavi2010 yes. If someone wants to do a PR adding AccountManager support i expect this to be a helper class which just fills the AccountHeader with the profiles. Shouldn't require a deep integration into any existing classes. 

Regarding the animation. https://github.com/mikepenz/MaterialDrawer/issues/909#issuecomment-168297253

**Comment by mikepenz** [comment]
Close. I'm still open for a PR in this area, but at the moment there is no huge interest in this addition
