### ISSUE TITLE
ProfileDrawerItem.withNameShown() does not make clear where this flag takes effect

### ISSUE THREAD

**Issue by mpost** [mikepenz/MaterialDrawer#1570]
The property `withNameShown` only applied to the account switcher which is not obvious from reading the property name or javadoc. Only from reading the code was that distinction clear.

The method should be renamed to `withNameShownInSwitcher` or the javadoc should make clearer what is going on.

Great library btw. :)

**Comment by mikepenz** [comment]
@mpost this not only reflects in the switcher, but also in the item in the list itself:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L218

if you set this make sure you do not forget about calling `updateProfile` on the `AccountHeader`

**Comment by mikepenz** [comment]
Thank you very much

**Comment by mpost** [comment]
I am not completely sure where there distinction between the switcher and the "list" is but setting the name to not show up still shows the name in the header itself.

I am setting the property when creating the `ProfileDrawerItem` and adding the profile.

**Comment by mikepenz** [comment]
Ah you were referring to the list, and not to the switch in the header. I see. If you want, you could open a PR making the javadoc a bit clearer about this ;)

Thank you

**Comment by mpost** [comment]
PR incoming: https://github.com/mikepenz/MaterialDrawer/pull/1571
