### ISSUE TITLE
Navigation Drawer disappears along with action bar if home button on the device is pressed?

### ISSUE THREAD

**Issue by Albean** [mikepenz/MaterialDrawer#1573]
Hi,
When i press the home button on the device  it brings me back to  the home screen on the device. When i click on the app icon to open it again , the navigation drawer and actionbar are gone? 

To have the navigation Drawer and actionbar appear again i have press the back button on the device.

Thanks,

**Comment by mikepenz** [comment]
Seems like you have some wrong activity launching with your launcher shortcut. 

As the ActionBar also disappears. This is for sure no library issue.
