### ISSUE TITLE
Bug Report: Header Image Does Not Appear On HTC One M8 Device

### ISSUE THREAD

**Issue by ZacharyDavidSaunders** [mikepenz/MaterialDrawer#1576]
Hello. I believe that I have found a bug regarding header image system. I would appreciate if you would review the following data and help me determine if this is, in fact, a bug.

### Observed Problem:

When the attached header image is used as the drawer header image, the image does not appear on HTC One M8 device. However, when the same code is run on a Motorola G4 device, Nexus 5 and Nexus 6P emulations, the image is correctly displayed.

### My Code:

    public static void createDrawer(final Activity activity)
    {
        currentActivity = activity;
        final PrimaryDrawerItem item1 = new PrimaryDrawerItem().withIdentifier(1)
                                                         .withName(menuOption1)
                                                         .withTextColor(unselectedLabelColor)
                                                         .withSelectedTextColor(selectedLabelColor)
                                                         .withDescription(menuOption1Description);

        final PrimaryDrawerItem item2 = new PrimaryDrawerItem().withIdentifier(2)
                                                         .withName(menuOption2)
                                                         .withTextColor(unselectedLabelColor)
                                                         .withSelectedTextColor(selectedLabelColor)
                                                         .withDescription(menuOption2Description);

        final PrimaryDrawerItem item3 = new PrimaryDrawerItem().withIdentifier(3)
                                                         .withName(menuOption3)
                                                         .withTextColor(unselectedLabelColor)
                                                         .withSelectedTextColor(selectedLabelColor)
                                                         .withDescription(menuOption3Description);

        final PrimaryDrawerItem item4 = new PrimaryDrawerItem().withIdentifier(4)
                                                         .withName(menuOption4)
                                                         .withTextColor(unselectedLabelColor)
                                                         .withSelectedTextColor(selectedLabelColor)
                                                         .withDescription(menuOption4Description);

        final PrimaryDrawerItem item5 = new PrimaryDrawerItem().withIdentifier(5)
                                                         .withName(menuOption5)
                                                         .withTextColor(unselectedLabelColor)
                                                         .withSelectedTextColor(selectedLabelColor)
                                                         .withDescription(menuOption5Description);

        AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(activity)
                .withHeaderBackground(R.drawable.drawer_header_background_image)
                .addProfiles(
                        new ProfileDrawerItem().withName(UserInformation.getName()).withEmail(UserInformation.getEmail())
                )
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener()
                {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile)
                    {
                        return false;
                    }
                })
                .withSelectionListEnabledForSingleProfile(false)
                .build();
        
        Drawer drawer = new DrawerBuilder()
                .withActivity(activity)
                .withAccountHeader(headerResult)
                .withHeaderPadding(true)
                .withCloseOnClick(true)
                .addDrawerItems(
                        new DividerDrawerItem(),
                        item1,
                        new DividerDrawerItem(),
                        item2,
                        new DividerDrawerItem(),
                        item3,
                        new DividerDrawerItem(),
                        item4,
                        new DividerDrawerItem(),
                        item5
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener()
                {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem)
                    {
                        switch((int)drawerItem.getIdentifier())
                        {
                            case (1):
                                        //... (so on and so forth)

### Project Structure:
![image](https://cloud.githubusercontent.com/assets/14244868/19290007/4babd4a4-8fc2-11e6-94ce-0c53c77a826d.png)

### Header Image:

![drawer_header_background_image](https://cloud.githubusercontent.com/assets/14244868/19289049/b5bff4f6-8fbd-11e6-8147-05b3a7d65e8b.jpg)

### Nexus 6P Emulator Screenshot:
![image](https://cloud.githubusercontent.com/assets/14244868/19289593/55097562-8fc0-11e6-8355-a1818e889f67.png)

### HTC One M8 Screenshot:
<img src="https://cloud.githubusercontent.com/assets/14244868/19289744/0cfc5d60-8fc1-11e6-95e1-00cc71509d37.png" alt="HTC One M8 Screenshot" width="465px" height="800px">

## HTC One M8 Device Details:
* Android Version: 6.0
* HTC Sense Version: 7.0
* Software Version: 6.21.605.3
* Kernel Version: 3.4.0-perf-g4c1aa5c and@AABM #1 SMP PREEMPT
* Baseband Version: 1.14.20.0930
* Build Version: 6.21.605.3 CL708022 release-keys
* Android Security Patch Level: 2016-02-01
* Software Status: Official
* Configuration Version: L14.HTC.HTC6525LVW.0

**Comment by mikepenz** [comment]
@ZacharyDavidSaunders could you please try to lower the resolution of this image? And if it works then?

In general the `Header` uses a normal `ImageView` and set's the image via the normal `set` method

**Comment by ZacharyDavidSaunders** [comment]
@mikepenz Yes, that seems to have fixed the problem...Thank you.
