### ISSUE TITLE
How does not closing drawer after click on SwitchDrawerItem?

### ISSUE THREAD

**Issue by zigzag-mobile** [mikepenz/MaterialDrawer#1577]
When i use **withOnCheckedChangeListener()** of **SwitchDrawerItem**, after click on item - drawer closes.
How can i do to change that? For example: **OnDrawerItemClickListener** for **withOnDrawerItemClickListener()** i can return **TRUE**, but **onCheckedChanged** is void.

Thanks!

**Comment by mikepenz** [comment]
@zigzag-mobile you can't do this in the `onCheckedChanged` method as this is only triggered from the `switch` in the item. 

You should add a `OnDrawerItemClickListener` and catch this event there for these items. 

You can see that the default behavior is, that the `SwitchDrawerItem` has its click listener just forwarding the event to the switch and toggles it.
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/AbstractSwitchableDrawerItem.java#L80

**Comment by zigzag-mobile** [comment]
Thanks!
I resolve this when add `withOnDrawerItemClickListener() `for `DrawerBuilder`, but if i add `withOnDrawerItemClickListener()` directly for `SwitchDrawerItem`, `OnDrawerItemClickListener` not trigged.
