### ISSUE TITLE
Can I use headerbackground as a slider ?

### ISSUE THREAD

**Issue by PeterPhyo** [mikepenz/MaterialDrawer#1579]
I would like to use headerbackground as a slider those images come from api.

**Comment by mikepenz** [comment]
@PeterPhyo you can provide a `view` as a header, and create the behavior you want. This is unrelated to the `MaterialDrawer`

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L287
