### ISSUE TITLE
Black status bar when used with Contextual Action Bar

### ISSUE THREAD

**Issue by blork** [mikepenz/MaterialDrawer#158]
If the drawer is set to use a translucent status bar, when a Contextual Action Bar is triggered the status bar reverts to black.

![screen shot 2015-03-26 at 20 39 39](https://cloud.githubusercontent.com/assets/116228/6856483/4b5d0126-d3f8-11e4-8424-c44f5bb79daf.png)
Before triggering the CAB, blue status bar.

![screen shot 2015-03-26 at 20 39 52](https://cloud.githubusercontent.com/assets/116228/6856484/4b806706-d3f8-11e4-81a4-0f74ff932b7f.png)
After triggering the CAB, black status bar.

I have `windowActionModeOverlay` set to true in my theme so the CAB will overlay my toolbar, so I'm not sure why it doesn't just appear on top and leave the status bar as it was.

If `withTranslucentStatusBar(false)` is set, the status bar maintains its color, but looks pretty bad since it stays "on top" of the drawer. Perhaps there is something in the custom theme causing this? I'm using `MaterialDrawerTheme.Light.DarkToolbar`.

**Comment by mikepenz** [comment]
@blork as far as i can tell there's nothing inside the theme which should cause this issue. no special attributes set which modify something with the actionoverlay oder the CAB. does this also happen with a default appCompat theme? 

i think this should not have its root cause inside the drawer.

**Comment by blork** [comment]
@mikepenz I thought the same, but with a default theme (Base.Theme.AppCompat.Light) and no drawer, I don't see the issue.

**Comment by mikepenz** [comment]
@blork so it's probably related to the ScrimInsetsFrameLayout or the fullscreen style :/

**Comment by mikepenz** [comment]
@blork found a solution for your issue. You can now find the sample how to do it in the SimpleCompactHeaderActivity

WAs added with this commit:
https://github.com/mikepenz/MaterialDrawer/commit/78aabdc6aefc79d3ea51d9529ac71a12b72aec0a

**Comment by blork** [comment]
Thanks @mikepenz, https://github.com/mikepenz/MaterialDrawer/commit/78aabdc6aefc79d3ea51d9529ac71a12b72aec0a#diff-f37c77aad9859ecdc9b957f2a4c032f0R145 was the line I needed :+1:

**Comment by mikepenz** [comment]
@blork don't forget to set it Transparent again as soon as the CAB closes or you will loose the drawer below the statusbar effect

**Comment by giovi9907** [comment]
Is there a solution for api 20?

**Comment by mikepenz** [comment]
@giovi9907 sorry. i don't know of one
