### ISSUE TITLE
Android test

### ISSUE THREAD

**Issue by herau** [mikepenz/MaterialDrawer#1580]
I'd like to test my Activity, which contains a drawer component, with the espresso framework.
But the drawer component doesn't have any id or other stuff that allow to find the view and perform action on it. 

Do you have any advice to be able to test the component inside an Activity please ? 

Thanks

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/opening-drawer-from-espresso.md

**Comment by herau** [comment]
@mikepenz what about select an item (click) when the drawer is open ?

**Comment by aitorvs** [comment]
On this same topic, if I wanted to click on a item that is off-screen. I know I could use onData().inAdapterView().xxx so that it scrolls but I don't know on what adapter.

**Comment by mikepenz** [comment]
@aitorvs you can access the `RecyclerView` and the `Adapter` from the `Drawer` just check the public methods from the `Drawer` object
