### ISSUE TITLE
is there a way to add items dynamically with a loop and list?

### ISSUE THREAD

**Issue by phoenix26** [mikepenz/MaterialDrawer#1581]
i have a section "bookmars" in drawerlayout and i'm making a list and passing it to drawer adapter in my listviewed drawerlayout.And i want to use your library in my project but i just checked your sample project and you make your drawer layout as a static not dynamic so is there a way to pass a list or a loop to your drawer?

code example through my project:

       ArrayList<String[]> books = DataUtils.getBooks();
        if (books != null && books.size() > 0) {
            Collections.sort(books, new BookSorter());
            for (String[] file : books) {
                list.add(new EntryItem(file[0], file[1], ContextCompat.getDrawable(this, R.drawable
                        .folder_fab)));
            }
            list.add(new SectionItem());
        }

       and im passing this list to drawer adapter like this:
        
         adapter = new DrawerAdapter(con, list, MainActivity.this, Sp);
        mDrawerList.setAdapter(adapter);

and i have a method selectitem(int pos) and passing position to that method and showing fragment via  position.

So can you tell me how can i do this with your brilliant library? I hope you help me to solve this.thank you

**Comment by mikepenz** [comment]
You can simply use the method `addDrawerItems` of the `DrawerBuilder` https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L980

So you will have something like

```java
DrawerBuilder drawerBuilder = new DrawerBuilder(this);
drawerBuilder.with*();
for(...) {
    drawerBuilder.addDrawerItems();
}
Drawer drawer = drawerBuilder.build();
```
