### ISSUE TITLE
Can't make status bar translucent

### ISSUE THREAD

**Issue by srpanchal** [mikepenz/MaterialDrawer#1582]
Great library!
Hi I used your library with [MaterialViewPager](https://github.com/florent37/MaterialViewPager) but I cant get translucent status bar .I tried codes from stackoverflow also(tried setting flags etc.).
According to you MaterialDrawerTheme.Light.TranslucentStatus should give translucent status bar but why am I not getting it?

My theme: 

`<style name="AppBaseTheme" parent="MaterialDrawerTheme.Light.TranslucentStatus">
    </style>

    
    <style name="AppTheme" parent="AppBaseTheme">
        
        <item name="android:textColorPrimary">@android:color/white</item>
        <item name="drawerArrowStyle">@style/DrawerArrowStyle</item>
        <item name="android:windowTranslucentStatus" tools:targetApi="19">true</item>
        <item name="android:windowContentOverlay">@null</item>
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>

        <item name="android:statusBarColor" tools:targetApi="lollipop">@android:color/transparent</item>
        
        <item name="colorControlNormal">@android:color/white</item>
        <item name="actionBarTheme">@style/AppTheme.ActionBarTheme</item>

        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>

        <item name="android:navigationBarColor" tools:targetApi="21">@color/navigationBarColor</item>
        <item name="android:windowDrawsSystemBarBackgrounds" tools:targetApi="21">true</item>

    </style>`

![screenshot_20161017-001914](https://cloud.githubusercontent.com/assets/11073524/19420002/5733d3ac-9400-11e6-8b62-82097847f5fa.png)

**Comment by srpanchal** [comment]
I could not get translucent status bar before I used materialviewpager.
I am using latest appcompat and library versions.

**Comment by mikepenz** [comment]
@srpanchal please make sure you use the `fitsSystemWindows` flag correctly on your views 

Please also have a look at this sample: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CollapsingToolbarActivity.java
and it's layout:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/activity_sample_collapsing_toolbar.xml

**Comment by srpanchal** [comment]
Still no change. 
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    tools:context="travello.com.travello.MainActivity"
    android:fitsSystemWindows="true">

    

    <com.github.florent37.materialviewpager.MaterialViewPager
        android:fitsSystemWindows="true"
        android:id="@+id/materialViewPager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:viewpager_logo="@layout/header_logo"
        app:viewpager_logoMarginTop="100dp"
        app:viewpager_color="@color/colorPrimary"
        app:viewpager_headerHeight="200dp"
        app:viewpager_headerAlpha="1.0"
        app:viewpager_hideLogoWithFade="false"
        app:viewpager_hideToolbarAndTitle="true"
        app:viewpager_enableToolbarElevation="true"
        app:viewpager_parallaxHeaderFactor="1.5"
        app:viewpager_headerAdditionalHeight="20dp"
        app:viewpager_displayToolbarWhenSwipe="true"
        app:viewpager_transparentToolbar="true"
        app:viewpager_animatedHeaderImage="true"
        app:viewpager_disableToolbar="false"
        app:viewpager_pagerTitleStrip="@layout/material_view_pager_pagertitlestrip_standard"
        />
</LinearLayout>
`

**Comment by mikepenz** [comment]
@srpanchal could you please provide a demo application so I can try this?

**Comment by srpanchal** [comment]
https://drive.google.com/open?id=0B1c_9ERailvzZEdoWW5BaWJUaW8

**Comment by srpanchal** [comment]
code : (https://drive.google.com/open?id=0B1c_9ERailvzSEIyOC1ST3B4LW8)

**Comment by mikepenz** [comment]
@srpanchal after some tries. It seems the used library does not correclty handle the insets when using the `fitsSystemWindows` attribute. 

Wrapping the whole `MaterialViewPager` inside a `ScrimInsetsFrameLayout` will move it below the `StatusBar` but ignoring the 24dp. (25dp as of Android 6.x). 

(Also one additional issue. You have 2 `Drawer`s in your activity, causing additional issues, please remove the empty one)

**Comment by mikepenz** [comment]
Ok after checking their official sample. They definitely handle the `fitsSystemWindow`s flag wrong. They require you to not use it at all. 

So to fix your sample. Remove the empty drawer (you have it before defining the items) and add `.withDrawerLayout(R.layout.material_drawer_fits_not)` to your `DrawerBuilder`. Please also remove the unused unnecessary layout around the `MaterialViewPager` in the `activity_main`

**Comment by mikepenz** [comment]
add 
```java
.withTranslucentStatusBar(false)
```

**Comment by mikepenz** [comment]
Thank you :)

Is it ok if I would use your sample as base for a new sample activity of the drawer?

**Comment by srpanchal** [comment]
@mikepenz  Sure, why not.
