### ISSUE TITLE
Suggestion: Way to set profile icon background color

### ISSUE THREAD

**Issue by cpboyd** [mikepenz/MaterialDrawer#1584]
Currently, if there's a transparent background in the profile image, the circle doesn't have any "fill" color. 

I've used the following to apply a background color:
```java
        ShapeDrawable background = new ShapeDrawable();
        background.getPaint().setColor(getResources().getColor(R.color.background));
        Drawable drawable = getResources().getDrawable(R.drawable.profile_image);
        LayerDrawable layer = new LayerDrawable(new Drawable[]{background, drawable});
```

It seems like being able to set a background color would be useful to others as well and there's probably a better way to integrate it directly into `BezelImageView`, rather than creating a separate `LayerDrawable` as I've done.

**Comment by mikepenz** [comment]
@cpboyd currently there are no plans to adjust this, as you can set a drawable on your own via the APIs. 
To simplify this you can also just move this code into a helper function for you. 

Thanks for the suggestion. 

(I have added the "good to know" label so it is easier to be found)
