### ISSUE TITLE
MaterialDrawer FAQ - select a drawer Item in expresso

### ISSUE THREAD

**Issue by herau** [mikepenz/MaterialDrawer#1586]
Hello,

How can i select an item in the the drawer after the opening with  `onView(withId(R.id.material_drawer_layout)).perform(DrawerActions.open());`

**Comment by mikepenz** [comment]
@herau as the `DrawerLayout`'s content is just a `RecyclerView` I would say you can test it the same way as you would test a `RecyclerView` in common. 

Selections are done via the `Drawer` object. the `DrawerBuilder` also allows you to define a listener which is called when the drawer is opened / closed
