### ISSUE TITLE
Material drawer and bottomsheet object

### ISSUE THREAD

**Issue by engi** [mikepenz/MaterialDrawer#1587]
Hello Mike.
My application uses your library MaterialDrawer and everything works.
However, when I try to add a BottomSheet object in my activity, the activity stops when opening the drawer. Is it a bug ?

**Comment by mikepenz** [comment]
@engi can't be a bug of the `MaterialDrawer` as it works fine in general. Has to be related to your implementation, or to the implementation of that library. 

You can add the stacktrace of the crash though, perhaps it is easy to describe / fix

**Comment by engi** [comment]
Oups ! I'm sorry for the inconvenience, just a NullPointerException on a non-instantiated object.
I am ashamed
