### ISSUE TITLE
How to use Profile Icon onClickListener??

### ISSUE THREAD

**Issue by ajithkpistar** [mikepenz/MaterialDrawer#1588]
Hi,
I want to change the profile image when i click on the profile icon by using alert and uploading image and setting bitmap to it????
is it possible to do this???

**Comment by mikepenz** [comment]
@ajithkpistar what do you mean?

You can set a `BitMap` to a `ProfileDrawerItem` at any time. Just notify the `AccountHeader` about the updated profile afterwards and you are fine.
