### ISSUE TITLE
Material Drawer Divider Customization

### ISSUE THREAD

**Issue by geolyth** [mikepenz/MaterialDrawer#1590]
Hi,
when I try to customize drawer divider nothing happens...

I put this line:
`<item name="material_drawer_divider">@color/white</item>`
in styles.xml.

**Comment by mikepenz** [comment]
@geolyth which divider are you talking about?

**Comment by geolyth** [comment]
Material Drawer Divider (separator between two rows)

**Comment by mikepenz** [comment]
@geolyth there is no separator between two rows, just if you have a `SectionDrawerItem` or a `DividerDrawerItem` and those colors are controlled by the above color. If you want a divider between all items you have to set it via an `Decorator`
see more here:
http://stackoverflow.com/a/27037230/325479

**Comment by geolyth** [comment]
@mikepenz Sorry for my poor explanation (but you have centered the problem) :)
You're right ;)

I know how to add a Decorator in a custom RecyclerView, but how could I add this one in Recycler View of your Library?

Thanks a lot ;)

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L215

**Comment by aitbaali** [comment]
@mikepenz , I want a divider between all items, how can I use the `Decorator`

[(http://stackoverflow.com/a/27037230/325479)](http://stackoverflow.com/a/27037230/325479)

**Comment by jayInd** [comment]
how can i set background color for minidrawer ?
