### ISSUE TITLE
How to change the font size of the Menu Item

### ISSUE THREAD

**Issue by singhalavi** [mikepenz/MaterialDrawer#1592]
Is there any way to change the font size

**Comment by mikepenz** [comment]
you can define the font size if you overwrite the dimensions set in the `dimens.xml` just add the entry to your dimens.xml and change the value

**Comment by Kashish-Sharma** [comment]
Tried overriding:
    <dimen name="material_drawer_account_header_title">20sp</dimen>
    <dimen name="material_drawer_account_header_subtext">13sp</dimen>
Didn't work. Need help.

**Comment by mikepenz** [comment]
What exactly does "didn't work mean"? which texts to you want to modify?
how does it look like?

**Comment by Kashish-Sharma** [comment]
Ohh I'm really sorry, it worked.
Was not doing it correctly.
My bad.
