### ISSUE TITLE
Modify CrossfadeDrawerLayout under Toolbar

### ISSUE THREAD

**Issue by Shruti6293** [mikepenz/MaterialDrawer#1594]
How can I modifiy ` CrossfadeDrawerLayoutActvitiy` which use Minidrawer but below Actionbar ? 
Something like below image . Which allow me to open and close Minidrawer ?

![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/15194143/19643525/6a5a0308-9a08-11e6-8510-79306399e1aa.jpg)

**Comment by Shruti6293** [comment]
I have customized Customcontainer and Minidrawer

**Comment by sarvajeet294** [comment]
@Shruti6293  Hi, Can you please tell me how you achieved this requirement? If you can share the required code that would be cherry on top.

**Comment by mikepenz** [comment]
@Shruti6293 just use the `CustomContainerActivity` of the sample activity it's very imilar

**Comment by sarvajeet294** [comment]
Worked fine.. Thanks :)
