### ISSUE TITLE
Prevent/Disable open CrossFadeLayout in Minidrawer

### ISSUE THREAD

**Issue by Shruti6293** [mikepenz/MaterialDrawer#1595]
Could I able to Prevent or Disable CrossfadeLayout which is expansion of MiniDrawer ? 
I want to just keep Minidrawer only not and expansion with full width .
Is it any way ?

**Comment by mikepenz** [comment]
@Shruti6293 if you just want the `MiniDrawer` you just have to remove the code for the `CrossFadeLayout` and add the `MiniDrawer`-View which you create via `miniResult.build(this)` to your layout.

**Comment by Shruti6293** [comment]
As I have removed `CrossFadeLayout` code and got result as I want but one problem occur , I have set **badge** using  **`withBadge` ** but it's not showing me that in my minidrawer

![device-2016-10-25-120533](https://cloud.githubusercontent.com/assets/15194143/19675365/8d28fc60-9aab-11e6-9b92-b33141c70c51.png)

**Comment by mikepenz** [comment]
@Shruti6293 can it be that you used the wrong view? The one from the normal `Drawer` instead the `MiniDrawer`? 

If you add a badge at a later time you have to notify the drawers again about the change.

**Comment by Shruti6293** [comment]
@mikepenz As I just want to only keep `MiniDrawer` under toolbar with actionbar-toggle which open - close my `MiniDrawer`. but still no luck. could you help me ? I have delete code of `CrossFadeLayout `from MinidrawerActivity it causes above result as above snap.

**Comment by mikepenz** [comment]
@Shruti6293 please post some code about how you do it now. it should be easy to locate
