### ISSUE TITLE
SwitchDrawerItem with badge

### ISSUE THREAD

**Issue by dyckster** [mikepenz/MaterialDrawer#1596]
Is it possible to add badge to switchdraweritem?

**Comment by dyckster** [comment]
Figured out using this [answer](http://stackoverflow.com/questions/31030595/how-to-customize-the-draweritem-using-the-lib-mikepenz-materialdrawer/32542999#32542999) from FAQ.

**Comment by mikepenz** [comment]
@dyckster great :)

**Comment by or-dvir** [comment]
@dyckster i also want to do that.
will you please post you custom drawer item with the badge added?
