### ISSUE TITLE
ProfileDrawerItem parent with indented ProfileDrawerItem children

### ISSUE THREAD

**Issue by rmunk** [mikepenz/MaterialDrawer#1598]
I have parent-child relations between profiles and I would like to represent it in the `AccountHeader` menu. I can add child `ProfileDrawerItem` as subitem to parent `ProfileDrawerItem` but in the list this relationship is not apparent because they are on the same level.

As `ProfileDrawerItem` does not inherit from `BaseDrawerItem` there is no `withLevel()` option available.

Is there any other way to achieve this? If not do you think modification of `ProfileDrawerItem` is a viable option and do you have some tips where should I start.

**Comment by mikepenz** [comment]
@rmunk for this case the most simple solution is to just extend from `ProfileDrawerItem` define a new id `https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L194` and overwrite the `bindView` method (https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L204). call the super method. and then just add your additional padding to the views. 

Should be everything you have to do

**Comment by rmunk** [comment]
Worked like a charm. Thanks!

I also used `DrawerUIUtils.setDrawerVerticalPadding(viewHolder.itemView, level)` to set the padding.
