### ISSUE TITLE
Decrease header height

### ISSUE THREAD

**Issue by Fuhrmann** [mikepenz/MaterialDrawer#16]
Hi, first of all thanks for this library. I am new to Android, so maybe you can help me...

I want to decrease my navigation drawer header height, is possible? This is my header.xml layout that I am passing as parameter in `.withHeader`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="170dp"
    android:background="@drawable/backheader"
    android:orientation="vertical"
    android:weightSum="1">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="56dp"
        android:orientation="vertical"
        android:layout_alignParentBottom="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true">

        <TextView
            android:id="@+id/name"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="16dp"
            android:textColor="#ffffff"
            android:text="Akash Bangad"
            android:textSize="14sp"
            android:textStyle="bold"

            />

        <TextView
            android:id="@+id/email"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textColor="#ffffff"
            android:layout_marginLeft="16dp"
            android:layout_marginTop="5dp"
            android:text="email@gmail.com"
            android:textSize="14sp"
            android:textStyle="normal"

            />
    </LinearLayout>
</RelativeLayout>
```

But even if I change the layout height of my drawer xml root layout to 50dp or something, the header keeps with the same height.

**Comment by mikepenz** [comment]
The height of the header view is determined by the layout which is passed to it. So in the given example your header layout is 170dp height. 

```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="170dp"
    android:background="@drawable/backheader"
    android:orientation="vertical"
    android:weightSum="1">
```

Also why do you wrap your linear layout within an relative layout?
And the weightSum is unnecessary in your example, as far as i can tell.

**Comment by Fuhrmann** [comment]
Well, I dont really know what I'm doing, I got this layout pre made in a tutorial. 

Anyway, I will try to change some parameters and see what happens.

Really thanks for your help!

**Comment by mikepenz** [comment]
@Fuhrmann found the solution?

**Comment by Fuhrmann** [comment]
Actually this got a little tricky that I can't solve. With the same xml I posted above, I can change the height but it does not matter, it will be always rendered with a full height. This is what I have (and what I want as final result) in my drawer_header.xml file:

![](http://i.imgur.com/Xd0xXbO.png?1)

And this is final result:

![](http://i.imgur.com/wtaI2KK.png?1)

I guess the problem is in my layout since you pointed out about the wrapped linear layout by a relative layout.

**Comment by mikepenz** [comment]
@Fuhrmann it's interesting, because i just add the Header as a normal view to the ListView. 

But this should be a basic android issue and nothing special MaterialDrawer.

I'll close this issue, but you can still answer questions here, and as far as possible i'll answer them.

**Comment by Fuhrmann** [comment]
Hey, no problem @mikepenz! Consider this solved and not related with MaterialDrawer! Thanks for the help!

**Comment by AbdulSamadQureshi** [comment]
I was having the same problem with a imageView in header/footer, i am not sure if it would help but it should give you the clue, i set the adjustViewBounds = false which did the trick.
