### ISSUE TITLE
How to add a switcher button to the navigation drawer?

### ISSUE THREAD

**Issue by edesdan** [mikepenz/MaterialDrawer#1600]
I would like to add a switcher button, like the standard android one (switcher preferences). I want to attach  a listener to listen for changes. Is it possible?

**Comment by mikepenz** [comment]
@edesdan have a look at the sample application. It has a `DrawerItem` with a switch in ;) (The code is all available in this repo)

**Comment by edesdan** [comment]
Oh, nice thanks! And if I want to change the item's icon inside the OnCheckedChangeListener() ?

**Comment by mikepenz** [comment]
Should be no problem in hooking into this

**Comment by edesdan** [comment]
Thanks!
