### ISSUE TITLE
Make drawer background transparent 

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/MaterialDrawer#1601]
Hi, i have a drawer embedded into a cardview, this works perfect.

the problem is that the cardview it is more "darker" than the background color of the cardview...see the screenshot.

![20161027_124322](https://cloud.githubusercontent.com/assets/9873666/19774730/75c19448-9c44-11e6-92cc-8446f42031dd.png)

how to change the background color of the drawer to transparent ?

thanks

**Comment by mikepenz** [comment]
@seba123neo you use the draver embedded in a cardview? :O 

Why don't you use a normal `RecyclerView` there and use the `FastAdapter` to add the items to it?

**Comment by seba123neo** [comment]
yes, thank you, is what I must do !!!

**Comment by seba123neo** [comment]
you can close the issue now
