### ISSUE TITLE
Change only textcolor of Name ?

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/MaterialDrawer#1602]
**.withTextColor** change the color of the Name and the Description too

y need only change the color of the Name...

**Comment by mikepenz** [comment]
@seba123neo this is not possible in the default item and requires a `CustomDrawerItem`

**Comment by seba123neo** [comment]
i already use a custom drawer item.

```
public class MultilineDrawerItem extends PrimaryDrawerItem {

    @Override
    public int getType() {
        return R.id.fastadapter_multiline_item_id;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.item_datos_cliente;
    }
}

the XML layout is the same as the PrimaryDrawerItem, with few changes
```

**Comment by mikepenz** [comment]
In addition to this you will now also have to overwrite https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/AbstractBadgeableDrawerItem.java#L68 call super and afterwards set the colors

**Comment by seba123neo** [comment]
i have this

`public class MultilineDrawerItem extends PrimaryDrawerItem {

    @Override
    public int getType() {
        return R.id.fastadapter_multiline_item_id;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.item_datos_cliente;
    }

    @Override
    public void bindView(ViewHolder viewHolder, List payloads) {
        super.bindView(viewHolder, payloads);

        Context ctx = viewHolder.itemView.getContext();
        viewHolder.material_drawer_name.setTextColor(ContextCompat.getColor(ctx, R.color.md_red_500));
    }

    public static class ViewHolder extends RecyclerView.ViewHolder {
        protected View view;

        public TextView material_drawer_name;

        public ViewHolder(View view) {
            super(view);
            this.view = view;
            material_drawer_name = (TextView) itemView.findViewById(R.id.material_drawer_name);
        }
    }
}`

the @Override above bindView show an error "method does not override method from its superclass"

**Comment by mikepenz** [comment]
That's probably because you can't use your own `ViewHolder` in this case
