### ISSUE TITLE
account header view position

### ISSUE THREAD

**Issue by kiotoze** [mikepenz/MaterialDrawer#1607]
Hi Mike!

I know that in material design current account visible on the top of drawer, in header. But I would like to put in in the middle of my drawer, like:
```
logo
-------
item1
item2
item3
--------
account header
--------
item4
....
```
I have checked the code and I didn't find solution how to do that. 
So, it would be nice if account item will implement `IDrawerItem` and support actions to manipulate with profiles and all common functionality dependent on account but header functionality is split to another class (`AccountHeader`). In this case it possible to put in any place of drawer. Then if header required it wraps in `AccountHeader(AccountItem)`...
Could you help me to understand how can I make it?

**Comment by mikepenz** [comment]
Hi @kiotoze sorry this is not possible, as this would result in many additional troubles, like the problem of showing the items for the header. It would be a big problem for it to implement that it should just remove all items but the account header, and then add the profile items around it. 

In your case I recommend you to implement a `CustomDrawerItem` which looks like the `AccountHeader` or like the things you need from the `AccountHeader` 

Also I don't think that this should be in the library as it wouldn't be used in general, and ist just required by your specific case.

**Comment by kiotoze** [comment]
Thanks for response
I will try to implement CustomDrawerItem

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md
