### ISSUE TITLE
Hof to load Fragments

### ISSUE THREAD

**Issue by Kara52deniz** [mikepenz/MaterialDrawer#1608]
Hello first I Love your Work, and sorry for my Bad English (i am German) .

I buy a app in Codecanyon (My Social Network)  this have a Navigation drawer with loads items via Fragment. 

Im newbie i try to use your PersistentHeader drawer but i have no idea how i can add fragments  in.

And my other Question: Is your Compile compatible with sdk 23?

Thank you

**Comment by mikepenz** [comment]
Hi @Kara52deniz 

The MaterialDrawer provides the listeners and callbacks which will allow you to implement any navigation logic you need. As for fragments. Just look up in the internet how to handle fragments in Android. 

As the `MaterialDrawer` uses the latest v25 of the support libraries, which in general should be used with compileSdk 25 and targetSdk 25 it is not recommend to use it with sdk 23. What prevents you from using the latest version?

**Comment by mikepenz** [comment]
https://developer.android.com/guide/components/fragments.html

**Comment by Kara52deniz** [comment]
The Problem is the App was i buyed in Codecanyon build with sdk 23 and when i changing this in Gradle to sdk 25 can i build an debug.apk but after install on my phone can i not open the App. 

Ich habe auf ihren Profil gelesen das Sie aus Österreich kommen und als Freelancer tätig sind.  Ist es möglich das ich Sie damit beauftrage ein paar Änderungen in meiner Social Networking App vorzunehmen?

Diese wären:
1. Ändern des jetzigen Drawer Menüs in das PresitentDrawer Menü mit Verlinkung zu den jeweiligen Fragmenten.

Bild aktueller NavDrawer:

[URL=http://www.directupload.net/file/d/4528/d4wf4n2h_png.htm][IMG]http://fs5.directupload.net/images/161103/temp/d4wf4n2h.png[/IMG][/URL]

2. Hinzufügen von einem Tab Menü unter der Toolbar oder ein Bottombar Menü in Profil Layout. 

Bild Profil:
[URL=http://www.directupload.net/file/d/4528/c7stkl42_png.htm][IMG]http://fs5.directupload.net/images/161103/temp/c7stkl42.png[/IMG][/URL]

Wenn das möglich wäre könnten Sie mir ihre Kontaktdaten sowie die Kosten hierfür an info@bmw-live.com zusenden.

Mfg
