### ISSUE TITLE
Hard to pull to open when slowly moving finger in comparison to Support Library

### ISSUE THREAD

**Issue by tajchert** [mikepenz/MaterialDrawer#1609]
I noticed that MaterialDrawer is significantly (at least noticeably) harder to open by gesture from the screen edge than Support Library implementation - in some cases where initial fling is not that great it tends to stop at 8-12dp and hide (even despite that finger is still moving vertically to right edge), where Support Library version tends to stick to finger no matter how fast finger is travelling (fling) - which results in open drawer where in MaterialDrawer it doesn't open.

I wonder how much it is due to decisions in implementation and if there is a way to modify this?

**Comment by mikepenz** [comment]
@tajchert the MaterialDrawer does exactly use the same `DrawerLayout` provided by the support library. there were no modifications made nor was there anything changed regarding this behavior. 

Could it be just a feeling?

**Comment by tajchert** [comment]
Ok, so this is very weird and I hope it is not my senses - I will upload a video where I have sample app with support library and your sample app. I tried to use same velocity in finger, but effect of "sticking to left edge" is visible only in MaterialDrawer sample. Just a sec - slow internet here.

**Comment by tajchert** [comment]
https://drive.google.com/file/d/0BzF5kvbBC38nLXd6OVpFVENPQ2s/view?usp=sharing
So now I wonder if same behavior of MaterialDrawer is on other phones - here OnePlus 2 with 6.0.1 CM13.

**Comment by mikepenz** [comment]
http://stackoverflow.com/a/20016088/325479
This should do the trick :D

**Comment by tajchert** [comment]
Many thanks! Tested - it works like a butter now.
Minor PR but still - in my case it makes a hell of a difference.

**Comment by mikepenz** [comment]
thank you for doing the PR ;)
