### ISSUE TITLE
Question - cannot set header image without white bars

### ISSUE THREAD

**Issue by PawelPleskaczynski** [mikepenz/MaterialDrawer#1611]
Hello, I added a drawer to my app and I decided to set the header image. I made new layout file with only imageView and then added the header layout to the drawer builder code. The header is working but it has some ugly white bars on the top and on the bottom. Is there any way to fix it? Here is a screenshot - http://imgur.com/qeYlVHc

**Comment by mikepenz** [comment]
Please see the sample application. There it works without problems:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/header.xml
https://github.com/mikepenz/MaterialDrawer/blob/fed00a199196efbc63296a081723e603647b5bc4/app/src/main/java/com/mikepenz/materialdrawer/app/MultiDrawerActivity.java#L43

**Comment by PawelPleskaczynski** [comment]
Thank you! It's working now
