### ISSUE TITLE
Expandable Listview inside custom header..

### ISSUE THREAD

**Issue by vanillazz** [mikepenz/MaterialDrawer#1613]
Is it possible to add expandable listview inside the custom header?

i hav tried it, but my expandable list cannot expand inside the custom header..
do you hav solution for this ?

**Comment by mikepenz** [comment]
@vanillazz the custom header allows you to pass any view in which you want. So this is completely independent of the `MaterialDrawer` itself. 

I assume that the height will change and as the containing `RecyclerView` item already was calculated the new height would not be respected. So you perhaps have to invalidate the RV or something like this. 

In general this is the same as if you would do the same in a normal `RecyclerView`. So please have a look how to nest your `Expandable ListView` inside a `RecyclerView`

**Comment by vanillazz** [comment]
thanks for your explanation..
Really appreciate it.. 
:)
