### ISSUE TITLE
Increase touch-responsive area for swipe gesture

### ISSUE THREAD

**Issue by vit1-irk** [mikepenz/MaterialDrawer#1614]
In current implementation of "normal" drawer, user has to place a finger to the left of the screen to perform swipe gesture.
Is it possible to open drawer not only from the end of the screen, but also from the center of visible activity? Because sometimes it is real pain for user to do "pull to right".

Telegram, for example, somehow managed to swipe it's drawer all over the activity, but unfortunately it is hard to get outside of their tricky source code.

**Comment by mikepenz** [comment]
@vit1-irk that's nothing related to the `MaterialDrawer` as I use a normal `DrawerLayout` and alos it'S features. 

I assume you can somehow have a `TouchListener` over your whole view and just check if the user swipes left to then open the drawer. You may also achieve this with a custom implementation of the `DrawerLayout` (which you can then pass to the `MaterialDrawer`)
