### ISSUE TITLE
Problem with RecyclerView

### ISSUE THREAD

**Issue by Xellsky** [mikepenz/MaterialDrawer#1616]
I'm using MaterialDrawer library with RecyclerView(android.support.v7.widget.RecyclerView) - and I have a problem.
If I add the MaterialDrawer library to gradle, RecyclerView does not work! My app could be run, but recyclerview not be displayed on the screen, and xml also throws the rendering problems. 

![image](https://cloud.githubusercontent.com/assets/1857948/20098328/a2472c60-a5f6-11e6-9152-dc6f2e9b575b.png)

My layout xml code.
![image](https://cloud.githubusercontent.com/assets/1857948/20098658/47b76786-a5f8-11e6-8aab-198b0ea0f830.png)

![image](https://cloud.githubusercontent.com/assets/1857948/20098887/46be57a8-a5f9-11e6-9d74-598ed0d16a34.png)

Here is my gradle code.
![image](https://cloud.githubusercontent.com/assets/1857948/20098401/f46df460-a5f6-11e6-8fb6-64779ee9cc56.png)

Some help will be apreciate!

**Comment by mikepenz** [comment]
@Xellsky please make sure you use appcompat and recyclerview 25 when using the latest version of the materialdrawer.
Maybe there is an appcompat conflict. 

For the `UltimateRecyclerView` I cannot give support

**Comment by Xellsky** [comment]
Solved. Thanks for your help!
