### ISSUE TITLE
Account Profile picture click listener

### ISSUE THREAD

**Issue by therealccarter** [mikepenz/MaterialDrawer#1619]
Not sure how to actually implement the Profile Picture listener. For example, here's my Drawer Account Builder code

    AccountHeader header = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.header)
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean current) {
                        //Handle Profile changes
                        return false;
                    }
                })
                .build();

Here's what I'm trying to do based on the library code

    AccountHeader header = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.header)
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean current) {
                        //Handle Profile changes
                        return false;
                    }
                })
                .withOnAccountHeaderProfileImageListener() // not sure how to actually place the intent to UserProfile.class here
                .build();

**Comment by mikepenz** [comment]
So you are not sure how to pass or define the listener itself?

**Comment by therealccarter** [comment]
I just don't understand how to make the app go to User Profile when the profile pic is clicked. I guess I'm not sure how to do either? Sorry for the noob question

**Comment by mrneiverth** [comment]
@therealccarter probably you want to start a new activity to go to a profile screen

I think something like this would be enough
`Intent intentProfile= new Intent(this, Profile.class);
startActivity(intentProfile);`

**Comment by therealccarter** [comment]
Yeah that's what I'd like to do, I just don't know where to put that. Would it be in the DrawerBuilder, or in the AccountHeaderBuilder? And then whichever that is, would it be with a .with constructor?

**Comment by mikepenz** [comment]
@therealccarter in general it's simple. 

All functions which are for the header can be found in the `AccountHeader` or `AccountHeaderBuilder` and everything for the normal drawer / drawerItems are in the `Drawer` `DrawerBuilder`

just add this to your `AccountHeaderBuilder` 

```java
.withOnAccountHeaderProfileImageListener(new AccountHeader.OnAccountHeaderProfileImageListener() {
                    @Override
                    public boolean onProfileImageClick(View view, IProfile profile, boolean current) {
                        return false;
                    }

                    @Override
                    public boolean onProfileImageLongClick(View view, IProfile profile, boolean current) {
                        return false;
                    }
                })
```

(or one of the other listeners if it helps you)
