### ISSUE TITLE
Bug - Bottom Unknown Layout

### ISSUE THREAD

**Issue by TurKurT656** [mikepenz/MaterialDrawer#162]
TnQ for new update. now the rtl bug is gone :+1: 
but there is a strange bug.
see:
![device-2015-03-27-123833](https://cloud.githubusercontent.com/assets/7152030/6864446/e6b77580-d47e-11e4-8c54-bf1cd858fee9.png)
If you see the bottom part, a layout appeared at bottom section. why this is happening?

**Comment by mikepenz** [comment]
@TurKurT656 is already an issue :D 
https://github.com/mikepenz/MaterialDrawer/issues/161

i've made a small default value mistake with the newest version.
To temporary fix this just add `withTranslucentNavigationBar(false)` 

Will be fixed later today

**Comment by TurKurT656** [comment]
TnQ :) and sorry for duplicate issue
