### ISSUE TITLE
Need a documentation for How To Implement ExpandableDrawerItem

### ISSUE THREAD

**Issue by joielechong** [mikepenz/MaterialDrawer#1620]

**Comment by mikepenz** [comment]
@joielechong I am not sure what you mean? The sample app showcases how to use it.

**Comment by mikepenz** [comment]
The source code for this item:
https://github.com/mikepenz/MaterialDrawer/blob/a4abf301d3a058881ffbf407683e877a840fdd1a/library/src/main/java/com/mikepenz/materialdrawer/model/ExpandableDrawerItem.java

Here how it's used:
https://github.com/mikepenz/MaterialDrawer/blob/3dbf0b6e9c657bfac792de60a401b73c32fbaab4/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L137

**Comment by joielechong** [comment]
I've successfully implemented the ExpandableDrawerItem. Thank you for your project.For implementing ExpandableDrawerItem

**Comment by joielechong** [comment]
I've successfully implemented the ExpandableDrawerItem. Thank you for your project.For implementing ExpandableDrawerItem

**Comment by joielechong** [comment]
I've successfully implemented the ExpandableDrawerItem. Thank you for your project.

For implementing ExpandableDrawerItem, a developer needs to spend some times to find and explore the sample apps. As one of MaterialDrawer philosophy, **integrate in less than 5 minutes**, MaterialDrawer needs a complete documentation for each of its features. I guess documentation is a very good leverage for this beautiful project. Thank you for hard work. 👍
