### ISSUE TITLE
How to create a the profile list like in your sample

### ISSUE THREAD

**Issue by herau** [mikepenz/MaterialDrawer#1621]
Hello,

I don't find, in the account header component methods, a way to build the profile list (with "Add account" and "Account manager" item) like you displayed in your readme file

![](https://raw.githubusercontent.com/mikepenz/MaterialDrawer/develop/DEV/github/screenshots1.jpg)

is it another component to use ?

Thanks

**Comment by roee88** [comment]
I'm not the developer, but I think it's in this sample:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java

**Comment by herau** [comment]
@roee88 thanks a lot

**Comment by mikepenz** [comment]
@herau all screenshots are made from the smaple app. just look at the sample apps code. 
@roee88 thanks for answering
