### ISSUE TITLE
No hamburger icon shown, only back button

### ISSUE THREAD

**Issue by SenorWesley** [mikepenz/MaterialDrawer#1624]
Whenever I try to use your library, I can't get it to display the hamburger icon. All that's being shown is the back button, even when the drawer is closed: 
<img width="270" alt="afd4d9c034f647feaa9f4fefd316b007" src="https://cloud.githubusercontent.com/assets/15349051/20261976/7c8f2900-aa60-11e6-9f6d-fa3ad7dd0b1f.png">

However it is possible for me to drag out the drawer from the side.

```
result = new DrawerBuilder()
    .withActivity(this)
    .withSavedInstance(savedInstanceState)
    .withDisplayBelowStatusBar(true)
    .withAccountHeader(headerResult)
    .withTranslucentStatusBar(false)
    .addDrawerItems(...)
    .withOnDrawerItemClickListener(...)
    .build();
```

Is this a bugg or a mistake on my end?

Thanks.

**Comment by mikepenz** [comment]
Anything else you define in your activity? It is definitely no bug, something on your end causes this. 

Make sure you do NOT play around with these methods:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MultiDrawerActivity.java#L169

In general the default should be that the `Hamburger` icon is shown

**Comment by SenorWesley** [comment]
There's nothing else in the activity. Nothing that I could determine the source of the problem from.

FULL CODE:
`public class HomeActivity extends AppCompatActivity {
    private Drawer result = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.home);
        setTitle("Welkom bij Kuijs Fysio");


        AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.header)
                .addProfiles(
                        new ProfileDrawerItem().withName("Test Profile").withIcon(getResources().getDrawable(R.drawable.profileTest))
                )
                .build();


        result = new DrawerBuilder()
                .withActivity(this)
                .withSavedInstance(savedInstanceState)
                .withDisplayBelowStatusBar(true)
                .withAccountHeader(headerResult)
                .withTranslucentStatusBar(false)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("Dashboard").withIcon(FontAwesome.Icon.faw_home),
                        new SecondaryDrawerItem().withName("Settings").withIcon(FontAwesome.Icon.faw_cog)
                ).build();

        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setHomeButtonEnabled(false);
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        outState = result.saveInstanceState(outState);
        super.onSaveInstanceState(outState);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                onBackPressed();
                return true;

            default:
                return super.onOptionsItemSelected(item);
        }
    }

    @Override
    public void onBackPressed() {
        if (result != null && result.isDrawerOpen()) {
            result.closeDrawer();
        }
    }
}`

**Comment by mikepenz** [comment]
as mentioned in my previous answer. do NOT play around with these methods:
```java
getSupportActionBar().setDisplayHomeAsUpEnabled(true);
getSupportActionBar().setHomeButtonEnabled(false);
```

just remove them

**Comment by SenorWesley** [comment]
My bad, i thought you meant to leave those lines and never touch them.

Whenever I try it without those methods, I get nothing at all. No back button, no hamburger. 
<img width="321" alt="dwdwdwdwd" src="https://cloud.githubusercontent.com/assets/15349051/20283693/4d3c4f48-aaba-11e6-9b4d-840d479710ef.png">


Is it possible that I perhaps am missing a setting or something like that?

Thanks

**Comment by mikepenz** [comment]
@SenorWesley oh you also have to pass the `Toolbar` to the `Drawer` so it can handle everything for you
