### ISSUE TITLE
How can I lock drawer layout menu?

### ISSUE THREAD

**Issue by tuzenvn** [mikepenz/MaterialDrawer#1626]
I want to lock drawer menu (Is not open drawer menu when gesture left to right)?

**Comment by tuzenvn** [comment]
I want to lock drawer menu (Is not open drawer menu when gesture left to right)?

**Comment by mikepenz** [comment]
@tuzenvn by setting the lockmode on the DrawerLayout.

**Comment by mikepenz** [comment]
`Drawer.getDrawerLayout()...`
