### ISSUE TITLE
List selector for drawer items

### ISSUE THREAD

**Issue by ProfPh** [mikepenz/MaterialDrawer#1629]
Hello,

Is it possible to change the background colour of a list item when pressed from the default grey? 

Thank you

**Comment by mikepenz** [comment]
@ProfPh you can do this via a `CustomDrawerItem` the default draweritems follow the Material Design Guideliens and do not support this.

https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md
