### ISSUE TITLE
Not Compatible with the Android TV (Inshort with Remote)

### ISSUE THREAD

**Issue by pm-code** [mikepenz/MaterialDrawer#1630]
Material Drawer works perfectly with android phone and tablet where we can use fingers/tabs but its not compatible with android TV/ STB where we need remote to fiddle around in the menu. 
I am unable to get focus on the menu items. :-(

**Comment by mikepenz** [comment]
@pm-code please refer to the default `DrawerLayout` and if it is possible with this. The `MaterialDrawer` depends on the `DrawerLayout` and will just support functions this component from the support libraries also supports.

**Comment by hyourinseta** [comment]
Any solution for this case? I am currently developing app that will use only remote control to navigate around the app's UI. MaterialDrawer is a great library to use. It's a great news if we could navigate to the MaterialDrawer menu.

**Comment by emouawad** [comment]
Any updates on this? maybe workarounds?
