### ISSUE TITLE
How can I disable/enable a drawer item after creating the drawer?

### ISSUE THREAD

**Issue by BRoy98** [mikepenz/MaterialDrawer#1631]
Drawer items can be disabled/enable while I am creating the drawer by adding `.withEnabled(false/true)`. But is it possible to disable or enable a drawer item after creating the drawer?

**Comment by mikepenz** [comment]
@BRoy98 just call the method on the item and then notify the drawer about the change:
https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer
