### ISSUE TITLE
[Question] Set selectionListEnabled

### ISSUE THREAD

**Issue by mychaelgo** [mikepenz/MaterialDrawer#1633]
hello, 

can i set the `withSelectionListEnabled` in Accountheader after AccountHeaderBuilder is build?

For example 
first i set `withSelectionListEnabled(false)` then user logged in my app and i want to set `withSelectionListEnabled(true)` . Is it possible?

**Comment by mikepenz** [comment]
@mychaelgo no this is not possible after the header was built.

**Comment by mychaelgo** [comment]
@mikepenz  ok thank you for the answer

**Comment by mychaelgo** [comment]
@mikepenz  sorry for question again, but are you have an idea how to update selectionlist enabled after the header was built?
