### ISSUE TITLE
Strange overhead onLayout calls when using mini drawer

### ISSUE THREAD

**Issue by gtgray** [mikepenz/MaterialDrawer#1634]
Hello, Mike!

I'm using your library to show mini drawer with crossfader in my app.
And when I started to optimize performance and launching time,
it was appeared that onLayout method called at least 3 times per activity launch.
I made some research in my code on this overhead measuring/layouting and
found out that it was called for mSlidingLayout view group (variable in DrawerBuilder).
Then I took your sample app (MiniDrawerActivity)
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java
added (at the end of onCreate() method)
```javascript
    result.getSlider().addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
            @Override
            public void onLayoutChange(View view, int i, int i1, int i2, int i3, int i4, int i5,
                                       int i6, int i7) {

                Log.e("MINI DRAWER", "------------ ON LAYOUT " + view + ", " + this);

            }
        });
```
and got that 3 times onLayout calls
```
11-21 14:14:55.319 13659-13659/com.mikepenz.materialdrawer.app.debug E/MINI DRAWER: ------------ ON LAYOUT
com.mikepenz.materialize.view.ScrimInsetsRelativeLayout{31a26039 V....... ......ID 0,0-399,618 
#7f0b001f app:id/material_drawer_slider_layout}, com.mikepenz.materialdrawer.app.MiniDrawerActivity$3@8a867e
11-21 14:14:55.354 13659-13659/com.mikepenz.materialdrawer.app.debug E/MINI DRAWER: ------------ ON LAYOUT 
com.mikepenz.materialize.view.ScrimInsetsRelativeLayout{31a26039 V....... ......ID 0,0-399,554 
#7f0b001f app:id/material_drawer_slider_layout}, com.mikepenz.materialdrawer.app.MiniDrawerActivity$3@8a867e
11-21 14:14:55.453 13659-13659/com.mikepenz.materialdrawer.app.debug E/MINI DRAWER: ------------ ON LAYOUT 
com.mikepenz.materialize.view.ScrimInsetsRelativeLayout{31a26039 V....... ......ID 0,0-399,618 
#7f0b001f app:id/material_drawer_slider_layout}, com.mikepenz.materialdrawer.app.MiniDrawerActivity$3@8a867e
```
The interesting thing here is that the measured height of the layout at second onLayout call 
is less for the value of navigation bar size. 
I use nexus 7 with tvdpi screen, so 618 - 554 = 64px ~ 48dp.
So, the suggestion here is some extra padding adding from somewhere that is removed 
on the third onLayout call.
Is there a way to force drawerBuilder not to add this extra padding?

**Comment by mikepenz** [comment]
Very interesting. You might want to consider the following https://github.com/mikepenz/MaterialDrawer/issues/1635#issuecomment-262482181

**Comment by gtgray** [comment]
I've read that ([comment](https://github.com/mikepenz/MaterialDrawer/issues/1635#issuecomment-262482181)). 
But in MiniDrawerActivity ```buildView``` method is used for layout creation ([MiniDrawerActivity#L142](https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java#L142)).
May be a pair of onLayout dope calls is not a problem, but the uncoolest thing here is such height changes are visible by eye in cases when between 2nd and 3rd onLayout calls is more than 70-100ms. 
And in most cases it happens when one's clicking mini drawer items (big one drawer is closed).
To start the same activity from mini drawer I've replaced a line ([here MiniDrawerActivity#L134](https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java#L134)) with the following one:
```
startActivity(new Intent(MiniDrawerActivity.this, MiniDrawerActivity.class));
```
So, the strange behaviour is looks like this (2nd and 3rd onLayout calls):
![photo_2016-11-28_13-10-01](https://cloud.githubusercontent.com/assets/9328004/20664485/7fdda2b4-b56c-11e6-8212-db31b299d2f1.jpg)
![photo_2016-11-28_13-10-05](https://cloud.githubusercontent.com/assets/9328004/20664491/89f46db4-b56c-11e6-8cf5-eaf154a0337f.jpg)
Can you help me with this?

**Comment by mikepenz** [comment]
@gtgray oh ok sorry. I totally forgot about the fact that you are using a the `Crossfader` in this case which is no `DrawerLayout` 

In general when trying the smaple app. If you remove the `Toast` displayed in the `MiniDrawer` it will already improve the performance a lot. 

I am not sure why you would want to launch the same activity from itself? This shouldn't be done anyway. 


If I run the sample on my phone I can't see those bad freezes :/

**Comment by gtgray** [comment]
@mikepenz, I had to be more clear.
In my app I move from one activity to another by clicking menu items in mini, not opening full drawer.
So, transitions performs simplier without any crossfader movements (full drawer closing I mean).
Also, during my app performance improvement I turned off all transition animations.
In such a way that overhead onLyaout calls became noticeable by eye, 
but it looks like _blinking_ not freezing.

In sample app, launching same activity is the simplest way to reproduce needed transition behaviour. 
```Toast``` displaying call is absent, as it was replaced with the ```startActivity()``` call.
I used debugger to catch and capture that black band at the bottom ([1st screenshot above](https://cloud.githubusercontent.com/assets/9328004/20664485/7fdda2b4-b56c-11e6-8212-db31b299d2f1.jpg)).

**Comment by mikepenz** [comment]
so you don't have the crossfader in at all. just the `MiniDrawer`?
Or do you have it but don't need the normal drawer?

**Comment by gtgray** [comment]
@mikepenz, I use normal drawer with mini wrapped with a crossfader (exactly as in your sample - [MiniDrawerActivity](https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java)).
Mini drawer contains less items (main items) then normal drawer (contains additional items). 
I don't need to open normal drawer to move to another activity by clicking main items in mini drawer.
Opening normal drawer is required when one wants to pick an additional item.
So, moving through mini items blinking can be also reproduced in sample after adding a pair of lines 
of code explained above.

**Comment by mikepenz** [comment]
@gtgray I am afraid I can not offer a solution at this time. you may be able to improve this by consuming the click event's so it would not open the normal drawer again. 
You could in addition also set the `Animator`'s of the RV to null, or to no animation time. Might be all things which help improving this
