### ISSUE TITLE
Use exisitng drawer defined in layout

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/MaterialDrawer#1635]
The drawer builder uses your `MaterializeBuilder` here: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1266

This leads to following code block in your `MaterializeBuilder` to be executed:

https://github.com/mikepenz/Materialize/blob/develop/library/src/main/java/com/mikepenz/materialize/MaterializeBuilder.java#L397 to https://github.com/mikepenz/Materialize/blob/develop/library/src/main/java/com/mikepenz/materialize/MaterializeBuilder.java#L421

And in this block you remove the content view and wrap it and add it back. That's fine in general, I would need to avoid this removing/adding.

**Questions**

* It seems like `withDrawerLayout(@NonNull DrawerLayout drawerLayout)` is for a custom drawer view, that is not yet part of the layout, correct`?
* Could this be extended to support a drawer that is part of the layout? I would like to add the drawer to my layout directly and expect that the builder checks if the drawer is already in the layout and skips detaching, wrapping in parent and reattaching the content view in this case

I need this because I'm using a library for view based layouts (instead of activities and fragments) and it does some actions based on the `onAttach` and `onDetach` events of views because those events are considered like "activity started" and "activity paused"

**Comment by mikepenz** [comment]
@MFlisar there is a different solution you may choose. You can use `buildView` which will just build the drawers content. This view can then be added to the `DrawerLayout` which may already exists in your activity. 

This should solve all your issues, as it will not do any custom or automatic handling of paddings / views etc...

**Comment by MFlisar** [comment]
Thanks, that's sounds great. I'll try that.

**Comment by MFlisar** [comment]
Has a view side effects (things like full screen have to be done manually afterwards), but fulfills my needs.

**Comment by mikepenz** [comment]
@MFlisar exactly the only "side-effects" are that fullscreen things are no longer handled, and that the view is not automatically inflated. It won't handle the ActionBarDrawerToggle for you either, but those are things easy to achieve "manually" :D

If you still want the `MaterializeBuilder` you can use it standalone too. doesn't have to be via the `MaterialDrawer`

**Comment by MFlisar** [comment]
The `MaterializeBuilder` needs a container view though and if I want to avoid the detach/attach actions, I can't use it

**Comment by mikepenz** [comment]
ok great
