### ISSUE TITLE
Load image in the PrimaryDrawerItem().withIcon()

### ISSUE THREAD

**Issue by dcgavril** [mikepenz/MaterialDrawer#1636]
Hello,

First of all, thank you for your wonderful library, it's really useful.

I'm trying to load some small images in the PrimaryDrawerItem().withIcon() - similar to the Profile image loader, but I can't seem to find the right way. I've seen the "Imageloader for icons" #69 - but haven't managed to make it work. I need this behavior because I have some items that are dynamic and I cannot show some random icons from resources.
Can you please advise?

Thanks!

**Comment by mikepenz** [comment]
@dcgavril normal draweritems do not allow this, as in general those do not require images to be loaded from urls. 

The sample contains a customdrawerItem allowing exactly this:

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomUrlPrimaryDrawerItem.java

(You still can show random icons from ressources, just get it as normal drawable and set the drawable)

**Comment by dcgavril** [comment]
That's perfect! I managed to get it to work as needed. Thanks!

PS: sorry for not giving the proper attention to the sample app. At least, the answer may be useful for others.
