### ISSUE TITLE
Change text font

### ISSUE THREAD

**Issue by Ahmed-Emad** [mikepenz/MaterialDrawer#1637]
How can I change the text font (set typeface) ?

**Comment by mikepenz** [comment]
What font do you want to change?

**Comment by Ahmed-Emad** [comment]
Primary Drawer Item Name.

**Comment by mikepenz** [comment]
@Ahmed-Emad the `DrawerItem` has the method `withTypeface` which allows you to provide a different typeface

**Comment by Ahmed-Emad** [comment]
Yes it worked. Thank you.
