### ISSUE TITLE
Drawer icons using withIconColorRes don't always return to the right color

### ISSUE THREAD

**Issue by jonathan-caryl** [mikepenz/MaterialDrawer#1638]
When you have multiple drawer items using 

                                .withIconTintingEnabled(true)
                                .withIconColorRes(R.color.tint)
                                .withIcon(someIcon),

and you programatically set the selected item with `result.setSelection(someId)` the previously selected item can retain the selected color for the icon, rather than the tinted one we'd expect. I've put a test app up [here](https://github.com/jonathan-caryl/MaterialDrawerTintTest) that shows the issue, but I've not been able to figure out exactly what the problem is.

**Comment by mikepenz** [comment]
@jonathan-caryl very interesting, as the tinting is handled by the android framework, via a `ColorStateList` and I just set the selected state or the normal state.

**Comment by jonathan-caryl** [comment]
@mikepenz I tried doing some digging in the code this morning, but I didn't figure anything out. I wanted to add some debug to `PressedEffectStateListDrawable` to see if maybe the state isn't as expected, but it looks like that's actually in the `Materialise` library, I couldn't see an easy way to do that.

I've got a workaround, along the lines of

            result.deselect();
            handler.post(() -> result.setSelection(MY_ID));

which seems to do the trick.

**Comment by mikepenz** [comment]
@jonathan-caryl also the following will fix your issue:

```java
result.getAdapter().withPositionBasedStateManagement(false);
```

this will change the way how selections are remembered and will also change the deselectoin / seleciton mechanism. 
Not sure why this is required for this specific tinting, but it works.

**Comment by jonathan-caryl** [comment]
Thanks for that @mikepenz, my `handler` based solution worked in the test app, but still seemed to be showing problems in the actual app. Your fix actually worked!

Still seems a bit weird that it's necessary, but I don't want to spend too much time on it.

**Comment by mikepenz** [comment]
@jonathan-caryl in general the different state management is anyway an improvement. but I did not yet change the drawer to this one as I don't want to break existing implementations with it. 

great that it works now for you too

**Comment by vibinr** [comment]
so I tried adding `.withPositionBasedStateManagement(false)` to the drawer builder, but the issue still persists. Will make a sample app and link it here when I get time.
