### ISSUE TITLE
Toolbar button

### ISSUE THREAD

**Issue by emreaktrk** [mikepenz/MaterialDrawer#164]
I am missing hamburger button in my toolbar. Can you please help me to add hamburger button by using your framework? 

Thanks

**Comment by mikepenz** [comment]
@emreaktrk did you look at the sample application?

What is your layout? What are you trying?

**Comment by emreaktrk** [comment]
I am trying to animate hamburger button.

Activity : https://github.com/emreaktrk/BaskaSinema/blob/master/app/src/main/java/com/akturk/baskasinema/ui/home/HomeActivity.java

Layout : 
https://github.com/emreaktrk/BaskaSinema/blob/master/app/src/main/res/layout/layout_home.xml

**Comment by mikepenz** [comment]
if you want to animate the drawerToggle you have to enable this with 
`.withActionBarDrawerToggleAnimated(true)`

**Comment by emreaktrk** [comment]
Thank you! this is what i am looking for. But it darkens toolbar when drawer is being opened. Can i disable it? :)

**Comment by mikepenz** [comment]
this is the default DrawerLayout implementation it is only possible to remove the complete shadow with this command:

```java
        result.getDrawerLayout().setScrimColor(Color.TRANSPARENT);
```
