### ISSUE TITLE
Dex methods and fields impact(s)

### ISSUE THREAD

**Issue by vanniktech** [mikepenz/MaterialDrawer#1642]
I just added MaterialDrawer to a fresh project and came to realize that it rather adds a lot of fields even after proguard.

All in all after proguard MaterialDrawer added around 1,5k methods which is acceptable.
However 5000 fields were added.

Is this wanted / normal?

**Comment by mikepenz** [comment]
@vanniktech the MaterialDrawer needs dependencies to the appcompat v7 library, which has a reference to the support v4 library. So alone because of these it includes many methods and fields. 
The MaterialDrawer itself does not add too much.

**Comment by vanniktech** [comment]
Yeah however I have those dependencies already. I use them myself.

**Comment by mikepenz** [comment]
so you did exclude those already. 

the materialdrawer also contains many default items. which should be removed from proguard anyway.

**Comment by mikepenz** [comment]
for the future I might consider a `core` `MaterialDrawer` which will remove all default items, but a basic Primary, and Secondary item. and perhaps a header.
