### ISSUE TITLE
Removing an item with subitems

### ISSUE THREAD

**Issue by seang96** [mikepenz/MaterialDrawer#1643]
If you remove an item that has subitems with removeItem() it places its subitems in the parent list. If I remove the subitem before removing the item, and add the main item later it will start collapsed.

**Comment by mikepenz** [comment]
`removeItem` will trigger the `remove` method on the `FastAdapter`
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L727

Which basically removes the item from the list and notifies thea dapter about the change:
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java#L428

It won't care about sub items. So if you want to remove this, you should make sure to collapse this item first (so no subitems are shown) and then you remove the parent. 


I am not sure what you wanted to say with the second sentence. You can expand / collapse items at anytime programatically too

**Comment by seang96** [comment]
How can you expand/collapse programmatically? withExpandable(true)? That didn't work since I reused the drawer.

**Comment by mikepenz** [comment]
@seang96 yes you can. 

The `MaterialDraewr` bases on the `FastAdapter` so you can use it's APIs for anything you want :D

First get the `FastAdapter`:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L224

and ten you can just call `collapse`
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1309
or so..



------ 

So to your answer. why `withExpandable(true)` does not work. This is only used for the initial displaying of the drawer, it won't expand/collapse at a later time. for this the above mentioned methods should be used

**Comment by seang96** [comment]
Yeah that is what I figured with with expandable. The adapter api seems more useful than I thought. Thanks for the information!
