### ISSUE TITLE
[ASK] Custom mini drawer item

### ISSUE THREAD

**Issue by cardovaeric** [mikepenz/MaterialDrawer#1644]
Dear all,

How can i make custom mini drawer item ?
so basically i want to make mini drawer item with label below icon.

Thanks,

**Comment by mikepenz** [comment]
There is a branch showing how this can be done: 

https://github.com/mikepenz/MaterialDrawer/commit/8deedf8470f19c74ed6b826fd5aadc4eaed506da

I hope this helps

**Comment by zayn1991** [comment]
I posted comment for your code, Mike
https://github.com/mikepenz/MaterialDrawer/commit/8deedf8470f19c74ed6b826fd5aadc4eaed506da
May you answer, please. There is few errors
