### ISSUE TITLE
MaterialDrawerTheme.TranslucentStatus

### ISSUE THREAD

**Issue by hamidjahandideh** [mikepenz/MaterialDrawer#1645]
hi
i designed this layout
![photo_2016-12-02_05-40-22](https://cloud.githubusercontent.com/assets/6348409/20820676/411f45c6-b852-11e6-8f00-be65c1acb84c.jpg)

but after adding mikepenz drawer , its change to this :
![photo_2016-12-02_05-40-30](https://cloud.githubusercontent.com/assets/6348409/20820714/7456200e-b852-11e6-9bac-1e3ed85f04ec.jpg)

i want to status bar not change in adding drawer 
my drawer code is :
` drawer = new DrawerBuilder()
                .withActivity(this)
                .withTranslucentStatusBar(true)
               ...`

and activity theme is :
`android:theme="@style/MaterialDrawerTheme.TranslucentStatus"`

what the problem ?

**Comment by mikepenz** [comment]
@hamidjahandideh please take a look in the `CollapsingToolbar` sample
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CollapsingToolbarActivity.java
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/activity_sample_collapsing_toolbar.xml

**Comment by hamidjahandideh** [comment]
it just corrected with 
`android:fitsSystemWindows="true"`
Thanks Mikepenz 👍
