### ISSUE TITLE
costing error

### ISSUE THREAD

**Issue by mujahid1001** [mikepenz/MaterialDrawer#1647]
i want to use built in navigation drawer but this error will occur

android.support.v4.widget.DrawerLayout cannot be cast to com.mikepenz.crossfade drawerlayout.view.Crossfade DrawerLayout

**Comment by mikepenz** [comment]
@mujahid1001 as the error indicates you are trying to cast the `DrawerLayout` to a `CrossfadeDrawerLayout` somewhere. What's your code? 

Please follow and check out the sample app showcasing the implementation

**Comment by mujahid1001** [comment]
![image](https://cloud.githubusercontent.com/assets/18958600/20862842/28ac53e4-b9d8-11e6-9e4b-a33dabb24103.png)

**Comment by mikepenz** [comment]
just replace `result.getDrawerLayout().closeDrawer` with `crossfadeDrawerLayout.closeDrawer(..)`
