### ISSUE TITLE
Action item that is not checkable (i.e., a shortcut for a settings activity)

### ISSUE THREAD

**Issue by davidcesarino** [mikepenz/MaterialDrawer#1655]
Is it possible to create shortcuts for Settings etc. that don't become the selected item when clicked? AFAIK, the `withCheckable` method defines this behavior, but it is not defined for primary and secondary items.

For example, define a drawer with primary items i1, i2, i3 and i4, where i1 is the currently selected item by user. Make it so that clicking i4 does not steal the selection/checked state from i1, but otherwise has normal behavior regarding the relation with the drawer. How do I do that when `withCheckable` is not available for that class?

I noticed that, in the demo, action items like settings shortcuts also steal the selection, when, at least in my case, I don't think it would be semantically appropriate since settings are not being seen in there.

So, right now, in order to achieve the behavior I want, I need to implement drawer's `withOnDrawerItemClickListener`, and then verify if the identifier equals any of the action items and then use the drawer's `setSelection` to select again what was previously selected, and, of course, returning false to allow the drawer to be closed.

This is still not ideal as the visual cue still goes briefly to the new item (i4 in that example) before returning to what was previously selected.

Is it possible without rewriting custom items? Like, with a higher level abstraction as `withCheckable` for them as well?

Thank you for your attention.

**Comment by mikepenz** [comment]
@davidcesarino thanks for the detailed description. 

This is shown in the sample activity. It's `withSelectable()`

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L119

**Comment by davidcesarino** [comment]
That's exactly what I need.

Sorry for the trouble, I'm stupid and looked at the method list and sources and still somehow didn't see it.

Thank you and have a great day.
