### ISSUE TITLE
Icon in selected primary items not change color when use vector drawable

### ISSUE THREAD

**Issue by bagrusss** [mikepenz/MaterialDrawer#1657]
I use vector icons in my project. This is an example of my code to create drawer items:
`                PrimaryDrawerItem().withName(R.string.map).withIcon(android.R.drawable.ic_delete).withSelectedIconColor(R.color.colorPrimary)
`

But icons not change color when item is selected. And vector drawable enabled in build.gradle
`defaultConfig {
       ...
        vectorDrawables.useSupportLibrary = true
    }`

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/1625
