### ISSUE TITLE
How MaterialDrawer works with Fragments?

### ISSUE THREAD

**Issue by rakesh1988** [mikepenz/MaterialDrawer#1658]
Hi Mike,
Before I could start using the library, I had few doubts. Your example app shows how to display drawer and multiple activities. I am more keen on having one activity with switching between fragments based on the navigation menu clicks. 

Currently, I am using default material drawer and I am having tough time managing states of each fragment on navigation. I wanted to understand if your library has any option to handle such scenario.

**Comment by mikepenz** [comment]
@rakesh1988 the sample app does just show how to use the drawer. the drawer has the events where you can do whatever you wish. that's up to you. 

handling the state is nothing the drawer should care about (the same as for the default drawer from the design lib)
