### ISSUE TITLE
is the behaviour of handleShowOnFirstLaunch correct?

### ISSUE THREAD

**Issue by edvaldeysteinsson** [mikepenz/MaterialDrawer#1659]
The current implementations sets "PREF_USER_LEARNED_DRAWER" to true directly after first launch, i'm not sure what the material design guidelines say about this but the older navigation drawer guidelines say that one should continue to open the drawer on app start until the user has manually opened it once and then have it closed at app start.

see http://www.androiddocs.com/design/patterns/navigation-drawer.html#Interaction

I think both ways have their use cases so any thoughts about having support for both? i.e. one that only shows it the first time and one that shows it until the user has opened it manually?

**Comment by mikepenz** [comment]
The interaction is correct. 

If you would love to add support for the other implementation, please just open a PR
