### ISSUE TITLE
Cannot find class

### ISSUE THREAD

**Issue by mshi** [mikepenz/MaterialDrawer#166]
Hello again,

I'm having these output in logcat. It seems that the classes are missing or something. I'm building with gradle and I've imported via `compile('com.mikepenz.materialdrawer:library:2.6.0@aar') {
        transitive = true
    }`
The drawer seems to work, but there's a big delay between clicking on the item to displaying the drawer. And within that delay is the output below.

Thanks!

>  W/dalvikvm﹕ Unable to resolve superclass of Lcom/mikepenz/materialdrawer/view/BezelImageView$CustomOutline; (1526)
 W/dalvikvm﹕ Link of class 'Lcom/mikepenz/materialdrawer/view/BezelImageView$CustomOutline;' failed
 E/dalvikvm﹕ Could not find class 'com.mikepenz.materialdrawer.view.BezelImageView$CustomOutline', referenced from method com.mikepenz.materialdrawer.view.BezelImageView.onSizeChanged
 W/dalvikvm﹕ VFY: unable to resolve new-instance 6768 (Lcom/mikepenz/materialdrawer/view/BezelImageView$CustomOutline;) in Lcom/mikepenz/materialdrawer/view/BezelImageView;
 D/dalvikvm﹕ VFY: replacing opcode 0x22 at 0x0006
 W/dalvikvm﹕ Unable to resolve superclass of Lcom/mikepenz/materialdrawer/view/BezelImageView$CustomOutline; (1526)
 W/dalvikvm﹕ Link of class 'Lcom/mikepenz/materialdrawer/view/BezelImageView$CustomOutline;' failed
 D/dalvikvm﹕ DexOpt: unable to opt direct call 0xc1f4 at 0x08 in Lcom/mikepenz/materialdrawer/view/BezelImageView;.onSizeChanged
 I/dalvikvm﹕ Could not find method android.view.Window.setStatusBarColor, referenced from method com.mikepenz.materialdrawer.Drawer.build
 W/dalvikvm﹕ VFY: unable to resolve virtual method 12938: Landroid/view/Window;.setStatusBarColor (I)V
 D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x007b

**Comment by mikepenz** [comment]
@mshi this log output is shown if you use the drawer on an api version lower than 21. this is default ouput for methods which are declared with a target api. so you don't have to be scared about this. 

the delay. i'm not sure which delay. when you click and the drawer closes? there is a custom delay of 200ms to improve animations. you can disable this if you want
