### ISSUE TITLE
replacing subItems to expandable causes issue

### ISSUE THREAD

**Issue by tomdiinur** [mikepenz/MaterialDrawer#1660]
First, Great project, I love using this library!
I have expandable drawer item which contains group members, each profile has different members.
The first initialized  profile has 5 members:
![screenshot_20161214-212738](https://cloud.githubusercontent.com/assets/9990825/21197644/d8cec580-c244-11e6-9a36-7b4b26593760.png),
Then I change profile whom has only 4 members, the expandable drawer item is still open so I see the same list:
![screenshot_20161214-212721](https://cloud.githubusercontent.com/assets/9990825/21197684/045f09bc-c245-11e6-9b75-5f738d7701cc.png)
But now when I close the list of members (Which really has 4 members in it) It only 'gathering' 4 members into it (as the number of sub items it's really has).
so my list looks like this:
![screenshot_20161214-212749](https://cloud.githubusercontent.com/assets/9990825/21197783/624c05ac-c245-11e6-82d5-bfa2ec192ab6.png)
And when I re-open it:
![screenshot_20161214-213433](https://cloud.githubusercontent.com/assets/9990825/21197801/7baa691c-c245-11e6-8903-671f128d86a1.png)

And there are 5 members (because the one in the bottom sticks),
Is there any way fixing this?
I don't mind close the expandable in case it's open when user changes profile but I'm not sure how to do this.
please contact me.
email - tomdinur@gmail.com
thanks!!!

**Comment by mikepenz** [comment]
@tomdiinur  if you update a sublist of a collapseable item you have to notify the adapter that it's subitems were changed.

Please read more here: https://github.com/mikepenz/MaterialDrawer/issues/1260#issuecomment-218735178
