### ISSUE TITLE
Drawer.setSelection does not work for nested SecondaryDrawerItem inside ExpandableBadgeDrawerItem

### ISSUE THREAD

**Issue by davidesoldan** [mikepenz/MaterialDrawer#1666]
Hi Mike,
I'm using your great library and I have a question (don't know if it is a bug):
if I try to set the current selected item with the method
`Drawer.setSelection(IDENTIFIER, false);`
for a PrimaryDrawerItem, all works correctly.
But trying to do the same thing with this element
`ExpandableBadgeDrawerItem exapndableItem = new ExpandableBadgeDrawerItem().withName(ITEM).withSubItems(
new SecondaryDrawerItem().withName(SUBITEM).withIdentifier(IDENTIFIER));`
it doesn not work. The expandable item remains collapsed and so I cannot see the subitem selected.
Is this a bug or am I doing something wrong?
Thank you so much!
Davide

**Comment by mikepenz** [comment]
Can you please try the following: 
https://github.com/mikepenz/MaterialDrawer/issues/1638#issuecomment-263698468

**Comment by davidesoldan** [comment]
Thanks for the quick reply!
I tried to set
`drawer.getAdapter().withPositionBasedStateManagement(false);`
after
`drawer = new DrawerBuilder()[...].build()`
but it still doesn't work

**Comment by mikepenz** [comment]
@davidesoldan oh sorry. 

Please keep the setting I proposed, in addition you have to "expand" the parent (this won't automatically be done)

So for this there is the  `expand()` method: https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1451 

```java
drawer.getAdapter().expand(int position)
```

**Comment by davidesoldan** [comment]
Ok, but when I have to select and expand to the right position, I only know the identifier of the subitem ... I tried to do this:
```
drawer.setSelection(IDENTIFIER, false);
drawer.getAdapter().expand(drawer.getCurrentSelectedPosition());
```
but the first row always return false and the `getCurrentSelectedPosition` returns -1 for the nested items.
All works correctly for non nested items...

**Comment by davidesoldan** [comment]
Oh, I have found that if I do:
```
drawer.getAdapter().expand()
drawer.setSelection(IDENTIFIER, false);
```
it works! So the problem is to select a nested item before expanding its parent...

**Comment by mikepenz** [comment]
@davidesoldan have you kept:
```
drawer.getAdapter().withPositionBasedStateManagement(false);
```
? 

If this is not done it won't allow selections inside a hidden expandable element. For this to work you then also need to make sure your items have identifiers

**Comment by davidesoldan** [comment]
Yes, I kept the setting `withPositionBasedStateManagement` and the items that I need to select all have an identifier...

**Comment by mikepenz** [comment]
@davidesoldan ok after another deep look. The problem is the following. the `FastAdapter` would not be able to select the item with the identifier as it is currently not in the list. So:
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1051
won't return an item if it is not currently shown. 

If you still want to select it. Keep this one:
```java
drawer.getAdapter().withPositionBasedStateManagement(false);
```

and then just set the item itself selected. 
```java
youSubItem.withSetSelected(true)
```

**Comment by davidesoldan** [comment]
Hi Mike,
thanks you so much for your further reply!
I'm trying your last tip, but without luck. When I have to select the subItem the only thing that I know is its identifier, so I tried to retrive the subItem with 
drawer.getDrawerItem(SUBITEM_IDENTIFIER)
but the method returns null for nested hidden items. So I cannot the subItem that I need to select...

**Comment by mikepenz** [comment]
@davidesoldan that's exactly the same for the drawer itself. You will have to know the item which you want to select. don't you know the parent?

**Comment by AllanWang** [comment]
Is `drawer.getAdapter().withPositionBasedStateManagement(false);` still the only fix if we programmatically select drawer items with tinting? If so, is there any reason not to include that by default since no drawer will have an enormous number of items?
