### ISSUE TITLE
Drawer and tablet

### ISSUE THREAD

**Issue by zTrap** [mikepenz/MaterialDrawer#1667]
Hi, Mike, thank you for your awesome lib, it works fine, but i dont find any solutions.  Probably you can give me answer. I need to keep drawer **always opened on tablets** and **opened/closed on phones**. I'm trying to use `result.getDrawerLayout().setDrawerLockMode(int mode);` but it don't allow all my touches on content. Maybe you have some ideas for resolve this trouble?

**Comment by mikepenz** [comment]
@zTrap the best for this approach is if you programatically decide if you are on phone or tablet. 
If you are on phone you will use the normal `.build()` 
If you are on a tablet, you use the `.buildView()` method and add the returned view to your layout programatically. For tablet's you don't need the `DrawerLayout`

**Comment by zTrap** [comment]
@mikepenz yes, it's best for me. Thank you very match. You are awesome!!! :)
