### ISSUE TITLE
Bug & Question - withStickyFooter

### ISSUE THREAD

**Issue by TurKurT656** [mikepenz/MaterialDrawer#167]
TnQ for new update.
But there is a few bugs here:
![device-2015-03-28-140430](https://cloud.githubusercontent.com/assets/7152030/6880514/806b3cc8-d553-11e4-8f1e-c81482bf2aff.png)
Bugs:
1- bottom divider is lighter (and thinner) than the DividerItems in the above.
2- bottom divider has no marginBottom of 8dp like DividerItems.
3- The Icon of stickyfooter is small and has no marginLeft of 16dp (also the name).

Question:
If i want to that stickyFooter Item be selectable like the primaryItems (when i select it close drawer and the color changes to primaryColor and the other Items unselected) how can i do that?

**Comment by mikepenz** [comment]
@TurKurT656 oh i see that there's a difference have to fix them. :/ sorry about those.

The items in the stickyFooter are not selectable or do not have a "active" (current selected) state. Closing the drawer is not yet in but yeah you are right i should add this too. 


EDIT:
ok i only see the lower height with those items. Here's a screenshot:
![730409286_7449847654423691950](https://cloud.githubusercontent.com/assets/1476232/6880612/96607f9c-d53b-11e4-9fef-28ec6188617a.jpg)
Will test it on lower api versions. perhaps this is the difference

**Comment by TurKurT656** [comment]
so are you going to add this feature(selectable state)?

**Comment by mikepenz** [comment]
i'll look at it and how i could possible get it working. but no promises :D

**Comment by TurKurT656** [comment]
TnQ very much :)

**Comment by binarybucks** [comment]
While you're at it, could you add an interface to set drawer items as the sticky footer without explicitly specifying a layout? Maybe add a ```withOnFooterItemClickListener``` that accepts an ```OnDrawerItemClickListener``` listener to handle clicks to footer elements. 

This would make it much easier to set a sticky settings item. 

Besides that, thanks for your great work. It's really useful and easy to implement.

**Comment by mikepenz** [comment]
@binarybucks i completely changed the api to add a sticky footer item with the next release ;). Is even easier than now :D

thank you so much

**Comment by binarybucks** [comment]
wow, that was fast and it works really well. 
Only thing is, the secondary items now have a pink ripple effect instead of a grey one :D 

![screenshot_2015-03-29-14-15-02](https://cloud.githubusercontent.com/assets/782356/6885372/19a175a4-d61e-11e4-8448-f75aae4d9477.png)

**Comment by mikepenz** [comment]
Hi.

Yeah they have the accent color as far as i've seen. Somehow this is system
default item selector :D
Not yet sure how to change this. i just use system default things

**Comment by binarybucks** [comment]
That's the only ripple appearing in pink. 
I've not yet dug into the code, but how are the secondary ones different from the primary drawer items?

**Comment by mikepenz** [comment]
@binarybucks the normal list items have system default list item selector. 
those items are not within a list item. they get the selectable drawable with this methdod:

https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/java/com/mikepenz/materialdrawer/util/UIUtils.java#L61

**Comment by mikepenz** [comment]
@ok found an additional issue i try to fix this :dancer:

**Comment by binarybucks** [comment]
Don't rush, the speed of your fixes and changes is insane allreay ;)

**Comment by TurKurT656** [comment]
Yes he is fixing like a machine :D

**Comment by mikepenz** [comment]
haha :P

**Comment by binarybucks** [comment]
works perfectly now. Thank you very much.
