### ISSUE TITLE
Only allow dragging to show drawer when dragging the toolbar

### ISSUE THREAD

**Issue by jidesoft** [mikepenz/MaterialDrawer#1670]
Is there a way to allow dragging to show a left drawer only when the dragging on the toolbar? My app has a map in the center so it is very easy to trigger the drawer accidentally when I just want to move the map. Thanks.

**Comment by mikepenz** [comment]
@jidesoft I don't know of any such functionality. You probably could lock the drawer, and just allow toggling it via the `ActionBarDrawerToggle` in the toolbar

**Comment by jidesoft** [comment]
I thought about that too but in certain cases, I changed the drawer toggle button to go back button, tap it will go back instead of opening the drawer.
