### ISSUE TITLE
Bug in click handling on the ActionBarToggle ?

### ISSUE THREAD

**Issue by mindwalkr** [mikepenz/MaterialDrawer#1671]
I have an option in a menu called "Settings".  Clicking this item replaces the current menu with new contents via changing the IDrawerItem's in the adapter, while keeping the menu open.  This works nicely.  However, I want to intercept the Actionbar back button (it is not routed through onBackPressed() for some reason) and back out from the Settings menu to the previous menu.

My plan was to add a OnDrawerNavigationListener(), check if the settings menu was displayed and if so, no op.

I tried to add a OnDrawerNavigationListener(), but it was not being called.  Digging deeper, I found that DrawerBuilder::handleDrawerNavigation has the following check:
`if (mOnDrawerNavigationListener != null && (mActionBarDrawerToggle != null && !mActionBarDrawerToggle.isDrawerIndicatorEnabled())) {`

Shouldn't that last part be:  
`mActionBarDrawerToggle.isDrawerIndicatorEnabled()`
 instead of 
`!mActionBarDrawerToggle.isDrawerIndicatorEnabled()`
 ?

As it stands, a onNavigationListener() will never get called.....

**Comment by mindwalkr** [comment]
As a workaround, you can set a NavigationClickListener on the toolbar AFTER build() has been called to overwrite the one that build() created.

**Comment by mikepenz** [comment]
@mindwalkr in general this logic is in since 2 years so I assume it should be correct. 

The MaterialDrawer managing this is just a little tiny helper thing, so just don't provide a `Toolbar` to the drawer, and then you can manage the `ActionBarDrawerToggle` completely on your side.

**Comment by mikepenz** [comment]
@mindwalkr you can see the drawer's internal logic here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1387
