### ISSUE TITLE
getDrawerItem(NAVID_LOGIN) only works correct with IDs?

### ISSUE THREAD

**Issue by just4phil** [mikepenz/MaterialDrawer#1672]
Hi ....
first of all: thanks for the really great library!!!! :) 👍 

i have some problem here with this snippet:

```java
 public void setMaterialDrawerLogInOut(boolean userIsSignedIn) {
        if(userIsSignedIn) {
            if (materialDrawer.getDrawerItem(NAVID_LOGIN) != null) {
                materialDrawer.removeItem(NAVID_LOGIN);
            }
            if (materialDrawer.getDrawerItem(NAVID_LOGOUT) == null) {
                materialDrawer.addItem(item9);
            }
        }
        else {
            if (materialDrawer.getDrawerItem(NAVID_LOGOUT) != null) {
                materialDrawer.removeItem(NAVID_LOGOUT);
            }
            if (materialDrawer.getDrawerItem(NAVID_LOGIN) == null) {
                materialDrawer.addItem(item8);
            }
        }
    }
```

this lines 
if (materialDrawer.getDrawerItem(NAVID_LOGIN) == null) {
seems to work only with `IDs.

this seems to be buggy:
if (materialDrawer.getDrawerItem(item8) == null) {

i guess its my fault but wanted to report.....

HAPPY CHRISTMAS!!!

bye
phil

**Comment by mikepenz** [comment]
@just4phil it also works with items. But those need an ID defined too ;)

Happy Christmas. :)

**Comment by just4phil** [comment]
hmmm strange... they have an ID....
but thankx for the quick reply!

**Comment by mikepenz** [comment]
@just4phil oh sorry. I mixed it up. This method won't depend on the identifier. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L423

It requires the `DrawerItem` to have a `Tag` set. As thi smethod searches per tag:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerUtils.java#L140

**Comment by just4phil** [comment]
ok thx!
