### ISSUE TITLE
Vectore drawable padding

### ISSUE THREAD

**Issue by amorenew** [mikepenz/MaterialDrawer#1674]
Hi
in my drawer the vector drawable doesn't have padding on start in pre-lollipop

**Comment by mikepenz** [comment]
@amorenew you use the `VectorDrawableCompat`?

**Comment by amorenew** [comment]
yes
i will make more investigation and i will put feedback if i got workaround

**Comment by amorenew** [comment]
i solved it by converting the vector drawable to bitmap then adding padding then convert it back to drawable

            ```
Drawable drawableIcon = ResourcesCompat.getDrawable(getResources(), icon, null);
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
                Bitmap bitmap = drawableToBitmap(drawableIcon);
                drawableIcon = new BitmapDrawable(getResources(), addBitmapPadding(bitmap, 15, 0));
            }
            drawerItem.withIcon(drawableIcon);
```

**Comment by amorenew** [comment]
`    public Bitmap addBitmapPadding(Bitmap Src, int padding_x, int padding_y) {
        Bitmap outputImage = Bitmap.createBitmap(Src.getWidth() + padding_x, Src.getHeight() + padding_y, Bitmap.Config.ARGB_8888);
        Canvas can = new Canvas(outputImage);
        can.drawBitmap(Src, padding_x, padding_y, null);
        return outputImage;
    }

    public Bitmap drawableToBitmap(Drawable drawable) {
        if (drawable instanceof BitmapDrawable) {
            return ((BitmapDrawable) drawable).getBitmap();
        }

        int width = drawable.getIntrinsicWidth();
        width = width > 0 ? width : 1;
        int height = drawable.getIntrinsicHeight();
        height = height > 0 ? height : 1;

        Bitmap bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bitmap);
        drawable.setBounds(0, 0, canvas.getWidth(), canvas.getHeight());
        drawable.draw(canvas);
        return bitmap;
    }`

**Comment by mikepenz** [comment]
@amorenew thank you very much.

**Comment by amorenew** [comment]
@mikepenz you are welcome
