### ISSUE TITLE
Added elements are not saved

### ISSUE THREAD

**Issue by Yundin** [mikepenz/MaterialDrawer#1676]
Hi! I can't save elements added by user. After destroy the state is returned to the original. What I'm doing wrong?

    Drawer result;
    int number = 5;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main);

        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        getSupportActionBar().setDisplayHomeAsUpEnabled(false);

        final TextView text = (TextView) findViewById(R.id.text);

        AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.header)
                .withCompactStyle(true)
                .build();

        result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .addDrawerItems(
                        new PrimaryDrawerItem().withIdentifier(2).withName(R.string.first).withIcon(GoogleMaterial.Icon.gmd_queue_music),
                        new PrimaryDrawerItem().withIdentifier(3).withName(R.string.second).withIcon(GoogleMaterial.Icon.gmd_queue_music),
                        new PrimaryDrawerItem().withIdentifier(4).withName(R.string.third).withIcon(GoogleMaterial.Icon.gmd_queue_music),
                        new PrimaryDrawerItem().withIdentifier(5).withName("Четвертая категория").withIcon(GoogleMaterial.Icon.gmd_queue_music),
                        new DividerDrawerItem(),
                        new SecondaryDrawerItem().withIdentifier(1).withName(R.string.add).withIcon(GoogleMaterial.Icon.gmd_add)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        // do something with the clicked item :D
                        if (drawerItem.getIdentifier() == 1) {
                            number++;
                            result.addItemAtPosition(new PrimaryDrawerItem().withIdentifier(number).withName("Added").withIcon(GoogleMaterial.Icon.gmd_queue_music), (number-1));

                        }
                        else{
                            result.closeDrawer();
                            String str = "Activity number " + (drawerItem.getIdentifier()-1);
                            text.setText(str);
                            Toast.makeText(getApplication(), "Hello", Toast.LENGTH_SHORT).show();
                        }
                        return true;
                    }
                })
                .withAccountHeader(headerResult)
                .withSavedInstance(savedInstanceState)
                .build();

        result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);

    }

    @Override
    public void onBackPressed() {
        if (result != null && result.isDrawerOpen()) {
            result.closeDrawer();
        } else {
            super.onBackPressed();
        }
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        outState = result.saveInstanceState(outState);
        super.onSaveInstanceState(outState);
    }

**Comment by mikepenz** [comment]
@Yundin the restore state can only retain the selected position. It can't save elements added by the user. That logic is up to the developer using the drawer.
