### ISSUE TITLE
isSelected is always false, even though item is clicked

### ISSUE THREAD

**Issue by bbetter** [mikepenz/MaterialDrawer#1677]
in my custom primary item
isSelected is always false, even though item is clicked
so I can't set color filter depending on item selection
it works well with setting tint on android lollipop and higher, but compatible version is working bad 
because of is selected is always false
 ```java
@Override
    public void bindView(ViewHolder viewHolder) {
        Context context = viewHolder.itemView.getContext();
        DrawerPrimaryItemBinding binding = DataBindingUtil.bind(viewHolder.itemView);

        if (binding != null) {
            if (getName() != null)
                binding.setTitle(getName().getText());
            if (getIcon() != null) {
                Drawable drawable = context.getResources().getDrawable(getIcon().getIconRes());
                ColorStateList list = context.getResources().getColorStateList(R.color.drawer_primary_item_text_color);
                Drawable transformDrawable = DrawableCompat.wrap(drawable);
                if (list != null) {
                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                        transformDrawable.setTintList(list);
                    } else {
                        Log.i("DRAWER_ITEM#"+getName().getText(), viewHolder.itemView.isSelected() ? "selected":"not selected");
                        int color = list.getColorForState(new int[]{viewHolder.itemView.isSelected() ?  android.R.attr.state_selected : -android.R.attr.state_selected}, Color.TRANSPARENT);
                        Log.i("DRAWER_ITEM_COLOR#" + getName().getText(), (color == context.getResources().getColor(R.color.aqua_blue) ? "blue" : "black"));
                        transformDrawable.setColorFilter(new PorterDuffColorFilter(color, PorterDuff.Mode.MULTIPLY));
                    }
                }
                binding.setIcon(transformDrawable);
            }

            binding.setNotifications(displayBadge);
        }
```

**Comment by mikepenz** [comment]
how does the rest of your item look like? Do you even have the `selectable` boolean in your item? Or do you use the `AbstractDrawerItem`? You should also call the super method on the `bindView`

By the way. why don't you use the default functionality of the `ColorStateList` there should be no necessity to handle this on your own

**Comment by bbetter** [comment]
sorry for not answering for so long
I've finally managed to make it work

but there is still one strange problem
from
`<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data>

        <variable
            name="title"
            type="java.lang.String" />

        <variable
            name="icon"
            type="Drawable" />

        <variable
            name="notifications"
            type="java.lang.Boolean" />

        <import type="android.view.View" />

        <import type="android.graphics.drawable.Drawable" />

    </data>

    <LinearLayout
        android:id="@+id/root"
        android:layout_width="match_parent"
        android:layout_height="60dp"
        android:orientation="horizontal">

        
        <ImageView
            android:layout_width="24dp"
            android:layout_height="21.1dp"
            android:layout_gravity="center_vertical"
            android:layout_marginLeft="16dp"
            android:layout_marginStart="16dp"
            android:contentDescription="@string/drawer_menu_icon"
            android:scaleType="fitCenter"
            android:tint="@color/drawer_primary_item_text_color"
            android:src="@{icon,default=@drawable/clock}"
            tools:src="@drawable/icon_house_alt" />

        <TextView
            android:id="@+id/textView2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical"
            android:layout_marginLeft="32dp"
            android:layout_marginStart="32dp"
            android:gravity="center_vertical"
            android:text="@{title}"
            android:textColor="@color/drawer_primary_item_text_color"
            android:textSize="14sp"
            app:fontName="@{@string/roboto_medium}"
            tools:text="Home" />

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="end"
            android:visibility="@{notifications ? View.VISIBLE : View.GONE}">

            <TextView
                android:id="@+id/textView4"
                android:layout_width="20dp"
                android:layout_height="20dp"
                android:layout_gravity="center_vertical"
                android:layout_marginEnd="25dp"
                android:layout_marginRight="25dp"
                android:background="@drawable/pink_circle"
                android:gravity="center"
                android:paddingBottom="3dp"
                android:text="@string/exclamation_mark_notifications"
                android:textColor="@color/md_white_1000"
                android:textSize="14sp"
                app:fontName="@{@string/roboto_bold}" />

        </LinearLayout>

    </LinearLayout>

</layout>
`

`package` io.bitspark.android.views.customs.drawer;

import android.content.Context;
import android.content.res.ColorStateList;
import android.databinding.DataBindingUtil;
import android.graphics.drawable.Drawable;
import android.os.Build;
import android.support.v4.graphics.drawable.DrawableCompat;

import com.mikepenz.materialdrawer.model.PrimaryDrawerItem;

import io.bitspark.android.R;
import io.bitspark.android.databinding.DrawerPrimaryItemBinding;

/**
 * Created by mac on 14.05.16.
 */
public class CustomPrimaryItem extends PrimaryDrawerItem {
    private boolean displayBadge = false;

    public CustomPrimaryItem withNotification(boolean displayBadge) {
        this.displayBadge = displayBadge;
        return this;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.drawer_primary_item;
    }

    @Override
    public void bindView(ViewHolder viewHolder) {
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            viewHolder.itemView.setSelected(isSelected());
        }
        Context context = viewHolder.itemView.getContext();
        DrawerPrimaryItemBinding binding = DataBindingUtil.bind(viewHolder.itemView);

        if (binding != null) {
            if (getName() != null)
                binding.setTitle(getName().getText());
            if (getIcon() != null) {
                Drawable drawable = context.getResources().getDrawable(getIcon().getIconRes());
                ColorStateList list = context.getResources().getColorStateList(R.color.drawer_primary_item_text_color);
                Drawable transformDrawable = DrawableCompat.wrap(drawable);
                if (list != null) {
                    DrawableCompat.setTintList(transformDrawable, list);
                }
                binding.setIcon(transformDrawable);
            }

            binding.setNotifications(displayBadge);
        }
    }
}`
the issue is that if i keep on clicking on items in drawer, at some moment the icon is disappearing

**Comment by mikepenz** [comment]
could it be possibly realted to databinding?

**Comment by bbetter** [comment]
i've dived into the primary item bindView realization and find the viewHolder.itemView.setTag(this);
is it somehow important thing to have?

**Comment by mikepenz** [comment]
@bbetter sorry for the very very late answer. Yes it is important. 
Have you solved it by then? Please report back and re-open if it'S still an issue

**Comment by bbetter** [comment]
no,   fixed that somehow, though took me few bad days of not knowing what's happening, anyway thanks for quick responses and support. sorry for not closing.
