### ISSUE TITLE
Can i use custom image loader for drawer's header image?

### ISSUE THREAD

**Issue by bagrusss** [mikepenz/MaterialDrawer#1679]
Can i use custom image loader for drawer's header image as in [this](https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java) example ?

**Comment by mikepenz** [comment]
@bagrusss the header itself just takes an image. it does not use this logic. 

If you want to load an image via glide or picasso. Just get the reference to the `ImageView` after the header was created and set the image on it
