### ISSUE TITLE
MaterialDrawer has an uneeded space upon landscape orientation and when app support fullscreen (Immersive mode)

### ISSUE THREAD

**Issue by SupremeProj** [mikepenz/MaterialDrawer#1680]
Hi Mike,
When Setting up my app to support fullscreen / IMMERSIVE, using the following flags:

```
        View decorView = this.activity.getWindow().getDecorView();
        decorView.setSystemUiVisibility(iew.SYSTEM_UI_FLAG_LAYOUT_STABLE |
                View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION |
                View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN |
                View.SYSTEM_UI_FLAG_HIDE_NAVIGATION |
                View.SYSTEM_UI_FLAG_FULLSCREEN |
                View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);
```

When showing application in landscape orientation there is an unneeded space added in the MaterialDrawer (on it's right area)

As shown in the image attached here:
![issue](https://cloud.githubusercontent.com/assets/24442921/21469074/9fc79128-ca40-11e6-971b-a5e0f1eadaa3.jpg)

NOTE:  The same space shows up when app is in portrait (vertical) orientation. I am pretty sure that this space added is to setup the MaterialDrawer higher so that the Navigation Panel won't hide Drawer options - BUT in landscape orientation this is not relevant since AFAIK Android Navigation panel are not being set to be in landscape. therefor this space should be removed in landscape orientation.

**Can you advise on this please (or supply a fix if needed)?**

Thanks for all of your effort, your Drawer Rocks!

(Maybe it is worth while openning an issue on supporing Fullscreen mode in general, I guess space should not appear in any orientation on fullscreen mode)

**Comment by mikepenz** [comment]
@SupremeProj sounds like this is added by the system because of the `fitsSystemWindows` flag. and in combination with your code it thinks that it has to add this space because of the navigation buttons which would be on the right. 

fullscreen mode is in general handled by the system nothing special done in the drawer itself

**Comment by SupremeProj** [comment]
Thanks for the reply, This means that you are going to fix this?

**Comment by mikepenz** [comment]
@SupremeProj if the issue is what I assume it is, then it could be that it is not easily solveable on my side, and would require custom handling on your side

**Comment by SupremeProj** [comment]
Isn't it a matter of telling the xml layout to start from a certian point upon fullscreen ? 
Can you fill me in about your thinkings, or can you direct me in the code where to look at (give me a few good places to look at)

I really liked this Drawer and i am stubborn to fix this - I really want the Material Drawer to support full screen

**Comment by mikepenz** [comment]
@SupremeProj sadly not. If my assumption is correct the space is added through the `fitsSystemWindows` flag which exists on the drawer content.
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_slider.xml#L11

you might be able to toggle this programatically if you know that the drawer will now be displayed in fullscreen.

**Comment by mikepenz** [comment]
@SupremeProj ok I just checked again. in the `FullscreenDrawerActivity` this is already done like this and works. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/FullscreenDrawerActivity.java#L81

**Comment by SupremeProj** [comment]
On the official Material Drawer app I see that still i get this space when orientation is landscape.
I will check that deeper and will let you know

Thanks for the help

**Comment by mikepenz** [comment]
@SupremeProj oh really? I just tried it on my device and it did not have this space. 

What's your phone and android version?

**Comment by SupremeProj** [comment]
@mikepenz 
Phone:  LG G2,  Android version 4.4.2  (KitKat)
Indeed on my phone I still see the redundant spaces (as you can see in images attached)


Wow another issue i see here (In the official MaterialDrawer app - Fullscreen activity):
Scenario:
Changing to landscape orientation in fullscreen activity.
Actual result:
Navbar style changing from good looking transparent background to a standard grey background.
(see in images attached)

![fullscreen - portrait](https://cloud.githubusercontent.com/assets/24442921/21496761/72a33dce-cc29-11e6-93b0-e2be9fea0a77.png)

![fullscreen - landscape](https://cloud.githubusercontent.com/assets/24442921/21496762/752b8f2e-cc29-11e6-986f-5f010c582f51.png)

**Comment by mikepenz** [comment]
Hmmm it might be a KitKat issue. 

If I am not wrong NavBar in landscape is not transparent. Nothing we can change here.

**Comment by SupremeProj** [comment]
@mikepenz, I will check that on other devices when i'll have a chance - and keep you posted.
Thanks man
