### ISSUE TITLE
Can I add elevation or shadow to minidrawer?

### ISSUE THREAD

**Issue by Mygod** [mikepenz/MaterialDrawer#1683]
I tried to set elevation on `drawer.getMiniDrawer().build(this)`, `drawer.getSlider()`, `crossfader.getContent()` simultaneously and it still won't work.

**Comment by mikepenz** [comment]
the `CrossFader` and the slider is just part of your normal view hierarchy. Theoretically yes. 



But you can also do it like this:
https://github.com/mikepenz/Crossfader/blob/b92469119c5c23067794db8bc7184de3b42c85dd/app/src/main/java/com/mikepenz/crossfader/app/SimpleActivity.java#L137

**Comment by Mygod** [comment]
Okay thanks!

**Comment by pcegarra** [comment]
Is it possible to change the shadow color? I need to draw a red line separation in the end of the drawer
