### ISSUE TITLE
How to create drawer that switches between fragments and even changes the titles of the toolbar

### ISSUE THREAD

**Issue by NovaViper** [mikepenz/MaterialDrawer#1684]
Hey, I just got this drawer and have the drawer created with the profiles but I can't seem to get it to change the screen (they are fragments) when I select a menu item.

I already tried this:
```java 
 						if (drawerItem != null) {
							Intent intent = null;
							if (drawerItem.getIdentifier() == 1) {
								intent = new Intent(MainScreenActivity.this, LockProfileOptionFragment.class);
							} else if (drawerItem.getIdentifier() == 2) {
								intent = new Intent(MainScreenActivity.this, VisualOptionFragment.class);
							} else if (drawerItem.getIdentifier() == 3) {
								intent = new Intent(MainScreenActivity.this, NotificationOptionFragment.class);
							} else if (drawerItem.getIdentifier() == 4) {
								intent = new Intent(MainScreenActivity.this, SecurityOptionFragment.class);
							} else if (drawerItem.getIdentifier() == 5) {
								intent = new Intent(MainScreenActivity.this, MiscOptionFragment.class);
							} else if (drawerItem.getIdentifier() == 6) {
								//intent = new Intent(MainScreenActivity.this, .class);
							} else if (drawerItem.getIdentifier() == 7) {
								//intent = new Intent(MainScreenActivity.this, EmbeddedDrawerActivity.class);
							} else if (drawerItem.getIdentifier() == 8) {
								intent = new Intent(MainScreenActivity.this, AboutAppActivity.class);
							}
							if (intent != null) {
								MainScreenActivity.this.startActivity(intent);
							}
						}

						return false;
					}
				})
				.build();
```

(EDIT: I somehow ended up losing the error for this piece of the coding, but it checked it like an activity..)

I even tried this:

```
Fragment f =(Fragment) new LockProfileOptionFragment();
getSupportFragmentManager().beginTransaction().replace(R.id.fragment_container, f).commit();
```

But that didn't work, giving this error (this is the piece of code that the error I posted before goes to)

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.nova.apps.trinitylocker, PID: 14266
                  java.lang.IllegalArgumentException: No view found for id 0x7f0e00d4 (com.nova.apps.trinitylocker:id/content_layout) for fragment LockProfileOptionFragment{827c1e0 #0 id=0x7f0e00d4}
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1292)
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323)
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136)
                      at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998)
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:709)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:158)
                      at android.app.ActivityThread.main(ActivityThread.java:7237)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                      at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102
```

I tried finding how do I call the Fragments when selecting an item but I don't see that anywhere.. it only talks about the activities.

**Comment by mikepenz** [comment]
@NovaViper the sample just shows different activities as I have different independent activities showing different drawer behaviors. 

The reason why setting the fragment in the first place does not work, because you are trying to start an activity. 

The second exception even exactly writes you what is going wrong. It can't find: `com.nova.apps.trinitylocker:id/content_layout` 

The Drawer gives you all the callbacks you need, so it will inform you that the user clicked. all the rest is up to you, what will happen in this case. 

Switching fragments is nothing library specific. Please just use stackoverflow and google to search for the proper implementation of commiting and changing fragments

**Comment by NovaViper** [comment]
Oh, ok! Um.. what parts of the navigation drawer are provided by the library? (Do I have to create anything in order for it work, like the content layout or the app bar? With the fragments and activities of course set aside).

Honestly, I changed the coding so many times that I thought what the library was missing was actually something I deleted out of my coding (Someone on [Reddit](https://www.reddit.com/r/androiddev/comments/5knwsn/need_help_trying_to_use/) brought this up to me). So.. I'm just going to delete what I have with the drawer so far and just create it again using Google's example and see what pieces I need.

**Comment by mikepenz** [comment]
@NovaViper the `MaterialDrawer` itself brings the ui elements you need inside a `DrawerLayout` to display a drawer as defined in the Google Material Design Guidelines, and a wrapper around these things which will handle `DrawerLayout` creation, `ActionBarDrawerToggle` creation etc. And a nice API so you can fill the drawer programatically without any issues. 

It also gives you all the listeners and callbacks you may need to interact. 

The part where you than commit a fragment or launch an acitvity is up to you, as also in the google drawer itself, as the library can't handle (and shouldn't) handle this for you

**Comment by NovaViper** [comment]
Oh ok! So the library provides the elements to display everything. So I still need to create the basic framework and layouts, right?

**Comment by mikepenz** [comment]
@NovaViper exactly. The MaterialDrawer provides the `Drawer` nothing else. It's up to you if you want to have a `Toolbar` how your content will look like, how navigation works. etc. 

The drawer library will just take care you don't have to care about the drawer, and the items and their design

**Comment by NovaViper** [comment]
Oh *facepalm* Thanks for clarifying that! I feel like an idiot because I didn't even realize what I was doing wrong the entire time. Now, I'm just going to create the example template from Google and branch off and see what happens.

**Comment by mikepenz** [comment]
good luck :)

**Comment by NovaViper** [comment]
Hurray! I got it working!!
