### ISSUE TITLE
How close drawer (mini+crossfader) by click on none selectable item?

### ISSUE THREAD

**Issue by igozhenko** [mikepenz/MaterialDrawer#1685]
Please look at 
https://github.com/mikepenz/MaterialDrawer/blob/82466cf9700fad3461e146d83180b6f76e36d28b/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java#L119-L119 to see item declaraion

I want to implement next behavior of app
- click on item would not  select it
- click on item would close (collapse) drawer

**Comment by mikepenz** [comment]
I think as of the moment clicking a non selectable icon won't trigger the click listener. 

You might need to directly hook in the adapter of the `MiniDrawer` and add a `preClickListener`

**Comment by igozhenko** [comment]
Thanks for response
