### ISSUE TITLE
A Couple of Questions with the Account Header

### ISSUE THREAD

**Issue by NovaViper** [mikepenz/MaterialDrawer#1686]
Hey again, I finally got that drawer working but I have a few questions about the AccountHeader

1. I want to add the 3 dot menu but I can't seem to find a method that does this
2. I want the activity to startup with the first drawer item selected (so it has the fragment associated with it displayed)
3. I want to be able to execute a command when you select one of the profile settings menu (so I can have the user sign out and/or revoke access to their account)
4. Hey I notice a bug where when I sign in my google account, I can't seem to have the profile icon to display the picture of the profile

My code is this:

    public class MainSettingsActivity extends AppCompatActivity {

	private AccountHeader header = null;
	private Drawer result = null;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		GoogleSignInSingleton signInSingleton = GoogleSignInSingleton.getInstance(null);
		GoogleSignInAccount googleAccount = signInSingleton.getGoogleSignIn();

		setContentView(R.layout.activity_main_settings);
		Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
		setSupportActionBar(toolbar);

		createAccountHeader(googleAccount);
		createDrawer(toolbar);

	}

	private void createAccountHeader(GoogleSignInAccount googleAccount){
		header = new AccountHeaderBuilder()
				.withActivity(this)
				.withTranslucentStatusBar(true)
				.withHeaderBackground(R.drawable.header_background)
				.addProfiles(
						new ProfileDrawerItem().withName(googleAccount.getDisplayName()).withEmail(googleAccount.getEmail()).withIcon(googleAccount.getPhotoUrl()),
						new ProfileSettingDrawerItem().withName("Add Account"),
						new ProfileSettingDrawerItem().withName("Manage Accounts")
				)
				.build();
	}

	private void createDrawer(Toolbar toolbar){
		result = new DrawerBuilder()
				.withActivity(this)
				.withToolbar(toolbar)
				.withAccountHeader(header)
				.addDrawerItems(
						new PrimaryDrawerItem().withName(R.string.nav_lock_profile_text).withIcon(ResourcesCompat.getDrawable(getResources(), R.drawable.ic_nav_lock_profile, getApplication().getTheme())).withIdentifier(1),
						new PrimaryDrawerItem().withName(R.string.nav_visual_text).withIcon(ResourcesCompat.getDrawable(getResources(), R.drawable.ic_menu_gallery, getApplication().getTheme())).withIdentifier(2),
						new PrimaryDrawerItem().withName(R.string.nav_notify_text).withIcon(ResourcesCompat.getDrawable(getResources(), R.drawable.ic_nav_notify, getApplication().getTheme())).withIdentifier(3),
						new PrimaryDrawerItem().withName(R.string.nav_security_text).withIcon(ResourcesCompat.getDrawable(getResources(), R.drawable.ic_nav_security, getApplication().getTheme())).withIdentifier(4),
						new PrimaryDrawerItem().withName(R.string.nav_misc_text).withIcon(ResourcesCompat.getDrawable(getResources(), R.drawable.ic_nav_misc, getApplication().getTheme())).withIdentifier(5),
						new DividerDrawerItem(),
						new PrimaryDrawerItem().withName(R.string.nav_tips_tricks_text).withIdentifier(6),
						new PrimaryDrawerItem().withName(R.string.nav_backup_restore_text).withIdentifier(7),
						new PrimaryDrawerItem().withName(R.string.nav_about_text).withIdentifier(8)
				)
				.withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
					@Override
					public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
						Fragment fragment = null;
						FragmentTransaction fragmentTransaction = getSupportFragmentManager().beginTransaction();
						Intent intent = null;
						if (drawerItem.getIdentifier() == 1) {
							fragment = new LockProfileOptionFragment();
						} else if (drawerItem.getIdentifier() == 2) {
							fragment = new VisualOptionFragment();
						} else if (drawerItem.getIdentifier() == 3) {
							fragment = new NotificationOptionFragment();
						} else if (drawerItem.getIdentifier() == 4) {
							fragment = new SecurityOptionFragment();
						} else if (drawerItem.getIdentifier() == 5) {
							fragment = new MiscOptionFragment();
						} else if (drawerItem.getIdentifier() == 6) {

						} else if (drawerItem.getIdentifier() == 7) {

						} else if (drawerItem.getIdentifier() == 8) {
							intent = new Intent(MainSettingsActivity.this, AboutAppActivity.class);
						}

						//Execute the fragments/intents when selected
						if (fragment != null) {
							fragmentTransaction.replace(R.id.main_settings_container, fragment).commit();
						}
						if (intent != null) {
							MainSettingsActivity.this.startActivity(intent);
						}

						return false;
					}
				})
				.withSelectedItem(1)
				.build();
	}

	private void signOut() {
		GoogleAPIClientSingleton googleAPIClientSingleton = GoogleAPIClientSingleton.getInstance(null);
		GoogleApiClient googleApiClient = googleAPIClientSingleton.getGoogleApiClient();

		Auth.GoogleSignInApi.signOut(googleApiClient).setResultCallback(
				new ResultCallback<Status>() {
					@Override
					public void onResult(Status status) {
						AppLogger.debug("signOut:onResult:" + status);
					}
				});
	}

	private void revokeAccess() {
		GoogleAPIClientSingleton googleAPIClientSingleton = GoogleAPIClientSingleton.getInstance(null);
		GoogleApiClient googleApiClient = googleAPIClientSingleton.getGoogleApiClient();

		Auth.GoogleSignInApi.revokeAccess(googleApiClient).setResultCallback(
				new ResultCallback<Status>() {
					@Override
					public void onResult(Status status) {
						AppLogger.debug("revokeAccess:onResult:" + status);
					}
				});
	}

	@Override
	public void onBackPressed() {
		if (result != null && result.isDrawerOpen()) {
			result.closeDrawer();
		} else {
			super.onBackPressed();
		}
	  }
    }

Also, thanks for helping me the last time!

**Comment by NovaViper** [comment]
Hey, I actually just uploaded the code on my [project's Github](https://github.com/NovaViper/TrinityLocker)

**Comment by mikepenz** [comment]
1.) There is no method to do this. as it is not in the material design guidelines. You can overwrite the layout of the header though, and then access the view. 
2.) just set the selection, and enable that the first selectionw ill fire a event, so you can handle the committing of this fragment
3.) just use one of the possible listeners
4.) you have to adjust the `ProfileDrawerItem` and then notify the drawer about the updated item

**Comment by NovaViper** [comment]
Sorry for taking so long to respond

2. I already have the item selected but I can't figure out how to make the drawer fire the event when the activity first starts up
3.  I haven't tested this yet (I just wrote the code and about to test it)
4. I can't seem to figure how to have it update when the activity starts up.. I see only the click events

**Comment by NovaViper** [comment]
I still haven't figured out how to make the profile picture load and I have yet another issue:

I'm trying to get a toast notification to display when pressing one of the Profile settings items, but its not display (but the method that executes after it gets called)

				.withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
					@Override
					public boolean onProfileChanged(View view, IProfile profile, boolean current) {
						//sample usage of the onProfileChanged listener
						//if the clicked item has the identifier 1 add a new profile ;)
						if (profile.getIdentifier() == Constants.profileRemoveID) {

							Toast.makeText(getApplicationContext(), "HIII", Toast.LENGTH_LONG);
							revokeAccess();
							Intent i = new Intent(getApplicationContext(), ChooseSignInActivity.class);
							startActivity(i);
							finish();
						}

						//false if you have not consumed the event and it should close the drawer
						return false;
					}
				})

**Comment by mikepenz** [comment]
I think the toast is not shown when this activity finishes

**Comment by mikepenz** [comment]
what do you mean you can't load the image
do you have the `DrawerImageLoader` set up as shown in the readme?

**Comment by NovaViper** [comment]
Oops, I forgot about that

		//initialize and create the image loader logic
		DrawerImageLoader.init(new AbstractDrawerImageLoader() {
			@Override
			public void set(ImageView imageView, Uri uri, Drawable placeholder) {
				Glide.with(imageView.getContext()).load(uri).placeholder(placeholder).into(imageView);
			}

			@Override
			public void cancel(ImageView imageView) {
				Glide.clear(imageView);
			}
		});
	}

**Comment by NovaViper** [comment]
Oh *facepalm* I got it working now, I just needed to add the DrawerImage Loader

**Comment by mikepenz** [comment]
Great :D

**Comment by NovaViper** [comment]
Thanks for the help!

**Comment by NovaViper** [comment]
Also.. I found out that I had to put .show(); in order to make the toast show up

**Comment by NovaViper** [comment]
Oops! There's one more question I forgot about! Is it possible to have the title in the toolbar display the name of the navigation drawer (or the text that I want it to say based what drawer item is selected)?
