### ISSUE TITLE
Corrupted shadow when app locale is configured RTL

### ISSUE THREAD

**Issue by SupremeProj** [mikepenz/MaterialDrawer#1689]
Hi @mikepenz 
First thanks alot for the awsome material drawer, it rocks!

When configuring my app locale to be RTL, I get the drawer popping out from the right side of the screen which is obviously ok, but when i pull out the drawer i see that the shadow is drawn badly (corrupted if i may)

I use LG G2 4.2.2 API Level 19
(which your app supports, so i guess this issue should not happen)

I will be greatful to have your help on this.

Screen shot:
**You can see that the RTL shadow is slightly shifted to the left.**

![materialdrawer_shadow_issue](https://cloud.githubusercontent.com/assets/24442921/21658893/f9439c72-d2d0-11e6-85cc-34d72c0801a3.jpg)

**Comment by mikepenz** [comment]
@SupremeProj I remember I had this fixed at some point. Are you using the latest version?


https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1582

**Comment by SupremeProj** [comment]
@mikepenz 
I see in the gradle file this:
       versionCode 581
        versionName '5.8.1'
The commit i am using is  - c1eda0b6 Merge branch 'release/v5.8.1'
on master branch ofcourse

**Comment by SupremeProj** [comment]
A bit debugging shows that I enter -into this:
if (ViewCompat.getLayoutDirection(mRootView) == ViewCompat.LAYOUT_DIRECTION_LTR) {
...
}

this explains it. 

Say what should i do then ? how can i configure my view to be LAYOUT_DIRECTION_**RTL**
?

**Comment by mikepenz** [comment]
Can you try: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L57

**Comment by SupremeProj** [comment]
Adding this line you said:
`getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);`
did not work!

But - Adding this line really changed the direction and therefor took the correct shadow:
`ViewCompat.setLayoutDirection(findViewById(android.R.id.content), ViewCompat.LAYOUT_DIRECTION_RTL);`

It's worth remembering this i guess.

**Say, one last question** - related to RTL / LTR
If my locale is RTL - but i still want to force Drawer to be popping from the left as if it was LTR, is there a way / hack you have in mind ? 

appreciate your help

**Comment by mikepenz** [comment]
hmmm you would need to set the whole application to LTR mode I think. opening it from the right is automatically handled by the `DrawerLayout` and from the system.
