### ISSUE TITLE
Move main content to reveal drawer

### ISSUE THREAD

**Issue by aitbaali** [mikepenz/MaterialDrawer#1694]
Thanks for this GREAT LIBRARY.

I want to achieve something like

![awbc_23122016](https://cloud.githubusercontent.com/assets/4213191/21866893/e83238b2-d843-11e6-9ea6-418a034d5134.jpg)

**Comment by mikepenz** [comment]
@aitbaali thank you. 

Your request is not `MaterialDrawer` specific but `DrawerLayout` specific which comes from google. 

Here's a a StackOverflow question which might helps you: http://stackoverflow.com/questions/20057084/how-to-move-main-content-with-drawer-layout-left-side
