### ISSUE TITLE
Cannot load firebase user images from Uri

### ISSUE THREAD

**Issue by boswelja** [mikepenz/MaterialDrawer#1696]
I think the issue here is the account header cant handle a Uri that points to a web address :/

**Comment by mikepenz** [comment]
@boswelja you want to set the background or the image of the profile?

for the image of the profile. please read the readme and add a `DrawerImageLoader` to your project

for the header, just get the `ImageView` (the headerBackground) of the `AccountHeader` and set the image on it

**Comment by boswelja** [comment]
@mikepenz trying it now, I'm trying to load the profile image

**Comment by boswelja** [comment]
@mikepenz It worked  :D
Although, why doesnt just passing the uri intoAccount .withIcon work?

**Comment by mikepenz** [comment]
@boswelja because the `Drawer` does not contain a image loading library. so it does not know what to do with this uri then. As I do not want to force devs into a library, they are able to choose their prefered lib via the `DrawerImageLoader`
