### ISSUE TITLE
Regarding Fix Id's

### ISSUE THREAD

**Issue by connectedhealthcaremy** [mikepenz/MaterialDrawer#1697]
Hi i want to get the fix id's of the sub items but the identifier changes every time i have sub items  with duplicate name so i can not differentiate which subitem belongs to which parent Your  library is very nice thanks for the great work

**Comment by mikepenz** [comment]
@connectedhealthcaremy sorry I am not quite sure. What fix Id's? 

If you fill the drawer during the generation with all items those id's won't change anymore. they will stay the same, they will only change if you set new items in addition

**Comment by connectedhealthcaremy** [comment]
yes the id remains same but after the application pause and i reopen the application the id chnages again. i dont know why it changes when the application pauses

**Comment by connectedhealthcaremy** [comment]
I have different items in the list and some of the items have sub items. Now i want to get information onclicklistener which one is clicked but i cant distinguish based on name because there are enteries with duplicate name. so i try to distuinguished based on id. The id is different but its not same every time so i dont know the proper way to distiguish please help in this thanks a lot

**Comment by mikepenz** [comment]
where do you fill the drawer? in your `onResume`? Perhaps you should make sure it is just filled in `onCreate` or that you define the `identifier` on your own and give unique id's to your items

**Comment by connectedhealthcaremy** [comment]
thank you so much my problem resolved  by giving fix unique identifier at start
