### ISSUE TITLE
DividerDrawerItem is not setting the tag

### ISSUE THREAD

**Issue by derpcoder** [mikepenz/MaterialDrawer#1699]
The default **DividerDrawerItem** is override the **bindView** method but is not calling the "**viewHolder.itemView.setTag(this);**" related to the **5.8.1** update, which causes an error message to be shown in the logcat terminal.

**Comment by mikepenz** [comment]
@derpcoder the `DividerDrawerItem` extends `AbstractDrawerItem` and calls it's super of the `bindView` method which sets the tag:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/AbstractDrawerItem.java#L319

**Comment by derpcoder** [comment]
Nevermind this, for some reason coworker didn't use 5.8.1 but 5.8.0 instead
