### ISSUE TITLE
DrawerToggle is not centered 

### ISSUE THREAD

**Issue by sgueniot** [mikepenz/MaterialDrawer#17]
Hello, thanks for this great lib.
I have noticed that DrawerToggle (and menu) is not centered in the height of the toolbar on some device (here nexus 7 lollipop) or after a rotation. I don't know what happens.
![screenshot_2015-02-16-10-52-08](https://cloud.githubusercontent.com/assets/1597778/6209851/2e9db496-b5ca-11e4-86c2-6c8a89f1aeae.png)

If someone has an idea...
Thanks

**Comment by mikepenz** [comment]
@sgueniot default nexus 7 with newest 5.0.2? and this is the sample app causing issues?

**Comment by mikepenz** [comment]
@sgueniot found the issue, and pushed an update to the source of the sample. should be working now for you ;)

**Comment by Fuhrmann** [comment]
I have the same problem, just saw you updated the sample, thanks!
