### ISSUE TITLE
How to remove drawer from the backstack?

### ISSUE THREAD

**Issue by therealccarter** [mikepenz/MaterialDrawer#1700]
If I'm in an activity and I open the drawer and click a drawer item, I'll go to that new activity. But when I click back, it goes back to the original activity but the drawer is still open. How can I make it so when going back to the original activity, the drawer is in a closed state?

**Comment by mikepenz** [comment]
@therealccarter managing the backstack is up to you and is not related to the drawer. The developer decides what to do after he got the event. 

In addition. the drawer will normally close, only if you disable this or consume the click event it won't close. So make sure that you return false in the click listener
