### ISSUE TITLE
setSystemUIHidden like setFullscreen  ?

### ISSUE THREAD

**Issue by Gounlaf** [mikepenz/MaterialDrawer#1702]
Hi,

Is possible to have a method `setSystemUIHidden` like `setFullscreen`, i.e. available on `Drawer`.
Right now, there is `withSystemUIHidden`, but only available on builder.

Currently, I have an Activity with fragments. I want, in landscape mode, go to an Immersive fullscreen mode, without rebuild a new Drawer.

Maybe there is a way to do it correctly ; but I don't find how (even with FullscreeenDrawerActivity example).

Thanks for your help.

Regards

**Comment by mikepenz** [comment]
@Gounlaf this does not make so much sense. In case if you really need this, I highly recommend to handle the full screen logic on your side.

Fullscreen behaviours are always a bit tricky. 

in general the insets of the drawer are handled by the `fitsSystemWindow`'s flag so it should work (this is nothing library specific)

**Comment by Gounlaf** [comment]
Hi @mikepenz,

Like you suggested, I handled it directly (and  yes, it's ... tricky).
