### ISSUE TITLE
Can I use local drawables for icons?

### ISSUE THREAD

**Issue by santafebound** [mikepenz/MaterialDrawer#1703]
I'm using your NavigationDrawer implemention in the MainActivity of my open-source app: https://github.com/santafebound/yeetclub-android/blob/master/app/src/main/java/com/yeetclub/android/activity/MainActivity.java#L281. When adding DrawerItems, I use icons from FontAwesome, just like you've shown in your sample code:

```java
.addDrawerItems(
                new PrimaryDrawerItem().withName(R.string.drawer_item_profile).withIcon(FontAwesome.Icon.faw_user).withIdentifier(1).withSelectable(false),
                new PrimaryDrawerItem().withName(R.string.drawer_item_create).withIcon(FontAwesome.Icon.faw_paint_brush).withIdentifier(2).withSelectable(false),
                new PrimaryDrawerItem().withName(R.string.drawer_item_yaanich_news).withIcon(FontAwesome.Icon.faw_newspaper_o).withIdentifier(3).withSelectable(false),
                new PrimaryDrawerItem().withName(R.string.drawer_item_my_groups).withIcon(FontAwesome.Icon.faw_users).withIdentifier(4).withSelectable(false),
                new PrimaryDrawerItem().withName(R.string.drawer_item_settings).withIcon(FontAwesome.Icon.faw_cog).withIdentifier(5).withSelectable(false)
                )
```

Is there any way to just use local drawables?

**Comment by mikepenz** [comment]
@santafebound just use the drawable there :D The `withIcon` will take different things

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDrawerItem.java#L56
