### ISSUE TITLE
Any way to disable and enable back?

### ISSUE THREAD

**Issue by khaledkhj** [mikepenz/MaterialDrawer#1704]
Thanks for such a great work.

Is there any way to disable (not to show it at all) the drawer and enable it back according to specific situations?

Thank you.

**Comment by khaledkhj** [comment]
I think I got it

mDrawer.getDrawerLayout().setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);

Or is there any other way?

**Comment by mikepenz** [comment]
No that's the correct solution
