### ISSUE TITLE
cannot update the name of SecondaryDrawerItem in ExpandableDrawerItem

### ISSUE THREAD

**Issue by DavidLiuh** [mikepenz/MaterialDrawer#1705]
hello,

```
new ExpandableDrawerItem().withName("Collapsable").withIcon(GoogleMaterial.Icon.gmd_collection_case_play).withIdentifier(19).withSelectable(false).withSubItems(
                                new SecondaryDrawerItem().withName("CollapsableItem").withLevel(2).withIcon(GoogleMaterial.Icon.gmd_8tracks).withIdentifier(2000),
                                new SecondaryDrawerItem().withName("CollapsableItem 2").withLevel(2).withIcon(GoogleMaterial.Icon.gmd_8tracks).withIdentifier(2001)
                        ),
```

```
 result.updateBadge(4, new StringHolder(11 + ""));
 result.updateName(2000,new StringHolder(11+""));
```

when I want to update the name of SecondaryDrawerItem in ExpandableDrawerItem, it didn't work.
Thanks for your help.

**Comment by mikepenz** [comment]
@DavidLiuh that's a subItem of an expandable item, so updating this wouldn't work the same as it might not be visible at that moment. 

Get the `Adapter` from the `Drawer` and then you can call the notify method for the subitems:
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1679
