### ISSUE TITLE
Change the badge background and text colors when the item is selected

### ISSUE THREAD

**Issue by dafi** [mikepenz/MaterialDrawer#1706]
I need to change the colors for the badge contained inside the selected drawer item but I can't find any way to do it.

My `BadgeStyle` definition is shown below

        final BadgeStyle badgeStyle = new BadgeStyle()
                .withTextColorRes(R.color.drawer_item_counter_text)
                .withColorRes(R.color.drawer_item_counter_bg);

May you give me an hint?

**Comment by mikepenz** [comment]
@dafi just define your own `BadgeStyle()` https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/holder/BadgeStyle.java#L43

and set it to the item. (If you do this after the item was created remember to notify the drawer about the update)

**Comment by zayn1991** [comment]
@mikepenz Your class worked for me, when i did `BadgeStyle extends  BadgeStyle` (DrawerItems wanded BadgeStyle class from library)
