### ISSUE TITLE
How to change the icon size of primary drawer item?

### ISSUE THREAD

**Issue by kalyandechiraju** [mikepenz/MaterialDrawer#1707]
Hi, I am using Font Awesome Iconics with Material Drawer. Some icons look bigger than the others. Is there any way to control the icon size for Navigation Drawer Item?

**Comment by mikepenz** [comment]
@kalyandechiraju you can't as those are defined in the material design guideliens this way. 
If you want other size you should either implement a `CustomDrawerItem` (or you can also overwrite the layout for the primaryDrawerItem)

**Comment by kalyandechiraju** [comment]
If they are as per guidelines, then I wouldn't touch those sizes. It's just that I felt Fontawesome iconics are little bit bigger than GMD iconics (I am using one from each). Anyways, thank you for a quick reply.

**Comment by mikepenz** [comment]
You can also pass vector dawables or other drawables in. or you setup these icons on your own and define `respectFontBounds()` for the `IconicsDrawable` (which would make them smaller though as they will have the padding in)
