### ISSUE TITLE
MaterialDrawer says I don't have specified an ImageLoader implementation

### ISSUE THREAD

**Issue by timoschwarzer** [mikepenz/MaterialDrawer#1708]
Everytime I set a new icon URL to a `ProfileDrawerItem`, the following warning occurs:
```
I/MaterialDrawer: you have not specified a ImageLoader implementation through the DrawerImageLoader.init(IDrawerImageLoader) method
```

Code in my Application's onCreate Method:
```java
DrawerImageLoader.init(new AbstractDrawerImageLoader() {
    @Override
    public void set(ImageView imageView, Uri uri, Drawable placeholder) {
        GlideUrl glideUrl = new GlideUrl(uri.toString(), new LazyHeaders.Builder()
                .addHeader("X-AuthToken", GlideGlobal.Token)
                .build());
        Glide.with(imageView.getContext()).load(glideUrl).placeholder(placeholder).into(imageView);
    }

    @Override
    public void cancel(ImageView imageView) {
        Glide.clear(imageView);
    }

    @Override
    public Drawable placeholder(Context ctx, String tag) {
        return ContextCompat.getDrawable(ctx, R.drawable.account_default);
    }
});
```

Everything **is working fine**, so I think there is an issue in the code where this warning gets printed.

**Comment by mikepenz** [comment]
You have not overwritten the method which also has the `tag` as param. This one prints the message:
https://github.com/mikepenz/MaterialDrawer/blob/fed00a199196efbc63296a081723e603647b5bc4/library/src/main/java/com/mikepenz/materialdrawer/util/AbstractDrawerImageLoader.java#L15

**Comment by timoschwarzer** [comment]
That makes sense!

I've made two PRs that may be useful here:
https://github.com/mikepenz/MaterialDrawer/pull/1709
https://github.com/mikepenz/MaterialDrawer/pull/1710
