### ISSUE TITLE
Setting status bar color overrides visibility of drawer under the status bar

### ISSUE THREAD

**Issue by KDB223** [mikepenz/MaterialDrawer#171]
The drawer (or rather the top portion of it) should be translucently visible under the status bar under every circumstance. 
This is followed the first time its rendered.
![first_render](https://cloud.githubusercontent.com/assets/6078533/6886269/6d8640b0-d654-11e4-8f0d-8edb3e60d5e0.png)
Upon calling `getWindow().setStatusBarColor()`, however, overrides the visibility of the drawer under the status bar and it appears to only "cover" the Toolbar.  
![after_method_call](https://cloud.githubusercontent.com/assets/6078533/6886270/6d91be0e-d654-11e4-8f18-df668f5b21d3.png)
I need to use this method to match the Toolbar color (which is changed depending on the selected option) with the status bar color.

**Comment by mikepenz** [comment]
@KDB223 you should not call getWindow().setStatusBarColor() 

You can change the `setStatusBarColor` via the Drawer.Result object
