### ISSUE TITLE
Can profile icons be square instead of circle?

### ISSUE THREAD

**Issue by virengujariya** [mikepenz/MaterialDrawer#1711]

**Comment by mikepenz** [comment]
@virengujariya you can overwrite the default style which defines the mask used for the `ImageView' s

Have a look here: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/values/styles.xml#L331

**Comment by virengujariya** [comment]
@mikepenz Also is it possible to set profile icon from string/character without using any other lib?

**Comment by mikepenz** [comment]
so you want to have a drawable just with a character?

**Comment by mikepenz** [comment]
@virengujariya you can do this with the `IconicsDrawable` which is already a part of the `MaterialDrawer` 

https://github.com/mikepenz/Android-Iconics/blob/develop/library-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.java#L202

**Comment by virengujariya** [comment]
Yes. I tried setting text drawable icon on ```IProfile``` object but when I switch to that profile it looks like (before and after):

![screenshot_2017-01-24-14-38-12](https://cloud.githubusercontent.com/assets/5392789/22270100/f7caf1b6-e242-11e6-87ca-88093e979b54.png)
![screenshot_2017-01-24-14-38-22](https://cloud.githubusercontent.com/assets/5392789/22270101/f7d9347e-e242-11e6-8486-edb337144699.png)

**Comment by MFlisar** [comment]
Could you provide a setup method for this? Something like

    .withBezelMask(int||drawable)
    .withBezelShadow(boolean)

In the past I often used the place to show a single pseudo profile with my app icon and there I always removed the mask and shadow
