### ISSUE TITLE
Remove account icon shadows

### ISSUE THREAD

**Issue by boswelja** [mikepenz/MaterialDrawer#1712]
In the screenshots, there is an Add/Manage accounts button. I am trying to recreate something similar but cannot find a way to remove the shadow on the account icons

**Comment by mikepenz** [comment]
@boswelja in the header? 

You can overwrite the used style and disable the shadow
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/values/styles.xml#L332
