### ISSUE TITLE
how to change the profile picture?

### ISSUE THREAD

**Issue by HimaAbousalem** [mikepenz/MaterialDrawer#1713]
I'm trying to handle when the user click on the profile picture he can access to gallery and pick picture, but i don't know how to set this picture as profile picture.
thats how i did it, but it didn't work.

    header = new AccountHeaderBuilder()
                .withActivity(this)
                .withSelectionListEnabledForSingleProfile(false)
                .withHeaderBackground(R.drawable.background)
                .addProfiles(profileDrawerItem)
                .withOnAccountHeaderProfileImageListener(new AccountHeader.OnAccountHeaderProfileImageListener() {
                    @Override
                    public boolean onProfileImageClick(View view, IProfile profile, boolean current) {
                        Intent gallaryIntent = new Intent();
                        gallaryIntent.setAction(Intent.ACTION_GET_CONTENT);
                        gallaryIntent.setType("image*//*");
                        startActivityForResult(gallaryIntent,GALLERY_REQUEST);
                        if(imageUri!=null){
                            profile.withIcon(imageUri);
                        }
                        return true;
                    }

                    @Override
                    public boolean onProfileImageLongClick(View view, IProfile profile, boolean current) {
                        return false;
                    }
                })
                .build();
I don't know how to access the profile image view and i didn't understand how to implement the `drawerImageLoader` in my activity

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java

To change adjust the url of the profile, and then notify the `AccountHeader` about the changed item. (similar what you would hvae to do for normal items)
