### ISSUE TITLE
UI Issue when calling drawer.setSelected() shortly after creating the drawer

### ISSUE THREAD

**Issue by timoschwarzer** [mikepenz/MaterialDrawer#1717]
I have created a drawer with a PrimaryDrawerItem.
When I select this Item using `drawer.setSelected(itemIdentifier, false)` the grey selection background doesn't show up. Selecting programmatically works fine if I call `drawer.setSelected(itemIdentifier, false)` after waiting for the selection background's animation's time length. (around 150ms?)

**Comment by mikepenz** [comment]
@timoschwarzer as the background is set by the system (it is a statelistdrawable) this is something I can't change. why don't you directly set the selected item during drawer creation?

**Comment by timoschwarzer** [comment]
@mikepenz I usually select the last selected item when creating the drawer. But I have to switch the selected item (to my settings item) if there are connection problems. And if there is no internet connection, the request will likely fail within a few milliseconds.

I've made a PR that allows one to disable the animation. https://github.com/mikepenz/MaterialDrawer/pull/1718

It's not the best solution, but I'll continue investigating this issue.

**Comment by mikepenz** [comment]
Fixed with v5.8.2
