### ISSUE TITLE
An item in mini drawer and crossfade mini drawer cannot be clicked twice

### ISSUE THREAD

**Issue by Pzy64** [mikepenz/MaterialDrawer#1719]
If an item is pressed once next time  it works only if another item is pressed in between. This problem persist even in the demo app .

**Comment by mikepenz** [comment]
That's the correct behaviour. Why should it do the action again even if it is already selected?

**Comment by Pzy64** [comment]
In my case , I launched an activity on clicking an item. That activity cannot be launched again after getting back

**Comment by mikepenz** [comment]
@Pzy64 if you launch an activity the element should not be selectable in the first place :D 

Add `.withSelectable(false)` to the item

**Comment by Pzy64** [comment]
Thanks it worked . I used to recreate the activity to re-enable the click so far. 
Check this app . It included Crossfader, MaterialDrawer 
https://play.google.com/store/apps/details?id=pzy64.secureremove

also check this link 
http://pzy64.blogspot.com/2017/01/android-creating-mini-drawer-using.html

**Comment by Pzy64** [comment]
Please give your opinion and close the issue

**Comment by mikepenz** [comment]
Thank you for the tutorial 👍
