### ISSUE TITLE
Wiki?

### ISSUE THREAD

**Issue by Technologx** [mikepenz/MaterialDrawer#1720]
Could you or someone else make a wiki on how to actually add this to a app your working on? I'm completely new to this and really have no idea how to add this to my app having the extra activities I'm wanting. I'm lost on this even when I checked your app code I'm lost.

**Comment by mikepenz** [comment]
@Technologx so the README already contains all the information on how you add this to the app. The navigation pattern which you will have in the app like activities or fragments, needs to be chosen by you. The MaterialDrawer comes with the listener which then allows you to start an activity or replace a fragment. 

See the listener here:
https://github.com/mikepenz/MaterialDrawer#add-items-and-adding-some-functionality

There's also the sample app available in this repo. 

There's some russian tutorial: http://java-help.ru/material-navigationdrawer/
And also some others: http://mobikul.com/implementation-mikepenzmaterialdrawer-library-navigation-view/


There are also many github projects which already use the drawer:
http://www.programcreek.com/java-api-examples/index.php?api=com.mikepenz.materialdrawer.Drawer
