### ISSUE TITLE
Can we get the width of the drawer 

### ISSUE THREAD

**Issue by gabrielintang** [mikepenz/MaterialDrawer#1722]
I want to make some overlay(some FrameLayout) on the drawer, but exact as the width of the drawer, I try `drawer.getDrawerLayout().getWidth()` , but I don't think it's the width of the drawer. is there any way to get the width of the opened drawer ? thanks in advance.

**Comment by mikepenz** [comment]
@gabrielintang you do not want the width of the `Drawer` but the width of the slider. 

That's the method I use to get the correct slider width by the way:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/util/DrawerUIUtils.java#L80

**Comment by gabrielintang** [comment]
ooh yes. I figured it out with this piece of code : `drawer.getSlider().getWidth()` thank you. problem solved !
