### ISSUE TITLE
 Feature Request:SetPadding value with DividerDrawerItem

### ISSUE THREAD

**Issue by rachitananda** [mikepenz/MaterialDrawer#1724]
The UI requirement I have is to have dividers for drawer items , but the default DividerDrawerItem padding is more than I need. There is no method to change the padding.

Requirement
<img width="275" alt="screen shot 2017-02-02 at 6 10 04 pm" src="https://cloud.githubusercontent.com/assets/4746204/22549779/0fc5e0f0-e973-11e6-85be-8bb0f050ca5c.png">

Drawer with MaterialDrawer Library
<img width="448" alt="screen shot 2017-02-02 at 6 10 24 pm" src="https://cloud.githubusercontent.com/assets/4746204/22549796/296ee682-e973-11e6-8d5c-2eeab441ebe0.png">

Thank you for the awesome library!

**Comment by mikepenz** [comment]
@rachitananda you can overwrite this layout: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_divider.xml (copy paste it to your app and adjust)

In addition. The items are displayed in an RV, so you can also add a decorator or anything else you need

**Comment by rachitananda** [comment]
Thank you 👍
