### ISSUE TITLE
Sticky header : unable to set background as transparent 

### ISSUE THREAD

**Issue by rachitananda** [mikepenz/MaterialDrawer#1725]
Sticky header : Need to set background as transparent  so that when the drawer scrolls, the header shows the current background , but the default background for sticky header is white any thing lighter than white appears white.

This is not happening with normal header , able to set transparent background

<img width="230" alt="screen shot 2017-02-05 at 6 40 57 pm" src="https://cloud.githubusercontent.com/assets/4746204/22626408/abbf6132-ebd2-11e6-96d0-679e4f7dd6fb.png">

**Comment by mikepenz** [comment]
@rachitananda the sticky header is above the normal recyclerview so the items won't scroll below it. Also you won't have transparent as you have the drawer background color behind. 

The normal header item is a normal item of the rv which is different. 

What are you trying to achieve? You perhaps have to do this manually as it might not be supported

**Comment by rachitananda** [comment]
I'm trying to do this manually, not been able to achieve yet. The Drawer has a background image, as the user scrolls, I need the header to have transparent background so  that the user can see the scrolling background. Thank you

**Comment by mikepenz** [comment]
You have to manually add this layout in the container RecyclerView. which is a `ScrimInsetRelativeLayout` https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_slider.xml

Then you will also have to manually adjust the padding of the recyclerview so it starts below this layout, and add clipToPadding false, so it scrolls below.

**Comment by rachitananda** [comment]
Thank you, I will try this
