### ISSUE TITLE
Ability to have onItemClick and on onArrowClick(to show subItems)?

### ISSUE THREAD

**Issue by khaledkhj** [mikepenz/MaterialDrawer#1728]
I would enable users to click on the item and trigger some event,
with the ability of clicking on the arrow to show subItems if there is any!

Is there any way to do this?

Thanks.

**Comment by mikepenz** [comment]
@khaledkhj you will have to handle this manually, but basically you would use the code of the `ExpandableDrawerItem` create an advanced version for your app, then you set ah `ClickEventHook` (The MaterialDrawer uses the FastAdapter for the items, please have a look on it's documentation) to set the click listener for the arrow. Move the code we have for the whole item into it. 

and keep the normal click handling default

**Comment by ericwa** [comment]
Hi, hope it's OK to ask this here. I was going to try setting up the same thing.

As a starting point, I wanted to set an event hook that would catch clicks on the arrow of a ExpandableDrawerItem. 

I'm getting weird results where my ClickEventHook.onClick only runs intermittently.. if I keep tapping on the arrow, sometimes it runs my onClick and skips the default expanding/contracting (as desired), and sometimes it runs the default click handler instead (expanding/contracting the item).

Does this look like it should work?
```
        FastAdapter<IDrawerItem> adapter = new FastAdapter<>();
        adapter.withEventHook(new ClickEventHook<IDrawerItem>() {
            @Nullable
            @Override
            public View onBind(@NonNull RecyclerView.ViewHolder viewHolder) {
                if (viewHolder instanceof ExpandableDrawerItem.ViewHolder) {
                    return ((ExpandableDrawerItem.ViewHolder) viewHolder).arrow;
                }
                return null;
            }

            @Override
            public void onClick(View v, int position, FastAdapter<IDrawerItem> fastAdapter, IDrawerItem item) {
                Toast.makeText(ViewerActivity.this, "clicked arrow", Toast.LENGTH_SHORT).show();
            }
        });

        new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withAdapter(adapter)
                .addDrawerItems(
                        new SecondaryDrawerItem().withName("item"),
                        new ExpandableDrawerItem().withName("expandable").withSubItems(
                                new SecondaryDrawerItem().withName("x")
                        )
                ).build();
```
this is with `'com.mikepenz:materialdrawer:5.9.4@aar'`.
