### ISSUE TITLE
Wrong SectionDrawerItem bottom padding

### ISSUE THREAD

**Issue by DreadTank27** [mikepenz/MaterialDrawer#1730]
Hello, I've been using your library for some time by now and I wanted to start a new project using it.
The problem is, when I use a SectionDrawerItem there is a very large gap between the divider and the next item.

Here's a screenshoot: http://imgur.com/a/pIKEi

Here's my code:
```java
 int selected = getResources().getColor(R.color.material_drawer_selected_text);
        View header = getLayoutInflater().inflate(R.layout.drawer_header, null);
        PrimaryDrawerItem home = new PrimaryDrawerItem().withName(R.string.drawer_home).withIcon(R.drawable.dr_home).withIdentifier(DASHBOARD).withSelectedIconColor(selected).withIconTintingEnabled(true);
        PrimaryDrawerItem settings = new PrimaryDrawerItem().withName(R.string.settings).withIcon(R.drawable.dr_settings).withIdentifier(SETTINGS).withSelectedIconColor(selected);
        final PrimaryDrawerItem debug = new PrimaryDrawerItem().withName("Debug Tools").withIcon(R.drawable.dr_settings).withIdentifier(DEBUG).withSelectable(false);

        List<IDrawerItem> dItems = new ArrayList<>();
        dItems.add(home);
        dItems.add(new SectionDrawerItem());

         // Here I add some dinamically generated items

        dItems.add(new SectionDrawerItem());
        dItems.add(debug);
        dItems.add(settings);

        drawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withHeader(header)
                .withDrawerItems(dItems)
                .withOnDrawerItemClickListener(this)
                .withOnDrawerListener(this)
                .build();
```

Thanks for your help.
P.S: Sorry for every typo or formatting error, English isn't my native language and it's the first time I ever opened a Issue on GitHub

**Comment by mikepenz** [comment]
@DreadTank27 hmmm it looks like you are modifying some dimensions. Are you overwriting some from the drawer?

**Comment by DreadTank27** [comment]
@mikepenz no, I'm not.
I have checked the Activity, the Layout file, styles.xml and dimens.xml and I haven't set anything about the drawer.
I've also tried adding items via the method addDrawerItems() but the same problem occours.
I'm using MaterialDrawer v. 5.8.1

**Comment by mikepenz** [comment]
@DreadTank27 are you sure your dynamically added items are all correct?

**Comment by DreadTank27** [comment]
@mikepenz I'm sure the problem has nothing to do with the dinamically added items, because it appears even if I make them like `PrimaryDrawerItem home = new PrimaryDrawerItem().withName(R.string.drawer_home).withIcon(R.drawable.dr_home).withIdentifier(1).withSelectedIconColor(selected).withIconTintingEnabled(true);`

But if you want to take a peek at these object, here's the code:
`Resources resources = getResources();
        for (final TipsyItem i : items) {
            final int resourceId = resources.getIdentifier(i.getImageUrl(), "drawable", getPackageName());
            PrimaryDrawerItem dIt = new PrimaryDrawerItem();
            dIt.withName(i.getLocalizedName());
            dIt.withIcon(resources.getDrawable(resourceId));
            dIt.withSelectedIconColor(selected);
            dIt.withIconTintingEnabled(true);
            dIt.withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                @Override
                public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                    String type = i.getField("type");
                    switch (type) {
                        case "list":
                            Fragment list = new RecyclerViewFragment().newInstance(i.getField("category"));
                            loadFragment(list, i.getLocalizedName());
                            break;
                        default:
                            break;
                    }
                    return true;
                }
            });
            dItems.add(dIt);
        }`
The icons are 50x50px and the text is trimmed before using it

**Comment by DreadTank27** [comment]
By the way, I could try overriding those mentioned dimensions.
What are and what are their values?

**Comment by mikepenz** [comment]
Oh stupid me. Finally I see it ^^. 

You are using the `SectionDrawerItem` which is meant to have also some text. If you just want a `divider` then please use the `DividerDrawerItem` 

completely overlooked this

**Comment by DreadTank27** [comment]
Thanks man, I didn't saw it neither!
Keep it up with this library, it's one of the most useful and complete I have ever used!

**Comment by mikepenz** [comment]
@DreadTank27 thanks a lot :)
