### ISSUE TITLE
Incorrect selected position after build() calling

### ISSUE THREAD

**Issue by gromiloff** [mikepenz/MaterialDrawer#1733]
```java
new DrawerBuilder(this)
                .withToolbar(toolbar)
                .addDrawerItems(
                       new PrimaryDrawerItem().withSelected(true)
                )
                .build();
```

So in bindView function the item is deselected, becase in DrawerBuilder->build() all items are deselected and my select is not restore.

**Comment by mikepenz** [comment]
select the item via the `DrawerBuilder` method, not by just flagging the element.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L812

or

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L826

**Comment by gromiloff** [comment]
@mikepenz, thx
but by calling this methods drawer is selected item only. View is not change state.
But after click on item - view state is changed

**Comment by mikepenz** [comment]
@gromiloff what do you mean with view state is not changed. During the building of the drawer, it will pre select this item. 

And If you pass in the savedInstance state it will also take care that this one is preferred vs the one set in the builder.

If you then want to change it even more, you still have the option to do this at a later point via the drawer provided methods too?

**Comment by gromiloff** [comment]
@mikepenz agree what when drawer is building we are not have the view items.
but why logic is different for cases: if item was clicked - it's view would be mark as selected, but on create it's not happaned. this is question about stable logic in different cases with select menu item.

**Comment by mikepenz** [comment]
@gromiloff do you have a custom drawerItem? because in the sample for example. the selected item is highlighted and marked as selected in the drawer (scroll down, it'S the "contact" item)

**Comment by gromiloff** [comment]
.addDrawerItems(
                        new PrimaryDrawerItem().withName("Position A"),
                        new PrimaryDrawerItem().withName("Position B")
                )
Now check on next code with withOnDrawerItemClickListener()

So, By click item bindView after deselec is calling, after select - not calling.
background is change because view state (selected) is changing (by bindViewHelper(viewHolder)).

**Comment by mikepenz** [comment]
@gromiloff if you need the bindView from being called each time you can enable this on the FastAdapter by defining `withSelectWithItemUpdate`

**Comment by gromiloff** [comment]
@mikepenz 

> withSelectWithItemUpdate

in what object ?)

**Comment by mikepenz** [comment]
@gromiloff on the `FastAdapter` 

Drawer.getAdapter() . or something like this

**Comment by gromiloff** [comment]
@mikepenz yes, it's work. Thx!
