### ISSUE TITLE
Question: Is it Possible to call PreferenceFragments when selecting drawers?

### ISSUE THREAD

**Issue by NovaViper** [mikepenz/MaterialDrawer#1735]
I'm wondering if this is possible since I'm trying to create a settings page that appears WITHIN the drawer as a fragment but as a `PreferenceFragment `instead of a normal `Fragment`

**Comment by IvanMazzoli** [comment]
PreferenceManager should extend a normal fragment instance, so it should work

**Comment by mikepenz** [comment]
@NovaViper you can select whatever you want. that's independent of the drawer. The drawer just gives the listener and you can decide which navigation you want to choose then

**Comment by NovaViper** [comment]
Thanks!
