### ISSUE TITLE
import as module

### ISSUE THREAD

**Issue by sefidpardazesh** [mikepenz/MaterialDrawer#1737]
hi mike.
I want to add your library to my Android application as module.
I dont want use :
```
compile('com.mikepenz:materialdrawer:5.8.1@aar') {
    transitive = true
}
```
I want edit some xml files..
how?
error is : Configuration with name 'default' not found.

**Comment by mikepenz** [comment]
@sefidpardazesh the great thing about android's build system is that you just have to put a xml file with the same name into your project, and modify it. It will automatically use the xml which is inside the main project
