### ISSUE TITLE
change color section Drawer

### ISSUE THREAD

**Issue by sefidpardazesh** [mikepenz/MaterialDrawer#1738]
hi mike :)
thanks for great lib.
i want change text color of section drawer item by overriding xml file..
but i dont find that.
can u help me?

**Comment by mikepenz** [comment]
@sefidpardazesh as defined in the Material Design Guidelines the sectionDrawerItem uses the color of the `secondaryText` you can only overwrite this value, but this will also change all the other texts using the secondaryText:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/SectionDrawerItem.java#L120

The only other solution is to create a `CustomDrawerItem`
