### ISSUE TITLE
OverflowMenuDrawerItem items access

### ISSUE THREAD

**Issue by AngleV** [mikepenz/MaterialDrawer#1740]
Hi Mike

I am using an OverflowMenuDrawerItem with some menu items placed.
How can i access each item for further actions like disable hide etc. ?

EDIT
Or even better is it possible somehow to prevent menu from appearing when user taps the overflow dots ? 

Thank you

**Comment by mikepenz** [comment]
@AngleV the `OverflowMenuDrawerItem` does not directly allow you to do this.
So if you have a look at it's implementation:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/OverflowMenuDrawerItem.java#L78

There is no way to prevent the click event from stating the overflow menu. 

reacting to the normal overflow menu clicks is done via this listener:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/OverflowMenuDrawerItem.java#L85

**Comment by AngleV** [comment]
@mikepenz 
Ok i did some modifications to the OverflowMenuDrawerItem bindview method  so that if a condition is false not showing the overflow dots.

```
    @Override
    public void bindView(ViewHolder viewHolder, List payloads) {
        super.bindView(viewHolder, payloads);

        final Context ctx = viewHolder.itemView.getContext();

        //bind the basic view parts
        bindViewHelper(viewHolder);

        //handle menu click
        viewHolder.menu.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                PopupMenu popup = new PopupMenu(view.getContext(), view);
                MenuInflater inflater = popup.getMenuInflater();
                inflater.inflate(mMenu, popup.getMenu());


                popup.setOnMenuItemClickListener(mOnMenuItemClickListener);
                popup.setOnDismissListener(mOnDismissListener);

                popup.show();
            }
        });

        //handle image
        viewHolder.menu.setImageDrawable(new IconicsDrawable(ctx, GoogleMaterial.Icon.gmd_more_vert).sizeDp(12).color(getIconColor(ctx)));
        
        boolean isUserLoggedIn = PreferenceManager.getDefaultSharedPreferences(ctx).getBoolean(Constants.ARG_IS_USER_LOGGED_IN, false);
        if(!isUserLoggedIn) {
            viewHolder.menu.setVisibility(View.INVISIBLE); // do not show the overflow dots
        }
        
        //call the onPostBindView method to trigger post bind view actions (like the listener to modify the item if required)
        onPostBindView(this, viewHolder.itemView);
    }
    
```

It works fine... in case someone else is looking fo something simillar
Thank you
