### ISSUE TITLE
Question ? Adding custom view for subitems in a PrimaryDrawerItem

### ISSUE THREAD

**Issue by mspmax** [mikepenz/MaterialDrawer#1742]
Hi Mike,

Thanks for the awesome library, just a quick question on adding custom views. Is it possible to add a custom view to a Drawer item like ```PrimaryDrawerItem``` ? I have attached a screenshot of my requirement herewith.

<img width="364" alt="screen shot 2017-02-16 at 1 23 04 pm" src="https://cloud.githubusercontent.com/assets/4340194/23004613/9f573d94-f44b-11e6-8cc3-b247b3ea1755.png">

**Comment by mikepenz** [comment]
@mspmax that looks like a `CustomDrawerItem` (https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md)
Just create one with 2 columns, and add a `ClickEventHook` on each column (That comes from the FastAdapter which is used to fill up the Drawer https://github.com/mikepenz/FastAdapter#4-click-listeners-for-views-inside-your-item)

**Comment by mspmax** [comment]
Hi Mike, 

Thanks for the quick response. I'll look into that. One more thing, is it possible to set text size for PrimaryDrawerItems ?

**Comment by mikepenz** [comment]
Not programatically, as the default items follow the material design guideliens. 
You can overwrite the dimension though. Just define the value in your dimens.xml

**Comment by mspmax** [comment]
Hi Mike,

I had a look at your suggestions and came up with a mock up,

```java
public class CustomDrawerItem extends AbstractDrawerItem<CustomDrawerItem, CustomDrawerItem.GridViewHolder> {

    private NavEntry navEntry1;
    private NavEntry navEntry2;

    public CustomDrawerItem(NavEntry navEntry1, NavEntry navEntry2) {
        this.navEntry1 = navEntry1;
        this.navEntry2 = navEntry2;
    }

    @Override
    public int getType() {
        return R.id.drawer_grid_item;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.drawer_grid_item;
    }

    @Override
    public void bindView(GridViewHolder holder, List<Object> payloads) {
        holder.setIsRecyclable(false);
        if (navEntry1 != null) {
            holder.txtCol1.setText(navEntry1.getLabel());
        }
        if (navEntry2 != null) {
            holder.txtCol2.setText(navEntry2.getLabel());
        }
    }

    @Override
    public ViewHolderFactory<GridViewHolder> getFactory() {
        return new ItemFactory();
    }


    public class ItemFactory implements ViewHolderFactory<GridViewHolder> {
        public GridViewHolder create(View v) {
            return new GridViewHolder(v);
        }
    }

    public class GridViewHolder extends RecyclerView.ViewHolder {
        private TextView txtCol1;
        private TextView txtCol2;

        public GridViewHolder(View view) {
            super(view);
            this.txtCol1 = (TextView) view.findViewById(R.id.txtCol1);
            this.txtCol2 = (TextView) view.findViewById(R.id.txtCol2);
        }
    }
}
```
Everything appears fine but I'm not sure about the way I have used bindView() and where should I add the ClickEventHook. Thanks in advance.

**Comment by mikepenz** [comment]
it looks fine. just make sure that you set the text of "textCol2" and "textCol1" to "" if navEntry was null

The `ClickEventHook`s need to be added on the `FastAdapter` 

--> Drawer.getAdapter() or so

**Comment by mspmax** [comment]
Hey Mike,
Everything worked fine and thank you so much for your help :)
