### ISSUE TITLE
Sticky footer can't be shown at minidrawer

### ISSUE THREAD

**Issue by rtokarenko** [mikepenz/MaterialDrawer#1745]
HI!

I'm trying to add sticky footer item this way

`drawer.addStickyFooterItem(
                    new PrimaryDrawerItem().withSelectable(false)
                            .withName("Collapse")
                            .withIcon(R.drawable.arrow_to_left)
            );`

Item isn't shown at minidrawer, only at expanded drawer.
Is there any way to show sticky footer item at minidrawer?

**Comment by mikepenz** [comment]
@rtokarenko there does not exist a `StickyFooter` for the `MiniDrawer`. You may open a PR and add this feature.

**Comment by rtokarenko** [comment]
Ok, got it) May be if I find some time for this)
