### ISSUE TITLE
method result.openDrawer(); wont work

### ISSUE THREAD

**Issue by Andrzej1991** [mikepenz/MaterialDrawer#1749]
Like i say. I use drawer in fragment. I configure it by default information

```
 result = new DrawerBuilder()
                .withActivity(getActivity())
                .withRootView((ViewGroup) view.findViewById(R.id.main_game_relative))
                .withDisplayBelowStatusBar(false)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("hello").withIcon(R.drawable.fx_pro_academy).withIdentifier(1)
                )
                .buildForFragment();


        result.getDrawerLayout().setFitsSystemWindows(false);
        result.getSlider().setFitsSystemWindows(false);`
```

The i create method to open it with ImageView

```
public void openDrawer() {
        openDrawer.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                result.openDrawer();
            }
        });
    }
```
But this not work. I can open drawer by sliding, but i cant open by clicking button. Whats wrong?

**Comment by mikepenz** [comment]
@Andrzej1991 can you please debug what happens? The `MaterialDrawer` just uses the `DrawerLayout`'s built in functionality to open/close:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L132

**Comment by Andrzej1991** [comment]
Hello

Problem is with this line:
`.withRootView((ViewGroup) view.findViewById(R.id.main_game_relative))`

i cant click with my fragment, i delete this and everything work good.

**Comment by mikepenz** [comment]
@Andrzej1991 you mean all clicks do not fire?

**Comment by Andrzej1991** [comment]
With this line is work like i cant use any button etc. Just zero reaction with click. This work like a glass.
I just delete this line and everythink work fine.

**Comment by mikepenz** [comment]
@Andrzej1991 hmmm very interesting. So without the line also the drawer is in place and so on? 

So we can close the issue?

**Comment by Andrzej1991** [comment]
Yes
