### ISSUE TITLE
How can i add edittext to drawer

### ISSUE THREAD

**Issue by sutinerr** [mikepenz/MaterialDrawer#1750]
Hi, help me pls, I need the edittext in drawer, how can I put him there? And how can I set text right of icon of profile, I need like this https://drive.google.com/open?id=0B1i-I5QLchYQbXlBZ0E3dGxSSHM

**Comment by mikepenz** [comment]
@sutinerr you will have to implement your own `CustomDrawerItem` which has a `EditText in it. 
Remember that the drawer's items are displayed in a `RecyclerView` so items may be re-used and recycled

**Comment by sutinerr** [comment]
i must create new xml with edittext, or it can be any layout? just R.i.id.editText? And how can i set text right of icon like in screenshot?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md

**Comment by mikepenz** [comment]
@sutinerr the text is on the right side anyways normally. (If the app is in RTL mode it will be in the opposite way)

**Comment by sutinerr** [comment]
I don't understand where in CustomPrimaryDrawerItem I can say that I need edittext, in your example I can see, how create item, in advance activity, but don't understand how to create edittext

**Comment by mikepenz** [comment]
@sutinerr the sample shows how you can create any item `CustomDrawerItem` using any layout, so also an `EditText`

**Comment by mikepenz** [comment]
Here are a few: https://github.com/mikepenz/MaterialDrawer/tree/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems

Basically a `CustomDrawerItem` can be as simpel as this one: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/DividerDrawerItem.java

provide a layout, define the viewholder, define the bindView logic, set the type (can be the layout id too, just ignore the warning) That's it
