### ISSUE TITLE
New Line for information in Drawer header

### ISSUE THREAD

**Issue by SatanPandeya** [mikepenz/MaterialDrawer#1752]
In header part, there is an option to include: header icon, user profile as: name and email and a lot of nice thing. 

  [1]: https://github.com/mikepenz/MaterialDrawer

For header part, I am using this:

    IProfile userProfile = new ProfileDrawerItem()
             .withName("Company Name" + "\n" + getPreference().getFirstName() 
               + " " + getPreference().getSecondName())
             .withEmail(getPreference().getEmail());

        AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.color.colorAccent)
                .addProfiles(
                        userProfile
                        )
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                        return true;
                    }
                })
                .build();
Comany name and user name both get display in single line. I want first company name, then user name and user email. User name and user email by default work fine.  When I try using `"\n"` or `System.lineSeperator()`, both doesn't work for me. I want company name at the top of user name. So, is there any way to solve this ? 

Now, I am using two profile for: company and username.
        
    IProfile companyProfile = new ProfileDrawerItem().withName("Company Name").withIcon(getResources().getDrawable(R.mipmap.ic_launcher_blue));
    IProfile userProfile = new ProfileDrawerItem()
                .withName(getPreference().getFirstName() + " " + getPreference().getSecondName())
                .withEmail(getPreference().getEmail());

Is there any way to make:Company name then User name?

**Comment by mikepenz** [comment]
@SatanPandeya the header only allows one line for each text. 
If you want to adjust the layout for the header, the best would be for you to simply overwrite the header layout, and modify it to your needs (do not remove views with identifier, or change their view type) 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml
