### ISSUE TITLE
CustomDrawerItem

### ISSUE THREAD

**Issue by aliakbar1997** [mikepenz/MaterialDrawer#1754]
hi, i want to change size of each item text and font, and you told me that i should use CustomDrawerItem, and i don't know how i can do it, may you explain more for me?

**Comment by sefidpardazesh** [comment]
hi.
the great thing about android's build system is that you just have to put a xml file with the same name into your project, and modify it. It will automatically use the xml which is inside the main project

**Comment by aliakbar1997** [comment]
@sefidpardazesh من ایرانیم. شرمنده من متوجه جوابتون نشدم.شما میدونید مشکل من چجوری رفع میشه؟

**Comment by mikepenz** [comment]
@aliakbar1997 as already mentioned in your previous issue, either you just define the dimensions in the xml. 

Or you create a `CustomDrawerItem` with adjustable textsize. 
The sample already showcases a few custom implementations (based on default items) too
