### ISSUE TITLE
Need to add custom arrow in AccountHeader part

### ISSUE THREAD

**Issue by akabirami** [mikepenz/MaterialDrawer#1755]
I need to add a custom arrow at the top of account header and give an action to it. 

Something like the one in the image
<img width="505" alt="screen shot 2017-02-22 at 2 25 47 pm" src="https://cloud.githubusercontent.com/assets/16002837/23204028/ee14078c-f90a-11e6-9b20-6c9a14cfc7e6.png">

**Comment by mikepenz** [comment]
@akabirami by default this is not possible, You can overwrite the used layouts though (copy paste the xml (with the same name) to your project. and add the shown arrow) 
After this you can access the `AccountHeader`'s view and set any listener on it you need. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml
