### ISSUE TITLE
Navigation with miniDrawer

### ISSUE THREAD

**Issue by Yanis007** [mikepenz/MaterialDrawer#1757]
Hi Mike,
Im using miniDrawer.
I have 5 items, each represent a fragment (f1- f5).

I have an issue with the navigation:
I want that the first fragment, f1, will be the base frament, meaning:
 * when pressing on one of the other items (e.g item 2-5), the app will show the corresponding fragment(f2 - f5).
 * when pressing on back button or menu home, the app will alyways go back to item1 -f1.

The problem:
after doing those 2 steps, and pressing again on the same item, the metoed "withOnDrawerItemClickListener" is not fired.

Scenario:
app starts with item1 -f1.
press on item2 - shows f2
press on home - shows f1.
press on item2 - still shows f1. problem.

If i would press on any other items, it would work ok.

Please tell me if you can help me with that issue.
Thanks.

**Comment by mikepenz** [comment]
@Yanis007 you have to make sure that if you click the back button, that the first item is selected (and the lower one deselected) as it will not fire again if it is already selected

**Comment by Yanis007** [comment]
Thank you! working.
miniDrawer.getAdapter().select(0, true);
