### ISSUE TITLE
TransparentStatus bar problem

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/MaterialDrawer#1758]
Hi @mikepenz, I'm using GoogleMaps in my activity with a transparent status bar and everything is ok. It works as it should. The problem is that when I use the MaterialDrawer, the status bar is  completely grey...
How can I have a transparent status bar with a map behind it like Google Maps app does and at the same time use your MaterialDrawer without any conflict?

**Comment by mikepenz** [comment]
@EpsilonOrionis this are always a bit tricky things :D especially as it comes back to the "fitsSystemWindows" flag :D 

If you have a small demo I can try and debug and test around it would speed up to find a solution :D

**Comment by EpsilonOrionis** [comment]
It's very simple. When I use the drawer, only the drawer is fullscreen. The drawer blocks the layout under the status bar.

**This is without the drawer**
![screenshot_2017-02-23-12-36-04](https://cloud.githubusercontent.com/assets/7190255/23257600/de45fdbe-f9c4-11e6-9a2f-cd507d9cd992.png)

**This is with the drawer**
![screenshot_2017-02-23-12-34-55](https://cloud.githubusercontent.com/assets/7190255/23257627/f847190a-f9c4-11e6-9b16-b718c1bfd9ca.png)

**Comment by mikepenz** [comment]
@EpsilonOrionis I mean a tiny sample app so I directly can alter the code and tell you what was necessary to fix it

**Comment by EpsilonOrionis** [comment]
I don't know if it is necessary. Just an app with an activity that contains a map and the translucent status bar. Create a MaterialDrawer and see what happens. Nothing special the activity is clean i think it's useless to provide you a tiny sample

**Comment by EpsilonOrionis** [comment]
Ok, I'll provide you a sample app 👍

**Comment by mikepenz** [comment]
@EpsilonOrionis thank you so much. it really helps me, as I can focus on solving the issue rather than first reproducing :)

**Comment by EpsilonOrionis** [comment]
I created the sample app, can I pass you only:
AndroidManifest.xml
styles.xml
MainActivity.java?

This will avoid to upload 6000 files

**Comment by mikepenz** [comment]
@EpsilonOrionis remove the build folders, the dist folders, the gradlew folder then it should be down already by a huge amount, zip it :)
You can send it also as e-mail if you prefer

**Comment by EpsilonOrionis** [comment]
mikepenz@gmail.com?

**Comment by mikepenz** [comment]
exactly

**Comment by EpsilonOrionis** [comment]
Done

**Comment by mikepenz** [comment]
I didn't get it yet

**Comment by EpsilonOrionis** [comment]
Google told me that for security reasons I can't send executables and archives

**Comment by mikepenz** [comment]
oh :D please upload it simply to google drive and sent a link or so :)

**Comment by EpsilonOrionis** [comment]
https://drive.google.com/open?id=0B15c_FuAzxI0emFTQ0tjcnBET0U

**Comment by mikepenz** [comment]
Thank you I'll check it out

**Comment by mikepenz** [comment]
Ok. So the following will remove that bar: ` .withDrawerLayout(R.layout.material_drawer_fits_not)`

```
Drawer result = new DrawerBuilder()
                .withActivity(this)
                .addDrawerItems(
                        item1,
                        //item2,
                        //item3,
                        item4,

                        about
                )
                .withSelectedItem(-1)
                .withDelayOnDrawerClose(250)
                .withActionBarDrawerToggleAnimated(true)
                .withDrawerLayout(R.layout.material_drawer_fits_not)
                .build();
```

**Comment by EpsilonOrionis** [comment]
Ok @mikepenz , it works but the status bar gets transparent, i just want to make it translucent

**Comment by mikepenz** [comment]
That's system behaviour. comes from your set flag, as far as I can tell. You might can put a custom `ScrimInsetsFrameLayout` inbetween and tint the statusbar, but it is not very clean in my opinion

**Comment by EpsilonOrionis** [comment]
Is there a way to change the status bar color?

**Comment by mikepenz** [comment]
What do you mean. That's basically provided by the system. I assume via the `primaryColor` or so. It is not set by the `MaterialDrawer` as far as I remember

**Comment by EpsilonOrionis** [comment]
@mikepenz this is a problem that you have to solve

**Comment by EpsilonOrionis** [comment]
Maybe I used thw wrong word "transparent". I want the status bar, but not completely transparent. Just the opacity as shown in the screenshot above. I understood that the MaterialDrawer forces the layout to be under the status bar even if it has the opacity. So the way to fix this issue is to tell the MaterialDrawer to stop to do what it is doing or to find a way to tell the layout to be under the status bar. I tried fitSystemWindows but I don't know if I used it in the right way. Please we have to find a solution to this. Thank you :)

**Comment by EpsilonOrionis** [comment]
@mikepenz can we found a solution together?

**Comment by mikepenz** [comment]
@EpsilonOrionis yes we will find a solution, I am currently ill so very limited available.

**Comment by mikepenz** [comment]
@EpsilonOrionis sorry that it took me a bit longer though to my illness to provide you a 100% solution. 

So I have a proper solution for you. 

Basically what I did:
- Remove the `Fullscreen` flags in the `MainActivity`
- Change the `DrawerBuilter` and use the default `DrawerLayout` again: `new DrawerBuilder().withActivity(this).addDrawerItems(...).build();`
- use a `ScrimInsetsRelativeLayout` (or whatever ScrimInsets*` layout you prefer)  in your `activity_main.xml` instead of the `RelativeLayout` --> `com.mikepenz.materialize.view.ScrimInsetsRelativeLayout` (materialize already provides one ;)
- add `android:fitsSystemWindows="true"` to it
- That's it ;)

https://drive.google.com/open?id=0B4Y8HN2BnSjpZ2FwUmc5XzA3YTQ

**Comment by EpsilonOrionis** [comment]
Thank you very much @mikepenz it works! I hope you get well soon 👍
