### ISSUE TITLE
Change HeaderProfile name and email TextColour and TextBackgroundColour

### ISSUE THREAD

**Issue by night-cypher** [mikepenz/MaterialDrawer#1759]
Hi, is it possible to change header profile name and email **text colour and text background colour** with just a few line of code? I am now searching for solution to change the text colour and text background colour. Thanks

**Comment by mikepenz** [comment]
@night-cypher the easiest solution (if you want to go against the google material design guidelines) is the following:
https://github.com/mikepenz/MaterialDrawer/issues/1755#issuecomment-282019106 

basically overwriting the xml used with a modified one from you
