### ISSUE TITLE
change hamburg icon color

### ISSUE THREAD

**Issue by AlexMercier** [mikepenz/MaterialDrawer#176]
Hello, please help me how i can change Drawer indicator hamburg icon color to white?

**Comment by mikepenz** [comment]
@AlexMercier the ActionBarDrawerToggle color is defined by the theme. so if you need it white you should use a dark theme or the DarkToolbar theme. (you should use one of the MaterialDrawerTheme)

if it should be black you have to use the light theme. 

else you have to set your own DrawerArrowStyle

in your theme:
```xml
<item name="drawerArrowStyle">@style/MaterialDrawer.DrawerArrowStyle</item>
```


```xml
<style name="MaterialDrawer.DrawerArrowStyle" parent="Widget.AppCompat.DrawerArrowToggle">
        <item name="spinBars">false</item>
        <item name="color">@android:color/white</item>
</style>
```

**Comment by AlexMercier** [comment]
Oh, thank you. The MaterialDrawerTheme.Light.DarkToolbar thats what i need.

**Comment by mikepenz** [comment]
@AlexMercier great ;)

**Comment by ajinkyapote1** [comment]
I have used the above code but unable to see the desired color to the hamburger icon. My theme is Theme.AppCompat.Light.NoActionBar

Please Help.
