### ISSUE TITLE
How can I put the drawer toggle button on the right of the tool bar?

### ISSUE THREAD

**Issue by OsamaDroidEgypt** [mikepenz/MaterialDrawer#1761]
Can i put the drawer toggle button on the right of the tool bar using this library?!

**Comment by mikepenz** [comment]
@OsamaDroidEgypt the `MaterialDrawer` does not do anything with the toggle. That's all basic Android stuff. 

If you have an RTL application it will automatically switch if the app is in RTL mode + the app is API 17+
