### ISSUE TITLE
right to left open

### ISSUE THREAD

**Issue by hra1368** [mikepenz/MaterialDrawer#1765]
it is possible drawer open from right?

**Comment by mikepenz** [comment]
@hra1368 if your application is in RTL mode that happens automatically, if not and you don't want RTL mode, just set the gravity for the drawer

**Comment by hra1368** [comment]
RTL mode don't applicable in CrossfadeDrawerLayoutActvitiy .please propose solution for Crossfade Drawer?

**Comment by mikepenz** [comment]
it should work the same for the `CrossfadeDrawerLayout` if your application is in real RTL mode (and API 17+) it will work

**Comment by behiunforgiven** [comment]
I use "android:layoutDirection="rtl"" in my activity but drawer opens from left!
How can I set my application in RTL mode?

Can you provide an example?

**Comment by mikepenz** [comment]
That's not library related. There are enough resources out there showing how this is done
