### ISSUE TITLE
Hide the PrimaryDrawerItem Icon

### ISSUE THREAD

**Issue by akabirami** [mikepenz/MaterialDrawer#1767]
Hi, I need to add icons for few drawer items and for the remaining only the layout space must be occupied. For eg: 
<img width="190" alt="screen shot 2017-03-01 at 1 42 14 pm" src="https://cloud.githubusercontent.com/assets/16002837/23451214/f960aa30-fe84-11e6-8088-99e78ae3fc48.png">

Is there any way to make icon invisible ?

And also how to stop highlight any drawer item even on click ?

**Comment by mikepenz** [comment]
@akabirami just set no icon? Or an empty transparent icon?

That's shown in the sample :D just define the item `withSelectable(false)` and for set the default selection to `-1`

**Comment by akabirami** [comment]
Thanks !
If no icon is set, The title moves to the Left. I need it aligned. Something like hiding the visibility

**Comment by mikepenz** [comment]
`new ColorDrawable(Color.TRANSPARENT)` or so?
