### ISSUE TITLE
GoogleApiClient isConnected turns to false on withOnDrawerItemClickListener

### ISSUE THREAD

**Issue by chrisjeon** [mikepenz/MaterialDrawer#1769]
Hi,

I'm trying to implement a signout button with one of the `ProfileSettingDrawerItem`.

Let's say that I have a singleton variable called `mGoogleApiClient` that returns `true` when I call `isConnected()` on it.

```java
mGoogleApiClient.isConnected(); // this returns true;
```

However, this happens

```java

mGoogleApiClient.isConnected(); // This returns true;
accountHeaderBuilder.addProfiles(
                new ProfileSettingDrawerItem()
                        .withName("Change Accounts")
                        .withDescription("Change Accounts")
                        .withIcon(GoogleMaterial.Icon.gmd_swap)
                        .withIdentifier(PROFILE_LOGOUT)
                        .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                            @Override
                            public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                                mGoogleApiClient.isConnected(); // This returns false
                                return false;
                            }
                        })
        );
```

How come in that onItemClick, the `mGoogleApiClient.isConnected()` magically returns `false` instead of `true`? Due to this, I can't sign the users out. I've been Googling for this for awhile and I can't figure it out. Any help? Thanks!

**Comment by mikepenz** [comment]
@chrisjeon even if it may seems it has something to do with the click listener. I am sure it does not. The MaterialDrawer does not interact with any 3rd party library in any way. 

It may be related to the time when the click happens.

**Comment by chrisjeon** [comment]
@mikepenz thanks for the prompt reply. Do you know if anyone else had this problem? I'm trying to implement sign out, and this issue is making it impossible.

**Comment by mikepenz** [comment]
As mentioned. This is unrelated to the MaterialDrawer. So you would not find help here. 

Somehting else in your code makes it disconnect. But it is definitely unrelated to this lib
