### ISSUE TITLE
com.mikepenz.materialdrawer.d.ts is not a module

### ISSUE THREAD

**Issue by peer-ligthart** [mikepenz/MaterialDrawer#1770]
Hi,

I've been trying to use nativescript-sidedrawer by [Gethuman](https://github.com/gethuman/nativescript-sidedrawer/).

I'm using NativeScript in combination with Angular 2. Now when I try to build my application I receive the error started in the title.

> com.mikepenz.materialdrawer.d.ts is not a module

Not sure if this is the right place to send in this issue, maybe you know a solution.

**Comment by mikepenz** [comment]
@peer-ligthart sorry I can not give support for `NativeScript` as this library was only tested with the original Android Build tools + Environment. 

I just had a look on what you are using. I think the correct place to report this is here: https://github.com/gethuman/nativescript-sidedrawer

The error sounds like some nativescript thing is not resolved. @gethuman perhaps you can help here?

**Comment by roblav96** [comment]
@mikepenz Apologies this issue was created :X

Your library here works phenomenal =] Thank you for the work you've done!

This error is something on my end not too worry.
