### ISSUE TITLE
Hamburger is not working

### ISSUE THREAD

**Issue by AhmedBadrSayed** [mikepenz/MaterialDrawer#1771]
Hi @mikepenz i
When I implement material drawer it shows hamburger icon in the action bar but when i click on it it do nothing, drawer just opens when i slide the screen from the left side

**Comment by mikepenz** [comment]
@AhmedBadrSayed have you followed the instructions? Do you pass the `Toolbar`?

**Comment by AhmedBadrSayed** [comment]
result = new DrawerBuilder()
                    .withActivity(this)
                    .withToolbar(toolbar)
                    .withTranslucentStatusBar(false)
                    .withActionBarDrawerToggle(true)
                    .withSavedInstance(savedInstanceState)
                    .withDisplayBelowStatusBar(false)
                    .withAccountHeader(headerResult)
                    .addDrawerItems(
                            item1,
                            new DividerDrawerItem(),
                            item2
                    )
                    .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                        @Override
                        public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                            // do something with the clicked item :D
                            Toast.makeText(Main.this, ((Nameable) drawerItem).getName().getText(Main.this), Toast.LENGTH_SHORT).show();
                            return true;
                        }
                    })
                    .build();
        }

**Comment by mikepenz** [comment]
@AhmedBadrSayed and your `Toolbar` is `!= null`?

**Comment by mikepenz** [comment]
Please report back. Closing the issue for now

**Comment by AhmedBadrSayed** [comment]
Hi @mikepenz 

Sorry for not replying, I have solved the issue i think the reason was that the toolbar was null as you said
