### ISSUE TITLE
How to load menu item base on user menu?

### ISSUE THREAD

**Issue by anton-khansa** [mikepenz/MaterialDrawer#1772]
hi mike,
i have case that i want to make list item menu change base on the user login, user A have menu 1,menu 2,menu 3 and if user B login he has only menu 1,menu 4

how can we loop the user menu to put in .addDrawerItems() function? i have try load the user menu in my_array and when i call .addDrawerItems(my_array) its wrong type. is this possible?

**Comment by mikepenz** [comment]
@anton-khansa if the user changes you will probably replace the current items with the new items. So you should use this method:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L968

Make sure you do this in the main thread, as `RecyclerView`s do weird stuff if their `notify` methods are called on a non UI thread
