### ISSUE TITLE
Question about returning from Intent Switched Via MaterialDrawer

### ISSUE THREAD

**Issue by Sparker0i** [mikepenz/MaterialDrawer#1773]
My Material Drawer has 2 secondary items - Home and Settings.  Default item is Home as intended.

But when I click the 2nd item - Settings, it loads up a new Activity (as intended) and selects the Settings Item in the Drawer, but when I switch back to the previous activity, the Settings Item remains selected in the Drawer, and not Home, the one from which I selected Settings via Drawer.

How do I tackle this?

Here's my drawer Code : 

        new DrawerBuilder()
                .withActivity(this)
                .withToolbar(getToolbar())
                .withSelectedItem(1)
                .withActionBarDrawerToggleAnimated(true)
                .addDrawerItems(
                        item1,
                        new DividerDrawerItem(),
                        item4
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        // do something with the clicked item :D
                        if (drawerItem != null) {
                            Intent intent = null;
                            if (drawerItem.getIdentifier() == 4) {
                                intent = new Intent(WeatherActivity.this, AboutActivity.class);
                            }
                            if (intent != null) {
                                startActivity(intent);
                            }
                        }
                        return false;
                    }
                })
                .build();
        }

where item1 and item4 are described as

        SecondaryDrawerItem item1 = new SecondaryDrawerItem().withIdentifier(1)
                .withName(R.string.drawer_item_home)
                .withIcon(new IconicsDrawable(this)
                .icon(GoogleMaterial.Icon.gmd_home);

        SecondaryDrawerItem item4 = new SecondaryDrawerItem().withIdentifier(4)
                .withName(R.string.drawer_item_settings)
                .withIcon(new IconicsDrawable(this)
                .icon(GoogleMaterial.Icon.gmd_settings);

**Comment by mikepenz** [comment]
@Sparker0i  please see the `withSelectable(false)` option (as shown in the sample) on the `DrawerItem`
