### ISSUE TITLE
change toolbar manually

### ISSUE THREAD

**Issue by aliakbar1997** [mikepenz/MaterialDrawer#1776]
how to change toolbar manually, for example i want to add search item in toolbar like telegram and remove navigation icon after click on the search icon?

**Comment by mikepenz** [comment]
@aliakbar1997 the `MaterialDrawer` does not do anything with the toolbar at all. It will just set the `ActionBarDrawerToggle` for you if you provide the `Toolbar` via the builder (that's the only thing) 

Everything is up to you, and independent of this library.
