### ISSUE TITLE
'ExpandableBadgeDrawerItem' arrow color - AND - API<=19 crash

### ISSUE THREAD

**Issue by RafaHDu** [mikepenz/MaterialDrawer#1782]
I have tried to search for this 2 issues but i couldn't find an answer, so i hope that im not asking something already answer :s  

In the '**ExpandableBadgeDrawerItem**' the little arrow forward to the text, how do i change the color? Because, the default one comes in black and my text is white so i want to put it white to but i can't find a solution for that.

![13c07dc754e8422ca5c51ff289cdfc4c](https://cloud.githubusercontent.com/assets/18510023/23926326/75dcbe24-090b-11e7-81af-0bd431c8567f.png)

The other issue is when i run the app in a **API <= 19**, the app crashes and i have tried run without the Drawer and run without problems... So is there something that we need to do for API <= 19 ?

Thank's mikepenz for this awesome lib!

**Comment by mikepenz** [comment]
@RafaHDu do you pass a `Vector` ressource as icon for any item? Or what's the crash `Stacktrace`? 

The `Arrow`s color can be changed `withArrowColor` on the `ExpandableDrawerItem`

**Comment by RafaHDu** [comment]
I already changed the arrow color and yes i was using vector image, i was passing the icon throw the '**Vector Asset**' from android studio feature, so i changed to '**Image Asset**' and now its working!

Thanks mikepenz!
