### ISSUE TITLE
Possible to set item typeface?

### ISSUE THREAD

**Issue by jpack1337** [mikepenz/MaterialDrawer#1783]
I've been trying to update the font of the navigation bar to Roboto but haven't found anything. Is it possible currently?

**Comment by mikepenz** [comment]
@jpack1337 the `Toolbar` has nothing to do with the `MaterialDrawer`

**Comment by jpack1337** [comment]
Correction, is it possible to change the default font of the MaterialDrawer?

**Comment by mikepenz** [comment]
@jpack1337 no there is no method to set a different typeface for the whole drawer at once. 
You might want to use a different lib like Calligraphy for something like this
