### ISSUE TITLE
Update support libraries to 25.3.0

### ISSUE THREAD

**Issue by auchri** [mikepenz/MaterialDrawer#1784]
My app doesn't build, because

> All com.android.support libraries must use the exact same version specification

and I have to use the newer versions

**Comment by mikepenz** [comment]
@auchri you can exclude the support libs from gradle dependencies

http://stackoverflow.com/a/21765656/325479

**Comment by auchri** [comment]
@mikepenz waht's the reason to not update the libs?

**Comment by mikepenz** [comment]
I'll but until the update is out it will take a while. And the above will allow you to use any support lib version in your app until then.
