### ISSUE TITLE
ExpandableDrawerItem() not showing in Mini Drawer

### ISSUE THREAD

**Issue by chanonly123** [mikepenz/MaterialDrawer#1786]
Alternativelty PrimaryDrawerItem().withIsExpanded(true) does not have expand/collapse indicator arrow.

**Comment by mikepenz** [comment]
@chanonly123 yes expandable items do not exist (won't show up) in the `MiniDrawer` and there are currently no plan to do so.

**Comment by chanonly123** [comment]
how to open mini drawer programmatically?

**Comment by mikepenz** [comment]
Do you use the `Crossfader` or `CrossfadeDrawerLayout`?

For the `Crossfader` there is the `crossFade()` method

for the `CrossfadeDrawerLayout` it's called `crossfade()`
