### ISSUE TITLE
How to get profile Icon Bitmap?

### ISSUE THREAD

**Issue by night-cypher** [mikepenz/MaterialDrawer#1787]
Hi, is there a way to get profile icon bitmap?

**Comment by night-cypher** [comment]
I am getting null pointer exception 
Bitmap bitmap =profile.getIcon().getBitmap();

**Comment by mikepenz** [comment]
@night-cypher only if you set it as `Bitmap`. Otherwise the image loader will set it and that's it you can't access it

**Comment by night-cypher** [comment]
Sorry, I cant understand it. So how i get the bitmap?

**Comment by mikepenz** [comment]
You can't. Why would the drawer provide you the bitmap. ?! You can set a bitmap (and if you set it before you can theoretically get it again)

**Comment by night-cypher** [comment]
How can i set the bitmap?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L65

**Comment by night-cypher** [comment]
Yup.... i am already set the icon with http url. But i cant get the bitmap. 
profileDrawerItem = new ProfileDrawerItem().withTextColor(getResources().getColor(R.color.accent)).withName(user.getName()).withEmail(user.getEmail())
          .withIcon("http://abc.com/image.png");

**Comment by mikepenz** [comment]
You are not supposed to get the bitmap. you set the url. the provided image loader (if you read the README) will then download and set the image. 

if you need to display the image somewhere else. use your image loading library to get it there too (it should cache it anyways)

**Comment by night-cypher** [comment]
Ok thanks
