### ISSUE TITLE
want horizontal footer with divider 

### ISSUE THREAD

**Issue by Pareshoct7** [mikepenz/MaterialDrawer#1789]
![drawer mark](https://cloud.githubusercontent.com/assets/10085177/24033952/4debc7c8-0b15-11e7-8f18-d513776dc6af.jpg)

i want drawer sticky footer item like this red mark.So, how can i achieve this footer or what code i have to write. please help me

**Comment by mikepenz** [comment]
@Pareshoct7 I'd recommend a `CustomDrawerItem` which just has those 3 buttons in.
