### ISSUE TITLE
Drawer displayed under ActionBar

### ISSUE THREAD

**Issue by sonovice** [mikepenz/MaterialDrawer#179]
Hello Mike and sorry for again stealing your time, but I can't solve the following problem:
![screenshot](https://cloud.githubusercontent.com/assets/8217108/6951567/8bf7d008-d8bc-11e4-9335-139509043400.jpg)

There are actually 3 mistakes. The first one is obvious. And then there are white lines on the left and right side of the drawer and now ActionBarDrawerToggle. Do you have any idea what I might do wrong?
This is the relevant Code:
```java
public class MainActivity extends ActionBarActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Drawer.Result result = new Drawer()
                .withActivity(this)
                .withActionBarDrawerToggle(true)
                .withTranslucentStatusBar(true)
                .withHeader(R.layout.header)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("Foo"),
                        new DividerDrawerItem(),
                        new SecondaryDrawerItem().withName("Bar")
                )
                .build();
        [...]
    }
}
```

This might also be important:
```xml
<style name="AppTheme" parent="MaterialDrawerTheme.Light.DarkToolbar.ActionBar.TranslucentStatus">
    <item name="colorPrimary">@color/material_drawer_primary</item>
    <item name="colorPrimaryDark">@color/material_drawer_primary_dark</item>
    <item name="colorAccent">@color/material_drawer_accent</item>
</style>
```

**Comment by mikepenz** [comment]
@sonovice you don't use a toolbar right? there is no option to draw the drawer on top of a normal old school ActionBar. please use .withActionBarCompatiblity (or something like this :D)

**Comment by sonovice** [comment]
@mikepenz Ok thanks, I've worked around it using the Toolbar from AppCompat v7. But I still have the white lines on both sides.

**Comment by mikepenz** [comment]
@sonovice using the Toolbar is no workaround :P it should be used :D

Never have seen those Oo any custom styles or any custom layouts? 

What phone are you using?

**Comment by sonovice** [comment]
@mikepenz Not as far as I can see. Everything is pretty basic.

I am using a Samsung Galaxy Note Pro 12.2 running with cm12.

**Comment by mikepenz** [comment]
Hmmm so it's either an issue with cm12. or the samsung galaxy note. 

I can't see this in any of my apps or on any of my emulators or anywhere else. 

can you try it on a different device too?

**Comment by sonovice** [comment]
@mikepenz Strange, no errors on my phone. But your sample APK looks good on my tablet... Any idea how I could start debugging?

**Comment by mikepenz** [comment]
any custom dpi applied? i assume it's caused by cm12 but can't prove that one. 
but on the other side the sample app is working on your tablet .

no not really because it seems that this issue is not caused by code :/

**Comment by sonovice** [comment]
@mikepenz My phone also has cm12 installed. Hmm.... the lines are exactly 1px in width.

I will take a look at your sample tomorrow and try to recreate the problem with a new app. Please don't close this issue, I'll try to solve this mistery. ;)

**Comment by mikepenz** [comment]
@sonovice no problem :D normally i close issues if they are not really specific to the drawer. there can still be discussion within the ticket :D

**Comment by sonovice** [comment]
@mikepenz I managed to track down the problem to the line saying `.withHeader(R.layout.header)`. Without this everything looks fine. Still don't know how this happens, the used layout and image is copied from the sample apk.

**Comment by mikepenz** [comment]
@sonovice really interesting. the header is a normal listViewItem so yeah :D i would understand it if it happens with a sticky header but not with the normal one :D
