### ISSUE TITLE
How do I select the title from the list menu to become bold?

### ISSUE THREAD

**Issue by levisaturnino** [mikepenz/MaterialDrawer#1790]
How do I leave my textview in bold when selecting the menu and the other without bold in my navigation drawer ?. Whereas in the material design guide you have a template selected in bold.

**Comment by mikepenz** [comment]
@levisaturnino if you need a custom behaviour, you can achieve this by implementing your own CustomDrawerItem, which does exactly what you need. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md
