### ISSUE TITLE
Snackbar behind keyboard when MaterialDrawer is used.

### ISSUE THREAD

**Issue by crm76** [mikepenz/MaterialDrawer#1791]
When I utilize MaterialDrawer, the Snackbar will no longer align to the top of the keyboard.

**Example Layout:**

```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/uxLayout">

    <EditText
        android:id="@+id/editText"
        android:layout_width="384dp"
        android:layout_height="wrap_content"
        android:ems="10"
        android:inputType="textPersonName"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        tools:layout_constraintLeft_creator="1"
        tools:layout_constraintTop_creator="1" />

</android.support.constraint.ConstraintLayout>
```

**In the Activity:**

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_example);

        //new DrawerBuilder(this).build();

        View view = findViewById(R.id.uxLayout);
        Snackbar.make(view, "Snack time!", Snackbar.LENGTH_INDEFINITE).show();
    }

**In the manifest, in the activity node:**

android:windowSoftInputMode="adjustResize"

If you run this, you'll see the Snackbar above the keyboard. If you un-comment "//new DrawerBuilder(this).build();", the Snackbar will be behind the keyboard.

**Comment by mikepenz** [comment]
@crm76  did you already try something, I suggested via e-mail?

**Comment by mikepenz** [comment]
Close for now as nothing was reported back
