### ISSUE TITLE
How to set a custom view as head view in Drawer

### ISSUE THREAD

**Issue by lizhengxian1991** [mikepenz/MaterialDrawer#1792]
I tried "new DrawerBuilder().withHeader(view)"，but it not worked. So, can I set a custom view as head view when I won't use AccountHeader? I just found the function "withCustomView"，but I only want to set the head, not all the drawer view.

**Comment by mikepenz** [comment]
@lizhengxian1991 what do you mean with `withHeader()` does not work?

The `MultiDrawerActivity` sample uses a custom header: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MultiDrawerActivity.java#L43 and it works as you can see in the sample app

**Comment by lizhengxian1991** [comment]
I see，it's useful for me，thanks! By the way, the drawer in the class MultiDrawerActivity didn't bind the toolbar, so it can't be show when I click the left-top button.
![image](https://cloud.githubusercontent.com/assets/5888937/24178576/e9638f6a-0ee4-11e7-811f-cb246f0449ca.png)

**Comment by mikepenz** [comment]
@lizhengxian1991 I know. I chose it to behave like this, as the sample is just there to showcase some different configurations of the drawer.

Still thanks for pointing out.
