### ISSUE TITLE
Scrolling with a vertical line is hard or right hand is hard

### ISSUE THREAD

**Issue by larkKent** [mikepenz/MaterialDrawer#1793]
When going down/up a nearly vertical line (which ends a tiny bit more to the right)
or a eliptical line from bottom to top over the left (kind of a normal movement with right hand),
or sliding from right bottom/top corner to the opposite end of the screen

 it can be 

that the drawer doesn't scroll, because it's already sliding.

I feel this could be fixed with a threshold or a smarter movement evaluation (ie. if the vertical component far outweighs the horizontal one then stop sliding), but I haven't looked to much into the code and don't know whether this is inherent to android drawers.

**Comment by mikepenz** [comment]
@larkKent sorry this can't be fixed by the library. it's default behavior of Google's provided `DrawerLayout`
