### ISSUE TITLE
Open Navigation Drawer,

### ISSUE THREAD

**Issue by alok96** [mikepenz/MaterialDrawer#1794]
Hello Mike, when we open navigation drawer, rest of the screen become dark, 
please guide me to keep the rest of the screen as the same color.

thank you
alok

**Comment by mikepenz** [comment]
@alok96 you mean the scrim color? 
get the `DrawerLayout` from the `Drawer` and set the `Scrim-Color` to transparent. 
(This is against the guidelines though, and touching outside will still close the drawer) 

--> That's `DrawerLayout` functionality and not related to this library by the way
