### ISSUE TITLE
Removing Drawer

### ISSUE THREAD

**Issue by carmas123** [mikepenz/MaterialDrawer#1795]
Refer to: https://github.com/mikepenz/MaterialDrawer/issues/840

I want ask you how I can delete completelly the Drawer and not only that items.

**Comment by mikepenz** [comment]
@carmas123 so you have created the drawer for an activity and then you want to remove it? 
You can either remove the `DrawerLayout` from your view hierachy (manually) 
or you lock the Slider of the drawer, or you remove the Slider of the drawer from the view hierachy. 

But that are cases which is specific to your project, and no convenient methods are available in the drawer for this.

**Comment by carmas123** [comment]
I need a specific drawer for each fragment opened. To do that I create the drawer from a fragment when it is need. Now when I go to a fragment that does not need the drawer it appear again.

**Comment by mikepenz** [comment]
Why don't you just switch the content? It is very very very very inefficient if you recreate a whole `DrawerLayout` over and over again for each fragment. 

Instead you should consider having the `Drawer` in your activity, and you just define from your fragment if the drawer is visible (if not just lock it and remove the hamburger of the toolbar) and in addition also define what it should show

**Comment by carmas123** [comment]
OK this is a good solution, but how can I lock the drawer (from gesture)

**Comment by mikepenz** [comment]
https://developer.android.com/reference/android/support/v4/widget/DrawerLayout.html#setDrawerLockMode(int, android.view.View)

**Comment by carmas123** [comment]
Thank you so much.

**Comment by mikepenz** [comment]
You're welcome
