### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by Baxtiyor1992** [mikepenz/MaterialDrawer#1797]
Hi there

Ia have expandable items in  drawer. But when user clicks to last of them it will expand bu user don't see any interaction. So, I want to scroll it to show it's sub items. How cant I do this?

**Comment by mikepenz** [comment]
@Baxtiyor1992 the elements in the Drawer are displayed in a normal `RecyclerView` you can get the reference to it via the `Drawer`

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L220

Then you can simply use the RV scroll methods :)

**Comment by Baxtiyor1992** [comment]
Thank you for so quick response :)
