### ISSUE TITLE
Highlighting issue in mini drawer

### ISSUE THREAD

**Issue by harshj94** [mikepenz/MaterialDrawer#1798]
I am using mini drawer in an app. But if I switch very quickly between the tabs when the mini drawer is in collapsed mode then the highlighting of the tab becomes invisible.
![img-20170325-wa0004](https://cloud.githubusercontent.com/assets/9678072/24322082/d7d695ee-1182-11e7-8572-5104d20fa3a7.jpg)

Please help me to fix this.

**Comment by harshj94** [comment]
This issue I also observed in the sample app uploaded by you on the play store

**Comment by harshj94** [comment]
Hi Mike... I am waiting for your response

**Comment by harshj94** [comment]
Mike, please reply to the issue.

**Comment by mikepenz** [comment]
@harshj94 this problem happens because of the Android system wrongly passing through the selected state to the `StateListDrawable`. 
You can try to set the following on the `MiniDrawer`:
```java
miniResult.getAdapter().withSelectWithItemUpdate(true);
```
