### ISSUE TITLE
colored status bar

### ISSUE THREAD

**Issue by yoavst** [mikepenz/MaterialDrawer#18]
I've had to add a view and in order to make it work.
```xml
<View
        android:id="@+id/status_bar"
        android:layout_width="match_parent"
        android:layout_height="25dp"
        android:background="@color/primary_color_dark" />
```

**Comment by Moter8** [comment]
Looks like this for me, blank activity just with the navigation Drawer added:

![1](http://i.imgur.com/W86DuHG.png)

Did you include these colors? https://github.com/mikepenz/MaterialDrawer#stylesxml-optional

**Comment by yoavst** [comment]
Do you use `fitsystemwindow`?

**Comment by Moter8** [comment]
@yoavst Not that I know of, actually.

**Comment by yoavst** [comment]
I've tried the sample apk but it didn't have it.

**Comment by mikepenz** [comment]
@yoavst what phone do you use?

**Comment by mikepenz** [comment]
I use the MaterialDrawer with the wall:splash app and in the sample app and in both cases it has the colored statusbar

do you use a custom theme, or do you extend the provided theme? do you set the accentColor, primaryColor, and so on?

**Comment by yoavst** [comment]
My themes extends AppTheme.Light.
I've set those attrs.

**Comment by mikepenz** [comment]
@yoavst can you post the layout you've created? because i think there are some issues with the padding and this is causing your issue. please also take a look at the updated sample which changed the way how the toolbar is used a little bit.

**Comment by mikepenz** [comment]
@yoavst i'll close this issue because it's nothing MaterialDrawer specific. 

You can still ask questions here, and i'll try to help you as far as possible.

**Comment by gpulido** [comment]
Hello,
I'm having the same problem.
This is my activity_layout.xml:
```xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    >    
    <FrameLayout android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
    /> 
    <include layout="@layout/toolbar_actionbar" />
</FrameLayout>
```
The actionbar layout is the following:
```xml
<android.support.v7.widget.Toolbar
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/toolbar"
    android:layout_width="match_parent"
    android:layout_height="?attr/actionBarSize"
    android:background="?attr/colorPrimary"
    android:clipToPadding="false"
    android:elevation="4dp"
    android:transitionName="actionBar"/>
'''
If I use MaterialDrawerTheme.Light.ActionBar.DarkActionBar.TranslucentStatus
The statusbar is translucent always, even if I try to give it a color using setStatusBarColor through code

If I use MaterialDrawerTheme.Light.ActionBar.DarkActionBar the statusbar is not translucent never, even when the navigation drawer is opened.
I have also tested changing the .withTranslucentStatusBar(true) property of the Drawer, and it doesn't affect anything.
The only way to have some color on the statusbar is by drawing a view under it.
