### ISSUE TITLE
Host a sample project somewhere

### ISSUE THREAD

**Issue by tommytcchan** [mikepenz/MaterialDrawer#180]
I'm having a hard time grasping in the samples where to put this code, partly due to the fact that there can be multiple implementation when it comes to so call material drawers.

Does this library require the use of DrawerLayout? If so it is not evident in the examples (all the examples tell you is to include the one-liner or deviations of that). 

Which views/preconditions need to be set up in order for this to work? A sample project would be tremendous help.

**Comment by tommytcchan** [comment]
Okay nevermind i just checked out the project and saw examples. Perhaps in the README one should mention that?

**Comment by mikepenz** [comment]
@tommytcchan i think it's normal practice to have a sample / app within a github project. So i think it's not really necessary to add another info about this :D. 

But yeah probably there should be more info about the fact that you don't have to handle the DrawerLayout on your own if you use the default feature. For extended usecases you can still to that and just use the View which is generated.

**Comment by tommytcchan** [comment]
@mikepenz sorry I didn't mean to come across as dismissing, great work on the project. Just would be awesome to point people new the library to the right direction would be great.

**Comment by mikepenz** [comment]
@tommytcchan yeah i try my best. I'm better in writing the library than improving the documentation :stuck_out_tongue_closed_eyes:

**Comment by tommytcchan** [comment]
@mikepenz tell you what I'll contribute to the docs after I finish my implementation =)

**Comment by mikepenz** [comment]
:D that would be great. You also see stuff which is a bit more difficult. I can't really tell which stuff will cause trouble for people. 

I really feel that all tasks are really simple :D but yeah i wrote it xD

**Comment by tommytcchan** [comment]
Yeah totally know what you mean. Sounds good!
