### ISSUE TITLE
Xamarin Support

### ISSUE THREAD

**Issue by Chelayos** [mikepenz/MaterialDrawer#1801]
Looks Great!!

Can I use this MaterialDrawer in my Xamarin Project too? If so, where(which folder) or how do I import it to my Visual Studio Solution? thanks!

**Comment by mikepenz** [comment]
Sorry I do not give support for Xamarin. This is only for real Android Studio projects. 

(I know there were some projects which ported the Drawer over to Xamarin, you may be able to find it. Please refer there then if you need help)
