### ISSUE TITLE
Right button on profile?

### ISSUE THREAD

**Issue by thaindq** [mikepenz/MaterialDrawer#1803]
Hi, I have a few questions:
1. I'm looking for a way to add a button on the right of profiles on the profile list, for example: to delete profile. Is this possible?
2. How can I open profile list by default?
3. How can I make the drawer to forget it's state after closing? For example: if I open the drawer and switch to profile list but do nothing. Next time I open the drawer it's still at the profile list
4. Can I stick account header (no scrolling)?

Thank you for creating this great library

**Comment by mikepenz** [comment]
@thaindq yes it is possible. You just have to create a `CustomProfileItem`. (https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java is the default one, you can base on this. extend it. whatever you need) 

There is a method which allows you to toggle the current state. So you can toggle to show the profile list. (https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L101) 

With that same method. 

You can. You basically build the header independent of the `DrawerBuilder` and then set it's view as sticky header.
