### ISSUE TITLE
edit logo position

### ISSUE THREAD

**Issue by abdelhedinizar** [mikepenz/MaterialDrawer#1804]
Hi, I have a question:
can i edit the position of the logo on my profile menu or edit the heigth and width of it also

**Comment by mikepenz** [comment]
you can overwrite the xml of the header. Just copy the xml used by the drawer to your project (keep it's name) and adjust it. (do not remove any view which has an identifier, or change their type)

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml

**Comment by abdelhedinizar** [comment]
How can i adjust it ?

**Comment by mikepenz** [comment]
As mentioned. you copy that xml to your project and edit the layout

**Comment by abdelhedinizar** [comment]
Thanks!!! Worked
