### ISSUE TITLE
PrimaryDrawerItem not tinting?

### ISSUE THREAD

**Issue by nam2017** [mikepenz/MaterialDrawer#1805]
I have followed the tutorial and the guidelines, but my Drawer Icons are allways white (the original drawable color), they are not tinting.

I am missing something? how can i tint the icons and the text of the item at the same time?

thanks!

**Comment by mikepenz** [comment]
@nam2017 have you enabled tinting?

**Comment by nam2017** [comment]
**withIconTintingEnabled** solves the problem! 

I have been using your library for a long time and i didint know this feature!

thanks for this great lib!
