### ISSUE TITLE
HeaderDrawer icon size

### ISSUE THREAD

**Issue by RafaHDu** [mikepenz/MaterialDrawer#1806]
Hi! I have an problem when try to load an image on the icon of the drawer. When i load it the image gets cuted on the left as on the right side... Do we have an way to increase the size of the 'icon' ? Probably is one of the solutions...

![billgates_is_my_father](https://cloud.githubusercontent.com/assets/18510023/24462426/dadc6996-149b-11e7-9e4b-7200c59684e1.png)

Thanks!

**Comment by abdelhedinizar** [comment]
Hi i solve it by resize the image i use this method

    private Drawable resize(Drawable image) {
        Bitmap b = ((BitmapDrawable)image).getBitmap();
        Bitmap bitmapResized = Bitmap.createScaledBitmap(b,500,500, false);
        return new BitmapDrawable(getResources(), bitmapResized);
    }

**Comment by hamdiank** [comment]
worked for me ,, @abdelhedinizar  you are the best

**Comment by RafaHDu** [comment]
@abdelhedinizar Thanks!!! Worked!!  U the man ahah ;)

**Comment by mikepenz** [comment]
@RafaHDu the image should be square. ;). So the solution of @abdelhedinizar is nice ;)

otherwise you can adjust the `ImageView`'s image scaletype the same way of editing the header layout
https://github.com/mikepenz/MaterialDrawer/issues/1804
