### ISSUE TITLE
How to dynamic drawerItem?

### ISSUE THREAD

**Issue by indralaman** [mikepenz/MaterialDrawer#1807]
1. Your library is usefull & very easy to use, thanks for sharing.

2. Can I create drawer item dynamicly, ex: i have arraylist of menu items 
.
.
.
 .addDrawerItems(
foreac(........){
new PrimaryDrawerItem().withName(......),
}
.
.

**Comment by aitorvs** [comment]
Just put your forEach() inside a method that returns a List<IDrawerItem> and use method withDrawerItems() instead.

**Comment by indralaman** [comment]
thank for your attendtion, but is not easy.

Look "new PrimaryDrawerItem().withName(......)" this is singgle item.

I've tried, and the best result is
1. Create methodt to extract data from sqlite
private List<DrawItem> kategori() {
        List<DrawItem> items = new ArrayList<DrawItem>();
        DrawItem DI = null;
        db=new DBhelper(getApplicationContext());
        vlist=db.getKat();
        for (int i = 0; i < vlist.size()-1; i++)
        {
            DI=new DrawItem();
            SecondaryDrawerItem item2 = new SecondaryDrawerItem().withName(vlist.get(i).getNama());
            Log.d("Nama",vlist.get(i).getNama());
            DI.setItem(item2);
            items.add(DI);
        }

        return items;
    }

2. Write item one by one, Draweritem

.
.
.
.addDrawerItems(
                        new SectionDrawerItem().withName("Categories"),
                       kategori().get(0).getItem(),
 kategori().get(1).getItem(),
 kategori().get(2).getItem(),
and more.....
                        .
                )
.
.

any idea??

**Comment by indralaman** [comment]
SOLVED THANK, I was less careful your "withDrawerItems()"

**Comment by adityamhatre** [comment]
how did you solve it ?
