### ISSUE TITLE
Question about setSelection()

### ISSUE THREAD

**Issue by aitorvs** [mikepenz/MaterialDrawer#1808]
Hi, I am using `setSelection(id)` programmatically. The item I am trying to select is a secondary item inside an `ExpandableDrawerItem`. The thing is, it works just fine if the `ExpandableDrawerItem` is expanded, but if it is collapsed, the item is not selected. 
How can I select one item even when its parent `ExpandableDrawerItem` is collapsed?

**Comment by mikepenz** [comment]
@aitorvs collapsed items are not selectable, as they are currently not actively displayed in the list. You will have to set the `withPositionBasedStateManagement(false)` so it will switch to `id` based system. 

It might work then already for you...

**Comment by aitorvs** [comment]
@mikepenz just tried `withPositionBasedStateManagement(false)` and select the item using both `setSelection(id)` and `setSelectionAtPosition(pos)` but neither worked for me -_- 
Do you have any more insight as to why this is not working for me? My config of the drawer is very standard:

```
        Drawer drawer = new DrawerBuilder()
            .withActivity(mActivity)
            .withToolbar(mToolbar)
            .withPositionBasedStateManagement(false)
            .withAccountHeader(header)
            .withSavedInstance(saveInstanceState)
            .withShowDrawerOnFirstLaunch(true)
            .withDrawerItems(createMenuItems())
            .withOnDrawerItemClickListener((view, position, drawerItem) -> {...}
```


PS: awesome library btw. Love it!

**Comment by mikepenz** [comment]
@aitorvs so the `Drawer` uses the `FastAdapter` to fill the `RecyclerView` with the items. This also provides the `expandable functionality. 

If an item is not displayed it won't be included directly for selection. 

So you will have to set the item as `selected` and then notify the drawer that the subitems were updated. 
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L1692

This will only work for the first level though.

**Comment by aitorvs** [comment]
@mikepenz so this is what I've got so far:
```
    int expandableItemId = menuItem.getMenuGroup().getTitleId(); // expandable ID
    mDrawer.setSelection(expandableItemId, false); // select it, don't fire (?)
    int pos = mDrawer.getPosition(expandableItemId); // get its pos in the adapter
    mDrawer.getAdapter().notifyAdapterSubItemsChanged(pos); // notify ?

    // now try to select the sub-item (?)
    mDrawer.setSelection(menuItem.getId());

```

This does not work but not sure if this is what you meant (?)

**Comment by mikepenz** [comment]
@aitorvs I meant you have to set on the specific `DrawerItem` that it is selected. the method `setSelection()` would not select subitems. 

so you set the subitem selected. and if it is visible you should also call the `notifyAdapterSubItemsChagned` as you correctly do. 

There was more focus on filling lists fast, and having for normal lists selection, than for more complex sub/expandable hierachies, which results in this being not as simple as the rest. Sorry.

**Comment by aitorvs** [comment]
How can I set the specific DrawerItem (sub-item) that I want to select? 

Maybe I didn't explain before the whole scenario: the drawer has some expandable items with sub-items inside. The user can either go to the drawer to select menu items (good) but the app also has a dashboard with some shortcuts to some menu sub-items. If the user clicks on one short-cut in the dashboard, I want the user to get to the same place as if he accessed that thru the menu. Mainly because if the user opens the menu later on, I want the menu to reflect the current navigation state of the app.

That's why I am trying to select sub-items programmatically.

Do you have any example code to get to that behavior? It'd be of great help. I am trying to figure how can I tell the adapter to behave as if the user had clicked in the expandable item. But can't find the entry point to tell the adapter to populate the sub-items.

Thanks a ton

**Comment by aitorvs** [comment]
@mikepenz I think I managed to work around it ;)

I however found one (maybe) issue that also happens in the sample app. If I select one sub-item, close the parent expandable and open it back up, the previous selected sub-item is no more selected.
