### ISSUE TITLE
Failed to resolve Gradle

### ISSUE THREAD

**Issue by Ne1c** [mikepenz/MaterialDrawer#181]
When building project(sync gradle), appears this error:
Error: Failed to resolve: com.mikepenz.materialdrawer:library:2.7.0

**Comment by raghunandankavi2010** [comment]
You can download the .aar and it as a jar @ maven central http://search.maven.org/#search|ga|1|g%3A%22com.mikepenz.materialdrawer%22

**Comment by mikepenz** [comment]
@Ne1c the newest version is available at maven central. as @raghunandankavi2010 already showed with the link to maven central ;)

Can you check if you have enabled the offline mode of gradle? 


thanks @raghunandankavi2010 for helping

**Comment by Ne1c** [comment]
how i can install, after download .aar and .jar files?

**Comment by mikepenz** [comment]
@Ne1c just disable offline mode sync your gradle build and reenable it. 

offline mode means it won't connect to the internet to download new libs
