### ISSUE TITLE
Can't handle the click for the first item

### ISSUE THREAD

**Issue by AleSpero** [mikepenz/MaterialDrawer#1810]
Hello there, i feel like i'm missing something, but i can't seem to handle the selection of the first item in my Drawer. I have a switch case inside `onItemClick` and a couple of items inside my drawer. I have set up all identifiers correctly, but the method onItemClick handles every item's click except the first.

I'll post my code.

Here's the drawer:

     `final static int CONTROL_PANEL = 1;
        final static int ACTIVITY_RECOGNITION = 2;
        final static int SENSOR_DATA = 3;
        final static int SETTINGS = 4;
       final static int ABOUT = 5;

    final PrimaryDrawerItem controlpanel = new PrimaryDrawerItem().withName("Control Panel")
                    .withIcon(GoogleMaterial.Icon.gmd_menu)
                    .withIdentifier(CONTROL_PANEL)
                    .withSelectable(true);

    result = new DrawerBuilder()
                    .withActivity(this)
                    .addDrawerItems(
                            //aggiungo elementi al mio Drawer
                            controlpanel,
                            new DividerDrawerItem(),
                           new PrimaryDrawerItem().withDescription("Starts the activity recognition service").withName("Activity Recognition").withIcon(GoogleMaterial.Icon.gmd_directions_walk).withIdentifier(ACTIVITY_RECOGNITION),
                            new PrimaryDrawerItem().withName("Sensor Data").withIcon(FontAwesome.Icon.faw_bar_chart).withIdentifier(SENSOR_DATA),
                            new PrimaryDrawerItem().withName(getString(R.string.settings)).withIcon(GoogleMaterial.Icon.gmd_settings).withIdentifier(SETTINGS),
                            new PrimaryDrawerItem().withName(getString(R.string.about)).withIcon(GoogleMaterial.Icon.gmd_info).withIdentifier(ABOUT))
                        .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                        @Override
                        public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                            if (drawerItem instanceof Nameable) {
                               // Toast.makeText(MiniDrawerActivity.this, ((Nameable) drawerItem).getName().getText(MiniDrawerActivity.this), Toast.LENGTH_SHORT).show();
                        }
                            switch (position){

                            case CONTROL_PANEL:
                                Log.d("lol","what");
                                if(!isExpanded){
                                    //Apro drawer completo
                                    Log.d("HomeActivity","espando");
                                    crossFader.crossFade();
                                    isExpanded = true;
                                    controlpanel.withIcon(GoogleMaterial.Icon.gmd_arrow_back);
                                }
                                else{
                                    //chiudo drawer
                                    crossFader.crossFade();
                                    Log.d("HomeActivity","riduco");
                                    isExpanded = false;
                                    controlpanel.withIcon(GoogleMaterial.Icon.gmd_menu);

                                }

                                break;

                            case ACTIVITY_RECOGNITION:
                                //Faccio partire il service
                                //Differenza tra mini e complete in termini di azioni?
                                Log.d("HomeActivity","activityrec");
                                break;

                            case SENSOR_DATA:
                                //Activity dati sensori
                                Log.d("HomeActivity","sensordata");
                                break;

                            case SETTINGS:
                                //Activity settings
                                Log.d("HomeActivity","settings");
                                startActivity(new Intent(HomeActivity.this,SettingsActivity.class));
                                break;

                            case ABOUT:
                                //About
                                Log.d("HomeActivity","about");
                                break;

                        }

                        return false;
                    }
                })
                    //.withDrawerGravity(Gravity.)
                    .withGenerateMiniDrawer(true)
                     .buildView();`

If i click on the first item, i don't even have the logs printed out in the console. i tried removing `.withSelectable(true)`, and nothing changed.

thanks a lot for your work, though :)

**Comment by AleSpero** [comment]
I also have a question, i tried to put an ExpandableDrawerItem in a mini drawer, and when the drawer is minified, i can't see the item, but when i expand it, it's there. Is this normal behaviour? is there a way to make it appear in the mini drawer?

Thanks a lot. :)

**Comment by mikepenz** [comment]
@AleSpero expandable items are not supported (and there is no plan to do so) in the `MiniDrawer`. it might be possible to work around this. but the MiniDrawer is meant for quick access for a few items, not many. 

because the first item is already selected, I guess. 
`withSelectable(true)` will only prevent user input selection, not programatically selection which happens during init. You can set the default selection to  `-1` or a different item. 

If you need the initial event to be fired you can also do this:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L781

**Comment by AleSpero** [comment]
@mikepenz Thanks for the response. I resolved the first issue, didn't know it assigned an identifier also at the `DividerDrawerItem`, so the first element was 0, even if i set its identifier with `.withIdentifier(1)`. 

For the ExpandableDrawerItem, in the mini drawer i just want an icon, kinda like the other items, and when i expand the drawer, i get the expandable.
I thought i could get this to work by adding a SimpleDrawerItem (that should represent the ExpandableDrawerItem) to the mini drawer, and then remove it when the user expands the drawer. Do you thing this is an acceptable workaround or i can do something better? thanks a lot.

**Comment by mikepenz** [comment]
Yeah. :D Great that you solved it. 

for the second problem. So the main thing is why I didn't include this in the first place, is that it doesn't make too much sense to overfill this MiniDrawer. If it has only a small amount of elements it's good. It will also just show Primary items by default no `SecondaryDrawerItem`s. 
Your solution would work, but you will have to make sure that both stay in sync and that you do not run into weird states. 

you could theoretically have a look into the `MiniDrawer` implementation and overwrite it (listening to the expand from the normal drawer item and then just do the same in the `MiniDrawer` and visa vers, but do remember that it will require quite some logic to get it right (which is an additional reason why I didn't implement it, I wanted to keep such complex behaviours which are probably needed just in a few special apps))

**Comment by AleSpero** [comment]
Ok ok! i'll look into it. Many thanks :D

**Comment by mikepenz** [comment]
Let me know if questions come up
