### ISSUE TITLE
Sub-menu items are unselected when collapsible parent is collapsed and re-expanded

### ISSUE THREAD

**Issue by aitorvs** [mikepenz/MaterialDrawer#1812]
For collapsible menu items with sub-items. The following scenario does not work properly:

1) open menu drawer
2) expand collapsible menu item
3) click on sub-menu item (menu drawer closes)
4) open menu drawer (the previously selected sub-menu item is selected)
5) collapse collapsible menu item, and expand it again
6) the sub-menu items is no longer marked as selected.

**Comment by mikepenz** [comment]
@aitorvs with the default position based statemanagment, the `FastAdapter` is only able to keep selections for items which are visible in the list (so only root elements), non existing elements (so those without a position (including sub items)) can't stay selected. (you can toggle this with here: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L879) 

in addition, you can prevent the drawer from auto-closing if you do not want this.

**Comment by aitorvs** [comment]
I will try `withPositionBasedStateManagement(false)` then. I guess with that the sub-item(s) should remain selected even when the parent menu item is collapsed and re-expanded.

The drawer auto-closing behavior is ok.

**Comment by aitorvs** [comment]
`withPositionBasedStateManagement(false)` has no effect. Sub-items get de-selected when the root element is collapsed and re-expanded.

**Comment by mikepenz** [comment]
@aitorvs ok let me try to produce a sample

**Comment by aitorvs** [comment]
@mikepenz thanks, let me know.

**Comment by mikepenz** [comment]
@aitorvs can you please update to v25.3.0 and try again with the `withPositionBasedStateManagement(false)` flag? I found this was not correctly passed to the adapter, resulting it not being used

**Comment by aitorvs** [comment]
@mikepenz I updated to 8.5.3 and fixed the issue. Thanks!

**Comment by mikepenz** [comment]
Thank you for your time, and helping to get this fixed :)

**Comment by aitorvs** [comment]
Thank You for the awesome lib and the quick fix ;)
