### ISSUE TITLE
ProgressBar over drawer items

### ISSUE THREAD

**Issue by andris95** [mikepenz/MaterialDrawer#1813]
Hi!
My question is: is it possible to display a custom view (in my case, a progress bar) over the drawer's items.
For example, I have a sticky footer 'Logout' button, and I want to display a progress bar inside the drawers layout, in center horizontally and vertically, without closing the drawer. Is it possible?
http://imgur.com/a/mIBnF

**Comment by mikepenz** [comment]
@andris95 I am not sure what the screenshot should show. 

You can alter the layouts used for the drawer, and add overlapping views.

**Comment by andris95** [comment]
http://imgur.com/a/Zd1On
I'd like to achieve this.
I know I can add a custom view as root view for the drawer, but I'm just lazy to do that, wonder if there a simpler way.

**Comment by mikepenz** [comment]
you can overwrite this layout and add another view in it. 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_slider.xml

(do not alter id's or anything, just add your progressbar) 
you can then get the reference to that view from the drawer, and show / hide your progressbar. make sure it is in front and not overlapped by the list.

**Comment by andris95** [comment]
Yes, it's working! Thank You very much!
