### ISSUE TITLE
method to override RTL alignment in mixed string?

### ISSUE THREAD

**Issue by waterwheelcreative** [mikepenz/MaterialDrawer#1816]
We have a mixed language string (English / Arabic) that is displayed in MaterialDrawer.

As we have enabled RTL the Arabic language is detected in string and text aligns right.

![material-drawer](https://cloud.githubusercontent.com/assets/5675449/24704888/dbdc51ec-1a4c-11e7-98eb-2603fe63daa3.png)

Visually this is not our desired result - we'd like to override while in English mode and align left.

There many ways to force left or right alignment but they do not seem to work in MaterialDrawer. We have tried adding \u200e to string without success (works elsewhere in App).

We are implementing like this:
```
final PrimaryDrawerItem languageItem = new PrimaryDrawerItem().withIdentifier(MORE_ITEM_ID)
                .withName(R.string.changeLanguage)
                .withIcon(R.drawable.ic_languageicon);
```
```
        //create the drawer and remember the `Drawer` drawer object
        drawer = new DrawerBuilder()
                .withActivity(activity)
                .withAccountHeader(header)
                .withToolbar(toolbar)
                .addDrawerItems(
                        profileItem,
                        starredItem,
                        new DividerDrawerItem(),
                        languageItem
                )
                .withOnDrawerItemClickListener(
```
```
<string name="changeLanguage">تغيير اللغة Change Language</string>
```

**Comment by mikepenz** [comment]
@waterwheelcreative if you do not want to have RTL aligned content you should disable RTL support for your application at all. 
The `MaterialDrawer` does not handle this at all, and only the android system is managing this.  (only the layouts are compatible to be displayed in RTL)

**Comment by waterwheelcreative** [comment]
@mikepenz  - we definitely need to support RTL (this is a multi-language App) but just wanted to override for this instance. OK - not possible to override in MaterialDrawer - Thanks for response.

**Comment by mikepenz** [comment]
@waterwheelcreative it is not a `MaterialDrawer` specific topic. It's more or less basic `Android` question / issue, as the `MaterialDrawer` simply displays a string within a `TextView`

**Comment by waterwheelcreative** [comment]
@mikepenz - thanks - I understand but there are ways to override RTL within a textfield such as gravity,  special character in string \u200e, android:textDirection that we are using elsewhere in this App but they are not working within MaterialDrawer hence my specific question.

**Comment by mikepenz** [comment]
Here you can see the layout used for the `MaterialDrawer`'s `PrimaryDrawerItem`:

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_primary.xml#L32

**Comment by haneef5k** [comment]
@mikepenz thanks..! it work, i added android:textAlignment="viewStart" and removed android:textDirection="anyRtl".
