### ISSUE TITLE
Keep showing sticky items when account drawer is expanded

### ISSUE THREAD

**Issue by shtolik** [mikepenz/MaterialDrawer#1819]
In our app we'd like to keep showing sticky drawer items (added addStickyDrawerItems to drawerBuilder), even after user clicked on a account header and a list of Profiles is shown. 
How could it be done? 
As far as i see in the code change to list of profiles is done in 

```
public void switchDrawerContent(@NonNull OnDrawerItemClickListener onDrawerItemClickListener, OnDrawerItemLongClickListener onDrawerItemLongClickListener, @NonNull List<IDrawerItem> drawerItems, int drawerSelection){
...
        //hide stickyFooter and it's shadow
        if (getStickyFooter() != null) {
            getStickyFooter().setVisibility(View.GONE);
        }
        if (getStickyFooterShadow() != null) {
            getStickyFooterShadow().setVisibility(View.GONE);
        }
}
```
I was trying to override the method in my project in a DrawerSticky (which 'extends Drawer') class, but hasn't succeed, because original Drawer class is still used in AccountHeaderBuilder from which this switchDrawerContent method is called. I will still try to override it as well, but i was thinking that may be you can just add some flag which would not remove those sticky items instead?

Thanks in advance.

**Comment by mikepenz** [comment]
Nice idea. I have to give it a closer look.

**Comment by SuperThomasLab** [comment]
The app [Inbox by Gmail](https://play.google.com/store/apps/details?id=com.google.android.apps.inbox) (made by Google) also doesn't hide the sticky items when the account drawer is expanded.
