### ISSUE TITLE
Icon Color for Item

### ISSUE THREAD

**Issue by danielgomezrico** [mikepenz/MaterialDrawer#182]
Disabled/Selected icon color is not changing the icon color.
    
    new SecondaryDrawerItem().withName(getString(R.string.drawer_item_become_driver))
								.withTag(2)
								.withIcon(R.mipmap.ic_drive_eta_black_24dp)
								.withSelectedIconColorRes(R.color.green)
								.withDisabledIconColorRes(R.color.gray)
								.withSelectedTextColorRes(R.color.green_accent),

**Comment by wKovacs64** [comment]
You need to add `.withTintSelectedIcon(true)` to enable that.

**Comment by mikepenz** [comment]
@danielgomezrico if you have additional questions let me know. thanks

**Comment by danielgomezrico** [comment]
Ok thanks

**Comment by danielgomezrico** [comment]
How can I set those in style?  all my items will have the same values

**Comment by mikepenz** [comment]
@danielgomezrico what do you mean? 

following the Design Guidelines the items should have the color of the primary color if selected.

**Comment by danielgomezrico** [comment]
Yeah, but mine don`t have the primary color on selection by default, it have the icon color always, I will send my initialisation code in the night.

**Comment by danielgomezrico** [comment]
AccountHeader.Result headerResult = new AccountHeader()
                .withActivity(this)
                .withProfileImagesClickable(false)
                .withSelectionListEnabled(false)
                .withHeaderBackground(R.drawable.status_drawer_header_background)
                .addProfiles(
                        new ProfileDrawerItem()
                                .withName(customer.getData().getName())
                                .withEmail(customer.getData().getEmail())
                                .withIcon(ResourceHelper.getDrawable(this, R.mipmap.ic_launcher))
                ).build();

        menuDrawer = new Drawer()
                .withActivity(this)
                .withToolbar(toolbar)
                .withOnDrawerItemClickListener(this)
                .withAccountHeader(headerResult)
                .withActionBarDrawerToggleAnimated(true)
                .withActionBarDrawerToggle(true)
                .withTranslucentStatusBar(true)
                .addDrawerItems(
                        new PrimaryDrawerItem()
                                .withName(getString(R.string.title_fragment_status))
                                .withTag(0)
                                .withIcon(R.mipmap.ic_map_white_24dp),

        new DividerDrawerItem(),

                new SecondaryDrawerItem().withName(getString(R.string.drawer_item_faq))
                        .withTag(1)
                        .withIcon(R.mipmap.ic_help_black_24dp),

                new SecondaryDrawerItem().withName(getString(R.string.drawer_item_become_driver))
                        .withTag(2)
                .withIcon(R.mipmap.ic_drive_eta_black_24dp),

                new SecondaryDrawerItem().withName(getString(R.string.drawer_item_contact))
                        .withTag(-2)
                        .withIcon(R.mipmap.ic_email_black_24dp),

                new DividerDrawerItem(),

                new SecondaryDrawerItem().withName(getString(R.string.drawer_item_logout))
                        .withTag(-1)
                        .withIcon(R.mipmap.ic_settings_power_black_24dp)
        ).build();

**Comment by raghunandankavi2010** [comment]
You just need to have `.colorRes(R.color.material_drawer_primary_text)`  for the items. Its missing.

**Comment by danielgomezrico** [comment]
@raghunandankavi2010  Excuse me but on which object?

**Comment by raghunandankavi2010** [comment]
@danielgomezrico  try the edited comment.

**Comment by mikepenz** [comment]
@danielgomezrico if it still does not work. do you try to set this on the black items? auto coloring isn't working for black item's as far as i can tell. if it's the case you have to set the colored icon as drawable on your own

**Comment by danielgomezrico** [comment]
@mikepenz I have it with white icons too and there´s no color on them

**Comment by danielgomezrico** [comment]
@raghunandankavi2010 
![image](https://cloud.githubusercontent.com/assets/76348/7107386/c342007c-e129-11e4-9e29-7cd3af728da9.png)
I got this
