### ISSUE TITLE
Alternative way to hide DraweItem (suggestion)

### ISSUE THREAD

**Issue by zunjae** [mikepenz/MaterialDrawer#1820]
Really enjoying this library, thank you for your efforts

If I can give one suggestion: please add a way to hide a DrawerItem directly on the object itself. 

Current way: 

//remove items with an identifier
result.removeItem(2);

Second way to hide item:
someItem = new PrimaryDrawerItem()
.withName("Super Cool Name")
.withShouldBeShown(true|false)

This way we can decide if an item should be shown without having to add the required logic [somewhere else] in the code. For me personally this would improve legibility

**Comment by mikepenz** [comment]
@zunjae thanks for the suggestion, but this is not planned and will not be added to the library. 

In my opionion removing the item / vs adding this item (2 lines in total) is still shorter than setting the drawerItem to `shouldBeShown`(true/false) . and then notifying the drawer about the change (in total 4 lines)
