### ISSUE TITLE
Mini drawer going over the main content

### ISSUE THREAD

**Issue by marijap93** [mikepenz/MaterialDrawer#1822]
Hello,

I am using the mini navigation drawer in my app only, but I was wondering if there's an option to make the mini drawer go over the content, without pushing it as you pull the drawer?

I tried rearranging the items in my xml file, but then the content that is bellow the drawer is not clickable.

So I'm looking for a way to make it work the same as the navigation drawer, but with the menu icon items always visible.

Thanks.

**Comment by mikepenz** [comment]
@marijap93 so you want to have a drawer like the normal drawer, but just with the `MiniDrawer` as content? 

Then I suggest you simply use the `DrawerLayout` from the support library, and set the `MiniDrawer` view as it's slider content.

**Comment by marijap93** [comment]
No, I am sorry I have not been clear enough.

I want to have the closed menu on the left (only the icons showing) and be able to swipe it right and open the full content (just like in the mini drawer), BUT to swipe it _over_ the other content - not pushing it to the right with the menu, as it is currently working.

![patterns_navdrawer_elevation1](https://cloud.githubusercontent.com/assets/17566369/24866297/ff834234-1e09-11e7-9182-de2a2554e902.png)

Something like the picture, when i swipe the mini drawer, i want the rest of the content to get darker and stay in the background, without moving along.

Is there a way to do this?

Thank you.

**Comment by mikepenz** [comment]
There is a way to do this. but this library does not provide such a way, and I assume you will have to implement this on your own. 

The library offers the approach via the `Crossfader` which you are using already I assume. (the one moving the content out of the window)

And the other one which is the `CrossfadeDrawerLayout` which basically has 3 Stages. 
- nothing shown, minidrawer shown, full drawer shown. 

In your case you will have to implement your own layout, or framelayout, which will just lay over the other view if swiped. doing basically the similar thing as the `DrawerLayout` just with a locked first state.

**Comment by marijap93** [comment]
Thanks, I'll try that out :)

**Comment by marijap93** [comment]
Just in case someone else needs this:

First, I separated the menu and the other content in separate layouts.
I solved my problem by overriding `onPanelSlide`, `onPanelOpened` and `onPanelClosed` by bringing the view of the main content (or the menu, depending on what I need) to the front by using `bringToFront()`

Works good now :)

**Comment by llOldmenll** [comment]
Was this case added in main functionality of library? If not maybe y can link sample?
