### ISSUE TITLE
Manifest merged failed

### ISSUE THREAD

**Issue by DenisMakovskyi** [mikepenz/MaterialDrawer#1823]
When I try compile material drawer dependency in gradle file, catch an error
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.0) from [com.android.support:support-v13:25.3.0] AndroidManifest.xml:27:9-31
	is also present at [com.android.support:design:25.3.1] AndroidManifest.xml:27:9-31 value=(25.3.1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.
_________________________________________________
I've update all support  libraries to 25.3.1 version

**Comment by DenisMakovskyi** [comment]
Resolved:
configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def requested = details.requested
            if (requested.group == 'com.android.support') {
                if (!requested.name.startsWith("multidex")) {
                    details.useVersion '25.3.1'
                }
            }
        }
    }

**Comment by mikepenz** [comment]
@DenisMakovskyi you can also use this one: 

```gradle
configurations.all {
    resolutionStrategy.force "com.android.support:appcompat-v7:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:cardview-v7:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:recyclerview-v7:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:design:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:percent:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:preference-v14:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:customtabs:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:support-annotations:${versions.supportLib}"
}
```
