### ISSUE TITLE
[Q] Reorder menu items

### ISSUE THREAD

**Issue by Cilenco** [mikepenz/MaterialDrawer#1826]
The title says it all:
Is it possible with this library to let the user reorder the menu items inside the NavigationDrawer?

**Comment by mikepenz** [comment]
@Cilenco it is possible with the `FastAdapter` which is the underlaying base for the items in the drawer. So yes. 

It will require some logic from your side though. 
Read more here: https://github.com/mikepenz/FastAdapter

**Comment by Cilenco** [comment]
Wow thanks, that worked great. Is there any chance that I can allow reordering only for some items? Let's say my items have a type and I only want to drag items with state `Dragable`. For all other items I do not want to start the drag process.

Btw. is it possible that the parameters of `itemTouchOnMove(int oldPosition, int newPosition)` are one based? I have to use `Collections.swap(getDrawerItems(), oldPosition-1, newPosition-1);` to get no `OutOfBoundsException`.

**Comment by mikepenz** [comment]
So basically I suppose you have a header set, which adds +1 to the positions :D

the positions are the global position (which means fastadapter global) 
the list of the `DrawerItems` is the items list only (so the specific itemadapter of the content)

**Comment by Cilenco** [comment]
Sorry one more question: I tried to implement draging for only a few items. For this I implemented `OnLongClickListener` and call `touchHelper.startDrag(...)` from it. But here is my problem.

`startDrag` needs a `ViewHolder` as parameter. I tried to use `item.getViewHolder(ViewGroup)` but if I pass the `RecyclerView` as ViewGroup parameter I get:

> Start drag has been called with a view holder which is not a child of the RecyclerView which is controlled by this ItemTouchHelper.

So which ViewGroup should I use for this?

**Comment by mikepenz** [comment]
I have updated the sample application and added the `IDraggable` interface to the item. 

https://github.com/mikepenz/FastAdapter/commit/ede61e262b657b5c046a78e501d4967a60379a5a

**Comment by Cilenco** [comment]
Wow thank you great work!

**Comment by mikepenz** [comment]
You are welcome

**Comment by Cilenco** [comment]
Is it also possible to add a reorder icon to the right side / end of a menu item to indicate the user that the items are dragable? Do I have to use a custom layout for this? If so which is the default layout?

**Comment by mikepenz** [comment]
@Cilenco in that case you will need to write a `CustomDrawerItem` head over to the sample app or to the FAQ to see some samples.

**Comment by thaindq** [comment]
@Cilenco can you provide some codes on how did you make it work? I'd like to reorder `SecondSecondaryDrawerItem` using drag & drop. According to [this](https://github.com/mikepenz/FastAdapter/blob/ede61e262b657b5c046a78e501d4967a60379a5a/app/src/main/java/com/mikepenz/fastadapter/app/SwipeListActivity.java), should I create a `FastItemAdapter` and attach it to the drawer as `DragDropUtil.onMove` only takes `FastItemAdapter`?
```
drawer = new DrawerBuilder()
    .withActivity(this)
    .withToolbar(toolbar)
    .withHasStableIds(true)
    .withAccountHeader(accountHeader)
    .withAdapter(fastItemAdapter)
    .build();

touchCallback = new SimpleDragCallback(this);
touchHelper = new ItemTouchHelper(touchCallback);
touchHelper.attachToRecyclerView(drawer.getRecyclerView());
```
@mikepenz any hints, please?

**Comment by Cilenco** [comment]
Here is the code I used to create reorderable items ins the drawer. In fact I created a subclass of `com.mikepenz.materialdrawer.Drawer` and `...DrawerBuilder` but it shouldn't be more then below:

    FastAdapter<IDrawerItem> adapter = new FastAdapter<>();
    adapter.withAllowDeselection(false);
    adapter.withSelectable(true);

    drawer.withAdapter(adapter);

    SimpleDragCallback touchCallback = new SimpleDragCallback(this);
    ItemTouchHelper touchHelper = new ItemTouchHelper(touchCallback);
    touchHelper.attachToRecyclerView(drawer.getRecyclerView());

For my items I used following subclass:

```
public class TextMenuItem extends PrimaryDrawerItem implements IDraggable<TextMenuItem, IItem> {

    protected boolean dragable;

    public TextMenuItem() {
        dragable = true;
    }

    @Override
    public boolean isDraggable() {
        return dragable;
    }

    @Override
    public TextMenuItem withIsDraggable(boolean b) {
        dragable = b;
        return this;
    }
}
```

I think it should be no problem to create the same subclass for your `SecondSecondaryDrawerItem`. Until now I hadn't had the time to create a custom `CustomDrawerItem` (to implement the reorder indicator) but if you wish I will upload my code here when it is finished.

**Comment by thaindq** [comment]
Thank you, I've been able to make it work now. It seems like all items are draggable by default. Is there any way to prevent this or I have to subclass every type of drawer item that I use with IDraggable interface?

**Comment by thaindq** [comment]
Nevermind, I found a way to archive that by setting `touchCallback.setIsDragEnabled(false);` and start the drag manually by calling `touchHelper.startDrag` in `Drawer.OnDrawerItemLongClickListener.onItemLongClick`.

**Comment by Cilenco** [comment]
> Is it also possible to add a reorder icon to the right side / end of a menu item to indicate the user that the items are dragable? Do I have to use a custom layout for this? If so which is the default layout?

> in that case you will need to write a CustomDrawerItem [...]

I manged to do this and it works great! I added an `ImageView` to the right of my custom layout. Depending on the selection I would like to tint the image, as you do with the text and left icon. Are there any helper methods I can use for this or can you at least tell me the color resources I should use for this?
