### ISSUE TITLE
Sticky footer not accepting different layouts

### ISSUE THREAD

**Issue by slai47** [mikepenz/MaterialDrawer#1827]
I adjusted the primary item layout to center align the text on the footer but setting the resource id using withFooter(int) and withStickyFooter(int) doesn't seem to reflect those changes. I add the footer after building the drawer using addStickyFooterItem(). I used layout_gravity and gravity on the text views with center on them and nothing worked. 

I also tried to remove the divider above the footer using withStickyFooterDivider(false) and withFooterDivider(false) and I'm still seeing a divider. Am I missing anything?

**Comment by mikepenz** [comment]
@slai47 you have changed the layout of the `PrimaryDrawerItem`?  Or do you want to have just a normal custom view in the footer?

Can you possibly also add a screenshot?

**Comment by slai47** [comment]
I'm just trying to do a custom view on the footer to have the text centered at the bottom. I grabbed the PrimaryDrawerItem layout and changed it so it would have the text centered but the text just goes back to normal.

**Comment by slai47** [comment]
`
//setup using builder
.withStickyFooterDivider(false)
  .withStickyFooter(R.layout.drawer_footer)
//builder

 PrimaryDrawerItem footer = new PrimaryDrawerItem()
                .withName(R.string.app_name)
                .withDescription("v" + version + " (" + versionCode + ")")
                .withIdentifier(IDEN_FOOTER);
  mDrawer.addStickyFooterItem(footer);

`

**Comment by mikepenz** [comment]
@slai47 the sticky footer uses the same logic to create the view, which would be used for the item in a normal case. So it sounds a bit weird that it would just go back to normal. 

How have you adjusted the view of the `PrimaryDrawerItem`?

**Comment by slai47** [comment]
I haven't changed PrimaryDrawerItem yet. Should I and what would I need to do to change the view id? Subclass primary drawer item?

**Comment by slai47** [comment]
I subclassed Primary DrawerItem and got it to work. Thank you and sorry for taking up your time.

**Comment by slai47** [comment]
Now I'm trying to remove the divider above the sticky footer

**Comment by mikepenz** [comment]
Great :)
