### ISSUE TITLE
IProfile withIcon(URL) not show up the image

### ISSUE THREAD

**Issue by anton-khansa** [mikepenz/MaterialDrawer#1828]
hi mike,
i have a problem with IProfile. i have copy paste your code but when i try run the code it not show the image.is that anything that i miss?i have try withICon(URI) it also not load the image. 

final IProfile profile = new ProfileDrawerItem().withName("Mike Penz").withEmail("mikepenz@gmail.com").withIcon("https://avatars3.githubusercontent.com/u/1476232?v=3&s=460").withIdentifier(100);

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#load-images-via-url
