### ISSUE TITLE
Footer divider not being removed

### ISSUE THREAD

**Issue by slai47** [mikepenz/MaterialDrawer#1829]
![device-2017-04-14-100327](https://cloud.githubusercontent.com/assets/2166487/25048634/a622e17e-20fa-11e7-833c-1347cfc7ccf1.png)

The bottom sticky footer divider isn't being removed even though when I'm building the drawer I use withStickyFooterDivider(false) or withFooterDivider(false). What am I failing to do in order to remove the divider.

**Comment by mikepenz** [comment]
do you mean the shadow?

**Comment by slai47** [comment]
Ok so its the shadow.

**Comment by slai47** [comment]
Thank you fixed it

**Comment by mikepenz** [comment]
Haha :) Great
