### ISSUE TITLE
Getting rid of the down arrow/down arrow action in Profile Header

### ISSUE THREAD

**Issue by therealccarter** [mikepenz/MaterialDrawer#1830]
I do not need the multi-user functionality, but I'm not sure how to get rid of it. I'd also like to have the entire header (profile image, header background, Display name, email) all be clickable (for 1 intent) but cannot see how to do so. Is this possible? Thanks

**Comment by mikepenz** [comment]
@therealccarter https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/accountheader_single_profile_without_dropdown.md

**Comment by therealccarter** [comment]
Fantastic, thank you.
