### ISSUE TITLE
Hamburger Icon Problem

### ISSUE THREAD

**Issue by harry0880** [mikepenz/MaterialDrawer#1831]
Hi Mike,

No matter how much I try, I fail to add hamburger icon in toolbar.
The method you told in description return a null pointer exception. 

Please help!!!

**Comment by mikepenz** [comment]
@harry0880 just pass the `Toolbar` to the `MaterialDrawer` and it's done for you. If you have no toolbar you will have to set this up manually. 

Also make sure the `Toolbar` you pass in is not null. 
If it is null, please see the sample application how a `Toolbar` is properly set up. If you need more help with the `Toolbar` please seach on google, as it is not a `MaterialDrawer` issue

**Comment by harry0880** [comment]
It was completely my fault...

I found that I had passed false to withActionBarDrawerToggle.
Sorry for putting silly question.
