### ISSUE TITLE
Spinner inside an ExpandableBadgeDrawerItem

### ISSUE THREAD

**Issue by L-Dogg** [mikepenz/MaterialDrawer#1832]
Hi Mike, I really admire your work on MaterialDrawer. I'd like to rewrite my application to use your plugin, but I have to use expandable lists with spinners as subitems. Is it possible using MaterialDrawer and ExpandableBadgeDrawerItem?

**Comment by mikepenz** [comment]
@L-Dogg it is not possible with the default items. But you can easily write your own `CustomDrawerItem`s doing whatever you need.

**Comment by L-Dogg** [comment]
Thanks for such a fast reply. So, extending `SecondaryDrawerItem` with additional fields will do?

**Comment by mikepenz** [comment]
@L-Dogg that's a solution. You can also write one from scratch if you do not need the flexibility of the `SecondaryDrawerItem`.

**Comment by L-Dogg** [comment]
Thanks for your help!

**Comment by mikepenz** [comment]
You are welcome. 

The sample also has a few custom ones. https://github.com/mikepenz/MaterialDrawer/tree/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems

This one is one of the simpler ones: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/IconDrawerItem.java

(As it does not base on the Primary or Secondary `DrawerItem`s which have a lot of configurations available)
