### ISSUE TITLE
Problems with CollapsableItem selection

### ISSUE THREAD

**Issue by rubengees** [mikepenz/MaterialDrawer#1833]
This is related to #1812.

I had the same problem as described in the issue and fixed it by setting `withPositionBasedStateManagement(false)`.

Now the following scenario causes problems (reproducable in the sample app if `positionBasedStateManagement` ist turned off):

- Expand `Collapsable Badge`
- Select `CollapsableItem`
- Collapse `Collapsable Badge`
- Select `Contact`
- Expand `Collapsable Badge`

Now two items are selected: `CollapsableItem` and `Contact`, which might confuse the user.

Thank you in advance for having a look!

**Comment by mikepenz** [comment]
@rubengees thanks for the report. This seems to be a `FastAdapter` issue then, as it won't remove the selection for an item which is currently not in the list. Not sure if this can be solved in a nice way without the requirement of iterating through the whole hierarchy (which is potential slow). I'll check for `FastAdapter` v3. 

I guess "single" selection is still active in that case?

**Comment by mikepenz** [comment]
Closing this here as it is a FastAdapter topic for v3
