### ISSUE TITLE
Sticky item loses focus after expanding and collapsing the account header

### ISSUE THREAD

**Issue by rubengees** [mikepenz/MaterialDrawer#1834]
If the user selects a sticky drawer item, expands the account header and collapses it, the previously selected sticky item is not selected anymore.

To reproduce, one can add a sticky item to the drawer in the sample app like so:

```java
.addStickyDrawerItems(
    new SecondaryDrawerItem()
        .withName(R.string.drawer_item_contact)
        .withIcon(GoogleMaterial.Icon.gmd_format_color_fill)
        .withIdentifier(21)
)
```

After that, select it and do the above described scenario.

Thank you in advance for having a look!

**Comment by mikepenz** [comment]
yeah. as the sticky draweritem gets removed and re-added via the accountheader

**Comment by rubengees** [comment]
Should we manage state ourself somehow or is this something you could add to the library?

**Comment by mikepenz** [comment]
It's best to manage on your side, as normally the sticky drawer's do not maintain the selection, but are more like options to go somewhere else. like to the settings screen or so
