### ISSUE TITLE
ActionBarDrawerToggle don't work with the miniDrawer

### ISSUE THREAD

**Issue by siffon1** [mikepenz/MaterialDrawer#1835]
I've tried everything to add the actionbar drawer toggle to the mini drawer but i always get a NullPointerException.

**Comment by mikepenz** [comment]
@siffon1 as the samples show. The `MiniDrawer` is added to the layout with a `Crossfader` in this case there is NO `DrawerLayout` in place --> So also the automatic handling of the `ActionBarDrawerToggle` is not in place for you. 

You have to go the goood old way without an `ActionBarDrawerToggle` as this only works with a `DrawerLayout` --> there are libraries out there providing this. You then simply hook it up and open / close the drawer. 

Remember this is not a MaterialDrawer issue, as the `ActionBarDrawerToggle` requies a `DrawerLayout` nothing I can do about that...
