### ISSUE TITLE
[Q] Get last selected item

### ISSUE THREAD

**Issue by Cilenco** [mikepenz/MaterialDrawer#1836]
Is there a method which is called right before the `onItemClick` method? I would like to get the currently selected item before the new one is selected (in `onItemClick` the new item is already selected).

I tried to override `setSelectionAtPosition(int, boolean)` because all setSelection... methods refer to it and the click event (`getOnDrawerItemClickListener().onItemClick`) is fired here but this does not seem to work.

**Comment by mikepenz** [comment]
You can either use the `withOnPreItemClickListener` from the `FastAdapter`
https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L129

Or you simply remember the position each time the `onItemClick` is called :D
