### ISSUE TITLE
[Question] Header to show header image and app name?

### ISSUE THREAD

**Issue by sonic2kk** [mikepenz/MaterialDrawer#1840]
I want to have a simple header displayed in the navigation drawer, similar to what the following would do:

`        AccountHeader testHeader = new AccountHeaderBuilder().withActivity(this).addProfiles(
                new ProfileDrawerItem().withName("App Name")
        ).build();`

However I do not want this for accounts. How would I achieve this?

Cheers.

**Comment by mikepenz** [comment]
@sonic2kk you can set the first and second line of text directly so you do not have to provide an account. 

And you can also disable the account selection. see the FAQ

**Comment by sonic2kk** [comment]
Thanks! If anyone stumbles upon this, the two lines to set the text are `yourAccountHeader.withSelectionFirstLine("First Line Text").withSelectionSecondLine("Second Line Text")`
