### ISSUE TITLE
[Question] startActivity after clicking ProfileSettingDrawerItem()

### ISSUE THREAD

**Issue by PetarCeho01** [mikepenz/MaterialDrawer#1841]
I addded your CrossfadeDrawerLayoutActvitiy and i want after clicking on ProfileSettingDrawerItem() to startActivity called AddAccount.class,Is there any way to do it ? 
Thank you !

**Comment by mikepenz** [comment]
@PetarCeho01 the drawer has the listener which is fired when an item is clicked. 
Do whatever you want in there.
https://github.com/mikepenz/MaterialDrawer#add-items-and-adding-some-functionality

**Comment by PetarCeho01** [comment]
` headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withCompactStyle(true)
                .withHeaderBackground(R.drawable.header)
                .addProfiles(
                        profile,
                        profile2,

                        //don't ask but google uses 14dp for the add account icon in gmail but 20dp for the normal icons (like manage account)
                        item = new ProfileSettingDrawerItem().withName("Add Account").withDescription("Add Account").withIcon(new IconicsDrawable(this, GoogleMaterial.Icon.gmd_plus).actionBar().paddingDp(5).colorRes(R.color.material_drawer_dark_primary_text)).withIdentifier(PROFILE_SETTING).withIdentifier(12),
                        item1 = new ProfileSettingDrawerItem().withName("Manage Account").withIcon(GoogleMaterial.Icon.gmd_settings).withIdentifier(11)

                )`

i got it working with the first drawer view with the drawerItemClickListener,but i need when i change the drawer view where the ManageAccount and AddAccount are to go to Activity?  I got it only working if i implement Add Account to the  .addDrawerItem {} but then it appears on the first drawer view.
Is there any way to do this ? 
I hope i explained or is there something that i missing ?
Thanks !

**Comment by mikepenz** [comment]
@PetarCeho01 please be a bit more specific I am not sure what you are trying to do. 

The Sample application shows how to set up a normal drawer with an `AccountHeader`:

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java

**Comment by PetarCeho01** [comment]
`headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withCompactStyle(true)
                .withHeaderBackground(R.drawable.header)
                .addProfiles(
                        profile,
                        profile2,

                        //don't ask but google uses 14dp for the add account icon in gmail but 20dp for the normal icons (like manage account)
                     new ProfileSettingDrawerItem().withName("Add Account").withDescription("Add Account").withIcon(new IconicsDrawable(this, GoogleMaterial.Icon.gmd_plus).actionBar().paddingDp(5).colorRes(R.color.material_drawer_dark_primary_text)).withIdentifier(PROFILE_SETTING).withIdentifier(12),
                        new ProfileSettingDrawerItem().withName("Manage Account").withIcon(GoogleMaterial.Icon.gmd_settings).withIdentifier(11)

                )
                  


                .withSavedInstance(savedInstanceState)
                .build();

        //Create the drawer
        result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withHasStableIds(true)
                .withDrawerLayout(R.layout.crossfade_drawer)
                .withDrawerWidthDp(72)
                .withGenerateMiniDrawer(true)
                .withAccountHeader(headerResult) //set the AccountHeader we created earlier for the header
                .addDrawerItems(

                        new PrimaryDrawerItem().withName("NASLOVNA").withIcon(GoogleMaterial.Icon.gmd_sun).withIdentifier(1),
                        new PrimaryDrawerItem().withName("MODA").withIcon(FontAwesome.Icon.faw_home).withBadge("22").withBadgeStyle(new BadgeStyle(Color.RED, Color.RED)).withIdentifier(2).withSelectable(false),
                        new PrimaryDrawerItem().withName("LIFESTYLE").withIcon(FontAwesome.Icon.faw_gamepad).withIdentifier(3),
                        new PrimaryDrawerItem().withName("LEPOTA I ZDRAVLJE").withIcon(GoogleMaterial.Icon.gmd_sun).withIdentifier(8),
                        new PrimaryDrawerItem().withName("VODIC").withIcon(FontAwesome.Icon.faw_eye).withIdentifier(4),
                        new PrimaryDrawerItem().withName("MAMA I DETE ").withIcon(GoogleMaterial.Icon.gmd_adb).withIdentifier(5),
                        new PrimaryDrawerItem().withName("INTERVJU").withIcon(GoogleMaterial.Icon.gmd_sun).withIdentifier(6),
                        new PrimaryDrawerItem().withName("BLOG").withIcon(GoogleMaterial.Icon.gmd_sun).withIdentifier(7),
                        new SectionDrawerItem().withName(R.string.drawer_item_section_header),
                        new SecondaryDrawerItem().withName("SETTINGS").withIcon(FontAwesome.Icon.faw_github),
                        new SecondaryDrawerItem().withName("Contact").withIcon(GoogleMaterial.Icon.gmd_format_color_fill).withTag("Bullhorn")
                ) // add the items we want to use with our Drawer
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        //    if (drawerItem instanceof Nameable) {
                        Toast.makeText(CrossfadeDrawerLayoutActvitiy.this, ((Nameable) drawerItem).getName().getText(CrossfadeDrawerLayoutActvitiy.this), Toast.LENGTH_SHORT).show();
                        //   }
                        if (drawerItem != null) {


                            Intent intent = null;
                            if (drawerItem.getIdentifier() == 1) {
                                intent = new Intent(CrossfadeDrawerLayoutActvitiy.this, AddAccount.class);
                            } else if (drawerItem.getIdentifier() == 11) {
                                intent = new Intent(CrossfadeDrawerLayoutActvitiy.this, AddAccount.class);
                            }
                            if (intent != null) {
                                CrossfadeDrawerLayoutActvitiy.this.startActivity(intent);

                            }


                        }


                        //we do not consume the event and want the Drawer to continue with the event chain
                        return false;
                    }
                })
             
                .withShowDrawerOnFirstLaunch(true)
                .build();
`

When i click on the Drawer and click the  PrimaryDrawerItem().withName("NASLOVNA").withIcon(GoogleMaterial.Icon.gmd_sun).withIdentifier(1), it opens my the activity AddAccount.class,
i want the same thing to happen when i click on 
 new ProfileSettingDrawerItem().withName("Add Account").withDescription("Add Account").withIcon(new IconicsDrawable(this, GoogleMaterial.Icon.gmd_plus).actionBar().paddingDp(5).colorRes(R.color.material_drawer_dark_primary_text)).withIdentifier(PROFILE_SETTING).withIdentifier(12),

How can i add a reference to the DrawerItem () to startActivity() that are in the AccountHeaderBuilder() ?

Sorry for not be precise!

**Comment by PetarCeho01** [comment]
i set it but the only thing i cannot open an activity from the ProfileSettingDrawerItem() that is defined in the AccoutHeaderBuilder() ?

**Comment by mikepenz** [comment]
@PetarCeho01 you can't you need a different click listener for the accountheader and also the one for the drawer. 

If you call the same method from those then it's fine. but still...


See the `DrawerActivity` it adds a `ACcountHeaderListener` which allows you to react on clicks in the `AccountHeader`

```java
.withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean current) {
                        //sample usage of the onProfileChanged listener
                        //if the clicked item has the identifier 1 add a new profile ;)
                        if (profile instanceof IDrawerItem && profile.getIdentifier() == PROFILE_SETTING) {
                            int count = 100 + headerResult.getProfiles().size() + 1;
                            IProfile newProfile = new ProfileDrawerItem().withNameShown(true).withName("Batman" + count).withEmail("batman" + count + "@gmail.com").withIcon(R.drawable.profile5).withIdentifier(count);
                            if (headerResult.getProfiles() != null) {
                                //we know that there are 2 setting elements. set the new profile above them ;)
                                headerResult.addProfile(newProfile, headerResult.getProfiles().size() - 2);
                            } else {
                                headerResult.addProfiles(newProfile);
                            }
                        }

                        //false if you have not consumed the event and it should close the drawer
                        return false;
                    }
                })
```

**Comment by PetarCeho01** [comment]
Get it for the onProfileChanged(), is there any example that from the AccountHeaderBuilder () ProfileDrawerItem () is a activity called ? Because i'm stuck here : 
 i get it with the 


`    .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        //    if (drawerItem instanceof Nameable) {
                        Toast.makeText(CrossfadeDrawerLayoutActvitiy.this, ((Nameable) drawerItem).getName().getText(CrossfadeDrawerLayoutActvitiy.this), Toast.LENGTH_SHORT).show();
                        //   }
                        if (drawerItem != null) {


                            Intent intent = null;
                            if (drawerItem.getIdentifier() == 1) {
                                intent = new Intent(CrossfadeDrawerLayoutActvitiy.this, AddAccount.class);
                            } else if (drawerItem.getIdentifier() == 11) {
                                intent = new Intent(CrossfadeDrawerLayoutActvitiy.this, AddAccount.class);
                            }
                            if (intent != null) {
                                CrossfadeDrawerLayoutActvitiy.this.startActivity(intent);

                            }


                        }


                        //we do not consume the event and want the Drawer to continue with the event chain
                        return false;
                    }
                }


But still don't understand how to code that that from  ProfileSettingDrawerItem () after clicking is going to Activity.class ? 

Thank you for your effort Mike !

**Comment by mikepenz** [comment]
I am not sure why a sample for this is needed. Launching an activity is one of Android's basics. That's nothing I need to show in the lib. 

Just launch the activity you want to see depnding on the item which was clicked. Stackoverflow will help you how to launch an activity

**Comment by PetarCeho01** [comment]
I understand it has nothing to do, but how to launch and activity from 
`headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withCompactStyle(true)
                .withHeaderBackground(R.drawable.header)
                .addProfiles(
                        profile,
                        profile2,

                        //don't ask but google uses 14dp for the add account icon in gmail but 20dp for the normal icons (like manage account)
                     new ProfileSettingDrawerItem().withName("Add Account").withDescription("Add Account").withIcon(new IconicsDrawable(this, GoogleMaterial.Icon.gmd_plus).actionBar().paddingDp(5).colorRes(R.color.material_drawer_dark_primary_text)).withIdentifier(PROFILE_SETTING).withIdentifier(12),
                        new ProfileSettingDrawerItem().withName("Manage Account").withIcon(GoogleMaterial.Icon.gmd_settings).withIdentifier(11)

                )` 


From the `new ProfileSettingDrawerItem().withName("Manage Account").withIcon(GoogleMaterial.Icon.gmd_settings).withIdentifier(11)`  ?

I implemented the method  : 

` .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener()
                {

                   @Override
                   public boolean onProfileChanged(View view, IProfile profile, boolean current) {



                      return false;
                   }
                })`

but this appears to work with onProfileChanged.

**Comment by PetarCeho01** [comment]
i found another solution by using ExpandableDrawerItem() . Thanks for you answers !!

**Comment by shanu95** [comment]
hi PetarCeho01, can you please tell me how you fix the issue?
