### ISSUE TITLE
The first item is always selected, even after clicking other selectable items

### ISSUE THREAD

**Issue by ryannmahajan** [mikepenz/MaterialDrawer#1842]
A helper class returns the (non-static) DrawerBuilder object (by a static method), on which .build() is called. When I open a new activity by selecting an item, the first item is selected, but not the one I clicked. But I can't find the problem. Here's my code:

```
public static DrawerBuilder returnDrawerBuilder(final Activity activity) {

        return new DrawerBuilder()
                .withActivity(activity)
                .withActionBarDrawerToggle(false)
                .withTranslucentStatusBar(false)
                .withHeader(R.layout.material_drawer_header_logo)
                .withDrawerLayout(R.layout.drawer_layout)
                .withCloseOnClick(true)
              //  .withHeaderHeight()
                .addDrawerItems(
                        new SecondaryDrawerItem().withName(R.string.configurations),
                        new DividerDrawerItem(),
                        new SecondaryDrawerItem().withIcon(R.drawable.ic_settings_black).withName(R.string.title_activity_settings),
                        new SecondaryDrawerItem().withIcon(R.drawable.ic_like_black).withName(R.string.feedback).withSelectable(false),
                        new SecondaryDrawerItem().withIcon(R.drawable.ic_tutorial).withName(R.string.tutorial).withSelectable(false)
                      
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        switch (position) {
                            case 1 :
                                activity.startActivity(ListActivity.newIntent(activity));
                                return true;

                            case 2 :
                                return false; // DividerDrawer

                            case 3 :
                                activity.startActivity(SettingsActivity.newIntent(activity,false));
                                return true;

                            case 4 :
                                // Feedback
                               sendEmail();
                                return true;
                            case 5 :
                                // Tutorial
                                openTutorial(activity);
                                return true;

                            default:
                                return false;
                        }
                    }
                });
    }

    public static DrawerBuilder returnDrawerBuilder(final Activity activity, Toolbar toolbar) {
        return returnDrawerBuilder(activity).withToolbar(toolbar).withActionBarDrawerToggle(true).withTranslucentStatusBar(true);
    }
```

I also tried a variation in which I called .withSetSelected(activity instanceof SettingsActivity) while adding drawer items, but amazingly that didn't change the outcome one bit.

**Comment by mikepenz** [comment]
Your other items are not `withSelectable(false)` selectable.. so they will never be highlighted. 

Only calling `withSetSelected(..)` on the item after the drawer was created won't directly update. You have to notify the drawer about the updated item. (Basically as in a normal RV)


 https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

**Comment by ryannmahajan** [comment]
The third item _is_ selectable. I think my observation was incorrect and it is, in fact highlighted. I just can't see it because a new activity and consequently, a new drawer is created.

However, my second observation was on point. Calling `.withSetSelected(...)` does not highlight the items . I'm calling it while adding the drawer items, so before the drawer is created (Should've mentioned this before. My bad)

`.addDrawerItems(

                new SecondaryDrawerItem().withName(R.string.configurations).withSetSelected(activity instanceof ListActivity),
                  
                new DividerDrawerItem(),

                 new SecondaryDrawerItem().withIcon(R.drawable.ic_settings_black).withName(R.string.title_activity_settings).withSetSelected(activity instanceof SettingsActivity),

                 new SecondaryDrawerItem().withIcon(R.drawable.ic_like_black).withName(R.string.feedback).withSelectable(false),

                new SecondaryDrawerItem().withIcon(R.drawable.ic_tutorial).withName(R.string.tutorial).withSelectable(false)
                )`

**Comment by mikepenz** [comment]
@ryannmahajan that's correct just calling `withSetSelected()` does NOT highlight. in that case you should notify the `Drawer` about the updated item. 

But in general I would anyways say that you should use the provided methods from the drawer to set the selection, as this is the only way how it would handle the state upon configuration changes for example

**Comment by suarezu** [comment]
Only 1 profile is added to the header, and only 1 draweritem.withSelectable(false) is added to the drawer, but when the drawer shows, the profile in the drop-down is selected; the only 1 draweritem is selected, even withSetSelected(false) added. please help how to unselect them after created, and withSelectable(false) they should not be rendered as selected at any time, right?

**Comment by mikepenz** [comment]
`withSelectable(false)` will only prevent the user from selecting it. programmatically you can always select it. if you want to have no selection at all (which seems weird :D) you can do that by setting the selection to "-1"

**Comment by suarezu** [comment]
-1 works for DrawerItems, but how to clear selection of Profile drop-down?

No selection seems natural in my case, since each DrawerItem leads to some fragment, and if that fragment is already on top of the back stack, do nothing.

**Comment by mikepenz** [comment]
so you don't want profiles at all? So simply don't define profiles? 

What are you using the profiles for?

**Comment by suarezu** [comment]
I want only 1 profile, as detailed in comment of another issue, the profile can show who the authenticated user is, and way to logout

**Comment by mikepenz** [comment]
so you have 2 items in the profiles? the profile itself and the logout item?

**Comment by suarezu** [comment]
yes, exactly, thank you, as in other comment, this problem solved by false to .withSelectionListEnabled
