### ISSUE TITLE
ScrimInsetsRelativeLayout statusbar state

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/MaterialDrawer#1845]
Hi @mikepenz, I'm using ScrimInsetsRelativeLayout in my activity because I wanted to have a matt statusbar and this works great. Now I have the necessity to use a bottomsheet in the same activity, but due the fact that I'm using the ScrimInsetsRelativeLayout the bottomsheet layout goes under the statusbar and I don't want this thing to happen. Is there a way to "materialize" the statusbar when I open the bottomsheet and the make it behave as always when i collapse it?

Thank you in advance for your time

**Comment by mikepenz** [comment]
@EpsilonOrionis I guess you will have to apply padding or margin at the bottom of the `BottomSheet`. Other than this, you might be able to adjust the insets of the `ScrimInsetsRelativeLayout` when the BottomSheet is shown, but could be tricky

**Comment by EpsilonOrionis** [comment]
I'm doing it already. I'm setting a margin to the top of the layout, but the problem is that we have different screen sizes on Android...

**Comment by mikepenz** [comment]
But the margin of the NavigationBar can be retrieved programatically

```java
public static int getNavBarHeight(Context context) {
        Resources resources = context.getResources();
        int resourceId = resources.getIdentifier("navigation_bar_height", "dimen", "android");
        if (resourceId > 0) {
            return resources.getDimensionPixelSize(resourceId);
        }
        return 0;
    }
```

And you can also check if there is a `navBar`
```java
public static boolean hasNavBar(Context context) {
        Resources res = context.getResources();
        int resourceId = res.getIdentifier("config_showNavigationBar", "bool", "android");

        if (resourceId != 0) {
            return res.getBoolean(resourceId);
        } else { // fallback
            return !ViewConfiguration.get(context).hasPermanentMenuKey();
        }
    }
```

**Comment by EpsilonOrionis** [comment]
I'll try as soon as possible and I'll let you know, don't close this issue please

**Comment by mikepenz** [comment]
Haha @EpsilonOrionis normally I wait at least 2 weeks without an answer before closing issues :D But I'd re-open if new interaction happens ;)

**Comment by EpsilonOrionis** [comment]
You're professional 🥇

**Comment by EpsilonOrionis** [comment]
Hi @mikepenz, sorry if I'm late... I solved the problem. What I needed to get was the status bar height but your advice helped me to solve my specific problem. Here is the code: 

`public int getStatusBarHeight() {
        int result = 0;
        int resourceId = getResources().getIdentifier("status_bar_height", "dimen", "android");
        if (resourceId > 0) {
            result = getResources().getDimensionPixelSize(resourceId);
        }
        return result;
    }`

Thank you again @mikepenz 🥇

**Comment by mikepenz** [comment]
@EpsilonOrionis awesome :) thank you very much
