### ISSUE TITLE
Question :Facebook profile information in ProfileDrawerItem ();

### ISSUE THREAD

**Issue by PetarCeho01** [mikepenz/MaterialDrawer#1847]
Is there a way to implement user_name,user_email,user_picture into ProfileDrawerItem ?

```java
JSONObject response, profile_pic_data, profile_pic_url;
    TextView user_name, user_email;
    ImageView user_picture;
```
```xml
 <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"

        android:text="Android Studio"
        android:id="@+id/username"
        android:textAppearance="@style/TextAppearance.AppCompat.Body1"/>


    <TextView
        android:id="@+id/email"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="android.studio@android.com"/>

    <de.hdodenhof.circleimageview.CircleImageView
        android:id="@+id/profile_pic"
        android:layout_width="100dp"
        android:layout_height="49dp"
        android:src="@drawable/profile"/>
```

Is it possible to implement the TextView and the ImageView into the :

```java
final IProfile profile = new ProfileDrawerItem().withName("Petar Ceho").withEmail("petar_ceho@hotmail.com").withIcon(R.drawable.profile).withSelectable(true).withIdentifier(9);
```

Because .withEmail (String)?

Thanks ! 

`

**Comment by mikepenz** [comment]
@PetarCeho01 I do not understand. The ProfileDrawerItem provides already the methods to pass a e-mail and a name and an icon?!

**Comment by PetarCeho01** [comment]
Is there a link with methods ?  i tried to add ProfileDrawerItem.getName(user_name) it say ProfileDrawerItem cannot be applied to (android.widget.TextView).
Is it possible to pass TextView user_name into the ProfileDrawerItem.getName() ,and ImageView ?

**Comment by mikepenz** [comment]
Well as the project is open-source you can look here: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L84

You can set the name and e-mail

**Comment by mikepenz** [comment]
And no why would you pass views into an item?!

**Comment by PetarCeho01** [comment]
After the logged in,wanted that the fb_profile info is added to the AccountHeaderBuilder() and be displayed just like the second drawer header
https://raw.githubusercontent.com/mikepenz/MaterialDrawer/develop/DEV/github/screenshots2.jpg

**Comment by mikepenz** [comment]
I do not understand what the problem is. The Item allows you to define those values. The sample + the readme shows how to add items to the drawer. The AccountHeader has an add method to add profiles.

**Comment by PetarCeho01** [comment]
I tried 
`  final IProfile profile3 = new IProfile() {
            @Override
            public Object withName(String name) {
                return null;
            }

            @Override
            public StringHolder getName() {
                return null;
            }

            @Override
            public Object withEmail(String email) {
                return null;
            }

            @Override
            public StringHolder getEmail() {
                return null;
            }

            @Override
            public Object withIcon(Drawable icon) {
                return null;
            }

            @Override
            public Object withIcon(Bitmap bitmap) {
                return null;
            }

            @Override
            public Object withIcon(@DrawableRes int iconRes) {
                return null;
            }

            @Override
            public Object withIcon(String url) {
                return null;
            }

            @Override
            public Object withIcon(Uri uri) {
                return null;
            }

            @Override
            public Object withIcon(IIcon icon) {
                return null;
            }

            @Override
            public ImageHolder getIcon() {
                return null;
            }

            @Override
            public Object withSelectable(boolean selectable) {
                return null;
            }

            @Override
            public boolean isSelectable() {
                return false;
            }

            @Override
            public Object withIdentifier(long identifier) {
                return null;
            }

            @Override
            public long getIdentifier() {
                return 0;
            }
        }


But the main problem that thhe  user_mail is TextView  i cannot change the String to TextView, to get TextView instead of String. it doesn't allow me to @Override it  to TextView. I'm clearly missing the point which method should i use to implement TextView and ImageView to my profile3.




`

**Comment by PetarCeho01** [comment]
I'm trying to do this with ViewHolder 

`final IProfile profile3 = new IProfile() {


            public ViewHolder getViewHolder(View v) {
                return new ViewHolder(v);
            }


           class ViewHolder extends RecyclerView.ViewHolder {
                private View view;
                private ImageView profileIcon;
                private TextView name;
                private TextView email;

                private ViewHolder(View view) {
                    super(view);
                    this.view = view;
                    this.profileIcon = (ImageView) view.findViewById(R.id.material_drawer_profileIcon);
                    this.name = (TextView) view.findViewById(R.id.material_drawer_name);
                    this.email = (TextView) view.findViewById(R.id.material_drawer_email);
                }



I stuck  here,


What is the way to get 
final IProfile profile = new ProfileDrawerItem().withName("Petar Ceho").withEmail("").withIcon(R.drawable.profile).withSelectable(true).withIdentifier(9);




only with final IProfile profile = new ProfileDrawerItem().withName(TextView).withEmail(TextView).withIcon(ImageView);


Sorry for asking not defined questions ,i dont understand not full this myself.

**Comment by mikepenz** [comment]
@PetarCeho01 I still do not understand. You want to have a different layout for the `ProfileDrawerItem`? Why would you want this? The default already allows to set email and name. 

If you want something completely custom please read the FAQ: https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md it's besically the same for `ProfileDrawerItem's`
