### ISSUE TITLE
Clicking on a subItem of  an ExpandableDrawerItem causes the clousure of the Drawer

### ISSUE THREAD

**Issue by LorenzoZoia** [mikepenz/MaterialDrawer#1848]
I am encountering a strange problem. Despite I set .withCloseOnClick(false) when I click on an subItem of an ExpandableDrawerItem and I start a new activity, the entire Drawer get closed.

**Comment by mikepenz** [comment]
@LorenzoZoia you could consume the event in the click listener if it's a subitem

**Comment by LorenzoZoia** [comment]
Ok, how can I do that when I set the touch listener on the drawer ??

**Comment by mikepenz** [comment]
@LorenzoZoia don'T you have a DrawerItemClickListener to do something when the user clicks an item?

**Comment by LorenzoZoia** [comment]
Yes, I am using the OnDrawerItemClickListener to start a new activity when I click on the subItem

**Comment by LorenzoZoia** [comment]
This is my code:

PrimaryDrawerItem item1 = new PrimaryDrawerItem().withIdentifier(1).withName(R.string.drawer_item_food);
        item1.withTextColor(Color.WHITE);
        item1.withIcon(R.drawable.ic_food);
        PrimaryDrawerItem item2 = new PrimaryDrawerItem().withIdentifier(2).withName(R.string.drawer_item_follow);
        item2.withTextColor(Color.WHITE);
        item2.withIcon(R.drawable.ic_follow);
        PrimaryDrawerItem subItem1 = new PrimaryDrawerItem().withIdentifier(3).withName(R.string.drawer_item_spina).withLevel(2).withTextColor(Color.WHITE);
        subItem1.withIcon(R.drawable.ic_beer_tap);
        PrimaryDrawerItem subItem2 = new PrimaryDrawerItem().withIdentifier(4).withName(R.string.drawer_item_bottle).withLevel(2).withTextColor(Color.WHITE);
        subItem2.withIcon(R.drawable.ic_beerbottle);
        ExpandableDrawerItem item = new ExpandableDrawerItem().withName(R.string.drawer_item_beer).withTextColor(Color.WHITE).withSelectable(false).withSubItems(
                subItem1,
                subItem2
        ).withIcon(R.drawable.ic_beer);
        PrimaryDrawerItem item3 = new PrimaryDrawerItem().withIdentifier(5).withName(R.string.drawer_item_pub);
        item3.withTextColor(Color.WHITE);
        item3.withIcon(R.drawable.ic_pub);
        PrimaryDrawerItem item4 = new PrimaryDrawerItem().withIdentifier(6).withName(R.string.drawer_item_promo);
        item4.withTextColor(Color.WHITE);
        item4.withIcon(R.drawable.ic_promo);
        PrimaryDrawerItem item5 = new PrimaryDrawerItem().withIdentifier(7).withName(R.string.drawer_item_qr);
        item5.withTextColor(Color.WHITE);
        item5.withIcon(R.drawable.ic_qr);
        SecondaryDrawerItem item6 = new SecondaryDrawerItem().withIdentifier(8).withName(R.string.drawer_item_settings);
        item6.withTextColor(Color.WHITE);
        item6.withIcon(R.drawable.ic_settings);
        SecondaryDrawerItem item7 = new SecondaryDrawerItem().withIdentifier(9).withName(R.string.drawer_item_edit);
        item7.withTextColor(Color.WHITE);
        item7.withIcon(R.drawable.ic_edit);
        PrimaryDrawerItem item8 = new PrimaryDrawerItem().withIdentifier(10).withName(R.string.drawer_item_home);
        item8.withTextColor(Color.WHITE);
        item8.withIcon(R.drawable.ic_home);

        //Creation of the Drawer
        final Drawer result = new DrawerBuilder()
                .withActivity(fatherActivity)
                .withHeader(R.layout.menu_header)
                .withToolbar(toolbar)
                .withCloseOnClick(false)
                .withSliderBackgroundColor(fatherActivity.getResources().getColor(windowBackground))
                .addDrawerItems(
                        item8,
                        item,
                        item1,
                        item2,
                        item3,
                        item4,
                        item5,
                        new DividerDrawerItem(),
                        item6,
                        item7
                )
                .build();
        result.setSelection(-1);

        result.setOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
            @Override
            public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                if(drawerItem != null){
                    Intent intent=null;
                    if(drawerItem.getIdentifier() == 4 && !(fatherActivity instanceof BottleBeerListActivity)){
                        intent = new Intent(fatherActivity, BottleBeerListActivity.class);
                    }
                    else if(drawerItem.getIdentifier() == 10 && !(fatherActivity instanceof HomeActivity)){
                        intent = new Intent(fatherActivity, HomeActivity.class);
                    }

                    if(intent != null){
                        fatherActivity.startActivity(intent);
                        fatherActivity.overridePendingTransition(R.anim.slide_in_right,R.anim.slide_out_right);
                    }
                }
                return true;
            }
        });
        return result;

**Comment by mikepenz** [comment]
Setting an `ExpandableItem` `withSelectable(false)` will also prevent the closing, as shown in the `DrawerActivity` of the sample app: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L138
