### ISSUE TITLE
UI freezing when I use Fragments

### ISSUE THREAD

**Issue by regiskakashi** [mikepenz/MaterialDrawer#1849]
Hi. I'm sorry for my terrible English.

In my application I'm using fragments and accessing my api with retrofit in the withOnDrawerItemClickListener event.

When my task takes a while, the Drawer Navigation freezes and is only hidden 100% when my asynchronous task is finished.

Please, can anyone give any suggestions on how to do Drawer Navigation collapse 100% regardless of the tasks that it triggered to run?

Thanks in advance!

**Comment by mikepenz** [comment]
@regiskakashi the drawer provides 2 configuration options, you can postpone the click listener being fired after a specific duration. Or you can postpone the closing after a specific time. 

Basically that's unrelated to the library and will also happen if you only use the `DrawerLayout`, as replacing a fragment is a "expensive" operation. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1103
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1120

**Comment by regiskakashi** [comment]
Hello @mikepenz .

The solution "**.withDelayDrawerClickEvent(350)**" solved my problem. 

However, any chance of a "**.triggerClickEventAfterMenuCollapsed(true)**" function being implemented in the future? 

Congratulations for the lib and thanks a lot!

**Comment by mikepenz** [comment]
`triggerClickEventAfterMenuCollapsed` sorry there will be no such method as you can already control the delay. And the delay might be different on the stuff you do. so there is no general rule which value is correct
