### ISSUE TITLE
how to use withOnDrawerNavigationClick

### ISSUE THREAD

**Issue by TaherZaki** [mikepenz/MaterialDrawer#185]
i want  to know when  i use this function (withOnDrawerItemClickListener) to navigate throw my activities how i can do it   

and thnx man great work

**Comment by mikepenz** [comment]
@TaherZaki can you be a bit more specific. this is shown in the sample app

**Comment by ishell** [comment]
I also want to know.
Is this code right?
```
.withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener(){
                    @Override
                    public void onItemClick(AdapterView<?> adapterView, View view, int i, long l, IDrawerItem iDrawerItem) {
                        if (iDrawerItem != null) {
                            //Do some navigate Intent
                            }
                        }
                    }
                }
```

**Comment by mikepenz** [comment]
@TaherZaki @ishell you can navigate through your activities as you need it :)

You have many options. decide which item was clicked by identifier, by it's position...

How it's done with identifiers is shown here:
https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/SimpleHeaderDrawerActivity.java#L125

Please look at the sample code. as addition this sample activity also deactivates the selected state for the items which start an activity.
