### ISSUE TITLE
IconicsImageView background color issue in v5.9.1

### ISSUE THREAD

**Issue by alessandrotorres** [mikepenz/MaterialDrawer#1851]
Hi Mike,

I noticed an issue after upgrading from 5.9.0 to 5.9.1.

For IconicsImageView, in MaterialDrawer package, you can set background color with .setBackgroundColor(int color) in onCreate() but, if called runtime, e.g. onClickListener(), it seems to ignore it.

Rolling back to 5.9.0 all is ok.

Thanks,
Ale

**Comment by mikepenz** [comment]
Wrong project. The Android-Iconics is here: https://github.com/mikepenz/Android-Iconics

**Comment by alessandrotorres** [comment]
Hi Mike,

I know it.
I've opened here just because issue happened with only MaterialDrawer included in Gradle.

Thanks,
Ale

**Comment by mikepenz** [comment]
yeah I updated the internal Android-Iconics version ;). Please still open the issue on the correct project so I can keep the overview about the open source projects I manage

**Comment by alessandrotorres** [comment]
Thanks Mike :)

I'll open it immediately.

Have a nice day :)
Ale
