### ISSUE TITLE
Change Header Icon after set

### ISSUE THREAD

**Issue by carmas123** [mikepenz/MaterialDrawer#1853]
Hi Mike, I try to change the drawer header profile icon at runtime but without success result :(

I try to use
`headerDrawer.updateProfile(myNewProfile)`

I've a single profile active

**Comment by mikepenz** [comment]
@carmas123 make sure you call this from the ui thread.

**Comment by carmas123** [comment]
Yes into 
withOnAccountHeaderListener

**Comment by carmas123** [comment]
I want change the icon when the user touch the icon

**Comment by carmas123** [comment]
I solved rebuilding the header and setting drawer.setHeader(buildmyheader().view)
and after that apply myNewHeader.setDrawer(myDrawer)

**Comment by mikepenz** [comment]
Hmmm I am almost 100% sure that this should not be necessary. I'll have to try again in the sample

**Comment by carmas123** [comment]
Thanks

**Comment by mikepenz** [comment]
Just tested again. Changing the icon at a later time works.
