### ISSUE TITLE
How can I enable Drawer Toggle for MiniDrawer ?

### ISSUE THREAD

**Issue by amrfarid140** [mikepenz/MaterialDrawer#1854]
is there a way to have a drawer toggle which expands/collapses the miniDrawer ?

**Comment by AleSpero** [comment]
Of course, you can use the method `crossfade()` on you crossfader object which expands/collapses the drawer :)

**Comment by amrfarid140** [comment]
That's great. I think I wasn't clear. Do I need to add a drawer toggle manually and then link it to the crossfader when it is clicked.. or does the MiniDrawer Builder include some kind of way to generate this Drawer Toggle automatically. Same way as the Normal drawer automatically adds a drawer toggle. 

Thanks !

**Comment by AleSpero** [comment]
As far as i know you need to create a toggle and then manually link it to the crossfader as you said. In my app i created a `PrimaryDrawerItem` which handles the expand/collapse stuff. :)

**Comment by amrfarid140** [comment]
Thanks @AleSpero . I am aiming to replicate the Gmail app UI (Tablet version) so I need the normal Drawer toggle to expand and collapse the MiniDrawer.

**Comment by mikepenz** [comment]
@AleSpero thanks for answering.
@amrfarid140 as already corretly answered. The Mini + normal Drawer usecase does not use the DrawerLayout so it won't automatically use the ActionBarDrawerToggle, as it requires a DrawerLayout. there are some libs out there which do not have that requirement and basically show the same animation
