### ISSUE TITLE
support CharSequence in StringHolder and BaseDescribeableDrawerItem

### ISSUE THREAD

**Issue by brucexia** [mikepenz/MaterialDrawer#1858]
This is what I'm trying to achieve. This is not possible with current implementation. The bindViewHelper is applying a default statelist text color to the name view. We need to support charSequence so we can format it more flexibly

<img width="278" alt="screen shot 2017-05-16 at 2 05 35 pm" src="https://cloud.githubusercontent.com/assets/766623/26128317/e040385c-3a40-11e7-9ee9-3521ff891cd2.png">

**Comment by mikepenz** [comment]
@brucexia you want to have a `Spannable` passed in. Good idea. You might want to open a PR allowing this

**Comment by brucexia** [comment]
will do. thanks for quick reply

**Comment by mikepenz** [comment]
Will be adjusted in the materialize lib and then updated int he drawer
