### ISSUE TITLE
make drawer.updateName() only update name not the whole item

### ISSUE THREAD

**Issue by brucexia** [mikepenz/MaterialDrawer#1859]
I have a requirement to put in a timer in one of the menu item. This is causing blinking of the item since it basically re-renders the whole item. We need a way to update only the specific piece.

**Comment by mikepenz** [comment]
@brucexia if you want to only update a specific piece, I'd recommend you that you implement a custom drawerItem like you'd normally would do using the fastadapter. And then you just notify the drawer about the updated item + payload. 

as an alternative you can remove the animation while updating, so it won't flash

**Comment by brucexia** [comment]
@mikepenz thanks for your quick reply. Just as reference: this is done through DrawerBuilder.withItemAnimator(null)
