### ISSUE TITLE
Sticky footer item in Profile Drawer

### ISSUE THREAD

**Issue by vatsa92** [mikepenz/MaterialDrawer#1860]
Is there any option to add a sticky footer view (item) in Profile Drawer? - I mean the account switching drawer. If there is no such option, can you please provide me the parent layout of Account Drawer Layout(Profile Drawer Layout), I will add a custom view in it myself. 

Thanks in advance.

**Comment by mikepenz** [comment]
@vatsa92 the `Drawer` object already gives you the ability to access one of its views. 
there is another open issue requesting somethihng similar. --> Keep the sticky drawer items also in the profile selection .Is this similar to your needs?

**Comment by vatsa92** [comment]
@mikepenz I need to have a footer item that sticks in profile section screen. Sticky drawer item isn't what I want. To be clear, my requirement is something like this - I need to show a button at the bottom of profile section, that always stays there even when the accounts and settings items are scrolled. 

Is there any option already available for this? if not, can you please guide me how I can achieve this?

**Comment by mikepenz** [comment]
I sadly haven't had time yet to implement this. But there is another feature request exactly for that scenario: https://github.com/mikepenz/MaterialDrawer/issues/1819

I'll close that one and keep the other open as it is a duplicate then :)
