### ISSUE TITLE
Accountheader onclick

### ISSUE THREAD

**Issue by sidharthanil** [mikepenz/MaterialDrawer#1861]
Hi, I started using your library and its awesome by the way. I need some help regarding account header.

I want to navigate to a profile when user clicks on anywhere on the header not just the header image. Can you help me how to do that?

Also i want to provide an outline around the header image like below
![25 nav drawer](https://cloud.githubusercontent.com/assets/20595135/26199937/a5f2da6a-3be9-11e7-90a2-c2ee678e03bc.jpg)

**Comment by mikepenz** [comment]
@sidharthanil  there is no listener pre-defined for that. But you can get a reference to the `View` from the `Drawer` object, and set your own listener on whatever view you need to

**Comment by sidharthanil** [comment]
Thank you Mike. It really helped. And the option to add custom header solved my second problem as well.
