### ISSUE TITLE
Delay OnDrawerItemClickListener #620

### ISSUE THREAD

**Issue by sweetdream0729** [mikepenz/MaterialDrawer#1866]
Thanks for this support.
In my app, fragment loading takes a bit delays, so closing drawer has been taking hang, so not smooth.
Please help me with this issue.

**Comment by mikepenz** [comment]
@sweetdream0729 you can define whatever value for the delay of closing or event fireing you need.  nothing special needed

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1103

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1120
