### ISSUE TITLE
How can I change the item text color in the Account Header?

### ISSUE THREAD

**Issue by santafebound** [mikepenz/MaterialDrawer#1867]
For the secondary menu where you can switch between accounts, I can't seem to change the color of the menu items. They are always black. I can get the icon colors changed, but not the text itself.

```
headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withTranslucentStatusBar(true)
                .withHeaderBackground(R.color.black)
                .addProfiles(
                        profile,
                        new ProfileSettingDrawerItem().withName(getString(R.string.drawer_item_edit_profile)).withIcon(new IconicsDrawable(this, GoogleMaterial.Icon.gmd_edit).actionBar().paddingDp(5).colorRes(R.color.stroke)).withIdentifier(100000),
                        new ProfileSettingDrawerItem().withName(getString(R.string.drawer_item_logout)).withIcon(new IconicsDrawable(this, GoogleMaterial.Icon.gmd_exit_to_app).actionBar().paddingDp(5).colorRes(R.color.stroke)).withIdentifier(100001)

                )
```

Similarly the band surrounding the accounts themselves:

```
final IProfile<ProfileDrawerItem> profile;
        if (profilePicture.equalsIgnoreCase("R.drawable.ic_profile_pic_add")) {
            profile = new ProfileDrawerItem().withName(name).withEmail(username).withIcon(BitmapFactory.decodeResource(getResources(), R.drawable.ic_profile_pic_add)).withIdentifier(100);
        } else {
            profile = new ProfileDrawerItem().withName(name).withEmail(username).withIcon(profilePicture).withIdentifier(100);
        }
```

The background is always white.

**Comment by mikepenz** [comment]
@santafebound  so you want to change the color of the text of the `ProfileSettingDrawerItem`? There is no method to directly set it as these are correct as of the Material Design Guidelines. 

So you can either overwrite the colors set in the theme. Or you overwrite the colors used:
https://github.com/mikepenz/MaterialDrawer#custom-colors---colorsxml

Or you implement your own `CustomDrawerItem` allowing you to change the color during runtime or so

**Comment by AllanWang** [comment]
For others looking at this question, `ProfileSettingDrawerItem` contains `withTextColor`

**Comment by suarezu** [comment]
ProfileDrawerItem.withTextColor() has no effect, in the xml there is no declaration for header text color, am I wrong?

**Comment by mikepenz** [comment]
if you want to do something with the items which is not supported by default you can always implement your own custom drawer item.
