### ISSUE TITLE
Can i use items of list (Listview or RecyclerView) in This drawer?

### ISSUE THREAD

**Issue by alira1377** [mikepenz/MaterialDrawer#1868]
hello,thanks for this fully functional library.i want to use a list with 10 items in this drawer,i want to set this items with Adapter.is anyway to do this?

**Comment by franciscofranco** [comment]
This lib gives you all the functionality you need and does all the heavy lifting for you, why in the hell do you want to do that manually? Read the docs, it's explicit enough.

**Comment by mikepenz** [comment]
@franciscofranco thanks :).

**Comment by alira1377** [comment]
Excuse me please,i can't find the docs of this lib,Where can I find it?
i'm newbie,sorry.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer

**Comment by mikepenz** [comment]
there is also a sample app
https://github.com/mikepenz/MaterialDrawer/tree/develop/app/src/main

and you even an have javadoc
http://javadoc.io/doc/com.mikepenz/materialdrawer/5.9.1

there is a FAQ for some things
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md

**Comment by alira1377** [comment]
I can't find the class that is related to the list of items to set in drawer.what is the name of it class?
