### ISSUE TITLE
How can i reduce spacing below active profile name in account header ?

### ISSUE THREAD

**Issue by Rushabhs999** [mikepenz/MaterialDrawer#1869]
![img](https://cloud.githubusercontent.com/assets/21279433/26486352/649145b8-4218-11e7-9a28-cbd1dddcf98c.PNG)

I want to reduce space below Vivaan Panda text in account header

**Comment by mikepenz** [comment]
@Rushabhs999 that's not doable programatically as the chose positioning is as defined in the Material Design Guidelines. You can copy paste the header layout to your project: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml

and adjust the positions
