### ISSUE TITLE
What is the difference between PrimaryDrawerItem and SecondaryDrawerItem?

### ISSUE THREAD

**Issue by Imangazaliev** [mikepenz/MaterialDrawer#187]
Hello. What is the difference between PrimaryDrawerItem and SecondaryDrawerItem? Thank's

**Comment by mikepenz** [comment]
@Imangazaliev the item height and icon size is different. You can see the specific dimensions here:
https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/res/values/dimens.xml
