### ISSUE TITLE
"Default" Profile not staying selected after activity return.

### ISSUE THREAD

**Issue by TimVelo** [mikepenz/MaterialDrawer#1870]
First of all, love the drawer; nice work!
I'm having a strange problem with the account header and I'm not sure what's causing it, thought I'd reach out and see your thoughts.
- I have an abstract AppCompatActivity called DrawerActivity that builds the drawer and header onCreate.
- There is a call from Firebase that returns the main user's information with the user's "other accounts"
- Code sets the "activeProfile" using accountHeader.setActiveProfle(currentProfile, true)
- First load of application works fine, the correct profile (profile for Tim) is selected and displays properly.
- If I launch another activity (not abstracted from DrawerActivity) and then return (either instantly or after a few minutes) the account header has another profile selected (profile for Kayla). It always seems to be the last profile in the list of added profiles. 
- If I select manually another profile (profile for John) other than the primary, leave via activity launch, and then return, the profile stays as expected. 

I'm not sure what I'm doing wrong or if I'm abusing the framework too much :). I'll send a gist if you'd like.
Thanks in advance, and for all the great work on this library. Very sharp!

**Comment by mikepenz** [comment]
@TimVelo if you go to the other activity and come back where you displaying the account selection in that case? 

Have you checked which values get'S written out in the savedInstance? (and read in)?

it will only stick if you choose the profile by doing it via the UI?

**Comment by TimVelo** [comment]
- The new activity does not show the drawer at all (is not abstracted from drawerActivity), but it could be an activity that shows the drawer. Either way the problem occurs.

- I will check the saved instance state right now and report back.

- It will not stay, regardless of setting via the setActiveProfile or actually clicking on it for the original "default" profile, 

-- I found that a "recreate()" will actually work properly so the correct profile is always selected. Its only on resume.

**Comment by TimVelo** [comment]
@mikepenz It doesn't look like the drawer is saved in the saveInstanceState, and the onRestoreInstanceState is not fired (mostly due to the short period the other activity is opened.) I don't know exactly what I'm looking for in the bundle though.

It will stay on "other" profiles. If I select one other than the default profile, launch a new activity and then return, the correctly selected profile. If I select the "default profile" it will never stay on return.

**Comment by TimVelo** [comment]
@mikepenz : Here's the strange thing, the OnProfileChanged method calls a snack bar that tells me who's active. It always says the correct user is active, even though the header says otherwise, even on resume. I'll keep playing with it and see where I get. Thanks for your help.

       @Override
        public boolean onProfileChanged(View view, IProfile profile, boolean current) {
        if (profile instanceof ProfileDrawerItem && ((ProfileDrawerItem) profile).getTag() instanceof UUID) {
            if (accountHeader.getProfiles() != null) {
                UUID uuid = (UUID) ((ProfileDrawerItem) profile).getTag();
                ApplicationBase.setSchema(uuid);
                SnackBarProcessor.showSnackBar(DrawerActivity.this, "Switching to " + profile.getName());
                accountHeader.setActiveProfile(profile, false);
            }
        } else if (profile.getIdentifier() == ACCOUNT_ID) {
            startActivity(new Intent("review", null, DrawerActivity.this, AuthChooserActivity.class));
        } else if (profile.getIdentifier() == REQUEST_ACCESS) {
            startActivityForResult(new Intent("review", null, DrawerActivity.this, ManagePermissionsActivity.class), REQUEST_ACCESS);
        }
        return false;
    }

**Comment by mikepenz** [comment]
@TimVelo perhaps you could create a small demo app which shows the problem. So I can better debug into it and see what's going on. 

It's a bit hard with just the information to properly figure out what may be wrong

**Comment by TimVelo** [comment]
@mikepenz I built a simple app taking the majority of the code from my app and it's not happening now in the testApp. It's here, but I wouldn't bother as it doesn't occur here: https://github.com/TimVelo/DrawerApplication

I'll look through the entire thing again and see if something else is firing to "clear" the account that is selected. Sorry to waste your time if it's something in my app.

**Comment by TimVelo** [comment]
@mikepenz Here's what I've found. It looks like the switchProfiles procedure is getting called by firebase on the removal of the listeners / launching of the new activity even though the new activity doesn't extend the firebase auth abstract activity. So here's what happens:
- First activity (extended of abstract BaseAuthenticationActivity) launches with the correct account.
- Start new activity (extended of abstract AppCompatActivity)
- OnCreate called in new activity.
- Firebase fires onAuthenticationChange.
- Causes the authentication handler to fire and get user, setting up header
- Header setup calls setProfiles. 
- setProfile calls switchProfiles thinks that mCurrentProfile is the incorrect account. The response of the switchable accounts is ordered by the JavaEE response from my server response in SQL.

I'm blaming firebase for right now. I'm rebuilding the authentication provider implementation to improve the flow and reduce possible duplicate callbacks that would fire after the oncreate on the new activity. Thanks for your help, I'll update this tonight once I find the actual problem and getting a working example.

**Comment by mikepenz** [comment]
@TimVelo sorry that you have to spend so much time hunting that bug down. But I am glad that it sounds like you are getting closer and closer :)

**Comment by TimVelo** [comment]
@mikepenz So it TOTALLY was Firebase. Here's the problem for anyone finding this:
- I had followed the Firebase Auth tutorial that showed to register the OnAuthenticationChangeListener during OnStart and release during OnStop.
- In my OnAuthenticationChangeListener I had a call to my own remote server API for user interaction. The result of this API would update the account header. 
- The registered activity's registration causes OnAuthenticationChangeListener to fire during OnPause of the original activity.

My solutiuon: I used the Firebase-UI library to handle the firebase account selection options: https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md

I removed the listener from the activity and only had it fire during OnCreate of that activity only. This prevents the half-loading, random fire of the auth-chain that was messing everything up. This is described in the link above. Here's the onCreate that handles the firebase user checking. @mikepenz Thanks for your help, I think it's safe to close this now (thanks firebase...).  I'll create a demo if anyone thinks it'll help??? 
        
         @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (FirebaseAuth.getInstance().getCurrentUser() == null)
            needsLogin();
        else
            Firebase.getCurrentInstance()
                    .getCurrentUser()
                    .getToken(true)
                    .addOnSuccessListener(new OnSuccessListener<GetTokenResult>() {
                        @Override
                        public void onSuccess(GetTokenResult getTokenResult) {
                            confirmFirebaseAisUser("Null", getTokenResult.getToken());
                        }
                    })
                    .addOnFailureListener(new OnFailureListener() {
                        @Override
                        public void onFailure(@NonNull Exception e) {
                            onAuthenticationError(e);
                        }
                    });
    }

**Comment by mikepenz** [comment]
Awesome. Thank you very much. 

Sure. If you want to open or add a demo activity to the sample, open a PR :)

**Comment by TimVelo** [comment]
@mikepenz I think I may do that here soon as I get over the initial build stage of my current project. After the rebuild, moved on to other things, but noticed that only as certain users would the issue happen. 

Is there a limit on the number of accounts that I can put into the account header? I'm getting the same issue, only when my account has more than 3 accounts to select from. Firebase was causing the problem at first because it was firing after the drawer was gone (possibly creating multiple "accounts" in error). But now there is no Firebase event fire on that activity, so I started playing. Noticed that if my account had 3 or less "switchable" accounts, the problem wouldn't happen. as soon as I add additional "switchable accounts", the problem comes back.
