### ISSUE TITLE
Changing Gravity of elements in Header

### ISSUE THREAD

**Issue by bzkdjc** [mikepenz/MaterialDrawer#1871]
Shouldn't it be possible to choose the position of icon, name and e-mail in header in a way like shown on this example: 
![unnamed1](https://cloud.githubusercontent.com/assets/13347655/26521950/073db0ea-42e5-11e7-8a6c-1e70b1bbdaf5.png)

**Comment by mikepenz** [comment]
@bzkdjc no as this is not in the MaterialDesignGuidelines. If you want to use a different layout for the header you can do this by overwriting the default.
