### ISSUE TITLE
Something wrong with 5.9.2

### ISSUE THREAD

**Issue by rodgarcialima** [mikepenz/MaterialDrawer#1872]
I think something is wrong with 5.9.2.

`drawerItem.getIdentifier()` is not exposed anymore or does not exists.

Build result:
![image](https://cloud.githubusercontent.com/assets/1371488/26524844/f1eae4ea-4318-11e7-94de-e941b4223a42.png)

5.9.1 is OK

**Comment by mikepenz** [comment]
@rodgarcialima you changed something else? Seems like the sub dependency is not resolved. 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/build.gradle#L50

**Comment by mikepenz** [comment]
I forgot to release on maven central, after I did it should be fine. Until then just add the sub dependencies too
