### ISSUE TITLE
Freeze drawer force open

### ISSUE THREAD

**Issue by pdapnz** [mikepenz/MaterialDrawer#1874]
Hi, Mike!
Is any possibility to freeze drawer in open state? I need set this state programmatically in code for some reason. 
The gamburger button and swipe gestures must not close drawer in this state, but all internal drawer clicks must triggered.

**Comment by mikepenz** [comment]
@pdapnz well you can disable via the listener that the drawer is closed via a item click (just consume the event by returning true) and you can set the drawer in the locked state using the `DrawerLayout` api. 
https://developer.android.com/reference/android/support/v4/widget/DrawerLayout.html#setDrawerLockMode(int, android.view.View)

And the hamburger icon shouldn't be visible anyways as the drawer should go over it.

**Comment by pdapnz** [comment]
Thanks, Mike!
This is exactly what I search for.
For whose who will do something like this I leave some code here:

Set/check force open Drawer state (LOCK_MODE_LOCKED_OPEN):

```
    public void setForceOpen(boolean isForceOpen) {
        if (isForceOpen) {
            mDrawer.openDrawer();
            mDrawer.getDrawerLayout().setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_OPEN, Gravity.LEFT);
        } else {
            mDrawer.getDrawerLayout().setDrawerLockMode(DrawerLayout.LOCK_MODE_UNLOCKED, Gravity.LEFT);
        }
    }

    public boolean isForceOpen() {
        return mDrawer.getDrawerLayout().getDrawerLockMode(Gravity.LEFT) != DrawerLayout.LOCK_MODE_UNLOCKED;
    }
```
And inside items click listeners

```
        mDrawer.addStickyFooterItem(new PrimaryDrawerItem()
                .withName(R.string.tech_support)
                .withSelectable(false)
                .withOnDrawerItemClickListener((view, position, drawerItem) -> {
                    if (mListener != null) mListener.onSupportClicked();
                    return isForceOpen();
                })
```



> And the hamburger icon shouldn't be visible anyways as the drawer should go over it.

Exactly so! No any action required!
