### ISSUE TITLE
CheckBoxDrawerItem support

### ISSUE THREAD

**Issue by jahirfiquitiva** [mikepenz/MaterialDrawer#1875]
Hi Mike

I was wondering if you could provide a CheckBoxDrawerItem in the library. There's already one with a switch, and one with a toggle, so this could be a nice addition, so we can have something like this at the end:

![screener_1496086272042](https://cloud.githubusercontent.com/assets/10360816/26560649/fe296f36-447d-11e7-9993-0fb760ebf480.png)
![screener_1496086282272](https://cloud.githubusercontent.com/assets/10360816/26560651/0132196c-447e-11e7-91e1-a7fe6d7f7d03.png)

**_Screenshots from Google I/O 17 app_**

**Comment by mikepenz** [comment]
@jahirfiquitiva you can build as many custom drawerItems as you need :) The drawer's interface allows you to do this. 

Basically look at the source of the `Toggle` or `Switch` drawerItem and replace it with the checkbox and the "tag" like style on for the `TextView` 

That's kinda easy. 

It's basically the whole idea behind the MaterialDrawer about being open and flexible, and allowing the dev to do whatever he wants to do

**Comment by jahirfiquitiva** [comment]
Thanks Mike. Was just giving the idea. I will create my own item then 😅

**Comment by mikepenz** [comment]
Awesome :) You can definitely add it to the sample app's source or to the FAQ just in case if someone wants it :)
