### ISSUE TITLE
How to hide icon in AccountHeader? How to prevent spinner if I have only one ProfileDrawerItem?

### ISSUE THREAD

**Issue by dinalt2006** [mikepenz/MaterialDrawer#1877]
I need only user name in ProfileDrawerItem in AccountHeader, like
new ProfileDrawerItem().withName(appsettings.getString("UserName", getString(R.string.empty)))
But I got default icon anyway! Can I prevent this?

**Comment by mikepenz** [comment]
The profile items will by default show a placeholder icon. You can change that one using the `DrawerImageLoader`

https://github.com/mikepenz/MaterialDrawer#load-images-via-url
