### ISSUE TITLE
Add account and Manage account not showing

### ISSUE THREAD

**Issue by fgagneten** [mikepenz/MaterialDrawer#1879]
I have to show "Manage account" and "Add account" when the user click on dropdownlist.
I thought this two items show by default. 

I couldn't find example related with those items.

May be is up to me. In that case I need to know how to add those items.

Thanks!

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L72
