### ISSUE TITLE
Glide PrimaryDrawerItem icon?

### ISSUE THREAD

**Issue by amanzan** [mikepenz/MaterialDrawer#1880]
I've seen is possible to use Glide for the ProfileItem, but is it possible for a PrimaryDrawerItem?

**Comment by mikepenz** [comment]
@amanzan no. The normal drawerItems only allow icons. 

The sample contains a Custom primaryDrawerItem allowing this:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomUrlPrimaryDrawerItem.java
