### ISSUE TITLE
[QUESTION] Add profile after drawer created 

### ISSUE THREAD

**Issue by fgagneten** [mikepenz/MaterialDrawer#1883]
Hey, I created a MaterialDrawer and everything works fine. What I have to do now, add new profile to my drawer. 

The problem is that I've already had my drawer. in the README only show how create a drawer with profile, but I need add profiles dynamically.

I think that is possible, but I don't know how. 
Thanks for helping!

**Comment by mikepenz** [comment]
@fgagneten after building you get an `AccountHeader` object and a `Drawer` object. You can use those to update and add items. 

It's very similar to the API of the Drawer
https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

**Comment by fgagneten** [comment]
Ok, but the drawer never show me a new profiler, after:

    ProfileDrawerItem newProfile= new ProfileDrawerItem()
        .withName("Name")
        .withEmail("Email")
        .withIdentifier(40222345)
        .withIcon(getResources().getDrawable(R.drawable.icondefault));
    headerResult.addProfile(newProfile,  headerResult.getProfiles().size() - 2);

        // Update profile
        headerResult.updateProfile(newProfile);`

**Comment by mikepenz** [comment]
you are doing this on the main thread? 
the `updateProfile` is not required

**Comment by fgagneten** [comment]
Yes, I removed updateProfile but still not working. 

First, I created my drawer and header without add account and mange accout, just with accountheader.


     headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.background_navbar)
                .build();

        ItemsDrawer menuItems = new ItemsDrawer();
        menuDrawer = new DrawerBuilder()
                .withToolbar(toolbar)
                .withActivity(this)
                .withSavedInstance(savedInstanceState)
                .withAccountHeader(headerResult)
                .withCloseOnClick(true)
                .withDrawerItems(listItems
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        ...
                        return false;
                       }
                })
                .build();


After that, when the user logged in the following function start:
     
    public void updateHeader(){
        headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.background_navbar)
                .addProfiles(
                        new ProfileSettingDrawerItem().withName("Add Account")
                              .withIcon(new IconicsDrawable(this, GoogleMaterial.Icon.gmd_add)
                              .actionBar().paddingDp(5)
                              .colorRes(R.color.material_drawer_primary_text))
                              .withIdentifier(R.id.addAccount),
                        new ProfileSettingDrawerItem().withName(R.string.mangeAccount)
                              .withIcon(GoogleMaterial.Icon.gmd_delete)
                              .withIdentifier(R.id.manageAccount)
                )
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean current) {
                        //sample usage of the onProfileChanged listener
                        //if the clicked item has the identifier 1 add a new profile ;)
                        if (profile instanceof IDrawerItem && profile.getIdentifier() == R.id.addAccount) {
                            Intent mainIntent = new Intent().setClass(
                                    BaseActionBar.this, LoginActivity.class);
                            mainIntent.putExtra("addAccount", true);
                            startActivityForResult(mainIntent, ADD_ACCOUNT_REQUEST);
                        }
                        return false;
                    }
                })
                .build();
        // Add new profile from the user logged in
           addNewProfile();
       }


    private void addNewProfile(){
        ProfileDrawerItem newProfile= new ProfileDrawerItem()
        .withName("Name")
        .withEmail("Email")
        .withIdentifier(40222345)
        .withIcon(getResources().getDrawable(R.drawable.icondefault));
        headerResult.addProfile(newProfile,  headerResult.getProfiles().size() - 2);
    }

**Comment by mikepenz** [comment]
@fgagneten you should not build the header new. use the `headerResult` from the initial drawer creation.

**Comment by arpitjindal97** [comment]
@fgagneten did you manage to solve your problem? I am also stuck in same situation and Author doesn't seems to understand the question
