### ISSUE TITLE
Set multiple profile image

### ISSUE THREAD

**Issue by Rushabhs999** [mikepenz/MaterialDrawer#1884]
1 ) How can i set multiple profile image using glide ? 
Currently as per your tutorial i am able to set image using glide,but when i create multiple profile same image is set for all the profile.

![drawer](https://cloud.githubusercontent.com/assets/21279433/26722391/61365ada-47ad-11e7-950c-c6932c1df9ad.PNG)

2) I am creating another activity to change profile picture. When i come back to Main Activity the **_class Application controller extends Application_**  , i cannot see the image updated in drawer.

![student profile](https://cloud.githubusercontent.com/assets/21279433/26722451/9f7e1102-47ad-11e7-8b7f-9a9656bfb557.PNG)

**Comment by mikepenz** [comment]
@Rushabhs999 seems like you set the same url to all those profiles. 

The sample application shows everything... https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L52

if the image is changed you have to notify the drawer that the image was changed, by telling it that the profile now has a different url.
