### ISSUE TITLE
How I can make padding among items

### ISSUE THREAD

**Issue by trinhvanminh2009** [mikepenz/MaterialDrawer#1885]
I want to margin top or padding among items ? How I can do that ?

**Comment by mikepenz** [comment]
@trinhvanminh2009 if you want to have items which do not follow the `Material Design Guidelines` you have to follow the `CustomDrawerItem` section.
 https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md

**Comment by trinhvanminh2009** [comment]
Thank you so much ! I got it .
