### ISSUE TITLE
how to change text size or custom layout of PrimaryDrawerItem ?

### ISSUE THREAD

**Issue by derohimat** [mikepenz/MaterialDrawer#1887]
I'll try with SpannableStringBuild but not work.

**Comment by mikepenz** [comment]
@derohimat if you want a custom drawerItem then you can create your own `CustomDrawerItem`
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md

**Comment by derohimat** [comment]
@mikepenz thank you. Solved with this 

https://github.com/mikepenz/MaterialDrawer/issues/1308
