### ISSUE TITLE
Change color icon programatically after drawer was created 

### ISSUE THREAD

**Issue by fgagneten** [mikepenz/MaterialDrawer#1889]
How can I change icon color  programatically after drawer was created?
I'm trying something like this

`//1234 is the identifier`
`menuDrawer.getDrawerItem(1234)`.setIconColor(R.color.blue):

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDrawerItem.java#L144 you set the iconColor and then you notify the drawer about the udpate. 
https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer
