### ISSUE TITLE
descriptions to drawer items

### ISSUE THREAD

**Issue by Remie-l** [mikepenz/MaterialDrawer#189]
Can you implement descriptions to SecondaryDrawerItem, please?
And really need to separate text and description styles (color and size, or though just color).

**Comment by Remie-l** [comment]
@mikepenz is there a function to add custom DrawerItems?

**Comment by mikepenz** [comment]
@Remie-l you just need to implement it

create a new class implementing the IDrawerItem interface and you can simply user it as any other drawer item. See at any of the already available drawerItems

**Comment by Remie-l** [comment]
ok, thanks again
