### ISSUE TITLE
Setting alpha not working

### ISSUE THREAD

**Issue by jtv7** [mikepenz/MaterialDrawer#1892]
There is an issue with either MaterialDrawer or IconicsDrawable.  After upgrading to 5.9.2, setting the alpha value doesn't seem to work. 

```
IconicsDrawable icon = new IconicsDrawable(this)
                    .icon(faw_icon)
                    .color(color)
                    .alpha(20)
                    .sizeDp(40);
```
This code works perfectly on 5.9.1, but doesn't on 5.9.2.

**Comment by mikepenz** [comment]
@jtv7 can you please try to set a color which already contains the alpha information? (I might have an idea what could cause this)

**Comment by jtv7** [comment]
@mikepenz Yes, I can confirm setting a color with alpha info (#80FF0000) works.

**Comment by mikepenz** [comment]
@jtv7 ok great. then I think I know where to fix. you can for the time being use the alpha via the color

**Comment by mikepenz** [comment]
v2.8.6 of the Android-Iconics library fixes this issue
