### ISSUE TITLE
May be a silly question - Mini Drawer

### ISSUE THREAD

**Issue by trialsNow** [mikepenz/MaterialDrawer#1895]
Here is my code
```java
 .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        if (drawerItem instanceof Nameable && position==1) {
                            String title = ((Nameable) drawerItem).getName().getText(MiniDrawerActivity.this);
                            getSupportActionBar().setTitle(title);
                            Intent intent = new Intent(getApplicationContext(), AuthenticatorsListActivity.class);
                            startActivity(intent);
                        }
                        return false;
                    }
                })
                .withGenerateMiniDrawer(true)
                .withSavedInstance(savedInstanceState)
``` 

This opens the new activate but it doesn't show the mini drawer. What should I do to retain that drawer in the new activity. I don't want a back button to go back to the menu.
Sorry I am completely new, so excuse my ignorance.

**Comment by mikepenz** [comment]
@trialsNow normally a `NavigationDrawer` is used if you have one root activity and then many sub-fragments. In your case you have multiple activities, which means you have to set-up the `Drawer` in each activity, as it wouldn't be able to do that automatically. 

Many people achieved this by having some kind of BaseActivity and initialising the drawer there, so the code is not duplicated. But that's more related to the structure of your project, and not really an issue related to the `MaterialDrawer`
