### ISSUE TITLE
How to import your library

### ISSUE THREAD

**Issue by iplusMario** [mikepenz/MaterialDrawer#1897]
I have a question regarding how to import your library to my project.
I downloaded zip from git hub. Copyed library folder to my projects lib folder then I clicked 
File -> new -> import modul -> Selected library folder and i am geting 
Error:(2, 0) Plugin with id 'com.novoda.bintray-release' not found.

**Comment by mikepenz** [comment]
Please follow the instructions found here: 
https://github.com/mikepenz/MaterialDrawer#1-provide-the-gradle-dependency

if you want to directly include the source you will have to modify the gradle scripts to adjust it to your project. It depends on your setup, and I can't give support for this, as it should be rather trivial

**Comment by mikepenz** [comment]
P.S. it can't find that plugin because you have not defined it in your root... https://github.com/mikepenz/MaterialDrawer/blob/develop/build.gradle#L17

**Comment by iplusMario** [comment]
Yea I found it. Ty anyway.
