### ISSUE TITLE
Selected gets unselected on Expand and Collapse of parent ExpandableBadgeDrawerItem

### ISSUE THREAD

**Issue by tajchert** [mikepenz/MaterialDrawer#1899]
Any selected SecondaryDrawerItem is not marked selected after open&close of parent ExpandableBadgeDrawerItem - with even setSelactable false, so selected item should remain the same.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L880 set this to false

**Comment by tajchert** [comment]
This! Thank you!
