### ISSUE TITLE
PrimaryDrawerItem with icon

### ISSUE THREAD

**Issue by josalvdel1** [mikepenz/MaterialDrawer#19]
If an icon is setted as following lines:

PrimaryDrawerItem().withName(R.string.drawer_item_find_friends).withIcon(getResources().getDrawable(R.drawable.image))

the project doesn't compile.

Error:(55, 92) error: cannot access IIcon
class file for com.mikepenz.iconics.typeface.IIcon not found

EDIT**
I forgot the "transitive" property in build.gradle. Sorry about that.

**Comment by mikepenz** [comment]
@josalvdel1 the IIcon drawable is a class from the Android-Iconics library to provide a simple and easy feature to include icons. 

great that you've found the solution already ;)

**Comment by aldefy** [comment]
Can u help : 
Error:(42, 13) Failed to resolve: com.mikepenz.materialdrawer:library:1.0.0

I cant even find the library via maven , instead i used aar downloaded to libs folder.. up until i used withICon

**Comment by mikepenz** [comment]
@aldefy not sure why you can't find the library at maven. Here it is:
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.mikepenz.materialdrawer%22

Do you have a wrong setup of your `build.gradle`?

do you refer to `mavenCentral()` within the `build.gradle` or just to `jCenter`? probably jCenter hasn't synced the lib yet.

**Comment by aldefy** [comment]
This is my build.gradle 

apply plugin: 'com.android.application'
repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}
android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        applicationId "package_name"
        minSdkVersion 14
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true

        }
    }
}

dependencies {
    compile files('libs/butterknife-6.0.0.jar')
   
 
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.google.android.gms:play-services:6.5.87'
 
    compile 'com.squareup.picasso:picasso:2.4.0'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.android.support:recyclerview-v7:21.0.+'
    compile 'com.android.support:cardview-v7:21.0.+'
    compile 'com.mikepenz.materialdrawer:library:1.0.0:aar'
}

**Comment by aldefy** [comment]
Can u tell me the maven url that i can in gradle file

**Comment by aldefy** [comment]
I have Fixed it , i rechecked build.gradle and also the offline mode , unticked it , its working fine , thank you

**Comment by mikepenz** [comment]
@aldefy ok great.
