### ISSUE TITLE
What is the best way to let every activities have AccountSwitcher.

### ISSUE THREAD

**Issue by ishell** [mikepenz/MaterialDrawer#190]
I'm an android newbie, and thank you to create this awesome lib.
Now I create a AccountSwitcher on `MainActivity` ,I want to use this AccountSwitcher to all my other activities, what is the best way to organize my code.

**Comment by raghunandankavi2010** [comment]
Look at the google io schedule code especially BaseActivity. I assume you want the NavigationDrawer in all activities. You could create a BaseActivity following the io schedule app and then make all your activities extend BaseActivity. You could use the mikepenz material library apply the same concept as in google io schedule app @ https://github.com/google/iosched/blob/master/android/src/main/java/com/google/samples/apps/iosched/ui/BaseActivity.java

**Comment by ishell** [comment]
@raghunandankavi2010 thank you.

**Comment by ishell** [comment]
@raghunandankavi2010 @mikepenz Sorry, the Google's code is too complicated , and I don't know how to schedule the code. I try a to create a BaseActivity and let some activity extend it , the app which i build will crash.Can you show some simple sample code? Thx.

**Comment by raghunandankavi2010** [comment]
Before getting to use this library i acutally used the code in Google IO schedule app.  Its not hard to get things going. Yes its time consuming cause you need to customize it in a way you want. It took me a few hours. But this library is awesome.
