### ISSUE TITLE
Shared element transitions for MiniDrawer and Crossfader

### ISSUE THREAD

**Issue by percula** [mikepenz/MaterialDrawer#1900]
The Gmail app uses shared element transitions so that icons that appear in both the MiniDrawer and full-size Drawer translate between the views. Is it possible to implement that with MaterialDrawer? Here's a [tutorial](https://medium.com/@bherbst/fragment-transitions-with-shared-elements-7c7d71d31cbb) with implementation details.

**Comment by mikepenz** [comment]
@percula I have not planned to do so, if you want to open a PR with it I am open to get it possibly merged. 

Thanks
