### ISSUE TITLE
Incorrect icon colors on API < 21

### ISSUE THREAD

**Issue by rubengees** [mikepenz/MaterialDrawer#1901]
With the current version `5.9.2`, the icons of `DrawerItems` do not have the correct color on API < 21:

| API 21 | API 19 |
| --------- | --------- |
| ![api21](https://user-images.githubusercontent.com/8021265/27014887-dcd71944-4f01-11e7-98bd-3fc3a46c4bf5.png) | ![api19](https://user-images.githubusercontent.com/8021265/27014879-c8c4875c-4f01-11e7-8133-0c3efc1f6eff.png) |

I do not know since which version this is a thing, I also tried `5.9.0` with the same results.

This is one of my items:  

```kotlin
PrimaryDrawerItem()
    .withName(R.string.section_news)
    .withIconTintingEnabled(true)
    .withIcon(CommunityMaterial.Icon.cmd_newspaper)
    .withSelectedTextColorRes(R.color.colorAccent)
    .withSelectedIconColorRes(R.color.colorAccent)
    .withIdentifier(someId)
```

Strangely, `ProfileSettingsDrawerItems` work fine (API 19):

![login](https://user-images.githubusercontent.com/8021265/27014899-265c6c18-4f02-11e7-983f-94927860572b.png)

```kotlin
ProfileSettingDrawerItem()
    .withName(R.string.section_login)
    .withIcon(CommunityMaterial.Icon.cmd_account_key)
    .withIconTinted(true)
    .withIdentifier(someId)
```

**Edit:** I just updated to Iconics `2.8.6`, which also introduces this problem on API 21 if `withIconTintingEnabled` is set to true (First has it enabled, second has not):

![](https://user-images.githubusercontent.com/8021265/27015072-fd205c7a-4f05-11e7-9aec-48c9aa5fe6c2.png)

I have tested on a variety of devices and emulators.  
Thanks in advance for your help!

**Comment by rubengees** [comment]
A very weird thing I just noticed is, that if you scroll up and down in a long list of items, those which were not visible are correctly colored when becoming visible again.

![bildschirmfoto von 2017-06-12 00-11-33](https://user-images.githubusercontent.com/8021265/27015012-4ea0b204-4f04-11e7-8a2b-0ca0a3cac331.png)

**Comment by mikepenz** [comment]
@rubengees please update to the latest Android-Iconics library: https://github.com/mikepenz/Android-Iconics/releases/tag/v2.8.6

**Comment by rubengees** [comment]
> Edit: I just updated to Iconics 2.8.6, which also introduces this problem on API 21 if withIconTintingEnabled is set to true 

I tried that but it sadly didn't work. To clarify: With the new `Iconics` version the issue is still present on APIs < 21, but now also on >= 21 when `withIconTintingEnabled` is set to true.

**Comment by mikepenz** [comment]
@rubengees you made sure to exclude the old version of the iconics?

**Comment by rubengees** [comment]
`gradle app:dependencies` shows:

```
+--- com.mikepenz:materialdrawer:5.9.2
|    +--- com.android.support:appcompat-v7:25.3.1 -> 26.0.0-beta2 (*)
|    +--- com.android.support:recyclerview-v7:25.3.1 -> 26.0.0-beta2 (*)
|    +--- com.android.support:support-annotations:25.3.1 -> 26.0.0-beta2
|    +--- com.android.support:design:25.3.1 -> 26.0.0-beta2 (*)
|    +--- com.mikepenz:materialize:1.0.2
|    +--- com.mikepenz:iconics-core:2.8.5 -> 2.8.6
|    \--- com.mikepenz:fastadapter:2.5.3
```

**Comment by marbat87** [comment]
@mikepenz  I confirm the issue in my case too.
I updated iconics version to 2.8.6 but nothing changes

Regards

**Comment by rubengees** [comment]
Works perfectly, thank you! :+1:
