### ISSUE TITLE
withSelectedTextColor not working for PrimaryDrawerItem

### ISSUE THREAD

**Issue by amanzan** [mikepenz/MaterialDrawer#1902]
I'm trying to change the color when item is selected for it's not changing for some reason. This is the way I create items:
`final PrimaryDrawerItem drawerItem = new PrimaryDrawerItem().withIdentifier(i)
                    .withTextColor(Color.BLACK)
                    .withSelectedTextColor(Color.BLACK);`

textColor is black, but selectedTextColor remains white. How can I change that color? 
Also, is there any way to change/remove the background color for selected items?

![screenshot_20170613-121203](https://user-images.githubusercontent.com/3911627/27077932-0b4646e8-5032-11e7-9740-4aa6ff0bbc5e.png)

**Comment by mikepenz** [comment]
@amanzan if you want to change the overall appearance of a default drawerItem you will have to look into writing your own `CustomDrawerItem` 
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md

Regarding the selected text color. I'll have a look why it didn't work for your case

**Comment by whirlwind-studios** [comment]
Hello,
unfortunately, I'm having a similar issue, but in my case, there's no way to change the color of icons of any DrawerItem (Tried everything with xml colors and programmatically on PrimaryDrawerItem, and withIconColor on SecondaryDrawerItem, so I assume, its not working there either)
For me, it isn't a big issue, but it would be great, if you could dig into that problem (I used ordinary .png resources for reproducing) and maybe fix it
Have a nice day

**Comment by whirlwind-studios** [comment]
I was stupid, sorry. Just found that nice `withIconTintingEnabled` method :D

**Comment by mikepenz** [comment]
@whirlwind-studios great :) thanks for reporting back
