### ISSUE TITLE
StickyFooter Item at bottom

### ISSUE THREAD

**Issue by ivanstojkovicapps** [mikepenz/MaterialDrawer#1903]
Hi,

is there a way to put the PrimaryDrawerItem that is in sticky Footer, at the bottom of Sticky Footer.

Currently looks like in screenshot, and i would like to have thin footer (same height as drawer item) or just to position DrawerItem at bottom of the footer).

![sticky_fotter](https://user-images.githubusercontent.com/8529804/27083647-8558587e-5049-11e7-8b02-0d18128e740f.png)

**Comment by mikepenz** [comment]
can you please check out the `AdvancedDrawerActivity` of the sample application, and look how it looks there? Is it on the bottom or does it also have the space?

**Comment by ivanstojkovicapps** [comment]
Hi, if i put two Items it looks great, but the height seams to be the same. Putting one button should set the height of Footer to item height, but somehow it doesn't

**Comment by mikepenz** [comment]
@ivanstojkovicapps I simply tried this by adding one `StickyFooterItem` to the sample application. And it works as expected. 

Can you please create a sample application or show some code on how I can reproduce this with the sample application?

**Comment by mikepenz** [comment]
Close until further information is provided
