### ISSUE TITLE
How to use one Heaher Navigation bar with data from getStringExtra

### ISSUE THREAD

**Issue by trinhvanminh2009** [mikepenz/MaterialDrawer#1904]
I'm using your navigation bar, I have a login activity push extra into the Header Navigation. How I can use only one Header Navigation Bar for others activities ?

**Comment by mikepenz** [comment]
@trinhvanminh2009 I do not understand the question

**Comment by trinhvanminh2009** [comment]
For Example : I have many activities need to using this Material Drawer . How I can create one Material Drawer for many activities (items) using. How to don't need to each activity one Material Drawer ?

**Comment by mikepenz** [comment]
Normally you have a root activity which has the `Drawer` and sub hierarchies are `Fragment`s
If you have all your navigation with Activities (which is not clever) then you will need some kind of `BaseActivity` which will add the Drawer to all of your activitites

**Comment by trinhvanminh2009** [comment]
Yeah ! I did it. Sorry, this isn't your Material Drawer issue. This is my issue . Thanks for the support. Hope you can support more and more people . Thank you .Have a nice day!
