### ISSUE TITLE
Icons are misplaced the first time you open the drawer

### ISSUE THREAD

**Issue by marconealberto** [mikepenz/MaterialDrawer#1905]
It used to work up to few weeks ago. Last week I rebuilt the project and the icons now look moved on the left:

![screenshot_20170615-092601](https://user-images.githubusercontent.com/779070/27170325-c780cad2-51ad-11e7-872f-08c0359646ba.png)

is this ever happened before? Once you close it and reopen it, you get just one misplaced icon.

![screenshot_20170615-092938](https://user-images.githubusercontent.com/779070/27170333-d09385e2-51ad-11e7-820d-6c5ddecb47d6.png)

**Comment by AllanWang** [comment]
How did you add the items to your drawer?

**Comment by marconealberto** [comment]
simply like this:
drawer.addItems(createRows());

I'm having the same problems somewhere else with icons when using the **com.mikepenz.iconics** library.

**Comment by AllanWang** [comment]
Is there anything you've done with the drawer setup or item setup that is different from the sample app? Or maybe you should specify your device info. I've personally never had that issue before.

**Comment by mikepenz** [comment]
@marconealberto can you please try if you see the same issue in the sample app? 
Which version of the drawer do you use? 
What's the Android verison on which you see that issue?

**Comment by mikepenz** [comment]
Close until further information is provided
