### ISSUE TITLE
Drawer title and arrow is not aligned

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/MaterialDrawer#1907]
I'm not sure if this is expected behaviour, but without a second line, the drawer title and the arrow aren't aligned.

![screenshot_20170615-162905](https://user-images.githubusercontent.com/6251823/27205940-cf2b8bba-51e8-11e7-93cf-6e8d4fddadfa.png)

I've added (from MaterialDrawerKt but they properly map to the same builder methods)

```
selectionSecondLineShown = false
selectionSecondLine = ""
paddingBelow = false
```

This looks the same whether `selectionSecondLineShown` is true or false, but in the [library](https://github.com/mikepenz/MaterialDrawer/blob/v5.9.2/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L1164) it should make the view gone

**Comment by mikepenz** [comment]
@AllanWang well the arrow is always positioned at the same place (center of both lines on the left). As far as I remember there were not specific rules in the Material Design Guidelines regarding this. 

You'd expect the single line on the left to center with the arrow?

**Comment by AllanWang** [comment]
When the secondary text is visible, it is vertically aligned with the arrow. When it is just the first line, I expected that to be brought down and align with the arrow. I think it would look nicer too

**Comment by mikepenz** [comment]
![2017-06-18 18 59 06](https://user-images.githubusercontent.com/1476232/27262505-3b61c7d8-5458-11e7-9227-059f8e180a84.jpg)

I have checked it again. The thing is the arrow is not centered with the text in any way. the arrow has it's specified position. 

The name already get's centered within the area the 2 lines are defined so that's fine. 

In case you need a different appearance you can always copy and paste the `xml` of the header to your project and alter the layout to the one you need.

**Comment by mikepenz** [comment]
Close as the solution by overwriting the `header` xml solves the problem

**Comment by AllanWang** [comment]
@mikepenz As a note since I've just gotten to changing this, going from

```xml
android:layout_marginBottom="@dimen/material_drawer_padding"
android:gravity="center_vertical"
```

to 

```xml
android:layout_marginBottom="@dimen/material_drawer_account_header_dropdown_margin_bottom"
android:gravity="center_vertical|bottom"
```

in the `material_drawer_account_header_text_section` `LinearLayout` is enough to address the issue. The padding is changed to match that of the arrow and the alignment is to the bottom.

Screenshot for original:

![screenshot_20170814-200721](https://user-images.githubusercontent.com/6251823/29300898-625c6044-812d-11e7-9f54-9cbe2c6e0448.png)

Screenshot for updated:

![screenshot_20170814-200937](https://user-images.githubusercontent.com/6251823/29300858-1fb0f926-812d-11e7-8ecf-bb390e75ca7f.png)

Screenshot for updated with both lines:

![screenshot_20170814-201234](https://user-images.githubusercontent.com/6251823/29300862-25973a1c-812d-11e7-9362-cb75b3125777.png)

Doesn't seem to look different from your current implementation but things are properly aligned if either line is hidden.

I think this may be preferred to the current center implementation, but it's up to you whether you want to make this change.

**Comment by mikepenz** [comment]
@AllanWang well I see, but not sure regarding the material design guideliens
