### ISSUE TITLE
How to change StatusBar color in SDK 25+

### ISSUE THREAD

**Issue by jordyamc** [mikepenz/MaterialDrawer#1909]
I read that before was a method named withStatusBarColorRes() but i search for it and i didnt found it.... is there an option to avoid override the color?

**Comment by AllanWang** [comment]
I believe the drawer has a translucent status bar by default. Try disabling that and setting the status bar color directly as you would in any activity:

```
getWindow().setStatusBarColor(Color.BLUE);
```

This is for lollipop and up and you may need to add other flags depending on your setup.

**Comment by mikepenz** [comment]
@AllanWang thanks for answering.

@jordyamc well it is more or less related to the `MaterialDrawer`. It's basically default `DrawerLayout` behaviour you see here. The `DrawerLayout` from Android is like a `ScrimInsetsLAyout` so this one will control the color. 
So you can directly use the method provided by the `DrawerLayout`:
https://github.com/mikepenz/MaterialDrawer/issues/1247#issuecomment-217641415
