### ISSUE TITLE
Real Transparent Status Bar & Navigation Bar

### ISSUE THREAD

**Issue by Kadrei** [mikepenz/MaterialDrawer#191]
I want to make the Translucent Navigation & Statusbar transparent so i can show Information of what is outside the screen like in the Picture below:
![map](https://cloud.githubusercontent.com/assets/2720282/7002224/9c26c356-dc47-11e4-9496-837c62ebd1b2.png)

This seems to be not possible with this library. Even if I set the translucent mode to true and define the color as @android:color/transparent it just shows a "transparent white"

Is there a possibility to get a real transparent status & navbar (and still switch to color status/navbar at runtime, ie when User changes View to a non Mapview)

**Comment by FabianTerhorst** [comment]
You can try:

mToolbar.getBackground().setAlpha(0)

**Comment by mikepenz** [comment]
@Kadrei the library uses the ScrimInsetsFrameLayout which will automatically color the area below the statusbar. with the default implementation it won't allow you to display something below the statusbar. i haven't found a method call yet to toggle this with the scriminsetslayout. 

For now you can use the Drawer to build the drawer layout contents for you and implement your own DrawerLayout and just add the view which is generated by the drawer. (This is a really advanced usage). 

If you can provide an acitivty like the one shown above i would like to try some things to get this working out of the box.

**Comment by Kadrei** [comment]
@FabianTerhorst that just makes the Toolbar transparent (and its what i did to get the look in the screenshot)

@mikepenz how would i get the Drawer to just build the drawerlayout content and then get it?
(I will provide a sample activity for you tomorrow)

**Comment by mikepenz** [comment]
@Kadrei you can use the buildView method which will only build the view. you can then use it with result.getSlider()

You can see how it's done here: https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/EmbeddedDrawerActivity.java

this is an embedded version of the drawer. but youc an also use it to inflate the contents to a normal DrawerLayout ;)

**Comment by Kadrei** [comment]
@mikepenz: it worked, so thank you.

i think the only informations for getting an activity to look like in the screenshot you need following in your style:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="AppTheme.Base" parent="MaterialDrawerTheme.Light">
        <item name="android:windowTranslucentNavigation">true</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowTranslucentStatus">true</item>
    </style>
</resources>
```

in your Activity following is needed:
```java
mToolbar.getBackground().setAlpha(0)
```

When i switch between fragments via the drawer is just change the padding of the fragmentsview to be below the toolbar (if it is not a mapfragment) or be behind the toolbar (if it is a mapfragment) but this should be the job of the fragment programmer not of the drawer.

it would be perfect to get your library working without having to manually put it into the layout (and i needed to do the whole work around the actionbardrawertoggle of my own also).
Maybe an Option to stop the library from handling the contentviews paddings would be the best way to get it easily working with the real transparent action bar

**Comment by mikepenz** [comment]
@Kadrei the sample now includes an activity showing how this can be done ;)

**Comment by Kadrei** [comment]
@mikepenz awesome, great library btw ;)

**Comment by mikepenz** [comment]
@Kadrei thanks
