### ISSUE TITLE
Using MiniDrawer

### ISSUE THREAD

**Issue by DEV-NP** [mikepenz/MaterialDrawer#1910]
How to implement MiniDrawer with your library?

**Comment by Timodz** [comment]
you can start by checking this code from the sample provided with the library [here](https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java)

**Comment by mikepenz** [comment]
@Timodz thanks for answering. 

@DEV-NP yes please look in the sample app

**Comment by DEV-NP** [comment]
how can I achieve mini drawer without using crossfade?.. i want it to look like as shown in the design..
![2_2](https://user-images.githubusercontent.com/19484623/27270416-9042dfaa-54dd-11e7-9832-30145530bd62.jpg)

**Comment by mikepenz** [comment]
@DEV-NP for this case I'd suggest you to go the good old way of manually implementing it. 

Use a `DrawerLayout` and add a list or a RecyclerView or a `ScrollView` with views with these icons to it. 

It looks completely different as the `MaterialDrawer` and so I guess you can not take advantage of all its strengths. 

-----------

In case you still want to do it with the `MiniDrawer` init your `MiniDrawer` get the reference to the view. and then add this view to a `DrawerLayout` which you defined in your layout
