### ISSUE TITLE
MiniDrawer From the right side

### ISSUE THREAD

**Issue by Timodz** [mikepenz/MaterialDrawer#1912]
The command  `.withDrawerGravity(Gravity.END)` for the MiniDrawer not working  to change the placement.

**Comment by mikepenz** [comment]
@Timodz as you add the `MiniDrawer` in the layout, it's up to you to position it. 

Beside that I am not 100% sure if the `Crossfader` allows to be used on the right side: https://github.com/mikepenz/Crossfader

**Comment by Timodz** [comment]
ok thank you ! 
going to check the crossfader then

**Comment by mikepenz** [comment]
@Timodz if it's not yet supported I guess you will have to do a PR on the `Crossfader` or modify it's source as there are no current plans of adding this. 

Basically it's really up to you as for the `MiniDrawer` (And normal `Drawer`) you define where those views are added, and nothing is handled by the `MaterialDrawer`

**Comment by Timodz** [comment]
@mikepenz  Thank you
