### ISSUE TITLE
Profile picture badge (unread count) in AccountHeader

### ISSUE THREAD

**Issue by SuperThomasLab** [mikepenz/MaterialDrawer#1914]
Hello,
The Gmail app shows an unread count badge next to a profile picture in the account switcher. Is this supported in this library? (I wasn't able to find such method in `ProfileDrawerItem`). Thanks a lot for this great library!
Regards, Thomas

**Comment by mikepenz** [comment]
@SuperThomasLab sorry this is not supported. The `Badge` is only supported in the item list

**Comment by SuperThomasLab** [comment]
@mikepenz Thanks for your quick reply. Any plans to add this in the future? I think this is a very useful feature.

**Comment by mikepenz** [comment]
@SuperThomasLab sadly there are no plans to do this, at last not right now. 

I will keep it in mind. Perhaps for v6.x, but I can't or won't promise anything :). 

You might also want to open a PR and add this. 

I think it can be closed as there are no current plans to support this

**Comment by SuperThomasLab** [comment]
@mikepenz Ok, I'll close this issue. Thanks for your help.

**Comment by mikepenz** [comment]
Sorry that this is currently not part of the futures
