### ISSUE TITLE
Failed to resolve: com.android.android.support 25.4.0

### ISSUE THREAD

**Issue by gmoraiz** [mikepenz/MaterialDrawer#1915]
compile 'com.android.support:appcompat-v7:25.3.1'

compile('com.mikepenz:materialdrawer:5.9.3@aar') {
        transitive = true
}

But... 25.4.0 also doesn't work.

**Comment by mikepenz** [comment]
@gmoraiz that's not a `MaterialDrawer` specific issue. 

Please follow Android / Google's guide on how to get the latest support libraries. 

https://developer.android.com/topic/libraries/support-library/setup.html

**Comment by IgorGanapolsky** [comment]
I am having the same issue as OP.  The developer doc you linked to doesn't solve the problem.  What is the solution?

**Comment by mikepenz** [comment]
@IgorGanapolsky please read the link. it does solve hte problem

**Comment by GreenSkinMonster** [comment]
If you cannot get support lib 25.4.0 installed, you can exclude it.
No problem for me so far.

    compile('com.mikepenz:materialdrawer:5.9.3@aar') {
        transitive = true
        exclude group: 'com.android.support'
    }

**Comment by WayneRiesterer** [comment]
Adding the Maven repository worked for me. Just put this code above your dependencies:

```
allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}

dependencies {...}
```

**Comment by Pravind-Clarion** [comment]
Now, instead of 'maven {url "https://maven.google.com" }' just 'google()' will also work.
allprojects {
    repositories {
        . . . 
        google()
        . . .
    }
}
