### ISSUE TITLE
Change Toolbar Navigation Icon color

### ISSUE THREAD

**Issue by jordyamc** [mikepenz/MaterialDrawer#1916]
How can i intercept the Navigation Icon set to change the color?, or a method to do it automaticly

I set withActionBarDrawerToggleAnimated to false and set the tinted icon manually but it still override the icon

**Comment by mikepenz** [comment]
@jordyamc the `MaterialDrawer` set's a `ActionBarDrawerToggle` if the `Toolbar` is supplied. It's color or it's appearance is not controlled by the `MaterialDrawer` but rather from the supplied theme. 

You can remove the `Toolbar` you pass to the `MaterialDrawer` and manually handle everything, or you look in the web on how to adjust the `ActionBarDrawerToggle`. (Normally the color is controlled via the theme you can set on the `Toolbar`)

But it's no `MaterialDrawer` issue.
