### ISSUE TITLE
How to make MiniDrawer hidden like normal NavigationDrawer?

### ISSUE THREAD

**Issue by DEV-NEP** [mikepenz/MaterialDrawer#1917]
How to toggle minidrawer between show/hide using hamburger button?

**Comment by mikepenz** [comment]
@DEV-NP exactly the same answer as here: https://github.com/mikepenz/MaterialDrawer/issues/1910#issuecomment-309357884

The `MiniDrawer` is meant to be used with the `Crossfader` like shown in the sample. If you do only want to have the `MiniDrawer` you have to do that manually. Create it. Get the `View` add it to your own `DrawerLayout`

**Comment by DEV-NP** [comment]
Sorry to bother you.. As I am a newbie on Android, I can hardly understand what u r saying...Can you plz provide a sample code for doing so?

**Comment by mikepenz** [comment]
well as mentioned in the other issue. Your requirement does not look like it needs the `MaterialDrawer`. It makes no sense to use a library for that case. and it will be better for you to look up a tutorial on how to use the `DrawerLayout` 

The `MiniDrawer` may look similar but it's use case is always meant with a normal `Drawer`.

**Comment by mikepenz** [comment]
Close until further information is provided
