### ISSUE TITLE
how to handle triangle on click and change the no of profile in headerview

### ISSUE THREAD

**Issue by uday-mshr** [mikepenz/MaterialDrawer#1918]
Hi I want to use this material drawer not exactly as the Gmail's drawer
For that, I want to call a function on the click of the triangle in nav header.
and I want to reduce the no of inactive profile view (the circles) in the profiles header view.

**Comment by mikepenz** [comment]
@uday-mshr could you please be a bit more specific. I am not sure what you are trying to achieve

**Comment by uday-mshr** [comment]
![screen shot 2017-06-19 at 4 35 57 pm](https://user-images.githubusercontent.com/19321534/27282414-6f89fde0-550d-11e7-8960-7797b4bf8e79.png)
I want to call a function on click of this triangle.

![screen shot 2017-06-19 at 4 35 50 pm](https://user-images.githubusercontent.com/19321534/27282417-73e6f96a-550d-11e7-916b-eb4ba4ccc443.png)

and can we reduce the no of this profile images.

**Comment by mikepenz** [comment]
@uday-mshr you can either have 2 or 3 small thumbs, and 1 big, there is no way to show less than this. 

Please see the listener functions available:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L520
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L534
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L644
