### ISSUE TITLE
Add ability to disable profile icon color filter on touch

### ISSUE THREAD

**Issue by LoburAlexander** [mikepenz/MaterialDrawer#1919]
As I can see, BezelImageViews are used for profile images in drawer header. And when user touches that imageViews, a color filter is applied to the underlying image. Although it's possible to change the color of that filter by overriding biv_selectorOnPress attribute, I haven't managed to disable this filter at all. That's because there's a hardcoded alpha value in BezelImageView (mSelectorAlpha field). 
Moreover, if biv_selectorOnPress is set to @null, another filter is still applied to the image (mDesaturateColorFilter). 

It would be nice to have an ability to disable any filters for profile images. Please, either add a flag to configure whether to use a filter on image or not, or allow developers to set full color for that filter, including alpha.

**Comment by mikepenz** [comment]
@LoburAlexander sorry for answering that late. Very interesting idea. I currently haven't planned to add this functionality. 

If you really want or need it, I am more than happy to accept a pull request to add such a functionality
