### ISSUE TITLE
Unable to change UI from setOnDrawerItemClickListener

### ISSUE THREAD

**Issue by efi-mk** [mikepenz/MaterialDrawer#1923]
Hello,

I've encountered a weird behavior in which any changes that I do to UI elements inside Drawer.OnDrawerItemClickListener implementation does not take any effect.

 Example:
```
rightDrawer.setOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
            @Override
            public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                // Act as a button, no need to show any selection.
                rightDrawer.setSelection(-1);

                switch ((int) drawerItem.getIdentifier()) {
...
                    case 4:
                        activity.showLoading(); <-- Should show a progress bar, but nothing happens.


...
// Method is being called, but any UI related stuff is ignored
public void  showLoading() {
        // Don't allow the user to refresh.
        swipeLayout.setEnabled(false);
        recyclerView.setVisibility(View.INVISIBLE);
        /* Finally, show the loading indicator */
        progress.setVisibility(View.VISIBLE);
 }
```

**Comment by mikepenz** [comment]
@efi-mk have you already debugged in? is `activity` the correct currently displayed activity?

The `event` you get from the `MaterialDrawer` is just a forwarded `onClick` event on the main thread. nothing special. 

If you set a delay for the click it will be delayed with a handler but still:
https://github.com/mikepenz/MaterialDrawer/blob/611adcf84936820c58e12630ca0c1af788662662/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1770

There must be some other issue in your code (like the wrong activity), why it does not show up. (or perhaps another code from you hides it too fast again.

**Comment by efi-mk** [comment]
You are right. Tx
