### ISSUE TITLE
How to make a drawer full in screen in a fragment

### ISSUE THREAD

**Issue by EdwardtoGitHub** [mikepenz/MaterialDrawer#1925]
I use the statement   ".withFullscreen(true)",but it doesn't work.
the drawer is still below the toolbar.

**Comment by mikepenz** [comment]
@EdwardtoGitHub why would you like to have a drawer within a fragment in the first place? 

But well independent of that, seems your fragment is not reaching up to the top of the screen. You will have to make sure you set the `fitsSystemWindow`s flag's property properly, and in addition you might have to use a `ScrimInsetsLayout` or so which does not inline your sub-views. 

Also make sure you correctly init the drawer within the fragment (See the sample) (that's different from an activity)
