### ISSUE TITLE
Change name and email color in account header. 

### ISSUE THREAD

**Issue by ATumbler** [mikepenz/MaterialDrawer#1926]
I not find method for change name and email color in account header. I try find textviews by id - R.id material_drawer_account_header_name/email. But i get null...

**Comment by ATumbler** [comment]
Note: i must be change it dinamically

**Comment by mikepenz** [comment]
@ATumbler equally to the normal items (https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer) , just change the item and then notify the `AccountHeader` about the updated item... (The `AccountHeader` has similar methods)

**Comment by ATumbler** [comment]
Hm.... It is not work. I try again find view by id - after build drawer and it work fine.

**Comment by mikepenz** [comment]
@ATumbler no don't do this. This is really bad and will cause many problems. 

Make sure you do the notifying of the update on the UI thread. 
Make sure the profile has an identifier.
