### ISSUE TITLE
Drawer under statusbar 

### ISSUE THREAD

**Issue by ATumbler** [mikepenz/MaterialDrawer#1927]
hi, mike, great library!
i can't explain what's wrong because see 
[screenshot](https://pp.userapi.com/c836623/v836623722/4b323/MpPVJI53efg.jpg).
If I put `colorPrimaryDark` then when you start everything works well, but if I programatically supply the statusbar the color that it loses the previous seen. 
Here is my method of setting the color:

```
public static void setStatusBarColor(Activity ctx, int color, boolean withLightStatusBar)
{
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP)
{
Window window = ctx.getWindow();
window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M)
{
int flags = ctx.getWindow().getDecorView().getSystemUiVisibility();
if (withLightStatusBar)
{
flags |= View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR;
}
else
{
flags &= ~View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR;
}
ctx.getWindow().getDecorView().setSystemUiVisibility(flags);
}
window.setStatusBarColor(color);
}
}
```

**Comment by ATumbler** [comment]
I really can't explain problem. 
I hope you understand

**Comment by ATumbler** [comment]
Sorry again.. I use `drawer.getDrawerLayout().setStatusBarBackgroundColor(int color)`

**Comment by ATumbler** [comment]
I use `drawer.getDrawerLayout().setStatusBarBackgroundColor`. how i can work with `lightStatyusBar`

**Comment by mikepenz** [comment]
@ATumbler `drawer.getDrawerLayout().setStatusBarBackgroundColor` has nothing to do with the lfag. 
You apply the flag as you did above, and then you apply the color with the `setStatusBarBackgroundColor` on the `DrawerLayout`

**Comment by abhay7030** [comment]
rawer.getDrawerLayout().setStatusBarBackgroundColor has nothing to do with the lfag.
You apply the flag as you did above, and then you apply the color with the setStatusBarBackgroundColor on the DrawerLayout

**Comment by mikepenz** [comment]
Please report back. Close for now
