### ISSUE TITLE
[Q] Close the header (w/ profiles) when drawer closes (?)

### ISSUE THREAD

**Issue by aitorvs** [mikepenz/MaterialDrawer#1929]
[Question] I have a drawer that contains a header with profiles. I'd need to make sure that the header is closed when the drawer is closed, but I can't find the proper method to do so...Is is supported?

**Comment by mikepenz** [comment]
@aitorvs the best would be you set up a listener to be notified when the drawer is closed
https://github.com/mikepenz/MaterialDrawer/blob/611adcf84936820c58e12630ca0c1af788662662/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1150
and then you simply check if the profile selection list is shown: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L110
If yes you close it, by toggling it:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L101

**Comment by aitorvs** [comment]
Thanks a lot @mikepenz. I guess I need to keep a reference to either the header or the drawer as I see that the `OnDrawerListener` methods return a `View`.

**Comment by mikepenz** [comment]
yeah the results of the builder for drawer and header should be remembered :)

**Comment by aitorvs** [comment]
That's fair enough. It works like a charm. Thanks a lot

**Comment by mikepenz** [comment]
You are welcome :)
