### ISSUE TITLE
Drawer Theme question

### ISSUE THREAD

**Issue by monakhv** [mikepenz/MaterialDrawer#193]
I use dynamic Theme in my project. It is set by  setTheme(R.style.Theme1) call in the onCreate method in activity. However Drawer seems to ignore it and use Light theme anyway. So I have Light drawer even in Dark theme.

**Comment by mikepenz** [comment]
What'S the parent of the theme you use?

**Comment by monakhv** [comment]
UPS.. 
I'm sorry. It's my mistake. I used wrong parent theme.
Just one more question. Is is possible somehow to reduce header height?

**Comment by mikepenz** [comment]
you can choose between the compact header and the normal header.

The compact header will only show the profile image of the active profile and the selection box with name and e-mail. 

there are no other implementations. The normal header is designed as described in the Material Design Guidelines so this one should be used.
