### ISSUE TITLE
[Ask] dinamic IProfile on drawer when data from Sqlite??

### ISSUE THREAD

**Issue by kalvian1060** [mikepenz/MaterialDrawer#1930]
[Capture 1] add iProfile manual
http://imgur.com/a/Mc6qI

[Capture 2]  add Iprofile to arraylist and get data from Sqlite
http://imgur.com/a/eoTov

[Capture 3]  add method arraylist to addProfile()  not support...
http://imgur.com/a/4MO58

How to add dynamic profile?? can u give me suggest 
Thanks for replay

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L268 this methods support an array. 

Alternative you do not have to write the builder all at once. You can split it up ;) 

So You can have:

```java
AccountHeaderBuilder builder = new ...;
builder. ...;
for(Whatever a : whatevers) {
   builder.addProfile(a);
}
AccountHeader ah = builder.build();
```

**Comment by kalvian1060** [comment]
protected void menuDrawer(int posisi) {
        toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        PrimaryDrawerItem home = setMenuItem("Order", R.drawable.order_ic, "home");
        PrimaryDrawerItem pelanggan = setMenuItem("Pelanggan", R.drawable.ic_person_outline, "pelanggan");
        PrimaryDrawerItem produk = setMenuItem("Produk", R.drawable.ic_store_black_24px, "produk");
        PrimaryDrawerItem produkkategori = setMenuItem("Produk Kategori", R.drawable.ic_home, "kategori");
        PrimaryDrawerItem pengaturan = setMenuItem("Pengaturan", R.drawable.ic_pengaturan, "pengaturan");
        PrimaryDrawerItem produkmasuk = setMenuItem("Stok Masuk", R.drawable.ic_master, "masuk");
        PrimaryDrawerItem update = setMenuItem("Update", R.drawable.ic_syncron, "update");
        PrimaryDrawerItem laporan = setMenuItem("Laporan", R.drawable.ic_insert_chart_black_24px, "laporan");
        PrimaryDrawerItem transaksi = setMenuItem("Transaksi Terbaru", R.drawable.ic_swap_horiz_black_24px, "transaksi");
        PrimaryDrawerItem store = setMenuItem("Ganti Toko", R.drawable.ic_store_black_24px, "store");
        PrimaryDrawerItem about = setMenuItem("About", R.drawable.ic_help_white_24px, "about");
        PrimaryDrawerItem logout = setMenuItem("Logout", R.drawable.ic_logout_green, "logout");


        final IProfile profile = new ProfileDrawerItem().withName(SharedData.getKeyNama()).withEmail(SharedData.getKey(c, "namaToko")).withIdentifier(100);

        builder = new AccountHeaderBuilder()
                .withActivity(this)
                .withTranslucentStatusBar(true)
                .withHeaderBackground(R.color.accent);

        List<res_users> dataUser = new Select().from(res_users.class).execute();

        int ACCOUNT = 100;

        for (res_users users : dataUser) {
            builder.addProfiles(new ProfileDrawerItem()
                    .withName(users.getName())
                    .withEmail(users.getLogin())
                    .withIcon(BitmapUtil.decode(users.getImage())).withIdentifier(ACCOUNT));
            ACCOUNT++;
        }

        headerResult = builder.build();
        builder.withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
            @Override
            public boolean onProfileChanged(View view, IProfile profile, boolean current) {
                if (profile instanceof IDrawerItem && profile.getIdentifier() == PROFILE_SETTING) {
                    int count = 100 + headerResult.getProfiles().size() + 1;

                    IProfile newProfile = new ProfileDrawerItem().withNameShown(true).withName("Admin" + count).withEmail("admin" + count + "@gmail.com").withIcon(R.drawable.ic_add_white_24px).withIdentifier(count);

                    if (headerResult.getProfiles() != null) {
                        headerResult.addProfile(newProfile, headerResult.getProfiles().size() - 2);
                    } else {
                        headerResult.addProfiles(newProfile);
                    }
                }

                //false if you have not consumed the event and it should close the drawer
                return false;
            }
        });

        
        drawerBuilder = new DrawerBuilder()
                .withTranslucentStatusBar(true)
                .withAccountHeader(headerResult)
                .withCloseOnClick(true)
                .withDelayOnDrawerClose(100)
                .withActivity(this)
                .withToolbar(toolbar)
                .addDrawerItems(home, transaksi, pelanggan, produk, produkkategori, produkmasuk, laporan, pengaturan, store, about, update)
                .withSelectedItemByPosition(posisi)
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        if (drawerItem.isSelected()) {
                            drawerBuilder.closeDrawer();
                        }
                        String tag = (String) drawerItem.getTag();
                        switch (tag) {
                            case "home":
                                getSupportFragmentManager().beginTransaction().replace(R.id.fLProduk, new DataPenjualan(), DataPenjualan.class.getSimpleName()).commit();
                                break;
                            case "masuk":
                                getSupportFragmentManager().beginTransaction().replace(R.id.fLProduk, new ProdukMasuk(), ProdukMasuk.class.getSimpleName()).commit();
                                break;
                            case "pengaturan":
                                getSupportFragmentManager().beginTransaction().replace(R.id.fLProduk, new Pengaturan(), Pengaturan.class.getSimpleName()).commit();
                                break;
                            case "store":
                                gantiToko();
                                break;
                            case "pelanggan":
                                SharedData.setKeyActionPilihCostumer(2);
                                getSupportFragmentManager().beginTransaction().replace(R.id.fLProduk, new DataCostumer(), DataCostumer.class.getSimpleName()).commit();
                                break;
                            case "produk":
                                getSupportFragmentManager().beginTransaction().replace(R.id.fLProduk, new ProductFragment(), ProductFragment.class.getSimpleName()).commit();
                                break;
                            case "laporan":
                                getSupportFragmentManager().beginTransaction().replace(R.id.fLProduk, new LaporanFragment(), LaporanFragment.class.getSimpleName()).commit();
                                break;
                            case "transaksi":
                                getSupportFragmentManager().beginTransaction().replace(R.id.fLProduk, new TransaksiFragment(), TransaksiFragment.class.getSimpleName()).commit();
                                break;
                            case "kategori":
                                until.replaceFragment(c, R.id.fLProduk, new KategoriFragment(), KategoriFragment.class.getSimpleName(), KategoriFragment.class.getSimpleName());
                                break;
                            case "update":
                                SharedData.setTglUpdate(timeStamp);
                                drawerBuilder.closeDrawer();
                                //check jika order produk sudah terupload semua maka baru lakukan aksi update data
                                if (until.getProdukMasuk() > 0) {
                                    Toast.makeText(c, "Silahkan Update Produk Masuk..", Toast.LENGTH_SHORT).show();
                                } else if (until.getDataPenjualan() > 0) {
                                    until.showToast(c, "Silahkan Selesaikan Order Dahulu");
                                } else {
                                    if (NetworkHelper.isConnectedToInternet(c)) {
                                        until.loadingProgress(c, "Mengunduh data. mohon menunggu.");
                                        c.startService(new Intent(c, DownloadService.class).setAction(DownloadService.PRODUK));
                                        c.startService(new Intent(c, DownloadService.class).setAction(DownloadService.COSTUMER));
                                        c.startService(new Intent(c, DownloadService.class).setAction(DownloadService.CATEGORY));
                                        c.startService(new Intent(c, DownloadService.class).setAction(DownloadService.VOUCHER));
                                    } else {
                                        until.showDialog(c, "Please Cek Internet Connection");
                                    }
                                }
                                break;
                            case "logout":
                                logoutActivity();
                                break;
                            case "about":
                                until.replaceFragment(c, R.id.fLProduk, new AboutSoftware(), AboutSoftware.class.getSimpleName(), AboutSoftware.class.getSimpleName());
                                break;
                        }
                        return true;
                    }
                }).build();


        drawerBuilder.addStickyFooterItem(logout);


    }
