### ISSUE TITLE
Show hint view

### ISSUE THREAD

**Issue by sweetdream0729** [mikepenz/MaterialDrawer#1931]
Hi,

Thanks for your support.
I would like to show hint overlay view to show some help texts on drawer items.
How can I implement this function?

Looking forward to hear from you.

**Comment by mikepenz** [comment]
@sweetdream0729 well there is no such function within the `Drawer` 

But the `Drawer` object has a method to return it's 'view':
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L199

You should be able to use this to add the views you want: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L199

(if you need to access a specific drawerItem --> remember it's a RecyclerView)
