### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by harshjain1711** [mikepenz/MaterialDrawer#1932]
i am  new at developing. please help me integrate this in my existing app. my drawer is nt good. i need this. thanks. contac via email : harshjain17112000@gmail.com or skype: harshsjain@outlook.com
thanks in advance. looking further for your help .

**Comment by mikepenz** [comment]
everything is shown in the readme and in the sample app

**Comment by abhay7030** [comment]
# a

**Comment by abhay7030** [comment]
a
