### ISSUE TITLE
Set the AccountHeaderBuilder header to sticky

### ISSUE THREAD

**Issue by Boom618** [mikepenz/MaterialDrawer#1933]
Hei,penz, AccountHeaderBuilder is not similar to DrawerBuilder. AddStickyDrawerItems method, how can i do

**Comment by mikepenz** [comment]
@Boom618 simply do not pass the `AccountHeader` object to the `DrawerBuilder` instead build your `AccountHeader`, and then get it's view `AccountHeader.getView()`, just set this view as `StickyHeader` of the `MaterialDrawer`

**Comment by Boom618** [comment]
@mikepenz  Oh, you are right, or you Niubi, I am so stupid, you handsome,

You have a good habit, the project often summed up, can add a friend _FB_ or _Twitter_, `BoomHe`
