### ISSUE TITLE
Header layout is not rendering properly

### ISSUE THREAD

**Issue by GoltsevEugene** [mikepenz/MaterialDrawer#1934]
Hi Mike, first of all thanks a lot for your beatiful library!

Here is very simple layout for header:
https://gist.github.com/GoltsevEugene/b56894741572afa7e93acb34c7e5b5dc

And I'm using it via DrawerBuilder.withHeader().

Here is a result:
![screenshot_2017-06-29-15-30-22-898_com](https://user-images.githubusercontent.com/12167642/27687913-574b8cb8-5ce1-11e7-99da-a559b1ef427f.png)
Drawer makes header wrap_content, not my pointed 200dp.

What am I doing wrong with layout?

**Comment by mikepenz** [comment]
@GoltsevEugene please define the preferred header height here: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L604

**Comment by GoltsevEugene** [comment]
Hmmm, thx, but now seems to be some bug. Here is how I use it:

![2017-06-30 12 01 34](https://user-images.githubusercontent.com/12167642/27728800-fd6c337c-5d8b-11e7-8b21-a0dd44299754.png)

And here is the result:

![2017-06-30 11 59 34](https://user-images.githubusercontent.com/12167642/27728810-053b4eda-5d8c-11e7-864f-8a334b261d92.png)

Header seems not to be there )

**Comment by mikepenz** [comment]
@GoltsevEugene can you please try to set your header layout height as `match_parent`. 

Here's the item which will hold the header view basically: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerUtils.java#L242

In the sample it works with the following header layout:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/header.xml

**Comment by GoltsevEugene** [comment]
What is interesting - with some images works fine, with other - not.

If I put this layout:
https://gist.github.com/GoltsevEugene/0660e4dabaa6910b274d1380ec4369b4

Here's a result:
![2017-06-30 12 37 37](https://user-images.githubusercontent.com/12167642/27730145-fcb0bf66-5d90-11e7-99d1-e95fe0dccc95.png)

But if I uncomment that dummy view, it works fine:
![2017-06-30 12 39 53](https://user-images.githubusercontent.com/12167642/27730242-40fc2016-5d91-11e7-844f-df96dcdf5c92.png)

Really don't know the reason, maybe you have some idea.

**Comment by mikepenz** [comment]
@GoltsevEugene well I guess I have the issue. The LayoutParams are not applied to the header view, but to the divider here: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ContainerDrawerItem.java#L117

**Comment by GoltsevEugene** [comment]
Glad I helped to figure it out ;)

**Comment by GoltsevEugene** [comment]
That did the trick, many thanks!
