### ISSUE TITLE
[ASK] on select profile account change but now show toast ...??

### ISSUE THREAD

**Issue by kalvian1060** [mikepenz/MaterialDrawer#1935]
We love u liblary...
this action on select user item...in this case if select account open start activity for input pin number. 
this code i test using toast but not showing??

```java
headerResult = builder.build();
        builder.withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
            @Override
            public boolean onProfileChanged(View view, IProfile profile, boolean current) {
                if (profile instanceof IDrawerItem && profile.getIdentifier() == PROFILE_SETTING) {
                    int count = 100 + headerResult.getProfiles().size() + 1;
                    IProfile newProfile = new ProfileDrawerItem().withNameShown(true).withName("Admin" + count).withEmail("admin" + count +"@gmail.com").withIcon(R.drawable.ic_add_white_24px).withIdentifier(count); 

                    if (headerResult.getProfiles() != null) {
                        headerResult.addProfile(newProfile, headerResult.getProfiles().size() - 2);
                        Toast.makeText(c,""+profile.getName().toString(),Toast.LENGTH_SHORT).show();
                    } else {
                        headerResult.addProfiles(newProfile);
                    }
                }
                return true;
            }
        });
```

**Comment by mikepenz** [comment]
@kalvian1060 thank you very much. 
Have you already debugged in, how far it goes? 
So the toast is also not showing? or only the profile missing?

**Comment by kalvian1060** [comment]
I have 2 account in nav drawer header. on click icon image or list in drawer it not problem. 
on click account 2 name and email successfull change. now i find code for get name or email from when i click the profile. 

`final IProfile profile = new ProfileDrawerItem().withName(SharedData.getKeyNama()).withEmail(SharedData.getKey(c, "namaToko")).withIdentifier(100);

        builder = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.color.accent);

        List<res_users> dataUser = new Select().from(res_users.class).execute();

        int ACCOUNT = 100;

        for (res_users users : dataUser) {
            builder.addProfiles(new ProfileDrawerItem()
                    .withName(users.getName())
                    .withEmail(users.getLogin())
                    .withIcon(BitmapUtil.decode(users.getImage())).withIdentifier(ACCOUNT));
            ACCOUNT++;
        }
`

**Comment by kalvian1060** [comment]
Variabel ACCOUNT is Iddentifier. of account. i find code if i click on account show email or name by identifier. i was read issue but in this project but not found same case.

**Comment by mikepenz** [comment]
@kalvian1060 sorry, but I am a bit confused. So what is the issue now? You can't see the toast, or the drawer is not working?

**Comment by kalvian1060** [comment]
issue is not show toast if clik on account header

**Comment by kalvian1060** [comment]
dawer is fine. toast in not showing

**Comment by kalvian1060** [comment]
sory for bad engglish..

**Comment by mikepenz** [comment]
can you please move the toast showing out of the condition, just to make sure it's not because the condition is never meet

**Comment by kalvian1060** [comment]
where the place right of toast?

**Comment by mikepenz** [comment]
just put it somewhere directly in the `onProfileChanged` so you see if it would be shown in general

**Comment by kalvian1060** [comment]
oke i move now. but @mikepenz  i like u code.. this what the name desain pattern on this project?? code very clean

**Comment by mikepenz** [comment]
Thank you very much

**Comment by mikepenz** [comment]
And did the toast show up?

**Comment by kalvian1060** [comment]
yes toast is show. thanks for it
