### ISSUE TITLE
get ID withHeader

### ISSUE THREAD

**Issue by dhamdani666** [mikepenz/MaterialDrawer#1937]
.withHeader(R.layout.header_material)
I use the withheader, I want to ask how to retrieve the id in the withheader so I can change it ?

**Comment by mikepenz** [comment]
@dhamdani666 which id?

You want to get it's view and access sub views?

This method returns the view of the header, then you can do whatever you want with it:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L274
