### ISSUE TITLE
Disable content when FullDrawer is open

### ISSUE THREAD

**Issue by feraguiba** [mikepenz/MaterialDrawer#1938]
I have two Drawers in my app: a fullDrawer and a miniDrawer with the corresponding Crossfader:

    crossFader = new Crossfader()
                .withContent(findViewById(R.id.fl_content))
                .withFirst(fullDrawer.getSlider(), firstWidth)
                .withSecond(miniDrawer.build(this), secondWidth)
                .withSavedInstance(savedInstanceState)
                .withGmailStyleSwiping()
                .build();

How can I enable the content (R.id.fl_content) only when the miniDrawer is displayed, so when the fullDrawer is displayed the content is disabled?
And when the content is disabled, how can I display the typical shadow that indicates the user that the content is not clickable?

**Comment by mikepenz** [comment]
@feraguiba well there is no such functionality as in your case there is no real `DrawerLayout` what you can do is to add a layout in front of your content, and set this visible / hidden depending on the dawer's visibility. and you will also set a color to it which is a little bit translucent. 

This is definitely no drawer issue, the use case for the `Crossfader` is not meant to block the content on the right side.

**Comment by feraguiba** [comment]
Thanks @mikepenz. I will follow your suggestions.
