### ISSUE TITLE
Add Profile Image to Drawer using Facebook Url

### ISSUE THREAD

**Issue by kkdroidgit** [mikepenz/MaterialDrawer#1939]
Hi Mike!,
Thanks for the awesome library!
I want to show the user profile picture from an Url in the DrawerImageLoader and am a bit confused on implementing it. This is what I've done;-

      final String ic_Url = "http://graph.facebook.com/" + bFacebookID + "/picture?type=square";

        //initialize and create the image loader logic
        DrawerImageLoader.init(new AbstractDrawerImageLoader() {
            @Override
            public void set(ImageView imageView, Uri uri, Drawable placeholder, String tag) {
                Picasso.with(imageView.getContext()).load(uri).placeholder(placeholder).into(imageView);
            }

            @Override
            public void cancel(ImageView imageView) {
                Picasso.with(imageView.getContext()).cancelRequest(imageView);
            }
        });

        final IProfile profile = new ProfileDrawerItem().withName(user_Name).withEmail(user_Email)
                .withIcon(ic_Url)
                .withIdentifier(100);

This doesn't seem to work. What am I missing?

**Comment by mikepenz** [comment]
@kkdroidgit the `DrawerImageLoader` has to be defined before the `Drawer` is created. 

Your code looks fine. (as shown here: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java#L26)

You set the `ProfileDrawerItem` to the `AccountHeader` during creation? Did you test if the url is really working?

**Comment by mikepenz** [comment]
@kkdroidgit  please also see the sample application in which this works.

**Comment by kkdroidgit** [comment]
Hey Mike, Thanks Now It works!
Yes, the problem was with the Url of Image. Thanks for the help

**Comment by trinhvanminh2009** [comment]
Glide.with(imageView.getContext()).load(uri).placeholder(placeholder).into(imageView);
//placeholder(placeholder) not found. How I can do that ?

**Comment by kkdroidgit** [comment]
Make sure you are initializing the Drawer Logic for Glide like this -

    DrawerImageLoader.init(new AbstractDrawerImageLoader() {
            @Override
            public void set(ImageView imageView, Uri uri, Drawable placeholder) {
                Glide.with(imageView.getContext()).load(uri).placeholder(placeholder).into(imageView);
            }

            @Override
            public void cancel(ImageView imageView) {
                Glide.clear(imageView);
            }

            @Override
            public Drawable placeholder(Context ctx) {
                return ContextCompat.getDrawable(ctx, R.drawable.avatar_placeholder);
            }

            @Override
            public Drawable placeholder(Context ctx, String tag) {
                return ContextCompat.getDrawable(ctx, R.drawable.avatar_placeholder);
            }
        });

**Comment by kkdroidgit** [comment]
Make sure you are initializing the Drawer Logic for Glide like this- 

      //initialize and create the image loader logic
        DrawerImageLoader.init(new AbstractDrawerImageLoader() {
            @Override
            public void set(ImageView imageView, Uri uri, Drawable placeholder, String tag) {
                Glide.with(imageView.getContext()).load(uri).placeholder(placeholder).into(imageView);
            }

            @Override
            public void cancel(ImageView imageView) {
                Glide.clear(imageView);
            }

**Comment by trinhvanminh2009** [comment]
I'm sure about initializing the  Drawer Logic for Gilde like you. But 
//placeholder(placeholder) not found. Can't resolve this method. How to fix that?

**Comment by mikepenz** [comment]
@trinhvanminh2009 which version of glide do you use? The above code is of glide 3.x 
If you use glide 4.x you have to adjust it for their new API

**Comment by trinhvanminh2009** [comment]
Thanks, Mike. I'm using version 4.0.0-RCO. I think it's new version. Why I don't have .placeholder in my version.

**Comment by mikepenz** [comment]
well glide (external library) they are free to change their API at any time. just check their source, documentation. I am sure they have replaced ith with something else. but that's not `MaterialDrawer` related. The DrawerImageLoader gives you the flexibility

**Comment by trinhvanminh2009** [comment]
Yeah!  which version of Glide do you use? Maybe I should change to get .placeholder.

**Comment by mikepenz** [comment]
the latest stable one. Which is 3.8.0 or so. 
As mentioned you can use 4.0.0-RC0 also, you just have to modify the code to fit their new API

**Comment by trinhvanminh2009** [comment]
Yeah! Thanks for supported.
