### ISSUE TITLE
.withTag on SwitchDrawerItem not working

### ISSUE THREAD

**Issue by sonovice** [mikepenz/MaterialDrawer#194]
Hey @mikepenz,
I've been trying to use the withTag-Feature of the SwitchDrawerItem like this:
```java
drawer.add(SwitchDrawerItem()
                    .withName("Name")
                    .withTag("Tag"));
```

And added this OnCheckedChangeListener:
```java
CompoundButton.OnCheckedChangeListener switchListener = new CompoundButton.OnCheckedChangeListener() {
    @Override
    public void onCheckedChanged(CompoundButton compoundButton, boolean b) {
        Log.d("SwitchListener", (String) compoundButton.getTag());
    }
};
```

Unfortunately `getTag()` always returns `null`.

**Comment by mikepenz** [comment]
@sonovice i think you mix up different tags. :D

as seen in the onCheckedChanged method you get the Tag of the View. The view of the CompoundButton does not contain the tag. 

You set the tag on the DrawerItem which is not returned by the onCheckedChanged listener. 

You should set the listener for the specific ToggleDrawerItem. I will see if i can improve this implementation.
