### ISSUE TITLE
How to implement onprofileimge click listner

### ISSUE THREAD

**Issue by PramUkesh** [mikepenz/MaterialDrawer#1941]
Hi  
Nice library dear
Hi I want to know how to implement onclick listener for profile image when user clicks on profile icon it should open an activity or fragment

**Comment by mikepenz** [comment]
@PramUkesh you just set the `OnAccountHeaderProfileImageListener` to your header...
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L400

The Builder provides all necessary methods

**Comment by PramUkesh** [comment]
Since I was new to programming  I don't know how to implement that 
So please give some tip 
Usage: when user clicks on profile image it opens an activity how to implement it.

**Comment by mikepenz** [comment]
Sorry I can not give beginners support. 

Opening an activity is a basic android stuff which can be found a thousand times on the web. 
Creating a listener annonymous class to pass via a method is the most basic thing from Java development.

**Comment by hosek** [comment]
Is possible to make whole profile screen clickable (name, email), not just profile image? Thanks

**Comment by mikepenz** [comment]
@hosek there is a listener for the case the user clicks on name, email

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L420
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L534

**Comment by usmaan-anwar** [comment]
@mikepenz as @hosek said there are just Listeners for Profile Image, Profile Selections and Header Long Click. Can you please let us know the name of Listener for Name, Email it will be really helpful. I want a Listener which works for all three combined Profile Icon+Name+Email.
Thanks in advance 👍 

**PS**: I have set the `withSelectionListEnabledForSingleProfile` to `false`.
