### ISSUE TITLE
PrimaryDrawerItem withIcon and withSelectedIcon from url

### ISSUE THREAD

**Issue by aitbaali** [mikepenz/MaterialDrawer#1942]
I've implemented (from the demo sample) 
[https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomUrlBasePrimaryDrawerItem.java](https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomUrlBasePrimaryDrawerItem.java)
and
[https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomUrlPrimaryDrawerItem.java](https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomUrlPrimaryDrawerItem.java)

the icon works fine, now, what is the appropriate way to handle the selected Icon?

**Comment by mikepenz** [comment]
@aitbaali depending on your needs, as this is not a default item, you can decide on how to handle it. 

Either you define a `StateListDrawable` as icon (but then you can't define from url) or you just tint it when it gets selected, or you just load a different icon from url when the item is selected. 

That's completely up to you, and independent of the lib

**Comment by aitbaali** [comment]
so when the item is selected, I've to change its Icon like:

```((UrlPrimaryDrawerItem) drawerItem).withIcon(url);
mDrawer.updateItem(drawerItem);```

and changing also all other Drawer Items to the unselected state, right?

**Comment by mikepenz** [comment]
@aitbaali well you can enable this: https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L249
on the `FastAdapter` (just call getAdapter() on the Draewr object)

And then the `bindView` method is called when an item get's selected automatically. So you can in the `bindView` method just check for (isSelected() or whatever this is called) and show a selected icon (just remember a different url for that state) 

As mentioned this is completly up to you and is just bound to the rules a `RecyclerView` defines

**Comment by aitbaali** [comment]
I ended up handling this like:
`public class UrlPrimaryDrawerItem extends PrimaryDrawerItem {

    @Override
    protected void bindViewHelper(BaseViewHolder viewHolder) {
        super.bindViewHelper(viewHolder);

        ImageView imageView = (ImageView) viewHolder.itemView.findViewById(R.id.material_drawer_icon);
        imageView.setVisibility(View.GONE);
        if (isSelected()) {
            if (selectedIcon != null && selectedIcon.getUri() != null) {
                imageView.setVisibility(View.VISIBLE);
                ImageHolder.applyTo(selectedIcon, imageView, "customUrlItem");
            }
        } else {
            if (icon != null && icon.getUri() != null) {
                imageView.setVisibility(View.VISIBLE);
                ImageHolder.applyTo(icon, imageView, "customUrlItem");
            }
        }
    }

    public UrlPrimaryDrawerItem withIcon(String url) {
        this.icon = new ImageHolder(url);
        return this;
    }

    public UrlPrimaryDrawerItem withSelectedIcon(String url) {
        this.selectedIcon = new ImageHolder(url);
        return this;
    }
}`

and enabling:
`mDrawer.getAdapter().withSelectWithItemUpdate(true);`

Thanks @mikepenz
