### ISSUE TITLE
Setting footer after switchDrawerContent

### ISSUE THREAD

**Issue by NikoDovidija** [mikepenz/MaterialDrawer#1943]
Greetings ,

I have been using your wonderful library in my application and it is working splendidly so far, props for all the work and effort. 

I am pulling some data from a server,  and on receive, I changed the items in the drawer accordingly.I am using the drawer with a toolbar
.So far, I thought the correct way to "reload" the drawer was to make a new instance of Drawer Builder
(i had 2 methods with different items but the same structure of new DrawerBuilder()),

```
private Drawer result:

private void initUserDrawer(Bundle savedInstanceState,User user) {
result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                 ....

private void initNoUserDrawer(Bundle savedInstanceState) {
result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                 ....

```
 but that has left me with some strange behavior (the back arrow froze, did not animate anymore). 
 It was probably related to the toolbar because I was trying to hide the sandwich icon with ` result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false);` but that did not happen.

**The problem now:**

Now I am using the switchDrawerContent method and it fixed my problem, but since I was using a custom header and footer I have a problem now showing the footer. In my switchDrawerContent I successfully replaced my header with:

` result.setHeader(View view);`

 but I can't seem to do the same with the footer. 

**Is there a way to replace/add a custom footer when using switchDrawerContent?** 

Thank you in advance for your time,

Regards,
Niko

**Comment by mikepenz** [comment]
You are not allowed to use `DrawerBuilder.build()` more than once.

Well possibly you can be a bit more specific. Why do you need to call `switchDrawerContent`?

If there is new data, you can just remove item's and add new item's. See some samples of updating item's here:
https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

**Comment by NikoDovidija** [comment]
I understand. 
So i should just update the values and add a new listener?

**Comment by NikoDovidija** [comment]
I had drawer items with identifiers, which i used to open activities and fragments acordingly. Each of the drawers should have their own

**Comment by NikoDovidija** [comment]
The no user drawer should have only a header  when the user logs in ,the header should become the footer, and a custom view becomes the new header. When the user loges out, the footer becomes the header again.

**Comment by NikoDovidija** [comment]
I can still post some more code for clearance if needed. 
I actually just need to know if there a way to change the footer after .build() ? 
Thank you

**Comment by mikepenz** [comment]
@NikoDovidija yes you are completely right. there is no direct method. 

You might be able to do it with the current version, by using this method: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L349 and just replacing the view with the new view. 

As an alternative you can get the `FooterAdapter` from the `Drawer` https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L256
'clear()' it's content and set a new item with the view you want: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerUtils.java#L342

**Comment by NikoDovidija** [comment]
Thank you for your answer and explanation. I managed to find an answer.
