### ISSUE TITLE
Lib broking design builder in Android Studio

### ISSUE THREAD

**Issue by a-kokulyuk** [mikepenz/MaterialDrawer#1944]
When i just adding library to gradle script (no changes in res or java), design builder throwing this exceptions:
```
- android.support.v7.widget.AppCompatImageView (Open Class, Show Exception, Clear Cache)
- xx.mapView.CMapView (Open Class, Show Exception, Clear Cache)
- android.support.v7.widget.Toolbar (Open Class, Show Exception, Clear Cache)
- android.support.constraint.ConstraintLayout (Open Class, Show Exception, Clear Cache)
- xx.mapView.CMapViewLayout (Open Class, Show Exception, Clear Cache)
- android.support.v7.widget.AppCompatTextView (Open Class, Show Exception, Clear Cache)
```

Exception from AppCompatImageView seems to be a reason
`java.lang.AssertionError: Entries for a declare-styleable should be after the array declaration.`

I'm using 'com.android.tools.build:gradle:2.3.1', and support libs 25.4.0 android android studio 3.0 canary 5

**Comment by mikepenz** [comment]
@a-kokulyuk well this library does not create any custom views, and just uses default Android provided components. so it is definitely related to the canary version of AS.

**Comment by a-kokulyuk** [comment]
I've checked also on stable studio v2.3, same issue, but different exception
`java.lang.NumberFormatException: For input string: "0x7f1700cb"`

Here is sample project (standard new project + gradle dependency)
[Sample](https://github.com/a-kokulyuk/MaterialDrawerStudioExample)

**Comment by mikepenz** [comment]
@a-kokulyuk hmmm it's strange. 

There are no array's in this project: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/values/attrs.xml

**Comment by mikepenz** [comment]
And you are definitely not using the support libs 26?
https://stackoverflow.com/a/44599195/325479

(In addition you might want to update to canary 6 of Android Studio)

**Comment by a-kokulyuk** [comment]
Yep, i've already updated.
I'm using 25.4.0
Both projects my and [Sample](https://github.com/a-kokulyuk/MaterialDrawerStudioExample) not working in both studios and have same exceptions:
2.3: `java.lang.NumberFormatException: For input string: "0x7f1700cb"`
3.0: `java.lang.AssertionError: Entries for a declare-styleable should be after the array declaration`

**Comment by mikepenz** [comment]
well all reports only point to the latest support libraries... https://stackoverflow.com/questions/44860016/android-support-library-26-0-0-beta2-preview-error-in-android-studio

**Comment by mikepenz** [comment]
https://issuetracker.google.com/issues/63054597
https://issuetracker.google.com/issues/62749978
https://issuetracker.google.com/issues/62614005

**Comment by a-kokulyuk** [comment]
Interesting thing that issue also happened on stable AS 2.3

**Comment by mikepenz** [comment]
as for the first exception there exists no info at all. 

you might want to output your gradle dependency tree to verify the lib versions which are used

**Comment by a-kokulyuk** [comment]
`+--- com.android.support:appcompat-v7:25.4.0
|    +--- com.android.support:support-annotations:25.4.0
|    +--- com.android.support:support-v4:25.4.0
|    |    +--- com.android.support:support-compat:25.4.0
|    |    |    \--- com.android.support:support-annotations:25.4.0
|    |    +--- com.android.support:support-media-compat:25.4.0
|    |    |    +--- com.android.support:support-annotations:25.4.0
|    |    |    \--- com.android.support:support-compat:25.4.0 (*)
|    |    +--- com.android.support:support-core-utils:25.4.0
|    |    |    +--- com.android.support:support-annotations:25.4.0
|    |    |    \--- com.android.support:support-compat:25.4.0 (*)
|    |    +--- com.android.support:support-core-ui:25.4.0
|    |    |    +--- com.android.support:support-annotations:25.4.0
|    |    |    \--- com.android.support:support-compat:25.4.0 (*)
|    |    \--- com.android.support:support-fragment:25.4.0
|    |         +--- com.android.support:support-compat:25.4.0 (*)
|    |         +--- com.android.support:support-media-compat:25.4.0 (*)
|    |         +--- com.android.support:support-core-ui:25.4.0 (*)
|    |         \--- com.android.support:support-core-utils:25.4.0 (*)
|    +--- com.android.support:support-vector-drawable:25.4.0
|    |    +--- com.android.support:support-annotations:25.4.0
|    |    \--- com.android.support:support-compat:25.4.0 (*)
|    \--- com.android.support:animated-vector-drawable:25.4.0
|         +--- com.android.support:support-vector-drawable:25.4.0 (*)
|         \--- com.android.support:support-core-ui:25.4.0 (*)
+--- com.android.support.constraint:constraint-layout:1.0.2
|    \--- com.android.support.constraint:constraint-layout-solver:1.0.2
\--- com.mikepenz:materialdrawer:5.9.4
     +--- com.android.support:appcompat-v7:25.4.0 (*)
     +--- com.android.support:recyclerview-v7:25.4.0
     |    +--- com.android.support:support-annotations:25.4.0
     |    +--- com.android.support:support-compat:25.4.0 (*)
     |    \--- com.android.support:support-core-ui:25.4.0 (*)
     +--- com.android.support:support-annotations:25.4.0
     +--- com.android.support:design:25.4.0
     |    +--- com.android.support:support-v4:25.4.0 (*)
     |    +--- com.android.support:appcompat-v7:25.4.0 (*)
     |    +--- com.android.support:recyclerview-v7:25.4.0 (*)
     |    \--- com.android.support:transition:25.4.0
     |         +--- com.android.support:support-annotations:25.4.0
     |         \--- com.android.support:support-v4:25.4.0 (*)
     +--- com.mikepenz:materialize:1.0.2
     +--- com.mikepenz:iconics-core:2.8.7
     \--- com.mikepenz:fastadapter:2.6.2
`
Nothing interesting here
I've also cloned yours repo (no code change), same exceptions in both studios

**Comment by a-kokulyuk** [comment]
I don't know how it happen, but iconics and fastadapter also broke preview
is i setting up library like this in works in both AS

```
  compile('com.mikepenz:materialdrawer:5.9.4@aar') {
        transitive = true
        exclude group: 'com.mikepenz', module: 'fastadapter'
        exclude group: 'com.mikepenz', module: 'iconics-core'
    }
    compile 'com.mikepenz:fastadapter:2.6.0'
    compile 'com.mikepenz:iconics-core:2.8.5' 
```

**Comment by illuzor** [comment]
I faced the same problem.
Some views like RecyclerView and ConstraintLayout are not displaing.
It happens independently of AS version or support libs version.
I can provide any info if needed.

**Comment by ubaidifti** [comment]
this fixed my  problem 
 maven {
            url "https://maven.google.com"
        }

**Comment by illuzor** [comment]
And the same problem with AboutLibraries. With 5.9.6 everything is ok, but with 5.9.7 not ok.
Problem somewhere between this two versions.

**Comment by mikepenz** [comment]
well v5.9.7 uses the new support libraries

**Comment by illuzor** [comment]
With "exclude" the problem not gone
```
compile('com.mikepenz:aboutlibraries:5.9.7@aar') {
        transitive = true
        exclude group: "com.android.support"
    }
```

**Comment by mikepenz** [comment]
anyone has the Android-Iconics or FastAdapter standalone in the project?

**Comment by mikepenz** [comment]
Seems to work for me. 

Android Studio 3.0.0 Canary 8
Support libs 26.x
Build Tools 26
Target 26
Compile 26
...
