### ISSUE TITLE
Dynamically change Drawer colors

### ISSUE THREAD

**Issue by bignadad** [mikepenz/MaterialDrawer#1945]
I am able to change all drawer colors in colors.xml or styles.xml

However, I am trying to change them dynamically and can't seem to figure it out. I saw this [post](https://github.com/mikepenz/MaterialDrawer/issues/881) but not sure what you mean. Should i rebuild the entire drawer with the updated colors? Do i need to update each item individually? 

I am updating the theme and accent colors in settings activity and when it closes and my main activity resumes i need the drawer to update.

Just trying to find the most efficient method.

**Comment by mikepenz** [comment]
@bignadad either you recreate that activity. 

or if you just want to update the colors, you can set the colors for the `DrawerItem`s and update them. Updating drawer items itself is mentioned in the README. 

There is no support though to modify all colors. you will have to manually adjust the view's colors from the drawer. like background, ...

**Comment by bignadad** [comment]
ok, thank you. I think it will be easier to recreate the activity and set the colors then. Thank you for your quick response.
