### ISSUE TITLE
Need help with some things

### ISSUE THREAD

**Issue by N-i-p-o-l** [mikepenz/MaterialDrawer#1946]
Hi! Need help please. This is my drawer - http://prntscr.com/fumnfx

1. I need move last item(with icon) down with some padding
2. Remove bar under accounts header or set color same as main (blue)
3. Set custom color on background image (i need white) and shadow circle color

How I can do this?

**Comment by mikepenz** [comment]
@N-i-p-o-l 

1. --> stickyDrawerItem?
2. --> disable the divider
3. --> just define a proper image, the drawer takes a square image. otherwise you can copy paste the header's xml to your project and set a background to those views.

**Comment by N-i-p-o-l** [comment]
1. Done
2. .withHeaderDivider(false);  .withFooterDivider(false);  .withStickyFooterDivider(false) doesn't give effect, but i changed color same as main, so it's ok for now
3. Icons from server have a transparent background, so I'm still thinking what to do

**Comment by mikepenz** [comment]
@N-i-p-o-l as mentioned you can also copy paste the xml of the header to your project, and apply a background to the `ImageView`s

a other solution is to just make the image square: https://stackoverflow.com/questions/19744120/how-to-create-a-square-bitmap-from-a-rectangular-bitmap-in-android 

you'd be able to write a transformatoin (or whatever this is called for the specific image loading lib you use) and just make the image square and fill it up with white

**Comment by N-i-p-o-l** [comment]
Ok, thanks!
