### ISSUE TITLE
Is there any drawer opening/closing listener..

### ISSUE THREAD

**Issue by rana01645** [mikepenz/MaterialDrawer#1948]
First of all Thanks for the awesome library... Now I need a drawer opening/closing listener.. Which will be called when the drawer open or close .. Is there any this type of listener available!

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1150

**Comment by rana01645** [comment]
Thanks for your reply mike :D :D 👍
