### ISSUE TITLE
Primary and secondary items looks the same

### ISSUE THREAD

**Issue by Remie-l** [mikepenz/MaterialDrawer#195]
`<color name="material_drawer_primary_text">#FF0000</color>` changes colors of primary and secondary text items.
`<color name="material_drawer_secondary_text">#00FF00</color>` change nothing.
And in generally, secondary and primary items visually do not differ from each other.

**Comment by mikepenz** [comment]
@Remie-l the Primary Item has a different height and the icon is smaller. 

You can see it. just see the sample application.

about the color. you are right. the current version has a small bug. will be fixed in the next version
