### ISSUE TITLE
SubItems access/update

### ISSUE THREAD

**Issue by Brtzn** [mikepenz/MaterialDrawer#1950]
Hi,
what's the proper way to access or update subitems?
`getDrawerItem` and `updateItem` methods of Drawer seem 
to only work with top level drawer items.

Thx
Mike

**Comment by mikepenz** [comment]
yes they only support top level items, and they most likely will never automatically handle sub items. 

If you want to change sub items and so on, you should check the direct api's of the ´FastAdapter´ project:
https://github.com/mikepenz/FastAdapter

**Comment by Brtzn** [comment]
Ok, I learned that the mentioned methods not only work with toplevel, but also with subitems of expanded items. With a little debugging (and getting more understanding of the underlying mechanisms) I got it working, thx.
