### ISSUE TITLE
Issue when update drawer items text after change to rtl in runtime

### ISSUE THREAD

**Issue by GoltsevEugene** [mikepenz/MaterialDrawer#1951]
Hi Mike.
I have an interesting issue now.

In my app I'm changing Locale and all layouts to rtl direction.
When I'm back in Activity with drawer, I'm calling updateDrawerItems.

In that method I'm preparing new list of items and use drawer.setItems(newItems).

When I'm changing to arabic language, it shows nothing.
But when I'm debugging items (before they are shown), they have correct arabic text!

PS. I tried drawer.updateItem and drawer.updateText - nothing helped.
Sometimes it doesn't work permanently, sometimes it doesn't work only at first time (I mean, after next Activity onResume and updateDrawerItems - it works, text is shown).

**Comment by mikepenz** [comment]
@GoltsevEugene sounds like some RTL switching issue. I am afraid I can't solve that. 
The system is switching and handling the RTL switching of the layouts. 

I suppose you can try to provide different layout's for the RTL case and it possibly will handle it different, but that's out of the scope of this project itself

**Comment by GoltsevEugene** [comment]
Okay, can I provide own layout for drawer items?

**Comment by mikepenz** [comment]
@GoltsevEugene either you copy paste the original xml of those items to your project (with the same name, the android build will take care of the rest) 

or you implement a CustomDrawerItem

**Comment by GoltsevEugene** [comment]
Heh, finally solved this with it:
`//1, cause 0 is header
        for (int i = 1; i < drawer.getRecyclerView().getChildCount(); i++) {
            TextView nameView = (TextView) drawer.getRecyclerView().getChildAt(i).findViewById(R.id.material_drawer_name);
            if (nameView != null) {
                nameView.setLayoutDirection(Localization.getInstance().isRTL() ? View.LAYOUT_DIRECTION_RTL : View.LAYOUT_DIRECTION_LTR);
            }
        }`

I believe that there is some weird bug in Android system.
When I try to set LayoutDirection on the top item layout, text is not displaying.

Anyway, thanks a lot for fast replies!!

**Comment by mikepenz** [comment]
@GoltsevEugene thanks for adding this here. 

You are welcome
