### ISSUE TITLE
Display below status bar on API >= 19 not working?

### ISSUE THREAD

**Issue by Jaguarhl** [mikepenz/MaterialDrawer#1954]
Hello. Just detected, that option .withDisplayBelowStatusBar(true) is not working properly on API greater then 19: is it true or false, status bar displays over menu item (in my case it is custom layout header). Is it bug, or I'm doing thomething wrong?
![materialrawer issue](https://user-images.githubusercontent.com/20791880/28262626-59a04f08-6aec-11e7-8224-848c5822294c.jpg)

**Comment by mikepenz** [comment]
@Jaguarhl `withDisplayBelowStatusBar` you should not need to set this at all. 

Check out the sample app. I don't use it. With the proper theme everything is working fine

**Comment by Jaguarhl** [comment]
For a few days I tryed to solve this problem and succesfully solved it with 3 different layouts. Each depends on API level: from 16 till 18 - standard. To 19 API level with margin and padding:
```<android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="?attr/colorPrimary"
        android:minHeight="?attr/actionBarSize"
        android:theme="?attr/actionBarTheme"
        android:layout_marginTop="@dimen/ab_padding_top"
        android:paddingTop="@dimen/ab_padding_top"/>
```
and greater then 19 standart again. But, from API 20 I added to custom menu header layout this View:
```<View
        android:layout_height="15dp"
        android:layout_width="match_parent"
        android:id="@+id/marginFromTop" />
```
I know that it is not the best solution, because later I will need to add layout for hi-def screens. But this solution works for me. Maybe I will experiment with theme, but it is strange.
And another question: could you point me to right direction - how to add animation to materialdrawer menu? For example - to hide some menu items except selected, and resume it later.

**Comment by mikepenz** [comment]
@Jaguarhl but did you try to use a different theme? 
What'S your setup? Did you check out the sample app. It does not need anything like this

**Comment by Jaguarhl** [comment]
My theme is:
```<!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowTranslucentStatus">true</item>
        <item name="android:windowContentOverlay">@null</item>
        <item name="material_drawer_divider">@color/divider</item>
        <item name="material_drawer_primary_text">@color/colorPrimaryText</item>
        <item name="material_drawer_secondary_text">@color/colorPrimaryText</item>
    </style>
```
I depends on design, and there not too much freedom )

**Comment by mikepenz** [comment]
hmmm one of those might break it though:
```xml
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowTranslucentStatus">true</item>
        <item name="android:windowContentOverlay">@null</item>
```

How do you init the Drawer. Do you use the default way or do you add it somewhere else in the view hierachy?

**Comment by Jaguarhl** [comment]
This was added in search of solution ) 
I init drawer by calling initDrawer() method in onCreate(). In method:
```LayoutInflater mInflater = LayoutInflater.from(this.getBaseContext());
View mCustomView = mInflater.inflate(R.layout.ls_menu_header, null);

... init UI elements in mCustomView ...

lsMenuDrawer = new DrawerBuilder().withActivity(this)
                .withTranslucentStatusBar(true)
                .withDrawerWidthRes(R.dimen.ls_mnu_width)
                .withSliderBackgroundColorRes(R.color.colorLeftSideMenu)
                .withHeader(mCustomView)
                .withHeaderDivider(false)
                .withPositionBasedStateManagement(false)
                .addDrawerItems(... and adding menu items...
```
This is current version. I had removed  .withDisplayBelowStatusBar(true) already.

**Comment by mikepenz** [comment]
hmmm but you do not use something like:
```
.withRootView(R.id.drawer_container)
```

and removing 
```
.withTranslucentStatusBar(true)
```
in addition didn't help either?

Did you check the sample apps drawer. This one is tested and works on all supported android versions. And also goes behind the StatusBar on android versions which are officially supported to do this

**Comment by Jaguarhl** [comment]
Oh, 
``` .withRootView(R.id.drawer_container) ``` 
will check tomorrow. Thank you.
I sow sample apps, but a few month ago.

And what can you advice me on animation question? )

**Comment by mikepenz** [comment]
Don't use it. I just asked if you have something like this in use (you did not post the whole drawer creation)

Well it depends on how and what you want to animate

**Comment by Jaguarhl** [comment]
For example - to hide some menu items except selected, and resume it later.

**Comment by mikepenz** [comment]
Well the items itself are displayed in an `RecyclerView` that means all rules which apply to a `RecyclerView` for animating also applies here. 

Basically the `DefaultItemAnimator` is set, and if you remove an item It will animate alpha out I guess. 

The MaterialDrawer uses internal the core of the `FastAdapter` so you can just call remove on a position and it will automatically notify the adapter...

**Comment by Jaguarhl** [comment]
Thank you. Will try it )

**Comment by mikepenz** [comment]
@Jaguarhl have you had chance to try it? 

Please report back. closing for now

**Comment by Jaguarhl** [comment]
I've tryed some things we talk about, but no changes. So, app works now in the needed way, and it's a time for next tasks. No time for searching root of problems with MateriaDrawer on different API versions. But in conclusion: API less then 18 works fine; API 19 - problem is coming, but solution differ from greater versions; API greater than 19 - different solution. All solved by different layouts:
API < 19:
```
<android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="?attr/colorPrimary"
        android:minHeight="?attr/actionBarSize"
        android:theme="?attr/actionBarTheme"/>
```
API 19:
```
<android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="?attr/colorPrimary"
        android:minHeight="?attr/actionBarSize"
        android:theme="?attr/actionBarTheme"
        android:layout_marginTop="@dimen/ab_padding_top"
        android:paddingTop="@dimen/ab_padding_top"/>
```
API greater than 19:
```
<android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="?attr/colorPrimary"
        android:minHeight="?attr/actionBarSize"
        android:theme="?attr/actionBarTheme" />
```

And in menu header layout for API greater than 19:
```
<View
        android:layout_height="15dp"
        android:layout_width="match_parent"
        android:id="@+id/marginFromTop" />
```
API less than 19 header do not include this View.

Hope, I explaned my solution )

**Comment by mikepenz** [comment]
@Jaguarhl thank you very much for your detailed solution. I am glad you got it working this way.

I still wonder what causing the problem. But if your solution works for you it's fine ;)
