### ISSUE TITLE
Why icon in AccountHeader blue by default?

### ISSUE THREAD

**Issue by ATumbler** [mikepenz/MaterialDrawer#1955]
Hi. AccountHeader.withIcon work fine but i not like blue selector by default. It's bad... How i can remove selector?

**Comment by ATumbler** [comment]
Help .. I see it BezelImageView why foreground is blue??

**Comment by ATumbler** [comment]
I have to modify the library. Usage is bad

**Comment by mikepenz** [comment]
Well the default placeholder uses the accent and primary color of your application. 

Change it in the `DrawerImageLoader`
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java#L52

**Comment by ATumbler** [comment]
No.. Not background, and selector. When i tap the icon he make foreground blue.

**Comment by ATumbler** [comment]
@mikepenz, my primary color is black, accent color is orange, why icon have blue :(
