### ISSUE TITLE
How I can reuse navigation drawer in fragments?

### ISSUE THREAD

**Issue by N-i-p-o-l** [mikepenz/MaterialDrawer#1959]
Hi. I Have a navigation drawer in main activity. It's common beetwen all fragments. Each fragment have own custom toolbar. When i replace fragment nav drawer is dissapear. Ok, i try link to existing main activity drawer from fragment and call buildForFragment with set custom toolbar, but it does not work. I dont wanna call each time DrawerBuilder with all params, i wanna reuse drawer in main activity. Do you have a solution?

**Comment by mikepenz** [comment]
@N-i-p-o-l you are not allowed to build the drawer more than once in one screen (well once per activity, fragment theoretically but that does not make sense). 

Why don't you simply init the `Drawer` in your activity, and then use the `Drawer` object to do any updates via your fragments you need?

**Comment by N-i-p-o-l** [comment]
Yes, I do so. I found the problem. Replaced fragment in activity container has a coordinator layout with toolbar (without coordinator layout, main drawer ok, don't dissapear). I will think how to get around

**Comment by mikepenz** [comment]
well in case you want to have the `ActionBarDrawerToggle` in the fragment itself it might be necessary that you bind this again and again for each fragment. and then you just call open/close on the drawer

**Comment by N-i-p-o-l** [comment]
ok, thanks

**Comment by kevinbarja** [comment]
I use the **Fragment Navigation Pattern** for this, check this [blog](https://www.toptal.com/android/android-fragment-navigation-pattern).
