### ISSUE TITLE
adjustResize not working

### ISSUE THREAD

**Issue by NamingException** [mikepenz/MaterialDrawer#196]
When you have a fragment with editText in it inside a scrollview and also a Navigation Drawer, when you focus the editText you can't scroll the contents of the fragment and the editText ends up behind the keyboard. If I remove the Navigation Drawer the editText is placed above keyboard and I can also scroll to view rest of content. This only happens on Lollipop.

**Comment by NamingException** [comment]
I found the problem. Its the translucent status bar. When its enabled you set the flag SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN 

```
 if (Build.VERSION.SDK_INT >= 19) {
                if (mTranslucentStatusBarProgrammatically) {
                    mActivity.getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
                }
            }
```

When I set withTranslucentStatusBar(false) the adjustResize is working again and I can scroll the layout when the keyboard is shown.

**Comment by mikepenz** [comment]
@NamingException yeah this is a known behavior of this FLAG. So i've implemented a util which will enable support for keyboards and this behavior. It lowers the layout size and adds enough padding to the bottom. 

You can enable this by calling `.keyboardSupportEnabled(activity, enabled)` on the Drawer.Result.
The sample application also contains a sample with this in use

**Comment by GreenSkinMonster** [comment]
Hi, 

I had same issue, and it took me some time to find this question.
`.keyboardSupportEnabled(activity, enabled)`  worked well with `.withTranslucentStatusBar(true)` .
Maybe this should be in the document?  Soft keyboard is used a lot.

Only one small problem, it will show a blue (colorPrimary) background before soft keyboard appear, which won't happen with `.withTranslucentStatusBar(false)` . 

I upload a video to show the problem.
https://youtu.be/tc158Otf5II

**Comment by mikepenz** [comment]
@GreenSkinMonster to get it working i've created the keyboardSupport function. It is in the sample app. The thing is that in fact this is no issue of the MaterialDrawer. It's Android functionality, and people don't know about this. There were other issues regarding this. If you have FullScreen the `adjustResize` won't work anymore. 

So to "fix" it i will resize the layout. as far as i can, i can't fix the display. the blue is your background color so you can change this.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/95

**Comment by mikepenz** [comment]
added the info here:
https://github.com/mikepenz/MaterialDrawer/blob/master/README.md#i-have-problems-with-the-softkeyboard-how-can-i-fix-this

**Comment by GreenSkinMonster** [comment]
@mikepenz Thank you for the reply and document update.
Sorry I missed those discussions.
I think they answered my question.

This a great project with great support.
Thanks.

**Comment by mikepenz** [comment]
@GreenSkinMonster no problem. 

Thanks ;)

**Comment by vanceanderson41** [comment]
@mikepenz It looks like this method was removed from the builder? I am encountering the issues claimed to be solved by this workaround and see no effect when calling it from the materialize object on the Drawer
