### ISSUE TITLE
Can I use GenericItemAdapter in MaterialDrawer?

### ISSUE THREAD

**Issue by chinkan** [mikepenz/MaterialDrawer#1961]
I have tried to implement a drawer using material drawer with generic model with two different list item layout. 

I just follow this example to implement but It result empty list in my drawer.
(Reference: https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/MultiTypeGenericItemActivity.java)

Is it MaterialDrawer support to use GenericItemAdapter for item adapter?

```orderedOrderLineFastItemAdapter = new FastItemAdapter();
        orderedOrderLineFastItemAdapter.withSavedInstanceState(savedInstanceState);
        orderedLineItemAdapter = new GenericItemAdapter<>(new Function<GenericOrderLineItem, GenericOrderLineListItem>() {
            @Nullable
            @Override
            public GenericOrderLineListItem apply(GenericOrderLineItem genericOrderLineItem) {
                if(genericOrderLineItem instanceof StagingOrderLineItem){
                    return new StagingOrderLineListItem((StagingOrderLineItem)genericOrderLineItem);
                }
                if(genericOrderLineItem instanceof OrderedOrderLineItem){
                    return new OrderedOrderLineListItem((OrderedOrderLineItem)genericOrderLineItem);
                }
                return null;
            }
        });

        result = new DrawerBuilder()
                .withActivity(getActivity())
//                .withHasStableIds(true)
                .withTranslucentStatusBar(false)
//                .withDisplayBelowStatusBar(true)
                .withSavedInstance(savedInstanceState)
                .withDrawerGravity(Gravity.END)
                .withStickyHeader(orderedListHeader)
                .withAdapterWrapper(orderedLineItemAdapter.wrap(orderedOrderLineFastItemAdapter))
                .withStickyFooter(orderedListFooter)
//                .withHeaderPadding(true)
//                .withFullscreen(false)
                .buildForFragment();
```

Thanks!
Sorry for my English!

**Comment by mikepenz** [comment]
@chinkan well theoretically yes, but I do not allow the adapter's to be changed right now. As all the default `DrawerItem`'s are anyways requireing a normal `ItemAdapter` 

What's the usecase?

**Comment by chinkan** [comment]
Hi @mikepenz 

I just want to have a order list in the drawer which contain ordered item and new added order item, and the layout for this two items is different and I want to reuse the layout which I have used in other page.

**Comment by mikepenz** [comment]
@chinkan this will change with the next major release, as I'll update to the FastAdapter v3 which will change things. 
For now I am sorry that this is not supported. 

You may be able to add the `IDrawerItem` interface to your item's and then you can use them in the drawer and in the other lists. And the Drawer also supports different item's themself as long as they implement the `IDrawerItem`
