### ISSUE TITLE
Themed profiles

### ISSUE THREAD

**Issue by fuentepa** [mikepenz/MaterialDrawer#1962]
Excuse my English

It is possible to have themed profiles? I want change color in the actionbar, buttons, etc by switching profiles

thanks in advance.

**Comment by mikepenz** [comment]
@fuentepa to theme `DrawerItem`s you need to provide a `CustomDrawerItem` (if you want to change colors other than the ones defined in the theme)

For the placeholder. Please see the `DrawerImageLoader`
