### ISSUE TITLE
Drawer open animation duration

### ISSUE THREAD

**Issue by ATumbler** [mikepenz/MaterialDrawer#1963]
How i can change animation duration for opening drawer?

**Comment by ATumbler** [comment]
For ex. 100ms

**Comment by ATumbler** [comment]
When i click hamburger icon

**Comment by mikepenz** [comment]
@ATumbler not supported by the `DrawerLayout` of the support libraries. Thus not supported here.

**Comment by mikepenz** [comment]
You can read more here: https://stackoverflow.com/a/19461195/325479

(the copy over sources does not work as the `MaterialDrawer` only works with the `DrawerLayout` or classes which extend the `DrawerLayout`)

**Comment by ATumbler** [comment]
Oh my god. I can get `DrawerLayout` by method `getDrawerLayout`.. ?

**Comment by mikepenz** [comment]
yes, but that does not allow you to modify the duratio. That's a component provided from the supportlibraries

**Comment by ATumbler** [comment]
Reflection ? :)

**Comment by mikepenz** [comment]
If you want to do this. :P just remember, no support for this. and there is a high chance this will break someday :D

**Comment by ATumbler** [comment]
I did not think that it was not easy. Thanks, great library!
