### ISSUE TITLE
Header RTL support issue

### ISSUE THREAD

**Issue by henengel** [mikepenz/MaterialDrawer#1964]
Hi Mike,
After setting up the drawer, I noticed an issue in the header.
The profile icon and name should appear on the right of the layout.

I already tried going over the issues here, and there seems to be a lot of reports of this issue, but not a clear answer.

Current configuration and solution tried:
1. Like your documentation says, I have set `getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);`
2. In my Application tag in the `Manifest.xml`, I have set `android:supportsRtl="true"`
3. I saw somewhere here that I need to set a custom header layout, but couldn't find any mehtod to do so in the Profile or `AccountHeaderBuilder.java` class.

Code:

```java
mDrawerHeader = new AccountHeaderBuilder()
				.withActivity(this)
				.addProfiles(
						new ProfileDrawerItem().withName("Chen Engel").withIcon(R.mipmap.ic_launcher_round)
				)
				.withTranslucentStatusBar(true)
				.withHeaderBackground(R.drawable.header)
				.build();

		mDrawer = new DrawerBuilder()
				.withActivity(this)
				.withToolbar(mToolBar)
				.withAccountHeader(mDrawerHeader)
				.withTranslucentStatusBar(true)
				.withItemAnimator(new AlphaCrossFadeAnimator())
				.addDrawerItems(
						//pass your items here
				)
				.withShowDrawerOnFirstLaunch(true)
				.build();
```

Issue refs that I have reviewed: #1451 , #1401 , #1402, #1364, #1259 , #1192 ... 

Also by the way, `withShowDrawerOnFirstLaunch(true)` doesn't seem to work though I still haven't tried to solve the issue.
Thanks

**Comment by henengel** [comment]
![screenshot_2017-07-21-22-10-48](https://user-images.githubusercontent.com/13081692/28479086-9cc868ae-6e63-11e7-8c53-f4045e5a22b4.png)

**Comment by mikepenz** [comment]
@henengel the header is working correctly as intended. I did not implement RTL support for the header as it was also not the case for google apps with the drawer. (Could have changed since then) 

There are no plans from my side to adjust this inside the library.
If you need to have this changed for your application, then you can simply copy and paste the `.xml` of the header to your project and adjust it to your needs (keep the id's the same'e and the view's types but otherwise you can adjust it to whatever is necessary)

`withShowDrawerOnFirstLaunch` will only show once when the app is first installed. this is tested and works in the sample

**Comment by henengel** [comment]
OK, thank you.
I'll adjust it and post here for other if may needed

**Comment by mikepenz** [comment]
@henengel great :)

**Comment by henengel** [comment]
RTL adjust:
1. Create new layout resource file named --> "material_drawer_header"
2. Paste the following code:

```java
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             android:layout_width="match_parent"
             android:layout_height="@dimen/material_drawer_account_header_height"
             android:clickable="true">

    <ImageView
        android:id="@+id/material_drawer_account_header_background"
        android:layout_width="match_parent"
        android:layout_height="@dimen/material_drawer_account_header_height"
        android:scaleType="centerCrop" />

    <RelativeLayout
        android:id="@+id/material_drawer_account_header"
        android:layout_width="match_parent"
        android:layout_height="@dimen/material_drawer_account_header_height">

        <com.mikepenz.materialdrawer.view.BezelImageView
            android:id="@+id/material_drawer_account_header_current"
            android:layout_width="@dimen/material_drawer_account_header_selected"
            android:layout_height="@dimen/material_drawer_account_header_selected"
            android:layout_alignParentStart="true"
            android:layout_alignParentTop="true"
            android:layout_marginBottom="@dimen/material_drawer_account_header_horizontal_bottom"
            android:layout_marginStart="@dimen/material_drawer_vertical_padding"
            android:layout_marginTop="@dimen/material_drawer_account_header_horizontal_top"
            android:clickable="true"
            android:elevation="2dp" />

        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_alignTop="@+id/material_drawer_account_header_current"
            android:gravity="right">

            <com.mikepenz.materialdrawer.view.BezelImageView
                android:id="@+id/material_drawer_account_header_small_first"
                android:layout_width="@dimen/material_drawer_account_header_secondary"
                android:layout_height="@dimen/material_drawer_account_header_secondary"
                android:layout_marginEnd="@dimen/material_drawer_vertical_padding"
                android:clickable="true"
                android:elevation="2dp"
                android:visibility="gone" />

            <com.mikepenz.materialdrawer.view.BezelImageView
                android:id="@+id/material_drawer_account_header_small_second"
                android:layout_width="@dimen/material_drawer_account_header_secondary"
                android:layout_height="@dimen/material_drawer_account_header_secondary"
                android:layout_marginEnd="@dimen/material_drawer_vertical_padding"
                android:clickable="true"
                android:elevation="2dp"
                android:visibility="gone" />

            <com.mikepenz.materialdrawer.view.BezelImageView
                android:id="@+id/material_drawer_account_header_small_third"
                android:layout_width="@dimen/material_drawer_account_header_secondary"
                android:layout_height="@dimen/material_drawer_account_header_secondary"
                android:layout_marginEnd="@dimen/material_drawer_vertical_padding"
                android:clickable="true"
                android:elevation="2dp"
                android:visibility="gone" />
        </LinearLayout>

        <LinearLayout
            android:id="@+id/material_drawer_account_header_text_section"
            android:layout_width="match_parent"
            android:layout_height="56dp"
            android:layout_alignParentBottom="true"
            android:layout_alignParentStart="true"
            android:layout_alignParentEnd="true"
            android:layout_marginBottom="@dimen/material_drawer_padding"
            android:layout_toStartOf="@+id/material_drawer_account_header_text_switcher"
            android:gravity="center_vertical"
            android:orientation="vertical"
            android:paddingEnd="56dp"
            android:paddingStart="0dp">

            <TextView
                android:id="@+id/material_drawer_account_header_name"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginStart="@dimen/material_drawer_vertical_padding"
                android:fontFamily="sans-serif-medium"
                android:gravity="start"
                android:textDirection="locale"
                android:lines="1"
                android:maxLines="1"
                android:textSize="@dimen/material_drawer_account_header_text" />

            <TextView
                android:id="@+id/material_drawer_account_header_email"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginStart="@dimen/material_drawer_vertical_padding"
                android:gravity="start"
                android:textDirection="locale"
                android:fontFamily="sans-serif"
                android:lines="1"
                android:maxLines="1"
                android:textSize="@dimen/material_drawer_account_header_text" />

        </LinearLayout>

        <ImageView
            android:id="@+id/material_drawer_account_header_text_switcher"
            android:layout_width="@dimen/material_drawer_account_header_dropdown"
            android:layout_height="@dimen/material_drawer_account_header_dropdown"
            android:layout_alignParentBottom="true"
            android:layout_alignParentEnd="true"
            android:layout_marginBottom="@dimen/material_drawer_account_header_dropdown_margin_bottom"
            android:layout_marginEnd="@dimen/material_drawer_vertical_padding" />

    </RelativeLayout>
</FrameLayout>
```

3. Good to go...

* Please note that the alignment of the header will be according to the local settings on the device.
In the case of situations where you intend to force an RTL layout, please test and adjust the code appropriately. (Of course, you are also welcome to post the code here for others :) )

**Comment by mikepenz** [comment]
@henengel does this one work properly in both cases?

**Comment by henengel** [comment]
Only tested on both LTR and RTL locales. (If on LTR locale displays ltr, and on RTL locale displays rtl).
In my case I don't need everything in RTL regardless of the local hence didn't test that use case...

**Comment by mikepenz** [comment]
ah ok I understand
Thanks a lot for adding it here

**Comment by mikepenz** [comment]
Added the `good to know` flag

**Comment by henengel** [comment]
@mikepenz 
Hi Mike,
So I have been working on the header layout to fully support RTL based on the layout direction and not locale.
While doing so I encountered an issue that I hope maybe you would know why it accrues, or maybe point me in a direction to solve it.

When the layout direction is LTR, the profile image, user name and email, and row icons all have the proper left layout margin of 16dp, and everything works as expected.
Now, when the layout direction is RTL the profile image and row icon have the proper layout margin on the right(also View.start), but the profile name and email are indented more than what is specified in XML.
Even when I completely remove the margins in this layout direction, there is still a layout margin on the right, that I can't figure out where it is coming from.
No matter what I do to eliminate the margin, I can't seem to get rid of it.
Any clue?

LTR:
![screenshot_2017-07-29-16-28-03](https://user-images.githubusercontent.com/13081692/28749652-41699ce2-74d7-11e7-9e50-77611a7bde11.png)

RTL:
![screenshot_2017-07-30-03-28-11](https://user-images.githubusercontent.com/13081692/28749654-4968f636-74d7-11e7-8804-47650011db64.png)

**Comment by henengel** [comment]
@mikepenz ?

**Comment by mikepenz** [comment]
@henengel I think that might be a result from here: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L1179
