### ISSUE TITLE
Primary/SecondaryDrawerItem initial background color.

### ISSUE THREAD

**Issue by GregoryIwanek** [mikepenz/MaterialDrawer#1965]
#Is there any possibility to set initial background color of Primary or SecondaryDrawerItem in ExpandableDrawerItem to chosen by me? Background of these items is transparent by default ( no attribute of any kind), so when I expand a list they have same background/color as a Drawer. 

I need to implement items with initial background color in expandable list, even when they are not focused. I tried to get Views responsible for them, but failed in doing so ( I'm playing with this library just since 2 days so I'm not very familiar with this that much).

Thanks!

**Comment by mikepenz** [comment]
@GregoryIwanek well getting the views won't work as this is displayed in a `RecyclerView` and thus the items are re-used. 

For custom behaviour you will need to implement a `CustomDrawerItem` or you just extend one of the existing. like shown a few times in the sample. 

https://github.com/mikepenz/MaterialDrawer/tree/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md
