### ISSUE TITLE
SwitchDrawerItem  missing icon in mini drawer

### ISSUE THREAD

**Issue by parmarravi** [mikepenz/MaterialDrawer#1966]
I would like to use the SwitchDrawerItem in the main primary section of the navigation bar  with icons displayed in mini drawer.
How to upgrade the lib file in the main project?
I manage to implement the functions by writing some extra lines of code in this Github file,
but  how can i wrap that file in .jar and use it in my project instead of using
compile('com.mikepenz:materialdrawer:5.9.2@aar).

**Comment by mikepenz** [comment]
@parmarravi I do not understand. 

Please us the official android way of including dependencies: 

```gradle
compile('com.mikepenz:materialdrawer:5.9.2@aar) 
```

*.jar files are not supported as the library contains resources.

**Comment by parmarravi** [comment]
I would like to add icon for a switch or a toggle in side bar .
i have attach the screen shot for what i am trying to achieve .Let me know how can i do it. 

![screen2](https://user-images.githubusercontent.com/7616089/28513874-7cecffc2-7075-11e7-8eb2-92581ff6e771.png)
![sreenshot1](https://user-images.githubusercontent.com/7616089/28513875-7cef0fc4-7075-11e7-83b6-1c6aecccae50.png)

**Comment by mikepenz** [comment]
@parmarravi ok but why would this require to add a *.jar to your project? 

A while ago I created a small sample commit to show how to adjust the MiniDrawer to allow custom items. You can see this herE:

https://github.com/mikepenz/MaterialDrawer/commit/8deedf8470f19c74ed6b826fd5aadc4eaed506da

**Comment by parmarravi** [comment]
I have an application for SmartLight where we need a switch button to turn on and off lights without opening the activity .the activity is for more advance features like changing color of lights.
When the user keeps on adding large number of light in activity it will be difficult for him to track which light is on and off.
The reason for adding this lib was to use the mini drawer and make ui really good. For example check out the screen shot.
![smartlightscreen2](https://user-images.githubusercontent.com/7616089/28515554-b2e85864-707b-11e7-8e24-5c515498aa32.png)
![smartlightsreen](https://user-images.githubusercontent.com/7616089/28515555-b2e9a7e6-707b-11e7-8de1-f8fb1280c0cb.png)

**Comment by mikepenz** [comment]
@parmarravi my link above shows how to implement a `CustomMiniDrawerItem` this should do the job

**Comment by parmarravi** [comment]
I have a question.
customMiniDrawerItem is not there is the newer 'com.mikepenz:materialdrawer:5.9.2@aar'. so how do i make change?

**Comment by mikepenz** [comment]
As you can see in the commit this was added. That's what you have to do. As mentioned the commit is showing how you can do it. It's custom behaviour

**Comment by parmarravi** [comment]
Thank you for help mike

**Comment by parmarravi** [comment]
I am getting this error after adding customMiniDrawer.
![minidrawererror](https://user-images.githubusercontent.com/7616089/28527720-0e9bf22e-70a9-11e7-8498-0033eb6f2c9c.png)

**Comment by mikepenz** [comment]
well the thing is that the `with*` methods still return the parent type. Extending does not change the return value. 

just keep your `miniResult` variable as `MiniDrawer` or do not chain the methods like htis

**Comment by parmarravi** [comment]
Can you show me how? I am a beginner so i am not getting exactly what to do.Sorry for trouble.

**Comment by mikepenz** [comment]
Sorry I can not give beginners support. 

It's plain java. there's nothing complicated about...

var = new CustomMiniDrawer();
var.with...;
var.withInnerShadow()..;
var....

**Comment by parmarravi** [comment]
Great that was an easy fix.thank you mike for help
