### ISSUE TITLE
Crossfader setSelection

### ISSUE THREAD

**Issue by RustamIbragimov** [mikepenz/MaterialDrawer#1968]
I have a material drawer and a crossfader. I want to fire setSelection function when some event happens. But, when I do this the selection changes  only in "big drawer" but not in crossfader.

**Comment by mikepenz** [comment]
@RustamIbragimov could it be that your `MiniDrawer` and normal `Drawer` are not properly linked together? Have you checked out the sample app

**Comment by RustamIbragimov** [comment]
I create drawer 
` 
val mDrawer = DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withTranslucentStatusBar(true)
                .withGenerateMiniDrawer(true).buildView()
`

then I create a crossfader
`
    val mCrossfader = Crossfader<GmailStyleCrossFadeSlidingPaneLayout>()
                .withContent(crossfade_content)
                .withFirst(mDrawer.slider, firstWidth)
                .withSecond(miniDrawer.build(this), secondWidth)
                .withSavedInstance(savedInstanceState)
                .withGmailStyleSwiping()
                .build()
`

And I link then 
`
mDrawer.miniDrawer.withCrossFader(CrossfadeWrapper(mCrossfader))
`

It looks like everything is like in a sample app

**Comment by mikepenz** [comment]
oh do you do the selection via code or manually?

**Comment by RustamIbragimov** [comment]
When I click on crossfader, everything works fine. 
But when I use this code
`        mDrawer.setSelection(identifier, false)`
it selects an item in drawer but not in crossfader

**Comment by mikepenz** [comment]
Makes absolutely sense. 

the `false` will prevent the listener from being called. The `MiniDrawer` and the normal `Drawer` are hooked together via the `listener`

So you will also have to set the selection on the `miniDrawer` directly (or you set the listener fireing to true, which is possibly not what you want) 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L410

**Comment by RustamIbragimov** [comment]
Oh, thanks, didn't know that mini drawer has this method. I tried to find something like this in crossfader.
