### ISSUE TITLE
RadioButton DrawerItem - Question

### ISSUE THREAD

**Issue by monakhv** [mikepenz/MaterialDrawer#197]
Is it possible somehow organize  RadioButton type of  DrawerItem?
Grouping by identifier   or tag.

**Comment by monakhv** [comment]
I try to use SwitchDrawerItem and ToggleDrawerItem to make them behave like radio buttons.
However both of theme ignore Checkable - property. According to the code it never use!
Is it the bug?

**Comment by mikepenz** [comment]
@monakhv the checkable method is used to disable the checked state of the items. (if you click it and it's the current view)
This is used for items like in the SimpleHeaderDrawerActivity:
https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/SimpleHeaderDrawerActivity.java#L101

If you require a logic that if one button disables the selection of the other you have to use the method. `withChecked`

**Comment by monakhv** [comment]
First of all. I'm sorry for so many stupid question. You did really grate job.

My main problem is I need organize RadioButtons group inside the Drawer.
I could not find anything like RadioButtonDrawerItem. 

I need some workaround and SwitchDrawerItem  looks quite good for that. The only problem I have it is programmatic method to block the user change switcher state. Is it possible? I believed that it can be done by checkable so I was wrong. 

My experiment show that the user can change state of switcher even if the SwitchDrawerItem   is in disable state.

**Comment by mikepenz** [comment]
@monakhv ok as far as i can tell the current SwitchDrawerItem or ToggleDrawerItem does not provide an api to disable the selection change of the toggle.

So i will have to add an api to deactivate the toggle button as it can be done with the real standalone controll
