### ISSUE TITLE
Arrow is not showing in Expandable Item.

### ISSUE THREAD

**Issue by atulgoswami21** [mikepenz/MaterialDrawer#1971]
Arrow is not showing in Expandable Item. I am using latest release.
Please help me.

i am using like this
```java
drawer.addItem(new ExpandableDrawerItem()
                .withName("Settings")
                .withIconColor(menu_color)
                .withIcon(GoogleMaterial.Icon.gmd_settings)
                .withIdentifier(8)
                .withSelectable(false)
                .withIsExpanded(false)
                .withArrowColor(Color.BLACK));
```

**Comment by mikepenz** [comment]
no sub-items?

**Comment by atulgoswami21** [comment]
Have three subitems primarydrawer item with badge. But not showing with or without them.

**Comment by mikepenz** [comment]
Hmmm @atulgoswami21 

Can you copy paste and try what I had in the sample for a long time: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L120

thanks

**Comment by atulgoswami21** [comment]
I have tried but no good news.

![screenshot_2017-07-28-16-27-29](https://user-images.githubusercontent.com/11611949/28714588-b3289256-73b1-11e7-8279-88073a2bf97f.png)

**Comment by mikepenz** [comment]
fascinating. is this with proguard or anything which might break it?
which support library version do you use?
which build tools, ...?

**Comment by Timmmeeeh** [comment]
I've got the same issue. Happens both with or without proguard enabled.
buildToolsVersion "26.0.1"
support library version: 26.0.0

**Comment by atulgoswami21** [comment]
I am not using proguard and below are tool's version info
    minSdkVersion = 15
    compileSdkVersion = 25
    targetSdkVersion = 25
    buildToolsVersion = "25.0.2"
    supportLibraryVersion = "25.4.0"
and gradle:2.3.3

**Comment by mikepenz** [comment]
@atulgoswami21 @Timmmeeeh can you please try the sample app I uploaded of the latest release. I enabled the expandable item again and I can see the arrow

**Comment by Timmmeeeh** [comment]
@mikepenz Installed the sample app. I can see the arrow.

**Comment by mikepenz** [comment]
@Timmmeeeh can you please try the latest library version again and see what happens?

**Comment by Timmmeeeh** [comment]
@mikepenz Works again for me using v5.9.5

**Comment by atulgoswami21** [comment]
Thanks!! now it working perfectly.
