### ISSUE TITLE
what should i do to remove the first Divider ?

### ISSUE THREAD

**Issue by iota9star** [mikepenz/MaterialDrawer#1972]
i'm sorry my poor english ,example:

![uc 20170730110519](https://user-images.githubusercontent.com/21272154/28750264-a1a97326-7517-11e7-9605-f85a83d60ba6.png)
![qq_pic_merged_1501384032621](https://user-images.githubusercontent.com/21272154/28750269-b8314498-7517-11e7-847e-9922e1808fd1.jpg)

thanks

**Comment by zsmb13** [comment]
You can remove that divider by adding `.withHeaderDivider(false)` to your builder.

**Comment by iota9star** [comment]
thank you very much .

**Comment by mikepenz** [comment]
@zsmb13 thanks for answering :)
