### ISSUE TITLE
DrawerBuilder is missing

### ISSUE THREAD

**Issue by Jspascal** [mikepenz/MaterialDrawer#1974]
Hello,
I recently dowload you library via gradle, but unfortunately it doesn't contains the class DrawerBuilder. I don't know why. Can you fix this issue, please?
Thank you

**Comment by mikepenz** [comment]
@Jspascal it is definitely included. please clean, sync gradle, make sure everything is downloaded and ready. 

(I decompiled the online available library and it is in)

**Comment by mikepenz** [comment]
<img width="274" alt="screen shot 2017-07-30 at 11 04 37" src="https://user-images.githubusercontent.com/1476232/28752051-e4fa009c-7516-11e7-82fe-6725fc053f68.png">

**Comment by Jspascal** [comment]
I saw it. It's present, but i can't import it into my activity. I will try to make all these operations.
Thank you for feedback
