### ISSUE TITLE
overriding "dimes" padding values isn't working  

### ISSUE THREAD

**Issue by AlaaZarifa** [mikepenz/MaterialDrawer#1979]
I know changing these values are against MD guidelines, but it's necessary for my case.!

I override some values of the "dimens" file and some works and some won't..!
the first two worked normally, but when I tried to make the padding of the icon a lot less nothing happen..!? can you help with..!

```
  <!-- worked -->
  <dimen name="material_drawer_item_primary_text">19sp</dimen>
  <dimen name="material_drawer_item_primary">55dp</dimen>
  
  <!-- did not -->
  <dimen name="material_drawer_item_primary_icon_padding">2dp</dimen>
  <dimen name="material_drawer_padding">2dp</dimen>
```
![issue](https://user-images.githubusercontent.com/18426012/28876275-534c0b8a-77a1-11e7-9e13-3448fe63dea5.png)

**Comment by mikepenz** [comment]
@AlaaZarifa if you need a different style which is not supported by default. Please implement your own `CustomDrawerItem`

https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md

**Comment by AlaaZarifa** [comment]
humm.. the links not providing a detailed tutorial for the process, but thanks anyway..!

**Comment by mikepenz** [comment]
@AlaaZarifa it definitely does as there are some samples shown how to implement custom drawer items. https://github.com/mikepenz/MaterialDrawer/tree/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems

It is possible to modify everything to fit someone's needs. But I can't to tutorials for every ones special requests
