### ISSUE TITLE
No resource found - MaterialProgressBar style

### ISSUE THREAD

**Issue by kolorszczak** [mikepenz/MaterialDrawer#1980]
Support version: 
`25.3.1`
MaterialDrawer version: 
`5.9.5`
Project gradle repositiories order: 
```
allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}
```
Dependecies:
```
compile ("com.mikepenz:materialdrawer:5.9.5@aar") { transitive = true }
compile ("com.mikepenz:fastadapter:2.6.0@aar")
compile ("com.mikepenz:materialize:1.0.3@aar")
compile ("com.mikepenz:iconics-core:2.9.1@aar")
compile ("com.mikepenz:fastadapter-extensions:2.6.0@aar")
```
Error:
```
C:\Users\UserName\.android\build-cache\c986dd65c8aec1d91cc11f1dde4658dac8d27e60\output\res\layout-v14\md_stub_progress.xml
Error:(23, 14) No resource found that matches the given name (at 'style' with value '@style/Widget.MaterialProgressBar.ProgressBar.Horizontal').

C:\Users\UserName\.android\build-cache\c986dd65c8aec1d91cc11f1dde4658dac8d27e60\output\res\layout-v14\md_stub_progress_indeterminate.xml
Error:(15, 12) No resource found that matches the given name (at 'style' with value '@style/Widget.MaterialProgressBar.ProgressBar').

C:\Users\UserName\.android\build-cache\c986dd65c8aec1d91cc11f1dde4658dac8d27e60\output\res\layout-v14\md_stub_progress_indeterminate_horizontal.xml
Error:(19, 12) No resource found that matches the given name (at 'style' with value '@style/Widget.MaterialProgressBar.ProgressBar.Horizontal').

C:\Users\UserName\ProjectName\app\build\intermediates\res\merged\debug\layout-v14\md_stub_progress.xml
Error:(23, 14) No resource found that matches the given name (at 'style' with value '@style/Widget.MaterialProgressBar.ProgressBar.Horizontal').

C:\Users\UserName\ProjectName\app\build\intermediates\res\merged\debug\layout-v14\md_stub_progress_indeterminate.xml
Error:(15, 12) No resource found that matches the given name (at 'style' with value '@style/Widget.MaterialProgressBar.ProgressBar').

C:\Users\UserName\ProjectName\app\build\intermediates\res\merged\debug\layout-v14\md_stub_progress_indeterminate_horizontal.xml
Error:(19, 12) No resource found that matches the given name (at 'style' with value '@style/Widget.MaterialProgressBar.ProgressBar.Horizontal').
```

**Comment by mikepenz** [comment]
@kolorszczak well the libs use support library 26, which also requires compile 26. 

If you do not use this, you have to either exclude the support libs of my library or you use an older version using older support libraries

**Comment by kolorszczak** [comment]
@mikepenz 
I've updated:

```
support libs version: 26.0.0
buildToolsVersion: 26.0.0
comileSdkVersion: 26
targetSdkVersion: 26
```

This does not changed almost anything - I've just getting one more warning:

`Warning: string 'status_bar_notification_info_overflow' has no default translation.`

**Comment by mikepenz** [comment]
well the above is almost definitely a sign that there are some different variants of the support libraries. 
If you want to force same versions you can do something like this:

```java
configurations.all {
    resolutionStrategy.force "com.android.support:support-v4:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:appcompat-v7:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:cardview-v7:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:recyclerview-v7:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:design:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:percent:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:preference-v14:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:customtabs:${versions.supportLib}"
    resolutionStrategy.force "com.android.support:support-annotations:${versions.supportLib}"
}
```

**Comment by kolorszczak** [comment]
Same results. 
If i force support version to 26.0.0 there is 7 errors + 1 warning, and if the forced version is 25.3.1 then there is just 7 errors without warning.

**Comment by mikepenz** [comment]
@kolorszczak but the file which shows the error is not even one of my projects: 
https://github.com/afollestad/material-dialogs/blob/master/core/src/main/res/layout-v14/md_stub_progress.xml

Why do you think the error is caused by the MaterialDrawer?

Have you also tried a clean? 
Cleaned the build cache?
Killed gradle?
Restarted AS?
Restarted the PC :D?

**Comment by mikepenz** [comment]
Did the issue solve itself?

**Comment by timbaev** [comment]
Oh, I faced with similar problem. I update all to new version 26.0.0 and com.android.support elements (for example recyclerView or CoordinatorLayout) in layouts not showing (failed to instantiate one or more classes). I solved with problem - I changed MaterialDrawer version to 5.9.0 in gradle and now all works perfectly. I don't know what is the reason for this

**Comment by ubihacks** [comment]
Try dis at the end of app level build 
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.3.0'
            }
        }
    }
}

**Comment by mikepenz** [comment]
@ubihacks thanks for adding this here too
