### ISSUE TITLE
How can i change user avatar in runtime

### ISSUE THREAD

**Issue by sh3lan93** [mikepenz/MaterialDrawer#1981]
I have an activity that enable user to update his/her profile. 
He/She can change his/her avatar. 
I want to change the account header user avatar to new one user selects in runtime.

**Comment by mikepenz** [comment]
@sh3lan93 simply change the `Profile`s image, and then notify the `AccountHeader` about the change


https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L244
