### ISSUE TITLE
Change Hamburger Icon Padding/Layout Margin?

### ISSUE THREAD

**Issue by GitUser4732** [mikepenz/MaterialDrawer#1982]
Hello,
The hamburger icon seems to have a large padding/layout margin. The goal is to get the searchbar centered between the hamburger icon and the profile image, but i cant get the left side any closer to the hamburger icon. 

Is there a way to change it so the searchbar in picture can be closer to Hamburger Icon? 

Thanks

**PREVIEW**

![preview](https://user-images.githubusercontent.com/30483593/28999829-d43916b6-7a1c-11e7-9f6a-082a2b26e758.png)

**RESULT FROM HAMBURGER ICON BEING ADDED BY MATERIAL DRAWER**

![nav_icon_padding_matdrawer](https://user-images.githubusercontent.com/30483593/28999816-ffc64fac-7a1b-11e7-847c-036fcf42dd9f.png)

**Comment by mikepenz** [comment]
the paddings are controlled by the system. not by the MaterialDrawer. 
The MaterialDrawer adds just a convinient method to automatically handle the `ActionBarDrawerToggle` but how this is working is no functionality of the lib itself

**Comment by Arnie09** [comment]
How to change that margin though???
