### ISSUE TITLE
ActionMode is duplicating the Toolbar

### ISSUE THREAD

**Issue by oscargrgm** [mikepenz/MaterialDrawer#1983]
I'm using the Drawer with my own Toolbar and I'm not able to make that only one bar appears with the ActionMode activated. Here is the Toolbar and Drawer declarations:

```
Toolbar mToolbar = (Toolbar) findViewById(R.id.toolbar);
if (mToolbar != null) {
    setSupportActionBar(mToolbar);
    mToolbar.setNavigationIcon(R.drawable.menu_hamburger);
    mToolbar.setTitleTextColor(ContextCompat.getColor(this, android.R.color.white));
    mToolbar.setBackgroundColor(ContextCompat.getColor(this, R.color.colorPrimary));
    mToolbar.setNavigationOnClickListener(this);
}

DrawerBuilder mBuilder = new DrawerBuilder(this)
          .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
              @Override
              public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                  /* Some stuff */
                  return true;
              }
          });
mDrawer = mBuilder.build();
```

I've also added the `<item name="windowActionModeOverlay">true</item>` in my styles.

In my `AndroidManifest.xml` I've set the Activity theme to `@style/MaterialDrawerTheme.Light`.

Even adding `mDrawer.withToolbar(mToolbar);` is not working. Any suggest of what should I do?

**Comment by oscargrgm** [comment]
Ok, I've solved the problem just removing the `style` in my `AndroidManifest.xml`. Do you know why this was causing the duplicity?

**Comment by mikepenz** [comment]
@oscargrgm well it was most likely caused by a wrong combination of toolbar/actionbar/ and the windowActionModeOverlay flag. 

Great that it's working now
