### ISSUE TITLE
Support with action bar ?

### ISSUE THREAD

**Issue by phukhanhlee** [mikepenz/MaterialDrawer#1984]
My app now support action bar (not toolbar). 
Follow instruction, My app is ready for drawer but it below actionBar and don't have menu icon, it still back button. I must swipe to show menu list. It should have menu icon instead of back icon.

<img width="279" alt="screen shot 2017-08-09 at 10 34 32 am" src="https://user-images.githubusercontent.com/943472/29104213-5a34abf8-7cee-11e7-8577-ca028f38eab8.png">

new DrawerBuilder().withActivity(this).build();

Can we still support actionbar and working like normal marterialDrawer like demo app ?

**Comment by mikepenz** [comment]
@phukhanhlee you have to manually do it and find some manually thing showing the animation. 

The icon itself is only supported (already by google) just for the Toolbar. (The ActionBarDrawerToggle) 

I highly recommend you to use a `Toolbar` what's preventing you from doing so?

**Comment by phukhanhlee** [comment]
Because my projects is old projects which use actionBar and menu item like search, bookmark on right.

I use this lib https://github.com/Arasthel/GoogleNavigationDrawerMenu but it not material design, and no longer support.

**Comment by mikepenz** [comment]
well as mentioned the hamburger icon itself is not a core thing of this lib anyways. It is just a convinience method of automatically adding it in case of a Toolbar. In case of no toolbar you simply set the icon you want to, and then you use the `open` or `close` methods of the `Drawer`

**Comment by phukhanhlee** [comment]
Thanks Mike ! I have just add toolbar and it works like i want !
