### ISSUE TITLE
How to close profileSelector when the drawer closes

### ISSUE THREAD

**Issue by Playdric** [mikepenz/MaterialDrawer#1985]
Hi !

I made an app using your fabulous drawer (Thakns btw)

And when I open the drawer, then the profile selector, then close the drawer without closing the profile selector, the profile selector stays open when I re open the drawer.

I wonder if it's possible to tell the drawer to close the profile selector when closing the drawer.

Regards

**Comment by mikepenz** [comment]
@Playdric you are welcome. 

You can set a listener to the drawer and listen for the `close` callback. 

And in that case you can use the following two methods to check if the profile selector is shown + in case it is shown to toggle it:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L110
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L101

**Comment by Playdric** [comment]
Works fine thanks a lot !
