### ISSUE TITLE
Load icon from url

### ISSUE THREAD

**Issue by phukhanhlee** [mikepenz/MaterialDrawer#1986]
Does MaterialDrawer support load icon from url string ?

For static icon:
item = new PrimaryDrawerItem().withName(getString(R.string.email_developer)).withIcon(R.drawable.ic_action_message).withIdentifier(GoogleNavigationItem.EMAIL_DEVELOPER_ITEM).withSelectable(false);

I tried this but seem not working ?
item = new PrimaryDrawerItem().withName(getString(R.string.email_developer)).withIcon(new ImageHolder(resourceURL)).withIdentifier(GoogleNavigationItem.EMAIL_DEVELOPER_ITEM).withSelectable(false);

resourceURL is a url String of image.

**Comment by mikepenz** [comment]
@phukhanhlee the default `PrimaryDrawerItem`'s do not support this. And there is no plan do feature this in the future. 

You can although get this working using a `CustomDrawerItem`
The sample app contains one doing exactly this:

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomUrlPrimaryDrawerItem.java

It will also need the `DrawerImageLoader` for the image loading logic (see the readme for more details)

**Comment by phukhanhlee** [comment]
Thanks Mike !
