### ISSUE TITLE
Handle both ExpandableDrawer row and arrow click.

### ISSUE THREAD

**Issue by slymnozdmrc** [mikepenz/MaterialDrawer#1987]
Hi,
This is issue may be related with #1728 and #1158 but this still confused me. I want to handle both row and arrow click to manage something. Arrow click just show and hide subitems of Expandabledrawer and row click should be display something on my fragment about all subitems. I added clicklistener to IconicsImageView in viewholder than i can handle arrow click but how can i handle ExpandableDrawer expanded or not. Maybe some people also need this feature in the future like me.
Regards.

**Comment by mikepenz** [comment]
@slymnozdmrc what'S confusing you about this: https://github.com/mikepenz/MaterialDrawer/issues/1158#issuecomment-207995248 ?

**Comment by slymnozdmrc** [comment]
I confused about passing adapter to ExpandableDrawerItem because of implementation of my logic. But I change so much thing and create first DrawerBuilder than add other DrawerItem to DrawerBuilder now everything clear thanks for your interest. One Last Question, Why do not prefer to add this as a feature ? Could using like this cause other problems?

**Comment by mikepenz** [comment]
@slymnozdmrc there probably wouldn't be much of an issue adding it, but right now i'd prefer keep the code simple, and adding this functionality is not too complicated especially with the other comments with full working solutions. 

there might also be a bigger refactor incoming with the next big release which could make it obsolete right now.

**Comment by mikepenz** [comment]
Close for now. Might be releavant again in the future though
