### ISSUE TITLE
How to change color of menu icon,hint SearchView,back icon when use MaterialDrawerTheme.Light

### ISSUE THREAD

**Issue by phukhanhlee** [mikepenz/MaterialDrawer#1988]
I need change all to white color. Seem follow your document, i just can change menu color theme.

<img width="277" alt="screen shot 2017-08-12 at 9 50 48 pm" src="https://user-images.githubusercontent.com/943472/29241667-61f675ee-7fa8-11e7-9f12-6018fb0a1754.png">

<img width="287" alt="screen shot 2017-08-12 at 9 51 07 pm" src="https://user-images.githubusercontent.com/943472/29241668-66462ff4-7fa8-11e7-8ac9-4f0f4b128e3b.png">

<img width="283" alt="screen shot 2017-08-12 at 9 54 06 pm" src="https://user-images.githubusercontent.com/943472/29241701-ccb26e06-7fa8-11e7-8e9c-516a977833d6.png">

menu icon,back icon, hint search text,text search need to change to white color. Can we change it ? 
Seem this belong to style of toolbar ?

**Comment by mikepenz** [comment]
@phukhanhlee toolbar's need their own theme set. That's not related to the `MaterialDrawer` or it's theme

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/activity_sample_dark_toolbar.xml#L13

**Comment by phukhanhlee** [comment]
Thanks Mike!
