### ISSUE TITLE
The drawer gets stuck in an "open" position while using Activity.recreate() method

### ISSUE THREAD

**Issue by inteist** [mikepenz/MaterialDrawer#1990]
I setup the drawer in the onCreate method of an activity and tie it to a burger button on the custom toolbar that is supposed to open the drawer once clicked. Everything works fine until the activity is restarted (there are certain use cases that warrant that) using the `this.recreate()` method.

The drawer is stuck in an open position and would not open after that. I tried 
```
drawer.close();
drawer.open();
```
which did not help
If I null the drawer and completely recreate it (I use a helper class - DrawerConfigurator) so basically doing 
```
DrawerConfigurator.reset();
//which basically does
//DrawerConfigurator.drawer= null;
```
then when I go back to the activity that gets recreated the drawer is open and is operational but I don't want it to be open when I get back.

my `withOnDrawerItemClickListener` method returns `false` to close the drawer when option is clicked. And otherwise it performs flawlessly with the problem only appearing with the recreate() method.

Can you please look into that. I have been trying to figure this out and find a workaround for a long time now but It feels wrong since it looks like the issue is within the lib itself somewhere and working around it is not the right thing to do, especially given the fact that I could not really find a satisfactory work around. The closest I got is what I described above.

**Comment by inteist** [comment]
I just tested
```
            Intent i = getIntent();
            this.finish();
            startActivity(i);
```

which leads to exactly the same behavior. I did not check the `recreate()` source code but it is must be little different because when doing shared animations the recreate() works while the manual restart doesn't. In this case both methods to restart activity fail however.

**Comment by mikepenz** [comment]
@inteist can you please try to directly access the `DrawerLayout` of the `Drawer` object. If this does not allow you to open close, then it is no library issue but a `DrawerLayout` issue (which I do not control)

**Comment by mikepenz** [comment]
@inteist there is an official recreate call on the `Activity` by the way https://stackoverflow.com/a/2488427/325479

**Comment by inteist** [comment]
Yes, that is what I was using but I also tested the

```
           Intent i = getIntent();
            this.finish();
            startActivity(i);
```
just in case with exact same result. 

all the methods within the DrawerLayout require parameters passed and I am not sure what exactly would be the right ones.

Can you give me a little more guidance with a snippet to check whether the layout is open and also to directly call the layout to open.

**Comment by mikepenz** [comment]
@inteist as mentioned that's the `DrawerLayout`. It's an external component: https://developer.android.com/reference/android/support/v4/widget/DrawerLayout.html

The MaterialDrawer just uses it.

**Comment by inteist** [comment]
I did some more debugging and analyzing and it looks like the drawer is not displayed. It is not stuck in the open position like I thought, rather it is not visible and after the first click on the burger it sure is "stuck" in the open position. 


Are you using the DrawerLayout from support library/SDK and are you saying this is an issue with the support library/SDK?

**Comment by mikepenz** [comment]
@inteist yes I use the `DrawerLayout` from the support libraries, nothing custom. 

If you do not have some weird handling of your drawer, and create it in the oncreate each time it is called you are fine.

**Comment by sandeshsk** [comment]
Hello How to make drawer open always. I have tried By setlockmode but it is locking the main UI. I have used build method to create drawerLayout. Is there any solution?

**Comment by inteist** [comment]
@mikepenz  – I couldn't make it work I have realized with the new changes I do not need to restart the activity in which case everything seem to work as expected. 

I guess the problem is somewhere with the DrawerLayout and Google fixes it.
