### ISSUE TITLE
OnCheckedChangeListener is not being triggered

### ISSUE THREAD

**Issue by thiago-tallison** [mikepenz/MaterialDrawer#1992]
Well, I want to put some `SwitchDrawerItems` in the subitems of a` ExpandableDrawerItem`. Basically, I create those subitems according to the datas retrieved from Firebase. I want the first subitem checked always by default. It works fine, but I have implemented the callback `OnCheckedChangeListener` and added it to each one. Here is the part of the code I create the subitems:

```
 List<SwitchDrawerItem> newServicesSubitem = new ArrayList<>();

for (DataSnapshot snapshot : dataSnapshot.getChildren()) {
    Service service = snapshot.getValue(Service.class);

    if (service != null) {
        long itemId = UUID.fromString(service.getId()).getMostSignificantBits();

        SwitchDrawerItem switchDrawerItem = new SwitchDrawerItem()
                .withLevel(2)
                .withIdentifier(itemId)
                .withName(service.getName())
                .withDescription(service.getDescription())
                .withOnCheckedChangeListener((OnCheckedChangeListener) presenter);

        newServices.add(service);
        newServicesSubitem.add(switchDrawerItem);
    }
}

presenter.updateCurrentServiceSubtems(newServicesSubitem);
```

where the `presenter` implements `OnCheckedChangeListener`. So far all works fine, the subitem are added on `ExpandableDrawerItem` as expected.

Later, I use `withChecked()` method to check the first item and change its state to checked, but the listener implemented by `presenter` interface is not being triggered. 

```
if (mDrawer.getDrawerItem(ITEM_CURRENT_SERVICE).getSubItems().size() > 0) {
    ((SwitchDrawerItem) mDrawer.getDrawerItem(ITEM_CURRENT_SERVICE).getSubItems().get(0)).withChecked(true);
    mDrawer.updateItem((IDrawerItem) mDrawer.getDrawerItem(ITEM_CURRENT_SERVICE).getSubItems().get(0));
}
```

So, the `OnCheckedChangeListener` is not being called when I change the state of first sub item programmatically, but when I check manually it works (the callback is triggered).

**NOTE**: English is not my first language, so if one thing is not clear let me know.

**Comment by mikepenz** [comment]
@thiago-tallison could you please create a simple example (open-able in AS) to showcase the issue, would be a lot easier to resolve it

**Comment by mikepenz** [comment]
Please report back. Close for now
