### ISSUE TITLE
How can I change to color email text?

### ISSUE THREAD

**Issue by steam0111** [mikepenz/MaterialDrawer#1993]
I want to have custom email color.

**Comment by mikepenz** [comment]
@steam0111 you want to change only the e-mail color. where?

**Comment by mikepenz** [comment]
If you want to modify it here, just copy paste that layout to your project and adjust it to your needs:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml#L91

If you want to change it in the item. there is a setter for the color: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L125

**Comment by ahmedsaber00** [comment]
@mikepenz 
i want to make account header name color white and account header email red
when i use this method `withTextColorRes` both of them changed , how i make them with different colors ?

i tried to use this layout in my project m but the color become white for both of them also
https://github.com/mikepenz/MaterialDrawer/blob/v5.9.1/library/src/main/res/layout/material_drawer_header.xml


how can make a color for name and another color for email in account header profile?

**Comment by mikepenz** [comment]
@ahmedsaber00 the color is set programatically. it's not possible without modifying it manually after the header was build.

**Comment by steam0111** [comment]
Actually, it's eazy , I did how you said, Thanks a lot

**Comment by AlaaZarifa** [comment]
@mikepenz  I'm having the same problem as @ahmedsaber00 ! so how can I solve it..!? I want the name and email to have different colors? right now any color I add in the xml does nothing and with the code I'm only changing both of them to a certain color..! any fix?
