### ISSUE TITLE
How To make the Drawer(created by build method) always opened without locking the main layout?  

### ISSUE THREAD

**Issue by sandeshsk** [mikepenz/MaterialDrawer#1994]
I have used the library to create a navigation drawer without having the drawer layout xml. So the problem is I made the setDrawerLockMode OPEN and scrimcolor as transparent but in the main UI i cant able to touch it. Is there any solution for this. And I am not getting the drawer width at runtime to set for the main UI??

**Comment by mikepenz** [comment]
@sandeshsk what do you try to achieve? The `DrawerLayout` is not assigned to do this. 

If you really want to have the elements which the `MaterialDrawer` offers always visible. 
Please have a look into the `EmbeddedDrawerSample`
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/EmbeddedDrawerActivity.java

(And please do not post in other unrelated questions, as it won't speed up getting an answer)

**Comment by sandeshsk** [comment]
Hello sorry for posting in other unrelated questions. I am trying to achieve a drawer always opened in the tablet but the problem I am getting is the drawer when it is always opened I cant able to touch the right side main layout since it has disabled by the drawer.

 I have used build to create a drawer at runtime. So is there any way to resolve this issue.

 I go through that Embedded Drawer sample. It means we cant achieve using a build method we need to use build view and view passing to the fragment?
