### ISSUE TITLE
Please refactor to be more compatible with current support lib

### ISSUE THREAD

**Issue by tererecool** [mikepenz/MaterialDrawer#1995]
I have implemented the version in the support lib and wanted to switch now to your lib but I am encountering many problems with it, it would be nice if the library can be easily be replaced. e.g. you have a function Drawer.removeAllItems() where with the official implementation you would use getNavigationView().getMenu().clear(), you you could use clear instead of removeAllItems. The same for the rest of the migration.

**Comment by mikepenz** [comment]
@tererecool there are no plans to follow the same API as the `NavigationView`.
