### ISSUE TITLE
righ to left drawer without application br RTL

### ISSUE THREAD

**Issue by sajadabasi** [mikepenz/MaterialDrawer#1996]
Hey,
thank you for your great drawer.
I face some problem if I make the application RTL means add this in manifest application:
`android:supportsRtl="true" `
I face some problem that I don't want to do that please help to do this.
and this works only when the language of the phone is RTL.
thank you.

**Comment by sajadabasi** [comment]
if I add
`.withDrawerGravity(Gravity.END)`
the drawer will open from the right but icons are left not right.
and icon to open the drawer is in the left

**Comment by mikepenz** [comment]
@sajadabasi there is no way to have it in RTL mode without the app being in RTL. There are also no plans to support this

**Comment by mikepenz** [comment]
you would have to basically replace all default layouts with RTL adjusted layouts
