### ISSUE TITLE
Pass bitmap to the accountheader withIcon() function

### ISSUE THREAD

**Issue by Jspascal** [mikepenz/MaterialDrawer#1997]
Hey guys, first i want to thank you for your support.
I recently help my friend with your lib. I'm not near and she want to pass a remote image to her account header icon.
I make a function which return a bitmap and i don't know if the whitIcon() function support that type.

**Comment by mikepenz** [comment]
You can pass a `Bitmap` in using the `ImageHolder`

https://www.javadoc.io/doc/com.mikepenz/materialdrawer/5.9.5 
see here for more details on the api's
