### ISSUE TITLE
idea: user-defined layouts

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/MaterialDrawer#2]
idea:
Make ist possible that the dev could use own layouts for the drawer-items.

Maybe we should discuss this. :-)

**Comment by Rainer-Lang** [comment]
If not possible - then please make it possible to set numbers at the right of the drawer.

**Comment by mikepenz** [comment]
@Rainer-Lang won't be that much work :D 
Right now you can pass your own adapter, or even your own listview. you con't have to use a list at all. so the sample just showcases the "normal" behavior. 

With a small update i will allow custom IDrawerItem implementations. but more today :D

**Comment by Rainer-Lang** [comment]
Please update the README ;-)

**Comment by mikepenz** [comment]
@Rainer-Lang the README is just about the minimalist setup. I'll add more sample to the sample app as soon as the project gets stable.

**Comment by mikepenz** [comment]
@Rainer-Lang so it's in :D See the sample / libs for details.

In fact a custom item for the drawer is defined by creating the item.xml and an class which implements the IDrawerItem interface.
