### ISSUE TITLE
ActionBar icons spacing

### ISSUE THREAD

**Issue by Yanis007** [mikepenz/MaterialDrawer#2001]
Hi Mike, 
How can I change the spacing between the Indicator icon (hamburger) to the other menu icons in the Action bar?
I want the same spacing between all of the icons.
Thanks
![screenshot_spacing](https://user-images.githubusercontent.com/25957125/29533295-e320d584-86b9-11e7-94a2-fb8c51c7fc62.jpg)

**Comment by mikepenz** [comment]
@Yanis007 sorry this is not a library specific thing. Look up the `ActionBarDrawerToggle` inside `Toolbar`s
