### ISSUE TITLE
How to Reduce  Gapping in Navigation bar Item ?

### ISSUE THREAD

**Issue by ravigupta9363** [mikepenz/MaterialDrawer#2002]
** Help me to reduce gapping between item on Navigation Bar**
### I Want to reduce Gap That is Marked By Blue 
![snap](https://user-images.githubusercontent.com/6815673/29602609-7e4e8886-87fe-11e7-8f0b-e7f540c3a609.PNG)

Help Me
Thank's

**Comment by mikepenz** [comment]
@ravigupta9363 the spacing is currently defined correctly as of the Material design guidelines. 
Have you tried if the SecondaryDrawerItem fits closer your needs?

**Comment by ravigupta9363** [comment]
**I Want To reduce space for all items in navigation** 
![navigationscreen](https://user-images.githubusercontent.com/6815673/29711438-698dce60-89b2-11e7-8215-3b7965026186.PNG)

**Comment by ravigupta9363** [comment]
`    public void initializeNavigation() {

        result = new DrawerBuilder()
                .withActivity(mainActivity)
                .withToolbar(toolbar)
                .withHeader(R.layout.nav_header)
                .withSelectedItem(-1)
                .withDrawerWidthDp(275)
                .addDrawerItems(
                        new ExpandableDrawerItem().withName(R.string.buy_a_new_vehicle_)
                                .withIcon(R.drawable.buy_new_vehicle_icon)
                                .withTypeface(mainActivity.getTypefaceOpenSansLight)
                                .withSubItems(
                                new SecondaryDrawerItem()
                                        .withName(R.string.buy_a_four_wheeler_)
                                        .withIcon(R.drawable.buy_new_vehicle_icon)
                                        .withTypeface(mainActivity.getTypefaceOpenSansLight)
                                        .withIdentifier(1),
                                new SecondaryDrawerItem()
                                        .withName(R.string.buy_a_two_wheeler_)
                                        .withIcon(R.mipmap.bike_icon)
                                        .withTypeface(mainActivity.getTypefaceOpenSansLight)
                                        .withIdentifier(2)
                        ),

                        new ExpandableDrawerItem().withName(R.string.settings_)
                                .withIcon(R.drawable.setting_icon)
                                .withTypeface(mainActivity.getTypefaceOpenSansLight)
                                .withSubItems(
                                new SecondaryDrawerItem()
                                        .withName(R.string.app_settings)
                                        .withTypeface(mainActivity.getTypefaceOpenSansLight)
                                        .withIcon(R.drawable.setting_icon)
                                        .withIdentifier(3),
                                new SecondaryDrawerItem()
                                        .withName(R.string.sos_settings)
                                        .withTypeface(mainActivity.getTypefaceOpenSansLight)
                                        .withIcon(R.drawable.setting_icon)
                                        .withIdentifier(4),
                                new SecondaryDrawerItem()
                                        .withName(R.string.gps_settings)
                                        .withTypeface(mainActivity.getTypefaceOpenSansLight)
                                        .withIcon(R.drawable.setting_icon)
                                        .withIdentifier(5)
                                ),

                        new PrimaryDrawerItem().withName(R.string.buy_gps_vehicle_tracker)
                                .withTypeface(mainActivity.getTypefaceOpenSansLight)
                                .withIcon(R.drawable.gps_tracker)
                                .withIdentifier(12)
                                .withSelectable(false),

                        new PrimaryDrawerItem().withName(R.string.make_a_service_booking_)
                                .withIcon(R.drawable.make_a_service_booking_icon).withIdentifier(6)
                                .withTypeface(mainActivity.getTypefaceOpenSansLight)
                                .withSelectable(false),

                        new PrimaryDrawerItem().withName(R.string.emergency_breakdown_)
                                .withIcon(R.drawable.emergency_breakdown_icon).withIdentifier(7)
                                .withTypeface(mainActivity.getTypefaceOpenSansLight)
                                .withSelectable(false),

                        new PrimaryDrawerItem().withName(R.string.my_quotes_)
                                .withIcon(R.drawable.my_quote_icon).withIdentifier(8)
                                .withTypeface(mainActivity.getTypefaceOpenSansLight)
                                .withSelectable(false),

                        new PrimaryDrawerItem().withName(R.string.my_vehicle)
                                .withIcon(R.drawable.my_vehicle_drawer_icon).withIdentifier(9)
                                .withTypeface(mainActivity.getTypefaceOpenSansLight)
                                .withSelectable(false),

                        new PrimaryDrawerItem().withName(R.string.about_contact_us)
                                .withIcon(R.drawable.about_us_icon).withIdentifier(10)
                                .withTypeface(mainActivity.getTypefaceOpenSansLight)
                                .withSelectable(false),

                        new PrimaryDrawerItem().withName(R.string.logout)
                                .withIcon(R.drawable.logout_icon).withIdentifier(11)
                                .withTypeface(mainActivity.getTypefaceOpenSansLight)
                                .withSelectable(false)
                )
                .withOnDrawerListener(new Drawer.OnDrawerListener() {
                    @Override
                    public void onDrawerOpened(View drawerView) {
                    }

                    @Override
                    public void onDrawerClosed(View drawerView) {

                    }

                    @Override
                    public void onDrawerSlide(View drawerView, float slideOffset) {

                    }
                })
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {

                        if (drawerItem != null) {
                            if (drawerItem.getIdentifier() == 1) {
                                mainActivity.replaceFragment(R.layout.fragment_select_brand, HomeFragment.TAG);

                            } else if (drawerItem.getIdentifier() == 2) {
                                Toast.makeText(mainActivity, "Coming Soon", Toast.LENGTH_SHORT).show();

                            } else if (drawerItem.getIdentifier() == 3) {
                                mainActivity.replaceFragment(R.layout.fragment_setting, null);

                            } else if (drawerItem.getIdentifier() == 4) {
                                Toast.makeText(mainActivity, "SOS Settings Coming Soon", Toast.LENGTH_SHORT).show();

                            } else if (drawerItem.getIdentifier() == 5) {
                                Toast.makeText(mainActivity, "GPS Settings Coming soon", Toast.LENGTH_SHORT).show();

                            } else if (drawerItem.getIdentifier() == 6) {
                                openDialog();
                                mainActivity.replaceFragment(R.layout.fragment_make_service_booking, null);

                            } else if (drawerItem.getIdentifier() == 7) {
                                mainActivity.replaceFragment(R.layout.fragment_emergency_and_breakdown, null);

                            } else if (drawerItem.getIdentifier() == 8) {
                                mainActivity.replaceFragment(R.layout.fragment_buy_car_offer, null);

                            } else if (drawerItem.getIdentifier() == 9) {
                                mainActivity.replaceFragment(R.layout.fragment_my_vehicle, null);

                            } else if (drawerItem.getIdentifier() == 10) {
                                mainActivity.replaceFragment(R.layout.fragment_about, null);

                            } else if (drawerItem.getIdentifier() == 11) {
                                userLogout();
                                //Toast.makeText(mainActivity, "You have been logout", Toast.LENGTH_SHORT).show();

                            }else if (drawerItem.getIdentifier() == 12){
                                Toast.makeText(mainActivity, "Buy GPS Vehicle Tracker Coming soon", Toast.LENGTH_SHORT).show();
                            }
                        }

                        return false;
                    }
                })
                .build();

        TextView userName = (TextView)result.getHeader().findViewById(R.id.nav_header_textview1);
        TextView email = (TextView)result.getHeader().findViewById(R.id.nav_header_textview2);
        RelativeLayout headLayout = (RelativeLayout) result.getHeader().findViewById(R.id.nav_header_relativelaout1);
        RelativeLayout notificationLayout = (RelativeLayout) result.getHeader().findViewById(R.id.nav_header_relativelaout2);
        TextView notificationNumber = (TextView) result.getHeader().findViewById(R.id.nav_header_textview4);
        String name = "";
        Customer customer = Presenter.getInstance().getModel(Customer.class, Constants.LOGIN_CUSTOMER);
        if(customer!=null){
            if(customer.getFirstName()!=null){
                if(!customer.getFirstName().isEmpty()){
                    name = customer.getFirstName();
                }
            }

            if(customer.getLastName()!=null){
                if(!customer.getLastName().isEmpty()){
                    name = name + " " + customer.getLastName();
                }
            }

            userName.setText(name);
        }

        userName.setTypeface(mainActivity.getTypefaceOpenSansLight);
        email.setTypeface(mainActivity.getTypefaceOpenSansLight);
        notificationNumber.setTypeface(mainActivity.getTypefaceOpenSansLight);
        notificationLayoutClickListener(notificationLayout);

        headLayout.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mainActivity.replaceFragment(R.id.nav_header_relativelaout1, "navigationHead");
                result.closeDrawer();

            }
        });
    }`
