### ISSUE TITLE
how can i add more info to profile?

### ISSUE THREAD

**Issue by bibubi** [mikepenz/MaterialDrawer#2003]
I'm sorry, my English is not good, please don't mind.
In my app, I want add more information just like phone num / age... to the Profile. And then display it on the Header. what should I do ?

![Screen shot](https://github.com/bibubi/Copy/blob/master/s.png?raw=true)

**Comment by mikepenz** [comment]
@bibubi that's not easily supported. it will require a little bit of "modification" on your side. 

1.) copy over the header xml to your project and add the views https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml
2.) access the view of the header and find the views 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L48
3.) everytime the profile is switched you have to manually set the new text values in the view
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L644

**Comment by bibubi** [comment]
So, I have to change your source code?

**Comment by mikepenz** [comment]
well you only have to change the layout, which is possible by copy pasting the xml to your project and adjusting it.
