### ISSUE TITLE
Empty space in layout in place of ActionBar

### ISSUE THREAD

**Issue by utsavmadaan1995** [mikepenz/MaterialDrawer#2008]
First of all thanks for the library sir. I am using this library for my app and i am facing one difficulty and already tried lot of things today but not able to solve it so finally came here for help. Please if you can help me in this.

Problem:
I have multiple activities some of which i want to have ActionBar and some not and the one which(main) has Material Drawer not to have ActionBar thats simple for this purpose i was using your recommended MaterialDrawer theme which does not have ActionBar(MaterialDrawerTheme.Light.DarkToolbar) nor i was adding any Toolbar to the activity everything works fine but now i need to have multiple themes for my app and for simplicity Activities which do not need to have Actionbar i am setting up them with ActionBar theme but in onCreate i am setting up ActionBar to be hidden. Now the problem is all activities are working fine but in the MainActivity which has MaterialDrawer there is empty space in place of ActionBar(as ActionBar is set to be hidden). And i have realized that it is because of MaterialDrawer by commenting off its code. MainActivity has  following setup:
**Theme**-MaterialDrawerTheme.Light.DarkToolbar.ActionBar 
**OnCreate**-ActionBar being setup to be hidden
`ActionBar actionBar = getSupportActionBar();
        actionBar.hide();` 
**Code for Drawer**-
`new DrawerBuilder()
                .withActivity(this)
                .withTranslucentStatusBar(false)
                .withActionBarDrawerToggle(false)
                .withDrawerGravity(Gravity.START)
                .withDelayDrawerClickEvent(250)
                .withDelayOnDrawerClose(0)
                .withCloseOnClick(true)
                .withAccountHeader(drawerHeader)`

Screenshot of the problem is attached. And i also having the latest version of the library(5.9.5)
![screenshot_20170827-175418](https://user-images.githubusercontent.com/26673311/29750038-2ba87c8a-8b56-11e7-94f4-ac4c45cf647f.png)

**Comment by mikepenz** [comment]
@utsavmadaan1995 please look at the sample application, it shows how to work with actionBar and without

**Comment by utsavmadaan1995** [comment]
Thanks sir it worked now actually i did just what the Advance Setup of the Main Page says and thought that my case is specific because i am hiding the ActionBar so should have problem with library in coverage of case. Sorry. And by the way after setting up according to Sample(ActionBarActivity) drawers are coming beneath the status bar and i have tried changing withDisplayBelowStatusBar & withTranslucentStatusBar but didnt work.. Any idea??

**Comment by mikepenz** [comment]
Properly wrong theme. 

Remember that only the `ActionBarSample` uses an ActionBar everything else uses Toolbars

**Comment by utsavmadaan1995** [comment]
Sir, updated setup is:
1. Theme: MaterialDrawerTheme.ActionBar & only colors are added to it(so same as sample) 
2. Builder: is now with 3 properties as in sample i.e withDisplayBelowStatusBar(false), withTranslucentStatusBar(false) & withDrawerLayout(R.layout.material_drawer_fits_not) 

Previous problem(blank space is gone) but drawer is still coming beneath the status bar. 
![screenshot_20170828-125953](https://user-images.githubusercontent.com/26673311/29763500-f1499010-8bf0-11e7-8146-3e662551378f.png)

**Comment by utsavmadaan1995** [comment]
![screenshot_20170828-130604](https://user-images.githubusercontent.com/26673311/29763663-b9548d08-8bf1-11e7-80f1-f51addf8c3bb.png)

**Comment by utsavmadaan1995** [comment]
Also tried switching withDisplayBelowStatusBar &&/|| withTranslucentStatusBar

**Comment by utsavmadaan1995** [comment]
Anybody??? What should i do to fix this??

**Comment by utsavmadaan1995** [comment]
Solved the issue..went back to original code where i was having problem that their was empty space in place of actionBar and than figured out where was the problem and realized that it was a inherent issue with fitsSystemWindow applied to MaterialDrawer layout causing it...so finally went on to use Toolbar theme but without toolbar in the layout(since was not required) and made changes in my style.xml to support theming to both type of activities(with ActionBar & without Action/Toolbar).
