### ISSUE TITLE
programmatically change StickyDrawerItems color

### ISSUE THREAD

**Issue by BRoy98** [mikepenz/MaterialDrawer#2009]
I changed the the drawer background color using .withSliderBackgroundColor(drawer_background). Main drawer background color is changed but the background color of Sticky Drawer Item is still white. How can I change it to my desired color?

**Comment by BRoy98** [comment]
@mikepenz please help 😞

**Comment by mikepenz** [comment]
@BRoy98 well the sticky footer itself has no color. It only uses the item color:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerUtils.java#L362

**Comment by BRoy98** [comment]
## Here is what I am getting:

![photo_2017-09-04_00-55-49](https://user-images.githubusercontent.com/12197521/30006016-c1131b34-910c-11e7-853e-6ed6ad6f5fc5.jpg)

## This is my code:
```
drawer = new DrawerBuilder()
                .withActivity(this)
                .withSliderBackgroundColor(drawer_background)
                ...
```

**Comment by mikepenz** [comment]
as mentioned. just set the following color: `material_drawer_background`

either overwrite the color itself or set the theme attribute.
