### ISSUE TITLE
withOnDrawerListener dont work

### ISSUE THREAD

**Issue by OlegWock** [mikepenz/MaterialDrawer#201]
Here is my code:
```java
result = new Drawer()
                .withActivity(this)
                .withTranslucentActionBarCompatibility(true)
                .withActionBarDrawerToggleAnimated(true)
                .withActionBarDrawerToggle(true)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.app_name).withIcon(FontAwesome.Icon.faw_home).withIdentifier(1),
                        new PrimaryDrawerItem().withName(R.string.app_name).withIcon(FontAwesome.Icon.faw_gamepad),
                        new PrimaryDrawerItem().withName(R.string.app_name).withIcon(FontAwesome.Icon.faw_eye).withIdentifier(2),
                        new SectionDrawerItem().withName(R.string.app_name),
                        new SecondaryDrawerItem().withName(R.string.app_name).withIcon(FontAwesome.Icon.faw_cog),
                        new SecondaryDrawerItem().withName(R.string.app_name).withIcon(FontAwesome.Icon.faw_question).setEnabled(false)

                )
                .withOnDrawerListener(new Drawer.OnDrawerListener() {
                    @Override
                    public void onDrawerOpened(View view) {
                        Log.d(LOG_TAG, "Drawer opened");
                        actionBar.setHomeAsUpIndicator(R.drawable.ic_arrow_back_white_24dp);
                    }

                    @Override
                    public void onDrawerClosed(View view) {
                        Log.d(LOG_TAG, "Drawer closed");
                        actionBar.setHomeAsUpIndicator(R.drawable.ic_menu_white_24dp);

                    }
                })
                .build();
```

But these messages do not appear in logcat.

**Comment by mikepenz** [comment]
@OlegWock yeah you are right this is a bug in the current version. will be fixed in the next version. this happens if there is no ActionBarDrawerToggle (this happenes if you have no toolbar)

**Comment by OlegWock** [comment]
Thanks for the answer, you have a wonderful library.

**Comment by mikepenz** [comment]
@OlegWock thanks

**Comment by INHack20** [comment]
+1

Hi I have the code:
//android.support.v7.widget.Toolbar
Toolbar toolbar = (Toolbar) mActivity.findViewById(R.id.toolbar);

//Create the drawer
        result = new DrawerBuilder()
                .withActivity(mActivity)
                .withToolbar(toolbar)
                        //No default
                .withTranslucentStatusBar(true)
                        //.withItemAnimator(new DefaultItemAnimator())
                .withActionBarDrawerToggle(false)
                .withActionBarDrawerToggleAnimated(true)
                .withDisplayBelowStatusBar(true)
                        //.withTranslucentNavigationBar(true)
                        //.withTranslucentStatusBarProgrammatically(true)
                        //.withTranslucentStatusBarShadow(true)

                        //Fin No default
                .withAccountHeader(headerResult) //set the AccountHeader we created earlier for the header
                .withOnDrawerListener(new Drawer.OnDrawerListener() {
                            @Override
                            public void onDrawerOpened(View drawerView) {
                                Log.e("Drawer","Open");
                            }

                            @Override
                            public void onDrawerClosed(View drawerView) {
                                Log.e("Drawer","Closed");
                            }

                            @Override
                            public void onDrawerSlide(View drawerView, float slideOffset) {
                                Log.e("Drawer","Slide");
                            }
                        });


And never soar methods, review the code but it seems rather a bug with the library support-v4 / 23.0.1?

Could you help me fix the bug?

PS: I love your library, you can customize a lot.!
