### ISSUE TITLE
Getting Installation error when adding dependency

### ISSUE THREAD

**Issue by NovaViper** [mikepenz/MaterialDrawer#2010]
I keep getting an error like this in my brand new application: 

![image](https://user-images.githubusercontent.com/7191115/29758075-47b67baa-8b76-11e7-9429-1c02cdc36ab4.png)

I keep clicking the install button but Android Studio doesn't do anything. I'm not sure what I'm doing wrong. Is there any way I can fix this?

**Comment by mikepenz** [comment]
@NovaViper https://developer.android.com/topic/libraries/support-library/setup.html

**Comment by Alirezadell** [comment]
Like it 
Thanks @mikepenz

**Comment by NovaViper** [comment]
I'm still having trouble getting the errors to go away. I added the support libraries but I'm still getting that error

![image](https://user-images.githubusercontent.com/7191115/29967263-73139978-8edb-11e7-8771-e6c474eeb9aa.png)

**Comment by mikepenz** [comment]
@NovaViper please read the support library page a bit more closely ;) 
https://developer.android.com/topic/libraries/support-library/setup.html

> Make sure that the repositories section includes a maven section with the "https://maven.google.com" endpoint. For example:

**Comment by NovaViper** [comment]
I do have a maven section, it's called mavenCentral(), I have used that for all of my other repos and it worked before

**Comment by mikepenz** [comment]
please read the documentation very very closely. 

<img width="970" alt="screen shot 2017-09-01 at 13 16 48" src="https://user-images.githubusercontent.com/1476232/29967626-d59e1794-8f17-11e7-8ef6-6219b081be4f.png">

**Comment by NovaViper** [comment]
I did, still spits up the same error

**Comment by mikepenz** [comment]
so you have the google maven repository in your repositories? for all projects?

**Comment by NovaViper** [comment]
Sorry for not responding, I was in class. And I finally got the error to go away, I cleared everything and put in the configurations from my previous repo with only changing the version numbers. Thanks for the help
