### ISSUE TITLE
Image from Google account not being displayed.

### ISSUE THREAD

**Issue by stevewhite21** [mikepenz/MaterialDrawer#2013]
I have setup a google sign in using firebase but after signing in and leaving the login activity, only the Username and email get changed. The image stays as blank Google sign in image. I used got the Uri link from Current user and load it into the drawer on create. Image still doesn't load. Do I need Picasso for loading it?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#load-images-via-url
