### ISSUE TITLE
How to remove ProfileSelector in AccountHeader?

### ISSUE THREAD

**Issue by thiagoperesbr** [mikepenz/MaterialDrawer#2015]
I would like to remove the ProfileSelector icon in AccountHeader. How can I do this?
And I would like to remove the click in AccountHeader, to don't open the ProfileSelector.

Sorry for my english, and thanks for fabolous Drawer.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/accountheader_single_profile_without_dropdown.md

Thanks
