### ISSUE TITLE
LG- H901 Material drawer icons are not positioned properly just for the first time.

### ISSUE THREAD

**Issue by RaMaJ123** [mikepenz/MaterialDrawer#2018]
The Material drawer icon I render just doesn't position the icon properly for the first time. After that it works properly. This happens only in the above mentioned LG phone in the title. The icons are cut and are pulled to the left, the first time you open the Material Drawer. Here is one of screenshot for your reference. 
![1504298589728 jpeg](https://user-images.githubusercontent.com/22960142/29990648-53ac2bf6-8f42-11e7-855e-e9a652b80b13.jpg)

**Comment by mikepenz** [comment]
@RaMaJ123 which version of the drawer do you use?
which version of the Android Iconics?

**Comment by RaMaJ123** [comment]
Hey Mike,

Thanks a lot for your quick response.

The version of Material Drawer i use is 5.1.6 and I use both Font Awesome and Google Material Icons. For Google Material Icons the version 2.2.0.1 and for Font Awesome it is 4.4.0.1!

**Comment by mikepenz** [comment]
Sadly I can not support old versions. Please use the latest and see if the issue persists

**Comment by RaMaJ123** [comment]
Gotcha!! I have been using your library for my classroom projects and I have been using the same versions. It is so weird that it happens only in a particular phone.

Thanks a lot Mike. I will compile the latest snapshot and keep you posted.

**Comment by mikepenz** [comment]
you can use the latest stable version 

```
compile('com.mikepenz:materialdrawer:5.9.5@aar') {
	transitive = true
}
```

**Comment by mikepenz** [comment]
and the latest iconics is:

```
//the core iconcis library (without any widgets)
compile "com.mikepenz:iconics-core:2.9.3@aar"
```

**Comment by mikepenz** [comment]
Closing this as it should be fixed with the newest versions of the libs. If not please report back

**Comment by RaMaJ123** [comment]
It seems to work perfect with the newest release Mike! Thanks!
