### ISSUE TITLE
How to put drawer above status bar?

### ISSUE THREAD

**Issue by AlexanderIgnacz** [mikepenz/MaterialDrawer#2019]
First of all, thanks @mikepenz for great working.
Can I put drawer above StatusBar?
Actually it is under status bar.

![image](https://user-images.githubusercontent.com/29761555/30033857-3a2cc632-919e-11e7-8999-b05b76ade280.png)

**Comment by mikepenz** [comment]
@AlexanderIgnacz that's the proper way. It can not be in front of the `StatusBar` 
the way as you see it is correct.
