### ISSUE TITLE
Hamburger Menu does not open drawer

### ISSUE THREAD

**Issue by djrausch** [mikepenz/MaterialDrawer#202]
The hamburger menu is added to the toolbar, but clicking it does nothing. The nav drawer can be opened by swiping though.

This is what I am doing:
    
    drawerResult = new Drawer()
                .withActivity(this)
                .withToolbar(toolbar)
                .withAccountHeader(headerResult)
                .addDrawerItems(...)         
                .withOnDrawerItemClickListener(...)
                .build();

My view has a toolbar. I've looked through the examples, and believe I am not forgetting anything.

Thanks for this great library!

**Comment by mikepenz** [comment]
@djrausch the code sample seems correct. (The code sample which is working also does the same: https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/SimpleHeaderDrawerActivity.java#L96)

Where do you initialize the drawer? any other custom code which ads an onClickListener to the navigation or to the toolbar or something similiar?

**Comment by djrausch** [comment]
I initialize the drawer in the onCreate of an ActionBarActivity. I set the title of the toolbar before passing it to the builder. I change the toolbar and status bar color on a page change of a ViewPager.

As far as onClickListeners on the toolbar, none that I know of.

I am debugging this, I'll let you know what I find.

**Comment by djrausch** [comment]
So it looks like I have a view overlapping the Toolbar. I just realized the overflow menu wasn't working either. Thanks for your help!
