### ISSUE TITLE
How to remove footer bottom padding?

### ISSUE THREAD

**Issue by AlexanderIgnacz** [mikepenz/MaterialDrawer#2020]
I added StickyDrawerItem to sample application and it works fine but there is bottom padding.
I want to remove this padding.

![screenshot_2017-09-05-02-07-05](https://user-images.githubusercontent.com/29761555/30035655-b6f62588-91ac-11e7-9bc2-d76224affbfc.png)

Is there any simple way to remove this?

**Comment by mikepenz** [comment]
@AlexanderIgnacz is you activity in fullscreen mode? 

which phone, which library version, which android version, what do you do?

does the same happen in the sample application?

**Comment by AlexanderIgnacz** [comment]
Mode - FullScreen Mode
Library version - 5.9.4

`...
.addStickyDrawerItems(new PrimaryDrawerItem().withName(R.string.drawer_item_custom).withIcon(FontAwesome.Icon.faw_eye))
...`

**Comment by AlexanderIgnacz** [comment]
I'll do some more tests and back again.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L248

**Comment by AlexanderIgnacz** [comment]
So, I tested on other types of drawers and those work fine.
But only for fullscreen mode, there're unexpected bottom padding.

**Comment by mikepenz** [comment]
@AlexanderIgnacz you set the flag as linked by me?

**Comment by AlexanderIgnacz** [comment]
Sorry, which flag do you mean?
I see only this line.
`public DrawerBuilder withFullscreen(boolean fullscreen) {`

**Comment by mikepenz** [comment]
yes. did you set withFullscreen true?

**Comment by AlexanderIgnacz** [comment]
Yes, I'm testing on example application now.

**Comment by AlexanderIgnacz** [comment]
How can I customize footer view so that hide bottom padding?

**Comment by mikepenz** [comment]
if `withFullscreen(true)` is provided in the `DrawerBuilder` the padding is not added here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerUtils.java#L312

**Comment by AlexanderIgnacz** [comment]
Ops, if condition is wrong there.
It should be `if (!(drawer.mTranslucentNavigationBar || drawer.mFullscreen) && Build.VERSION.SDK_INT >= 19) {`

**Comment by AlexanderIgnacz** [comment]
How can I use this change on my current library version 5.9.4?

**Comment by mikepenz** [comment]
well as you can't do the change directly in the lib. 
I would suggest you get the `StickyFooter` and set the padding to 0 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L358
