### ISSUE TITLE
Drawer item click without selection

### ISSUE THREAD

**Issue by jahirfiquitiva** [mikepenz/MaterialDrawer#2021]
Hi Mike

I was wondering if there's a way to enable drawer item click without selecting the item.
Like firing a click listener but not firing the item selection internally.

I have tried returning `false` in
```java
.withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
        @Override
        public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
    	    // do something with the clicked item :D
           return false;
        }
    })
```

but that doesn't seem to work.

Can you please tell me how can I achieve this? Or if there's no way, can you please implement this in a future release?

Thanks in advance.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L130

`withSelectable(false)`

**Comment by jahirfiquitiva** [comment]
Oh, thank you so much 😁
