### ISSUE TITLE
Use drawer in multiple activities best approach

### ISSUE THREAD

**Issue by dev2961io** [mikepenz/MaterialDrawer#2024]
I have one question. I want to use the same drawer in multiple activities. 
1st approach. Can I create one activity with a method where I generate the drawer and then use that activity and create multiple child activities for it then simply change the withActivity on the already created drawer?
2nd approach : Should I use only one activity for the entire app with two fragments: one for drawer and the other for content? 
Is there a way to implement the first approach without having to generate the sa drawer for every activity?

**Comment by mikepenz** [comment]
That simply depends on your app. 

You can have the drawer in a BaseActivity and all your activities have it (which is not suggested)

Or you have fragments and replace them on the top navigation level. 

Read the guidelines of Google to get a better understanding of a proper navigation flow for your users
