### ISSUE TITLE
Nav drawer not covering layout views

### ISSUE THREAD

**Issue by emansih** [mikepenz/MaterialDrawer#2025]
Hi there,

I have a navigation drawer, whenever an item in it is clicked, a new fragment will be called. however my view is overlaying the navigation drawer (see the image below). what could be the reason?

![screenshot_](https://user-images.githubusercontent.com/5896415/30216604-22aafb5a-94e6-11e7-829d-a378a2e8278a.png)

![screenshot](https://user-images.githubusercontent.com/5896415/30215893-f3fd2014-94e3-11e7-8a82-5b4c4f599a1b.png)

sample code to reproduce this issue.

public class BaseActivity extends AppCompatActivity { 

    private AccountHeader headerResult = null;
    private Drawer result = null;
    private ActivityBaseBinding binding;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = DataBindingUtil.setContentView(this,R.layout.activity_base);
        setSupportActionBar(binding.toolbar);
        buildAccountHeader(false,savedInstanceState);
        setupDrawer(savedInstanceState);
    }

    private void buildAccountHeader(boolean compact, Bundle savedInstanceState){
        IProfile profile = new ProfileDrawerItem().withName("Random Name").withEmail("xyz@gmail.com")
                .withIcon(ContextCompat.getDrawable(this,R.drawable.hisname)).withIdentifier(100);
        headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withTranslucentStatusBar(true)
                .withHeaderBackground(R.drawable.header)
                .withCompactStyle(compact)
                .addProfiles(profile)
                .withSavedInstance(savedInstanceState)
                .build();
    }

    private void setupDrawer(Bundle savedInstanceState){
        new DrawerBuilder().withActivity(this).build();
        PrimaryDrawerItem discover = new PrimaryDrawerItem().withIdentifier(1).withName("Discover");
        PrimaryDrawerItem profileDrawerItem = new PrimaryDrawerItem().withIdentifier(2).withName("Profile");
        PrimaryDrawerItem inbox = new PrimaryDrawerItem().withIdentifier(3).withName("Inbox");
        PrimaryDrawerItem favorites = new PrimaryDrawerItem().withIdentifier(4).withName("Favorites");
        PrimaryDrawerItem settingsScreen = new PrimaryDrawerItem().withIdentifier(5).withName("Settings");
        PrimaryDrawerItem aboutUs = new PrimaryDrawerItem().withIdentifier(6).withName("About Us");

        Drawer result = new DrawerBuilder()
                .withActivity(this)
                .withAccountHeader(headerResult)
                .withToolbar(binding.toolbar)
                .addDrawerItems(
                        discover, profileDrawerItem , inbox, favorites, settingsScreen, aboutUs
                )
                .withOnDrawerItemClickListener((view, position, drawerItem) -> {
                    if(drawerItem.getIdentifier() == 1){
                        getSupportFragmentManager().beginTransaction()
                                .replace(android.R.id.content,new DiscoverFragment())
                                .addToBackStack(null)
                                .commit();
                    } else if(drawerItem.getIdentifier() == 2){
                        getSupportFragmentManager().beginTransaction()
                                .replace(android.R.id.content,new ProfileFragment())
                                .addToBackStack(null)
                                .commit();
                    } else if(drawerItem.getIdentifier() == 3){

                    } else if(drawerItem.getIdentifier() == 4){

                    } else if(drawerItem.getIdentifier() == 5){

                    } else if(drawerItem.getIdentifier() == 5){

                    } else if(drawerItem.getIdentifier() == 6){

                    }
                    return false;
                })
                .withSavedInstance(savedInstanceState)
                .build();
        result.closeDrawer();
        getSupportActionBar().setDisplayHomeAsUpEnabled(false);
        result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);

        if (savedInstanceState == null) {
            result.setSelection(1, true);
        }
    }

    @Override
    public void onBackPressed() {
        if (result != null && result.isDrawerOpen()) {
            result.closeDrawer();
        } else {
            super.onBackPressed();
        }
    }}

**Comment by mikepenz** [comment]
@emansih because you set your fragment in front of the drawer:
give it a proper framelayout container somewhere in your view hierachy and don'T use `android.R.id.content`

**Comment by emansih** [comment]
thanks mike.
