### ISSUE TITLE
How to add sticky footer to builder

### ISSUE THREAD

**Issue by fermatijoe** [mikepenz/MaterialDrawer#2026]
Hi, i have this code to create the drawer:

     `mDrawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(mToolbar)
                .withAccountHeader(headerResult)
                .withStickyFooter(new PrimaryDrawerItem().withName("d").withIdentifier(8))
                .addDrawerItems(
                        new PrimaryDrawerItem().withIdentifier(4).withName(R.string.Favorites),
                        new DividerDrawerItem(),`

But at the line 

                .withStickyFooter(new PrimaryDrawerItem().withName("d").withIdentifier(8))

I get the "cannot resolve method" error. What am I doing wrong?

**Comment by 2SFN** [comment]
The method `withStickyFooter` expects a [layout resource identifier](https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L738) or a [ViewGroup](https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L727).
Try [`addStickyDrawerItems`](https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1023) instead.

**Comment by fermatijoe** [comment]
Thank you very much.
