### ISSUE TITLE
Unreliable OnDrawerItemClickListener position when using drawer header

### ISSUE THREAD

**Issue by MarcelBochtler** [mikepenz/MaterialDrawer#2027]
Hello,
I have this drawer:
```kotlin
        drawer = DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withHeader(R.layout.drawer_header)
                .withOnDrawerItemClickListener { view, pos, drawerItem ->
                    Toast.makeText(this, "Position: $pos", Toast.LENGTH_SHORT).show()
                    false
                }
                .build()
```

With the header the position in the OnDrawerItemClickListener is at the first call 0, in all subsequent calls it is 1, when clicking the first item in the drawer.

Without the header the position is every time 0, which is the expected behavior.

Is this the correct behavior?
And does this mean that I can't rely on the position when using a header in the drawer?

**Comment by mikepenz** [comment]
@MarcelBochtler yes this is the correct behaviour. The header is also just an element in the `RecyclerView` so the position changes. 

Well why shouldn't you be able to rely on it? Your code decides if there is a header, so you also know which position you have to expect

**Comment by MarcelBochtler** [comment]
Thanks for your answer. It helped me a lot.
I thought it was inconsistent because the first time I called `drawer.setSelectionAtPosition(myPos)` I did set myPos to the first element of my list which is 0 (this was called in on resume).

So calling it from onResume meant pos = 0, clicking it manually meant pos = 1.
So it was a programming error.
