### ISSUE TITLE
setIcon for ExpandableDrawerItem from Url not work

### ISSUE THREAD

**Issue by funnymobiledev** [mikepenz/MaterialDrawer#2028]
With ExpandableDrawerItem I use:
`item.withIcon(new ImageHolder(url))`

It not work (Others item work fine)

**Comment by mikepenz** [comment]
@funnymobiledev that's not supported. please use the search function of github issues as this was already asked

**Comment by funnymobiledev** [comment]
@mikepenz 
I create a drawer dynamic, all data setting by server so that icon will be  url.
is it not support ?

**Comment by mikepenz** [comment]
the sample contains a custom item supporting this:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomUrlPrimaryDrawerItem.java
