### ISSUE TITLE
[enhancement] Add ability to show list of names instead of e-mails in account switcher

### ISSUE THREAD

**Issue by ilyamodder** [mikepenz/MaterialDrawer#203]
That would be great, because emails in my app totally uninformative.

**Comment by mikepenz** [comment]
@ilyamodder just set the name instead of the e-mail. should be a quick and easy fix.

**Comment by ilyamodder** [comment]
Then they will be swapped in the header, that's not good.

**Comment by mikepenz** [comment]
So you want it to stay the same in the header but in the items it should not show the e-mail?

**Comment by ilyamodder** [comment]
Yes, exactly.
Can you help me with it, please?

**Comment by mikepenz** [comment]
I would recommend that you look at the source code of the PrimaryDrawerItem. (https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java)

You can copy it and just switch the e-mail and name. 
https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L281
https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L291
