### ISSUE TITLE
Material drawer id being close after activity back or pressed 

### ISSUE THREAD

**Issue by seluhadu** [mikepenz/MaterialDrawer#2032]
https://github.com/mikepenz/MaterialDrawer/blob/6cf50ed11a0cbe4be80d0a05991dd4db5df2ee2f/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java#L119

i created material drawer and  i added a custom color for each icon drawer 
but drawer is not closing if i clicked drawer item.
i have checked in the example drawer in play store in the MIni Drawer if i clicked actionBar Drawer  it also not working the code line is in the 119 under "Mini Drawer"
so my problem is i think when i use custom color icon not closing drawer when i clicked the drawer item and when i back from another activity it stay open
sorry my English.
thank you!!!!!!

**Comment by mikepenz** [comment]
remove 
```
.withSelectable(false)
```
