### ISSUE TITLE
StringHolder toString() can cause NullPointerException

### ISSUE THREAD

**Issue by woodii** [mikepenz/MaterialDrawer#2034]
`Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference`

If you call `toString()` on a StringHolder where the CharSequence `mText` is null you get a NullPointerException. (not sure why this didn't happen in previous versions of my app/your library)

I would suggest a simple Nullcheck.

**Comment by mikepenz** [comment]
Depends when you updated. in the very past the `mText` field was a `String` so it would just return null, now it returns the fields content. 

You are aware that this field is also not set if you initialised the `StringHolder` with an string identifier?

**Comment by woodii** [comment]
In my use case the email in the `ProfileDrawerItem` can be null. In previous versions it was ok to just set it null and when u want to read it back you can use toString().
Now you either have to set the property with an empty String instead of null or check if `StringHolder.getText != null` before accessing the value to avoid a nullpointer, which is a bit inconvenient.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/Materialize/issues/17

**Comment by mikepenz** [comment]
Please update to `Materialize` v1.1.1 (you can do this by excluding the included version and use the newer version)
