### ISSUE TITLE
Android temporary view over Material drawer

### ISSUE THREAD

**Issue by codedentwickler** [mikepenz/MaterialDrawer#2035]
Hi, I'm using your library and it's super cool. 
I want to implement a mode switch button in the navigation drawer. When the button is clicked, a selector view like the one below should be drawn.
Also any idea how I can change the default change account behaviour at the upper right corner to perform the switch mode button function.
Thanks.
![screen shot 2017-09-20 at 10 59 26 am](https://user-images.githubusercontent.com/18694890/30638305-e3c22c36-9df2-11e7-818f-9e686a81ae15.png)

**Comment by mikepenz** [comment]
@codedentwickler I am not sure if you should use the `MaterialDrawer` library if you want to have a completely different appearance. 

Please just sue the `DrawerLayout` instead (from google) 

doesn't seem as you need anything from this library
