### ISSUE TITLE
Attaching drawer to my Controller (Conductor) causes a Controller detach

### ISSUE THREAD

**Issue by 4Face** [mikepenz/MaterialDrawer#2036]
Launching this:

new DrawerBuilder()
                .withActivity(getMainActivity())
                .withToolbar(getToolbar())
                .withAccountHeader(accountHeader).build();

Detach my Controller and I think that also doesn't permit me to show the options menu.
I'm extending the same class "BaseRootControllerToolbar" but the Controller with the drawer never triggers the onCreateOptionsMenu.

**Comment by mikepenz** [comment]
@4Face your code does not show anything. 

The building of the drawer will inflate the `DrawerLayout` to the view hierarchy. 

Please refer to the sample apps showing usage.
