### ISSUE TITLE
How to set SectionDrawerItem background color

### ISSUE THREAD

**Issue by erikswed** [mikepenz/MaterialDrawer#2037]
Thanks for lib. I use this `new CustomPrimaryDrawerItem().withBackgroundRes(R.color.accent)` to set color but the divider line `new  SectionDrawerItem(...  does not take the `withBackgroundRes`. so that background is color white. Any ide?

**Comment by erikswed** [comment]
ok got it it´s trough xml

**Comment by bc1213** [comment]
How you changes in xml ?
