### ISSUE TITLE
DividerDrawerItem margin

### ISSUE THREAD

**Issue by vasskob** [mikepenz/MaterialDrawer#2039]
Halo. Can you help me, please. How to add DividerDrawerItem marginStart to draw divider with some margin at start position?

**Comment by vasskob** [comment]
[https://drive.google.com/open?id=0B1kbuamjUg66cEZnWlBNR3cwVE0](url)
Actually, I need to draw DividerDrawerItem from left DrawerItem icon position, like on the picture above.

**Comment by vasskob** [comment]
https://drive.google.com/open?id=0B1kbuamjUg66cEZnWlBNR3cwVE0

**Comment by mikepenz** [comment]
@vasskob create your own `CustomDrawerItem`
