### ISSUE TITLE
Account Header - NullPointerException

### ISSUE THREAD

**Issue by jayrambhia** [mikepenz/MaterialDrawer#204]
I have encountered this error in a particular way. I have only one profile added in the AccountHeader. When I open the drawer, select that profile, it shows a drop down. I keep it that way and close the drawer and open another activity. Current activity is not destroyed. When I get back from the new activity, it throws this error.

     java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.View.getContext()' on a null object reference
            at com.mikepenz.materialdrawer.accountswitcher.AccountHeader$5$1.run(AccountHeader.java:1159)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

If I close the account header drop down and perform the same routine, it works fine.

If I toggle the selection manually as soon as the drawer is closed, it works perfectly.

    withOnDrawerListener(new Drawer.OnDrawerListener() {
            @Override
            public void onDrawerOpened(View view) {}

            @Override
             public void onDrawerClosed(View view) {
                 if (accountHeaderResult != null) {
                     if (accountHeaderResult.isSelectionListShown()) {
                         accountHeaderResult.toggleSelectionList(context);
                      }
                  }
             }
    })

**Comment by raghunandankavi2010** [comment]
@mikepeenz  i encountered a similar situation. I added a Custom View HeaderView. I wanted to display just an icon. A banner as the background. Instead of  Name and Email i just have Name and some other text. I just think this has a overhead invovled!.

**Comment by mikepenz** [comment]
@jayrambhia i need some more details here. i just tried it with the same steps. opening a new activity after i opened the profile list. and if i go back there's no issue.

**Comment by mikepenz** [comment]
@jayrambhia please test i've added an additional check with the newest version. perhaps it's fixed.

**Comment by jayrambhia** [comment]
Some more info:

Account Header

    AccountHeader.Result accountHeaderResult = new AccountHeader().withActivity(this)
        .withHeaderBackground(R.drawable.account_header_bg)
        .addProfiles(new ProfileDrawerItem().withName(presenter.getUsername())                                                                  .withTypeface(dosis_bold).withIcon(presenter.getUserIconDrawable()))
        .build();

I am sure that none of the above fields are null.

Drawer
    
    LinearLayout footer = (LinearLayout)inflater.inflate(R.layout.navigation_drawer_footer, null);    

    drawerResult = new Drawer().withActivity(this)
           .withToolbar(toolbar)
           .withAccountHeader(accountHeaderResult)
           .addDrawerItems(getDrawerItems())
           .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                @Override
                public void onItemClick(AdapterView<?> adapterView, View view, int i, long l, IDrawerItem iDrawerItem) {
                    if (i == 3) {
                          presenter.performLogOut();
                     } else if (i == 2) {
                          showSettings();
                     } else {
                           return;
                     }
                    drawerResult.setSelection(0);
             }
      }).withStickFooter(footer).build();


    private IDrawerItem[] getDrawerItems() {

        List<IDrawerItem> listItems = new ArrayList<>();

        listItems.add(new PrimaryDrawerItem().withName("Notes")
                                            .withIcon(R.drawable.ic_launcher)
                                            .withTypeface(dosis_bold)
                                            .withTextColor(green_primary)
                                            .withSelectedTextColor(accent_yellow)
                                            .withSelectedColor(green_secondary));

        listItems.add(new DividerDrawerItem());

        listItems.add(new PrimaryDrawerItem().withName("Settings")
                                            .withIcon(R.drawable.draw_settings)
                                            .withTextColor(green_primary)
                                            .withTypeface(dosis_bold)
                                            .withSelectedTextColor(accent_yellow)
                                            .withSelectedColor(green_secondary));

        listItems.add(new PrimaryDrawerItem().withName("Log Out")
                                            .withIcon(R.drawable.draw_logout)
                                            .withTextColor(green_primary)
                                            .withTypeface(dosis_bold)
                                            .withSelectedTextColor(accent_yellow)
                                            .withSelectedColor(green_secondary));

        IDrawerItem[] items = new IDrawerItem[listItems.size()];
        listItems.toArray(items);
        return items;

    }

Layout

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#ffebeff1"
        tools:context=".NoteListActivity">

    <android.support.v7.widget.Toolbar
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="@dimen/toolbar_height"
        app:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
        android:background="?attr/colorPrimary">

        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:gravity="left|center"
            android:padding="3dp"
            android:orientation="vertical">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/toolbar_title_textview"
                android:textColor="@color/white"
                android:textSize="24sp"
                android:gravity="center"
                android:text="@string/toolbar_title"/>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/toolbar_subtitle_textview"
                android:textColor="@color/white"
                android:textSize="15sp"
                android:gravity="bottom"
                android:text="@string/toolbar_subtitle"/>

        </LinearLayout>

    </android.support.v7.widget.Toolbar>

    <android.support.v7.widget.RecyclerView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="12dp"
        android:layout_marginLeft="15dp"
        android:layout_marginRight="15dp"
        android:layout_marginBottom="12dp"
        android:layout_below="@id/toolbar"
        android:visibility="visible"
        android:id="@+id/recyclerview">

    </android.support.v7.widget.RecyclerView>

    </RelativeLayout>

I apologize for the bad formatting. And I'll try the updated version. Thanks.

**Comment by mikepenz** [comment]
@jayrambhia is it working with the newest version?

**Comment by jayrambhia** [comment]
@mikepenz I tried this with `2.7.7@aar` and I get nullPointerException. Should I clone the master and try that?

**Comment by mikepenz** [comment]
@jayrambhia would be great. somehow there must be some strange combination which causes this issue

**Comment by mikepenz** [comment]
@jayrambhia still the case? i'll close this for now. please report back
