### ISSUE TITLE
is there some helper when on tablet size device

### ISSUE THREAD

**Issue by erikswed** [mikepenz/MaterialDrawer#2041]
hi
Thanks for grate lib. Wanted to ask because everything looks good on a 5" device but on a 10" tablet the 
`MaterialDrawer` menu items are tiny

```
 CustomPrimaryDrawerItem feedsDrawerItem = new CustomPrimaryDrawerItem()
                .withName(R.string.navigation_feeds)
                .withIcon(R.drawable.ic_notifications_active_black_24dp)
                .withDescription("This is a description")
                .withIdentifier(FEEDSDRAWERITEM);
```

Do I have to during creation test for this and space everything up for tablet size or is  there some `MaterialDrawer` helper when on tablet size device that will fix this?

![sssssss](https://user-images.githubusercontent.com/3285249/30774976-fe3576c8-a08a-11e7-963b-5a1eade62342.png)

**Comment by mikepenz** [comment]
@erikswed for tablet's you should usually not use the `DrawerLayout` but add the side-bar as part of the view hierachy. look in the sample apps. perhaps the `MiniDrawer` is interesting for you. or the sample which showcases how you can add the `Drawer` to your view hierachy. 

the size and width is correct as of the guidelines though.
