### ISSUE TITLE
Performance issue on animated gifs in header background

### ISSUE THREAD

**Issue by yigitserin** [mikepenz/MaterialDrawer#2043]
Hey there,

Is there any good way to set an animated gif or video as an header background?

I tried setting an animated gif this way, but it does not play smoothly.

` Glide.with(this).load(R.drawable.anim).into(header.getHeaderBackgroundView());`

Here is the gif I used:

https://media.giphy.com/media/xT9IgyaftFIcZNphcI/giphy.gif

**Comment by mikepenz** [comment]
@yigitserin nothing related to this library. 

possible solutions:
- use a smaller gif
- use a lower res gif
- don't use a gif
