### ISSUE TITLE
Header view is always being displayed under the StatusBar

### ISSUE THREAD

**Issue by oscargrgm** [mikepenz/MaterialDrawer#2046]
This is my DrawerBuilder: 

```
View view = getLayoutInflater().inflate(R.layout.lateral_menu_custom_header, null);

DrawerBuilder mBuilder = new DrawerBuilder(this)
   .withTranslucentStatusBar(false)
   .withOnDrawerItemClickListener(this);
   .withHeader(view);
   .withHeaderDivider(false);
   .withDisplayBelowStatusBar(true);
```

But the `StatusBar` is always being displayed above this `view`, no matter if I change the `withDisplayBelowStatusBar` attribute or the `withTranslucentStatusBar`.

Is there any method to make it really appears below the `StatusBar`?

The first image is what I have right now, and the red square represents my header view. 
![obtained](https://user-images.githubusercontent.com/9430919/30867054-302d5838-a2db-11e7-88b1-0ef24a4782e6.png)

The second one represents what I really want to have. The red square should be "after" the StatusBar.
![desired](https://user-images.githubusercontent.com/9430919/30867058-32bfd576-a2db-11e7-868d-c0d85bedcaa1.png)

**Comment by mikepenz** [comment]
@oscargrgm if you provide your own header you have to make sure you handle the 24dp / 25dp of the statusbar. in addition it would be transparent, it seems you have set a solid color to it

**Comment by oscargrgm** [comment]
How can I handle this 24/25dp padding or margin? I have tried using `withHeatherHeight(DimenHolder.fromDp(200))` (for example) and also setting my view's height to 80dp, 100dp or even more, but the only result I get is a white space under my view, which is still having the same size.

**Comment by mikepenz** [comment]
well if you handle the header manually because you have a custom view, then you will need to add and handle the margin for it too. 
Otherwise the `AccountHeader` does it

**Comment by oscargrgm** [comment]
Ok, but is there any method provided by the library to handle this margin manually? Because setting it inside the layout is not working.

**Comment by mikepenz** [comment]
well the margin can not be on the root of your header view, you can use padding if you want to have it defined on this headers root. 

there is no method to get that

**Comment by mikepenz** [comment]
Please report back if you need more information

**Comment by oscargrgm** [comment]
Sorry for the late response. Now it works perfectly. I write here the solution in case somebody needs it.

```
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@color/colorPrimaryDark">
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:layout_marginTop="25dp"
        android:paddingLeft="16dp"
        android:paddingRight="16dp"
        android:paddingTop="8dp"
        android:paddingBottom="8dp">
        <ImageView
            android:layout_width="150dp"
            android:layout_height="match_parent"
            android:src="@drawable/menu_header_icon"/>
    </LinearLayout>
</LinearLayout>
```

[Here](https://stackoverflow.com/a/3410200/5919525) I've found some code to calculate the StatusBar height and set the inner `LinearLayout`'s `layout_marginTop` dynamically.
