### ISSUE TITLE
Actionbar over the drawer

### ISSUE THREAD

**Issue by stevewhite21** [mikepenz/MaterialDrawer#2047]
How can I set the drawer over the ActionBar. I used the code given in the details for using it with ActionBar.
![capture _2017-09-27-22-56-02](https://user-images.githubusercontent.com/28768536/30950059-73eda80a-a3d7-11e7-9b41-af7ff813149e.png)
![1506574746849245293488](https://user-images.githubusercontent.com/28768536/30950065-80c068ce-a3d7-11e7-8388-605b14e307f2.jpg)

**Comment by mikepenz** [comment]
@stevewhite21 not possible with the `ActionBar` please use a `Toolbar`
