### ISSUE TITLE
Drawer not showing in new Activity

### ISSUE THREAD

**Issue by FajarKhan** [mikepenz/MaterialDrawer#2048]
So I have successfully created drawer.

In main activity, I am building drawer with` toolbar` and the in item click listener I'm calling another activity like this:
```
if (drawerItem.getIdentifier() == 3) 
                                Intent _fav_intent=new Intent(MainActivity.this,Favourite.class);
                                startActivity(_fav_intent)
                            }
```
Now the problem is, when opening new activity there is no drawer in in left side. Anyone have any idea why?

**Comment by mikepenz** [comment]
@FajarKhan the drawer is a ui element of that specific activity, if you do launch a new activity you have to add it there again. That's why you usually should use fragments for such a navigation pattern
