### ISSUE TITLE
Custom content for drawer

### ISSUE THREAD

**Issue by vuz** [mikepenz/MaterialDrawer#205]
Hi Mike,

First of all thank for the great library, really a good job, helps a lot !

The only missing point for me would be to be able to set a fragment as the content for one of the drawer.

Explanations : 

I already use a "left" drawer with header, account switcher, and drawer items, and it does the job perfectly.
But I would like to use a right drawer filled with something a little more custom, and I can't find anything to do that. Am I missing something or is it not possible at the moment ?

Thank you !

**Comment by mikepenz** [comment]
@vuz if you have a listView on the other side you can also pass a custom ListView to the drawer. 

If you don't require the stuff which is handled by the drawer you can also just create the content (the view which is used within the drawer) and add it to your existing drawer. 

adding a complete custom view isn't possible at the moment.

**Comment by mikepenz** [comment]
This will be available in the next version. 

```
new Drawer().withActivity(this).withDrawerGravity(Gravity.RIGHT).append(result, THECUSTOMVIEW);
```

**Comment by vuz** [comment]
Hi Mike,

I got the last version and it's working great, thank you !

Still got two questions however : 

How can I access the second drawer so I can open it / close it programmatically ? For the left drawer I know I can user the Drawer.Result, but I don't see any options for the second one.

On API > 21, the second drawer does not behave like the first one, and appears above the status bar

Examples with the same images on top of each drawer so you can see the difference : 

Left drawer :

![screen shot 2015-04-13 at 14 21 07](https://cloud.githubusercontent.com/assets/3830545/7115383/8a421694-e1e8-11e4-889a-88d195ba0e1c.png)

Right drawer : 

![screen shot 2015-04-13 at 14 23 55](https://cloud.githubusercontent.com/assets/3830545/7115416/cf9217da-e1e8-11e4-8e9b-0b1488ef4139.png)

The code : 

    Drawer drawer = new Drawer()
                .withActivity(this)
                .withToolbar(mToolbar)
                .withAccountHeader(headerResult)
                .addDrawerItems(
                        /* stuff */
                )
                .withStatusBarColor(Color.parseColor(mColorScheme.getmDarkPrimaryColor()))
                .withOnDrawerItemClickListener(mDrawerClickListener);
    mDrawer = drawer.build();    

    new Drawer()
                 .withActivity(this)
                 .withDrawerGravity(Gravity.RIGHT)
                 .append(mDrawer, new CartView(this, null));    

Thank you for your input once again !

**Comment by mikepenz** [comment]
@vuz the thing is this. the MaterialDrawer manages the shadow above the StatusBar. This is added by the MaterialDrawer. If you also want this shadow for your custom drawer content you also have to add this shadow on your own. 

And about opening and closing the second drawer. just remember the result of the second drawer and use the Drawer.Result result2 to open close the drawer ;)

**Comment by Ksernik** [comment]
Hi Mike, I have a similar situation as at vuz..
you say "If you don't require the stuff which is handled by the drawer you can also just create the content (the view which is used within the drawer) and add it to your existing drawer." , but how to do that?
some code: `
AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withSelectionListEnabledForSingleProfile(false)
                .withHeaderBackground(R.color.colorNavBackgroundColor)
                .withTextColorRes(R.color.colorBlackTextColor)
                .withCurrentProfileHiddenInList(true)
                .addProfiles(profile)
                .build();

 DrawerBuilder builder = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withSelectedItem(1)
                .withAccountHeader(headerResult) 
                .addDrawerItems(new PrimaryDrawerItem().withName(R.string.drawer_item_first).withIcon(R.drawable.nav_client_icon).withTintSelectedIcon(true).withSelectedIconColorRes(R.color.colorAccent).withIdentifier(1));
`
exactly where I need to insert my view?
sorry for the stupid question , and for my bad english

**Comment by mikepenz** [comment]
@Ksernik in your case you say that you still want header + drawerItems. 

So I highly recommend that you just create a `CustomDrawerItem` (or use a `ContainerDrawerItem`)  and add it as first `DrawerItem` this will then be within header and drawerItems

**Comment by Ksernik** [comment]
Yes, I need header + drawerItems.
should get something like this
![navigation drawer info new](https://cloud.githubusercontent.com/assets/9426994/16234133/0082fbb8-37ea-11e6-855f-5f17de3436f8.png)

thank you very much for your reply!  I will try to create a CustomDrawerItem =)
