### ISSUE TITLE
Multiple menu items selected

### ISSUE THREAD

**Issue by erikswed** [mikepenz/MaterialDrawer#2052]
Thanks for grate lib. when i run your demo app all the different example activity´s always the menu item I selected get selected and that´s it. When I try it it look like this: I cant see that in your demo app you are explicitly setting/unsetting the selected menu item selected. What did I miss? 

![screenshot_2017-10-01-17-25-57](https://user-images.githubusercontent.com/3285249/31056233-a6d36486-a6ce-11e7-994c-84b5b3950005.png)

I thought It might be a styling issue but I dont think so

  ```
      <!-- MaterialDrawer specific values -->
        <item name="material_drawer_background">@color/material_bohemia_400</item>
        <item name="material_drawer_primary_text">@color/material_bohemia_200</item>
        <item name="material_drawer_primary_icon">@color/material_drawer_primary_icon</item>
        <item name="material_drawer_secondary_text">@color/material_bohemia_500</item>
        <item name="material_drawer_hint_text">@color/material_bohemia_600</item>
        <item name="material_drawer_divider">@color/material_bohemia_a100</item>
        <item name="material_drawer_selected">@color/material_bohemia_600</item>
        <item name="material_drawer_selected_text">@color/material_bohemia_a100</item>
        <item name="material_drawer_header_selection_text">@color/material_drawer_header_selection_text</item>
```

**Comment by mikepenz** [comment]
@erikswed can you reproduce this in the sample?

**Comment by erikswed** [comment]
I run som observation test and see everything works as expected as long as Activity is not going into background `onPause()` then `onResume()` . This is setting the drawer in some dislocated state and the menu item that was selected when  enter  `onPause()` will not get set to unselected when `onResume()` run. I think I just mess some lifestyle handling here

**Comment by erikswed** [comment]
I found the reason for this behavior. 
I have a few differerat header xml depending on app state and In `onResume()` i set the header xml like this: 
```
View head = getLayoutInflater().inflate(R.layout.navigation_view_header_test, navigationDrawer.getDrawerLayout(), false);
navigationDrawer.setHeader(head); 
```

When I change it to:

```
View head = getLayoutInflater().inflate(R.layout.navigation_view_header_test, navigationDrawer.getDrawerLayout(), false);
        if (currentNavigationHeader == null || currentNavigationHeader.getId() != head.getId()) {
            if (currentNavigationHeader != null)
                navigationDrawer.removeHeader();
            navigationDrawer.setHeader(head);
        }
currentNavigationHeader = head;
```

That is I test if the desired xml is in the drawer and then don´t load it. Now it works when app go onPause() then onResume(). Now menu items are selected accordingly and not like in my above picture
