### ISSUE TITLE
Cannot select both ExpandableDrawerItem and sub item

### ISSUE THREAD

**Issue by MarkOSullivan94** [mikepenz/MaterialDrawer#2054]
Hoping that this is possible, currently wanting to have any ExpandableDrawerItem set as selected whenever any of their sub items is selected, in my case a SecondaryDrawerItem.

Currently I'm trying to use  `myExpandableItem.withSetSelected(true)` within the onItemClick for any of the secondaryDrawerItems and it seems that this isn't updating until the next click.

**Comment by mikepenz** [comment]
@MarkOSullivan94 only one item is selected at a time.

**Comment by MarkOSullivan94** [comment]
@mikepenz is there a way to override the default behavior? I only ask because I have noticed you can have two items highlighted as if they're selected at one time by doing something similar to what I have described.

**Comment by mikepenz** [comment]
well you can hack it into but it is not prepared for this. (you need to adjust the configuration of the adapter)

**Comment by MarkOSullivan94** [comment]
I've downloaded the source code and delved in to try and find a solution myself to the problem, it seems that because the MaterialDrawer library uses the FastAdapter library, it seems like if I'm going to have to make a pull request for any potential solution firstly for the FastAdapter and secondly for this library.

I'm thinking a solution could be implemented within the `handleSelection(View view, Item item, int position)` method. I notice there is a boolean called mMultiSelect, a similar boolean could be created called `mSelectParent` so you can enable / disable whether or not you want parents to be selected whenever one of their subItems is selected.

I know there's a method getParent() within AbstractDrawerItem.java, just wondering if it would be possible to get the parent from the item within the handleSelection method?

**Comment by mikepenz** [comment]
@MarkOSullivan94 the `FastAdapter` already supports multi select that's not the problem. the `MaterialDrawer` just do not support it, as it disables it.

**Comment by MarkOSullivan94** [comment]
Why does it disable it?

**Comment by mikepenz** [comment]
because it is not a common pattern and might end up causing other issues. 

You can try the configurations of the `FastAdapter` and it most likely will work, but it is currently not a official supported thing of the MaterialDrawer

**Comment by mikepenz** [comment]
@MarkOSullivan94 if you have further questions please report back. close for the time beeing
