### ISSUE TITLE
Change drawer view programmatically

### ISSUE THREAD

**Issue by tral** [mikepenz/MaterialDrawer#206]
Hi! So, I have this two things working in my MainActivity:
private AccountHeader.Result headerResult;
private Drawer.Result drawerResult;

So I have two views of the drawer: its "main view" with different actions and its "accounts view". I can switch between them by clicking on the profile email for example. How can I do this switch programmatically?

(The problem is when I click on "Logout" in drawer's "accounts view", I start new activity (LoginActivity). After the successfull re-login user can see drawer's "accounts view" instead of it's "main view")...
Oh, I can give a sample if it's not clear.

**Comment by tral** [comment]
.withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean current) {
                        if (profile instanceof IDrawerItem && ((IDrawerItem) profile).getIdentifier() == ACCOUNTS_LOGOUT_ID) {

                            SharedPreferences settings = PreferenceManager.getDefaultSharedPreferences(activity);
                            SharedPreferences.Editor editor = settings.edit();
                            editor.putInt("prefUserId", 0);
                            editor.commit();
                            Intent intent = new Intent(activity, LoginActivity.class);
                            activity.startActivityForResult(intent, Utils.ACT_RESULT_LOGIN);
                        }

                        //false if you have not consumed the event and it should close the drawer
                        return false;
                    }
                })

**Comment by tral** [comment]
oh.. I got it - drawerResult.resetDrawerContent() works perfectly for me, you can close the issue :)

**Comment by mikepenz** [comment]
@tral great that you were able to sort this out
