### ISSUE TITLE
SetSelection on MiniDrawer

### ISSUE THREAD

**Issue by NelsonPRSousa** [mikepenz/MaterialDrawer#2061]
Hi,
Thank you for your awesome work.

Right now, I am using this 2 blocks of code to manually select an item:

```C#
        result.setSelection(1, false);
        result.getMiniDrawer().setSelection(1);
```

How can I disable the selected item? I tried this:
```C#
        //-1 doesn't exist
        result.setSelection(-1, false);
        result.getMiniDrawer().setSelection(-1);
```

However, only the expanded drawer loses the focus, but MiniDrawer keeps the focus. How can I handle this?

Thank you.

**Comment by mikepenz** [comment]
@NelsonPRSousa I think the `MiniDrawer` does not support no selection :/  I am currently super busy so I can't check

**Comment by NelsonPRSousa** [comment]
@mikepenz I checked by myself. It doesn't work.
So, no way?

**Comment by mikepenz** [comment]
@NelsonPRSousa well this method set's the selection by the identifier. A method which set's the item per position would be needed.

**Comment by NelsonPRSousa** [comment]
@mikepenz But SetSelection() of the Drawer loses the selection, but MiniDrawer doesn't. Is this a bug or it is the correct behavior?

**Comment by mikepenz** [comment]
because it falls back to `setSelecitonAtPosition` which supports it. 

So it would be an enhancement to add this functionality :) 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L571

**Comment by NelsonPRSousa** [comment]
So the comment is wrong... "

> /**
     * set the selection of the MiniDrawer
     *
     * @param identifier the identifier of the item which should be selected (-1 for none)
     */

Can we wait for this enhancement or should we consider other options?

Thank you

**Comment by mikepenz** [comment]
will be in the next version. sorry for the long delay

**Comment by NelsonPRSousa** [comment]
Thank you :)
