### ISSUE TITLE
Cant add dependency to gradle

### ISSUE THREAD

**Issue by yoctopus** [mikepenz/MaterialDrawer#2063]
Hi, I keep getting dependency errors when i try to  add this library using compile option to my gradle file. It says the support lib dependencies need to be downloaded yet i have the dependencies already in use in the gradle file. The dependency version 26 for design,support and annotations  is in my gradle file already.
Kindly assist.

**Comment by mikepenz** [comment]
@yoctopus https://developer.android.com/topic/libraries/support-library/setup.html

**Comment by yoctopus** [comment]
@mikepenz Thanks
