### ISSUE TITLE
Drawer item remain selected

### ISSUE THREAD

**Issue by seluhadu** [mikepenz/MaterialDrawer#2065]
i have Material Drawer with items when i click like usually  Intent to activity.
but when i click back the item i clicked remains selected. it doesn't redirect to the open activity that is open.
i'm using this ` <item name="material_drawer_selected">@color/Dark_material_drawer_selected</item>` 
here is what is happening.

and i want to change the hamburger icon. is is possible

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/25090268/31471891-36a06a7c-aeb9-11e7-8772-81624e2dfe64.gif)

**Comment by mikepenz** [comment]
if you click will it launch a new activity with a new drawer? if yes you have to select on your own.

**Comment by seluhadu** [comment]
Thanks for replying!
I don't know how to select programmatically. I tried setSelection but it closes the app when I click Drawer item.
It you watched the gift when I click arrow back it supposed to be selected **All** but it remains selected that I selected before.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#selecting-an-item

Also if you do not want to have an item selected if it's clicked then make it `.withSelectable(false)`

**Comment by mikepenz** [comment]
Please report back if you have more issues
