### ISSUE TITLE
My Application crashed using your library

### ISSUE THREAD

**Issue by NorthZuera** [mikepenz/MaterialDrawer#2066]
Hey @mikepenz, i'm work in my app about "entrepreneurship" i using your library for create a method for get famous e set titles theirs for intent in fragments and I'm also making a menu showing pre-defined users. But when i create this method, i use "String[]" 
and this is necessary. I watch a video in youtube saying this method and i want use in my app, but 
as I said i cannot use this method:

```java
private List<Person> getSetProfileList(){
            String[] names = new String[]{"User 1", "User 2", "User 3", "User 4"};
            String[] emails = new String[]{"emailUser_1_@gmail.com", "emailUser_2_@gmail.com", "emailUser_3_@gmail.com", "emailUser_4_@gmail.com"};
            int[] photos = new int[]{R.drawable.person_1, R.drawable.person_2, R.drawable.person_3, R.drawable.person_4};
            int[] background = new int[]{R.drawable.gallardo, R.drawable.vyron, R.drawable.corvette, R.drawable.paganni_zonda};
            List<Person> list = new ArrayList<>();

            for(int i = 0; i < names.length; i++){
                ProfileDrawerItem aux = new ProfileDrawerItem();
                ERROR: aux.setName(names[i]);
                aux.setEmail(emails[i]);
                aux.setIcon(getResources().getDrawable(photos[i]));

                Person p = new Person();
                p.setProfile(aux);
                p.setBackground(background[i]);

                list.add( p );
            }
            return(list);
        }
```

I marked it as "ERROR:" to show where it is giving error. i cannot use this method so i use this other method:

```java
private List<Person> getSetProfileList(){
        String[] names = new String[]{"User 1", "User 2", "User 3", "User 4"};
        String[] emails = new String[]{"emailUser_1_@gmail.com", "emailUser_2_@gmail.com", "emailUser_3_@gmail.com", "emailUser_4_@gmail.com"};
        int[] photos = new int[]{R.drawable.person_1, R.drawable.person_2, R.drawable.person_3, R.drawable.person_4};
        int[] background = new int[]{R.drawable.abilio_diniz, R.drawable.bill_gates, R.drawable.fabio_seixas, R.drawable.mark_zuckerberg};
        List<Person> list = new ArrayList<>();

        for(int i = 0; i < names.length; i++){
            ProfileDrawerItem aux = new ProfileDrawerItem();
            aux.getName().setText(names[i].toString());
            aux.getEmail().setText(emails[i].toString());
            aux.getIcon().setIcon(getResources().getDrawable(photos[i]));

            Person p = new Person();
            p.setProfile(aux);
            p.setBackground(background[i]);

            list.add( p );
        }
        return(list);
    }
```

But even though it is giving error, even taking the method and setting!

```
Follow error: "Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mikepenz.materialize.holder.StringHolder.setText(java.lang.String)' on a null object reference
                                                       at br.com.testes.testederecycleview.MainActivity.getSetProfileList(MainActivity.java:255)
                                                       at br.com.testes.testederecycleview.MainActivity.onCreate(MainActivity.java:114)"
```

Sorry for use very "this method"! :) I necessary answer, Thanks! Gabriel B.

*EDIT: This method at where i use is also giving error in this line, but I believe, as I said, that it is about the method I used and it must be wrong... Error:

```java
        listProfile = getSetProfileList();
```

listProfile is a variable:     `private List<Person> listProfile;`

**Comment by mikepenz** [comment]
you somewhere set the text as `null`
might be related to: https://github.com/mikepenz/Materialize/issues/17

(you might also want to enhance the formatting of your issue :D quite hard to see what's going on)

**Comment by NorthZuera** [comment]
So, I stated in my text: "I", but how do I withdraw null in my variable?

**Comment by NorthZuera** [comment]
But what I mean is that the person in the video put setText, and I did this kind of "gambiarra" and I do not know if it's right, it's giving error I do not know why!

**Comment by mikepenz** [comment]
hmm I don't know what you do, but there does not exist a `setName` method on the `ProfileDrawerItem` 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L84

**Comment by NorthZuera** [comment]
I also don't know, why the video is 2015. I will try change "getName().setText(names[i])" for ".withName(names[il)". I'll try, but if this method does not work I'll return a response. Please dont close this Issue

**Comment by mikepenz** [comment]
@NorthZuera please use the latest version of the library. The github repository shows all code, has a sample application and everything is documented
