### ISSUE TITLE
Loading Image from Link into ProfileDrawerItem

### ISSUE THREAD

**Issue by pramodjg** [mikepenz/MaterialDrawer#2067]
I tried to load image into ProfileDrawerItem, but not worked.  Is there anything I am missing?

` IProfile newprofile = new ProfileDrawerItem().withName("name").withIcon("link").withIdentifier("identifier"));`

**Comment by mikepenz** [comment]
please check out the sample and read the readme
you need a `DrawerImageLoader`

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#load-images-via-url
