### ISSUE TITLE
ExpandableBadgeDrawerItem drop down

### ISSUE THREAD

**Issue by balasaheb143** [mikepenz/MaterialDrawer#2068]
How add drop down images in  ExpandableBadgeDrawerItem 
How add divider for each row

**Comment by mikepenz** [comment]
@balasaheb143 not supported

**Comment by mikepenz** [comment]
@balasaheb143 either create a `CustomDrawerItem` which has the divider and use it as child, or ad a `DividerItem` after each normal item
