### ISSUE TITLE
Custom view of accounts list

### ISSUE THREAD

**Issue by KhalilTB** [mikepenz/MaterialDrawer#2069]
How can I change the list view of accounts when the user tap the icon of listing available accounts? I want to change the view in a way that pushes the drawer contents down instead of hiding them.

**Comment by mikepenz** [comment]
@KhalilTB that's not possible, as both lists share the same `RecyclerView` and it's just replaced. 

It would require a big change to allow this, and as it is a very specific case this won't be part of this project. 

You will have to implement this on your own.
