### ISSUE TITLE
Can description of DrawerItem has multiple lines?

### ISSUE THREAD

**Issue by li3p** [mikepenz/MaterialDrawer#2070]
First I wanna thank you for your brilliant work. It saves a lot of my time to my development.

Now I have one question: does the description of DrawerItem only support one line currently? In the sample app I found that description of DrawerItem will be truncated and appended with “...” if it is too long. 

Currently I am using the Material Drawer in the embedded way to work with the preference activity, it works great except only one line supported in the description of each DrawerItem. Is it possible to have a method to display full description in multiline?

**Comment by mikepenz** [comment]
@li3p the default one not. but you can create a `CustomDraewrItem` or modify the original one to allow you this

**Comment by mikepenz** [comment]
copy the original layout to your project (keep the name) and modify it to your needs:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_primary.xml#L49
