### ISSUE TITLE
Drawer item gets deselcted

### ISSUE THREAD

**Issue by anshul90** [mikepenz/MaterialDrawer#2071]
Here I'm updating a `DrawerItem` dynamically from a fragment with badge but most of the time it's getting deselected. Please tell me if I'm doing anything wrong. 

     `public void onUpdate() {
        if (AppPreferences.getNotificationRead(this, AppUtils.NOTIFICATION_READ) != null) {
            String value = AppPreferences.getNotificationRead(this, AppUtils.NOTIFICATION_READ);
            if (!value.equals("0")) {
                itemFeeds = new PrimaryDrawerItem().withIcon(FontAwesome.Icon.faw_newspaper_o).withIdentifier(4)
                        .withName(getString(R.string.activity_feeds)).withSelectable(true)
                        .withBadge("" + value).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.md_red_700));
            } else {
                itemFeeds = new PrimaryDrawerItem().withIcon(FontAwesome.Icon.faw_newspaper_o).withIdentifier(4)
                        .withName(getString(R.string.activity_feeds)).withSelectable(true);
            }
            drawer.updateItem(itemFeeds);
        }
        Fragment currentFragment = getSupportFragmentManager().findFragmentById(R.id.frame_container);
        if (currentFragment instanceof ActivityFeedsFragment) {
            // add your code here
            if (drawer.getCurrentSelection() != 4)
                drawer.setSelectionAtPosition(4, false);
        }

        }`

**Comment by mikepenz** [comment]
@anshul90 you create a new item when you update it. just remember the item you have at position 4. modify it, and then notify the drawer about the update
