### ISSUE TITLE
Using with ButterKnife

### ISSUE THREAD

**Issue by D330** [mikepenz/MaterialDrawer#2074]
I wrote helper class

```java
public class NavigationDrawer {

    private Drawer drawer;

    @BindView(R.id.drawer_footer_logo) ImageView footerLogo;

    @OnClick(R.id.drawer_footer_logo)
    public void onFooterLogoClick() {
         close():
         if(drawerListener != null) {
             drawerListener.onFooterLogoClick();
        }
    }

    public NavigationDrawer(Activity activity) {
         drawer = new DrawerBuilder()
             .withActivity(activity)
             .withHeader(R.layout.drawer_header)
             .withFooter(R.layout.drawer_footer)
             //etc..
             .build();
         ButterKnife.bind(this, drawer.getDrawerLayout());
    }

public void close() {
    drawer.close();
}

    //etc..

}
```

When I click on the logo, nothing happens (the side menu should close). If I change @OnClick to setOnClickListener after ButterKnife.bind, then the application drops to NPE. What's wrong?

**Comment by mikepenz** [comment]
Please check if the `drawer.getDrawerLayout()` really contains this child view (access it via the normal way) 

There would be no reason of butterknife not to work, other than the view not being there at this moment.

**Comment by mikepenz** [comment]
Please report back if you have more issues. 

I use butterknife in many of my projects and it does not have conflicts
