### ISSUE TITLE
IDrawerItem identifier should be of type Int

### ISSUE THREAD

**Issue by mradzinski** [mikepenz/MaterialDrawer#2075]
MaterialDrawer provides the ability to inflate a menu from an XML resource, and given the following partial resource:

```
    <item
        android:id="@+id/action_my_performance"
        android:checked="true"
        android:icon="@drawable/ic_goals"
        android:title="@string/my_performance"/>
```

`android:id="@+id/action_my_performance"` will be of type `Int` which will be assigned as the menu item identifier (although the same is of type `Long`). If the implementer has a `switch` statement to determine which menu item has been selected/clicked then it'll be impossible to compare the identifier vs. the resource's menu item id (Integers can't be compared against Longs).

<img width="329" alt="screen shot 2017-10-19 at 8 05 58 am" src="https://user-images.githubusercontent.com/4214209/31768141-631c787a-b4a4-11e7-9e24-6701b80c8af7.png">

**Comment by mikepenz** [comment]
@mradzinski no `long` is correct as the `RecyclerView.Adapter` expects a long id:
https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#getItemId(int)

**Comment by mradzinski** [comment]
I get your point, but that casting should be internally handled by the library then. Like is said, you'll be assigning the item on the RecyclerView the id of the loaded menu item resource. If the loaded resource is of type `Integer` then there's no problem (the casting is done automatically) but to evaluate if a certain item has been tapped you'll be providing a `Long` as the identifier when the implementer actually provided the library with an `Integer` (the id of the menu resource item). It's kind of like providing apples and getting pears.

**Comment by mikepenz** [comment]
If you want to improve this behaviour. You might want to open a PR
