### ISSUE TITLE
Disable drawer

### ISSUE THREAD

**Issue by davix10** [mikepenz/MaterialDrawer#2078]
Hi, it is possible disable the drawer either with the hamburger icon and with the swipe?
If this is not possible, can I disable each item in the drawer?

Thanks.

**Comment by mikepenz** [comment]
you can lock the drawer. see the official documentation of the `DrawerLayout` for this please
and you can remove or consume the event for the hamburger listener. 

disabling drawerItems can be done by setting it enabled to false, and notify the drawer about this item's update

**Comment by davix10** [comment]
Thank you for your quick reply!

**Comment by jahirfiquitiva** [comment]
Hi @mikepenz 

I am trying to disable the drawer using this:
```kotlin
drawer?.drawerLayout?.setDrawerLockMode(.LOCK_MODE_LOCKED_CLOSED, Gravity.START)
drawer?.actionBarDrawerToggle?.toolbarNavigationClickListener = null
```

But it isn't working :/ ... Any help? Thanks in advance
