### ISSUE TITLE
Cannot update item name on drawer

### ISSUE THREAD

**Issue by jrcacd** [mikepenz/MaterialDrawer#2079]
I tried this way: 
```
drawerItem.withName(R.string.name)
drawer.updateItem(drawerItem)
```

And this way:
`drawer.updateName(identifier, StringHolder("New name"));`

But it remained unchainged

**Comment by mikepenz** [comment]
your drawerItem has an identifier defined?
You do the update on the UI thread?

**Comment by jrcacd** [comment]
Yes, and yes.

**Comment by mikepenz** [comment]
it is working for me in the sample application. can you please provide a sample application showcasing the issue?

**Comment by mikepenz** [comment]
Please report back. Will open if further action is required
