### ISSUE TITLE
MaterialDrawer themes

### ISSUE THREAD

**Issue by skir** [mikepenz/MaterialDrawer#208]
How to apply MaterialDraver themes in my app?
I added dependency in gradle 
`compile('com.mikepenz.materialdrawer:library:0.9.5@aar') {
        transitive = true
    }`
but if I specify 
`<style name="AppTheme" parent="MaterialDrawerTheme">`
AndoidStudio will not recognize it.

**Comment by skir** [comment]
Sorry, something went wrong and I used too old version. I changed version to 2.7.6 and theme recognized.

**Comment by mikepenz** [comment]
@skir great that you were able to fix this for you ;)
