### ISSUE TITLE
java.lang.NoClassDefFoundError: com.mikepenz.fastadapter.adapters.HeaderAdapter

### ISSUE THREAD

**Issue by jxr202** [mikepenz/MaterialDrawer#2081]
```java
10-27 11:20:31.553  6679  6679 E AndroidRuntime: Process: com.oudmon.lifehelper, PID: 6679
10-27 11:20:31.553  6679  6679 E AndroidRuntime: java.lang.NoClassDefFoundError: com.mikepenz.fastadapter.adapters.HeaderAdapter
10-27 11:20:31.553  6679  6679 E AndroidRuntime:        at com.mikepenz.materialdrawer.DrawerBuilder.<init>(DrawerBuilder.java:869)
10-27 11:20:31.553  6679  6679 E AndroidRuntime:        at com.oudmon.lifehelper.MainActivity.initDrawer(MainActivity.java:45)
10-27 11:20:31.553  6679  6679 E AndroidRuntime:        at com.oudmon.lifehelper.MainActivity.onCreate(MainActivity.java:35)
10-27 11:20:31.553  6679  6679 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6378)
10-27 11:20:31.553  6679  6679 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
10-27 11:20:31.553  6679  6679 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2482)
10-27 11:20:31.553  6679  6679 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2589)
10-27 11:20:31.553  6679  6679 E AndroidRuntime:        at android.app.ActivityThread.access$1100(ActivityThread.java:169)
10-27 11:20:31.553  6679  6679 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434)
10-27 11:20:31.553  6679  6679 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
10-27 11:20:31.553  6679  6679 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
10-27 11:20:31.553  6679  6679 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5648)
10-27 11:20:31.553  6679  6679 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-27 11:20:31.553  6679  6679 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:845)
10-27 11:20:31.553  6679  6679 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:735)
10-27 11:20:33.513  5006  5006 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
```

**Comment by mikepenz** [comment]
do you use proguard? any more details what you try to do?

**Comment by flatdesignapps** [comment]
I have this same problem, when I want execute class. I created new project with Empty Activity.
`new DrawerBuilder().withActivity(this).build();`

Android Studio 3.0 RC 1
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"
    defaultConfig {
        applicationId "com.flatdesignapps.indirect.admin"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    compile('com.mikepenz:materialdrawer:5.9.5@aar') {
        transitive = true
        exclude group: 'com.android.support'
    }
}`

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-rc1'
        

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

**Comment by mikepenz** [comment]
Please add the sub dependencies of the lib manually. Seems the new build tools no longer handle transitive=true

**Comment by flatdesignapps** [comment]
You could show how it should look like, because by adding dependencies of the library, the problem continues.

**Comment by mikepenz** [comment]
The dependencies as seen here: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/build.gradle#L30

**Comment by jxr202** [comment]
I created new project with Empty Activity. Just test the API。

my project   

https://github.com/jxr202/LifeHelper

**Comment by mikepenz** [comment]
@jxr202 ok 2 issues. 

1.) pls update to the buildTools 26.0.2 as 26.0.1 has build issues missing some classes `buildToolsVersion "26.0.2"`
2.) pls add `compile 'com.android.support:recyclerview-v7:26.+'` as you exclude the support libs of the `materialDrawer` so it won't auto add the rv

**Comment by jxr202** [comment]
@mikepenz Your answer was very useful, and it solved my problem，Thank you！
