### ISSUE TITLE
Change Typeface of selected

### ISSUE THREAD

**Issue by balasaheb143** [mikepenz/MaterialDrawer#2087]
How change text size and typeface of selected item in drawer

**Comment by mikepenz** [comment]
@balasaheb143 you can only have a general `Typeface` for the provided default items, If you need more flexibility. You want to create your own `CustomDrawerItem` supporting this usecase

**Comment by balasaheb143** [comment]
How add custom typeface in CustomDrawerItem for selected item can you provide sample

**Comment by mikepenz** [comment]
@balasaheb143 there are a few `CustomDrawerItem`s in the sample app. and the FAQ contains details about it too: https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md
