### ISSUE TITLE
Crash when opening CompactHeader Drawer from sample app

### ISSUE THREAD

**Issue by pn** [mikepenz/MaterialDrawer#2089]
Hi,

Thank you for this great library!

There is a crash when opening CompactHeader Drawer in the sample app.

Looks like color defined in styles.xml is triggering this:
`<item name="material_drawer_selected_text">#F1433C</item>`

A workaround is to reference the color:
`<item name="material_drawer_selected_text">@color/material_drawer_dark_selected_text</item>`

Stack trace:

> android.content.res.Resources$NotFoundException: Resource ID #0x0
>                                                                                            at android.content.res.Resources.getValue(Resources.java:1351)
>                                                                                            at android.content.res.Resources.getColor(Resources.java:963)
>                                                                                            at android.support.v4.content.res.ResourcesCompat.getColor(ResourcesCompat.java:143)
>                                                                                            at com.mikepenz.materialize.util.UIUtils.getThemeColor(UIUtils.java:42)
>                                                                                            at com.mikepenz.materialize.util.UIUtils.getThemeColorFromAttrOrRes(UIUtils.java:56)
>                                                                                            at com.mikepenz.materialize.holder.ColorHolder.color(ColorHolder.java:141)
>                                                                                            at com.mikepenz.materialdrawer.model.BaseDrawerItem.getSelectedTextColor(BaseDrawerItem.java:299)
>                                                                                            at com.mikepenz.materialdrawer.model.BaseDescribeableDrawerItem.bindViewHelper(BaseDescribeableDrawerItem.java:72)
>                                                                                            at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.java:71)
>                                                                                            at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.java:18)
>                                                                                            at com.mikepenz.fastadapter.listeners.OnBindViewHolderListenerImpl.onBindViewHolder(OnBindViewHolderListenerImpl.java:30)
>                                                                                            at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.java:692)
>                                                                                            at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
> ...

**Comment by mikepenz** [comment]
@pn thank you very much. Seems to be a result of: https://github.com/mikepenz/Materialize/commit/6a9b3625a47ce190ee480705963ba317afce824b

**Comment by mikepenz** [comment]
Fixed in v1.1.2 of Materialize. will be included in the next Materialdrawer update. 

Thanks

https://github.com/mikepenz/Materialize/releases/tag/v1.1.2
