### ISSUE TITLE
setOnDrawerItemLongClickListener method does not work

### ISSUE THREAD

**Issue by OlegWock** [mikepenz/MaterialDrawer#209]
Hi, I found a bug. Here is my code, but nothing in the logs (v. 2.7.6)

```java
result.setOnDrawerItemLongClickListener(new Drawer.OnDrawerItemLongClickListener() {
            @Override
            public boolean onItemLongClick(AdapterView<?> adapterView, View view, int i, long l, IDrawerItem iDrawerItem) {
                Log.d(LOG_TAG, "Long click on drawer item");
                // Some code
                return false;
            }
        });

**Comment by OlegWock** [comment]
By the way, if you create a Drawer to call a method withOnDrawerItem LongClickListener, then subsequent calls setOnDrawerItemLongClickListener work. Hope this helps.

P.S. Sorry for my English

**Comment by mikepenz** [comment]
@OlegWock yeah i found what's the issue. it's fixed in the next version
