### ISSUE TITLE
About view of navigation drawer

### ISSUE THREAD

**Issue by rohitlanjewar009** [mikepenz/MaterialDrawer#2091]
How to add name along with email in accountheader and dropdown list as shown in image below. Please help me. I also wanted to get view added for that email list as shown in image below. 
![Uploading Screenshot_2017-11-02-13-22-45.png…]()

**Comment by mikepenz** [comment]
@rohitlanjewar009 everything is shown in the sample application

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java

Use the `Drawer` with a `AccountHeader` and you are good to go. (the screenshot was actually taken from the sample application)
