### ISSUE TITLE
[v6] withIsExpanded(true) buggy

### ISSUE THREAD

**Issue by rmarau** [mikepenz/MaterialDrawer#2092]
Hi

After updating to v6 I'm having problems with .withIsExpanded(true). It might just be a FastAdapter V3 issue. Tested it using demo app DrawerActivity.java.

It will not expand subItems upon creation. The Expand arrow is misleading (as if it's expanded). In fact clicking on it will collapse Primary items sitting bellow.

Thanks

**Comment by mikepenz** [comment]
@rmarau could you please add more details. If I enable `expandable` functionality in the demo app everything works as expected.

**Comment by rmarau** [comment]
@mikepenz Check this [test](https://github.com/rmarau/MaterialDrawer/commit/9a028f6b0c2241b2bfed105c4fd3056e34e14556)

For the sake of completeness, I've used sdk version 26.

**Comment by mikepenz** [comment]
@rmarau oh initial expand state. was this working in the past? 

in general i'd recommend to use the `ExpandableExtension` of the `FastAdapter` and just expand it programatically after building the drawer, so all states can be properly managed

**Comment by rmarau** [comment]
Ok, I'll have a look on that. 
But then, what's the purpose of `withIsExpanded`.? It was working fine with materialdrawer:5.9.5
I could even do this on-the-fly (upon creating drawer):
`navigationView.addItemAtPosition(expandedDrawerWithExpandedTrue, 1);`

Now, not only it fails the auto-expand, it also harms the Primary items sitting bellow (as in [test](https://github.com/rmarau/MaterialDrawer/commit/9a028f6b0c2241b2bfed105c4fd3056e34e14556))

I'll come back here if I found some workaround.
Thanks

**Comment by mikepenz** [comment]
@rmarau I will also take a look. and possibly try to improve this and add back the old behaviour. 

`withIsExpanded` is primarily a internal setter to allow keeping track of it's state.

**Comment by rmarau** [comment]
@mikepenz It looks to be just a missing drop of items in the adapter when adding Expandable Items.
I've managed to come up with a [workaround](https://github.com/rmarau/MaterialDrawer/commit/ef6407abf5c63fcf41e51134c6d8a655ce2be43c). 

It simply drops the subItems in the Adapter manually.

**Comment by mikepenz** [comment]
@rmarau ok I have checked this now with v2.6.3 of the `FastAdapter` and it only worked with the `positionBasedStateManagement` which was already deprecated by then. (and got removed in v3) 

with the v3 of the `FastAdapter` you should use the `ExpandableExtension` which handles it for you. 

You can get expand using that by doing this:

```java
result.getExpandableExtension().expand(position);
```
(the `getExpandableExtension` convenient method will be added in the next update, right now you can access it by doing `drawer.getAdapter().getExtensions()`)

**Comment by rmarau** [comment]
Thank you for helping.
That solved my problem.
