### ISSUE TITLE
Error on add item on menu

### ISSUE THREAD

**Issue by dafdesig** [mikepenz/MaterialDrawer#2093]
Hi,

I need some help, I've been trying to solve it for 3 days and I did not find the solution.
When I add an item in Builder the app stops working and closes.

Drawer menuLeft = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withActionBarDrawerToggleAnimated(true)
                .withDrawerGravity(Gravity.LEFT)
                .withSavedInstance(savedInstanceState)
                .withSelectedItem(-1)
                .withDisplayBelowStatusBar(false)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.app_name).withIdentifier(1) // this line
                )
                .withActionBarDrawerToggle(true)
                .build();

menuLeft.addItem(new DividerDrawerItem()); // this line does not error

===== ERROR on android 
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: eprofessional.websister, PID: 3644
                  java.lang.NoSuchMethodError: No static method setBackground(Landroid/view/View;Landroid/graphics/drawable/Drawable;)V in class Landroid/support/v4/view/ViewCompat; or its super classes (declaration of 'android.support.v4.view.ViewCompat' appears in /data/app/eprofessional.websister-2/split_lib_dependencies_apk.apk:classes6.dex)

Tks,
Daniel

**Comment by dafdesig** [comment]
My greadle

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile files('libs/ksoap2.jar')
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.android.support:design:24.0.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:support-v4:24.2.1'
    compile 'com.android.support:support-vector-drawable:24.2.1'
    testCompile 'junit:junit:4.12'

    compile("com.mikepenz:materialdrawer:6.0.0@aar") {
        transitive = true
    }

}

**Comment by mikepenz** [comment]
@dafdesig the latest version of the drawer requires the latest support libraries:
v27.0.0

older versions will conflict

if you want to stick to the old ones you can do this:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/build.gradle#L87

**Comment by dafdesig** [comment]
Great... i can back to work after 5 days kkkk
