### ISSUE TITLE
CustomPrimaryDrawerItem no where to be found

### ISSUE THREAD

**Issue by ohenepee** [mikepenz/MaterialDrawer#2099]
Android Studio can't resolve `CustomPrimaryDrawerItem`. has it been removed? Even the full path does not work `com.mikepenz.materialdrawer.drawerItems.CustomPrimaryDrawerItem`

Everything else works!

I am using this in my `gradle:app` file
```
compile('com.mikepenz:materialdrawer:5.9.5@aar') {
  transitive = true
  exclude group: 'com.android.support'
}
```

**Comment by mikepenz** [comment]
Well these are custom, and samples ;) :D 

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomPrimaryDrawerItem.java

**Comment by ohenepee** [comment]
Yeah... found it and wanted to close the issue, except that its not working... I simply copied the source code.. changed the package string to my app's package name and placed it on the same level as my `MainActivity.java`.

Yet there's not code completion support... I even rebuilt the entire project just in case... and yet no methods are exposed... Any Help? @mikepenz

**Comment by ohenepee** [comment]
100% Working Now!
