### ISSUE TITLE
Cannot set translucent status bar

### ISSUE THREAD

**Issue by tjmille2** [mikepenz/MaterialDrawer#2102]
I am using an AppCompat theme with the appropriate settings for a translucent status bar which slightly darkens the content behind it. When using DrawerBuilder, setting withTranslucentStatusBar(true) does not yield the expected behavior. My content is placed below the status bar. I followed a suggestion in another question reccomending the root layout be a ScrimsInsetFrameLayout, but that just places my content below a transparent status bar, while placing the toolbar under the status bar where it shouldn't be.

**Comment by mikepenz** [comment]
@tjmille2 something in your theme seems to be missing. as you can see in the sample it works correctly with proper theme

**Comment by tjmille2** [comment]
I checked your demo app. I can get the toolbar & fragment contents drawing behind the status bar with

if (Build.VERSION.SDK_INT >= 19) {
            drawer.getDrawerLayout().setFitsSystemWindows(false);
        }


I fixed the toolbar issue by adding top margin equal to the status bar on version of Android Kitkat and higher.

The only oddity now is that the status bar is fully transparent, not translucent, like I would like.

**Comment by tjmille2** [comment]
I checked your demo app. I can get the toolbar & fragment contents drawing behind the status bar with

```
if (Build.VERSION.SDK_INT >= 19) {
            drawer.getDrawerLayout().setFitsSystemWindows(false);
        }
```


I fixed the toolbar issue by adding top margin equal to the status bar on version of Android Kitkat and higher.

The only oddity now is that the status bar is fully transparent, not translucent, like I would like.

**Comment by tjmille2** [comment]
I checked your demo app. I can get the toolbar & fragment contents drawing behind the status bar with

```
if (Build.VERSION.SDK_INT >= 19) {
            drawer.getDrawerLayout().setFitsSystemWindows(false);
}
```


I fixed the toolbar issue by adding top margin equal to the status bar on version of Android Kitkat and higher.

The only oddity now is that the status bar is fully transparent, not translucent, like I would like.

**Comment by tjmille2** [comment]
I checked your demo app. I can get the toolbar & fragment contents drawing behind the status bar with

```
if (Build.VERSION.SDK_INT >= 19) {
            drawer.getDrawerLayout().setFitsSystemWindows(false);
}
```


I fixed the toolbar issue by adding top margin equal to the status bar on version of Android Kitkat and higher.

The only oddity now is that the status bar is fully transparent, not translucent, like I would like.

**Comment by mikepenz** [comment]
the `DrawerLayout` should have `setFitsSystemWindows true`. The Fragment activity in the sample has the fragments below the `Actionbar` + the Fragments contain the drawer thus it's different. 

For a normal `Activity` with the drawer there should be no special configuration needed

**Comment by tjmille2** [comment]
When I don't set drawer.getDrawerLayout().setFitsSystemWindows(false); the translucent effect comes back to the drawer, but the fragment's contents are drawn below a color colored status bar. The toolbar doesn't require extra margin in this setting, so it seems the fragment's contents are simply drawing below the status bar. setFitsSystemWindows(true) is not set anywhere in the fragment's layout.

**Comment by mikepenz** [comment]
@tjmille2 working with the `fitsSystemWindows()` flag can be really tricky. you either have it somewhere too much, or too less, or a false true or false false somewhere. 

It could also be that you need a `ScrimInsets*Layout` somewhere. 

But it is definitely do-able to properly set up everything without the need of custom inset handling

**Comment by mikepenz** [comment]
Is this issue solved? Closing for the time being ;)
