### ISSUE TITLE
Lock Mini Drawer View

### ISSUE THREAD

**Issue by h777arsh** [mikepenz/MaterialDrawer#2103]
currently `getDrawerLayout()` from mini drawer it returns null. so how to lock drawer layout only in mini drawer?

PS: Amazing library

**Comment by mikepenz** [comment]
@h777arsh there is no `DrawerLayout` in case of the `MiniDrawer` 

Just the `Crossfader`
https://github.com/mikepenz/Crossfader/blob/develop/library/src/main/java/com/mikepenz/crossfader/Crossfader.java

**Comment by h777arsh** [comment]
Okay, First thank you for very quick reply.
so now I need to customize sliding panel like this thread [#1822](https://github.com/mikepenz/MaterialDrawer/issues/1822]).

Thank you.

**Comment by mikepenz** [comment]
As far as I understand your message. This issue is resolved right?
