### ISSUE TITLE
CustomPrimaryDrawerItem is not working in Mini Drawer

### ISSUE THREAD

**Issue by h777arsh** [mikepenz/MaterialDrawer#2104]
Hi, 
If we create `CustomPrimaryDrawerItem` as per your sample code then we can not use in a mini drawer because I think mini-drawer item depends on `PrimaryDrawerItem`. how can we fix that?

**Comment by mikepenz** [comment]
To support custom items, you need a `CustomMiniDrawer`

https://github.com/mikepenz/MaterialDrawer/commit/8deedf8470f19c74ed6b826fd5aadc4eaed506da

**Comment by h777arsh** [comment]
Okay, made some changes as per new version and it is working. 
can you suggest how to save its value? because as per default mini drawer can retain its instance with the help of drawer's `savedInstance`, but for `CustomMiniDrawer` what can we do?

**Comment by mikepenz** [comment]
well the `CustomMiniDrawer` extends the `MiniDrawer` so it has the same functions
