### ISSUE TITLE
profile image

### ISSUE THREAD

**Issue by neelamharne** [mikepenz/MaterialDrawer#2105]
Account image structure changes according to image size

![screenshot](https://user-images.githubusercontent.com/21379418/32598810-af293db2-c560-11e7-8045-ececf19f866e.png)
account image structure is changes according to image size
![screenshot_2017-11-09-15-04-30 1](https://user-images.githubusercontent.com/21379418/32598748-870091c8-c560-11e7-865c-f248fc0bb5ef.png)

**Comment by mikepenz** [comment]
@neelamharne you should provide a square image. glide or picasso allow this as far as I know

**Comment by mikepenz** [comment]
You can also check this: https://github.com/mikepenz/MaterialDrawer/issues/1394#issuecomment-233187311

**Comment by Yayo-Arellano** [comment]
My temporal solutios is like this:
```

clinicHeader = new AccountHeaderBuilder()
                .withActivity(this)
                .withTranslucentStatusBar(true)
                .withHeaderBackground(R.drawable.header)
                .withSelectionListEnabledForSingleProfile(false)
                .addProfiles(clinicProfileDrawer)
                .build();

        BezelImageView image = clinicHeader.getView().findViewById(R.id.material_drawer_account_header_current);
        image.setScaleType(ImageView.ScaleType.CENTER_CROP);
```
