### ISSUE TITLE
Clicking drawer item in mini drawer crashes if item identifier is not set manually.

### ISSUE THREAD

**Issue by MadeDragon** [mikepenz/MaterialDrawer#2106]
MiniDrawer:490 throws a NullPointerException if an item being clicked is not built with positive identifier with withIdentifier(long) (getDrawerItem() returns null obviously w/ negative identifiers but they are assigned negative values if not set manually).
Are we required to set ids with withIdentifier() (not a problem actually as I'm about to use them anyway) or am I missing something? This was not an issue in MaterialDrawer 5.9.3.

**Comment by mikepenz** [comment]
@MadeDragon do you have the stacktrace for that nullpointer?

It is always recommended to use `identifiers`. I still should fix the NPE though

**Comment by mikepenz** [comment]
@MadeDragon thank you

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L490

will fix that with an update.
