### ISSUE TITLE
Several questions

### ISSUE THREAD

**Issue by bydlokoder** [mikepenz/MaterialDrawer#211]
Hi. Thanks for you library :) It is realy nice!

I have several questions:

How to open drawer when application is opened?

What is the best way to handle a click on item? 
In your examples I found that you get the name of the item, also we can use position in onClick (but what if i add elements dinamicly? Should I count static elements?) Please provide the best solution.

When I click on item the drawer is closed automaticaly, but I want to open a dialog without closing the drawer. How to do that?

**Comment by wKovacs64** [comment]
You can open the drawer with `result.openDrawer();` immediately after you've build the drawer and have a Drawer.Result object if you wish.

As for handling clicks, you're probably looking for identifiers. You can create each drawer item using `.withIdentifier(someNumber)` and then in your `Drawer.OnDrawerItemClickListener` you can just use a switch statement on `drawerItem.getIdentifier()` to determine which one was clicked. The example app uses inline literal integers but I would probably recommend defining them elsewhere like `protected static final int DRAWER_ITEM_SEARCH = 13;` for example and comparing the result of `getIdentifier()` to the constants you defined.

I don't think you can open a dialog without closing the drawer. I think the only drawer item types that don't close the drawer inherently are switches and toggles. @mikepenz might correct me here, though.

Hope that helps for now.

**Comment by mikepenz** [comment]
@wKovacs64 thanks for answering. 

@bydlokoder you can disable the closing with this `withCloseOnClick(false)` then you can handle the closing on your own
