### ISSUE TITLE
Animate the Hamburger Icon While the Drawer is being pulled

### ISSUE THREAD

**Issue by feinstein** [mikepenz/MaterialDrawer#2110]
It would be a nice touch (pun intended) if the hamburger icon on a `toolbar` could be animated (maybe passing a reference to the hamburger `drawable`? or extracting it from a `toolbar`?) to an arrow, progressively, while the drawer is opening.

I think this is the default behavior, and can be observed on the template example of the `Navigation Drawer Activity` and on the VLC app. If you don't know what I am talking about, please check one of these examples, and slide the drawer slowly and see how the hamburger animates.

That being said, all google apps that I know don't implement this, so I must say it's a bit curious at least, so maybe add it as an option?

**Comment by mikepenz** [comment]
@feinstein no this is not the default behaviour. it is against the material design guidelines and should not be done, as the drawer should overlap the toolbar anyways. 

the functionality itself is provided by the `ActionbarDrawerToggle` and you can enable it again if you use a `Toolbar`

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L496

**Comment by feinstein** [comment]
@mikepenz I just saw the `CustomContainer` example on the example app does implement this behavior, with a different animation though.

I just got curious now why would Google placed this animation as default on the `ActionbarDrawerToggle`, it it goes against the Material Design guidelines...

**Comment by erodewald** [comment]
Google regularly disobeys Material Design _when it makes sense_ -- I don't think it's entirely unreasonable to support out-of-guideline features as an option. That being said, this is *Material* Drawer and it's entirely up to the maintainer.
