### ISSUE TITLE
How to change text size of Badge (Non-Minidrawer)

### ISSUE THREAD

**Issue by ohenepee** [mikepenz/MaterialDrawer#2111]
I can't find any `@dimen` attribute to change the text size of my badges, I increase the primary text size using the `dimen` attribute and the badges also got increased which isn't cool (by the percentage I increased the drawerItem text). I there anyway to get the badges back to normal without affecting the drawerItems text sizes?

**Comment by mikepenz** [comment]
@ohenepee the bade uses the same text dimension: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_primary.xml#L77

You can either create a `CustomDrawerItem`, or you add this xml to your project and adjust the dimension.

**Comment by ohenepee** [comment]
You mean I can just place this XML (modified to suite me) in my layout and do nothing else and it'll just work? O.o

**Comment by mikepenz** [comment]
Yep as long as you do not change the type of layouts or remove id's it will work. 

The android build will take care that the one in your project is used in favour of the one in libs. the same works for dimens, strings, ... basically most xml based things.

**Comment by ohenepee** [comment]
Wow! Thanks a bunch... testing atm.. will close issue if this works... you're Awesome!!!

**Comment by ohenepee** [comment]
Okay, that didn't really work (perhaps b'cos I've already using a `CustomPrimaryDrawerItem` for background color)... how do I modify the badge dimensions from this class?

**Comment by mikepenz** [comment]
@ohenepee which layout do you use? only the xml you use matters. 

but as you already have a custom draweritem. just set the size you want in the `bindView` method

**Comment by ohenepee** [comment]
Not really a pro in Java & Android development... I can't seem to implement a custom viewHolder (if I even should) in the `CustomPrimaryDrawerItem` which is extended from `AbstractPrimaryDrawerItem`. I get an argument error of me giving 2 arguments when only 1 is required when I do this

```
public class CustomPrimaryDrawerItem extends AbstractBadgeableDrawerItem<CustomPrimaryDrawerItem, CustomPrimaryDrawerItem.ViewHolder> {
```

At the moment I am going with the increased badges. A little help with sample code would be appreciated. Thanks a lot

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomPrimaryDrawerItem.java#L26

You can then do something like

```java
viewHolder.badgeTextView.setTextSize()
```

**Comment by ohenepee** [comment]
`Error:(26, 15) error: cannot find symbol variable badgeTextView`

**Comment by mikepenz** [comment]
Well you have to get the view from the `ViewHolder` (badge itself is private) 

See the sourcecode here: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/AbstractBadgeableDrawerItem.java#L104

**Comment by estatico3** [comment]
@mikepenz for me the first option with xml works properly. Thanks a lot!
