### ISSUE TITLE
How to add custom layout in footer also with values to view programmatically

### ISSUE THREAD

**Issue by rohitmedcords** [mikepenz/MaterialDrawer#2113]

**Comment by mikepenz** [comment]
@rohitmedcords either you use a `DrawerItem` and set it as `StickyDrawerItem` 
or you create your own `CustomDrawerItem` and set it as `StickyDrawerItem` 

or you just use the `Footer` functionality and provide any view you want
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L672
