### ISSUE TITLE
Error converting bytecode to dex:

### ISSUE THREAD

**Issue by balasaheb143** [mikepenz/MaterialDrawer#2115]
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/mikepenz/materialdrawer/AccountHeaderBuilder;

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithDexMergerForDevDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/mikepenz/materialize/util/UIUtils;

After update to 6.0.0

**Comment by mikepenz** [comment]
@balasaheb143 v6.x uses the latest version of Materialize. which version do you have in your gradle?

**Comment by mikepenz** [comment]
MaterialDrawer v6.x

needs support libs 27.x
materialize 1.1.2
fastadapter 3.x
iconics 2.9.x

**Comment by mikepenz** [comment]
If you want different versions you can define a resolution strategy

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/build.gradle#L83
