### ISSUE TITLE
java.lang.NoSuchMethodError 

### ISSUE THREAD

**Issue by lekhanhduybkhn** [mikepenz/MaterialDrawer#2116]
when I using your lib and using on Android 5.1 with many device. Lib is crash with error

java.lang.NoSuchMethodError: 
  at com.mikepenz.materialdrawer.AccountHeaderBuilder.handleSelectionView (AccountHeaderBuilder.java:729)
  at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:821)

**Comment by zayn1991** [comment]
@lekhanhduybkhn what version of your library in dependency?

**Comment by mikepenz** [comment]
@lekhanhduybkhn please add the full stacktrace + please also provide the version of the library + other dependencies you have as already pointed out by @zayn1991 

You might also want to read the following:
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_use_different_sub_library_version.md

**Comment by mikepenz** [comment]
Close until further info is proivded
