### ISSUE TITLE
I,ve founded bug with Badge for MiniDrawer

### ISSUE THREAD

**Issue by zayn1991** [mikepenz/MaterialDrawer#2117]
**I used standart BadgeStyle class and set it to PrimaryDrawerItem-**

**I used** 

```
BadgeStyle badgeStyle = new BadgeStyle()
                .withBadgeBackground(ContextCompat.getDrawable(Application.getAppContext(), R.drawable.circle_red))
                .withTextColor(ContextCompat.getColor(Application.getAppContext(), R.color.color_white));
```

**Libraries, i,ve used:**

```
compile('com.mikepenz:materialdrawer:5.5.0@aar') {
        transitive = true
    }
    compile('com.mikepenz:aboutlibraries:5.8.0@aar') {
        transitive = true
    }
    compile 'com.mikepenz:google-material-typeface:3.0.1.2.original@aar'
    compile 'com.mikepenz:fontawesome-typeface:4.7.0.2@aar'
    compile('com.mikepenz:crossfader:1.5.0@aar') {
        exclude group: 'com.android.support:appcompat'
        exclude group: 'com.android.support:support'
    }
```
**In that class**
```
package com.mikepenz.materialdrawer.model;
//imports...
public class MiniDrawerItem extends BaseDrawerItem<MiniDrawerItem, MiniDrawerItem.ViewHolder> {

//...

@Override
    public void bindView(ViewHolder viewHolder) {
    //....
        boolean badgeVisible = StringHolder.applyToOrHide(mBadge, viewHolder.badge);
        //style the badge if it is visible
        if (badgeVisible) {
            mBadgeStyle.style(viewHolder.badge);
        }
    }
//.....
}
```
**you use** `StringHolder.applyToOrHide(mBadge, viewHolder.badge);`
**but if we need to hide badge,** `applyToOrHide` **method must take null - as first parameter.**

```
//method from StringHolder
public static boolean applyToOrHide(StringHolder text, TextView textView) {
        if (text != null && textView != null) {
            return text.applyToOrHide(textView);
        } else if (textView != null) {
            textView.setVisibility(View.GONE);
            return false;
        }
        return false;
    }
```

**For hiding badge with** `StringHolder.applyToOrHide(mBadge, viewHolder.badge);`
**i need to call:**
`itemPrimaryDrawer.withBadge(new StringHolder(null));
`
**because** `itemPrimaryDrawer.withBadge("");
`
**and**
`itemPrimaryDrawer.withBadge(null);
`
**shows error.**

**My solution - is changing method** `itemPrimaryDrawer.withBadge(null);` **to accept null**
**because i don't know right way, how to hide badge in bindView method with** `StringHolder.applyToOrHide(mBadge, viewHolder.badge);`

**P.S. Badge backround is showig, when we call**  `itemPrimaryDrawer.withBadge("");`
**That is bug, i think**

**Comment by mikepenz** [comment]
`itemPrimaryDrawer.withBadge(null);`

what's the error shown?

**Comment by zayn1991** [comment]
@mikepenz i found your answer. You said to use `item.withBadge((StringHolder) null);`
and it helped
