### ISSUE TITLE
How to use different badge styles?

### ISSUE THREAD

**Issue by zayn1991** [mikepenz/MaterialDrawer#2118]
Hi Mike! Thank you for fast answers)

I would like to use different badge styles: one style for badge in item MiniDrawer, another style for item in opened MiniDrawer (2 drawers, as in Gmail in tablet).
**I need to show a little circle badge in MiniDrawer and big circle badge in opened MiniDrawer**

I use this style **for showing a little red circle**
```
BadgeStyle badgeStyle = new BadgeStyle()
                .withColor(ContextCompat.getColor(Application.getAppContext(), R.color.color_e3000b))
                .withCornersDp(16)
                .withTextColor(ContextCompat.getColor(Application.getAppContext(), R.color.color_white));
```

and that is good for showing badge on MiniDrawer item, but when i open that drawer, badge on item shows as oval (horizontal width of badge is less).
I thouhg to use 2 different badge styles or change custom MiniDrawerItem
How to solve the problem of this?

![1](https://user-images.githubusercontent.com/17571172/33086981-5e3145dc-cefa-11e7-9f4c-77d3ce6a2bad.PNG)
![2](https://user-images.githubusercontent.com/17571172/33086988-6375291e-cefa-11e7-97b1-7416be2c4b36.PNG)

**Comment by mikepenz** [comment]
@zayn1991 I think for this requirement it would best to use a `CustomMiniDrawer`  allowing different `BadgeStyle`'s basically you can intercept the creation of the `MiniDrawer` item's when overwriting the `MiniDrawer` and then use whatever style your usecase needs :)

**Comment by zayn1991** [comment]
@mikepenz i have `CustomMiniDrawer` and `CustomMiniDrawerItem` in my project. May you help,  what method i need to change? And what to change?

**Comment by mikepenz** [comment]
@zayn1991 your `CustomMiniDrawerItem` get's filled with the `PrimaryDrawerItem` here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/MiniDrawerItem.java#L40

you can just change the passing in of the `BadgeStyle` to whatever `BadgeStyle` you need

**Comment by zayn1991** [comment]
@mikepenz 
but this will change the badgestyle of the item completely, and I need the badgestyle of one item to change depending on whether the MiniDrawer is open or not, don't it?

**Comment by mikepenz** [comment]
you need to create a copy of the badgeStyle set for the `DrawerItem` and have it's own for the `MiniDrawerItem`

**Comment by zayn1991** [comment]
@mikepenz i added 2 pictures in question

**Comment by zayn1991** [comment]
@mikepenz 
and this `badgeStyle `will not replace the style of the item completely at the same time? if I just don't take `badgeStyle `from `Primarydrawer item` in `CustomMiniDrawer `constructor?

**Comment by mikepenz** [comment]
well the screenshot shows you have to adjust the style for the normal `DrawerItem` and use the one which works fine for the `MiniDrawerItem` you can do that hardcoded during the creation of those items.

**Comment by zayn1991** [comment]
@mikepenz do you mean i'll have to hardcode `badgeStyle `in custom` MiniDrawerItem`, ignoring `badgeStyle ` of `PrimaryDrawerItems`?

**Comment by zayn1991** [comment]
As @mikepenz said, i did

```
private BadgeStyle mBadgeStyle = new BadgeStyle()
        .withColor(ContextCompat.getColor(Application.getAppContext(), R.color.color_e3000b))
        .withCornersDp(16)
        .withTextColor(ContextCompat.getColor(Application.getAppContext(), R.color.color_white));
    private boolean mEnableSelectedBackground = false;
    protected DimenHolder mCustomHeight;

    public CustomMiniDrawerItem() {}

    public CustomMiniDrawerItem(CustomPrimaryDrawerItem primaryDrawerItem) {
        this.mIdentifier = primaryDrawerItem.getIdentifier();
        this.mTag = primaryDrawerItem.getTag();

        this.mBadge = primaryDrawerItem.getBadge();
        //this.mBadgeStyle = primaryDrawerItem.getBadgeStyle();

        this.mEnabled = primaryDrawerItem.isEnabled();
        this.mSelectable = primaryDrawerItem.isSelectable();
        this.mSelected = primaryDrawerItem.isSelected();

        this.icon = primaryDrawerItem.getIcon();
        this.selectedIcon = primaryDrawerItem.getSelectedIcon();

        this.iconTinted = primaryDrawerItem.isIconTinted();
        this.selectedColor = primaryDrawerItem.getSelectedColor();

        this.iconColor = primaryDrawerItem.getIconColor();
        this.selectedIconColor = primaryDrawerItem.getSelectedIconColor();
        this.disabledIconColor = primaryDrawerItem.getDisabledIconColor();
    }
```
i created own `BadgeStyle `in `CustomMiniDrawerItem` and commented all strokes, where global variable `mBadgeStyle `rewrites
And it worked! Mike, thank you very much!!!

**Comment by mikepenz** [comment]
Amazing :) 

You are welcome
