### ISSUE TITLE
Account header not update profile

### ISSUE THREAD

**Issue by Luiz-Otavio-Dorigon** [mikepenz/MaterialDrawer#2119]
If ProfileDrawerItem does not have handle when executing method updateProfile in AccountHeader does not update ProfileDrawerItem.

**Comment by mikepenz** [comment]
@Luiz-Otavio-Dorigon you do it on the main thread? your profile has an identifier?

**Comment by Luiz-Otavio-Dorigon** [comment]
My question was exactly this, if it is mandatory to have an identifier?

**Comment by mikepenz** [comment]
@Luiz-Otavio-Dorigon yes it is :)

**Comment by Luiz-Otavio-Dorigon** [comment]
Ok, thank you.
