### ISSUE TITLE
Set unselected icon color

### ISSUE THREAD

**Issue by KlassenKonstantin** [mikepenz/MaterialDrawer#212]
This is how I create Drawer icons:

    new PrimaryDrawerItem().withName("arriba")
           .withIcon(R.drawable.guide)
           .withTintSelectedIcon(true)

and I set the selected icon color like that:

    <item name="material_drawer_selected_text">?attr/colorPrimary</item>

Although it says "text" it also colors the icon which is what I want.
However it only works for the selected color.

I can't find the corresponding color attribute for unselected texts/icons.
What I want is I put in a white base icon and tint it gray when unselected and primary color when selected.

**Comment by mikepenz** [comment]
@KlassenKonstantin you can only tint the selected icon. no method call to tint the normal color. 
you can either pass the correct icons as drawable and manage it on your own. you can pass the tinted icons there. or you implement a custom drawerItem which handles the colors like you need it ;)

**Comment by KlassenKonstantin** [comment]
```java
new PrimaryDrawerItem().withName("arriba")
    .withIcon(R.drawable.calendar_unselected)
    .withSelectedIcon(R.drawable.calendar_selected),
```

Works, thank you :+1:. I thought I was missing something. : O

**Comment by mikepenz** [comment]
@KlassenKonstantin great :)
