### ISSUE TITLE
Error:(33, 0) Could not get unknown property 'versions' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by sarveshchavan7** [mikepenz/MaterialDrawer#2120]
When i add the dependency it gives the error
 implementation("com.mikepenz:materialdrawer:6.0.2@aar") {
        transitive = true
    }
//required support lib modules
    implementation "com.android.support:appcompat-v7:${versions.supportLib}"
    implementation "com.android.support:recyclerview-v7:${versions.supportLib}"
    implementation "com.android.support:support-annotations:${versions.supportLib}"
    implementation "com.android.support:design:${versions.supportLib}"

**Below is the logcat**

Error:(33, 0) Could not get unknown property 'versions' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by gilbeckers** [comment]
Hey, I'm getting the same error. How did you fixed it? Thanks!!

**Comment by rizal-rovins** [comment]
How did you fix this?

**Comment by BlackCat1606** [comment]
can you please tell us how did you fix it ? i had the same issue today

**Comment by mikepenz** [comment]
just replace the placeholder with a precise version number

**Comment by IdiosApps** [comment]
With the androidx implementations in 6.1.0-rc02, I managed to get things working thusly:

```
    ext {
        androidxSupportVersion = '1.0.0-rc02'
        supportLibVersion = '28.0.0-alpha1'
        androidVersion = '28.0.0'
    }

//required support lib modules
    implementation "androidx.appcompat:appcompat-v7:${androidxSupportVersion}"
```

Hope it saves someone a lot of time googling! I found the version number for androidx at https://mvnrepository.com/artifact/androidx.recyclerview/recyclerview .
