### ISSUE TITLE
getActionBarDrawerToggle() is null in MiniDrawer 

### ISSUE THREAD

**Issue by achievegame** [mikepenz/MaterialDrawer#2123]
I'm getting an error on the line
result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);
please Help

```java
 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main_custom);   

        // Handle Toolbar
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
     
        getSupportActionBar().setDisplayHomeAsUpEnabled(false);
        getSupportActionBar().setTitle(R.string.app_name);



        String version = getString(R.string.version);
        try {
            PackageInfo pInfo = this.getPackageManager().getPackageInfo(getPackageName(), 0);
            version = "Version: " + pInfo.versionName;
        } catch (PackageManager.NameNotFoundException e) {
            e.printStackTrace();
        }

        // NOTE you have to define the loader logic too. See the CustomApplication for more details
        final IProfile profile = new ProfileDrawerItem().withName("User Account").withEmail("Store Id").withIcon(GoogleMaterial.Icon.gmd_business_center).withIdentifier(100);
        // Create the AccountHeader
        headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.color.colorPrimary)
                .addProfiles(profile)
                .withSelectionListEnabledForSingleProfile(false)
                .withSavedInstance(savedInstanceState)
                .withProfileImagesVisible(false)
                //.withHeightDp(140)
                .withCompactStyle(true)
                .build();


        result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withAccountHeader(headerResult)
                .withTranslucentStatusBar(false)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.home).withIcon(GoogleMaterial.Icon.gmd_home).withIdentifier(1),
                        new PrimaryDrawerItem().withName(R.string.change_language).withIcon(GoogleMaterial.Icon.gmd_language).withIdentifier(2),
                        new PrimaryDrawerItem().withName(R.string.request_device).withIcon(GoogleMaterial.Icon.gmd_devices).withIdentifier(3),
                        new PrimaryDrawerItem().withName(R.string.live_support).withIcon(GoogleMaterial.Icon.gmd_live_help).withIdentifier(4).withSelectable(false),
                        new PrimaryDrawerItem().withName(R.string.logout).withIcon(GoogleMaterial.Icon.gmd_exit_to_app).withIdentifier(5).withSelectable(false),
                        new PrimaryDrawerItem().withName(version).withIdentifier(6).withSelectable(false)
                ) // add the items we want to use with our Drawer
                .withOnDrawerItemClickListener(this)
                .withGenerateMiniDrawer(true)
                .withSavedInstance(savedInstanceState)
                .withShowDrawerOnFirstLaunch(true)
                // build only the view of the Drawer (don't inflate it automatically in our layout which is done with .build())
                .buildView();

        result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);
        
        //the MiniDrawer is managed by the Drawer and we just get it to hook it into the Crossfader
        miniResult = result.getMiniDrawer();




        //get the widths in px for the first and second panel
        int firstWidth = (int) UIUtils.convertDpToPixel(220, this);
        int secondWidth = (int) UIUtils.convertDpToPixel(72, this);

        //create and build our crossfader (see the MiniDrawer is also builded in here, as the build method returns the view to be used in the crossfader)
        //the crossfader library can be found here: https://github.com/mikepenz/Crossfader
        crossFader = new Crossfader()
                .withContent(findViewById(R.id.crossfade_content))
                .withFirst(result.getSlider(), firstWidth)
                .withSecond(miniResult.build(this), secondWidth)
                .withSavedInstance(savedInstanceState)
                .build();

        //define the crossfader to be used with the miniDrawer. This is required to be able to automatically toggle open / close
        miniResult.withCrossFader(new CrossfadeWrapper(crossFader));

        //define a shadow (this is only for normal LTR layouts if you have a RTL app you need to define the other one
        crossFader.getCrossFadeSlidingPaneLayout().setShadowResourceLeft(R.drawable.material_drawer_shadow_left);

        crossFader.getCrossFadeSlidingPaneLayout().setShadowResourceRight(R.drawable.material_drawer_shadow_right);

        
       
        //set home
        result.setSelection(1);
    }
```

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <!--<include-->
        <!--android:id="@+id/include"-->
        <!--layout="@layout/custom_toolbar"-->
        <!--android:visibility="gone"-->
        <!--app:layout_constraintEnd_toEndOf="parent"-->
        <!--app:layout_constraintStart_toStartOf="parent"-->
        <!--app:layout_constraintTop_toTopOf="parent"></include>-->

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        android:elevation="4dp"
        tools:ignore="UnusedAttribute"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light"/>

    <FrameLayout
        android:id="@+id/frameLayout"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/toolbar">

        <FrameLayout
            android:id="@+id/crossfade_content"
            android:layout_width="match_parent"
            android:layout_height="match_parent"></FrameLayout>
    </FrameLayout>

</android.support.constraint.ConstraintLayout>
```

**Comment by mikepenz** [comment]
@achievegame that's the correct behaviour. as the `MiniDrawer` has no `DrawerLayout` there is also no `ActionBarDrawerToggle`. 

Use your own icon in the `Toolbar` or a third party library. the android efault `ActionBarDrawerToggle` requires a `DrawerLayout`

**Comment by achievegame** [comment]
thanks for your instant reply.
I've made custom toolbar and hamburger Button but 
result.openDrawer();
result.closeDrawer();
not working

please see the code 
hamburgerBtn.setOnClickListener((View v)->{
        Toast.makeText(this,"isDrawerOpen:"+result.isDrawerOpen(),Toast.LENGTH_LONG).show();
        if(result.isDrawerOpen()){
            result.closeDrawer();
        }else{
            result.openDrawer();
        }
    });



@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main_custom);

        // Handle Toolbar
        Toolbar toolbar =  findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        //set the back arrow in the toolbar
       // getSupportActionBar().setDisplayHomeAsUpEnabled(false);
        //getSupportActionBar().setTitle(R.string.app_name);

        hamburgerBtn = findViewById(R.id.hamburgerBtn);
        hamburgerBtn.setImageDrawable(
                new IconicsDrawable(this)
                        .icon(FontAwesome.Icon.faw_bars)
                        .color(Color.WHITE)
                        .sizeDp(24)
        );

        hamburgerBtn.setOnClickListener((View v)->{
            Toast.makeText(this,"isDrawerOpen:"+result.isDrawerOpen(),Toast.LENGTH_LONG).show();
            if(result.isDrawerOpen()){
                result.closeDrawer();
            }else{
                result.openDrawer();
            }
        });


        titleTextView = findViewById(R.id.titleTextView);
        titleTextView.setText(R.string.home);

        String version = getString(R.string.version);
        try {
            PackageInfo pInfo = this.getPackageManager().getPackageInfo(getPackageName(), 0);
            version = "Version: " + pInfo.versionName;
        } catch (PackageManager.NameNotFoundException e) {
            e.printStackTrace();
        }

        // NOTE you have to define the loader logic too. See the CustomApplication for more details
        final IProfile profile = new ProfileDrawerItem().withName("User Account").withEmail("Store Id").withIcon(GoogleMaterial.Icon.gmd_business_center).withIdentifier(100);
        // Create the AccountHeader
        headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.color.colorPrimary)
                .addProfiles(profile)
                .withSelectionListEnabledForSingleProfile(false)
                .withSavedInstance(savedInstanceState)
                .withProfileImagesVisible(false)
                //.withHeightDp(140)
                .withCompactStyle(true)
                .build();


        result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withAccountHeader(headerResult)
                .withTranslucentStatusBar(false)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.home).withIcon(GoogleMaterial.Icon.gmd_home).withIdentifier(1),
                        new PrimaryDrawerItem().withName(R.string.change_language).withIcon(GoogleMaterial.Icon.gmd_language).withIdentifier(2),
                        new PrimaryDrawerItem().withName(R.string.request_device).withIcon(GoogleMaterial.Icon.gmd_devices).withIdentifier(3),
                        new PrimaryDrawerItem().withName(R.string.live_support).withIcon(GoogleMaterial.Icon.gmd_live_help).withIdentifier(4).withSelectable(false),
                        new PrimaryDrawerItem().withName(R.string.logout).withIcon(GoogleMaterial.Icon.gmd_exit_to_app).withIdentifier(5).withSelectable(false),
                        new PrimaryDrawerItem().withName(version).withIdentifier(6).withSelectable(false)
                ) // add the items we want to use with our Drawer
                .withOnDrawerItemClickListener(this)
                .withGenerateMiniDrawer(true)
                .withSavedInstance(savedInstanceState)
                .withShowDrawerOnFirstLaunch(true)
                // build only the view of the Drawer (don't inflate it automatically in our layout which is done with .build())
                .buildView();


        //the MiniDrawer is managed by the Drawer and we just get it to hook it into the Crossfader
        miniResult = result.getMiniDrawer();




        //get the widths in px for the first and second panel
        int firstWidth = (int) UIUtils.convertDpToPixel(220, this);
        int secondWidth = (int) UIUtils.convertDpToPixel(72, this);

        //create and build our crossfader (see the MiniDrawer is also builded in here, as the build method returns the view to be used in the crossfader)
        //the crossfader library can be found here: https://github.com/mikepenz/Crossfader
        crossFader = new Crossfader()
                .withContent(findViewById(R.id.crossfade_content))
                .withFirst(result.getSlider(), firstWidth)
                .withSecond(miniResult.build(this), secondWidth)
                .withSavedInstance(savedInstanceState)
                .build();

        //define the crossfader to be used with the miniDrawer. This is required to be able to automatically toggle open / close
        miniResult.withCrossFader(new CrossfadeWrapper(crossFader));

        //define a shadow (this is only for normal LTR layouts if you have a RTL app you need to define the other one
        crossFader.getCrossFadeSlidingPaneLayout().setShadowResourceLeft(R.drawable.material_drawer_shadow_left);

        crossFader.getCrossFadeSlidingPaneLayout().setShadowResourceRight(R.drawable.material_drawer_shadow_right);

        //set home
        result.setSelection(1);
    }


<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <include
        android:id="@+id/include"
        layout="@layout/custom_toolbar"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"></include>

    <FrameLayout
        android:id="@+id/frameLayout"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/include">

        <FrameLayout
            android:id="@+id/crossfade_content"
            android:layout_width="match_parent"
            android:layout_height="match_parent"></FrameLayout>
    </FrameLayout>

</android.support.constraint.ConstraintLayout>

<android.support.v7.widget.Toolbar xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/toolbar"
    android:layout_width="match_parent"
    android:layout_height="?attr/actionBarSize"
    android:layout_margin="0dp"
    android:background="?attr/colorPrimary"
    android:padding="0dp"
    app:contentInsetEnd="0dp"
    app:contentInsetEndWithActions="0dp"
    app:contentInsetStart="0dp">

    <android.support.constraint.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="start"
        android:minHeight="48dp"
        android:orientation="horizontal">

        <ImageButton
            android:id="@+id/hamburgerBtn"
            android:layout_width="72dp"
            android:layout_height="18dp"
            android:layout_gravity="start"
            android:background="@android:color/transparent"
            android:backgroundTint="@color/white"
            android:onClick="toggleDrawer"
            android:scaleType="fitCenter"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:srcCompat="@drawable/fr" />

        <TextView
            android:id="@+id/titleTextView"
            android:layout_width="300dp"
            android:layout_height="match_parent"
            android:layout_marginStart="16dp"
            android:layout_weight=".3"
            android:gravity="center|start"
            android:paddingEnd="5dp"
            android:paddingStart="5dp"
            android:textAlignment="viewStart"
            android:textColor="@color/white"
            android:textSize="17sp"
            android:textStyle="bold"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintStart_toEndOf="@+id/hamburgerBtn"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintVertical_bias="0.0" />


        <ImageButton
            android:id="@+id/imgBtnLogo"
            android:layout_width="wrap_content"
            android:layout_height="40dp"

            android:layout_gravity="end"
            android:layout_marginEnd="16dp"
            android:background="@android:color/transparent"
            android:src="@drawable/logo"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
    </android.support.constraint.ConstraintLayout>
</android.support.v7.widget.Toolbar>

**Comment by mikepenz** [comment]
@achievegame as mentioned there is no `DrawerLayout` and there is no `open` / `close` in this case. 

the `crossFader` has the functions to toggle the full or the mini variant

**Comment by achievegame** [comment]
thanks a lot
crossFader.crossFade();
