### ISSUE TITLE
Library should use "colorPrimary" theme attr

### ISSUE THREAD

**Issue by mpost** [mikepenz/MaterialDrawer#2124]
When using a base theme that inherits from the app compat themes, the `colorPrimary` etc. colors are not used. Instead the default colors as defined by the library are used. This behavior can be overwritten by creating a custom color resource called "primary" etc. which is unexpected.

I would expect that the drawer picks app the colors from the theme of the activity.

**Comment by mikepenz** [comment]
@mpost you can just define those colors in your theme. 

https://github.com/mikepenz/MaterialDrawer#custom-style---stylesxml

**Comment by mpost** [comment]
That seems to be true when extending the MaterialDrawerTheme but not when extending another theme like app compat.

**Comment by mikepenz** [comment]
I would be surprised if applying the same attributes has no effect, as I fetch the colors from the applied theme.

**Comment by mpost** [comment]
That is why i am surprised :)

**Comment by mikepenz** [comment]
I close this one as communication is going on here: https://github.com/mikepenz/MaterialDrawer/issues/2157
