### ISSUE TITLE
Change typeface of items inflated from a menu.xml

### ISSUE THREAD

**Issue by mradzinski** [mikepenz/MaterialDrawer#2125]
Hey @mikepenz, QQ: is there a way of changing the typeface and overall appearance of items inflated from a menu.xml file?

Thanks!

**Comment by mikepenz** [comment]
@mradzinski no there is no direct way to do this. (we can not add additional fields to the menu.xml) 
You might simply overwrite the font for the whole application  instead. 
Or overwriting the layout for the `DrawerItem` and setting your font in xml

**Comment by mradzinski** [comment]
Wouldn't overriding the default `DrawerItem` layout implementation would mean that most of the extra features such as badges and icons would be lost? Can't override the font for a whole app just for the drawer menu, so the second method would be more appealing. How would one override the laoyut?

**Comment by mikepenz** [comment]
@mradzinski simply copy paste the layout for the `primaryDrawerItem` to your project. and then adjust the typeface to your needs in the xml
make sure ids and general structure of the item stays the same, but other than that you can adjust all to you rneeds

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_primary.xml

**Comment by mradzinski** [comment]
Awesome. Thanks @mikepenz!
