### ISSUE TITLE
Change size of dragging to open

### ISSUE THREAD

**Issue by uruloke** [mikepenz/MaterialDrawer#2126]
We would like to change the size of the box for opening the drawer when you are trying to swipe it in. 
It can be pretty hard to swipe it in sometimes and in our use-case we do not got a toolbar to open it with.

Is this already possible to change, if yes, how?

**Comment by mikepenz** [comment]
@uruloke this is unrelated to this library as this is controlled by the `DrawerLayout` which offers no setting to adjust the drag target. 

You might be able with some reflection based hacks but no "clean" solution is available as far as I know

https://stackoverflow.com/a/27794460/325479
