### ISSUE TITLE
Best way to remove the Drawer

### ISSUE THREAD

**Issue by AngeloAvv** [mikepenz/MaterialDrawer#2127]
Hi, I'm trying to find out a way to remove the Material Drawer from my activity, since its visibility depends on the currently showed fragment.

```
mDrawer = new DrawerBuilder()
                    .withActivity(this)
                    .addDrawerItems(items)
                    .withSliderBackgroundColorRes(R.color.primary)
                    .withDrawerGravity(Gravity.END)
                    .withActionBarDrawerToggle(false)
                    .withOnDrawerItemClickListener((Drawer.OnDrawerItemClickListener) fragment)
                    .build();
```

I'm using the following code, but it leads to a crash:
`((ContentFrameLayout)mDrawer.getDrawerLayout().getParent()).removeView(mDrawer.getDrawerLayout());`

is there a proper way to remove the Drawer from the activity?

Thank you in advance

**Comment by mikepenz** [comment]
@AngeloAvv I would recommend not removing it, but just locking it from being displayed

https://stackoverflow.com/a/17165256/325479

**Comment by AngeloAvv** [comment]
Thank you, seems to work properly for my case
