### ISSUE TITLE
ExpandableDrawerItem withIsExpanded(true) is NOT working

### ISSUE THREAD

**Issue by prateekarora** [mikepenz/MaterialDrawer#2128]
Hi @mikepenz
Please help. Consider following use cases:

CASE 1: Load an activity with sub-items filled in an ExpandableDrawerItem in a MaterialDrawer and set the expandable item's expanded value to TRUE. Sub-items should be shown by default.

CASE 2: Load an activity with sub-items filled in an ExpandableDrawerItem in a MaterialDrawer and set the expandable item's expanded value to FALSE. Click drop arrow to expand and show sub-items.

CASE 1 is NOT working when using FastAdapter v3.0.0+ and MaterialDrawer v6.0.2 configuration. No sub-items are shown when drawer is shown with Expandable Item in expanded state by default. Only Expandable Item's header name and a drop arrow is shown. Only if you click drop arrow to collapse and expand it again, Expandable Item shows its sub-items. CASE 2 is working by default on above mentioned configuration.

CASE 1 and CASE 2 work as expected as soon as I revert code back to using FastAdapter v2.6.3 and MaterialDrawer v5.9.5 configuration.

I am using the following Android dev configuration:

Android Studio 3.0.1

```gradle
compile 'com.android.support:appcompat-v7:26.1.0'
compile 'com.android.support:support-v13:26.1.0'
compile 'com.android.support:design:26.1.0'
compile 'com.android.support:support-v4:26.1.0'
compile 'com.android.support:cardview-v7:26.1.0'
compile 'com.android.support:support-annotations:26.1.0'
compile 'com.android.support:customtabs:26.1.0'

implementation('com.mikepenz:fastadapter:3.0.4@aar') {
        transitive = true
}
implementation 'com.mikepenz:fastadapter-commons:3.0.3@aar'
implementation 'com.mikepenz:fastadapter-extensions:3.0.3@aar'
implementation 'com.mikepenz:materialize:1.1.2@aar'
implementation('com.mikepenz:materialdrawer:6.0.2@aar') {
        transitive = true
}
```

Appreciate your help. Thanks.

**Comment by mikepenz** [comment]
@prateekarora case 1 was actually only working "by mistake" in the previous release. 

You should use the provided `expand()` method to expand it programatically. 
Applying the internal `isExpanded` state on the item itself has no effect.

**Comment by mikepenz** [comment]
Similar issue with some additional conversation: https://github.com/mikepenz/MaterialDrawer/issues/2092

**Comment by prateekarora** [comment]
You rock! Although I had double checked to see if there was already an open issue but could not find #2092. Hence, asked here. Thanks for your help and awesome libraries.

**Comment by mikepenz** [comment]
You are welcome :)
