### ISSUE TITLE
How use with fragments?

### ISSUE THREAD

**Issue by goodandrewsoft** [mikepenz/MaterialDrawer#2129]
How implement behaviour, described [there](https://developer.android.com/training/implementing-navigation/nav-drawer.html?hl=ru)  using your drawer library?
```
private void selectItem(int position) {
    // Create a new fragment and specify the planet to show based on position
    Fragment fragment = new PlanetFragment();
   .....


```
How use with fragments?

**Comment by mikepenz** [comment]
@goodandrewsoft the `MaterialDrawer` provides the listener which is called when the user clicks. 
You can then do whatever you need to do in your application. 

How to work with fragments and commit fragments is a default android thing and independent of the `MaterialDrawer`
