### ISSUE TITLE
Feature request for back pattern navigation with Fragments

### ISSUE THREAD

**Issue by raghunandankavi2010** [mikepenz/MaterialDrawer#213]
I just saw this pattern in gmail app. Consider 2 Fragments  hosted by HomeActivity. You have fragment1 attached by default. You then select the drawer item 2 and you replace the container by fragment 2. 

Now clicking back button you navigate to fragment1. The selection of the drawer item is at position1.

I saw this implement in another libray by neokree. 

Is this possible to implement which would be great. Also its very confusing cause the pattern are different for different apps released by google.

**Comment by mikepenz** [comment]
@raghunandankavi2010 you can already do this. i'm not sure why this needs to be managed by the MaterialDrawer. 

just set the fragment on the drawerItemClick. and if the back button is pressed set the selection to the previous selection.

**Comment by raghunandankavi2010** [comment]
@mikepenz  thanks. WIll try it. I am just trying that.

**Comment by mikepenz** [comment]
@raghunandankavi2010 great :)

**Comment by raghunandankavi2010** [comment]
@mikepenz absolutelt works. Just need to make sure you don't add the fragment to the backstack again if its already there and of cource set the selected identifier to previous one in onBacPressed. Also you need to check if there is only 1 fragment on backstack so that on back press you finish the activity.

For anyone looking for more info

http://stackoverflow.com/questions/18305945/how-to-resume-fragment-from-backstack-if-exists

@mikepenz one again big  thanks. this is the only drawer library that is agressively maintained that's what prompted me .

**Comment by mikepenz** [comment]
@raghunandankavi2010 no problem :). i try my best to keep this as flexible as it is right now so everyone can use it for his purposes ;)
