### ISSUE TITLE
Horizontal items in CustomItem

### ISSUE THREAD

**Issue by KhalilTB** [mikepenz/MaterialDrawer#2132]
I have CustomItem that contains items in horizontal order, image attached.

![screen shot 2017-12-03 at 12 01 11 pm](https://user-images.githubusercontent.com/30475046/33523857-033431e0-d822-11e7-8822-80cbc252fdaf.png)

Is it possible to make one of them selectable without selecting the whole row? Like just enlarging the size of selected item. Currently when I want to select an item the whole row is selected and unable to find a solution so far

**Comment by mikepenz** [comment]
@KhalilTB well that is up to you. You will have to handle this in your `CustomDrawerItem`. 

Basically you make the whole item not selectable, and you have to internally handle the selection and keep the selected state through configuration changes..

**Comment by mikepenz** [comment]
Close until new infos are provided
