### ISSUE TITLE
its not adding in new project

### ISSUE THREAD

**Issue by pourya0111** [mikepenz/MaterialDrawer#2133]
hey there im adding implementation("com.mikepenz:materialdrawer:6.0.2@aar") {
   transitive = true
}
to my project and synching but when i try to create a new drawer its show nothing that i can select and create

**Comment by mikepenz** [comment]
@pourya0111 do you have a gradle sync issue? 
which gradle version do you have?
which android studio version do you have?
which build tools do you have?
do you have a build error?

**Comment by pourya0111** [comment]
hey again
studio v3.0
buildtools 26.01
there no error in logcat
also i noticed in your sample peoject theres a library folder and i suppose it should be add when i compile the line in dependencied but nothing happend
i just compiled it and no chance to create a drawer

**Comment by mikepenz** [comment]
@pourya0111 gradle dependencies are not added as a folder.

they will only show up in the `referenced libraries` part in Android Studio. 

after adding it to your gradle you can simply use the `DrawerBuilder` in your project. 
Don't forget to do the proper imports. as it is necessary for java

**Comment by pourya0111** [comment]
ok i'll give it a try and getting back with results soon :)

**Comment by pourya0111** [comment]
hey it worked i started a new project,synched everything and its working like charm
thank you
