### ISSUE TITLE
sourceSets property is unknown (from root project)

### ISSUE THREAD

**Issue by LeFizzy** [mikepenz/MaterialDrawer#2134]
Hey there @mikepenz,

I encountered a problem when I tried to build my project after adding your module. 
`Error:Could not get unknown property 'sourceSets' for root project '***' of type org.gradle.api.Project.`

I've tried to fix this by adding a custom sourceSets property to my build-grandle (project file), and it returned with a new error:
`Error:(18, 0) Could not find method sourceSets() for arguments [build_36x7r1yheo5jqnd1locmdhmc5$_run_closure1@38dc36] on root project '***' of type org.gradle.api.Project.`

grandle-version: 3.0.0-beta7
bintray-version: 0.8.0
Android Studio: 2.3.3
BuildTools-version: 26.0.2

I look forward for your reply, 
LeFizzy.

**Comment by LeFizzy** [comment]
Thanks for your reply, I went over the few mentioned files to check whetner I've got a syntax-error or not. I haven't found any, and it's still warns me that I need to define this "sourceSets" property inside my root-projects build-grandle file. How should I define it correctly (if it's needed to get your module work)?

**Comment by mikepenz** [comment]
No only 

```gradle
implementation("com.mikepenz:materialdrawer:6.0.2@aar") {
   transitive = true
}

//required support lib modules
implementation "com.android.support:appcompat-v7:${versions.supportLib}"
implementation "com.android.support:recyclerview-v7:${versions.supportLib}"
implementation "com.android.support:support-annotations:${versions.supportLib}"
implementation "com.android.support:design:${versions.supportLib}"
```

is required in your dependencies of the app module. Nothing else.

**Comment by LeFizzy** [comment]
It's correct. I have already added it to the project tree before made this issue. For example, if I build the project without MaterialDrawer, it's builds as it should, but not with the module added. I still look forward for your reply, wonder if it's getting fixed.

**Comment by mikepenz** [comment]
Do you by any chance have old gradle version?

You need gradle 4.1 at least. 
gradle build tools 3.x at least

**Comment by LeFizzy** [comment]
For the last try, I will install the 4.1 version of grandle, as soon as I get home.

**Comment by mikepenz** [comment]
well gradle 4.1 is anyways a dependency of the gradle build tools 3.x 

as mentioned the library does not need any changes to the sourceSet. It is working for everybody else + I use it in a few of my projects too. 

Something in your setup is not correct.

**Comment by LeFizzy** [comment]
Thanks for all your help you made. I guess it was my setup, definitely inside the project structure.
Firstly, I've updated to the latest Android Studio (which is 3.0), with latest grandle&build-tools. It didn't worked, until I moved back a step in my git-branch (a working project-tree) solved it, and it's seems to be done.
