### ISSUE TITLE
Hide drawer item programmatically

### ISSUE THREAD

**Issue by anshul90** [mikepenz/MaterialDrawer#2135]
Hi,

I need to hide an item from drawer pro-grammatically according to the position. Currently I'm using static position to click also so I don't want to create different primary items for each item. Can anyone please tell how we can do that ?

Thanks,
Anshul Tyagi

**Comment by mikepenz** [comment]
@anshul90 you can remove it from the list, and re-add it. no hide possible (as of the nature of `RecyclerView`s)

why not work with the identifier?

**Comment by mikepenz** [comment]
Please report back. close for now
