### ISSUE TITLE
Unable to delete profile in header

### ISSUE THREAD

**Issue by cabudies** [mikepenz/MaterialDrawer#2137]
Hello there. Firstly thank you so much for this great Material Drawer. I have a question that when I'm running this line of code.
`headerResult.removeProfile(profile-id)`
I am unable to delete the profile from the headerResult. I have even tried making my first profile as selected profile and then deleting the requested profile. Even used close drawer function and then again reassigning the drawer to headerResult. Please advice what to do.

**Comment by mikepenz** [comment]
you only have to use the `removeProfile` function with the proper `identifier` you gave that profile. on a `UIThread`

**Comment by tonyshkurenko** [comment]
I have the same problem with line (kt):

    resultHeader.removeProfile(resultHeader.activeProfile)

Simply not working

**Comment by mikepenz** [comment]
do you do it on the main thread?

**Comment by tonyshkurenko** [comment]
Yeah main. Tried removing before selecting new and selecting new one and removing after. Both not working.

**Comment by mikepenz** [comment]
can you debug into. what happens?

Mike Penz
__________________________________________
*Mike Penz*
Android | Backend | Open Source | Web Developer
mikepenz.com

**Comment by tonyshkurenko** [comment]
Hm, noticed, that identifier is negative and this isn't valid

**Comment by tonyshkurenko** [comment]
Using custom identifier (not default) made everything work

**Comment by mikepenz** [comment]
@tonyshkurenko you need to provide identifier :) by default non is defined
