### ISSUE TITLE
Centred items on DrawerBuilder

### ISSUE THREAD

**Issue by roman-shpuntov** [mikepenz/MaterialDrawer#2138]
I could not find any method for centred items in DrawerBuilder. How can i do it?
For example from ios
![img_8130](https://user-images.githubusercontent.com/33626426/33662930-6aae612e-dac0-11e7-8cc4-81f8a821e654.jpg)
:

Thanks!

**Comment by mikepenz** [comment]
@roman-shpuntov there is no function to do this, because this goes against the google material design guidelines. 

You should be able to achieve this using the trick mentioned 2 years ago: https://github.com/mikepenz/MaterialDrawer/issues/702#issuecomment-144160543

**Comment by roman-shpuntov** [comment]
Mike, thank you so much! This is good solution for me :)
