### ISSUE TITLE
recyclerview inside material drawer

### ISSUE THREAD

**Issue by pascalito007** [mikepenz/MaterialDrawer#2139]
Dear All,

I would like to add recyclerview inside material drawer. The data of the recyclerview is from a cursor.
How to add recyclerview inside material drawer. Any sample code or tutorial will be appreciate.
Exact as the image below (after 'Ajouter un podcast')
![screenshot_20171204-093243](https://user-images.githubusercontent.com/4120406/33756763-de6ece8a-dbee-11e7-95f8-4238bb0882d9.png)

Thanks

**Comment by mikepenz** [comment]
@pascalito007 the drawer is already a `RecyclerView` 

You should implement a `CustomDrawerItem` for your special items. You can then simply use the same api you already know from the `MaterialDrawer` to add these, your own styled items :)

**Comment by pascalito007** [comment]
Thanks for your comment @mikepenz 
Most of the time what I did is I create layout where I put Recyclerview and another layout for Recyclerview Items. After I create adapter and in the activity I provider all data for the adapter and then I set the adapter to the recyclerview.
How to manage for Material drawer librairy? Any link that show the process please ?

**Comment by mikepenz** [comment]
You have the API methods to add elements after building the drawer for example:
https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

And there is also a FAQ article on how to create a `CustomDrawerItem` allowing you to implement the design you need:
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md

**Comment by pascalito007** [comment]
I follow your link but I dont know how to make this work.

This is from my Main Activity
 Cursor cursor=getContentResolver().query(PodcastProvider.PodcastList.CONTENT_URI,null,null,null,null);
        
        result = new DrawerBuilder()
                .withToolbar(toolbar)
                .withActivity(this)
                .withTranslucentStatusBar(true)
                .withHeader(R.layout.header)
                .addDrawerItems(
                        new PrimaryDrawerItem().withIcon(R.drawable.ic_drawer_list).withName("List"),
                        new PrimaryDrawerItem().withIcon(R.drawable.ic_drawer_feed).withName("Subscribe"),
                        new PrimaryDrawerItem().withIcon(R.drawable.ic_drawer_download).withName("Downloads"),
                        new PrimaryDrawerItem().withIcon(R.drawable.ic_drawer_add_podcast).withName("Add podcast")

                )
                .addStickyDrawerItems(
                        new PrimaryDrawerItem().withName("Preferences").withIcon(R.drawable.ic_drawer_preferences)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        if (((Nameable) drawerItem).getName().getText().equals("Add podcast")) {
                            Fragment fragment = new AddPodcastFragment_();
                            getSupportFragmentManager().beginTransaction().replace(R.id.main_container, fragment).commit();
                        } else {
                            Toast.makeText(MainActivity.this, ((Nameable) drawerItem).getName().getText(), Toast.LENGTH_SHORT).show();
                        }
                        return false;
                    }
                })
                .build();

This is my layout (recyclerview items)

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_margin="10dp">

    <ImageView
        android:id="@+id/drawer_podcast_img"
        android:layout_width="75dp"
        android:layout_height="75dp"
        android:src="@drawable/podcast_img"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <TextView
        android:id="@+id/drawer_podcast_title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginLeft="5dp"
        android:text="TextView"
        app:layout_constraintBottom_toBottomOf="@+id/drawer_podcast_img"
        app:layout_constraintStart_toEndOf="@+id/drawer_podcast_img"
        app:layout_constraintTop_toTopOf="@+id/drawer_podcast_img" />


</android.support.constraint.ConstraintLayout>
```

Now how to provide cursor data to material drawer ? @mikepenz

**Comment by mikepenz** [comment]
@pascalito007 you will have to run over the curser and fill the drawer with the items. 
There is no way to just provide the cursor.

**Comment by pascalito007** [comment]
Thank you @mikepenz  for your response.
