### ISSUE TITLE
An option to use textAllCaps on SectionDrawerItem

### ISSUE THREAD

**Issue by dimsuz** [mikepenz/MaterialDrawer#214]
Some navigation drawers (e.g. Youtube app nav drawer) display a section titles using capitalized letters.

Would it be possible to support this feature in this library?

I could provide a pull request for you, but I am not sure what would be the best way to implement this:

1. Use this as a default? Then this is just a matter of adding `textAllCaps=true` to the `layout.material_drawer_item_section` layout xml
2. Provide a SectionDrawerItem.setTextAllCaps(boolean) and update `convertView()` to invoke `setAllCaps` on the respective TextView
3. Somehow allow user to style this
4. Some other option?

What do you think?

**Comment by dimsuz** [comment]
Here's the [screenshot](https://cloud.githubusercontent.com/assets/42920/7106582/3b63387a-e146-11e4-9e0b-d19f974ec1de.png) of Youtube's android app

**Comment by mikepenz** [comment]
@dimsuz not sure. as far as i can tell the current implementation is correct. I let it up to the user. Just pass your text as string and make an toUpper on it. or just set your text in uppercase letters in your strings.xml. i think it's a bit to much if i add an additional method for something which is really easy ;)

**Comment by DominikAngerer** [comment]
```String.toUpperCase();``` will do the trick for you @dimsuz 

```java
"your String".toUpperCase();
```

You can replace ```"your String"``` also with a string variable or similar and simply set this as your Text. No need for a new Method inside the MaterialDrawer.

**Comment by dimsuz** [comment]
Ok. With this approach I won't be able to nicely pass strings as resource identifiers and will have to do 

`.withName(context.getString(resId).toUppercase())` 

which feels a bit ugly, but you are probably right that adding a method for every single setting is wrong.

**Comment by dimsuz** [comment]
The best solution IMO would be some styleable option so user could say once `sectionAllCaps=true` and wouldn't need to bother with any method calls or whatever - this would be a proper separation of styling and code :)

**Comment by mikepenz** [comment]
@dimsuz yeah adding a method for all features is a bit an overkill. it's important to keep it flexible and light. additional methods make it harder to manage and handle :)

You can still just define the string in uppercase in your strings.xml. not sure if you have to reuse it.

style option is also an additional option. :D

**Comment by dimsuz** [comment]
@mikepenz I recently figured that defining strings in uppercase in strings.xml is sometimes a bad option for big projects where single string could be reused in multiple contexts... I guess this is why Google invented textAllCaps in the end :)

**Comment by mikepenz** [comment]
@dimsuz yeah if it will be reused then it's bad :D

Still you have the option to add the method and do a pull-request. remember old default functionality should not be altered

**Comment by dimsuz** [comment]
Ok, will think about it, maybe will come up with some better idea and send PR.
