### ISSUE TITLE
Drawer Item Update Not working at all 

### ISSUE THREAD

**Issue by atul-forbinary** [mikepenz/MaterialDrawer#2140]
I am trying to update drawer item text and icon depends on functionality of my application , but its not update the same item 
```java
PrimaryDrawerItem primaryDrawerItem = (PrimaryDrawerItem) result.getDrawerItem(IDENTIFIER_ABC);
primaryDrawerItem.withIcon(R.drawable.profile);
primaryDrawerItem.withName("new name");
result.updateItem(primaryDrawerItem);
```

**Comment by mikepenz** [comment]
you do the update on the `main`-thread?

**Comment by mikepenz** [comment]
Please report back. close for now

**Comment by msegmx** [comment]
Hi Mike,

I've updated the library and this code doesn't work anymore :

```
pdiUsername.withEmail(text);
accountHeader.updateProfile(pdiUsername);
```

pdiUsername here is the object I add as a profile :

```
pdiUsername = new ProfileDrawerItem();
pdiUsername.withName("Username");
pdiUsername.withEmail("....");
new AccountHeaderBuilder().addProfiles(pdiUsername)
```

I see the "Username" and "...." in the header section, but an update is not being reflected to the header.
I'm on the main thread.
What could be the problem ?

**Comment by mikepenz** [comment]
Do you do this on the main thread?
Does your `pdiUsername` have a `identifier` set?

**Comment by msegmx** [comment]
Yes, on the main thread. I just added this line :

`pdiUsername.withIdentifier(18648);`

the number is totally random and hardcoded. It worked, the header update succeeds !
Thanks !
