### ISSUE TITLE
How to set the MaterialDrawerThemes?

### ISSUE THREAD

**Issue by YitschakGlik** [mikepenz/MaterialDrawer#2143]

**Comment by mikepenz** [comment]
Like you set any other theme

**Comment by YitschakGlik** [comment]
thanks for responding so quick, wow.

Its supposed to be at AndroidManifest.xml : android:theme="@style/AppTheme">
?
you wrote that its extends the appTheme. 

please help.

**Comment by YitschakGlik** [comment]
<style name="MaterialBaseTheme." parent="Theme.AppCompat.NoActionBar">
    
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="colorAccent">@color/colorAccent</item>
</style>
 and here?

**Comment by mikepenz** [comment]
@YitschakGlik you can either use the provided `MaterialDrawer` theme. or you use it as parent and adjust it values. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/AndroidManifest.xml#L16

Custom:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/AndroidManifest.xml#L25
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/values/styles.xml#L4

all shown in the sample..

**Comment by YitschakGlik** [comment]
Thanks Mr Mike.

**Comment by YitschakGlik** [comment]
One more question dear Mike,

Can I set the width of the drawer?

**Comment by mikepenz** [comment]
Well you can: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L418

But you shouldn't :D The included algorithm sets the correct width as of the Google Material Design Guidelines. in all different scenarious

**Comment by YitschakGlik** [comment]
thanks, amazing job. 

נשלח מה-iPad שלי

‫ב-11 בדצמ׳ 2017, בשעה 13:20, ‏‏Mike Penz ‏<notifications@github.com> כתב/ה:‬
