### ISSUE TITLE
Custom drawble as background

### ISSUE THREAD

**Issue by rana01645** [mikepenz/MaterialDrawer#2145]
Hey Mike,

First of all thanks for the awesome library. Now my question is can I use custom drawable as drawer background??

I'm trying to add blurry transparent effect to the drawer, Is there any other way to achieve it!

**Comment by mikepenz** [comment]
you can always directly access the view's of the drawer and adjust them to what you need

**Comment by rana01645** [comment]
I'm unable to figure out how can I use a custom image/drawable as drawer background.. :(

**Comment by rana01645** [comment]
Okay

Maybe this will work for my case :D 
Thanks a lot for your quick response  
        result.getRecyclerView().setBackground();
