### ISSUE TITLE
Unable to set OnDrawerListener outside of DrawerBuilder

### ISSUE THREAD

**Issue by MrMindyMind** [mikepenz/MaterialDrawer#2146]
Why is there no way of setting DrawerListener outside of DrawerBuilder? It would be nice if we could get a setter method for doing this.

**Comment by mikepenz** [comment]
it should only be created during build type. 

if you need to adjust the logic, just forward it to your own listener, or have a method which decides what happens

**Comment by MrMindyMind** [comment]
Okay, thank you for the quick response.
