### ISSUE TITLE
Binary xml inflate exception (27.0.2 support library)

### ISSUE THREAD

**Issue by N-i-p-o-l** [mikepenz/MaterialDrawer#2147]
If i use 27.0.2 support library version, i get binary xml exception in AccountHeaderBuilder class. Downgrade to 27.0.1 solve the problem. No additional information is need, just try new support library 27.0.2

- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [6.0.2 ] Used library version
- [27.0.2 ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

**Comment by mikepenz** [comment]
Define a resolution strategy if you want to use a different version of the support libs than defined in the current library version.

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/build.gradle#L83
