### ISSUE TITLE
Intercepting click events on ProfileDrawerItems without switching Profiles

### ISSUE THREAD

**Issue by connyduck** [mikepenz/MaterialDrawer#2148]
## About this issue

I would like to handle the clicks on ProfileDrawerItems myself without having the drawer header switching profiles automatically. I can do this for the profile images with withOnAccountHeaderProfileImageListener and returning true in onProfileImageClick. Setting ClickListeners on the Items does not change the behavior - no matter what is returned.

Any idea what I can do? It seems as there should be an method like withOnAccountHeaderProfileListener to accomplish this, but I can't find it. 

## Details
- Used library version 6.0.1
- Used support library version 27.0.2
- Used gradle build tools version 27.0.1
- Used tooling / Android Studio version 3.0.1
- Other used libraries, potential conflicting libraries \

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@connyduck you could theoretically intercept it via the lowest api. The one provided via the `FastAdapter`. 

You'd be able to attach a `PreClickListener` to the `FastAdapter` and just prevent any further interaction as of the normal flow

**Comment by connyduck** [comment]
Ok thx for the answer 🙂

**Comment by LinXueyuanStdio** [comment]
There is another way to solve it, just add `.withSelectable(false)` to which you don't want to switch.

```java
            if (drawerItem != null && drawerItem instanceof IProfile && drawerItem.isSelectable()) {
                isCurrentSelectedProfile = switchProfiles((IProfile) drawerItem);
            } else {
                isCurrentSelectedProfile = false;
            }
            ......
            boolean consumed = false;
            if (drawerItem != null && drawerItem instanceof IProfile) {
                if (mOnAccountHeaderListener != null) {
                    consumed = mOnAccountHeaderListener.onProfileChanged(view, (IProfile) drawerItem, isCurrentSelectedProfile);
                }
            }
```

**Comment by connyduck** [comment]
well yes, but then the profiles don't show up in the drawer header
