### ISSUE TITLE
Sticky Footer margin

### ISSUE THREAD

**Issue by DavyHubrecht** [mikepenz/MaterialDrawer#215]
Hi,

I implemented the new sticky footer, but the margin seems a bit off. There's too much space between the divider and the list.

I used the `addStickyDrawerItems()` function with the array containing one `PrimaryDrawerItem`

Screenshot, look at "Settings": 
![2015-04-13 13 50 17](https://cloud.githubusercontent.com/assets/3082124/7117116/05a29b02-e1f7-11e4-83c8-b129f7404487.png)

And another where I pressed the button for clarity:
![2015-04-13 13 50 47](https://cloud.githubusercontent.com/assets/3082124/7117167/5fa3e688-e1f7-11e4-8431-06a08c27be00.png)

**Comment by mikepenz** [comment]
@DavyHubrecht the margin is exactly 8dp. should be the correct value as far as i can see in the Material Design Guidelines.

**Comment by DavyHubrecht** [comment]
That's 8dp around the divider you're refering to, right? That seems correct indeed, but I don't think the top line of the sticky footer should be seen as a normal divider. The only official Google app using a sticky footer, that I know of, is the 'Inbox' app, which doesn't add margin. They also used elevation/shadow there instead of a normal divider.

The material design guidelines don't seems to describe the sticky footer in a navigation drawer though.

Screenshot:
![2015-04-13 16 57 41](https://cloud.githubusercontent.com/assets/3082124/7124249/db2b9244-e227-11e4-87c1-3c16979fad36.png)

**Comment by mikepenz** [comment]
@DavyHubrecht yes i know it should be a shadow. But i'm not able to get it working with elevation. I've removed at least the margin for the next release

**Comment by DavyHubrecht** [comment]
Thank you!

**Comment by mikepenz** [comment]
No problem ;)
