### ISSUE TITLE
How to use ActionMode with mini drawers?

### ISSUE THREAD

**Issue by Mygod** [mikepenz/MaterialDrawer#2151]
## About this issue

Sample app: https://github.com/shadowsocks/shadowsocks-android/commit/8b584c717f9afb3f5d2f65b6605d3fcb77304176 (or https://github.com/Mygod/shadowsocks-android)

ActionMode works fine with portrait mode (no minidrawer), but with minidrawer enabled, it appears behind the content view (CrossFadeSlidingPaneLayout).

## Details
- [x] Used library version 6.0.2
- [x] Used support library version 27.0.2
- [x] Used gradle build tools version 3.0.1
- [x] Used tooling / Android Studio version 3.0.1
- [x] Other used libraries, potential conflicting libraries: https://github.com/Gericop/Android-Support-Preference-V7-Fix

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by Mygod** [comment]
Here's a layout capture: [capture-minidrawer-actionmode.li.zip](https://github.com/mikepenz/MaterialDrawer/files/1574865/capture-minidrawer-actionmode.li.zip)

**Comment by Mygod** [comment]
CC @madeye

**Comment by mikepenz** [comment]
@Mygod not sure how much can be done about that as it sounds like it might be an issue of the `SlidingPaneLayout` for android itself already. 

have you tried to bring the CAB to the front?

**Comment by Mygod** [comment]
What's CAB?

**Comment by mikepenz** [comment]
Isn't your ActionMode a `Contextual Action Bar`?

**Comment by Mygod** [comment]
Oh. I suppose I could get the reference of that with some reflection using [`ActionMode` returned from `View.startActionMode`](https://github.com/shadowsocks/shadowsocks-android/commit/8b584c717f9afb3f5d2f65b6605d3fcb77304176#diff-7ad141ce280dd05e941d7989e96acc4dR296) but I'd have to look into that. Is that what you mean?

**Comment by mikepenz** [comment]
I am just wondering. as the `CrossFadeSlidingPaneLayout` simply uses the `SlidingPaneLayout` from google, and as far as I remember I didn'T adjust it's position in the view hierarchy.  it sounds strange that it has such an effect :/ 

so maybe a `bringToFront()` would fix it, but It's just a guess. :/

**Comment by Mygod** [comment]
Could it be the elevation/translationZ? Views with higher elevation are drawn later than the ones with lower elevation.

**Comment by Mygod** [comment]
Also I wonder if it's possible to show CAB over the old action bar instead of over the mini drawer as well.

**Comment by mikepenz** [comment]
well if you want to show a `CAB` `over` the `Toolbar` you have to set a specific theme attribute. 

I think this one:

```
<item name="windowActionModeOverlay">true</item>
```

**Comment by Mygod** [comment]
Thanks! I will try it out when I've got time.

**Comment by mikepenz** [comment]
Awesome :)

**Comment by Mygod** [comment]
I just checked and [I'm already using `windowActionModeOverlay`](https://github.com/Mygod/shadowsocks-android/commit/8b584c717f9afb3f5d2f65b6605d3fcb77304176#diff-9de96b8fdf4ca3b69403cee2561831f0R12). Any other suggestions?

**Comment by Mygod** [comment]
Also could you reopen this issue please?

**Comment by mikepenz** [comment]
Reopened it. But as far as I can tell you it is not related to the lib itself, but to the underlaying system component / google android view

**Comment by Mygod** [comment]
Well what do you suggest I should do then?

**Comment by mikepenz** [comment]
As it is not really related to this library, and it will happen with any usage of the `DrawerLayout` I can not tell you sorry.

**Comment by Mygod** [comment]
Thanks. I dropped minidrawers.
