### ISSUE TITLE
Ripple animation on DrawerItem

### ISSUE THREAD

**Issue by Cilenco** [mikepenz/MaterialDrawer#2153]
I tried to implement [this](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B4kv-3uZbS1qN21uRzN6OF9KQ00/useredu-er-featuredisc-motion-idle2.mp4) (the ongoing ripple) for my onboarding. I tried to do this with the following code:

```
public void forceRippleAnimation(final IDrawerItem item)
{
    View itemView = item.getViewHolder(getRecyclerView()).itemView;
    Drawable background = itemView.getBackground();

    if(Build.VERSION.SDK_INT >= 21 && background instanceof RippleDrawable)
    {
        final RippleDrawable rippleDrawable = (RippleDrawable) background;
        rippleDrawable.setState(new int[]{state_pressed, state_enabled});

        Handler handler = new Handler();
        handler.postDelayed(new Runnable()
        {
            @Override public void run()
            {
                rippleDrawable.setState(new int[]{});
                forceRippleAnimation(item);
            }
        }, 200);
    }
}
```

Unfortunately this code does not work because (as I think) the IDrawerItem background is not an instance of a `RippleDrawable`. Am I right with this assumption? What do you think is the best way to implement this?

**Comment by mikepenz** [comment]
@Cilenco if you want to have anything different than the default implementation. you can always implement your own `CustomDrawerItem` see the faq for more infos about custom drawer items..

**Comment by Cilenco** [comment]
Okay thank you I will have a look on it.

How is the ripple color for the items applied here in the library? I search for `attr/selectableItemBackground` but this is not found in the repo. So how is it 'normally' done here?

**Comment by mikepenz** [comment]
The background is set here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDescribeableDrawerItem.java#L78

and the selectable background is retrieved here:
https://github.com/mikepenz/Materialize/blob/develop/library/src/main/java/com/mikepenz/materialize/util/UIUtils.java#L257

**Comment by Cilenco** [comment]
For everyone who also wants to implements this:
I created a [repo](https://github.com/Cilenco/WholeRippleView) here with the final RippleView and an example of a custom DrawerItem.
