### ISSUE TITLE
Programmatically adding sub item to ExpandableDrawerItem causes duplicate items

### ISSUE THREAD

**Issue by thaindq** [mikepenz/MaterialDrawer#2154]
## About this issue
The title says it all, I've encountered this bug after updating to version 6

![](https://i.imgur.com/LKtaNoz.gif)

Here is the [sample app](https://github.com/thaindq/MaterialDrawer/commit/84d19923fef8e8ac2d1d2d95d5d6bd9f3b5ee55f)
## Details
- Used library version: 6.0.2
- Used support library version: 27.0.1
- Used gradle build tools version: 3.0.1
- Used tooling / Android Studio version: 3.0.1
- Other used libraries, potential conflicting libraries: none

## Checklist
- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@thaindq can you please try to collapse this expandable before adding and notifying the adapter?

**Comment by thaindq** [comment]
@mikepenz no help, as you can see on the gif above.  

I just tried again and found out that the issue only occurs when adding sub items while the expandable is collapsed. It works just fine if I expand it first.

**Comment by mikepenz** [comment]
@thaindq the following will work as expected:

```
int pos = result.getPosition(9999);
boolean expanded = expandable.isExpanded();
result.getExpandableExtension().collapse(pos);

expandable.getSubItems().add(new SecondaryDrawerItem().withIdentifier(counter).withName("Sub item " + counter));

if(expanded) {
    result.getExpandableExtension().expand(pos);
}
```
