### ISSUE TITLE
Account Header default profile image

### ISSUE THREAD

**Issue by insecta** [mikepenz/MaterialDrawer#2155]
## About this issue

Hello mike, I am trying to change user's picture if user set any image. I am okay with setting picture if user provides me a link or uploads an image. There is no problem with this but I want to set a default image if user didn't provide any image to me.

`addProfiles(new ProfileDrawerItem()
                        .withIcon(sharedPref.imagelink())` 

I get "default" string as a return if user did not set any image. My default image is in res>mipmap folder.

## Details
Using last version of all.

## Checklist

- [OK ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [OK] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [OK] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [OK] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [OK] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by kaloglu** [comment]
you can define in sharedPref.imageLink().

Could you add sharedPref.imageLink() code?

**Comment by insecta** [comment]
public String imageLink(){
        return sharedPref.getString(user_profile, "default");
}

Here is my sharedpref code. Also I get "default" string from database too.

**Comment by kaloglu** [comment]
You can add "http://domain/.../default_image_link.png" instead of "default".

Or

String image_url=sharedPref.getString(user_profile, "default");
if (image_url.equals("")) image_url="http://domain/.../default_image_link.png"
return image_url;

**Comment by insecta** [comment]
yes @kaloglu, thank you for a great idea. I am going to try this

**Comment by insecta** [comment]
Yes, I set an another link if there is no provide for another image. My problem solved. But @mikepenz if you implemented something for setting default image from drawables, it would be nice to know for another people maybe :)
