### ISSUE TITLE
Icon URL for ExpandableDrawerItem

### ISSUE THREAD

**Issue by philipp65** [mikepenz/MaterialDrawer#2156]
## About this issue

Hi.
I managed to get the PrimaryDrawerItem and the SecondaryDrawerItem working with icon URLs. Now I'm trying the same with the ExpandableDrawerItem. Is there any example of how this could work?

Thank you!

## Details
- [6.0.2] Used library version
- [27.0.1] Used support library version
- [3.0.1] Used gradle build tools version
- [3.0.1] Used tooling / Android Studio version
- [x] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@philipp65 images from the web are not supported via the standard included items. 

There is a sample item doing this for the `PrimaryDrawerItem`: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomUrlPrimaryDrawerItem.java
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomUrlBasePrimaryDrawerItem.java#L105

You'd need to do some similar adjustments for the `ExpandableDrawerItem`
(the `ExpandableDrawerItem`'s source: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ExpandableDrawerItem.java )

**Comment by philipp65** [comment]
Thank you for the fast response.

I know that this is not supported by default. I'm also using your `CustomUrlPrimaryDrawerItem`, `CustomUrlBasePrimaryDrawerItem` & `CustomBaseViewHolder` example classes for using images from the web for PrimaryDrawerItems.
I just wanted to know if theres also an existing implementation of some kind of `CustomUrlExpandableDrawerItem`.

Thank you

**Comment by philipp65** [comment]
Managed it by creating a custom `CustomUrlExpandableDrawerItem`, `CustomUrlBaseDescribeableDrawerItem` and your `CustomBaseViewHolder`

**Comment by mikepenz** [comment]
@philipp65 awesome :) 

If you like you could add an FAQ article via a PR showcasing it, helping others who might need it in the future.
