### ISSUE TITLE
Primary color not used for selection

### ISSUE THREAD

**Issue by Cilenco** [mikepenz/MaterialDrawer#2157]
## Details
- [6.0.2] Used library version
- [27.0.1] Used support library version
- [27.0.3] Used gradle build tools version
- [3.0.5] fastadapter
- [3.0.5] fastadapter-extensions

## Problem
After updating this library and the fastadapter ones the drawer does not use the primary color anymore for the selected text and icon. Here is my style I use in the activity given to the drawer in the constructor:

```
<style name="AppTheme" parent="MaterialDrawerTheme.Light">
    <item name="colorPrimary">@color/ColorPrimary</item>
    <item name="colorPrimaryDark">@color/ColorPrimaryDark</item>
    <item name="colorAccent">@color/ColorAccent</item>

    <item name="android:windowTranslucentStatus">true</item>

    <item name="drawerArrowStyle">@style/DrawerArrowStyle</item>

    <item name="tabBackground">?attr/selectableItemBackground</item>
    <item name="preferenceTheme">@style/PreferenceThemeOverlay.v14.Material</item>
</style>
```

The accent color is used properly with a `SwitchMenuItem`. I also call `withIconTintingEnabled` on each item and if I call `withSelectedIconColorRes` (or. `withSelectedTextColorRes`) it also works great but it is not done automatically by the drawer.

**Comment by mikepenz** [comment]
Please check out:
https://github.com/mikepenz/MaterialDrawer#custom-style---stylesxml

the drawer uses the 
```xml
<item name="material_drawer_selected">@color/material_drawer_selected</item>
```
theme attribute for the selected color

**Comment by Cilenco** [comment]
Yes of course using `material_drawer_selected_text` works grat.
I was only wondering because it worked without it before the update.

Thought it could be a use of wrong `Context` instance when requesting the color internally or something like this. Sorry for bothering about this.

**Comment by mikepenz** [comment]
Hmmm I am not aware of direct changes in this area. 

I wonder if possibly:
https://github.com/mikepenz/Materialize/commit/6a9b3625a47ce190ee480705963ba317afce824b
and
https://github.com/mikepenz/Materialize/commit/895b535bc0f7521995c8a77b1c1ec10d36e15f02

have an effect on this?

**Comment by Cilenco** [comment]
Puh, that's a tough one! Maybe...

But I think it's more important with which `Context` you call these methods.
Do you call `getApplicationContext` within the library or do you use any other `Context` than Activites?

From [this Article](https://possiblemobile.com/2013/06/context/) I got:

> [...] there are a number of functions the application context is not properly suited to handle; all of them related to working with the UI.  In fact, the only implementation equipped to handle all tasks associated with the UI is Activity [...]

**Comment by mikepenz** [comment]
@Cilenco the item uses the view `Context`

```java
Context ctx = viewHolder.itemView.getContext();
```

**Comment by mikepenz** [comment]
I think this can be closed. It uses the correct context. You can define via `material_drawer_selected_text` and otherwise you can also always programatically set the color for the selection via `withSelectedColor` on the item
