### ISSUE TITLE
AccountHeader profile background

### ISSUE THREAD

**Issue by ivanessence** [mikepenz/MaterialDrawer#2159]
Details
[6.0.2] Used library version
[26.1.0] Used support library version
[27.0.3] Used gradle build tools version
 [3.0.1] Used tooling / Android Studio version
Problem
When I try to set icon with png extention to ProfileDrawerItem() I have incorrect background and I don't understand what is it. I suppose it's shadow or something else. I  didn't find any methods to resolve this problem or it's not a problem? Help me pls
![header](https://user-images.githubusercontent.com/17102355/34554178-a8326e22-f13c-11e7-9773-0c7c118a707d.png)

**Comment by mikepenz** [comment]
@ivanessence you can disable the shadow via a theme: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/values/styles.xml#L31

**Comment by ivanessence** [comment]
@mikepenz thx, it's resolve my problem :) also tell me pls can I do it programmatically?

**Comment by mikepenz** [comment]
@ivanessence sadly there is no option to do this programatically

**Comment by ivanessence** [comment]
@mikepenz I have another one question. Can I change this arrow programmatically when I click on header? By default realization I know that it change automatically
![header2](https://user-images.githubusercontent.com/17102355/34563251-f7ac837c-f162-11e7-89ac-3e9a0f155681.png)

**Comment by mikepenz** [comment]
@ivanessence you want to toggle the selection list? or what do you want to do with this arrow?

**Comment by ivanessence** [comment]
@mikepenz for example I set to header withOnAccountHeaderSelectionViewClickListener() and I don't want to go to account list, when I click on header, I want create Drawer with another menu, but I want change arrow state or arrow icon

**Comment by ivanessence** [comment]
@mikepenz ?

**Comment by mikepenz** [comment]
The second list is meant for `profiles` not really for anything else. as you also use profiles in addition you will have to adjust and overwrite some core logics of the drawer, and I am not sure if that is a very good idea. 

The `AccountHeader` provides you with the option to provide listeners for the clicks, you can consume them, adjust the list on the bottom in the drawer to your needs. 
To adjust the arrow then I guess it is the easiest ot get the view of the header, find the `ImageView` containing that arrow, and then change the `Drawable`

**Comment by ivanessence** [comment]
@mikepenz I tried to use `headerResult.getView().findViewById(R.id.material_drawer_arrow).setVisibility(View.INVISIBLE);`
but I have NullPointerException, however if I used `headerResult.getView().findViewById(R.id.material_drawer_account_header_name).setVisibility(View.INVISIBLE);` it work fine. What I did wrong?

**Comment by mikepenz** [comment]
Well the id is a different one:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml#L103

**Comment by ivanessence** [comment]
@mikepenz big thx for help!
