### ISSUE TITLE
Get instance of current drawer

### ISSUE THREAD

**Issue by dennes544** [mikepenz/MaterialDrawer#216]
Hey!

I wanna use your drawer in my project, but i have a question: how to get instance of current drawer, from fragment, to change counters for example, or listen for open/close state

Thanks in advance!

**Comment by mikepenz** [comment]
@dennes544 you create the drawer and will receive a Drawer.Result object. Then you can use this one for all fragments where you have to update stuff.

**Comment by dennes544** [comment]
So I just make my Drawer.Result public  and static and use it?

**Comment by mikepenz** [comment]
@dennes544 there are other ways how to interact with ui components from the activity to fragments. There are a lot of thread about this topic on stackoverflow. :) You should be able to get a good answer ;)

**Comment by dennes544** [comment]
Thanks! And I I may, I have one more question: how to handle click on current user avatar? For example: I click on user avatar and it opening user profile fragment.

**Comment by mikepenz** [comment]
@dennes544 you don't want the switch functionality? Or what do you need?
There's a listener to listen for profile switches

**Comment by dennes544** [comment]
No, switch I need too, but i want another thing. In drawer header, there is a big user avatar, and when I click exactly on this big user avatar it closes the drawer and just change fragment, without profile switch.

**Comment by mikepenz** [comment]
Just add a withOnAccountHeaderListener this will also return a boolean defining if its the current profile

**Comment by dennes544** [comment]
Okay. Big thanks to you and to your work on this NavDrawer!
