### ISSUE TITLE
profile image replaces Drawer Item after clicking profile 

### ISSUE THREAD

**Issue by achievegame** [mikepenz/MaterialDrawer#2160]
![screen shot 2018-01-04 at 1 17 34 pm](https://user-images.githubusercontent.com/5011610/34554290-34d4ea48-f152-11e7-84ce-c6843d9c007d.png)
![screen shot 2018-01-04 at 1 24 03 pm](https://user-images.githubusercontent.com/5011610/34554384-97bd64be-f152-11e7-8c85-a97ef6e80809.png)

I want that after  profile selection there will be Home button as you see in image it replaced by profile image

**Comment by mikepenz** [comment]
@achievegame can you please add a bit more details. I am not quite sure what the issue is here. 
CAn you please also provide some code? What do you do? 
Do you only use the `MiniDrawer` or the `CrossfadeDrawerLayout`?

**Comment by achievegame** [comment]
thanks for the reply. No problem I found the solution.
