### ISSUE TITLE
Glide v4

### ISSUE THREAD

**Issue by k4dima** [mikepenz/MaterialDrawer#2161]
https://github.com/mikepenz/MaterialDrawer/blob/48ea3ee0c8260e9b4b33c459c995f76a88cc9b6f/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java#L42

Should be

```java
DrawerImageLoader.init(new AbstractDrawerImageLoader() {
                @Override
                public void set(ImageView imageView, Uri uri, Drawable placeholder) {
                    Glide.with(imageView.getContext()).load(uri)
                            .apply(new RequestOptions().placeholder(placeholder)).into(imageView);
                }

                @Override
                public void cancel(ImageView imageView) {
                    Glide.with(imageView).clear(imageView);
                }
            });
```

**Comment by mikepenz** [comment]
Thank you very much. The sample currently still uses `Glide 3.x` so the code is not needed. 

For people already updated that is the proper adjustment though ;). 

Thanks  a lot!

**Comment by k4dima** [comment]
@mikepenz actually it should be 
`            DrawerImageLoader.init(new AbstractDrawerImageLoader() {
                @Override
                public void set(ImageView imageView, Uri uri, Drawable placeholder, String tag) {
                    Glide.with(imageView.getContext()).load(uri).
                            apply(new RequestOptions().placeholder(placeholder)).into(imageView);
                }

                @Override
                public void cancel(ImageView imageView) {
                    if (!isDestroyed())
                        Glide.with(imageView).clear(imageView);
                }
            });
`
Glide throws IllegalStateException if activity destoyed.
