### ISSUE TITLE
getCurrentSelection() returns -1 on SubItem when restoring the state

### ISSUE THREAD

**Issue by masterleclerc** [mikepenz/MaterialDrawer#2163]
The problem is that when the state is restored (rotation, activity kill etc) and the `SubItem `was selected before, `drawerResult.getCurrentSelection()` returns -1 . What is important, the expandable list is correctly expanded and proper `SubItem `is selected.  The `drawerResult.getCurrentSelection()` returns correct value if `Item `(not `SubItem`) was selected before the rotation/activity kill. 

My code:
```
        drawerResult = new DrawerBuilder().withActivity(activity)
                .withToolbar(toolbar)
                .withDrawerItems(NavigationDrawerItemProvider.getItems())
                .withOnDrawerListener(new DrawerListener(layoutSwitch))
                .withOnDrawerItemClickListener(new DrawerItemClickListener(layoutSwitch))
                .withSavedInstance(savedInstanceState)
                .build();

        if(isNull(savedInstanceState)) {
            drawerResult.setSelection(ApplicationStartupData.getInstance().getDefaultNavigationItemId(), true);
        } else {
            drawerResult.setSelection(drawerResult.getCurrentSelection(), true); //here is the problem
        }
```
and of course
```
   public void onSaveInstanceState(Bundle outState) {
        drawerResult.saveInstanceState(outState);
    }
```

btw The library is great! :)
  
**Edited:**
I commented  `if(isNull(savedInstanceState))  ... else ...` statement and after more tests I found that `getCurrentSelection()` from time to time returns correct value on the `SubItem`. But when it returns -1, the expandable list is expanded but the proper item isn't selected. That means the state of navigation drawer isn't always correctly restored when the `SubItem ` was selected before.

**Edited 2:**
The problem also affects your example app - DrawerActivity.
1. Open navigation drawer
2. Expand "Collapsable Badge", select the first item - "CollapsableItem"
3. Rote the phone, open menu, check if the "CollapsableItem" is selected
4. If yes, repeat the point 3 as long as "CollapsableItem" will not be selected.
I can't find the pattern - sometimes it happens on the first rotation, sometimes later.

**Comment by mikepenz** [comment]
@masterleclerc  that is the correct behaviour. A sub item which is not currently displayed has no position. 

that's why the selection and re-selecting of the `MaterialDrawer` uses only the `identifier`. 

The whole situation gets a bit more complicated though due to the fact that currently the selection can only be set on root elements. programatically setting the selection to a element which is currently not shown won't work. 

Please see the following issue:
https://github.com/mikepenz/MaterialDrawer/issues/2122

**Comment by masterleclerc** [comment]
Probably I didn't express clearly. I don't use `drawerResult.setSelection()` any more . I just want `withSavedInstance(savedInstanceState)` and `drawerResult.saveInstanceState(outState)` to work correctly with selected sub item. Is it possible? Now occasionally sub item is correctly re-selected after the phone rotation (btw even if the sub list is collapsed). But half of the time it re-selectes anything.

**Comment by mikepenz** [comment]
@masterleclerc well it's the same issue. As the `MaterialDrawer` internally uses the same APIs

I'll improve that in an upcoming version, and automatically recursively re-set selections for expandables

**Comment by mikepenz** [comment]
Hmmm selection should be restored (with the savedInstanceState, on screen rotation for example) of subitems can you please debug into this here:
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.java#L68

Or provide a sample which showcases this issue?

**Comment by masterleclerc** [comment]
Sorry for my bad English ;)
First of all:
> But half of the time it re-selectes anything.
-> But half of the time it re-selectes **nothing**.
---
> Or provide a sample which showcases this issue?

It happens with your sample app and I found the pattern when it happens:
1. Select sub item "CollapsableItem" in the menu, remember to leave "Collapsable Badge" **open**
2. Rotate the phone, CollapsableItem won't be selected (no item in the menu will be selected)

I debuged the code and the problem is with condition `!((IExpandable) item).isExpanded()`
from line the https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/utils/AdapterUtil.java#L21

Now the functions works only with the collapsed IExpandable item. Can we just remove `!((IExpandable) item).isExpanded() `condition?

**Comment by mikepenz** [comment]
Thank you very much for debugging into it. I will check that as soon as possible.

**Comment by mikepenz** [comment]
@masterleclerc as for this behaviour. there is a big new release of the `FastAdapter` upcoming, which should solve the issues you are seeing. You can already test it and give feedback here:

https://github.com/mikepenz/FastAdapter/pull/607

Thank you very much

**Comment by mikepenz** [comment]
Should be fine in the latest release v6.0.3 and FastAdapter v3.2.1
