### ISSUE TITLE
MiniDrawer selected item background not showing sometimes

### ISSUE THREAD

**Issue by androideveloper** [mikepenz/MaterialDrawer#2166]
## About this issue

After upgrade from 5.9.5 to 6.0.2 I have noticed a small issue. I have MiniDrawer  and .withEnableSelectedMiniDrawerItemBackground(true). When I click on MiniDrawer  , background is shown, but when I click from opened drawer (and it closes automatically) background for MiniDrawer  item is missing. The issue is present only after upgrade.

## Details
- [ ] Library 6.0.2
- [ ] Support library 27.0.2
- [ ] Build Tools 27.0.3
- [ ] AS 3.0.1

**Comment by mikepenz** [comment]
Is this reproduceable in the sample app?

**Comment by androideveloper** [comment]
Yeah, just add this line after 145 row in MiniDrawerActivity.
miniResult.withEnableSelectedMiniDrawerItemBackground(true);

**Comment by mikepenz** [comment]
Will be fixed in the next release

**Comment by androideveloper** [comment]
Ok, Thanks!
