### ISSUE TITLE
library in android 2.3.3

### ISSUE THREAD

**Issue by hiyam97** [mikepenz/MaterialDrawer#2168]
Hello, I am unable to add these to my buil.gradle(app) file because I have android 2.3.3, how can I solve this ??

Here are the libraries: 

```java
implementation("com.mikepenz:materialdrawer:6.0.2@aar") {
   transitive = true
}

//required support lib modules
implementation "com.android.support:appcompat-v7:${versions.supportLib}"
implementation "com.android.support:recyclerview-v7:${versions.supportLib}"
implementation "com.android.support:support-annotations:${versions.supportLib}"
implementation "com.android.support:design:${versions.supportLib}"
```

**Comment by mikepenz** [comment]
The `MaterialDrawer` has min API level 14. (as noted in the readme) 

2.3.3 is not supported

**Comment by hiyam97** [comment]
Oh okay thank you

Is there another alternative I can seek, i.e do u know a library that also
handles making a navigation drawer ?

I have been 4 days working on making a navigation drawer from scratch but
nothing else helps on the internet, I am developing an android app for my
senior project

Thanks in advance

**Comment by mikepenz** [comment]
modern application should be API 16+ 

14+ of this library is already a huge compatiblity

This is the last version of this library supporting 10+:
https://github.com/mikepenz/MaterialDrawer/tree/v5.6.0

no support from my side for old versions...

**Comment by hiyam97** [comment]
Thank you so much.
