### ISSUE TITLE
White gap below status bar

### ISSUE THREAD

**Issue by i906** [mikepenz/MaterialDrawer#217]
There is a white gap above the contents when the status bar size is not standard. Tested on a Xiaomi Mi 3, Android 4.4.4.

![screenshot_2015-04-14-12-31-15](https://cloud.githubusercontent.com/assets/866735/7130473/2dab7eaa-e2a3-11e4-8fef-8520e69b38db.png)

**Comment by mikepenz** [comment]
@i906 any custom dpi or something? it seems the statusBar height isn't the 25dp height as it's defined by android

**Comment by i906** [comment]
no, I don't think so. Perhaps the navigation bar height in Xiaomi's version of Android is modified.

**Comment by mikepenz** [comment]
@i906 yes. could be. 

at the moment the statusbar height is fetched through the dimens.xml. i'll try to find a programmatically approach for this

**Comment by mikepenz** [comment]
@i906 please test the new version v2.7.8 i have added another method to get the height by code. probably this fixes your isssue. (i hope so)

**Comment by i906** [comment]
@mikepenz the white gap is now gone with the new version. Though it seems the dark background covering the status bar is missing (the background is there for other phones).

Either way, the original issue is solved. Thank you for the library and support.

![screenshot_2015-04-15-09-47-03](https://cloud.githubusercontent.com/assets/866735/7150911/cf84b82a-e354-11e4-80fb-fc8e9de6a827.png)

**Comment by mikepenz** [comment]
@i906 the shadow is removed by default for Android versions lower than 21 because they normally have the shadow below the statusbar. you can enable it again if you like.
