### ISSUE TITLE
IExpandable: withIsExpanded(boolean collapsed) -> withIsExpanded(boolean expanded)

### ISSUE THREAD

**Issue by masterleclerc** [mikepenz/MaterialDrawer#2170]
I'm not sure but probably `withIsExpanded(boolean collapsed)` from `IExpandable` interface should be named `withIsExpanded(boolean expanded)`.
It is a really small inconsistency but can be misleading.

I'm using static list with drawer items for optimization, so every time I provide the list to the DrawerBuilder I have to set default states:

```
    public List<IDrawerItem> getItems() {
        setDefaultStates();
        return items;
    }

    private void setDefaultStates() {
        for (IDrawerItem item : items) {
            item.withSetSelected(false);
            item.withIsExpanded(false);
        }
    }
```
And `item.withIsExpanded(false)` is shown by IntelliJ as `item.withIsExpanded( collapsed: false)`.

**Comment by mikepenz** [comment]
Thanks That will be in a future update. Sadly not in the next. 

https://github.com/mikepenz/FastAdapter/commit/32b10ab674ca87cf26ca12e7be30db3e79377a66
