### ISSUE TITLE
DrawerBuilder.Build() removes the snackbar when orientation changed

### ISSUE THREAD

**Issue by thairA2Ajaber** [mikepenz/MaterialDrawer#2172]
Hi,

Thanks for the great library.
I have an issue which is :
I'm using `DrawerBuilder.Build()` to build the drawer in 
`onConfigurationChanged(Configuration newConfig)` method , and right before the orientation  changed to portrait i show a snackbar , now when i call `DrawerBuilder.Build()` and the orientation is portrait the toast is gone. 
is there anything i could do to keep the snackbar showing when the orientation changed and the 
 `DrawerBuilder.Build()` while the snackbar is showing ?

Thanks.

**Comment by mikepenz** [comment]
@thairA2Ajaber the `Snackbar`  or `Toast` is not made or handled by the `Drawer`. The drawer has nothing to do with it.

**Comment by mikepenz** [comment]
Remember a `orientationChange` will cause the activity to be recreated resulting in the drawer being recreated and all your view hierachy, that's default android. 

You will need to show the `Snackbar` again in that case
