### ISSUE TITLE
Hidden view is still focusable in CrossFadeSlidingPaneLayout

### ISSUE THREAD

**Issue by Mygod** [mikepenz/MaterialDrawer#2173]
## About this issue

Sample app: https://github.com/shadowsocks/shadowsocks-android/commit/8b584c717f9afb3f5d2f65b6605d3fcb77304176 (or https://github.com/Mygod/shadowsocks-android)

When using minidrawers, hidden view is still focusable in CrossFadeSlidingPaneLayout. This caused malfunctions in d-pad navigations.

## Details
- [x] Used library version 6.0.2
- [x] Used support library version 27.0.2
- [x] Used gradle build tools version 3.0.1
- [x] Used tooling / Android Studio version 3.0.1
- [x] Other used libraries, potential conflicting libraries: https://github.com/Gericop/Android-Support-Preference-V7-Fix

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
New crossfader release to fix this: https://github.com/mikepenz/Crossfader/releases/tag/v1.5.2

**Comment by Mygod** [comment]
That worked perfectly. Thanks.
