### ISSUE TITLE
right to left navigation items and toolbar

### ISSUE THREAD

**Issue by zoho1381** [mikepenz/MaterialDrawer#2174]
My problem is that --> What should I do to make menu-items rtl (rihght-to-left), and toolbar too?

![untitled](https://user-images.githubusercontent.com/25884790/35042502-3b0ff44c-fb9e-11e7-803d-ec31df3f9e77.png)

**Comment by mikepenz** [comment]
@zoho1381 well the toolbar is unrelated to the library. but as the toolbar is in LTR. It seems you simply do not have your application in RTL mode. If the whole app is in RTL mode everything will be on the right.

**Comment by zoho1381** [comment]
about toolbar is ok.
but about menu items? they are not rtl. How should I do this?

**Comment by mikepenz** [comment]
If your application is in real RTL mode they are:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/AndroidManifest.xml#L12
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L45
