### ISSUE TITLE
Drawer drop down for non-Google profiles?  For generic profiles?

### ISSUE THREAD

**Issue by Antebios** [mikepenz/MaterialDrawer#2175]
I am building an app that can view one or more cameras.  I would like to have multiple Camera Profiles.  These are not tied to Google in any way.  Can his 'generic' profile be create and leveraged with your MaterialDrawer?

**Comment by mikepenz** [comment]
@Antebios well the `MaterialDrawer` does not define which kind of information is served with the `Accounts`. the `Account`s section is super generic, and is in general set up for profiles, but you can also use it to serve any other type of toggleable information
