### ISSUE TITLE
How to handle clicks on Profile Photo Icon

### ISSUE THREAD

**Issue by wanclem** [mikepenz/MaterialDrawer#2176]
Hi, given the below

`        currentProfile = new ProfileDrawerItem()
                .withName("Ken")
                .withIcon("ken_photo_url") 
                .withIdentifier(ACTIVE_PROFILE);
`
How can I allow users click on the user photo(icon) to open a custom activity?

Thanks

**Comment by mikepenz** [comment]
You simply provide a listener: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L400
To your `AccountHeaderBuilder` 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L519
