### ISSUE TITLE
Drawer showing navigation bar's shadow, even when in fullscreen

### ISSUE THREAD

**Issue by sbruno-tupaca** [mikepenz/MaterialDrawer#2177]
Hi Mike, I''ve been trying to find a solution to this problem for a couple of days now, but I can't seem to get to the bottom of it.
My drawer still shows the navigation and status bar shadows even when both are hidden.
Exactly like this: https://i.hizliresim.com/XEVaa3.png (not my actual app)
Googling, i've found what I thought was a valid solution for this, which is set the FLAG_LAYOUT_NO_LIMITS flag on my activity, but this causes my fragments to not resize when the softKeyboard is shown (exactly like https://github.com/mikepenz/MaterialDrawer/issues/95)
Both shadows are shown only on the drawer, and not on the fragment container nor the fragments.
Any help would be greatly appreciated.
Thank you for this awesome library, it really is a life saver.

**Comment by mikepenz** [comment]
@sbruno-tupaca the `NavigationBar`  and `StatusBar` is from the system, not from this drawer. 

That's why the latest drawer does no longer set any of these flags and works with the system built in `fitsSystemWindow`s flags
