### ISSUE TITLE
compile is deprecated

### ISSUE THREAD

**Issue by Mygod** [mikepenz/MaterialDrawer#2178]
Source: https://stackoverflow.com/a/44493379/2245107

https://github.com/mikepenz/MaterialDrawer/blob/e22b593682b4952182543023297d493c2c621ff4/library/build.gradle#L40-L51

**Comment by mikepenz** [comment]
@Mygod I know. but I can not update to `api` as long as the gradle publishing would otherwise miss those in the `pom.xml` 

I will update as soon as api and implementation are supported by it

**Comment by mikepenz** [comment]
Just for completeness I was refering to: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/build.gradle#L2

**Comment by mikepenz** [comment]
Thanks for the report though

**Comment by Mygod** [comment]
Are you sure you need that plugin to publish it? I've seen some other open source library that doesn't need that, like [this one](https://github.com/Gericop/Android-Support-Preference-V7-Fix).
