### ISSUE TITLE
Minor issue with Huge font size on Amazon Kindle Fire 4th generation 7inches

### ISSUE THREAD

**Issue by afarber** [mikepenz/MaterialDrawer#2180]
Hello Mike, thank you for your software, which I am just learning to use.

Just FYI there is a minor issue with Amazon Kindle Fire devices - when I select the "Huge" font site, the menus in your sample app look a bit crowded:

![screenshot_2018-01-21-13-11-56](https://user-images.githubusercontent.com/1884458/35194087-72577454-fead-11e7-942a-89489cb11c59.png)
![screenshot_2018-01-21-13-12-04](https://user-images.githubusercontent.com/1884458/35194088-7270d5de-fead-11e7-98f4-7779176cc0bf.png)
![screenshot_2018-01-21-13-12-22](https://user-images.githubusercontent.com/1884458/35194089-728b713c-fead-11e7-8024-6b294343e47c.png)
![screenshot_2018-01-21-13-13-37](https://user-images.githubusercontent.com/1884458/35194090-72a4134a-fead-11e7-9c41-fa4b28b05032.png)

**Comment by mikepenz** [comment]
@afarber I think for this purpose there needs to be a specific item provided. It simply can't fit in the default items :D 

You can implement your own `CustomDrawerItem`s or you provide an additional layout (for the default)  items handling this case. (copy the *.xml of the default item, add it to the proper layout folder for that device, and adjust sizes to your needs :))
