### ISSUE TITLE
Action bar uses black font despite "Light" theme and overlaps the left drawer menu

### ISSUE THREAD

**Issue by afarber** [mikepenz/MaterialDrawer#2181]
Good evening, I am new to the MaterialDrawer and would like to create a white navigation menu on the left plus an action bar which would change the burger icon to the left arrow when the menu is open.

First I try the code without an action bar and it looks ok -

![screenshot_2018-01-21-18-31-49](https://user-images.githubusercontent.com/1884458/35197725-e29fbcf4-fee3-11e7-9090-9c3361395d5f.png)

**Layout file activity_main.xml**

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center">

        <FrameLayout
            android:id="@+id/root"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
</RelativeLayout>

```
**MainActivity.java onCreate method**

```
setTheme(R.style.MaterialDrawerTheme_Light);
setContentView(R.layout.activity_main);

mNavigationDrawer = new DrawerBuilder()
        .withActivity(this)
        .withSavedInstance(savedInstanceState)
        .withDisplayBelowStatusBar(true)
        .addDrawerItems(
            new PrimaryDrawerItem().withName("Item 1").withIcon(R.drawable.play_circle),
            new PrimaryDrawerItem().withName("Item 2").withIcon(R.drawable.numeric_2_box),
            new PrimaryDrawerItem().withName("Item 3").withIcon(R.drawable.numeric_3_box)
);

```
Then I try to add the action bar by switching the theme and suddenly it obscures the "Item 1" entry in the navigation menu:

![screenshot_2018-01-21-18-29-10](https://user-images.githubusercontent.com/1884458/35197720-cf157868-fee3-11e7-855b-0a1ed3cee54b.png)

**MainActivity.java onCreate method**

```
setTheme(R.style.MaterialDrawerTheme_Light_ActionBar);
setContentView(R.layout.activity_main);

mNavigationDrawer = new DrawerBuilder()
        .withActivity(this)
        .withSavedInstance(savedInstanceState)
        .withDisplayBelowStatusBar(true)
        .addDrawerItems(
            new PrimaryDrawerItem().withName("Item 1").withIcon(R.drawable.play_circle),
            new PrimaryDrawerItem().withName("Item 2").withIcon(R.drawable.numeric_2_box),
            new PrimaryDrawerItem().withName("Item 3").withIcon(R.drawable.numeric_3_box)
);

getSupportActionBar().setDisplayHomeAsUpEnabled(true);
getSupportActionBar().setHomeButtonEnabled(true);
```

I have 3 problems with the above code:

- Why is the title text black? I was expecting it to be white in the "Light" theme
- Why is the "Item 1" menu entry obscured by the title?
- How to enable the "Burger" menu and enable changing it to "Arrow"?

Thank you for any hints!

By the way I set the theme in onCreate and not in AndroidManifest.xml, because I use a splash theme in the latter file.

**Comment by mikepenz** [comment]
@afarber actionbar's are deprecated. 
Having the Drawer on top of a `Toolbar` is against the guidelines and not recommended. 
If you still want it, there is a sample in the `Sample` app which showcases to have the drawer in a sub view (different location) 

Please check the sample
