### ISSUE TITLE
update badge of SecondaryDrawerItem, badge not showing

### ISSUE THREAD

**Issue by Quacksilber** [mikepenz/MaterialDrawer#2182]
## About this issue

My drawer contains an ExpandableBadgeDrawerItem (with ID=1) with a SecondaryDrawerItem (with ID=2).

Both have styles set up for them, and using .setBadge directly in the drawer builder (result) works perfectly for both of them.

```
new ExpandableBadgeDrawerItem().withName("A").withIcon(R.drawable.ic_feedback).withSelectable(false).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.md_red_700)).withIdentifier(1).withSubItems(
new SecondaryDrawerItem().withName("B").withIcon(R.drawable.ic_funktionsanforderung).withIdentifier(2).withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.md_red_700)),
```
However, when calling

```
result.updateBadge(1, new StringHolder("1"));
result.updateBadge(2, new StringHolder("1"));
```

only the ExpandableBadgeDrawerItem receives a badge.

## Details
- MatrialDrawer v6.0.2
- build tools version 26.0.1
- Android Studio 2.3.3

**Comment by mikepenz** [comment]
@Quacksilber the second item is a `SubItem` the `update` methods to not update sub items. 

https://github.com/mikepenz/MaterialDrawer/issues/1705#issuecomment-275867012

This will perhaps be optimized in the future.

**Comment by Quacksilber** [comment]
Hey @mikepenz , thanks for your response!
unfortunately the line 1679, from your referenced issue deosnt exist anymore, but I tried to solve my problem. 
So far I have 
```
SecondaryDrawerItem s = (SecondaryDrawerItem) IDraweritem;
s.withBadge((StringHolder) null);
result.getAdapter().notifyItemChanged(result.getPosition(7));
```

what does this draweritem have to be?
and what do I have to insert for null? Javadoc says sth. like badgeRes, but I have no clue what that is :D 

or is this a totally wrong approach?

**Comment by mikepenz** [comment]
The `null` was just to reset the badge. :D removing the badge is basically the same `update` task as setting a new value :) 

Oh sorry. the linked line moved to a new file:
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.java#L180

Get the `ExpandableExtension` of the adapter and notify that a subitem changed

**Comment by mikepenz** [comment]
alternative you can also just call the notify method on the adapter for this items position (it is the same)
