### ISSUE TITLE
it's possible to dynamically change Drawer content? 

### ISSUE THREAD

**Issue by rudda** [mikepenz/MaterialDrawer#2185]
I'm using CustomView to change the drawer layout, but in the layout change throws the following exception: 

> The specified child already has a parent. You must call removeView() on the child's parent first

```
 public void changeNavDrawer2AlertContent(){
            this.navRigth = new DrawerBuilder()
                    .withCustomView(viewAlert)
                    .withActivity(this)
                    .withDrawerLayout(-1)
                    .withDrawerGravity(Gravity.RIGHT)
                    .build();
    }

    public void changeNavDrawer2MessageContent(){
            DrawerBuilder drawerBuilder =   new DrawerBuilder()
                    .withCustomView(viewMessage)
                    .withActivity(this)
                    .withDrawerLayout(-1)
                    .withDrawerGravity(Gravity.RIGHT);

            this.navRigth = drawerBuilder.build();
    }
```

**Comment by mikepenz** [comment]
@rudda what you try is create a new drawer. which is NOT supported. A drawer can only be created once in an activity (+ one appended drawer if you want one on both sides) 

You can though adjust and update the items within. 


All shown and mentioned in the readme and samples: https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

**Comment by rudda** [comment]
I'm trying to do a custom layout for the drawer.
in addition this same drawer can switch between one and another layout.

**Comment by mikepenz** [comment]
you can not change the layout after the drawer was created. sorry. this is not supported, and there are no plans to support that any any time.

**Comment by rudda** [comment]
using withcustomView method i can to inflate one LinearLayout into drawer and using addView and removeAllView methods from linearLayout then i can do change drawer layout content.
realy i stay using two drawers. thus i  use one drawer with com linearLayout with dinamic content

**Comment by mikepenz** [comment]
Well removing the childs and adjusting them is possible, but there is no support for this. So if it causes issues or problems I can not support that approach.

**Comment by soenkegissel** [comment]
But to remove children and readd them the withOnDrawerItemClickListener() will not work anymore with the newly added items.
Changing item1 with another one the action onClick will stay the same.
I would fancy an example where a change in the header profile will call a new activity with the right selection in header and new items in the drawer (with new actions associated).

**Comment by mikepenz** [comment]
@soenkegissel it is not common practice to have multiple activities with multiple drawers. if you have such a case you will have to handle selections on your own. no sample needed as it is no rocket sience. drawers are meant to be for navigation patterns like one activity with draewr and then fragments, or you jump somewhere which does not have a drawer. 

also if you replace item 1 with another the usual click listener will then be notified on click for the new item.

**Comment by soenkegissel** [comment]
Thank you for the quick answer.
When I am using Google Inbox or Google AdWords and I select another account from the header my drawer will get updated accordingly. For Inbox the personal folders get shown, for AdWords the campaigns. For me the same is needed for the drawer.

**Comment by mikepenz** [comment]
simply use the provided methods to remove/add/change elements which are in the drawer

https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

**Comment by soenkegissel** [comment]
Ok understood. But what about changing the listeners as well?

**Comment by mikepenz** [comment]
@soenkegissel why would you need to change the listener? 

you can simply check in the global listener which item was clicked. you get the identifier, or the position. (usually you should define a unique identifier to make your life easier) and then just do whatever you have defined for a specific element

**Comment by soenkegissel** [comment]
I could assign unique identifiers for every possible entry and then add a listener with every possible identifier as well. But this will be bit obscure.
Ahh you answered already - same thing. Thanks!

**Comment by mikepenz** [comment]
The listener always has also the `DrawerItem` for the click event available. and the beauty of it. the developer (so you) have all the freedom, you can handle it via position, via identifier, via any object you attach to the item. 

https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/java/com/mikepenz/fastadapter/IItem.java#L30

all up to you :)
