### ISSUE TITLE
PrimaryDrawerItem disabled (does not react on clicks), but not greyed out when calling withEnabled(false)

### ISSUE THREAD

**Issue by afarber** [mikepenz/MaterialDrawer#2187]
Good evening, I have searched old issues, for example #1266

In a word game I would like to display a navigation drawer on the left side and a game actions on the right side:

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {

        mNavigationDrawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(mToolbar)
                .withHeader(R.layout.left_header)
                .withShowDrawerOnFirstLaunch(true)
                .withActionBarDrawerToggle(true)
                .build();

        mActionDrawer = new DrawerBuilder()
                .withActivity(this)
                .withHeader(R.layout.right_header)
                //.withGenerateMiniDrawer(true)
                .withDrawerGravity(Gravity.END)
                .append(mNavigationDrawer);
```

I fill the actions drawer by the following code:

```
    private Drawer mNavigationDrawer;
    private Drawer mActionDrawer;

    private final List<IDrawerItem> mNavigationMenu = new ArrayList<>();
    private final List<IDrawerItem> mActionMenu = new ArrayList<>();

    private final PrimaryDrawerItem mRecallItem = new PrimaryDrawerItem()
            .withName(R.string.item_recall_letters)
            .withIcon(R.drawable.item_recall_letters)
            //.withSelectable(false)
            //.withDisabledTextColor(Color.GRAY)
            //.withDisabledIconColor(Color.GRAY)
            .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                @Override
                public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                    mGameView.recallAllLetters();
                    return false;
                }
            });

    private void buildActionMenu() {
        mActionMenu.clear();
        mActionMenu.add(mResignItem);
        mActionMenu.add(mSkipItem);
        mActionMenu.add(mSwapItem);
        mActionMenu.add(mShuffleItem);
        mActionMenu.add(mRecallItem);
        mActionMenu.add(mPlayItem);
        mActionDrawer.setItems(mActionMenu);
    }
```

And then, when user drags tile around in my custom mGameView, I repeatedly call the method, depending on user actions (dragging letter tiles to the board):

```
    @Override
    public void updateActionMenu(boolean canResign, boolean canSkip, boolean canSwap, boolean canShuffle, boolean canRecall, boolean canPlay) {
        mActionDrawer.updateItem(mResignItem.withEnabled(canResign));
        mActionDrawer.updateItem(mSkipItem.withEnabled(canSkip));
        mActionDrawer.updateItem(mSwapItem.withEnabled(canSwap));
        mActionDrawer.updateItem(mShuffleItem.withEnabled(canShuffle));
        mActionDrawer.updateItem(mRecallItem.withEnabled(canRecall));
        mActionDrawer.updateItem(mPlayItem.withEnabled(canPlay));
    }
```

It does disable clicking the items.

But for some reason they are not greyed out, the icon and the text stay black -

Screenshot Moto G (recall drawer item and all other items stays black):

![screenshot_20180125-174049](https://user-images.githubusercontent.com/1884458/35401078-da029720-01f8-11e8-9e70-fbd8563200e2.png)

Screenshot Amazon Fire Kindle 7 (recall item stays blue for some reason and all others are black):

![screenshot_2018-01-25-20-44-21](https://user-images.githubusercontent.com/1884458/35408883-ed1dba7a-0210-11e8-8085-cdf0b6cd8598.png)

Please help

## Details
- [6.0.2] Used library version
- [27.0.2] Used support library version
- [ ] Used gradle build tools version
- [27.0.3] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by afarber** [comment]
I have modified the official example app [MultiDrawerActivity.java](https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MultiDrawerActivity.java) by moving 1 drawer item to:

```
    private PrimaryDrawerItem freeplay = new PrimaryDrawerItem().withName(R.string.drawer_item_free_play).withIcon(FontAwesome.Icon.faw_gamepad);

        result = new DrawerBuilder()
                .withActivity(this)
                .withHeader(R.layout.header)
                .withSavedInstance(savedInstanceState)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.drawer_item_home).withIcon(FontAwesome.Icon.faw_home).withBadge("99").withIdentifier(1),
                        freeplay,
                        new PrimaryDrawerItem().withName(R.string.drawer_item_custom).withIcon(FontAwesome.Icon.faw_eye).withBadge("6").withIdentifier(2),
                        new SectionDrawerItem().withName(R.string.drawer_item_section_header),
                         .....
```

And then try to toggle that item with:

```
                                    int badge = Integer.valueOf(badgeable.getBadge().toString());
                                    if (badge > 0) {
                                        badgeable.withBadge(String.valueOf(badge - 1));
                                        result.updateItem(freeplay.withEnabled(badge % 2 == 0));
                                        result.updateItem(drawerItem);
                                    }
```

And unfortunately that does not work either - the "Free Play" item is never greyed out

Regards
Alex

**Comment by mikepenz** [comment]
@afarber it seems the `freePlay` item misses the `identifier`?

**Comment by afarber** [comment]
Adding` .withIdentifier() ` call has fixed my issue, thank you.

I can not find in the docs though, when to add identifier, always?

**Comment by mikepenz** [comment]
Usually you should always set an identifier. but the lib will assign automatically one too. In the next update there will be some fixes related to this. (FastAdatper 3.x changed auto defined ids to be < -1, which resulted in issues it seems)
