### ISSUE TITLE
White status bar While using the drawer

### ISSUE THREAD

**Issue by sohail77** [mikepenz/MaterialDrawer#2191]
## About this issue
I'm using my custom theme to set the status bar color to black ,but when i create a drawer the status bar color changes to white and I'm unable to change it 

here is how it looks
![device-2018-01-28-150036](https://user-images.githubusercontent.com/6673533/35480790-202e2dc8-043c-11e8-8696-3e5643daeea9.png)

this is the theme i'm using

` <style name="listtheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimaryDark">@android:color/white</item>
        <item name="colorAccent">@color/shopAccent</item>
        <item name="android:statusBarColor" tools:targetApi="lollipop">#000000</item>
        <item name="android:windowActivityTransitions" tools:targetApi="lollipop">true</item>
    </style>`

**Comment by mikepenz** [comment]
@sohail77 the thing is that the `DrawerLayout` from google uses it's own scrim which sets the color. you have to adjust the color on the `DrawerLayout` 
https://github.com/mikepenz/MaterialDrawer/issues/1247#issuecomment-217641415

(in your sample you might want to make the image go below the statusbar for the best look) see the `CollapsingToolbar` sample
