### ISSUE TITLE
default user name and email after resume

### ISSUE THREAD

**Issue by DDolG** [mikepenz/MaterialDrawer#2194]
Hi! Thank you for the nice code.
I have liitle problem with header.
I loggin in app by firebase, and write name user and email. 
![user_error_1](https://user-images.githubusercontent.com/35914802/35499795-b900b322-04f5-11e8-9cf6-7c9cfd95f533.jpg)

But after i start another activity in user name appeare "Android Studio", email - "android.studio @android.com"
![user_error_2](https://user-images.githubusercontent.com/35914802/35499802-bd014aae-04f5-11e8-9295-8b639f058190.jpg)

## Details
- [ 0.9.5@aar] Used library version

**Comment by mikepenz** [comment]
@DDolG only support for latest versions. (But as this questions is version independent here my answer)

The thing is a drawer is setup in one activity, if you modify it there. it's just within one activity. You have to apply the same changes in other activities too if you navigate there. 
The library does not and will never contain any persistence code to remember progrmatically generated items, or modifications to the items. That's the only part up to the developer depending on the usecase. 

The best would anyways be to have a fragment navigation. so the drawer exists only once. if this is not possible. you will have to sync modifications across activities and apply the asme changes over and over again.

**Comment by DDolG** [comment]
Thank you very much
