### ISSUE TITLE
adding entries to FAQs

### ISSUE THREAD

**Issue by mithrilstar** [mikepenz/MaterialDrawer#2196]
Hi Mike

I've just started using MaterialDrawer in an [android starter project](https://github.com/mithrilstar/Android-Starter) I'm making for myself. Would it be helpful if I add sections to the FAQ here about anything MaterialDrawer related that I wasn't clear on? I'm assuming that if I had to search for something, another user might also have to search for it.

If you think this would be of help, tell me if there are any specific things/formats etc I should keep in mind. Also should I fork and have open pull requests?

Thanks for the awesome work!

**Comment by mikepenz** [comment]
@mithrilstar definitely everything which can help new users, which caused questions should be added to the FAQ. :) 

Yes forking and opening PRs is the way to go :)

Related to the format. Just keep it similar to the existing FAQs
Have the link in the  FAQ.md and link to a page per topic.
