### ISSUE TITLE
how to cancel the color of the default selected item?

### ISSUE THREAD

**Issue by jhwsx** [mikepenz/MaterialDrawer#2197]
I just move from NavigationView to MaterialDrawer. The problem I face is that there is always a item in the drawer with selected color. In fact, I want to cancel this default selected color. I want the selected color to show only when I click this item. I am trying to be successful by reading the related APIs and doing a lot of trials, but I am failing. I am very frustrated now, because the pm and ui are forcing me to do that.

Used library version is 6.0.2
Used support library version is 25.3.1
Used gradle build tools version is 2.3.2
Used tooling / Android Studio version is 2.3.2

**Comment by mikepenz** [comment]
@jhwsx you want no selection at all? or you want just selected items have no color?

**Comment by mikepenz** [comment]
For no selection: https://github.com/mikepenz/MaterialDrawer#how-can-i-create-a-drawer-without-a-default-selection :D

**Comment by jhwsx** [comment]
What I want is no selection at all. Thanks a billion. You're really very helpful. On the other hand, I am so careless that I missed the FAQ.
