### ISSUE TITLE
App is crashing if I use onBackPressed()

### ISSUE THREAD

**Issue by sezoid** [mikepenz/MaterialDrawer#22]
I use this code for hide Navigation Drawer/close activity:

```java
@Override
public void onBackPressed() {
     if (drawerResult.isDrawerOpen()) {
           drawerResult.closeDrawer();
     } else {
          super.onBackPressed();
     }
}
```
LogCat:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.mikepenz.materialdrawer.Drawer$Result.isDrawerOpen()' on a null object reference at ru.sezex.miped.MainActivity.onBackPressed(MainActivity.java:213)

**Comment by Moter8** [comment]
Hint: To make code show up easier to read on Github issues/elsewhere surround it by three `

\`\`\` java
if (isAwesome){
  return true
}
\`\`\`
will show up as
``` java
if (isAwesome){
  return true
}
```

**Comment by egor-n** [comment]
Your `drawerResult` is null. Where are you assigning value to it?

**Comment by sezoid** [comment]
Above ```javaprotected void onCreate(Bundle savedInstanceState)
```


```java
private Drawer.Result drawerResult = null;
```

**Comment by egor-n** [comment]
Well, it is `null`. Are you assigning it a value in `onCreate`? I mean like this:

```java
@Override
protected void onCreate(Bundle savedInstanceState) {
    drawerResult = new Drawer()
            .withActivity(this)
    // ..
```

**Comment by sezoid** [comment]
@egor-n oh, thanks. I love you <3

**Comment by mikepenz** [comment]
Great that you were able to solve your issue :).
