### ISSUE TITLE
removeStickyItem(index) method doen't exist

### ISSUE THREAD

**Issue by jrcacd** [mikepenz/MaterialDrawer#2201]

**Comment by mikepenz** [comment]
You can remove it by passing the position: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L903

**Comment by jrcacd** [comment]
But I. have multiple itens acording with user choices.
With removeStickyItem(index) I do not need to track the positions of the items

**Comment by mikepenz** [comment]
@jrcacd and why does `removeStickyFooterItemAtPosition(int position) ` not work?

**Comment by jrcacd** [comment]
Sorry, my question has a mistake.
I wrote 'removeStickyItem(index) method doen't exist' but it should be 'removeStickyItem(**long identifier**) method doen't exist'

An example: if I have 3 StickyFooterItem's, and each one may be visible or not, with several visible at the same time. 
If I remove the 2nd and then some time later need to remove the 3rd, to do it, now I have to keep track of the index of each item to be able to remove.
But if each of them already has an Identifier, why have this work?
Just calling a method 'removeStickyItem(**long identifier**)

**Comment by mikepenz** [comment]
You can use this method to get the position: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L464

**Comment by jrcacd** [comment]
Ok, thanks.
