### ISSUE TITLE
Apostrophe not preceded by \ (in  GNU LESSER GENERAL PUBLIC LICENSE<br />

### ISSUE THREAD

**Issue by BigGitWorld** [mikepenz/MaterialDrawer#2203]
I copied your "MaterialDrawer/app" sample code to android studio and run the project.
But I will get the following error : 
```
/home/MyWorks/AndroidProjects/TestMaterialDrawer/app/build/intermediates/res/merged/debug/values/values.xml
Error:(6259) Apostrophe not preceded by \ (in  GNU LESSER GENERAL PUBLIC LICENSE<br />
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```
why?

**Comment by mikepenz** [comment]
@BigGitWorld that one is not in the MaterialDrawer. I am not aware of such a string.

**Comment by BigGitWorld** [comment]
okay. thank you very much.

**Comment by mikepenz** [comment]
@BigGitWorld Seems you have had opened the issue in the wrong repo. 

It was a issue in the AboutLibraries. Which got fixed: https://github.com/mikepenz/AboutLibraries/releases/tag/v6.0.4
