### ISSUE TITLE
Secondary description text color

### ISSUE THREAD

**Issue by BigGitWorld** [mikepenz/MaterialDrawer#2205]
## About this issue
I want to set a color for description of secondary items.
I saw "withDescriptionTextColor" method to change it programmatically, but I want to change by theme.
I can change text of secondary items by "material_drawer_secondary_text", but I did not find any
attribute for it's description text color too.
should I create a attribute in attr.xml?

**Comment by mikepenz** [comment]
@BigGitWorld it uses the same color as the normal text.
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDescribeableDrawerItem.java#L88

If you want to change it just provide the themed color via the programatical approach, or you have to create your own custom drawer item allowing you to do this

**Comment by BigGitWorld** [comment]
I know that but think its good to assign a attribute to it also.
thank you.
