### ISSUE TITLE
icon size

### ISSUE THREAD

**Issue by BigGitWorld** [mikepenz/MaterialDrawer#2206]
## About this issue
I'm using several svg icons for drawer instead of font-icons and know you are using material design guidelines.
Moreover, I need to change the icon size because my icon is very detailed and must to be a little larger.
I saw that Item have some padding (paddingTop & paddingBottom).
what is the best way to increase size of my icons?

**Comment by mikepenz** [comment]
@BigGitWorld if you want to have different style of the items. You have to implement your own `CustomDrawerItem` as described in the FAQ.
