### ISSUE TITLE
setSelection() dont work

### ISSUE THREAD

**Issue by OlegWock** [mikepenz/MaterialDrawer#221]
I call the method setSelection(), but it does not work and does not stand out item in draver. Code: 
```java
result.setSelectionByIdentifier(-1);
```

**Comment by mikepenz** [comment]
You try to set the selection to an element with an identifier -1. you can't have items with an identifier lower than 0. 

also if you want to deselect you should not call setSelectionByIdentifier but setSelection instead.

**Comment by OlegWock** [comment]
Lol. I have item with id -1
```
result.addItem(new PrimaryDrawerItem().withName(res.getString(R.string.all)).withIdentifier(-1));
```
and it has been used successfully in the listener
```
int id = iDrawerItem.getIdentifier();
if (id == -1) {
     readNotes("", -1);
     curCat = -1;
 }
```

**Comment by mikepenz** [comment]
@OlegWock i really recommend not using identifiers lower then 0. 

In the listener it just gives you the value of the drawerItem no other methods are called

**Comment by OlegWock** [comment]
ok, thanks you

**Comment by ashraful29** [comment]
In my Case setSelection does not select any drawer item.
     result = new DrawerBuilder()
                .withActivity(this)
                .addDrawerItems(
                        new        PrimaryDrawerItem().withName("Home").withIcon(FontAwesome.Icon.faw_home).withIdentifier(-1),
                        new PrimaryDrawerItem().withName("Wishlist").withIcon(FontAwesome.Icon.faw_heart),
               .............     
    result.setSelection(1);

**Comment by mikepenz** [comment]
@ashraful29 because you do not have a drawerItem with `identifier` **1**.
Negative identifiers are not supported either.

**Comment by ashraful29** [comment]
Thank you. Now issue is Fixed
