### ISSUE TITLE
How to remove all items in a drawer or add a new  item in a drawer, which is not present in the list? 

### ISSUE THREAD

**Issue by parmarravi** [mikepenz/MaterialDrawer#2210]
Hello Mike,

 I have a add button in a navigation bar ,when user presses this button it will  check for new data  and will update the navigation bar  from the database.
**Q ) How can i  update the drawer with new Data ?** 
**Q ) Can we get the list of  data present in a ' itemSwitch ' drawer ?** 

The below code is invoked every time when the add button is press.it gets the result from the Async task  running in the background.
```
 public void getResult(Context rescontext) {

        mContext = rescontext;
        t = new ToastMessage(rescontext);
        Log.e("DEVICE SIZE:", String.valueOf(deviceAdd.getDrawerItems().size()));
        // it should get invoked when user has already launched the app.
        if(deviceAdd.getDrawerItems().size() >5 && deviceAdd.getDrawerItem(itemSwitch)!=null) {
//            Log.e("DEVICE:", "removing items....");
//            deviceAdd.getDrawerItem(itemSwitch).removeItems();
        }
        for (int i = 0; i < db.HomeLightDao().getDeviceTurnedOn().size(); i++) {
            itemSwitch = new SwitchDrawerItem()
                    .withName(db.HomeLightDao().getDeviceTurnedOn().get(i).getDname())
                    .withIcon(FontAwesome.Icon.faw_lightbulb_o)
                    .withIconColor(rescontext.getResources().getColor(R.color.white))
                    .withOnCheckedChangeListener(onCheckedChangeListener).withChecked(true);
            deviceAdd.addItem(itemSwitch);
        }
        deviceAdd.updateItem(itemSwitch);
    }

```

**Comment by mikepenz** [comment]
Adding removing clearing the drawer just via the existing methods on the `Drawer` object
https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

Item's in the `AccountHeader` (which you possibly refer to as `itemSwitch` drawer, are in the `AccountHeader` which also offers you a great amount of methods ;)

**Comment by parmarravi** [comment]
How can i get the list of data present in the itemSwitch ? so that i can compare if data is present or not.

**Comment by parmarravi** [comment]
I dont know below code is a correct way to do it  or not . but its not working now 
I am unable to remove the items in itemSwitch drawer . so i have to reconstruct entire navigation bar items
` ```
public void getResult(Context rescontext) {
        mContext = rescontext;
        t = new ToastMessage(rescontext);
        if(deviceAdd.getDrawerItems().size()>4){
            Log.e("remove items","true");
            deviceAdd.removeAllItems();
            deviceAdd.addItems(lamp, lightStrip, smartLightStrip);
            deviceAdd.addItems(new DividerDrawerItem());
        }
        for (int i = 0; i < db.HomeLightDao().getDeviceTurnedOn().size(); i++) {
            itemSwitch = new SwitchDrawerItem()
                    .withName(db.HomeLightDao().getDeviceTurnedOn().get(i).getDname())
                    .withIcon(FontAwesome.Icon.faw_lightbulb_o)
                    .withIconColor(rescontext.getResources().getColor(R.color.white))
                    .withOnCheckedChangeListener(onCheckedChangeListener).withChecked(true);
            deviceAdd.addItem(itemSwitch);
        }
    }
```

**Comment by mikepenz** [comment]
Glad that you solved it :) 

Not sure what you mean with `ItemSwitch` drawer. but they are not handled in the normal `Drawer` class but only in the `AccountHeader`
