### ISSUE TITLE
Is ther a click listerner for the profiles 

### ISSUE THREAD

**Issue by AsfanUlla** [mikepenz/MaterialDrawer#2211]
How can i implement a click listerner on the profiles in the header?

**Comment by mikepenz** [comment]
There are various listeners. Like this one:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L519

Just check out the javadoc of the code. 
+ simply read the available methods on the `AccountHeader` class ;)

**Comment by AsfanUlla** [comment]
Thank you I have another question when clicked on profile there is a drop down with list/details. in crossfade drawer i managed to prevent it when the drawer is completely expanded but when the drawer is half open or the way it expand in crossfade when clicked on profile image the list gets expanded. How cant prevent this from happening.
Than you for your support.
Love your work Big Fan
