### ISSUE TITLE
Help me.

### ISSUE THREAD

**Issue by Pryanko** [mikepenz/MaterialDrawer#2212]
How can I change the icon (home button) in the Toolbar?

**Comment by Pryanko** [comment]
Sorry, if we use toolbar.setNavigationIcon(R.drawable.not_burger), after result.withToolbar(toolbar). The icon takes the form of a burger.I would like another icon.
For myself, I found a solution.I do not call result.withToolbar(toolbar). 
I use 
        public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                result.openDrawer();
                return true;
        } 
.
Do you think this is correct?

**Comment by mikepenz** [comment]
@Pryanko the `Toolbar` and the `ActionbarDrawerToggle` are only indirectly handled by the drawer. it is not core functionality. and you should refer to the official doc of these. 

Just as info before. the `ActionbarDrawerToggle` does not allow to change its icons and you will have to do it manually. 
Also you will then have to manually open / close the drawer
