### ISSUE TITLE
MenuItem margin from Top

### ISSUE THREAD

**Issue by MorZada** [mikepenz/MaterialDrawer#2213]
Hello,

How can I set a menuItem margin from the top of the device (not margin from another items)?
For example, set the third Item to to be with 300dp margin from top? (or from the the bottom)?

Thanks in advance,
Mor

**Comment by mikepenz** [comment]
@MorZada I'd guess it is easiest to just create a `placeHolder` item (like the `DividerDrawerItem` or the `ContainerDrawerItem`) and put that at the position where you need spacing

**Comment by MorZada** [comment]
Thanks for the answer, but I'm not sure what you mean.

If I want to replace this:

PrimaryDrawerItem item3 = new PrimaryDrawerItem().
               withIdentifier(3).withName(R.string.drawer_item_payment).withIcon(R.drawable.sidebar);

Do you mean to replace PrimaryDrawerItem with DividerDrawerItem? How do I set the margin? (and icon and name)?

**Comment by mikepenz** [comment]
it would basically be like

```
placeholderItem <-- does not serve any purpose just there to add the margin you want
normalItem
```

There is no element which allows to use margin. I just gave the idea of a custom drawer item which adds spacing. 

If you really need explicit margin. you will have to create your own `CustomDrawerItem` (as described in the README, the FAQ, and shown in the sample for some cases) and add this functionality.

**Comment by MorZada** [comment]
Ok, thank you, I'll try that.

**Comment by MorZada** [comment]
I created a CustomPrimaryDrawerItem  but when I set the margin it has no effect (with background color it worked) :

[public class CustomPrimaryDrawerItem extends PrimaryDrawerItem {

    private int marginTop;

    public CustomPrimaryDrawerItem withMarginTop(int marginTop) {
        this.marginTop = marginTop;
        return this;
    }

    @Override
    public void bindView(ViewHolder holder, List payloads) {
        super.bindView(holder, payloads);

        holder.itemView.setPadding(200, marginTop, 200, 200);
    }
}

And I call it on MainActivity:

CustomPrimaryDrawerItem item3 = new CustomPrimaryDrawerItem().withMarginTop(300);

and I can't add .withIcon(R.drawable.sidebar_2) and .withName(R.string.drawer_item_start_ride);

What am I doing wrong?

**Comment by MorZada** [comment]
This is what I'm trying to do:

![drawer](https://user-images.githubusercontent.com/8402421/36060975-0e756464-0e5c-11e8-8137-0e93f8a05e55.png)

**Comment by mikepenz** [comment]
@MorZada you want to center your items? 

That was done in the past like this: https://github.com/mikepenz/MaterialDrawer/issues/702#issuecomment-144160543

**Comment by MorZada** [comment]
Great, thank you, I'll check that.
And thanks for a great library and a quick answers :)
