### ISSUE TITLE
Load image using Picasso into a custom header

### ISSUE THREAD

**Issue by asknask** [mikepenz/MaterialDrawer#2215]
## About this issue

Suppose I have a Drawer with a custom header that contains an ImageView. This ImageView is in R.layout.layout_navigation_header.

It is being added to the Drawer using the following code:

`Drawer navigationDrawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withTranslucentStatusBar(true)
                .withHeader(R.layout.layout_navigation_header)
                .build();`

How do I set the image in that ImageView?

## Details
- Library version: 6.0.4
- Support library version: 27.0.2

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L65

**Comment by mikepenz** [comment]
Oh sorry. just saw you don't use the `AccountHeader` but a header

So head over here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L285

**Comment by mikepenz** [comment]
It is absolutely right to answer questions on gitHub. The issue section is perfectly fine for that :)

And there is the chance that some contributors or other people answer faster than me (saving some time, as I might be busy sometime) 

And if you have questions or if you find answers to questions. open a PR and improve the FAQ. 

and always check the javadoc before, and the public api's, as they should clarify most of the questions ;)
