### ISSUE TITLE
Is it possible to control the Drawer from a fragment if the drawer is initialized inside the host activity?

### ISSUE THREAD

**Issue by asknask** [mikepenz/MaterialDrawer#2218]
Using the latest version of the library.

Suppose my Drawer is in a FragmentHostActivity. Would it be possible to toggle the drawer visibility using a button inside the fragment?

**Comment by mikepenz** [comment]
@asknask sure. but that has nothing to do with this library. 

You simply have to create the option that the fragment can trigger some functionality on the activity. 

like so:
https://stackoverflow.com/questions/46150954/call-method-from-fragment-to-activity

there are many many other stackoverflow questions regarding the same topic
