### ISSUE TITLE
How can i add linear layout with a textview as a drawer item to drawer? question

### ISSUE THREAD

**Issue by ilkeryasinaksoy** [mikepenz/MaterialDrawer#2219]
Hi, i am very very beginner for android.
My question is: how can i add linear layout with a textview (or expandable listview) as a drawer item to drawer?

Example like this:

`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:orientation="vertical"
    android:background="#f4f4f4" > 
            <ExpandableListView
                android:id="@+id/lvExp"
                android:layout_height="match_parent"
                android:layout_width="match_parent"/>    
</LinearLayout>`

or like this:

`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:orientation="vertical"
    android:background="#f4f4f4" > 
            <TextView
                android:id="@+id/textView"
                android:layout_height="match_parent"
                android:layout_width="match_parent"/>    
</LinearLayout>`

Sorry my bad English, please help me this issue, thanks.

**Comment by mikepenz** [comment]
@ilkeryasinaksoy follow the FAQ and the already showed samples on how to create a `CustomDrawerItem`
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md
