### ISSUE TITLE
Wrong icon size?

### ISSUE THREAD

**Issue by maxkrass** [mikepenz/MaterialDrawer#222]
I currently use the 24dp icon from Google's material design icon repository, just like the guidelines recommend. In the screenshot, the icon behind the drawer in the right are the same (they are the same files) as the ones next to the drawer elements on the left but they appear much smaller. Any idea how to fix the size so the icon in the drawer appear in their full (bigger) size?
![screenshot_2015-04-14-09-23-29](https://cloud.githubusercontent.com/assets/11082866/7138915/d6bd47dc-e288-11e4-9359-d1c8b98f7f2e.png)

**Comment by mikepenz** [comment]
@maxkrass do you use the PrimaryDrawerItem?

The ImageView of the PrimaryDrawerItem has a size of 24x24dp. Following the Android Guidelines the Images are 24dp in total but if you just create the images itself they are 22dp of the image + 1dp of padding. So probably the images have the wrong size?


Here's the imageView:
![bildschirmfoto 2015-04-14 um 19 57 53](https://cloud.githubusercontent.com/assets/1476232/7143591/b9824a3e-e2e0-11e4-9ced-ded155a324e9.png)

**Comment by maxkrass** [comment]
@mikepenz I use the PrimaryDrawItem for the second to fourth item and the SecondaryDrawItem for the last item.

If I get this right, then the image for the PrimaryDrawItem can have a height of 24dp and a width of 12dp? Therefore my icons are scaled to 12x12dp?

What size do the images have to be then so that they appear as 24x24dp?

**Comment by mikepenz** [comment]
@maxkrass so then this is the issue. The IconSize of the SeconaryDrawerItems is lower then the 24dp of the PrimaryDrawerItem

Nope :D You have to take a second look at the code above ;)

it states RIGHT and END (This is the same :D just RTL stuff) (48-24 = 24)
and TOP and Bottom  (48-12-12=24)

So the icon is 24x24dp

**Comment by maxkrass** [comment]
@mikepenz I see it now! Couldn't wrap my head around it first : D Thank you anyways.

**Comment by mikepenz** [comment]
@maxkrass yeah is a bit of a uncommon definition and position. but it's the specification of the Google Material Design Guidelines
