### ISSUE TITLE
How Can I change menu button color the top left corner ? 

### ISSUE THREAD

**Issue by raniputri** [mikepenz/MaterialDrawer#2220]
I want to change the color of the menu button that begins white to be the color I want
how can I change the menu button? please answer this question  
<img width="328" alt="ss" src="https://user-images.githubusercontent.com/22884934/36245036-9609612a-125b-11e8-84a0-984e281575bd.png">

**Comment by mikepenz** [comment]
That's the `ActionBarDrawerToggle` and it is usually colored with a proper toolbar theme. Which has nothing to do with the `MaterialDrawer` ;)
