### ISSUE TITLE
add radio group button in the Navigation drawer

### ISSUE THREAD

**Issue by sushantchopra94** [mikepenz/MaterialDrawer#2221]
I want to add a dynamically sized radio group in the primary Navigation drawer and I can't find the way.
Please help! its urgent.

**Comment by mikepenz** [comment]
@sushantchopra94 you can write your own `customDrawerItem`

**Comment by sushantchopra94** [comment]
isn't there something like like toggle and switch in the library for radioGroup @mikepenz

**Comment by mikepenz** [comment]
No, as  something like this is not really a default behaviour. it is possible to implement yes. 

But no item is provided, and it will have to be implemented from the dev needing it.

**Comment by mikepenz** [comment]
You can have a look at the item sample in the `FastAdapter` with a radio group for example too.

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/RadioButtonSampleActivity.java

**Comment by dsourav** [comment]
i want add radio button like 
distance short ,medium, long in the drawer how to do that
