### ISSUE TITLE
Keep drawer open on profile change

### ISSUE THREAD

**Issue by soenkegissel** [mikepenz/MaterialDrawer#2222]
Is it possible to keep the drawer open on profile change in AccountHeader?
If I call openDrawer() at the end of withOnAccountHeaderListener it has no effect. Possibly isDrawerOpen boolean is still true at this point.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L432

**Comment by soenkegissel** [comment]
This product is wonderful!
