### ISSUE TITLE
White Navigation bar below

### ISSUE THREAD

**Issue by mariocasereses** [mikepenz/MaterialDrawer#2223]
## About this issue

- A White bar below appears in the screen activity. I want to remove it.
![screenshot_20180217-144716](https://user-images.githubusercontent.com/17214099/36338734-d5c9e860-13f1-11e8-92e5-26e990c432d0.png)

## Details
    android studiuo 3.0.1
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.project.dpwhrbia"
        minSdkVersion 21
        targetSdkVersion 26
    }
}

dependencies {
    implementation("com.mikepenz:materialdrawer:6.0.6@aar") {
        transitive = true
    }

    implementation 'com.android.support:appcompat-v7:26.1.0'

**Comment by mikepenz** [comment]
@mariocasereses you most likely have somewhere a `fitsSystemWindows` too much in your layout. 

The issue is not related to the library itself. 

As you can see in the support libs.

**Comment by mikepenz** [comment]
Close until further details are added
