### ISSUE TITLE
Badge update issue

### ISSUE THREAD

**Issue by shvetsmax** [mikepenz/MaterialDrawer#2224]
## About this issue

Hello!
I encountered the problem of updating the Badge. 
You can set the text when creating Drawer without problems. But when I try to update it, the following happens: Badge updates the value only after a few drawer open / close actions. 
It is updated correctly, no errors are detected.
I've found a workaround: after
updateBadge (itemId, "123") 
I call the method setSelection (-1);
At once the desired value is set.

## Details
- 6.0.5 -  Used library version
- 26.0.1 - Used support library version
- 3.0.1 - Used gradle build tools version
- Idea Ultimate 2017.3.4 - Used tooling / Android Studio version

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@shvetsmax you update the drawer on the main thread? 
You made sure the identifier used matches? 
The sample sets the badge and it works in there: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L211


Also the `updateBadge` method takes a `StringHolder` not a `String`
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L665
