### ISSUE TITLE
How to get the Name of DrawerItem

### ISSUE THREAD

**Issue by soenkegissel** [mikepenz/MaterialDrawer#2226]
Going crazy getting the name of an item shown in the drawer.
My approach from existing 2015 and 2016 issues:
IDrawerItem item = drawer.getDrawerItem(drawer.getCurrentSelection());
item.getName()        ----- NOT FOUND ANYMORE.

Found out if I use PrimaryDrawerItem .getName() works.
But I have different types of Items in Drawer.

**Comment by afarber** [comment]
You could always add the name as a tag...

**Comment by mikepenz** [comment]
@soenkegissel well the `IDrawerItem` is an interface. 

```java
if(item instanceof PrimaryDrawerItem) {
    ((PrimaryDrawerItem) item).getName();
}
```

**Comment by soenkegissel** [comment]
Allright - I gave the drawerItem a tag.

IDrawerItem item = drawer.getDrawerItem(drawer.getCurrentSelection());
if(item != null)
        Log.d(TAG, "Toolbar subTitle: "+ (CharSequence) item.getTag());

This returns "Toolbar subTitle: 2131562033"

**Comment by soenkegissel** [comment]
Did it like this:
getResources().getString((Integer) item.getTag()) because tag is object filled with R.string in my case.
**Thank you very much!**
