### ISSUE TITLE
withIsExpanded doesn't work as expected?

### ISSUE THREAD

**Issue by mtrakal** [mikepenz/MaterialDrawer#2227]
## About this issue
```
new ExpandableDrawerItem()
                    .withName("Open something (DEV)")
                    .withIsExpanded(true)
                    .withSubItems(OpenSomethingMenu.getItems(mMainActivity))
                    .withIconColorRes(R.color.md_red_600)
                    .withIcon(IconSZ.moon_truckcementmixer)
                    .withTextColorRes(NAVIGATION_MENU_TEXT_COLOR)
                    .withSelectable(false);
```

`withIsExpanded` I expect that will expand item menu, but it only change icon on end expanded/collapsed icon, but it doesn't expand menu. So after you must click 2 times to expand menu.

Expected:
when set `withIsExpanded` menu will be expanded by default after open Navigation drawer.

## Details
- [6.0.6] Used library version
- [27.0.2 ] Used support library version
- [ 3.2.0-alpha03] Used gradle build tools version
- [ AS 3.2 canary 3] Used tooling / Android Studio version
- [ a lot of] Other used libraries, potential conflicting libraries

**Comment by mikepenz** [comment]
@mtrakal that is correct behaviour. you will have to use the `expand` method to expand it. 

Just setting `withIsExpanded` will have no effect. 



See:

https://github.com/mikepenz/MaterialDrawer/issues/2092
https://github.com/mikepenz/MaterialDrawer/issues/2128

**Comment by mtrakal** [comment]
ouch, sorry for open a new issue. 
Thanks a lot, you are best 👍

**Comment by mikepenz** [comment]
@mtrakal no worries :) 

It's probably one of the more less covered topics. We might need some additional info in the README about that. or some cross reference to the FastAdapter docu. 

Or a FAQ article :D 

I am open for improvements or PRs enhancing documentation ;)
