### ISSUE TITLE
Mini Drawer enhancement

### ISSUE THREAD

**Issue by johnny68** [mikepenz/MaterialDrawer#2228]
Can the mini drawer be moved on the other edges of the screen ?
Like right, bottom ?
I want to use the mini drawer from the bottom and without the account header.

**Comment by mikepenz** [comment]
@johnny68 well you place it's view. but you won't be able to use it with the `MaterialDrawer` then

**Comment by johnny68** [comment]
Can you elaborate further please ?

**Comment by mikepenz** [comment]
the `slidingPaneLayout` and the `crossfader` is LTR left only, and with some luck RTL right too. 

But you can not specify it's side.
