### ISSUE TITLE
If you inflate menu items from a menu, how do you enable icon tinting on the items?

### ISSUE THREAD

**Issue by dphillipsprosper** [mikepenz/MaterialDrawer#2229]
## About this issue

I'm trying to convert over to your library from the NavigationView in the Support Library b/c I need a footer view. I've gotten it up and running, but when I inflate my items from a menu, the icons don't change color when selected.

I've seen from searching the issues that you can make the icon tinting happen if you create the items programatically. Is there a way for me to set this value on the items if I inflate them from a menu.xml?

## Details
Library version - 6.0.6
Support library version - 27.0.2
Build tools version - 27.0.3
Android Studio version - 3.0.1

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@dphillipsprosper you can't the menu xml does not allow any custom flags. 

It's recommended to use the library programmatically if you need more than this

**Comment by dphillipsprosper** [comment]
Sounds good. Just making sure I wasn't missing anything.
