### ISSUE TITLE
HeaderView dragable

### ISSUE THREAD

**Issue by Cilenco** [mikepenz/MaterialDrawer#2230]
```
FastAdapter<IDrawerItem> adapter = new FastAdapter<>();
adapter.withAllowDeselection(false);
adapter.withSelectable(true);

builder.withAdapter(adapter);
builder.withHeader(R.layout.nav_header);
Drawer drawer = builder.build();

//...

RecyclerView rcv = drawer.getRecyclerView();

SimpleDragCallback touchCallback = new SimpleDragCallback(this);
ItemTouchHelper touchHelper = new ItemTouchHelper(touchCallback);
touchHelper.attachToRecyclerView(rcv);
```

When I setup the drawer like this it it possible to drag the header view. Since we have no method like `withHeaderDragable` we can not modify this behavior. In general I think header should not be dragable so it would be great to have this option or disable header dragging completely.

Version: 6.0.2

**Comment by mikepenz** [comment]
Which header do you mean?

**Comment by Cilenco** [comment]
The header I can add to the drawer through `withHeader(leyoutRes)`.
I edited the code above.

**Comment by mikepenz** [comment]
@Cilenco you want the header to prevent the `DrawerLayout` from moving? 

I am not very sure about the usecase or what you want to achieve.

**Comment by Cilenco** [comment]
No. With the setup from above the user is able to reorder all drawer items unless I call `setDragable(false)` on them. For this I created my own DrawerItems which implement `IDraggable`.

Since I have to set the header as view or layout resource and there is no `HeaderDrawerItem `I can not call `setDragable` for the header. This results in a header view with is dragable but I want to prevent this.

Sorry for the obscurity.

**Comment by mikepenz** [comment]
Basically `DrawerBuilder.withHeader` only does the following:
https://github.com/mikepenz/MaterialDrawer/blob/b903da90c60ae46cc122a3e319112098fa596141/library/src/main/java/com/mikepenz/materialdrawer/DrawerUtils.java#L236
(The same for `Drawer.setHeader` https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L336)

So in the end you can overwrite this item (the `ContainerDrawerItem`) and add it yourself in the same manner like here:
drawer.getHeaderAdapter().add(new ContainerDrawerItem().withView(drawer.mHeaderView).withHeight(drawer.mHeiderHeight).withDivider(drawer.mHeaderDivider).withViewPosition(ContainerDrawerItem.Position.TOP));

and adjust the padding if necessary:
https://github.com/mikepenz/MaterialDrawer/blob/b903da90c60ae46cc122a3e319112098fa596141/library/src/main/java/com/mikepenz/materialdrawer/DrawerUtils.java#L247

**Comment by Cilenco** [comment]
Thank you that worked great! I did it like this in case someone has the same problem:
First you have to create a custom HeaderItem

```
public class HeaderItem extends ContainerDrawerItem implements IDraggable<HeaderItem, IItem> {
    private boolean draggable;

    public HeaderItem() {
        withViewPosition(TOP);
        draggable = false;
    }

    @Override
    public boolean isDraggable() {
        return draggable;
    }

    @Override
    public HeaderItem withIsDraggable(boolean draggable) {
        this.draggable = draggable;
        return this;
    }
}
```

Then you have to override the `withHeader(...)` method from the `DrawerBuilder` like this:

```
public static class Builder extends DrawerBuilder {

    private Activity activity;
    private View headerView;

    public Builder(@NonNull AppCompatActivity activity) {
        super(activity);
        this.activity = activity;
    }

    @Override
    public DrawerBuilder withHeader(int headerViewRes) {
        LayoutInflater inflater = activity.getLayoutInflater();
        headerView = inflater.inflate(headerViewRes, null, false);

        return this;
    }

    @Override
    public CustomDrawer build() {
        FastAdapter<IDrawerItem> adapter = new FastAdapter<>();
        adapter.withAllowDeselection(false);
        adapter.withSelectable(true);

        withAdapter(adapter);
        super.build();

        CustomDrawer drawer = new CustomDrawer(this);

        if(headerView != null) {
            HeaderItem header = new HeaderItem();
            header.withView(headerView);

            drawer.getHeaderAdapter().add(header);
        }

        RecyclerView rcv = drawer.getRecyclerView();
        rcv.setPadding(rcv.getPaddingLeft(), 0, rcv.getPaddingRight(), rcv.getPaddingBottom());

        mHeaderView = headerView; // Important if you want to find Views in the HeaderView
        
        SimpleDragCallback touchCallback = new SimpleDragCallback(...);
        ItemTouchHelper touchHelper = new ItemTouchHelper(touchCallback);
        touchHelper.attachToRecyclerView(rcv);

        return drawer;
    }
}
```

If you have any ideas how to improve this code (especially I'm not sure about the build method) please drop a comment here.

**Comment by mikepenz** [comment]
Marked it as good to know :) thanks for adding all the details here ;)
