### ISSUE TITLE
Remove StickyDrawerItems top divider

### ISSUE THREAD

**Issue by N-i-p-o-l** [mikepenz/MaterialDrawer#2231]
1. How to remove StickyDrawerItems top divider from menu or change color of this divider only?

**Comment by N-i-p-o-l** [comment]
2. How to change color of drawer menu main icon?
http://prntscr.com/ii90wp

Problem is if I add
` <color name="material_drawer_accent">#FF4081</color>`
project wont compile (Error:(115, 5) error: :color>.)

**Comment by mikepenz** [comment]
@N-i-p-o-l where did you add the color? in your color.xml? 


The divider can be toggled with:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L714

**Comment by N-i-p-o-l** [comment]
1. I add to builder
```
.withStickyFooterDivider(false)
 .withFooterDivider(false)
```
but has no effect http://prntscr.com/iilwyi

2. Yes, my mistake i add `<color name="material_drawer_accent">@color/colorPrimary</color>` not in color.xml. But then i add correctly in color.xml this lines:
```
<color name="material_drawer_primary">#2196F3</color>
<color name="material_drawer_primary_dark">#1976D2</color>
<color name="material_drawer_primary_light">#BBDEFB</color>
<color name="material_drawer_accent">@color/colorPrimary</color>
``` (colorPrimary is white)
But problem is drawer menu icon is same pink (this my colorAccent in project).
http://prntscr.com/iilx1t

I want white color for drawer menu icon. How to change color of drawer icon and its area?

**Comment by mikepenz** [comment]
@N-i-p-o-l if you want icon tinting you have to enable it on the specific drawerItem. (usually tinting is not enabled and the icon will have the color as it's drawable)

**Comment by N-i-p-o-l** [comment]
I change all colors, but navigation drawer menu icon area (where menu drawer icon inside) is still as my colorAccent theme. I want to navigaation drawer menu icon area use custom color. `material_drawer_accent` color in colors.xml doesnt help. Have any options to change this color without change main coloraccent color in my theme?

**Comment by N-i-p-o-l** [comment]
https://prnt.sc/ii90wp
Current: icon - black, area - pink (pink is style colorAccent)
I want: icon - black, area - white

**Comment by N-i-p-o-l** [comment]
Ok, I changed colorAccent main color, problem is solved for now. But problem #1 `.withStickyFooterDivider(false)` does not disappear http://prntscr.com/iilwyi

**Comment by N-i-p-o-l** [comment]
All problems solved. Thanks a lot)
