### ISSUE TITLE
OnDrawerClosed, OnDrawerOpened, OnDrawerSliding

### ISSUE THREAD

**Issue by ZigZapps** [mikepenz/MaterialDrawer#2232]
Hi Mike, thanks for this awesome drawer library.
does it support these 3 listeners (OnDrawerClosed, OnDrawerOpened, OnDrawerSliding)? is there any way that I can access them?

**Comment by mikepenz** [comment]
Hi @ZigZapps. Thank you very much. 

Sure just attach a listener:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1142
