### ISSUE TITLE
Drawer.getCurrentSelection() returns Active profile's id

### ISSUE THREAD

**Issue by Quix0tic** [mikepenz/MaterialDrawer#2234]
## Description
This is a really strange bug.

I have a drawer with a header which contains many profiles.
When I long-press one row on the profiles adapter, I delete a profile and update the header with this function:

``` kotlin
private fun updateDrawerHeader() {
    val NEW_ACCOUNT_ROW = ProfileSettingDrawerItem().withName("New Account").withIcon(R.drawable.fab_add).withIconTinted(true).withIdentifier(0L)
    headerResult.clear()
    headerResult.profiles = Profile.getIProfiles() + NEW_ACCOUNT_ROW //Profile.getIProfiles() fetches all profiles from database
    headerResult.setActiveProfile(Account.with(this).user,true) //Account.with(this).user fetches active profile from shared preferences
}
```

After the profile is deleted, the header and the list are updated, but it doens't switch back to the base navigation list.

At this point, if I call 
``` kotlin
Log.d("MainActivity", "Drawer selection: ${drawerView.currentSelection}")
Log.d("MainActivity", "Drawer position: ${drawerView.currentSelectedPosition}")
Log.d("MainActivity", "Profile selection: ${headerResult.activeProfile.identifier}")
```
I get 
```
Drawer selection: 4011914
Drawer position: 1
Profile selection: 4011914 // Note that this profile is the first in the list
```

It prints the id and the position of the active profile, but I want the position and the id of the selected navigation item for then updating fragments accordingly.

Some normal output would be
```
Drawer selection: 2131296382 // This is coming from the app's resources
Drawer position: 6
Profile selection: 4011914
```

## Details
Version `6.0.6` 
Support library version `26.1.0`

**Comment by mikepenz** [comment]
@Quix0tic very interesting :D funnily nobody ever had such a case :D

It is a result of the fact that the library uses the same `RecyclerView` (and adapter) for the first main list and the second list, (allowing a nice cross animation on replacing the items) 

The logic getting the current position does not really check in which "state" we are (so normal list vs. profile list) it simply gives the selected position / selected identifier. Which is correct according to this method's logic. 

For your case, would it be possible that you remember which active element you had?

(You could theoretically get the original items: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L992 and check for their selection but that would be not very nice :D )

**Comment by Quix0tic** [comment]
I figured out a way that looks like it's working:

``` kotlin

private var selectedItem: Long = -1

override fun onCreate(savedInstanceState: Bundle?) {
    drawerView = DrawerBuilder()
                .withActivity(this)
                .withSelectedItem(selectedItem)
                .withOnDrawerItemClickListener { _, _, drawerItem -> selectedItem = drawerItem.identier }
                .build()
    }
}

override fun onSaveInstanceState(outState: Bundle?) {
    outState?.putLong(BUNDLE_CURRENT_SELECTION, selectedItem)
    super.onSaveInstanceState(outState)
}

```

**Comment by mikepenz** [comment]
Thank you very much
