### ISSUE TITLE
Get event open AccountHeader

### ISSUE THREAD

**Issue by wiltonbarros** [mikepenz/MaterialDrawer#2235]
Hi, how can i get event when the account header is showing?
Thanks.

**Comment by mikepenz** [comment]
There is an event allowing you to check if the user clicks on the toggle:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L420

You can also check for it's state here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L110
