### ISSUE TITLE
Delete Item Drawer

### ISSUE THREAD

**Issue by bsjoker** [mikepenz/MaterialDrawer#2239]
Hello Mike!
I have custom DrawerItem with imageView. I can't understand: how can I remove item drawer when I clicked to Image. Look this:

ImageDrawerItem.java:
public class ImageDrawerItem extends BaseDescribeableDrawerItem<ImageDrawerItem, ImageDrawerItem.ViewHolder> {

    @Override
    public int getType() {
        return R.id.material_drawer_item_image;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.material_drawer_item_image;
    }

    @Override
    public void bindView(final ImageDrawerItem.ViewHolder viewHolder, List payloads) {
        super.bindView(viewHolder, payloads);

        Context ctx = viewHolder.itemView.getContext();

        //bind the basic view parts
        bindViewHelper(viewHolder);
        viewHolder.imageView.setImageResource(android.R.drawable.ic_delete);//setOnCheckedChangeListener(null);
        viewHolder.imageView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                int id = viewHolder.itemView.getId();

                Toast.makeText(ctx, String.valueOf(id), Toast.LENGTH_LONG).show();
                //Need to delete current Item????
            }
        });
        viewHolder.getItemId();

        //add a onDrawerItemClickListener here to be able to check / uncheck if the drawerItem can't be selected
        withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
            @Override
            public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {

                return false;
            }
        });

        //call the onPostBindView method to trigger post bind view actions (like the listener to modify the item if required)
        onPostBindView(this, viewHolder.itemView);
    }

    @Override
    public ViewHolder getViewHolder(View v) {
        return new ViewHolder(v);
    }

    public static class ViewHolder extends BaseViewHolder {
        private ImageView imageView;

        private ViewHolder(View view) {
            super(view);
            this.imageView = (ImageView) view.findViewById(R.id.material_drawer_iv);
        }
    }
}

Activity.java:
...
    public void setUpDrawer(){
        ImageDrawerItem item1 = new ImageDrawerItem().withIdentifier(1).withName(R.string.screen_name_news)
                .withIcon(GoogleMaterial.Icon.gmd_home);
        ImageDrawerItem item2 = new ImageDrawerItem().withIdentifier(2).withName(R.string.screen_name_my_posts)
                .withIcon(GoogleMaterial.Icon.gmd_list);
        PrimaryDrawerItem item3 = new PrimaryDrawerItem().withIdentifier(3).withName(R.string.screen_name_settings)
                .withIcon(GoogleMaterial.Icon.gmd_settings);
        PrimaryDrawerItem item4 = new PrimaryDrawerItem().withIdentifier(4).withName(R.string.screen_name_members)
                .withIcon(GoogleMaterial.Icon.gmd_people);
        PrimaryDrawerItem item5 = new PrimaryDrawerItem().withIdentifier(5).withName(R.string.screen_name_topics)
                .withIcon(GoogleMaterial.Icon.gmd_record_voice_over);
        PrimaryDrawerItem item6 = new PrimaryDrawerItem().withIdentifier(6).withName(R.string.screen_name_info)
                .withIcon(GoogleMaterial.Icon.gmd_info);
        PrimaryDrawerItem item7 = new PrimaryDrawerItem().withIdentifier(7).withName(R.string.screen_name_rules)
                .withIcon(GoogleMaterial.Icon.gmd_assignment);

        Set<String> cities = new HashSet<>();
        cities = PreferencesHelper.getSharedPreferences().getStringSet("cities", null);

        String[] cityArray = {};

        cityArray = cities.toArray(new String[cities.size()]);
        Log.d(TAG, "Text: " + cityArray[0] + " " + cityArray[1]);

        mAccountHeader = new AccountHeaderBuilder()
                .withActivity(this)
                .build();
        mDrawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withTranslucentStatusBar(true)
                .withActionBarDrawerToggle(true)
                .withAccountHeader(mAccountHeader)

                .addDrawerItems(item1, item2)
                .build();

        mDrawer.addItem(item3);
    }
....

Help me, pls))

**Comment by fastcoreapp** [comment]
It is not deleted

**Comment by mikepenz** [comment]
@bsjoker does not really seem to be related to the MaterialDrawer, looks like a general coding question. 

As if you have the reference to the drawer (which you haven't in the item) then you can call the delete method accordingly. 

You might also wanna do a quick look in the `FastAdapter` documentation and sample app as it has helpers to attach a click listener to a view inside an item (without doing this inside the item, which is bad)

**Comment by mikepenz** [comment]
Close until further details are provided
