### ISSUE TITLE
Changes in Glide methods

### ISSUE THREAD

**Issue by Philipp97714** [mikepenz/MaterialDrawer#2243]
https://github.com/mikepenz/MaterialDrawer/blob/6c7c52d6090ff9bfb04f12fdc8829440754e5739/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java#L48

The given example doesn't compile. The Line must be
` Glide.with(imageView.getContext()).clear(imageView);`
instead.

`Glide.with(imageView.getContext()).load(uri).placeholder(placeholder).into(imageView);` is also wrong.

https://bumptech.github.io/glide/doc/migrating.html

**Comment by mikepenz** [comment]
@Philipp97714 this sample app still uses glide v3. I see no need to update it as glide v3 works great for the sample. 

The `DrawerImageLoader` is written in such a generic way so any image loader can be used. 

You might want to open a PR to add sample code for glide v4 though.

**Comment by mikepenz** [comment]
Close. Please report back if you have an update.
