### ISSUE TITLE
Activity widgets behind notification bar

### ISSUE THREAD

**Issue by Philipp97714** [mikepenz/MaterialDrawer#2244]
I'm using Google Smart Lock for passwords in my app. After the user is signed in, I add the Drawer to my UI. At the same time Goolge is showing a quick snackbar-like notification (seen here: https://developers.google.com/identity/smartlock-passwords/android/images/netflix-retrieve.png)

When I add build and add the drawer at the same time, the view with all widgets moves a little bit up and is on top of the notification bar.

I fixed it with adding the Drawer befor the login and fill it after login.

**Comment by mikepenz** [comment]
@Philipp97714 I think this is just a result out of the way a snackbar works. the snackbar is inflated in the view hierarchy. so is the `DrawerLayout` if you add the `DrawerLayout` while the snackbar is shown the view hierarchy moves around and will `move` up. 

This is somehow acceptable behaviour as this is how the `Snackbar` functions

**Comment by mikepenz** [comment]
Close. Please report back if you have an update.
