### ISSUE TITLE
Toggle button is getting clicked even after Selectable(false)

### ISSUE THREAD

**Issue by parmarravi** [mikepenz/MaterialDrawer#2245]
Hello Mike;

I want to turn off the toggle button  sliding animation when i  use this code ".withSelectable(false)". But right now the switch button is active .when clicked ...
Is it a bug? .
```
    .withIconColor(mContext.getResources().getColor(R.color.white))
                                    .withSubItems(new SecondarySwitchDrawerItem()
                                            .withName("hello world")
                                            .withSelectable(false)
                                            .withIconColor(mContext.getResources().getColor(R.color.black))
                                            .withIcon(FontAwesome.Icon.faw_lightbulb_o));

```

**Comment by mikepenz** [comment]
@parmarravi I think you mix it up with the `withSwitchEnabled()` call. 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/AbstractSwitchableDrawerItem.java

`withSelectable()` will only disable the selection of the item.
