### ISSUE TITLE
Is there a way to find out the expandable view name when we click on the respective sub items ?

### ISSUE THREAD

**Issue by parmarravi** [mikepenz/MaterialDrawer#2247]
Hi Mike , 

I am trying to figure out  the name of expandable view  when i click  subitems in it.How can i get it ?

**Comment by mikepenz** [comment]
The click listener gives you the child, and the child extends `ISubItem` which should have a `getParent()` method. This gives you the parent item. 

There is now `view` of the parent accessible, as it is not guaranteed that the parent view is currently bound

**Comment by parmarravi** [comment]
Hi Mike,

This is what i am trying and getting getParent() is null.
```
 .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() //this will enabled only when the item is clicked in navigation bar
                {
                    @Override
                    public boolean onItemClick(final View view, int position, final IDrawerItem drawerItem) {
                        if (drawerItem instanceof Nameable) {

                            String na = drawerItem.getParent().toString();
                            Log.e("na",na);
                            new ISubItem() {
                                @Override
                                public IItem getParent() {
                                    return null;
                                }

                                @Override
                                public Object withParent(IItem parent) {
                                    parent.getTag();
                                    return null;
                                }
                            };
                        }
                        return true;
                    }
                })
```

**Comment by mikepenz** [comment]
If the clicked item has a parent (so is an expandable child) then it should not be null.

Also I do not really understand what you do with the `new ISubItem()` implementation here?

**Comment by parmarravi** [comment]
I resolved the above issue by adding withTag and getTag .Thank you mike for such a amazing lib .
We are developing  Wifi based Smart Lights.
![28577644_2043013775726950_3924882535684447384_n](https://user-images.githubusercontent.com/7616089/37872386-4f32be90-3024-11e8-8509-cc0fc7e81d18.jpg)
