### ISSUE TITLE
arrow back

### ISSUE THREAD

**Issue by rudda** [mikepenz/MaterialDrawer#2250]
i used this follow code:
```java
result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false);
getSupportActionBar().setDisplayHomeAsUpEnabled(true);

```
but the arrow back only close and open the drawer .
I want witch the arrow finish the activity

**Comment by mikepenz** [comment]
You need both:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MultiDrawerActivity.java#L169

**Comment by wellbranding** [comment]
Not working. In fragments in particular. Spend a day trying to figure out. Why this issue exist?

**Comment by mikepenz** [comment]
@wimbervoets the `ActionbarDrawerToggle` is not directly managed by the drawer and default system behaviour + api's apply. 

Also you might want to ensure you hooked up the toolbar as the supportActionBar and provided the toolbar to the drawer if you want the hamburger icon.
