### ISSUE TITLE
How to get google account header?

### ISSUE THREAD

**Issue by DesigningKnights** [mikepenz/MaterialDrawer#2251]
So after lots of google searching , I've found out how to get the user's profile avatar photo, but does anyone know how to retrieve the background header from a profile?

**Comment by mikepenz** [comment]
@DesigningKnights I don't think this is related to this library. Managing and handling the information to your profiles is up to the developer. The MaterialDrawer simply provides the plain ui without any further logic assigned. 

If you want to adjust the `Header`s background. you can do this via it's `ImageView`
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L65
