### ISSUE TITLE
Fixed drawer

### ISSUE THREAD

**Issue by Nishikant-07** [mikepenz/MaterialDrawer#2252]
## I want to make drawer fixed to screen.

- I am making an app where drawer will stay open along with screen every time. I mean Drawer will not close.
![dashboard-15march 1](https://user-images.githubusercontent.com/17667302/37588137-5bdb24bc-2b87-11e8-8dc6-46af136ac5d9.jpg)

**Comment by mikepenz** [comment]
@Nishikant-07 then you should not use a `DrawerLayout`. Look at the `Embedded Drawer` sample showcasing how to embed the drawer layout view anywhere you like
