### ISSUE TITLE
can't change properties of Profile drawer item

### ISSUE THREAD

**Issue by saeedata** [mikepenz/MaterialDrawer#2253]
hi, 
by overwrite dimes.xml just updated properties of Primary And secondary Drawer Items and not any change in Profile Drawer Item 
I over write this dimens:

    <dimen name="material_drawer_item_profile">72dp</dimen>
    <dimen name="material_drawer_item_profile_icon">40dp</dimen>
    <dimen name="material_drawer_item_profile_icon_width">48dp</dimen>
    <dimen name="material_drawer_item_profile_icon_padding">16dp</dimen>
    <dimen name="material_drawer_item_profile_icon_padding_right">8dp</dimen>
    <dimen name="material_drawer_item_profile_text">14sp</dimen>
    <dimen name="material_drawer_item_profile_description">14sp</dimen>

what should i do?

thanks ;)

**Comment by mikepenz** [comment]
If you have a dimens.xml file with these values changed it should definitely result in a difference of the item, as these values are used. 

Alternatively you can overwrite the layout itself too (copy it to your project, and modify it to your needs) 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_profile.xml
