### ISSUE TITLE
Can I add an expandable group in this menu?

### ISSUE THREAD

**Issue by mytms** [mikepenz/MaterialDrawer#2258]
I love your library but I really need the ability to add one expandable group in the menu I would like to keep the rest as a single item. Is there anyway of doing this?

**Comment by mikepenz** [comment]
@mytms yes there is. 

See the sample it has many normal items, and some as expandable:

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L122
