### ISSUE TITLE
Error:Module version com.mikepenz.materialdrawer:library:2.7.9 depends on libraries but is not a library itself

### ISSUE THREAD

**Issue by yolapop** [mikepenz/MaterialDrawer#226]
This was on Android Studio.

**Comment by mikepenz** [comment]
@yolapop has to be an issue on your side. please check for this error on stackOverFlow or somewhere, but it's working for everyone else here.

**Comment by yolapop** [comment]
Ah yes, sorry :-(

**Comment by mikepenz** [comment]
@yolapop have you found the issue?

**Comment by yolapop** [comment]
I re-synced and it was okay. Probably it was my internet connection.
