### ISSUE TITLE
Remove SubItem of ExpandableDrawerItem

### ISSUE THREAD

**Issue by yatindeokar** [mikepenz/MaterialDrawer#2260]
I implement ExpandableDrawerItem like below .

```java
new ExpandableDrawerItem().withName("My Name List").withLevel(2)     
 .withSubItems(new SecondaryDrawerItem().withName("Name One").withLevel(3).withIdentifier(22))
.withSubItems(new SecondaryDrawerItem().withName("Name Two").withLevel(3).withIdentifier(23))
```

now i want to remove SubItem of ExpandableDrawerItem by specifying identifier, so i try to do it like below after .build() but it dosn't work . How Can i remove sub item.

```java
result.removeItem(22);
result.removeItem(23);
```

**Comment by mikepenz** [comment]
@yatindeokar `removeItem` can only remove an element if it's visible. (The same for `removeItemByPosition`)  if the expandable item is not visible it won't be removed.

You have to remove the child element from the parent, and then notify the `ExpandableExtension` via `notifyAdapterSubItemsChanged`. 

As an alternative there's the `SubItemUtil` which comes with a  `delete` function allowing you to remove x items by their identifier.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/utilities/SubItemUtil.java#L411

**Comment by mmrmartin** [comment]
Hi @mikepenz,

Can I call `notifyAdapterSubItemsChanged` when the parent item is not expanded (the elements are not shown), In my case, this call causes adding extra items into my drawer. It looks like I have a few last sub items twice after parents expansion.

The expansion check solve it for me but I'm now a bit confused with it ;-)
```
// Clear old sub items
int oldSubItemsCount = parentItem.getSubItems().size(); // in my case == 2
parentItem.getSubItems().clear();

// Insert new items
for(int i = 0; i < 4; i++) (
    SecondaryDrawerItem portalItem = new SecondaryDrawerItem()
            .withIdentifier(i)
            .withName("Item " + i)
            .withTag(ENTRY_TAG);
    parentItem.withSubItems(portalItem);
}

// Insert control items
// They have correct Identifiers
parentItem.withSubItems(ADD_ENTRY, MANAGE_ENTRIES);

// Notify about changes
if (parentItem.isExpanded()) { // Without this line I have some sub items twice
    mDrawer.getExpandableExtension().notifyAdapterSubItemsChanged(
            mDrawer.getPosition(parentItem), oldSubItemsCount);
}
```
