### ISSUE TITLE
Set disabled text color in styles for drawer item

### ISSUE THREAD

**Issue by N-i-p-o-l** [mikepenz/MaterialDrawer#2261]
## About this issue

How to set unique text color for disabled DrawerItem when use method withEnabled(false)?
I want set disabled text color in styles for material drawer like for selected as this:
`<item name="material_drawer_selected">@color/colorGrayBack</item>`

or how do this in code like this?
```
val drawerItem = drawer?.getDrawerItem(1)
drawerItem?.setTextColor(R.color.somecolor)
```

## Details
- [6.0.6] Used library version
- [27.0.1 ] Used support library version
- [3.1.0] Used gradle build tools version
- [3.1] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

**Comment by mikepenz** [comment]
The default items allow you to set the disabled text color:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDrawerItem.java#L134

**Comment by mikepenz** [comment]
The default attribute or color name for it is: `material_drawer_hint_text`

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDrawerItem.java#L287

**Comment by N-i-p-o-l** [comment]
thanks
