### ISSUE TITLE
withIsExpanded(true) Problems

### ISSUE THREAD

**Issue by mirza-alim-m** [mikepenz/MaterialDrawer#2262]
Since version 6.0.0, using withIsExpanded(true) makes problem.
- It doesn't expand from the beginning, and only shows arrow up. Or we can say, no child appears.
- When clicked, it eats menu below and never show again.

Here is my code:
`.addDrawerItems(
                        ExpandableDrawerItem().withName("Book").withIcon(FontAwesome.Icon.faw_book).withIsExpanded(true).withSubItems(
                                SecondaryDrawerItem().withIdentifier(11).withName("Book 1").withIcon(FontAwesome.Icon.faw_bookmark2).withSetSelected(true),
                                SecondaryDrawerItem().withIdentifier(12).withName("Book 2").withIcon(FontAwesome.Icon.faw_bookmark2)
                        ),
                        DividerDrawerItem(),
                        ExpandableDrawerItem().withName("Video").withIcon(FontAwesome.Icon.faw_youtube_square).withSubItems(
                                SecondaryDrawerItem().withIdentifier(21).withName("Video 1").withIcon(FontAwesome.Icon.faw_play_circle2).withIconColor(Color.GRAY).withTextColor(Color.GRAY),
                                SecondaryDrawerItem().withIdentifier(22).withName("Video 2").withIcon(FontAwesome.Icon.faw_play_circle2).withIconColor(Color.GRAY).withTextColor(Color.GRAY)
)`

**Comment by mikepenz** [comment]
@mirza-alim-m `withIsExpanded` will not automatically open it. it is just used by the library. 

Please use the provided methods to expand/collapse items.


- https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L267


Expand by position:
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.java#L425

**Comment by mdtuyen** [comment]
I have a similar problem, as you explain, the time you need to use expanded function to expand a certain item however, about the problem:

"When clicked, the menu below and never show again again."

How will it explain?

And if I want an item to expand then I have to go back to find its location after I created it, but I can't set it up immediately when I create it?
