### ISSUE TITLE
unique drawer item identifier

### ISSUE THREAD

**Issue by ivanessence** [mikepenz/MaterialDrawer#2264]
Details
[6.0.2] Used library version
[26.1.0] Used support library version
[27.0.3] Used gradle build tools version
[3.0.1] Used tooling / Android Studio version
Problem
I set drawerItems to navigation drawer from my SQLite database, for example it is List of objects and I set to drawer item object.name and object.color . 
Then I want to get Object on navigation drawer which corresponds to the object in my database. How can I do it? How can I set to the drawer item any unique identifier such as object id from my database?

**Comment by mikepenz** [comment]
generate a unique id of your item as long and apply it to the item. some sort of hashing or anything else. 

It is not really related to this library.

**Comment by ivanessence** [comment]
How can I do it? With library method with.identifier() ?

**Comment by mikepenz** [comment]
`withIdentifier()` set's the identifier as long to the item

**Comment by ivanessence** [comment]
But I tried it and when I used method getIdentifier() it returned me incorrect values such as -15, -18 but must returned another values 150, 1230

**Comment by ivanessence** [comment]
What I did wrong?

**Comment by ivanessence** [comment]
help :)

**Comment by ivanessence** [comment]
if I use drawerItem.withIdentifier(5) so when I will use  drawerItem.getIdentifier() it will return me 5, right?
