### ISSUE TITLE
MiniDrawer.withOnMiniDrawerItemClickListener() is not working in CrossfadeDrawerLayout.

### ISSUE THREAD

**Issue by DLeague9** [mikepenz/MaterialDrawer#2265]
I'm following the sample project  of CrossfadeDrawerLayout and implementing the MiniDrawer.withOnMiniDrawerItemClickListener() but its not working. here's my code

     result = new DrawerBuilder()
               .withActivity(this)
               .withToolbar(toolbar)
               .withDrawerLayout(R.layout.crossfade_drawer)
               .withDrawerWidthDp(72)
              .withGenerateMiniDrawer(true)
               .withAccountHeader(headerResult)
               .addDrawerItems(
              new PrimaryDrawerItem().withName(R.string.drawer_item_compact_header).withIcon(GoogleMaterial.Icon.gmd_brightness_5).withIdentifier(1),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_action_bar_drawer).withIcon(FontAwesome.Icon.faw_home).withBadge("22").withBadgeStyle(new BadgeStyle(Color.RED, Color.RED)).withIdentifier(2).withSelectable(false),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_multi_drawer).withIcon(FontAwesome.Icon.faw_gamepad).withIdentifier(3),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_non_translucent_status_drawer).withIcon(FontAwesome.Icon.faw_eye).withIdentifier(4),
                        new PrimaryDrawerItem().withDescription("A more complex sample").withName(R.string.drawer_item_advanced_drawer).withIcon(GoogleMaterial.Icon.gmd_adb).withIdentifier(5),
                        new SectionDrawerItem().withName(R.string.drawer_item_section_header),
                        new SecondaryDrawerItem().withName(R.string.drawer_item_open_source).withIcon(FontAwesome.Icon.faw_github),
                        new SecondaryDrawerItem().withName(R.string.drawer_item_contact).withIcon(GoogleMaterial.Icon.gmd_format_color_fill).withTag("Bullhorn")
                ) 
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        if (drawerItem instanceof Nameable) {
                            Toast.makeText(MainActivity.this, ((Nameable) drawerItem).getName().getText(MainActivity.this), Toast.LENGTH_SHORT).show();
                        }
                        return false;
                    }
                })
                .withSavedInstance(savedInstanceState)
                .withShowDrawerOnFirstLaunch(true)
                .build();
        crossfadeDrawerLayout = (CrossfadeDrawerLayout) result.getDrawerLayout();
        crossfadeDrawerLayout.setMaxWidthPx(DrawerUIUtils.getOptimalDrawerWidth(this));
        final MiniDrawer  miniResult = result.getMiniDrawer().withIncludeSecondaryDrawerItems(true);
        miniResult.withOnMiniDrawerItemOnClickListener(new OnClickListener<IDrawerItem>() {
            @Override
            public boolean onClick(@Nullable View v, IAdapter<IDrawerItem> adapter, IDrawerItem item, int position) {
                if (item instanceof Nameable) {
                    item.withSelectable(true);
                    Toast.makeText(MainActivity.this, position +"", Toast.LENGTH_SHORT).show();
                }
                return false;
            }
        });
        View view = miniResult.build(this);
        view.setBackgroundColor(UIUtils.getThemeColorFromAttrOrRes(this, 
        com.mikepenz.materialdrawer.R.attr.material_drawer_background, 
        com.mikepenz.materialdrawer.R.color.material_drawer_background));
        crossfadeDrawerLayout.getSmallView().addView(view, ViewGroup.LayoutParams.MATCH_PARENT,                             
        ViewGroup.LayoutParams.MATCH_PARENT);`

Kindly guide me if i'm missing something. Thanks

**Comment by mikepenz** [comment]
Can you please be a bit more precise. What exaclty is not working?
Which version of the lib do you use, ...
