### ISSUE TITLE
Set normal icons size for sticky drawer items

### ISSUE THREAD

**Issue by N-i-p-o-l** [mikepenz/MaterialDrawer#2266]
How to set normal icon size for sticky drawer items? Size like simple primary drawer item
http://prntscr.com/j0l821

How to fix this? Please help

**Comment by mikepenz** [comment]
Seems you provided a `SecondaryDrawerItem` as sticky item and not a `PrimaryDrawerItem`

**Comment by ihewro** [comment]
thx ,too
