### ISSUE TITLE
Logo icon cutting at the bottom

### ISSUE THREAD

**Issue by N-i-p-o-l** [mikepenz/MaterialDrawer#2267]
Earlier when background was dark blue, logo icon cutting at the bottom was not noticeable. But now what we have now you can see on the screenshot (background is grey):
https://prnt.sc/j0l9sl

How to fix this? Please help

**Comment by mikepenz** [comment]
the provided images should be square.

**Comment by mikepenz** [comment]
hmm it seems like not the logo is cut, but simply the shadow is clipped

**Comment by N-i-p-o-l** [comment]
I open material_drawer_header.xml and see this:
http://prntscr.com/j5y119
Is it normal?

**Comment by mikepenz** [comment]
Let's say it is a problem which nobody else has seen yet. 

I would be happy to see a PR with a fix for this. Currently there are no plans (as I am super flooded with work) from my side to fix this

**Comment by N-i-p-o-l** [comment]
https://github.com/mikepenz/MaterialDrawer/pull/2300
