### ISSUE TITLE
Remove StickyFooter right and left margin

### ISSUE THREAD

**Issue by H03in** [mikepenz/MaterialDrawer#2270]
Hi there
tanks for amazing library
i cant remove the left and right padding or margin on sticky footer

android version : 6
library version : 5.9.4

**Comment by mikepenz** [comment]
If you want to change the look of an item you have to implement your own `CustomDrawerItem` 

see the FAQ or see the sample for more details

**Comment by H03in** [comment]
yes i done this by extending AbstractDrawerItem but still has padding

**Comment by mikepenz** [comment]
Can you post a screenshot please?

**Comment by H03in** [comment]
of course

**Comment by H03in** [comment]
yes of course 

CustomItem : 
![1](https://user-images.githubusercontent.com/12210646/38704181-c0f9e888-3eba-11e8-93ab-a2509688e0a6.jpg)
 
CustomItem layout
![2](https://user-images.githubusercontent.com/12210646/38704273-0501b524-3ebb-11e8-939a-081ec7e823f8.png)

add to drawer : 
![3](https://user-images.githubusercontent.com/12210646/38704385-627880f2-3ebb-11e8-8e36-f835015d1d5c.png)

**Comment by H03in** [comment]
CPIView component does not have any padding or margin, i used a simple imageview too, and still has margin

**Comment by H03in** [comment]
hi penz
did you check my code?
is there any thing wrong with that?
i will send you result of code

**Comment by H03in** [comment]
as you see there is right and left distance near the yellow banner : 
![screen shot 2018-04-17 at 9 46 09 am](https://user-images.githubusercontent.com/12210646/38849940-44a5cc26-4224-11e8-808c-70cde4111bd6.png)

**Comment by mikepenz** [comment]
Can you please use the layout inspector of Android Studio and see where the margin/padding is applied. Perhaps it happens in your item

**Comment by mikepenz** [comment]
Please report back. :) Close for the time being

**Comment by Amalip** [comment]
Hi @mikepenz! I have the same question and I have checked with the Layout Inspector and It's applied in material_drawer_sticky_footer, it sets startMargin and endMargin in -2147483648

**Comment by mikepenz** [comment]
there is padding applied for API 17 for compat reasons, the other padding should be applied for the items https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerUtils.java#L397

**Comment by Amalip** [comment]
I did `DrawerUIUtils.setDrawerVerticalPadding(drawerMenu.getStickyFooter(), 0);` but it didn't work.

It looks like this 
![54435936_409454206488697_7019092355512795136_n](https://user-images.githubusercontent.com/11381420/54646394-829ca600-4a64-11e9-9c2f-e1d51d73b374.png)

My custom DrawerItem is
```
public class FooterDrawerItem extends AbstractDrawerItem<FooterDrawerItem, FooterDrawerItem.ViewHolder> {

    @Override
    public int getLayoutRes() {
        return R.layout.drawer_footer;
    }

    @Override
    public int getType() {
        return 0;
    }

    @Override
    public ViewHolder getViewHolder(View v) {
        return new ViewHolder(v);
    }

    public static class ViewHolder extends RecyclerView.ViewHolder {
        private TextView txv;

        public ViewHolder(View itemView) {
            super(itemView);

            itemView.setPadding(0,0,0,0);
            itemView.setBackgroundColor(Color.TRANSPARENT);
            txv = itemView.findViewById(R.id.txv);
            txv.setPadding(0,0,0,0);
        }
    }

}
```
