### ISSUE TITLE
StickyDrawerItems not scrolling

### ISSUE THREAD

**Issue by N-i-p-o-l** [mikepenz/MaterialDrawer#2273]
How to enable scrolling for stickyDrawerItems in landscape mode with PrimaryDrawerItems?

In portrait mode stickyDrawerItems and PrimaryDrawerItems looks ok. But in landscape mode only PrimaryDrawerItems scrolling and stickyDrawerItems show as overlay. See screenshot:
https://prnt.sc/j4753o

**Comment by mikepenz** [comment]
@N-i-p-o-l as of the `design` of sticky items, they are not supposed to scroll.

There are no plans to adjust this behaviour. You might want to make these items normal items which are at the bottom of your list in landscape

**Comment by N-i-p-o-l** [comment]
Ok, thanks
