### ISSUE TITLE
Issue While Adding

### ISSUE THREAD

**Issue by wildstone1** [mikepenz/MaterialDrawer#2275]
Hey dude Appreciate your work
I face problem while adding the library

problem occur  

	Gradle sync failed: Could not get unknown property 'versions' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

gradle version : 4.4
android studios : 3.1.1 
![capture](https://user-images.githubusercontent.com/23513339/38679917-5cc63330-3e7e-11e8-9fe9-a969634d460b.PNG)

**Comment by mikepenz** [comment]
@wildstone1 `versions.supportLib` is just a placeholder I have defined in my gradle files. you can replace it with a specific version.

https://github.com/mikepenz/MaterialDrawer/blob/develop/build.gradle#L10
