### ISSUE TITLE
Load AccountHeader icon from URL

### ISSUE THREAD

**Issue by asrma7** [mikepenz/MaterialDrawer#2277]
is it possible to load account header from url instead of drawable?
for eg:-
String url = "http://example.com/image.png";
new ProfileDrawerItem().withName(fullname+"("+username+")").withEmail(email).withIcon(url);

**Comment by mikepenz** [comment]
the icon for a profile yes. the big header picture no. (but you can get a reference to the ImageView for the header background allowing you to do it manually if you want to)
https://github.com/mikepenz/MaterialDrawer#load-images-via-url

**Comment by asrma7** [comment]
i tried using url but it doesnot load.
Sample user icon shows instead of the url image.
Yes it is for profile image not the header image.
