### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by twinone** [mikepenz/MaterialDrawer#228]
When you set withTranslucentActionBarCompatibility(false) and withDisplayBelowToolbar(true) the toolbar still gets translucent. withDisplayBelowToolbar(true) should imply translucent actionbar and toolbar to false.

**Comment by mikepenz** [comment]
@twinone no i don't think this should make the toolbar non translucent. perhaps you just need this in your app. you can just use a non translucent toolbar theme and set the toolbar to be non translucent.
