### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [mikepenz/MaterialDrawer#2280]
Hello! 
I created a New logo Proposal for this amazing project. I wanted to create a logo that feels unique and has an identity to it. If you find it good enough and like it...
The Google drive link contains all the files: https://drive.google.com/drive/folders/1hLcgeAMF_LVZE2mJoiS08qf34R24gpD1?usp=sharing

Regards...

![material-drawer logo presentation](https://user-images.githubusercontent.com/37814297/38854428-55d1383e-4218-11e8-890b-f93a320b5812.jpg)

**Comment by mikepenz** [comment]
@chimzycash thank you very much! That looks really great ;)

**Comment by mikepenz** [comment]
@chimzycash once again thank you soo much! It is really great to see such PRs :) 

Currently I won't yet merge it as I don't necessarily have time to rebrand. 
But I'll keep the issue a little bit longer open to give it more visibility :)

**Comment by mikepenz** [comment]
Thank you very much! :)

**Comment by chimzycash** [comment]
I appreciate... 

I'm always available in case of anything you may need... :)

**Comment by mikepenz** [comment]
Thank you again very much. 

Closing this as It got a lot of visibility by now :). 

Great work!
