### ISSUE TITLE
withOnlyOneExpandedItem not working

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/MaterialDrawer#2282]
hi
i have recently updated to the latest version (6.0.6) and i want only one expandable item to be open at any given time.
immediately after creating my drawer i call `mDrawer.getExpandableExtension().withOnlyOneExpandedItem(true);`  but it's not working and multiple items can be expanded.

i did not find any other issues about this on github, and i did not find any usage examples for this feature in the sample app

please advise

**Comment by mikepenz** [comment]
* I am afraid this was related to: https://github.com/mikepenz/MaterialDrawer/commit/9fbd0ce208c0e593702611f34689a385b9052ded

Tested it in the sample after this commit and it works great :)
