### ISSUE TITLE
Manual changing of selection of drawer items

### ISSUE THREAD

**Issue by pavolgolias** [mikepenz/MaterialDrawer#2284]
Hi Mike!
This library is awesome, thank you very much!

But still, I have one question - I want to select drawer item manually - I do it as you shown in docs by this statement:
`drawer.setSelection(itemId, true);`
Everything works fine except one thing - item is selected and highlighted with my custom color, but there is no background ("or highlight") at selected item. If I change the selected item by touching it on the screen, everything changes correctly and selected item is highlighted also with the background. So problem is only when I change selection programatically.

Can you help my with this? Am I missing some property to set up?
Thank you very much!!

**Comment by mikepenz** [comment]
you do the selection on the main thread?

**Comment by pavolgolias** [comment]
Hi, thanks for answer. 
No, I am not. I am doing it in LiveData observer - so as my data are downloaded and updated, I am changing count (badge) of unseen items. Is it the cause of problem? Is so, how should I do this?

**Comment by mikepenz** [comment]
can you please call this on the main ui thread. as it will change the ui and such need to run on the ui thread

**Comment by pavolgolias** [comment]
Hello @mikepenz, is there anything I can do with this issue?
Thank you for your answer.

**Comment by mikepenz** [comment]
I do the following in the sample: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L205

it works great

Please ensure:
- It's done on the main thread
- The item has an identifier
- The identifier is equal to the one you use to set the selection

**Comment by JRascagneres** [comment]
I am having the same issue and I have ensured that those points are met
