### ISSUE TITLE
Back arrow on click just opens the drawer.

### ISSUE THREAD

**Issue by therealccarter** [mikepenz/MaterialDrawer#2286]
I decided to try to get the back arrow working but am having some issues. 

First thing I did was add the code found here: https://github.com/mikepenz/MaterialDrawer#code---show-the-back-arrow

That worked fine for showing the back arrow, but when I click it, it just opens the material drawer. 

So the next thing I did was look around the issues page to see if this was a common misunderstanding and I used the @Override method in Mike Penz's first answer here: https://github.com/mikepenz/MaterialDrawer/issues/65

But no luck, clicking the arrow still opens the drawer instead of going back. I'm probably missing something obvious/easy, but I'm stuck. Any help appreciated, thanks!

Material Drawer version 6.0.7
Support Library Version 27.1.1
Gradle Build Tools 27.0.3
Android Studio version 3.1.2

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/FullscreenDrawerActivity.java#L63

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/FullscreenDrawerActivity.java#L111

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/FullscreenDrawerActivity.java#L121
