### ISSUE TITLE
Color budge, like it github issues

### ISSUE THREAD

**Issue by yoavst** [mikepenz/MaterialDrawer#229]
Is there a way to set the background color for the badge (and text color also of course)?
and if it will be a bit rounded rectangle it will be awsome.

**Comment by raghunandankavi2010** [comment]
It can be implemented.

In BaseDrawerItem Add

          private int textBadgeColor= 0;

         public T withTextBadgeColor(int textBadgeColor) {
         this.textBadgeColor = textBadgeColor;
         return (T) this;
        }

Then in PrimaryDrawerItem

Comment the below

       // viewHolder.badge.setTextColor(UIUtils.getTextColor(color, selected_text));

Add

        viewHolder.badge.setTextColor(getTextBadgeColor());

Then in your activity for the PrimaryDrrawerItem

      .withTextBadgeColor(Color.GREEN).withBadge("23")

**Comment by yoavst** [comment]
Can you add it? I just don't want to add new module :(

**Comment by raghunandankavi2010** [comment]
@yoavst I don't think its necessary in most cases. As when you select a drawer item you apply a primary color to the drawer item. Its according to material specs

**Comment by mikepenz** [comment]
@raghunandankavi2010 you can simply implement a custom DrawerItem and use it. No need to modify anything?

**Comment by yoavst** [comment]
You only need to modify the Base one, and the implementations. (something like 20 short line of code max)

**Comment by mikepenz** [comment]
Yeah but the same for you :D 

Just add it for your usecase ;) Perhaps i will add in the future but not right now. :D keep it simple and clean

**Comment by raghunandankavi2010** [comment]
@mikepenz yes a custom drawer would be a  good choice.

**Comment by yoavst** [comment]
I know mike, but for me it mean create a module, and have to sync it with your repo all the time. I can work on it if you would apply the pull request.

**Comment by mikepenz** [comment]
why? just copy a drawerItem or look at the source and then add it to your project. no need to modify anything inside the MaterialDrawer
