### ISSUE TITLE
[Question] Select Item Just Once

### ISSUE THREAD

**Issue by TurKurT656** [mikepenz/MaterialDrawer#2292]
## About this issue
Hi and thank you for this great job.
I have a simple question. I have an PrimaryDrawerItem that is selectable and when its selected a fragment starts. So how do I prevent selection of this item when its already selected? because i dont want to replace that fragment again and again.

## Details
- [6.0.7] Used library version
- [27.1.1 ] Used support library version
- [3.1.2 ] Used gradle build tools version
- [3.1.2 ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [yes ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [no ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [yes ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [yes] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [yes ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [no ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@TurKurT656 I would recommend simply add a `item.isSelected()` check in your listener :)

**Comment by mikepenz** [comment]
oh sorry. 

you can attach a `preClickListener` before the selection was made by the adapter.

```java
result.getAdapter().withOnPreClickListener(new OnClickListener<IDrawerItem>() {
    @Override
    public boolean onClick(View v, IAdapter<IDrawerItem> adapter, IDrawerItem item, int position) {

        Log.e("INFO", "" + item.isSelected());

        return false;
    }
});
```
