### ISSUE TITLE
How to show StickyFooterItem in MiniDrawer??

### ISSUE THREAD

**Issue by liupeng826** [mikepenz/MaterialDrawer#2294]
## About this issue

How to show StickyFooterItem in MiniDrawer??

## Details
- [ 6.0.7] Used library version
- [27 ] Used support library version
- [ 4.6] Used gradle build tools version
- [ 3.0.1] Used tooling / Android Studio version
- [ 27] Other used libraries, potential conflicting libraries

## Checklist

- [ yes] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ yes] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [ yes] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ yes] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ yes] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ yes] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
This is not supported and there are currently no plans to do so. 

You can achieve it potentially if you implement it manually by changing the elements being used here: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L452
