### ISSUE TITLE
withStickyHeader doesn't show anything, but withHeader works fine

### ISSUE THREAD

**Issue by feinstein** [mikepenz/MaterialDrawer#2298]
If I add a header with `.withHeader(R.layout.nav_header_main)` it works fine:

![image](https://user-images.githubusercontent.com/8120472/40154237-c6c70142-5963-11e8-8ba4-93754318a575.png)

but if I try `.withStickyHeader(R.layout.nav_header_main)` nothing shows up:

![image](https://user-images.githubusercontent.com/8120472/40154317-2e108e72-5964-11e8-9acc-695c5d9056fa.png)

## Details
- [ ] Used library version : 6.0.7
- [ ] Used support library version: 27.1.1
- [ ] Used gradle build tools version: 4.4
- [ ] Used tooling / Android Studio version: 3.1.2
- [ ] Other used libraries, potential conflicting libraries:
```
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    implementation 'com.github.barteksc:android-pdf-viewer:3.0.0-beta.5'
    implementation 'com.jakewharton:butterknife:8.8.1'
    implementation("com.mikepenz:materialdrawer:6.0.7@aar") { transitive = true }
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
```

**Comment by mikepenz** [comment]
If I do the following the sticky header works as expected:
https://github.com/mikepenz/MaterialDrawer/tree/issue/2298
You can check it ou tin the sample

**Comment by feinstein** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/8414fbcd880b95702e5b05a2cd3928288225bca9/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L105

Here you say?

**Comment by mikepenz** [comment]
yes Just a sample to showcase that it should work. 

Basically the sticky header is just a view. above the recyclerview:

https://github.com/mikepenz/MaterialDrawer/blob/b903da90c60ae46cc122a3e319112098fa596141/library/src/main/java/com/mikepenz/materialdrawer/DrawerUtils.java#L201

**Comment by feinstein** [comment]
The app got approved without the sticky header so I will leave it be for now. 

The difference I can see is that I am passing a view id, referenced in xml, while you create it programmatically.

**Comment by mikepenz** [comment]
Ok :) 

The difference might be that it has an explicit height. perhaps the height was not measured correctly and due to that it would not be visible

**Comment by feinstein** [comment]
Yes it has, is it there a way to overcome this?

**Comment by mikepenz** [comment]
I know it sounds "bad" but can you possibly try to have it nested also with an explicit set height? perhaps the children do not enforce the height or so
