### ISSUE TITLE
withIcon can't be worked from url

### ISSUE THREAD

**Issue by journeyOS** [mikepenz/MaterialDrawer#2299]
url = https://avatars2.githubusercontent.com/u/13032439?v=4
final IProfile profile = new ProfileDrawerItem()
                .withName(user.name)
                .withEmail(user.email)
                .withIcon(Uri.parse(avatar));

**Comment by mikepenz** [comment]
Please follow the issue template from github. 

https://github.com/mikepenz/MaterialDrawer#load-images-via-url
