### ISSUE TITLE
Rewrite Documentation

### ISSUE THREAD

**Issue by mikepenz** [mikepenz/MaterialDrawer#23]
Rewrite the documentation and include document more features.

Probably create a wiki

**Comment by gpulido** [comment]
Hello,
Nice Library, It would be great to have a working example source code. It only needs to be the a main Activity with the nav drawer.
Thank you for sharing!

**Comment by egor-n** [comment]
There [is a sample](https://github.com/mikepenz/MaterialDrawer/tree/master/app).

**Comment by gpulido** [comment]
Thank you, sorry for not having seen it, I would suggest you to rename it to "demo " or "example".
Again thank for sharing
