### ISSUE TITLE
Bolded name?

### ISSUE THREAD

**Issue by nisie** [mikepenz/MaterialDrawer#230]
I saw from the sample you can bold the name on the header. I can't find the way to bold the name, can someone teach me how? Sorry for such a newbie question..

**Comment by mikepenz** [comment]
@nisie the text is bold by default because i set the correct style of the font. the problem is that on pre lollipop devices this is not done because those don't have the fonts specified in the Android Design Guideliens

**Comment by nisie** [comment]
Ah, I get what's going on now. Thank you very much. Is it possible to make it bold for pre-lollipop devices, though?

**Comment by mikepenz** [comment]
Not yet. Or not with the provided functions. You still can get it by implementing a custom DrawerItem which is done in 5 minutes.

**Comment by nisie** [comment]
Alright. Thank you for your suggestions and fast reply :)
