### ISSUE TITLE
Is it possible to provide custom layout for Items?

### ISSUE THREAD

**Issue by masterleclerc** [mikepenz/MaterialDrawer#2302]
_Is it possible to provide custom layout for Items?_ I want to support rare situation when the application supports RTL layout but there is no translation available for currently selected RTL language. In this case drawer is correctly placed on the right side, is populated with English (default) values but words in the menu are aligned to the left. Correct value would be to the right. I handle it it in the rest of my app with simple adding  android:textAlignment="viewStart" to the text vies.

I can see in `material_drawer_item_primary.xml` :
```
        <TextView
            android:id="@+id/material_drawer_name"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:fontFamily="sans-serif-medium"
            android:gravity="center_vertical|start"
            android:lines="1"
            android:singleLine="true"
            android:textDirection="anyRtl"
            android:textSize="@dimen/material_drawer_item_primary_text"
            tools:text="Some drawer text" />
```

it would be great if I could just add simple `android:textAlignment="viewStart"` ; )

**Comment by masterleclerc** [comment]
Haha, so simple, just extend DraweItem ; ) Thanks.

**Comment by Shakezulla57** [comment]
@mikepenz Am I being dense or is this not in FAQ anymore?

**Comment by mikepenz** [comment]
@Shakezulla57 it's still part of the FAQ: https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md

https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md

**Comment by Shakezulla57** [comment]
Thanks @mikepenz 

I was looking at the FAQ section of the README.
