### ISSUE TITLE
Expandable drawer item inside another expandable drawer item causes issues

### ISSUE THREAD

**Issue by hamzabinamin** [mikepenz/MaterialDrawer#2305]
## About this issue

- Briefly describe the issue
- If I add an expandable drawer item of level 3 inside one of the secondary items of the parent expandable item of level 2, then when the parent item is collapsed, it causes some of the items to be displayed outside of the parent item list. This only happens when the second child list is not collapsed. If the second child list is collapsed before collapsing the parent list, then it works fine. I have also attached three images to showcase this. 

## Details
- [6.0.6/6.0.7] Used library version
- [27.1.1] Used support library version
- [3.0.1] Used gradle build tools version
- [3.0.1] Used tooling / Android Studio version
- [none ] Other used libraries, potential conflicting libraries

## Checklist

- [ yes] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ yes] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [ yes] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ yes] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ yes] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ yes] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)
![1](https://user-images.githubusercontent.com/12872039/40575617-975308f2-6101-11e8-9698-d39841b77cb3.jpg)
![2](https://user-images.githubusercontent.com/12872039/40575618-9785bc3e-6101-11e8-8b4f-75028b19caf1.jpg)
![3](https://user-images.githubusercontent.com/12872039/40575619-97bf753c-6101-11e8-8cc8-3b0ea6a24a95.jpg)

**Comment by hamzabinamin** [comment]
@mikepenz any help?

**Comment by hamzabinamin** [comment]
@spbisya @alorma 
 Can anyone help please. I really need to figure this one out.

**Comment by mikepenz** [comment]
@hamzabinamin what are you doing? do you have sample code to showcase the issue ?

Did you check out the sample of the FastAdapter showcasing this too?

**Comment by mikepenz** [comment]
You can check out this FastAdapter sample having multiple nested levels: https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/ExpandableSampleActivity.java

**Comment by hamzabinamin** [comment]
@mikepenz , thanks for replying. I'm going to check the fast adapter. I have a question. Why do you we need the fast adapter? I thought it was used to help with recycler view? Can't I get multiple nested levels without using the fast adapter?

**Comment by mikepenz** [comment]
@hamzabinamin the FastAdapter is a adapter simplification implemented by me to streamline usage of it and eliminate boilerplate adapter code... 

You write an item, and that one can instantly be used in a RecyclerView. 

RecyclerView and their default adapter has no "logic" for collapsable items. This is just provided via the FastAdapter by me. 

The MaterialDrawer uses the FastAdapter internally to allow me providing a super flexible easily enhanceable API.
Items can be written and provided to the adapter / drawer without any changes in the main code

**Comment by asafbennatan** [comment]
@mikepenz  happens here as well  ,using the following:
drawer->expandable(three)->expandable(three)->secondary(10)
if we open all(it happens if the last one is open) the inner expandable , and close the outer expandable , the secondaries are not being closed , under some circumstances it duplicates the drawer items entries

**Comment by hamzabinamin** [comment]
@mikepenz 
My code looks like this

`result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withHasStableIds(true)
                .withItemAnimator(new DefaultItemAnimator())
                .withAccountHeader(headerResult) 
      .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.homeTitle).withIcon(R.drawable.house).withIdentifier(12).withSelectable(false),

        new ExpandableDrawerItem().withName(getString(R.string.categoriesTitle)).withIcon(R.drawable.carttwo).withIdentifier(19).withSelectable(false).withSubItems(

 new SecondaryDrawerItem().withName(getString(R.string.categoryFruit)).withLevel(2).withIdentifier(7).withSelectable(false),

.............

 new ExpandableDrawerItem().withName(getString(R.string.categoryFood)).withLevel(2).withIdentifier(101).withSelectable(false).withSubItems(
                new SecondaryDrawerItem().withName(getString(R.string.categoryFoodShelf)).withLevel(3).withIdentifier(43).withSelectable(false),
                new SecondaryDrawerItem().withName(getString(R.string.categoryDriedNuts)).withLevel(3).withIdentifier(44).withSelectable(false),
                new SecondaryDrawerItem().withName(getString(R.string.categoryCereals)).withLevel(3).withIdentifier(45).withSelectable(false)
                ), 

....................
),

....... `

You mentioned that fast adpater is already being used by the drawer internally, so how do I fix my issue? If I keep the child expandable list open and close the parent list (categories here), it starts to show some items outside of categories, like in 2nd image.

**Comment by hamzabinamin** [comment]
@mikepenz could you help me with this please?
