### ISSUE TITLE
Update a profile image in AccountHeader in MiniDrawer

### ISSUE THREAD

**Issue by akhbulatov** [mikepenz/MaterialDrawer#2308]
When updating a profile, the new image is not updated in `MiniDrawer`, but in `Drawer` itself it is updated correctly. And when I start an activity, the image is updated in `MiniDrawer` as expected.
Here is the profile update code:
```
if (profile != null) {
    profile.withName(name);
    profile.withEmail(email);
    profile.withIcon(icon);

    if (accountHeader != null) accountHeader.updateProfile(profile);
}
```
where `icon` is the URL of the image.

Also I add the following code in `onCreate()` of my class extends `Application`:
```
DrawerImageLoader.init(new AbstractDrawerImageLoader() {
    @Override
    public void set(ImageView imageView, Uri uri, Drawable placeholder) {
        Picasso.with(imageView.getContext()).load(uri).placeholder(placeholder).fit().centerCrop().error(R.drawable.photo_not_found).into(imageView);
    }

    @Override
    public void cancel(ImageView imageView) {
        Picasso.with(imageView.getContext()).cancelRequest(imageView);
    }
});
```
How to fix it?

![2018-05-31 12 49 55](https://user-images.githubusercontent.com/6171938/40775652-428eaf6e-64d1-11e8-93af-01243fb975ef.jpg)
![2018-05-31 12 50 38](https://user-images.githubusercontent.com/6171938/40775672-4d0f9e9e-64d1-11e8-8f16-0017f2b871f4.jpg)

**Comment by mikepenz** [comment]
* if you change elements a recreation of the items in the `MiniDrawer` is most likely necessary: `MiniDrawer.createItems()`

Alternatively you can try to call `miniDrawer.getAdapter().notifyAdapterDataSetChanged();

**Comment by akhbulatov** [comment]
Thanks, it works :)
