### ISSUE TITLE
Method isSelected() returns false after click on MiniDrawerItem

### ISSUE THREAD

**Issue by akhbulatov** [mikepenz/MaterialDrawer#2309]
I've implemented a custom `MiniDrawerItem` to add text under the icon. Now I need to highlight the text after clicking on the item of `MiniDrawerItem`. Here is my implementation of the override method `bindView()` in my custom `MiniDrawerItem`:
```
@Override
public void bindView(ViewHolder viewHolder, List payloads) {
    super.bindView(viewHolder, payloads);
    MyViewHolder holder = (MyViewHolder) viewHolder;
    Context context = holder.itemView.getContext();
    holder.nameText.setText(name.getTextRes());

    // Highlight the text of the selected item
    holder.nameText.setTextColor(isSelected()
                ? getSelectedTextColor(context)
                : ContextCompat.getColor(context, R.color.color_black)); 
}
```

But there is a problem: when I click on an item in `Drawer`, `isSelected()` in `bindView()` returns true, but when I click on an item in `MiniDrawer` `isSelected()` returns false. In the second case, should the method not return true?

After click on the item in `Drawer`:
![2018-05-31 13 21 49](https://user-images.githubusercontent.com/6171938/40778929-a371a084-64db-11e8-820e-f6cd79c3b5d2.jpg)

And in `MiniDrawer`
![2018-05-31 13 21 28](https://user-images.githubusercontent.com/6171938/40778980-d87af258-64db-11e8-92f9-72c2807626d2.jpg)

**Comment by mikepenz** [comment]
@akhbulatov is the `bindView` called again? As far as of the defaults it should not and only the state would change. 

You might wanna enable: `withSelectWithItemUpdate` on the `FastAdapter` of the `MiniDrawer`

**Comment by akhbulatov** [comment]
Thanks, `withSelectWithItemUpdate` method fixed this :)
