### ISSUE TITLE
Set profile image gravity as center

### ISSUE THREAD

**Issue by nambv** [mikepenz/MaterialDrawer#231]
Hi, @mikepenz 
Can you allow to set the profile image in header as center (instead of current default is left)? I'm very appriciated to wating for your answer

**Comment by raghunandankavi2010** [comment]
@nambv I don't think its required cause it does not match the material design guidelines. 

You can have a header(a custom view) added to the Drawer. The custom view can be customized the the way you want. Why do you want profile image in the center?

**Comment by mikepenz** [comment]
@nambv please see @raghunandankavi2010 answer. No need to implement this because this is nothing which can be found in the Material Design Guidelines. Please just use the .withHeader() function of the drawer. Create your view. set everything and done.
