### ISSUE TITLE
Layout height not changing with keyboard open

### ISSUE THREAD

**Issue by shalevmo** [mikepenz/MaterialDrawer#2310]
## About this issue

I created a custom layout, and put it in a drawer. 
The custom layout is made of a few EditText items, wrapped in a LinearLayout, wrapped in a ScrollView. 
When I focus one of the Edittext and the keyboard opens up, the height of the layout doesn't change to fit, so I can't see the bottom EditText items, and I can't scroll to see them. 

## Details
- [ ] Used library Verizon : 6.0.7
- [ ] Used support library version: 27.1.1
- [ ] Used gradle build tools version: 3.1.0
- [ ] Used tooling / Android Studio version: 3.1.1
- [ ] Other used libraries, potential conflicting libraries: irrelevant.

**Comment by tallevi12** [comment]
@mikepenz can you help? Im having this issue too. Thanks!

**Comment by mikepenz** [comment]
Please see:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/util/KeyboardUtil.java

and relevant topics:
http://stackoverflow.com/a/9108219/325479


https://github.com/mikepenz/MaterialDrawer/issues/183
https://github.com/mikepenz/MaterialDrawer/issues/877
https://github.com/mikepenz/MaterialDrawer/issues/721


In case you make the UI fullscreen, try not to and simply work with the scrims and the fitsSystemWindows flag
