### ISSUE TITLE
Changing the selected icon color

### ISSUE THREAD

**Issue by aakarnik** [mikepenz/MaterialDrawer#2313]
## About this issue

The color of the icon in the drawer does not change when an item is clicked and selected. I am currently trying to use the `withSelectedIconColor()` method.

Is there any other method I should try? Thanks!

```java
private IDrawerItem[] getDrawerItems() {
        return new IDrawerItem[]{
                new PrimaryDrawerItem().withName(R.string.menu_home).withIcon(getResources().getDrawable(R.drawable.home)).withTextColor(getResources().getColor(R.color.textColorPrimary)).withSelectedIconColor(getResources().getColor(R.color.primary_dark)),
                new PrimaryDrawerItem().withName(R.string.menu_library).withIcon(getResources().getDrawable(R.drawable.library)).withTextColor(getResources().getColor(R.color.textColorPrimary)).withSelectedIconColor(getResources().getColor(R.color.primary_dark)),
                new PrimaryDrawerItem().withName(R.string.menu_courses).withIcon(getResources().getDrawable(R.drawable.courses)).withTextColor(getResources().getColor(R.color.textColorPrimary)).withSelectedIconColor(getResources().getColor(R.color.primary_dark)),
                new PrimaryDrawerItem().withName(R.string.menu_meetups).withIcon(getResources().getDrawable(R.drawable.meetups)).withTextColor(getResources().getColor(R.color.textColorPrimary)).withSelectedIconColor(getResources().getColor(R.color.primary_dark)),
                new PrimaryDrawerItem().withName(R.string.menu_surveys).withIcon(getResources().getDrawable(R.drawable.survey)).withTextColor(getResources().getColor(R.color.textColorPrimary)).withSelectedIconColor(getResources().getColor(R.color.primary_dark)),
        };
    }
```
## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@aakarnik you need to enable tinting if you provide a drawable is icon :) (Coloring only happens completely automatically for Iconics drawables :) )

**Comment by aakarnik** [comment]
Hi, thanks for the prompt reply :) I used the `.withIconTintingEnabled(true)` but it changed the color of the icon permanently. Is there a method I should combine with it?

**Comment by mikepenz** [comment]
Oh I am not seeing this in your code sample ;) 

what do you mean it changed permanently? It would not change back when deselecting?

**Comment by aakarnik** [comment]
Yes, I was changing the code quite frequently. I used it like this:
```java
new PrimaryDrawerItem().withName(R.string.menu_home).withIcon(getResources().getDrawable(R.drawable.home)).withTextColor(getResources().getColor(R.color.textColorPrimary)).withSelectedIconColor(getResources().getColor(R.color.primary_dark))
```

**Comment by mikepenz** [comment]
Do you still have the issue? Did you compare with the sample app because there it seems to work. 

Otherwise could you please provide a sample app or so which showcases the problem making it easier to fix?

**Comment by aakarnik** [comment]
I compared with the sample app, I don't know it is not working for ours. Currently we are using two arrays of xmls to change the color of the items in the drawer. The function looks like this: 

```java
public PrimaryDrawerItem changeUX(int iconText, Drawable drawable, int blueDrawable) {
+        return new PrimaryDrawerItem().withName(iconText).withIcon(drawable).withTextColor(getResources().getColor(R.color.textColorPrimary)).withSelectedIcon(blueDrawable);
+    }
```

**Comment by mikepenz** [comment]
In the sample I try here the coloring: https://github.com/mikepenz/MaterialDrawer/blob/f2d9e10587fb0cfab581da29b3ef75123323fdb0/app/src/main/java/com/mikepenz/materialdrawer/app/AdvancedActivity.java#L88

Do you color that drawable manually somewhere? tint it before use? Perhaps you need to `.mutate()` it?

**Comment by aakarnik** [comment]
The original xml file for the icon is white - so it is not manually colored in the Java class.
The requirement is to have the icon of the selected item to have the color/similar color of the background. For that, an xml of the same icon with different color is used with the method `withSelectedIcon()`

Here is a screenshot for a better idea:
![5 5in-landscape](https://user-images.githubusercontent.com/37878201/42771804-5b6f1372-88f6-11e8-8f65-48d62b52afc3.jpg)

I will try to use the methods in your comment and let you know. I really appreciate the help :)

**Comment by aakarnik** [comment]
Finally, this code worked:

```java
return new PrimaryDrawerItem().withName(iconText)
                .withIcon(drawable)
                .withIconColor(getResources().getColor(R.color.textColorPrimary))
                .withTextColor(getResources().getColor(R.color.textColorPrimary))
                .withSelectedIconColor(getResources().getColor(R.color.primary))
                .withIconTintingEnabled(true);
```

I had to set the color of the icon in method regardless of the original color of the drawable to use the `withSelectedIconColor()` and `.withIconTintingEnabled()` method.
