### ISSUE TITLE
Failed to resolve: com.mikepenz:materialdrawer:6.0.8

### ISSUE THREAD

**Issue by bipindr123** [mikepenz/MaterialDrawer#2316]
adding this to build.gradle under dependencies 

 implementation("com.mikepenz:materialdrawer:6.0.8@aar") {
        transitive = true
    }

 gives sync error

Failed to resolve: com.mikepenz:materialdrawer:6.0.8
Open File
Show in Project Structure dialog

using gradle plugin version 3.1.3and gradle version 4.4

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/2312 see there

having problems with jcenter. waiting for the support to come bakc to me

**Comment by balavishnu** [comment]
I am facing the same issue as well. Unable to load my existing apps in the new system. any solutions?
