### ISSUE TITLE
How to remove mini drawer completely

### ISSUE THREAD

**Issue by Rizora** [mikepenz/MaterialDrawer#2317]
Im unable to remove the mini drawer... all I want is an app with tabs I can edit... this is the only working one I can find... however it is bloated

**Comment by mikepenz** [comment]
@Rizora you don't have to use the minidrawer. and if you have proguard properly set up classes you don't use will be removed

**Comment by Rizora** [comment]
How would I do that? Sorry I'm coming from a simple Swift/ObjectC background

**Comment by mikepenz** [comment]
First off. you are worried about the classes being inside the library? Right?

**Comment by mikepenz** [comment]
As for how to do that. Here's the official android documentation: https://developer.android.com/studio/build/shrink-code

**Comment by Rizora** [comment]
I just want the menu with separate views/activities.... in Xcode/IOS I rely heavily on Storyboard for the heavy lifting... sadly no such thing here in Android.

**Comment by mikepenz** [comment]
This library only does the UI for a drawer as defined in the guidelines. it does not navigation for you. You get have the callback via the listener and then you can execute whatever code you need :)

**Comment by mikepenz** [comment]
Sorry I can't help or guide with getting started with android :)

**Comment by mikepenz** [comment]
Otherwise perhaps the `NavigationView` of android fits more your needs: https://developer.android.com/reference/android/support/design/widget/NavigationView

**Comment by Rizora** [comment]
Thanks no problem I don't expect you too have too. Thanks for the resources you have provided, they are helpful.
