### ISSUE TITLE
Problem with custom layout

### ISSUE THREAD

**Issue by cherolopez56** [mikepenz/MaterialDrawer#2318]
Hello I'm trying to use a custom layout, and for that I create a create a class extended by "SecondaryDrawerItem" like that

```java
public class CustomSecondaryDrawerItem extends SecondaryDrawerItem {

    @Override
    @LayoutRes
    public int getLayoutRes() {
        return R.layout.custom_material_drawer_item_secondary;
    }

    private ColorHolder background;

    public CustomSecondaryDrawerItem withBackgroundColor(int backgroundColor) {
        this.background = ColorHolder.fromColor(backgroundColor);
        return this;
    }

    public CustomSecondaryDrawerItem withBackgroundRes(int backgroundRes) {
        this.background = ColorHolder.fromColorRes(backgroundRes);
        return this;
    }

    @Override
    public void bindView(ViewHolder holder, List payloads) {
        super.bindView(holder, payloads);

        if (background != null) {
            background.applyToBackground(holder.itemView);
        }
    }

}
```

Then I invoke that like this:

```java
private CustomSecondaryDrawerItem createSecondaryDrawerItem (int name, int id){
        return (CustomSecondaryDrawerItem)new CustomSecondaryDrawerItem()
                .withBackgroundColor(getColorFromResources(R.color.white))
                .withName(getString(name))
                .withSelectable(false)
                .withLevel(5)
                .withIdentifier(id)
                .withTextColor(mGrayColor);
    }
```

And even that I put my custom layout, it forces the default one, can you tell me what I'm doing wrong???

Help me please
 jajaja

**Comment by mikepenz** [comment]
@cherolopez56 do you have normal items also in that recyclerView? 

you have not defined a unique identifier (for the element) if the rv caches it will reuse the other one if available

**Comment by cherolopez56** [comment]
"do you have normal items also in that recyclerView?"
-no, I just add two items of the same class (for test the custom class)
"you have not defined a unique identifier (for the element) if the rv caches it will reuse the other one if available"
-no, every component have a unique identifier

I create an another custom class extended of "DividerDrawerItem" more simple, but de result is the same:

`
public class CustomDividerDrawerItem extends DividerDrawerItem {

    @LayoutRes
    @Override
    public int getLayoutRes() {
        return R.layout.custom_material_drawer_item_divider;
    }
}
`
do you have a simple example for that?

**Comment by mikepenz** [comment]
I don't see: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/AbstractBadgeableDrawerItem.java#L55 being overwritten and having a unique value

**Comment by mikepenz** [comment]
Please report back :) Closing for the time being
