### ISSUE TITLE
Multiple drawers + inheritance + append

### ISSUE THREAD

**Issue by vanceanderson41** [mikepenz/MaterialDrawer#2319]
## About this issue
- I have a set of use cases that call for 2 drawers used in an application:

1. A "home" activity that is able to be used to navigate (drawer) throughout the application (pretty standard)
2. A "utility" drawer with a custom view that is used in more activities than the navigation (Right/end)
3. Most activities will have a "utility" drawer and for intent of this question, only a single will have navigation

MaterialDrawer has been a fantastic solution for this case up to this point. I encountered an issue when setting up the drawer toggle with this architecture: 

- Abstract UtilityDrawerActivity that builds/manages the "utility" drawer
- Home activity extending this UtilityDrawerActivity that appends its navigation drawer to the already built "utility" drawer

Functionally, this achieves precisely what I desired. However, When trying to add in the drawer toggle for the navigation drawer (the one that has been `append()`ed to the utility drawer, not having had `build()` called), the method call `getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);` results in a `NullPointerException` invariably. If I instead simply `build()` the navigation drawer instead of appending it to the already built utility/right-side drawer, no NPE is thrown. Do I miss anything if I instead build 2 separate drawers, one of which simply holds a custom view/fragment container?

## Details
- [[6.0.8] Used library version
- [ 27.1.1] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [X] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [X] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@vanceanderson41 sorry if I keep it short :)

So using `append()` is the correct solution. 

as of the design of the `ActionBarDrawerToggle` only the `main` drawer (the one which was built) will have the `ActionBarDrawerToggle` as also only that one will be opened via it. (a Toolbar only has one `ActionBarDrawerToggle`)

The other (the right one which is appended) is only opened via sliding from the right edge. alternatively you can use the `open` and `close` methods to toggle it's opening state from whatever control you have in place which would be capable of opening it.

**Comment by vanceanderson41** [comment]
This answers my question. Thanks for the reply @mikepenz
