### ISSUE TITLE
How to mark first list item of the drawer as selected

### ISSUE THREAD

**Issue by Shajeel-Afzal** [mikepenz/MaterialDrawer#232]
Hi!

I am using Drawer with Toolbar and i want that the first item from the drawer list should be selected by default. 

I am trying with following code:

Drawer.Result result = new Drawer()
                .withActivity(this)
                .withSelectedItem(1)
                .withToolbar(mToolbar)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("Home"),
                        new DividerDrawerItem(),
                        new SecondaryDrawerItem().withName("Settings")
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id, IDrawerItem drawerItem) {
                        // do something with the clicked item :D
                    }
                })
                .build();

        //use the result object to get different views of the drawer or modify it's data
        //some sample calls
        result.setSelectionByIdentifier(1);

Thanks.

**Comment by mikepenz** [comment]
You have to options you can select the item by position or by identifier. 

position is 0 indexed :D so `.setSelectedItem(0) `
or by identifier but then you have to pass the identifier to the DrawerItem like `.withIdentifier(1)`

just check out the sample app.

**Comment by Shajeel-Afzal** [comment]
Thanks Mike but 0 is also not working.

On Fri, Apr 17, 2015 at 11:48 PM, Mike Penz <notifications@github.com>
wrote:

> Closed #232 <https://github.com/mikepenz/MaterialDrawer/issues/232>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikepenz/MaterialDrawer/issues/232#event-284155789>.
>



-- 

*Shajeel  Afzal*
Call: +923003419643 | Skype: shajeel.voice
<http://pk.linkedin.com/in/shajeelafzal/>
<http://facebook.com/shajeel.afzal>
<https://plus.google.com/+shajeelafzal/> [image: enter image description
here] <https://twitter.com/ShajeelAfzal>

**Comment by mikepenz** [comment]
@Shajeel-Afzal 0 should work for the withSelectedItem method :D

**Comment by Shajeel-Afzal** [comment]
Mike believe me it is not working :(
![screen shot 2015-04-17 at 11 53 04 pm](https://cloud.githubusercontent.com/assets/3718283/7208841/ff971dbe-e55c-11e4-9556-66ef3045c38b.png)

**Comment by mikepenz** [comment]
@Shajeel-Afzal probably you have overwritten the colors or you use the wrong theme.

**Comment by Shajeel-Afzal** [comment]
This is my theme. 

<style name="AppBaseTheme" parent="MaterialDrawerTheme.Light.DarkToolbar"></style>

    
    <style name="AppTheme" parent="AppBaseTheme">
        <item name="windowActionBar">false</item>
        <item name="colorPrimary">@color/primary</item>
        <item name="colorPrimaryDark">@color/primary_dark</item>
        <item name="colorAccent">@color/accent</item>
        <item name="android:textColorPrimary">@color/primary_text</item>
    </style>

**Comment by mikepenz** [comment]
@Shajeel-Afzal ok the theme seems correct :D You don't need the windowActionBar false :D

hmmm then it's strange. but it's working for everyone else and in the sample :/

what are the rgb values of the priamry, primarydark, coloraccent?

**Comment by Shajeel-Afzal** [comment]
This is how it looks like when i select it. 

![screen shot 2015-04-17 at 11 57 03 pm](https://cloud.githubusercontent.com/assets/3718283/7208922/7ab29ae6-e55d-11e4-8e62-b784400a6434.png)

**Comment by mikepenz** [comment]
so if you do 
`.withSelectedItem(0)`

and remove the 
`result.setSelectionByIdentifier(1); `

it's not working?

**Comment by Shajeel-Afzal** [comment]
Removing `result.setSelectionByIdentifier(1);` worked :+1: thanks for your precious time.

**Comment by mikepenz** [comment]
@Shajeel-Afzal just as an info. setSElectionByIdentifier won't find an item with an identifier of `1` because you have not set identifiers for your items. so it will just select none.
