### ISSUE TITLE
ExpandableBadgeDrawerItem Arrow

### ISSUE THREAD

**Issue by cherolopez56** [mikepenz/MaterialDrawer#2320]
is it possible change de arrow indicator with an images?, one to expand one to collapse

![update_cerrar_null](https://user-images.githubusercontent.com/22398584/41955590-425db9d8-79a6-11e8-806f-3cd3e97c7db0.png)
![ver_mas](https://user-images.githubusercontent.com/22398584/41955591-427904ae-79a6-11e8-9979-de260bd0f53c.png)

**Comment by mikepenz** [comment]
you need to implement your own custom drawer item for this requirement
