### ISSUE TITLE
Item unclickable after update

### ISSUE THREAD

**Issue by sbruno-tupaca** [mikepenz/MaterialDrawer#2323]
Hi Mike, I'm using the latest version of MaterialDrawer(6.0.8) and sometimes after an updateItem() that item becomes unclickable.
Even if that item doesn't change visually, after the update the item doesn't even fire the click events.
I must highlight the fact that this doesn't always happen, it appears to happen at random.

Do you have any idea what could be the problem? I'm suspecting the adapter.

Thanks!

**Comment by mikepenz** [comment]
what do you change the item to? do you disable it? do you change it somehow? do you select it? do you change it on a non ui thread?

**Comment by sbruno-tupaca** [comment]
The drawer item shows a custom view that I would like to change on a certain event of my app, but even if I don´t change anything of the view itself, after the updateItem() it becomes unclickable. The item remains enabled and selectable, and it doesn't have to be selected at the time of the update for this bug to happen.
Both the change of the item and the updateItem() run on the UI thread.
I forgot to mention that, if after the update the item becomes unclickable, closing the drawer and opening it again solves this, it becomes clickable/selectable again.

**Comment by mikepenz** [comment]
Can you reproduce it somehow in the sample app or create a showcase too show it?

**Comment by mikepenz** [comment]
Please report back with additional information :)

Close for now. Simply re-open if relevant
