### ISSUE TITLE
How can I disable Auto RTL?

### ISSUE THREAD

**Issue by nabeghe** [mikepenz/MaterialDrawer#2324]
I created a drawer on the left side, but my RTL Language show in right and Icons show in left!
How to disable RTL? Of course, I don't want the drawer to be on the right side.

**Comment by nabeghe** [comment]
I solved this problem by Custom Drawer Item and using reflection, apache commons-lang3:

`public class EnhancedPrimaryDrawerItem extends PrimaryDrawerItem {

  @SuppressLint("RtlHardcoded")
  private int textGravity = Gravity.LEFT;

  public EnhancedPrimaryDrawerItem withGravityForText(int gravity) {
    textGravity = gravity;
    return this;
  }

  @Override
  protected void bindViewHelper(BaseViewHolder viewHolder) {
    try {
      ((TextView) FieldUtils.readField(viewHolder, "name", true))
              .setGravity(textGravity);
    } catch (Exception ignored) {
    }
    try {
      ((TextView) FieldUtils.readField(viewHolder, "description", true))
              .setGravity(textGravity);
    } catch (IllegalAccessException ignored) {
    }
    super.bindViewHelper(viewHolder);
  }

}`

but can't do same in ProfileDrawerItem and the below custom ProfileDrawerItem, don't run the bindView method:

`public class EnhancedProfileDrawerItem extends ProfileDrawerItem {

  @SuppressLint("RtlHardcoded")
  private int textGravity = Gravity.LEFT;

  public EnhancedProfileDrawerItem withGravityForText(int gravity) {
    textGravity = gravity;
    return this;
  }

  @Override
  public void bindView(ViewHolder viewHolder, List payloads) {
    logD("bindView");
    try {
      LinearLayout              view = (LinearLayout) FieldUtils.readField(viewHolder, "view", true);
      LinearLayout.LayoutParams lllp = (LinearLayout.LayoutParams) view.getLayoutParams();
      lllp.gravity = textGravity;
      view.setLayoutParams(lllp);
    } catch (Exception ignored) {

    }
    try {
      ((TextView) FieldUtils.readField(viewHolder, "name", true))
              .setGravity(textGravity);
    } catch (Exception ignored) {
    }
    super.bindView(viewHolder, payloads);
  }
  
}`

**Comment by mikepenz** [comment]
you can not really change the RTL behaviour as it is handled by android. either you disable RTL at all or you use it. 

You can also implement your own custom items, for normal drawer and for profiles which do the layouts in hardcoded way like you want them to be.

Please see past github issues as mentioned
