### ISSUE TITLE
cannot resolve com.mikepenz:materialdrawer library android

### ISSUE THREAD

**Issue by harshagrawal6763** [mikepenz/MaterialDrawer#2326]
cannot resolve com.mikepenz:materialdrawer library android 
i keep getting this error when i try to sync my gradle

**Comment by mikepenz** [comment]
which version?

**Comment by mikepenz** [comment]
It's available on jcenter
https://bintray.com/mikepenz/maven/com.mikepenz%3Amaterialdrawer/6.0.8#files/com/mikepenz/materialdrawer

**Comment by harshagrawal6763** [comment]
for version 6.0.2
