### ISSUE TITLE
Custom ActionBarDrawerToggle

### ISSUE THREAD

**Issue by hatamiarash7** [mikepenz/MaterialDrawer#2327]
Hi
How can i add a custom `ActionBarDrawerToggle` ? I want add Translation for my base layout but there is some problems

To do that we should write some codes like these : 

```
ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(activity, drawerLayout, R.string.material_drawer_open, R.string.material_drawer_close) {
			@Override
			public void onDrawerSlide(View drawerView, float slideOffset) {
				super.onDrawerSlide(drawerView, slideOffset);
			}
		};

drawer = new DrawerBuilder()
			.withActivity(activity)
			.withToolbar(toolbar)
			.withActionBarDrawerToggleAnimated(true)
			.withActionBarDrawerToggle(toggle)
                        ...

```

We need a `drawerLayout` here.

```
public ActionBarDrawerToggle(Activity activity, DrawerLayout drawerLayout,
            @StringRes int openDrawerContentDescRes,
            @StringRes int closeDrawerContentDescRes)
```
How can i have it? if i use `drawer.getDrawerLayout()`, there will be an Null Exception. And we should write `ActionBarDrawerToggle ` just before drawer, so we can use `.withActionBarDrawerToggle(toggle)`

I'm a bit confused.

**Comment by mikepenz** [comment]
You can use any custom one. but it won't be handled with the MaterialDrawer then. 

Simply do not provide the Toolbar in that case , and call open / clos eaccordingly

**Comment by hatamiarash7** [comment]
In my case, we can use `null` for `drawerLayout` parameter here

```
new ActionBarDrawerToggle(activity, << null >>, R.string.material_drawer_open, R.string.material_drawer_close) {
			@Override
			public void onDrawerSlide(View drawerView, float slideOffset) {
				super.onDrawerSlide(drawerView, slideOffset);
			}
		};
```

Everything works fine.
