### ISSUE TITLE
Some informations

### ISSUE THREAD

**Issue by Angelk90** [mikepenz/MaterialDrawer#2328]
Hi @mikepenz : 

Congratulations on the module, I wanted to know some information.

1) How many accounts can I view as a second account, I talk about the images?
![dsd](https://user-images.githubusercontent.com/20476002/42177216-3f0cbc68-7e2c-11e8-9f0f-a35712c47c08.png)

2) Could you have more information about all the functions that are implemented?
3) It would be interesting to be able to use if you want instead of the user's image, the material letter icon, I recommend this one: https://github.com/IvBaranov/MaterialLetterIcon
4) I tried app, I happened this strange bug, at least I think.

  ![](https://i.imgur.com/VDRUM6h.jpg)

**Comment by mikepenz** [comment]
2 by default, and max 3. the rest will only show up in the list for profiles
