### ISSUE TITLE
Error:Failed to resolve: com.mikepenz:library-core:3.2.6

### ISSUE THREAD

**Issue by Angelk90** [mikepenz/MaterialDrawer#2329]
Hi @mikepenz, 

I am given the following error:
`Error: Failed to resolve: com.mikepenz: library-core: 3.2.6`
when I try to put the following code in the build.gradle file:
```
implementation("com.mikepenz:materialdrawer:6.0.8@aar") {
        transitive = true
    }
```

My build.gradle:
```
buildscript {
    repositories {
        jcenter()
        maven { url "https://maven.google.com" }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}

repositories {
    mavenCentral()
    maven { url "https://maven.google.com" }
}

dependencies {
    implementation("com.mikepenz:materialdrawer:6.0.8@aar") {
        transitive = true
    }
    implementation "com.android.support:appcompat-v7:27.1.1"
    implementation "com.android.support:recyclerview-v7:27.1.1"
    implementation "com.android.support:support-annotations:27.1.1"
    implementation "com.android.support:design:27.1.1"
    implementation 'com.facebook.react:react-native:+'
}
```

**Comment by mikepenz** [comment]
something requests an old dependency of the fastAdapter. If you download the POM here: https://bintray.com/mikepenz/maven/com.mikepenz%3Amaterialdrawer/6.0.8#files/com%2Fmikepenz%2Fmaterialdrawer%2F6.0.8
it will show that it wants the fast adapter 3.2.7 

try to refresh the dependencies

**Comment by Angelk90** [comment]
@mikepenz : I did not understand.
It seems that the problem is: 
```
{
         transitive = true
     }
```

**Comment by Angelk90** [comment]
@mikepenz : How do I use the link provided? never used it.

**Comment by mikepenz** [comment]
What I am saying. as of the definition of the repo it should try to get the v3.2.7 of the fastAdapter not v 3.2.6 as shown in your sample. can you try to call:

```
./gradlew clean build --refresh-dependencies
```` 

(unix cli command)

it will redownload all pom's and the libraries to ensure you have the latest state

**Comment by Angelk90** [comment]
@mikepenz : 
```
BUILD FAILED in 58s
2 actionable tasks: 2 executed
```

**Comment by mikepenz** [comment]
if you do a gradle sync now. and build will it work?

**Comment by mikepenz** [comment]
In that case I think you should go with 6.0.6 or older and wait until there is a new release

**Comment by Angelk90** [comment]
@mikepenz : I'm given this error: 
```
Could not find method implementation () for arguments [com.mikepenz: materialdrawer: 6.0.6@aar, build_5wgik6y7y3yvazx4wo7syiyti $ _run_closure3 $ _closure7 @ 1d7f2f0a] on object of type org
.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Comment by mikepenz** [comment]
seems like you copied some invisible characters. please remove them

**Comment by Angelk90** [comment]
@mikepenz : What should I remove?
The build.gradle file is the one I posted, tell me what should I remove?

**Comment by mikepenz** [comment]
`arguments [com.mikepenz: materialdrawer: 6.0.6@aar,` the error message shows spaces. it seems to me like there are invalid characters. which cause problems. 


v6.0.6 exists on jcenter correctly: https://bintray.com/mikepenz/maven/com.mikepenz%3Amaterialdrawer#files/com%2Fmikepenz%2Fmaterialdrawer%2F6.0.6

**Comment by Angelk90** [comment]
@mikepenz : 
I'm not understanding where I'm wrong, the error is given to me right on the line where I enter:
```
implementation ("com.mikepenz: materialdrawer: 6.0.6@aar") {
         transitive = true
     }
```
just his line:
`... \ android \ build.gradle 'line: 35`



https://pastebin.com/raw/gSw4JRpG

**Comment by mikepenz** [comment]
<img width="469" alt="screen shot 2018-07-03 at 00 07 16" src="https://user-images.githubusercontent.com/1476232/42188627-0eb0e912-7e55-11e8-9622-15cac655212c.png">

you posted it yourself. there are characters after ":" sign. 

it has to be:

```gradle
implementation ("com.mikepenz:materialdrawer:6.0.6@aar") {
         transitive = true
}
```

**Comment by Angelk90** [comment]
@mikepenz : Look at the pastebin, that's the right thing.

**Comment by mikepenz** [comment]
You miss 

```
 jcenter()
```

in repositories
