### ISSUE TITLE
Selecting item at same time as update causes issues

### ISSUE THREAD

**Issue by jdepypere** [mikepenz/MaterialDrawer#2335]
## About this issue

While trying to figure out an issue with having icon tinting sometimes tinting the wrong icon after a badge update I stumbled upon another issue that I can't seem to fix. I have a callback that updates the badge value. If you have item B selected, you then select item A and around the same time the badge of item A is updated, item A gets briefly selected and then gets deselected again.

Here's my sample code:

``` java
new DrawerBuilder()
    .withActivity(this)
    .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
        @Override
        public boolean onItemClick(View view, int position, final IDrawerItem drawerItem) {
            if (drawerItem.getIdentifier() == 1L) // no delay for our first element
                return true;

            final Handler handler = new Handler(Looper.getMainLooper());
            handler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    Log.d("MainAct", "On main thread: " + (Looper.myLooper() == Looper.getMainLooper()));
                    drawer.updateBadge(1L, new StringHolder("1"));
                    drawer.updateBadge(2L, new StringHolder("10"));
                }
            }, 1000);
            return true;
        }
    })
    .addDrawerItems(
            new SecondaryDrawerItem()
                    .withName("Item 1")
                    .withIdentifier(1L)
                    .withBadge("1")
                    .withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.md_red_700))
                    .withIcon(R.drawable.ic_android_black_24dp)
                    .withIconTintingEnabled(true),
            new SecondaryDrawerItem()
                    .withName("Item 2")
                    .withIdentifier(2L)
                    .withBadge("10")
                    .withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.md_red_700))
                    .withIcon(R.drawable.ic_android_black_24dp)
                    .withIconTintingEnabled(true))
    .build();
```
To replicate, select the second item in the list. After 1 second select the first item. If done right, no items will be selected.

Because I've seen quite a few threading issues I triple checked that the code is running on the main looper which seems to be the case. Also, after rotating the device the correct item is selected again.

## Details
- Used library version: 6.0.6
- Used support library version: 27.0.2
- Used gradle build tools version: 3.1.3
- Used tooling / Android Studio version: AS 3.1.3
- Other used libraries, potential conflicting libraries: nope

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by jdepypere** [comment]
I'm aware that in this case the handler is unnecessary, but it does illustrate my use case.

My use case is the following: when the drawer is opened some network tasks are started to get the unread amount if items in that item. When they are done they update the badge of the corresponding items. It does indeed seem as though the view isn't updated correctly. Clicking on the item that shows deselected but should be selected also results in no action. After rotating the device it is selected correctly again.

Is there another way to fix this?

**Comment by mikepenz** [comment]
hmmm can you try to notify the adapter about changes. will it adjust?

**Comment by jdepypere** [comment]
Adding `drawer.getAdapter().notifyAdapterDataSetChanged();` after the `.updateBadge()` does indeed seem to work. Can't seem to get notifying the adapter about a single change to work though.

**Comment by mikepenz** [comment]
hmmm do you have a header? is the position off by 1 if you try to notify the single change?

**Comment by jdepypere** [comment]
In this example I don't have a header no. I've tried offsetting the notifies but haven't had any success strangely. Notifying the whole adapter seems to work just fine though and isn't impacting performance too much, if I get around to it I'll try and dig a little deeper but for now the workaround is ok. Awesome library btw!
