### ISSUE TITLE
Drag menu

### ISSUE THREAD

**Issue by wiltonbarros** [mikepenz/MaterialDrawer#2336]
Hi @mikepenz, 

When i click in hamburguer menu the menu is show, when i drag left to right show a null blank menu, like the image.
How can i override this event to show the right menu?
Thanks.
![print menu](https://user-images.githubusercontent.com/23128619/42704197-59ea8bf6-86a5-11e8-9aa6-c9555ba2b875.jpg)

**Comment by mikepenz** [comment]
Please see the sample app on how to add items. 

If you set the gravity to be right and you only have one menu it should show it. this behaviour comes automatically from the ActionbarDrawerToggle and is not handled by the library. if it does not owkr you will have to handle it manually. simply do not pass the Toolbar in that case and hanllde it manually
