### ISSUE TITLE
Allow latest specs selected item style

### ISSUE THREAD

**Issue by jahirfiquitiva** [mikepenz/MaterialDrawer#2337]
## About this issue

Hello Mike

I wanted to ask you to add an option to show the selected state of items, just as the latest [material design guidelines](https://material.io/design/components/navigation-drawer.html#anatomy) showcase.

Thanks in advance

![anatomy](https://user-images.githubusercontent.com/10360816/42719387-4d62a762-86da-11e8-8a3b-e42b1c5f9cf3.png)

## Details
- [x] Used library version
- [x] Used support library version
- [x] Used gradle build tools version
- [x] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@jahirfiquitiva there are plans to update to the new guidelines as soon as the new design support libraries are final. :). Currently you can only achieve this by using a custom drawer item :)
