### ISSUE TITLE
Proguard erroring out when using MD as a module

### ISSUE THREAD

**Issue by rpgdev** [mikepenz/MaterialDrawer#2339]
## About this issue

I did a couple of modifications to your library a while back because I needed it to behave differently. Then I imported it as an aar module into my project and it worked fine-- until I started to use proguard on it.  For some reason it gives me this error:

> 16:11:42.719 [ERROR] [system.err] Warning: com.mikepenz.materialdrawer.model.ExpandableBadgeDrawerItem: can't find referenced class com.mikepenz.iconics.view.IconicsImageView
> 16:11:42.719 [ERROR] [system.err] Warning: com.mikepenz.materialdrawer.model.ExpandableBadgeDrawerItem: can't find referenced class com.mikepenz.iconics.view.IconicsImageView
> 16:11:42.719 [ERROR] [system.err] Warning: com.mikepenz.materialdrawer.model.ExpandableBadgeDrawerItem: can't find referenced class com.mikepenz.iconics.view.IconicsImageView
> 16:11:42.719 [ERROR] [system.err] Warning: com.mikepenz.materialdrawer.model.ExpandableBadgeDrawerItem: can't find referenced class com.mikepenz.iconics.view.IconicsImageView
> 16:11:42.720 [ERROR] [system.err] Warning: com.mikepenz.materialdrawer.model.ExpandableBadgeDrawerItem$ViewHolder: can't find referenced class com.mikepenz.iconics.view.IconicsImageView
> 16:11:42.720 [ERROR] [system.err] Warning: com.mikepenz.materialdrawer.model.ExpandableBadgeDrawerItem$ViewHolder: can't find referenced class com.mikepenz.iconics.view.IconicsImageView
> 16:11:42.720 [ERROR] [system.err] Warning: com.mikepenz.materialdrawer.model.ExpandableBadgeDrawerItem$ViewHolder: can't find referenced class com.mikepenz.iconics.view.IconicsImageView
> 16:11:42.720 [ERROR] [system.err] Warning: com.mikepenz.materialdrawer.model.ExpandableDrawerItem: can't find referenced class com.mikepenz.iconics.view.IconicsImageView
> 16:11:42.720 [ERROR] [system.err] Warning: com.mikepenz.materialdrawer.model.ExpandableDrawerItem: can't find referenced class com.mikepenz.iconics.view.IconicsImageView
> 16:11:42.720 [ERROR] [system.err] Warning: com.mikepenz.materialdrawer.model.ExpandableDrawerItem: can't find referenced class com.mikepenz.iconics.view.IconicsImageView
> 16:11:42.720 [ERROR] [system.err] Warning: com.mikepenz.materialdrawer.model.ExpandableDrawerItem: can't find referenced class com.mikepenz.iconics.view.IconicsImageView
> 16:11:42.721 [ERROR] [system.err] Warning: com.mikepenz.materialdrawer.model.ExpandableDrawerItem$ViewHolder: can't find referenced class com.mikepenz.iconics.view.IconicsImageView
> 16:11:42.721 [ERROR] [system.err] Warning: com.mikepenz.materialdrawer.model.ExpandableDrawerItem$ViewHolder: can't find referenced class com.mikepenz.iconics.view.IconicsImageView
> 16:11:42.721 [ERROR] [system.err] Warning: com.mikepenz.materialdrawer.model.ExpandableDrawerItem$ViewHolder: can't find referenced class com.mikepenz.iconics.view.IconicsImageView

I have added a couple of proguard rules in order to keep the classes in your namespace unobfuscated without any luck. The version of the library I made my modification of was 5.8.1.

For perspective, AS also fails to build the project with proguard for the latest version pushed here if I add it as an aar module without any modifications... I know that's not the common use case but it shows that it has nothing to do with the modification I did to the project. 

I know that custom builds are not supported here but hopefully you can point me in the right direction. Proguard config is bizantine to me and I'm out of ideas.

**Comment by mikepenz** [comment]
You include the library properly including the transitive: https://github.com/mikepenz/MaterialDrawer#1-provide-the-gradle-dependency ?

**Comment by rpgdev** [comment]
I was using the lib as an .aar and imported it as a module, I don't know if you can use the transitive property for those. Anyways, thanks for answering. It seems the problem was that I had updated the Iconics lib I was using while keeping the old MD. I went back to the one I was using with the project and now it's working again. I will update each lib eventually but it will take time and I don't remember how I managed to get MD to behave the way I wanted it to.
