### ISSUE TITLE
colorPrimary is not reflected in task switcher when using MaterialDrawerTheme

### ISSUE THREAD

**Issue by meetshawn** [mikepenz/MaterialDrawer#234]
Specifically I noticed this using the no action bar variants. Also, when the app is starting that same blue color is visible in the status bar for a brief moment, before my chosen app colors are applied.

MaterialDrawerTheme:
The blue color is NOT my colorPrimary and not a color I have set anywhere for anything!
![MaterialDrawerTheme](http://i.imgur.com/D8vZ4r7m.png)

AppCompat Theme:
My colorPrimary is applied to the task switcher preview.
![AppCompat Theme](http://i.imgur.com/uaK5B3Lm.png)

The only functional difference between the two is the use of AppCompat theme in one image, and a minimal drawer with the MaterialDrawer equivalent theme.

**Comment by mikepenz** [comment]
@meetshawn how do you set the colors in the theme?

**Comment by raghunandankavi2010** [comment]
@mikepenz this happens on lollipop devices only (Guessing). May be we need to defines styles in styles v21?

**Comment by mikepenz** [comment]
@raghunandankavi2010 color working in my apps. so i've asked how he sets the color

**Comment by raghunandankavi2010** [comment]
@mikepenz i too noticed the same in my app. I used the below

         <style name="CustomTheme" parent="MaterialDrawerTheme.Light.DarkToolbar">
        
        <item name="colorPrimary">@color/orange_primary</item>
        <item name="colorPrimaryDark">@color/orange_primary_dark</item>
        <item name="colorAccent">@color/orange_primary</item>

        
        <item name="material_drawer_window_background">@color/material_drawer_window_background</item>
        <item name="material_drawer_background">@color/material_drawer_background</item>
        <item name="material_drawer_icons">@color/material_drawer_icons</item>
        <item name="material_drawer_primary_text">@color/material_drawer_primary_icon</item>
        <item name="material_drawer_primary_icon">@color/material_drawer_primary_icon</item>
        <item name="material_drawer_secondary_text">@color/material_drawer_secondary_text</item>
        <item name="material_drawer_hint_text">@color/material_drawer_hint_text</item>
        <item name="material_drawer_divider">@color/material_drawer_divider</item>
        <item name="material_drawer_selected">@color/material_drawer_selected</item>
        <item name="material_drawer_selected_text">@color/orange_primary</item>
        <item name="material_drawer_header_selection_text">@color/material_drawer_header_selection_text</item>
    </style>

**Comment by mikepenz** [comment]
ok interesting. can you try to do the same vor values-v21? and setting android:colorPrimary too?

**Comment by raghunandankavi2010** [comment]
@mikepenz  sure it does not happen on pre lollipop

**Comment by mikepenz** [comment]
@raghunandankavi2010 pre lollipop devices do not support the color defined from the primaryColor :D

**Comment by raghunandankavi2010** [comment]
@mikepenz i get that. its the toolbar color.

**Comment by mikepenz** [comment]
don't forget to set android:colorPrimary, android:colorPrimaryDark and android:colorAccent

**Comment by raghunandankavi2010** [comment]
@mikepenz  i still see the same issue even with values-v21/styles

**Comment by mikepenz** [comment]
@raghunandankavi2010 have you defined the values with android: in there?

**Comment by raghunandankavi2010** [comment]
@mikepenz i forgot!.

**Comment by mikepenz** [comment]
@raghunandankavi2010 :D please add them and try it again ;)

**Comment by raghunandankavi2010** [comment]
@mikepenz strange i thought it should work. Nope. values-21/styles.xml

         <item name="android:colorPrimary">@color/orange_primary</item>
        <item name="android:colorPrimaryDark">@color/orange_primary_dark</item>
        <item name="android:colorAccent">@color/orange_primary</item>

Am i missing something here??

**Comment by mikepenz** [comment]
interesting. I'll try something later today. probably i can improve the styles.

**Comment by mikepenz** [comment]
@raghunandankavi2010 i've made the step with android:... obsolete. should work now by simply overriting colorPrimary

**Comment by raghunandankavi2010** [comment]
@mikepenz that seems to fix the issue. thanks.

**Comment by meetshawn** [comment]
@mikepenz yes working as expected now

**Comment by mikepenz** [comment]
Great ;)
