### ISSUE TITLE
Drawer Discription Issues 

### ISSUE THREAD

**Issue by mostafazaghlol** [mikepenz/MaterialDrawer#2345]
## About this issue

- When I open the drawer I found that the description is not full appear ? How I can solve This ?
![index](https://user-images.githubusercontent.com/19761838/43776315-be051a94-9a4f-11e8-896f-97863f9783a9.jpeg)

**Comment by mikepenz** [comment]
@mostafazaghlol if the default items do not work as you want them, you can implement your own customer drawer items as mentioned in the FAQ :)
