### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by sajjadjaved01** [mikepenz/MaterialDrawer#2347]
## About this issue

- Briefly describe the issue
Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.0-rc01] AndroidManifest.xml:22:18-86	is also present at [com.android.support:support-compat:28.0.0-rc01] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-20:19 to override.

- How can the issue be reproduced / sample code
add this in your build gradle. implementation 'com.mikepenz:materialdrawer:6.1.0-rc01'

## Checklist

- [ x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@sajjadjaved01 if you do not use androidX yet please use a version lower than 6.1.0.

**Comment by mikepenz** [comment]
Please report back. close for now

**Comment by sajjadjaved01** [comment]
Thanks, solved by using a lower version. ✔👍
