### ISSUE TITLE
How to update views in a custom PrimaryDrawerItem?

### ISSUE THREAD

**Issue by afarber** [mikepenz/MaterialDrawer#2349]
Hello and thank you for your library!

I am using it (and also FastAdapter) to create left and right drawers in my app and currently I use a compact style account header in the right drawer (see the green area with user photo in the below screenshot).

However I need few more text fields there, so I would like to switch - and use a custom PrimaryDrawerItem (please see the magenta area in the below screenshot).

I have studied the guides listed at https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md and have tried creating such an item with an ImageView and two TextViews here:

```
public class RightDrawerItem extends AbstractDrawerItem<RightDrawerItem, RightDrawerItem.ViewHolder> {

    public String photo;
    public String given;
    public String score;

    @Override
    public int getType() {
        return R.id.right_drawer_item_id;
    }

    @Override
    @LayoutRes
    public int getLayoutRes() {
        return R.layout.right_drawer_item;
    }

    @Override
    public void bindView(ViewHolder vh, List<Object> payloads) {
        super.bindView(vh, payloads);

        Context ctx = vh.itemView.getContext();
        if (ctx.getApplicationContext() instanceof SlovaApplication) {
            SlovaApplication app = (SlovaApplication) ctx.getApplicationContext();

            if (URLUtil.isHttpsUrl(photo)) {
                app.getPicasso()
                        .load(photo)
                        .placeholder(R.drawable.account_gray)
                        .into(vh.mPhoto);
            }
        }

        vh.mGiven.setText(given);
        vh.mScore.setText(score);

        //call the onPostBindView method to trigger post bind view actions (like the listener to modify the item if required)
        onPostBindView(this, vh.itemView);
    }

    @Override
    public ViewHolder getViewHolder(View v) {
        return new ViewHolder(v);
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public void setGiven(String given) {
        this.given = given;
    }

    public void setScore(String score) {
        this.score = score;
    }

    public static class ViewHolder extends RecyclerView.ViewHolder {
        private ImageView mPhoto;
        private TextView mGiven;
        private TextView mScore;

        private ViewHolder(View view) {
            super(view);

            view.setBackgroundColor(Color.MAGENTA);

            mPhoto = view.findViewById(R.id.photo);
            mGiven = view.findViewById(R.id.given);
            mScore = view.findViewById(R.id.score);
        }
    }
}

```

My problem is that when I call 

```
mRightDrawerItem.setPhoto(...);
mRightDrawerItem.setGiven(...);
mRightDrawerItem.setScore(...);
```

then the views my custom PrimaryDrawerItem are not updated, as you can see in the screenshot:

![screen shot 2018-08-19 at 17 50 09](https://user-images.githubusercontent.com/1884458/44310684-a4ed1900-a3da-11e8-9de7-df6b6419ecd5.png)

Also, I am not quite sure what exactly is the `vh.itemView`?

Please give me some hints

## Details
- [6.0.8] Used library version
- [27.1.1] Used support library version
- [4.6] Used gradle build tools version

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@afarber as the Drawer is nothing else than a RecyclerView with elements (thus the items are based on the same approach like the items your create for the FastAdapter (theoretically fastAdapter items can be used by additionally implementing the IDrawerItem interface, and drawer items simply in any list)) 

So that means whenever you adjust fields of an element, you will need to notify the adapter about the update to the item ;)
The `MaterialDrawer` comes with convenient functions like: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L654
But you can also go to the roots of the adapter. Get the adapter: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L654 and then update the item as you know it from the fastAdapter ;)

Also the same rules like in the FastAdapter applies. You can use a `payload` (if you update via the adapter) to optimize adjustments

**Comment by afarber** [comment]
Thank you, this has worked
