### ISSUE TITLE
Change navigation bar background color dinamically

### ISSUE THREAD

**Issue by serandel** [mikepenz/MaterialDrawer#235]
Hi!

In my app I can go in and out of immersive mode. 

I'm changing the status bar color to android.R.color.transparent when going immersive, so I don't end with color bands at the top and at the bottom of the screen. It works without problem.

The thing is, when showing again navigation and status, I succesfully change the status bar back to a semitransparent color but I want the navigation bar to remain transparent, and it gets the same color than the status bar.

Is there any way to achieve this? Thanks!

**Comment by mikepenz** [comment]
@serandel i'm not sure if this is something which is MaterialDrawer specific?

**Comment by serandel** [comment]
If I don't use the library, I can simply

    getWindow().setStatusBarColor(getResources().getColor(R.color.primary_dark));

and the status bar gets red, i.e., but the navigation bar remains translucid black, its default color. I think it's because MaterialDrawer uses a ScrimInsetsFrameLayout, that keeps status and navigation the same color, by using a single ```ColorDrawable``` as ```mInsetForeground```.

**Comment by mikepenz** [comment]
@serandel oh i see. never had the case of a different colored navigationbar so i never came to this issue.  seems like a more complex issue then. never saw a multi colored scrimInsetsLayot :D

**Comment by serandel** [comment]
This is what I was trying to do. :)

![snikt](https://dl.dropboxusercontent.com/u/688658/snikt.png)

**Comment by mikepenz** [comment]
@serandel have you looked at the fullscreen sample

**Comment by mikepenz** [comment]
@serandel if still an issue please reopen

**Comment by MFlisar** [comment]
A layout like the one in the picture above works, but what if I want a custom color for the navigation bar? `wnidow.setStatusBarColor(...);` is not working... Using a view in the layout is not working either, because the navigation bar only is semi transparent and not completely transparent...

**Comment by mikepenz** [comment]
@MFlisar the `StatusBar` color can be set via the  `DrawerLayout`

**Comment by MFlisar** [comment]
My fault, I meant navigation bar color...

**Comment by mikepenz** [comment]
@MFlisar you have to google for that. Not sure if this can be controlled via the DrawerLayout or somewhere else. (if at all)

**Comment by MFlisar** [comment]
Actually, I think this feature is blocked, because of the insets method you use with the drawer...

**Comment by mikepenz** [comment]
@MFlisar shouldn't be blocked all the things are managed by the system via the `fitsSystemWindows` flag, and the normal `DrawerLayout`
