### ISSUE TITLE
How to use withDrawerLayout()?

### ISSUE THREAD

**Issue by bios90** [mikepenz/MaterialDrawer#2350]
## About this issue
How can i pass custom xml layout into MaterialDrawer?

I made custom class that extends DrawerLayout

    public class MyDrawerClass extends android.support.v4.widget.DrawerLayout
    {
        private static final String TAG = "MyDrawerClass";
        public MyDrawerClass(@NonNull Context context)
    {
        super(context);
        CustomInit();
    }

    public MyDrawerClass(@NonNull Context context, @Nullable AttributeSet attrs)
    {
        super(context, attrs);
        CustomInit();
    }

    public MyDrawerClass(@NonNull Context context, @Nullable AttributeSet attrs, int defStyle)
    {
        super(context, attrs, defStyle);
        CustomInit();
    }

    void CustomInit()
    {
        Log.e(TAG, "Custominit: I finally made!");
    }
    }

Than i created custom material_drawer.xml

    `<?xml version="1.0" encoding="utf-8"?
    <dimfcompany.com.drawertest2.Helpers.MyDrawerClass
    android:background="@color/colorAccent"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/material_drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">
    
     </dimfcompany.com.drawertest2.Helpers.MyDrawerClass>``

Than in my activity i use this to create custom DrawerLayout

`Drawer drawer = new DrawerBuilder().withActivity(this).withToolbar(toolbar).withDrawerLayout(R.layout.material_drawer).build();`

But i get blank default style layout. 

What i am doing wrong?
Thanks!)

## Details
- [6.0.9 ] Used library version
- [28.0.0 ] Used support library version
- [3.1.1 ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

**Comment by mikepenz** [comment]
you don't seem to provide items. without any additional configuration you just get the drawer inflated.


Add items and stuff :)

**Comment by bios90** [comment]
Thanks for answer but i still do not understand what is the purpose of withDrawerLayout()?
For example in my custom custom material_drawer.xml i changed background color and add button, but when app runs i still get full default layout. It is impossible to make full custom layout and just load it into drawer?

     `<dimfcompany.com.drawertest2.Helpers.MyDrawerClass
    android:background="@color/colorAccent"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/material_drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <RelativeLayout
        android:layout_margin="48dp"
        android:background="@android:color/holo_orange_dark"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        
        <Button
            android:text="Test Button"
            android:layout_centerInParent="true"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
     </RelativeLayout>
     </dimfcompany.com.drawertest2.Helpers.MyDrawerClass>`

**Comment by mikepenz** [comment]
@bios90 it allows you to provide a custom implementation of a `DrawerLayout` nothing else, it does not allow you to add any ui parts. 

If you want a drawer with your own views, you do not need this library.

**Comment by bios90** [comment]
Ok All clear thanks for answers.

**Comment by mikepenz** [comment]
You are welcome
