### ISSUE TITLE
Cannot make status bar completely transparent

### ISSUE THREAD

**Issue by shailesh369** [mikepenz/MaterialDrawer#2351]
![screenshot from 2018-08-20 21-41-32](https://user-images.githubusercontent.com/3890217/44352641-90844b80-a4c2-11e8-9041-0622043d5893.png)
Background of hamburger remains white
## About this issue

- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Close as unrelated to the library. 

Please check you have the components styled correctly disabled backgrounds and stuff. :)
