### ISSUE TITLE
Account Icon rotating

### ISSUE THREAD

**Issue by Demonic217** [mikepenz/MaterialDrawer#2353]
Greetings, 

I'm having an issue where the account icon is rotating to the side. I suspect it is because of the aspect ratio of the image. If I take a picture in portrait mode, the picture is rotated on it on it's side and the image is displayed horizontally.

If I crop the image to 1:1 the rotation is fine.

```
DrawerImageLoader.init(new AbstractDrawerImageLoader() {
            @Override
            public void set(ImageView imageView, Uri uri, Drawable placeholder, String tag) {
                Glide.with(imageView.getContext()).load(uri).apply(RequestOptions.centerCropTransform()).into(imageView);
            }

            @Override
            public void cancel(ImageView imageView) {
                Glide.with(imageView.getContext()).clear(imageView);
            }

            @Override
            public Drawable placeholder(Context ctx, String tag) {
                if (DrawerImageLoader.Tags.PROFILE.name().equals(tag)) {
                    return DrawerUIUtils.getPlaceHolder(ctx);
                } else if (DrawerImageLoader.Tags.ACCOUNT_HEADER.name().equals(tag)) {
                    return new IconicsDrawable(ctx).iconText(" ").backgroundColorRes(com.mikepenz.materialdrawer.R.color.primary).sizeDp(56);
                } else if ("customUrlItem".equals(tag)) {
                    return new IconicsDrawable(ctx).iconText(" ").backgroundColorRes(R.color.md_red_500).sizeDp(56);
                }

  

                return super.placeholder(ctx, tag);
            }
        });
```

I'm using glide to load the image, I did try and use Glides centerCrop and CircleCrop but it's the same result.

**Comment by Demonic217** [comment]
![inkedscreenshot_20180827-122245_li](https://user-images.githubusercontent.com/20418444/44655108-49cbaf80-a9f4-11e8-9513-c6e092815c6a.jpg)

Here you go.

**Comment by mikepenz** [comment]
@Demonic217 oh the 90° rotation? well this is not related to this library. The BezelImageView used in here will only apply a mask to round the image. 

The rotation itself most likely comes from the image loading library, or it might even come theoretically from the embedded EXIF information telling it to be rotated by 90° (exif has some orientation logic :D) 

You might anyways want to crop it to 1:1 (which most likely ignores / or respects the exif information) to full fill the circle. (or if you do not want to crop, you will need to ensure the rotation is not applied and then modify the scale type to fill the circle)

**Comment by Demonic217** [comment]
I've never heard of EXIF information before but I've found a reader of some sort and Orientation is listed as Rotate 90 CW.

I'll check out cropping solution.

Thanks for your help and speedy replys

**Comment by mikepenz** [comment]
As far as I see you take the picture with the camera. Depending on your camera implementation the camera will add information about the camera and the orientation to the image. 

a very important thing to know is, that the camera's on Android devices are (usually) 90° rotated build in. (so like your picture shows) 
(side note. some devices like the Nexus 5X and Nexus 6P have the camera built in 270° rotated)

Thus the exif information will contain the information that the image is 90° rotated, and if you look at it in a file browser or on a computer this information is used to correctly rotate the image for you.

So I assume the code you used to crop to 1:1 respected the 90° info from the exif and resulted in the proper display. the `ImageView` alone does not do this for you as far as I know.

This stackoverflow article might help you :)

https://stackoverflow.com/questions/14066038/why-does-an-image-captured-using-camera-intent-gets-rotated-on-some-devices-on-a



You are welcome
