### ISSUE TITLE
Is there a possibility to implement similar to 'shiburagi/Drawer-Behavior" in opening drawer?

### ISSUE THREAD

**Issue by emami7495** [mikepenz/MaterialDrawer#2358]
Hi, thanks for your amazing library. Is it possible to implement the effects of opening the drawer that is in this link [https://github.com/shiburagi/Drawer-Behavior] in your library?

**Comment by mikepenz** [comment]
@emami7495 you can use his library and use his implementation of the `DrawerLayout` instead of the default `DrawerLayout` from google.

**Comment by mikepenz** [comment]
Just create an xml like this: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer.xml
but instead using the drawerlayout from that person. 

pass it in using:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L325

and it should be good
