### ISSUE TITLE
BezelImageView.java

### ISSUE THREAD

**Issue by rishirD** [mikepenz/MaterialDrawer#2359]
**ISSUE**
BezelImageView.java line 213
#398com.mikepenz.materialdrawer.view.BezelImageView.onDraw

The attached file is the crash insight from fabric -
[xyz.rishideep.wallon_issue_398_crash_5BA1AC2201660001156915DF54FA55AC_DNE_0_v2.txt](https://github.com/mikepenz/MaterialDrawer/files/2395403/xyz.rishideep.wallon_issue_398_crash_5BA1AC2201660001156915DF54FA55AC_DNE_0_v2.txt)

Is the issue from my side or from the library?

**Comment by mikepenz** [comment]
Which version of the library do you use?

**Comment by rishirD** [comment]
@mikepenz 

implementation('com.mikepenz:materialdrawer:6.0.0@aar') {
        transitive = true
    }

**Comment by mikepenz** [comment]
It was fixed in this PR: 
https://github.com/mikepenz/MaterialDrawer/pull/2293

Which was introduced in this version:
https://github.com/mikepenz/MaterialDrawer/releases/tag/v6.0.8

**Comment by rishirD** [comment]
Oh, thanks. I'll check.
