### ISSUE TITLE
Dark toolbar issue when using .withDisplayBelowToolbar(true)

### ISSUE THREAD

**Issue by Reza-Rg** [mikepenz/MaterialDrawer#236]
Actually, I guess there is bug(?) when making MaterialDrawer to be shown below toolbar.
When `.withDisplayBelowToolbar()` is set to true, the toolbar get darker with main layout,
but I guess toolbar should not get darker.

![screenshot_2015-04-19-03-18-01](https://cloud.githubusercontent.com/assets/3043068/7217493/63782238-e643-11e4-9cde-100bd2476810.png)

As you can see in Google Play Music app, which drawers opens below toolbar, toolbar does not become darker.

![screenshot_2015-04-19-03-18-23](https://cloud.githubusercontent.com/assets/3043068/7217492/631e2bf2-e643-11e4-9fd4-e30c671311a5.png)

**Comment by raghunandankavi2010** [comment]
@Reza-Rg  With the new material specs the drawer comes on top of toolbar. You can switch your to the same

**Comment by Reza-Rg** [comment]
@raghunandankavi2010 I guess that's optional, because `Google Play Music` app is also using material design, but drawer is below toolbar.
And also MatrialDrawer library also provide this feature to have drawer below toolbar. so I think, it's better to prevent toolbar becoming dark while drawer is below toolbar.

**Comment by raghunandankavi2010** [comment]
@Reza-Rg I am not sure if its optional looking at the specs @ http://www.google.com/design/spec/patterns/navigation-drawer.html.

I will give your code a try and see what is happening.

**Comment by mikepenz** [comment]
@Reza-Rg your issue is that you use an actionBar. An ActionBar does not allow the drawer to overlap it. You have to use the toolbar. 

And the dark shadow is created by the drawerLayout no way to just remove it from the top. you can generally deactivate it but that's it
