### ISSUE TITLE
Step 01 of setup breaks current project build

### ISSUE THREAD

**Issue by RedSkyRoad** [mikepenz/MaterialDrawer#2361]
## About this issue

I've added the dependencies but it clearly clashes with what I have

## Details
implementation "com.mikepenz:materialdrawer:6.1.0-rc02" causes the following error

> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0-rc02] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0-rc02] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-31:19 to override.

## Checklist

- [x ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Well it seems you use the support libraries still. 

Please see the info under the first step:

```
To use appcompat please use a version smaller than 6.1.0. (See the releases on GitHub)
```

**Comment by mikepenz** [comment]
This new release uses androidX, thus your project should use androidX :)

**Comment by RedSkyRoad** [comment]
Fixed it, thanx. Refactored, added, and synced

**Comment by mikepenz** [comment]
Awesome :).
