### ISSUE TITLE
NullPointerException after upgrading to 6.1.0

### ISSUE THREAD

**Issue by rtchagas** [mikepenz/MaterialDrawer#2364]
## About this issue

- Briefly describe the issue

Just upgraded from 6.0.8 to 6.1.0 and got this crash.

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.constraintlayout.widget.Guideline.setGuidelineBegin(int)' on a null object reference
        at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:799)

My project was already using AndroidX.

- How can the issue be reproduced / sample code

// Create the AccountHeader
        AccountHeaderBuilder headerBuilder = new AccountHeaderBuilder()
                .withActivity(mTargetActivity)
                .withSavedInstance(mSavedInstanceState)
                .withHeaderBackground(R.drawable.img_default_car)
                .withOnlyMainProfileImageVisible(true)
                .withOnAccountHeaderListener((AccountHeader.OnAccountHeaderListener) mTargetActivity);

        mHeader = headerBuilder.build();  // <-- Crashes here

**Comment by rtchagas** [comment]
Migration guide mentions the statusbar guideline but have no ideia how to adapt my current drawer.

> Reworked the header views to be a lot more simple by using a ConstraintLayout
Any previously custom headers require to be adjusted to the new structure. (The statusbar Guideline is required, for example)

**Comment by rtchagas** [comment]
Sorry, found my mistake.
I use a custom header layout... Need to add the guideline there. :)

**Comment by roip890** [comment]
@rtchagas 
Hi,
Can you explain how did you fix that problem please?

Thanks!

**Comment by rtchagas** [comment]
Sure!

As I needed to customize the Drawer's header, I copied the original layout to my own project (res\layout\material_drawer_header.xml).

After upgrading to 6.1.0 that layout changed and the code now makes reference to a constraint guideline inside of it.

I just had to compare the new **material_drawer_header.xml** from 6.1.0 with mine and add the necessary guideline.

Hope that helps!
