### ISSUE TITLE
AndroidX - why bridge theme

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/MaterialDrawer#2366]
In the newest version you still rely on your materialize library which uses the bridge theme instead of the default `Theme.MaterialComponents` theme. Any reasons for this?

You say, v6.1.0 only supports androidx anyways and does not support `AppCompat` anymore, so why are you using the bridge themes?

**Comment by mikepenz** [comment]
@MFlisar I use the bridge theme to have as much compatibility as possible. 

You do not have to use the provided themes. You can use any theme you prefer and just apply the required fields: https://github.com/mikepenz/MaterialDrawer#custom-style---stylesxml

**Comment by MFlisar** [comment]
Ok. Was just curious if this is intended or was overseen...
