### ISSUE TITLE
Low memory issues

### ISSUE THREAD

**Issue by androideveloper** [mikepenz/MaterialDrawer#2367]
When using MiniDrawer, app sometimes recovers incorrectly (i guess, when memory is low and app is killed). Here is the screenshot of the state (enable "Don't keep activities" to get this).

![1521542157](https://user-images.githubusercontent.com/1249919/46289574-86ae3780-c59a-11e8-997f-faddb7525ea8.png)

**Comment by mikepenz** [comment]
I assume then something in your app does not correctly recreate the UI for this case.

**Comment by androideveloper** [comment]
We don't do any specific recreation. Shouldn't it be done automatically when we pass savedinstance to materialdrawer?

**Comment by mikepenz** [comment]
You need to fill the drawer with the items again. the saved instance only stores the selection. 

the problem is that the items can be anything, dynamically, bitmaps, ... so it is hard to find a general serialization solution to tackle all people's needs

**Comment by androideveloper** [comment]
Do you mean in onSavedInstanceState() method?

**Comment by androideveloper** [comment]
My initialization code is written in onCreate() so it is called anyway when activity is destroyed and created again

**Comment by mikepenz** [comment]
you also add the items again? 

can you debug if this happens accordingly in the case you report?

**Comment by mikepenz** [comment]
Please report back. close until then
