### ISSUE TITLE
Adjust text size AccountHeader name

### ISSUE THREAD

**Issue by yarg375** [mikepenz/MaterialDrawer#2368]
Hi, I need to adjust the text size of the AccountHeader name like this in the MATERIAL DESIGN guide. Thank you very much!

![mio-design 2fassets 2f1jb00-om1_ij_tmaymljia2llavmufeoq 2fanatomy-header-account](https://user-images.githubusercontent.com/1945675/46387814-3fa16e80-c68e-11e8-80d0-9673fa470c95.png)

**Comment by mikepenz** [comment]
It's defined [here](https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml#L96). Right now it is bound to the same dimension as the e-mail. (you could only overwrite the header xml for now until I had chance to do the change)

But thanks for pointing that out. I'll update the library to also follow this detail. Have overlooked it when doing the material 2 upgrade.

**Comment by mikepenz** [comment]
The adjustments were introduced in v6.1.1 and there are now different dimensions which can be modified if you prefer different dimensions

**Comment by yarg375** [comment]
Hello, thank you very much!
