### ISSUE TITLE
when used in fullscreen app - the visible part of the main activity shrinks

### ISSUE THREAD

**Issue by fpv999** [mikepenz/MaterialDrawer#2369]
## About this issue

When I tried to add this MaterialDrawer to my app.
It kinda worked, but it affected my MainActivity visible area. 
The app which worked previously fullscreen (statusbar, toolbar and navigation buttons hidden), after adding MaterialDrawer got shrinked verticaly - the space where statusbar, toolbar and navigationbar were just black and empty.

Fullscreen was achieved with this: window.getDecorView().setSystemUiVisibility(
                      View.SYSTEM_UI_FLAG_FULLSCREEN 
                    | View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                    | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                    | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                    | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
                    | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
            );

## Details
- [6.1.0] Used library version
- [androidx 1.0.0] Used support library version
- [3.2.0 ] Used gradle build tools version
- [3.2] Used tooling / Android Studio version

**Comment by fpv999** [comment]
It's like MaterialDrawer is forcing android:fitsSystemWindows="true" into my main activity root view

**Comment by fpv999** [comment]
...getDrawerLayout().setFitsSystemWindows(false);
that was it!

**Comment by yashjain27** [comment]
Anyone who faces this issue should use the following template I created:

```
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <include
        android:id="@+id/toolbar"
        layout="@layout/toolbar"
        app:logo="@drawable/ic_baseline_menu_24"/>

    <androidx.drawerlayout.widget.DrawerLayout
        android:id="@+id/root"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true">


        <com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView
            android:id="@+id/slider"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_gravity="start"
            android:fitsSystemWindows="true" />

    </androidx.drawerlayout.widget.DrawerLayout>

</androidx.constraintlayout.widget.ConstraintLayout>
```

Note that the fix lies in android:fitsystemwindows:true property
