### ISSUE TITLE
MaterialDrawer Theming

### ISSUE THREAD

**Issue by alok96** [mikepenz/MaterialDrawer#2370]
theming using attrs, and themes

I am trying to theme my current app with a dynamic theme switcher.
how can i set attrs, theme on styles. for button arrow color, navigation background

**Comment by mikepenz** [comment]
the arrow color is not part of this library. This is the ActionBarDrawerToggle from the android support library. So please refer to this specific components docs instead. 

The drawer background is the following in the theme:

```xml
<item name="material_drawer_background">@color/material_drawer_background</item>
```

**Comment by alok96** [comment]
Hello Mike,

I am using styling using attrs with dynamic theming
eg:

        <com.google.android.material.textfield.TextInputLayout
            **style="?edit_text"**
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:layout_gravity="center"
            android:enabled="true"
            android:gravity="center|left"
            app:layout_heightPercent="8%"
            app:layout_marginTopPercent="3%"
            app:layout_paddingLeftPercent="2%"
            app:layout_textSizePercent="2.7%"
            app:layout_widthPercent="82%">

I am setting the drawer background color with this method.
.withSliderBackgroundDrawable(ContextCompat.getDrawable(tradeActivity, R.drawable.bg_layout))

bg_layout
<?xml version="1.0" encoding="utf-8"?>
<shape android:shape="rectangle"
    xmlns:android="http://schemas.android.com/apk/res/android">
    <gradient
        android:startColor="@color/gradient"
        android:centerColor="@color/gradient1"
        android:endColor="@color/gradient2"
        android:type="linear"
        android:angle="270">
    </gradient>
</shape>

How can i set the attributes to the background for the navigation drawer.

I am using this class and put that in my BaseActivity for dyanamic theme switching
public class ThemeUtils {

    private static int sTheme;
    public final static int THEME_DARK = 0;
    public final static int THEME_LIGHT = 1;



    public static void changeToTheme(Activity activity, int theme) {
        sTheme = theme;
        activity.finish();
        activity.startActivity(new Intent(activity, activity.getClass()));
        activity.overridePendingTransition(android.R.anim.fade_in,
                android.R.anim.fade_out);
    }

    public static void onActivityCreateSetTheme(Activity activity) {
        switch (sTheme) {
            default:
            case THEME_DARK:
                activity.setTheme(R.style.dark_mode);
                break;
            case THEME_LIGHT:
                activity.setTheme(R.style.light_mode);
                break;
        }
    }

**Comment by alok96** [comment]
bg_layout

<?xml version="1.0" encoding="utf-8"?>
<shape android:shape="rectangle"
xmlns:android="http://schemas.android.com/apk/res/android">

<gradient
    android:startColor="@color/gradient"
    android:centerColor="@color/gradient1"
    android:endColor="@color/gradient2"
    android:type="linear"
    android:angle="270">
</gradient>


</shape>
