### ISSUE TITLE
DrawerItem selection background with rounded corners

### ISSUE THREAD

**Issue by mdvisla** [mikepenz/MaterialDrawer#2374]
Hi, In your example project the background of selected item doesn't cover up the whole width of drawer. It has some padding and rounded corners. How can I do that? In my case it's a full-width rectangle.

**Comment by mikepenz** [comment]
Update to the latest release v6.1.1 and use androidX

**Comment by mikepenz** [comment]
And also ensure you set the proper theme. (One of the provided, if not define the attributes) 
And make sure to disable legacy style:
```xml
<item name="material_drawer_legacy_style">false</item>
```
