### ISSUE TITLE
drawer.addItem

### ISSUE THREAD

**Issue by jrcacd** [mikepenz/MaterialDrawer#2376]
After 

`drawer = drawerBuilder.build()`

When I insert a new item
`drawer.addItem(SecondaryDrawerItem())`

It does not show the new item on the drawer.

What am I doing wrong?

**Comment by mikepenz** [comment]
are you doing this on the main thread? 
does it have an identifier? some text?

**Comment by jrcacd** [comment]
Yes, yes and yes.

**Comment by mikepenz** [comment]
just to make sure, you don't construct the drawer twice? 
(there was a issue reported once where a person constructed it twice, and added the items to a non visible instance :D)

**Comment by jrcacd** [comment]
No, I only construct once and use de builded drawer to add other item.

**Comment by jrcacd** [comment]
It's my mistake. I fund the bug
