### ISSUE TITLE
Recolor dropdown icon

### ISSUE THREAD

**Issue by Albert-Jan** [mikepenz/MaterialDrawer#2377]
Since I've updated to 6.1.1. the drawer icon, which used to be white turned to black. Is there a simple way to recolor this? Keep up your awesome work ;)

**Comment by mikepenz** [comment]
can you post a screenshot please? 

The color should be the same as the "subtext" color: 
https://github.com/mikepenz/MaterialDrawer/commit/23fa925cb6e738dbf9df7a6eeea7f7223737ae6b#diff-83c4a25990f2ec4de2d3958b7d079a54R831

**Comment by mikepenz** [comment]
It should look like one of these screenshots:

![2018-10-14 11 12 29](https://user-images.githubusercontent.com/1476232/46914758-0e844080-cfa2-11e8-989c-2232c95d2464.jpg)
![2018-10-14 11 12 26](https://user-images.githubusercontent.com/1476232/46914759-0fb56d80-cfa2-11e8-9375-fc4da45b2646.jpg)


Also make sure (if you don't use one of the provided themes) to define the new style attribute:

```xml
<item name="material_drawer_header_selection_subtext">@color/material_drawer_dark_header_selection_subtext</item>
```

**Comment by Albert-Jan** [comment]
Hi! 
Thanks for the response, I wasn't displaying a subheader, so didn't know it was supposed to be the same. Thanks for the clarification! :)
