### ISSUE TITLE
onDrawerOpened not called for the 2nd drawer on the right side

### ISSUE THREAD

**Issue by afarber** [mikepenz/MaterialDrawer#2378]
Good evening!

In [my app](https://play.google.com/store/apps/details?id=de.slova) I use 2 drawers from your excellent library - on the left and on the right side:

![screenshot_20181015-213812](https://user-images.githubusercontent.com/1884458/46974065-4636d980-d0c3-11e8-8393-08609f4d4a63.png)

```
        mNavigationDrawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(mToolbar)
                .withAccountHeader(mAccountHeader)
                .withActionBarDrawerToggle(true)
                .withShowDrawerOnFirstLaunch(false)
                .withShowDrawerUntilDraggedOpened(false)
                .build();

        mActionDrawer = new DrawerBuilder()
                .withActivity(this)
                .withOnDrawerListener(new Drawer.OnDrawerListener() {
                    @Override
                    public void onDrawerOpened(View drawerView) {
                        Log.d("tag", "XXX onDrawerOpened");
                    }

                    @Override
                    public void onDrawerClosed(View drawerView) {
                        Log.d("tag", "XXX onDrawerClosed");
                    }

                    @Override
                    public void onDrawerSlide(View drawerView, float slideOffset) {
                        Log.d("tag", "XXX onDrawerClosed");
                    }
                })
                .addDrawerItems(
                        mRightDrawerItem,
                        mRecallItem,
                        mShuffleItem,
                        mSwapItem,
                        mSkipItem,
                        mResignItem,
                        mPlayItem,
                        mShareItem
                )
                .withSelectedItem(-1)
                //.withGenerateMiniDrawer(true)
                .withDrawerGravity(Gravity.END)
                .append(mNavigationDrawer);
```

However the `onDrawerOpened` callback is unfortunately not called - neither in debugger nor the trace line is to be seen.

What could be please the reason?

## Details
- [6.0.8] Used library version
- [28.0.0] Used support library version
- [3.2.1] Used gradle build tools version
- [28] Used tooling / Android Studio version

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
the callback should be called on the main managing drawer instance. as only one DrawerLayout is used in that case. As such that one should theoretically have the callback too

**Comment by afarber** [comment]
Thank you Mike, after moving `.withOnDrawerListener()` to the `mNavigationDrawer` the callbacks are finally called.

If you look at the screenshot, I have a green `AbstractDrawerItem` at the top and there a countdown `23:49:07` which I'd like to animate (by calling its `bindView` method every second; with a `payload` so that the ImageView does not blink) - by starting a timer on `onDrawerOpened` and then stopping the timer on `onDrawerClosed` - to save the phone battery.

Do you maybe have a recommendation, which timer to use or maybe AsyncTask?

**Comment by afarber** [comment]
And how to know please if the right drawer has been opened (and not the main one on the left)?

I am trying the following but get syntax error:

```
                    @Override
                    public void onDrawerOpened(View drawerView) {
                        Log.d(Utils.TAG, "XXX onDrawerOpened: " + (drawerView == mNavigationDrawer));
                    }

```

**Comment by mikepenz** [comment]
well the callback is from the `DrawerLayout` that one only provides the view. you should be able to compare with the view you can get from the `mNavigationDrawer` 

Most likely `mNavigationDrawer.getSlider()` I think (did not check the real method name so it might slightly differ)

And the best approach. that highly depends how accurate this timer has to be. you could also use a handler which posts delayed every second, but that won't be really accurate

**Comment by afarber** [comment]
Thank you
