### ISSUE TITLE
i need your help

### ISSUE THREAD

**Issue by elbetbirgun** [mikepenz/MaterialDrawer#2379]
Configuration with name 'testImplementation' not found.

![image](https://user-images.githubusercontent.com/38755096/47004744-e5e37e80-d13a-11e8-95c1-1c43b5b13cc2.png)

**Comment by mikepenz** [comment]
ensure you use AS 3.2 and gradle 4.7 or so

**Comment by elbetbirgun** [comment]
i'am using distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip and AS 3.2

detail error:

![image](https://user-images.githubusercontent.com/38755096/47009265-b8033780-d144-11e8-9d3b-50e1ef4a54c2.png)

![image](https://user-images.githubusercontent.com/38755096/47009288-ca7d7100-d144-11e8-89a2-9a0b1c75273c.png)

**Comment by mikepenz** [comment]
oh you might even want to use AS 3.3 canary. sorry. 

The project uses the latest alpha plugins: https://github.com/mikepenz/MaterialDrawer/blob/develop/build.gradle#L27

**Comment by elbetbirgun** [comment]
haha :) im AS 3.3 but gradle in correction "classpath 'com.android.tools.build:gradle:3.2.1'" :)) 

![image](https://user-images.githubusercontent.com/38755096/47010389-82ac1900-d147-11e8-957d-ded8d1ff012b.png)

successful :)

thank you.
