### ISSUE TITLE
Selected icon color doesnt work

### ISSUE THREAD

**Issue by andhie** [mikepenz/MaterialDrawer#238]
Does this library support tinting of the icon (a .png file) in selected state? from what I gone thru, the code does so by tint the icon with `material_drawer_selected_text` color
My icons are still white even in selected state.

```xml
<style name="CustomStyle" parent="MaterialDrawerTheme">
    <item name="colorPrimary">@color/primary_color</item>
    <item name="colorPrimaryDark">@color/primary_dark_color</item>
    <item name="colorAccent">@color/accent_color</item>

    <item name="material_drawer_selected_text">@color/accent_color</item>
</style>
```

I have also tried setting it in Java, where i see it has higher priority. but it also doesnt tint with my color accent

```java
new PrimaryDrawerItem()
    .withName(NAVDRAWER_TITLE_RES_ID[i])
    .withIcon(NAVDRAWER_ICON_RES_ID[i])
    .withSelectedIconColorRes(R.color.accent_color)
    .withIdentifier(NAV_ITEMS[i]);
```

**Comment by raghunandankavi2010** [comment]
@andhie have tried with `.withTintSelectedIcon(true)`?

**Comment by andhie** [comment]
@raghunandankavi2010 yes, that works now. thanks.
need more documentation on the library and behaviour

**Comment by mikepenz** [comment]
@andhie almost all functions are in the sample :)

**Comment by andhie** [comment]
I've updated to the latest v2.9.2 which enables tinting by default. The selected state is tinted properly, but setting a default color state `withIconColorRes()` doesnt work. Probably `withDisabledIconColorRes()` also doesnt work.

**Comment by mikepenz** [comment]
@andhie haha those methods were never meant to be used for these things too. they are only for the Android-Iconics icons. but you are right with the new changes to the tinting i also can enable these methods for drawables.

**Comment by andhie** [comment]
If you're putting in the enhancement, I hope you wouldn't change to the new v4 tinting methods. It doesnt work on Lollipop onwards.
I've filed an AOSP bug report related to that, https://code.google.com/p/android/issues/detail?id=172067

**Comment by mikepenz** [comment]
@andhie yeah tested it but did not work so i stay with normal colorfilter ;)

**Comment by mikepenz** [comment]
Fixed with v2.9.5. See the upgrade notes

**Comment by andhie** [comment]
Upgraded to 2.9.5, the default state is now tinted, but it breaks the selected state color.
It is now always tinted with blue.
Previously on 2.9.2 it was correctly tinted according to `withSelectedIconColorRes`.
Note: I did not inherit from MaterialDrawer Themes nor override any material_* attrs

```java
new PrimaryDrawerItem()
    .withName(NAVDRAWER_TITLE_RES_ID[i])
    .withIcon(NAVDRAWER_ICON_RES_ID[i])
    .withTextColorRes(R.color.navdrawer_text_color) // black
    .withIconColorRes(R.color.navdrawer_icon_tint) // grey
    .withSelectedTextColorRes(R.color.navdrawer_text_color_selected) // red
    .withSelectedIconColorRes(R.color.navdrawer_icon_tint_selected) // red
    .withIconTinted(true);
```

**Comment by mikepenz** [comment]
@andhie you are right:

```java
int selectedIconColor = UIUtils.decideColor(ctx, getSelectedIconColor(), getSelectedColorRes(), R.attr.material_drawer_selected_text, R.color.material_drawer_selected_text);
```

missed the `getSelectedColorRes()` there. will fix it in the next release. hopefully out later today.

**Comment by andhie** [comment]
i think you should start deprecating methods, or else the library will have lots of methods but doing the same thing, such as `withIconTinted` and `withTintSelectedIcon`. it will be confusing since the name suggests 2 different consequences.

**Comment by simonckenyon** [comment]
the colour of an icon created with new IconicsDrawable(this, "faw-cog")
is not the same as one created with FontAwesome.Icon.faw_cog

i generate some of the drawer programmatically and get the icon name from a string

is there something i can do to make them the same?

**Comment by mikepenz** [comment]
@simonckenyon wrong issue but i answer here :D

in fact it makes sense that the color is different. if you just give me the icon i am able to handle the whole icon creation in the drawer. if you create a custom drawable i can't do this. 

how different is the icon color? can you post screenshtos?

**Comment by mikepenz** [comment]
@simonckenyon as a better thing i would recommend that you just do the following:

```java
new FontAwesome().getIcon("faw-cog") 
```

**Comment by simonckenyon** [comment]
i'll put the code back the way it was and send a screenshot.
thanks for the tip above. did not know that.

i'm creating a custom drawable because i don't know the icon name at compile time, only at run time.

**Comment by mikepenz** [comment]
If you just know the string use this one: `new FontAwesome().getIcon("faw-cog")` ;). is the best solution. and most performant once too :)

**Comment by simonckenyon** [comment]
that should be:

 new FontAwesome().getIcon("faw_cog")

note the "_" instead of the "-"

**Comment by mikepenz** [comment]
@simonckenyon thanks :D wrote it out of my head. so sorry

**Comment by simonckenyon** [comment]
On 05/20/15 21:39, Mike Penz wrote:
>
> @simonckenyon <https://github.com/simonckenyon> thanks :D wrote it out 
> of my head. so sorry
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mikepenz/MaterialDrawer/issues/238#issuecomment-104031270>.
>
no problem. your library is super cool. i am using it on a number of 
projects.

-- 
simon

Simon Kenyon
Managing Director. The Koala Computer Company Limited
e: simon@koala.ie
m: +353 86 240 0005
l: http://ie.linkedin.com/pub/simon-kenyon/0/6b2/744/
s: simonckenyon
t: @simonckenyon
g: google.com/+SimonKenyon

**Comment by mikepenz** [comment]
@simonckenyon thanks

**Comment by MarkOSullivan94** [comment]
@mikepenz could we get an updated example of this in the readme? I've just noticed that the following code is depreciated.

`withIconTinted(true);`

Here's an example of a snippit of code which is working for me

`item1 = new PrimaryDrawerItem()
                .withName("Home")
                .withIcon(R.drawable.ic_home_black_24dp)
                .withIconColor(ContextCompat.getColor(getApplicationContext(), R.color.material_drawer_primary_text))
                .withSelectedIconColor(ContextCompat.getColor(getApplicationContext(), R.color.material_drawer_dark_selected_text))
                .withIconTintingEnabled(true);`

**Comment by mikepenz** [comment]
@MarkOSullivan94 yeah it's exactly the same, i just renamed the method as the new name makes more sense. I have not yet planned to remove the old variant so it should be fine ;)
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDrawerItem.java#L187
