### ISSUE TITLE
Load image via URL using Picasso & Glide (Last versions) with MaterialDrawer

### ISSUE THREAD

**Issue by burekas7** [mikepenz/MaterialDrawer#2380]
Hi,
I'm trying to show the profile picture after log in, but it doesn't work, the image remains like the default ‘ic_account_circle_black_48dp’ but in a different color.
And I verified, it does return the jpg url of the profile image in 96×96 resolution (When using Google login for example)

This is the code (focus on the line ".withIcon")
```
    private void setupProfileDrawer() {
        //check if the user is logged in. If logged in, get details (name, email, pic etc) dynamically
        //For demonstration purpose, I have set a personal photo hard coded. In real-time, we can easily
        // pass the actual photo dynamically.
        if (mFirebaseUser != null) {
            String urlll = mFirebaseUser.getPhotoUrl().toString();
            mProfileDrawerItem = new ProfileDrawerItem()
                    .withName(mFirebaseUser.getDisplayName())
                    .withEmail(mFirebaseUser.getEmail())
                    .withIcon(mFirebaseUser.getPhotoUrl().toString());
                    //.withIcon(getResources().getDrawable(R.drawable.profile));
        } else {//else if the user is not logged in, show a default icon
            mProfileDrawerItem = new ProfileDrawerItem()
                    .withIcon(getResources().getDrawable(R.mipmap.ic_account_circle_black_48dp));
        }
    }
```

## Details
- [6.1.1] Used library version
- [ ] Used support library version
`implementation 'androidx.appcompat:appcompat:1.0.0' `
- [ ] Used gradle build tools version
```
    implementation('com.mikepenz:materialdrawer:6.1.1@aar') {
        transitive = true
    }
```
- [ 3.2.1] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [v] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [v] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [v] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [v] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [v] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [v] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by burekas7** [comment]
[Solved]

OK, so I solve the problem.

The docs are not updated with the last versions of Picasso and Glide:
https://github.com/mikepenz/MaterialDrawer#load-images-via-url

Here are the updated codes and the steps to implement it according to the last versions.
---
### Picasso:
* Last version:  2.71828
* http://square.github.io/picasso/
* Based on:
https://stackoverflow.com/questions/47844478/cannot-find-symbol-method-with-using-picasso-library-android

Step 1: In build.gradle (Module: app)
//Picasso
`    implementation 'com.squareup.picasso:picasso:2.71828'`

Step 2: The updated code in the manual should be (I put it inside a procedure):
```
    private void overrideDrawerImageLoaderPicasso(){
        //initialize and create the image loader logic
        DrawerImageLoader.init(new AbstractDrawerImageLoader() {
            @Override
            public void set(ImageView imageView, Uri uri, Drawable placeholder) {
                     Picasso.get().load(uri).placeholder(placeholder).into(imageView);
            }

            @Override
            public void cancel(ImageView imageView) {
                Picasso.get().cancelRequest(imageView);
            }

            /*
            @Override
            public Drawable placeholder(Context ctx) {
                return super.placeholder(ctx);
            }

            @Override
            public Drawable placeholder(Context ctx, String tag) {
                return super.placeholder(ctx, tag);
            }
            */
        });
    }
```
Step 3 - Use Alt+Enter to add all the neccesary imports
`import com.squareup.picasso.Picasso;`

Step 4 - Put the overrideDrawerImageLoaderPicasso() procedure in onCreate() , before the Drawer is created.
* Basically, this has to be done, before the first image should be loaded via URL. (Should be done in the Application, but any other spot before loading the first image is working too)

---
### Glide:
* Last version: 4.8.0
* https://bumptech.github.io/glide/
* https://bumptech.github.io/glide/doc/getting-started.html

Step 1: In build.gradle (Module: app)
(NOTE: It seems that it's still not compatible with "AndoirdX" libraries, so there is a need to add the "Android Support" libraries)

```
    //Glide
    implementation 'com.github.bumptech.glide:glide:4.8.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
    
    implementation 'com.github.bumptech.glide:okhttp3-integration:4.8.0@aar'

    implementation "com.android.support:support-annotations:28.0.0-alpha3"
    annotationProcessor 'com.android.support:support-annotations:28.0.0-alpha3'
```

Step 2 - Create a new Java module class and call it: MyAppGlideModule.
* https://bumptech.github.io/glide/doc/getting-started.html#applications

Put this code into it:
```
package com.iteritory.itcmyfirebaseauth;

import com.bumptech.glide.annotation.GlideModule;
import com.bumptech.glide.module.AppGlideModule;

@GlideModule
public final class MyAppGlideModule extends AppGlideModule {}
```

Step 3: The updated code in the manual should be (I put it inside a procedure):
```
    private void overrideDrawerImageLoaderGlide(){
        //initialize and create the image loader logic
        DrawerImageLoader.init(new AbstractDrawerImageLoader() {
            @Override
            public void set(ImageView imageView, Uri uri, Drawable placeholder, String tag) {
                GlideApp.with(imageView.getContext()).load(uri).placeholder(placeholder).into(imageView);
            }

            @Override
            public void cancel(ImageView imageView) {
                Glide.with(imageView.getContext()).clear(imageView);
            }

            @Override
            public Drawable placeholder(Context ctx, String tag) {
                //define different placeholders for different imageView targets
                //default tags are accessible via the DrawerImageLoader.Tags
                //custom ones can be checked via string. see the CustomUrlBasePrimaryDrawerItem LINE 111
                if (DrawerImageLoader.Tags.PROFILE.name().equals(tag)) {
                    return DrawerUIUtils.getPlaceHolder(ctx);
                } else if (DrawerImageLoader.Tags.ACCOUNT_HEADER.name().equals(tag)) {
                    return new IconicsDrawable(ctx).iconText(" ").backgroundColorRes(com.mikepenz.materialdrawer.R.color.primary).sizeDp(56);
                } else if ("customUrlItem".equals(tag)) {
                    return new IconicsDrawable(ctx).iconText(" ").backgroundColorRes(R.color.md_red_500).sizeDp(56);
                }

                //we use the default one for
                //DrawerImageLoader.Tags.PROFILE_DRAWER_ITEM.name()

                return super.placeholder(ctx, tag);
            }
        });
    }
```

Step 4 - Use Alt+Enter to add all the neccesary imports

Step 5 - Put the overrideDrawerImageLoaderGlide() procedure in onCreate() , before the Drawer is created.
* Basically, this has to be done, before the first image should be loaded via URL. (Should be done in the Application, but any other spot before loading the first image is working too)

**Comment by mikepenz** [comment]
@burekas7 you might want to open a PR and update them inside the sample app :).

**Comment by burekas7** [comment]
@mikepenz 

I have made a PR:
https://github.com/mikepenz/MaterialDrawer/pull/2383

Hope it's good.
Pay attention that people should be aware also to the manifest changes as I wrote here.

**Comment by mikepenz** [comment]
Thank you very much!
