### ISSUE TITLE
Set Selected Item Color

### ISSUE THREAD

**Issue by ken-estrella** [mikepenz/MaterialDrawer#2384]
Is there any way we can set the color of the drawer items when long pressed, or simply clicked?
I found out that it uses the **_colorAccent_** for press events and **_colorPrimaryDark_** for selected item.

**Comment by mikepenz** [comment]
The color is retrieved here:
https://github.com/mikepenz/MaterialDrawer/blob/32297f89de3882a0f53365e98f4a5ee56adcf0c5/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDrawerItem.java#L275

and you can set the color in the theme:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/values/styles.xml#L39
