### ISSUE TITLE
A grey narrow strip is shown at the top of drawer

### ISSUE THREAD

**Issue by sorous** [mikepenz/MaterialDrawer#2385]
I followed [this tutorial](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_show_drawer_under_toolbar.md) from FAQ / WIKI to show navigation drawer underneath the toolbar, but know, a grey narrow strip is created at the top of navigation items. How can I hide that?
![screenshot_20181023-235623](https://user-images.githubusercontent.com/42151206/47389291-41a49d80-d721-11e8-83ec-0f3f9610d166.png)

**Comment by mikepenz** [comment]
@sorous please look at the sample app it also has such a sample.

The grey bar comes from the inset which would be needed for the drawer if it was normally implemented in fullscreen.

**Comment by sorous** [comment]
@mikepenz Thanks for the answer. I added ` .withDisplayBelowStatusBar(false)
                .withTranslucentStatusBar(false)
                .withDrawerLayout(R.layout.material_drawer_fits_not)` to my code. Navigation items are not under status bar anymore, but the status bar still exists and its grey color is really annoying me! I think I have to say the drawer layout to not have a status bar, am I right? How can I do that?

**Comment by mikepenz** [comment]
use a ActionBar theme:
https://github.com/mikepenz/MaterialDrawer/blob/32297f89de3882a0f53365e98f4a5ee56adcf0c5/app/src/main/AndroidManifest.xml#L34

And configure the drawer as shown here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/ActionBarActivity.java#L22

If you use a `ActionBar` 

If you just want to have the drawer in a different hiarachry level with a toolbar. Then see here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java
