### ISSUE TITLE
Account profile email/name click listener

### ISSUE THREAD

**Issue by Zeynal7** [mikepenz/MaterialDrawer#2387]
I have seen something like this in one of the apps. When you click on the user's email on the drawer, it opens email app to send an email. 
In my app, there will only be one profile with my profile name and email. Can I do something similar with my app? 
<img width="298" alt="screen shot 2018-10-31 at 21 32 38" src="https://user-images.githubusercontent.com/35888362/47807045-90bb8580-dd54-11e8-8d03-65fe588d49ba.png">

P.S. I am new to the github, so I don't know if it is correct way of asking question.

**Comment by mikepenz** [comment]
You can use this here to set a click listener for the selection list area:

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L534
