### ISSUE TITLE
Lastest Setup

### ISSUE THREAD

**Issue by justdan0227** [mikepenz/MaterialDrawer#2389]
Have the setup procedure changed?  Just created a new Android Project, added the dependencies and after hunting around found that I needed to add the buildscript 

```
 ext {
        release = [
                versionName: "6.1.1",
                versionCode: 6101
        ]

        setup = [
                compileSdk: 28,
                buildTools: "28.0.3",
                minSdk    : 14,
                targetSdk : 28
        ]

        versions = [
                androidX: '1.0.0',
                constraintLayout: '1.1.3'
        ]
    }
```

however still getting this on sync...

```
Android resource linking failed
Output:  /Users/Documents/Development/android/xxx/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
/Users/Documents/Development/android/xxx/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
/Users/Documents/Development/android/xxx/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:925: error: resource android:attr/fontVariationSettings not found.
/Users/Documents/Development/android/xxx/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:925: error: resource android:attr/ttcIndex not found.
error: failed linking references.
```

**Comment by mikepenz** [comment]
could it be that you still have support lib dependencies somewhere? 

also the part you add to the build script is not required from the materialDrawer, just add the dependency with the version. if you want to move definitions into a different gradle file that's up to you.

**Comment by justdan0227** [comment]
If I go not include the build script part it says $version undefined 

Dan

**Comment by mikepenz** [comment]
Well you have to replace the version placeholder with the version you want to use. but it is not required to move it to a general place

**Comment by justdan0227** [comment]
Oh I'm sorry I did not see that in the instructions.  What do you replace it with to get the latest and greatest.  Thank you

**Comment by mikepenz** [comment]
You can always check on maven central which are the latest released binaries :) 

https://search.maven.org/artifact/com.mikepenz/materialdrawer/6.1.1/aar

Please note that everything newer than 6.1.x uses androidx ;)

**Comment by justdan0227** [comment]
Awesome thanks!
