### ISSUE TITLE
Toolbar Color Is Always Grey

### ISSUE THREAD

**Issue by akshayt23** [mikepenz/MaterialDrawer#239]
Hi, 
I'm trying to use your library and I see this strange issue where the toolbar color is always grey. The status bar is fine though and shows the correct color.
Here's how it looks: 
![screenshot_2015-04-20-17-38-41](https://cloud.githubusercontent.com/assets/8946657/7229842/d3408dce-e785-11e4-989e-605943dcd60a.png)

The code I'm using is this: 

build.gradle:

    dependencies {
        compile('com.mikepenz.materialdrawer:library:2.7.9@aar') {
            transitive = true
        }
    }

styles.xml:

            <style name="FullscreenTheme" parent="MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus">
                <item name="colorPrimary">@color/color_primary</item>
                <item name="colorPrimaryDark">@color/color_primary_dark</item>
                <item name="colorAccent">@color/color_accent</item>
            </style>

Manifest.xml:

            <activity
                android:name=".activities.Temp"
                android:label="@string/app_name"
                android:theme="@style/FullscreenTheme" >
                <intent-filter>
                    <action android:name="android.intent.action.MAIN" />

                    <category android:name="android.intent.category.LAUNCHER" />
                </intent-filter>
            </activity>

layout/activity_temp.xml:

    <RelativeLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:gravity="center"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            android:elevation="4dp"/>

        <FrameLayout
            android:layout_below="@id/toolbar"
            android:id="@+id/frame_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <TextView
                android:id="@+id/txtLabel"
                android:layout_gravity="center"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Test"
                android:textSize="16sp"/>
        </FrameLayout>
    </RelativeLayout>

TempActivity.xml:

 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_temp);

        // Handle Toolbar
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        toolbar.setBackgroundColor(Color.BLACK);
        toolbar.getBackground().setAlpha(90);

        IProfile iProfile = new ProfileDrawerItem()
                .withName("Akshay")
                .withEmail("akshay.thapa23@gmail.com")
                .withIcon(getResources().getDrawable(R.drawable.photo));

        //Create AccountHeader
        accountHeader = new AccountHeader()
                .withActivity(this)
                .withHeaderBackground(R.drawable.navbar_header)
                .addProfiles(iProfile)
                .withSavedInstance(savedInstanceState)
                .build();

        //Create the drawer
        drawer = new Drawer()
                .withActivity(this)
                .withToolbar(toolbar)
                .withAccountHeader(accountHeader)
                        //.withFullscreen(true)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("Option1"),
                        new PrimaryDrawerItem().withName("Option2"),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem().withName("Option3")
                )
                .withSavedInstance(savedInstanceState)
                .build();

        drawer.setSelectionByIdentifier(1, false);
        accountHeader.setActiveProfile(iProfile);

        //set the back arrow in the toolbar
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setHomeButtonEnabled(false);
    }

Also, it shows an arrow instead of the hamburger icon. Can anyone please help with this.

Though I should mention that it works perfectly when I use the sample app you have provided. Could it be because of the difference in the versions being used? The one used in the sample app is:

    compile('com.mikepenz.aboutlibraries:library:4.5.8@aar') {
        transitive = true
    }  

Thanks!

**Comment by mikepenz** [comment]
@akshayt23 i will take a closer look at this. but there's a second issue open which probably should be referred to this one #234 .

oh and no you misread the library dependency :D you 'com.mikepenz.aboutlibraries:library:4.5.8@aar' is a different lib

**Comment by akshayt23** [comment]
@mikepenz Hi Mike, Issue #234 could possibly be happening for the same reason. But it specifically talks about the ActionBar color in the task switcher. I'm not able to get it to work even within the app. If you check raghunandankavi2010's snaps that he's posted, he's actually able to get the proper color and hamburger icon in the action bar. 
Am I missing something here?

**Comment by mikepenz** [comment]
oh about your toolbar:

```java
    toolbar.setBackgroundColor(Color.BLACK);
    toolbar.getBackground().setAlpha(90);
```

**Comment by akshayt23** [comment]
That portion of the code is already there and its still not working. I have done this:

    // Handle Toolbar
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        toolbar.setBackgroundColor(Color.BLACK);
        toolbar.getBackground().setAlpha(90);

**Comment by mikepenz** [comment]
@akshayt23 yeah but why don't you remove the toolbar color overwrite? you make it grey with the those lines:

```java
toolbar.setBackgroundColor(Color.BLACK);
toolbar.getBackground().setAlpha(90);
```

**Comment by akshayt23** [comment]
@mikepenz Ohh I completely missed that. Thanks a ton! :D
Also how can I get the hamburger icon instead of the left pointing arrow?

**Comment by mikepenz** [comment]
if you use the toolbar see at the sample :D

just a hint you set it to the arrow right now:
```java
    //set the back arrow in the toolbar
    getSupportActionBar().setDisplayHomeAsUpEnabled(true);
    getSupportActionBar().setHomeButtonEnabled(false);
```

**Comment by akshayt23** [comment]
@mikepenz That's extremely stupid of me. Though everything works now. Cheers mate! :D

**Comment by mikepenz** [comment]
@akshayt23 no problem man :D
