### ISSUE TITLE
How to create the 2nd drawer in a Fragment instead of main Activity?

### ISSUE THREAD

**Issue by afarber** [mikepenz/MaterialDrawer#2392]
Good evening, I have an app with single Activity and several Fragments.

One of the fragments displays a custom view:

![screenshot_20181124-201052](https://user-images.githubusercontent.com/1884458/48972226-6fce1380-f026-11e8-88ca-9c61e7bfa49b.png)

and has a 2nd drawer on the right side:

![screenshot_20181124-201057](https://user-images.githubusercontent.com/1884458/48972228-8d02e200-f026-11e8-8d19-a8d49b38dc02.png)

My problem is that the 2nd drawer (and the navigational drawer on the left side) are created in the main activity and I have to add a lot of boilerplate code to communicate between the custom view and the right drawer (by always going through the fragment)

Is there maybe a way to create and activate the 2nd drawer in the fragment only?

Thank you

**Comment by afarber** [comment]
Mike, by „slider“ do you mean ViewPager?

**Comment by mikepenz** [comment]
@afarber by "slider" I mean the thing you pull out from the side in a `DrawerLayout` 

The `DrawerLayout` is just the wrapping `ViewGroup` providing the functionality to have the main view and `sliders` top, right, bottom, left (which are normally hidden and can be pulled out via a swipe) 

In your screenshot the slider would be the thing with the profile, and then the items (the drawer content)

**Comment by afarber** [comment]
Thank you
