### ISSUE TITLE
How to add a new IProfile if user creates a new profile?

### ISSUE THREAD

**Issue by sdzshn3** [mikepenz/MaterialDrawer#2396]
Suppose, currently there is only one profile in AccountHeader or in ExpandableDrawerItem.

And then if user creates a new profile, then how to add that profile automatically to the existing list of AccountHeader or ExpandableDrawerItem?

The reason why i choosed AccountHeader or ExpandableDrawerItem is because, I wanna let the user switch his profile either in AccountHeader or in ExpandableDrawerItem.

Which one is better and how to achieve the above requirement?

**Comment by mikepenz** [comment]
I am not 100% sure about the requirement. 

But the `AccountHeader` is meant to manage profiles. 

And you can use its class all the time to add / remove elements. Create a new `ProfileDrawerItem` and then add it to the `AccountHeader` it will automatically show up in the account selection list. 

The sample shows how to add items to the `AccountHeaderBuilder` but you can also use the apis to add items to the `AccountHeader` via its api
