### ISSUE TITLE
Update Issue from 2.9.1 to latest version which support appcombat

### ISSUE THREAD

**Issue by samansalamat** [mikepenz/MaterialDrawer#2397]
could u give me the instruction to change the mainActivity and layout structure?
because i want to use the RTL version with header and icons in right sides of items.
in 2.9.1 cant add header, change the position of icons.

best regaurds,

**Comment by mikepenz** [comment]
@samansalamat please read the migration guides. The latest release does use AndroidX and is no longer compatible with support or appcompat dependencies. 

You need to use an older version for this. 

Also there were many changes sind 2.x. So ensure you properly check out the migration notes and changes in the APIs

**Comment by samansalamat** [comment]
tnx for your help
