### ISSUE TITLE
NoSuchMethodError setBackground on API 14 and 15

### ISSUE THREAD

**Issue by grote** [mikepenz/MaterialDrawer#2398]
The README claims that this library is "compatible down to API Level 14". However:

```
    java.lang.NoSuchMethodError: android.view.View.setBackground
        at com.mikepenz.materialdrawer.util.DrawerUIUtils.themeDrawerItem(DrawerUIUtils.java:123)
```

See: https://github.com/mikepenz/MaterialDrawer/blob/efc8f7cca0b0553e6dab399c4e4ec56199680481/library/src/main/java/com/mikepenz/materialdrawer/util/DrawerUIUtils.java#L123

**Comment by mikepenz** [comment]
Shouldn't the compiler prevent this already :O

**Comment by grote** [comment]
Yeah, not sure why this isn't caught before a runtime exception on an actual device :P
