### ISSUE TITLE
Is there a way to get View class object of separate menu item?

### ISSUE THREAD

**Issue by panovvitalik** [mikepenz/MaterialDrawer#2399]
I want to add tutorial for menu items and try to use: 
https://github.com/douglasjunior/android-simple-tooltip

It need View class object. Can I get menu item's View class object?

**Comment by mikepenz** [comment]
The `MaterialDrawer` uses a `RecyclerView` as such there is no guarantee that there is currently a `View` bound for an element. 

Depending on how the user scrolled. 

As the `MaterialDrawer` depends on a `RecyclerView` all rules of `RecyclerView`s apply and you can use all APIs available. 

(The `Drawer` has a `getter` to retrieve the `RecyclerView` and then you can call all related methods)
