### ISSUE TITLE
Icon color with semitransparent text color

### ISSUE THREAD

**Issue by h6ah4i** [mikepenz/MaterialDrawer#24]
Hi. I noticed that icons do not change their transparency even if the text color has alpha channel.

**Comment by mikepenz** [comment]
The icons are created with the color set within the material_drawer_* colors. These are the colors mentioned within the google material docs (a direct grey value and not black with alpha)

The icons are generated as drawable, and i think this will ignore alpha values.

You can pass the icon as drawable if you need an alpha value. Just create it with the Android-Iconics library (which is a dependency of the MaterialDrawer) like this:

```java
new IconicsDrawable(this, FontAwesome.Icon.faw_adjust).alpha(50);
```

**Comment by h6ah4i** [comment]
Thanks for your advice. Solved the issue.

**Comment by mikepenz** [comment]
@h6ah4i that was also really fast ;). what have you done to solve it for you?

**Comment by h6ah4i** [comment]
Sorry for the late reply. I've solved this issue by just choosing a grey color (without alpha).
