### ISSUE TITLE
NPE when trying to add the hamburger icon to an action bar.

### ISSUE THREAD

**Issue by fdorssers** [mikepenz/MaterialDrawer#240]
I've been trying to add this drawer to an older application which still uses action bars and I'm running into bit of an issue when trying to actually add the hamburger.

I create a drawer:
```Java
result = new Drawer()
        .withActivity(this)
        .withTranslucentStatusBar(false)
        .withActionBarDrawerToggle(true)
        .addDrawerItems(
            ...
        ).build();
```
And I try to enable the hamburger toggle icon as according to the docs:
```Java
    getSupportActionBar().setDisplayHomeAsUpEnabled(false);
    result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);
```
However this results in the following NPE:
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBarDrawerToggle.setDrawerIndicatorEnabled(boolean)' on a null object reference
```
So it appears that the the `ActionBarDrawerToggle` isn't being initialized in the drawer. 
My guess is it happens because I'm not using a toolbar. Because when I look in `Drawer.java` then the only place where `mActionBarDrawerToggle` is being set is in the following if statement:
```Java
if (mActionBarDrawerToggleEnabled && mActionBarDrawerToggle == null && mToolbar != null) {
    this.mActionBarDrawerToggle = new ActionBarDrawerToggle(mActivity, mDrawerLayout, mToolbar, R.string.drawer_open, R.string.drawer_close) {
```
Would you happen to have a solution to this? Or am I simply doing something wrong.

**Comment by mikepenz** [comment]
@fdorssers the problem is with the newest support library there is no functionality to use the ActionBarDrawerToggle on an actionbar just on a toolbar. The toolbar is the recommend ui component so you should use this one. 

and yes you are right the ActionBarDrawerToggle is only initialized inside the drawer if you use a toolbar. so i would just recommend you remove the line
`result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);`
and handle the display of the arrow or hamburger icon on your own.

**Comment by fdorssers** [comment]
Okay, thanks for the answer. I'll figure something out then :) .

**Comment by MichaelEvans** [comment]
@fdorssers Did you figure something out? I guess we can't simply create your own ActionBarDrawerToggle, because we don't have a reference to the DrawerLayout?

**Comment by fdorssers** [comment]
@MichaelEvans In the end I simply chose to spend a bit more time and change activities to extend `ActionBarActivity` and use toolbars. So unfortunately I can't give any advice on this.

**Comment by mikepenz** [comment]
just for anyone who is still interested in this. 

If you really want to handle the ActionBarDrawerToggle on your own. This is the code i use for it internally.

```
//set the navigationOnClickListener
View.OnClickListener toolbarNavigationListener = new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        boolean handled = false;

        if (mOnDrawerNavigationListener != null && (mActionBarDrawerToggle != null && !mActionBarDrawerToggle.isDrawerIndicatorEnabled())) {
            handled = mOnDrawerNavigationListener.onNavigationClickListener(v);
        }
        if (!handled) {
            if (mDrawerLayout.isDrawerOpen(mSliderLayout)) {
                mDrawerLayout.closeDrawer(mSliderLayout);
            } else {
                mDrawerLayout.openDrawer(mSliderLayout);
            }
        }
    }
};

//if we got a toolbar set a toolbarNavigationListener
if (mToolbar != null) {
    this.mToolbar.setNavigationOnClickListener(toolbarNavigationListener);
}

// create the ActionBarDrawerToggle if not set and enabled and if we have a toolbar
if (mToolbar != null) {
    this.mActionBarDrawerToggle = new ActionBarDrawerToggle(mActivity, mDrawerLayout, mToolbar, R.string.drawer_open, R.string.drawer_close) {
        @Override
        public void onDrawerOpened(View drawerView) {
            if (mOnDrawerListener != null) {
                mOnDrawerListener.onDrawerOpened(drawerView);
            }
            super.onDrawerOpened(drawerView);
        }

        @Override
        public void onDrawerClosed(View drawerView) {
            if (mOnDrawerListener != null) {
                mOnDrawerListener.onDrawerClosed(drawerView);
            }
            super.onDrawerClosed(drawerView);
        }

        @Override
        public void onDrawerSlide(View drawerView, float slideOffset) {
            if (!mAnimateActionBarDrawerToggle) {
                super.onDrawerSlide(drawerView, 0);
            } else {
                super.onDrawerSlide(drawerView, slideOffset);
            }
        }
    };
    this.mActionBarDrawerToggle.syncState();

}

//handle the ActionBarDrawerToggle
if (mActionBarDrawerToggle != null) {
    mActionBarDrawerToggle.setToolbarNavigationClickListener(toolbarNavigationListener);
    mDrawerLayout.setDrawerListener(mActionBarDrawerToggle);
}
```

you can probably simplify the whole code for your purpose.
