### ISSUE TITLE
DrawerImageLoader only works for URL's

### ISSUE THREAD

**Issue by Nohus** [mikepenz/MaterialDrawer#2400]
### Issue

My application doesn't use HTTP to communicate with it's server, instead using raw sockets and a custom, efficient binary format to avoid the HTTP overhead. Images are also transferred this way, no HTTP involved. I have a custom `ImageLoader` class which works just like `Glide` or `Picasso`, but uses internal image references instead of URI's, since there are no URI's in my system. It was easy to hook this up with `DrawerImageLoader`, but now the problem is that it only accepts URI's, and I have none, just Strings (which are the image references). As a workaround I have to prefix my image references with "`https://`" so it's accepted as an URI, and then remove that prefix in the `set` method before passing it on as a String to my `ImageLoader`. I also cannot use a custom protocol like "`reference://`", because the `DrawerImageLoader` is not triggered then.

### Expectation

`DrawerImageLoader` should be triggered for all URI's passed to `withIcon()` (and others), not filtered by protocol, or if some protocols are internally handled, it should be triggered for all unknown protocols. An URI like "`reference://abc123`" should be passed to the `DrawerImageLoader` instead of crashing the app, like it currently does. Alternatively, bare Strings should be allowed to be used instead of URI's.

**Comment by mikepenz** [comment]
@Nohus sorry for the late answer. 

This is a very specific case, but to be honest actually really impressive ;). 
I definitely share the thought of properly handling any URIs not just ones with http / https prefixed. 
I am not sure about plain strings though. 

As this is a very special case and I am currently super flooded with work. If you still need the adjustment to allow any URIs and not just http /  https, would you mind to open a PR?

Hopefully this helps

**Comment by Nohus** [comment]
Would you accept a PR in Kotlin?

**Comment by mikepenz** [comment]
Towards the kotlin branch. Sure.

**Comment by mikepenz** [comment]
Is this issue still relevant? I made huge progress on the v7 branch, and love to slowly face it torwards beta releases, it would be great if this is still important for you if you'd open a PR so we can get it into v7 ;)

**Comment by mikepenz** [comment]
Thank you so much for the PR. This will get included in the v7 update. It still takes a bit to completely wrap it up as iconics and fastAdapter need to get a final release first ;)
