### ISSUE TITLE
how to solve this

### ISSUE THREAD

**Issue by Prabha10cs** [mikepenz/MaterialDrawer#2402]
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:14:5-134:19 to override.

**Comment by mikepenz** [comment]
By reading the README :) 

v6.1.2 uses androidX
if you use appcompat 28 you need to use something lower than 6.1.0 

Always check the release notes page which release contains the according support lib version you use in your project
