### ISSUE TITLE
is there is simple way to use MaterialDrawer in many activitys 

### ISSUE THREAD

**Issue by heshesh2010** [mikepenz/MaterialDrawer#2403]
Hi , 

I have using MaterialDrawer , but i have many activity like mainActivity - adminActivity - addCourseActivity and so on , so i want to use you MaterialDrawer in all these activities without much code to create in every file

**Comment by zTrap** [comment]
Read this: [MaterialDrawer in multiple activities](https://android.jlelse.eu/android-using-navigation-drawer-across-multiple-activities-the-easiest-way-b011f152aebd)

**Comment by heshesh2010** [comment]
thank you
