### ISSUE TITLE
Does the drawer survive config changes?

### ISSUE THREAD

**Issue by KhyatiMehta3** [mikepenz/MaterialDrawer#2405]
I have an application where I want to use this material drawer but can it survive orientation changes? Also, can latest android architecture components be used to implement the material drawer? 
Lastly, if I have a pre-androidX configuration, how do I use the drawer?

**Comment by mikepenz** [comment]
It is up to the developer to provide the items again after the activity is recreated, as a config change will correctly completely recreate the activity and all its views (including the drawer)

So after config change, just fill up the drawer again with the items, and provide the savedInstanceState (like shown in the sample application) The drawer will make sure the same item is selected again. 

Sadly the drawer does not completely keep the state for you as this logic can be highly application specific (for example custom items not known to the library, or other data), so we leave that up to the developer. 

To use pre-androidX please see the README:
https://github.com/mikepenz/MaterialDrawer#1-provide-the-gradle-dependency
As noted, simply use a version smaller than 6.1.0. So for example: v6.0.9
