### ISSUE TITLE
Theming with Colorful Library

### ISSUE THREAD

**Issue by shripal17** [mikepenz/MaterialDrawer#2406]
## About this issue

Material Drawer doesn't automatically apply Dark Theme when using the [Colorful](https://github.com/garretyoder/Colorful) Library for Theming

Any sample implementation with the [Colorful](https://github.com/garretyoder/Colorful) library?

## Details
- [ 6.1.1 ] Used library version
- [ AndroidX 1.0.0 ] Used support library version
- [ 5.1 ] Used gradle build tools version
- [ 3.4 Canary 10 ] Used tooling / Android Studio version
- [ [Colorful](https://github.com/garretyoder/Colorful) ] Other used libraries, potential conflicting libraries

Used MaterialDrawerKt v2.0.1 as my project is Kotlin based

One of My Apps: https://github.com/shripal17/Wallow

## Checklist

- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
I do not use the `Colorful` library and it is in no way related to the `MaterialDrawer` as such there is no sample or anything. 

I guess you will have to look at the API of Colorful and check how you can theme normal views. 

The `MaterialDrawer` supports theming via the `themes.xml` and `styles.xml` it also offers a light and dark theme. 

Just check out the sample application. For example dark theme:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/AndroidManifest.xml#L37

You can also see in the README all colors and style attributes which can be themed:
https://github.com/mikepenz/MaterialDrawer#style-the-drawer

**Comment by shripal17** [comment]
Alright I will try adding the dependency.

Any additional steps? Or just adding the dependency will work?

**Comment by mikepenz** [comment]
You should use the resolution strategy to overrule the version. 

this dependency is a dependency of the `MaterialDrawer` but a older version is included, so you will need to tell gradle to use the newer version. 

This can be done similar to the resolution strategy here: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/build.gradle#L88

**Comment by shripal17** [comment]
Okay got it. Will try and respond in some time

**Comment by mikepenz** [comment]
If you have updates please report back, closing for the time being.
