### ISSUE TITLE
Move menu to the left side and open with touch

### ISSUE THREAD

**Issue by RAM0112** [mikepenz/MaterialDrawer#2407]
Can I slide open the menu open from the left, currently the code I am using (which could be quite old now) opens the menu from the right via a button click?

I'm using b4a also.

I checked the date created on an xml file to be 2015, so the lib is a few years old.

thanks

**Comment by mikepenz** [comment]
I don't know what "b4a" is. 

Also no support for older versions than the current major version. 

But it seems you have your app in RTL mode. usually it opens from the left by default :D 

Just check out the sample application, it also shows various configurations and different combinations. 
Like the `MultiDrawer` sample which has a drawer on both sides. 

Btw. the whole "gravity" thing is default `DrawerLayout` functionality, there is nothing special in the `MaterialDrawer` library about it :). 
Just follow how it is done with the `DrawerLayout` to work with the gravity. 

Also sliding in with touch from the side is provided from the `DrawerLayout` which is from Google :D
