### ISSUE TITLE
Navigation Library Support?

### ISSUE THREAD

**Issue by percula** [mikepenz/MaterialDrawer#2408]
Question: Are there any plans to include support for the new androidx navigation library, or reasons it won't work?

**Comment by mikepenz** [comment]
Hi.

So the `Navigation Library` is closed down, it does not allow the amount of flexibility the `MaterialDrawer` offers. It is perfect for minimal cases where you don't need a lot of customization. 

Also there are no real available api's to make use of it inner logics or elements. 

As such it sadly has to stay 2 different things. 

I hope that answers your question :)

**Comment by percula** [comment]
Thanks. I really wish they had made it a more open API. I was poking around the source after asking this question and couldn't find a good way to integrate the two either.
