### ISSUE TITLE
using Image as Drawer Header

### ISSUE THREAD

**Issue by QaziAbeelQureshi** [mikepenz/MaterialDrawer#2409]
I Want to Use Image As A drawer Header. what should i do ??

**Comment by mikepenz** [comment]
You can either provide your own item as first element. 
Or you can provide a header view via:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L559

Or you use the `AccountHeader` just for the default header element and set an image to it:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java

Also check out the `MultiDrawer` sample it also has a header with only an image:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MultiDrawerActivity.java
