### ISSUE TITLE
How to change background color of the menu?

### ISSUE THREAD

**Issue by KChernenko** [mikepenz/MaterialDrawer#241]
Hello! Could you tell me how can I override background color of the menu into white.
![screenshot_2015-04-21-12-29-15](https://cloud.githubusercontent.com/assets/3322440/7249458/30b00e42-e823-11e4-99df-972ffa54788a.png)

I'm using `MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus` theme.

**Comment by raghunandankavi2010** [comment]
@KChernenko its the toolbar. you can style the popup by adding

    app:popupTheme="@style/ThemeOverlay.AppCompat.Light"

**Comment by mikepenz** [comment]
@raghunandankavi2010 thanks.

@KChernenko see @raghunandankavi2010 s comment. you have to style the overlay and set it for the toolbar. can't do this in the MaterialDrawer theme

**Comment by KChernenko** [comment]
Greate. @raghunandankavi2010, @mikepenz thanks!
