### ISSUE TITLE
Removing SubItems

### ISSUE THREAD

**Issue by FaramarzZ** [mikepenz/MaterialDrawer#2410]
1- removing a subitem is not possible by removing it's parent.
2- assuming items are read from a preset and fixed arraylist, removing subitems removes them from the array list too. (when subitem is current)

**Comment by mikepenz** [comment]
If you remove elements which are currently visible (subitems) you will also need to inform the recyclerview that the items are now gone.. so as sub items need to be handled somewhat special, there is also a special `notify*` method to notify when sub items changed. 

You might should consider looking at some more code / samples in the FastAdapter

**Comment by mikepenz** [comment]
Please report back. close for the time being
