### ISSUE TITLE
Reducing accessibility issues reported by Pre-launch report in Google Play

### ISSUE THREAD

**Issue by afarber** [mikepenz/MaterialDrawer#2414]
Good afternoon, 

the MaterialDrawer library (and FastAdapter + Android Iconics) work very well for me, thank you.

However I wonder if it is possible to reduce the supposedly accessibility issues reported by Google Play Pre-launch report for [my app](https://play.google.com/store/apps/details?id=de.slova).

1) For example it is missing a readable label for the header -

<img width="863" alt="screenshot 2019-01-26 at 16 27 09" src="https://user-images.githubusercontent.com/1884458/51789260-4c8b2600-2187-11e9-9cfd-a98848c379a3.png">

but I cannot find how to add a label in my code:

```
        mAccountHeader = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.side_nav_bar)
                .withOnlyMainProfileImageVisible(true)
                .withCompactStyle(true)
                .withDrawer(mNavigationDrawer)
                .withTextColor(Color.WHITE)
                .build();
```

2) Also, I am not sure how to add a readable label to the drawer items -

<img width="863" alt="screenshot 2019-01-26 at 15 59 35" src="https://user-images.githubusercontent.com/1884458/51789137-4a749780-2186-11e9-893b-5e560c283ecd.png">

Here is my item:

```
    private final PrimaryDrawerItem mFinishedItem = new PrimaryDrawerItem()
            .withName(R.string.item_finished_games)
            .withIdentifier(R.id.navi_drawer_finished)
            .withIcon(FontAwesome.Icon.faw_database)
            .withSelectable(true)
            .withOnDrawerItemClickListener((view, position, drawerItem) -> {
                FinishedGamesFragment f = FinishedGamesFragment.newInstance();
                getSupportFragmentManager()
                        .beginTransaction()
                        .replace(R.id.root, f)
                        .commitAllowingStateLoss();
                return false;
            });
```

3) And I am not sure why does the report thinks that I have a clickable item right below the header:

<img width="863" alt="screenshot 2019-01-26 at 16 01 16" src="https://user-images.githubusercontent.com/1884458/51789189-83147100-2186-11e9-8c57-d9edc351b20b.png">

4) Finally it reports multiple spots where several clickable items share same location -

<img width="863" alt="screenshot 2019-01-26 at 16 03 11" src="https://user-images.githubusercontent.com/1884458/51789200-af2ff200-2186-11e9-8da5-bc5dc8222f57.png">

5) And here is one more issue, but maybe the Pre-launch report is confused by the russian label -

<img width="863" alt="screenshot 2019-01-26 at 16 04 29" src="https://user-images.githubusercontent.com/1884458/51789211-c7077600-2186-11e9-804d-dc6863639340.png">

```
    private final PrimaryDrawerItem mLetterHard = new PrimaryDrawerItem()
            .withName(R.string.item_letter_hard)
            .withIdentifier(R.id.navi_drawer_letter_hard)
            .withIcon(FontAwesome.Icon.faw_lock)
            .withOnDrawerItemClickListener(mFetchWordsListener)
            .withTag(R.id.navi_drawer_letter_hard);

    private final PrimaryDrawerItem mLetterEh = new PrimaryDrawerItem()
            .withName(R.string.item_letter_eh)
            .withIdentifier(R.id.navi_drawer_letter_eh)
            .withIcon(FontAwesome.Icon.faw_lock)
            .withOnDrawerItemClickListener(mFetchWordsListener)
            .withTag(R.id.navi_drawer_letter_eh);
```

Thank you for any hints

## Details
- [6.1.2] Used library version
- [2.1.0-alpha01] Used arch library version
- [3.3.0] Used gradle build tools version
- [3.3] Used tooling / Android Studio version
- [3.3.1] FastAdapter
- [3.1.0] Android Iconcis

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thanks for the report. I will add a label for the first problem into v7 of the MaterialDrawer, and introduce a new API to allow setting the content description for items to solve the second issue.

For the third issue, I am not sure, the `DividerDrawerItem` is not clickable, not enabled, and the accessibility info is set to not important. so :/

for the fourth issue, that might be a problem of that tool, the `DrawerLayout` itself should make sure that it does not allow clicking through (which is strange :D)

and for the fifth, possibly :D
