### ISSUE TITLE
gradle build error: testImplementation

### ISSUE THREAD

**Issue by codaman** [mikepenz/MaterialDrawer#2416]
I got error when compiling as with Android Studio 3.3

ERROR: Configuration with name 'testImplementation' not found.

Gradle version: 4.10.1
Android Plugin Version: 3.3.0

I tested also gradle 5.1 and plugin 3.4.0 alpha 08

**Comment by mikepenz** [comment]
in your project?
that is not related to this library for integrating it in your project.

**Comment by mikepenz** [comment]
I can not detect any issues with running the samples of this repo. 

Perhaps something strange with the setup?

**Comment by mikepenz** [comment]
Closing. Please add new information if still relevant
