### ISSUE TITLE
Android Studio application build problem

### ISSUE THREAD

**Issue by itzThiefz-exe** [mikepenz/MaterialDrawer#2419]
Before the new version ### 7.x of MaterialDrawer I could compile my project in java of Android studio without problems, but now with this new version. 

I am having the following problem: "**_com.android.builder.merge.DuplicateRelativeFileException: More than one file was found with OS independent path 'META-INF / library_release.kotlin_module_**'. Any solution to this or could lord fix this problem with **Android Studio projects in Java**?

**Comment by mikepenz** [comment]
@itzThiefz-exe that seems to happen if multiple dependencies/modules with kotlin are in an app.

You can add:

```
packagingOptions {
    exclude 'META-INF/library_release.kotlin_module'
}
```

to the build.gradle

**Comment by itzThiefz-exe** [comment]
Obtain again the same error message even by entering the code you recommended. What I can do?

**Comment by mikepenz** [comment]
the same error are you sure? did you also add it to the right build.gradle in the correct module?

**Comment by itzThiefz-exe** [comment]
Yes. Add it to the build.gradle (Module: app)

**Comment by mikepenz** [comment]
and the exact same log appeared or was it a different file? (there might be various of those kotlin files which need to be excluded)

**Comment by itzThiefz-exe** [comment]
I already managed to repair it, I had to delete the Build folder and rebuild the project.

**Comment by dafi** [comment]
Apologize me if I reopen this bug I'm unable to compile my project using version 7.0.0-rc02.

Adding exclusion inside `packagingOptions` doesn't resolve.

May you consider to change the module name directly inside your library?

In my libraries I change `kotlinOptions`, take a look at my [build.gradle](https://github.com/ternaryop/TinyFeedly/blob/master/library/build.gradle#L16)

**Comment by mikepenz** [comment]
@dafi you might need to adjust the packageOptions to whatever file conflicts. 

interesting. I am still curious on why this situation exists in general, as I believe it should be handled by the android tooling
