### ISSUE TITLE
Support Library v22.1

### ISSUE THREAD

**Issue by MassiveZergInc** [mikepenz/MaterialDrawer#242]
Hello,

the app crashes when i set the theme to MaterialDrawerBaseBaseTheme.Light.DarkToolbar, but only when i use the new supported library version 22.1.

**Comment by jahirfiquitiva** [comment]
I have the same issue, though I'm using
MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus

**Comment by raghunandankavi2010** [comment]
In the library styles we had

   <style name="MaterialDrawerBaseBaseTheme.Light.DarkToolbar" parent="Theme.AppCompat.Light.DarkActionBar">

Which caused the crash.

Changing it to Theme.AppCompat.Light.NoActionBar works. But i am not sure why. 

Something to so with changes in appcompat library!. http://android-developers.blogspot.in/2015/04/android-support-library-221.html

Also your activities need to extend from AppCompatActivity

**Comment by mikepenz** [comment]
@MassiveZergInc @jahirfiquitiva @raghunandankavi2010 i assume this is now a problem with all my libraries and i have to update them step by step. 

For the moment i recommend to use the old support libraries til i've updated everything

**Comment by raghunandankavi2010** [comment]
@mikepenz ok. will use the old one for now. I am trying to figure out What attribute features are not allowed?

**Comment by mikepenz** [comment]
@raghunandankavi2010 thanks

**Comment by mikepenz** [comment]
@MassiveZergInc @jahirfiquitiva @raghunandankavi2010

I (think) found a solution. You can use the newest support libs if you exclude the old ones from the libs you use. Here's how i did it for *wallsplash*

```gradle
compile('com.mikepenz.materialdrawer:library:2.7.9@aar') {
        transitive = true
        exclude group: 'com.android.support'
}
compile('com.mikepenz.aboutlibraries:library:4.6.0@aar') {
        transitive = true
        exclude group: 'com.android.support'
}
```

**Comment by raghunandankavi2010** [comment]
@mikepenz if you remove the old libs and update your support repository and use the latest one does it still crash??

**Comment by mikepenz** [comment]
@raghunandankavi2010 i added the `exclude` of the support group to the libs and now it works. have you tried it?

**Comment by raghunandankavi2010** [comment]
@mikepenz trying it. i tried it with material drawer. Will try the same with one of my projects

**Comment by raghunandankavi2010** [comment]
@mikepenz take a look @ http://stackoverflow.com/questions/29790070/upgraded-to-appcompat-v22-1-0-and-now-getting-illegalargumentexception-appcompa.

I was getting same crash report.

**Comment by mikepenz** [comment]
@raghunandankavi2010 ah i see. this is an additional theme issue. i had an additional issue that it had conflicts with the old version and it locked up my app

**Comment by raghunandankavi2010** [comment]
@mikepenz the bugs @jahirfiquitiva @MassiveZergInc referred to was related to the one in stackoverflow 

http://stackoverflow.com/questions/29790070/upgraded-to-appcompat-v22-1-0-and-now-getting-illegalargumentexception-appcompa.

@mikepenz  This needs to be updated in your other libraries as well.

**Comment by mikepenz** [comment]
@raghunandankavi2010 yeah saw it already. will do this, this week. i try to get it out today, but i will move to a new apartment so i'm really busy :D

**Comment by mikepenz** [comment]
Fixed in v2.8.0

**Comment by raghunandankavi2010** [comment]
@mikepenz seems good for the new release.

**Comment by mikepenz** [comment]
@raghunandankavi2010 great ;)
