### ISSUE TITLE
Menu switcher

### ISSUE THREAD

**Issue by RimonGazi** [mikepenz/MaterialDrawer#2420]
How to switch menu item when switched Account

**Comment by mikepenz** [comment]
@RimonGazi what do you mean? you want to return to the normal list?

**Comment by RimonGazi** [comment]
@mikepenz Thank you for your quick reply. please see the picture 
![screenshots1](https://user-images.githubusercontent.com/6096176/52706386-82197700-2faf-11e9-961c-19678888b054.png)

**Comment by mikepenz** [comment]
You will need to listen for account changes and then update the list. 

The list can be updated simply by using the `Drawer` object you retrieve after building the drawer, it provides remove, add, .. methods. 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L718-L827

And to detect profile switches add a listener:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L643-L652
The interface of this listener.
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L377-L386

**Comment by RimonGazi** [comment]
@mikepenz Thank you.
