### ISSUE TITLE
Re-arrange items

### ISSUE THREAD

**Issue by eakteam** [mikepenz/MaterialDrawer#2421]
Is there any way to re-arrange the items for e.x with drag and drop functionality after default configuration to give the users better experience ?

**Comment by mikepenz** [comment]
the MaterialDrawer's content is basically a `RecyclerView` with items in it. you can hold of the `RecyclerView` and get a reference to the `Adapter`s . 

You should be in full control and can implement anything you want. 

this is not a feature which the MaterialDrawer directly offers, but you should be able to achieve it with the exposed getters to retrieve the classes. 

You might also look into the samples of the `FastAdapter` which offers drag and drop samples

**Comment by eakteam** [comment]
I understand, thanks for your help. I am daily user of Fast Adapter too but i mean with "Drag and Drop" functionality to be able to give the users a option to drag the items and arrange in runtime. It's dificult to achieve that for the moment, and i fact i can't make it works... Also in my app it include fast adapter. Any idea ?
Best Regards

**Comment by mikepenz** [comment]
as it is not an official feature and not planned I can only refer to the official APIs of the `RecyclerView` which can be used. 

The `MaterialDrawer` offers a getter for the `RecylerView` the `Adapter` and everything so it should be based on the available APIs possible.
