### ISSUE TITLE
MaterialDrawer does not show the correct icon, name and email in the Account Header

### ISSUE THREAD

**Issue by Schwartzalexander** [mikepenz/MaterialDrawer#2422]
I use Volley to asynchronously load the profile picture from a server. This means, when I create the list of ProfileDrawerItems for the logged in profiles (when starting the app), I add a default icon. It should be updated as soon as the Volley request returns the correct icon. The same logic applies, when adding a new account.

This work partly. The correct icons are shown in the full account list (below the Account Header). But in the Account Header, I still see the default icons:

[Example showing the default icon for the latest added profile](https://i.imgur.com/9E1HnfP.png). This picture shows, what the drawer looks like after adding a new profile ("Jubi").

After a successful login, I use `getAccountHeader().getProfiles().add(loadProfile(token));`
to add the new profile to the Account Header. `loadProfile(Token)` looks like this:

  ```
 /**
     * Loads and returns the profile for the given token. If a profile already exists in the map profilesByUserId for the token's userID, that profile is updated, otherwise a new profile is created and put into that map.
     * The returned profile might not yet be ready, when this method returns. Some date is loaded asynchronously: Picture, username, user's first and last name.
     *
     * @param token the token, for which the profile should be created or updated
     * @return the profile
     */
    public ProfileDrawerItem loadProfile(Token token) {
        ProfileDrawerItem profile = profilesByUserId.get(token.getUserId());
        if (profile == null) {
            profile = new ProfileDrawerItem();
            profilesByUserId.put(token.getUserId(), profile);
            profile.withIdentifier(token.getId());
            profile.withName(token.getUsername());
            profile.withIcon(R.drawable.default_profile_pic);
        }

        loadProfileData(token);
        loadProfilePic(token);
        return profile;
    }
```
`loadProfileData(Token)` and `loadProfilePic(Token)` contain the Volley requests. `onSuccess(...)` is called, when the request returns successfully.

`loadProfileData(Token)`:

  ```
 /**
     * Loads the profile data (user's name and email address) for the given token and sets it in the appropriate profile. If there is no profile for the given token, nothing happens.
     *
     * @param token token, for which the profile data should be loaded
     */
    private void loadProfileData(final Token token) {

        final ProfileDrawerItem profile = profilesByUserId.get(token.getUserId());
        if (profile == null)
            return;

        // Load name and email address
        Callback<User> callbackUser = new Callback<User>() {
            @Override
            public void onSuccess(User user) {
                profile.withName(String.format("%s %s", user.getFirstName(), user.getLastName()));
                profile.withEmail(user.getUsername());
                profile.withNameShown(true);
            }

            @Override
            public void onError(String error) {
               // not relevant
            }
        };
        loadUserById(token.getUserId(), Source.LOCAL_OVER_REMOTE, callbackUser, token);
    }
```
`loadProfilePic(Token)`:

 ```
   /**
     * Loads the profile pic for the given token and sets it in the appropriate profile. If there is no profile for the given token, nothing happens.
     *
     * @param token token, for which the profile pic should be loaded
     */
    private void loadProfilePic(final Token token) {

        final ProfileDrawerItem profile = profilesByUserId.get(token.getUserId());
        if (profile == null)
            return;

        // Load profile pic
        Callback<File> callbackPic = new Callback<File>() {
            @Override
            public void onSuccess(File profilePic) {
                Bitmap bitmap = FileUtils.createBitmap(profilePic);
                // Crop center square of the bitmap
                int dimension = Math.min(bitmap.getWidth(), bitmap.getHeight());
                bitmap = ThumbnailUtils.extractThumbnail(bitmap, dimension, dimension);
                profile.withIcon(bitmap);

            }

            @Override
            public void onError(String error) {
                // Not relevant
            }
        };
        loadProfilePicById(token.getUserId(), true, callbackPic, true);
    }
```
My expectation is that after `onSuccess(File)` has executed, the new profile pic should be shown in the Account Header and in the account list below the header. However, the pic, name and email in the Account Header are not updated. Only after switching profiles, which executes `getAccountHeader().setActiveProfile(token.getId())`, the correct data and pic are shown in the Account Header.

To me, this looks, like it was an issue with MaterialDrawer, but I'm not sure about that. And even if it were, maybe there is a workaround.

Does any one know, how I can get MaterialDrawer to refresh the Account Header, after changing a profile, or how else I can solve this issue?

## Details
- [ ] Used library version
    implementation "com.mikepenz:materialdrawer:6.1.2"
- [ ] Used support library version
    implementation "androidx.appcompat:appcompat:1.0.2"
    implementation "androidx.recyclerview:recyclerview:1.0.0"
    implementation "androidx.annotation:annotation:1.0.1"
    implementation "com.google.android.material:material:1.0.0"
    implementation "androidx.constraintlayout:constraintlayout:1.1.3"
- [ ] Used gradle version
    4.6
- [ ] Used Android Studio version
    3.2.1
- [ ] Used Android Plugin version
    3.2.1
- [ ] Other used libraries, potential conflicting libraries
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0-alpha4', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    wearApp project(':wear')
    implementation 'com.google.android.gms:play-services-maps:16.0.0'
    implementation 'com.google.android.gms:play-services-location:16.0.0'
    implementation 'com.commit451:PhotoView:1.2.4'

    // Butterknife
    implementation 'com.jakewharton:butterknife:9.0.0-SNAPSHOT'
    annotationProcessor 'com.jakewharton:butterknife-compiler:9.0.0-SNAPSHOT'

    // Firebase
    implementation 'com.google.firebase:firebase-core:16.0.6'
    implementation 'com.google.firebase:firebase-appindexing:17.1.0'

    implementation 'com.nineoldandroids:library:2.4.0'
    implementation 'com.daimajia.easing:library:1.0.0@aar'
    implementation 'com.daimajia.androidanimations:library:1.0.8@aar'
    implementation 'org.greenrobot:greendao:3.2.2'
    implementation 'com.android.volley:volley:1.1.1'
    implementation 'commons-codec:commons-codec:1.10'
    testImplementation 'junit:junit:4.12'

    // Material Drawer
    implementation "com.mikepenz:materialdrawer:6.1.2"
    // Material Drawer required support lib modules
    implementation "androidx.appcompat:appcompat:1.0.2"
    implementation "androidx.recyclerview:recyclerview:1.0.0"
    implementation "androidx.annotation:annotation:1.0.1"
    implementation "com.google.android.material:material:1.0.0"
    implementation "androidx.constraintlayout:constraintlayout:1.1.3"

    // Google Material and FontAwesome Icons
    implementation 'com.mikepenz:iconics-core:3.1.0@aar'
    implementation 'com.mikepenz:google-material-typeface:3.0.1.2.original@aar'
    implementation 'com.mikepenz:fontawesome-typeface:4.7.0.2@aar'
    implementation 'androidx.multidex:multidex:2.0.1'

    implementation 'com.google.code.gson:gson:2.8.5'
    annotationProcessor 'com.google.auto.service:auto-service:1.0-rc2'

    implementation 'com.google.guava:guava:26.0-android'

    // Glide media management and image loading framework
    implementation 'com.github.bumptech.glide:glide:4.8.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'

    // Maps SDK for Android Utility Setup
    implementation 'com.google.maps.android:android-maps-utils:0.5'

}
```
Note: I already asked the same question on [stackoverflow ](https://stackoverflow.com/questions/54169012/why-does-mikepenzs-materialdrawer-not-show-the-correct-icon-name-and-email-in) without an answer.

**Comment by mikepenz** [comment]
The header uses the following to load images:

https://github.com/mikepenz/MaterialDrawer#load-images-via-url

(this was introduced to have a generic way of allowing any image loader you may use)

**Comment by Schwartzalexander** [comment]
> The header uses the following to load images:
> 
> https://github.com/mikepenz/MaterialDrawer#load-images-via-url
> 
> (this was introduced to have a generic way of allowing any image loader you may use)

Thank you @mikepenz. I am going to try that. But what about the name and email? These don't get updated in the header, either. See [example](https://i.imgur.com/9E1HnfP.png).

**Comment by mikepenz** [comment]
You are calling the "update" method to notify about updated elements in the header?
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L244

**Comment by Schwartzalexander** [comment]
I was not. But I just tried it. Calling `updateProfile(@NonNull IProfile)` seems to solve that problem, but it introduces some other problems, I never had before.

1. Some times, the profile list can no longer be expended propperly: When I click on the little arrow, nothing happens. Only when I swipe the menu up or down, the default menu items disappear and the profiles are shown instead.
2. Some times, the menu breaks completely, meaning that the menu items get selected on click, but the appopriate actions (attaching fragments) are not executed. When this happens, the other profile icons and the active profile name/email disappear, too.

I will have to investigate this more deeply.

Thank you for the help :)

**Comment by mikepenz** [comment]
That sounds like these could actually be something related to v7 :) 

thank you so much for helping to figure this out ;)

**Comment by rmayayo** [comment]
I'm having a similar issue in 6.0.9. When adding more than 4 accounts, the first 4 accounts will show the proper username in the header. Once I pick the 5th or lower account on the list, it just remains populated with the name of the first account on the list.

**Comment by mikepenz** [comment]
@rmayayo can you please provide some sample to reproduce this issue? (based on the sample app?)

**Comment by mikepenz** [comment]
Please provide more details to be able to handle this issue
