### ISSUE TITLE
Make Drawer.deselect() optionally call protected resetStickyFooterSelection()

### ISSUE THREAD

**Issue by davcpas1234** [mikepenz/MaterialDrawer#2423]
I'm programmatically calling a method to reset the items and selection of my implementation of MaterialDrawer when the user goes "up" my app's backstack.

The issue I'm experiencing appears when attempting to clear all selections of the drawer. When calling the method:
```
drawer.deselect();
```

If the user was last in a sticky footer section, the drawer does not update and deselect when navigating up. This is the result:

![issue](https://user-images.githubusercontent.com/3764587/53102006-c615fa00-3522-11e9-926f-e1c3def4f408.png)

This issue does not occur when the user chooses a navigation item themselves. After a bit of a dive into the source I've noticed this protected method being called:
```
/**
 * simple helper method to reset the selection of the sticky footer
 */
protected void resetStickyFooterSelection() {
    if (mStickyFooterView instanceof LinearLayout) {
        for (int i = 0; i < (mStickyFooterView).getChildCount(); i++) {
            (mStickyFooterView).getChildAt(i).setActivated(false);
            (mStickyFooterView).getChildAt(i).setSelected(false);
        }
    }
}
```

This method is called from the `notifySelect()` method but not the `deselect()` method.

If I modify the my method to include this code:
```
drawer.deselect();

ViewGroup stickyFooterView = (ViewGroup) drawer.getStickyFooter();
if(drawer.getStickyFooter() instanceof LinearLayout) {
    for (int i = 0; i < (stickyFooterView).getChildCount(); i++) {
        (stickyFooterView).getChildAt(i).setActivated(false);
        (stickyFooterView).getChildAt(i).setSelected(false);
    }
}
```
It works as expected.

Would it be possible to add an optional parameter to `deselect()` to "reset" the sticky footer items as well? Such as:

```
/**
 * deselects all selected items
 */
public void deselect(boolean resetStickyFooterItems) {
    getAdapter().deselect();
    if(resetStickyFooterItems){
        mDrawerBuilder.resetStickyFooterSelection();
    }
}
````

**Comment by mikepenz** [comment]
@davcpas1234 thank you very much for this great investigation. 

I'll give it a look and hopefully have it fixed / included in one of the next releases

**Comment by mikepenz** [comment]
this will be in the upcoming v7 upgrade of the MaterialDrawer. thanks again for the report
