### ISSUE TITLE
Customize AccountHeader

### ISSUE THREAD

**Issue by Kashish-Sharma** [mikepenz/MaterialDrawer#2425]
![screenshot_20190305-113854](https://user-images.githubusercontent.com/26424111/53784636-eb036780-3f3b-11e9-982c-862a4c4ae0aa.jpg)
 How to change the name and email textColor in AccountHeader.
And also how to remove the extra space above the user avatar!

**Comment by mikepenz** [comment]
See the style section here:

https://github.com/mikepenz/MaterialDrawer#style-the-drawer

you can theme the drawer and you can change the used color attributes. 



It seems like you already modified the header layout with those 3 buttons?
You might want to modify the height of the header via: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L167

**Comment by Kashish-Sharma** [comment]
Thanks for the quick reply!
I tried changing the header height directly from xml but there's a block above the user avatar which is fixed and its height doesn't change.
As you can see in the screenshot itself there's just too much margin above the avatar.

**Comment by Kashish-Sharma** [comment]
It worked !!
Thanks a lot, you're the best!

**Comment by nataliegerman** [comment]
@Kashish-Sharma can you please tell how did you make this custom drawer? with separation lines and custom header?
I can't even change the header height...
Thanks in advance

**Comment by Kashish-Sharma** [comment]
Hi @nataliegerman you can copy [this](https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml) file in your res folder and make edits there.
But you can only add views in their not remove. If you don't want any view present their just set it's visibility to gone.
