### ISSUE TITLE
Cannot hide the status bar

### ISSUE THREAD

**Issue by upupming** [mikepenz/MaterialDrawer#2427]
## Cannot hide the status bar

My app is a game, and I hide the status bar according to the [Sticky immersive documentation](https://developer.android.com/training/system-ui/immersive#sticky-immersive), it works. However, if I add the `drawer` to my activity, the status bar will show up and cannot be hidden at all.

By the way, my application uses `Theme.MaterialComponents.Light.NoActionBar` theme.

I'm not including the source code here because this is easy to reproduce. If you have some problems on reproducing this, I can create another demo for that.

## Details

- [x] Used library version: Latest
- [x] Used support library version: Latest

```gradle

dependencies {
    implementation 'com.google.android.material:material:1.0.0'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'

    implementation 'com.mikepenz:materialdrawer:6.1.2'
}
```
- [x] Used gradle build tools version: 4.10.1
- [x] Used tooling / Android Studio version 3..3.1

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by upupming** [comment]
Anyone could help with this, thanks in advance!

**Comment by mikepenz** [comment]
@upupming have you checked out the demo application? it has a "fullscreen" sample

**Comment by upupming** [comment]
Thank you so much for the quick reply! I did try the demo but not go deep into other activities other than MainActivity, sorry for the bother. (Maybe we can improve the documentation so people knows all the configurations available.)

However, the demo still has a status bar.

Here is my app without `drawer`:

![image](https://user-images.githubusercontent.com/24741764/54019723-d7b7fc80-41c6-11e9-9066-d836b2ea3910.png)

But after adding the `drawer`, I got this (the status bar shows again):

![image](https://user-images.githubusercontent.com/24741764/54019753-eef6ea00-41c6-11e9-93d3-f1ab6e8e272a.png)

# Code I used

```java
        drawer = new DrawerBuilder()
                .withActivity(this)
                .withFullscreen(true)
                .withSavedInstance(savedInstanceState)
                .....
        .build();
```

```java
        if (Build.VERSION.SDK_INT >= 19) {
            drawer.getDrawerLayout().setFitsSystemWindows(false);
        }
```

**Comment by upupming** [comment]
Don't know why but the status bar goes away if I set the `android:background` for my main activity layout.
