### ISSUE TITLE
status bar hide problem

### ISSUE THREAD

**Issue by phm1015** [mikepenz/MaterialDrawer#2428]
## About this issue

- I am setting drawer after api has been called but initially my status bar gets hidden and after i navigate to other page my status bar is shown
![screen shot 2019-03-08 at 7 23 05 pm](https://user-images.githubusercontent.com/33953391/54032485-bca1b880-41d7-11e9-8c04-807e5c04fbe2.png)
![screen shot 2019-03-08 at 7 23 31 pm](https://user-images.githubusercontent.com/33953391/54032486-bca1b880-41d7-11e9-9b71-1051d95f60b4.png)

**Comment by mikepenz** [comment]
I would assume some combination of the "fitsSystemWindows" flag and the "theme" and the drawer configuration. :/ 

please check the sample app to see how to normally specify it

**Comment by mikepenz** [comment]
Have you figured out what the problem for your case is?

**Comment by mikepenz** [comment]
Closing this as there was no update

**Comment by phm1015** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/2428#issuecomment-478670618
Yes it got resolved in my case after setting header dynamically after getting response from api

**Comment by phm1015** [comment]
But the original problem still remains
I mean you cannot initialize drawer after api has been called
You have to init drawer in oncreate method

**Comment by mikepenz** [comment]
@phm1015 I do not understand. 

It sounds unusual to have no drawer and only add it after the API finished. 

You can have an empty drawer though or a drawer with general items, and just add the items you get from your API at a later point.
