### ISSUE TITLE
updateName of profile

### ISSUE THREAD

**Issue by softmarshmallow** [mikepenz/MaterialDrawer#2429]
## About this issue
```

        activity.viewModel.loadCurrentUser().observe(activity, Observer {
            if (it.status == Status.SUCCESS){
                try {
                    profileDrawerItem.withName(it.data!!.fullName)
                }catch (e: NullPointerException){
                    Timber.i("ERR:: current user is null. Please Check")
                }
            }else Timber.i("ERR:: cannot load current user. Please Check")
        })


```

> Nothing happens with this

- Cannot update name of primary profile.

## Details
- [ 6.2.1] Used library version
- [28 ] Used support library version

**Comment by mikepenz** [comment]
@softmarshmallow after changing a name you need to notify the header about the change (similar like a recyclerview)

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L244
