### ISSUE TITLE
Drawer below the toolbar

### ISSUE THREAD

**Issue by mutindaz** [mikepenz/MaterialDrawer#243]
How do you setup the drawer to be below the toolbar?

**Comment by mutindaz** [comment]
Ooh seems I got the solution.
``` java
drawer.withDisplayBelowToolbar( true );
```

**Comment by mikepenz** [comment]
@mutindaz yes. 
but why would you need this?

it also has a downside -> the shadow which is created by the DrawerLayout is above the toolbar. 
only solution would be to handle the DrawerLayout on your own and let the MaterialDrawer only generate the Drawer content

**Comment by mutindaz** [comment]
@mikepenz have seen the shadow and I had decided to use a custom DrawerLayout. Is there a sample activity you have created that demonstrates how to use .withDrawerLayout() ?

**Comment by mikepenz** [comment]
@mutindaz in the next update there will be a new method which will allow the correct behavior.

**Comment by mikepenz** [comment]
@mutindaz so the newest update v2.8.1 contains a new method which will allow the thing you try. Please look at the new sample activity

**Comment by mutindaz** [comment]
@mikepenz  let me check it out

**Comment by mutindaz** [comment]
@mikepenz  great!!.
In-fact you nailed it here - I had copied the entire convertView() method. 
```java 
convertView = super.convertView(inflater, convertView, parent);
```

**Comment by mikepenz** [comment]
@mutindaz yes :D if you do it different you will loose the original logic. :D this makes only sense if we extend an existing item :D for completely different Custom DrawerItems you will still have to implement the Interfaces and create the complete convertView logic, and everything. But still a lot less work than creating a custom adapter or something...

did the new method work for you to nest the drawerLayout inside your layout?
