### ISSUE TITLE
withHeightDp/withHeightPx doesn't work

### ISSUE THREAD

**Issue by nataliegerman** [mikepenz/MaterialDrawer#2434]
I'm trying to set a smaller height for my header and nothing changes. Only if i set the height to some very high value (e.g. 300) I see the change but not on a smaller values. What am I missing?

```java
  AccountHeader headerResult = new AccountHeaderBuilder()
                    .withTextColorRes(R.color.black)
                    .withActivity(this)
                    .withHeightDp(40)
                    .withSelectionListEnabledForSingleProfile(false)
                    //.withCompactStyle(false)
                    .withProfileImagesVisible(false)
                    .addProfiles(profile)
                    .withSavedInstance(null)
                    .build();
```

**Comment by mikepenz** [comment]
the normal accountHeader is not meant to be used in such a small variant. There is a min height specified to make the contents fit.

There is the compat header which is already smaller. 

If your usecase requires a completely different header consider using just a normal headerview and this allows you to specify anything you need.

**Comment by mikepenz** [comment]
Was the provided answer helpful? Please report back. close until then
