### ISSUE TITLE
com.mikepenz.materialdrawer.R not resolved

### ISSUE THREAD

**Issue by Gkundu1** [mikepenz/MaterialDrawer#2435]
## About this issue
return new IconicsDrawable(ctx).iconText(" ")
                            .backgroundColorRes(com.mikepenz.materialdrawer.R.color.primary)
                            .sizeDp(56);
Here, in the above code, the `com.mikepenz.materialdrawer.R` is not resolved.
- Briefly describe the issue
Project Build and execution is fine, but `com.mikepenz.materialdrawer.R` show as not resolved
- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
implementation('com.mikepenz:materialdrawer:5.9.0@aar') {
        transitive = true
    }
- [ ] Used support library version
[supportLib: "27.1.1"]
- [ ] Used gradle build tools version
classpath 'com.android.tools.build:gradle:3.1.4'
- [ ] Used tooling / Android Studio version
Android Studio 3.3.2
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by Gkundu1** [comment]
Any help regarding the above reported issue

**Comment by mikepenz** [comment]
Just use resources of your project.
