### ISSUE TITLE
Jetpack Navigation Compatibility

### ISSUE THREAD

**Issue by guger** [mikepenz/MaterialDrawer#2437]
Is this library compatible with AndroidX Jetpack's Navigation-UI?

e.g. `mDrawer.setupWithNavController(...)`

**Comment by mikepenz** [comment]
There is no direct dependency to it. This library provides all listeners and callback you might need to implement navigation.

**Comment by guger** [comment]
Would it be a possibility feature/improvement?

**Comment by mikepenz** [comment]
Currently I have no plan yet to directly integrate as it should be possible out of the box via using the listeners. and invoke the relevant calls. 

It might also be possible to write a plugin which hooks up a listener and coordinates with the navigation components if required. 

I am open for more input of people if that is really needed to improve

**Comment by kibotu** [comment]
not sure why but in my current project the combination of material drawer library, [BottomNavigationView](https://material.io/develop/android/components/bottom-navigation-view/) and jetpack navigation components leads to a weird bug where the current fragment gets zero width/height after few navigations (just tabbing bottom navigation tabs few times)

it only occurs when i have material drawer added

**Comment by mikepenz** [comment]
@kibotu I am 99% sure that you have a version conflict. The latest MaterialDrawer RC uses the Material Components 1.1.0-beta08 due to the Shape framework which was embedded into the drawer. 

If you used older versions of the MaterialComponents that most likely will cause conflicts

**Comment by kibotu** [comment]
thanks for the info @mikepenz, i will check the versions throughout the project

**Comment by DanteAndroid** [comment]
@mikepenz Could you provide a document or sample to show how to integrate Navigation with MaterialDrawer

**Comment by mikepenz** [comment]
@DanteAndroid 

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/NavControllerActivity.kt

**Comment by DanteAndroid** [comment]
@mikepenz That's fast. Thanks.
