### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by newfinal100** [mikepenz/MaterialDrawer#2441]
Hello! I'd like to contribute to your project by designing a logo for it. If you'd want that too, please let me know if there are any specific things you'd want this logo to represent, and if you don't have any I'll just implement my own ideas. Looking forward to hearing from you!

**Comment by mikepenz** [comment]
Hi there. 

I really appreciate the offer. 

There was already a similar offer a while ago: https://github.com/mikepenz/MaterialDrawer/issues/2280

Sadly there are currently no real plans to change the logo.

**Comment by newfinal100** [comment]
Oh I didn't know that, that's okay :) thank you for letting me know!
