### ISSUE TITLE
SwitchDrawerItem toggle programatically

### ISSUE THREAD

**Issue by kraghu** [mikepenz/MaterialDrawer#2442]
## About this issue
I am using `SwitchDrawerItem` as one of the drawer item. I want to toggle the drawer state programmatically after initial set up based on the deep link . Currently it works fine with this code at one place,
 ```
SwitchDrawerItem switchItem = new SwitchDrawerItem();
...
rawer.addItem(switchItem.withSelectable(false)
                    .withTag("switch")
                    .withChecked(!enable)
                    .withName(<name>)
                    .withOnCheckedChangeListener((__, ___, ____) -> {
                         // do something
                    }));
```
How do i trigger toggling this switch after this drawer set up ?

**Comment by mikepenz** [comment]
if you modify a item you need to notify the drawer about its change. (like a recyclerView)


https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L654


the README also mentions this:

https://github.com/mikepenz/MaterialDrawer#add-items-and-adding-some-functionality
