### ISSUE TITLE
drawer background gradient

### ISSUE THREAD

**Issue by rexfordnyrk** [mikepenz/MaterialDrawer#2444]
## About this issue

- I am trying to set a gradient background for the drawer but I cant tell where to get started on doing that.
- So instead of having like a white colour which is by default as I do now, I would like to add a gradient rather just like can be done to a view background like so below. Awesome project you got here tho
```
<?xml version="1.0" encoding="UTF-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape>
            <gradient
                android:startColor="@color/application_background"
                android:endColor="@color/bright_red"
                android:angle="45"/>
        </shape>
    </item>
</selector>
```

**Comment by mikepenz** [comment]
@rexfordnyrk thank you very much. 

You can provide a background drawable for the slider here: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L381

**Comment by rexfordnyrk** [comment]
Thanks
