### ISSUE TITLE
Updating the description of an PrimaryDrawerItem

### ISSUE THREAD

**Issue by lcapellanWork** [mikepenz/MaterialDrawer#2445]
I'm kind of using the MaterialDrawer as a shopping cart, everything is perfect, the only problem that I'm having is when trying to update the description of an item, as I have seen, can only update the bade, name, or the icon, but not the description, is there any way that I could update the description? in the meanwhile, I'm deleting de item and just adding it again, but is not an efficient way, and the item changes the position to the last place.
![image](https://user-images.githubusercontent.com/48138150/57146287-fb488f00-6d92-11e9-895b-9d2864e93f0f.png)

**Comment by lcapellanWork** [comment]
In the meanwhile, I'm deleting the item and add it again at the same position, no problems at the moment

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

you can change the item, and then notify the drawer about the update:

```
//modify an item of the drawer
item1.withName("A new name for this drawerItem").withBadge("19").withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.md_red_700));
//notify the drawer about the updated element. it will take care about everything else
result.updateItem(item1);
```

**Comment by lcapellanWork** [comment]
` SecondaryDrawerItem Precio = new SecondaryDrawerItem()
                .withBadge("RD$" + producto.getPrecio())
                .withName("Precio")
                .withSelectable(false)
                .withTag("Sec");

        SecondaryDrawerItem ITBIS = new SecondaryDrawerItem()
                .withBadge("RD$" + producto.getITBIS())
                .withName("ITBIS")
                .withSelectable(false)
                .withTag("Sec");

        SecondaryDrawerItem Desc = new SecondaryDrawerItem()
                .withBadge("RD$" + producto.getDesc())
                .withName("Descuento")
                .withSelectable(false)
                .withTag("Sec");
        double total = producto.getPrecio() + producto.getITBIS() - producto.getDesc();

        PrimaryDrawerItem newItem = new PrimaryDrawerItem()
                .withIdentifier((long) productos.indexOf(producto))
                .withSubItems(Precio, ITBIS, Desc)
                .withName("" + producto.getNombre())
                .withDescription(producto.getCant() + "")
                .withBadge(total + "").withBadgeStyle(new BadgeStyle().withTextColor(Color.WHITE).withColorRes(R.color.md_red_700));
        drawer.addItemAtPosition(newItem, pos + 1);
`
as you may see in my code, i add dynamically every item, so is kind of an array, i just call the method add item and pass some atributtes and thats it, the problem is retrieving those datas

**Comment by mikepenz** [comment]
@lcapellanWork  when you need to modify then, I highly recommend to either keep the reference to the item modify the object, and then notify the drawer about the change. 

Alternative you could give the items a unique identifier and retrieve the item via the identifier and do the same:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L429


Or you will just update the item at the position with a new element:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L712

**Comment by lcapellanWork** [comment]
Thanks for the help, I use the update item at position and it works, but now I think I found a new bug, or maybe I'm doing something wrong, as you see at my code, I have subitems, when I add a new item, if an item at the drawer is open, it will add the sub item, but not the item.
![image](https://user-images.githubusercontent.com/48138150/57228041-dd706980-6fe0-11e9-93e0-a30fa0b6c518.png)

**Comment by lcapellanWork** [comment]
in the meanwhile, I have a really not that memory-friendly of a solution, delete all the items, and reload it again since I save all of the data at an array, I tried to use the notify, but it gives me some kind of thread error.

**Comment by mikepenz** [comment]
Can you please be a bit more specific related to the subitems? 

you change the subItem or you change just an item?

perhaps you might check out v7.0.0-rc01 which comes with the fastAdapter v4 which might fixes this problem

**Comment by Guziq** [comment]
@mikepenz is there any way to update the `ProfileDrawerItem` on `v7.0.0-rc01`? I am failing with:

```
drawer?.updateName(1, StringHolder("Test"))
```

looks like `ProfileDrawerItem` is not `Nameable`.

Sorry for asking this question under this ticket, but I think it is kinda related.

**Comment by mikepenz** [comment]
@Guziq there is a specific method to update profiles: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.kt#L201

**Comment by lcapellanWork** [comment]
> Can you please be a bit more specific related to the subitems?
> 
> you change the subItem or you change just an item?
> 
> perhaps you might check out v7.0.0-rc01 which comes with the fastAdapter v4 which might fixes this problem

As you may see, when we add a new PrimaryItem, we can add SecondaryItems as subitems, the problem is when I delete the parent, in this case,  the primaryItem, the subitems (SecondaryItems) does not, and stay floating there. Is there a way to delete the parent and then the subitems be deleted with the parent?

**Comment by mikepenz** [comment]
@lcapellanWork the most simple and best solution to this is to simply collapse the expanded item and remove the parent then.

**Comment by lcapellanWork** [comment]
> @lcapellanWork the most simple and best solution to this is to simply collapse the expanded item and remove the parent then.

Mhmm gonna try that now, thanks for the help, a lot.
