### ISSUE TITLE
Build fails after library update to 6.1.2

### ISSUE THREAD

**Issue by AkritiSondhi** [mikepenz/MaterialDrawer#2446]
## About this issue
I have updated my app recently, and because of a crash on targeted API level 28, I had to update the version for this library as well (from 5.6.0 to  6.1.2). The project couldn't find "material_drawer_account_header_text" anymore in the updated version. I added a value to this. So, now I get compile time error - “cannot resolve symbol ‘RecyclerViewCacheUtil’. If I comment that code, just to get the project working right now, I get a lot of errors like - "Duplicate class android.support.v4.accessibilityservice.AccessibilityServiceInfoCompat found in modules classes.jar (com.android.support:support-compat:26.1.0) and classes.jar (com.android.support:support-v4:24.1.1)”.

I have only added the androidx dependencies as mentioned in the setup guide, having removed the duplicate entries like 'com.android.support:support-v4:28.0.0’, etc.

## Details
- Used library version - 6.1.2
- Used support library version - androidx 1.0.2
- Used gradle build tools version - 3.4.0
- Used Android Studio version - 3.4
- Other used libraries, potential conflicting libraries - 

```
testImplementation 'junit:junit:4.12'
implementation 'com.squareup.retrofit:retrofit:1.9.0'
implementation 'com.joanzapata.iconify:android-iconify-fontawesome:2.2.2'

// Add dependency injection
annotationProcessor 'com.google.guava:guava:24.1-jre'
annotationProcessor 'com.google.dagger:dagger-compiler:2.5'
implementation 'com.google.dagger:dagger:2.5'
compileOnly 'javax.annotation:jsr250-api:1.0'

implementation 'com.facebook.stetho:stetho:1.3.1'
implementation 'com.facebook.stetho:stetho-okhttp:1.3.1'
implementation 'com.squareup.okhttp:okhttp:2.7.2'
implementation 'it.sephiroth.android.library.targettooltip:target-tooltip-library:1.3.15'

implementation('com.mikepenz:materialdrawer:6.1.2@aar') {
     transitive = true
}

//required support lib modules
implementation "androidx.appcompat:appcompat:1.0.2"
implementation "androidx.recyclerview:recyclerview:1.0.0"
implementation "androidx.annotation:annotation:1.0.2"
implementation "com.google.android.material:material:1.0.0"
implementation "androidx.constraintlayout:constraintlayout:1.1.3"
implementation 'com.mikepenz:fastadapter-commons:3.3.1@aar'

implementation 'com.mikepenz:google-material-typeface:2.2.0.1@aar' //Google Material Design Icons
implementation 'com.mikepenz:fontawesome-typeface:4.6.0.3@aar'
implementation 'com.blankj:utilcode:1.3.4'
```

**Comment by mikepenz** [comment]
Can you check if any other of your dependencies might use support libs?

**Comment by AkritiSondhi** [comment]
Yes, I check the dependency tree, and 2 of my dependencies were internally downloading the support libraries. I was able to successfully create the drawer just now, after fixing a few more issues on my end.
Thanks for the help, and sorry about false alarm. There were a lot of major changes because I had to update from a very old version.
