### ISSUE TITLE
Toggle right drawer with button

### ISSUE THREAD

**Issue by aeroperf** [mikepenz/MaterialDrawer#245]
Thank you for a great library.

I've implemented a right drawer and can swipe it out from the right edge. But I cannot figure out how to refer to the right drawer if I want to toggle show/hide it via button tap. I also have a left drawer and append the right one to it, per instruction.

**Comment by aeroperf** [comment]
I just found my answer here:

https://github.com/mikepenz/MaterialDrawer/issues/205

**Comment by mikepenz** [comment]
@aeroperf great that you found the solution. You can also look at the sample app which implements many different uses
