### ISSUE TITLE
Can't catch back arrow press with included drawer toggle

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/MaterialDrawer#2451]
## About this issue

I can't catch the back arrow click of the included drawer toggle. I've created a very simply MCVE here: 
https://github.com/MFlisar/tests/blob/f97832ff43febf4b88db275652630cd7810161aa/app/src/main/java/com/michaelflisar/tests/tests/drawerTest/TestDrawerActivity.kt#L67-L80

Am I missing something? In the test activity, the back button click always opens the locked drawer instead of going back to level 0.

## Details
- Used library version: 4.0.0
- Used support library version: android x - appcompat 1.0.2
- Used gradle build tools version: 3.4.0

**Comment by mikepenz** [comment]
Remove the `setHomeButtonEnabled(false)` and add a `OnDrawerNavigationListener` which allows you to intercept these event

```kotlin
private fun initViews() {
        drawer = DrawerBuilder()
                .withToolbar(binding.toolbar)
                .withActivity(this)
                .withOnDrawerNavigationListener(object : Drawer.OnDrawerNavigationListener {
                    override fun onNavigationClickListener(clickedView: View): Boolean {
                        if (level == 1) {
                            onBackPressed()
                            return true
                        }
                        return false
                    }
                })
                .build()
    }

    @SuppressLint("SetTextI18n")
    private fun updateViews() {
        binding.tvLevel.text = "Current state: level = $level"
        if (level == 0) {
            //show the hamburger icon
            supportActionBar?.setDisplayHomeAsUpEnabled(false)
            drawer.actionBarDrawerToggle?.isDrawerIndicatorEnabled = true
            drawer.drawerLayout.setDrawerLockMode(DrawerLayout.LOCK_MODE_UNLOCKED)
        } else {
            //show the arrow icon
            drawer.actionBarDrawerToggle?.isDrawerIndicatorEnabled = false
            supportActionBar?.setDisplayHomeAsUpEnabled(true)
            drawer.drawerLayout.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED)
        }
        drawer.actionBarDrawerToggle?.syncState()
    }
```

**Comment by mikepenz** [comment]
(btw. if you remove the home button enabled false, and the drawer lock, then it works out of the box. I have no clue why the drawer lock would break the default behavior)

**Comment by MFlisar** [comment]
Thanks for the help, that works
