### ISSUE TITLE
Is it possible to make a multi selection behavior like in RadioGroup?

### ISSUE THREAD

**Issue by proninyaroslav** [mikepenz/MaterialDrawer#2452]
## About this issue

Hi. Is it possible to make a selection behavior as shown in the screenshot? This allows to select one item only within own group (like `RadioGroup`). I found `withMultiSelect` method in the lib, but this is not what I need. It works like a lot of checkboxes, not like `RadioGroup`.
__P.S:__ maybe I was looking badly and there is already such a solution. Otherwise, I will have to implement it myself (I need to handle the click event of the subitem in the parent to make deselect).

![Screenshot_1561310227](https://user-images.githubusercontent.com/7840559/59979800-e2629a00-95db-11e9-8f27-8367531308e0.png)

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@papageorgiouk no there is not such a functionality in this library as it is very very unusual to have something like this in a drawer. 

the method you found is from the underlaying adapter, as the list is just a `RecyclerView` in the end. 

You can see the sample app and features of the adapter here: https://github.com/mikepenz/FastAdapter

**Comment by proninyaroslav** [comment]
Ok, I'll try to do it. I only care about one question: do I understand correctly that I can't handle click of subitems from the parent code? In this case, the implementation will not be very beautiful.

**Comment by mikepenz** [comment]
@proninyaroslav what do you mean? 

You can listen for clicks on any item. you can find the parent of a child. or the child of a parent. 
you can also deselect or select items programmatically in the adapter

**Comment by proninyaroslav** [comment]
Thank you.
