### ISSUE TITLE
ProfileDrawerItem open or add data property

### ISSUE THREAD

**Issue by mtrakal** [mikepenz/MaterialDrawer#2453]
In 6.x version we used `ExtendedDrawerItem extends ProfileDrawerItem` because we need to provide some data and after click on drawer get this data back. It's not possible do it same way in 7.x because ProfileDrawerItem is final.

Coud it be possible make `ProfileDrawerItem` open for allow extensions or provide inside some data property in which we could store data and after read them?

Thanks

**Comment by mikepenz** [comment]
@mtrakal oh yes absolutely. There are definitely still classes which should be specified open. I don't see a reason why people should not be able to adjust library provided classes
