### ISSUE TITLE
Is there any lite version of this library available?

### ISSUE THREAD

**Issue by rana01645** [mikepenz/MaterialDrawer#2454]
Thank you so much for your awesome library.

The library is very powerful. 

I want to just use a simple drawer with dropdown items and switch items, is there any lite version of this library available for doing this kind of simple work!

**Comment by mikepenz** [comment]
No there is not, as it makes not much sense. If you don't want a drawer according to the material design guidelines. Just use the `DrawerLayout` from google and fill it with a list of yours
