### ISSUE TITLE
Tap on item at n-th position, listener receives n+1

### ISSUE THREAD

**Issue by guilhermearaujo** [mikepenz/MaterialDrawer#246]
This is how I am using the drawer:

When the activity starts I run this:

```java
drawer = new Drawer()
    .withActivity(this)
    .withToolbar(toolbar)
    .withOnDrawerItemClickListener(this)
    .build();
// add a few PrimaryDrawerItems

if (/* user is logged in */) {
    // profileDrawerItem = setup profile

    new AccountHeader()
        .withActivity(this)
        .withDrawer(drawer)
        .addProfiles(profileDrawerItem)
        .build();
}
```

When the user logs in or out, I set `drawer = null;` and re-run the code above. After doing that, the `OnDrawerItemClickListener` starts responding incorrectly. When I click on one item, the listener receives the next item instead.
I am not sure if that is the correct process to add and remove a profile header on demand, but I didn't find any method to remove it after adding it.

**Comment by mikepenz** [comment]
@guilhermearaujo i'm not sure why it will trigger the wrong OnDrawerItemClick event after recreating. 

Normally you should not recreate the drawer. there should only be a single drawer with the same life ccle as your activity. if the activity is recreated you create a new drawer. else you should use the Drawer.Result und update the content of the drawer itself. 

I also recommend to use an AccountHeader with and without a logged in user. You can still display it without any profiles.

**Comment by guilhermearaujo** [comment]
I've been playing with some different setups, and I think I've addressed the n+1 to be caused because I was adding the account header after adding the other items. When I added if before the items, it worked.

Regarding the header visibility, I think that is something I will have to deal for now. I also thought to change its height to 0 depending on user login status, but a method for that is not available. Changing the view's visibility to GONE as a last measure, but as I suspected, it just left a large, empty gray rectangle. I know this is not trivial to fix, bug maybe could be a future improvement.

**Comment by mikepenz** [comment]
@guilhermearaujo ok that sounds strange. can you add some code how you've added the header to the list? the issue with n+1 needs to be fixed :D

**Comment by guilhermearaujo** [comment]
With the same code as I did above:
```
Drawer.Result drawer = new Drawer()
    .withActivity(this)
    .withToolbar(toolbar)
    .withOnDrawerItemClickListener(this)
    .build();

PrimaryDrawerItem item = new PrimaryDrawerItem()
    .withName(getString(R.string.drawer_item))
    .withIdentifier(ID_ITEM);

drawer.addItem(item);

AccountHeader header = new AccountHeader()
    .withActivity(this)
    .withDrawer(drawer)
    .build();
```

I didn't have this problem when I did the opposite, first the header and then the items, like this:

```
AccountHeader header = new AccountHeader()
    .withActivity(this)
    .build();

Drawer.Result drawer = new Drawer()
    .withActivity(this)
    .withToolbar(toolbar)
    .withAccountHeader(header)
    .withOnDrawerItemClickListener(this)
    .build();

PrimaryDrawerItem item = new PrimaryDrawerItem()
    .withName(getString(R.string.drawer_item))
    .withIdentifier(ID_ITEM);

drawer.addItem(item);
```

**Comment by mikepenz** [comment]
@guilhermearaujo that was fast. but i think i found the issue a few seconds ago :dancer:
