### ISSUE TITLE
Design item checked different

### ISSUE THREAD

**Issue by kboirel** [mikepenz/MaterialDrawer#2461]
## About this issue

I don't know why but the items selected are not designed like the demo. 
I spent 3 hours to search how I could change that, without success. Could you help me on that please ?

What I have:
Something like that: https://i.imgur.com/gCgB5PQ.png

What I would like (the rectangle with border radius):
Something like that: https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1nsuL8VDpBW_LZYXgabK1H0uq6icmmKYt%2Fnav-drawer-intro.png

## Details
- [ v6.0.9] Used library version

**Comment by mikepenz** [comment]
because the new design is only introduce din v6.1.x

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/releases

**Comment by kboirel** [comment]
All right, so I can't have it given that I'm using Java?

**Comment by mikepenz** [comment]
v6.1 still uses java
v7.x starts to be in kotlin (you can use it from java, but it will add kotlin to your project)
