### ISSUE TITLE
Suggestion - add easier support for "info" header

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/MaterialDrawer#2462]
I copy & paste following in nearly all my apps as I do not use real profiles anywhere but I want a beatiful drawer header.

Here's what I do:

1) copy my `rectangle_mask.xml` to my app

		<shape xmlns:android="http://schemas.android.com/apk/res/android"
			android:shape="rectangle">
			<solid android:color="#000" />
		</shape>

2) copy the `BezelImageView` style to my app

		<style name="BezelImageView">
			<item name="biv_maskDrawable">@drawable/rectange_mask</item>
			<item name="biv_drawCircularShadow">false</item>
			<item name="biv_selectorOnPress">@color/material_drawer_primary</item>
		</style>
		
3) create my header like following

		val header = BitmapDrawable(resources, BitmapFactory.decodeResource(resources, R.drawable.header))
        header.setColorFilter(ColorUtil.shiftColorUp(Tools.getThemeColor(this, R.attr.colorPrimary)), PorterDuff.Mode.MULTIPLY)

        val headerResult = AccountHeaderBuilder()
            .withActivity(this)
            .withTextColor(Color.WHITE)
            .withHeaderBackground(header)
            .addProfiles(
				// pseudo profile with app name + info + app icon
                ProfileDrawerItem()
                    .withName(R.string.app_name)
                    .withEmail(R.string.app_info)
                    .withIcon(ContextCompat.getDrawable(this, R.mipmap.ic_launcher))
            )
            .withSelectionListEnabledForSingleProfile(false)
            .withProfileImagesClickable(false)
            .build()

**Suggestion**

Actually, it's not about writing the code, it's about copying the resources into all my projects what I dislike. I think, that what I do looks great for all apps that do use your drawer without profiles and a lot better than the boring no header drawer - so I think this would be useful for many others as well. I would suggest to add the ability to remove the bezel mask with a builder function. Alternatively define an alternative style without the circle mask inside your project and allow use to pass a custom style to the header builder.

Just to show you that this looks great, here's a screenshot of my current app:

![Screenshot_20190705-140451_Habit Tracker](https://user-images.githubusercontent.com/2437726/60721395-11f39980-9f2e-11e9-93ba-682e87f8f1d2.jpg)

**Comment by mikepenz** [comment]
@MFlisar I don't think we should do this. The API is provided to allow you to add this kind of customization, but the idea of the `AccountHeader` is mainly to provide support to implement profile support. 

Is there any particular section in the material design guidelines for this kind of header? 
Usually I would suggest simply adding a normal header only view with image (even though I guess even this is no longer a common pattern)

**Comment by MFlisar** [comment]
Even if you don't like the reason I want this (it's not in the design guidelines as far as I know), maybe some easier way to overwrite the `BezelImageStyle` is something you could add? It's cumbersome to add resources vs simply writing one line (or a few lines) of code instead.
