### ISSUE TITLE
about StatusBar 

### ISSUE THREAD

**Issue by woleigeququ** [mikepenz/MaterialDrawer#2465]
i want to :
public abstract class BaseActivity extends AppCompatActivity {
...
        setContentView(initView());

        StatusBarUtil.setRootViewFitsSystemWindows(BaseActivity.this,true);
        StatusBarUtil.setTranslucentStatus(BaseActivity.this);
...

then other activities can display normally , but the MainActivity which create drawer is like this :
 
![problem](https://user-images.githubusercontent.com/28921977/61042564-0230f500-a407-11e9-93cc-c39620d84dd9.jpg)

the top of drawer is normal but main page isn't
so could anyone help me ?    thanks a lot .

**Comment by Okami-x-Senpai** [comment]
That's because you are using a dependency that is not MaterialDrawer. To make the notification bar transparent when you open the menu you have to put this line of code in your MaterialDrawer constructor:

```
        mMainMenu = new DrawerBuilder()
                .....
                .withToolbar(toolbar)
                .withTranslucentStatusBar(true)
                .withTranslucentNavigationBar(true)
```

I hope it works for you. :)

**Comment by woleigeququ** [comment]
i did that , but the problem still.  then i set the backgound color of mainactivity to yellow..  it looks normal..
 I used to think it would automatically turn yellow , just like other activity  ,   i don't know much about it . (ㄒoㄒ)

**Comment by Okami-x-Senpai** [comment]
Try adding
```
android:fitsSystemWindows="true"
```
In the main layout of the activity.

**Comment by woleigeququ** [comment]
i set it in baseactivity after setContentView
public static void setRootViewFitsSystemWindows(Activity activity, boolean fitSystemWindows) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            ...
                    rootView.setFitsSystemWindows(fitSystemWindows);
}}
 i tried to set it in xml,  they have the same effect

**Comment by mikepenz** [comment]
@woleigeququ you use the proper theme?

**Comment by woleigeququ** [comment]
it's my setting of theme :
android:theme="@style/AppNoTitleTheme"
<style name="AppNoTitleTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
</style>
is that correct ? 
and .. i didn't use toolbar , so i didn't set "withToolbar(toolbar)" , does it affect the display?

**Comment by mikepenz** [comment]
You might also want to see comments here: https://github.com/mikepenz/MaterialDrawer/issues/2473
