### ISSUE TITLE
When I use Material Drawer v7.0.0-rc01 all the colors set in my Style.xml stop working

### ISSUE THREAD

**Issue by Okami-x-Senpai** [mikepenz/MaterialDrawer#2466]
When I install the **new version**, **all colors like colorAccent or colorPrimary of my style.xml file stop working and they turn dark black** and it does not matter **if I change the color of my style.xml the color persists**, and **only when I return to the previous version** **my styles work normally**. What I can do? How can I avoid it?

I'm using **Android Studio 3.4.2** with **JAVA programming language** and localized with **JAVA 8**.

**Comment by mikepenz** [comment]
@Okami-x-Senpai v7.x.y of the MaterialDrawer uses 100% kotlin and also the new Material Components. 

You might want to check if your themes are compatible with the Material Components in case you still use appcompat themes.

**Comment by mikepenz** [comment]
https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md

**Comment by Okami-x-Senpai** [comment]
That's right. I was using the parent of Material Components in my main style, but when I use the new version all my main style settings stop working.

**Comment by mikepenz** [comment]
Which version of the Material Components do you use? perhaps a version conflict?

You can try not using the theme from the MaterialDrawer and just add the attributes to your theme
https://github.com/mikepenz/MaterialDrawer#custom-style---stylesxml

**Comment by Okami-x-Senpai** [comment]
**I'm using:**
`implementation 'com.google.android.material: material: 1.0.0'`

**This is the main structure of my main style:**
```
    <style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>

    </style>
```

**Comment by mikepenz** [comment]
The latest rc uses a newer version of the material components 1.1.0-alpha07 or so. because it makes use of the shape theming.

**Comment by Okami-x-Senpai** [comment]
But Gradle tells me that the **1.1.0-alpha8**  is available and when I put that version back all my styles get out of control

**Comment by mikepenz** [comment]
hmmmm so it must be some form of new style definition by the material compnoents library :/ can't really tell what's going on in your project. and seems to be not directly related to this library

**Comment by Okami-x-Senpai** [comment]
I found the problem: The problem is when I use **implementation 'com.google.android.material:material:1.1.0-alpha08'** and now all my colors stop working, but when I go back to **implementation 'com.google.android.material:material:1.0.0'** my application returns to normal.

Using **com.google.android.material: material:1.1.0-alpha08**

![IMG_20190722_112514](https://user-images.githubusercontent.com/47009141/61651808-e1bd3200-ac73-11e9-9dad-1585846cb78f.jpg)

Using **com.google.android.material: material:1.0.0**

![IMG_20190722_112606](https://user-images.githubusercontent.com/47009141/61651867-fe596a00-ac73-11e9-9686-1981f5d487ce.jpg)

As you can see in the screenshots, that's what you spend with my colors and I avoid using the new version of **MaterialDrawer v7.0.0-rc03**

**Comment by mikepenz** [comment]
@Okami-x-Senpai if you can't use the material 1.1.0 (yet) please just fallback to an older version of the MaterialDrawer not yet using this version of the material component library. 

https://github.com/mikepenz/MaterialDrawer/releases/tag/v6.1.2

v7 requires 1.1.0 of the material components library due to the shape system.
