### ISSUE TITLE
Please make BezelImageView open or allow customization of outline

### ISSUE THREAD

**Issue by connyduck** [mikepenz/MaterialDrawer#2468]
I subclass `BezelImageView` in order to provide a custom outline (needed for the elevation shadow to work). This approach works fine with MaterialDrawer 6.1.2 but not with 7.0.0-rc03 since `BezelImageView` is not open.

Yes, I tried your code from https://github.com/mikepenz/MaterialDrawer/issues/617, but it disables the shadow when a custom shape is used, and I really want to have the shadow.

Instead of making `BezelImageView` open I would also be fine with another way of customizing the outline, e.g. a setter method.

See here for me current code: https://github.com/tuskyapp/Tusky/pull/1388

**Comment by mikepenz** [comment]
Thank you for the ticket. I will definitely open up the class. 

I will tro to think of a way to provide the outline, as the outline would be used in various places.
