### ISSUE TITLE
Badge background with state_selected restores the no longer selected item

### ISSUE THREAD

**Issue by dafi** [mikepenz/MaterialDrawer#2469]
I have a BadgeStyle() using `selector` for background

	BadgeStyle()
	    .withTextColorStateList(context.getColorStateList(R.color.drawer_counter_text_selector))
	    .withBadgeBackground(checkNotNull(context.getDrawable(R.drawable.drawer_counter_bg_selector)))

Everything works fine but changing the selected item produces the following result

- the new selected text and badge item is correctly styled
- the no longer selected item has text correctly styled but the badge is drawn as selected

[Here](https://github.com/dafi/material_drawer_badge_background_issue) you can find the project used to reproduce the bug

In attach you can find a .GIF to see what happens, below I describe the steps

selected = badge red background 
not selected = badge green background

1. the app start with item with badge correctly selected (red background)
2. a new item is selected
3. the previous item is styled like no-selected (green background)
4. the item with badge is selected again and it's styled correctly (red background)
5. another item is selected
6. the item with badge is no longer selected but the background used is red!!!!!!

## Details
- [ ] com.mikepenz:materialdrawer:7.0.0-rc03
- [ ] androidx.appcompat:appcompat:1.0.2

![badge_background](https://user-images.githubusercontent.com/84500/61272009-57259000-a7a6-11e9-89b2-117b3a587b68.gif)

**Comment by mikepenz** [comment]
@dafi I will try to give it a look as soon as possible. currently a bit flooded with work

**Comment by mikepenz** [comment]
So I looked into it. as far as I can say this seems to be a platform problem as (according to debugging) the states of the elements are properly set and the drawable initially properly reacts to the updates state. 

but somehow at a later point the system breaks the state for the view. 
(basically the automatic behavior is to fully depend on the system to set the selected state for the view hierarchy. 

So what you can do is to change the selected background to be selected not via the system behavior but with a real update of the element. This will prevent the animation to be properly run though (in case you have a selection animation in place) 

You can achieve this by telling the adapter to update it's item if the selection state changes :

```java
drawer.selectExtension.selectWithItemUpdate = true
```

**Comment by mikepenz** [comment]
Please report back if using the update will fix the problem
