### ISSUE TITLE
Append multiple right-side drawers, tap in darkened area to dismiss does not work.

### ISSUE THREAD

**Issue by aeroperf** [mikepenz/MaterialDrawer#247]
I decided to append three separate right-side nav drawers, each with its own custom view. 

It all works well, showing only one drawer at a time. But only the first appended drawer will close when I tap off the drawer, in the darkened left-side region. The other appended drawers (#2 and #3) will not close when tapped there. You can, however, swipe them away.

Bug or by design? (I know...why would anyone need multiple right nav drawers...?)

**Comment by mikepenz** [comment]
@aeroperf the close is triggered by the DrawerLayout itself so this catches the click and will trigger the hide event. It will then consume the event and the other drawers won't get it anymore. You can listen to the onDrawerClose event of the DrawerLayout and then trigger the close on the other drawers too

**Comment by aeroperf** [comment]
I have three buttons that need to show different custom views. And when I tried out additional appends, and it worked, I that that is good enough for now. But I'll probably rewrite things to only have one right-drawer and pick the custom view to show in it based on which button was tapped. As you mentioned, untested multi-drawers might cause some issues down the road.

Thanks for the onDrawerClose event hint. That should work, if I decide to keep the three drawers.

**Comment by mikepenz** [comment]
@aeroperf great ;)
