### ISSUE TITLE
Not compatible with over "custom recycler adapters" (ShamylZakariya/StickyHeaders)

### ISSUE THREAD

**Issue by argiad** [mikepenz/MaterialDrawer#2472]
I am using "https://github.com/ShamylZakariya/StickyHeaders"
So, after Drawer object was built, StickyHeaders library crashes on scrolling.

Not happens until object created

**Comment by mikepenz** [comment]
@argiad do you have any additional details. crash log. anything?

In general this seems to be an unrelated issue. as the MaterialDrawer does NOT make any use of any external libraries like the StickyHeaders. 

I assume you run into some version conflict in which one lib uses a different version of the RV or stuff like this

**Comment by argiad** [comment]
@mikepenz I will create an application today and will share a git url
but, but I checked this behavior couple times, it happens only in case when the Drawer object created.

**Comment by argiad** [comment]
@mikepenz 
Unfortunately, I can't open sources for public, but can add you to repository.
The Problem is in "onTouchevent" or something so similar.
when the Drawer object created, something happens, I still not figured what. But  I got next errors:

    java.lang.IllegalArgumentException: view is not a child, cannot hide androidx.constraintlayout.widget.ConstraintLayout{c5d2fa6 VFE...C.. ........ 0,565-1028,723 #7f090069 app:id/clHeaderContainer}
 
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.view.View.getTag(int)' on a null object reference

They alternate without any visible dependencies.
When I switch off  Drawer object creation - all works perfect ....

**Comment by argiad** [comment]
Right now found something similar for  both errors...

Before Stack trace :

E/InputEventReceiver: Exception dispatching input event.

**Comment by mikepenz** [comment]
The way the drawer injects itself into the application is the following:

It takes the root of the view hierachy removes it from its parent. adds the DrawerLayout to the parent, and then adds the viewHierachy as child to the DrawerLayout. 

You can adjust the position where it injects which might make a different. 

What I wonder though is. Does the crash start to occur by adding that sticky header library? or does it happen just "randomly"

**Comment by argiad** [comment]
/**
     * Moves a child view from hidden list to regular list.
     * Calling this method should probably be followed by a detach, otherwise, it will suddenly
     * show up in LayoutManager's children list.
     *
     * @param view The hidden View to unhide
     */
    void unhide(View view) {
        final int offset = mCallback.indexOfChild(view);
        if (offset < 0) {
            throw new IllegalArgumentException("view is not a child, cannot hide " + view);
        }
        if (!mBucket.get(offset)) {
            throw new RuntimeException("trying to unhide a view that was not hidden" + view);
        }
        mBucket.clear(offset);
        unhideViewInternal(view);
    }

roots of the error in this function.
the most weird behavior is that after notifyDataSetChanged the RecyclerView doesn't changed (reload) section... and let me repeat - that happens only in case then the Drawer object created.

**Comment by mikepenz** [comment]
It could also be that the new RV library version is causing issues for you?

Perhaps you do something on the wrong thread

**Comment by argiad** [comment]
Found.
It was inside the RecyclerView, but critically activating only in case a builded Drawer object... don't know the reason
