### ISSUE TITLE
Gradient in the user header (cover photo)

### ISSUE THREAD

**Issue by Okami-x-Senpai** [mikepenz/MaterialDrawer#2474]
It would be a good idea to be able to **choose if you want to set a gradient at the bottom of the user's cover photo** , as well as **choose the color of the gradient** .

**Comment by mikepenz** [comment]
could you please be a bit more specific about this request? is this something reflected in the material design guidelines? 

how would this look like?

**Comment by Okami-x-Senpai** [comment]
No, it is not reflected in the Material Design guidelines but it would be something more in style

That has a grady, as well as a transfer effect of a color, for example black, coming from the foot of the header to the top.

**Comment by mikepenz** [comment]
I am not really sure how this would fit into the library itself. You can provide a background for the header yourself and this can be a gradient for example

**Comment by Okami-x-Senpai** [comment]
**Example of Gradient:** 

```
<?xml version="1.0" encoding="utf-8"?> <shape xmlns:android="http://schemas.android.com/apk/res/android"> <gradient android:startColor="#00000000" android:endColor="#80000000" android:angle="270" android:dither="true" /> </shape>

```

**Comment by Okami-x-Senpai** [comment]
Example of Gradient:

```

<?xml version="1.0" encoding="utf-8"?>

<shape xmlns:android="http://schemas.android.com/apk/res/android">

<gradient

android:angle="90"

android:endColor="#00000000"

android:startColor="#222533" />

</shape>

```

**Comment by mikepenz** [comment]
I am closing this as I think this is already possible just using the existing APIs. If not please let me know what you would need to be able to achieve this
