### ISSUE TITLE
tree Menu

### ISSUE THREAD

**Issue by gorisulato** [mikepenz/MaterialDrawer#2475]
Can it implement some menu tree view sir?? thx before

**Comment by mikepenz** [comment]
@gorisulato the included list is a `RecyclerView` and the used adapter is the `FastAdapter` (https://github.com/mikepenz/FastAdapter/) 

As such you can have expanding and collapsing items as shown in the sample at the bottom

**Comment by gorisulato** [comment]
Well thx man... Somehow i got the solution by using subitem and expandable but ill try using adapter later thx man

**Comment by mikepenz** [comment]
@gorisulato the drawer internally uses that adapter, you can access it and can do fancy things :D 

but it is fine to use the provided expandable items and adding subItems
