### ISSUE TITLE
How can i change text size on navigation menu?

### ISSUE THREAD

**Issue by mrDevGo** [mikepenz/MaterialDrawer#2476]
How can i change text size on navigation menu? i need will change size 7 and 6 text.
![nav](https://user-images.githubusercontent.com/48598325/62049458-f53e3f00-b217-11e9-9cdd-36a69cbd6b4e.PNG)

**Comment by mikepenz** [comment]
Specify the custom dimens you need: 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/values/dimens.xml#L44

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/values/dimens.xml#L75

**Comment by mrDevGo** [comment]
Thank you very much ))

**Comment by mrDevGo** [comment]
I apologize, but I did not understand how to change the font in the navigation bar. I need to change the **FONT** (my own font), not the font size

` <style name="AppTheme" parent="MaterialDrawerTheme.Light.ActionBar">
        <item name="android:fontFamily">@font/ubuntu_mono</item>
    </style>`

Throughout the application changes, but not in the material drawer.

**Comment by mikepenz** [comment]
You can set the typeface to items: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/AbstractDrawerItem.kt#L48

**Comment by mrDevGo** [comment]
Thank you very much ))
