### ISSUE TITLE
Good afternoon, please tell me how to change the font in the navigation bar?

### ISSUE THREAD

**Issue by mrDevGo** [mikepenz/MaterialDrawer#2477]
![nav](https://user-images.githubusercontent.com/48598325/62110097-56b4eb00-b2b6-11e9-850c-500b662c1ed2.PNG)
Good afternoon, please tell me how to change the font in the navigation bar?
I need to replace the font in 6 text

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/2476
