### ISSUE TITLE
Please put Multidex application to demo

### ISSUE THREAD

**Issue by mimoccc** [mikepenz/MaterialDrawer#2479]
## About this issue
Hi, there in demo You didnt override MultidexApplication, but simple Application which cause deodex error and raise to ClassNotFoundException, when Your application use multidex (multidex enabled in gradle build file).

- How can the issue be reproduced / sample code
Just compile app and start it.

## Details
build.gradle in app folder:
multiDexEnabled true

CustomApplication.kt:
class CustomApplication : Application()

should be:

class CustomApplication : MultiDexApplication()

or use:

override fun attachBaseContext(base: Context) {
        super.attachBaseContext(base)
        MultiDex.install(this)
    }

**Comment by mikepenz** [comment]
@mimoccc it compiles on travis and locally for me. 

The `multiDex=true` flag should already cover that. :/

**Comment by mimoccc** [comment]
Thats half true, on pre-art (pre-lollipop), or if you like on  android v5.0< devices the dex must be installed first.
It will solve many issues i saw here for you, if you include it, and it would work on kitekat too.
I am sure.
I allready have working copy with that (standard) call.
