### ISSUE TITLE
Please put the sample for using Glide

### ISSUE THREAD

**Issue by Tsabary** [mikepenz/MaterialDrawer#2480]
The link for the sample using Glide to load images into profile photos is broken. Would appreciate a fix. Can'r figure out how to use the DrawerImageLoader with the Drawer and can't find a complete sample

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.kt

**Comment by Tsabary** [comment]
Thank you
