### ISSUE TITLE
Fullscreen activityy does not work

### ISSUE THREAD

**Issue by VahidGarousi** [mikepenz/MaterialDrawer#2483]
## Hi, I made exactly like your code but I get a different result

this is result :
https://ibb.co/pjPkC3P
![image](https://user-images.githubusercontent.com/19606714/63593134-89f24d80-c5c8-11e9-83a8-04963e979026.png)

## My code
`private fun setupDrawer(savedInstanceState: Bundle?) {
        val itemHome = PrimaryDrawerItem()
            .withIdentifier(1)
            .withTypeface(drawerFont)
            .withSelected(true)
            .withIcon(R.drawable.ic_home)
            .withName(R.string.drawer_item_home)
        val itemCategories = PrimaryDrawerItem()
            .withIdentifier(2)
            .withTypeface(drawerFont)
            .withIcon(R.drawable.ic_category)
            .withName(R.string.drawer_item_category)
        val itemFavorite = PrimaryDrawerItem()
            .withIdentifier(3)
            .withTypeface(drawerFont)
            .withIcon(R.drawable.ic_favorite)
            .withName(R.string.drawer_item_favorite)
        // Create the AccountHeader
        val itemAbout = PrimaryDrawerItem()
            .withIdentifier(4)
            .withTypeface(drawerFont)
            .withIcon(R.drawable.ic_about)
            .withName(R.string.drawer_item_about)
        val itemContact = PrimaryDrawerItem()
            .withIdentifier(5)
            .withTypeface(drawerFont)
            .withIcon(R.drawable.ic_call)
            .withName(R.string.drawer_item_contact)
        val itemShare = PrimaryDrawerItem()
            .withIdentifier(6)
            .withTypeface(drawerFont)
            .withIcon(R.drawable.ic_share)
            .withName(R.string.drawer_item_share)
        val itemLogout = PrimaryDrawerItem()
            .withIdentifier(7)
            .withTypeface(drawerFont)
            .withIcon(R.drawable.ic_exit_to_app)
            .withName(R.string.drawer_item_logout)
        val itemLogoutFromApp = PrimaryDrawerItem()
            .withIdentifier(8)
            .withTypeface(drawerFont)
            .withIcon(R.drawable.ic_exit_to_app)
            .withName(R.string.drawer_item_logout_from_app)

        //create the drawer and remember the `Drawer` result object
        result = DrawerBuilder()
            .withActivity(this)
            .withFullscreen(false)
            .withHeader(R.layout.drawer_header)
            .withHeaderHeight(DimenHolder.fromDp(150))
            .addDrawerItems(
                itemHome,
                itemCategories,
                itemFavorite,
                itemAbout,
                itemContact,
                itemShare,
                itemLogout,
                itemLogoutFromApp
            )
            .withDisplayBelowStatusBar(true)
            .withOnDrawerItemClickListener(object : Drawer.OnDrawerItemClickListener {
                override fun onItemClick(
                    view: View?,
                    position: Int,
                    drawerItem: IDrawerItem<*>
                ): Boolean {
                    // do something with the clicked item :D
                    return false
                }
            })
            .build()
        iv_fragmentMain_menu.setOnClickListener {
            result!!.openDrawer()
        }
    }`

**Comment by mikepenz** [comment]
Most likely your theme is configured different and misses some flags.

**Comment by VahidGarousi** [comment]
So what exactly should I do now?

**Comment by mikepenz** [comment]
To be honest I am not yet sure what you want?

The NavigationBar to be translucent? 
If so ensure you properly specify . your theme to have translucent navigationBar, and also specify the proper UI flags. 

This is less a topic of this library but a general android UI topic. 

You can see how it works in the sample app

**Comment by mikepenz** [comment]
Also note that there is a known issue for landscape: 
https://github.com/mikepenz/MaterialDrawer/issues/2493
