### ISSUE TITLE
How to open from top side the material drawer?

### ISSUE THREAD

**Issue by BigGitWorld** [mikepenz/MaterialDrawer#2484]
Hi.
I want to open the material drawer from top side, so that the account header is visible.
In fact, After scrolling the material drawer to some position, it does not open from top side again.
How to open it from top side always?

**Comment by mikepenz** [comment]
I am not sure what you ask? 

You want to open the header? (so the accoutn list is shown?)

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.kt#L116

**Comment by BigGitWorld** [comment]
Suppose my drawer is very long and is scrollable.
So, when user clicks on an item in lower sections of the drawer, my app opens a fragment and close the drawer by ```drawerLayout.closeDrawers();```.
Now, if user again opens the drawer (by clicking the hamburger icon), it will be opened from that section (not top of the drawer) 
What I am looking for is tha user observe the drawer from it's top side section, so that my logo is visible every time user opens the drawer.
How do I have to do it?

**Comment by mikepenz** [comment]
get the reference to the `RecyclerView` and use any of the rv default methods to scroll to top. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.kt#L101

**Comment by 7bd7** [comment]
> get the reference to the `RecyclerView` and use any of the rv default methods to scroll to top.
> 
> https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.kt#L101

Link doesn't work.
