### ISSUE TITLE
Issue with ExpandableDrawerItem

### ISSUE THREAD

**Issue by vivek0203** [mikepenz/MaterialDrawer#2485]
## About this issue

-  ExpandableDrawerItem withSetExpanded(true) causes items below to disappear, only the subitems of that drawer item remain
- Create a menu with multiple items and an expandable drawer item (with 2-3 subitems) on top and try interacting with the menu. 

## Details
- [v7.0.0-rc05] Used library version
- [v1.1.0] Used support library version
- [3.3.1] Used gradle build tools version
- [3.4.2] Used tooling / Android Studio version

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@vivek0203 you can not expand via this method. it is only the flag which is set by the adapter when expanding. 

get the expandableExtension from the adapter and use it to expand an element: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.kt#L147

**Comment by vivek0203** [comment]
thanks for the quick response. I was able to use expandableExtension to make it work.
