### ISSUE TITLE
关于主题的问题

### ISSUE THREAD

**Issue by wangliyang206** [mikepenz/MaterialDrawer#2486]
您好
      我最近在做一个关于切换主题的APP，有幸使用到了MaterialDrawer框架。其它界面均已使用Colorful实现日间、夜间模式切换(无需重启Activity、无需自定义View)， 最后发现MaterialDrawer无法切换。请问，此框架有没有动态切换主题的接口？难道这个问题我只能自定义MaterialDrawer了吗？

**Comment by mikepenz** [comment]
**Please only report issues in english.** 

Closing this one, open a new one translated to english please.
