### ISSUE TITLE
Drawer creates a margin in top

### ISSUE THREAD

**Issue by jlccaires** [mikepenz/MaterialDrawer#249]
When a activity is started from another that has a drawer, it creates a margin above toolbar.

![screen shot 2015-04-22 at 21 31 37](https://cloud.githubusercontent.com/assets/842600/7288377/184e3ca6-e937-11e4-9677-48bb16b83ff9.png)

**Comment by raghunandankavi2010** [comment]
@jlccaires  could you add a sample to reproduce the same!.

**Comment by jlccaires** [comment]
I find a solution!
By some reason, the context from my listView framework is getting some wrong theme context.
i changed this:
```java
Intent intent = new Intent(FirstActivity.this, OtherActivity.class);
startActivityForResult(intent, 0);
```
to this:
```java
Intent intent = new Intent(getApplicationContext(), OtherActivity.class);
startActivityForResult(intent, 0);
```

THE PROBLEM WAS NOT IN MATERIAL DRAWABLE.
Thanks by create this awesome library.

**Comment by mikepenz** [comment]
@jlccaires great that you were able to solve your prolbem
