### ISSUE TITLE
Hide the mini drawer at the beginning

### ISSUE THREAD

**Issue by hjh2881** [mikepenz/MaterialDrawer#2491]
Can MiniDrawer hide mini drawer at the beginning like CrossfadeDrawerLayout?

**Comment by mikepenz** [comment]
There is no officially API for that, you could use the CrossfadeDrawerLayout if that's your desired effect. 

otherwise I suggest you animate the container manually or hide it, and display it when you need it

**Comment by hjh2881** [comment]
Thank you!
