### ISSUE TITLE
Landscape fullscreen bad shadow

### ISSUE THREAD

**Issue by pcegarra** [mikepenz/MaterialDrawer#2493]
I have just runned the demo app in landscape.

You can see the error here:
https://i.imgur.com/C60WHfQ.png

Any idea?

**Comment by mikepenz** [comment]
Ok checked the problem and it is related to the `ScrimsInsetFrameLayout` which will draw the scrims. 

the one included does not allow disabling it for left and right. 

created a branch which allows it theoretically: 
https://github.com/mikepenz/MaterialDrawer/tree/feature/adjusted_scriminset_framelayout

but my goal is anyways to re-think and overwork the whole scrim and insets topic to hopefully also eliminate this problem

**Comment by mikepenz** [comment]
This will be fixed and addressed in v8 of the drawer. No ETA. 

Please refer to the provided branch to see how it could be fixed in v7 or lower
