### ISSUE TITLE
Customize Sticky Footer

### ISSUE THREAD

**Issue by DarrelAeturnum** [mikepenz/MaterialDrawer#2494]
I am creating a sticky footer with multiple custom drawer items extending BasePrimaryDrawerItem. But I am unable to customize the theme upon selection of an item from the footer. Can you help me on this if possible ? Please note that the theme customization is working when the drawer item is added as a normal item.

**Comment by mikepenz** [comment]
the items in the stickyFooter are basically added normally into a layout. As such it is not dynamically loaded in a recyclerView like the other items. 

I would suggest you remove the items from the sticker footer and re-add them after adjusting the theme.

**Comment by DarrelAeturnum** [comment]
It worked. Thanks
