### ISSUE TITLE
Navigation item selection makes all items highlighted

### ISSUE THREAD

**Issue by ronjunevaldoz** [mikepenz/MaterialDrawer#2495]
## Screenshot
![Screenshot_2019-09-05-18-58-46](https://user-images.githubusercontent.com/4947998/64336379-5fb07f00-d00f-11e9-90c4-768921f0d9b4.png)

## About this issue

- Navigation item selection makes all items highlighted
- Navigation item selection sometimes Navigation item is not showing, only blank screen

## Details

- [x] v7.0.0-rc06
- [x] com.google.android.material:material:1.1.0-alpha01
- [x] androidx.navigation:navigation-fragment-ktx:2.1.0-rc01
- [x] androidx.navigation:navigation-ui-ktx:2.1.0-rc01
- [x] https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
- [x] Android Studio 3.4.2

## Code

`DrawerNavigationUI.setupWithNavController(drawer, navController)`

**Comment by mikepenz** [comment]
@ronjunelopez that's interesting. The same seems to not happen in the sample app. have you compared your code?

**Comment by ronjunelopez** [comment]
> @ronjunelopez that's interesting. The same seems to not happen in the sample app. have you compared your code?

using this reference `https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/NavControllerActivity.kt`

`    private fun initDrawer(savedInstanceState: Bundle?) {
        val toolbar = findViewById<Toolbar>(R.id.toolbar)
        setSupportActionBar(toolbar)

        DrawerImageLoader.init(object : AbstractDrawerImageLoader() {
            override fun set(imageView: ImageView, uri: Uri, placeholder: Drawable) {
                Glide
                    .with(this@MainActivity)
                    .load(uri)
                    .centerCrop()
                    .placeholder(placeholder)
                    .apply(RequestOptions.circleCropTransform())
                    .override(128, 128)
                    .into(imageView)
            }

            override fun cancel(imageView: ImageView) {

            }
        })
        // Create the AccountHeader
        accountHeader = AccountHeaderBuilder()
            .withActivity(this)
            .withOnAccountHeaderListener(object : AccountHeader.OnAccountHeaderListener {
                override fun onProfileChanged(view: View?, profile: IProfile<*>, current: Boolean): Boolean {
                    return false
                }
            })
            .build()

        drawer = DrawerBuilder(this)
            .withRootView(R.id.drawer_container)
            .withAccountHeader(accountHeader)
            .withToolbar(toolbar)
            .withDisplayBelowStatusBar(false)
            .withActionBarDrawerToggle(true)
            .withActionBarDrawerToggleAnimated(true)
            .withDrawerLayout(R.layout.material_drawer_fits_not)
            .addDrawerItems(
                NavigationDrawerItem(
                    R.id.home_fragment,
                    PrimaryDrawerItem()
                        .withName(R.string.drawer_item_home)
                        .withIcon(FontAwesome.Icon.faw_home)
                ),
                DividerDrawerItem(),
                NavigationDrawerItem(
                    R.id.privacy_settings_fragment,
                    PrimaryDrawerItem()
                        .withName(R.string.drawer_item_privacy_settings)
                        .withIcon(FontAwesome.Icon.faw_cog)
                )
            )
            .withOnDrawerItemClickListener(object : Drawer.OnDrawerItemClickListener {
                override fun onItemClick(view: View?, position: Int, drawerItem: IDrawerItem<*>): Boolean {

                    if (drawerItem.identifier == 21L) {
                        presenter.onToolbarOptionSignOutClick()
                    }

                    return false
                }
            })
            .withSavedInstance(savedInstanceState)
            .build()
        navController = findNavController(R.id.nav_host_fragment)
        drawer.setupWithNavController(navController)
    }`

**Comment by yogirana5557** [comment]
Getting same issue using NavController....drawer item selection & fragment backstack seems broken..need some workaround with issue.

**Comment by mikepenz** [comment]
Can you somehow reproduce the issue in the sample app?

**Comment by ronjunelopez** [comment]
> Getting same issue using NavController....drawer item selection & fragment backstack seems broken..need some workaround with issue.

due to critical issue, It s better to use the basics from [Navigation-UI](https://developer.android.com/guide/navigation/navigation-ui).

**Comment by mikepenz** [comment]
we can not reproduce this in the sample app. please add more details or a full (runnable) sample app which showcases the problem

**Comment by kareemzok** [comment]
I m having the same issue with the highlight. When I click on any button other than the home, 
buttons are been highlighted and not cleared. 
On any button click, it should select the clicked one and cleared the others.

![Capture](https://user-images.githubusercontent.com/6444765/68290129-12dd3900-0090-11ea-87de-9c4b0cec6f01.PNG)

**Comment by mikepenz** [comment]
@kareemzok can you please try to reproduce this in the sample app? or adjust the sample app so it showcases your issue? 

I've yet to see this problem :/

**Comment by kareemzok** [comment]
Hello, 

It works now after adding the style theme to the drawer.

**Comment by kareemzok** [comment]
Hello, 

On the sample app it works fine but on my app not.
Should we add something or its included already..

Please advise.

**Comment by mikepenz** [comment]
Well I need help to reproduce the problem to be able to investigate. I have not enough information to figure out what might be going on.

You can see the samples code here: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/NavControllerActivity.kt

perhaps you can find what you di dofferent, or adjust it to make it behave the same as in your app

**Comment by kareemzok** [comment]
In my app I have the item shown in the image above when I click on an item and go to new activity then go back to the home activity I open the drawer, I click on another item  and then go back to the home activity I got 2 item clicked selected while the first selected  one should be cleared.

As per your example, I m doing same for the java code, not kotlin but I don't have fragment, its activities

**Comment by kareemzok** [comment]
I was able to solve it, the issue was from my side as when I defined the item I added the identifier number for all which is 2. After I gave each item an identifier the selection work perfectly now.

**Comment by mikepenz** [comment]
Awesome :)
