### ISSUE TITLE
the PrimaryDrawerItem in MiniDrawerActivity‘s left slider icon does not support online image url？

### ISSUE THREAD

**Issue by AlawnXu** [mikepenz/MaterialDrawer#2496]
## About this issue

- the PrimaryDrawerItem in MiniDrawerActivity‘s left slider icon does not support online image url？
- CustomPrimaryDrawerItem can download online image，but it doesn't support to showing in the second view？
-how to make custom drawerItem showing in second view？

## Details
- [ ] Used library version
MaterialDrawer 6.0.9

**Comment by mikepenz** [comment]
Please follow the issue template.

And no they don't. 


There is a sample item in the sample app which showcases how you can implement it though

**Comment by AlawnXu** [comment]
i know the sample item，however it couldn't show on the second view

**Comment by mikepenz** [comment]
What do you mean by "it couldn't show on the second view"?

**Comment by AlawnXu** [comment]
the miniDrawer cannot load online image url

**Comment by mikepenz** [comment]
@AlawnXu the same would be required to implement a custom item to support images there too. 

This is not a standard functionality as it is uncommon to have remote images in the drawer. usually it is just normal icons. 

For example like this: https://github.com/mikepenz/MaterialDrawer/issues/2114
