### ISSUE TITLE
Hey coders !! Can you tell me that how can i use my own custom header layout ?

### ISSUE THREAD

**Issue by Tinyhuge** [mikepenz/MaterialDrawer#2498]
## About this issue

**is there any way to use my own header Layout with this, like we use in Normal navigation ?**

i want to use my own header Layout with image and some textviews, but i am wondering is there any way ?

**##Thanks for giving your precious time**

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by anggrayudi** [comment]
Can you be a little polite? Please change the title.

**Comment by mikepenz** [comment]
Beside not following the issue template, the sample showcases how you can provide a xml file to display as the header. 

The `AccountHeader` is available in the two variants compact and normal variant (matching the material design guidelines) and does not support other variants.

**Comment by Tinyhuge** [comment]
It means i can't add my own custom header layout with it, like  we used to add in normal  
Navigation Bars ?

And yes sample contains xml file as 'header.xml' but i want  my fully custom Layout with more views and Layouts instead 'one image'  ?

**Comment by mikepenz** [comment]
Well as you say yourself. you can provide an xml. and that xml can be any layout you want to provide. so I am not sure what you mean by your question

**Comment by Tinyhuge** [comment]
Thanks for your help 😀 btw, i found what i am looking for..
