### ISSUE TITLE
Custom item background support 

### ISSUE THREAD

**Issue by h6ah4i** [mikepenz/MaterialDrawer#25]
I want to set custom background drawable (e.g. StateListDrawable) to list items.  How can I achieve this?

**Comment by mikepenz** [comment]
@h6ah4i the items use the default background, just with the StateListDrawable to show the selected list item. 

There are 2 possible solutions:
1. create your own DrawerItem implementation changing the way the background is set (just look at the source of the PrimaryDrawerItem)
2. i will add another method for the drawerItem allowing you to overwrite the background

I will look at it later today. It's probably a good idea to have the method to set the background per item.

**Comment by h6ah4i** [comment]
Thanks, I've solved the issue by the first solution. 
Thank you for the great library, this library saves a lot of my time :smile:

**Comment by mikepenz** [comment]
@h6ah4i awesome :)
