### ISSUE TITLE
Crash on header click

### ISSUE THREAD

**Issue by IgorGanapolsky** [mikepenz/MaterialDrawer#250]
Every time I try to click on a header in the nav drawer, I get the following crash:
> This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.

Please advise.

**Comment by raghunandankavi2010** [comment]
@IgorGanapolsky is it with a custom header. Also does your layout have a toolbar.

**Comment by IgorGanapolsky** [comment]
This is your sample app.  When I click a Section Header, the crash occurs.

**Comment by raghunandankavi2010** [comment]
@IgorGanapolsky i was able to reproduce the same with the new sample. Will look at it

**Comment by IgorGanapolsky** [comment]
Looking at LibsActivity.class, I see that it tries to instantiate an ActionBar.  I have no idea why, since Toolbar should be the way to go...

**Comment by raghunandankavi2010** [comment]
@IgorGanapolsky  hmm. Changing the style to MaterialDrawer works. Looking at the styles

        <style name="MaterialDrawerTheme.ActionBar" parent="MaterialDrawerTheme">
        <item name="windowActionBar">true</item>
        <item name="windowNoTitle">false</item>
         </style>

And this

 http://stackoverflow.com/questions/29790070/upgraded-to-appcompat-v22-1-0-and-now-getting-illegalargumentexception-appcompa/29790071#29790071

Toolbar is the way to go...

**Comment by raghunandankavi2010** [comment]
@IgorGanapolsky Looking @ https://github.com/mikepenz/AboutLibraries The LibsActivity has a toolbar.

**Comment by IgorGanapolsky** [comment]
@raghunandankavi2010 But it also has this: `ActionBar ab = this.getSupportActionBar();`

**Comment by IgorGanapolsky** [comment]
And now I get a runtime exception!
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mikepenz.materialdrawer.app/com.mikepenz.aboutlibraries.ui.LibsActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.

**Comment by IgorGanapolsky** [comment]
I also get a slew of warnings like this:
> com.mikepenz.materialdrawer.app I/ViewUtils﹕ app:theme is now deprecated. Please move to using android:theme instead.

**Comment by mikepenz** [comment]
@IgorGanapolsky you mix up the issues :D i think this is an issue of the AboutLibraries. And the exception you get is something different. You should use a non ActionBar theme with it. Just use `MaterialDrawerTheme`. i only proivide the ActionBar themes too if some people still use them.

The warning is new. Is crated by the AppCompat activity. but not yet sure why...

**Comment by mikepenz** [comment]
@IgorGanapolsky ok i found the solution for the warning. 

for the AboutLibraries where you able to solve it?

and yes getSupportActionBar returns an ActionBar object even if you set a toolbar :P

**Comment by IgorGanapolsky** [comment]
Well I cannot solve it if I cannot even call `new Drawer()` in my application.  Kinda futile to go from there...

**Comment by mikepenz** [comment]
@IgorGanapolsky solved?
