### ISSUE TITLE
How to make the header of my drawer not scrollable?

### ISSUE THREAD

**Issue by gabriel-TheCode** [mikepenz/MaterialDrawer#2500]
I want my drawer header to be fixed (not scrollable), with drawer items that can scroll.

**Comment by mikepenz** [comment]
You can provide a sticky header: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.kt#L722

**Comment by gabriel-TheCode** [comment]
Thank you Mike,
I add the line below and it works fine !

https://github.com/mikepenz/MaterialDrawer/blob/8414fbcd880b95702e5b05a2cd3928288225bca9/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L105
