### ISSUE TITLE
Cannot update item name on profileDrawerItem

### ISSUE THREAD

**Issue by iman2420** [mikepenz/MaterialDrawer#2501]
I tried this way:

    `profileDrawerItem = new ProfileDrawerItem().withName(profileDB.getName() + " " + profileDB.getLastName())        
    .withEmail(profileDB.getEmail()).withIcon(R.drawable.ic_isaco_text).withIdentifier(MENU_PROFILE);`

And this way to update name:

    ` bannerViewPager.post(() -> {
                            if (profileDrawerItem != null)
                            drawer.updateName(MENU_PROFILE, new StringHolder(profileDrawerItem.getName() + "\n" + scoreText));
                            drawer.getAdapter().notifyAdapterDataSetChanged();
                            Tools.log_d(TAG, "updateName "+ profileDrawerItem.getName()+ "\n" + scoreText);
                        });`

But it remained unchainged

**Comment by mikepenz** [comment]
you don't need a `drawer.getAdapter().notifyAdapterDataSetChanged();`

the `updateName` will do that already for you. 

are you sure your post call is called?

**Comment by iman2420** [comment]
> you don't need a `drawer.getAdapter().notifyAdapterDataSetChanged();`
> 
> the `updateName` will do that already for you.
> 
> are you sure your post call is called?

Yes.  I logged in to make sure.

**Comment by mikepenz** [comment]
Can you somehow reproduce this in the sample app? It works perfectly for me
