### ISSUE TITLE
setSelection not working properly

### ISSUE THREAD

**Issue by marbat87** [mikepenz/MaterialDrawer#2502]
## About this issue

Hi,

Using drawer.setSelection(id) to manually select a drawer item, it is not highlighting it.
The onclick related action is correctly called, the color is set on both icon and item name, but the highlight is missing.

Regards

See image
![image](https://user-images.githubusercontent.com/8694304/64690932-e347f100-d491-11e9-86ee-48fbcaae3991.png)

## Details
- [v7.0.0-rc06 ] Used library version
- [androidx.appcompat:appcompat:1.1.0 / com.google.android.material:material:1.1.0-alpha09 ] Used support library version
- [com.android.tools.build:gradle:3.5.0 ] Used gradle build tools version
- [3.5 ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [X ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [X ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [X ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [X ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [X ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [X] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
you call it from the main thread?

**Comment by marbat87** [comment]
yes

**Comment by o-sense** [comment]
Hi,
Facing the exact same issue, the menu is not highlighted (background) but the text color became blue.
I use this because I switch to other tabs sometimes from a button or something, so I call mDrawer.setSelection(ID, false).
Any suggestions?
It was working ok before I updated the targetSDK to 28 and updated the MaterialDrawer to latest version.

**Comment by mikepenz** [comment]
Do your items use identifiers?

Is your theme set correctly?

Can you reproduce it in the sample app?

**Comment by mikepenz** [comment]
Please report back. Close for now. Reopen if still relevant
