### ISSUE TITLE
README update required

### ISSUE THREAD

**Issue by vxplore** [mikepenz/MaterialDrawer#2508]
Please update the README file. It is outdated and points to invalid URLs. And at least write some lines on how to use the drawerimageloader in android. As far as I remember last time I had used this it was working. But now neither the init method nor the AbstractDrawerImageLoader is found in android application class. Am I missing something here?

Edit:
I finally could access the init method from the manger class where I am creating the drawer. But according to the docs I should be using it in the application class, but I cannot access the init method in custom application class.

**Comment by mikepenz** [comment]
Not sure what you mean. The API for it did not change and is still the same: 

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.kt

**Comment by mikepenz** [comment]
Oh perhaps some issue in java? As everything I do is now 100% kotlin. and the Drawer v7 is kotlin first. 

v6 is the last version in java

**Comment by vxplore** [comment]
> Oh perhaps some issue in java? As everything I do is now 100% kotlin. and the Drawer v7 is kotlin first.
> 
> v6 is the last version in java

yes probably a java issue. Check the edit. Do you have any thoughts on that?

**Comment by vxplore** [comment]
Hope you could provide some documentation for android. I know it is a kotlin first library, and it is one of the best libraries, but not all of us have migrated to kotlin yet. Will be of great help thanks.
