### ISSUE TITLE
Drawer is not showing when DataBinding enabled

### ISSUE THREAD

**Issue by rddewan** [mikepenz/MaterialDrawer#2509]
## About this issue

Drawer is not showing when working with Data Binding is there any way we can use it with data binding 
## Details
- [ 7.0.0-rc07 ] Used library version
- [ ] Used support library version
- [3.5.1 ] Used gradle build tools version
- [3.5.1 ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
I don't know why it wouldn't be showing, do you have some sample code or anything?

------

As a side note. I am currently working on v8 alpha which will disable the auto inflating of the drawer, which might fix this problem too if databinding does not allow the view to be inflated programmatically

**Comment by rddewan** [comment]
how did u did a data binding without root <layout > tag ?  is it possible ?

**Comment by frozenheime** [comment]
Drawer worked. Not binding.

**Comment by mikepenz** [comment]
You might want to try this with v8. As it will no longer do auto inflation of the `DrawerLayout`

https://github.com/mikepenz/MaterialDrawer/releases/tag/v8.0.0-a01

For advanced usecases it will still be a few weeks until I was able to migrate all different samples and usecases there were in old releases

**Comment by mikepenz** [comment]
I sadly have no further information regarding this other than that the layout is dynamically added to your project. between root and your first parent. 

You might also want to just setup the `DrawerLayout` manually and add the `Drawer`'s view to the `DrawerLayout` manually (similar to how the embedded sample is done) 

Big updates and improvements will come in v8 :) 

Thanks so much
