### ISSUE TITLE
expandablelistview implemetation

### ISSUE THREAD

**Issue by arslan311** [mikepenz/MaterialDrawer#2510]
hallo i am trying to implement the expanable navigation drawer menus with header menus, and i am not aware how to do this. can you help me please or provide me the source.?

**Comment by mikepenz** [comment]
expandables are shown in the sample app :)

**Comment by arslan311** [comment]
Hi mikepenz/Materialdrawer
Thanks for your reply, please can yoi guide me how to use that app, i will
be thankful to you.

**Comment by arslan311** [comment]
I am not sure, how to use it. Can you provide the exact link of the app?.

**Comment by arslan311** [comment]
i need urgent implemetation of expandable menus in navigation drawer, if any one can provide the source or help???

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.kt#L110-L117
