### ISSUE TITLE
accessibility issue with Header

### ISSUE THREAD

**Issue by navczydev** [mikepenz/MaterialDrawer#2511]
## About this issue

- talkback behave header as a clickable item
- open the app and start using it with talkback
- header suppose not be clickable 
- how we can make it work
@mikepenz 
Thanks

## Details
- [ ] Used library version : 6.0.6
- [ ] Used tooling / Android Studio version : 3.5

**Comment by mikepenz** [comment]
@navczydev I would gladly take a PR to improve this. 

as I do not use or have talkback there is currently no real plan to change this. 

Also it would be great to do those improvements on v7

**Comment by navczydev** [comment]
thanks @mikepenz for your response will check and see if I can add something

**Comment by mikepenz** [comment]
Thank you very much

**Comment by mikepenz** [comment]
May I ask for an update on this topic? If this is still relevant I would kindly ask for your contributions. 
Will close for the time being (as this is inactive quite some time)
