### ISSUE TITLE
Search item in Material Drawer Support

### ISSUE THREAD

**Issue by bismarabia** [mikepenz/MaterialDrawer#2515]
## Is there a way to add a search bar on top of the drawer?

I think adding an option to search in the nav drawer would be better. Can we expect such thing anytime soon? You can add as part of the header or just below the header as separate view.

it can be something like this [
![image](https://user-images.githubusercontent.com/16321223/67570763-dd088e00-f73a-11e9-878e-24459c723bc9.png)
](url)

**Comment by mikepenz** [comment]
you can provide your own layout for the header. and that might contain a search bar if you need

**Comment by mikepenz** [comment]
It is nothing which is part of the material spec so I sadly won't add it

**Comment by bismarabia** [comment]
Thanks for the reply @mikepenz
Let's say I somehow managed to add searchView to the header or so, How can I get the itemAdapter and filter items accordingly?

**Comment by mikepenz** [comment]
You can get the itemAdapter of the materialDrawer and use the `filter` function. 

Or you just get the elements of the drawer, filter them and set them.

**Comment by bismarabia** [comment]
Alright, thanks for the reply, I will give it a try and let you know.
