### ISSUE TITLE
Unable to use ProfileDrawerItem without an image

### ISSUE THREAD

**Issue by TakeoffAndroid** [mikepenz/MaterialDrawer#2516]
I  have a requirement where in I have to show only name and email in ProfileDrawerItem, but currently I see this is not supported.. Any solution? Thanks!

**Comment by mikepenz** [comment]
@TakeoffAndroid what exactly is your requirement? 

You can also use the `ProfileSettingsDrawerItem` https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.kt#L64
It will be ignored in the header. 

And you can modify the first and second line shown in the header programmatically too:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.kt#L147

**Comment by TakeoffAndroid** [comment]
@TakeoffAndroid My major requirement to show name and email only in `ProfileDrawerItem`, but not image. I see that by default account header showing some random logo, and also tried to pass `null` but it was throwing `IllegalStateException`

**Comment by mikepenz** [comment]
As mentioned use a `ProfileSettingsDrawerItem` instead. it does not have a profile icon. 

and you will be able to control the content in the header manually.

**Comment by martinchirchir** [comment]
I have tried using ProfileSettingsDrawerItem but the contents do not appear, I only see the background image.
What can I be doing wrong?

**Comment by Crone163** [comment]
I did it this way
ProfileDrawerItem().apply {
                    profileImagesVisible = false
}
But spent a lot of time for it
