### ISSUE TITLE
Question about fullscreen

### ISSUE THREAD

**Issue by Kuroiteiken** [mikepenz/MaterialDrawer#2517]
Hello, i want to ask something about fullscreen. 
I've set my drawer, And  I've setted Fullscreen as true. But when i swipe to open it, it will appears on only half of the activity. I've also add ` drawer.getDrawerLayout().setFitsSystemWindows(true); ` after building, but nothing happens. On tablets, it is normal, but on phones it had to be appear fullscreen on top of activity.
` Drawer drawer = new DrawerBuilder()
.withActivity(this)
.withFullscreen(true)
.withDrawerGravity(Gravity.RIGHT)
.withSliderBackgroundColor(this.getResources().getColor(R.color.col_drawer))
.withSelectedItem(-1)
.addDrawerItems(.... ))
.build();
`

**Comment by mikepenz** [comment]
Have you had a look into the sample app? there is one fullscreen activity too. 

Regarding the behavior. I am currently working on v8 which has a general rewrite for how the `MaterialDrawer` is added inside projects. 

This will help with the drawer no longer taking over anything, or trying to be clever about the fullscreen flags / fitsSystemWindows. 

I might do a first alpha version today (not all samples work yet, but the core functionality works)

**Comment by mikepenz** [comment]
You might want to have a look at v8. For basic usecases the current state might already be interesting:
https://github.com/mikepenz/MaterialDrawer/releases/tag/v8.0.0-a01

For advanced usecases it will still be a few weeks until I was able to migrate all different samples and usecases there were in old releases

**Comment by Kuroiteiken** [comment]
I'm using 6.1.2 version with Java. I will try but i'm not hopeful.
