### ISSUE TITLE
Style problem with 2.8.1 and AppCompat lib 22.1.0 on android 4.0.3

### ISSUE THREAD

**Issue by wildfatduck** [mikepenz/MaterialDrawer#252]
If I'am using MaterialDrawerTheme.Light.DarkToolbar.ActionBar as parent style, I have problems with fonts color, if this colors was inherited from theme (they just white) and in logs a lot of messages:
"app:theme is now deprecated. Please move to using android:theme instead."

With MaterialDrawerTheme.Light as parent there is no such problems, but humburger icon is black, I need white :)

On 5.1 everything is ok.

**Comment by mikepenz** [comment]
@wildfatduck i'm not sure. i don't use app:theme in the MaterialDrawer do you have it somewhere?

**Comment by mikepenz** [comment]
@wildfatduck i think i found the issue. it's fixed in the next version

**Comment by wildfatduck** [comment]
With v2.8.2 "app:theme is now deprecated. Please move to using android:theme instead." messages are gone, but problem with fonts color is still there. I fixed this by using Base.Theme.AppCompat.Light.DarkActionBar as parent and added <item name="drawerArrowStyle">@style/MaterialDrawer.DrawerArrowStyle</item> for white color of humburger icon.

**Comment by mikepenz** [comment]
yeah this will be fixed in the next version. it will also be required to set a theme for the toolbar then

**Comment by gpulido** [comment]
Hello,
I'm having a similar problem.
I was using the following theme as my main theme on the AndroidManifest:
```xml
<style name="MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus.Background" parent="MaterialDrawerTheme.ActionBar.TranslucentStatus">
        <item name="android:windowBackground">@color/material_drawer_primary</item>
            <item name="android:textColorPrimary">@color/text_primary</item>
            <item name="android:textColor">@color/text_secondary</item>
    </style>
```
AS this is a lightTheme, my textColorPrimary is a "grey" color, however when I apply the following

```xml
style="@style/Base.TextAppearance.AppCompat.Body2"
```

to a textview, the thet is white instead of grey (the body2 uses the text_primary)
What I'm doing wrong?

Thank you!

**Comment by mikepenz** [comment]
@gpulido there will be an update with an updated theme soon. this will then require you to set the theme for the toolbar too (as advised from the android team)

**Comment by gpulido** [comment]
@mikepenz Thank you for the info. I guess that you are refering to an "material drawer" update, aren't you?
It seems also that there were a bug on the v22 that google solved on the 22.1.1

**Comment by mikepenz** [comment]
@gpulido have you details about the changelog of 22.1.1 (not 22.1.0)

**Comment by gpulido** [comment]
@mikepenz Take a look here:
https://code.google.com/p/android/issues/detail?id=169760

**Comment by gpulido** [comment]
v2.9.0 solved the issue, amazing work as always @mikepenz

**Comment by mikepenz** [comment]
@gpulido awesome ;)
