### ISSUE TITLE
Error when using Java of Typeface com.mikepenz.iconics.typeface.ITypeface.getRawTypeface() which causes app to crash

### ISSUE THREAD

**Issue by Geowan** [mikepenz/MaterialDrawer#2520]
Am using the sample as on the readme and i have added the following in my build.gradle

      implementation "com.mikepenz:materialdrawer:6.1.2"
     implementation 'com.mikepenz:actionitembadge:4.0.0' //using this for badges not on drawer
     implementation 'com.mikepenz:google-material-typeface:3.0.1.4.original-kotlin@aar'
     implementation 'com.mikepenz:fontawesome-typeface:5.9.0.0-kotlin@aar'

And now my navigation drawer

      public  void setUpDrawer(final Activity activity, Toolbar toolbar) {
        new DrawerBuilder().withActivity(activity).build();
        AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(activity)
                .withHeaderBackground(R.drawable.bsplogo)
                .addProfiles(
                        new ProfileDrawerItem().withName("Mike Penz").withEmail("mikepenz@gmail.com")
                )
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                        return false;
                    }
                })
                .build();
         Drawer result = new DrawerBuilder()
                .withAccountHeader(headerResult)
                .withActivity(activity)
                .withToolbar(toolbar)
                .addDrawerItems(
                        new PrimaryDrawerItem().withIdentifier(1).withName("Dashboard")
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        // do something with the clicked item :D

                        return false;
                    }
                })
                .addStickyDrawerItems(
                        new SecondaryDrawerItem().withName("Logout").withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                            @Override
                            public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                                tryLogout(activity);
                                return true;
                            }
                        })
                )
                .build();
    }
    
BUt am still getting the error java.lang.AbstractMethodError: abstract method "android.graphics.Typeface com.mikepenz.iconics.typeface.ITypeface.getRawTypeface()" despite adding the google material typeface. 
In my android project am using java not kotlin. What is wrong?

**Comment by mikepenz** [comment]
Hey @Geowan so you seem to mix up `Android-Iconics` fonts for v4 with Android-Iconics v3. 

All font addons ending on `-kotlin` are only compatible with `Android-Iconics` `v4` releases.

If I am not mistaken. v6.1.2 of the MaterialDrawer still uses `Iconcis` v3.x

**Comment by Geowan** [comment]
Thanks mike, Kindly clarify on whats the gradle dependency for the Iconcis v3.x since on the  iconics repository i can only see the gradle dependecy with -kotlin as per [Android-Iconics](https://github.com/mikepenz/Android-Iconics)

Kindly clarify on whether Java users (without kotlin) can use the material drawe version 7 as from the readme part it indicates

           Kotlin | v7.0.0-rc08
           Java && AndroidX | v6.1.2
           Java && AppCompat | v6.0.9

Which i asssumed that the Java users can only use version 6.1.2

**Comment by mikepenz** [comment]
#### Android-Iconics v3.x
https://github.com/mikepenz/Android-Iconics/tree/v3.2.5
You can see the icon addons at that tag in its README :) 

 #### Java
So v7.x is mainly targeted at Kotlin users, and might work for Java users but its API will not be as nice. 
V6.1.2 of the MaterialDrawer uses v3.x of the Iconics: https://github.com/mikepenz/MaterialDrawer/blob/v6.1.2/library/build.gradle#L46 (v4 of Iconics is also mainly for Kotlin users) 
You can find the documentation for the older releases at the tagged states of the corresponding repos :)

**Comment by Geowan** [comment]
Thanks, to make this work i also had to downgrade the Itembadge from 4.00 to 3.3.2 with 

          implementation 'com.mikepenz:actionitembadge:3.3.2'
