### ISSUE TITLE
ERROR: Failed to resolve: com.mikepenz:materialdrawer-nav:6.1.2

### ISSUE THREAD

**Issue by kareemzok** [mikepenz/MaterialDrawer#2522]
Hello,

When I added the libraries to the Gradle file I got the following error :

"ERROR: Failed to resolve: com.mikepenz:materialdrawer-nav:6.1.2"

Any advice, please?

**Comment by mikepenz** [comment]
This extension did not exist for v6.1.2 


You can always look at the state of the library at a specific tag using that tag: https://github.com/mikepenz/MaterialDrawer/tree/v6.1.2

**Comment by kareemzok** [comment]
Oh so we shouldn't add it because it exists in the main readme file.

Thanks for your help i will try without adding it

**Comment by mikepenz** [comment]
You should always refer to the README at the state of the release you are gonna use :) 

v7 is the current active release. the only reason why it is in RC is because it requires the material components v1.1.0-beta01

v7 will go into a final release as soon as the MDC are v1.1.0-rc01

**Comment by kareemzok** [comment]
All works now thanks but I have a questions 

What is the difference between PrimaryDrawerItem and SecondaryDrawerItem, when should we use each

**Comment by mikepenz** [comment]
well in general you are fine with Primary items. if you have something less important you can use secondary items. which are slightly smaller
