### ISSUE TITLE
windowTranslucentStatus 

### ISSUE THREAD

**Issue by timtsj** [mikepenz/MaterialDrawer#2524]
Hi, i want Translucent Status, like this:
![Uploading 1573118401.png…](https://i.ibb.co/hVrxYcQ/Screenshot-1573118401.png)

but if i use MaterialDrawer, its not work:
![Uploading Screenshot_1573118459.png…](https://i.ibb.co/jVGHVyY/Screenshot-1573118459.png)

I try .withTranslucentStatusBar(false) but it effected only for drawer, not all my layout, so i wrapp my layout with FrameLayout and set it like withRootView for drawer, it not help.
How i can fix it?

**Comment by mikepenz** [comment]
Have you had a look into the sample app? the drawer draws beneath / behind the statusBar. 


Also v8 will completely change the way the drawer is setup to better work with various scenarios. 
You can already have a sneak peak at v8 here: https://github.com/mikepenz/MaterialDrawer/releases/tag/v8.0.0-a01

**Comment by timtsj** [comment]
```Have you had a look into the sample app? the drawer draws beneath / behind the statusBar.```
Yup, i see i can do drawer behind status bar, but i cant do all my layout behind status bar if i use MaterialDrawer, i writed about it in my first message.

```Also v8 will completely change the way the drawer is setup to better work with various scenarios. You can already have a sneak peak at v8 here: https://github.com/mikepenz/MaterialDrawer/releases/tag/v8.0.0-a01```

Currently i use com.mikepenz:materialdrawer:6.0.9@aar

**Comment by mikepenz** [comment]
I believe the only way to get control of the area behind the statusbar would be to not contorl the insets from the DrawerLayout. you will have to try around playing with the flags. different possibility would be if you look into the fullscreen example activity as this one draws behind to. 

that being said. v8 will change this by a huge factor and simplify it. 

You can have a sneak peak at it already. 

as of v6.0.9 an alternative approach is that you look into the embedded drawer example. it basically showcases how you us this lib only as a `view` container. e.g. you setup the DrawerLayout manually let it be standard way. and then add the `Drawer` as the lisder view manually

**Comment by mikepenz** [comment]
Btw. I remembered one example which might be exactly what you want. 

The CollapsingToolbarActivity which also draws behinid the statusbar
