### ISSUE TITLE
Drawer causes layout to goes up

### ISSUE THREAD

**Issue by Kuroiteiken** [mikepenz/MaterialDrawer#2526]
## About this issue

Hello, I'm using 6.1.2 version with AndroidX. We are coding in Java. 
We are writing a project. I've added gradle files and wrote a GenerateDrawer method for creating DrawerMenu at BaseActivity which extends AppCompatActivity then I'm extending this BaseActivity at Other activities. 
Our layout action bar and hamburger menu is different than others. I cannot find any similiar examples like ours. We added an toolbar layout which uses Constraint layout and couple of buttons, then at Right, there is Hamburger Menu button. And using these buttons for different purposes. At our content layouts, we are using this with Include. At our BaseActivity,  we are calling drawerResult.openDrawer for opening drawer. 
So, here is the problem. 
When opening drawer menu, all layouts include my content and drawer, goes up and there is a bar like thing stays below even if i close my drawer. 
Also, our superiors are requested our drawer menu's should be full screen instead of partial. I'm adding couple of screenshots. Even if i'm using tablet instead of phone, when we tried at phones we cannot use it fullscreen.

Btw, i think you will said for `.withTranslucentStatusBar(false)`. But when i add that, it will still goes up and there is still white bar below, also our logo which top of buttons, are going below status bar. It looks like adding minus margin and causing layout to move couple pixels up.

Screenshots
[Layout](https://ibb.co/FqXWN8z)
[Drawer Opens](https://ibb.co/W6wfr6N)
[Drawer Closes](https://ibb.co/vcY3xY8)

`
        drawer = new DrawerBuilder()
        .withActivity(this) 
        .withDrawerGravity(Gravity.RIGHT)
        .withSliderBackgroundColor(this.getResources().getColor(R.color.hamburger_menu_backcolor))
        .withSelectedItem(-1).addDrawerItems(drawer1, drawer2, drawer3).withOnDrawerItemClickListener((view, position, drawerItem) -> { }).build();
        if (Build.VERSION.SDK_INT >= 19) {
            drawer.getDrawerLayout().setFitsSystemWindows(false);
        }
`

`            case R.id.imgMenu:
                if (drawer != null)
                    drawer.openDrawer();
                else {
                    generateDrawerMenu();
                    drawer.openDrawer();
                }
                break;
`

## Details
- [ ] Used library version 6.1.2
- [ ] Used support library version AndroidX
- [ ] Used gradle build tools version 3.5.2
- [ ] Used tooling / Android Studio version 3.5.2

## Checklist

- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x]  Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
based on the screenshots I can not make a real conclusion 

Have a look at the sample app which showcases all sorts of usecases. 
also ensure you use a proper theme. and ensure that the layout hirarchy is done accordingly

**Comment by Kuroiteiken** [comment]
After drawer is open, it goes below status bar and my layout goes up at size of status bar. I've tried to set "withDisplayBelowStatusBar(true)" but it still cause samething.

**Comment by mikepenz** [comment]
This problem will be handled with the release of v8 as it will give back all control for such behavior back into the developers hands, and remove all responsibility for it from the lib itself. 

Please keep an eye on v8 and it's future development. 

(first alpha releases are available)

Other than that my best suggestion is to really look into the various provided showcases in the sample app. as it already offers quite a lot of flexibility. 

In the worst case you will have to use the drawer similar like showcased in the `EmbeddedActivity`. Whereas you will handle the `DrawerLayout` on your own, add it to your layout. and simple then add the contents of the slider to it (e.g. use the view of the drawer and add it as child, which gives you full control over all the UI)
