### ISSUE TITLE
Change PrimaryItem Icon tint

### ISSUE THREAD

**Issue by Kashish-Sharma** [mikepenz/MaterialDrawer#2528]
## About this issue

Is there any method to change the PrimaryItem IconTint when `withEnabled(false)`, same as the item name's color changes when disabled or enabled.

## Details
- [7.0.0-rc08 ] Used library version

Thanks

**Comment by mikepenz** [comment]
@Kashish-Sharma you can create your own custom drawer item and implement the icon tint as a `ColorStateList` 



v8 (which has some big changes) will change the colors to a `ColorStateList` already. But right now I would not handle the enabled state as well: https://github.com/mikepenz/MaterialDrawer/blob/feature/v8/library/src/main/java/com/mikepenz/materialdrawer/util/Utils.kt#L19-L46

**Comment by mikepenz** [comment]
but the disabled state will be covered. 

So please stay tuned for v8. 

Until then you might consider creating your own custom drawer item. you can find this be done in the sample or FAQ section

**Comment by Kashish-Sharma** [comment]
Is there any way to set `backgroundColor` of a single `PrimaryDrawerItem` in `v8` ?
