### ISSUE TITLE
Is it possible to disable the touch events propagating to content below when swiping from the left to open the drawer?

### ISSUE THREAD

**Issue by svenoaks** [mikepenz/MaterialDrawer#2529]
## About this issue

- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Please refer to the documentation of the `DrawerLayout` this is nothing what the `MaterialDrawer` would provide. As far as I know though you will have to probably implement your custom `DrawerLayout` handling touch events manually

Thanks.

https://developer.android.com/reference/android/support/v4/widget/DrawerLayout
