### ISSUE TITLE
Cannot resolve symbol Drawer

### ISSUE THREAD

**Issue by IgorGanapolsky** [mikepenz/MaterialDrawer#253]
I get the compilation error when trying to create `new Drawer()`in my AppCompatActivity.

**Comment by mikepenz** [comment]
@IgorGanapolsky library in your build.gradle?

**Comment by IgorGanapolsky** [comment]
@mikepenz `    compile('com.mikepenz.aboutlibraries:library:4.6.5@aar') {
        transitive = true
    }`

**Comment by mikepenz** [comment]
@IgorGanapolsky and you were able to sync the build.gradle without issues?

**Comment by IgorGanapolsky** [comment]
yep

**Comment by mikepenz** [comment]
@IgorGanapolsky hmmm not really sure why you have this issue. should be a configuration problem, noone else reported this issue

**Comment by easycheese** [comment]
@IgorGanapolsky Why are you not using:

compile('com.mikepenz.materialdrawer:library:2.8.2@aar') {
    transitive = true
}

**Comment by mikepenz** [comment]
@IgorGanapolsky oh sorry. i found the issue :D you have the gradle dependency for the AboutLibraries library but not for the MaterialDrawer :D

**Comment by IgorGanapolsky** [comment]
Do I need both dependencies, or just MaterialDrawer?

**Comment by IgorGanapolsky** [comment]
@easycheese Because the README page says to use:
`compile('com.mikepenz.materialdrawer:library:2.8.2@aar') {
    transitive = true
}`

What happened there??

**Comment by mikepenz** [comment]
@IgorGanapolsky depends. if you just want to use the MaterialDrawer you just need this one. if you also want the AboutLibraries library you need the second. not sure what's confusing here?
