### ISSUE TITLE
Show the selected item without opening the Minidrawer completely

### ISSUE THREAD

**Issue by taksumaki** [mikepenz/MaterialDrawer#2530]
I want to see what menu item I have selected without opening the menu completely. I am using Minidrawer but with the menu not fully open it only shows me the icons, however, not what item I have selected.

Any way to see what menu item I have selected without opening the full menu?

**Comment by mikepenz** [comment]
@taksumaki look at the sample app. the selected element should be highlighted (with the highlighted color)

**Comment by taksumaki** [comment]
It would be great that not only the icon will change color, but also a circle of the accent color will appear next to the icon.

**Comment by mikepenz** [comment]
This is a custom usecase. for this you will have to implement a custom `DrawerItem`

This is discussed for example here: https://github.com/mikepenz/MaterialDrawer/issues/2114

**Comment by mikepenz** [comment]
If you have further questions please let me know
