### ISSUE TITLE
No virtual method withIdDistributor(Lcom/mikepenz/fastadapter/IIdDistributor;)Lcom/mikepenz/fastadapter/adapters/ModelAdapter; in class Lcom/mikepenz/fastadapter/adapters/ItemAdapter; or its super classes (declaration of 'com.mikepenz.fastadapter.adapters.ItemAdapter'

### ISSUE THREAD

**Issue by akhandafm17** [mikepenz/MaterialDrawer#2532]
Hi I have the following error

No virtual method withIdDistributor(Lcom/mikepenz/fastadapter/IIdDistributor;)Lcom/mikepenz/fastadapter/adapters/ModelAdapter; in class Lcom/mikepenz/fastadapter/adapters/ItemAdapter; or its super classes (declaration of 'com.mikepenz.fastadapter.adapters.ItemAdapter'

and I don't know why, as described in documentation using Java and AndroidX i have used
implementation "com.mikepenz:materialdrawer:6.1.2" and all the other requirements.

Stack trace is the following
` java.lang.NoSuchMethodError: No virtual method withIdDistributor(Lcom/mikepenz/fastadapter/IIdDistributor;)Lcom/mikepenz/fastadapter/adapters/ModelAdapter; in class Lcom/mikepenz/fastadapter/adapters/ItemAdapter; or its super classes (declaration of 'com.mikepenz.fastadapter.adapters.ItemAdapter' appears in /data/app/akhandaf.com.shabab.halalfoodscanner-N2DaSLR08G6XiB_L4CiySQ==/base.apk!classes3.dex)
        at com.mikepenz.materialdrawer.DrawerBuilder.<init>(DrawerBuilder.java:875)
        at akhandaf.com.shabab.halalfoodscanner.views.MainActivity.onCreate(MainActivity.java:253)`

I'm not able to identify the problem, the code seems to be correct
`result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withHasStableIds(true)
                .withAccountHeader(headerResult) 
                .withOnDrawerListener(new Drawer.OnDrawerListener() {
                    @Override
                    public void onDrawerOpened(View drawerView) {
                        Utils.hideKeyboard(MainActivity.this);
                    }`

              
this are the dependency i use 

`implementation("com.mikepenz:materialdrawer:$rootProject.materialDrawer") {
        transitive = true
    }
 implementation 'com.mikepenz:fastadapter-extensions-expandable:4.1.1'`

    //UI Component : Adapters

    //DO NOT UPDATE : RecyclerViewCacheUtil removed, needs rework

    implementation "com.mikepenz:fastadapter-commons:$rootProject.fastAdapterCommons"
    implementation "com.squareup.retrofit2:converter-scalars:$rootProject.converterScalars"

    //UI Component : Fab
    implementation "com.github.clans:fab:$rootProject.fabVersion"
    implementation "androidx.work:work-runtime:$rootProject.workRuntime"
    //UI Component : Font Icons
    implementation "com.mikepenz:iconics-core:$rootProject.fontIconCoreVersion"
    implementation "com.mikepenz:google-material-typeface:$rootProject.googleMaterialFontVersion"
    implementation "com.mikepenz:material-design-iconic-typeface:$rootProject.materialFontVersion"
    implementation "com.mikepenz:fontawesome-typeface:$rootProject.awesomeFontVersion"
   `
materialDrawer = '6.1.2'
fastAdapterCommons = '3.3.1@aar'
fontIconCoreVersion = '3.0.0@aar'
    googleMaterialFontVersion = '3.0.1.2.original@aar'
    materialFontVersion = '2.2.0.4@aar'
    awesomeFontVersion = '4.7.0.2@aar'

**Comment by mikepenz** [comment]
You can not mix up fastAdapter v3.3.1 with v4.1.1 

Please stay with 1 version. In this case with v3.3.x due to the usage of the MaterialDrawer v6.1.2
