### ISSUE TITLE
Undesirable item collapsing / inability to keep items expanded

### ISSUE THREAD

**Issue by NoHarmDan** [mikepenz/MaterialDrawer#2533]
After reading through several issues, I still fail to understand how collapsing/expanding and the ExpandableExtension work. I was forced to update an ancient app to the newest appcompat version of MaterialDrawer (6.0.9 from 5.5) due to Google's API 28 requirements and inherent compatibility issues.

The menu in the app has several primary items that each have several sub items. The required (and previously working) behavior is that all items are expanded by default and stay so unless the user manually collapses them. Regardless of any changes to them. They do undergo changes regularly: the label, the badge and the icon can all change. The badge changes very often to reflect to state of the item, where it's very undesirable for the item to suddenly become invisible because its parent collapses.

Now you suggest calling the `notifyAdapterSubItemsChanged(int globalPosition)`, which isn't available anymore, as it now also requires the number of previous sub items - not a problem really I guess. Problem is, I fail to understand when exactly I should call this, because so far it has only thrown a `ConcurrentModificationException` with a useless stacktrace.

To clarify what I'm trying to do in the case of say updating the icon:
- Something is rendered into a `Drawable` and `item.withIcon(drawable)` is called on the respective` SecondaryDrawerItem`. Previously what I would do next was to call `drawer.updateItem(item)`, which still works, but it might be (not 100% positive this is the cause) collapsing **ALL** the expandable items in the menu.

And the badge:
- `updateBadge(identifier, badge)` is called and again, **ALL** expandable items are collapsed.

Pretty much the same goes for the title, but that changes rarely. In none of the cases any of the `notifySomethingChanged` methods have ever been explicitly called (I presume the `updateBadge` or `updateItem` methods do call that somewhere deep inside) and everything worked perfectly until the update.

I'm not really sure updating the sub items is the reason why all collapsible items (including those whose items are never updated) seem to be collapsed every time the menu is opened, regardless of the state they were left in, but it appears to be the most probable cause. Meanwhile calling `drawer.getExpandableExtension().expand()` seems to either rarely work, or be immediately cancelled out by something triggering the collapse. And the most curious part is, the `ExpandableExtension.collapse()` method does not get called, yet the items become magically collapsed.

**Comment by mikepenz** [comment]
@NoHarmDan are you by any chance able to showcase this with the sample app / do the relevant modifications in the sample app to showcase this?

**Comment by mikepenz** [comment]
One specific detail about how expandables / subItems are implemented in the `MaterialDrawer` (via the `FastAdapter`) is that the functionality itself is provided as an extension. 

The base adapters all function the same. with the basic principle of displaying a list of elements. 
Whereas the `FastAdapter` brings the abstraction for you not to actually being required to write an adapter, but you can solely define items which specify on how an element is visualized. 

Expandables based on the idea are nothing more than sub items which are added to the list at the position where they belong to. (moving down the other top level elements in their actual position) 
Adding nesting will then further adjust the positions and move "down" other elements 

This whole functionality is bundled into the `expandable` extension provided to the `FastAdapter`. 

The specific method you are searching `notifyAdapterSubItemsChanged` is now part of the extension: https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.kt#L253 ( as the core fastAdapter does not longer understand expandables per se) 


I wonder though about the collapsing part. there is a situation in the code whereas all elements are collapsed when the list is changed. to ensure we are not ending up in  a corrupt state. e.g. the adapter would display wrong elements. (as sub items are basically "virtual" elements inside the list at the expanded state)

**Comment by NoHarmDan** [comment]
While trying to be as specific about my problem as I could, I forgot to mention something that's probably important: I'm not aware of using a `FastAdapter`, at least not explicitly. Honestly I haven't even heard of it until I started looking the issues up. The app just imports the `MaterialDrawer` library and that's it. Does `MaterialDrawer` require and automatically include `FastAdapter` or does it work in a different way, without it, unless specified?

I know where to find `notifyAdapterSubItemsChanged`, I don't know how to use it properly. I don't understand if I should or shouldn't call `drawer.updateItem(item)` or `updateBadge(identifier, badge)` when calling `notifyAdapterSubItemsChanged`, or in which order to call the methods and what other things to look out for in order to achieve the desired behavior without a `ConcurrentModificationException` popping up.

And yeah, I'm not sure what really triggers the collapsing. Is there something I should check that might be a malpractice causing it? Or is there a reliable way of making the items somehow default to expanded state?

**Comment by NoHarmDan** [comment]
> @NoHarmDan are you by any chance able to showcase this with the sample app / do the relevant modifications in the sample app to showcase this?

I'll see what I can do.

**Comment by NoHarmDan** [comment]
Well, given the fact that nobody's gonna pay for it and my time is limited, I have had to resort to the cheapest option. I have worked around the issue by implementing a `SparseArray` that holds the desired expanded states (capture through a `Drawer.OnDrawerItemClickListener` on each expandable item) and uses those to expand items each time the drawer is opened. It ain't pretty, but it works.

In other words, I won't be providing an example to showcase the issue. I'm sorry if I have wasted your time, although I believe that there is an actual issue that can be resolved - possibly in the documentation or examples not being clear enough or not covering this, rather than an error in `MaterialDrawer`.

**Comment by mikepenz** [comment]
@NoHarmDan no you did not waste my time. 

If there is an actual problem or if there are good ideas and suggestions on how we can improve (adjust) the API to make it actually more easy to use, update documentation to resolve questions around this topic, or similar... Then I highly appreciate any issue opened. 

The goal of this library is to offer developers a good (extensible) solution beside Googles `NavigationView` to implement the proper drawer functionality in their applications. 



Based on what it sounds like you are doing now, seems like you do something similar like the internals do with the saveInstanceState to store and apply the previous configuration again.

**Comment by mikepenz** [comment]
I believe we may be able to close this one for inactivity, and as it is no longer relevant. 

Also in further consideration, this is more an topic for the `FastAdapter` library as all expandable related functionality in the `MaterialDrawer` depends solely on the `FastAdapter`s API and behavior.
