### ISSUE TITLE
Status bar color is set below the toolbar when placing the drawer under the toolbar

### ISSUE THREAD

**Issue by PembaTamang** [mikepenz/MaterialDrawer#2539]
I just downloaded the zip and ran the sample app.
Then I followed your [post](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_show_drawer_under_toolbar.md)
the result is that the status bar color is set underneath the toolbar
![Screenshot_1576920776](https://user-images.githubusercontent.com/32651212/71306157-fe1bf100-2402-11ea-9675-939d3330e5a8.png)

**Comment by mikepenz** [comment]
@PembaTamang Seems you do something wrong with the `fitsSystemWindows` flags. 

Please look at the sample app it shall have samples for most usecases. 
Also it seems you are trying to do a non anticipated pattern (the material design guidelines are very specific, and you should be full height)

**Comment by PembaTamang** [comment]
I don't follow. I just ran the sample app and copy pasted code from your post. I added nothing. Try to do the same maybe you'll see it too

**Comment by mikepenz** [comment]
I do not see this behavior in the sample app. 

Ensure the proper theme is used. 

With a proper setup and `Toolbar` it should look like: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/DEV/github/screenshots1.png

**Comment by mikepenz** [comment]
Please report back. Close due to inactivity for now
