### ISSUE TITLE
Misc Kotlin Comments

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/MaterialDrawer#2540]
Happy holidays :)

For v7.0.x:

---

https://github.com/mikepenz/MaterialDrawer/blob/96bf8efacf9a748d9883eb976a147cc61b3b1339/library/src/main/java/com/mikepenz/materialdrawer/Drawer.kt#L68-L74

For stuff like this, isn't the return value always nonnull? In that case, consider using lazy (unsynchronized if it's UI only)

---

https://github.com/mikepenz/MaterialDrawer/blob/96bf8efacf9a748d9883eb976a147cc61b3b1339/library/src/main/java/com/mikepenz/materialdrawer/holder/BadgeStyle.kt#L28-L32

Typically, kotlin doesn't really use builder styles, since users can already use builder like syntax using extension functions.

For this specific case, you have:

```kt
var gradientDrawable = R.drawable.material_drawer_badge
var badgeBackground: Drawable? = null

fun withGradientDrawable(@DrawableRes gradientDrawable: Int): BadgeStyle {
    this.gradientDrawable = gradientDrawable
    this.badgeBackground = null
    return this
}
```

Firstly, all values are public, so users can set `gradientDrawable` and `badgeBackground` themselves while bypassing your `with`* functions (and the associated logic). The alternative could be to have something like 

```kt
private var _gradientDrawable = R.drawable.material_drawer_badge
private var _badgeBackground: Drawable? = null

var gradientDrawable: Int
    get() = _gradientDrawable
    set(value) {
        _gradientDrawable = value
       _badgeBackground = null
   }

// Similar for other field
```

which ensures that your logic will always be used. 

The other functional approach would be to only have one field, and use something like sealed classes + instance matching to decide the format. Stuff like that ensures that impossible states remain impossible. It would be a very similar pattern to how you are storing color and dimen values in the other fields.

---

https://github.com/mikepenz/MaterialDrawer/blob/96bf8efacf9a748d9883eb976a147cc61b3b1339/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.kt#L724-L728

Kotlin if else and when return values, so instead of this,  you can do:

```kt
this.accountHeaderContainer = it.layoutInflater.inflate(if (compactStyle) R.layout.material_drawer_compact_header else R.layout.material_drawer_header, null, false)
```

---

For the same class, I'm not sure if Builder is retained, but if you have a nullable list, it may be more readable to just instantiate it to a mutable list at the start, and to keep it nonnull.

Null checks like the first part of `mProfiles == null || mProfiles?.size == 1` are also redundant, but is not seen as redundant by the compiler given that `mProfiles` is mutable.

Stuff like: 

https://github.com/mikepenz/MaterialDrawer/blob/96bf8efacf9a748d9883eb976a147cc61b3b1339/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.kt#L1309-L1311

may be in preparation for more content, but it can currently be reduced with just null propagation without let.

Stuff like:

https://github.com/mikepenz/MaterialDrawer/blob/96bf8efacf9a748d9883eb976a147cc61b3b1339/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.kt#L1332-L1349

Can use return functions (`val mDrawer = drawer ?: return`) to avoid large numbers of nested braces

**Comment by mikepenz** [comment]
Happy Holidays to you too ☺️.

Thank you so much. I'll have a look.
I see some things I'd not do like the anymore either 😂. It's interesting how the way we write kotlin code changes over time

**Comment by mikepenz** [comment]
Regarding the comments for the builder style. This was mainly to maintain backwards compatibility with the old API. it will be fully removed with v8. 

Using lazy for the non null fields is absolutely something we should refactor for v8. also mainly just legacy :/

The null check and return instead of the let, I'll make sure to catch them all with v8 :) Should have done a refactor of these more recently too :D 

Hopefully I'll not overlook any of the improvements for v8 :) but I will try to have a more in depth refactor this time around to clean up as far as possible :)

**Comment by mikepenz** [comment]
Thanks again for the comments. I think a big amount already got covered (in current v8 commits, and more to be covered soon. 

v7 I currently not have big plans to follow up with such a refactor. as I believe the future lays in v8 :)
