### ISSUE TITLE
Misc Lint

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/MaterialDrawer#2543]
v7.0.x

---

https://github.com/mikepenz/MaterialDrawer/blob/e3273e9651efebb96e0c8342f71b17c97070312c/library/src/main/res/layout/material_drawer_item_expandable.xml#L66-L69

Use of both `start` and `left` (and `end` and `right`) is redundant

**Comment by mikepenz** [comment]
there was a particular issue which I faced without doing this on some API 16, 17, ...(?) phones. Not sure if these problems got fixed with newer build tools, but back in the days things really broke in a bad way :D

**Comment by AllanWang** [comment]
Ah that's true. Up to you whether or not you want to keep the current set up (which is correct), or bump your min sdk. From the [distribution dashboard](https://developer.android.com/about/dashboards), fewer than 2% of devices are under SDK 17

**Comment by mikepenz** [comment]
Yeah for private apps I always go to 21+ already. but for a library which does not necessarily require newer APIs I'd still try to offer support for as many people as possible :)
