### ISSUE TITLE
Android X update

### ISSUE THREAD

**Issue by 2assas** [mikepenz/MaterialDrawer#2547]
All library imports are became not exist after the android X

import com.mikepenz.materialdrawer.AccountHeader;
import com.mikepenz.materialdrawer.util.DrawerUIUtils;
import com.mikepenz.materialdrawer.AccountHeaderBuilder;
import com.mikepenz.materialdrawer.Drawer;
import com.mikepenz.materialdrawer.DrawerBuilder;
import com.mikepenz.materialdrawer.MiniDrawer;

all unrecognized, i use java code, and have add all dependencies on gradle as well.

**Comment by mikepenz** [comment]
Which version did you use?

**Comment by 2assas** [comment]
i use android 10 API 29 
and these is the dependencies version

    implementation('com.mikepenz:aboutlibraries:8.0.0-a05') {
        transitive = true
    }
    implementation("com.mikepenz:materialdrawer:8.0.0-a05") {
        transitive = true
    }
    implementation 'com.mikepenz:aboutlibraries:7.1.0'
    implementation 'com.mikepenz:google-material-typeface:3.0.1.1.original@aar'
    implementation 'com.mikepenz:fontawesome-typeface:5.0.6.0@aar'
    implementation 'com.mikepenz:octicons-typeface:3.0.0.1@aar'
    implementation 'com.mikepenz:crossfader:1.6.0'
    implementation 'com.mikepenz:itemanimators:1.1.0'

**Comment by mikepenz** [comment]
Please see in the readme about the current releases v7 is the last stable release which still uses the old API. 
And it is also the kotlin rewrite. 

If you are in Java there's also a v6 update with Android x.

v8 will feature a completely new API and is a ground up refractor. If you want to use it please see the v8 branch and it's sample and readme for v8

**Comment by 2assas** [comment]
okey Thanks, that's works.
