### ISSUE TITLE
Methods cannot be resolved

### ISSUE THREAD

**Issue by 2assas** [mikepenz/MaterialDrawer#2548]
Hello Mike,

here is face some problems, with these methods on the new update android 10, api 29.

isDrawerOpen()
closeDrawer()
getDrawerLayout()
getMiniDrawer()

i dont know that what dependencies to add, i added most of it ? i cant solve it :(

**Comment by mikepenz** [comment]
Can you please complete the issue template and provide app the required details?

Which dependency do you include now?
Which version do you use?
Which code do you have?

Also did you have a look at the sample application for the version you use?

**Comment by 2assas** [comment]
okey this is my dependencies 

    implementation "com.mikepenz:materialdrawer:6.1.2"
    implementation 'com.mikepenz:aboutlibraries:7.1.0'
//required support lib modules
    implementation "androidx.appcompat:appcompat:1.1.0"
    implementation "androidx.recyclerview:recyclerview:1.1.0"
    implementation "androidx.annotation:annotation:1.1.0"
    implementation "com.google.android.material:material:1.0.0"
    implementation "androidx.constraintlayout:constraintlayout:1.1.3"
    implementation 'com.mikepenz:crossfadedrawerlayout:1.1.0'

    implementation 'com.mikepenz:itemanimators:1.1.0'
    implementation 'com.mikepenz:crossfader:1.6.0'


and this is the part of code that contain isDrawerOpen() and closeDrawer() problems..


  result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withHasStableIds(true)
                .withDrawerLayout(R.layout.crossfade_drawer)
                .withAccountHeader(headerResult)
                .withDrawerWidthDp(72)
                .withGenerateMiniDrawer(true)
                .withTranslucentStatusBar(true)
                .withActionBarDrawerToggleAnimated(true)
                .addDrawerItems(
                        item1, item2, item3, item4, item5, new DividerDrawerItem(), item7, item8, item9, item10,new DividerDrawerItem(),item12,item13
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {

                        switch (position) {

                            case 1:
                                if (result != null && result.isDrawerOpen()) {
                                    result.closeDrawer();

                                }


--------------------------------------------------------------------------------------------
and this the other part that contain getDrawerLayout() and getMiniDrawer() problems..

  crossfadeDrawerLayout = (CrossfadeDrawerLayout) result.getDrawerLayout();

        //define maxDrawerWidth
        crossfadeDrawerLayout.setMaxWidthPx(DrawerUIUtils.getOptimalDrawerWidth(this));

        //add second view (which is the miniDrawer)
        final MiniDrawer miniResult = result.getMiniDrawer();


Thank you for helping me :)

**Comment by mikepenz** [comment]
You can see the `CrossfadeDrawerLayout` sample here: 

https://github.com/mikepenz/MaterialDrawer/blob/v6.1.2/app/src/main/java/com/mikepenz/materialdrawer/app/CrossfadeDrawerLayoutActvitiy.java

**Comment by 2assas** [comment]
well, it was really stupid error but i solved it now, Thanks !
