### ISSUE TITLE
Larger Size of Library. It has iconics and fastadapter inside.

### ISSUE THREAD

**Issue by anjalsaneen** [mikepenz/MaterialDrawer#2549]
<img width="1272" alt="Screenshot 2020-01-19 at 12 32 45 PM" src="https://user-images.githubusercontent.com/43947967/72676529-2a856480-3ab8-11ea-82de-34bbdad86833.png">

**Comment by mikepenz** [comment]
@anjalsaneen this is no longer the case with v8

**Comment by mikepenz** [comment]
`FastAdapter` will still be needed though as it is used to fill in the list. 

Iconics and Materialize will be removed though.
