### ISSUE TITLE
add custom view in Menu

### ISSUE THREAD

**Issue by artemkutukov** [mikepenz/MaterialDrawer#255]
How to add my layout in Menu(Drawer) ?

**Comment by mikepenz** [comment]
@artemkutukov more details please? what do you want/need?

**Comment by artemkutukov** [comment]
Mike, i need create Drawer Menu with my layout. It's possible ?

**Comment by mikepenz** [comment]
DrawerItem with custom layout?

the whole drawer with custom layout? it's possible but why using this lib then?

**Comment by artemkutukov** [comment]
I need full custom Left Menu. Im use your lib becouse menu to run into the color status bar in 4.4 and 5.0+

**Comment by mikepenz** [comment]
@artemkutukov this feature is not possible. You can only attach a 100% custom layout if you append a drawer to another drawer. but yeah i can add this for a future version

**Comment by artemkutukov** [comment]
It's super, man ! how soon will it happen?

**Comment by mikepenz** [comment]
never ask for a release date. i assume within 5 days :P

**Comment by artemkutukov** [comment]
I have 1 more questions) whether support for tablets in a horizontal position

**Comment by mikepenz** [comment]
this can't be handled by the drawer. you have to handle it on your own. but the api should be flexible enough

**Comment by artemkutukov** [comment]
I meant that the menu was opened and closed. and the content was right.

**Comment by artemkutukov** [comment]
Not closed *

**Comment by mikepenz** [comment]
what?

**Comment by artemkutukov** [comment]
Sorry for my English ( Is it possible to open the menu in the horizontal position on the tablet. and content to the right of the Open menu?

**Comment by mikepenz** [comment]
should be somehow possible. the MaterialDrawer is a normal DrawerLayout so everything should be possible as with a normal DrawerLayout

**Comment by artemkutukov** [comment]
Here is an example
https://lh3.ggpht.com/cqpev8bYpgky7iURg7ThRtwAwh1CNEKOjINNy3MS-MYbRf8UHD38WlomoU53ScqtbnEn=h900

**Comment by artemkutukov** [comment]
it would be cool if the library standard would support this

**Comment by mikepenz** [comment]
@artemkutukov if it'S possible with a DrawerLayout it's also possible here. haven't had the need for this yet

**Comment by artemkutukov** [comment]
Thank you for such quick answers! and sorry that so many have spent your time)

**Comment by artemkutukov** [comment]
Thank you for such quick answers! and sorry that so many have spent your time)

**Comment by mikepenz** [comment]
@artemkutukov no problem :) great that i was able to help you :)

oh and the next version will have the .DarkToolbar theme which will then require the android:theme on your toolbar + app:popupTheme ;) 

will have to add this to the FAQ
