### ISSUE TITLE
weird behavior in my drawer

### ISSUE THREAD

**Issue by beshoy-samy** [mikepenz/MaterialDrawer#2550]
## I am having a weird behavior in my drawer

- before I click on any item the drawer looks like this
![InkedScreenshot_1579625351_LI](https://user-images.githubusercontent.com/16430789/72826615-d9c16780-3c81-11ea-97df-9eb2f29d7deb.jpg)

- after I do any click it looks like this which I actually want it to be
![Screenshot_1579625459](https://user-images.githubusercontent.com/16430789/72826604-d3cb8680-3c81-11ea-8af5-ca8eb3935ccd.png)

# how I build my drawer
```
drawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withAccountHeader(accountHeader)
                .withTranslucentStatusBar(true)
                .addDrawerItems(getDrawerItems())
                .addStickyDrawerItems(new PrimaryDrawerItem().withName(R.string.stpola)
                        .withIcon(R.drawable.stpola).withSelectable(false))
                .withCloseOnClick(true)
                .withOnDrawerItemClickListener(this)
                .build();
        drawer.setSelection(DrawerItemsIds.ITEM_HOME, true);
```

# my app theme
```
<style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:windowBackground">@color/whiteSmoke</item>
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:textColor">@color/slateGray</item>
        <item name="cardViewStyle">@style/CardView</item>
    </style>
```

## Details
- [6.1.2] Used library version
- [1.1.0 ] Used androidx library version
- [ 3.5.3] Used gradle build tools version
- [3.5.3 ] Used tooling / Android Studio version
- [29.0.2] build tools version

any help would be appreciated thank you!

**Comment by mikepenz** [comment]
@beshoy-samy can you reproduce this in the sample app? 

I would suppose something in drawing onto the insets

**Comment by beshoy-samy** [comment]
@mikepenz I tried a color instead of the drawable I am using in the account header and still, the same problem occurs also this problem only happened after migration to androidx
I will try to reproduce this in the sample app

**Comment by pehkay** [comment]
I am getting this behavior too with 6.1.2. Was there a solution for this?

**Comment by mikepenz** [comment]
Please try to reproduce this in the sample app. or showcase how to make it happen in the sample app. 

Also all of this behavior will be completely different and refactored in v8 so there is a high chance we won't make any changes to this in v6 anymore (as it also does not occur in the sample)

**Comment by mikepenz** [comment]
Closing for now. please report back with a reproducible sample or so, which allows us to have a closer look
