### ISSUE TITLE
lag when using fragment

### ISSUE THREAD

**Issue by azizi436** [mikepenz/MaterialDrawer#2551]
Hi 
I use **kotlin** and **version 7.0.0** of this library, and i have a fragment in navigation bottom which the **fragment** has 3 recycler view and a slider .
when i show the fragment , **drawer** work very **slowly** ,what should i do ??
could you help me?

**Comment by mikepenz** [comment]
Seems like something may be blocking your UI thread. Something in the code seems to cause it be slower..
Showing and closing the drawer is not part of this library as this is done by the `DrawerLayout`.

**Comment by mikepenz** [comment]
Were you able to identify the problem? 

If you still think it may be a library issue, please showcase the issue using the sample app. But as of the testing I did, I can not reproduce it in the sample.
