### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ARV105** [mikepenz/MaterialDrawer#2552]
## About this issue
I would like to use badge styling for the Account Holder. I can use badges in the drawer menu but not for an AccountHeader or AccountProfile. .withBadgeStyle or .withBadge is only available in a PrimaryDrawerItem().

Would it be possible for this feature to be added to a future release?

![ProfilewithBadge](https://user-images.githubusercontent.com/8717825/73372289-35888380-4274-11ea-9f6c-4d2fd89e157f.png)

**Comment by mikepenz** [comment]
I will have a look at this, and see if it makes sense to add this into the next major version of the library (MaterialDrawer v8)

Thanks for the suggestion and report.

**Comment by mikepenz** [comment]
This is now available in v8.0.0-b01
