### ISSUE TITLE
Alternatives withName() ... ?

### ISSUE THREAD

**Issue by flashiran1** [mikepenz/MaterialDrawer#2554]
hi  what Alternatives withName() or withEmail() ...???

I have cloned the example version but do not replace it in this version!

@Deprecated("Please consider to replace with the actual property setter")

**Comment by mikepenz** [comment]
@flashiran1 you can see them here: 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.kt#L24-L25

So something like

```
ProfileDrawerItem().apply {
     name = StringHolder(res)
     description = StringHolder(res)
}
```

would be the case
