### ISSUE TITLE
How to use NavController with Drawer in java?

### ISSUE THREAD

**Issue by mdtuyen** [mikepenz/MaterialDrawer#2555]
How can I use the NavController with the Drawer in my java application?
The setupWithNavController method could not be called.

**Comment by mikepenz** [comment]
@mdtuyen the latest versions of the `MaterialDrawer` are all only targeting Kotlin. Whereas most things will work fine in Java (may not as nice) some things will not work at all in Java. 

We are sorry for this and highly suggest to get started with Kotlin. 

We take PRs to improve compatibility (if it is in form of adding an annotation or so) but won't accept bigger changes which may add technical debt just so we can support Java. 

Thank you so much for you report though.

**Comment by ghost1372** [comment]
hi @mikepenz  how to implement navcontrol in kotlin? im new in kotlin and your library
tnx

**Comment by mikepenz** [comment]
@ghost1372 it is showcased here: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/NavControllerActivity.kt

**Comment by ghost1372** [comment]
@mikepenz  really fast! tnx❤
