### ISSUE TITLE
materialDrawerDividerColor not work

### ISSUE THREAD

**Issue by flashiran1** [mikepenz/MaterialDrawer#2556]
hi please help
`<item name="materialDrawerDividerColor">#ff0000</item>`

this lin not work in xml style

`<style name="SampleApp.DayNight" parent="Theme.MaterialComponents.DayNight.NoActionBar">
<item name="materialDrawerDividerColor">#ff0000</item>
<item name="materialDrawerStyle">@style/Widget.MaterialDrawerStyle</item>
<item name="materialDrawerHeaderStyle">@style/Widget.MaterialDrawerHeaderStyle</item>
</style>`

**Comment by mikepenz** [comment]
Which version of the drawer are you using?

**Comment by flashiran1** [comment]
oh very fast :)

my version 8.0.0-b01

**Comment by mikepenz** [comment]
So you tried something like: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/values/styles.xml#L9 ?

and use `Widget.MaterialDrawerStyleCustom` in your theme like:

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/values/themes.xml#L11

**Comment by flashiran1** [comment]
tanks 👍  

`<style name="SampleApp.DayNight" parent="Theme.MaterialComponents.DayNight.NoActionBar">
        <item name="materialDrawerStyle">@style/Widget.MaterialDrawerStyleCustom</item>
        <item name="materialDrawerHeaderStyle">@style/Widget.MaterialDrawerHeaderStyle</item>
    </style>

    <style name="Widget.MaterialDrawerStyleCustom" parent="Widget.MaterialDrawerStyle">
        <item name="materialDrawerDividerColor">#1FFFFFFF</item>
    </style>`
