### ISSUE TITLE
add list from Items

### ISSUE THREAD

**Issue by flashiran1** [mikepenz/MaterialDrawer#2557]
hi how add list from IDrawerItem<*>
in setItems

i can not init IDrawerItem<*>

`val drawerItems: IDrawerItem<*>
        drawerItems.apply {
            PrimaryDrawerItem().apply {
                name = StringHolder("asdasd")
                description = StringHolder("sdfsdfsdf")
                icon = ImageHolder(ContextCompat.getDrawable(this@MainActivity, R.drawable.profile))
                identifier = 1
                isSelected
            }
        }`

`slider.apply {
            addItems(drawerItems)
}`

indeed what alternative withDrawerItems ?

**Comment by flashiran1** [comment]
```
  val aaa: MutableList<IDrawerItem<*>> = arrayListOf()

        aaa.add(PrimaryDrawerItem().apply {
            name = StringHolder("asdasd")
            description = StringHolder("sdfsdfsdf")
            icon = ImageHolder(
                ContextCompat.getDrawable(
                    this@MainActivity,
                    R.drawable.profile
                )
            )
            identifier = 1
            isSelected
        })

        slider.apply {
            addItems(
                *aaa.toTypedArray()
            )
        }
```

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/util/MaterialDrawerSliderViewExtensions.kt#L54

You may also not use the extension but directly the adapter e.g.

```
slider.itemAdapter. set()
```
