### ISSUE TITLE
Crossfader overwrites enabled state

### ISSUE THREAD

**Issue by OuterObsessionSoftware** [mikepenz/MaterialDrawer#2559]
## About this issue

**Overview**
So I set: `.withEnabled(false)` on some items in my account header

I open expand my account header so I can see my `IProfile` and `ProfileSettingDrawerItem` items that I have added. As expected I can't click on any of said items :)

I now open/close my drawer with the profiles still expanded. Now I can click on the items that had `withEnabled(false)`

Expanding/collapsing the account header makes `withEnabled(false)` work again.

More interesting you can add `withEnabled(false)` on any drawer item that is not in the account header and it will simply not work until the account header is toggled.

Btw this only happens with the MiniDrawer

**Reproducing**
- In the MaterialDrawer sample app open the MiniDrawerActivity and add `.withEnabled(false)` to any item.
 - Drawer items not in the header fail to apply `.withEnabled(false)` immediately
 - Open and close the drawer with the header expanded, drawer items in the header now fail to apply `.withEnabled(false)`
 - Toggling the header returns proper functionality of `.withEnabled(false)`

## Details
(not sure on library version as I just reproduced in the sample app, but old enough to be in Java)
- Support library version: AndroidX 1.1.0
- Gradle build tools version: 28.0.3 
- Android Studio version: Android studio 3.5.3 

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
The problem is actually related to the `Crossfading` mechanism. which disables the view behind so that clicks are not going through. there have been reports of issues due to that at some point :/ 

Quickest solution would be to include the `CrossFadeSlidingPaneLayout` and modify it to not disable / enable views magically 

And then use a different base layout using your implementation: https://github.com/mikepenz/Crossfader/blob/develop/library/src/main/java/com/mikepenz/crossfader/Crossfader.java#L40-L43

**Comment by OuterObsessionSoftware** [comment]
I changed the implementation in `CrossFadeSlidingPaneLayout` (just commented out `enableDisableView`) but I still get the same behaviour?

**Comment by OuterObsessionSoftware** [comment]
As a temporary solution I just used `withPanelSlideListener` to close the `AccountHeader` when the drawer closes.

**Comment by OuterObsessionSoftware** [comment]
Actually using `myAccountHeader.updateProfile(profile)`  in `onPanelSlide` is a better patch.

**Comment by mikepenz** [comment]
It would still disable the item even without `enableDisableView`? that shouldn't be the case.

**Comment by OuterObsessionSoftware** [comment]
I cloned the crossfader repo and tried to reproduce but commenting out `enableDisableView` worked fine in that instance.

My guess is because I still had the compiled version of crossfader in my other project it was causing some sort of conflict or something.
