### ISSUE TITLE
2.8.2 - Colors are broken

### ISSUE THREAD

**Issue by buraktamturk** [mikepenz/MaterialDrawer#256]
Hello again,

I think there is a confusion in styles in 2.8.2, I am using MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus theme and textColors are white instead of black. In 2.8.1 there is no problem.

I can attach screenshot in case of need.

**Comment by mikepenz** [comment]
DarkToolbar --> Dark background -> white text. 

And yes screenshot will help.

**Comment by buraktamturk** [comment]
But it's not MaterialDrawerTheme.DarkToolbar.TranslucentStatus, it is MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus, it means dark toolbar on white background and black text.

Before 2.8.2

![screen11](https://cloud.githubusercontent.com/assets/3593288/7307019/2ee25200-ea12-11e4-9ac3-51c702c467e4.png)

![screen12](https://cloud.githubusercontent.com/assets/3593288/7307023/37e6ff9a-ea12-11e4-9a83-8608f9182c68.png)

After 2.8.2 (nothing changes in code or layouts except the gradle file)
![screen shot 2015-04-23 at 23 41 59](https://cloud.githubusercontent.com/assets/3593288/7307040/62b93cc4-ea12-11e4-870a-f4271fd131f8.png)

![screen13](https://cloud.githubusercontent.com/assets/3593288/7307026/40891fa2-ea12-11e4-9057-3eb1c1691817.png)

Some of them are black because their style is not @android:style/TextAppearance.Large, some of them have textColor black in their definition.

![screen14](https://cloud.githubusercontent.com/assets/3593288/7307028/466e3d62-ea12-11e4-9ded-707c33906db7.png)

**Comment by mikepenz** [comment]
@buraktamturk ah i see. no issue with the color of the drawer or the colors of the toolbar. 

but with one of your elements.

a possible solution is to use a normal light theme and set the ThemeOverlay.AppCompat.Dark theme on your toolbar. i assume something changed with the following commit:
https://github.com/mikepenz/MaterialDrawer/commit/569bff6212c7833e9b35c3a085c1603dd71279b1

**Comment by buraktamturk** [comment]
No problem on me, as it's an easy fix on my side. I just throught the theme was (mistakenly) inherited by the dark version instead of the light version or something else in the new version.

**Comment by mikepenz** [comment]
@buraktamturk i think this should work for you:

```xml
 <?xml version="1.0" encoding="utf-8"?>
    <android.support.v7.widget.Toolbar
        android:id="@+id/my_awesome_toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="@color/green"
        app:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light"/>
```

no the theme itself is correct. but yeah the new appcompat style is handled different and it seems it is not possible anymore to set the theme for the actionBar only like it was done before... :/

**Comment by buraktamturk** [comment]
I think i didn't understant it all, should i change my activity theme to MaterialDrawerTheme.DarkToolbar.TranslucentStatus then give my toolbar @style/ThemeOverlay.AppCompat.Dark.ActionBar?

**Comment by mikepenz** [comment]
@buraktamturk no you change it to MaterialDrawerTheme.Light.TranslucentStatus and then you add the styles with `app:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"` to your toolbar

**Comment by buraktamturk** [comment]
It worked with one side effect, the drawer indicator icon is now black instead of white. But the search button reamins white.

**Comment by mikepenz** [comment]
@buraktamturk that's ture ^^ :/ it's annoying :D

**Comment by buraktamturk** [comment]
^^ but it's cool too. Thank you much for all of this. It's like a feature like on YouTube app :)

**Comment by mikepenz** [comment]
@buraktamturk haha yes. but i think i can create the theme to fix this. but devs will have to add the theme to their toolbar which is (or should be done) 

I just see those why is the text black questions :D

**Comment by buraktamturk** [comment]
That's very normal you to see those questions, it's success. Your library is so friendly even ones who does not know much about android or doesn't know why it's happening.

**Comment by mikepenz** [comment]
@buraktamturk no problem. great that i was able to help you. 

(i think github had just a big issue :D)

the next version will feature the .DarkToolbar theme fixed which will allow you to use it. but will require the android:theme and app:popupTheme
