### ISSUE TITLE
[8.0.0-b02]AccountHeaderView missing function to remove profile

### ISSUE THREAD

**Issue by onlymash** [mikepenz/MaterialDrawer#2560]
## About this issue
There are [clear][removeProfileByIdentifier] functions in v7.0,and these are missing in v8.0, making it difficult for my app to migrate to v8.0

## Details
- [ 8.0.0-b02] Used library version

**Comment by mikepenz** [comment]
Thanks for the report. we will have a look and add all relevant APIs which may be of help
