### ISSUE TITLE
How to clear all items (include sticky) from slider in v8.0.0-b02

### ISSUE THREAD

**Issue by beeline09** [mikepenz/MaterialDrawer#2561]
slider.removeAllItems () only removes PrimaryDrawerItems, but I need everything to be cleared, even stickyDrawerItems

**Comment by mikepenz** [comment]
We will add more convenient methods via: https://github.com/mikepenz/MaterialDrawer/issues/2560

**Comment by beeline09** [comment]
Thanks! But what should I do now? Can you tell me how to remove stickydraweritems separately?

**Comment by mikepenz** [comment]
Sadly this was missed out and is not yet available in the current pre release. 

there is only 1 workaround possible :/ 

```kotlin
sliderView.apply {
    stickyFooterDivider = false
    stickyDrawerItems.clear()
}
```

(note the apply, and the setting the divider to false or true is needed)

**Comment by beeline09** [comment]
Thank you very much! It helps me! Thanks for such a wonderful library!
