### ISSUE TITLE
Changing the Toolbar icon to Back

### ISSUE THREAD

**Issue by aniq-pirzada** [mikepenz/MaterialDrawer#2562]
## About this issue
How do you change the hamburger icon to a back icon when navigating from one fragment to another. For example my Fragment1 (which has a recyclerView) and can click on an item to go to Fragment 2 and change the toolbar icon to back instead of the hamburger icon.

I have tried `(activity as AppCompatActivity).supportActionBar?.setDisplayHomeAsUpEnabled(true)` but this is not working.

Navigate from one fragment to another fragment using: 
```
holder.itemView.setOnClickListener { v ->
  Log.d("Clicked", item.name)                
  v.findNavController().navigate(R.id.action_fragment1_to_fragment2)
}
```

## Details
- Used library version: 8.0.0-b02
- Support library version: AndroidX 1.1.0
- Gradle build tools version: 28.0.3
- Android Studio version: Android studio 3.5.3

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [X] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [X] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
thank you for your report. 

With v8 the `MaterialDrawer` will no longer handle or manage the back arrow / `ActionBarDrawerToggle` and gives full control back to the developer :) 

Have a look here:
https://developer.android.com/reference/androidx/appcompat/app/ActionBarDrawerToggle

and perhaps also here:
https://stackoverflow.com/questions/26651602/display-back-arrow-on-toolbar
