### ISSUE TITLE
Issue when resolving materialdrawer-iconics

### ISSUE THREAD

**Issue by EngMah96** [mikepenz/MaterialDrawer#2566]
I'm trying to install materialdrawer-iconics inside gradle and I'm getting the following issue:
```
ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.mikepenz:materialdrawer-iconics:8.0.0-b04.
Show Details
Affected Modules: app
```
My implementation line is:
`implementation "com.mikepenz:materialdrawer-iconics:8.0.0-b04@aar"
`
I tried this too:
`    implementation "com.mikepenz:materialdrawer-iconics:8.0.0-b04"`
but the same error, so can you help me

**Comment by mikepenz** [comment]
@EngMah96 the library is not yet on maven central as it is not final and bintray does not allow non release versions of libraries on their main repo. 

You can find it here: https://bintray.com/beta/#/mikepenz/maven/com.mikepenz:materialdrawer-iconics?tab=overview

And it is available via the bintray repo from here: https://dl.bintray.com/mikepenz/maven
