### ISSUE TITLE
cannot resolve method 'init(anonymous com.mikepenz.materialdrawer.util.AbstractDrawerImageLoader)'

### ISSUE THREAD

**Issue by guitorioadar** [mikepenz/MaterialDrawer#2568]
## About this issue

`DrawerImageLoader.init` is not initializing...

     //====================== Drawer ======================

        // Create the AccountHeader
        headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withProfileImagesClickable(true)
                .withOnAccountHeaderProfileImageListener(new AccountHeader.OnAccountHeaderProfileImageListener() {
                    @Override
                    public boolean onProfileImageClick(View view, IProfile profile, boolean current) {
                        // startActivity(new Intent(HomeActivity.this, ProfileActivity.class));
                        return false;
                    }

                    @Override
                    public boolean onProfileImageLongClick(View view, IProfile profile, boolean current) {
                        return false;
                    }
                })
                .withSelectionListEnabledForSingleProfile(false)
                .addProfiles(
                        new ProfileDrawerItem()
                                .withName(SharedPreferanceClient.read("customerNmae", null)).withIdentifier(101)
                                .withEmail(SharedPreferanceClient.read("customerEmail", null)).withIdentifier(102)
                                // .withIcon(IMAGE_URL)
                                .withIdentifier(103)

                                .withIcon(getResources().getDrawable(R.drawable.logo))
                )
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                        return false;
                    }
                })
                .build();

        //initialize and create the image loader logic
        DrawerImageLoader.init(new AbstractDrawerImageLoader() {
            @Override
            public void set(ImageView imageView, Uri uri, Drawable placeholder) {
                Picasso.get().load(uri).placeholder(placeholder).resize(500, 500).centerCrop().into(imageView);
            }

            @Override
            public void cancel(ImageView imageView) {
                Picasso.get().cancelRequest(imageView);
            }
        });

        //Drawer
        drawerBuilderLeft = new DrawerBuilder()
                .withActivity(this)
                // .withToolbar(mainActivityToolbar)
                .withDisplayBelowStatusBar(true)
                .withActionBarDrawerToggle(false)
                .withActionBarDrawerToggleAnimated(true)
                .withDrawerGravity(Gravity.START)
                .withSliderBackgroundDrawableRes(R.drawable.nav_drawer_bg)
                .withSavedInstance(savedInstanceState)
                // .withSelectedItem(0)
                // .withAccountHeader(headerResult)
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {

                        // getSelectedItemIdentifier(drawerItem);

                        return false;
                    }
                })
                .withOnDrawerItemLongClickListener(new Drawer.OnDrawerItemLongClickListener() {
                    @Override
                    public boolean onItemLongClick(View view, int position, IDrawerItem drawerItem) {
                        return false;
                    }
                })
                .withOnDrawerListener(new Drawer.OnDrawerListener() {
                    @Override
                    public void onDrawerOpened(@NotNull View view) {

                    }

                    @Override
                    public void onDrawerClosed(@NotNull View view) {
                        drawerOpen = false;
                    }

                    @Override
                    public void onDrawerSlide(@NotNull View view, float v) {

                    }
                })
                .build()
        ;

## Details
- [7.0.0] Used library version
- [1.1.0] Used support library version
- [29.0.2] Used gradle build tools version
- [Android Studio 3.4.2] Used tooling / Android Studio version

I could not find what am i doing wrong but i am getting this error....

> cannot resolve method 'init(anonymous com.mikepenz.materialdrawer.util.AbstractDrawerImageLoader)'

**Comment by mikepenz** [comment]
The sample (which is in kotlin uses it without issues): 

https://github.com/mikepenz/MaterialDrawer/blob/v7.0.0/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.kt#L37-L59

I believe you may need to use 

`DrawerImageLoader.Companion.init()` 

as you are java user

**Comment by guitorioadar** [comment]
Thank you.... As i was working on java... this works for me.... and thanks again for this awesome library

**Comment by 2mbili** [comment]
> Thank you.... As i was working on java... this works for me.... and thanks again for this awesome library

Hi, please share your solution.  DrawerImageLoader.Companion.init(new AbstractDrawerImageLoader() {... is this what you mean?
