### ISSUE TITLE
how change textSize 

### ISSUE THREAD

**Issue by flashiran1** [mikepenz/MaterialDrawer#2570]
hi how cheng description text size  in ProfileDrawerItem??

**Comment by mikepenz** [comment]
there is no direct API to do this, because this should not be done, as the items follow the material design guidelines. 

You can do it though by either overwriting the dimensions in the dimens.xml. Or by creating your own custom draweritem:

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/values/dimens.xml

**Comment by flashiran1** [comment]
i overwriting the dimensions in the my dimens.xml but not work

```xml
    <dimen name="material_drawer_item_profile_description">14sp</dimen>
```

**Comment by flashiran1** [comment]
and Some fonts are small in size

**Comment by mikepenz** [comment]
The profile drawer item uses: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_profile.xml#L46
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_profile.xml#L71

The profile settings item uses:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_profile_setting.xml#L39
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_profile_setting.xml#L56

The dimensions follow the guidelines. usually users who do not like the default sizes will change their phone in general to a larger font

**Comment by flashiran1** [comment]
how get  material_drawer_email  TextView from ProfileDrawerItem?

**Comment by mikepenz** [comment]
you can't you can change the dimension specification, or you can create your own custom drawerItem which is more complicated

**Comment by flashiran1** [comment]
how crate custom drawerItem?

**Comment by mikepenz** [comment]
look at an existing as base: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileSettingDrawerItem.kt

**Comment by flashiran1** [comment]
I made a custom ProfileDrawerItem but not work
I don't need ProfileSettingDrawerItem Because my app is single-user
i debug ProfileDrawerItem  but Can't get inside the custom ProfileDrawerItem

**Comment by mikepenz** [comment]
If you don't need profiles why do you use them then? 

There have been issues already on how to not have profile change, disable the drop down and similar. you can find everything by searching. 

also the sample showcases many different aspects. 

if you just want to change the font size. then overwrite the dimensions as outlines earlier.
