### ISSUE TITLE
How to override the arrow_back button.

### ISSUE THREAD

**Issue by mrDevGo** [mikepenz/MaterialDrawer#2571]
Hello. I hid the hamburger and showed the button arrow_back.

`       
mDrawer.actionBarDrawerToggle?.isDrawerIndicatorEnabled = false
mainActivity.supportActionBar?.setDisplayHomeAsUpEnabled(true)`

But when clicked , the driver opens. How to make the button work like a system onBaskPressed()?

## Details
- [ 7.0.0 ] Used library version
- [ 1.1.0 ] Used support library version
- [ 3.6.1  ] Used gradle build tools version
- [ 3.6 ] Used tooling / Android Studio version

## Checklist

- [* ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ *] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [ *] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [* ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ *] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ *] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
if you do not want the `Drawer` to manage the toggle for you, simply don't provide the toolbar and things will be in your control :) 

with v8 we also remove managing this completely

**Comment by Sailoc** [comment]
Hello, I have the same problem, I disabled the driver

`
val drawer = result.drawerLayout

drawer.setDrawerLockMode (DrawerLayout.LOCK_MODE_LOCKED_OPEN)
`

But when you click on the back button, the Driver opens.

**Comment by mikepenz** [comment]
If you do not want the drawer to close you should not call the close drawer method: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MenuDrawerActivity.kt#L73

those things are all related to the `DrawerLayout` itself :)

**Comment by mrDevGo** [comment]
> Hello, I have the same problem, I disabled the driver
> 
> `
> val drawer = result.drawerLayout
> 
> drawer.setDrawerLockMode (DrawerLayout.LOCK_MODE_LOCKED_OPEN)
> `
> 
> But when you click on the back button, the Driver opens.

` toolbar.setNavigationOnClickListener {
          // Do something here when you click on the button back...
        }`
