### ISSUE TITLE
Drawer Profile name has in-correct text color 

### ISSUE THREAD

**Issue by Shajeel-Afzal** [mikepenz/MaterialDrawer#258]
Hi. I am adding profile as:

```java
headerResult = new AccountHeader()
                .withActivity(MainActivity.this)
                .addProfiles(
                        new ProfileDrawerItem().withName("Mike Penz").withEmail("mikepenz@gmail.com")
                )
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                        return false;
                    }
                })
                .build();
```

the text color is white with white background. Can it pick the color from app theme?

Thnaks.

**Comment by mikepenz** [comment]
@Shajeel-Afzal what theme? what version?

**Comment by Shajeel-Afzal** [comment]
Theme: `MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus`
Version: 
`compile('com.mikepenz.aboutlibraries:library:4.5.9@aar') {
        transitive = true
}`

**Comment by mikepenz** [comment]
@Shajeel-Afzal you can set the theme for the text by code. it uses the correct color but your image is "wrong" for the theme. :D just use the api methods

**Comment by Shajeel-Afzal** [comment]
I am trying `.withTextColor()` with `AccountHeader`. By the way i am sorry i could not understand "your image is "wrong" for the theme."

Thanks.

**Comment by Shajeel-Afzal** [comment]
`withtextColor()` worked.

**Comment by mikepenz** [comment]
yeah. is the best idea :) 

you could also overwrite following in your theme: `material_drawer_header_selection_text`
or the color with the same name `material_drawer_header_selection_text`


(there can only be one default color :P and white is standard :D )

**Comment by Shajeel-Afzal** [comment]
Thanks @mikepenz. awesome.
