### ISSUE TITLE
Header name disappear while changing the header name color 

### ISSUE THREAD

**Issue by deepakdawson** [mikepenz/MaterialDrawer#2580]
## About this issue

- when i change the color of name in the header of drawer with setTextColor() method, the color not change. i am using the version 6.1.2 and when i tried to change color by getting header reference and get the reference of textview, by doing this text does not appear on the screen. please help me how to solve this issue. 

this is my code

 PrimaryDrawerItem item1 = new PrimaryDrawerItem().withIdentifier(1).withName("item1");
        SecondaryDrawerItem item2 = new SecondaryDrawerItem().withIdentifier(2).withName("item2");
        Bitmap bitmap = ((BitmapDrawable)getResources().getDrawable(R.drawable.layer1)).getBitmap();
        Bitmap r = Bitmap.createScaledBitmap(bitmap,500,500,false);
        ProfileDrawerItem myProfile = new ProfileDrawerItem();
        myProfile.withIcon(new BitmapDrawable(getResources(),r))
                .withName("Deepak");

        AccountHeader accountHeader = new AccountHeaderBuilder()
                .withActivity(this)
                .addProfiles(myProfile)
                .withSelectionListEnabledForSingleProfile(false)
                .build();
        mDrawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(mMaterialToolbar)
                .withActionBarDrawerToggleAnimated(true)
                .withActionBarDrawerToggle(true)
                .withAccountHeader(accountHeader)
                .addDrawerItems(
                item1,
                new DividerDrawerItem(),
                item2,
                new SecondaryDrawerItem()
        ).build();
        View header =  mDrawer.getHeader();
        TextView hName = header.findViewById(R.id.material_drawer_account_header_name);
        hName.setTextColor(0xff0000);

**Comment by mikepenz** [comment]
I can't really support old versions anymore.

Anyways. have you had a look at the colors and style section in the old README? 

https://github.com/mikepenz/MaterialDrawer/tree/v6.1.2#custom-style---stylesxml

**Comment by deepakdawson** [comment]
> I can't really support old versions anymore.
> 
> Anyways. have you had a look at the colors and style section in the old README?
> 
> https://github.com/mikepenz/MaterialDrawer/tree/v6.1.2#custom-style---styles

i am very thankful to you that you answered my question within no time. I solved this issue
