### ISSUE TITLE
CrossfadeWrapper.kt Error

### ISSUE THREAD

**Issue by iman2420** [mikepenz/MaterialDrawer#2583]
CrossfadeWrapper.kt: (12, 28):

Type parameter bound for T in val <T : SlidingPaneLayout!> Crossfader<T>.isCrossFaded: Boolean where T : ICrossFadeSlidingPaneLayout!
 is not satisfied: inferred type CapturedTypeConstructor(*) is not a subtype of ICrossFadeSlidingPaneLayout!

**Comment by mikepenz** [comment]
@iman2420 do you have any additional information? 

There is no such file in this project

**Comment by iman2420** [comment]
@mikepenz i try to implement MiniDrawerActivity like [this page](https://github.com/mikepenz/MaterialDrawer/blob/c3b0e61ab13b14ae4a94e8d011f690781a08472b/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.kt)

**Comment by mikepenz** [comment]
Which version of the crossfader do you use?

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/build.gradle#L94-L97

**Comment by iman2420** [comment]
@mikepenz` implementation "com.mikepenz:crossfader:1.6.0"`

**Comment by mikepenz** [comment]
Hmmm something seems to not match these versions in your app as the sample app compiles just fine :)

**Comment by iman2420** [comment]
@mikepenz  I don't understand what you mean, Mike, can you explain more?
I just copied the code

**Comment by mikepenz** [comment]
I do not know as I do not have access to your code / the project. 

You can get the sample project here on github, and you can see it will compile. 
Please ensure all dependencies were provided / you have the proper imports / the right versions.

**Comment by milovan92** [comment]
@iman2420 I had similar problem. You need to include this dependency 'androidx.slidingpanelayout:slidingpanelayout:1.0.0'

**Comment by mikepenz** [comment]
I hope this is resolved by adding:

```
implementation "androidx.slidingpanelayout:slidingpanelayout:${versions.slidingpaneLayout}"
``` 

?

Please report back if you need more help

**Comment by mikepenz** [comment]
Thanks @milovan92 for helping
