### ISSUE TITLE
DrawerLayout is always behind BottomSheet, no matter any params

### ISSUE THREAD

**Issue by dexion** [mikepenz/MaterialDrawer#2585]
## About this issue

- Briefly describe the issue

DawerLayout is always behinde BottomSheet, but I want vice versa that drawer should be under bottom sheet. Elevation, order in layout file - nothing works

- How can the issue be reproduced / sample code

My layout at [pastebin](https://pastebin.com/mXBHHuYf)

## Details
- [ x] Used library version: 8.0.1
- [x ] Used support library version: material-1.1.0
- [x] Used gradle build tools version 29.0.3
- [x] Used tooling / Android Studio version. AS 3.6.2
- [x] Other used libraries, potential conflicting libraries: com.google.android.material:material:1.1.0

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@dexion this is a problem with the `DrawerLayout` setup you have. this library does no longer maintain the `DrawerLayout` and the control is fully on your side :) 

Please reference to official documentation on how to define the layout when you have a `DrawerLayout`

**Comment by mikepenz** [comment]
(the drawerlayout should be the root of your activity in most cases)

**Comment by dexion** [comment]
Thanks! My fault is that I use `CoordinatorLayout` as root instead `DrawerLayout`. I moved `CoordinatorLayout` inside `DrawerLayout`.
