### ISSUE TITLE
Can't listen onDrawerOpened in 8.0.1

### ISSUE THREAD

**Issue by dexion** [mikepenz/MaterialDrawer#2586]
How to listen `onDrawerOpened`/`onDrawerClosed` event at 8.0.1 version like at 6.1.1? I can't find anything in code. Only two listeners - `onDrawerItemClickListener` and `onDrawerItemLongClickListener`

**Comment by mikepenz** [comment]
8.0.1 stopped managing the `DrawerLayout` it only provides the slider (the content) 

If you want to open / close please refer to the `DrawerLayout` API (also for a listener regarding these)

https://developer.android.com/reference/android/support/v4/widget/DrawerLayout#adddrawerlistener
(please refer to the androidX docs can't find right now)
