### ISSUE TITLE
Custom header item with a search bar

### ISSUE THREAD

**Issue by itsamirrezah** [mikepenz/MaterialDrawer#2587]
Great library! Thank you for your hard work.
I tried to put a search bar above the drawer items as a header, but I couldn't find a way to implement something like custom header item.
is it possible to achieve this?
[screenshot](https://imgur.com/wCiiUcV)

## Details
- [8.0.1] Used library version
- [3.5.1] Used gradle build tools version
- [3.5.1] Used tooling / Android Studio version

## Checklist
- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)

**Comment by mikepenz** [comment]
Your screenshot does not really show a search bar. 

Anyways. it is not directly supported, can be achieved with some workarounds though. 

I believe there has been a similar question in the past. 


The library provides an API to provide a custom header view or layout. 

You can always also create custom drawerItems for other features. remember the drawer content is basically a `RecyclerView` so it is flexible in that regard.

**Comment by itsamirrezah** [comment]
Since I have a very simple use case I think it makes sense to use a custom drawer item at top of the drawer for search bar insead of creating a custom header.

Thank you for your response @mikepenz
