### ISSUE TITLE
App crashes when "colorSurface" or "materialDrawerBackground" is not set

### ISSUE THREAD

**Issue by dankito** [mikepenz/MaterialDrawer#2589]
## About this issue

I added MaterialDrawer version 8.0.1 to my project and got an UnsupportedOperationException that an attribute could not be resolved:

```
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0300c0 a=3}
        at android.content.res.TypedArray.getDrawable(TypedArray.java:925)
        at android.content.res.XResources$XTypedArray.getDrawable(XResources.java:1372)
        at com.mikepenz.materialdrawer.widget.MaterialDrawerSliderView.<init>(MaterialDrawerSliderView.kt:405)
```

Issue was that in my project neither a value for attribute "colorSurface" nor for "materialDrawerBackground" was set.

Could you please give "materialDrawerBackground" or "colorSurface" a feasible default value (e.g. "colorPrimary") in your library so that adding MaterialDrawer to a project works out of the box?

Cheers, and thanks a lot for your great library!
dankl

## Details
MaterialDrawer version 8.0.1, AndroidX AppCompat and Material Design version 1.1.0, Gradle 6.2.1, Android Studio 3.6.

**Comment by mikepenz** [comment]
@dankito the drawer requires a theme which is a parent of one of the `Material` themes from the material components. 

I will investigate the requirement for `materialDrawerBackground ` though as this should fallback to a default

**Comment by mikepenz** [comment]
Just tried to only use the material components theme. E.g.: `Theme.MaterialComponents.DayNight.NoActionBar` and it works fine. 

Please check again if you had used a Material components theme. 

The same as with most components from the material components library, the drawer requires a material compoments theme :)

**Comment by yashjain27** [comment]
Thanks for the answer. FInally I have the slider working =)

For those who were further confused like me, you need to do this:

`<resources>

    
    <style name="AppTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>

        <item name="materialDrawerStyle">@style/Widget.MaterialDrawerStyle</item>
        <item name="materialDrawerHeaderStyle">@style/Widget.MaterialDrawerHeaderStyle</item>
    </style>





</resources>`

Youtuber's add a new style to styles.xml. You shouldn't do that. Modify the pre-existing style's parent like how I did above and it should work!
