### ISSUE TITLE
Status bar hides away when using MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus theme

### ISSUE THREAD

**Issue by Shajeel-Afzal** [mikepenz/MaterialDrawer#259]
Hi!

My app theme is: `MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus`

and when i open an activity that does not has navigation drawer. The layout shows below the status bar. Please see the attached picture. 

![device-2015-04-25-020706](https://cloud.githubusercontent.com/assets/3718283/7328582/0c67f746-eaf0-11e4-85fc-02d4ae683f8f.png)

I have tested it on Android 4.4.4 with app version 4.5.9

```gradle
compile('com.mikepenz.aboutlibraries:library:4.5.9@aar') {
        transitive = true
    }
```

Thanks.

**Comment by mikepenz** [comment]
@Shajeel-Afzal for non MaterialDrawer activities you should use a theme which has no Translucent Statusbar
