### ISSUE TITLE
How add additional text under email?

### ISSUE THREAD

**Issue by alexei-28** [mikepenz/MaterialDrawer#2597]
Is it possible to show not only additional text just under email?
And also is it possible to change height of Header item?

**Comment by mikepenz** [comment]
@alexei-28 there's no direct support for this, the header only supports 2 lines. name and e-mail
This is not supported as it is not part of the material design guidelines. 


You may want to provide your own custom header layout instead (if you don't need the profile functionality) 
E.g. pass in the view for the header, and manage it's UI directly. 

Alternative you can overwrite the header layout used for the account header (it requires though to retain all ids and views there are) additionally this may break with version updates. 
doing this you can then access the view from the header


----

changing the height of the header can be done via the respective method: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/widget/MaterialDrawerSliderView.kt#L179
(this is only for the scenario of a custom header view though: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/widget/MaterialDrawerSliderView.kt#L145-L159)

**Comment by mikepenz** [comment]
I greatly recommend to stay with the guidelines as it will not require custom adjustments

**Comment by mikepenz** [comment]
I hope this answered your questions. Please report back if additional questions occur
