### ISSUE TITLE
Is it possible to remove space between items and divider?

### ISSUE THREAD

**Issue by alexei-28** [mikepenz/MaterialDrawer#2599]
Android Studio 3.6

` implementation("com.mikepenz:materialdrawer:6.0.9@aar") { transitive = true }`

Is it possible to remove space between items and divider?

![image](https://user-images.githubusercontent.com/303539/80764540-9496b680-8b49-11ea-9f2c-b670b53a6d11.png)

**Comment by mikepenz** [comment]
have a look in those 2 method: 

https://github.com/mikepenz/MaterialDrawer/blob/v6.0.9/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L298-L312

**Comment by alexei-28** [comment]
> have a look in those 2 method:
> 
> https://github.com/mikepenz/MaterialDrawer/blob/v6.0.9/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L298-L312

`.withDividerBelowHeader(false)`

No. I mean not remove divider. I only need to remove space between item and divider.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/v6.0.9/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L298

**Comment by alexei-28** [comment]
> https://github.com/mikepenz/MaterialDrawer/blob/v6.0.9/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L298

```
.withDividerBelowHeader(true)
.withPaddingBelowHeader(false)
```

Not help. The space is not gone.

**Comment by mikepenz** [comment]
So I tried it with the latest release (as I can't support old versions) and it looks to work:

![photo_2020-05-09 16 46 32](https://user-images.githubusercontent.com/1476232/81476872-a85eae80-9214-11ea-83e2-c2cbdd3851de.jpeg)
![photo_2020-05-09 16 46 34](https://user-images.githubusercontent.com/1476232/81476876-aa287200-9214-11ea-97c5-448512c6248f.jpeg)

-----

So looking at it I realize you want a different kind of divider. 

The divider defines a 8dp padding top and bottom:
![image](https://user-images.githubusercontent.com/1476232/81476897-c9270400-9214-11ea-8a26-5d30980c5bd1.png)


You can either overwrite it's layout changing all divider items, or you create your own divider draweritem based on the one provided by the library which has no padding top or bottom
