### ISSUE TITLE
Change Toggle Button Color

### ISSUE THREAD

**Issue by easycheese** [mikepenz/MaterialDrawer#260]
Is there any way to manually change the Toggle Button color?  I can't seem to find one...

Note:  I don't want to change the Theme from MaterialDrawerTheme.Light to MaterialDrawerTheme.Light.DarkToolbar

**Comment by mikepenz** [comment]
@easycheese i use the normal toggleButton i think this one can't be colored. Just implement a Custom DrawerItem. should be really really easy
