### ISSUE TITLE
How to disable accountSwitcherArrow?

### ISSUE THREAD

**Issue by goodibunakov** [mikepenz/MaterialDrawer#2600]
Hi, Mike!
I try to disable arrow, but i cant find how to do it.

`headerView = AccountHeaderView(this, compact = true)
                .apply {
                    attachToSliderView(slider)
                    headerBackground = ImageHolder(R.drawable.header)
                    addProfiles(profile)
                    withSavedInstance(savedInstanceState)
                    accountSwitcherArrow.visibility = View.GONE
                }`

visibility does not work.
And  how to disable clickListener for this arrow drawable? onAccountHeaderListener = null does not work

**Comment by mikepenz** [comment]
You want to use the provided header with only a single profile?


you can disable the selection list via `selectionListEnabledForSingleProfile`

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/widget/AccountHeaderView.kt#L240-L241

**Comment by goodibunakov** [comment]
selectionListEnabledForSingleProfile = false 
yep, it is what i need
thanks
