### ISSUE TITLE
StickyFooter Not clickable on First Launch

### ISSUE THREAD

**Issue by pavan555** [mikepenz/MaterialDrawer#2602]
## About this issue

Using MaterialDrawer Version Java&AndroidX 6.1.2

I have added the sticky Footer and it is working fine except when the app first launch 

Here is the snippet of adding of StickyFooter to DrawerBuilder object 

```java
Drawer resultDrawer=drawerBuilder.withStickyFooterDivider(true)
                    .withStickyFooterShadow(true)
                    .withStickyFooter(R.layout.sticky_footer).build();

activity.findViewById(R.id.headbutton).setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Intent intent = new Intent(activity, GetProActivity.class);
                    intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
                    activity.startActivityForResult(intent, START_MANAGE_SUBS);
                }
});
```

here is the **sticky_footer** layout

```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <Button
        android:id="@+id/headbutton"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:background="#03a9f4"
        android:gravity="center"
        android:text="GET PRO NOW"
        android:textColor="#ffffff"/>

</RelativeLayout>
```

**Comment by mikepenz** [comment]
@pavan555 you can not create a click listener like this. 

The content of the drawer is a RecyclerView so this item will not exist when you first create it. only if you scroll then this view will exist. 

You can provide the inflated view instead if you want to ensure the view already existed. 

The proper way would be to simply use normal sticky drawer items and pass them as item. 

If you need a custom design you can always create your own custom draweritems

**Comment by pavan555** [comment]
@mikepenz thanks for letting me know
