### ISSUE TITLE
No non-deprecated way to set item level

### ISSUE THREAD

**Issue by Nohus** [mikepenz/MaterialDrawer#2603]
## About this issue

In the `BaseDrawerItem` class:

```Kotlin
    var level = 1
        protected set

    @Deprecated("Please consider to replace with the actual property setter")
    fun withLevel(level: Int): T {
        this.level = level
        return this as T
    }
```

The `withLevel` deprecation message says to use the property setter, but the property setter is `protected` so it can't be used.

## Details
- [x] Used library version: 8.0.2
- [ ] Used support library version: not relavant
- [ ] Used gradle build tools version: not relavant
- [ ] Used tooling / Android Studio version: not relavant
- [ ] Other used libraries, potential conflicting libraries: not relavant

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thank you @Nohus for your report. this will be fixed in v8.0.3
