### ISSUE TITLE
Icon color

### ISSUE THREAD

**Issue by MBoberski** [mikepenz/MaterialDrawer#2605]
## Question

Is there a way for make PrimaryDrawerItem to change color if item is in active state?

I use newest library version.

**Comment by mikepenz** [comment]
which icon do you use?

do you have tinting enabled? `withIconTintingEnabled`

**Comment by MBoberski** [comment]
I use tint enable and also I use vector asset. But icon stays the same color, all the time. I want to icon be gray at default and green if item is in active state.

**Comment by MBoberski** [comment]
Ok I see now, I was in need od removing materialDrawerPrimaryIcon to get selector working.

**Comment by mikepenz** [comment]
Sounds like you were able to resolve your question?

Please re-open if you need something else

**Comment by engi** [comment]
I'm using this thread because I have the same problem and I can't find the solution to use your library (v 9.0.2).
I want to insert items in the drawer whose icons are customized (color, size) according to certain criteria.
No matter what I try, nothing works as expected. I can change the size or the color, but nothing changes in the activity.
Here's an extract from the code I'm using:

Style:
    `<style name="AQPTheme" parent="Theme.Material3.DayNight" >
        <item name="colorPrimary">@color/colorDayPrimary</item>
        <item name="colorPrimaryVariant">@color/colorDayPrimaryVariant</item>
        <item name="colorOnPrimary">@color/colorDayOnPrimary</item>
        <item name="colorSecondary">@color/colorDaySecondary</item>
        <item name="colorSecondaryVariant">@color/colorDaySecondaryVariant</item>
        <item name="colorOnSecondary">@color/colorDayOnSecondary</item>
        <item name="windowActionModeOverlay">true</item>
        <item name="actionModeBackground">@color/colorDayPrimary</item>
        <item name="materialDrawerStyle">@style/Widget.MaterialDrawerStyle</item>
        <item name="floatingActionButtonStyle">@style/AQPFabButtonStyle</item>
        <item name="android:windowTranslucentStatus">true</item>
    </style>`

Activity:

    ```fun setNavigationDrawer(savedInstanceState: Bundle?)
    {
        val alarmesDrawerItem: PrimaryDrawerItem = PrimaryDrawerItem().apply {
            identifier = 1
            nameRes = R.string.main_menu_alarmes
            isSelectable = false
            iconDrawable = IconicsDrawable(mContext, GoogleMaterial.Icon.gmd_notifications).apply {
                colorInt = R.color.md_amber_300
                sizeDp = 72
            }
        }

        osmosisDrawerItem = PrimaryDrawerItem().apply {
            identifier = 2
            nameRes = R.string.main_menu_osmoseur
            isSelectable = false
            iconDrawable = IconicsDrawable(mContext, CommunityMaterial.Icon.cmd_chemical_weapon).apply {
                colorInt = R.color.md_amber_500
                sizeDp = 72
            }
        }

        binding?.slider?.apply {
            addItems(
                alarmesDrawerItem,
                osmosisDrawerItem!!
            )
            setSavedInstance(savedInstanceState)
        }
    }```

What do you think about it?
