### ISSUE TITLE
set Email in ProfileDrawerItem

### ISSUE THREAD

**Issue by Wouter12** [mikepenz/MaterialDrawer#2606]
## About this issue

I can't seem to find the functionality to set the email in a ProfileDrawerItem in version 8.0.3.

**Comment by mikepenz** [comment]
There's a extension function for backwards compatiblity: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/interfaces/IProfile.kt#L14

but to unify it was renamed to description:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/interfaces/Describable.kt#L11

**Comment by Wouter12** [comment]
Thanks!
