### ISSUE TITLE
Testing clicking an item in the drawer with espresso integration test

### ISSUE THREAD

**Issue by Wv5twkFEKh54vo4tta9yu7dHa3** [mikepenz/MaterialDrawer#2607]
## About this issue

Hi, I've been trying to figure out how to get espresso to click on the items in the drawer for a bit now, and have only ever found answers about how to open the drawer (which I already managed to do)

so, I'm opening the drawer like so:

```       
onView(withId(R.id.drawer_layout))
            .perform(DrawerActions.open())
```

How do I then click on the first item for example? Thanks in advance for your help, and I hope this isn't too obvious of a question, but I really can't figure it out

If it's relevant, to add the items to the drawer I use `drawer.itemAdapter.add`, then I set `drawer.onDrawerItemClickListener`

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
Nevermind, I was being very daft. Just using withText works fine.

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
Actually, no, I was only partially being daft, how do you click on a profile picture or on the account name/email? After opening the drawer I'm doing `onView(withText("Account")).perform(click())` where Account is the account I set during the test

The matcher doesn't find that text: `No views in hierarchy found matching: with text: is "Account"` (I checked that the text was actually in the account header)

**Comment by mikepenz** [comment]
@Wv5twkFEKh54vo4tta9yu7dHa3 the Drawer is using a `RecyclerView` to display it's contents, so all applies as for recyclerviews. 

Ensure you are scrolled to a location where the view is visible. 
Ensure you are at the right state.

**Comment by mikepenz** [comment]
I hope this helped to resolve the problem you mentioned
