### ISSUE TITLE
Recycler as custom menu item

### ISSUE THREAD

**Issue by MBoberski** [mikepenz/MaterialDrawer#2608]
## Question
I created custom element with recycler view in it. I set on click listeners for my inside recycler items. But it seems that on click inside my recycler are not working. Any tips on that?

## Details
Newest lib version

**Comment by mikepenz** [comment]
This does not necessarily sound like a problem of this library itself. 

One think you have to keep in mind is that the Drawer is a `RecyclerView`  so items are dynamically added / removed during scrolling as the RV does it. 
ensure that your listener is properly attached and removed while scrolling and also ensure you do not leak references

**Comment by mikepenz** [comment]
Were you able to resolve your problem? 

Please report in case additional questions surfaced
