### ISSUE TITLE
Incomplete Tutorial + XML menu inflation

### ISSUE THREAD

**Issue by SharkFourSix** [mikepenz/MaterialDrawer#2610]
## About this issue

I was hoping this would be easy to setup and get going. Instead, I'm now finding myself trying to figure out how to set it up.

I feel like your example isn't complete. I can't get any items to show up.

Also, is it possible to load the items from a menu resource? That would be very convenient.

**Comment by mikepenz** [comment]
Have a look at the sample app there are sample implementations for all sort of different usecase. Including from a menu xml

**Comment by SharkFourSix** [comment]
Ok. Thanks. I'll do that first and will come back

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MenuDrawerActivity.kt

**Comment by mikepenz** [comment]
If you got improvements for the readme we always appreciate prs to enhance things ☺️

**Comment by SharkFourSix** [comment]
I'm have trouble converting this to Javaa equivalent:

```java
slider.apply {
            inflateMenu(R.menu.example_menu)
            onDrawerItemClickListener = { v, drawerItem, position ->
                if (drawerItem is Nameable) {
                    Toast.makeText(this@MenuDrawerActivity, (drawerItem as Nameable).name!!.getText(this@MenuDrawerActivity), Toast.LENGTH_SHORT).show()
                }
                false
            }
            setSavedInstance(savedInstanceState)
        }
```

What is being returned by the apply callback method? And what is the significance of calling apply instead of calling those methods directly? Is it the same as ``post(Runnable)``?

**Comment by mikepenz** [comment]
I'm sorry but the new release is mainly optimized for kotlin. If you want
to use Java I suggest staying with v6.x as outlined in the docs.

You can use the tag from that version to see the sample code at that state.





Regardless I'm highly suggesting to have a look at kotlin of you start a
new app

**Comment by mikepenz** [comment]
For the above java kind of equivalent could be:

```
slider.inflateMenu(R.menu.example_menu)
slider.setOnDrawerItemClickListener(...)
slider.setSavedInstance(savedInstanceState)
```

**Comment by mikepenz** [comment]
I hope you were able to resolve the problem. please comment / reopen if you need additional input
