### ISSUE TITLE
slider.removeAllItems() now needs arguments, why?

### ISSUE THREAD

**Issue by fuentepa** [mikepenz/MaterialDrawer#2612]
Hi Mike

In my app I need rebuild slider items several times. Before, I call 'slider.removeAllItems()' to remove them and after call slider.addItems for the new items.. All was ok, but now (8.0.3) that don`t works.

Can you create a method (without arguments) for this functionality?

Thanks in advance

- materialdrawer:8.0.3
- androidx.appcompat:appcompat:1.1.0
- com.android.tools.build:gradle:4.0.0
- Android Studio 4.0

**Comment by mikepenz** [comment]
The `removeAllItems` is only a small extension wrapper around the adapteR:

https://github.com/mikepenz/MaterialDrawer/blob/659514439e5252238d5093e5b27a6df205b831b8/library/src/main/java/com/mikepenz/materialdrawer/util/MaterialDrawerSliderViewExtensions.kt#L47-L51

You can simple also call

```kotlin
slider.itemAdapter.clear()
```

now :)

**Comment by mikepenz** [comment]
We may want to add back an extension function for this though to ease transition

**Comment by fuentepa** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/2612#issuecomment-636869664

perfect, it solves it

thanks Mike
