### ISSUE TITLE
Use without fitsSystemWindows

### ISSUE THREAD

**Issue by goodibunakov** [mikepenz/MaterialDrawer#2613]
Hi Mike!
Is there any way to use your lib without android:fitsSystemWindows="true"? 
I use one lib for youtube and if set android:fitsSystemWindows="true" videoframe not match parent when fullscreen on. But without fitsSystemWindows drawer looks crazy ))))

So, can you help?

**Comment by mikepenz** [comment]
@goodibunakov have you tried to handle the insets for your video frame by setting it to fitsSystemWindows = false? 

or use something like that to handle insets?
https://gist.github.com/PaeP3nguin/4e41f7e76be452fe2f78d3c534fb8dd1


v8 kind of tries to make full use of the system and just work with the APIs and insets the way they were meant. 

previous v8 we would try to magically handle things which took away too much control from devs

**Comment by goodibunakov** [comment]
If I understood correctly, i can leave fitsSystemWindows="true" for DrawerLayout and put my videoView in InsetFrameLayout in xml?

**Comment by mikepenz** [comment]
so basically the fitsSystemWindow will tell the DrawerLayout that it can handle insets, and via that then the material drawer can handle its insets. 

if you manually handle insets then for your video view that may be already sufficient. but you'd need to try it. 

Also did you. have a look at the "FullscreenDrawer" sample activity? 

It shows how the content can draw behind the statusbar

**Comment by goodibunakov** [comment]
Thanks Mike!

**Comment by mikepenz** [comment]
Please let me know if that helps. if not it would be great if you could create a sample to showcase the problem which makes it easier to assist / fix it :)

**Comment by goodibunakov** [comment]
Well, InsetFrameLayout did not help unfortunately. 
My problem is undestanding of work with insets. 
When i'll find a desition i can write how i did

**Comment by goodibunakov** [comment]
Well, FullscreenDrawer helped. 
I use `rootLayout.updatePadding(top = insets.systemWindowInsetTop)` where rootLayout is RelativeLayout inside DrawerLayout and it works!

**Comment by mikepenz** [comment]
Glad it works :)

**Comment by goodibunakov** [comment]
I'm sorry but... What determines the width of the shadow? How fix shadow shift?
Maybe something like slider.method() in OnApplyWindowInsetsListener?
![изображение](https://user-images.githubusercontent.com/12848175/84792300-e45c0f00-b01d-11ea-871a-70c6a0da965e.png)
I use onConfigurationChanged() and shadow shift after first device rotate.

**Comment by mikepenz** [comment]
Which shadow @goodibunakov ?
Is this reproducible in the sample app?

**Comment by goodibunakov** [comment]
![Untitled-1](https://user-images.githubusercontent.com/12848175/84794468-7b29cb00-b020-11ea-8d1d-080480325081.jpg)
After rotate i have this. I cant find the way to fix it.

**Comment by mikepenz** [comment]
This doesn't seem to happen in the sample. 

Could it be that you have a `fitsSystemWindows` flag somewhere in a not so good position perhaps?

**Comment by goodibunakov** [comment]
Mike, so what determines the width of the shadow? I mean this dark area.

**Comment by mikepenz** [comment]
Looks to me to be the `fitsSystemWindows` flag (from the Android system) which will apply the shadow for the navigation bar.

**Comment by goodibunakov** [comment]
In sample you set fitsSystemWindows = false (FullScreen) but you not use onConfigurationChanged(). 
If i remove android:configChanges from AndroidManifest everything is ok. But i have to use android:configChanges. And... I can't find what and where to do to fix this shadow :(

**Comment by mikepenz** [comment]
Usually those insets come from the system and are handled by it. but as you opt in to handle those manually :/ 

I guess that may results in the fitsSystemWindows true no longer working for the drawer itself. 

does your theme somehow specify a transparent system UI?

**Comment by goodibunakov** [comment]
I have no transparency.
I use youtube-player library. Activity has android:configChanges="orientation|screenSize|keyboardHidden|smallestScreenSize|screenLayout" in manifest. After device rotate player goes to fullscreen it somehow set landscape. When player goes back - orientation again set portrait. And here i have my problem.
fitsSystemWindows is setted for MaterialDrawerSliderView, not for DrawerLayout.
If i set fitsSystemWindows for DrawerLayout, player fill not fullscreen, navigation bar stay.

**Comment by mikepenz** [comment]
this behavior can't be controlled by the view itself. either you want to be drawn behind system bars. that requires the fits system windows flags. or without it, it can't draw behind :( 

I am afraid I don't know a good alternative to it :(
