### ISSUE TITLE
NavigationDrawerItem highlight unexpected behaviour

### ISSUE THREAD

**Issue by Mcgode** [mikepenz/MaterialDrawer#2614]
## About this issue

Hey, first of all, thanks for the work up until now ;)

So, going back to the topic at hand, I've encountered what appears to be a bug of the highlighting of NavigationDrawerItem instances.
When selecting one of these items, the highlighting background does not show (the text itself still gets highlighted) most of the time (for  some reasons it works sometime). 

Here are some screenshots taken directly from the sample app (installed from Google Play):

![Screenshot (4 juin 2020 14 23 49)](https://user-images.githubusercontent.com/8111506/83757750-3e012880-a671-11ea-8e9b-4b561e29838a.png)
![Screenshot (4 juin 2020 14 24 43)](https://user-images.githubusercontent.com/8111506/83757759-3fcaec00-a671-11ea-9136-c6dd13a1066e.png)

Tested on a Google Pixel 3a

## Details

Library version 8.03
Gradle build tools version 4.0.0 
Android Studio version 4.0

**Comment by mikepenz** [comment]
Thanks for the report. I hope the new update fixes the issue you faced.
