### ISSUE TITLE
Item design like Gmail

### ISSUE THREAD

**Issue by goodibunakov** [mikepenz/MaterialDrawer#2616]
![изображение](https://user-images.githubusercontent.com/12848175/84181043-b3765a00-aab2-11ea-9571-dc3c2428a37c.png)
Hi Mike! How i can do something like this?

**Comment by mikepenz** [comment]
the default items look like the items according to the material design guidelines. but with some theming work like adjusting the corner radius and stuff you should be able to achieve the above :)

**Comment by mikepenz** [comment]
It would actually be a great thing for our sample if you'd love to contribute to the project :)

**Comment by goodibunakov** [comment]
Oh, if i find how to do this...  )))

**Comment by mikepenz** [comment]
All magic basically happens here. As you can see we make use of the new MaterialShapeDrawable which allows for shape theming :) 

https://github.com/mikepenz/MaterialDrawer/blob/57b072883ea444b6109d6390aaf24aaf66d9aca9/library/src/main/java/com/mikepenz/materialdrawer/util/DrawerUtils.kt#L354

and we support passing in a custom `shapeAppearanceModel` which get's constructed here:

https://github.com/mikepenz/MaterialDrawer/blob/7d336034ee09e496747314be824251a0cae9379b/library/src/main/java/com/mikepenz/materialdrawer/model/AbstractDrawerItem.kt#L330-L333

So theoretically if you overwrite the `PrimaryDrawerItem` and modify that method (e.g. have a different shape appearance model defined. that should be it and magically work :D

**Comment by mikepenz** [comment]
Ok additionally the insets via `material_drawer_item_background_padding_start_end` have to be adjusted too it looks

**Comment by mikepenz** [comment]
![photo_2020-06-11 19 49 04](https://user-images.githubusercontent.com/1476232/84421975-9e1d3f00-ac1c-11ea-93d4-f4c8ea1b4ec7.jpeg)
![photo_2020-06-11 19 50 59](https://user-images.githubusercontent.com/1476232/84422160-e3417100-ac1c-11ea-8c9b-936973f1d75c.jpeg)


So right now the best approach is to overwrite the `PrimaryDrawerItem` and then define your own getShapeAppearanceModel function. and possibly also define your own way of theming the item. adjusting the dimensions, paddings and such a bit :) 

See the above sample how it's possibly looking like (with dark theme and light theme)

**Comment by mikepenz** [comment]
for the style I used a shape appearance model like this:

```
return ShapeAppearanceModel.builder()
                .setTopRightCorner(CornerFamily.ROUNDED, cornerRadius.toFloat())
                .setBottomRightCorner(CornerFamily.ROUNDED, cornerRadius.toFloat())
                .build()
```

**Comment by mikepenz** [comment]
so the next version will make theming this a bit easier :) also I will have a sample for you to see how it's done

**Comment by goodibunakov** [comment]
Well, we are waiting for v8.1.2? ;)

**Comment by mikepenz** [comment]
Released v8.1.2 for you :) hope it helps

**Comment by goodibunakov** [comment]
Unbelievable! Thanks a lot! )))

**Comment by goodibunakov** [comment]
It works! Great!
I saw example app and i have to use GmailDrawerItem class (its ok) and ids.xml file inside my project?

**Comment by mikepenz** [comment]
Yes :) 

You can use the sample GmailDrawerItem class in your project and the one id which is needed :) 

And having this in your class allows you to finetune it to your exact needs
