### ISSUE TITLE
Hamburger icon on the welcome screen

### ISSUE THREAD

**Issue by Noezis** [mikepenz/MaterialDrawer#262]
hi,

I see that every layout in the sample apps section shows the back arrow in onCreate method.

        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setHomeButtonEnabled(false);

I think that that hamburger icon should be visible in the first screen. For me, the back arrow really messes up the user experience, because how can user know about drawer if it's not opened? Am I right? Is this concept ok with material design guideliness? I can't find any info about this. 

If so, how can I show hamburger icon instead of back arrow in onCreate? I experimented with setHomeButtonEnabled in onCreate, but the back arrow always appeares.

Update:

I was able to achive my goal by this code:

        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        result = new Drawer()
                .withActivity(this)
                .withToolbar(toolbar)
                .withActionBarDrawerToggle(true)
                .withTranslucentStatusBar(false)
                .withDisplayBelowToolbar(false)
                .addDrawerItems(

                )
                .build();

but still I don't really know why all examples show back arrow on first screen

**Comment by mikepenz** [comment]
@Noezis I assume you haven't tried the sample application. There is only one activity which is the parent of all other activities, and this one (the first one) will show the hamburger icon. all other activities show the back arrow because they are second level
