### ISSUE TITLE
Android studio doesn't detect these variables, please define the values in the documentation.

### ISSUE THREAD

**Issue by yashjain27** [mikepenz/MaterialDrawer#2621]
The following result in errors as they are being reported as 'unknown property versions' by Android studio.  How do we define them? 
${lastestMaterialDrawerRelease}
${versions.appcompat}
${versions.recyclerView}
${versions.annotation}
${versions.material}
${versions.constraintLayout}

**Comment by yashjain27** [comment]
For anyone looking for an answer to the same issue I faced. Check this out and add release, setup, and versions block to your buildscript code in the build.gradle:

**Comment by mikepenz** [comment]
it's a common pattern to put placeholders in READMEs as otherwise the version number has to be changed in various places for every single release :) 

Instead I can have a single source of truth in the README which makes it much more accessible :) 

![image](https://user-images.githubusercontent.com/1476232/84624220-42370c80-aee1-11ea-8148-73d902ba8938.png)

**Comment by yashjain27** [comment]
Hey Mike, I am still getting an error for $lastestMaterialDrawerRelease. It is not defined in the gradle dependencies you provided above. And if we hardcore the values, is it '8.1.2' or 'v8.1.2'?

**Comment by mikepenz** [comment]
Its 8.1.2 

You can see all versions here: 

https://bintray.com/beta/#/mikepenz/maven/com.mikepenz:materialdrawer?tab=overview

**Comment by yashjain27** [comment]
> Its 8.1.2
> 
> You can see all versions here:
> 
> https://bintray.com/beta/#/mikepenz/maven/com.mikepenz:materialdrawer?tab=overview

Thanks so much. Although I feel, for beginners, shouldn't you write that in the main documentation? Unless I'm missing something, because I'm having a hard time implementing this slider. And I want to implement it, it looks beautiful

**Comment by mikepenz** [comment]
All versions are listed on the release page too: https://github.com/mikepenz/MaterialDrawer/releases :)

**Comment by yashjain27** [comment]
Sorry to keep disturbing you. Now I'm getting the following error:

Could not find com.mikepenz:materialdrawer-nav:6.1.3.
Required by:
    project :app

Here is my gradle:
`dependencies {
    //Firebase
    implementation 'com.google.firebase:firebase-auth:19.3.1'
    implementation 'com.google.android.gms:play-services-auth:18.0.0'

    //Material Drawer
    implementation 'com.mikepenz:materialdrawer:6.1.3'

    //required support lib modules
    implementation "androidx.appcompat:appcompat:${versions.appcompat}"
    implementation "androidx.recyclerview:recyclerview:${versions.recyclerView}"
    implementation "androidx.annotation:annotation:${versions.annotation}"
    implementation "com.google.android.material:material:${versions.material}"
    implementation "androidx.constraintlayout:constraintlayout:${versions.constraintLayout}"

    // Add for NavController support
    implementation 'com.mikepenz:materialdrawer-nav:6.1.3'

    // Add for Android-Iconics support
    implementation "com.mikepenz:materialdrawer-iconics:6.1.3"

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.core:core-ktx:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.annotation:annotation:1.1.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
`

**Comment by mikepenz** [comment]
You are mixing up things. If you integrate v6.1.x you should also reference the docs at this state.

The nav module only exists in new versions like v8 



v6.1.3 has been a minor update to an old version and is deprecated

**Comment by yashjain27** [comment]
Oh I see. I think I got the gradle correct. We can close this thread.
