### ISSUE TITLE
Deprecated:  PrimaryDrawerItem().withIdentifier(1).withName("One")

### ISSUE THREAD

**Issue by yashjain27** [mikepenz/MaterialDrawer#2622]
Hey Mike,

withIdentifier and withName are deprecated:

<img width="648" alt="Screen Shot 2020-06-15 at 12 39 26 PM" src="https://user-images.githubusercontent.com/17304257/84683472-407f4000-af05-11ea-9c7a-7f42494fb51b.png">

How do we work around this?

**Comment by mikepenz** [comment]
v8 fully embraces Kotlin as such all methods providing a builder pattern have been deprecated. 

Prefer to use apply instead and the properties:

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.kt#L94

```
PrimaryDrawerItem().apply { nameRes = R.string.drawer_item_compact_header; descriptionRes = R.string.drawer_item_compact_header_desc; iconicsIcon = GoogleMaterial.Icon.gmd_brightness_5; isSelectable = false; identifier = 1 },
```
