### ISSUE TITLE
Could not find com.mikepenz:google-material-typeface:x.y.z.

### ISSUE THREAD

**Issue by yashjain27** [mikepenz/MaterialDrawer#2623]
Hey I couldn't find the values for the following:

 implementation 'com.mikepenz:google-material-typeface:x.y.z@aar' //Google Material Icons
 implementation 'com.mikepenz:fontawesome-typeface:x.y.z@aar'     //FontAwesome

**Comment by mikepenz** [comment]
You can find the respective used versions in the sample app at the given tag. 

Or you head to iconics and check out the versions: https://github.com/mikepenz/Android-Iconics#2-choose-your-desired-fonts-v4

Note (As far as I know) you are using an old version of the drawer, so you need to look for versions prior the kotllin refactor. 

So something along v3.2.5 of iconics: https://github.com/mikepenz/Android-Iconics/tree/v3.2.5#2-choose-your-desired-fonts
