### ISSUE TITLE
Status bar is not fully hidden (icons are hidden, status bar is displayed) on Android 11 beta (RPB1.200504.020)

### ISSUE THREAD

**Issue by stepanov-standy** [mikepenz/MaterialDrawer#2625]
## About this issue
I have updated by Pixel 3a from Android 10 to Android 11 beta and the app stops hiding status bar. I don't see status bar icons, but the app reserves space for status bar. Please see a [screenshot](https://drive.google.com/file/d/13z1i_PHvaHR8yzWzXj40bUbi-lLoM5_E/view?usp=sharing)

I tried all possible combinations to hide status bar, but looks like my current configuration is correct from Android stand point. I see such problem on both apps with the Material Drawer. Another app that doesn't have the Material Drawer, but have all the same configurations to hide status bar, works correctly.

I've installed the sample application, but didn't find a way how to hide status bar in it.

## Details
User libraries:
- [ ] Used library version

```
implementation('com.mikepenz:materialdrawer:6.1.2@aar') {
        transitive = true
    }
    implementation 'com.mikepenz:iconics-core:3.2.5'
    implementation 'com.mikepenz:iconics-views:3.2.5'
    implementation 'com.mikepenz:fontawesome-typeface:5.3.1.1@aar'
    implementation 'com.mikepenz:community-material-typeface:3.5.95.1@aar'
    implementation 'com.mikepenz:google-material-typeface:3.0.1.2.original@aar'
    implementation 'com.mikepenz:material-design-iconic-typeface:2.2.0.4@aar'
    implementation 'io.github.inflationx:calligraphy3:3.1.1'
    implementation 'io.github.inflationx:viewpump:2.0.3'

    implementation 'androidx.appcompat:appcompat:1.2.0-alpha01'
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.gridlayout:gridlayout:1.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.percentlayout:percentlayout:1.0.0'
```

- [ ] Used gradle build tools version

classpath 'com.android.tools.build:gradle:4.0.0'

- [ ] Used tooling / Android Studio version

Android Studio 4.0

Here is the code that I use to hide status bar:

```
decorView.setSystemUiVisibility(
                    View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                            | View.SYSTEM_UI_FLAG_FULLSCREEN
                            | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                            | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);
```

drawer builder is:

```
drawerResult = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(initToolbar())
                .withActionBarDrawerToggle(true)
                .withFullscreen(true)
...
```

**Comment by stepanov-standy** [comment]
@mikepenz thank you so much for the quick response. I was wrong and didn't get the point that I can use v8 even in Java project. I will migrate both my projects on v8 within 1 week. I am sure that the issue will be solved after the migration.

**Comment by mikepenz** [comment]
@stepanov-standy v8 works best with kotlin due to many functions being exposed as extension functions. let me know if there is something particular which may cause blockers
