### ISSUE TITLE
Drawer into Bottom Navigation Bar

### ISSUE THREAD

**Issue by biancaarno8** [mikepenz/MaterialDrawer#2626]
## About this issue

Hello, as illustrated in the image that I published, I wanted to ask you if i can move the drawer in the bottom right into bottom navigation view.
In the documentation and in the various issues it is not explained how to do it.
Thanks for the attention.

## Details
- [x ] Used library version : com.mikepenz:materialdrawer:6.0.9
- [x] Used gradle build tools version : 4.0.0
- [x] Used tooling / Android Studio version: 4.0

## Checklist

- [x ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [- ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

Screenshot:
![example_navigation_bar_2](https://user-images.githubusercontent.com/51739571/86116844-60e6f700-bace-11ea-90c9-8d65f991a59d.png)

**Comment by mikepenz** [comment]
@biancaarno8 I see you are still using v6 of the drawer. Note that I only give partial support for that version as it is pretty old. 

The drawer itself is a `DrawerLayout` if you provide a `Toolbar` to it, it will try to hook up a `ActionBarDrawerToggle` for the toolbar, if you drop this though then the showing and closing behavior is up to you.

So in that case you will build the drawer, and then open it via: https://github.com/mikepenz/MaterialDrawer/blob/v6.0.9/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L132 
(and respectively close with the counter part method)

**Comment by biancaarno8** [comment]
Ok thank you very much for your reply.
I will close this issue.
