### ISSUE TITLE
Transparent status bar

### ISSUE THREAD

**Issue by benjdero** [mikepenz/MaterialDrawer#2627]
Hello, sorry to open an issue for this but I think you may help as I couldn't find a solution online.

I've tried to set transparent status bar using:
```xml
<item name="android:statusBarColor">@android:color/transparent</item>
```

It seems to work fine in activities where I have your drawer setup, but in activities without drawer the status bar is light gray, which is the color of my activity's root layout background color. How does the drawer set the color behind the transparent status bar ? Or what do you think could make the Android framework draw behind it ?

**Comment by mikepenz** [comment]
@benjdero which version of the drawer do you use?

**Comment by benjdero** [comment]
@mikepenz I use 6.1.2, haven't got the time to migrate to 8 yet. Btw do you recommend migrating 6->7->8 or 6->8 directly?

**Comment by mikepenz** [comment]
@benjdero I'd highly recommend to migrate to v8 directly. I know it may be more effort than a usual migration, as the approach was changed on how the drawer is set-up but it was a very important step. 

Which also now brings me to your mentioned issue:

- v6 tries to be "magical" and applies activity flags which make the activity to allow drawing behind statusbar and navigation bar. so it will try to find the proper flags and do all sorts of magic to handle it. Which worked for a long time but now...

- v8 -> Brings back full control in your hands. your app "owns" the `DrawerLayout` meaning that now the `MaterialDrawer` can fully embrace the system by having it to simply apply the insets as provided by the window insets. and the draw a behind is simply via the theme + `fitsSystemWindows` behavior. 

------------

I suppose your other activities will need: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/values/themes.xml#L14

**Comment by benjdero** [comment]
I added "statusBarBackground" and it seems to work, the status bar is transparent BUT have a background color, which doesn't make sens to me and have nothing to do with the solutions other people suggested me online, but whatever, enough Android theming for today...

```xml
<style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
    <!-- [...] -->
    <item name="android:statusBarColor">@android:color/transparent</item>
    <item name="statusBarBackground">@color/md_blue_500</item>
</style>

Thank you for your fast answers.

**Comment by mikepenz** [comment]
You are welcome :)
