### ISSUE TITLE
Icon Stroke - Border

### ISSUE THREAD

**Issue by JRaadPro** [mikepenz/MaterialDrawer#2628]
Hello, 
Thank you for this amazing library. 
I wonder if there is a way to remove icon stroke

**Comment by mikepenz** [comment]
do you have a picture of what you mean?

also which version of the lib are you using?

**Comment by JRaadPro** [comment]
I am using the latest version
here is a pic 
![Screenshot_20200708-174120](https://user-images.githubusercontent.com/65556568/86932786-7a2d1a80-c142-11ea-8f80-678fc69f9365.jpg)

**Comment by mikepenz** [comment]
You can adjust the `BezelImageView` style as outlined here: https://github.com/mikepenz/MaterialDrawer#adjust-bezelimageview-style

**Comment by mikepenz** [comment]
I hope you were able to resolve your issue with the provided information.
