### ISSUE TITLE
I am not able to update the values of stickyfooter textview and Imageview.

### ISSUE THREAD

**Issue by jaypalsodha** [mikepenz/MaterialDrawer#2630]
## About this issue

- Briefly describe the issue
   I have created the drawer. In the drawer I have one stickyFooter. Stickyfooter is created with one custom view. the file name is item_drawer_footer.xml.
  Now, initially drawer is created and sticky footer as well. I have created one click listner on that sticky footer. using that I am moving to another activity. Once the new activity task is completed I am moving back to the drawer screen. 
at that time I am not able to update the value of stickyfooter items.

https://codeshare.io/Nc6rK

I have kept neccesary code in the above link. 

- How can the issue be reproduced / sample code

## Details
- [ 6.1.2] Used library version
- [ ] Used support library version
- [ 3.6.3] Used gradle build tools version
- [ 4.0] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@jaypalsodha you can retrieve the parent view of the sticky footer via: https://github.com/mikepenz/MaterialDrawer/blob/v6.1.2/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L369 and that allows you then to find your contents and alter them as you need

**Comment by mikepenz** [comment]
Based on what I see it looks like you want a profile item to be displayed in the footer. e.g. profile image and then some text. 

I'd actually recommend to use a drawerItem as sticky drawer item instead (that's also the only supported way moving beyond v6) 

Showcased here:
https://github.com/mikepenz/MaterialDrawer/commit/77fb1b24bbe223bb5bdae97936cd04da27da3211

![Screenshot_20200718-151951](https://user-images.githubusercontent.com/1476232/87853431-3d171400-c90a-11ea-81df-1491f93d7421.png)


You could also use any custom drawer item for the same.

**Comment by mikepenz** [comment]
Close due to inactivity
