### ISSUE TITLE
How to locate icons in the AppDrawer on the right walls of appdrawer, while text will be located on the left side? Is it possible? And additional question: If it possible, how to change the background color of the single item?

### ISSUE THREAD

**Issue by bulletBane** [mikepenz/MaterialDrawer#2631]
## About this issue

- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by bulletBane** [comment]
Library version 7.0.0

**Comment by mikepenz** [comment]
Please follow the issue template

**Comment by mikepenz** [comment]
Closing as the issue template is not followed
