### ISSUE TITLE
Not able to temporarily disable the drawer

### ISSUE THREAD

**Issue by moylir** [mikepenz/MaterialDrawer#2635]
I've tried to block the behavior of the drawer if some conditions are met.

I just need to avoid that if three lines icon is pressed items are displayed.

No .setEnabled(boolean value) method seems to exist.

I cannot either find something that would make the drawer not to respond to a click on that.

Is this possible somehow? As it's a common thing, I find rare that's not implemented, even if there's no direct setEnabled method, but maybe author hasn't considered this yet.

Thanks for the attention.

**Comment by mikepenz** [comment]
Please use the issue template. 

which version of the drawer do you use? 

Also please note that this is not behavior or part of this library. that's the API of the `DrawerLayout`, please find the documentation here: https://developer.android.com/reference/androidx/drawerlayout/widget/DrawerLayout

**Comment by Mcgode** [comment]
If you need to disable the drawer you can use 
``` kotlin
val slider: MaterialDrawerSliderView

// Disable the drawer, by making it non-accessible and closed
slider.drawerLayout?.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED)

// Re-enable the drawer interaction
slider.drawerLayout?.setDrawerLockMode(DrawerLayout.LOCK_MODE_UNLOCKED)
```

**Comment by mikepenz** [comment]
@Mcgode thanks for the infos there. yes that's the official API to lock a `DrawerLayout` via its API
