### ISSUE TITLE
Plans for version 9?

### ISSUE THREAD

**Issue by connyduck** [mikepenz/MaterialDrawer#2638]
I would be very interested in a version 9 of this library that A) removes all deprecated stuff and B) set the minimum API level to 21 with the goal of making the library more lightweight. I could dedicate some time to help with that.

**Comment by mikepenz** [comment]
@connyduck I would have imagined v9 perhaps already being in compose, but that could also be made to be a v10 :D (would be a nicer version number actually :D) 

beside that there are currently no plans yet, I guess R8 does already a great job in making it very lightweight. 

for a v8.2 having all samples to no longer use deprecated APIs would already be great though

**Comment by NotNotMarshall** [comment]
> I would be very interested in a version 9 of this library that A) removes all deprecated stuff and B) set the minimum API level to 21 with the goal of making the library more lightweight. I could dedicate some time to help with that.

Where I live 70% of people still use devices with API version 14 and 16

**Comment by mikepenz** [comment]
@NotNotMarshall you can always still use older releases of the library which offered support for API 16. 

From a maintenance standpoint those have been extremely stable for a long time now, the new iteration would most likely use compose which will only be API 21+ (https://developer.android.com/jetpack/compose/setup#configure_gradle)

**Comment by COMDroid** [comment]
https://github.com/mikepenz/MaterialDrawer

**Comment by COMDroid** [comment]
https://github.com/wopian/smooth-corners
