### ISSUE TITLE
withOnDrawerItemClickListener return boolean.

### ISSUE THREAD

**Issue by alorma** [mikepenz/MaterialDrawer#264]
If the method `withOnDrawerItemClickListener` returns boolean, it can be used to mark an item as "selected".

Now, when i launch a new activity from drawer, and come back, it remains marked the "new activity" option", and that's not correct.

**Comment by mikepenz** [comment]
@alorma there is a different method which makes a DrawerItem checkable. (the selectionstate) see the sample app this shows how it can be used.

**Comment by alorma** [comment]
No, i know it can be checkable.

It's just about make it selected by default or not

**Comment by mikepenz** [comment]
@alorma making it selected by default? so it's the first selected item?
or you mean it should have the selected state? then set it checked ( or selected ) not sure at the moment

**Comment by alorma** [comment]
Uhmmmm...

When you click on a DrawerItem, it remains selected, that is OK.

But sometimes, i don't want to mark this drawer item as selected, so, i
need to make a trick at onResume() and restore las saved item...

**Comment by mikepenz** [comment]
yeah but if the specific draweritem can't have a select state why don't you use .withChecked(false) ?

**Comment by alorma** [comment]
uhmmm, and this allows me to select it, but not marked as selected?

**Comment by mikepenz** [comment]
there are 2 different method
one that sets it selected and one that prevents it from being automatically checked after click

**Comment by alorma** [comment]
Ok, that's what i need :D

**Comment by mikepenz** [comment]
haha :D 
i was sure that it's just something strange :D 

the thing is that i have no better method names for those functions :/
