### ISSUE TITLE
No interface method withSetSelected(Z)Ljava/lang/Object; in class Lcom/mikepenz/fastadapter/IItem

### ISSUE THREAD

**Issue by kenargo** [mikepenz/MaterialDrawer#2642]
I am using (successfully) the MaterialDrawer library and it's a really good implementation but I have the need to select a subitem and have its action called.  I found [this link](https://github.com/mikepenz/MaterialDrawer/issues/2122) and added the library, everything compiles but when I run the app and call selectItem() I get this exception:

    java.lang.NoSuchMethodError: No interface method withSetSelected(Z)Ljava/lang/Object; in class Lcom/mikepenz/fastadapter/IItem; or its super classes (declaration of 'com.mikepenz.fastadapter.IItem' appears in /data/app/com.certifly.certiflyroof-2/base.apk:classes3.dex)

The subitem works correctly when I expand the drawer and select it by touch and when I used the following it did select the subitem but did not fire the action, which is what lead me to the link above suggesting to use SubItemUtil 
 materialDrawerSliderViewCoreLandingPage.setSelection(IDENTIFIER_NEW_ASSIGNMENT, true)

I have the following in my build.gradle:

`implementation 'com.mikepenz:materialdrawer:8.1.4'`

implementation 'com.mikepenz:fastadapter-extensions:3.1.1@aar'

I also have these but I don't think they are related to the issue:
```
    implementation 'com.mikepenz:materialdrawer-iconics:8.1.3'
    implementation 'com.mikepenz:google-material-typeface:3.0.1.4.original-kotlin@aar'
    implementation 'com.mikepenz:community-material-typeface:5.0.45.1-kotlin@aar'
```

and these are commented out as they don't appear to affect the issue so maybe not needed:
```
    //implementation 'com.mikepenz:fastadapter:3.1.1'
    //implementation 'com.mikepenz:fastadapter-commons:3.1.1@aar'
    //implementation 'com.mikepenz:fastadapter-extensions-expandable:3.1.1'
```

The code for the item in question is:

```
        homeDrawerItem.setSubItems(
            PrimaryDrawerItem().apply {
                identifier = IDENTIFIER_NEW_ASSIGNMENT
                nameText = "Assignments"
                descriptionText = "Create/Assignment"
                level = 2
                iconicsIcon = GoogleMaterial.Icon.gmd_work
                onDrawerItemClickListener = { v, item, position ->
                    openNewAssignmentFragment()
                    true
                }
            }
```

This is what causes the crash:

`SubItemUtil.selectItem(materialDrawerSliderViewCoreLandingPage.adapter, IDENTIFIER_NEW_ASSIGNMENT, true)`

Any help is greatly appreciated.

**Comment by mikepenz** [comment]
v8 requires the latest `FastAdapter` https://github.com/mikepenz/MaterialDrawer/releases/tag/v8.1.4

```
update fastadapter to 5.2.2
```

https://github.com/mikepenz/MaterialDrawer/blob/develop/build.gradle#L26

**Comment by kenargo** [comment]
I figured it was versioning but I couldn't pin it down, thanks.  However I still have a crash (same thing) but I winder if it's because of a change in the design pattern.

I have this in gradle:
    implementation 'com.mikepenz:fastadapter:5.2.2'
    implementation 'com.mikepenz:fastadapter-extensions:3.1.1@aar'

I thought may I needed this:
    implementation 'com.mikepenz:fastadapter:5.2.2'
    implementation "com.mikepenz:fastadapter-extensions-utils:5.2.2"

But in the later case there is no SubItemUtil.selectItem()

Do I need additional libraries or did the design pattern change.

**Comment by mikepenz** [comment]
@kenargo sadly it is not possible to mix versions of the same library as various APIs changed on the way since. (resulting in the issue you see above) 

v5 is a few years newer and its APIs changed since, so there is a high likelihood that old APIs are no longer available, like the one you just mentioned

**Comment by kenargo** [comment]
I have only 5.2.2 
![dependencies](https://user-images.githubusercontent.com/13565496/90223296-a6335f80-ddc2-11ea-92dc-bdd63540c1fe.PNG)

**Comment by kenargo** [comment]
Is there a method to select a subitem and have its action fired?  The setSelection() does select the subitem but it doesn't fire the onClick listener, oddly, if I open another item and then try it, then it does work but until I touch at least one drawer item it never fires.

**Comment by kenargo** [comment]
I have a repro in the sample...

In DrawerActivity, add a click handler (I set it on txtLabel), remember to make the txtLabel "clickable"

```
        txtLabel.setOnClickListener {
            slider.setSelection(2000, true)
        }
```
I added an onClickListener to identifier 2000:

                                SecondaryDrawerItem()
                                        .withName("CollapsableItem")
                                        .withLevel(2)
                                        .withIcon(GoogleMaterial.Icon.gmd_format_bold)
                                        .withIdentifier(2000)
                                        .withOnDrawerItemClickListener { v, item, position ->
                                            Log.d("ASDF", "I've been executed")
                                            true
                                        },

When you run and touch the "Test" initially nothing happens, but if you open the drawer and look at the subitem it has been selected.

Next, close the drawer and touch "Test" again, this time the onClickListener on the sub-Item is fired.

Any ideas how I can get this to work?

**Comment by kenargo** [comment]
After a bit more playing, I found that expanding the parent before calling setSelection() allows onClick to fire, it appear to be tied to visibility of the subitem.

This works in the sample:

`
        txtLabel.setOnClickListener {

            if (!firstExpander.isExpanded) {
                slider.expandableExtension.expand(
                        slider.getPosition(firstExpander), notifyItemChanged = true)
            }

            slider.setSelection(2000, true)
        }
`
It has one side-affect, selecting the other item results in both being highlighted, so maybe this work-around can work well once I research a way to clear all item selections with the exception of the one I'm selecting in the function.

**Comment by mikepenz** [comment]
@kenargo that's correct. child elements are only part of the RecyclerView when they are expanded, otherwise they are only in the list. 

the `MaterialDrawerSliderView` gives you access to the select and expandable extension of the `FastAdapter` 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/widget/MaterialDrawerSliderView.kt#L322-L323

Which give you the power to select, expand, ... and do all sorts of actions with the elements.

**Comment by kenargo** [comment]
This is what I found works (for other's who might be interested):

```
    private fun closeExpander(expander: ExpandableBadgeDrawerItem) {

        if (expander.isExpanded) {
            materialDrawerSliderViewCoreLandingPage.expandableExtension.collapse(
                materialDrawerSliderViewCoreLandingPage.getPosition(expander), notifyItemChanged = true
            )
        }
    }

    override fun selectDrawerItem(value: Long) {

        materialDrawerSliderViewCoreLandingPage.adapter.getSelectExtension().deselect()

        // Make sure everyone is collapsed, technically, only the homeDrawerItem can stay open but if I add similar
        //  functionality to another fragment then I want to be clean
        closeExpander(homeDrawerItem)
        closeExpander(settingsDrawerItem)

        if (!homeDrawerItem.isExpanded) {
            materialDrawerSliderViewCoreLandingPage.expandableExtension.expand(
                materialDrawerSliderViewCoreLandingPage.getPosition(homeDrawerItem), notifyItemChanged = true
            )
        }

        materialDrawerSliderViewCoreLandingPage.setSelection(value, true)
    }

```
