### ISSUE TITLE
tree structure

### ISSUE THREAD

**Issue by mo3tafatayebi** [mikepenz/MaterialDrawer#2645]
is it possible to implement a tree structure? if it is how I can?

**Comment by mikepenz** [comment]
@mo3tafatayebi the `MaterialDrawer` uses the `FastAdapter` underlaying to offer it's RV functionality. 

It is possible to build a list which has expandable and expandables with more expandables. the FastAdapter shows an example for something like this. 

Also there is the sample app from the MaterialDrawer showing how to use expandable items.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.kt#L108-L119
