### ISSUE TITLE
Usage on activities without toolbars

### ISSUE THREAD

**Issue by jackpeters667** [mikepenz/MaterialDrawer#2646]
## About this issue
Suppose I have an activity without a toolbar. Lets say I have an imageview with a hamburger menu icon somewhere in my layout (top left) and I want this to trigger the drawer. How do I go about it?

Is it possible? If so how?

**Comment by mikepenz** [comment]
@jackpeters667 MaterialDrawer provides the `Slider` which is the UI within the `DrawerLayout` it does not do the sliding or anything. 

So you are solely limited by what the `DrawerLayout` offers. 

And for your specific question. the `DrawerLayout` has APIs to open / close programmatically. 

Please see the documentation from google
