### ISSUE TITLE
Opened Drawer

### ISSUE THREAD

**Issue by utya** [mikepenz/MaterialDrawer#2649]
Hello can i use the library in this condition:
when drawer is opened, it does not overlap the buttons in the main view.

**Comment by mikepenz** [comment]
Not sure what you mean by that?

the `MaterialDrawer` provides the UI component which is placed usually within the `DrawerLayout` so everything will behave as it does with `DrawerLayouts` :)

**Comment by utya** [comment]
I don't know hot implements this solution with standart DrawerLayout and trying find the solutions with another library

**Comment by mikepenz** [comment]
The library may be able to achieve what you want, but it may need some more advanced implementation. you can have a look into the sample app to see different possibilities
