### ISSUE TITLE
Open Fragment

### ISSUE THREAD

**Issue by Rafelcf** [mikepenz/MaterialDrawer#2651]
How can I open a fragment directly without going through an activity?
`drawerItem.identifier == 12L -> intent = Intent(this@DrawerActivity, FragmentActivity::class.java)`

why

`var intent: Intent? = null
val drawerFragment = DrawerFragment()
 when {
drawerItem.identifier == 12L ->
supportFragmentManager.beginTransaction().replace(R.id.fragment_container, , drawerFragment).commit()
                    `

**Comment by mikepenz** [comment]
@Rafelcf the library has a listener which allows you to execute any code you want. 

e.g. commit a fragment, ... 

This question seems unrelated to this library
