### ISSUE TITLE
Dynamically load icons from name

### ISSUE THREAD

**Issue by mridah** [mikepenz/MaterialDrawer#2652]
I want to know is it possible to dynamically load the icons from a string that I get from an API.

For example, instead of

     PrimaryDrawerItem().withIcon(GoogleMaterial.Icon.gmd_wb_sunny)

Can I use something like

    PrimaryDrawerItem().withIcon(GoogleMaterial.GetIconByName("gmd_wb_sunny"))

Is this possible @mikepenz

**Comment by mikepenz** [comment]
@mridah yes that's possible :) 

You can do this via: 

```
GoogleMaterial.Icon.valueOf("gmd_wb_sunny")
```

Please note that if you look up something non existing it will throw an exception

**Comment by mridah** [comment]
Thanks for the fast reply !! It's working :)
