### ISSUE TITLE
darwer header little change

### ISSUE THREAD

**Issue by pejmanghorbani** [mikepenz/MaterialDrawer#2653]
is it possible to use some objects( like cars of logged in user)as items of selection view(that contains logged in user emails).
and app is single profile user mode .and by click on selection view the cars of user will be appear and user can select one of them and code its onclick...is it possible??   [stackoverflow ](https://stackoverflow.com/questions/64118061/material-drawer-mikepenz-customize).

**Comment by mikepenz** [comment]
The library does not specify which information you put into a `Profile` you can give a `Profile` any name and description. 

So yes it seems possible

**Comment by pejmanghorbani** [comment]
i can put any information i want into a profile ...but  i want my profile to be itself  but the selection items be his cars...(imagine he  has 3 cars)...i don't want to change the profile by click on one of items(car)....as i know by click on each item it will change the profile image...i want profile image be fix. sorry for my bad english.

**Comment by mikepenz** [comment]
you want the header to only contains a fixed text? but have a list of cars in the profile?

**Comment by pejmanghorbani** [comment]
fix profile...only one logged in profile by user picture and three cars of him in selection view

**Comment by mikepenz** [comment]
I don't think that your usecase is directly supported. 


You can have profiles which are not selectable: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.kt#L72-L73

and you specify a name for the first and second line: 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/widget/AccountHeaderView.kt#L138

**Comment by pejmanghorbani** [comment]
if this links was not ok ,is it ok to make a custom view header?

**Comment by mikepenz** [comment]
If you don't use the `AccountHeader` you will have to manually manage the replacing of items in the drawer with the list of cars when you switch and stuff. it's possible but will require some effort on your side.

**Comment by pejmanghorbani** [comment]
it was the best if you have this on library...any way you are God of drawers.

**Comment by mikepenz** [comment]
You could hardcode line1 and line2 and disable the profile image:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/widget/AccountHeaderView.kt#L181

that could solve the problem for you

**Comment by pejmanghorbani** [comment]
thank you man...i will do it.

**Comment by pejmanghorbani** [comment]
hi mike...i wasn't able to handle my problem... help me in java...i renewed pic of my problem...i cant find your java samples.all in kotlin..https://stackoverflow.com/questions/64118061/material-drawer-mikepenz-customize

**Comment by pejmanghorbani** [comment]
@mikepenz
