### ISSUE TITLE
custom header in performance 

### ISSUE THREAD

**Issue by pejmanghorbani** [mikepenz/MaterialDrawer#2654]
hi mike...i wasn't able to handle my problem... help me in java...i renewed pic of my problem...i cant find your java samples.all in kotlin..https://stackoverflow.com/questions/64118061/material-drawer-mikepenz-customize
is there any one to write it?

**Comment by pejmanghorbani** [comment]
sorry for ask twice...i have not enough knowledge  to make it by my self

**Comment by mikepenz** [comment]
With the latest releases this library is only targeted at kotlin developers. 

There's no support for java. sorry.
