### ISSUE TITLE
dual pane with static drawer

### ISSUE THREAD

**Issue by localhostEU** [mikepenz/MaterialDrawer#266]
Is it possible to use drawer in dual pane mode being one of the panes?

**Comment by mikepenz** [comment]
@localhostEU never tried it. but you should be able to easily check this with the sample project. will take about 5 mins

**Comment by localhostEU** [comment]
@mikepenz thank you!

**Comment by mikepenz** [comment]
@localhostEU can you report back if you tried it? Perhaps adding it to the sample app?

**Comment by localhostEU** [comment]
@mikepenz it works! Will make PR tonight.

**Comment by mikepenz** [comment]
@localhostEU awesome ;) thanks
