### ISSUE TITLE
No Hamburger Menu Icon

### ISSUE THREAD

**Issue by imangelicas** [mikepenz/MaterialDrawer#2664]
## No Hamburger Menu Icon

- When ever i try to add MaterialDrawer to my code everything works as expected but no hamburger icon is displayed 

## Details
    def material_drawer_version = "8.1.7"
    implementation "com.mikepenz:materialdrawer:$material_drawer_version"
    implementation "com.mikepenz:materialdrawer-iconics:$material_drawer_version"
    implementation 'com.mikepenz:fontawesome-typeface:5.9.0.0-kotlin@aar'
    implementation 'com.mikepenz:google-material-typeface:3.0.1.4.original-kotlin@aar'
- [ 1.4 ] Library version
- [ 6.5 ] Gradle build tools version
- [ 4.1 ] Android Studio version 

## Source Code
    class MainActivity : AppCompatActivity() {

    private lateinit var binding: ActivityMainBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

        setSupportActionBar(binding.toolbar)
        supportActionBar?.setDisplayHomeAsUpEnabled(false)
        supportActionBar?.setHomeButtonEnabled(true)

        val item1 = PrimaryDrawerItem().apply {
            identifier = 1
            name = StringHolder("Home")
            iconicsIcon = GoogleMaterial.Icon.gmd_home
        }
        val item2 = PrimaryDrawerItem().apply {
            identifier = 2
            name = StringHolder("Settings")
            iconicsIcon =FontAwesome.Icon.faw_tools
        }
        val item3 = PrimaryDrawerItem().apply {
            identifier = 3
            name = StringHolder("Security")
            iconicsIcon = GoogleMaterial.Icon.gmd_security
        }

        binding.drawer.apply {
            itemAdapter.add(
                item1,
                DividerDrawerItem(),
                item2,
                item3
            )
            setSavedInstance(savedInstanceState)
        }

    }
    }

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [X] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)

**Comment by mikepenz** [comment]
@imangelicas v8 will no longer take over the `ActionBarDrawerToggle` for you. (v7 and before did so) 

v8 gives back all control of those APIs (`ActionBarDrawerToggle` and `DrawerLayout`) to the developer :) 

Please refer to the official `DrawerLayout` and `ActionBarDrawerToggle` documentation if those are causing problems. 

You may also want to have a look in the sample app in which various different scenarios are highlighted:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.kt#L39-L44
