### ISSUE TITLE
Can't disable profile click for MiniDrawer

### ISSUE THREAD

**Issue by karapetyanmery** [mikepenz/MaterialDrawer#2666]
Hi Mike,
After upgrading MaterialDrawer version from `7.0.0` to `8.1.7`, I can't disable profileClick for MiniDrawer anymore. Now `setEnableProfileClick(boolean)` has private access in `MiniDrawerSliderView`, and I haven't found another way to disable it.
Could you please help me with the issue, I really need to disable it in my app.
Thanks in advance.

**Comment by mikepenz** [comment]
I'll add back support for those 2 methods

**Comment by karapetyanmery** [comment]
Thanks a lot
