### ISSUE TITLE
A problem occurred starting process 'command '/.../sdk/build-tools/22.0.1/aapt''

### ISSUE THREAD

**Issue by w821881341** [mikepenz/MaterialDrawer#267]
when I Compile this project,It shows as blow:
>Error:Execution failed for task ':library:processReleaseResources'.
A problem occurred starting process 'command '/home/wei/sdk/build-tools/22.0.1/aapt'

I need some advice , thanks!

**Comment by mikepenz** [comment]
@w821881341 this is not the complete exception. please post more details.

also this is not a MaterialDrawer specific issue ;D

**Comment by adityasiriguppa** [comment]
I am also getting the same error i am creating app using ionic build

svee@Adityas:~/AOE$ cordova build --release android
Running command: /home/svee/AOE/hooks/after_prepare/010_add_platform_class.js /home/svee/AOE
add to body class: platform-android
ANDROID_HOME=/home/svee/AOE/android-sdk-linux
JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseRenderscript UP-TO-DATE
:CordovaLib:generateReleaseResValues UP-TO-DATE
:CordovaLib:generateReleaseResources UP-TO-DATE
:CordovaLib:packageReleaseResources UP-TO-DATE
:CordovaLib:compileReleaseAidl UP-TO-DATE
:CordovaLib:generateReleaseBuildConfig UP-TO-DATE
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets UP-TO-DATE
:CordovaLib:processReleaseManifest UP-TO-DATE
:CordovaLib:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':CordovaLib:processReleaseResources'.
> A problem occurred starting process 'command '/home/svee/AOE/android-sdk-linux/build-tools/23.0.2/aapt''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.111 secs
ERROR building one of the platforms: Error code 1 for command: /home/svee/AOE/platforms/android/gradlew with args: cdvBuildRelease,-b,/home/svee/AOE/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
You may not have the required environment or OS to build this project
Error: Error code 1 for command: /home/svee/AOE/platforms/android/gradlew with args: cdvBuildRelease,-b,/home/svee/AOE/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true

**Comment by mikepenz** [comment]
@adityasiriguppa sorry no support for non Android developemnt. You may find solutions for **cordova** on stackoverflow.
