### ISSUE TITLE
Mixed NavigationDrawerItem and PrimaryDrawerItem and onDrawerItemClickListener

### ISSUE THREAD

**Issue by francescogatto** [mikepenz/MaterialDrawer#2672]
Hi!

I'm having some troubles with `onDrawerItemClickListener` and Navigation Components. It works nice with NavigationDrawerItems, but what if i need to have a callback on a simple PrimaryDrawerItem? 
I tried to use `slider?.onDrawerItemClickListener = { v, drawerItem, position ->` with ` slider.setupWithNavController(findNavController(R.id.nav_host_fragment))` , but the last one disable the first one.

Thanks!

[ ] Used library version 8.1.7
[ ] Used support library version androidx
[ ] Used gradle build tools version
[ ] Used tooling / Android Studio version 4.1

**Comment by francescogatto** [comment]
I found a solution, i changed the method to accept a "FallBack" onDrawerItemClickListener.. like this:
`slider.setupWithNavController(findNavController(R.id.nav_host_fragment), fallBackListener!!)
`

**Comment by mikepenz** [comment]
good idea. would you like to open a PR with this improvement to the project?

**Comment by francescogatto** [comment]
Sure!

**Comment by mikepenz** [comment]
Closing this ticket for inactivity, that being said, we'd still love to improve this behavior.

**Comment by francescogatto** [comment]
Sorry for the late, i'm working on this and soon a pull request!

**Comment by francescogatto** [comment]
@mikepenz  Pull request sent
