### ISSUE TITLE
Header colors and compact style not being applied on 8.1.8

### ISSUE THREAD

**Issue by carlos-mg89** [mikepenz/MaterialDrawer#2674]
- Basically, I'm not managing to customize the color and to apply the compact style for the AccountHeaderView
- I've tried to do so by reading the style section at the README (https://github.com/mikepenz/MaterialDrawer#style-the-drawer).

I've changed the styles.xml with the new Custom style:

```
<style name="SampleApp.DayNight" parent="Theme.MaterialComponents.DayNight.NoActionBar">
        <item name="materialDrawerStyle">@style/Widget.MaterialDrawerStyle</item>
        <item name="materialDrawerHeaderStyle">@style/Widget.MaterialDrawerHeaderStyleCustom</item>
    </style>

    <style name="Widget.MaterialDrawerHeaderStyleCustom" parent="">
        <item name="materialDrawerCompactStyle">true</item>
        <item name="materialDrawerHeaderSelectionText">@color/menuProfileTextColor</item>
        <item name="materialDrawerHeaderSelectionSubtext">@color/menuProfileTextColor</item>
    </style>
```

I've tried as well putting the color directly, but it always appears in black. Aside from this, the compact style as it was being applied in v 6.1.x is not working either. So I believe that the style is just not being applied at all.

Any ideas¿? I know that the SampleApp.DayNight style is working, cause earlier today the DrawerLayout simply crashed while being inflated.

## Details
- [ ] Used library version: 8.1.8
- [ ] Used gradle build tools version: 30.0.2
- [ ] Used tooling / Android Studio version: 4.1

**Comment by mikepenz** [comment]
Sorry for the late answer, but I have not been able to reproduce the issue. things seem to apply correctly if trying to use in the sample app. 

If it won't work for you regardless, may you please build a sample app showcasing the issue allowing me to see what may go on?

![image](https://user-images.githubusercontent.com/1476232/99971176-1f1c5d00-2d9d-11eb-9809-9f06896244f7.png)

themes.xml
```xml
    <style name="SampleApp.DayNight" parent="Theme.MaterialComponents.DayNight.NoActionBar">
        <!-- ...and here we setting appcompat’s color theming attrs -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>

        <item name="materialDrawerStyle">@style/Widget.MaterialDrawerStyleCustom</item>
        <item name="materialDrawerHeaderStyle">@style/Widget.MaterialDrawerHeaderStyleCustom</item>

        <item name="android:windowTranslucentStatus">true</item>

        <!-- CAB :D -->
        <item name="windowActionModeOverlay">true</item>
    </style>
```

styles.xml
```xml
    <style name="Widget.MaterialDrawerStyleCustom" parent="Widget.MaterialDrawerStyle">
        <!-- MaterialDrawer specific values -->
        <item name="materialDrawerBackground">#303030</item>
        <item name="materialDrawerPrimaryText">?android:textColorPrimary</item>
        <item name="materialDrawerSecondaryText">?android:textColorSecondary</item>
        <item name="materialDrawerDividerColor">#1FFFFFFF</item>
        <item name="materialDrawerSelectedBackgroundColor">#1FF1433C</item>
    </style>

    <style name="Widget.MaterialDrawerHeaderStyleCustom" parent="">
        <item name="materialDrawerCompactStyle">false</item>
        <item name="materialDrawerHeaderSelectionText">#FF0000</item>
        <item name="materialDrawerHeaderSelectionSubtext">#FF0000</item>
    </style>
```

**Comment by mikepenz** [comment]
Please let me know if this resolved your problem. 
Closing for now. Please re-open if not solved

**Comment by carlos-mg89** [comment]
@mikepenz thanks for replying. Wasn't the compact style to display horizontally the user profile picture and the name and email?

In the picture you've attached it shows as not Compact Style.

In the one I attach now, which belongs to the previous MaterialDrawer v6, it shows with Compact Style enabled.
![IMG-20201130-WA0001](https://user-images.githubusercontent.com/19690868/100631493-0fb48b00-332c-11eb-99ce-383c924292ae.jpg)

**Comment by mikepenz** [comment]
also works for compact style in the sample with the latest release. 

![photo_2020-11-30 16 53 37](https://user-images.githubusercontent.com/1476232/100631993-9b2e1c00-332c-11eb-8369-cf0d106b78bf.jpeg)


So you are using the legacy v6 release instead?

If that's the case please see the old README: https://github.com/mikepenz/MaterialDrawer/tree/v6.1.3#custom-style---stylesxml

**Comment by carlos-mg89** [comment]
No, I'm not using the v6. I was using it, and that screenshot is from a release that used v6. Now I'm using v8 but I'm unable to apply the compact style there. It's the only missing thing after the whole migration.

Will do as you say, trying with the sample app.

Thanks for the help. I guess there's some tiny thing I'm missing here.

**Comment by mikepenz** [comment]
let me push a branch with what I did. perhaps it highlights what may be going on :/

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/commit/340a2ed3613f646ef7ea1a5dc0d375c608ce4cf8

**Comment by carlos-mg89** [comment]
Oh!!! My bad :disappointed: I was applying the theme into the `DrawerLayout` on my `activity.xml` and not in the `AndroidManifest.xml`.

I haven't really been using themes in Android at all. I use styles for concrete `View`s, not for entire `Activities`. So I'm afraid this was a total ignorance from my side.

Thanks a lot @mikepenz  for pointing out your example. Definitely I should have checked the Sample app.

**Comment by mikepenz** [comment]
@carlos-mg89 oh don't worry :D `themes` and `styles` can be "special" in times for Android.

Also things will be fully different as soon as compose makes it way to prod :D so I think not jumping too deep into it, at this time makes sense :P 

Glad you found the problem though
