### ISSUE TITLE
Very odd - finish an activity, ExpandableDrawerItem(s) don't expand

### ISSUE THREAD

**Issue by kenargo** [mikepenz/MaterialDrawer#2676]
Everything is current, latest version, etc and I search the issues list and while there are things close there is nothing that matches what I'm seeing.

When 1st launched everything works correctly, expandable items work, expand, collapse, etc and root level items work.  In my app most items launch an activity (the app design is similar to Google Play with most screen having a back button).  This all works, the new activity launches and back brings me back to the activity housing the drawer.  Now it gets strange...

Following the finish() from the second activity the drawer opens and closes and all 'root' items, when touched execute their onDrawerItemClickListener.  However, the ExpandableDrawerItem, which I have confirmed are processing their click do not automatically expand.

At first, I thought somehow items where cleared but then accidentally I dragged my finger down the drawer and the ExpandableDrawerItem expanded, it's like the drawer isn't invalidating the ExpandableDrawerItem after returning from the second activity.  For each ExpandableDrawerItem, if I drag down on the drawer after touching the expander, it repaints correctly.

The same behavior for the account header but slight difference, the arrow rotates to indicate the expand state but doesn't expand until I drag down on the drawer but closing the account header works.

Hopefully this makes sense and you can point me to something that I must be missing.

Thanks ahead of time!

**Comment by mikepenz** [comment]
@kenargo could you please create a sample app to showcase and allow to reproduce this issue? you may also modify the sample app from the library to achieve the same wrong behaviour. :)

**Comment by kenargo** [comment]
I was able to chase it down to the 2 commencted0out flags that the app was using for full-screen.

`
    private fun hide() {

        with(window) {
            addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN)
            addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)

            // Information that some of these constants are new as of API 16 (Jelly Bean)
            // and API 19 (KitKat). It is safe to use them, as they are inlined
            // at compile-time and do nothing on earlier devices.
            decorView.systemUiVisibility = (View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                    or View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                    or View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
//                    or View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
//                    or View.SYSTEM_UI_FLAG_FULLSCREEN
                    or View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY)
        }
    }

    override fun onWindowFocusChanged(hasFocus: Boolean) {
        super.onWindowFocusChanged(hasFocus)

        if (hasFocus) {
            hide()
        }
    }`

If either flag is set, returning from an activity launched from an onDrawerItemClickListener results in the ExpandableDrawerItem(s) failing to refresh visually.  They appear to actually expand since a finger drag down the panel shows the new state but visually they are incorrect.

**Comment by mikepenz** [comment]
Honestly it seems odd that those flags would cause this problem for you. could it be that there are some different view hierarchies or so active? and that the wrong things get outlaid / drawn? 

can you please try if you can reproduce it with the sample app / providing a sample app?

**Comment by kenargo** [comment]
Sorry, I guess I was unclear.  Adding the above code into the sample shows the issue.  I added it into the DrawerActivity, they touch any of the panels that launches an activity.  touch back, notice that the "Collapsible Badge" and Collapsible" no longer expand.

Note, the work "collapsible" is misspelled as "collapsable".

**Comment by mikepenz** [comment]
@kenargo can you possibly showcase that in a branch. which activity specifically do you say it needs to be added. doing it in the `DrawerActivity` doesn't seem to result in the described behavior

**Comment by kenargo** [comment]
Android 6.0.1 Samsung Tablet is my test device but it breaks others that I've tested on.

Let me know if you need more information!

At the end of the DrawerActivity.kt, I added the following:


    private fun hide() {

        with(window) {
            addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN)
            addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)

            // Information that some of these constants are new as of API 16 (Jelly Bean)
            // and API 19 (KitKat). It is safe to use them, as they are inlined
            // at compile-time and do nothing on earlier devices.
            decorView.systemUiVisibility = (View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                    or View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                    or View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                    or View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                    or View.SYSTEM_UI_FLAG_FULLSCREEN
                    or View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY)
        }
    }

    override fun onWindowFocusChanged(hasFocus: Boolean) {
        super.onWindowFocusChanged(hasFocus)

        if (hasFocus) {
            hide()
        }
    }

Run the sample app, notice that you can expand the "Collapsible Badge" and "Collapsible" drawer items.

Next, touch and item that launches an activity and then back button, the expandables no longer expand.

Here is a video: https://drive.google.com/file/d/1calQjUZyhwMPpjbaAtXD4oFl45ieiRCs/view?usp=sharing

Here is edited code, only change is as noted above:

https://drive.google.com/file/d/1Me1EdObufI9FIwxBBvOWgniwej9uU4-o/view?usp=sharing

**Comment by mikepenz** [comment]
@kenargo thank you for coming back. 

I've added the code above but fail to be able to reproduce :( 

Tried with 6 different phones from different brands on various API levels but it didn't happen. 

I now also tried emulators for example with API 23 and even API 16 but it won't happen either. 

Really not sure why this may occurs for you. :/

**Comment by kenargo** [comment]
Really, this makes no sense ☹  The video I sent comes from the code I sent.  The flags hide the soft navigation keys in the Tab A.

 

I’m going to take a guess, based on the device it reproduces on…  The only difference I can immediately see between the devices that they issue appears on and not is that the devices showing the issue have hardware nav buttons, the devices having soft nav buttons don’t seam to show the issue.

 

Do you have a device with hardware nav buttons?   

 

Ken

**Comment by mikepenz** [comment]
Sadly I don't have a device with nav buttons. :/ 

But that sounds suspiciously like a system issue to me and less of a problem the library would make. I honestly don't know of any code neither in the FastAdapter nor in the drawer which would specifically make a difference on that.

**Comment by kenargo** [comment]
If you would save me some time learning the code and point me to the file that would process the expand ion touch I’ll see if I can investigate and locate the issue.  Since I know the touches are reaching the root-level drawer, I suspect that something is blocking the click from routing to the code that animates and expands the subordinates.

 

Let me know where to start and I’ll investigate and send a fix if I can find one.

 

Hopefully this can be fixed!

**Comment by mikepenz** [comment]
@kenargo practically the expanding is just a `notifyItemChanged` on the `RecyclerView` hosting the items. 

as the manual animation happens I'd believe some invalidation problem perhaps from the system in the RV may occur :/ but honestly I don't know. 


Also tried with an emulator faking hardware buttons but that seems to haven't done the trick either

**Comment by kenargo** [comment]
OK, for now, it appears to be specific with hardware buttons so I've solved it by detecting if the device has hardware buttons and only using the flags when they are available.

I guess you can close this, the work-around isn't too bad and in testing, so far works well.


```
    private fun hide() {

        hasImmersive(this)

        with(window) {
            addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN)
            addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)

            // Information that some of these constants are new as of API 16 (Jelly Bean)
            // and API 19 (KitKat). It is safe to use them, as they are inlined
            // at compile-time and do nothing on earlier devices.
            var defaultFlags = (View.SYSTEM_UI_FLAG_LAYOUT_STABLE or
                    View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION or
                    View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN or
                    View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY)

            if (hasImmersive) {

                defaultFlags = defaultFlags or
                        View.SYSTEM_UI_FLAG_HIDE_NAVIGATION or
                        View.SYSTEM_UI_FLAG_FULLSCREEN
            }

            decorView.systemUiVisibility = defaultFlags
        }
    }

    private var hasImmersive = false
    private var cached = false

    @SuppressLint("NewApi")
    open fun hasImmersive(ctx: Context): Boolean {

        if (!cached) {

            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.KITKAT) {
                hasImmersive = false
                cached = true
                return false
            }

            val display = (ctx.getSystemService(Context.WINDOW_SERVICE) as WindowManager).defaultDisplay

            val displayMetrics = DisplayMetrics()
            
            display.getRealMetrics(displayMetrics)

            val realHeight = displayMetrics.heightPixels
            val realWidth = displayMetrics.widthPixels

            display.getMetrics(displayMetrics)

            val displayHeight = displayMetrics.heightPixels
            val displayWidth = displayMetrics.widthPixels

            hasImmersive = (realWidth > displayWidth) || (realHeight > displayHeight)

            cached = true
        }

        logInfo("ASDF: hasImmersive = $hasImmersive")

        return hasImmersive
    }
    
    override fun onWindowFocusChanged(hasFocus: Boolean) {
        super.onWindowFocusChanged(hasFocus)

        if (hasFocus) {
            hide()
        }
    }

```

**Comment by mikepenz** [comment]
@kenargo glad you found a workaround. I am still curious though on why this would be like this. 

Honestly I'd be surprised to be any code of the libs themselves being the root cause, but you never know with android :( 

If you find out anything else, feel free to keep on posting here. if there's anything else we could do to patch or such. 

thanks a ton
