### ISSUE TITLE
Migrate to kotlin-parcelize plugin as kotlin-android-extensions is deprecated

### ISSUE THREAD

**Issue by unveloper** [mikepenz/MaterialDrawer#2677]
I cannot build my app because this library depends on kotlin-android-extensions. I'm using Kotlin 1.4.20-RC.

Is possible to release a snapshot in which the library uses 1.4.20-RC and the kotlin-parcelize?

**Comment by mikepenz** [comment]
We'd be happy to take PRs to do the migration :) 

Would absolutely love to give an update which would fix this conflict

**Comment by mikepenz** [comment]
@unveloper btw. I upgraded to 1.4.20 it does seem kotlin-android-extensions are only deprecated, not removed. so nothing should prevent you from building your app

**Comment by unveloper** [comment]
@mikepenz thanks for your support.
The problem was before Kotlin 1.4.20
Kotlin 1.4.20 has released, and fix this issue by simply moving the old runtime to kotlin-android-extensions-runtime, so using current MaterialDrawer version with Kotlin 1.4.20 will be just fine.
