### ISSUE TITLE
Transparent background color while using withCustomView

### ISSUE THREAD

**Issue by topnax** [mikepenz/MaterialDrawer#2685]
Hello,

I need to implement and advanced drawer design and I think i need to use `withCustomView`, where the custom view will contain both header and body of the drawer. However I am not able to set transparent background color of the drawer in order to achieve round corners.

I have set transparent background color to the custom view provided, it's XML definition also has transparent color (`#00000000`) but none of that really work. 

Using `withSliderBackgroundColor` does not work either.

Is there any way to use `customView` with round corners (top right and bottom right)? 

Thank for your work on this awesome library

**Comment by mikepenz** [comment]
@topnax I would suggest to upgrade to the latest version of the `MaterialDrawer` which just provides the containing view for the drawer. 

This gives you full control about the `DrawerLayout`. 

Even more you will be able to provide for example an `OutlineProvider` to the view to give it rounded corners. 
Please note that I do not have control about the `DrawerLayout` which is provided by google. You will have to check if it allows to be transparent


```kotlin
view.outlineProvider = object : ViewOutlineProvider() {
            override fun getOutline(view: View, outline: Outline) {
                outline.setRoundRect(0, 0, view.width, view.height, 12)
            }
        }
```

**Comment by topnax** [comment]
I have solved this issue by providing an `OutlineProvider` to the member `slider` of `MaterialDrawer` without the need to update this framework. The drawer now has round corners and even casts a shadow correctly.

Thanks!
