### ISSUE TITLE
The README file in this repo has quite a few bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [mikepenz/MaterialDrawer#2687]
## About this issue

The markup version of the readme that is displayed for the main page in this repo contains the following bad links:

Status code [404:NotFound] - Link: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=com.mikepenz.unsplash
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=com.alorma.github
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=com.e13engineering.strength
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=com.gabilheri.fithub
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=rebus.smartphone.italia
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=pt.massena.holdemtracker.free
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=br.edu.uea.app
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=com.pixcell8.prod
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=com.game_state.ts3viewer
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=com.tabe3.news
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=com.apps.anker.facepunchdroid
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=indian.fig.whatsaround
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=com.hipcar.android
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=com.taddu.adfree.slidechat
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=com.trackandtalk.pafos17
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=com.antonionicolaspina.sensu
Status code [404:NotFound] - Link: https://play.google.com/store/apps/details?id=com.fa.touch.free

(The link in the readme’s raw markdown may appear in a different relative format to the link above)

## Details
N/A

## Checklist

- [x ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Extra**

Re-check this Repo via: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fmikepenz%2fMaterialDrawer
Check all Repos for this GitHub account: http://githubreadmechecker.com/Home/Search?User=mikepenz

--

Theses bad links were found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback, or log an “Issue”.

**Comment by mikepenz** [comment]
Thanks for the report. We have removed the dead links from the repo
