### ISSUE TITLE
When I select an item and reopen the drawer with sticky Header, spaces appear next to the items

### ISSUE THREAD

**Issue by cristhian-sn** [mikepenz/MaterialDrawer#2689]
## About this issue

- Hi, I am starting a new project, I implement the Drawer with a header using stickyHeaderView. At this point when I start the app I see that a space appears between the header and the first item and also that only when I select an item and reopen the drawer do spaces appear next to the items, as shown in the image.

## Details
- [8.2.0 ] Used library version
- [4.0.1] Used gradle build tools version

![3333315](https://user-images.githubusercontent.com/22756597/101964951-17541980-3be1-11eb-9765-a7e47aab7dbc.png)

![ddddd3](https://user-images.githubusercontent.com/22756597/101964766-7bc2a900-3be0-11eb-97e8-d387832fa1b5.png)

## Checklist

- [X] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [X] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [X] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [X] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@cristhian-sn is this problem reproducible in the sample app?

**Comment by cristhian-sn** [comment]
Yes, I put a sticky header in sample app and..
![cap2](https://user-images.githubusercontent.com/22756597/102133815-b2d4cc80-3e23-11eb-87bd-2cc5c427fdad.png)

**Comment by pCulv** [comment]
I can confirm, I'm facing the same issue, that only happens when the sticky header is used. 
`val headerItem = layoutInflater.inflate(R.layout.nav_header, null)
            drawer.stickyHeaderView = headerItem`

**Comment by cristhian-sn** [comment]
@mikepenz Hi, the 8.3.0 release fixes the problem with the padding top, but I have tried the sample app in this version and the problem with the shadow is still there, maybe it is not appreciated because of the dark theme but it is there. As I mentioned earlier this is only seen when you open and close the drawer. You can better appreciate it with a light theme.

**Comment by mikepenz** [comment]
@cristhian-sn I checked it with light theme actually on a Pixel 5 with Android 11 but didn't see it anymore then :/ 

I could reproduce it first but afterwards it would be fine. Will give it another pair of eyes. :/

**Comment by cristhian-sn** [comment]
@mikepenz  Maybe the android version :d ? I have seen it in android 9 and 10. I will check it in android 11 ..

**Comment by cristhian-sn** [comment]
@mikepenz  I test it on an emulator with android 11 and the shadow keeps appearing :(
![Screenshot_1608310747d](https://user-images.githubusercontent.com/22756597/102640784-02b7da00-4129-11eb-8051-485036276984.png)

**Comment by mikepenz** [comment]
well must have been lucky then :D will give it another look. :D
