### ISSUE TITLE
Close one ExpandableDrawerItem if another is opened

### ISSUE THREAD

**Issue by PembaTamang** [mikepenz/MaterialDrawer#2698]
I am using the latest version 8.3.1
I am using a bunch of EDI's if I expand multiple items they all stay opened.
Is there a way to close the last expanded menu if I open the next one?

**Comment by mikepenz** [comment]
The `ExpandableExtension` allows to configure of only allowing a single expanded item:
https://github.com/mikepenz/FastAdapter/blob/develop/library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.kt#L100

**Comment by PembaTamang** [comment]
thanks a lot for this wonderful library
