### ISSUE TITLE
setBackgorundColor making the drawer transparent

### ISSUE THREAD

**Issue by PembaTamang** [mikepenz/MaterialDrawer#2699]
I am using the latest version 8.3.1
When I use setBackgroundColor the drawer becomes transparent

```
 slider = slider_id
 slider.setBackgroundColor(android.R.color.white)
```

![image](https://user-images.githubusercontent.com/32651212/103164328-d8a09f00-482f-11eb-9f28-d59f16293343.png)

**Comment by PembaTamang** [comment]
also cannot set the hamburger menu icon color

**Comment by mikepenz** [comment]
the hamburger (`ActionBarDrawerToggle`) is not part of this library, please refer to its official documentation. 

You are using the wrong method. the method you use to update the background is taking an `ColorInt` not a ressource.

Also this is not part of this library but official `View` API

![image](https://user-images.githubusercontent.com/1476232/103201928-6f816000-48f1-11eb-8285-423f16057c46.png)
