### ISSUE TITLE
Can't set Profile typeface when using Calligraphy

### ISSUE THREAD

**Issue by guilhermearaujo** [mikepenz/MaterialDrawer#270]
I started using [Calligraphy](https://github.com/chrisjenx/Calligraphy) in my app, and I notice that I am able to set a default font using Calligraphy and then replace each Drawer item's font with another one.

But looks like the AccountHeader font's remains unchanged (i.e. using the default one set using Calligraphy).

**Comment by mikepenz** [comment]
@guilhermearaujo Calligraphy also has some more side effects. i think it will prevent you from using the Android-Iconics functionality. (haven't tested it yet but yeah i am afraid this can cause issues)

about the font not changed. so it will stay on the default android font?

**Comment by guilhermearaujo** [comment]
It will stay the font I set as default using Calligraphy.

**Comment by mikepenz** [comment]
@guilhermearaujo i assume this happens because the items inside the Drawer are a list and the elements in the AccountHeader are "static" (wrong word but yeah) items inside a view

**Comment by guilhermearaujo** [comment]
Ok, it won't be a big matter to me, I just wanted to register that this is how it's behaving as of today.

**Comment by mikepenz** [comment]
@guilhermearaujo great. thanks.
