### ISSUE TITLE
Navigation graph with the mini drawer?

### ISSUE THREAD

**Issue by rehabMohamed** [mikepenz/MaterialDrawer#2701]
Hello,
I am using the mini drawer with 10 items, each one should open a fragment on selection. Can I use the navigation graph to handle the fragment transitions? 
Also, can I use the menu to populate the items to the drawer?

Used library version : 8.3.1

**Comment by mikepenz** [comment]
@rehabMohamed you can use the menu to fill a normal slider: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MenuDrawerActivity.kt#L32

if mini and normal drawer are connected, it should theoretically also work for the mini drawer. 
As you see in this sample: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.kt we also only provide the items to the main slider

----

Navigation is a bit more complicated. so direct nav graph support is not given, as it requires `NavigationDrawerItem` which are not handled by the mini drawer. 

what you can do though is to hook up the listener and according to the clicked item navigate to whatever screen / fragment you need using the navController

**Comment by rehabMohamed** [comment]
Thanks a lot. Both worked!
