### ISSUE TITLE
Diable nav drawer swipe?

### ISSUE THREAD

**Issue by aeroperf** [mikepenz/MaterialDrawer#271]
Is there a way to disable swiping out of the drawer? I have left and right drawers implemented, but want to disable swiping out of the right drawer and force a button action instead. Possible?

**Comment by mikepenz** [comment]
@aeroperf as the MaterialDrawer uses the normal DrawerLayout everything which is possible with the DrawerLayout can be done. I'm not sure but i think there's an option which allows you to lock a specific slider by it's gravity

**Comment by aeroperf** [comment]
Ok, thanks. Looks like this might be possible (will try it out later):
http://stackoverflow.com/questions/17901504/navigation-drawer-disable-swipe

**Comment by mikepenz** [comment]
@aeroperf yes this was the thing i was referring to :D just get the drawer.result from the first drawer you build and then get the drawrLayout from it

**Comment by anand-agrawalglobant** [comment]
Is their any way that i can open the drawer only when swipe in left panel.I am using the viewpager in right panel.When i swipe the viewPager the drawer opens/close.I want open the drawer only when i swipe from left to right on area as shown in attached image.
![screenshots2](https://cloud.githubusercontent.com/assets/16498823/15572382/e0c5d926-235d-11e6-9a9c-15490af5dfc8.jpg)

**Comment by aligholamee** [comment]
:) bilakh

**Comment by Omid-naji** [comment]
چرا ؟

Sent from Mail for Windows 10
