### ISSUE TITLE
README.md does not reflect current library

### ISSUE THREAD

**Issue by clydebarrow** [mikepenz/MaterialDrawer#2710]
## About this issue

- The README.md suggests using this pattern to construct drawer items:
````
val item1 = PrimaryDrawerItem().withIdentifier(1).withName(R.string.drawer_item_home)
````
But this produces deprecation messages. I saw nothing in the Migration Guide to help. The sample app does have the newer syntax. Either the README.md should be updated with the current syntax, or suggestions there should be removed.

## Details

- [x] Used library version - 8.1.3
- [x] Used support library version - using AndroidX
- [x] Used gradle build tools version 4.0.2

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thank you so much for the @clydebarrow ticket. updated the README to also reflect the new syntax
