### ISSUE TITLE
DrawerImageLoader not running set function

### ISSUE THREAD

**Issue by wakaztahir** [mikepenz/MaterialDrawer#2715]
## About this issue

-  I initialized the DrawerImageLoader like this
```
-         DrawerImageLoader.init(object : AbstractDrawerImageLoader() {
            override fun set(imageView: ImageView, uri: Uri, placeholder: Drawable, tag: String?) {
                Log.d("RUNNINGDDDDDD","III")
                Glide.with(context).load(account?.photoUrl).placeholder(placeholder).into(imageView)
            }
        })
```

I placed a Log call inside the set function and it just does't call , I have a profile item like this 
```
addProfiles(
                ProfileDrawerItem().apply {
                    nameText = accountName
                    descriptionText = accountEmail
                    badgeStyle = BadgeStyle().apply {
                        textColor = ColorHolder.fromColor(Color.BLACK)
                        color = ColorHolder.fromColorRes(R.color.primaryColor)
                    }
                },
                ProfileSettingDrawerItem().apply {
                    name = StringHolder("Manage Account")
                    description = StringHolder("Manage Timeline Account")
                    icon = ImageHolder(
                        IconicsDrawable(
                            context,
                            CommunityMaterial.Icon.cmd_account_cog_outline
                        )
                    )
                    identifier = 100001
                }
            )
```

## Details
- [ 8.3.3] Used library version
- [No] Used support library version
- [no idea] Used gradle build tools version
- [4.2 beta 6] Used tooling / Android Studio version
- [no other] Other used libraries, potential conflicting libraries

## Checklist

- [yes] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [yes] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [yes] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [yes] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [yes] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [no] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by wakaztahir** [comment]
I have also put the loader in the onCreate function before the content view is even set but that did't work , Glide is loading the image fine in other places but the set function is just not being called

**Comment by mikepenz** [comment]
@wakaztahir the imageloader should be set in the application to ensure it happened before the drawer is used. beyond that. your sample does not look like setting a `url` as icon. it will only call the loader when it is needed (e.g. when you specify the url drawable to the item)

**Comment by wakaztahir** [comment]
I don't have an application class but I set the initLoader before setContentView

**Comment by wakaztahir** [comment]
Thanks , as soon as I specified a url , it started working but the image is still displaying squared !
Do you have any idea how to make it circular and make it fit , Otherwise thanks for help

**Comment by mikepenz** [comment]
@wakaztahir usually image loaders provide APIs which allow you to transform the image to the needed form. e.g. ciruclar. 

Beyond this. the `ProfileDrawerItem` uses a `BezelImageView` and applies the style as defined in the theme
https://github.com/mikepenz/MaterialDrawer/blob/develop/materialdrawer/src/main/res/layout/material_drawer_item_profile.xml#L16

**Comment by wakaztahir** [comment]
Thanks I used 
`Glide.with(context).load(account?.photoUrl).placeholder(placeholder).circleCrop().into(imageView)`
which did it !
