### ISSUE TITLE
Question - Custom menu items?

### ISSUE THREAD

**Issue by Anatidae-Project** [mikepenz/MaterialDrawer#272]
Does your lib support custom menu items? Like I have a client who wants a menu item that doesn't open a new activity, but rather has a row of toggle states. 

While I am asking, they also want a custom logo locked up top where an account picture would be.... Any chance for custom header views too? I know I can add to the repo, but just wondering if any of this is already in place.

**Comment by mikepenz** [comment]
@Anatidae-Project you can have any custom menu items you want. just implement the IDraewrItem interface and then it can be used. there is nothing like an expandable drawerItem if you mean something like this.

you can place any custom view on top of the drawer

**Comment by Anatidae-Project** [comment]
Really loving your work. 
On a previous job, I used this:
https://github.com/neokree/MaterialNavigationDrawer

There are some cool build-ins, but once you need to customize...

I got my custom menu items going. I do have a follow up. Do you have a good example on setting up a sticky footer with menu items in it? I see how to inject my own view, which is fine - but I'm wondering if you had a pattern in mind for adding setting menu items in a stick below and how it interacts with the main menu list?

**Comment by mikepenz** [comment]
@Anatidae-Project yeah a very important thing in my drawer was to first be 100% Android Design Guidelines conform which is no other drawer library as far as i know. 
The second thing was to be as easy to use as possible. And the third to be as flexible as possible to allow everything (or at least a lot of stuff :D)

About the sticky thing :D everything built in ;) Just check out the `ComplexHeaderActivity` -> https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/ComplexHeaderDrawerActivity.java#L115
You add the stickyFooterItems as normal drawerItems with an extra call and everything is working as the other stuff :D
