### ISSUE TITLE
Disable badge for profile image

### ISSUE THREAD

**Issue by artbristol** [mikepenz/MaterialDrawer#2726]
## About this issue

We would like to use the badge for displaying an unread count in K-9, but we don't want to show the badge on the profile image. Is this possible, or can it be added as a feature?

(It looks like previously it wasn't show there https://github.com/mikepenz/MaterialDrawer/issues/1914 ; is this behaviour configurable?)

Some discussion on https://github.com/k9mail/k-9/pull/5289

## Details
MaterialDrawer com.mikepenz:materialdrawer:8.4.0

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Hi @artbristol without looking at things, I believe it's currently not possible. Happy to improve upon that. 
Not sure when I will have time to look into this (with a bit of luck maybe today, otherwise it may take a few days as I am currently super busy)

**Comment by mikepenz** [comment]
Ok added the flag. will be in v8.4.1

**Comment by artbristol** [comment]
Wow thanks for the speedy turnaround!
