### ISSUE TITLE
migration guide 

### ISSUE THREAD

**Issue by AzamudinUMCH** [mikepenz/MaterialDrawer#2730]
## About this issue

- Briefly describe the issue
- How can the issue be reproduced / sample code

I'm trying to upgrade from 6.0.8 to latest version which are 8.x.x. After i upgrade, the app cannot find few import which are 
-import com.mikepenz.materialdrawer.AccountHeader;
-import com.mikepenz.materialdrawer.AccountHeaderBuilder;
-import com.mikepenz.materialdrawer.Drawer;
-import com.mikepenz.materialdrawer.DrawerBuilder;

currently my **static Drawer drawer** cannot import from this **import com.mikepenz.materialdrawer.Drawer;**

Can you guild me how to do this migration as I already read the migration guide documentation but was not success.

**Comment by mikepenz** [comment]
Please have a look at the README with code on how to define the drawer, the sample showcasing different example implementations and the migration docs: https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md 


None of those above listed classes exist anymore, as they were replaced by a different approach. 

The drawer is now set up via XML and won't auto inflate anymore, as this gives much more flexibility https://github.com/mikepenz/MaterialDrawer#2-add-the-drawer-into-the-xml

**Comment by AzamudinUMCH** [comment]
Is there any version after 6.0.8 still using that class?

**Comment by mikepenz** [comment]
v7 was upgraded to be kotlin first. 
v8 got completely refactored.
