### ISSUE TITLE
Get Drawer Item as a View

### ISSUE THREAD

**Issue by shivamsoods** [mikepenz/MaterialDrawer#2739]
## About this issue
Hey I would like to get the drawer item as view instead of IDrawerItem. I have implemented a tap-intro-library and it needs a view to process.
I have tried to get the view by accessing the drawer recycler view but that doesn't differentiate between different items.

Is there any other way to use the drawer items with the given library?

## Details
- [ 8.4.1] Used library version
- [ v4:1.0.0] Used support library version
- [ 4.2.2] Used gradle build tools version
- [ 4.2.1] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries
Tap Target View [https://github.com/KeepSafe/TapTargetView](link) 
implementation 'com.getkeepsafe.taptargetview:taptargetview:1.13.3'

**Comment by mikepenz** [comment]
@shivamsoods the `Drawer` uses an `RecyclerView` to display the elements. as such list items are re-used and you can not directly reference the view as it may run out of view. 

If you really need to get the view, you could scroll to the view in the RV, and then get the view based on its position. 

This is unrelated to this library though, and more related to `RecyclerView`s and view recycling.

**Comment by shivamsoods** [comment]
Okay. I tried that and selected that view which was visible but the view is not being properly bounded in the tap intro library. The item selected in the intro view is the entire drawer (recycler view).

Thank you so much. Will look more into it and try to figure out from where is this issue arising-> Tap Intro View or from recycler view's item.
