### ISSUE TITLE
Save selected Item

### ISSUE THREAD

**Issue by T0h6BY** [mikepenz/MaterialDrawer#274]
Hi.
Can you help me.
My steps:
1. I open menu and see selected item (first item in menu)
2. I select menu item and open new activity (etc. About activity)
3. I open menu but now selected first item in menu (etc. Home activity)
I need, when i open menu in About activity - i see selected item (About) in menu.
Thanks

**Comment by mikepenz** [comment]
@T0h6BY not sure what you are doing but i assume that you have setted withCheckable(false) this will prevent the auto selection of this item
