### ISSUE TITLE
Superflous status bar inset in targetSdkVersion 30+

### ISSUE THREAD

**Issue by Nohus** [mikepenz/MaterialDrawer#2741]
## About this issue

Here is how my drawer should look like, and looked like so far:
![image](https://user-images.githubusercontent.com/11064768/128646433-46e568b4-515f-40fb-b4ff-7661ace97bab.png)

After changing my `targetSdkVersion` from 29 to 30, this extra inset appears at the top:
![image](https://user-images.githubusercontent.com/11064768/128646228-54a0516f-762f-4922-9e54-b9786d1dd176.png)

I suspect it's there to prevent this:
![image](https://user-images.githubusercontent.com/11064768/128646543-fbfab6b3-d601-4000-8cc6-7742f50f0f99.png)

Instead turning it into this:
![image](https://user-images.githubusercontent.com/11064768/128646589-5c7789fc-6f3f-4ff2-9cef-0635aefb5e53.png)

This makes sense for normal items, but not in my case with a header. And of course I didn't expect my layout to change due to a `targetSdkVersion` update. It was working fine for a long time.

## Details

- [x] Used library version: `8.4.2`
- [x] Used support library version: `appcompat 1.3.0`
- [x] Used gradle build tools version: `7.0.2`
- [x] Used tooling / Android Studio version: `Arctic Fox 2020.3.1`
- [x] Other used libraries, potential conflicting libraries: `-`

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md) (**Although relevant questions are dead links**)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
This inset is not directly controlled by the library, but comes from the system. 

The library has built in window inset handling, it's important to make sure the `DrawerLayout` is allowed to properly handle its insets for it to work. 

Please have a look at the sample app, which also has an account header with a background image

**Comment by Nohus** [comment]
I tried reproducing this in the sample app. `AccountHeaderView` was displaying correctly, however I can't just use the account header because I don't use it for accounts and it's not possible to customize it enough so it looks like the layout I need. My header was a simple subclass of `AbstractDrawerItem` and added in the same as any other item. It still has the issue when added to the drawer in the sample app:
![image](https://user-images.githubusercontent.com/11064768/128741413-ae5b8061-fef0-46d5-988b-c3024b07f21a.png)

I found the solution is to not use the `DrawerItem` system, and instead instantiate my `View` myself and set it to `MaterialDrawerSliderView.headerView`. Then it displays correctly. I didn't find this documented, all examples I see just use the `AccountHeaderView`. But I wasn't able to confirm, the [library's website](https://mikepenz.github.io/MaterialDrawer) is just displaying a 404 now.

This doesn't really answer why the problem happened though. If this is the correct way, why was it working in `targetSdkVersion < 30`, and why did it stop in `30`? I looked through the [behavior changes in Android 11](https://developer.android.com/about/versions/11/behavior-changes-11) and nothing seems relevant. Although I found a solution for my use case, it doesn't answer what happened here. Feel free to close the issue if you don't think it's worth investigating though; my issue is solved.

**Comment by mikepenz** [comment]
As you noted, the normal `DrawerItem`s will not draw behind the `StatusBar` as this is usually not anticipated. Only the `AccountHeader` or `HeaderView` will go behind. 

More advanced features like this are mainly highlighted either in the sample or can be seen by looking through the source. 

There has been some changes to the insets handling in newer android versions, and I believe updating to target 30 may be triggering such. 

Btw. the `AccountHeader` can be modified to not have any accounts and may only consist of 2 lines of text and the background.
