### ISSUE TITLE
Can you give more documentation or examples? 

### ISSUE THREAD

**Issue by picaro** [mikepenz/MaterialDrawer#2742]
## About this issue

The project is great, but it's missing documentation on it.

Migration from 7 to 8 becomes tough in so many ways. 
There is no good documentation or examples. I could open several questions on StackOverflow, 
but it's not so useful for other users.

Sample problems 
- How to add a toolbar?  
- How to add a template for the header like it was in v7?
- How to modify header image sizes, fonts etc.
- How to turn on scroll for the menu elements?
also in my case setOnDrawerItemClickListener never called, but I think it's not so common issue.

## Details
- [ ] Used library version - 8.4.2
- [ ] Used support library version 8.4.2
- [ ] Used gradle build tools version 4.0.0
- [ ] Used tooling / Android Studio version 2020.3.1
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thank you very much. 

The main reason to not expose significant amounts of migration between v7 to v8 is, as v8 is a complete rewrite, and the best approach to it is to start newly. As major concepts of the library changed, including removal of for example `DrawerLayout` handling. 

the `MaterialDrawer` v8 is solely the UI within a `DrawerLayout` it won't control the `DrawerLayout` or any UI around anymore though. This gives much more flexibility and freedom to the developers. 


Related to the noted problems:
- `Toolbar` is not related or handled by this library, please see official docs
- May you elaborate more on the `template` you refer to?
- Please refer to the README and the styles section to modify colors, font is not handled by the library, if you apply an application wide font it should apply, sizes are in accordance to the material spec and are not recommended to be changed
- Could you please elaborate more on "turn on scroll for the menu elements"?
