### ISSUE TITLE
textColorRes and descriptionTextColorRes aren't work correctly

### ISSUE THREAD

**Issue by CheK539** [mikepenz/MaterialDrawer#2744]
## About this issue

Hi, I am trying to create a PrimaryDrawerItem with color changing textColor and desctiptionTextColor using textColorRes and desctiptionTextColorRes, but it doesn't work as I expected. Instead of changing the textColor, the selectedColor is changed.
Note that changing the textColor field manually works correctly.
Then I went through the source code and saw that textColorRes and descriptionTextColorRes are a SelectableColor extension instead of a NameableColor in NameableColor.kt:
```
var SelectableColor.textColorRes: Int
    @Deprecated(level = DeprecationLevel.ERROR, message = "Not readable")
    get() = throw UnsupportedOperationException("Please use the direct property")
    set(@ColorRes value) {
        selectedColor = ColorHolder.fromColorRes(value)
}
```

Sample code for this: 
```
binding.slider.addItems(
    PrimaryDrawerItem().apply {
        nameText = "Test item"
        descriptionText = "Test description"
        textColorRes = R.color.teal_700
        descriptionTextColorRes = R.color.teal_200
    }
)
```
![image](https://user-images.githubusercontent.com/54955855/131385694-fb38a19c-9bf9-4a40-8fca-db6acf3f0469.png)

![image](https://user-images.githubusercontent.com/54955855/131385593-8a0ce3cc-8634-4efc-bc18-8460a2f781a3.png)

## Details
- [ ] Used library version - 8.4.2
- [ ] Used support library version - 8.4.2
- [ ] Used gradle build tools version - 7.0.0
- [ ] Used tooling / Android Studio version - 2020.3.1
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@CheK539 thank you very much for the detailed report. Looking into it.

**Comment by davidhowe** [comment]
@mikepenz FYI This issue seems to also be present for _ProfileDrawerItem_

**Comment by mikepenz** [comment]
@davidhowe it should be the same extension function. due to it not having access to the context, the `res` variant is no-op and it's suggested to use `textColor` directly
