### ISSUE TITLE
Selected Icon color not working

### ISSUE THREAD

**Issue by raghunandankavi2010** [mikepenz/MaterialDrawer#275]
I have a icon from google io schedule ic_drawer_my_schedule. The accent color is not set to the icon in the navigation drawer for the item selected.

The icon is from the xxhdpi folder google io schedule app. The text color works. Is this something to do with the icon or something related to setting color? .

Note : Works well with the FontAwesome icons and google material icons. 

     new PrimaryDrawerItem().withName("Schedule").withIcon(R.drawable.ic_drawer_my_schedule).withIdentifier(4).withCheckable(true).withTintSelectedIcon(true).withSelectedIconColor(R.color.color_accent)

**Comment by mikepenz** [comment]
@raghunandankavi2010 i have changed something with the newest release. i hope this fixes your issue

**Comment by raghunandankavi2010** [comment]
@mikepenz thanks will try it.

**Comment by mikepenz** [comment]
@raghunandankavi2010 great ;)
