### ISSUE TITLE
Material Drawer review

### ISSUE THREAD

**Issue by Java-Help** [mikepenz/MaterialDrawer#276]
Hi Mike. You can insert a link to a review of your library (MaterialDrawer) in readme.md?

**Comment by mikepenz** [comment]
@Java-Help first send me the link to the review ;)

**Comment by Java-Help** [comment]
Of course , here it http://java-help.ru/material-navigationdrawer/. A review in Russian language and is intended for Russian-speaking users.

**Comment by mikepenz** [comment]
@Java-Help very detailed ;).

**Comment by mikepenz** [comment]
@Java-Help added ;)

**Comment by Java-Help** [comment]
Thank you

**Comment by mikepenz** [comment]
@Java-Help no problem ;).
