### ISSUE TITLE
OnclickListener for multiple views

### ISSUE THREAD

**Issue by haamedheidari** [mikepenz/MaterialDrawer#2766]
Hi I implemented a CustomDrawer item by extending AbstractDrawerItem
How can I set a click listener for each view inside my customDrawer?

**Comment by mikepenz** [comment]
You could do something like this: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/OverflowMenuDrawerItem.kt#L65

Or similar like done here: https://github.com/mikepenz/MaterialDrawer/blob/develop/materialdrawer/src/main/java/com/mikepenz/materialdrawer/model/AbstractSwitchableDrawerItem.kt

**Comment by mikepenz** [comment]
Or you could do something like this using FastAdapter APIs:
https://github.com/mikepenz/FastAdapter/blob/70b1380b6e888b9fbfb6bb4357295892ffb1d8a5/app/src/main/java/com/mikepenz/fastadapter/app/ImageListActivity.kt#L65

https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/items/ImageItem.kt#L157-L173
