### ISSUE TITLE
Unable to fully reset the MaterialDrawerSliderView (account header remains)

### ISSUE THREAD

**Issue by carlos-mg89** [mikepenz/MaterialDrawer#2776]
## About this issue

Hi everyone!

I'm trying to fully reset the `MaterialDrawerSliderView` by rebuilding it (after certain user events). The view is almost fully rebuilt, except the `AccountHeaderView` (which I only create if there's an active profile == user logged in).

Basically, this is the whole process.

**1. Scenario with active profile**
  * Account header set
  * Common items are added
  * A "Log out" item is added

**2. Scenario without active profile**
  * Account header IS NOT set
  * Common items are added
  * A "Log in" item is added

This is my code to build the slider:

```
private fun build() {
        slider.accountHeader = getAccountHeaderView()
        addNavigationDrawerItems()

        slider.onDrawerItemClickListener = { _, drawerItem, _ ->
            processNavigationDrawerOnClick(drawerItem.identifier.toInt())
            false
        }
        getDrawerLayout()?.closeDrawers()
    }

private fun getAccountHeaderView(): AccountHeaderView? {
        return if (user != null) {
            val accountHeaderView = AccountHeaderView(activity)
            val profileDrawable = ContextCompat.getDrawable(activity, R.drawable.profile)
            profileDrawable?.colorFilter = android.graphics.PorterDuffColorFilter(
                ContextCompat.getColor(activity, R.color.menuProfileTextColor),
                PorterDuff.Mode.SRC_IN
            )
            accountHeaderView.addProfiles(
                ProfileDrawerItem().apply {
                    iconDrawable = profileDrawable
                    name = StringHolder(user?.name)
                    description = StringHolder(user?.email)
                }
            )
            accountHeaderView.headerBackground = ImageHolder(R.color.menuProfileBackgroundColor)
            accountHeaderView.onAccountHeaderListener = { _, _, _ -> showAccountSettingsActivity() }

            return accountHeaderView
        } else {
            null
        }
    }
```

And the code to reset the slider:

```
private fun reset() {
        slider.accountHeader?.activeProfile?.let {
            slider.accountHeader?.removeProfile(it)
            slider.accountHeader?.clear()
            slider.accountHeader?.updateHeaderAndList()
            slider.accountHeader = null
        }
        slider.removeAllItems()
        slider.resetDrawerContent()
        build()
    }
```

If you go from scenario 2, and login, then the account header is properly set, with the active profile information.

However, if you are in the scenario 1, and log out, the account header gets the profile removed, but the background remains there.

![image](https://user-images.githubusercontent.com/19690868/164481901-563e707c-ba06-4f10-bd39-e4d44a56e132.png)

And I'll expect it to be, as it is in the scenario 2:

![image](https://user-images.githubusercontent.com/19690868/164482122-cdd59fc5-52ff-47d1-8bc8-882162a83f99.png)

## Details
- Used library version: 8.4.5
- Used gradle build tools version: 31.0.0
- Used tooling / Android Studio version: Android Studio Bumblebee (latest)

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

![Screenshot_20220421_163214](https://user-images.githubusercontent.com/19690868/164481801-75aa8867-66ee-4be2-90ae-9897f728ed0e.png)

**Comment by mikepenz** [comment]
I believe that this could possibly be because not all things are reset. E.g. the different held references:
```
        binding.slider.accountHeader = null
        binding.slider.headerView = null
        headerView.sliderView = null
```
(based on the sample activity)


A quick draft of a method to do a detach could look like (this would be a full detach, not 100% tested yet):

```kotlin

    fun AccountHeaderView.detachFromSliderView(sliderView: MaterialDrawerSliderView) {
        this.sliderView = null

        // set the top padding to 0 as this would happen when the AccountHeader is created during Drawer build time
        sliderView.recyclerView.updatePadding(top = /* topInset + */ context.resources.getDimensionPixelSize(R.dimen.material_drawer_padding_top_bottom))

        // remove the views again
        sliderView.headerView = null
        sliderView.accountHeader = null

        // rebuild the things
        updateHeaderAndList()
        sliderView.resetDrawerContent()
    }
```

**Comment by carlos-mg89** [comment]
Thanks a lot! That was it :)
