### ISSUE TITLE
How to implement on item click listener in Java

### ISSUE THREAD

**Issue by panovvitalik** [mikepenz/MaterialDrawer#2786]
## About this issue

I'm trying to migrate from 6.1.2 to 9.0.1

My project is on Java.

In Kotlin I see an example: 

```
// specify a click listener
slider.onDrawerItemClickListener = { v, drawerItem, position ->
    // do something with the clicked item :D
    false
}
```

In java I wrote below code (as Android studio was supposed to me):

 ```
slider.setOnDrawerItemClickListener(new Function3<View, IDrawerItem<?>, Integer, Boolean>() {
            @Override
            public Boolean invoke(View view, IDrawerItem<?> iDrawerItem, Integer integer) {
                switch ((int)iDrawerItem.getIdentifier()) {
                    case MENU_ITEM_LOGIN:
                        login();
                        break;
                }
                return false;
            }
        });
```

and this on click listener is never called. Where am I wrong?
It only closes menu drawer - and thats all.

## Details
- [ ] 9.0.1
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

**Comment by mikepenz** [comment]
Sadly there is no support for Java in the versions beyond v6.x, and many of the extensions and helper functions will only work in Kotlin projects.

----

https://github.com/mikepenz/MaterialDrawer#latest-releases-

<img width="327" alt="Screenshot 2022-08-19 at 14 57 53" src="https://user-images.githubusercontent.com/1476232/185623335-97b72b5b-6926-4199-9da0-0c3965a3df3c.png">

**Comment by panovvitalik** [comment]
It's very sad to hear this :-(
