### ISSUE TITLE
Color attribute

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/MaterialDrawer#279]
In my XML color file I set the icons color in the material drawer, but they remain black.
Could anyone help me? Thanks in advance.

**Comment by mikepenz** [comment]
@EpsilonOrionis please more details. which xml, which color value, which icons?

icons as drawable or icons via the Android-Iconics library?

**Comment by mikepenz** [comment]
@EpsilonOrionis i have changed the behavior of this in the newest release perhaps it's working now?
