### ISSUE TITLE
Update a profile header in AccountHeader in Drawer

### ISSUE THREAD

**Issue by artem-inkaz** [mikepenz/MaterialDrawer#2795]
Header is not updated after changes, but only when onCreate inActivity
I use
 private lateinit var mCurrentProfile:ProfileDrawerItem
    private lateinit var mHeader: Account Header
        current profile
            .with Icon(R.drawable.sample)
            .withName("Sample")
            .withEmail("Sample")
            .withIdentifier(200)

        mHeader.update Profile(current profile)
        drawer.adapter.notify Adapter DataSetChanged()

        materialdrawer              : '7.0.0',
        materialdrawerNav  : "com.mikepenz:materialdrawer-nav:${libVersion.materialdrawer}",
        materialdrawer     : "com.mikepenz:materialdrawer:${libVersion.materialdrawer}"

**Comment by artem-inkaz** [comment]
I watched the previous article
https://github.com/mikepenz/MaterialDrawer/issues/2308

**Comment by mikepenz** [comment]
The linked ticket and the above mentioned version number are both pretty old and only provided as-is at this point. 

You can try to upgrade to `v8.4.5 ` which was the last release prior to the material3 transition. 
You can also look into the sample app at this version and see if that one contains examples matching your need. 

However versions other than the most recent version are provided as-is, and are not planned to get any further updates
