### ISSUE TITLE
Drawer Toogle not correctly positioned

### ISSUE THREAD

**Issue by RubyDerBoss** [mikepenz/MaterialDrawer#280]
As you can see in the screenshot, the Drawer Toogle is not on the same height as the title, which looks weird.
![example1](https://cloud.githubusercontent.com/assets/8021265/7441146/75cfa86e-f0db-11e4-9b78-cffdefade327.png)

Version: 2.9.1

**Comment by mikepenz** [comment]
@RubyDerBoss please more details. i'm sure you have set a wrong height of the toolbar. (in fact this is no issue of the MaterialDrawer)

**Comment by RubyDerBoss** [comment]
This is my toolbar:
```xml
<android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="?attr/colorPrimary"
        android:elevation="4dp"
        android:minHeight="?attr/actionBarSize"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar" />
```

I've set minHeight because I want to add some Views to the toolbar later on.
If it's not a bug with the Library do you have a hint what I can do to fix the isue?

**Comment by mikepenz** [comment]
@RubyDerBoss yeah that's exactly the thing i thought will cause the issue. i had this in use in the past too, but the wrap_content seems to don't work properly here. 

if you do it like this:

```java
<android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        android:elevation="4dp"/>
```

it will work. Perhaps you find hints how to create your layout with additional content in the google docs.

**Comment by RubyDerBoss** [comment]
Hmm okay. Thank you for the help!
