### ISSUE TITLE
How Change Selector

### ISSUE THREAD

**Issue by Sinokos** [mikepenz/MaterialDrawer#283]
How can i change that blue color (text color and selector) to orange or something else?
Which attribute do I need to change?

![111](https://cloud.githubusercontent.com/assets/11757717/7445645/88b79768-f1c4-11e4-9c6f-396a97d1948a.png)
![222](https://cloud.githubusercontent.com/assets/11757717/7445646/88bdddb2-f1c4-11e4-9cbb-eb2d382e528c.png)

**Comment by mikepenz** [comment]
the blue of the selector is system default

the blue of the text of an selected item is the apps primary color as defined in the Google Material design guidelines

**Comment by Sinokos** [comment]
TY. It's help i little bit.
But default holo blue color(on focuse) still blue :(
![111](https://cloud.githubusercontent.com/assets/11757717/7474090/df0d798c-f347-11e4-82ef-0a5c9497bcaf.png)

Can u help me?

**Comment by mikepenz** [comment]
@Sinokos as mentioned this is default selector color. As far as i know this is system default. Correct me if i'm wrong.

Starting with API Level 21 the selector uses the correct color but on pre 21 devices it won'T

**Comment by Sinokos** [comment]
@mikepenz ty for help, i hope google can help me fix it)
