### ISSUE TITLE
Method setHeader() doesn't remove previous header.

### ISSUE THREAD

**Issue by halipso** [mikepenz/MaterialDrawer#284]
Method setHeader doesn't remove previously set header.
It just makes header's height bigger (as for me)

Also method removeHeader() do nothing.

Explanation:
...
result.setHeader(customHeader);
result.removeHeader();
result.setHeader(customHeader);
...

After this code header's height became 2x of customHeader view.

**Comment by halipso** [comment]
Well, you had to call withHeader at first.
Otherwise those methods wouldn't work.

**Comment by mikepenz** [comment]
@halipso you have closed it already but you are right this is an issue. it will be fixed in the next version. thanks
