### ISSUE TITLE
right to left compatibility

### ISSUE THREAD

**Issue by TheLoyalCruel** [mikepenz/MaterialDrawer#285]
would you please help me to change navigation drawer and action bar completely right to left?

**Comment by TheLoyalCruel** [comment]
up to api level 14!

**Comment by mikepenz** [comment]
actionBar is nothing MaterialDrawer specific. 

the MaterialDrawer can have it's gravity. Set it to right. If you need to change the layouts to support rtl, just add the layout of let's say the PrimaryDrawerItem to your project, and modify it to be RTL. 

I can't test it so i can't add it as default.
