### ISSUE TITLE
Window background color

### ISSUE THREAD

**Issue by alexander159** [mikepenz/MaterialDrawer#286]
How to change "material_drawer_window_background" color attribute in style.xml?

I have the following code (style.xml):

    <color name="c1">#fffffa4b</color>
    
    <style name="CustomTheme" parent="CustomTheme.Base">
    </style>

    <style name="CustomTheme.Base" parent="MaterialDrawerTheme.Light.DarkToolbar">
        
        <item name="colorPrimary">@color/material_drawer_primary</item>
        <item name="colorPrimaryDark">@color/material_drawer_primary_dark</item>
        <item name="colorAccent">@color/material_drawer_accent</item>

        
        <item name="material_drawer_window_background">@color/c1</item>
        <item name="material_drawer_background">@color/material_drawer_background</item>
        <item name="material_drawer_icons">@color/material_drawer_icons</item>
        <item name="material_drawer_primary_text">@color/material_drawer_primary_text</item>
        <item name="material_drawer_primary_icon">@color/material_drawer_primary_icon</item>
        <item name="material_drawer_secondary_text">@color/material_drawer_secondary_text</item>
        <item name="material_drawer_hint_text">@color/material_drawer_hint_text</item>
        <item name="material_drawer_divider">@color/material_drawer_divider</item>
        <item name="material_drawer_selected">@color/material_drawer_selected</item>
        <item name="material_drawer_selected_text">@color/material_drawer_selected_text</item>
        <item name="material_drawer_header_selection_text">@color/material_drawer_header_selection_text</item>
    </style>

but the background is still  white.

This theme works fine:

    <style name="MyMaterialTheme" parent="MyMaterialTheme.Base">
    </style>

    <style name="MyMaterialTheme.Base" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">@color/c1</item>
    </style>

**Comment by mikepenz** [comment]
@alexander159 this value is not used anymore. The background of the app is not handled by the MaterialDrawer
