### ISSUE TITLE
Drawer offset listner?

### ISSUE THREAD

**Issue by NorbertSzydlowski** [mikepenz/MaterialDrawer#287]

**Comment by mikepenz** [comment]
@NorbertSzydlowski please add some more information? What are you refering to?

**Comment by NorbertSzydlowski** [comment]
I think about callback that return percentage open progress.
Dnia 5 maja 2015 20:52 Mike Penz napisał(a):
 @NorbertSzydlowski please add some more information? What are you refering to?—
Reply to this email directly or view it on GitHub. 
--
Norbert Szydłowski
