### ISSUE TITLE
Call onProfileChanged by code

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/MaterialDrawer#288]
I'm using this library and works great, except I need a profile enabled by default, but does not enter the onProfileChanged event, I tried to make the setActiveProfile(identifier) but do not run the onProfileChanged...

I need to run the event onProfileChanged, because each profile can have different configurations must initialize.

Thank !!!

**Comment by mikepenz** [comment]
@seba123neo this is not yet possible. as an alternative i would recommend that you move the code outside the listener into a own method and you can trigger this once after start and in the event method then.

**Comment by seba123neo** [comment]
@mikepenz yes mike, that's what I did, it works fine now, thanks !!!

**Comment by mikepenz** [comment]
@seba123neo great ;)
