### ISSUE TITLE
Custom header layout items click event listener

### ISSUE THREAD

**Issue by mutindaz** [mikepenz/MaterialDrawer#289]
I was just wondering if instead of binding click events for views inside the header layout like this 
``` java
View header = result.getHeader();
ImageView headerBack = (ImageView) header.findViewById(R.id.header_back);
headerBack.setOnClickListener( new View.OnClickListener() {
	@Override
	public void onClick(View view) {
		result.closeDrawer();
	}
});
```
We have something like 
``` java 
drawer.withOnHeaderItemClickListener( the_view_id, new Drawer.OnItemClickListener(){
    ......
});
```

Just a suggestion though. :D

**Comment by mikepenz** [comment]
@mutindaz nice idea, but in my opinion this should stay up to the dev. it is really easy to do this inside your code so i really suggest you do this.

**Comment by mutindaz** [comment]
@mikepenz I get your point.

**Comment by mikepenz** [comment]
@mutindaz thanks ;)
