### ISSUE TITLE
Blackout background

### ISSUE THREAD

**Issue by Java-Help** [mikepenz/MaterialDrawer#290]

**Comment by Java-Help** [comment]
Hey, you can do darkening background of the Navigation Drawer here: http://rghost.net/6XK9dvXWz, that darkened only content (without Toolbar) ?. Now shade looks very bad

**Comment by mikepenz** [comment]
@Java-Help not sure what you want to do, but please take a look at the sample application. It shows how you can nest the DrawerLayout inside your layout (this is the only solution to have the darkening only in this area)

**Comment by Java-Help** [comment]
I'm sorry, but I do not understand you. As can be nest Navigation Drawer in layout?

**Comment by mikepenz** [comment]
The MaterialDrawer will create a DrawerLayout as you would to. As we use Toolbars now and those are in the layout and the DrawerLayout is above the whole layout so it can be under the statusbar the shadow is drawn above the whole layout (this is done by the DrawerLayout nothing to change by me) 

If you want only the right area to have the shadow oyu have to nest the DrawerLayout inside your view hirachie. See the sample app for a sample implementation for this. 

No idea why you want such an behavior, but it's possible

**Comment by Java-Help** [comment]
Can you give me a link to an example? Please

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java

This is the last sample activity if you start the sample app. Please note this will include the drawer inside your view. not as root. Look at the layout it uses. You will realize that the layout is under the drawer --> so only the area on the right of the drawer is darkened.

**Comment by Java-Help** [comment]
Thank yo!
