### ISSUE TITLE
How to deselect rows?

### ISSUE THREAD

**Issue by guilhermearaujo** [mikepenz/MaterialDrawer#291]
I don't want any row to be selected in my drawer, since all of them will start a new activity without the drawer.
For that, I set the `OnItemClickListener`, determine which activity to start and then I'm trying to de-select the row I tapped.

I tried these options, but the first crashes, and the second seems to go on an infinite loop of OOM errors.
`drawer.setSelection(null);`
`drawer.setSelection(0);`

How do I deselect the row?

**Comment by mikepenz** [comment]
@guilhermearaujo why you need them to deselect? Just disable the selection on those items?

but if you really want to deselect try drawer.setSelection(-1)

**Comment by guilhermearaujo** [comment]
Because they will open new activities, rather than changing the fragment of the drawer's activity.
If I disable selection will they still be clickable, but will not be rendered as a selected row?
How do I disable it?

I tried `-1` and it didn't work either.

**Comment by mikepenz** [comment]
try to set the selection to `-1` on the result object. 

yes they are still clickable but they wont feature a selected state

**Comment by guilhermearaujo** [comment]
It crashes with the message
> java.lang.NullPointerException: Attempt to invoke interface method 'int com.mikepenz.materialdrawer.model.interfaces.IDrawerItem.getIdentifier()' on a null object reference

**Comment by mikepenz** [comment]
You use this method:
https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L2108 ?

**Comment by guilhermearaujo** [comment]
That's what I am doing, right?

```java
drawer = new Drawer()
        .withActivity(this)
        .withToolbar(toolbar)
        .withDrawerWidthDp(320)
        .withTranslucentStatusBar(true)
        .withActionBarDrawerToggleAnimated(true)
        .withDisplayBelowToolbar(true)
        .withOnDrawerItemClickListener(this)
        .build();
drawer.setSelection(-1);
```

**Comment by mikepenz** [comment]
@guilhermearaujo please try

```java
setSelection(-1, false);
```

**Comment by guilhermearaujo** [comment]
That one works

**Comment by mikepenz** [comment]
@guilhermearaujo great. i will fix the issue for the call without the `false` in a future release. Thanks

**Comment by mikepenz** [comment]
@guilhermearaujo oh sorry. just saw the thrown exception was not by the library. Please make sure that you check if the DrawerItem in the onDrawerClickListener is not null. Because this one can be null. (If the user clicks on a header, or if you set the selection to an non existing item..)

**Comment by guilhermearaujo** [comment]
The DrawerItem is not null. In fact, I can even extract its ID to know which row to handle.

**Comment by mikepenz** [comment]
@guilhermearaujo but still there was a nullPointerException. `setSelection(-1);` should not throw a nullPointer. As far as i found everything is checked in my code. So are you sure the NullPointer was not in your code?

**Comment by guilhermearaujo** [comment]
Yes, because the log points exactly to the line where I call `drawerItem.setSelection(-1)`

**Comment by mikepenz** [comment]
@guilhermearaujo can you please post the whole stacktrace?
