### ISSUE TITLE
Change profile image in header

### ISSUE THREAD

**Issue by Dimorinny** [mikepenz/MaterialDrawer#293]
Hi, I have a question.
How can I set profile image, when drawer is already created?

Thanks.

**Comment by mikepenz** [comment]
@Dimorinny you mean the icon of a user?

Just update the ProfileDrawerItem?

`updateProfileByIdentifier()`

The profile which will be updated must have an identifier which is set to the ProfileDrawerItem with `withIdentifier()` this one has to be unique!
