### ISSUE TITLE
Error:(426, 21) No resource found that matches the given name: attr 'windowNoTitle'.

### ISSUE THREAD

**Issue by DavidHR96** [mikepenz/MaterialDrawer#294]
I'm using Android 2.3.3
<img src="http://i.gyazo.com/2f07d1f7bc1e46708722210b8e8f2a24.png">

**Comment by mikepenz** [comment]
@DavidHR96 what'S the appcompat library version you use?

**Comment by DavidHR96** [comment]
@mikepenz 21.0.3

**Comment by mikepenz** [comment]
@DavidHR96 https://github.com/mikepenz/MaterialDrawer#-v290
