### ISSUE TITLE
Unable to execute dex

### ISSUE THREAD

**Issue by patelakshay13890** [mikepenz/MaterialDrawer#295]
Getting Exception on starting the project..
 Unable to execute dex: Multiple dex files define Lcom/mikepenz/google_material_typeface_library/GoogleMaterial$Icon;
Conversion to Dalvik format failed: Unable to execute dex: Multiple dex files define Lcom/mikepenz/google_material_typeface_library/GoogleMaterial$Icon;

**Comment by mikepenz** [comment]
@patelakshay13890 do you ad the Android-Iconics project seperately to your build.gradle? If yes, i assume you have a different version than the version included in the MaterialDrawer. If you want to add it on your own you can remove the transitive from the MaterialDrawer dependency, but then you have to make sure to add the all the dependencies yourself

**Comment by patelakshay13890** [comment]
okay done thanx for quick response

**Comment by mikepenz** [comment]
@patelakshay13890 the MaterialDrawer comes automatically with the Android-Iconics library so normally nothing to add here on your side ;)
