### ISSUE TITLE
SectionDrawerItem - setIdentifier

### ISSUE THREAD

**Issue by matthew2402** [mikepenz/MaterialDrawer#298]
setIdentifier for SectionDrawerItem is missing (getIdentifier() is implemented). Will it be added in the future?

Thanks in advance!

**Comment by mikepenz** [comment]
@matthew2402 you are right. I'll add it in the next release. It makes sense for changing the section name :P Thanks.

**Comment by matthew2402** [comment]
Alright, thanks! :)
