### ISSUE TITLE
Cannot resolve symbol Font Awesome/GoogleMaterial/IconicsDrawble

### ISSUE THREAD

**Issue by YuvPrime** [mikepenz/MaterialDrawer#299]
Hey,

First of all thanks for your library. It's awesome as it was soo easy to implement. But, i faced some error when i open the `SimpleHeaderDrawerActivity.java` file. Some errors are : 

Cannot resolve symbol Font Awesome
Cannot resolve symbol Cannot resolve symbol Font Awesome
Cannot resolve symbol IconicsDrawble

**Comment by mikepenz** [comment]
@YuvPrime i assume you've missed the transitive in your `build.gradle`?

```gradle
compile('com.mikepenz.materialdrawer:library:2.9.2@aar') {
    transitive = true
}
```

**Comment by YuvPrime** [comment]
I haven't edited anything. Just trying your sample code. Here's the `build.grade` file https://gist.github.com/YuvPrime/8c772b17f0c9fd8bb764

**Comment by mikepenz** [comment]
@YuvPrime that's interesting. Is your gradle in offline mode?

**Comment by YuvPrime** [comment]
Nope. It's on. Haven't checked that option and one more doubt. What's the diff b/w `compile('com.mikepenz.materialdrawer:library:2.9.2@aar') {
    transitive = true
}` and `compile('com.mikepenz.aboutlibraries:library:4.7.1@aar') {
        transitive = true
    }`

**Comment by mikepenz** [comment]
the first line says **.materialdrawer** and the second one **aboutlibraries** two different libs ;)

**Comment by YuvPrime** [comment]
@mikepenz oh thanks :) Does the functions are same for both library? or if i use first one,  will the error disappears?

**Comment by mikepenz** [comment]
The sample app should work out of the box, so the question is what's happening for you. Can you add more information about the development environment you have?

The **MaterialDrawer** is this project. The **AboutLibraries** can be found here: https://github.com/mikepenz/AboutLibraries

**Comment by YuvPrime** [comment]
@mikepenz Android Studio. Have SDK from 14 to current version. Everything up-to-date.

**Comment by mikepenz** [comment]
Android Studio 1.2? Perhaps this causes some troubles. Haven't updated yet because i've read about some issues. 

It would be interesting if someone else already uses the latest Android Studio and sees similar issues

**Comment by YuvPrime** [comment]
@mikepenz I just created a new project and added your library through gradle. It works fine. It throws error only on your sample you've provided. I've one more doubt. Do i need to open new issue for question or can i ask here?

**Comment by mikepenz** [comment]
@YuvPrime so i assume you made a small mistake during importing the sample project. But good that it is working ;)

You can also jump over to gitter and we can chat there.
