### ISSUE TITLE
Ripple Effect on Drawer Items Pre-Lollipop

### ISSUE THREAD

**Issue by SuperiorJT** [mikepenz/MaterialDrawer#300]
I just wanted to say first that this library is epic. I love how you made it so translucent status bar works with dialogs correctly. I was wondering though if you could have a style setting that allows for ripple effect on the drawer items for devices not on lollipop. I have seen other material libraries pull this off and I use them as well. If you can't do this, is there a way to change the color effect when the item is pressed? Thanks for this fine piece of work!

**Comment by SuperiorJT** [comment]
Another option maybe to completely remove the drawer item pressed effect. The google maps app seems to do something similar to that with their drawer. The only reason this is important is because my app is primaryPurple and the holo_blue effect kinda kills it. So I'm looking for a workaround

**Comment by mikepenz** [comment]
@SuperiorJT i have decided to not mimic any visual stuff which is not provided by google and is not specified. Google states to display stuff on pre Lollipop devices as it was default there. It is already wrong that i use a translucent StatusBar for the Drawer on Pre Lollipop devices, but i think this one is ok :D

If you really need the ripple effect just implement your own DrawerItem or extend the PrimaryDrawerItem ;). Is a task of a few minutes and will work with the lib ;)
