### ISSUE TITLE
Icons are colored wrong

### ISSUE THREAD

**Issue by RubyDerBoss** [mikepenz/MaterialDrawer#301]
Like you can see in the Screenshot some Icons are colored (or tinted) wrong.
![example](https://cloud.githubusercontent.com/assets/8021265/7556188/1f0b3574-f767-11e4-9109-2a9551c58252.png)
The first Icon has .withIconTinted() enabled, the second one doesn't.

**Comment by mikepenz** [comment]
@RubyDerBoss and how do you create those icons? what's the color of the original icons?

**Comment by RubyDerBoss** [comment]
I generated these Icons with the AndroidAssetStudio, (https://romannurik.github.io/AndroidAssetStudio/) 
They are entirely black, as recommended in the Google Design Guidelines.

**Comment by mikepenz** [comment]
@RubyDerBoss so the behavior is working correct. If you tint the icon it will have the correct color for the Drawer as of the Material Design Guidlines

**Comment by RubyDerBoss** [comment]
![ic_stats](https://cloud.githubusercontent.com/assets/8021265/7556214/190cb084-f768-11e4-963e-2e41a9325533.png)
![ic_play_games](https://cloud.githubusercontent.com/assets/8021265/7556213/190ca6ac-f768-11e4-845e-df6d407e1eec.png)
These are the Icon how they are in my res folder.

**Comment by RubyDerBoss** [comment]
No, these Icons are selected, therefore they shouldn't be tinted.

**Comment by mikepenz** [comment]
Further reading here: http://www.google.com/design/spec/patterns/navigation-drawer.html

**Comment by RubyDerBoss** [comment]
Sorry, I dind't describe my Issue very well. I'll retry:
None of the Sections in the Screenshot is selected. They should look the same even one is tinted on click and the isn't. 
![unbenannt](https://cloud.githubusercontent.com/assets/8021265/7556228/9a3eaea0-f768-11e4-8937-19d518b3b402.png)
This is how it looks like if I selected one, that is working correctly.

**Comment by mikepenz** [comment]
@RubyDerBoss with the option `withIconTinted()` you enable general icon tinting. the library will then tint the icons in the correct colors as specified in the theme. i think i named the method wrong. 

will rename it to `withIconTinting` in the next version

**Comment by RubyDerBoss** [comment]
I'm sorry, the behavior of the Drawer is indeed correct. I always thought the Icons should be entirely black, which is not the case. (54%) Thank you for pointing that out!

**Comment by mikepenz** [comment]
@RubyDerBoss no problem ;)

Just in case you need them to be black. Just overwrite this color value: material_drawer_primary_icon or define it in your style

**Comment by RubyDerBoss** [comment]
No, I try to follow the Guidelines as close as possible. But thank you for the hint!

**Comment by mikepenz** [comment]
@RubyDerBoss the behavior was different in previous versions because it did not handle the standard icons. just the selected icon. but i found that many people include their icons in black so i've decided to unify this function and enable it for both

**Comment by RubyDerBoss** [comment]
Okay, I think that is/was a very good improvement. It would be great if you could document this and maybe the other Methods of the DrawerItem to prevent Questions like this and make the life for Developers even more easy.
