### ISSUE TITLE
Sticky Section gets diabled

### ISSUE THREAD

**Issue by RubenGees** [mikepenz/MaterialDrawer#302]
I have 2 Sections in my StickySection. One is checkable, the other isn't ( item.setCheckable(false); )
When I click on the Section which is checkable and then on the Section which is not Checkable, the first one is disabled. (The Indicator that this Section is currently selected goes away) 
This happens only in the StickySection.

**Comment by mikepenz** [comment]
@RubyDerBoss you are right the sticky section does not set back the selection. thanks. nice finding
