### ISSUE TITLE
Request: Don't call Callback if section is already selected

### ISSUE THREAD

**Issue by RubenGees** [mikepenz/MaterialDrawer#303]
It would be great if you could include a Mehod which enables or disables the feature described in the title!

**Comment by mikepenz** [comment]
@RubenGees please handle this on your side, because this will just add more unnecessary boilerplate code to the MaterialDrawer. and to keep it simple i want to keep it as clean as possible

**Comment by RubenGees** [comment]
Okay, no Prob. :D
