### ISSUE TITLE
Changing status bar color makes status bar solid

### ISSUE THREAD

**Issue by djrausch** [mikepenz/MaterialDrawer#304]
I have a view pager that changes the status bar and toolbar color when the page changes. The nav drawer is drawn over the status bar before I change the page (before I change the color programmatically), but after setting the color, the status bar is the solid color.

I'm changing the statusbar color with:
 ```android
getWindow().setStatusBarColor(getResources().getColor(statusBarColor));
```

Any suggestions?

**Comment by mikepenz** [comment]
@djrausch as the statusBar has to be translucent because the drawer should be displayed below i use the ScrimInsetsLayout to color the upper area. So you can change this color via the `result` object:

`result.setStatusBarColor()`

**Comment by djrausch** [comment]
Perfect. Thanks!

**Comment by mysgithub** [comment]
this method does not exists... result.setStatusBarColor()
so now status bar always shows with color or translucent color

**Comment by mikepenz** [comment]
@mysgithub the method is no longer there. Just set the `StatusBarColor` on the `DrawerLayout` https://github.com/mikepenz/MaterialDrawer/issues/1024
