### ISSUE TITLE
minSdkVersion?

### ISSUE THREAD

**Issue by The28AWG** [mikepenz/MaterialDrawer#305]
С какими minSdkVersion совместим MaterialDrawer? У меня получилось использовать библиотеку при minSdkVersion = 10, ниже не получилось из за зависимости от com.mikepenz.iconics:library:0.9.1 которая требует minSdkVersion = 10.
Возможно кто нибудь собирал MaterialDrawer с более низким minSdkVersion? Можно ли тогда пометить библиотеку com.mikepenz.iconics как опциональную? Чтобы при minSdkVersion < 10 функционал реализуемый библиотекой был недоступен. Или переделать библиотеку com.mikepenz.iconics так чтобы она работала с более низким minSdkVersion...

**Comment by mikepenz** [comment]
Support only in english.

**Comment by mikepenz** [comment]
MaterialDrawer: minSdk: 10
https://github.com/mikepenz/MaterialDrawer/blob/master/library/build.gradle#L8
Android-Iconics: minSdk: 10
https://github.com/mikepenz/Android-Iconics/blob/master/library/build.gradle#L8

**Comment by The28AWG** [comment]
Да, да! Но можно ли собрать MaterialDrawer при minSdkVersion < 10?
But is it possible to build MaterialDrawer at minSdkVersion <10? (google translate)
Можно ли пометить Android-Iconics как опциональный пакет?
Is it possible to mark the Android-Iconics as an optional package?
Чтобы в случае если minSdkVersion = 9 Android-Iconics не работал.

**Comment by mikepenz** [comment]
No. API Level 10 is already very very low :D. In fact if we release pre 10 it will break a lot of functions. you can still fork it and include it in your project and try to make it backward compatible.

Android-Iconics is a required dependency. It is required for some icons i display inside the drawer. it eliminates the need of real drawables which don't scale and will add more size to the library

**Comment by The28AWG** [comment]
Спасибо за ответ. =(

**Comment by mikepenz** [comment]
@The28AWG why still develop vor pre 10? Recommended is >14 or even >16

**Comment by The28AWG** [comment]
Need develop for android 2.2 They are very small price. =)
Нужно разрабатывать под андроид 2.2. Они очень мало стоят. =)
My test  phone Samsung Galaxy Tab GT-P1000! Its very older phone! current android version 2.3.3. If but work this phone then work any android devices!

**Comment by OlegWock** [comment]
2.3.3 Уже почти нет, а про 2.2 говорить нечего
