### ISSUE TITLE
problem header height side menu

### ISSUE THREAD

**Issue by rebus007** [mikepenz/MaterialDrawer#306]
in api 21 no problem but in api 19 or minor l'header become too hight, look screenshot below

lollipop: http://s27.postimg.org/u5h78dmxf/header_2.png
api 18: http://s27.postimg.org/q7pc58aqb/header_1.png

**Comment by mikepenz** [comment]
@rebus007 the height is correct as of the Material Design Specification. The "problem" is that the header won't move under the statusBar. so the pixels which would be under the statusBar are shown below it and the header seems higher.

**Comment by mikepenz** [comment]
As far as i can tell this is no real issue. i have not found a word about this in the google material design guidelines. If you find something let me know ;)

**Comment by rebus007** [comment]
just look at these two screenshots taken from the app google play
api 18 http://s3.postimg.org/h0nv1f6o3/google_play_header_2.png
lollipop http://s3.postimg.org/ovyeg8gar/google_play_header_1.png

**Comment by mikepenz** [comment]
@rebus007 ok they cut it. so even if it is not documented. let us assume google's apps are correct ;)
