### ISSUE TITLE
Implement behavior as recommended by Google

### ISSUE THREAD

**Issue by RubenGees** [mikepenz/MaterialDrawer#307]
Taken from here: https://developer.android.com/design/patterns/navigation-drawer.html at "Interaction Details"

A Navigation Drawer should implement the Learning Pattern to show the Drawer on first use. (Sure we could do it ourselves, but it would be really great if the Library could do that since it should be a part of a Navigation Drawer)

Another thing is a Peak if you touch on the very left of your screen. (I don't know if it is implemented, but I couldn't produce that effect.)

**Comment by mikepenz** [comment]
@RubenGees you can do everything with the Drawer generated by the lib as with a normal DrawerLayout. If it is not possible with a DrawerLayout it is not possible here either. 

About the show on first use. Not sure if this is still the cases with the new Material Design Guidelines. I can for sure add it to the MaterialDrawer but it is also a very easy task for you to implement in your application

**Comment by RubenGees** [comment]
I think it still makes sense since there are (sadly) some users who don't know that there is the Drawer. I came from this Library: https://github.com/neokree/MaterialNavigationDrawer which had this feature and I missed it here. (I like yours better btw, I'm glad I changed, great job!)

About the peak, are you able to produce this effect with one of your Devices or an emulator? If not, do you know how to get it?

**Comment by mikepenz** [comment]
@RubenGees the peak thing is working on my phone. i think this is default DrawerLayout functionality.

about the open on first launch. i'll add this. because it's handy. for some special usecases :D

**Comment by mikepenz** [comment]
@RubenGees in fact i just checked the source of this drawer lib. it does not include the logic to store if it was shown on first launch? how do you did it?

**Comment by RubenGees** [comment]
Okay It is not shown on my Phone. Weird. 

Uhm sorry, you are right I implemented it by myself. :D It is just some Interaction with SharedPreferences and savedInstanceState.

If you create a new Project in Android Studio and select "Activity with Navigation Drawer" you will get some sample code, containing that feature. It would be great if you could keep the names of the settings, so your lib will recognise if people already used that implementation!

**Comment by mikepenz** [comment]
@RubenGees if you can send the sample implementation i will include that name.

**Comment by RubenGees** [comment]
Sure, just wait a sec :)

**Comment by RubenGees** [comment]
https://gist.github.com/RubenGees/0c80196f88b3d2a44b2f
This is the code, generated by Android Studio.

This is th interesting part:
```java
    /**
     * Per the design guidelines, you should show the drawer on launch until the user manually
     * expands it. This shared preference tracks this.
     */
    private static final String PREF_USER_LEARNED_DRAWER = "navigation_drawer_learned";
```

**Comment by mikepenz** [comment]
@RubenGees thanks. is in the next version

**Comment by RubenGees** [comment]
:+1:
