### ISSUE TITLE
Tint Color

### ISSUE THREAD

**Issue by danielgomezrico** [mikepenz/MaterialDrawer#309]
Hi Mike, 

I´m just updated and added the `withIconTinted` like this:

      menuDrawer = new Drawer()
                .withActivity(this)
                .withToolbar(toolbar)
                .withOnDrawerItemClickListener(this)
                .withAccountHeader(headerResult)
                .withActionBarDrawerToggleAnimated(true)
                .withActionBarDrawerToggle(true)
                .withTranslucentStatusBar(true)
                .addDrawerItems(
                        new PrimaryDrawerItem()
                                .withName(getString(R.string.title_fragment_status))
                                .withIcon(R.drawable.ic_map_black_24dp)
                                .withIconColorRes(R.color.pickup_primary)
                                .withSelectedIconColorRes(R.color.pickup_primary)
                                .withSelectedTextColorRes(R.color.pickup_primary)
                                .withIconTinted(true)
                                .withIdentifier(1),

                        new DividerDrawerItem(),

                        new SecondaryDrawerItem().withName(getString(R.string.drawer_item_faq))
                                .withCheckable(false)
                                .withIdentifier(2),

                        new SecondaryDrawerItem().withName(getString(R.string.drawer_item_become_driver))
                                .withCheckable(false)
                                .withIdentifier(3),

                        new SecondaryDrawerItem().withName(getString(R.string.drawer_item_contact))
                                .withCheckable(false)
                                .withIdentifier(4),

                        new DividerDrawerItem(),

                        new SecondaryDrawerItem().withName(getString(R.string.drawer_item_logout))
                                .withCheckable(false)
                                .withIdentifier(5)
                ).build();

And it tints the icon but with blue, if I dont set any color it sets the text/icon color to blue, but I need them to be the primary if it is selected, what I am doing wrong?

**Comment by mikepenz** [comment]
`withSelectedIconColorRes()` is currently broken. an update is on it's way ;)

https://github.com/mikepenz/MaterialDrawer/issues/238

**Comment by danielgomezrico** [comment]
or should I remove it? 
I just want to tint the icon/text with primary color that I setted with:

  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="android:windowBackground">@color/pickup_background</item>
        <item name="android:colorBackgroundCacheHint">@color/pickup_background</item>

        <item name="colorPrimary">@color/pickup_primary</item>
        <item name="colorPrimaryDark">@color/pickup_primary_dark</item>
        <item name="colorAccent">@color/pickup_accent</item>
    </style>

**Comment by mikepenz** [comment]
@danielgomezrico see this section:

https://github.com/mikepenz/MaterialDrawer#custom-style---stylesxml

add this to your style:
```xml
        <item name="material_drawer_primary_icon">@color/pickup_primary</item>
```
