### ISSUE TITLE
set colors in toolbar

### ISSUE THREAD

**Issue by dizelmotor** [mikepenz/MaterialDrawer#310]
after updating MD lib from v2.8 to 2.9.0 color for back arrow and threeDotsMenu in toolbar is black now, but with v2.8 they was are white..
before update:
![](http://i48.fastpic.ru/big/2015/0512/29/189ed875f39c52e25f77aae9c6719929.png)
![](http://i48.fastpic.ru/big/2015/0512/a0/2ae94810bbfd473f672eeb601bc6cba0.png)
![](http://i58.fastpic.ru/big/2015/0512/fc/67e692b83e833b1f2fc91481b6f4b9fc.png)
after:
![](http://i47.fastpic.ru/big/2015/0512/45/5f3962f437e8633e1becf028bac17f45.png)
![](http://i47.fastpic.ru/big/2015/0512/8e/c65baad25a0c11bfbecec90d4ab7758e.png)
![](http://i48.fastpic.ru/big/2015/0512/b0/c8e1e80c5b14f5ca59826bdfa57de5b0.png)

on main activity with MD the hamburg icon is white, but when i call startActivity then in new activity with toolbar and back arrow (withoud MD) the back arrow is black. i have one theme for all activities:
```
parent="MaterialDrawerTheme.Light.DarkToolbar"
```
i'll try set theme to "MaterialDrawerTheme" but then all backrounds is black and i want white.
How i can set back arrow and threeDotsMenu color to white?

```
<style name="AppTheme" parent="MaterialDrawerTheme.Light.DarkToolbar">
        <!-- All customizations that are NOT specific to a particular API-level can go here. -->
        <item name="colorPrimary">#5EB1F7</item>
        <item name="colorAccent">@color/blue_light</item>
        <item name="actionModeBackground">@color/black_half_transparent</item>
        <item name="android:textColor">@color/black</item>
        <item name="android:textColorPrimary">@color/white</item>
    </style>
```

**Comment by mikepenz** [comment]
Please read the upgrade notes:

https://github.com/mikepenz/MaterialDrawer#-v290

**Comment by dizelmotor** [comment]
my Toolbar widget has  app:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar" but colors is black

**Comment by mikepenz** [comment]
@dizelmotor wrong namespace. with appcompat v22.1.0 you have to use `android:theme`
```xml
 android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
```
