### ISSUE TITLE
Can't get name of DrawerItem

### ISSUE THREAD

**Issue by VINChe1990** [mikepenz/MaterialDrawer#311]
How can I get the name of `DrawerItem` via `Drawer.OnDrawerItemClickListener` -> `onItemClick` ?

I initialised Drawer Items:

```
.addDrawerItems( new PrimaryDrawerItem().withName("Home").withIdentifier(1)....
```

Try to get identifier- `((PrimaryDrawerItem)drawerItem).getIdentifier()` - it returns 1.
Try to get name - `((PrimaryDrawerItem)drawerItem).getName()` but it returns Null.

**Comment by mikepenz** [comment]
Ok. And you don't use `withNameRes()` ?

**Comment by VINChe1990** [comment]
Hmm....What component has this method? I didn't find it.

**Comment by mikepenz** [comment]
@VINChe1990 the DrawerItem. you can set the name as test or from resource, but you will only be able to get it back with the same method. The sample app also uses those methods and it works. :/

Perhaps you can post a bit more of your source, so it's easier to hunt down the issue

**Comment by VINChe1990** [comment]
Thanks! I see!

when I use res name: 
new PrimaryDrawerItem().withName(R.string.drawer_item_main).withIdentifier(1)
to get name I need to: 
activity.getResources().getString(((PrimaryDrawerItem)drawerItem).getNameRes())

when I use string variable: 
new PrimaryDrawerItem().withName("Main").withIdentifier(1)
to get name I need to: 
((PrimaryDrawerItem)drawerItem).getName()

**Comment by mikepenz** [comment]
@VINChe1990 right ;)
