### ISSUE TITLE
SwitchDrawerItem and ToggleDrawerItem random change it state

### ISSUE THREAD

**Issue by dzungpv** [mikepenz/MaterialDrawer#313]
I have try with sample app and my own implementation.

How to produce this bug:
- Switch of "Switch" "Switch2" and "Toggle"
- Click "Open Source" all three item will revert back original state.

**Comment by mikepenz** [comment]
@dzungpv i think i know what's going on. one part has to be fixed by me. 

(You have to make sure on your side to store the specific state too :D so it is restored on the next launch)

**Comment by dzungpv** [comment]
Yes, I save those state in Preference and load it at onCreate().

Other action will make state change is scroll the Drawer (Hold and scroll down).

**Comment by mikepenz** [comment]
yeah i know. and i think i know why. let me check this later today.
