### ISSUE TITLE
Missaligned profile picture/data

### ISSUE THREAD

**Issue by danielgomezrico** [mikepenz/MaterialDrawer#316]
Hi Mike.

I´m using the header to show an image/username/name but they are not aligned, why?

This is how I build the `AccountHeader`:
```    
AccountHeader.Result headerResult = new AccountHeader()
                    .withActivity(this)
                    .withSelectionListEnabled(false)
                    .withHeaderBackground(R.drawable.status_drawer_header_background)
                    .withOnAccountHeaderListener(this)
                    .addProfiles(
                            new ProfileDrawerItem()
                                    .withName("daniel")
                                    .withEmail("daniel5@example.com")
                                    .withIcon(ResourceHelper.getDrawable(this,
                                            R.drawable.ic_account_circle_white_48dp))
                    ).build();
```

But the image is not aligned with username and name.  My icon is 48dp, it have the correct size? 

![screenshot_2015-05-13-15-58-40](https://cloud.githubusercontent.com/assets/76348/7621124/f608fca4-f989-11e4-9b7d-2b755e2ff23e.png)

**Comment by RubenGees** [comment]
Maybe there is some padding around the button?

**Comment by danielgomezrico** [comment]
This is the button image, I have it on each drawable-... folder and was created by [Material design icon generator](https://github.com/konifar/android-material-design-icon-generator-plugin)
![ic_account_circle_white_48dp](https://cloud.githubusercontent.com/assets/76348/7621507/f37d27dc-f98c-11e4-8778-ca23f8d6ba39.png)

**Comment by danielgomezrico** [comment]
Yeah, the icon have some padding, thanks :+1:

**Comment by mikepenz** [comment]
@danielgomezrico you can also use the built in Android-Iconics library to use Material Design Icons. All the Google Material Design Icons are already in ;) via Font so they scale for all devices. No drawables required

**Comment by danielgomezrico** [comment]
:O

**Comment by danielgomezrico** [comment]
I want to! but I use [Material Edit Text](https://github.com/rengwuxian/MaterialEditText) for my text fields, so how can I use [Android-Iconics)(https://github.com/mikepenz/Android-Iconics) and that?

**Comment by mikepenz** [comment]
You can generate normal Drawables with the Android-Iconics lib. 

Or what do you mean?

**Comment by danielgomezrico** [comment]
But I will have to put them by code right?
I´m setting the icon for my forms thought styles

**Comment by mikepenz** [comment]
@danielgomezrico yeah ok. so you will have to keep your forms via drawables if you want to set them via styles. but you can use the Android-Iconics for the Drawer and MenuItems and everywhere else ;)

**Comment by danielgomezrico** [comment]
:+1:
