### ISSUE TITLE
Header Profile update

### ISSUE THREAD

**Issue by danielgomezrico** [mikepenz/MaterialDrawer#317]
I need to update the profile that I already added to my drawer but I can´t find a way to.

**Comment by danielgomezrico** [comment]
This works:

```
IProfile profile = headerResult.getProfiles().get(0);
        profile.setName(customer.summary.name);
        profile.setEmail(customer.summary.email);
        headerResult.updateProfileByIdentifier(profile);
```

**Comment by mikepenz** [comment]
@danielgomezrico you can update items inside the drawer or header with the update methods. 

also make sure the items have identifiers so i can map the correct ones together.
