### ISSUE TITLE
Is there any way not to close Drawer when clicking an item?

### ISSUE THREAD

**Issue by Falcon5f** [mikepenz/MaterialDrawer#318]
I didn't find any library native method that allows not to close the drawer when clicking specific item.
For example, if I want to open SettingsActivity drawer should stay open.

It will be great if you add something like `.withCloseDrawer(boolean close)` for drawer items.

**Comment by mikepenz** [comment]
You can generally disable closing with this:
`withCloseOnClick(false)`

and then just close the drawer on your own with `result.closeDrawer()` if you need to close it
