### ISSUE TITLE
Drawer problem in tablet

### ISSUE THREAD

**Issue by rebus007** [mikepenz/MaterialDrawer#320]
I have tested MaterialDrawer in a tablet (nexus 7 2012) and i have found some problem with header height end drawer width. Look at these screenshots to better understand

MaterialDrawer portrait http://s15.postimg.org/3radkmykb/Screenshot_2015_05_15_15_19_13.png
MaterialDrawer landscape http://s15.postimg.org/9x6ru9m63/Screenshot_2015_05_15_15_19_21.png

GooglePlay portrait http://s15.postimg.org/b74l9bfy3/Screenshot_2015_05_15_15_19_35.png
GooglePlay landscape http://s15.postimg.org/dm1iqv2ij/Screenshot_2015_05_15_15_19_47.png

**Comment by mikepenz** [comment]
@rebus007 i will take a deeper look but as far as i know i follow the Guidelines which are well documented, probably the Play Store is wrong. I will report back if i find out more.

**Comment by mikepenz** [comment]
As of here: **The 320 dp on phones and 400 dp on tablets/desktop is the max width standard for all Google apps in Material Design** the behavior of the MaterialDrawer is correct. 

Further read up here: 
https://medium.com/@sotti/navigation-drawer-styling-under-material-design-f0767882e692
