### ISSUE TITLE
Selectable SwitchDrawerItem

### ISSUE THREAD

**Issue by ChainsDD** [mikepenz/MaterialDrawer#321]
Is it possible to have a SwitchDrawerItem that can be selected like a PrimaryDrawerItem if it's tapped anywhere except the switch?

Would open up the possibility of having a drawer item that can be turned on or off, but selected to launch a fragment with finer control. For example, a notifications item that can be easily turned on or off from the drawer, but selected to control type and frequency of notifications.

**Comment by mikepenz** [comment]
@ChainsDD not right now, but should be easily extendable. If it will not fit in the lib i will post how you can do it by adding a simple CustomDrawerItem for your case ;)

Good idea. Thanks

**Comment by ShkurtiA** [comment]
I have done a custom drawer item and it has the same purpose that you are asking:


I use it like this: `... .addDrawerItems( new TextSwitchDrawerItem().withName(R.string.menu).withIcon(R.drawable.eye).withIdentifier(3).setShowPoints(show).setListenerDrawerMapSiwtchCompat(this).withCheckable(false),....`

### Java code: 

 
    
    import android.content.Context;
    import android.graphics.drawable.Drawable;
    import android.support.v7.widget.SwitchCompat;
    import android.view.LayoutInflater;
    import android.view.View;
    import android.view.ViewGroup;
    import android.widget.CompoundButton;
    import android.widget.ImageView;
    import android.widget.TextView;
    
    import com.mikepenz.iconics.IconicsDrawable;
    import com.mikepenz.materialdrawer.model.BaseDrawerItem;
    import com.mikepenz.materialdrawer.model.PrimaryDrawerItem;
    import com.mikepenz.materialdrawer.util.PressedEffectStateListDrawable;
    import com.mikepenz.materialdrawer.util.UIUtils;

    
    /**
     * Created by Armando Shkurti on 2015-03-22.
     *
     */
    public class TextSwitchDrawerItem extends BaseDrawerItem<TextSwitchDrawerItem> implements CompoundButton.OnCheckedChangeListener {
    
        public boolean showPoints;
    
    
        @Override
        public String getType() {
            return "PRIMARY_ITEM";
        }
    
    
        @Override
        public int getLayoutRes() {
            return R.layout.material_drawer_txt_switch;
        }
    
    
        @Override
        public View convertView(LayoutInflater inflater, View convertView, ViewGroup parent) {
            Context ctx = parent.getContext();
    
            //get the viewHolder
            ViewHolder viewHolder;
            if (convertView == null) {
                convertView = inflater.inflate(getLayoutRes(), parent, false);
                viewHolder = new ViewHolder(convertView);
                convertView.setTag(viewHolder);
            } else {
                viewHolder = (ViewHolder) convertView.getTag();
            }
    
            //get the correct color for the background
            int selectedColor = UIUtils.decideColor(ctx, getSelectedColor(), getSelectedColorRes(), R.attr.material_drawer_selected, R.color.material_drawer_selected);
    
            //get the correct color for the text
            int color;
            if (this.isEnabled()) {
                color = UIUtils.decideColor(ctx, getTextColor(), getTextColorRes(), R.attr.material_drawer_primary_text, R.color.material_drawer_primary_text);
            } else {
                color = UIUtils.decideColor(ctx, getDisabledTextColor(), getDisabledTextColorRes(), R.attr.material_drawer_hint_text, R.color.material_drawer_hint_text);
            }
    
            int selectedTextColor = UIUtils.decideColor(ctx, getSelectedTextColor(), getSelectedTextColorRes(), R.attr.material_drawer_selected_text, R.color.material_drawer_selected_text);
    
            //get the correct color for the icon
            int iconColor;
            if (this.isEnabled()) {
                iconColor = UIUtils.decideColor(ctx, getIconColor(), getIconColorRes(), R.attr.material_drawer_primary_icon, R.color.material_drawer_primary_icon);
            } else {
                iconColor = UIUtils.decideColor(ctx, getDisabledIconColor(), getDisabledIconColorRes(), R.attr.material_drawer_hint_text, R.color.material_drawer_hint_text);
            }
            int selectedIconColor = UIUtils.decideColor(ctx, getSelectedIconColor(), getSelectedIconColorRes(), R.attr.material_drawer_selected_text, R.color.material_drawer_selected_text);
    
    
            //set the text for the name
            if (this.getNameRes() != -1) {
                viewHolder.name.setText(this.getNameRes());
            } else {
                viewHolder.name.setText(this.getName());
            }
    
            //set the background for the item
            UIUtils.setBackground(viewHolder.view, UIUtils.getDrawerItemBackground(selectedColor));
    
            //set the colors for textViews
            viewHolder.name.setTextColor(UIUtils.getTextColorStateList(color, selectedTextColor));
    
            /**
             * shtimi i switch
             * */
            viewHolder.switchCompat.setChecked(showPoints);
            viewHolder.switchCompat.setOnCheckedChangeListener(this);
    
            //define the typeface for our textViews
            if (getTypeface() != null) {
                viewHolder.name.setTypeface(getTypeface());
            }
    
            //get the drawables for our icon
            Drawable icon = UIUtils.decideIcon(ctx, getIcon(), getIIcon(), getIconRes(), iconColor, isIconTinted());
            Drawable selectedIcon = UIUtils.decideIcon(ctx, getSelectedIcon(), getIIcon(), getSelectedIconRes(), selectedIconColor, isIconTinted());
    
            //if we have an icon then we want to set it
            if (icon != null) {
                //if we got a different color for the selectedIcon we need a StateList
                if (selectedIcon != null) {
                    viewHolder.icon.setImageDrawable(UIUtils.getIconStateList(icon, selectedIcon));
                } else if (isIconTinted()) {
                    viewHolder.icon.setImageDrawable(new PressedEffectStateListDrawable(icon, iconColor, selectedIconColor));
                } else {
                    viewHolder.icon.setImageDrawable(icon);
                }
                //make sure we display the icon
                viewHolder.icon.setVisibility(View.VISIBLE);
            } else {
                //hide the icon
                viewHolder.icon.setVisibility(View.GONE);
            }
    
            return convertView;
        }
    
    
        public boolean isShowPoints() {
            return showPoints;
        }
    
    
        public TextSwitchDrawerItem setShowPoints(boolean showPoints) {
            this.showPoints = showPoints;
            return this;
        }
    
    
        ListenerDrawerMapSiwtchCompat listenerDrawerMapSiwtchCompat;
    
    
        public TextSwitchDrawerItem setListenerDrawerMapSiwtchCompat(ListenerDrawerMapSiwtchCompat listenerDrawerMapSiwtchCompat) {
            this.listenerDrawerMapSiwtchCompat = listenerDrawerMapSiwtchCompat;
            return this;
        }
    
    
        @Override
        public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
            showPoints = isChecked;
            listenerDrawerMapSiwtchCompat.onSwitchCompatCheckChange((SwitchCompat) buttonView, getIdentifier(), isChecked);
        }
    
    
        private static class ViewHolder {
            private View view;
            private ImageView icon;
            private TextView name;
            private SwitchCompat switchCompat;
    
    
            private ViewHolder(View view) {
                this.view = view;
                this.icon = (ImageView) view.findViewById(R.id.icon);
                this.name = (TextView) view.findViewById(R.id.name);
                this.switchCompat = (SwitchCompat) view.findViewById(R.id.map_switch);
            }
        }
    }

### XML Code:

    <?xml version="1.0" encoding="utf-8"?>
    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                    xmlns:tools="http://schemas.android.com/tools"
                    android:layout_width="match_parent"
                    android:layout_height="@dimen/material_drawer_item_primary"
                    android:paddingEnd="@dimen/material_drawer_vertical_padding"
                    android:paddingLeft="@dimen/material_drawer_vertical_padding"
                    android:paddingRight="@dimen/material_drawer_vertical_padding"
                    android:paddingStart="@dimen/material_drawer_vertical_padding">
    
        <ImageView
            android:id="@+id/icon"
            android:layout_width="@dimen/material_drawer_item_primary"
            android:layout_height="@dimen/material_drawer_item_primary"
            android:layout_gravity="center_vertical"
            android:layout_marginEnd="@dimen/material_drawer_item_padding"
            android:layout_marginRight="@dimen/material_drawer_item_padding"
            android:paddingBottom="@dimen/material_drawer_item_primary_icon_padding"
            android:paddingEnd="@dimen/material_drawer_item_primary_icon_padding_right"
            android:paddingRight="@dimen/material_drawer_item_primary_icon_padding_right"
            android:paddingTop="@dimen/material_drawer_item_primary_icon_padding"/>
    
        <TextView
            android:id="@+id/name"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_toEndOf="@id/icon"
            android:layout_toLeftOf="@+id/map_switch"
            android:layout_toRightOf="@id/icon"
            android:layout_toStartOf="@+id/map_switch"
            android:fontFamily="sans-serif-medium"
            android:gravity="center_vertical|start"
            android:lines="1"
            android:singleLine="true"
            android:textDirection="anyRtl"
            android:textSize="@dimen/material_drawer_item_primary_text"
            tools:text="Some drawer text"/>
    
        <android.support.v7.widget.SwitchCompat
            android:id="@+id/map_switch"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentEnd="true"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true"
            android:layout_marginRight="@dimen/gjashtembedhjet_dp"
            style="@style/SwitchCompatBckg"
            android:gravity="center"
            android:focusable="false"/>
    
    
    </RelativeLayout>

**Comment by mikepenz** [comment]
@ShkurtiA thank you ;).

**Comment by mikepenz** [comment]
the next version will have this function included. You can then just make the item checkable if you want it to be selectable

**Comment by ChainsDD** [comment]
Cool! I didn't notice that you made that last comment until after I made that pull request...

Is checkable the right term for that? I used the word selectable instead.

**Comment by mikepenz** [comment]
@ChainsDD oh sorry i commented a bit to late. Still thank you for the Pull Request. 

Yeah its probably the wrong term, but checkable is also in use for the PrimaryDrawerItem if it is not checkable or does not have a active selection state. 

So perhaps a refractor to selectable can help for `v3.0.0`
