### ISSUE TITLE
DrawerToggle missing after update to v2.9.7

### ISSUE THREAD

**Issue by destil** [mikepenz/MaterialDrawer#322]
Hi,
I have recently updated your library from v2.0.8 to v2.9.7. and I updated support library from v22.0.0 to v22.1.1.

Before the update there was a hamburger icon, now there is just a back arrow and when I click it, I get NullPointerException stating that ActionBarDrawerToggle is null. 

I'm using ActionBarActivity (now AppCompatActivity), no Toolbar. 

I tried many things without success, can you help me please?

**Comment by destil** [comment]
I solved it by migrating to Toolbar. But the issue is still there for those not using Toolbar.

**Comment by mikepenz** [comment]
@destil this is no real issue with the newest AppCompat library there should be a toolbar which is passed to the ActionBarDrawerToggle. You get a NullPointerException by default or if you try to call result.getActionBarDrawerToggle()?

**Comment by destil** [comment]
I get Nullpointer in onOptionsItemSelected when I click the UP arrow (which should be hamburger menu).
I had simple setup .withActivity(this)..withActionBarDrawerToggleAnimated(true)

**Comment by mikepenz** [comment]
@destil a nullPointer in onOptionsItemSelected? Can you post the stacktrace. because ActionBar is working in the sample app

**Comment by destil** [comment]
I don't have a stacktrace since I reworked my app to support Toolbar.

But I see possible problem in the sample app:
When I change the line 33 in ActionBarDrawerActivity like this
'.withActionBarDrawerToggle(false)' -> '.withActionBarDrawerToggle(true)'
it still shows Up button, no hamburger menu.

**Comment by mikepenz** [comment]
@destil the call `withActionBarDrawerToggle` just toggles if there will be a `ActionBarDrawerToggle` set to the toolbar. this will not change anything for the ActionBar. you have to check these methods:

```java
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setHomeButtonEnabled(false);
```

**Comment by destil** [comment]
I'm confused - how to display hamburger menu in the ActionBar?

**Comment by mikepenz** [comment]
You can try to set the ActionBarDrawerToggle to the toolbar doing the following:

```java
mActionBarDrawerToggle = new ActionBarDrawerToggle(mActivity, mDrawerLayout, R.string.drawer_open, R.string.drawer_close) {
                @Override
                public void onDrawerOpened(View drawerView) {
                    super.onDrawerOpened(drawerView);
                }

                @Override
                public void onDrawerClosed(View drawerView) {
                    super.onDrawerClosed(drawerView);
                }

                @Override
                public void onDrawerSlide(View drawerView, float slideOffset) {
                        super.onDrawerSlide(drawerView, slideOffset);
                }
            };
            mActionBarDrawerToggle.syncState();
```
