### ISSUE TITLE
Is there a way to make selected item's text bold?

### ISSUE THREAD

**Issue by magicgoose** [mikepenz/MaterialDrawer#323]
Like in Google Play, for example:
![google-play](https://cloud.githubusercontent.com/assets/1442206/7669627/d878eeba-fc86-11e4-927f-d49a869aff9c.png)

**Comment by mikepenz** [comment]
@magicgoose not by default. You can implement your CustomDrawerItem to do this. 

As of the Google Material Design Guidelines it is correct without bold:
http://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-content
