### ISSUE TITLE
Smaller profile icon not loading

### ISSUE THREAD

**Issue by rabyunghwa** [mikepenz/MaterialDrawer#326]
Hey. I seem to have an issue with the top profile icon loading. The smaller profile icon loads fine but the big one on top doesn't load. What do you think is causing this problem? FYI I am trying to load a local bitmap into the ImageView not a url. Thanks in advance.

**Comment by mikepenz** [comment]
how do you set the bitmap to the ImageView?

**Comment by rabyunghwa** [comment]
Hey man. Here is part of the code. The bitmap is saved locally and can be retrieved like following. The smaller icon loads fine but the bigger one doesnt load. Is there any external API I can use to load the bigger icon manually? 

"Bitmap bitmap = BitmapLoader.getBitmapFromFile(file.getAbsolutePath(), dm.widthPixels, (int) (density * 300));

            DrawerImageLoader.init(new DrawerImageLoader.IDrawerImageLoader() {
                @Override
                public void set(ImageView imageView, Uri uri, Drawable placeholder) {
                    Picasso.with(imageView.getContext()).load(uri).placeholder(placeholder).into(imageView);
                }

                @Override
                public void cancel(ImageView imageView) {
                    Picasso.with(imageView.getContext()).cancelRequest(imageView);
                }

                @Override
                public Drawable placeholder(Context ctx) {
                    return null;
                }
            });

            final IProfile profile = new ProfileDrawerItem().withName("").withEmail("").withIcon(bitmap);"

**Comment by mikepenz** [comment]
@rabyunghwa then the DrawerImageLoader is obsolete because you don't use it. 

You set the bitmap to your profile and then it's wrong? do you change it at a later time or what's happening?

**Comment by rabyunghwa** [comment]
Haha I have solved the problem dude. Instead of loading the bitmap directly, I first convert the bitmap to a BitmapDrawable and then load it. Now both icons load pretty well.
Here is the code.

"
DisplayMetrics dm = new DisplayMetrics();
getWindowManager().getDefaultDisplay().getMetrics(dm);
double density = dm.density;
Bitmap bitmap = BitmapLoader.getBitmapFromFile(file.getAbsolutePath(), dm.widthPixels, (int) (density * 300));
Drawable d = new BitmapDrawable(getResources(), bitmap);
            
final IProfile profile = new ProfileDrawerItem().withName("").withEmail("").withIcon(d);
"

**Comment by rabyunghwa** [comment]
Yes dude. If i set the bitmap directly to my profile then the bigger icon wouldn't load. I have solved this problem by converting the bitmap to a BitmapDrawable first and then load it to the ImageView. Still Don't know what went wrong though. I did check the source code and it seemed that everything was right.

**Comment by mikepenz** [comment]
@rabyunghwa i have found the issue with bitmaps. will be fixed in the next version

**Comment by rabyunghwa** [comment]
ok man.
