### ISSUE TITLE
Selected Item Set back to default after Orientation Change

### ISSUE THREAD

**Issue by RubenGees** [mikepenz/MaterialDrawer#327]
This only happens in the Sticky Section. When I select my Item "Help" in the sticky section and rotate the device, the default item is selected. I think that happens because of an error in your savedInstanceState Handling.

**Comment by mikepenz** [comment]
@RubenGees that's true. because the stickyItems do not have a position like the items in the drawer. so i can't remember the exact positioning.

**Comment by mikepenz** [comment]
This issue is a bit of a bigger thing as the footer is managed separately..
will have to see how i can get this in without adding a lot of unnecessary logics and checks..

**Comment by RubenGees** [comment]
Okay, no prop.
Looking forward to your solution! Thank you for your great work.
