### ISSUE TITLE
withDrawerItems.

### ISSUE THREAD

**Issue by Grozny** [mikepenz/MaterialDrawer#328]
why do you use ArrayList instead SparseArray?

**Comment by mikepenz** [comment]
In fact i assume that the difference for the few items is not noticeable.

Any real noticeable difference?

**Comment by Grozny** [comment]
http://developer.android.com/reference/android/util/SparseArray.html

http://stackoverflow.com/questions/25444226/difference-between-sparsearray-vs-arraylist

2015-05-18 18:32 GMT+01:00 Mike Penz <notifications@github.com>:

**Comment by mikepenz** [comment]
As of the stackoverflow answer no advantage for short lists.

Why do I still like ArrayLists is probably that I normally work as backend
engineer with plain java only.

Rui Oliveira <notifications@github.com> schrieb am Mi., 20. Mai 2015 10:16:
