### ISSUE TITLE
Icons stay tinted on the rest of the app

### ISSUE THREAD

**Issue by jpmassena** [mikepenz/MaterialDrawer#329]
Hey,

I think I found a bug with your awesome library.

If I had items to the drawer with 
```java
.withIcon(R.drawable.icon24dp)
 .withIconTintingEnabled(true)
```
the icons are correctly tinted as I want them to be.

The issue is that if I use the same resource elsewhere in my app, the icon will not tint to the color I have set for it, but will (mostly) stay with the `unselected` color of the drawer.

Maybe you could mutate the Drawables before painting them?

I guess I can load a Drawable mutated from the resource too, but I think it would be cleaner if it was done inside the library.

**Comment by mikepenz** [comment]
@jpmassena thanks for the info. yeah you are right. i do not mutate the drawable right now. but if you plan to reuse the drawable this will cause troubles. i will look into it

**Comment by alexdemers** [comment]
Why is this closed as it is not fixed? I'm having the same problem right now with v5.6.0. I can't use the drawables of the DrawerItems anywhere else as they are not mutated and the tinting affects the drawable's state.

This should be the solution for using the drawables in the DrawerItems: http://stackoverflow.com/a/30928051/140212

**Comment by mikepenz** [comment]
@alexdemers please just provide the `mutated` drawable to the drawer instead. Should do the same.
