### ISSUE TITLE
Palette Target

### ISSUE THREAD

**Issue by danielgomezrico** [mikepenz/MaterialDrawer#331]
Hi

I just wanted to suggest https://github.com/florent37/PicassoPalette for the palette, it´s simple and do a great job with cache.

**Comment by danielgomezrico** [comment]
Wrong repo, should be on https://github.com/mikepenz/wallsplash-android

**Comment by mikepenz** [comment]
@danielgomezrico i already use the system palette from the compat lib. and have my own cache ;).
