### ISSUE TITLE
Mark DrawerItem as selected without executing action

### ISSUE THREAD

**Issue by jdzuri** [mikepenz/MaterialDrawer#332]
Hi,

Let me know if there any way to mark as selected a DrawerItem without executing the event, 
only displayed as selected. 

**setSelection** isn't valid for this because runs the event.

Thanks

**Comment by mikepenz** [comment]
@jdzuri set selection is valid because it allows you to pass an boolean with the info if it should fire the event ;). 

`setSelection(int position, boolean fireOnClick)`

**Comment by jdzuri** [comment]
Thanks @mikepenz . An oversight on my part haven't seen this method...

**Comment by mikepenz** [comment]
No problem :D
