### ISSUE TITLE
Action bar is always on top of the drawer

### ISSUE THREAD

**Issue by phanghos** [mikepenz/MaterialDrawer#333]
No matter what I do, the action bar is always on top of the drawer

I added these lines:

    .withTranslucentStatusBar(false)
    .withActionBarDrawerToggle(false)

and used MaterialDrawerTheme.ActionBar as theme, but it's not working for me.

**Comment by mikepenz** [comment]
@phanghos if you use the good old `ActionBar` it is not possible to Display the drawer on top of it. This is a limitation of the Android System. 

If you want a drawer with the full height and a translucent StatusBar you have to use a Toolbar. 

As a sidefact. You should switch to the `Toolbar`. It will give you so much new possibilities. The switch is done very easily. Just take a look at the sample app

**Comment by phanghos** [comment]
Thank you for the quick reply! That's what I was about to conclude. By using the Toolbar I was getting the result I wanted. I just wasn't sure whether it was possible with the Action Bar.

**Comment by mikepenz** [comment]
@phanghos as far as i know (and i hope i am not wrong :D) it is not possible. i found no "hack" or any api to do this. 



If someone has an idea let me know ;)

**Comment by phanghos** [comment]
@mikepenz I'm almost conviced that it is not possible. As I said, I tried many different combinations and none of them worked.

**Comment by mikepenz** [comment]
@phanghos yeah i found out the same.

**Comment by parisaalamshahi** [comment]
hello mike. I have an Error with library.can you help me ? this is my code:

val item1 = PrimaryDrawerItem().withIdentifier(1).withName("لیست ویدیوها")
            .withIcon(R.mipmap.app_icon).withOnDrawerItemClickListener(this)

//
        val item2 =
            SecondaryDrawerItem().withIdentifier(2).withName("لیست پادکست ها").withIcon(R.mipmap.app_icon)
                .withOnDrawerItemClickListener(this)
////
        val item3 =
            SecondaryDrawerItem().withIdentifier(3).withName("سوالات متداول").withIcon(R.mipmap.app_icon)
                .withOnDrawerItemClickListener(this)
//
        val item4 =
            SecondaryDrawerItem().withIdentifier(4).withName("پشتیبانی").withIcon(R.mipmap.app_icon)
                .withOnDrawerItemClickListener(this)

         drawer = DrawerBuilder()
            .withActivity(this)
            .addDrawerItems(
                item1,
                item2,
                item3,
                item4
            )
            .withDrawerGravity(Gravity.END)
            .build()

as soon as run I'm getting this error:

java.lang.NoSuchMethodError: No virtual method withCornerRadius(F)Lcom/google/android/material/shape/ShapeAppearanceModel; in class Lcom/google/android/material/shape/ShapeAppearanceModel; or its super classes (declaration of 'com.google.android.material.shape.ShapeAppearanceModel' appears in /data/app/com.zavosh.itfamily-2/base.apk)
        at com.mikepenz.materialdrawer.model.AbstractDrawerItem.getShapeAppearanceModel(AbstractDrawerItem.kt:420)
        at com.mikepenz.materialdrawer.model.BaseDescribeableDrawerItem.bindViewHelper(BaseDescribeableDrawerItem.kt:64)
        at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.kt:51)
        at com.mikepenz.materialdrawer.model.AbstractBadgeableDrawerItem.bindView(AbstractBadgeableDrawerItem.kt:15)
        at com.mikepenz.fastadapter.listeners.OnBindViewHolderListenerImpl.onBindViewHolder(OnBindViewHolderListenerImpl.kt:21)
        at com.mikepenz.fastadapter.FastAdapter.onBindViewHolder(FastAdapter.kt:390)

**Comment by mikepenz** [comment]
You have to use the `material components` v1.1.x at least
