### ISSUE TITLE
Fixed DrawItem

### ISSUE THREAD

**Issue by gearlles** [mikepenz/MaterialDrawer#334]
Is is possible to fix DrawerItem's on the bottom of the Drawer? Just like the Inbox app which has the last two items at a fixed position:

https://gfycat.com/FearfulFrayedBalloonfish

**Comment by mikepenz** [comment]
@gearlles please check out the sample app. Yes this is possible.  

https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/ComplexHeaderDrawerActivity.java#L115
