### ISSUE TITLE
Color of items when user click them in pre-lollipop

### ISSUE THREAD

**Issue by NogerbekNurzhan** [mikepenz/MaterialDrawer#335]
Hello! First of all Great Thanks for this project! I have 2 question.

1 question: How I can change color when user click items? I noticed that in lollipop when user click items in NavDrawer in will be grey with ripple effect but in pre-lollipop in became deep blue color and you cant see text and icon because of that. So is it possible to make color in pre-lollipop the same as in lollipop.

2 question: Is it possible to set height of header? I want to add image with bigger height than in your example.

**Comment by mikepenz** [comment]
@NogerbekNurzhan 

1. the library uses the system default selection drawable. this is different in pre lollipop devices. as far as i know those are not changeable by theme or the default does not change with the primaryColor. The only solution would be to provide a custom drawable to do so. Until now i had decided to don't do so. 
With my tests the text should be still readable..

2. you can set any header you like. withHeader. You can't change the height of the AccountHeader as this is defined in the guidelines and there is no other size you should use

**Comment by mikepenz** [comment]
@NogerbekNurzhan drawing the selector below the text will probably improve it again. 

I talk about this line:
https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L1407

If i change it to > API 21 it will show the Ripple on Top and the normal selector in the Background. 

Theoretically it's possible to get the ListView from the result object and change the ListViews selector

**Comment by NogerbekNurzhan** [comment]
Thanks for information. I changed it like here below and Text became visable. Guidelines of course is good but sometimes you need little bit more. By the way thats what I have in my header when I use my Image. As you see Image looks strange (shrink). For thats why I asked you about height of Header. Anyway thanks.

           if (Build.VERSION.SDK_INT > 21) {
                mListView.setDrawSelectorOnTop(true);
            }

![fab_shadow](https://cloud.githubusercontent.com/assets/8999232/7744302/04bbbf58-ffc4-11e4-9166-202d1cbd11c4.png)

**Comment by mikepenz** [comment]
@NogerbekNurzhan yeah will change it to draw the selector below. 

About the header. you can set any custom layout as header so the height is defined by you then.
