### ISSUE TITLE
How to update the description of PrimaryDrawerItem?

### ISSUE THREAD

**Issue by ruinpsilva** [mikepenz/MaterialDrawer#336]
I'm trying to update the description of a PrimaryDrawerItem but, I'm haven't succeed.
Can anybody give me a hand?

**Comment by mikepenz** [comment]
@ruinpsilva if you want to set it use this `withDescription()`
if you want to update an existing item, define an identifier for the item and just change the description of it at a later time. there a method on the `result` object which allows you to update a DrawerItem

**Comment by ruinpsilva** [comment]
Thanks! I'm going to try it!

**Comment by mikepenz** [comment]
@ruinpsilva great. just let me know if there are more questions. Or head over to gitter
