### ISSUE TITLE
drawer closing when activity finishes

### ISSUE THREAD

**Issue by bbetter** [mikepenz/MaterialDrawer#339]
i need drawer not to close when activity finishes, how to prevent it from finishing after i click

**Comment by mikepenz** [comment]
@bbetter if which activity finishes? if the activity with the drawer is gone there is no more drawer to show. you can disable the close if you click on a item with `result.withCloseOnClick(false)`

**Comment by bbetter** [comment]
but if i need it just for one item , do i need to handle close in onDraweItemClick  by myself

**Comment by mikepenz** [comment]
@bbetter yes. having this indicator per DrawerItem would be so much overhead that it makes no sense.
