### ISSUE TITLE
Non selectable items

### ISSUE THREAD

**Issue by yoavst** [mikepenz/MaterialDrawer#34]
For example: Settings, help.

**Comment by Rainer-Lang** [comment]
about also.

**Comment by yoavst** [comment]
can you explain what should be done to make item non selectable but clickable?

**Comment by mikepenz** [comment]
It will be in the final documentation. And the call to disable the selection will be in v1.0.0

it's really easy. just do the following:

https://github.com/mikepenz/MaterialDrawer/commit/9f7095b06ceaddd5090171b5cc3f06b0c22110df

**Comment by yoavst** [comment]
Thanks!
