### ISSUE TITLE
How to use a single drawer for every activity

### ISSUE THREAD

**Issue by jd-alexander** [mikepenz/MaterialDrawer#341]
I want to use the material drawer in all activities instead of using a  fragment based navigation. I explored the samples and I also saw that the library inflates the drawer layout but im not sure how to go about configuring it. What I have done so far is to create a base activity with the drawer then extend other activities from it but when I do the drawer isn't available so can I get some guidance. Thanks.

**Comment by mikepenz** [comment]
This is no valid navigation pattern. The drawer should only be available in the root activity. if there are different views in the root you should use fragments. if you jump to other activites those should not have a drawer. 

still you can do this with the drawer. but i highly recommend to do it like it should be done.

**Comment by ammar786-1** [comment]
Hi Mike, 

Although I agree with you that a navigation drawer in any other activity other than the root is kind of not a valid navigation pattern, but Google itself uses this pattern in the Play Store app. Go into the detail activity of an app, then swipe from the left edge to reveal the drawer. There is no indication of a drawer being there, but it's there.

**Comment by mikepenz** [comment]
@ammar786-1 i know ;). it was just a hint to follow the guidelines (and we all know google itself doesn't do this :P)

about the main issue. I think the BaseActivity he has written must be wrong, there is no thing in the Drawer which should prevent this. 

In fact it should work exactly as in any other default activity. as seen in the sample app.

**Comment by raghunandankavi2010** [comment]
@mikepenz But the google io schedule app has drawer in all activities although they finish the activity when you navigate to different screen probably to avoid complexities of back pattern.

@ammar786-1 Follow Google io Schedule app on github. It has a BaseActivity from which all activites extend. Also do make changes like extending AppCompatActivity and themes...
