### ISSUE TITLE
Lock Drawer

### ISSUE THREAD

**Issue by patelakshay13890** [mikepenz/MaterialDrawer#342]
How can I lock drawer from opening it in some fragment ??

**Comment by mikepenz** [comment]
I've added this to the FAQ section as this is the second time this was asked:
https://github.com/mikepenz/MaterialDrawer/blob/master/README.md#can-i-lock-the-drawer


#####Can I lock the Drawer
As the MaterialDrawer will just create a normal DrawerLayout (with some magic around it) everything a normal
DrawerLayout can do is also available in the MaterialDrawer. 
```java
//get the DrawerLayout from the Drawer.Result
DrawerLayout drawerLayout = result.getDrawerLayout();
//do whatever you want with the Drawer. Like locking it. 
drawerLayout.setDrawerLockMode(int lockMode); //or (int lockMode, int edgeGravity)
```

**Comment by AkshayPathak** [comment]
Well when I try this in a fragment, it gives a null object reference error. Where would I put these lines of code to disable the drawer in a fragment?

**Comment by mikepenz** [comment]
you have to do this in your activity. perhaps an method which you can then call from your fragments.

**Comment by AkshayPathak** [comment]
I see, and which fragment method would I call in in? Oncreate(), onCreateView() or onActivityCreated(). By the way, thanks for the super fast answer :)

**Comment by mikepenz** [comment]
No you have to create a method like `disableDrawer()` inside your activity. and inside your fragment you call this method of the activity. (still this is really much overhead)

The easiest solution is to lock the drawer inside your `onDrawerItemClick` listener where you switch the fragments.

**Comment by AkshayPathak** [comment]
Ok, thanks!
