### ISSUE TITLE
Question regarding styling

### ISSUE THREAD

**Issue by Anatidae-Project** [mikepenz/MaterialDrawer#343]
Mike, really enjoying using your drawer!

I have a question regarding styling. Overall I am using MaterialDrawerTheme.Light.TranslucentStatus as it puts the app generally to what I'm looking for.

However, my drawer and title bar have dark colors in the backgrounds in contrast to the rest of the app. The toolbar isn't an issue. But the drawer - if I don't use .withIconColorRes, it pulls from a black/darn grey color. But what I want is to have my icons pull from MaterialDrawerTheme.TranslucentStatus while the rest of the app has the light theme.

Setting the color in style  <item name="material_drawer_icons">@color/white</item> has no effect it seems. The icon still remains dark.

How do you suggest theming the icons in the drawer? Where the drawer should be using a dark theme while the rest of the app is based on a light theme?

Thanks!

**Comment by mikepenz** [comment]
@Anatidae-Project normally the drawer should be light if the rest of the app is dark. 
If you need a custom style i would recommend you to create a new theme based on the MaterialDrawerTheme.Light (as parent) and set the drawer colors from the dark theme.

Your custom theme could be something like this: https://github.com/mikepenz/MaterialDrawer#custom-style---stylesxml

You can then just set the dark colors of the drawer instead of the light variants. (material_drawer_background --> material_drawer_background_dark)

**Comment by mikepenz** [comment]
```xml
<style name="CustomTheme" parent="MaterialDrawerTheme.Light">
        <!-- ...and here we setting appcompat’s color theming attrs -->
        <item name="colorPrimary">@color/material_drawer_primary</item>
        <item name="colorPrimaryDark">@color/material_drawer_primary_dark</item>
        <item name="colorAccent">@color/material_drawer_accent</item>

        <!-- MaterialDrawer specific values -->
        <item name="material_drawer_background">@color/material_drawer_background_dark</item>
        <item name="material_drawer_icons">@color/material_drawer_icons_dark</item>
        <item name="material_drawer_primary_text">@color/material_drawer_primary_text_dark</item>
        <item name="material_drawer_primary_icon">@color/material_drawer_primary_icon_dark</item>
        <item name="material_drawer_secondary_text">@color/material_drawer_secondary_text_dark</item>
        <item name="material_drawer_hint_text">@color/material_drawer_hint_text_dark</item>
        <item name="material_drawer_divider">@color/material_drawer_divider_dark</item>
        <item name="material_drawer_selected">@color/material_drawer_selected_dark</item>
        <item name="material_drawer_selected_text">@color/material_drawer_selected_text_dark</item>
        <item name="material_drawer_header_selection_text">@color/material_drawer_header_selection_text_dark</item>
    </style>
```

**Comment by mikepenz** [comment]
What happens here is that you mix up the light theme variant from Android with the dark style i have defined for the drawer. 

If you just want a dark toolbar i would suggest that you use the `DarkToolbar` theme and also set the theme on the toolbar itself

**Comment by Anatidae-Project** [comment]
My style is below. BUt this results in white text in the drawer items and black icons. If I change to <item name="material_drawer_icons">@color/material_drawer_dark_icons</item> I still get black icons. 

~~~
    <style name="EnforcerTheme" parent="MaterialDrawerTheme.Light.TranslucentStatus">
        <!-- ...and here we setting appcompat’s color theme attrs -->
        <item name="colorPrimary">@color/primary</item>
        <item name="colorPrimaryDark">@color/primaryStatusBar</item>
        <item name="colorAccent">@color/secondary</item>

        <!-- MaterialDrawer specific values -->
        <item name="material_drawer_background">@color/secondary</item>
        <item name="material_drawer_icons">@color/material_drawer_icons</item>
        <item name="material_drawer_primary_text">@color/material_drawer_dark_primary_text</item>
        <item name="material_drawer_secondary_text">@color/material_drawer_dark_secondary_text</item>
        <item name="material_drawer_hint_text">@color/material_drawer_dark_hint_text</item>
        <item name="material_drawer_divider">#ffffffff</item>
        <item name="material_drawer_selected">#32ffffff</item>
        <item name="material_drawer_selected_text">#ffffffff</item>
        <item name="material_drawer_header_selection_text">@color/material_drawer_dark_primary_text</item>

        <!-- CAB :D -->
        <item name="windowActionModeOverlay">true</item>
    </style>
~~~

**Comment by mikepenz** [comment]
because you miss one line of my above posted sample ;)

```xml
        <item name="material_drawer_primary_icon">@color/material_drawer_dark_primary_icon</item>
```
