### ISSUE TITLE
DrawerItem can't deselect itself

### ISSUE THREAD

**Issue by Conradowatz** [mikepenz/MaterialDrawer#345]
I have a DrawerItem in my footer list, that should only show a dialog. So when I click it, it shouldn't select itself. Until 3.0.0 I count just do navigationDrawer.setSelection(navigationDrawer.getCurrentSelection()); in the onItemClick method, but that doesn't work anymore. Any fix?
Btw. thanks for this awsome libary :+1:

**Comment by mikepenz** [comment]
@Conradowatz what do you mean with footer list?

in fact it should still work as before. It is just different if you select a stickyFooterItem then it will change the `currentSelection` index to `-1` and the `currentFooterSelection` to the position in the footer

**Comment by Conradowatz** [comment]
It is in the footer section. I tested it and it looks like currentSelection gets set before onItemClick now, so it doen't work anymore. I was able to fix it by having a private int, which keeps track of what is currently selected.

**Comment by mikepenz** [comment]
@Conradowatz ok. I think this is the best practice now. It was wrong before to set the new currentSelection after the event :P
