### ISSUE TITLE
IDrawerItem should have setEnabled()

### ISSUE THREAD

**Issue by paulgavrikov** [mikepenz/MaterialDrawer#347]
Usecase: Dynamic enabling / disabling of items.

Temp. Workaround:
```

public void setItemEnabled(int identifier, boolean enabled) {


        ArrayList<IDrawerItem> items = result.getDrawerItems();
        int pos = result.getPositionFromIdentifier(identifier);
        IDrawerItem item = items.get(pos);
        if(item instanceof  PrimaryDrawerItem)
                ((PrimaryDrawerItem) item).setEnabled(enabled);
        else if(item instanceof  SecondaryDrawerItem)
            ((SecondaryDrawerItem) item).setEnabled(enabled);
    }

**Comment by mikepenz** [comment]
@paulgavrikov i know. in some cases it makes sense, but the `setEnabled()` method is not available in items like the `SectionDrawerItem` or the `DividerDrawerItem`

**Comment by mikepenz** [comment]
@paulgavrikov i would recommend you just do the following:

```java
if (item instanceof BaseDrawerItem) {
     ((BaseDrawerItem) item).setEnabled(enabled);
}
```

(The PrimaryDrawerItem, SecondaryDrawerItem and Switch/ToggleDrawerItem implement the BaseDrawerItem)

**Comment by paulgavrikov** [comment]
Okay, thank you. Keep on doing that great lib!

**Comment by mikepenz** [comment]
@paulgavrikov thanks ;)
