### ISSUE TITLE
Simple Drawer header with just one circular picture and no dropdowns

### ISSUE THREAD

**Issue by somghosh** [mikepenz/MaterialDrawer#350]
I am looking to make a simple Drawer header as below, with no dropdown/profile chooser at all. Is ther an easy way to do it?

I tried doing this

	result = new Drawer()
	                .withActivity(this)
	                .withToolbar(mToolbar)
	                .withHeader(R.layout.header_plain) // where this is my layout and instead of imageview as in the example/sample, I put a custom layout, but does not seem to work
					

#xml
					
	<?xml version="1.0" encoding="utf-8"?>

	<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
	    xmlns:tools="http://schemas.android.com/tools"

	    android:layout_width="match_parent"
	    android:layout_height="72dp"
	    android:background="@color/green"
	    android:paddingLeft="16dp"
	    android:orientation="vertical"
	    android:gravity="center_vertical"
	    >

	    <ImageView
	        android:id="@+id/drawer_user_image_iv"
	        android:layout_width="48dp"
	        android:layout_height="48dp" />
	    <TextView
	        android:id="@+id/drawer_user_name_tv"
	        android:layout_width="wrap_content"
	        android:layout_height="wrap_content"
	        android:text="John Smith"
	        android:textColor="@color/black"

	        />

	</LinearLayout>

![screenshot_2015-05-08-15-44-03](https://cloud.githubusercontent.com/assets/5731118/7790285/51e93478-027a-11e5-9a16-c2fede2f5fa4.png)

**Comment by paulgavrikov** [comment]
```
AccountHeader headerResult = new AccountHeaderBuilder()
                ....
                .withSelectionListEnabledForSingleProfile(false)

**Comment by mikepenz** [comment]
If you just set one profile in the `AccountHeader` and set `.withSelectionListEnabledForSingleProfile(false)` you will get this:
![screenshot_2015-05-25-13-05-38](https://cloud.githubusercontent.com/assets/1476232/7796367/0fca0ca6-02df-11e5-9a5e-61c353f3dc18.png)

If you add `.withCompatctStyle(true)` you will get this:
![screenshot_2015-05-25-13-06-09](https://cloud.githubusercontent.com/assets/1476232/7796364/0e05f1c8-02df-11e5-9e94-8d305311c511.png)
