### ISSUE TITLE
Disable menu highlight

### ISSUE THREAD

**Issue by MGaetan89** [mikepenz/MaterialDrawer#351]
Thanks for this great library!

I would like to know if there is an option to disable menu highlighting when it is selected?
I have a couple of menu items that display `AlertDialog`s, so I don't want the selected menu item to be changed, but still want to support click on them obviously (so I can't use `withEnabled()` I guess).

**Comment by mikepenz** [comment]
@MGaetan89 please check the sample app. there is a method called `withCheckable(false)`

**Comment by MGaetan89** [comment]
Sorry, I missed that method ...
Thanks for your help.
