### ISSUE TITLE
Possible Bug with Back Button when Using Fragments

### ISSUE THREAD

**Issue by Endud** [mikepenz/MaterialDrawer#353]
To demonstrate the problem, I have created a gif. Check it out here: http://i.giphy.com/xTiTnijrMHV4ky3lQc.gif

Let me give a quick overview: To start off, I opened and closed the drawer from the Add Assignment Fragment to show that is it's working. Next I tapped the Circular Add button which starts another fragment (Add Assignment Fragment). The Hamburger icon is now replaced with the back arrow and I disabled the navigation drawer in this fragment. The problem occurs when the back arrow (up button) is clicked which for some reason causes the navigation drawer to show instead of actually going back.

In my Add Assignment Fragment, I added the line in my onActivityCreated to show the back arrow:
```
actionBar.setDisplayHomeAsUpEnabled(true)
```

I am also checking for back button click in this method of the same fragment
```
@Override
public boolean onOptionsItemSelected(MenuItem item) {
    switch (item.getItemId()) {
        case android.R.id.home:
            getActivity().onBackPressed();
            return true;
    }
    return true;
}
```

Can you confirm if it's a bug or is it an error on my side. 
By the way, thank you for this awesome library and I really appreciate your work.

**Comment by mikepenz** [comment]
@Endud the MaterialDrawer will automatically define the default logic for the Arrow action on top to close and open the drawer. If you want to specify your own logic i would recommend that you add your own logic to open close the drawer and handle the arrow on top on your own. (just don't pass the toolbar to the Drawer)

**Comment by mikepenz** [comment]
@Endud or you can also pass an `OnDrawerNavigationListener` via the `withOnDrawerNavigationListener` and then just return true if you have consumed the event and want to do something on your own.

**Comment by mikepenz** [comment]
@Endud just closed it we can still discuss here.

**Comment by Endud** [comment]
Hmmm, the second choice seems more elegant but I am not sure how to implement my logic inside it. I tried looking for the documentation but I was not able to find it as the closest I found was [DrawerLayout.DrawerListener.](https://developer.android.com/reference/android/support/v4/widget/DrawerLayout.DrawerListener.html) I understand that you must be quite busy and if you don't have time to help me out, that's completely fine with me. I am just wondering though, would it be possible for me to implement my logic in the libraries code? If so can you please provide me with where I would do that?

**Comment by mikepenz** [comment]
@Endud no i don't think that you should do it inside the library code. 

if you are not sure about the drawerListener i would really recommend that you just handle the ActionBarDrawerToggle (or the up and hamburger arrow) on your own. 

And depending on what you do and on where you are you open the drawer on the click or not.
