### ISSUE TITLE
Seems bug in getFooterPositionFromIdentifier

### ISSUE THREAD

**Issue by GreenSkinMonster** [mikepenz/MaterialDrawer#354]
Hi,

Compare to getPositionFromIdentifier, it should return position of item, not identifier.

https://github.com/mikepenz/MaterialDrawer/blob/06177cae88ea707653101dc84c377849374019d3/library/src/main/java/com/mikepenz/materialdrawer/DrawerUtils.java#L163

**Comment by mikepenz** [comment]
@GreenSkinMonster yes you are right. I will look at this later today
