### ISSUE TITLE
question regarding the return value of Drawer.OnDrawerItemClickListener().onItemClick()

### ISSUE THREAD

**Issue by simonckenyon** [mikepenz/MaterialDrawer#355]
i could not find a description.
but from my experiments if you return true then the drawer does not close.
is this the intended behaviour?

**Comment by mikepenz** [comment]
@simonckenyon there is a comment on the listener. so if you include the docs you should see it. 

https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L797

The boolean values just states if the event was consumed. if not i will finish it with closing the drawer. this can be used to just close the drawer for specific items...
