### ISSUE TITLE
set compact header padding

### ISSUE THREAD

**Issue by ToonvanStrijp** [mikepenz/MaterialDrawer#356]
![wrong](https://cloud.githubusercontent.com/assets/11893063/7810895/5ce5f974-03a6-11e5-8016-38c4d86879cd.jpg)

How can i change the top padding of the compact header?... i want it to be null so i get this result (photoshopped it)

![good](https://cloud.githubusercontent.com/assets/11893063/7810898/6179feea-03a6-11e5-97a8-d09b916bf996.jpg)

**Comment by mikepenz** [comment]
Add `.withTranslucentStatusBar(false)` to your Drawer and AccountHeader

**Comment by mikepenz** [comment]
@ToonvanStrijp You have a different badge there. Can you share the DrawerItem or badge logic you have? It looks really good?

**Comment by ToonvanStrijp** [comment]
i've made a custom textview... doenst work properly yet:

public class SquereTextView extends TextView {

    public SquereTextView(Context context) {
        super(context);
    }

    public SquereTextView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public SquereTextView(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);

    }

    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
        int width = getMeasuredWidth();
        int heigth = getMeasuredHeight();
        width = width+20;
        heigth = heigth+20;
        int dimen = (width > heigth) ? heigth : width;

        setMeasuredDimension(dimen, dimen);

    }

}


I want it to resize as a square, within the text, but if the te text is bigger then 1000 or 100 its not resizing. so any help is welcome :). But i did ad this custom textview.

second:
i'd add this custom drawable

<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <solid android:color="?material_drawer_bagde_background_color"/>

</shape> 

and als last:

add this to your item view (primaryitem):

<com.mikepenz.materialdrawer.view.SquereTextView
        android:id="@+id/badge"
        android:layout_width="20dp"
        android:layout_height="wrap_content"
        android:textSize="@dimen/material_drawer_item_primary_text"
        android:lines="1"
        android:singleLine="false"
        tools:text="99"
        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true"
        android:nestedScrollingEnabled="false"
        android:background="@drawable/circle_badge"
        android:layout_centerInParent="true"
        android:gravity="center"
        android:elevation="3dp"
        android:layout_marginRight="1dp" />

the 1dp margin right if for the shadow of the elevation.


almost forgot:

add this to the attrs file:

<attr name="material_drawer_bagde_background_color" format="color|reference" />

so you can change the color in the theme folder.


I think i forget a couple of things. Cause you also need to add or change some things in the theme file to make te custom background color work. And also do you need to change the viewholder :).

@mikepenz if you can help me with the resizing textview :) it will be appreciated ;)

**Comment by mikepenz** [comment]
@ToonvanStrijp did the `.withTranslucentStatusBar(false)` work?

i will look at it. but thanks for the code snippets ;)

**Comment by ToonvanStrijp** [comment]
@mikepenz yes it did work!!! thanks!!! :)!!!

if someone wants more information, or an example, ask me ;)

**Comment by mikepenz** [comment]
@ToonvanStrijp I really like the style. perhaps i will add this to the default badge ;) let me see :P
