### ISSUE TITLE
How to set selected item with viewpager?

### ISSUE THREAD

**Issue by ToonvanStrijp** [mikepenz/MaterialDrawer#358]
Can i set the selected item by identifier? Sorry for this question... but i couldn't find the answer.

**Comment by mikepenz** [comment]
@ToonvanStrijp look here: https://github.com/mikepenz/MaterialDrawer#code-1
Or look at the sample. 

The `Drawer` object you get after building it has the required methdos

**Comment by ToonvanStrijp** [comment]
@mikepenz  sorry but i cant find it... i know i can set a selection... but cant find anything about set one item as selected...

sorry... ;)

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/SimpleHeaderDrawerActivity.java#L171

**Comment by ToonvanStrijp** [comment]
:O how can i missed that?... 

 slidingTabLayout.setOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

            }

            @Override
            public void onPageSelected(int position) {
                result.setSelectionByIdentifier(position, false);
            }

            @Override
            public void onPageScrollStateChanged(int state) {

            }
        });


;) thanks @mikepenz  sorry for the stupid question :p

**Comment by mikepenz** [comment]
position is != identifier. don't mix position and identifier up!

**Comment by ToonvanStrijp** [comment]
i know, but my tab 0,1,2 overlap the identifier :)... or do you suggest another way? :)

**Comment by mikepenz** [comment]
ok then you can do this. just make sure they will match. or you make sure to define them.

**Comment by ToonvanStrijp** [comment]
i've changed a little bit ;) result.setSelection(position, false); Now the drawer items index == tabindex ;)
