### ISSUE TITLE
drawer toggle is invisible

### ISSUE THREAD

**Issue by bbetter** [mikepenz/MaterialDrawer#359]
drawer toggle becomes invisible  with new google navigation tabs and toolbar

**Comment by mikepenz** [comment]
@bbetter can you be a bit more specific? the sample app uses a toolbar and everything works as it should. 

If you do some custom stuff you will have to handle the DrawerToggle on your own. The Drawer provides the required APIs

**Comment by bbetter** [comment]
my sorries, just 've figured out it's my mistake , 
thx for help, issue can be closed.
