### ISSUE TITLE
Display name instead of e-mail in accounts list

### ISSUE THREAD

**Issue by Chesteer89** [mikepenz/MaterialDrawer#360]
Hi,
what's the fastest way to display account name instead of e-mail address on accounts list?

**Comment by mikepenz** [comment]
@Chesteer89 there is a easy method do show the name as addition to the email: `withNameShown(true)` (on the ProfileDrawerItem)

**Comment by mikepenz** [comment]
@Chesteer89 else this will require a CustomProfileDrawerItem ;). In fact you can just use the source of the ProfileDrawerItem and only write out the name. ;)
