### ISSUE TITLE
takes time to opened for first time

### ISSUE THREAD

**Issue by patelakshay13890** [mikepenz/MaterialDrawer#362]
First time open the application, screen hangs one or two seconds before opening completely.
& Apply Ripple Effect to Drawer Selection as in Material Design ??

**Comment by mikepenz** [comment]
@patelakshay13890 i assume you do something in the Main Thread which blocks the UI. This is not MaterialDrawer specific. 

Ripple effect only on devices with API Level > 21

**Comment by patelakshay13890** [comment]
No i m not doing any thing that blocks main UI thread ..!!

**Comment by mikepenz** [comment]
@patelakshay13890 i use the drawer in all of my apps. have tested it on many different devices + emulators. (HTC Desire S, which is really slow). 

No delays or hangs. So it has to be specific to your application.

**Comment by patelakshay13890** [comment]
okay

**Comment by mikepenz** [comment]
If you can proof the opposite i will try to fix it. but no other reports yet and i can't reproduce any screen hangs for 2 seconds
