### ISSUE TITLE
Since v3.0.0, the drawer does not close after item clicked

### ISSUE THREAD

**Issue by aminezghidi** [mikepenz/MaterialDrawer#363]
Drawer does not close after drawer item clicked even if I use .withCloseOnClick(true)

**Comment by mikepenz** [comment]
@aminezghidi without knowing your code i just assume you return `true` inside the `onDrawerItemClick` listener. 

true means that the event was consumed and no further action is required from the drawer. As you want the drawer to finish everything and close itself you should return `false`, which states the event was not consumed and all things after this should continue to run.

**Comment by aminezghidi** [comment]
Thank you for this explanation @mikepenz !
