### ISSUE TITLE
Regression : AutoClose on click

### ISSUE THREAD

**Issue by nalmada** [mikepenz/MaterialDrawer#364]
Hi, 

I've just updated to 3.0.3 from 2.9.8

I've an  Activity with ```android:launchMode="singleTop" ``` . When i click on an item in the nav drawer i send an Intent. If i send an intent to my singleTop Activity, the nav drawer doesn't automatically close like in 2.9.8.

If i use ``` drawer.close() ```  before sending my Intent, there is a serious framerate drop while the nav is closing.
If i use ``` drawer.close() ``` after sending my Intent (in ``` onResume()``` ) nothing happens and ``` drawer.isOpen()```  returns false 

Would be nice if i can retrieve the previous behavior in 3.0.3

Thanks

**Comment by mikepenz** [comment]
I assume it's the same as this: https://github.com/mikepenz/MaterialDrawer/issues/363
