### ISSUE TITLE
Account switcher caret is not exactly centered

### ISSUE THREAD

**Issue by meetshawn** [mikepenz/MaterialDrawer#365]
This is a bit nitpicky, but looking at other material apps it's obvious the caret is a little off-center. Google Apps seem to center it between the name and email while the material spec site has it center on the email line. The current material drawer implementation doesn't seem to match either of these.

Google Docs (other Google Apps are the same):

![Google Docs]
(http://i.imgur.com/LRbix8rl.png)

Material Spec:

![Material Spec]
(http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7NDF2RjRVMlozQ2s/patterns_navdrawer_elevation1.png)

vs

![MaterialDrawer]
(https://raw.githubusercontent.com/mikepenz/MaterialDrawer/master/DEV/screenshots/screenshot1_small.png)

**Comment by mikepenz** [comment]
@meetshawn totally right. not sure how i kept this so long. fixed in the next version
