### ISSUE TITLE
youtube app like drawer refresh (from anonymous to signed in)

### ISSUE THREAD

**Issue by talanta** [mikepenz/MaterialDrawer#366]
Hi Mike,

This MaterialDrawer lib is simply awesome ! Thank you
I want to use it in the way of the youtube app, meaning I need to handle an anonymous (small header) and signed in (large header) states of the drawer, in the same activity.
So my question: is there a way to achieve this using the MD lib ?

**Comment by mikepenz** [comment]
@talanta can you add screenshot of the logged out state?

**Comment by talanta** [comment]
![getfgtk9bv](https://cloud.githubusercontent.com/assets/5102138/7870039/da86f0ae-0586-11e5-9c4e-39901ace2e61.gif)

**Comment by mikepenz** [comment]
![screenshot3_small](https://cloud.githubusercontent.com/assets/1476232/7870115/49fd8394-0587-11e5-83e5-174202aa8d44.png)

Yeah this drawer supports a compact header and also the normal header. you will have to rebuild the header after the user logs in to switch from compact to normal but is possible

**Comment by talanta** [comment]
alright ! when you say "rebuild", do you mean I should create a new Drawer instance with the current activity, or the previous can be reset or invalidate ? Or even can this operation simply be done in the Account header , meaning to attach a new account header to the current Drawer ?

**Comment by mikepenz** [comment]
@talanta i will try in the sample app now. but the best way is to rebuild the AccountHeader and attach it to the drawer again. i will try something.

**Comment by mikepenz** [comment]
@talanta i have added it to the sample app:

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/ComplexHeaderDrawerActivity.java#L172

**Comment by talanta** [comment]
great ! i'll try try it and keep you posted. Thank you

**Comment by mikepenz** [comment]
Great ;). Just post here. 


I'll close it as the main question is solved :D (also i hate unresolved issues :P)

**Comment by simonckenyon** [comment]
@talanta if you implement this (the Sign In) I would really like to know how you did it

**Comment by mikepenz** [comment]
@simonckenyon any troubles with the general implementation?

**Comment by simonckenyon** [comment]
I just don't know now to draw the avatar and Sign In, along with any listener that might be required.
I could not find an example. A fully worked out demo with the authentication lifecycle implemented would be a great benefit to a lot of people. I would offer to write one if I knew how to do this.

**Comment by mikepenz** [comment]
@simonckenyon  you can set a listener on the first and second line. it is something called like selectionListener. 

The logic which is required to switch without redoing the whole drawer is also in the sample now. as mentioned above ;). 

so what's missing?

**Comment by simonckenyon** [comment]
i created a profile with the name "sign in" on a compact header. but the dropdown arrow is displayed and when the profile is clicked on the navigation drawer is replaced with the "Sign In" user. is there someway to remove the arrow and to have a listener on the header profile?

**Comment by mikepenz** [comment]
@simonckenyon don't add a profile. just set the text for the first and second line. and set an AccountHeaderSelectionListener which will get called if the users clicks on the area. No profile required for this.

**Comment by simonckenyon** [comment]
is this correct?
```java
            accountHeader = new AccountHeaderBuilder()
                    .withActivity(this)
                    .withCompactStyle(true)
                    .withHeaderBackground(R.drawable.header)
                    .withTranslucentStatusBar(false)
                    .withSelectionListEnabledForSingleProfile(true)
                    .withProfileImagesClickable(true)
                    .withOnAccountHeaderSelectionViewClickListener(new AccountHeader.OnAccountHeaderSelectionViewClickListener() {
                        @Override
                        public boolean onClick(View view, IProfile iProfile) {
                            drawer.closeDrawer();
                            // do sign in however you want
                            return false;
                        }
                    })
                    .withSavedInstance(savedInstanceState)
                    .build();
            View headerContainer = accountHeader.getView();
            View headerView = headerContainer.findViewById(com.mikepenz.materialdrawer.R.id.account_header_drawer);
            headerView.setVisibility(View.VISIBLE);
            BezelImageView icon = (BezelImageView) headerContainer.findViewById(R.id.account_header_drawer_current);
            icon.setImageResource(R.drawable.anon);
            icon.setVisibility(View.VISIBLE);
            TextView drawerName = (TextView) headerView.findViewById(R.id.account_header_drawer_name);
            drawerName.setText("Sign In");
            drawerName.setVisibility(View.VISIBLE);
```
when i login and replace the navigation drawer all is well. but when i logout and rerun this code, the drawerName is still the profile name. and the downarrow is visible.
however the correct callback is called. so i'm a bit confused.

i also don't like using the exposed view from the header.

**Comment by simonckenyon** [comment]
well it was so much simpler to go:

```java
            profile = new ProfileDrawerItem()
                    .withName("Sign In")
                    .withIcon(getResources().getDrawable(R.drawable.anon))
                    .withIdentifier(PROFILE_USER);
            accountHeader = new AccountHeaderBuilder()
                    .withActivity(this)
                    .withCompactStyle(true)
                    .withHeaderBackground(R.drawable.header)
                    .withTranslucentStatusBar(false)
                    .withSelectionListEnabledForSingleProfile(false)
                    .withProfileImagesClickable(true)
                    .addProfiles(
                            profile
                    )
                    .withOnAccountHeaderSelectionViewClickListener(new AccountHeader.OnAccountHeaderSelectionViewClickListener() {
                        @Override
                        public boolean onClick(View view, IProfile iProfile) {
                            Log.d(TAG, "user asked to sign in");
                            drawer.closeDrawer();
                            // do login
                            return false;
                        }
                    })
                    .withSavedInstance(savedInstanceState)
                    .build();
```

**Comment by mikepenz** [comment]
@simonckenyon oh no. i meant some different calls. 

No profile but with the following: 
`.withSelectionFirstLine`
`.withSelectionSecondLine`
and then react on the `withOnAccountHeaderSelectionViewClickListener` listener. 

I assume you won't need an user image there...?

**Comment by simonckenyon** [comment]
i would like an anonymous avatar, just like the youtube app, which my method allows.
is there a ```.withAvatar()``` or similar? but looking at the code there doesn't seem to be a way to set ```mCurrentProfileView```

**Comment by mikepenz** [comment]
@simonckenyon ok if you need an profile image then create a profile for this thing
