### ISSUE TITLE
Remove fading edge color in old Android Versions

### ISSUE THREAD

**Issue by jssamitkumar** [mikepenz/MaterialDrawer#368]
I have to use  the library  MaterialDrawer in my android application to create drawer but the show the white colour after scrolling  the drawer.
![device-2015-05-29-121533](https://cloud.githubusercontent.com/assets/10560302/7877820/440ed80e-05fd-11e5-8696-2e22e5b93b43.png)

**Comment by mikepenz** [comment]
As discussed via e-mail. 

Get the `ListView` which is there to handle the DrawerItems from the `Drawer` object with `getListView` and disable or set the fading edge color to a different color or transparent color.
