### ISSUE TITLE
Primary/Secondary Extend BaseNavItem?

### ISSUE THREAD

**Issue by easycheese** [mikepenz/MaterialDrawer#37]
Is there any reason that the Primary/Secondary Nav items couldn't extend a BaseNavItem w/common methods like getName()?

Right now my code looks like this:

                        if (drawerItem instanceof PrimaryDrawerItem) {
                            String name = ((PrimaryDrawerItem) drawerItem).getName();
                            selectMenuItem(name);
                        }
                        if (drawerItem instanceof SecondaryDrawerItem) {
                            String name = ((SecondaryDrawerItem) drawerItem).getName();
                            selectMenuItem(name);
                        }

But looking at your code I don't really see any reason why they couldn't have a common superclass.  Unless I'm missing something....

**Comment by mikepenz** [comment]
@easycheese those items extend an interface called ```Nameable```

So just check if the drawerItem is ```instanceOf Nameable````

```java
if (drawerItem instanceof Nameable) {
   Toast.makeText(SimpleDrawerActivity.this, SimpleDrawerActivity.this.getString(((Nameable) drawerItem).getNameRes()), Toast.LENGTH_SHORT).show();
}
```
