### ISSUE TITLE
Error with single OnAccountHeaderSelectionViewClickListener iProfile = null

### ISSUE THREAD

**Issue by ThibaudAV** [mikepenz/MaterialDrawer#370]
If I use a Materialdrawer version over 2.9.5, I have a :  "iProfil=null" when I click on the profile's header of the drawer

```
...
.withSelectionListEnabledForSingleProfile(false)
.withProfileImagesClickable(false)
...
.withOnAccountHeaderSelectionViewClickListener(new  AccountHeader.OnAccountHeaderSelectionViewClickListener() {
                    @Override
                    public boolean onClick(View view, IProfile iProfile) {
                        Log.d("APP", iProfile + "");
                        return false;
                    }
                })
...
```
However, if I use the 2.9.5 version, it's working well

**Comment by mikepenz** [comment]
@ThibaudAV which version are you using now?

**Comment by ThibaudAV** [comment]
With v3.0.4, I have a "Failed to resolve: com.mikepenz.materialdrawer:library:3.0.4"
But for the v2.9.8 i have the "iProfil=null" problem .

**Comment by mikepenz** [comment]
--> https://github.com/mikepenz/MaterialDrawer#-v298
it is com.mikepenz:materialdrawer:3.0.4 now

please update first and if it still is the same we can take a deeper look

**Comment by ThibaudAV** [comment]
With v3.0.4 I have the same problem :/
Thank you for your help

**Comment by ThibaudAV** [comment]
Thank you ;)
