### ISSUE TITLE
Use NavigationView from new Design Support library

### ISSUE THREAD

**Issue by grote** [mikepenz/MaterialDrawer#371]
Are there any plans to use the new [NavigationView](https://developer.android.com/reference/android/support/design/widget/NavigationView.html) from the Design Support library?

It would IMHO make sense to converge this library with the direction Google is taking with their library. Also, it would be neat to be able to use a menu resource to populate the drawer.

**Comment by h6ah4i** [comment]
:+1:

**Comment by mikepenz** [comment]
@grote sorry no this won't happen. I have checked out the source of the new NavigationView and as far as i've found it has no support for custom DrawerItems so it won't allow me to do the AccountSwitcher, or anything else. You can check out the current source yourself too, if you find information on how this would be possible let me know.

**Comment by grote** [comment]
Hi Mike, thanks for checking. I didn't look into it too deeply, but couldn't you use [inflateHeaderView()](https://developer.android.com/reference/android/support/design/widget/NavigationView.html#inflateHeaderView%28int%29) or [addHeaderView()](https://developer.android.com/reference/android/support/design/widget/NavigationView.html#addHeaderView%28android.view.View%29) to add your custom header with accounts switcher?

The menu supports also [different sections](http://android-developers.blogspot.co.nz/2015/05/android-design-support-library.html). What else would be missing?

**Comment by mikepenz** [comment]
@grote the header is the smallest problem. The main issue is that the NavigationView only has 3 different types of Items in it's list. As far as i understand the code there is no function to add additional or different items, which would be required. 

![img_2015-05-31 10 11 06](https://cloud.githubusercontent.com/assets/1476232/7901226/a0f30348-077d-11e5-9f18-47936ceb8a21.jpg)

I totally understand that the new NavigationView works great for a very very simple Drawer. just with a simple header. just with one type of drawer item and with sections. 

no profiles, no custom drawer items, no sticky footer, no sticky header. no normal footer, ...

**Comment by joxad** [comment]
Hi,

I wanted to do something like that: 



fragment_menu_footer.xml

`<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <data>

        <variable
            name="fragmentMenuVM"
            type="com.startogamu.zikobot.viewmodel.fragment.menu.FragmentMenuVM" />
    </data>


    <android.support.design.widget.NavigationView
        android:id="@+id/navigation_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:menu="@menu/menu_drawer_footer" />

</layout>
`


fragment_menu.xml

`<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <data>

        <variable
            name="fragmentMenuVM"
            type="com.startogamu.zikobot.viewmodel.fragment.menu.FragmentMenuVM" />
    </data>


    <android.support.design.widget.NavigationView
        android:id="@+id/navigation_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:menu="@menu/menu_drawer" />

</layout>
`


` /***
     * Init the menu drawer layout that will contains the other way to play music
     */
    private void initDrawer() {
        AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(activity)
                .withHeaderBackground(R.drawable.header)
                .addProfiles(
                        new ProfileDrawerItem().withName("Local").withIcon(ContextCompat.getDrawable(activity,R.drawable.ic_folder))
                )
                .withOnAccountHeaderListener((view, profile, currentProfile) -> false)
                .build();

        FragmentMenuBinding menuBinding = DataBindingUtil.inflate(LayoutInflater.from(activity),R.layout.fragment_menu,null, false);
        FragmentMenuFooterBinding menuFooterBinding = DataBindingUtil.inflate(LayoutInflater.from(activity),R.layout.fragment_menu_footer,null, false);

        drawer = new DrawerBuilder()
                .withActivity(activity)
                .withAccountHeader(headerResult)
                .withToolbar(binding.toolbar)
                .withCustomView(menuBinding.getRoot())
                .withFooterDivider(true)
                .withFooter(menuFooterBinding.getRoot())
                .build();
        actionBarDrawerToggle = new ActionBarDrawerToggle(activity, drawer.getDrawerLayout(),
                R.string.drawer_open, R.string.drawer_close);
        actionBarDrawerToggle.setDrawerIndicatorEnabled(true);
        drawer.setActionBarDrawerToggle(actionBarDrawerToggle);

    }`
  

The only problems is that "withCustomView" put the view in matchparent and accountheader /footer dissapear.

What about doing something like :  

-accountHeader
-customview(if one, below accountheader and above footer) 
-footer

**Comment by mikepenz** [comment]
@joxad sorry this is not possible the `AccountHeader` will only work with a normal drawer, and when the list of items is there. What you theoretically could do is just create a `CustomDrawerItem` which is full height and contains the fragment you want to display. This way you will have the fragment, but also the header, and footer functionality

**Comment by joxad** [comment]
@mikepenz : Ah yeah nice idea thanks a lot ! For now I use it with the classic way you prepared for it. By the way, I don't know where you want us to send new app using  your lib so here it is : [zikobot](https://play.google.com/apps/testing/com.startogamu.zikobot) (still in beta)

**Comment by mikepenz** [comment]
@joxad if the app is in the playstore you can do a pull request and add it at the end of the list.
