### ISSUE TITLE
Custom Icons Size

### ISSUE THREAD

**Issue by AngleV** [mikepenz/MaterialDrawer#374]
I am using your awesome library with custom icons of mine.
In SecondaryDrawerItem they appear small.
Any way to set the size of them ?

Thanks

**Comment by mikepenz** [comment]
@AngleV the icon size of the SecondaryDrawerItem should be smaller. 
Just use the PrimaryDrawerItem?


If you need custom icon size or a custom DrawerItem just create your own CustomDrawerItem ;)
