### ISSUE TITLE
No menu selection in Android 2.3

### ISSUE THREAD

**Issue by CROSP** [mikepenz/MaterialDrawer#376]
There is one problem with android 2.3. When you select menu in navigation drawer it doesn't make it selected in the navigation drawer. On 4+ works fine. I haven't tried to find the problem yet, but I think there some problems with themes.

**Comment by CROSP** [comment]
Also another issue it that background changes when you are scrolling navigation drawer in Android 2.3. 
But in 4+ works fine, so there is some fault with themes I think.

**Comment by mikepenz** [comment]
@CROSP hmmm i assume this has something to do with API Level 10. That the item does not stay selected is a known issue and won't be fixed. The required api calls are missing in this release. and as it already is recommend to develop for 14+ or even 16+ it just makes no sense to spend a few hours on fixing this. 

About the scrolling, i'll check it
