### ISSUE TITLE
rippleColor error in conjuction with com.android.support:design:22.2.0

### ISSUE THREAD

**Issue by Spiderbezno** [mikepenz/MaterialDrawer#379]
Error with variable rippleColor in conjuction with     compile 'com.android.support:design:22.2.0'

/Users/..../AndroidStudioProjects/..../app/build/intermediates/exploded-aar/com.mikepenz/materialdrawer/3.0.5/res/values/values.xml

Error:(1) Attribute "rippleColor" has already been defined

**Comment by mikepenz** [comment]
@Spiderbezno there is no attribute `rippleColor` inside the MaterialDrawer library. Neither in the Android-Iconics library.

**Comment by Spiderbezno** [comment]
Maybe is necessary to define, I don't know, but if I use the new android.support:design, I have this error 
El 1/6/2015 15:11, Mike Penz <notifications@github.com> escribió:@Spiderbezno there is no attribute rippleColor inside the MaterialDrawer library. Neither in the Android-Iconics library.

**Comment by Anatidae-Project** [comment]
Mike, you're updating so fast that people using your lib are expecting to have support for Google Libs within a day or so of release!

**Comment by mikepenz** [comment]
@Anatidae-Project in fact i already updated for the appcompat v22.2.0
i am pretty sure this issue is something completely different, but as i got a new notebook it will take a while until everything is set up again

**Comment by mikepenz** [comment]
Just tried this. I can add
```gradle
    compile 'com.squareup.picasso:picasso:2.5.2'
```

To the sample and/or the library and build and run the project without any issues. So there must be a different lib you use which causes this issue

**Comment by Spiderbezno** [comment]
May be the rror is with other library but the console ever say this

AGPBI: {"kind":"ERROR","text":"Attribute \"rippleColor\" has already been defined","sourcePath":"/Users/Jorge1Old/AndroidStudioProjects/My_Andorra_Telecom/app/build/intermediates/exploded-aar/com.mikepenz/materialdrawer/3.0.5/res/values/values.xml","position":{"startLine":1},"original":""}


 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Applications/DevTools/android_sdk_AS/sdk/build-tools/22.0.1/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by mikepenz** [comment]
![bildschirmfoto 2015-06-04 um 13 18 19](https://cloud.githubusercontent.com/assets/1476232/7982974/3351c1a2-0abc-11e5-933d-a1a3875bb430.png)

I can't say more than there is nothing called rippleColor in this project. And that it's working with the design lib in the sample

**Comment by Spiderbezno** [comment]
OK thanks 
El 4/6/2015 13:19, Mike Penz <notifications@github.com> escribió:

I can't say more than there is nothing called rippleColor in this project. And that it's working with the design lib in the sample

**Comment by Spiderbezno** [comment]
Maybe the problem is with this library (MaterialDesignLibrary, inconvination with android support:design)
you could test it??

**Comment by mikepenz** [comment]
I can't test other libraries. Go to the creators github repository and get in touch with him. Sorry. I have choosen prefixed attributes so my lib does not get in conflict with any other library.

**Comment by Spiderbezno** [comment]
Your library is a great job, thx 
El 5/6/2015 14:37, Mike Penz <notifications@github.com> escribió:I can't test other libraries. Go to the creators github repository and get in touch with him. Sorry. I have choosen prefixed attributes so my lib does not get in conflict with any other library.

**Comment by javiersantos** [comment]
Issue comes from Material Design Library (third-party library). It includes a 'rippleColor' param: https://github.com/navasmdc/MaterialDesignLibrary/blob/9998c2dbb608bf78de28b3fb3384e75d5871715e/MaterialDesign/res/values/attributes.xml#L7

**Comment by mikepenz** [comment]
@javiersantos thanks for adding the info here ;)
