### ISSUE TITLE
Close the drawer while executing ripple effect

### ISSUE THREAD

**Issue by Aselox** [mikepenz/MaterialDrawer#380]
Hello,
Is it possible (as an option maybe) to close the drawer as soon as an item is clicked and while the ripple effect is running? This is what Google does with its apps, but currently this library waits for the ripple effect to finish and then close the drawer.
Thank you

**Comment by mikepenz** [comment]
@Aselox the library waits 200ms to keep the ui responsive. You can overwrite this with `. withDelayOnDrawerClose(0)`
