### ISSUE TITLE
Error with OnAccountHeaderListener: iProfile = null

### ISSUE THREAD

**Issue by chelexey** [mikepenz/MaterialDrawer#381]
Similar to #370 I have an error IProfile profile = null with OnAccountHeaderListener:

```
    ... new AccountHeaderBuilder()
        .withActivity(this)
        .withHeaderBackground(R.drawable.background)
        .addProfiles(iProfile).withSavedInstance(savedInstanceState)
        .withSelectionListEnabledForSingleProfile(false)
        .withCompactStyle(true)
        .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
          @Override
          public boolean onProfileChanged(View view, IProfile iProfile, boolean current) {
            // iProfile == null 
            Log.d("iProfile", iProfile + "");
            return true;
          }
        })
```

**Comment by mikepenz** [comment]
@chelexey what version are you using?

**Comment by chelexey** [comment]
@mikepenz  v3.0.5

**Comment by str4d** [comment]
Seen here too. I am using v3.0.5 with this code (loading the real `IProfile`s once the app is unlocked):

```
... new AccountHeaderBuilder()
        .withActivity(this)
        .withHeaderBackground(R.drawable.drawer_header_background)
        .addProfiles(getLockedProfile())
        .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
            @Override
            public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                if (profile.getIdentifier() == ID_LOCKED)
                    // Request password...
                else if (!currentProfile)
                    identitySelected(profile);
                return false;
            }
        })
        .withSavedInstance(savedInstanceState)
```

However, I only get `profile = null` when clicking on the currently-selected profile's icon (top-left). If I click on the second or third profile icons, or I open the account selector and click any profile (including currently-selected), I get the expected non-null `IProfile`.

**Comment by chelexey** [comment]
> when clicking on the currently-selected profile's icon 

Confirm, in this case I click on single profile's icon and have iProfile == null

**Comment by mikepenz** [comment]
@str4d @chelexey thanks to both of you for the detailed description. I think i know where to search. I will fix this as soon as possible. 

It takes a bit longer than normal for my answers and updates as i have to do a lot of extra stuff at work. So sorry for the delay.
