### ISSUE TITLE
Setting header below notifications bar

### ISSUE THREAD

**Issue by cmonfortep** [mikepenz/MaterialDrawer#382]
If I set a header to my drawer, the header appears over the notifications bar.

Is there any way to indicate a padding or be able to draw the header just below the notification bar and not over it?

**Comment by mikepenz** [comment]
@cmonfortep please take a look at the sample app. It includes many different cases on how you can do it. Just download it via google play and check the source afterwards ;)

(A fast hint: it's possible ;))
