### ISSUE TITLE
Expose size settings for IIcons

### ISSUE THREAD

**Issue by str4d** [mikepenz/MaterialDrawer#384]
My remarks in mikepenz/Android-Iconics#36 comment 2 apply here also - the drawer `IIcon`s are sized differently to equivalent 24dp drawables, if the drawables had internal margins. However, in this case using an `IconicsDrawable` does not help, because its size is ignored (I assume the drawer icons are scaled to a uniform 24dp size - although strangely, setting the `IconicsDrawable` size to 24dp *does* make the drawer icons slightly bigger and sharper, it's only smaller sizes that don't do anything).

I propose that the various size setters be exposed anywhere an `IIcon` is accepted. If an `IIcon` is supplied and a size setter is used, that size should be respected and the `IIcon` centered in the drawer icon position, matching how an equivalent drawable with internal margins would be positioned.

**Comment by mikepenz** [comment]
@str4d a 24dp drawable is different than a 24dp Android-Iconics icon. This is correct. But if you take a closer look at the specifications you can see that those drawables are in fact only 24dp with 1dp padding. And this is done inside the Drawer too. 

So the provided DrawerItems use the correct size according to the Google Material Design Guideliens. If you need different icon sizes i recommend you to just implement a CustomDrawerItem. 

There's also an example in the source of the app how to extend an existing DrawerItem if you want to simplify this process.

**Comment by str4d** [comment]
You miss my point. If you look at the drawables themselves, some have excess space around them, inside the drawable. This is where the inconsistency creeps in.

Examples:

- `ic_inbox_grey600_24dp.png` has 3dp of padding; the actual physical icon is 18dp high and 18dp wide.
- `ic_cloud_upload_grey600_24dp.png` has no padding; the actual physical icon is 16dp high and 24dp wide.
- `ic_send_grey600_24dp.png` has 1dp of padding; the actual physical icon is 18dp high and 21dp wide (with 2dp padding on left and 1dp padding on right).
- `ic_delete_grey600_24dp.png` has 3dp of padding; the actual physical icon is 18dp high and 14dp wide.

The corresponding `IIcon`s use the same physical icon shapes but don't retain the padding. This means that when actually using the above four icons in a navigation drawer (as I am), `ic_inbox` and `ic_delete` appear much larger than they should.

Yes, your drawer is correctly implementing the Material Design Guidelines for navigation drawer icons. But the `IIcon`s themselves are inconsistently sized, which leads to the drawer `IIcon`s being incorrectly sized. So if allowing the `IIcon`s to be resized here is the wrong solution, then the right one is for the `IIcon`s to correctly include the padding that they are supposed to.

**Comment by mikepenz** [comment]
@str4d but as the drawer also allows you to provide a drawable you can create the IconicsDrawable with the correct size + padding?

**Comment by str4d** [comment]
I can, yes. I have now had a chance to test the padding methods, and it does solve the problem this issue covers. However, I still think it shouldn't be necessary for every single developer to manually measure and apply this padding just to re-instate the right inter-icon ratios.

Thinking about it, this is probably a more general Android-Iconics issue. Perhaps having e.g. a `GoogleMaterial.PaddedIcon` class that automatically adds the original padding (and then the user can add extra padding with `paddingDp()` to that as they need) would be the best way to resolve this.

**Comment by str4d** [comment]
Or alternatively, a new icon namespace could be added - `gmdp` - that uses all the `gmd` icons but includes their original padding. This would be far more versatile and useful to developers, and I expect probably easier to implement.

**Comment by mikepenz** [comment]
@str4d there is no original padding. in fact this uses a font to have the vector icons. So i am afraid there is no such thing like padding by icon. (and i also assume that nobody will make such an list) Also if someone does it is enough if there's a wiki page describing the paddings per icon.
