### ISSUE TITLE
Material design animation?

### ISSUE THREAD

**Issue by sartechb** [mikepenz/MaterialDrawer#385]
Hello!

First off I'd like to say thanks because this is an incredible library. I was just wondering if there was some way to change the animation for the hamburger icon? Currently the animation I see is having the top and bottom bars tilting to form an arrow, and I'd like to see it more like [this](http://www.google.com/design/spec/animation/delightful-details.html) where the icon spins.

Thanks so much!

**Comment by mikepenz** [comment]
@sartechb this is just theme specific and you can overwrite it. There are enough resources on StackOverFlow available ;). 

On a side note. You shouldn't do this. The Drawer should be the full height. Only in some special samples it is ok if it was done different

**Comment by mikepenz** [comment]
But in fact i assume you are looking for this: https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/res/values/styles.xml#L152
