### ISSUE TITLE
android:supportsRtl="true"  layout issue

### ISSUE THREAD

**Issue by mingqlin** [mikepenz/MaterialDrawer#386]
enable android:supportsRtl="true"  and switch language to Arabic or any RTL language, drawer automatically switch to the right of the screen, but content in the list view doesn't layout properly (eg: icon is missing). also Account Header text overlap

**Comment by mikepenz** [comment]
@mingqlin no default RTL support in this launcher as i can't test. there were a few issues already regarding this. please search for them in the github issues section

**Comment by mingqlin** [comment]
@mikepenz follow is the steps you can setup your demo to test RTL feature.

1. in app AndroidManifest.xml add android:supportsRtl="true"
    <application
        android:name=".CustomApplication"
        android:allowBackup="true"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true">

2. open any sample activity eg: SimpleHeaderDrawerActivity, add following line:

public class SimpleHeaderDrawerActivity extends AppCompatActivity {
    private static final int PROFILE_SETTING = 1;

    //save our header or result
    private AccountHeader headerResult = null;
    private Drawer result = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
// begin of added line
        Locale.setDefault(new Locale("ar"));

        Configuration config = new Configuration();

        config.locale = new Locale("ar");

        getBaseContext()
                .getResources()
                .updateConfiguration(
                        config,
                        getBaseContext().getResources()
                                .getDisplayMetrics());

// end of added line
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sample_dark_toolbar);

**Comment by mingqlin** [comment]
you probably know, but just in case, this link to instruction to support RTL:
http://android-developers.blogspot.com/2013/03/native-rtl-support-in-android-42.html

**Comment by mingqlin** [comment]
following is screenshot show the problem.

![device-2015-06-03-092539](https://cloud.githubusercontent.com/assets/970456/7960986/93e1949c-09d2-11e5-8aea-c136db7b18b8.png)

**Comment by mikepenz** [comment]
@mingqlin thanks a lot for the above info. the next update will include a fix for this issue. there is still a different problem with RTL and the Iconics Drawable. I will check how to fix this ;)

**Comment by mingqlin** [comment]
you are most welcome. thank you for great library!
