### ISSUE TITLE
Right drawer is being shown underneath the statusbar

### ISSUE THREAD

**Issue by RadicalMonkey** [mikepenz/MaterialDrawer#387]
Firstly thanks for the great library, its very flexible!

I've noticed an issue when adding a second drawer to the right hand side. If I set 
```java
.withTranslucentStatusBar(false)
``` 
on the right hand drawer, it is displayed over the statusbar rather than below it. 
If I use a right drawer without a left drawer then it is drawn correctly below the statusbar.

The code I have is:
```java
drawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withActionBarDrawerToggle(true)
                .withAccountHeader(headerResult)
                .addDrawerItems(
                        ...
                ).build();

drawer2 = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withDrawerGravity(Gravity.RIGHT)
                .withTranslucentStatusBar(false)
                .withStickyHeader(R.layout.header)
                .withStickyFooter(footer)
                .withFooterClickable(true)
                .withStickyFooterDivider(true)
                .withCloseOnClick(false)
                .append(drawer);
```

**Comment by mikepenz** [comment]
@RadicalMonkey the right drawer is just an addition for the left drawer and the DrawerLayout itself can't have completely different ui logics. So you can have it the same but i'm afraid that you won'T be able to have 2 different logics for this.

**Comment by RadicalMonkey** [comment]
Ah ok, that makes sense. 

So its not possible to make this layout from the material spec using your library?http://www.google.co.uk/design/spec/layout/structure.html#structure-ui-regions

**Comment by mikepenz** [comment]
@RadicalMonkey as of now this is not possible. But as it's in the guidelines i'll see how i can get this in ;)

**Comment by RadicalMonkey** [comment]
Thanks! You rock!

**Comment by mikepenz** [comment]
@RadicalMonkey the latest release has a new method which allows you to do this

**Comment by BenoitDuffez** [comment]
Hi @mikepenz and @RadicalMonkey, I'm puzzled, I can't make this work: left over status bar, right underneath it.

    Drawer drawer = new DrawerBuilder()
            .withActivity(this)
            .withToolbar(toolbar)
            .withRootView(rootView)
            .withActionBarDrawerToggle(true)
            .withActionBarDrawerToggleAnimated(true)
            .withTranslucentStatusBar(true)
            .withDisplayBelowStatusBar(true)
            .addDrawerItems( ... )
            .build();
    new DrawerBuilder()
            .withActivity(this)
            .withToolbar(toolbar)
            .withCloseOnClick(false)
            .withDisplayBelowStatusBar(true)
            .withTranslucentStatusBar(false)
            .addDrawerItems( ... )
            .withDrawerGravity(Gravity.END)
            .append(drawer);

How can I achieve [this](https://material.io/guidelines/layout/structure.html#structure-ui-regions)?
