### ISSUE TITLE
Support for CheckboxDrawerItem

### ISSUE THREAD

**Issue by roughboy** [mikepenz/MaterialDrawer#388]
Analogously to already existing Switch/Toggle drawer items it would be nice to also have CheckBoxDrawerItem, especially usefull when using side navigation drawer for data filtering.

**Comment by mikepenz** [comment]
@roughboy you can create this as a CustomDrawerItem inside your project. Just get the source of the already existing toggles. modify it for your needs and use it ;). No modification of the library required :)
