### ISSUE TITLE
hamburger woes

### ISSUE THREAD

**Issue by simonckenyon** [mikepenz/MaterialDrawer#389]
sorry to be such a PITA
but the hamburger used to display
but i updated a bunch of stuff and now it doesn't

my build is
```
	compile 'com.android.support:support-v4:22.2.0'
	compile 'com.android.support:appcompat-v7:22.2.0'
	compile('com.mikepenz:materialdrawer:3.0.5@aar') {
		transitive = true
	}
	compile('com.mikepenz:aboutlibraries:5.0.2@aar') {
		transitive = true
	}
```
my theme is
```
<style name="Theme.MediEmoTheme" parent="MaterialDrawerTheme.Light.DarkToolbar">
```
i create the Toolbar with
```java
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
```
i create the drawer with
```java
        drawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withDrawerItems(drawerItems)
                .withStickyDrawerItems(stickyFooterItems)
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(AdapterView<?> parent, View view, int position, long id, IDrawerItem drawerItem) {
                        if (drawerItem != null) {
                            int identifier = drawerItem.getIdentifier();
                            Node node = application.getRoot().getAt(identifier);
                            invokeAction(node);
                        }
                        return false;
                    }
                })
                .withSavedInstance(savedInstanceState)
                .build();
```
and i display the hamburger with
```java
    //show the hamburger icon
    private void hamburger() {
        try {
            getSupportActionBar().setDisplayHomeAsUpEnabled(false);
        } catch (NullPointerException npe) {
            Log.e(TAG, "setting hanburger icon threw exception");
        }
        drawer.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);
    }
```
but it will not display the hamburger. the navigation drawer works fine.

is there some magic incantation that i am missing?

**Comment by mikepenz** [comment]
@simonckenyon after a quick look over your source everything seems fine. don't you have a git log what you've changed? In fact the Drawer only sets the `ActionBarDrawerToggle` and everything works as it would with the normal Android system. The sample also uses `v22.2.0` of the AppCompat lib and it's working too

**Comment by simonckenyon** [comment]
i know. i copied the sample app launcher activity into my code and that works.
i cannot see what the issue is. thanks for the help.

**Comment by mikepenz** [comment]
@simonckenyon perhaps it's about the moment when you try to set the hamburger thing?

**Comment by simonckenyon** [comment]
On 06/04/15 00:10, Mike Penz wrote:
>
> @simonckenyon <https://github.com/simonckenyon> perhaps it's about the 
> moment when you try to set the hamburger thing?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mikepenz/MaterialDrawer/issues/389#issuecomment-108641120>.
>
i had it working.
and i can get the test activity to work in my app.
i suspect it is the order in which i do things.

i'll sort it out in the end!

-- 
simon

Simon Kenyon
Managing Director. The Koala Computer Company Limited
e: simon@koala.ie
m: +353 86 240 0005
l: http://ie.linkedin.com/pub/simon-kenyon/0/6b2/744/
s: simonckenyon
t: @simonckenyon
g: google.com/+SimonKenyon

**Comment by simonckenyon** [comment]
you can close the issue because and the answer (after about 6 hours of debugging) is stupidity on my part...

i had
```java
private Toolbar toolbar;
```
and then in onCreate()
```java
Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
setSupportActionBar(toolbar);
```

later on i set up the drawer in a separate method
but the class variable was null as it had been masked by the local variable

bit sad, but worth explaining should anybody else copy the sample code without really reading it.

i have nobody to blame by myself.
