### ISSUE TITLE
how can I set content offset for the drawer

### ISSUE THREAD

**Issue by brucewzp** [mikepenz/MaterialDrawer#390]
hi mikepenz,
I just found this repos and I use for my android project,
since few display items, I need small drawer than default,but how can I set the content offset of the drawer that make it looks like smaller.
Appreciate for your great work!

**Comment by mikepenz** [comment]
@brucewzp what do you want to achieve? Sounds like something which is not recommended following the guidlines?

**Comment by brucewzp** [comment]
@mikepenz I checked and this does not comply with guidelines. I left a lot of blanks and it does not look good.
![2015-06-04 8 31 39](https://cloud.githubusercontent.com/assets/7270576/7984141/62d6aafe-0af9-11e5-8ac7-1eb20371a87b.png)
So I want to make it little smaller.

**Comment by mikepenz** [comment]
@brucewzp with so less actions a different menu structure like a fab or the normal menu will be a better choice.

**Comment by brucewzp** [comment]
@mikepenz you might be right
thank you!
