### ISSUE TITLE
How to override the function of the navigation button?

### ISSUE THREAD

**Issue by RadicalMonkey** [mikepenz/MaterialDrawer#391]
I made the navigation button a back arrow using 
```java
drawer.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false);       
getSupportActionBar().setDisplayHomeAsUpEnabled(true);
```

I've also set the following listener:
```java
drawer.getActionBarDrawerToggle().setToolbarNavigationClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                onBackPressed();
            }
        });
```

However pressing the navigation button still opens the drawer. How can get it to close the activity?
This was working fine in 3.0.5

**Comment by mikepenz** [comment]
provide your own onNavigatioClickListener and return true if you have consumed the event. also check out the sample app there are a few different. I would recommend you check the ComplexHeader Drawer example

**Comment by RadicalMonkey** [comment]
Thanks
