### ISSUE TITLE
Can not use withDrawerWidthDp() method.

### ISSUE THREAD

**Issue by HanderWei** [mikepenz/MaterialDrawer#392]
I used this method, then the application crashed.

Logcat show:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mikepenz/iconics/utils/Utils;
...
...
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mikepenz.iconics.utils.Utils" on path: DexPathList[[zip file "...
```

But when I use withDrawerWidthPx(), it works.

In **DrawerBuilder.java**
```
    public DrawerBuilder withDrawerWidthDp(int drawerWidthDp) {
        if(this.mActivity == null) {
            throw new RuntimeException("please pass an activity first to use this call");
        } else {
            this.mDrawerWidth = Utils.convertDpToPx(this.mActivity, (float)drawerWidthDp);
            return this;
        }
    }
```

But I can't find/goto **Utils** class. 

Now I  add dpToPx() method to workaround this problem. 
```
    public int dpToPx(int dp) {
        DisplayMetrics displayMetrics = mContext.getResources().getDisplayMetrics();
        int px = Math.round(dp * (displayMetrics.xdpi / DisplayMetrics.DENSITY_DEFAULT));
        return px;
    }
```

But I still want to know why withDrawerWidthDp cause the app crash.
If it was a bug, I hope @mikepenz  will fix it.
If not, please tell me how to solve it.

**Comment by mikepenz** [comment]
@HanderWei have you added the library with the `transitive = true` thing in the `build.gradle`

**Comment by HanderWei** [comment]
@mikepenz , I did not add `transitive = true`.
I tried to update the `build.gradle`. But I can't download support-v7 22.2.0(current is 22.1.1) cause I'm inside of the Grate Wall.

If I solve this problem I will tell to you.

Thanks for your answer.

**Comment by mikepenz** [comment]
@HanderWei i updated the support-v7 with version v3.0.5. So you should be fine with v3.0.4
