### ISSUE TITLE
Attribute "insetForeground" has already been defined

### ISSUE THREAD

**Issue by d1m0nh** [mikepenz/MaterialDrawer#393]
after updating to com.android.support:design:22.2.0  got this error. "Attribute "insetForeground" has already been defined". Please rename insetForeground in attrs.xml

**Comment by mikepenz** [comment]
@d1m0nh my project does not contain this attribute. Sorry. 

https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/res/values/attrs.xml#L22
