### ISSUE TITLE
Unexpected top level exception

### ISSUE THREAD

**Issue by sagits** [mikepenz/MaterialDrawer#394]
Hi, i'm trying to use your lib in my project, everything went fine util i put the MaterialDrawer dependence, then it give me unexpected top level exception. 
  I have searched a lot and came across two possible problems: Same lib being added twice or 65k method limit. 
  I tryied to implement multidex for the 65k limit, but it stills gave me the same error. So i have tryied to exclude some of the dependencies, but still got the error.
 Can you help me please? Thanks in advance.

Heres the error:
```
    Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	C:\Android\sdk\build-tools\22.0.1\dx.bat --dex --no-optimize --output C:\Android\workspace\equipee-android\app\build\intermediates\dex\debug --input-list=C:\Android\workspace\equipee-android\app\build\intermediates\tmp\dex\debug\inputList.txt
Error Code:
	2
Output:
	UNEXPECTED TOP-LEVEL EXCEPTION:
	com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
		at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
		at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:277)
		at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)
```

My build.gradle:
```
android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.br.velvet.gerenciarclientescrm"
        minSdkVersion 15
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
         //   runProguard false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
...
```

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar', 'volley.jar'])
    compile project(':facebook')
  // compile project(':fastandeasyrest')
    compile 'com.android.support:appcompat-v7:22.0.0'

    compile 'com.android.support:support-annotations:22.0.0'
    compile 'com.google.android.gms:play-services:6.5+'
    compile 'com.android.support:support-v4:22.0.0'
    compile 'com.squareup.picasso:picasso:+'
    compile 'com.jakewharton:butterknife:6.1.0'
    compile 'com.google.http-client:google-http-client-android:+'
    compile 'com.google.api-client:google-api-client-android:+'
    compile 'com.google.api-client:google-api-client-gson:+'
    compile 'com.google.code.gson:gson:2.2.4'
    compile 'com.github.navasmdc:MaterialDesign:1.+@aar'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.amulyakhare:com.amulyakhare.textdrawable:1.0.1'
    compile 'com.github.leonardoxh:android-masks:1.1'
    compile 'net.the4thdimension:poly-picker:1.0.11'
    compile('com.mikepenz:materialdrawer:3.0.6@aar') {
        transitive = true
        exclude module: 'support-v4'
    }
```

**Comment by mikepenz** [comment]
@sagits you can also try to exclude the appcompat-v7 module because this library includes v22.2.0

**Comment by sagits** [comment]
Thank you for your response.

It gives me this error when i try to exclude appcompat-v7 from materialDrawer:

![image](https://cloud.githubusercontent.com/assets/6174566/8014240/71b68d76-0ba5-11e5-92f0-a03aae768d3a.png)

**Comment by mikepenz** [comment]
@sagits strange as you include the appcompat in your project already. try to update your appcompat to v22.2.0 too. i don't know if this will help already.

another small thing. you don't have to include:
compile 'com.android.support:support-v4:22.0.0'
the appcompat v22.2.0 already includes it.

**Comment by sagits** [comment]
Thanks for the help, but didnt work either, some of my libs are using the same imports.
I have tryied using:
```
configurations {
    // to avoid double inclusion of support libraries
    all*.exclude group: 'com.android.support'
}
```

The problem is that i think appCompact download a lot of support stuff as dependencie (including v4, as you said), so this prevent any version of v4.

I end up using a very bad approach. but at leat it works:

![image](https://cloud.githubusercontent.com/assets/6174566/8014928/152326fe-0bab-11e5-8de1-a4c63264a51f.png)

I have manually excluded support dependencies for every lib. 

By the way, my menu icon turns into the back icon, i hope this is something about your library (some config) and not a "something is missing for dependencies", i'll edit later.

 Thank you for your time and for this amazing lib.

**Comment by mikepenz** [comment]
@sagits as you said this is a really bad thing. 

you mentioned this:
```gradle
configurations {
    // to avoid double inclusion of support libraries
    all*.exclude group: 'com.android.support'
}
```
so then just include support-v4 manually? won't this work?

the main issue is that somehow you get over the method limit or there is an loop dependency (which is kinda strange) 

to be fair. the libs you use do not look to much. so i'm wondering why you should get over the method limit.

**Comment by sagits** [comment]
I see, unfortunally this wont work too. My guess is that appcompact have something like supportv13, supportv4, and other dependences with support name.

**Comment by mikepenz** [comment]
@sagits that's bad :( and using MultiDex for the dev builds and proguard for release builds?

**Comment by sagits** [comment]
Won't wont work too. Theres a gradle option to resolveConflicts, but i don't know how to use it well. Im out of time for this project but i will give it a try later and post it here.

**Comment by simonckenyon** [comment]
i have a lot of dependencies in my app and it works fine.
removing the whole of play services and only including what i needed allowed me to not have to use multidex. i include my build.gradle
see below:

```
apply plugin: 'com.android.application'

android {
	compileSdkVersion 22
	buildToolsVersion "22.0.1"

	defaultConfig {
		targetSdkVersion 22
	}
	productFlavors {
		dev {
			minSdkVersion 19
		}
		prod {
			// The actual minSdkVersion for the application.
			minSdkVersion 14
		}
	}

	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android.txt'),
					'proguard-rules.pro'
		}
	}

	packagingOptions {
		exclude 'META-INF/LICENSE.txt'
		exclude 'META-INF/LICENSE'
		exclude 'META-INF/NOTICE.txt'
		exclude 'META-INF/NOTICE'
	}

	configurations {
		all*.exclude group: 'commons-logging', module: 'commons-logging'
	}
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_1_7
		targetCompatibility JavaVersion.VERSION_1_7
	}
}

repositories {
	maven {
		url "https://mint.splunk.com/gradle/"
	}
}

dependencies {

	compile files('libs/gravatar-android-1.0.jar')
	compile 'com.google.code.gson:gson:2.3.1'
	compile 'com.android.support:cardview-v7:22.2.0'
	compile 'com.android.support:recyclerview-v7:22.2.0'
	compile 'com.android.support:support-v4:22.2.0'
	compile 'com.android.support:appcompat-v7:22.2.0'
	compile 'com.google.android.gms:play-services-analytics:7.5.0'
	compile 'com.google.android.gms:play-services-gcm:7.5.0'
	compile 'com.google.android.gms:play-services-location:7.5.0'
	compile 'com.splunk.mint:mint:4.2'
	compile('com.mikepenz:materialdrawer:3.0.5@aar') {
		transitive = true
	}
	compile('com.mikepenz:aboutlibraries:5.0.2@aar') {
		transitive = true
	}
	compile 'info.bliki.wiki:bliki-core:3.0.19'
	compile 'commons-codec:commons-codec:1.10'
	compile 'org.apache.commons:commons-compress:1.9'
	compile 'apache-httpclient:commons-httpclient:3.1'
	compile 'org.apache.commons:commons-lang3:3.4'
	compile 'com.fasterxml.jackson.core:jackson-annotations:2.6.0-rc1'
	compile 'com.fasterxml.jackson.core:jackson-core:2.6.0-rc1'
	compile 'com.fasterxml.jackson.core:jackson-databind:2.6.0-rc1'
	compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.4'
	compile 'com.roomorama:caldroid:2.0.1'
	compile 'org.ocpsoft.prettytime:prettytime:4.0.0.Final'
	compile 'com.squareup.picasso:picasso:2.5.2'
	compile 'com.appyvet:materialrangebar:1.0'
	compile 'com.github.gabrielemariotti.cards:cardslib-core:2.1.0'
	compile 'com.github.gabrielemariotti.cards:cardslib-cards:2.1.0'
	compile 'com.github.gabrielemariotti.cards:cardslib-recyclerview:2.1.0'
	compile 'com.squareup:android-times-square:1.6.1@aar'
	compile 'com.github.paolorotolo:appintro:1.1.0'

	// for test
	compile 'com.mikepenz:octicons-typeface:2.2.0@aar'
}
```

**Comment by mikepenz** [comment]
@simonckenyon as mentioned i have no chance to provide this without the Android-Iconics library (which is tiny) and the appcompat libs which is in most apps out there already :D

**Comment by simonckenyon** [comment]
not suggesting *you* change anything.

all i was trying to say was that i was also exceeding the 65k methods limit. at first i went down the multidex route, which worked. but builds took forever.

so i experimented and by removing play services and only including the pieces i needed i was able to build without multidex. as you can see, i have a whole pile of stuff included and i can stay under the 64k limit.

looking @sagits build.gradle he too is using play services. if he changed build.gradle to only use the pieces he needed (like i did) then the app might build.

**Comment by mikepenz** [comment]
@simonckenyon ah ok :D that was not clear with the first answer. sorry.
