### ISSUE TITLE
How to set Drawer Item text size?

### ISSUE THREAD

**Issue by HanderWei** [mikepenz/MaterialDrawer#397]
I want to set Drawer Item text size more bigger cause default size is too small for me.

**Comment by mikepenz** [comment]
@HanderWei the default size is the size as specified in the Material Design Guidelines. You should really keep it. If it's to small change the text size in your phone settings? 

(You can modify it. see the values of the dimens.xml, you can overwrite them in your app, but this is not recommended)

**Comment by HanderWei** [comment]
@mikepenz  Thanks for your answer!

**Comment by HanderWei** [comment]
``` xml
    <!-- Override the default value 14sp if you want do it!-->
    <dimen name="material_drawer_item_primary_text">16sp</dimen>
```
