### ISSUE TITLE
It's possible change position of the drawer open? [question] 

### ISSUE THREAD

**Issue by bkawakami** [mikepenz/MaterialDrawer#398]
It's possible change position of the drawer open?

The current behaviour is slide from left. It's possible slide from right?

**Comment by PsyGik** [comment]
```
new DrawerBuilder()
    .withActivity(this)
    .addDrawerItems(
        //pass your items here
    )
    .withDrawerGravity(Gravity.END)
    .append(result);
```

You can supply the Gravity value for changing the drawer position

**Comment by mikepenz** [comment]
@PsyGik thanks for helping ;)
