### ISSUE TITLE
Hide the Scrollbar in the Drawer? [Question]

### ISSUE THREAD

**Issue by PsyGik** [mikepenz/MaterialDrawer#399]
How do I hide the scrollbar in the Drawer if the contents are more? It doesn't go well the design of my app.

**Comment by mikepenz** [comment]
@PsyGik as the Drawer uses a ListView internally just get the reference to it by calling `drawer.getListView()` and then you can modify everything you need

**Comment by DVassilev** [comment]
@mikepenz There is no method getListView on the latest version. Is there a workaround?

**Comment by mikepenz** [comment]
@DVassilev with v4 it is now `getRecyclerView`
