### ISSUE TITLE
possibility to define the separator

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/MaterialDrawer#4]
maybe I want a bigger separator or in other color or shorter from the right...

**Comment by mikepenz** [comment]
@Rainer-Lang the included separator is default right now. I'll add more options to it. Also it should be possible to use custom DrawerItem implementations without much extra work.

**Comment by mikepenz** [comment]
@Rainer-Lang no bigger separator but you can now create your own DrawerItems :D I'll add the docu as soon as the whole thing is stable. All elements for a default Drawer following the guidelines are now included. See the Sample project to get some insights :)
