### ISSUE TITLE
How to add/remove items after creating the drawer?

### ISSUE THREAD

**Issue by y2kshane** [mikepenz/MaterialDrawer#40]
Is it possible to add/remove items from the drawer after the initiation ?

**Comment by mikepenz** [comment]
It's really easy:
```java
Drawer.Result result = new Drawer().withActivity(this).build();
//now you can use the result and do some stuff with it
result.addItem(..);
result.removeItem(..);
```

**Comment by y2kshane** [comment]
wow that's easy ...... i actually wasted like 2 days with this other material drawer lib which won't allow to add/remove items dynamically ...that's why i asked without even trying the lib :)
You should create a wiki.....that will clarify the capabilities of this lib
Anyway thanks for the lib and for the reply

**Comment by mikepenz** [comment]
It is ;) and it should be :D

```java
Drawer.Result result = new Drawer().withActivity(this).build();
```
is just the most simple configuration for the drawer. see the README.md for advanced usage :)

**Comment by mgrebnev** [comment]
How remove item in 5.3.1 version? I didn't see Drawer.Result

**Comment by dvraman** [comment]
Does it have a method which removes all items with a particular tag ? I couldn't find any

**Comment by msubham193** [comment]
how to store all item in database
