### ISSUE TITLE
Which is the elevations of the drawer??

### ISSUE THREAD

**Issue by Spiderbezno** [mikepenz/MaterialDrawer#401]
In tbhe new guidlines googleput this
Nav Drawer & Right drawer

16dp

but the sentations is less

**Comment by mikepenz** [comment]
@Spiderbezno can you be a bit more specific as this is default from the DrawerLayout and i don't modify this. If it's wrong, it's wrong by the Android system

**Comment by Spiderbezno** [comment]
In the guide line of Android and material Design, specified the elevation of navigation drawer to 16dp, and  only I want know the elevation of your widget 
El 8/6/2015 18:50, Mike Penz <notifications@github.com> escribió:@Spiderbezno can you be a bit more specific as this is default from the DrawerLayout and i don't modify this. If it's wrong, it's wrong by the Android system

**Comment by mikepenz** [comment]
@Spiderbezno as mentioned i don't specify this at all. I keep it as default from the DrawerLayout
