### ISSUE TITLE
How to Lock Swipe from Left

### ISSUE THREAD

**Issue by thanhsontube** [mikepenz/MaterialDrawer#402]
Normal i used to : DrawerLayout.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED); to lock swiping to open Drawer.
How to do this with this Libs. 
Thanks

**Comment by mikepenz** [comment]
@thanhsontube just get the DrawerLayout from the Drawer and lock it.

**Comment by patelakshay13890** [comment]
Here I cannot get code for the same..
Can you provide sample or code snippet for the same ??
