### ISSUE TITLE
withCustomView shadow status bar

### ISSUE THREAD

**Issue by artemkutukov** [mikepenz/MaterialDrawer#404]
Hi, Mike! At the beginning I would like to thank you for an excellent library! Tell me how to add a transparent shadow in the status bar when using the withCustomView  method ? 

```java
Drawer result;
DrawerBuilder builder = new DrawerBuilder()
                .withActivity(this)
                .withCustomView(View.inflate(this, R.layout.menu_view, null))
                .withStatusBarColorRes(R.color.header);
result = builder.build();
result.keyboardSupportEnabled(this, true);
```

**Comment by artemkutukov** [comment]
I have 
![no_shadow](https://cloud.githubusercontent.com/assets/9209799/8056326/bb00232c-0eaf-11e5-990e-783fc50d5d62.PNG)
I need 
![shadow](https://cloud.githubusercontent.com/assets/9209799/8056329/c0dc96c2-0eaf-11e5-943a-407df4fa272e.PNG)

**Comment by mikepenz** [comment]
@artemkutukov if you use a custom header .you will have to manually overlay it. you can look at the logic how i create this overlay for the normal header. I can point you to the source if you are interested?

**Comment by artemkutukov** [comment]
Yes , of course . the shadow will be applied on the status bar ?of the toolbar

**Comment by artemkutukov** [comment]
Maybe I need add drawable to status bar ?

**Comment by mikepenz** [comment]
You can add something like this to your layout:

```xml
<View
        android:layout_height="@dimen/tool_bar_top_padding"
        android:layout_width="match_parent"
        android:background="#59000000"
        android:layout_alignParentTop="true"
        android:id="@+id/shadow_top" />
```

make sure you set it's height correctly afterwards as this is different over some api levels. also make sure you hide it on older api levels.

**Comment by artemkutukov** [comment]
ty, Mike!
