### ISSUE TITLE
Updating drawer item descriptions problems

### ISSUE THREAD

**Issue by vgf89** [mikepenz/MaterialDrawer#405]
The description of a drawer item cannot be updated with a string (item.setDescription("some string") then drawer.updateItem(item)) if that item was instantiated using a string resource for the description (new PrimaryDrawerItem().withDescription(R.string.xxx)). However, item.setDescriptionRes(R.string.xxx) will update the description.

I haven't done any additional testing to see if using .setDescriptionRes() causes similar behavior, or if the description can't be set as a resource if it was been set as a string, but that might also be an issue. I also haven't checked if the issue exists for titles.

I'm using MaterialDrawer 3.0.6 and nightly Cyanogenmod 12 (Android 5.1.1) on a OnePlus One.

EDIT: forgot to mention that I do call drawer.updateItem(item) after I set the description.

**Comment by mikepenz** [comment]
@vgf89 you should not trust the set... methods to update the item. Always make sure to update an item via the update methods via the `Drawer` object

**Comment by vgf89** [comment]
Oh, sorry, I left that out.

I always call drawer.updateItem(item) every time I update the description. It doesn't change the behavior.

**Comment by mikepenz** [comment]
@vgf89 i assume his happenes because i did not reset the other value. so if you set it via res and then via string the res would have still been set. this will be fixed in the next version
