### ISSUE TITLE
CardListView is getting "squeezed"

### ISSUE THREAD

**Issue by appmath** [mikepenz/MaterialDrawer#41]
For some reason, the awesome Gabriele Mariotti's CardListView is not properly displayed.
Screenshot:  
  Left: used a regular drawerlayout
  Right: MaterialDrawer.

BTW, I have tried all of the available DrawerLayout libs and this is by far my favorite, I love its flexibility and the fact that I don't have to extend any bloody class. I also love the fact that it's activity-friendly.

Aziz
![cardlistview_vs_recyclerview](https://cloud.githubusercontent.com/assets/4098053/6406229/fac9c91a-bdea-11e4-83c6-7f9fdf227c22.png)

**Comment by mikepenz** [comment]
@appmath seems it must have to do something with the theme. Which style do you use?

As far as i can tell the MaterialDrawer itself is not the cause for this issue.

It seems that on the right your cardViews contain a padding on top and at the bottom. can you check which padding dimensions are in use there?

**Comment by appmath** [comment]
Here is the ent
Hello Mike,
Here is the entire layout:
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card="http://schemas.android.com/apk/res-auto"
    android:gravity="center"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
        android:background="@color/md_black_1000">

    <RelativeLayout
        android:id="@+id/toolbar_container"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="?attr/colorPrimary"
        android:paddingTop="@dimen/tool_bar_top_padding">
        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            android:elevation="4dp"
            android:transitionName="actionBar"/>
    </RelativeLayout>

    <FrameLayout
        android:layout_below="@id/toolbar_container"
        android:id="@+id/frame_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <it.gmariotti.cardslib.library.view.CardListView
                android:id="@+id/product_cardlistview"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                card:list_card_layout_resourceID="@layout/list_card_thumbnail_layout"
                style="@style/list_card.thumbnail"/>

    </FrameLayout>
</RelativeLayout>

card:list_card_layout_resourceID and style are Grabriele's baked-in values.

The black background was added to show the unexpected gaps.
I have used Gabriele's cards inside a regular DrawerLayout and outside of it and this is the first time I notice this behavior. I can ask him if he has ever ran into something like this.

**Comment by mikepenz** [comment]
The layout itself seems to be correct. 

Will it still display if you remove the drawer again (keep the dependency)? If the issue is still there remove the dependency too? Something must be different with the styles. 
 
Do you use my styles too?

**Comment by appmath** [comment]
So far nothing seems to be helping:
1)	I removed the drawer and all of its dependencies
2)	I removed the CardListView style
3)	Yes, I am using your styles. I have also switched to different styles.

**Comment by mikepenz** [comment]
@appmath ok now we know it has to be something with the cardView and nothing depending to the MaterialDrawer. probably you should ask Gabriele for help?
