### ISSUE TITLE
background shadow underneath actionbar?

### ISSUE THREAD

**Issue by ToonvanStrijp** [mikepenz/MaterialDrawer#410]
Heeey,

I want my background shadow to be below the actionbar, who can help me out! :)

And another thing... can i animate the actionbar color while im pulling the drawer out?
![schermafbeelding 2015-06-10 om 18 38 35](https://cloud.githubusercontent.com/assets/11893063/8088301/95bac058-0fa0-11e5-9b14-de556f725e79.jpg)

**Comment by mikepenz** [comment]
@ToonvanStrijp this is not possible by default as the DrawerLayout will be in the root of the activity. To get the same look you will have to use an ActionBar (don't do this) or you follow the instructions in the https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java

**Comment by mikepenz** [comment]
@ToonvanStrijp i'm sorry that there is no "easier" way to achieve this. 

In fact why do you want it to be under the toolbar? this is wrong?
