### ISSUE TITLE
header and AccountHeader in the same drawer?

### ISSUE THREAD

**Issue by cmonfortep** [mikepenz/MaterialDrawer#411]
is it possible to have a header and an AccountHeader in the same drawer?

If I set the account header, my header dissapears. I need to have a header and after this header an AccountHeader.

Thanks!

**Comment by mikepenz** [comment]
@cmonfortep no this is not possible. The only "workaround" which will work is that you create a customDrawerItem which you will then add in the first position of the list?

**Comment by cmonfortep** [comment]
Thanks for your fast response.

With this workaround, will the position of the header be over or below the AccountHeader? I need it over it.

**Comment by mikepenz** [comment]
@cmonfortep hmm if you need it over there is another work around which would work. you can just create the AccountHeader and obtain it's view and add it to your custom header. (a bit more work, but it will work ;))

**Comment by cmonfortep** [comment]
Thanks, I'll check it.

**Comment by mikepenz** [comment]
@cmonfortep just let me know if you need more help :D
