### ISSUE TITLE
withIconColor/withIconColorRes not working

### ISSUE THREAD

**Issue by badoualy** [mikepenz/MaterialDrawer#414]
Hi, thank for the awesome lib !

I want to use withIconColor/withIconColorRes to tint my icon drawable, but it's not working
```
new PrimaryDrawerItem()
    .withName(R.string.inbox)
    .withTextColorRes(R.color.ic_navigation)
    .withIcon(R.drawable.ic_inbox_white_24dp)
    .withIconColorRes(R.color.primary)
```

My ultimate goal is to have 1 tint color for unselected (normal) state, and 1 tint color for selected state, the selection color works fine with

```
.withTintSelectedIcon(true)
.withSelectedIconColorRes(R.color.primary)
```

Am I missing something ?

Thanks

**Comment by mikepenz** [comment]
@badoualy and you still enable icon tinting in the above example?

**Comment by badoualy** [comment]
I tried with and without, not working in both cases

**Comment by mikepenz** [comment]
@badoualy as you can see it has both the same logic: https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/java/com/mikepenz/materialdrawer/model/PrimaryDrawerItem.java#L199 so if coloring is working for the selected one, it will also work (with the correct properties) with the normal one

**Comment by badoualy** [comment]
Well, I thought my bug came from using the same icon multiple times without being mutable, but tried again, still not working

**Comment by mikepenz** [comment]
@badoualy i do the mutable stuff inside the project. so you don't have to worry about this ;)

**Comment by badoualy** [comment]
@mikepenz Ok just forget about this, so tired I didn't even think of checking if I had the latest version, I did not, should probably be ok now, sorry for this !

**Comment by mikepenz** [comment]
@badoualy please report if it's working with the latest version. if not i will take a closer look

**Comment by badoualy** [comment]
Working like a charm ! Sorry for wasting your time !

**Comment by mikepenz** [comment]
@badoualy no problem ;).
