### ISSUE TITLE
PrimaryDrawerItem should support loading URI image through Picasso

### ISSUE THREAD

**Issue by mingqlin** [mikepenz/MaterialDrawer#415]
There use cases when PrimaryDrawerItem need to load URI image into the left icon. Think of YouTube app, Drawer Item are dynamically added when user subscribe to a channel. and channel image is displayed. hope you would consider this feature as enhancement. tks!

**Comment by mikepenz** [comment]
@mingqlin at the moment you can implement this with a CustomDrawerItem. Just look at the source of the PrimaryDrawerItem and add it for you ;). Should not be that much work. I am still not sure if i should add it by default.

**Comment by ranjithstar256** [comment]
hi mikepenz! glad to write to you! i just implemented ComplexHeaderDrawer in my app! thanks a lot to you :+1:  i loved your user friendly codes! 
and now o do have one doubt that is,  in my app based on the parameter that i pass, i want to load drawer items dynamically. 
How can i do this? how can i use CustomPrimaryDrawerItem?  can i have any example implementing dynamic drawer items?
Thanks in advance! :)

**Comment by mikepenz** [comment]
@ranjithstar256 please head over to gitter or open a new issue.

**Comment by ranjithstar256** [comment]
sorry @mikepenz i'm new to github! just created and added you on my gitter conversation.
thanks :+1:
