### ISSUE TITLE
Supporting loading image using Facebook Fresco

### ISSUE THREAD

**Issue by mingqlin** [mikepenz/MaterialDrawer#416]
Loading images in Material Drawer using Picasso, UIL or Glide are straight forward through DrawerImageLoader.init() method. 

But for developers who have migrated Image Loader to Facebook Fresco, it is quite challenge to use Fresco with Material Drawer. Since it doesn't use ImageView, instead it uses its own SimpleDraweeView. 

Are there anyway Material Drawer could improve to also support Fresco? or could someone shed light on how to use Fresco to load image in Material Drawer?

**Comment by Anatidae-Project** [comment]
I think you can go two ways. First, you can just extend the header class and add your own methods to handle fresco drawees. 

Another way is to use the Fresco pipeline to grab the bitmap:
http://frescolib.org/docs/using-image-pipeline.html#_

The first way you'll have to mask the Fresco image yourself. 
http://frescolib.org/docs/modifying-image.html#_

The second you're losing some of the features of Fresco...  The thing is Fresco just uses a pretty different method handling images. I'm using a project with Fresco for a lot of the images in the list views and galleries, but honestly I also have Retrofit in there for other uses - such as profile icons in the drawer here and a couple other places where I want more traditional access to the imageview/bitmaps.

**Comment by mikepenz** [comment]
@mingqlin i have not used fresco yet but there is the DrawerImageLoader thing i added to use any image loader. As long as it takes an imageView and a url.

https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java#L22

**Comment by MummyDing** [comment]
@mingqlin  I met the same issue and I found solution here: https://github.com/facebook/fresco/issues/364
```java
    DataSource <CloseableReference<CloseableImage>> dataSource = Fresco.getImagePipeline().fetchDecodedImage(ImageRequest.fromUri(Uri.parse(IMAGE_URL)),getApplicationContext());

    dataSource.subscribe(new BaseBitmapDataSubscriber() {
                             @Override
                             public void onNewResultImpl(@Nullable final Bitmap bitmap) {
                                 IMAGEVIEW.post(new Runnable() {
                                     public void run() {
                                         IMAGEVIEW.setImageBitmap(bitmap);
                                     }
                                 });
                             }

                             @Override
                             public void onFailureImpl(DataSource dataSource) {
                                 // No cleanup required here.
                             }
                         },
            CallerThreadExecutor.getInstance());
```

It works well.

**Comment by mikepenz** [comment]
@MummyDing thanks for adding your solution :)
