### ISSUE TITLE
Drawer created but no surface reaction on menu items

### ISSUE THREAD

**Issue by agungsijawir** [mikepenz/MaterialDrawer#420]
Hello,

I tried your code and it was amazing! But, something missing from my code. Yes, that is any menu items on drawer has no surface reaction. I tried to follow your code on `CustomContainerActivity.java` and this layout `activity_sample_custom_container_dark_toolbar.xml`.

Here is my modifications:
https://gist.github.com/agungsijawir/a3a742c194453babd6ba

Also, I notice that ActionBarDrawerToggleAnimation seems not working even if I set `true`. Sorry if my english is not good.

Any missing from my code? My phone using Android 5.0.2 (non-custom rom), 

Please help, thank you :smiley:

**Comment by mikepenz** [comment]
@agungsijawir what do you mean with no surface reaction?

ActionBarDrawerToggle is only working if you set the toolbar for the Drawer.

**Comment by agungsijawir** [comment]
Hi @mikepenz 

Please take a look on this:
https://www.google.com/design/spec/animation/responsive-interaction.html#responsive-interaction-user-input

Yes, ActionBarDrawerToggleAnimation is working now. The remain *beauty* of material drawer still not work for me, at least my project.

**Comment by mikepenz** [comment]
@agungsijawir still not sure what you mean because there is a ripple effect on click with API 21+

perhaps you use the wrong theme?

**Comment by agungsijawir** [comment]
I was wrong when define `CustomTheme`'s `parent`.  I define `parent` for `CustomTheme` like follows:
`<style name="CustomTheme" parent="MaterialDrawerTheme">`

But I change to:
`<style name="CustomTheme" parent="MaterialDrawerTheme.Light.DarkToolbar">`

Now, ripple effect works. I will close this ticket.

Thank you @mikepenz for the clue :smiley:

**Comment by mikepenz** [comment]
@agungsijawir :) the problem is that the wrong theme has a differen ripple color and this color is not visible then :D

**Comment by agungsijawir** [comment]
Ah... I see, so that is how it works. 
Sorry for such question, still learning ... :sweat_smile:
