### ISSUE TITLE
Toggling the drawer with ActionBar

### ISSUE THREAD

**Issue by iSimar** [mikepenz/MaterialDrawer#422]
Hey Mike,

Great Lib. 

I'm trying to build a simple drawer with the toggling feature (w/ 'hamburger to back' icon animation) in the action bar. 

I have done the following:
````
.withActionBarDrawerToggle(true)
.withActionBarDrawerToggleAnimated(true)
````

It doesn't seem to be working, my code looks very similar to this file:
https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/ActionBarDrawerActivity.java

**Comment by mikepenz** [comment]
@iSimar have you looked at the sample app?

**Comment by iSimar** [comment]
I have, the thing is minSDKVersion is set to 15 (which has no toolbar only actionbar).
I'm trying to get the toggle drawer(open and close using icons) to work with the actionbar (which doesn't seem to be working the sample app ethier) 

The thing I want is similar to whats done with CustomContainer Drawer in the Sample App.

**Comment by mikepenz** [comment]
@iSimar toolbar is available starting with v7. you have to use the appcompat so what's the issue?

the thing is that the actionBar is more or less deprecated. the sample app shows how to do the back button. just as a note. this is basic Android stuff, and you will find enough answers how to do this with a DrawerLayout (which my lib uses)

About this. You should not do this. this is not material design conform

**Comment by iSimar** [comment]
you are right, it worked! 

Thank you Mike.
