### ISSUE TITLE
MultiAccount list, icon has weird gravity

### ISSUE THREAD

**Issue by badoualy** [mikepenz/MaterialDrawer#423]
Hi,

(this time I'm on the latest version)
I have a weird bug in the account list, I'm using textdrawable library to have a text icon, but the selected item behave in a weird way.

When not selected, the icon is displayed as it should, like the other account, when I select on, the drawable gravity is changed (displayed from top-left corner instead of center from what I can see).

The only difference between the 2 icons is the color.

![screenshot_2015-06-14-18-44-51](https://cloud.githubusercontent.com/assets/3463818/8150074/74315bf2-12db-11e5-8c27-d97da766e88b.png)

Any idea ?

**Comment by mikepenz** [comment]
@badoualy i assume the library you use creates a wrong drawable. have not had any issues with the Circular ImageView i use (it's from the Google IO app)

**Comment by badoualy** [comment]
@mikepenz The weird thing is that the code to generate the icon above the first one is the same, and there's no bug with it when not selected

**Comment by mikepenz** [comment]
@badoualy the icon only shows this way when the line is selected? really? that's really weird. no different code between selected or non selected

**Comment by badoualy** [comment]
@mikepenz yes, exactly, this is what I don't understand

**Comment by mikepenz** [comment]
@badoualy have you found out something new?

**Comment by badoualy** [comment]
@mikepenz no, only that I have the similar issue in the top header, when the account list is expanded and I select one item through the list and not the top-header icon

**Comment by mikepenz** [comment]
@badoualy i have added the functionality to Android-Iconics to create drawables with a text. So can you try to use this, and report if it also creates the same troubles for you?

(The latest version of Android-Iconics is included in the latest MaterialDrawer ;) )

**Comment by badoualy** [comment]
@mikepenz Very nice ! I'll test ASAP, probably Monday ! (I myself was using TextDrawable, maybe the issue is in this library)

**Comment by mikepenz** [comment]
@badoualy yeah i just want to make sure it is not caused by the MaterialDrawer

**Comment by badoualy** [comment]
@mikepenz Ok, I updated the code that generates the drawable to specify the size (40dp from what I saw in dimen.xml), and it works fine !
