### ISSUE TITLE
DrawerLayout setDrawerLockMode()

### ISSUE THREAD

**Issue by chesiq** [mikepenz/MaterialDrawer#424]
Hi. I've been using your library for a while. It's awesome. Thank you for your work.
I need [one feature](https://developer.android.com/reference/android/support/v4/widget/DrawerLayout.html#setDrawerLockMode(int, int)) from DrawerLayout class.
How can I set drawer lock mode?

Thanks for your time.

**Comment by mikepenz** [comment]
@chesiq just geht the DrawerLayout from the Drawer object?

**Comment by Mozasis** [comment]
thank you :)))
