### ISSUE TITLE
Conflict with new Android Material Design Library.

### ISSUE THREAD

**Issue by Quarx2k** [mikepenz/MaterialDrawer#425]
If i add "com.android.support:design:22.2.0" to project. I get error "Attribute "rippleColor" has already been defined" Full error: http://pastebin.com/3DLmHLb7
I'm use 3.0.7 version of your lib.
Thanks!

**Comment by mikepenz** [comment]
@Quarx2k rippleColor is not defined in this project.

**Comment by mikepenz** [comment]
The only case which could cause problems is that this project contains the 
`compile "com.android.support:appcompat-v7:22.2.0"`

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/379

**Comment by kulafine** [comment]
make sure there is no design library in your gradle
