### ISSUE TITLE
result.getActionBarDrawerToggle() is null

### ISSUE THREAD

**Issue by sigrlami** [mikepenz/MaterialDrawer#426]
When using simple builder wit or without line `.withActionBarToggle` toggle always `null` how to fix this?

**Comment by mikepenz** [comment]
@sigrlami i assume you forgot to pass the toolbar

**Comment by cami7ord** [comment]
But what about when i don't have a Toolbar and I'm using the "Activity with ActionBar" builder?

**Comment by mikepenz** [comment]
@cami7ord if you have an `ActionBar` you will have to handle the hamburger icon on your own. 

I really suggest you to update to a `Toolbar` this is done within 3 minutes and allows you to have a `Drawer` which goes below the `StatusBar` and follows the Google Material Design Guidelines
