### ISSUE TITLE
Why does not support drawer selected icon color ?

### ISSUE THREAD

**Issue by leelei** [mikepenz/MaterialDrawer#427]
```
<activity
            android:name=".ui.activity.HomeActivity"
            android:theme="@style/MaterialDrawerTheme"
            android:label="@string/title_activity_home" >
        </activity>
```

```
 new PrimaryDrawerItem().withName(R.string.drawer_item_news_info)
                .withIcon(R.drawable.ic_drawer_item_news_info)
```

when drawer item selected, icon select color does not work

**Comment by mikepenz** [comment]
@leelei i assume that you don't have enabled tinting?

**Comment by leelei** [comment]
I do not understand, why need enabled enabled tinting ? drawer icon has nomal color and selected color , but if i  use
```
new PrimaryDrawerItem().withIcon(FontAwesome.Icon.faw_home)
```
replace
```
new PrimaryDrawerItem().withIcon(R.drawable.faw_home)
```
it is ok

**Comment by mikepenz** [comment]
because if you use the built in vector icon library it is able to automatically color the icons. this is a complete different thing. 

if you pass an drawable i won't magically color it. you have to enable tinting for drawables you pass manually
