### ISSUE TITLE
Badge Backgrounds

### ISSUE THREAD

**Issue by ch4ot1c** [mikepenz/MaterialDrawer#428]
Hi Mike! Great work on this library!
Do you think you could allow a Drawable behind any ColorfulBadgeable in your next release? This would allow me to do some custom layouts 1-notch more complex than just changing the text color.

Or did I miss something, and is this already doable?

Thanks in advance

**Comment by mikepenz** [comment]
@ch4ot1c as of this commit it should be possible: https://github.com/mikepenz/MaterialDrawer/commit/25b1a1976028bc71c0835edca9f9ac9584cc3100

**Comment by ch4ot1c** [comment]
Just didnt see it on the first, second, or third pass! HAHA! Thanks
Working.
