### ISSUE TITLE
RTL language issue with android:gravity="center_vertical|left" 

### ISSUE THREAD

**Issue by mingqlin** [mikepenz/MaterialDrawer#429]
This repository search 
android:gravity="center_vertical|left"

you will find there are still few places in layout files have android:gravity="center_vertical|left" in TextView. the "left" attribute, cause RTL language like Arabic to always align to the left, which doesn't look good, it should default to the right in RTL language.

my suggestion is create one more same copy of layout file, and put it in layout-ldrtl folder, with android:gravity="center_vertical|right"

**Comment by mingqlin** [comment]
SS Before the change:
![device-2015-06-17-144145](https://cloud.githubusercontent.com/assets/970456/8215615/2111857a-14ff-11e5-9af4-4a2b5f6a7b5e.png)

SS After the suggested change:
![device-2015-06-17-144111](https://cloud.githubusercontent.com/assets/970456/8215623/2c3bc866-14ff-11e5-9be9-f6d2a6d3442d.png)

**Comment by mikepenz** [comment]
```xml
android:gravity="center_vertical|start"
```
should also do the job
