### ISSUE TITLE
Is MaterialDrawer compatible with Android-ObservableScrollView?

### ISSUE THREAD

**Issue by tommytcchan** [mikepenz/MaterialDrawer#431]
Hi there,
Just wanted to see if this library is compatible with the Android-ObservableScrollView library? The use case I'm trying to implement is a drawer (hamburger menu) always on the action bar, and when user scrolls down the image on the toolbar turns into text (to save real estate), very similar to the new example on the material design support library example: 

http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQscXNQY3dNdVlYeTQ/patterns-scrolling-techniques_flex_space_image_xhdpi_003.webm

**Comment by mikepenz** [comment]
@tommytcchan I don't see a thing why it should not be compatible. This library will just inflate a DrawerLayout inside a FrameInsetsLayout in the root and so the content should be as in any other application. If this is not the thing you need there you can do a more advanced setup. Most cases are shown in the sample app.
