### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by sharikovvladislav** [mikepenz/MaterialDrawer#435]
Hi,

I am trying to add your library to my android project. My project using maven as dependency manager.

I'd added dependency:
```
<dependency>
    <groupId>com.mikepenz</groupId>
    <artifactId>materialdrawer</artifactId>
    <version>3.0.7</version>
</dependency>
```

And I got error in Maven window:
![image](https://cloud.githubusercontent.com/assets/5622526/8268736/7aa94f2a-1796-11e5-8074-35d3e7902caf.png)

I tried to get what is the problem. I found your repo in mavenrepositories.com: http://mvnrepository.com/artifact/com.mikepenz/materialdrawer/3.0.7
I can see dependency ```com.android.support » appcompat-v7```, but when I press on this link, I got 404 error about repo not found. 

Is it a problem or I am doing something wrong? 

Can't use your library now.

**Comment by mikepenz** [comment]
@sharikovvladislav you develop an android app? why not use maven? The thing here is that you need to have the Google Repository on your pc. This can be installed through the Android Studio Settings -> Android SDK --> Google Support Repository

![bildschirmfoto 2015-06-20 um 21 14 34](https://cloud.githubusercontent.com/assets/1476232/8268841/6964e33c-1791-11e5-8771-5b523f6492d0.png)

**Comment by sharikovvladislav** [comment]
I am using IntelliJ IDEA for dev. I had already download tools you mentioned. But I am not sure android SDK is problem.

How maven works? He knows about some online repositories. I am adding dependency. Maven search this dependency through repositories. LIke your library. Maven found your repository ([like he found yours](http://mvnrepository.com/artifact/com.mikepenz/materialdrawer/3.0.7)) and download it. Now he can't found dependency of your repository: ```com.android.support » appcompat-v7```. May be I am missing something and maven works another way? Maybe I should include appcompat-v7 library another way?

**Comment by sharikovvladislav** [comment]
Actually, I can't find appcompat v7 anywhere. 
http://search.maven.org/#search|ga|1|appcompat%20v7
http://mvnrepository.com/search?q=appcompat+v7
https://repository.apache.org/#nexus-search;quick~appcompat%20v7

I'm sure I do not understand something.

Can you try to explain this one for me? Or can you provide some link where I can get understanding how maven works?

Another point, that I am not understanding something is you couldn't miss that fact, that dependency of your project is not found.

**Comment by mikepenz** [comment]
@sharikovvladislav oh i wanted to ask why you do not use gradle? which is the main android build system. and which handles importing files from maven. 

also it will handle the fact that all google specific libs are not on maven, only on a local maven repository which gets installed through the SDK tools. 

I know how maven works. 

> Another point, that I am not understanding something is you couldn't miss that fact, that dependency of your project is not found.
Please keep friendly. I spend my free time for creating open source, and i spend my free time to answer issues, even if they are not caused by my library like this. If you use any other library which also has an dependency to a google library you will have the same issue. 
And to be fair. Your screenshot even shows that it can't find the appcompat dependency, but mine. 

about the error you get if you include it manually. as mentioned you should use gradle for the whole project, as this is the main build system of Android. This library was set up with Android Studio and with gradle and so it is correct. 

You can find more information about Android Studio here: https://developer.android.com/sdk/index.html

**Comment by sharikovvladislav** [comment]
Firstly!!!!! 
>Please keep friendly.

Ah! I thought that you might think so! I don't want to be "not-friendly". The problem in my English, I think. I am not native-english speaking man. 

> Another point, that I am not understanding something is you couldn't miss that fact, that dependency of your project is not found.

I wanted to said here, that you couldn't do mistake at his point (```dependency of your project is not found```) and don't notice, that some of dependencies of your project are not valid. Do you get this now? Sorry, it is some language barrier. Sorry about that. (And I understand what you said about your free time etc – you are right). 

>all google specific libs are not on maven

This is the problem. I didn't knew about this.

> in a local maven repo which gets installed through the Android SDK

Hm. Strange then. I downloaded Android SDK tools. For example, I added dependencies appcompat-v7 and android-support-v4 manually (not maven dependencies) in Project Structure and it is ok. I think I have bad settings in maven if he can't find appcompat-v7 locally. Can you suggest how I can fix it?

About why I am using maven and not gradle. I think there is some fluence from my friends. They suggested to use maven, because they usually use it.

P.S.: Again sorry about my english and I am really very sad about you didn't understood me.

**Comment by sharikovvladislav** [comment]
I need some google there I think. You explained, that it is not problem of your library, but my problem.

And again sorry. I didn't wanted to hurt you.

**Comment by mikepenz** [comment]
@sharikovvladislav ok it's fine. ;)

How you can fix it. I would highly suggest you use the official tools and the official Android Studio. IT has far better support and you can be sure that it's supported. If you are new to Android development it's even better if you start of with the correct toolset. 

About the Android SDK Tools. They are different than the thing you need. The tools for Android Studio come with the SDK Manager. And through the SDK Manager you can install the tools, the apis, and also the extras, --> Google Support repository. 



Using gradle. If you start with the project and with everything. I really suggest it!. Most people will only give support if you use the correct tools. And you can be sure that there are updates in the future and that it's supported in the future
