### ISSUE TITLE
How to handle the onItemClickListener

### ISSUE THREAD

**Issue by taimur97** [mikepenz/MaterialDrawer#436]
I am a beginner and this is my question. After struggle for many hours I was not successful in handling the click events in my drawer. I don't know why it one time worked for the first one item but not for others. I tried to understand the sample code but no luck :(
Please provide me a solution
Here is my code 

```java
@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.new_activity_locker);
		handleIntent();

		// Handle Toolbar
		Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
		setSupportActionBar(toolbar);

		

	mTitle = getTitle();


		mCurrentFragment = new AppsFragment();
		getSupportFragmentManager().beginTransaction()
				.add(R.id.container, mCurrentFragment).commit();
		mCurrentFragmentType = NavigationElement.TYPE_APPS;

		mSequencer = new DialogSequencer();
		showDialogs();
		showLockerIfNotUnlocked(false);

		result = new DrawerBuilder()
				.withActivity(this)
				.withTranslucentStatusBar(false)
				.withActionBarDrawerToggle(false)
				.withHeader(R.layout.header_layout)
				.addDrawerItems(
						new PrimaryDrawerItem().withName(R.string.app_name).withIcon(R.drawable.ic_launcher),

						new SecondaryDrawerItem().withName(R.string.action_settings).withIcon(android.R.drawable.ic_menu_preferences)
				).withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
			@Override
			public boolean onItemClick(AdapterView<?> adapterView, View view, int position, long l, IDrawerItem drawerItem) {
				if (drawerItem instanceof Nameable) {
					Toast.makeText(MainActivity.this, MainActivity.this.getString(((Nameable) drawerItem).getNameRes()), Toast.LENGTH_SHORT).show();
					getSupportActionBar().setTitle(((Nameable) drawerItem).getNameRes());
					String sleected_item = MainActivity.this.getString(((Nameable) drawerItem).getNameRes());
					
				
					if ( sleected_item.equals(R.string.app_name)) {
						Fragment f = AppsFragment.newInstance(getResources().getString(((Nameable) drawerItem).getNameRes()));
						getSupportFragmentManager().beginTransaction().replace(R.id.container, f).commit();

					}else if (sleected_item.equals(R.string.action_settings)) {
											Fragment f2 = SettingsFragment.newInstance(getResources().getString(((Nameable) drawerItem).getNameRes()));
							getSupportFragmentManager().beginTransaction().replace(R.id.container, f2).commit();

					}
				}
				return true;
			}
		}).withSelectedItem(0)
				.build();
	
		getSupportActionBar().setDisplayHomeAsUpEnabled(true);
		getSupportActionBar().setHomeButtonEnabled(false);
	}
```

And here is my layout

```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:gravity="center"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        android:elevation="4dp" />
    <FrameLayout
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1" />

    </RelativeLayout>
```

As you can also see I have added Toolbar still I was not able to show a hamburger icon and also please help me how I can perform any action when my header layout is clicked. I have not added any profile I just want to perform some action when header image is clicked.
Your help will be highly appreciated

Thanks

**Comment by mikepenz** [comment]
@taimur97 you also have to pass the toolbar to the drawer with `withToolbar()`

**Comment by taimur97** [comment]
thanks for your help the toolbar issue is now resolved
the onClick problem is I can't figure out how to perform some action based on the item clicked in the drawer. You can Well you can destroy the asshole. There are some legal ways to fight with them and there are also some illegal ways. You can contact writers of some popular how I am trying to change my fragment in the onClick method but its not working.

**Comment by mikepenz** [comment]
You can define an identifier per drawerItem and check for that identifier in the onClick method. It's the best method. 

Just take a close look at how it'S done in the sample app. It does everything you need ;)

**Comment by taimur97** [comment]
Thanks everything seems to be resolved now only one problem left Is there any way to set an imageview as header background? As far I see only a drawable or layout can be used as the background and when i change the header background should I rebuild the header and again add it to the drawer? I tried converting an imageview to drawable but after setting it as the header background there was no image set and the header background became empty(Just white empty space)
I tried the following code 
header_background.buildDrawingCache();
			Bitmap bmap = header_background.getDrawingCache();
			// Set click listener
			Drawable d = new BitmapDrawable(getResources(), bmap);
			headerResult.setBackground(d);

**Comment by taimur97** [comment]
@mikepenz Hi, sorry for informing you late everything is working great thank u so much for this amazing library
