### ISSUE TITLE
Select account with header toggle when selection list opened

### ISSUE THREAD

**Issue by badoualy** [mikepenz/MaterialDrawer#437]
For each account, I use a different color scheme, so I update the status bar color and the toolbar color, everything works fine, but when I select an account from the header's toggle when the selection list is opened, the status bar color is not invalidated right away, I have to touch the screen once before the color changes.

It works fine when the selection list is not opened, I don't really understand !

I'm using 

    drawer.setStatusBarColor(darkColor);

to update the color, should I call another method to invalidate?

**Comment by mikepenz** [comment]
@badoualy i will add a method to get the ScrimInsetsFrameLayout in the next verison, so you can call invalidate on it

**Comment by badoualy** [comment]
@mikepenz Ok thanks, closing the issue then
