### ISSUE TITLE
Result.withHeaderBackground PrimaryDrawerItem should support loading URI image through Picasso

### ISSUE THREAD

**Issue by korrio** [mikepenz/MaterialDrawer#438]
Will this be possible on the next version as long as you can set your avatar from the URI.

**Comment by taimur97** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java

**Comment by korrio** [comment]
It's able to load URI only for profile's avatar but not background.

**Comment by taimur97** [comment]
I am trying to solve the exact problem what I am doing is creating an imagview then loading the image into it after that converting it to drawable and then setting it as the background but it's not working properly. Check the issue onClickLIstener you will find the code I am trying

**Comment by mikepenz** [comment]
@taimur97 why do you need to go the way over the imageView? picasso and other image loading libs still allow you to fetch it as bitmap or drawable?

**Comment by taimur97** [comment]
that's because I am trying to display a native ad and this is the way how the ad network integration works. They will bind my imageview and will load the image inside it and then I can use the imageview anywhere.
					Like This	avocarrotCustom.loadImage(ad, header_background);
In case if you want to try the ad network you can use my referral link you will get a $30 welcome bonus using my link http://www.avocarrot.com/?refcode=8080833c

**Comment by mikepenz** [comment]
@taimur97 you can also get the `ImageView` of the header by calling `header. getHeaderBackgroundView()` ?

**Comment by mikepenz** [comment]
@korrio the header background is accessible via it's view? see previous answer. also you can easily extend the `PrimaryDrawerItem` if you need extended functionality

**Comment by korrio** [comment]
@mikepenz got it, thankyou.
