### ISSUE TITLE
Proguard? 

### ISSUE THREAD

**Issue by danielgomezrico** [mikepenz/MaterialDrawer#440]
Hi

Is there any proguard setup ?

I´m getting:

`E/dalvikvm﹕ Could not find class 'com.mikepenz.materialdrawer.view.BezelImageView$CustomOutline', referenced from method com.mikepenz.materialdrawer.view.BezelImageView.onSizeChanged`

**Comment by mikepenz** [comment]
@danielgomezrico this is normal. This is caused because this specific option is only available on API > 21

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/view/BezelImageView.java#L134

**Comment by danielgomezrico** [comment]
Not sure if this is because of that but I have a MapView inside the fragment and the menu appears behind it.

It happen on Nexus s with  `4.0.4`

![20150623_143110](https://cloud.githubusercontent.com/assets/76348/8315253/e1779142-19b4-11e5-9569-7f73e560c912.jpg)

**Comment by mikepenz** [comment]
you init the drawer without modifications? or have you any special setup?

**Comment by danielgomezrico** [comment]
My Init:

```
if (menuDrawer == null) {
                headerResult = new AccountHeaderBuilder()
                        .withActivity(this)
                        .withSelectionListEnabled(false)
                        .withHeaderBackground(R.drawable.status_drawer_header_background)
                        .withOnAccountHeaderListener(this)
                        .addProfiles(
                                new ProfileDrawerItem()
                                        .withName(customer.getName())
                                        .withEmail(customer.getEmail())
                                        .withIcon(ResourceHelper.getDrawable(this,
                                                R.drawable.ic_account_circle_white_48dp))


                        ).build();

                menuDrawer = new DrawerBuilder()
                        .withActivity(this)
                        .withToolbar(toolbar)
                        .withOnDrawerItemClickListener(this)
                        .withAccountHeader(headerResult)
                        .withActionBarDrawerToggleAnimated(true)
                        .withActionBarDrawerToggle(true)
                        .withTranslucentStatusBar(true)
                        .build();
            } else {
                menuDrawer.removeAllItems();
            }

            IProfile profile = headerResult.getProfiles().get(0);
            profile.setName("username");
            profile.setEmail("email");
            headerResult.updateProfileByIdentifier(profile);

            menuDrawer.addItems(
                    new PrimaryDrawerItem()
                            .withName(R.string.title_fragment_status)
                            .withIcon(R.drawable.ic_map_black_24dp)
                            .withIconTintingEnabled(true)
                            .withIdentifier(1),

                    new PrimaryDrawerItem()
                            .withName(R.string.title_fragment_orders)
                            .withIcon(R.drawable.ic_access_time_black_24dp)
                            .withIconTintingEnabled(true)
                            .withIdentifier(2),

                    new PrimaryDrawerItem()
                            .withName(getString(R.string.title_activity_credit_card_picker))
                            .withIcon(R.drawable.ic_payment_black_24dp)
                            .withIconTintingEnabled(true)
                            .withIdentifier(3),

                    new DividerDrawerItem(),

                    new SecondaryDrawerItem().withName(R.string.drawer_item_faq)
                            .withCheckable(false)
                            .withIdentifier(-1),

                    new SecondaryDrawerItem().withName(R.string.drawer_item_become_driver)
                            .withCheckable(false)
                            .withIdentifier(-2),

                    new SecondaryDrawerItem().withName(R.string.drawer_item_contact)
                            .withCheckable(false)
                            .withIdentifier(-3),

                    new DividerDrawerItem(),

                    new SecondaryDrawerItem().withName(R.string.drawer_item_logout)
                            .withCheckable(false)
                            .withIdentifier(-4)
            );
```

**Comment by mikepenz** [comment]
@danielgomezrico i assume it has to do something with the map because if you take a close close look on the map you will see that the drawer is visible a bit in the area of the locate button

**Comment by danielgomezrico** [comment]
I just reported here https://code.google.com/p/android/issues/detail?id=186149 if someone gets the same problem.

**Comment by danielgomezrico** [comment]
@mikepenz there´s a way to avoid it.

1. Open the app
2. Show the drawer.
3. Resume the app with the drawer visible.
4. Open it again and now it looks right.

What can I do to avoid it? :+1:

**Comment by mikepenz** [comment]
@danielgomezrico i think you should not refer to a library in an official android bug report. have you tried it with a normal DrawerLayout with the ScrimInsetsFrameLayout without any library code? 

Also do you use the latest version? updated to the latest appcompat libs?

**Comment by danielgomezrico** [comment]
@mikepenz why should not refer a library? I was trying to give all the info I can to them.

 I´m using `4.0.8` and support libs are `23.0.1` but haven't tried with the normal one. I will. :+1:

**Comment by mikepenz** [comment]
@danielgomezrico i mean refer to the MaterialDrawer library. the android team can only care if it's just their apis. and if this is reproduceable with just the DrawerLayout and nothing more

**Comment by danielgomezrico** [comment]
@mikepenz got it, :+1:

**Comment by carmelo-ruota** [comment]
Seem this resolves the issue :) 
http://stackoverflow.com/questions/15432961/slidingdrawer-over-googlemap/16231935#16231935
