### ISSUE TITLE
Drawer Toggle listener 

### ISSUE THREAD

**Issue by rajazeeshanahmed** [mikepenz/MaterialDrawer#441]
As normal drawer class contains the drawer open and close listener which we can achieve thorough setting the toggle listener. I want to implement here the same thing e.g. on drawer open listener and on drawer close listener. please help

**Comment by mikepenz** [comment]
great that you found your answer

**Comment by milaptank** [comment]
May be help else one 

``` 
Drawer result = new DrawerBuilder()
    .withActivity(this)
    .withToolbar(toolbar)
    .addDrawerItems(
	    item1,
	    new DividerDrawerItem(),
	    item2,
    )
   .withOnDrawerListener(this)  // this will notify us
    .build();
```
