### ISSUE TITLE
Define customize DrawerItem

### ISSUE THREAD

**Issue by shic** [mikepenz/MaterialDrawer#442]
I would like to use the side bar on the right as the filter section like Foursquare filter ( http://techaeris.com/wp-content/uploads/2014/08/DFG_2014-08-06-10-55-15-887x1500.png ). But I noticed that there are only SectionDrawerItem.java, SwitchDrawerItem.java and ToggleDrawerItem.java that defined toggle and switch. But they are not enough to define the filters. I would like to ask if I can define my own layout for the sidebar or add more options to the DrawerItem? Thanks in advance!

**Comment by mikepenz** [comment]
@shic were you able to figure it out?

**Comment by shic** [comment]
Reading the source code of ToggleDrawerItem class.

**Comment by mikepenz** [comment]
@shic it is the only correct solution ;). +1

**Comment by shic** [comment]
I think it's better to write it in the readme file or somewhere. What do you think?

**Comment by mikepenz** [comment]
i should. but implementing new things or bugfixing is of a higher prio for me :D you can add it if you like ;)

**Comment by shic** [comment]
In face I would like to use the lib 3.0, but all versions above the 3.0 not works for my project. so I have to use materialdrawer:library:2.9.7 for now. I don't know if there are some conflicts.

**Comment by mikepenz** [comment]
@shic ;) https://github.com/mikepenz/MaterialDrawer#-v298
