### ISSUE TITLE
Disable profile click and hiding the dropdown arrow

### ISSUE THREAD

**Issue by AngleV** [mikepenz/MaterialDrawer#443]
In case someone wants to have only one profile is there any way to disable the click event on whole header?
Also is it possible to hide the dropdown arrow?

**Comment by raghunandankavi2010** [comment]
You can design a customer header and attach it to the drawer

**Comment by mikepenz** [comment]
@AngleV yes you can just pass one profile and use the `withSelectionListEnabledForSingleProfile(false)`  method
