### ISSUE TITLE
Enabling / Disabling Drawer

### ISSUE THREAD

**Issue by paulgavrikov** [mikepenz/MaterialDrawer#444]
Is it possible to enable or disable the drawer? Basically this would mean ignore toggle input and ignore swipe gestures.

**Comment by mikepenz** [comment]
@paulgavrikov this can be done via the DrawerLayout functions. Just get the DrawerLayout and lock it.
https://github.com/mikepenz/MaterialDrawer#can-i-lock-the-drawer
