### ISSUE TITLE
Header SelectionViewClickListener not called when using custom header

### ISSUE THREAD

**Issue by jbarr21** [mikepenz/MaterialDrawer#445]
I just migrated from v2.9.2 to v3.0.8 and I'm noticing that on my Nexus 5 on Android 5.1 that my `OnAccountHeaderSelectionViewClickListener` is not getting called when I use the `withAccountHeader()` option to set a custom header layout.  This was working for me before, so I was wondering if this was expected or a bug. If it is expected, it may be nice to throw an `AssertionError` saying that the 2 can't be used together.

Edit: FWIW I do have `withSelectionListEnabledForSingleProfile() set to `false`

**Comment by mikepenz** [comment]
@jbarr21 just tried it and it's working for me. i also have a Nexus 5 with Android 5.1. 

Any special setup?

**Comment by jbarr21** [comment]
building my drawer w/:
```
DrawerBuilder drawerBuilder = new DrawerBuilder()
                .withActivity(mDrawerHost.getActivity())
                .withToolbar(mDrawerHost.getToolbar())
                .withTranslucentStatusBar(true)
                .withAccountHeader(mAccountHeader)
                .withOnDrawerItemClickListener(this)
                .withOnDrawerNavigationListener(this)
                .withSavedInstance(savedInstanceState);
```

and my header with:
```
new AccountHeaderBuilder()
                .withActivity(activity)
                .withTranslucentStatusBar(VERSION.SDK_INT >= VERSION_CODES.LOLLIPOP)
                .withAccountHeader(R.layout.my_own_custom_layout)
                .withHeaderBackground(R.color.material_drawer_dark_header_background)
                .withCompactStyle(true)
                .withProfileImagesVisible(false)
                .withSelectionSecondLineShown(false)
                .withTypeface(TypefaceUtils.load(activity.getAssets(), "fonts/OpenSans-Semibold.ttf"))
                .addProfiles(getProfileDrawerItem())
                .withSelectionListEnabledForSingleProfile(false)
                .withOnAccountHeaderSelectionViewClickListener(new AccountHeader.OnAccountHeaderSelectionViewClickListener() {
                    @Override
                    public boolean onClick(View view, IProfile iProfile) {
                        // do stuff
                        return true;
                    }
                })
                .build();
```

my custom layout for the account header is very similar to the standard compact header layout

**Comment by mikepenz** [comment]
@jbarr21 why you return true inside your onClick listener?

does the my_own_custom_layout.xml contain all the ids of the original layout? the thing is that the selection listener is different for devices with api >= 21. then it's set over the whole view, not only the selection area as before

**Comment by jbarr21** [comment]
i returned true because i've consumed the event, correct? i tried this with false, too, and it did not work there either.

yes it has the same ids.

if it's working for you, then i'll assume its just custom handling on my side and can work through it some more. thanks!

**Comment by mikepenz** [comment]
@jbarr21 correct ;)

yes it fires the event when i set the breakpoint inside the listener. something has to be different with the layout.
