### ISSUE TITLE
Lock Drawer & Show BackPress in Fragment

### ISSUE THREAD

**Issue by patelakshay13890** [mikepenz/MaterialDrawer#446]
How to Lock Drawer & Show BackPress in ActionBar in Fragment ??

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/444
https://github.com/mikepenz/MaterialDrawer/issues/424
https://github.com/mikepenz/MaterialDrawer/issues/402
--> https://github.com/mikepenz/MaterialDrawer/issues?utf8=%E2%9C%93&q=lock

About showing back arrow
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/ComplexHeaderDrawerActivity.java#L159

**Comment by patelakshay13890** [comment]
ya it's get locked on Swiping the Screen but when I click on Drawer-icon on
top left most the Drawer is get opened, so how can I disable on the Drawer
Icon click also ...

**Comment by mikepenz** [comment]
@patelakshay13890 you can try the sample app. and open the ComplexHeader Drawer activity. And try it. It will work as expected and close the current activtiy with the arrow.

**Comment by gparigibini** [comment]
Hi Mike, I've the same problem: I want to open a fragment and visualize the arrow icon to go back, with the drawer locked. 
If I call setDisplayHomeAsUpEnabled(true), I can see the arrow icon as expected. 
But if I click on it, it opens the drawer instead of going back: neither onBackPressed nor onOptionsItemSelected are called. I've tried also using setHomeButtonEnabled(false), setDrawerIndicatorEnabled(false), it always opens the drawer.
I've tried looking at the demo source, but I didn't find anything that might help.
Can you kindly suggest me what I'm missing?

Thank you!

**Comment by mikepenz** [comment]
@gparigibini please check the code of the sample application. it showcases how this is working. you can even download the sample via google play and try it out. (You should open the Complex Header Drawer activity)

Here's the code of the specific activity to try: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/ComplexHeaderDrawerActivity.java#L159

**Comment by gparigibini** [comment]
Thanks for your reply. As I wrote, I've tried everything, included the two instructions used in that activity. The drawer still opens. 
Have you got any suggestion or consideration about what could cause such a conflict?

**Comment by mikepenz** [comment]
@gparigibini you tried the implementation like it'S done in the ComplexHeaderDrawerActivity? Because if you test the sample app you can switch to the back arrow and then it will close the activity.

**Comment by gparigibini** [comment]
Yes I did. I tried the app and I saw the code, I really don't have any possible explanation. if you don't have any suggestion, I'll keep testing random things in order to find the root of my problem

**Comment by mikepenz** [comment]
I can only check with more source code. if you did everything like in the sample app it should work

**Comment by gparigibini** [comment]
@mikepenz I don't have any special code to show you, unfortunately.
I tried with (as CompactHeader sample):
```    
getSupportActionBar().setDisplayHomeAsUpEnabled(false);
getSupportActionBar().setHomeButtonEnabled(true);
```
and (as ComplexHeader sample):
```    
mDrawer.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);
getSupportActionBar().setDisplayHomeAsUpEnabled(false);
```
and with the 3 instructions combined. In any case, neither onBackPressed nor onOptionsItemSelected are called.
I'm not using anything special, a simple AppCompatActivity and this code to create the drawer:
```
mDrawer = new DrawerBuilder()
			.withActivity(this)
			.withSavedInstance(savedInstanceState)
			.withToolbar(mToolbar)
			.withAccountHeader(mHeader)
			.addDrawerItems(...)
			.withOnDrawerItemClickListener(this)
			.withShowDrawerOnFirstLaunch(true)
			.build();
```

I'd be interested to know if @patelakshay13890 solved this issue, eventually.
Great library anyway, I'll use it in my app even though I can't manage to get this feature working, maybe one day it'll fix itself by magic :)

**Comment by mikepenz** [comment]
@gparigibini you should only create the drawer by default. pass the toolbar to it and you are fine. now as you need the back arrow call the following code:

```
result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false);
getSupportActionBar().setDisplayHomeAsUpEnabled(true);
```
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/ComplexHeaderDrawerActivity.java#L160

If you want back the burger icon do the following:
```
getSupportActionBar().setDisplayHomeAsUpEnabled(false);
result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);
```
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/ComplexHeaderDrawerActivity.java#L165

Now you know how to switch between both states. Now you also need a listener to react if the user clicks on the back arrow. so you add the following:

```
.withOnDrawerNavigationListener(new Drawer.OnDrawerNavigationListener() {
                    @Override
                    public boolean onNavigationClickListener(View clickedView) {
                        //this method is only called if the Arrow icon is shown. The hamburger is automatically managed by the MaterialDrawer
                        //if the back arrow is shown. close the activity
                        ComplexHeaderDrawerActivity.this.finish();
                        //return true if we have consumed the event
                        return true;
                    }
                })
```
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/ComplexHeaderDrawerActivity.java#L78

**Comment by gparigibini** [comment]
I totally missed the presence of that OnDrawerNavigationListener code because I thought that onBackPressed would be called, as in the original API, that was my missing piece, thank you so much!
You should really consider to put a link for PayPal donations (or at least I didn't find anything) to get back something for your dedication.
Keep up the good work!

**Comment by mikepenz** [comment]
@gparigibini no paypal link as i don't do this for money :D I am happy that the MaterialDrawer helps so many devs out there, and i try to keep it the best drawer lib as far as possible. 

Helping devs out there is great, as i use other libs in my projects too. So i just give something back :D. And i also hope that helping others, will probably help me sometime if i need the help ;)

So thank you so much, and i'm glad that we fixed it ;)

**Comment by engividal** [comment]
Thank you Mike I had this problem and managed to solve.

**Comment by pedrox-3w** [comment]
ComplexHeaderActivity not exists

**Comment by mikepenz** [comment]
@pedrox-3w it was renamed: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/AdvancedActivity.java

**Comment by pedrox-3w** [comment]
Thanks @mikepenz
