### ISSUE TITLE
Hard/Soft back button

### ISSUE THREAD

**Issue by amouly** [mikepenz/MaterialDrawer#45]
On the standard Material Drawer, for example, on Hangouts, when you touch the "back button" on the Android UI, it closes the Navigation Drawer. This is not happening with this library.

BTW, awesome work!

**Comment by mikepenz** [comment]
@amouly just overwrite the `onBackPressed` in your activity and call the `closeDrawer` method on the `Drawer.Result` object you get from the `.build()`method. 

```java
@Override
    public void onBackPressed() {
        if (result != null && result.isDrawerOpen()) {
            result.closeDrawer();
        } else {
            super.onBackPressed();
        }
    }
```

**Comment by amouly** [comment]
Ok, cool, it's better doing this way, and not from the library, right?

**Comment by mikepenz** [comment]
@amouly yes it is. i can't control or catch the `onBackPressed` method from within the library. it will also give you the control what to do.
