### ISSUE TITLE
Support for StateListDrawable icons on DrawerItems?

### ISSUE THREAD

**Issue by MichaelEvans** [mikepenz/MaterialDrawer#450]
I have a Drawable that I manipulate programmatically (via a LayerDrawable), and would like to be able to use a StateListDrawable for selected/unselected state, rather than two drawables. Is support of this possible?

**Comment by mikepenz** [comment]
@MichaelEvans can you be a bit more specific? where do you want to use it?

Setting it for a default DrawerItem is not possible, you will have to extend or implement your own CustomDrawerItem and just set the drawable. 

Also why do you need it? Is the normal tinting not enough?

**Comment by MichaelEvans** [comment]
Well now that I look at updates to this library, it might be possible to just cut out some of my logic - I have a LayerDrawable for badging the icon with a number over it. 

I want the bottom layer of the drawable to have selected / unselected state - so right now I'd need to maintain two LayerDrawables, and pass them in via `.withIcon` and `.withSelectedIcon`. I'd like to set the base layer of the LayerDrawable to a StateListDrawable with both states, and then the selected state of the drawer item propagate to the icon?

Is there a sample that shows the badging that this library provides? Maybe it accomplishes what I'm trying to solve with the LayerDrawable; I don't think it did that before (or I missed that)

**Comment by mikepenz** [comment]
@MichaelEvans i am still not quite sure how this should look like. but as far as i tell i'm sure you can just get this working for you with a simple CustomDrawerItem. Look at the source of the PrimaryDrawerItem, remove everything you don't need and then allow to set a StateListDrawable (just make sure it has no sideeffects as i had problems with StateListDrawables in the past)

Perhaps you can also fix it just with the IconicsDrawable? Not sure how your icons look like and if those are custom or icons from the GoogleMaterialDesign icons.

**Comment by mikepenz** [comment]
As discussed over at Slack the best solution is to just `extend` the `PrimaryDrawerItem` and overwrite the layout with a custom layout, showing the badge above the icon.

**Comment by MichaelEvans** [comment]
+1 to extending / creating custom DrawerItem. 

Thanks!
