### ISSUE TITLE
How i can hook toolbar click?

### ISSUE THREAD

**Issue by objaa** [mikepenz/MaterialDrawer#452]
Hello, 
I cant hook click on NavigationOnClickListener.

When i click on menu icon i see how drawer open only, but i need hook this action ;\

Need open drawer or hide searchview ;\

My code:
```
Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
setSupportActionBar(toolbar);
actionbar = getSupportActionBar();
actionbar.setDisplayHomeAsUpEnabled(true);

drawer = new DrawerBuilder()
.withActivity(this)
.withTranslucentStatusBar(true)
.withToolbar(toolbar)
.withSelectedItem(-1)
.build();
```

i try toolbar.setNavigationOnClickListener, but hook only click on menu (not drawer) icons.

what iam doing wrong?;\

**Comment by mikepenz** [comment]
@objaa you can set a `withOnDrawerNavigationListener` via the drawer, this should do the job

**Comment by objaa** [comment]
Yep, should ;\
I add new listener and write Toast.makeText(MainActivity.this, "nav", Toast.LENGTH_SHORT).show();
And when i click on arrow - toast not shown ;\

drawer = new DrawerBuilder()
                .withActivity(this)
                .withTranslucentStatusBar(true)
                .withToolbar(toolbar)
                .addDrawerItems(
// my items
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(AdapterView<?> adapterView, View view, int i, long l, IDrawerItem iDrawerItem) {
// ..
                        return false;
                    }
                })
                .withOnDrawerNavigationListener(new Drawer.OnDrawerNavigationListener() {
                    @Override
                    public boolean onNavigationClickListener(View view) {
                        Toast.makeText(MainActivity.this, "nav", Toast.LENGTH_SHORT).show();
                        return false;
                    }
                })
                .withSelectedItem(-1)
                .build();

I try set breakpoint into Toast and It does not work for me ;\

**Comment by mikepenz** [comment]
@objaa oh sorry i was wrong. this is used for a differnt use case. 

for getting notified on open or close of the drawer use this listener:

```java
                .withOnDrawerListener(new Drawer.OnDrawerListener() {
                    @Override
                    public void onDrawerOpened(View drawerView) {
                        
                    }

                    @Override
                    public void onDrawerClosed(View drawerView) {

                    }

                    @Override
                    public void onDrawerSlide(View drawerView, float slideOffset) {

                    }
                })
```

**Comment by objaa** [comment]
No, sorry, you misunderstood. I need set listener to hook on Menu click

![2015-07-03 20-00-02](https://cloud.githubusercontent.com/assets/7000585/8502838/8e2aa620-21be-11e5-8f51-dfeae4268c36.png)

i try set withOnDrawerNavigationListenerm but when i clicked on menu listener not called ;\


i try set withOnDrawerNavigationListenerm but when i clicked on menu listener not called ;\

**Comment by mikepenz** [comment]
@objaa the OnDrawerNavigationListener is only called if the burger is not enabled and the back button is shown.

the other listener will get called if the user clicks there and the drawer is opened closed.

what's the exact use case for you?

**Comment by objaa** [comment]
use case: 
![2015-07-03 20-13-13](https://cloud.githubusercontent.com/assets/7000585/8502972/447e7824-21c0-11e5-803d-08664972d022.PNG)
![2015-07-03 20-13-17](https://cloud.githubusercontent.com/assets/7000585/8502974/466f7ec6-21c0-11e5-8467-5d109957c3a9.PNG)

I try realise: if search is shown and user click on arrow then hide search
else if search not shown - open drawer

**Comment by mikepenz** [comment]
@objaa that's exactly the bahavior which is showcased in the ComplexHeader Drawer activity of the sample application. Just check it out. 

If you click on the hamburger icon, the drawer is shown. But if you switch to the Arrow via the Menu on the top right. (You can check out the source code what is called there) the listener will get called and the Arrow closes the activity (in this case). If i switch back to the hamburger, then the normal drawer behavior is triggered again.

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/ComplexHeaderDrawerActivity.java

**Comment by samy-baili** [comment]
@mikepenz I have the same issue here, your link is not available

**Comment by mikepenz** [comment]
@samy-baili https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/AdvancedActivity.java

**Comment by samy-baili** [comment]
Perfect Thank you
