### ISSUE TITLE
Hide switching profile option

### ISSUE THREAD

**Issue by marinica94** [mikepenz/MaterialDrawer#454]
Is there a way to hide the switching profile ? my app runs only one profile so I don't need more than one.

**Comment by mikepenz** [comment]
If you only provide a single profile you can disable the onClick and the touch feedback with

```java
.withSelectionListEnabledForSingleProfile(false)
```

**Comment by pintupyadav** [comment]
switching profile  dropdown arrow not working

**Comment by mikepenz** [comment]
@pintupyadav if there is no profile it doesn't switch, if the above is applied there is no switch when only one profile is there.

**Comment by pintupyadav** [comment]
switching profile dropdown arrow clicking  code 
listview

**Comment by pintupyadav** [comment]
how set backgroundColorRes minidrawer

**Comment by Avamander** [comment]
I'd love if there was a document or similar that described all these functions. If there is please let me know.

**Comment by TonyVintachi** [comment]
hello how can i enlarge my profile section
