### ISSUE TITLE
Programmatically deselect drawer item

### ISSUE THREAD

**Issue by marinica94** [mikepenz/MaterialDrawer#455]
I am really sorry for asking again but I couldn't find in the wiki info about this, how can I deselect the drawer item I have selected programmatically ?

Thank you!

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#how-can-i-create-a-drawer-without-a-default-selection

You can deselect it at a later time with a similar method on the drawer object. just read trough the provided methods :D you will be able to figure it out
