### ISSUE TITLE
Additional Data in Account Header and Custom Dropdown instead of AccountSwitcher

### ISSUE THREAD

**Issue by anobilisgorse** [mikepenz/MaterialDrawer#457]
Hello, I want to customize the data seen in the Account Header, where instead of Name and Email only, I would add two data fields. I tried scanning through your source codes and find it rather complex for me to track all implementations regarding the "name" and "email". I would also like (if possible) to shift the user-icon orientation/alignment to right instead of left.

Also, I would like to change the implementation of the AccountSwitcher, instead of seeing other accounts upon clicking the "arrow-down" or dropdown, I would like to instead project other data there (i.e. the user's personal information). It would be great if you would just pinpoint which class and methods should I just override for me to instead use my own implementation.

Please refer to this image regarding my concept. I hope you could help me for I am an amateur in android app development.
![main menu](https://cloud.githubusercontent.com/assets/8383878/8510760/fc45106e-232b-11e5-885c-5cbe108ce409.jpg)

**Comment by mikepenz** [comment]
@anobilisgorse if you really need a custom AccountHeader which does not follow the Android Design Guidelines and which is against those. (i also see the list itself is against the guidelines) i give you the advice to implement the header on your own and you just pass the view to the Drawer. You will then also have to implement the logic for switching the list items and everything else. it is possible, but it requires a lot work.

An easier but more "hacky" approach would be that you overwrite the default layout which is used in the AccountHeader by copying it over into your project. modify it that the header is on the right and that there are additional fields. (make sure the original structure stays similar and that the current id's stay) then you just use the accountHeader as default. now you will say oh no the additional views are not updated on profile change. now there comes the hack. you can retrieve the root view of the AccountHeader through the provided methods. You use those to get a reference to the additional views and then you can update them in the listener method when a profile gets changed.
