### ISSUE TITLE
Which icons should be used

### ISSUE THREAD

**Issue by amouly** [mikepenz/MaterialDrawer#46]
The Material guidelines said that we should use "24dp" icons for the Drawer. But on the layout the ImageView of the icon has a "48dp" size.

Any recommendation?

**Comment by mikepenz** [comment]
@amouly you just checked the layout ;). If you take a close look at the paddings you'll see that the icon itself is 24dp. 

Take a look at the sample.

**Comment by amouly** [comment]
Thanks, I understand what you said. But in the Sample, you are using FontAwesome (I asume that this has all the icons as a vector, I don't know), and I'm using the assets exported by the Material Icons repo:

 http://google.github.io/material-design-icons/

They provide all the icons on the specific size. I'm using "24dp" size, and looks smaller than the Sample.

Another thing that I'm seeing now: you are setting the "fontFamilty" to "sans-serif-medium", but the guidelines said to use "Roboto Medium".

Maybe i'm wrong on something, i'm just asking. Thanks for your help, this library is the best out there!

**Comment by mikepenz** [comment]
@amouly i see :D yeah that's true ;) i use the FontAwesome font.

But the icons are 24dp so you can also use the drawables if you like.

Oh i would suggest you also use the GoogleMaterial Font which also provides the icons as vector. See the sample for it's usage. 

Roboto Medium is "sans-serif-medium" 

android:fontFamily="sans-serif"           // roboto regular
android:fontFamily="sans-serif-light"     // roboto light
android:fontFamily="sans-serif-condensed" // roboto condensed
android:fontFamily="sans-serif-thin"      // roboto thin (android 4.2)
android:fontFamily="sans-serif-medium"    // roboto medium (android 5.0)


I hope this answers your questions ;)

**Comment by amouly** [comment]
Wou, thank you very much for you explanation!

**Comment by mikepenz** [comment]
@amouly no problem
