### ISSUE TITLE
Load Header Background Image from URL

### ISSUE THREAD

**Issue by xsorifc28** [mikepenz/MaterialDrawer#460]
Is it currently possible to load the header background image via url?

For example..

```
final AccountHeader headerResult = new AccountHeaderBuilder()
				.withActivity(this)
				.withHeaderBackground("http://...")
				...
```

**Comment by raghunandankavi2010** [comment]
It takes a drawable. You can download the image and add them yourself.

**Comment by mikepenz** [comment]
@xsorifc28 you can get the reference to the view of the header after adding it to the drawer and set the image via url with any image loader you want

**Comment by xsorifc28** [comment]
Just wasn't sure if if the background supported URL loading the same way as the profile icons.

Thank you for the insight.

**Comment by raghunandankavi2010** [comment]
@mikepenz Something like ImageView view = headerResult.getHeaderBackgroundView() and  then using a Picasso or any other image loader you can load the url!.

**Comment by mikepenz** [comment]
@raghunandankavi2010 +1 :)
