### ISSUE TITLE
Add a shadow for pre-Lollipop APIs

### ISSUE THREAD

**Issue by Vilian** [mikepenz/MaterialDrawer#461]
Just noticed that we have a drawer's shadow for API 21 and above, but don't have it for old APIs.

**Comment by mikepenz** [comment]
it's in v3.1.1

**Comment by Ki41foo** [comment]
Hello. I got a shadow problem on pre-Lollipop when using gravity right. It seems the drawer still use the left shadow which has reversed gradient for right drawer. How can I fix it? Thank you.

**Comment by mikepenz** [comment]
@Ki41foo it is fixed in v4.0.0 ;)
