### ISSUE TITLE
withCustomView for sticky and non-sticky items?

### ISSUE THREAD

**Issue by tom91136** [mikepenz/MaterialDrawer#464]
Currently we have`withListView(ListView)` and this only works with `ListView`. I was thinking of swapping the whole ListView out for something else (a RecyclerView or some other custom view perhaps) so that I can have other features such as animated item manipulation and such. 

Maybe something this:

    withCustomView(Type, View)

where Type is:

    enum Type{
        MAIN, STICKY, ALL
    }

That way we can cover all custom view use cases without making the builder more complicated on the client side :)

**Comment by mikepenz** [comment]
@tom91136 you can provide your custom view for the stickyFooter or the stickyHeader. You can also provide a custom view for the header itself. You can also provide custom views for the drawer. 

Which use case is still required?

**Comment by tom91136** [comment]
Sorry my bad, `withHeader` sounds awfully a lot like this [method](http://developer.android.com/reference/android/widget/ListView.html#addHeaderView(android.view.View, java.lang.Object, boolean)) in `ListView`. I got confused because the docs are available in AndroidStudio.

You might want to consider bundling javadocs with the artifact.

**Comment by mikepenz** [comment]
@tom91136 there are the javadocs uploaded to maven central. what do you mean with bundling them?

about the `withHeader`. it adds the view as headerView inside the `ListView` but i also have the option of a `StickyHeader`. At the moment i stayed with a `ListView` because of the included selected state handling, and the automatically provideded `Header` but i also know how to build custom views for a `RecyclerView` which interact like headers. In fact i'm quite comfortable with both. But i did not see a real advantage of the `RecyclerView` for the `Drawer`.

Last years Google IO app went even with an `ScrollView`

**Comment by tom91136** [comment]
So with my use case, the `RecyclerView` would actually go into the header of the `ListView` in the implementation, correct?

**Comment by mikepenz** [comment]
@tom91136 if you let me know what you want to do. I mean why do you need a `RecyclerView`?

**Comment by tom91136** [comment]
Well, the built-in ListView works but I need some other features with the list such as drag-n-drop/animated item manipulation. All those features can be accomplished with a RecyclerView easily so I'm planning on using a RecyclerView. 

Now, I could have just used `withCustomView` but then I loose the StickyDrawerItems on the bottom...

**Comment by mikepenz** [comment]
ok in this case this is not yet possible. I think you got one of the only cases where it is a bad idea to use this lib. (for now. :D) 

I mean it will be easier that you handle the content on your own. 
you can even use the provided views, and the drawer itself. but you will have to go with your own logic for the content. so you can go with a customView. let me check if it is possible to get rid of the whole ListView for your special case

**Comment by tom91136** [comment]
Thanks, I used to implement my own drawer by using google's drawer template but their template is over engineered with fragments and all sorts of stuff that I don't like. One of the tricky part of the nav drawer is the stickydraweritems and interactions with the ToolBar/StatusBar. I choose this lib so I can save some time :)

**Comment by mikepenz** [comment]
@tom91136 yeah but you have a very complex use case. so you will have a bad time with all available drawers :D haha

**Comment by mikepenz** [comment]
@tom91136 at the moment the only thing you can do is to have a completely customView within the Drawer, but this will also require you to manage everything on your own. as a RecyclerView works completely different in terms of header, footer, items, keeping track of selection, ..

I'm afraid you can only use the stuff which happens around like managing the statusbar, toggle, etc for you.

**Comment by tom91136** [comment]
Oh well, I guess that will work. Thanks anyway.

**Comment by mikepenz** [comment]
Sorry. If you can't go with the MaterialDrawer. feel free to ask for Drawer specific stuff and how things should be like described in the Material Design Guidelines
