### ISSUE TITLE
Setting the ProfileIcon after loading

### ISSUE THREAD

**Issue by stratbasher** [mikepenz/MaterialDrawer#467]
Hello,

I am needing to use an ASyncTask to load my profile image + cache it. The problem is that I can't seem to get the ImageView of the profile icon.

Heres my code

    Drawer drawer = new DrawerBuilder()/*insert options here*/.build();
    LinearLayout header = (LinearLayout)drawer.getHeader();
    ImageView profileIconImageView = (ImageView)header.findViewById(R.id.profileIcon);
    profileIconImageView.setImageBitmap(picture); //Heres where the error starts. NullPointerExceptoin trying to invoke setImageBitmap on null object reference

It seems that header.findViewById() cannot find R.id.profileIcon, so I can't set it. Is there any way to do this?

**Comment by mikepenz** [comment]
You can provide your own logic to download the ProfileImages from the web. As an example via picasso. You can check this out in the sample. You can then simply provide the url for the profile.

You have to provide the ImageLoader logic here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java#L22

And then just use the url of the image when you create the profile

**Comment by stratbasher** [comment]
This is not a solution for me, as I am not getting a raw image. I am receiving the image as Base64 from a json response.

**Comment by mikepenz** [comment]
@stratbasher but as you see it gives you an imageView and the url and you can do your own logic...

**Comment by stratbasher** [comment]
Is the IDrawerImageLoader asynchronous? I tried putting my logic into the "Set" and "Cancel" functions, but I had trouble passing the imageview in. 

Alright, so I've swapped it out to using the .init() function again. I've created a custom IDrawerImageLoader class. I put a breakpoint on the set() function and it never fires.

**Comment by mikepenz** [comment]
no it isn't you have to do it. 

you have to set the url for the profiles

**Comment by stratbasher** [comment]
Do you mean setting the URL instead of a resource for the withIcon function? I just tried that and the set() function still didn't fire.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/SimpleHeaderDrawerActivity.java#L57

**Comment by stratbasher** [comment]
I'm currently using...

    new ProfileDrawerItem().withName(firstName + " " + lastName).withIcon("https://developers.google.com/+/images/branding/g+128.png")

as a test. None of my breakpoints except for the constructor are firing. I'm implementing DrawerImageLoader.IDrawerImageLoader

    AccountHeader headerResult  = new AccountHeaderBuilder()
				.withActivity(this)
				.withHeaderBackground(R.drawable.header2)
				.addProfiles(
						new ProfileDrawerItem().withName(firstName + " " + lastName).withIcon("https://developers.google.com/+/images/branding/g+128.png")//.withIcon(getResources().getDrawable(R.drawable.placeholder_icon))
				)
				.withAlternativeProfileHeaderSwitching(false)
				.withSelectionListEnabled(false)
				.build();

		DrawerImageLoader.init(new CustomIDrawerImageLoader(this.employee, MainActivity.this));

		drawer = new DrawerBuilder()
				.withActivity(this)
				.withToolbar(toolbar)
				.withAccountHeader(headerResult)
				.addDrawerItems(
						new PrimaryDrawerItem().withName(R.string.drawer_item_home),
						new DividerDrawerItem(),
						new PrimaryDrawerItem().withName(R.string.drawer_item_redacted),
						new PrimaryDrawerItem().withName(R.string.drawer_item_redacted),
						new DividerDrawerItem(),
						new SecondaryDrawerItem().withName(R.string.drawer_item_settings)
				)
				.withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
					@Override
					public boolean onItemClick(AdapterView<?> adapterView, View view, int i, long l, IDrawerItem iDrawerItem) {
						// Convert the drawer item to a nameable, then compare the resource ID returned against the drawer item names
						// If the drawer item name matches, start the associated fragment
						switch (((Nameable) iDrawerItem).getNameRes()) {
							case R.string.drawer_item_redacted: {
								Fragment f = new RedactedFragment();
								getFragmentManager().beginTransaction().replace(R.id.activity_main_frame, f).addToBackStack(null).commit();
								break;
							}
							case R.string.drawer_item_redacted: {
								Fragment f = new RedactedFragment();
								getFragmentManager().beginTransaction().replace(R.id.activity_main_frame, f).addToBackStack(null).commit();
								break;
							}
						}
						return false;
					}
				})
		.build();


And CustomIDrawerImageLoader....

    public class CustomIDrawerImageLoader implements DrawerImageLoader.IDrawerImageLoader {

	Employee employee;
	PhotoCacher pc;

	public CustomIDrawerImageLoader(Employee employee, Context context) {
		this.employee = employee;
		pc = new PhotoCacher(employee, context);
		Log.w("debugging", "new CustomIDrawerImageLoader instantiated");
	}

	@Override
	public void set(ImageView imageView, Uri uri, Drawable drawable) {
		Log.w("debugging", "Set function called");

		Log.w("debugging", uri.toString());

		new AsyncTask<ImageView, Void, Void>() {
			Bitmap picture;
			ImageView iv;

			@Override
			protected Void doInBackground(ImageView... params) {
				Log.w("debugging", "Loading bitmap");
				picture = pc.getPicture();
				this.iv = params[0];
				return null;
			}

			@Override
			protected void onPreExecute() {
				super.onPreExecute();
			}

			@Override
			protected void onPostExecute(Void aVoid) {
				iv.setImageBitmap(picture);
				super.onPostExecute(aVoid);
			}

			@Override
			protected void onProgressUpdate(Void... values) {
				super.onProgressUpdate(values);
			}

			@Override
			protected void onCancelled(Void aVoid) {
				super.onCancelled(aVoid);
			}

			@Override
			protected void onCancelled() {
				super.onCancelled();
			}
		}.execute();
	}

	public void customSet(Bitmap bitmap) {

	}

	@Override
	public void cancel(ImageView imageView) {
		pc.cancel();
	}

	@Override
	public Drawable placeholder(Context context) {
		//return new BitmapDrawable(context.getResources(), pc.getPlaceholder());
		return null;
	}

**Comment by mikepenz** [comment]
Probably you should do this:

`DrawerImageLoader.init(new CustomIDrawerImageLoader(this.employee, MainActivity.this));`

before creating the header?

**Comment by stratbasher** [comment]
Ok that changed some things. The problem now is that it's calling the cancel() function immediately.

**Comment by mikepenz** [comment]
yeah the cancel function will get called often as the views are switched and so on. it will require a good logic to handle this. so i use picasso for loading the image. 

if all this is not working i would suggest that you create the profile with a placeholder image. and you download the bitmap on your own. and as soon as you get it, you update the drawerItem with the image

**Comment by stratbasher** [comment]
Your suggestion is exactly what I was trying to do originally. I was using withIcon(R.drawable.placeholder), but I couldn't figure out how to update that icon later. I had it to where I could get my bitmap correctly, but I didn't know how/where to use findViewById to actually get the placeholderIcon because when I used drawer.getHeader().findViewById(R.id.placeholderIcon), it returned null

**Comment by mikepenz** [comment]
because you should not do this. 

You should keep an reference to your ProfileDrawerItem and just udpate this one with the image as soon as you get it. and then you can update the header with the udpated profileDrawerItem as soon as you got it

**Comment by stratbasher** [comment]
Ah, so instead of doing

    new ProfileDrawerItem().withName(firstName + " " + lastName).withIcon("https://developers.google.com/+/images/branding/g+128.png")//.withIcon(getResources().getDrawable(R.drawable.placeholder_icon))

I should do

    pd = new ProfileDrawerItem().withName(firstName + " " + lastName).withIcon("https://developers.google.com/+/images/branding/g+128.png")//.withIcon(getResources().getDrawable(R.drawable.placeholder_icon))

and then later....

    pd.withIcon(myBitmap)

Last question then: How would I update that header with the updated profileDrawerItem?

**Comment by stratbasher** [comment]
Also, I just managed to get your first recommendation to work. I had to add lots of !isDone() checks, but everything is working perfectly. I may change it to your second recommendation later, however.

**Comment by mikepenz** [comment]
@stratbasher it's bad that your image is as base64 else you would be able to use any image loader. 

for the second one you will have to set an identifier for your profile to identify it for the update and then you can do the following: `updateProfileByIdentifier`

**Comment by stratbasher** [comment]
Ok. Thank you for your help. I didn’t pick the API that I’m hitting, so I’m kinda stuck with it :/





From: Mike Penz
Sent: ‎Friday‎, ‎July‎ ‎10‎, ‎2015 ‎5‎:‎45‎ ‎PM
To: mikepenz/MaterialDrawer
Cc: Adam Besmer





@stratbasher it's bad that your image is as base64 else you would be able to use any image loader. 

for the second one you will have to set an identifier for your profile to identify it for the update and then you can do the following: updateProfileByIdentifier
