### ISSUE TITLE
NullPointerException when click on AccountHeader

### ISSUE THREAD

**Issue by saadqbal** [mikepenz/MaterialDrawer#469]
This happens when you use

 switch (((Nameable) drawerItem).getNameRes() ) {} on withOnDrawerItemClickListener() since there is no nameRes set for HeaderBackground

**Comment by mikepenz** [comment]
@saadqbal i think not the nameRes is null but the drawerItem as the Header is no drawerItem. you should always do an null check or at least an instanceOf check for the item you use

**Comment by saadqbal** [comment]
Yup. A simple null check on drawerItem resolves the issue. Thanks for the help.
