### ISSUE TITLE
I dont want drawer to span from top of the screen

### ISSUE THREAD

**Issue by macmos** [mikepenz/MaterialDrawer#470]
Hi mikepenz.
Thanks for the library.

Please I don't want the drawer to span from top of the screen. Like this:
![screenshot1_small](https://cloud.githubusercontent.com/assets/3740968/8634940/48e67e6a-2806-11e5-9118-d760e7668cf7.png).

I want it to start from the beginning of the actionbar (toolbar) like all Google Apps. How can I achieve that? Just as shown in the picture below
![nexus2cee_2015-02-04-15 09 48](https://cloud.githubusercontent.com/assets/3740968/8634959/f14f04fa-2806-11e5-9f39-a46dfd8e4461.png)

Secondly, the scrolling of drawer items isn't so smooth, especially when compared with Google Apps. Can the scrolling be a little smoother?

Great library. I am waiting for your reply

**Comment by mikepenz** [comment]
@macmos i am not sure where you got the screenshot from, but the latest Google Music App also has the drawer from the top of the screen, same for the Google Play store and Google Inbox. 

If you really want to achieve this, just check out the sample app it also shows how you can do this. 


Scrolling is not as smooth? I really can't follow this one as it is very very smooth on my side too. how many items do you have in your drawer? 

the MaterialDrawer uses an ListView including a ViewHolder and i also checked for everything to be smooth. The Google IO app from last year uses a ScrollView.

**Comment by macmos** [comment]
Alright. Thanks  a lot. I guess the scrolling is because of the scrollview. Nice library. Keep the good work

**Comment by mikepenz** [comment]
@macmos i never had any troubles with scroll performance in my apps using the MaterialDrawer. So perhaps you can give some insight how many items you have and what you are doing. If they have any special handling or anything else? What phone are you using?

Thanks
