### ISSUE TITLE
Below Toolbar

### ISSUE THREAD

**Issue by A-N-D-R-E** [mikepenz/MaterialDrawer#474]
![screenshot_2015-07-12-09-36-47](https://cloud.githubusercontent.com/assets/13125781/8637801/6b241efa-287a-11e5-9683-8384c6b2ae9f.png)
drawer above the toolbar

**Comment by mikepenz** [comment]
@A-N-D-R-E you should do this differently if you really want it below the toolbar (you should not do this!) any special need for this?

See the CustomContainer activity from the sample app it shows how to do this.
