### ISSUE TITLE
SwitchDrawerItem color

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/MaterialDrawer#475]
Hi mike, I'm using the SwitchDrawerItem, and the question is: How do I set the colors for the normal state and the checked state for the switch? Maybe ColorStateList? Could you help me please with some code snippet? Thanks in advance

P.S: This library is awesome, I really appreciate it.

**Comment by mikepenz** [comment]
@EpsilonOrionis no api for this. if you need special handling you will have to create your own custom draweritem which allows you to do this. the easiest thing is that you just copy and paste the SwitchDrawerItem to your project and then modify it to work as expected for your needs.

**Comment by EpsilonOrionis** [comment]
I copied SwitchDrawerItem and pasted in my project. I figured out what methods SwitchCompat uses for set its colors, and are setTrackDrawable() and setThumbDrawable(), I thought to pass drawables to these methods in this way: getResources().getDrawable(R.drawable.switch_compat_thumb)) and the same thing for the track, but I can't use getResources method... How could I solve this?

**Comment by mikepenz** [comment]
you can use this method because you have the view. the view has a context. and the context has this method

**Comment by EpsilonOrionis** [comment]
I still don't have access to my drawables...

**Comment by mikepenz** [comment]
@EpsilonOrionis then there must be a different issue. as this is now a class within your project. but view.getContext().getResources() is available. I even have the reference to the context:

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/SwitchDrawerItem.java#L127

**Comment by EpsilonOrionis** [comment]
Ok, when I type getResources().getDrawable(R.) the suggest prompts: com.mikepenz.materialdrawer

**Comment by mikepenz** [comment]
@EpsilonOrionis the class is part of your project it will also have access to R of your project. but if you have problems with your resources then you have to sort them out first.
