### ISSUE TITLE
Some Lag's when drawer open/close

### ISSUE THREAD

**Issue by sanuggko** [mikepenz/MaterialDrawer#476]
I see some in my application, when drawer opening or closing. In my activity I use expandableListView, maybe there's a reason? I will very grateful.

**Comment by mikepenz** [comment]
@sanuggko the drawer has by default an delay of 200ms to prevent lag when switching fragments. you can add more delay or remove it if you want

**Comment by sanuggko** [comment]
Sorry, but where I can change this parameter?

**Comment by mikepenz** [comment]
`withDelayOnDrawerClose`

**Comment by sanuggko** [comment]
Thank's

**Comment by sanuggko** [comment]
Unfortunately, nothing has changed =-(

**Comment by mikepenz** [comment]
@sanuggko then i assume you have some cpu intensive task somewhere which causes the lag

**Comment by sanuggko** [comment]
Understood, thanks
