### ISSUE TITLE
Question: is it possible to have a material drawer into a fragment?

### ISSUE THREAD

**Issue by brunano21** [mikepenz/MaterialDrawer#479]
I do not even know if the question makes sense.
I have an app that already makes us of a material drawer into an activity, but I'm thinking if it's possible to add a secondary drawer to a fragment which belong to the above activity. In this case I would use a drawer on the right.
Thanks

**Comment by mikepenz** [comment]
@brunano21 theoretically you can host as many DrawerLayouts as you want. It will just make your app slower, make the view hirachy more complex, add some complexity for you to manage, will make the navigation probably in-transparent and so on. 

It will also require some custom handling for you with the MaterialDrawer. 

So yes it's possible, but you should be really careful if you implement this

**Comment by brunano21** [comment]
I would say that I would like to use it into a fragment to implement something like a 'friends list'. Do you suggest something else, based on your experience?

**Comment by mikepenz** [comment]
It's about the view hirachy and the complexity as you will have to nested DrawerLayouts within each other. So yeah, do you have a better solution or place for the friends list?

**Comment by brunano21** [comment]
Not yet :-) I was wondering which are all available options..

**Comment by mikepenz** [comment]
@brunano21 to name it. yes it's an option. but to keep your app simple there are properly better solutions :D but just let me know how you decide on it

**Comment by brunano21** [comment]
Yeah, sure! :-) honestly I do not have yet a clear 'user actions flow' yet, so probably my question won't make sense in future. It depends on how I decide to proceed. However this remains still an option. I'll let you know. Thanks ;-)
