### ISSUE TITLE
Clear selection?

### ISSUE THREAD

**Issue by Anatidae-Project** [mikepenz/MaterialDrawer#480]
Is there a clear selection method?

**Comment by mikepenz** [comment]
Removing the selection can be done with `-1` 

https://github.com/mikepenz/MaterialDrawer#how-can-i-create-a-drawer-without-a-default-selection

**Comment by Anatidae-Project** [comment]
That works, but I was looking to clear a selection after one has been made.

Like maybe: drawer.setSelection(-1, false); ? (that doesn't work)

**Comment by mikepenz** [comment]
`result.setSelection(-1);` 

Just tried this in the SimpleHeaderActivity and the selection is unset. So perhaps you do this in a wrong order?

**Comment by Anatidae-Project** [comment]
So, my drawer is my result. Or specifically, an instance of Drawer.

I call setSelection(-1) and tried setSelection(-1, false) and both don't clear the visual selection aspect within the main listview. Meaning, that the last drawer item used stays highlighted and with the text color change.

I set up main menu listening with withOnDrawerItemClickListener.
I also launch the build with .withSelectedItem(-1)

And this is what the listener looks like when I select an item from the sticky footer:

```
    private void selectBookmarkSection() {
        drawer.setSelection(-1);
        Fragment dest = BookmarkFragment.newInstance();

        FragmentManager fm = getFragmentManager();
        if (fm.getBackStackEntryCount() > 0) {
            Fragment source = fm.findFragmentByTag(fm.getBackStackEntryAt(fm.getBackStackEntryCount() - 1).getName());

            // Use fade transitions if lollipop
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                source.setExitTransition(TransitionInflater.from(this)
                        .inflateTransition(android.R.transition.slide_left));
                source.setEnterTransition(TransitionInflater.from(this)
                        .inflateTransition(android.R.transition.slide_left));
                dest.setEnterTransition(TransitionInflater.from(this)
                        .inflateTransition(android.R.transition.slide_right));
                dest.setExitTransition(TransitionInflater.from(this)
                        .inflateTransition(android.R.transition.slide_right));
            }
            replaceFragment(source, dest, "Bookmarks");
        } else {
            getFragmentManager()
                    .beginTransaction()
                    .replace(R.id.fragment_container, dest, "Bookmarks")
                    .addToBackStack(String.valueOf("Bookmarks"))
                    .commit();
        }
        drawer.closeDrawer();
    }
```

**Comment by mikepenz** [comment]
@Anatidae-Project strange. if you select an existing item will this work?

**Comment by Anatidae-Project** [comment]
If I select an item on the menu, it works completely as expected. 

In my case, clicking on the header brings you to the "home page". 

Then the footer has two icons, one for settings and one that brings up a listview of items the user has bookmarked.
