### ISSUE TITLE
No ripple effect

### ISSUE THREAD

**Issue by khangneovip** [mikepenz/MaterialDrawer#481]
I'm try to use ripple effect on drawer, like this:

![](https://raw.githubusercontent.com/mikepenz/MaterialDrawer/master/DEV/screenshots/screenshot2_small.png)

But it not working for me.

**Comment by seba123neo** [comment]
Ripple effect only works on lollipop.
what is your version of android?

**Comment by mikepenz** [comment]
@khangneovip as @seba123neo mentioned. No ripple effect on pre lollipop as this is not supported by google
