### ISSUE TITLE
How to make Drawer Items Dynamic ?

### ISSUE THREAD

**Issue by MrThiago** [mikepenz/MaterialDrawer#482]
I want to make the Drawer Item Dynamic.

if the user is login, then show LogOut, else show Login ?

Thank you.

        //Create the drawer
        drawer = new DrawerBuilder(this)
                //this layout have to contain child layouts
                .withRootView(R.id.drawer_container)
                .withToolbar(toolbar)
                .withActionBarDrawerToggleAnimated(true)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.drawer_item_home).withIcon(FontAwesome.Icon.faw_home).withIdentifier(R.id.action_home).withCheckable(false),
                        If(isLogin) {
                            new PrimaryDrawerItem().withName(R.string.drawer_item_logout).withIdentifier(2).withCheckable(false);
                        }
                        else {
                            new PrimaryDrawerItem().withName(R.string.drawer_item_login).withIdentifier(2).withCheckable(false);
                        }

**Comment by mikepenz** [comment]
@MrThiago as far as i can see you just want to update the text of the item with the identifier `2`. 

The easiest thing is that you just remember this drawerItem

```java
IDrawerItem actionDrawerItem = new PrimaryDrawerItem().withName(R.string.drawer_item_logout).withIdentifier(2).withCheckable(false);
```

And then you can just add it.

```java
.addDrawerItems(
 new PrimaryDrawerItem().withName(R.string.drawer_item_home).withIcon(FontAwesome.Icon.faw_home).withIdentifier(R.id.action_home).withCheckable(false),
actionDrawerItem
)
```

And afterwards you can update it anytime with:
```java
actionDrawerItem.withName("logout"); //or login depending what you need
drawer.updateItem(actionDrawerItem);
```
