### ISSUE TITLE
Item Identifier for Tests

### ISSUE THREAD

**Issue by danielgomezrico** [mikepenz/MaterialDrawer#483]
I´m using Espresso and JUnit 4 and:

1. setting the id using a resource:

```
<resources>
    <item name="drawer_item_cancel" type="id"/>
</resources>
```

2. And create the items like this:
```
.addItem(new SecondaryDrawerItem()
                            .withName(R.string.drawer_item_cancel)
                            .withCheckable(false)
                            .withIdentifier(R.id.drawer_item_cancel));
```

But that identifier don´t looks like match the view id in the hierarchy because in my tests
```
onView(withId(R.id.drawer_item_cancel)).perform(ViewActions.click());
onData(allOf(withId(R.id.drawer_item_cancel))).check(matches(ViewMatchers.isDisplayed()));
```
results on error: `android.support.test.espresso.AmbiguousViewMatcherException: 'is assignable from class: class android.widget.AdapterView' matches multiple views in the hierarchy.`

Then how can I test with the MaterialDrawer? how can I set the id to each button in the drawer?

**Comment by mikepenz** [comment]
@danielgomezrico the identifier you set is not a `view.setId()`. It is an identifier used for the DrawerItem objects so i can match them later for updates and so on...

**Comment by danielgomezrico** [comment]
The same happens with 

`onData( allOf( is( instanceOf( String.class)), is( rowContents))).perform(click());`

 From [here](http://stackoverflow.com/questions/26722349/android-espresso-click-on-navigation-drawer-item-with-image-and-text]

**Comment by mikepenz** [comment]
@danielgomezrico let me check if it somewhere conflicts with ids i set for those views. if not i will just set the identifier to the view too

**Comment by danielgomezrico** [comment]
:+1:

**Comment by mikepenz** [comment]
@danielgomezrico should be fine. the change was done in the refactoring branch and will be available in a big update which won't be here in the next 1-2 weeks. i hope you can wait for it

**Comment by danielgomezrico** [comment]
:+1: thanks :D

**Comment by danielgomezrico** [comment]
@mikepenz using 4.0.8 how can I open the drawer? I´m checking http://developer.android.com/intl/ko/reference/android/support/test/espresso/contrib/DrawerActions.html but I get:

```
android.support.test.espresso.PerformException: Error performing 'open drawer with gravity 8388611' on view 'with id: com.pickupnow.customer:id/drawer_layout_main'
...
Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
is assignable from class: class android.support.v4.widget.DrawerLayout
Target view: "RelativeLayout{id=2131689596, res-name=drawer_layout_main, visibility=VISIBLE, width=1080, height=1701, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=75.0, child-count=2}"
```

This is my activity layout:
```
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/drawer_layout_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:ignore="MergeRootFrame">

    <include
        android:id="@+id/toolbar"
        layout="@layout/toolbar" />

    <RelativeLayout
        android:id="@+id/container"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:layout_below="@id/toolbar" />

</RelativeLayout>
```

or how can I open it using espresso? I think it was working before `4.x` material drawer version.

**Comment by mikepenz** [comment]
@danielgomezrico have you tried with Gravity.LEFT?

**Comment by danielgomezrico** [comment]
@mikepenz didn´t work :(.

```
android.support.test.espresso.PerformException: Error performing 'open drawer with gravity 3' on view 'with id: com.pickupnow.customer:id/drawer_layout_main'.
...
Target view: "RelativeLayout{id=2131689596, res-name=drawer_layout_main, visibility=VISIBLE, width=1080, height=1701, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=75.0, child-count=2}"
```

**Comment by mikepenz** [comment]
@danielgomezrico strange. you try it on the correct layout and view as i can see.

**Comment by danielgomezrico** [comment]
@mikepenz I´m trying onView(withId(R.id. drawer_layout_main)).perform(open(Gravity.LEFT));

**Comment by rocboronat** [comment]
Just had the same problem. Looked for it in the Hierarchy Viewer, and found it :·)

It's **R.id.material_drawer_layout**.

So, if you are using espresso-contrib library, you should open the drawer with `DrawerActions.openDrawer(R.id.material_drawer_layout);`
