### ISSUE TITLE
Validate if item click should select item or not

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/MaterialDrawer#485]
Is there a way, to validate if a click should select an item? I'm loading data and before the data is loaded, not all my menu items are selectable...

Would be great if I could use following (or something similar):

    .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(AdapterView<?> parent, View view, int position, long id, IDrawerItem drawerItem) {
                        updatePage(drawerItem.getIdentifier());
                        return true; // or false, if click should not select item
                    }
                })

Do I have to remember the selection myself and reset it, if necessary? Or is there something in your library I can use for that?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/SimpleHeaderDrawerActivity.java#L107

See the `.withCheckable()` attribute.

**Comment by MFlisar** [comment]
I'm using that anyways...

So I have to actively enable and disable the checkable attribute myselft... No way to query my apps state and use it...

**Comment by mikepenz** [comment]
@MFlisar you can update a drawerItem at a later time. 

* So you keep the reference to your `DrawerItem`  (You also have to set an identifier to it)
* Then you create the drawer with that one.
* Then you can modify the `DrawerItem` and set it to the `Drawer` again via the update method.

**Comment by MFlisar** [comment]
Thanks. Everything is fine and I do it that way anyways.

Just, if possible, I would have preferred a non active way...

**Comment by anticafe** [comment]
@mikepenz I wonder after modifying `DrawerItem`, why do we need to set `DrawerItem` to `Drawer` again? Doesn't it already attach to `Drawer`, does it?

**Comment by mikepenz** [comment]
@anticafe no the DrawerItem does not know about it's drawer. It can be used everywhere and you can modify it as you need it. you can even create a new object with the same identifier. also the drawer needs to get informed about the fact that it got changed
