### ISSUE TITLE
How can I open a drawer section programatically?

### ISSUE THREAD

**Issue by axierjhtjz** [mikepenz/MaterialDrawer#486]
Is there a way? I mean Drawer.setCurrentIndex(position) or something. I´ve been looking up and couldn't find it, maybe I´m looking in the wrong place.

Thanks in advance!

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#activity-with-toolbar

There are even more options to modify the drawer after creation.
