### ISSUE TITLE
Cant import Gradle

### ISSUE THREAD

**Issue by saeedDarvish** [mikepenz/MaterialDrawer#489]
hi when i import your project from gradle its making an error 

Error:(59, 13) Failed to resolve: com.mikepenz:materialdrawer:3.1.2

what am i doing?
how can i fix it ?

**Comment by mikepenz** [comment]
@saeedDarvish it is on maven central: http://search.maven.org/#artifactdetails|com.mikepenz|materialdrawer|3.1.2|

Is you gradle in offline mode?
