### ISSUE TITLE
Ripple effect on Pre lollipop Devices?

### ISSUE THREAD

**Issue by vishnudbimcs** [mikepenz/MaterialDrawer#49]
Hey, Thanks for the great library. Can you please add ripple effect functionality for pre lollipop devices

**Comment by mikepenz** [comment]
@vishnudbimcs this is not a planned feature. i really want to stay with plain android features and elements. If you really want to have ripple on pre lollipop devices please create a custom draweritem implementation (copy the PrimaryDrawerItemClass and using a different xml for example) should do the trick and will keep this library small and fast
