### ISSUE TITLE
SwitchDrawerItem color

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/MaterialDrawer#490]
Why don't you create APIs to set SwitchDrawerItem state color? It could be very useful.

**Comment by mikepenz** [comment]
@EpsilonOrionis to keep the api simple. Also it's very easy to create Custom DrawerItems or extend existing DrawerItems

**Comment by mikepenz** [comment]
You can also define it by style: http://stackoverflow.com/a/26715076/325479

**Comment by EpsilonOrionis** [comment]
It works, thank you very much. I'm eager to try the new version of MaterialDrawer
