### ISSUE TITLE
Update Gradle to latest version

### ISSUE THREAD

**Issue by anticafe** [mikepenz/MaterialDrawer#492]
At the moment, in `gradle-wrapper.properties`, Gradle is in v2.4. Let update its to latest version 2.5.

**Comment by alorma** [comment]
Isn't 2.5 in beta?

**Comment by anticafe** [comment]
AFAIK, Gradle 2.5 has been released week ago (here is its [release note](https://discuss.gradle.org/t/gradle-2-5-released/10490))

**Comment by mikepenz** [comment]
@anticafe gradle 2.5 is older. but in combination with the beta Android Studio and the new Gradle DSL format it's still beta. I will update it as soon as the new build tools, and dsl structure is final. Just a few more weeks. Also it does not improve anything, 2.4 already had the performance boost :D
