### ISSUE TITLE
 .withDisplayBelowToolbar(true)

### ISSUE THREAD

**Issue by needsst** [mikepenz/MaterialDrawer#494]
Work in 3.0.5, but hasn't work in 3.1.2

**Comment by mikepenz** [comment]
@needsst i will remove this one in a future release. please see this sample activity how this can be done properly: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/EmbeddedDrawerActivity.java

Also note that it is not common and against the GoogleMaterialDesign guidelines to have the drawer below the toolbar
