### ISSUE TITLE
Update bange text of sticky drawer item

### ISSUE THREAD

**Issue by sanuggko** [mikepenz/MaterialDrawer#495]
I`m try to use method updateBange with position -1, because in OnDrawerItemClickListener paramets "i" and "l" has value -1. But nothing happends.

**Comment by mikepenz** [comment]
StickyDrawerItems do not have a position. They need to be handled differnetly

**Comment by sanuggko** [comment]
and how I can to update it?

**Comment by mikepenz** [comment]
@sanuggko this is not yet possible

**Comment by sanuggko** [comment]
okey, thanks for your attention!

**Comment by mikepenz** [comment]
@sanuggko this will be possible in the next version v4.0.0

**Comment by denernun** [comment]
And updateName in StickyDrawerItem will be possible in next version too ?

Tks

**Comment by mikepenz** [comment]
@denernun it will be possible via updating the set item via an identifier in the footer.

**Comment by sanuggko** [comment]
Sorry, but I tried to update footer in v 3.1+ version, and my stiky item updated successfully =-)
