### ISSUE TITLE
withIcon(String uri) always result in a default place holder icon

### ISSUE THREAD

**Issue by hy9be** [mikepenz/MaterialDrawer#496]
My code:
```java
mDrawerHeader.addProfiles(new ProfileDrawerItem()
                .withName(userInfo.getName())
                .withEmail(userInfo.getUserName())
                .withIcon(userInfo.getProfilePicUrl()));
```

This always result in a placeholder profile icon with blue background and black foreground. I checked the url, it is pointed to a valid profile image.

**Comment by hy9be** [comment]
Here is the full logic:

```java
mDrawerHeader.clear();

mDrawerHeader.addProfiles(new ProfileDrawerItem()
                .withName(userInfo.getName())
                .withEmail(userInfo.getUserName())
                .withIcon(userInfo.getProfilePicUrl()));

mDrawerHeader.setActiveProfile(0);
```

**Comment by hy9be** [comment]
I tried to use Picasso to load the image from the url. The returned bitmap is valid, but once I set the icon with ``setIcon`` method. The icon turns to the placeholder one.

**Comment by hy9be** [comment]
I updated to 3.1.2. The issue still presents.

**Comment by mikepenz** [comment]
@hy9be you provide the ImageLoader to use?
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java#L22

**Comment by hy9be** [comment]
That worked. Thank you!
