### ISSUE TITLE
How to enable multiline for Section header

### ISSUE THREAD

**Issue by macaronlover** [mikepenz/MaterialDrawer#497]
Hi. How can I enable multiline for a section header? I need my appropriately long title to appear on 4 lines.

**Comment by mikepenz** [comment]
Here's the source of the original SectionDrawerItem you can copy it / or extend it and create a custom DrawerItem. You can also specify a different layout. this will allow you to get the desired effect

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/SectionDrawerItem.java

**Comment by macaronlover** [comment]
Can it be specified with the declaration 'new SectionDrawerItem().(...)' where the ellipsis is where the multiline feature is specified - e.g. new SectionDrawerItem().withMultiline(true)?

**Comment by mikepenz** [comment]
@macaronlover if you need Custom DrawerItem's you can implement your own CustomDrawerItem. See the sample for an example

**Comment by macaronlover** [comment]
I've created a duplicate class of the link below in my project but I don't know which parts need to change in order to enable multiline. I can't see any properties in that code relating to the maximum number of lines allowed.

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/SectionDrawerItem.java

**Comment by mikepenz** [comment]
This class inflates a layout. I'm sure you can find it out on your own

**Comment by macaronlover** [comment]
OK, I found it will get back to you.
