### ISSUE TITLE
How show original icon colour on Lollipop & pre-Lollipop 

### ISSUE THREAD

**Issue by macaronlover** [mikepenz/MaterialDrawer#498]
How can I show the original colour of my icon for my item on both Lollipop and pre-Lollipop?

**Comment by mikepenz** [comment]
@macaronlover can you show screenshot or describe what you want?

**Comment by macaronlover** [comment]
Sure. I want the menu item icon to appear in the original colour (rather than plain ol' grey) for pre-Lollipop as well as >= Lollipop. 
![xun30](https://cloud.githubusercontent.com/assets/12353505/8751407/c005514a-2ca4-11e5-9108-8915e9ce0b30.png)

**Comment by mikepenz** [comment]
what do you mean with original color?

**Comment by macaronlover** [comment]
the colour of the icon is brown but doesn't show that colour on pre-Lollipop

**Comment by mikepenz** [comment]
why don't you just provide gray drawables instead?

**Comment by macaronlover** [comment]
Because I want them to appear in colour

**Comment by mikepenz** [comment]
so you provide a .png which is in color and it does not show up like this on pre lollipop?

**Comment by macaronlover** [comment]
That's correct

**Comment by mikepenz** [comment]
@macaronlover the library does not change the provided icon drawable if you do not enable withTinting

**Comment by macaronlover** [comment]
How do I enable it on pre-Lollipop?

**Comment by mikepenz** [comment]
why should you enable it. you already mentioned the icon is in color and you do not want to change its color?

**Comment by macaronlover** [comment]
correct but in pre-Lollipop it changes from to grey for some reason

**Comment by mikepenz** [comment]
and you have not enabled `withIconTintingEnabled()`
on the drawerITem?

and just again to make sure you have it as a ".png" not as drawable which you colored on your own

**Comment by macaronlover** [comment]
I'll need to get back to you as I was actually using this library and may switch over to yours if this can be done: https://github.com/chrisbanes/cheesesquare/

**Comment by mikepenz** [comment]
You just sent me a showcase :D

**Comment by macaronlover** [comment]
I do apologise mikepenz, What does that mean?

**Comment by mikepenz** [comment]
You still did not answer these questions: https://github.com/mikepenz/MaterialDrawer/issues/498#issuecomment-122329309

about the previous message. cheesesquare is just a showcase? so not sure what you are trying to say?

**Comment by macaronlover** [comment]
What I was saying is that I haven't used your project yet. I've been using cheese square but was wondering if I can achieve want I want using your project, then I'll use yours instead of cheesesquare.

**Comment by macaronlover** [comment]
![screen shot 2015-07-17 at 17 36 32](https://cloud.githubusercontent.com/assets/12353505/8752158/62f97138-2caa-11e5-86be-0d2142d64318.png)

**Comment by mikepenz** [comment]
@macaronlover you can download this repo and try everything yourself. but yes it is possible.

**Comment by macaronlover** [comment]
withIconTintingEnabled() solved the colour issue so many thanks for that

**Comment by macaronlover** [comment]
withIconTintingEnabled() solved the pre-Lollipop issue so many thanks for that. I'll ditch chessesquare eventually ;-)

**Comment by mikepenz** [comment]
Try everything first and make sure it works as expected. then you can use it

**Comment by macaronlover** [comment]
Sure, I certainly will.

**Comment by macaronlover** [comment]
Had a play around with your project but it is so difficult to pick out the important bits to create a simple project. All I want is to replicate the SimpleCompactHeaderDrawerActivity (without the accounts stuff) but find it too difficult to determine which files need to be copied. Have a look at my screenshot of my project for more information.
![screen shot 2015-07-17 at 23 36 40](https://cloud.githubusercontent.com/assets/12353505/8758529/f22c3426-2cdc-11e5-9c74-e0f663f5971e.png)

**Comment by mikepenz** [comment]
@macaronlover why should you copy over files? just add the gradle dependecy and use the drawer?

**Comment by macaronlover** [comment]
Don't I need to add some imports?
![screen shot 2015-07-19 at 15 54 07](https://cloud.githubusercontent.com/assets/12353505/8766396/6c084788-2e2e-11e5-8352-7074c6cfd95f.png)
