### ISSUE TITLE
Back Arrow Click is Opening Drawer?

### ISSUE THREAD

**Issue by theCodingWizard** [mikepenz/MaterialDrawer#501]
Hello,

I got a little issue. The library works great, but whenever I decide to show the back arrow whenever I click it it always shows the drawer.

**How do I implement a back arrow click?**

I want to be able to show a back arrow and handle a click, then at the home page the arrow should turn into a three-line icon.

Note that I am manually controlling when the back arrow should be shown. I am using fragments with API level 22.

Thanks!
Nathan

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/452#issuecomment-118399293

**Comment by mikepenz** [comment]
The ComplexHeaderActivity in the sample showcases what you are trying.

**Comment by theCodingWizard** [comment]
Ah thank you!
