### ISSUE TITLE
Second drawer withSliderBackgroundColor() not working? [3.1.2]

### ISSUE THREAD

**Issue by vkuzub** [mikepenz/MaterialDrawer#502]
I am trying to change background color for Second (right) slider with `withSliderBackgroundColor()` or `withSliderBackgroundColorRes()`, this methods are working for the first (left) drawer but nothing happen for the second drawer.

**Comment by mikepenz** [comment]
@vkuzub how do you try to use this method?

**Comment by vkuzub** [comment]
Drawer result = new DrawerBuilder()
                .withActivity(this)
                .withDrawerWidthDp(160)
                .withSliderBackgroundColorRes(android.R.color.white)
//some init code here
                .build();

Drawer second = new DrawerBuilder()
                .withActivity(this)
                .withDrawerWidthDp(200)
                .withSliderBackgroundColor(Color.RED)
                .withDrawerGravity(Gravity.END)
                .append(result);

**Comment by mikepenz** [comment]
i will look at it later today

**Comment by mikepenz** [comment]
Will be fixed in v4.0.0
