### ISSUE TITLE
Where can I find the style of your Toast

### ISSUE THREAD

**Issue by jonwu** [mikepenz/MaterialDrawer#503]
I really like your toast, but it doesn't extend to my other activities. Where can I find this style?

**Comment by mikepenz** [comment]
@jonwu which toast? toasts are not part of this project

**Comment by jonwu** [comment]
You are correct. I didn't realize Activity toasts vs Application toasts have different styles :/ My bad. 

Thanks for the quick response, mike! This library is amazing :+1:

**Comment by mikepenz** [comment]
@jonwu thanks ;)
