### ISSUE TITLE
Badge support for mini drawer ?

### ISSUE THREAD

**Issue by korrio** [mikepenz/MaterialDrawer#504]
![screenshot](https://raw.githubusercontent.com/mikepenz/Crossfader/develop/DEV/screenshots/screenshot1_small.png)

I'm thinking about the badges, Mike said that it's a good idea.

**Comment by alorma** [comment]
:+1:

**Comment by mikepenz** [comment]
can be tested in the latest beta of v4.0.0 https://github.com/mikepenz/MaterialDrawer/issues/487
