### ISSUE TITLE
Laggy Drawer

### ISSUE THREAD

**Issue by vanshg** [mikepenz/MaterialDrawer#506]
Whenever I try to use the drawer, it is really laggy. Regardless of opening or closing, it is laggy. I have made sure that there is no work going on in the background. Even when the app is not doing anything, and I try to open the drawer, I still get the issue.

How do I go about fixing this?

**Comment by mikepenz** [comment]
@vanshg which version of the drawer do you use? which phone do you have? which android version? is the sample app also laggy?

**Comment by vanshg** [comment]
Thanks for the prompt reply.

I'm using 3.1.2 on a Samsung GS6 with 5.1.1. The sample application is working as smooth as honey.

**Comment by mikepenz** [comment]
@vanshg so you have an empty application containing the same setup as in the sample application?

**Comment by vanshg** [comment]
It's not empty; it's got most of the application finished. I decided to get rid of the simple navigation drawer that I had and I decided to replace it with this one for easy customization and usage. The weird thing is that the drawer I was using before seemed to work without lag.

**Comment by mikepenz** [comment]
@vanshg and you have implemented the drawer like you see it inside the sample application?

**Comment by vanshg** [comment]
Just ran through and compared the code, the only difference I see is that you used withSavedInstaneState, so I decided to try adding that, but to no avail. Other than that, the implementation is nearly identical

**Comment by vanshg** [comment]
The code I'm using to build the drawer is as follows:

drawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withSavedInstance(savedInstanceState)
                .withAccountHeader(headerResult)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(mDrawerItems.get(0)).withIcon(mDrawerIcons.getDrawable(0)),
                        new PrimaryDrawerItem().withName(mDrawerItems.get(1)).withIcon(mDrawerIcons.getDrawable(1)),
                        new PrimaryDrawerItem().withName(mDrawerItems.get(2)).withIcon(mDrawerIcons.getDrawable(2)),
                        new PrimaryDrawerItem().withName(mDrawerItems.get(3)).withIcon(mDrawerIcons.getDrawable(3)),
                        new PrimaryDrawerItem().withName(mDrawerItems.get(4)).withIcon(mDrawerIcons.getDrawable(4)),
                        new PrimaryDrawerItem().withName(mDrawerItems.get(5)).withIcon(mDrawerIcons.getDrawable(5))
                )
                //.withTranslucentStatusBar(false)
                /*.withAdapter(mDrawerAdapter)*/
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(AdapterView<?> parent, View view, int position, long id, IDrawerItem drawerItem) {
                        switch (position) {
                            case 0:
                                getFragmentManager().beginTransaction().replace(R.id.content_frame,
                                        new  ()).addToBackStack(null).
                                        setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE).commit();
                                break;
                            case 1:
                                getFragmentManager().beginTransaction().replace(R.id.content_frame,
                                        new  ()).addToBackStack(null).
                                        setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE).commit();
                                break;
                            case 2:
                                getFragmentManager().beginTransaction().replace(R.id.content_frame,
                                        new  ()).addToBackStack(null).
                                        setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE).commit();
                                invalidateOptionsMenu();
                                break;
                            case 3:
                                getFragmentManager().beginTransaction().replace(R.id.content_frame,
                                        new  ()).addToBackStack(null).
                                        setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE).commit();
                                break;
                            case 4:
                                //startActivity(new Intent(getApplicationContext(),  .class));
                                break;
                            case 5:
                                //startActivity(new Intent(getApplicationContext(),  .class));
                                getFragmentManager().beginTransaction().replace(R.id.content_frame,
                                        new  ()).addToBackStack(null)
                                        .setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE).commit();
                                break;
                            default:
                                Toast.makeText(getParent(), "Error", Toast.LENGTH_SHORT).show();
                                break;
                        }

                        return false;
                    }
                })
                .build();

**Comment by mikepenz** [comment]
@vanshg the drawables are the correct size?

**Comment by vanshg** [comment]
I believe so. I have multiple resources depending on the density of the screen (aka pictures in the mdpi folder, hdpi, xhdpi, etc). Is there a better way of doing that?

**Comment by mikepenz** [comment]
@vanshg that is correct. but what's the size of them. if you remove them is it still laggy?

**Comment by vanshg** [comment]
I just removed all instances of .withIcon(...), but the drawer is still not working as expected

**Comment by mikepenz** [comment]
@vanshg something must block the drawer or must lower the performance. else the sample would also be laggy on your phone :/

**Comment by vanshg** [comment]
Wait! I just tried disabling the account header, and it's working smoothly now. I think I may have an incorrect sized picture for my profile picture

**Comment by mikepenz** [comment]
@vanshg oh you did not show this part :D

great ;).

**Comment by vanshg** [comment]
Sorry, my bad. Didn't realize that would be the cause of it ¯\_(ツ)_/¯

**Comment by mikepenz** [comment]
no problem :dancer:

**Comment by rajvijay68** [comment]
Hey @mikepenz ,

I too am facing severe lag issues. 

- Tested on Android 6,7. 
- The sample app works smoothly.
- Using version 6.0.8

**Comment by mikepenz** [comment]
Sounds like something in your code may be blocking the UI thread? adding a too large image for the header?

Can you try to adjust the sample app to reproduce the issue?

@rajvijay68
