### ISSUE TITLE
Set icon for account

### ISSUE THREAD

**Issue by Mikhail-dev** [mikepenz/MaterialDrawer#508]
Hello. I sure that it's trivial question, but I can not find answer. 

I want change icon for IProfile. I have one IProfile in global variables and in some time, I change
   `profile.setIcon(getResources().getDrawable(R.drawable.icon));`
but this does not help for me. Then I tried to update profile
   `headerResult.updateProfileByIdentifier(profile);`
but this also doesn't help for me. 

What am I doing wrong? Thanks!

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/ComplexHeaderDrawerActivity.java#L156


Does your profile have an identifier set?

**Comment by Mikhail-dev** [comment]
Deep sorry for my late reply. 

Many thanks! The problem was in identifier of profile. I didn't set identifier.
But I don't understand, what did you want to tell by this link? Am I use incorrect "setIcon" ?

**Comment by mikepenz** [comment]
The link shows how you can set the icon and update the drawer afterwards ;)
