### ISSUE TITLE
How to style item texts?

### ISSUE THREAD

**Issue by 155martinmoreno** [mikepenz/MaterialDrawer#510]
I'm trying to style the text items... any idea how?

**Comment by mikepenz** [comment]
@155martinmoreno can you be a bit more specific? how do you want to style the text? of which items?

**Comment by 155martinmoreno** [comment]
I'm trying to apply a style to the PrimaryDrawerItem name

**Comment by mikepenz** [comment]
Please be a bit more specific. Which style? Color? Size? Typeface?

Martín Moreno <notifications@github.com> schrieb am Mo., 27. Juli 2015
00:11:

**Comment by 155martinmoreno** [comment]
ok, something like this:

<style name="H1" parent="@android:style/TextAppearance.Medium">
        <item name="android:textSize">24sp</item>
        <item name="android:fontFamily">sans-serif-thin</item>
        <item name="android:textStyle">normal</item>
    </style>

**Comment by mikepenz** [comment]
@155martinmoreno the typeface can be set via the api. setting the textSize can be done by overwriting the default dimen value via resource. 

I would suggest if you need a custom drawerItem with custom style (which follows not the Android Design Guidelines) that you create a CustomDrawerItem by implementing the IDrawerItem interface (you can look at the PrimaryDrawerItem and modify it to your needs)

**Comment by douglasjunior** [comment]
To change textSize I created a item on my `dimens.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
     <dimen name="material_drawer_item_primary_text">20sp</dimen>
</resources>
```
Works for me.
