### ISSUE TITLE
Support for submenu

### ISSUE THREAD

**Issue by ipragmatechadmin** [mikepenz/MaterialDrawer#512]
Hi, 

Could you suggest a way that allow me to have two level of menus in the menu. The use case is that there are multiple categories and each category have multiple subcategories. At the time of opening, only one category should be opened along with all the categories.

**Comment by mikepenz** [comment]
@ipragmatechadmin this is not yet available by default. But you can somehow get this behavior if you cat cht eonClick on the `parent` DrawerItem and update the Drawer with the Additional Items (or remove them on the second click)

**Comment by ipragmatechadmin** [comment]
thx for the quick reply and suggestion. I shall try it

**Comment by idragon81** [comment]
One way of possibly doing this is by using switchdrawercontent
SwitchDrawerContent when clicking on primarydraweritem and in the switched drawer add a back button (That's how I am currently doing it). But yeah even i would vouch for a submenu similar to an expandableview

**Comment by ipragmatechadmin** [comment]
In my use case, there are multiple categories with multiple subcategories so I need to hide subcategories when some other category is being clicked.

**Comment by mikepenz** [comment]
@ipragmatechadmin the v4.0.0 will base upon a `RecyclerView` but i still don't see an easy clean solution on implementing an Exandable DrawerItem or adding some real hirachy to it.
