### ISSUE TITLE
Visibility of DrawerItems based on profile selected

### ISSUE THREAD

**Issue by gpulido** [mikepenz/MaterialDrawer#514]
I'm trying to change the visibility of some items of the materialdrawer when the user selects some of the profiles on the account manager.
The IDrawerItem interface doesn't expose such method, so maybe I'm trying to do something weird.
What is the best aproach to achieve such functionallity?

PS: I know that I already have told you, but your work in this library is amazing.

**Comment by mikepenz** [comment]
@gpulido there is nothing like `hidding` you should delete / add those items on demand. so you can switch out all drawerItems if you like and add them back and so on. 

thanks ;)
