### ISSUE TITLE
How do you make this work with an ActionBarDrawerToggle?

### ISSUE THREAD

**Issue by GYberkeley** [mikepenz/MaterialDrawer#515]
How should the Drawer Toggle be instantiated?

Could you give me an example of what that should look like?

**Comment by mikepenz** [comment]
@GYberkeley pass the `Toolbar` to the `DrawerBuilder`

**Comment by GYberkeley** [comment]
You're saying I should pass a Toolbar object into the DrawBuilder using withToolbar and not using withActionBarDrawerToggle?

Is that right?

Switching between Back-Arrow or Hamburger-Icon

"If you use the included ActionBarDrawerToggle you can switch between back-arrow or hamburger-icon with the following code snippet. (Please note that the order of these lines matter)"

Any way to do this with a toolbar?

Code - Show the back arrow:
result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false);
getSupportActionBar().setDisplayHomeAsUpEnabled(true);
Code - Show the hamburger icon:
getSupportActionBar().setDisplayHomeAsUpEnabled(false);
result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/ComplexHeaderDrawerActivity.java shows everything you need
