### ISSUE TITLE
How to customize Header without AccountHeader?

### ISSUE THREAD

**Issue by anticafe** [mikepenz/MaterialDrawer#516]
I would like to customize Header like this:
![image](https://cloud.githubusercontent.com/assets/340836/8922907/d64638bc-3513-11e5-86d6-117b6a162a7b.png)

It contains:
- An non-rounded ImageView which is app icon
- App name
- App short description (might be no description)
- There is no account switcher there

As I see, it's a standard Material Drawer design, while Material Drawer with Account Switcher only account for less than 1% of all Android app (most of them are from Google's app such as Gmail, Keep, Drive...).

So, is the standard Material header are built-in? Or I must create a custom view then set it to Header?

**Comment by mikepenz** [comment]
@anticafe can you show me the page inside the Google Material Design Guidelines where this is stated?

You can have the whole view but the non-rounded imageview with the current AccountHeader. If you want to change the header to have a non rounded image you can just overwrite the header xml (https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml) and remove the mask from the BezelImageView
