### ISSUE TITLE
How to use this library with FragmentActivity ?

### ISSUE THREAD

**Issue by MrThiago** [mikepenz/MaterialDrawer#517]
get error while trying to set up toolbal. " Can not resolve method get setSupportActionBar ?

**Comment by mikepenz** [comment]
@MrThiago do you use the `AppCompatActivity`? 

Beside this, this is not a MaterialDrawer bug :P

**Comment by MrThiago** [comment]
I am using a Fragments:

public class MainActivity extends FragmentActivity {...

if dont work, in that case I use AppCompatActivity.

**Comment by mikepenz** [comment]
@MrThiago a fragment has no supportActionBar so why do you need it?
