### ISSUE TITLE
not change drawer ? bug drawer below toolbar (newbie)

### ISSUE THREAD

**Issue by helmifluida** [mikepenz/MaterialDrawer#519]
![bug1](https://cloud.githubusercontent.com/assets/12003296/8953691/a8234e96-360a-11e5-8510-701775cb49de.png)
![bug2](https://cloud.githubusercontent.com/assets/12003296/8953718/ca6f1e9e-360a-11e5-9915-ada2197abc3f.png)

i want drawer below toolbar

What this problem ? help me mikepenz :)

**Comment by Kostya1375** [comment]
try using this one

.withDisplayBelowToolbar(true)


2015-07-29 12:01 GMT+03:00 Helmi Ismail <notifications@github.com>:

**Comment by mikepenz** [comment]
@Kostya1375 this method will be removed in v4.0.0

The preferred way to implement the drawer below the toolbar is  like shown here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java

@helmifluida you have to pass the activity to the builder as stated in the exception ;).
