### ISSUE TITLE
Focused item

### ISSUE THREAD

**Issue by Kostya1375** [mikepenz/MaterialDrawer#520]
How can i remove focus on item? Any time i open drawer one of items are focused

**Comment by mikepenz** [comment]
@Kostya1375 is there no selectable item at all or what is the desired behavior?

If you want to remove the selection you can set the selection to `-1`
(https://github.com/mikepenz/MaterialDrawer#how-can-i-create-a-drawer-without-a-default-selection)

**Comment by macaronlover** [comment]
There is no touch feedback appearing on my device when I select an item. How do I fix that?


        AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(getActivity())
                .withCompactStyle(true)
                .withHeaderBackground(R.color.wc)
                .withProfileImagesVisible(false)
                .withTextColor(Color.parseColor("#FFFFFF"))
                .withSelectionListEnabled(false)

                .addProfiles(
                        new ProfileDrawerItem().withName("Mike Penz").withEmail("mikepenz@gmail.com")
                )
                .build();

        new DrawerBuilder()
                .withActivity(getActivity())
                .withAccountHeader(headerResult)
                .withTranslucentStatusBar(false)
                .withActionBarDrawerToggle(false)
                .withSelectedItem(-1)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.greeting).withIdentifier(1).withCheckable(false)
                )
        .build();
