### ISSUE TITLE
HTC M8 (5.0.1) SLOW PERFORMANCE

### ISSUE THREAD

**Issue by NorbertSzydlowski** [mikepenz/MaterialDrawer#521]
HI,

I have got bug on one my device with slow performance while close or open drawer.

It is hanging (swipe and programmatically). It is only on this one.

Any idea how to resolve this bug?

**Comment by mikepenz** [comment]
@NorbertSzydlowski depends how you implemented the Drawer. is the Sample app laggy for you?

**Comment by NorbertSzydlowski** [comment]
I checked the sample app. It isn't laggy. I don't know where is problem with my app.

**Comment by mikepenz** [comment]
@NorbertSzydlowski do you have icons on the DrawerItems which are not in the correct size?
Do you have a AccountHeader with a background image which is to huge? Do you have profile images which are not in the correct size?

**Comment by NorbertSzydlowski** [comment]
It is problem with image in custom header.
But I don't understood why.

**Comment by mikepenz** [comment]
@NorbertSzydlowski what's the size of it?
