### ISSUE TITLE
ActionBar Is Hidding

### ISSUE THREAD

**Issue by saeedDarvish** [mikepenz/MaterialDrawer#522]
When i use MaterialDrawerTheme in My App My action bar is hide, i test all of theme like MaterialDrawerTheme.Light.ActionBar,
aterialDrawerTheme.ActionBar,
 and also i have this problem ,... what am i doing ?

![gradle](https://cloud.githubusercontent.com/assets/5301170/8976593/bb6238b0-36a4-11e5-8314-0f025e2b181a.png)
![mob](https://cloud.githubusercontent.com/assets/5301170/8976594/bb640708-36a4-11e5-93b7-ae7f79b168bf.png)
![theme](https://cloud.githubusercontent.com/assets/5301170/8976595/bb645c62-36a4-11e5-9d7d-7b89b9a0027c.png)

is There any thing that i have to do?

**Comment by mikepenz** [comment]
First you should not use an `ActionBar` ;) go with a `Toolbar` :D 

Then i recommend that you use the latest beta release of the v4.0.0
--> https://github.com/mikepenz/MaterialDrawer/issues/487#issuecomment-124599889

So if you updated to the rc1 of the v4.0.0 beta. you should also use a ActionBar specific theme for an ActionBar activity:

Look at the SampleActivity + Manifest for this:
Manifest
https://github.com/mikepenz/MaterialDrawer/blob/feature/refactoring/app/src/main/AndroidManifest.xml#L26
Activtiy
https://github.com/mikepenz/MaterialDrawer/blob/feature/refactoring/app/src/main/java/com/mikepenz/materialdrawer/app/ActionBarDrawerActivity.java#L31

**Comment by saeedDarvish** [comment]
OK .. Thanks I found it

.
