### ISSUE TITLE
Prevent selection of drawer items completely

### ISSUE THREAD

**Issue by macaronlover** [mikepenz/MaterialDrawer#524]
Is it possible to prevent the drawer items appearing as selected/highlighted?

**Comment by mikepenz** [comment]
See the sample app.

Take a specific look here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/SimpleHeaderDrawerActivity.java#L107

`withCheckable(false)`

**Comment by macaronlover** [comment]
I've used exactly the same code you suggested but for some reason it doesn't work on my app, here's my code + a screenshot:
![screen shot 2015-07-31 at 14 06 47](https://cloud.githubusercontent.com/assets/12353505/9007866/663b9a18-378d-11e5-8c92-9919fd401ef9.png)

        AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(getActivity())
                .withCompactStyle(true)
                .withHeaderBackground(Color.parseColor("#66CCCC"))
                .withProfileImagesVisible(false)
                .withTextColor(Color.parseColor("#FFFFFF"))
                .withSelectionListEnabled(false)

                .addProfiles(
                        new ProfileDrawerItem().withName("Mike Penz").withEmail("mikepenz@gmail.com")
                )
                .build();

        new DrawerBuilder()
                .withActivity(getActivity())
                .withAccountHeader(headerResult)
                .withTranslucentStatusBar(false)
                .withActionBarDrawerToggle(false)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.greeting).withIdentifier(1).withCheckable(false)
                )
        .build();

**Comment by Kostya1375** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/520

**Comment by macaronlover** [comment]
There is no touch feedback appearing on my device when I select an item. How do I fix that?


        AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(getActivity())
                .withCompactStyle(true)
                .withHeaderBackground(R.color.wc)
                .withProfileImagesVisible(false)
                .withTextColor(Color.parseColor("#FFFFFF"))
                .withSelectionListEnabled(false)

                .addProfiles(
                        new ProfileDrawerItem().withName("Mike Penz").withEmail("mikepenz@gmail.com")
                )
                .build();

        new DrawerBuilder()
                .withActivity(getActivity())
                .withAccountHeader(headerResult)
                .withTranslucentStatusBar(false)
                .withActionBarDrawerToggle(false)
                .withSelectedItem(-1)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.greeting).withIdentifier(1).withCheckable(false)
                )
        .build();
