### ISSUE TITLE
How to use back press feature in a fragment

### ISSUE THREAD

**Issue by macaronlover** [mikepenz/MaterialDrawer#526]
How can I use the back press code within a fragment in order to close the drawer?

    @Override
    public void onBackPressed() {
        //handle the back press :D close the drawer first and if the drawer is closed close the activity
        if (result != null && result.isDrawerOpen()) {
            result.closeDrawer();
        } else {
            super.onBackPressed();
        }
    }

**Comment by RubenGees** [comment]
Use a interface connection between your activity and your fragment. This is how I do it:

In Activity:
```
@Override
    public void onBackPressed() {
        if (drawer.isDrawerOpen()) {
            drawer.closeDrawer();
        } else {
            return onBackPressedListener.onBackPressed();
        }
    }
```

The interface:
```
    public interface OnBackPressedListener {

        /**
         * Callback, which is called if the Back Button is pressed.
         * Fragments that extend MainFragment can/should override this Method.
         *
         * @return true if the App can be closed, false otherwise
         */
        boolean onBackPressed();
    }
```

In Fragment:
```
    /**
     * {@inheritDoc}
     */
    @Override
    public boolean onBackPressed() {
        return true;
    }
```

All my Fragments implement the Listener and each decides on it own, what shuold happen.

**Comment by mikepenz** [comment]
@macaronlover as stated by @RubenGees you have to pass this to the activity and trigger the action there. you will find enough topics on the web how to do this, but @RubenGees answer is already very detailed

**Comment by macaronlover** [comment]
After using the code suggested by @RubenGees in exactly the right classes as necessary, I get this error: 'Method does not override method from its superclass' + I get this warning: 'Method 'onBackPressed()' is never used' Also the 'o' is OnBackPressedListener is supposed to be lowercase.

**Comment by RubenGees** [comment]
Interesting. Maybe there is a typo in my code or something. Try to delete the Method and let Android Studio auto-complete it for you. (Alt+Enter)

**Comment by macaronlover** [comment]
Still no difference. Please check your code and edit it as necessary. Here are my screenshots:
![screen shot 2015-08-03 at 22 46 39](https://cloud.githubusercontent.com/assets/12353505/9048514/afc0f538-3a31-11e5-926f-4eeffa481888.png)
![screen shot 2015-08-03 at 22 47 02](https://cloud.githubusercontent.com/assets/12353505/9048513/afb9a062-3a31-11e5-9c87-4dae89bbb593.png)

**Comment by RubenGees** [comment]
Okay, I'll have a look at it tomorrow.

**Comment by macaronlover** [comment]
Cool

**Comment by RubenGees** [comment]
One thing I see is, that the brackets are missing at the call in your Activity. Try onBackPressedListener.onBackPressed();

Do you implement the interface correctly? Try to use a fully qualified declaration in your Fragment: implements YourActivity.onBackPressedListener

On a side note: Classes and interfaces are declared with a upper-case letter. Only if you use them (Declare them as a field) you write them with a lower-case letter.

**Comment by macaronlover** [comment]
Tried it but I get this
![screen shot 2015-08-04 at 00 08 38](https://cloud.githubusercontent.com/assets/12353505/9049709/17e4b63a-3a3d-11e5-9c1b-b1b9abb6843b.png)

**Comment by mikepenz** [comment]
@macaronlover you named your interface `onBackPressedListener` note the lowerCase `o`? You need somewhere the implementation of this interface and keep the reference to the implementation. the implementation is then called from inside the activity with the `onBackPressedListener.onBackPressed()` with the `onBackPressedListener` being the implementation of the current active fragment. (in this case the fragment)

Please use Google search / Stackoverflow to find the information how to implement `Listeners` in Java. This is not related to the MaterialDrawer
