### ISSUE TITLE
Feedback not occurring when item is clicked

### ISSUE THREAD

**Issue by macaronlover** [mikepenz/MaterialDrawer#527]
For some reason no feedback is shown whenever I select an item. Why does this happen & how can this issue be resolved?

        headerResult = new AccountHeaderBuilder()
                .withActivity(getActivity())
                .withCompactStyle(true)
                .withHeaderBackground(R.color.wc)
                .withProfileImagesVisible(false)
                .withTextColor(Color.parseColor("#FFFFFF"))
                .withSelectionListEnabled(false)

                .addProfiles(
                        new ProfileDrawerItem().withName("Mike Penz").withEmail("mikepenz@gmail.com")
                )
                .build();

        result = new DrawerBuilder()
                .withActivity(getActivity())
                .withAccountHeader(headerResult)
                .withTranslucentStatusBar(false)
                .withActionBarDrawerToggle(false)
                .withSelectedItem(-1)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.greeting).withIdentifier(1).withCheckable(false)
                )
        .build();

**Comment by mikepenz** [comment]
@macaronlover which Android Version, which library version, what do you mean with no feedback?

**Comment by macaronlover** [comment]
I tested it on a Lollipop device.

**Comment by mikepenz** [comment]
@macaronlover so what do you expect to happen? and which library version you use?

**Comment by macaronlover** [comment]
I expect a ripple effect at least to happen when I tap and hold an item. I'm using version 3.1.2.

**Comment by mikepenz** [comment]
@macaronlover i can't see any problems why this should work in your case? probably you use the wrong theme?

**Comment by macaronlover** [comment]
My theme is Theme.AppCompat

**Comment by mikepenz** [comment]
@macaronlover when you don't use an MaterialDraewr theme as suggested you will have to provide the color values on your own: https://github.com/mikepenz/MaterialDrawer#style-the-drawer

if you don't do this it will use default values. and i assume those are the wrong colors for your application as you don't see the ripple effect

**Comment by macaronlover** [comment]
So do I basically put this code in styles.xml?:
    <style name="CustomTheme" parent="AppTheme">
        
        <item name="colorPrimary">@color/material_drawer_primary</item>
        <item name="colorPrimaryDark">@color/material_drawer_primary_dark</item>
        <item name="colorAccent">@color/material_drawer_accent</item>

        
        <item name="material_drawer_background">@color/material_drawer_background</item>
        <item name="material_drawer_icons">@color/material_drawer_icons</item>
        <item name="material_drawer_primary_text">@color/material_drawer_primary_text</item>
        <item name="material_drawer_primary_icon">@color/material_drawer_primary_icon</item>
        <item name="material_drawer_secondary_text">@color/material_drawer_secondary_text</item>
        <item name="material_drawer_hint_text">@color/material_drawer_hint_text</item>
        <item name="material_drawer_divider">@color/material_drawer_divider</item>
        <item name="material_drawer_selected">@color/material_drawer_selected</item>
        <item name="material_drawer_selected_text">@color/material_drawer_selected_text</item>
        <item name="material_drawer_header_selection_text">@color/material_drawer_header_selection_text</item>
    </style>


...then add         android:theme="@style/CustomTheme"     to the activity of my choice in the manifest.xml file?

**Comment by mikepenz** [comment]
@macaronlover you only have to add the items which are prefixed with `material_drawer_*`
depending on your theme it will require the correct colors. 

Just a question. Why don't you just use a MaterialDraewr theme? it is based on the appcompat theme and is compatible with all api levels down to 10?

**Comment by macaronlover** [comment]
My app supports API 17+, never heard of that theme tbh

**Comment by mikepenz** [comment]
Everything stated in the README ;) 
https://github.com/mikepenz/MaterialDrawer#androidmanifestxml

here are all themes listed

**Comment by macaronlover** [comment]
OK, THAT has solved the problem so many thanks for that.

**Comment by macaronlover** [comment]
I've exactly specified the theme of your project and it STILL doesn't work on Lollipop

**Comment by mikepenz** [comment]
I am sure you mix up light, and normal style

**Comment by macaronlover** [comment]
I don't think I did. Here's my code (I'm really am lost now):

AndroidManifest.xml

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme"
        android:supportsRtl="true">
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <activity
            android:name=".bakerloo.BakerlooHDNActivity"
            android:label="@string/hdn"
            android:theme="@style/MaterialDrawerTheme" >
        </activity>
    </application>
</manifest>

styles.xml

<resources>

    
    <style name="AppTheme" parent="MaterialDrawerTheme.ActionBar">
        
    </style>

        <style name="BakerlooHDNTheme" parent="MaterialDrawerTheme.ActionBar">
            <item name="android:windowNoTitle">true</item>
            <item name="windowActionBar">false</item>
        </style>

</resources>

**Comment by mikepenz** [comment]
@macaronlover there is already a theme without an ActionBar just use `MaterialdrawerTheme` :D

You also don't overwrite any color values in your xml's?

**Comment by macaronlover** [comment]
When you said "You also don't overwrite any color values in your xml's?", does this include colours within the nav drawer?

**Comment by macaronlover** [comment]
OK, found the problem. I overwrote some colour vales hence changed those back to default and the effect now works. Many thanks :-)
