### ISSUE TITLE
How to hide account header

### ISSUE THREAD

**Issue by macaronlover** [mikepenz/MaterialDrawer#528]
How can I hide the account header? I've created the code below but I don't want the account header to be showing during runtime. The solution is 'headerResult.?' where the question mark is replaced by something but I don't know what.

        headerResult = new AccountHeaderBuilder()
                .withActivity(getActivity())
                .withHeaderBackground(R.color.red)

                .addProfiles(
                        new ProfileDrawerItem().withName("Mike Penz").withEmail("mikepenz@gmail.com")
                )
                .build();

        result = new DrawerBuilder()
                .withActivity(getActivity())
                .withAccountHeader(headerResult)
                .withTranslucentStatusBar(false)
                .withActionBarDrawerToggle(false)
                .withSelectedItem(-1)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.greeting).withIdentifier(1).withCheckable(false)
                )
                .build();

**Comment by mikepenz** [comment]
If you don'T have an header jsut don'T create it and pass it to the drawer?

**Comment by macaronlover** [comment]
I want my header to appear on phones but not on tablets

**Comment by mikepenz** [comment]
Then just check in an `if`? 

If you are on a phone do not add it. if you are on a tablet add it?

**Comment by macaronlover** [comment]
if (mTwoPane){
?
} else {
?
}

**Comment by mikepenz** [comment]
if you want the header add it to the drawer if not don't add it. i do not get your question? if you have trouble with java things, please try to search via Google

**Comment by macaronlover** [comment]
Both my tablet and phone are using a fragment rather than activity for phones & fragment for tablets

**Comment by mikepenz** [comment]
but the drawer should be created in the activity (as shown in the samples) and in the activity you can decide what to do

**Comment by macaronlover** [comment]
My tablet uses fragments from a master detail flow hence it is easier to have the code in a fragment.

**Comment by mikepenz** [comment]
you have many possibilities, but i do not see this as MaterialDrawer issue as the functionality works and everything is fine.

**Comment by macaronlover** [comment]
Activities are not being used on tablets for my detail flow so where am I supposed to put that code? I placed it in the fragment code.

Can't I use headerResult.hide or something like that?

**Comment by mikepenz** [comment]
i repeat it again. if you don't need a header don't add it. if you need it add it. you can theoretically remove the header view from the drawer, but this is normally not done. 

there is a method called `removeHeader()`

**Comment by macaronlover** [comment]
I know but based on the code I have, it is more efficient for me to open fragments + couldn't find 'removeHeader()' for some reason. Either way I'll take what you mentioned on board.
![screen shot 2015-08-01 at 19 18 13](https://cloud.githubusercontent.com/assets/12353505/9023008/25e91e7c-3882-11e5-97ab-0798dfc2d731.png)

**Comment by mikepenz** [comment]
the `removeHeader` method only exists on the result of the drawer

**Comment by macaronlover** [comment]
Hmmmm OK. Does the method go with the DrawerBuilder properties or somewhere else?

![screen shot 2015-08-01 at 19 58 27](https://cloud.githubusercontent.com/assets/12353505/9023156/c58a07ca-3887-11e5-920b-fa187b625892.png)

**Comment by mikepenz** [comment]
on the result

**Comment by macaronlover** [comment]
Just to clarify, where is that?

**Comment by mikepenz** [comment]
the variable called `result` in your code?

**Comment by macaronlover** [comment]
Cool. I thought so :-) Many thanks

**Comment by macaronlover** [comment]
It doesn't hide the hide/remove the header but I'll look into it.

        if (mTwoPane){
            result.removeHeader();
        } else {

        }

**Comment by macaronlover** [comment]
I've almost got it. When using this method the header is removed but I don't know what to use to keep the header.

        if (mTwoPane){
            result.removeHeader();
        } else {
            result.removeHeader();
        }

**Comment by mikepenz** [comment]
why you remove it in both cases?

**Comment by macaronlover** [comment]
Sorry, wrong code, I've updated it now

**Comment by macaronlover** [comment]
if (mTwoPane){
            result.getHeader();
        } else {
            result.removeHeader();
        }

**Comment by mikepenz** [comment]
@macaronlover why do you try to getHeader from the result when you aren't going to use it?

**Comment by macaronlover** [comment]
It was just a guess. All I'm aiming to do is show the header.

**Comment by mikepenz** [comment]
either you add the header and show it, or you remove it. i don't see what you are trying? if you removed it, it won't be shown. if you don't it will be shown.

**Comment by macaronlover** [comment]
I only want to show the header on two pane devices

**Comment by macaronlover** [comment]
Please have a look at these two classes when you can (the fragment class is for tablets and the activity class is for phones) and see if you can figure out what is wrong and/or what needs changing.

http://pastebin.com/V3U8Z793

http://pastebin.com/SFveHN9k

**Comment by mikepenz** [comment]
I don'T see why you just don't do the drawer in the activity (which is suggested and highly recommended) 
and i don't understand why you have to add the header and then remove it, wouldn't it be beetter if you don't create it at all if you don't need it?

**Comment by macaronlover** [comment]
When I create it in the activity, it doesn't appear on the tablet as it opens a fragment not an activity + no, it wouldn't be better because I only want the header to appear on phones and NOT on tablets.

PHONES: Drawer only
TABLETS: Drawer + Header

Have a look at my activity and fragment codes below and you'll see what I meant:
http://pastebin.com/hteZApWF
http://pastebin.com/9tsPxs6y
