### ISSUE TITLE
How to remove line above section header title

### ISSUE THREAD

**Issue by macaronlover** [mikepenz/MaterialDrawer#529]
How can the line that appears above the SectionDrawerItem text be removed?

![screen shot 2015-08-01 at 19 10 13](https://cloud.githubusercontent.com/assets/12353505/9022982/89c98450-3881-11e5-9873-697a8dddf7ec.png)

**Comment by mikepenz** [comment]
@macaronlover as of the Material Design Guidelines a Section has a divider line.

Perhaps this method helps you: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/SectionDrawerItem.java#L56

**Comment by macaronlover** [comment]
Cool. Problem solved. Many thanks again Mike :-) :+1:
