### ISSUE TITLE
AlertDialog smaller width

### ISSUE THREAD

**Issue by achuinard** [mikepenz/MaterialDrawer#53]
I'm finding that when extending from this theme, my AlertDialog width is a lot smaller. Why is this happening?

**Comment by mikepenz** [comment]
@achuinard i overwrite the alertdialog theme to provide the accent colors here too. 

```xml
<style name="MaterialDrawerBaseTheme.Light.DarkActionBar" parent="Theme.AppCompat.Light.DarkActionBar">
        ...
        <item name="android:alertDialogTheme">@style/MaterialDrawerBaseTheme.Light.Dialog</item>
    </style>


<!-- General Theme override to change the Dialog design -->
    <style name="MaterialDrawerBaseTheme.Dialog" parent="Theme.AppCompat.Dialog">
        <item name="colorPrimary">@color/material_drawer_primary</item>
        <item name="colorPrimaryDark">@color/material_drawer_primary_dark</item>
        <item name="colorAccent">@color/material_drawer_accent</item>
    </style>
```

To be honest it shouldn't change anything depending the size of the AlertDialog.

**Comment by mikepenz** [comment]
Ok after doing some research. it seems that i probably shouldn't set the `alertDialogTheme` within the style but the `android:dialogTheme`. The change will be in the next version. 

http://stackoverflow.com/questions/27319516/android-datepickerdialog-accent-color-in-v21

**Comment by mikepenz** [comment]
i removed the overwrite of the dialog themes now. it causes to many issues. 

fixed in the next release. you can currently test it here:
https://github.com/mikepenz/MaterialDrawer/issues/36#issuecomment-77248361

**Comment by mikepenz** [comment]
will be in v2.0.0
