### ISSUE TITLE
right to left AccountHeaderBuilder

### ISSUE THREAD

**Issue by tux-world** [mikepenz/MaterialDrawer#530]
why this class dont have setting right to left drawer ?

thanks

**Comment by mikepenz** [comment]
@tux-world right left is automatically done. if the phone is rtl the drawer is content is rtl. gravity should be set GravityCompat.START by you

**Comment by tux-world** [comment]
​my phone is ltr and i want to force that to rtl. i'm using ltr direction
on phone but i like to my application support force rtl. and user dont
change phone language to rtl to view correctly my application​

**Comment by mikepenz** [comment]
Then see following two lines:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/AndroidManifest.xml#L11
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/SimpleHeaderDrawerActivity.java#L49

**Comment by tux-world** [comment]
thants not good for android >14

**Comment by mikepenz** [comment]
@tux-world there was no RTL support on earlier devices
