### ISSUE TITLE
Layout appears under translucent Action bar

### ISSUE THREAD

**Issue by knseir** [mikepenz/MaterialDrawer#531]
Hi, 

For some reason, the layout is UNDER the action bar when I use material drawer.

The layout is set to 
```
android:fitsSystemWindows="true"
```
And This is the code for the drawer: 
```
new DrawerBuilder()
                .withActivity(this)
                .withTranslucentStatusBar(false)
                .withActionBarDrawerToggle(false)
                .addDrawerItems(
                        //pass your items here
                )
                .build();
```
The activities all extend ```ActionBarActivity```

I can't understand why this is happening : 

![screenshot_2015-08-02-04-20-12](https://cloud.githubusercontent.com/assets/10488165/9024118/ddc401d0-388a-11e5-8e0d-b26c73f686dc.png)

The problem the layout is starting at the very top of the screen
I tries changing android:fitsSystemWindows="true" to false
and toggling some values in the drawer builder
I've been trying to solve this all day, with no success.

Any help is appreciated.

**Comment by mikepenz** [comment]
@knseir you have your app with a `Toolbar` or with an `ActionBar` ?

**Comment by knseir** [comment]
I'm using an action bar. The activities all extend actionBarActivity
let me know if I can provide you with more info, 
Thank you

**Comment by mikepenz** [comment]
@knseir which theme are you using? 

See a sample here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/ActionBarDrawerActivity.java
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/AndroidManifest.xml#L28

**Comment by knseir** [comment]
Ok great
Thanks !
So i should implement

android:theme="@style/MaterialDrawerTheme.ActionBar" />

Is it also necessary to extend appComparActivity ?

**Comment by mikepenz** [comment]
@knseir correct ;). 

Yes it is highly recommended, as this theme  extends the AppCompat theme, and this one should be used in an AppCompatActivity

**Comment by knseir** [comment]
Ok thanks again
I'm sorry about the question I know I should  read the documentation but didn't find anything about this
So i assumed there was something wrong with my code

**Comment by mikepenz** [comment]
@knseir i tried to have all possibilities in the sample ;) you can download and install it.

**Comment by knseir** [comment]
Hi Again, 

So I forgot to mention I was going for a translucent action and status bars

Here's what I tried: 

1) when I change the activity theme to ```android:theme="@style/MaterialDrawerTheme.ActionBar``` in the manifest
- I solve the problem that the layout is under the action bar
- BUT I get a coloured status and action bar

2) In ```styles.xml```, I create this new theme : 
```
<style name="translucentStatusBarTheme" parent="MaterialDrawerTheme.ActionBar">
        <item name="android:windowTranslucentStatus">true</item>
        <item name="android:windowTranslucentNavigation">true</item>
        <item name="android:windowContentOverlay">@null</item>
    </style>
```
I inherit from the MaterialDrawer style and implement translucent bars

Then, in the activity ```.java``` file, 
```
        final ActionBar actionBar = getSupportActionBar();
        ColorDrawable colorDrawable = new ColorDrawable();
        colorDrawable.setColor(Color.argb(0, 0, 0, 0));//getResources().getColor(R.color.instabeat_dark_blue));
        actionBar.setBackgroundDrawable(colorDrawable);
        colorDrawable.setColor(Color.argb(0, 0, 0, 0));//rgetResources().getColor(R.color.instabeat_blue));
        actionBar.setStackedBackgroundDrawable(colorDrawable);
```

The result is the same as in the beginning (note this is still true```android:fitsSystemWindows="true"```):
The action and status bars are transparent but the layout is under the bats

3) with this style directly in ```Manifest.xml```
```"@style/MaterialDrawerTheme.ActionBar.TranslucentStatus"```
Same problem: translucency is OK, but layout under bars 

4) This : ```android:theme="@style/MaterialDrawerTheme.Light.TranslucentStatus"``` has no action bar

I'm sorry to take your time I've tries everything I saw in the examples
But I can't solve this !

**Comment by mikepenz** [comment]
@knseir i'm afraid that you will have to switch to a `Toolbar` if you want the drawer below the StatusBar and over the Toolbar. 

It is not possible to have the drawer above the ActionBar. (or i haven't found a solution for this)

in case you will get it to work with an actionbar. to get your layout below the actionBar you can use the UIUtils class to get the ActionBar height and the StatusBar height and add it as margin
