### ISSUE TITLE
Ripple effect not working on Lollipop despite setting appropriate theme

### ISSUE THREAD

**Issue by macaronlover** [mikepenz/MaterialDrawer#533]
For some reason the ripple effect doesn't work on Lollipop when I click a drawer item. It does work on pre-Lollipop but not on Lollipop. any idea why?

<resources>

    
    <style name="AppTheme" parent="Theme.AppCompat">
    </style>

    <style name="BakerlooHDNTheme" parent="MaterialDrawerTheme">
        <item name="android:windowNoTitle">true</item>
        <item name="windowActionBar">false</item>
    </style>

</resources>

AndroidManifest.xml

        <activity
            android:name=".bakerloo.BakerlooHDNActivity"
            android:theme="@style/BakerlooHDNTheme">
        </activity>

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/527
