### ISSUE TITLE
Problem Item Selected

### ISSUE THREAD

**Issue by engividal** [mikepenz/MaterialDrawer#534]
I'm having trouble on the selected item. It does not alter the background in my program. When used your demo it works.
![am3spbzqn6fetsac3emek6ulmunuvjglxcg618bbl7p2](https://cloud.githubusercontent.com/assets/396722/9031745/3b10768e-3985-11e5-9900-842cf1939919.jpg)

since already I appreciate the help!!!

**Comment by mikepenz** [comment]
@engividal you mean the selected state does not work? have you set `withCheckable(false)`? remove this

**Comment by engividal** [comment]
I solved my problem.
Thanks @mikepenz.

**Comment by mikepenz** [comment]
Great :). What was the issue?

**Comment by engividal** [comment]
I remove withCheckable(false).
