### ISSUE TITLE
How to declare custom drawer item

### ISSUE THREAD

**Issue by macaronlover** [mikepenz/MaterialDrawer#535]
I've created a custom section drawer item but don't how do I declare it with the java of Drawer builder. My xml is called 'material_drawer_item_section_multiline.xml' and my java is called 'SectionDrawerItemMultiline.java'

XML: http://pastebin.com/n7iDibhj
Java: http://pastebin.com/PS2zN07y

**Comment by mikepenz** [comment]
Just use it

**Comment by macaronlover** [comment]
All I can think of is 'new SectionDrawerItemMultiline()' which I know is wrong hence I don't know what the right way of doing it is.

**Comment by mikepenz** [comment]
It is correct. If you have modified it correctly it will just work.

**Comment by macaronlover** [comment]
OK, this time it worked. I had to sync & rebuild my project so thanks for your help.
