### ISSUE TITLE
How to customise ToggleDrawerItem ?

### ISSUE THREAD

**Issue by Aabidi09** [mikepenz/MaterialDrawer#536]
Hi, i'm using your library and i want to further customize the ToggleDrawerItem, but i can seem to find how to change the Text for "On/Off". In normal ToggleButtons we have the "setTextOn" and "setTextOff" methods

**Comment by mikepenz** [comment]
@Aabidi09 if you need a different text you will have to create your own CustomDrawerItem with the modified behavior. (Copy the ToggleDrawerItem and modify it ;))

**Comment by Aabidi09** [comment]
Works like a charm, Thank you very much !
