### ISSUE TITLE
Problem setting dynamic number of accounts

### ISSUE THREAD

**Issue by githubbucah** [mikepenz/MaterialDrawer#537]
Number of accounts depends on boolean method in my case. But while building the AccountHeader I can't put if-else statement before build() method of AccountHeader.  

Can you help me to do this? Thanks.

**Comment by mikepenz** [comment]
@githubbucah you can have the variable AccountHeaderBuilder and split the builder thing up in multiple parts. But this is normal java stuff ;). You can find enough information about this on Google or StackOverFlow

**Comment by githubbucah** [comment]
That's where I have problem. Splitting the code won't work. When I split the code, it says that it requires AccountHeaderBuilder unless I don't write build() at the end of it.

**Comment by mikepenz** [comment]
@githubbucah please use Google or Stackoverflow to find out basic programming questions. 

Just as a hint. .build() will return an AccountHeader, before build its an AccountHeaderBuilder. you can split it up.
