### ISSUE TITLE
Is there a way to programmatically click or select a profile in account header?

### ISSUE THREAD

**Issue by christiandennis** [mikepenz/MaterialDrawer#538]
I think .setActiveProfile(identifier, true) should do it but somehow it does not.

**Comment by mikepenz** [comment]
@christiandennis yes if you have set an identifier for the profile this will work

**Comment by christiandennis** [comment]
@mikepenz it does highlight the profile that i pass into the identifier but does not trigger the .withOnAccountHeaderListener() method. How do i trigger it programmatically?

**Comment by christiandennis** [comment]
@mikepenz it actually triggered the listener. sorry, my bad. But i notice something weird.

Lets say I have 3 profiles: profile1, profile2, and profile3.
Then I do .setProfiles(profiles) which consist of profile1, profile2, profile3, profile4.
And do .setActiveProfile(profile1).
The accountHeader stays opened and clickable but the listener is not triggered.
Is this a bug? Or I shouldn't add new profiles this way?

**Comment by mikepenz** [comment]
@christiandennis i will take a look later.

if you pass true with the setActiveProfile it should trigger .setActiveProfile(profile1, true).

It will trigger the mOnAccountHeaderListener.onProfileChanged

**Comment by mikepenz** [comment]
@christiandennis did you try it with the boolean? for me it's working

**Comment by christiandennis** [comment]
@mikepenz I just notice that the listener that's not working is the drawer's onItemClickListener. Inside the accountHeaderListener I do setSelectionByIdentifier for the drawer. I suspect the onItemClickListener doesn't work because the accountHeader stays opened. 

In my program, when some event happened, I need to clear all the current profiles and put the new profiles. I do this by setProfiles but the accountHeader somehow opens itself and wont automatically close. preventing me from clicking the items in the drawer.

**Comment by christiandennis** [comment]
@mikepenz is there any way i could programmatically close the account header drop down?

**Comment by mikepenz** [comment]
@christiandennis yes that's true as long as you are switched to the profiles view you can't change the selection fro the other view. 

why the accountheader opens is strange. should not happen. but yeah there's the option to toggle the header drop down: `toggleSelectionList()`
