### ISSUE TITLE
Display drawer below actionbar/appbar

### ISSUE THREAD

**Issue by Marty** [mikepenz/MaterialDrawer#54]
Hi there,

I really like the features and handling of this library and would like to use it in my app.
However, I need the drawer to be displayed below my appbar.
Is this possible or if not, is it planned to be implemented?

**Comment by mikepenz** [comment]
@Marty it is possible already :D.

If you use an activity with an ActionBar this is done automatically just see the sample for the activity with actionbar. 

if you use a toolbar you can use the `.withTranslucentActionBarCompatibility(true)` property to add the specific margin on top of the drawer.

**Comment by Marty** [comment]
Hi there,
I just updated to the newest version and it seems that the support for this feature has been dropped, am I correct?
That's a shame since I find it visually much more appealing in my app.

Any way for something like .withDisplayBelowActionbarBar(true) to be implemented again? :)

**Comment by mikepenz** [comment]
@Marty https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_show_drawer_under_toolbar.md

**Comment by Marty** [comment]
Hi, yeah I saw that, but I find wrapping my entire layout a bit hacky just to get the drawer a few dp down.
I think then I'll have to get comfortable with the drawer being above the appbar (when I see it now, it's actually not that bad).

Just out of curiosity:
Wouldn't be a simple mechanism with paddingTop possible like with mDisplayBelowStatusBar?
Even UiUtils.getActionBarHeight is already there.

Greetings

**Comment by mikepenz** [comment]
@Marty no it is not hacky. the thing is the following. the drawer will normally inflate itself in the root of your activity. if you want to be below the toolbar, you have to tell the drawer where he has to inflate to be below the toolbar. 

the old implementation just added the padding on top of the drawer to be below the toolbar. which caused the drawer shadow to overlap the toolbar. which was not the best solution.

**Comment by Marty** [comment]
@mikepenz Thanks for the explanation.
