### ISSUE TITLE
Unable to use library in eclipse

### ISSUE THREAD

**Issue by rpalsaxena** [mikepenz/MaterialDrawer#540]
Hello everyone
I am trying to use MaterialDrawer library
Currently,My androidstudio is not working properly
So, I am using eclipse
I downloaded project aar file then converted it to jar file
added it in libs folder
When i added this

new DrawerBuilder().withActivity(this).withTranslucentStatusBar(false)
.withActionBarDrawerToggle(false).addDrawerItems(
// pass your items here
).build();

So, I am using eclipse
It is showing error "DrawerBuilder cannot be resolved to a type"

**Comment by mikepenz** [comment]
@rpalsaxena no support for eclipse
