### ISSUE TITLE
How to implement customDrawerItem.

### ISSUE THREAD

**Issue by lectricas** [mikepenz/MaterialDrawer#541]
Hi, I want to change custom icon size in primaryDrawerItem. I heard that I can do that with customDrawerItem. Can you show me how I can do that? 
Sorry for my silly questions.

**Comment by mikepenz** [comment]
You can look at the `PrimaryDrawerItem`. (For a custom drawerItem you can use it's source as base)

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/PrimaryDrawerItem.java

and at it's layout
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_primary.xml


Just create a layout and the item in your project and use it ;)
