### ISSUE TITLE
update drawer item from the thread

### ISSUE THREAD

**Issue by vanza** [mikepenz/MaterialDrawer#542]
Hi! How can i update drawer item (badge) from the running thread or asynctask? Thanks in advance.

**Comment by mikepenz** [comment]
@vanza you can't update the ui from a thread. just from the ui thread

**Comment by vanza** [comment]
I appeal to the main thread via handler or onPostExecute. I mean is it possible to call drawerResult in this manner.

**Comment by mikepenz** [comment]
as long as you update the ui via the main thread it is ok.
