### ISSUE TITLE
Grab activity nav drawer from fragment

### ISSUE THREAD

**Issue by macaronlover** [mikepenz/MaterialDrawer#543]
It is possible to use an activity's nav drawer from a fragment? I've created a nav drawer in an activity but want the fragment class to use the same nav drawer along with it back press capabilities.

**Comment by deinok** [comment]
yes, it is posible, please post the code or a more specific exemple

**Comment by macaronlover** [comment]
@deinok Code is attached:

**Activity code**

public class BakerlooHDNActivity extends AppCompatActivity {

    private Drawer result = null;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_bakerloo_hdn);


        final String actionBarColor = "#B36305";

        Toolbar mToolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(mToolbar);

        if(getSupportActionBar()!=null) {
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
            getSupportActionBar().setDisplayShowHomeEnabled(false);
            getSupportActionBar().setTitle(Html.fromHtml("<font color='#FFFFFF'>" + getResources().getString(R.string.hdn) + "</font>"));
            getSupportActionBar().setSubtitle(Html.fromHtml("<font color='#FFFFFF'>" + getResources().getString(R.string.zone_3) + "</font>"));

            final Drawable upArrow = ContextCompat.getDrawable(this, R.drawable.abc_ic_ab_back_mtrl_am_alpha);
            upArrow.setColorFilter(getResources().getColor(R.color.white), PorterDuff.Mode.SRC_ATOP);
            getSupportActionBar().setHomeAsUpIndicator(upArrow);
        }

        // start of navigation drawer
        headerResult = new AccountHeaderBuilder()
                .withActivity(getActivity())
                .withCompactStyle(true)
                .withHeaderBackground(R.color.bakerloo)
                .withProfileImagesVisible(false)
                .withTextColor(Color.parseColor("#FFFFFF"))
                .withSelectionListEnabled(false)

                .addProfiles(
                        new ProfileDrawerItem().withName(getString(R.string.hdn)).withEmail(getString(R.string.hello_world))
                )
                .build();

        result = new DrawerBuilder()
                .withActivity(getActivity())
                .withAccountHeader(headerResult)
                .withTranslucentStatusBar(false)
                .withActionBarDrawerToggle(false)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.hello_world).withIdentifier(1).withCheckable(false)
                )
                .build();
        // end of navigation drawer
    }


    @Override
    public void onBackPressed() {
        if (result.isDrawerOpen()) {
            result.closeDrawer();
        } else {
            super.onBackPressed();
        }
        LocalBroadcastManager.getInstance(getApplicationContext()).sendBroadcast(new Intent("BACKPRESSED_TAG"));
    }
}


**Fragment code**

public class FragmentBakerlooHDN extends android.support.v4.app.Fragment {

    public FragmentBakerlooHDN() {
        // Required empty constructor
    }

    BroadcastReceiver onNotice = new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
            // do something when back in activity is pressed
             result.closeDrawer();
        }
    };

    private AccountHeader headerResult = null;
    private Drawer result = null;

    private boolean mTwoPane;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        LocalBroadcastManager.getInstance(getActivity()).registerReceiver(onNotice, new IntentFilter("BACKPRESSED_TAG"));

        super.onCreate(savedInstanceState);
    }

    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.fragment_bakerloo_hdn, container, false);

        super.onCreate(savedInstanceState);
        return v;
    }

    @Override
    public void onActivityCreated(Bundle savedInstanceState) {
        View v = getView();

        super.onActivityCreated(savedInstanceState);
    }
 }

**Comment by deinok** [comment]
I supose that what you want is a fragment inside an activity and while viewing that fragment see the navigation drawer. The only thing that you should do is:
Create a layout(container) inside "activity_bakerloo_hdn" (the layout is going to be the fragment).
Set the OnClickListner of the drawer, and when is clicked, start the FragmentTransition to put "FragmentBakerlooHDN" inside the layout view

**Comment by mikepenz** [comment]
@macaronlover as @deinok already noted yes it is possible to have the drawer in a fragment, it is also possible to have the drawer in the activity (which is recommended) and you manage it via the fragment. 

There are enough resources available, how you can access stuff from the activtiy, on stackoverflow as this is a basic question for beginners.

Just search for it. you will find enough answers, as this is not a MaterialDrawer specific issue. 

thanks
