### ISSUE TITLE
Question: Dynamic switching and enabling SwitchDrawerItem

### ISSUE THREAD

**Issue by markdwags** [mikepenz/MaterialDrawer#546]
I've been attempting to dynamically change the SwitchDrawerItem.  I can step through my code and see this successfully hit the code that you'd think would make the change, but the UI state of the switch doesn't change.

I initialize it in a disabled, unchecked state.

    mFavoriteSwitch = new SwitchDrawerItem()
                .withName("Show As Favorite")
                .withIcon(new IconDrawable(this, Iconify.IconValue.fa_heart_o))
                .withChecked(false)
                .withSwitchEnabled(false)
                .withOnCheckedChangeListener(onCheckedChangeFavoriteListener)
                .withTag("fav_switch");

Later, when I do a check to see if it is a favorite and enable and check it if `isFavorite` is true/false

    for (IDrawerItem drawerItem : drawerItems) {
            if (drawerItem instanceof SwitchDrawerItem) {
                ((SwitchDrawerItem) drawerItem).setChecked(isFavorite);
                ((SwitchDrawerItem) drawerItem).setEnabled(true);
            }
        }

My work around I'm pursuing is to delete the DrawerItem from the array, recreate it using a true flag to check it.  That get's a bit messy and I'd rather just be able to toggle it, if possible.  Hopefully I'm just missing something small.

Awesome library, just discovered it a few days ago.  Thanks for all the time you put into this to make life easier for guys like me.

**Comment by mikepenz** [comment]
@markdwags you have to notify the drawer that the item was updated, so it can handle the changes:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L443

note that this require an `identifier` on the items

**Comment by markdwags** [comment]
Dang, I knew it would be something simple.  Thanks again, much appreciated.
