### ISSUE TITLE
Conflict with colors (com.android.support:design)

### ISSUE THREAD

**Issue by Mikhail-dev** [mikepenz/MaterialDrawer#547]
Hello Mike! 

I have a little problem. I wanted to use TabLayout. I added com.android.support:design library and then I have got conflict with "insetForeground" color (Attribute "insetForeground" has already been defined). How can I resolve carefully this problem? May be add your library as project and remove your color value? Or may be better solution? 

Thanks in advance!

**Comment by mikepenz** [comment]
@Mikhail-dev my library does not overwrite any attributes from other libs. the attributes are prefixed
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/values/attrs.xml#L22
