### ISSUE TITLE
Activity with MaterialDrawer and fragment(s) with toolbars

### ISSUE THREAD

**Issue by gpulido** [mikepenz/MaterialDrawer#549]
Hello,
I'm on a big refactor / adapting to the new material design libraries to use the coordinatorlayout and It seems to me that in order to have different screens with different toolbar behaviors, we can do one of the following:
1) One activity for each toolbar and coordination behavior, create several material drawers instances (one for activity)
2) One activity with one material drawer, each fragment implements the toolbar and the coordinationlayout.

I'm trying to implement the second aproach as it lets you encapsulate the visualization logic and has sense: The common logic (drawer) on the activity (one), and each fragment handles its own toolbar, tabs, whatever.

As I want the material drawer to be common to all the application, I created an activity that holds the materialdrawer instance but it is just a placeholder for fragments that would provide the toolbar coordination, tabs, fab and so on. Son instead of having an activity with just all those things that would be "activated, hidding, showing, etc" with each fragment, the fragment itself provides the implementation.

Also this allows me to use the "Flow library" from square.

The problem is when I try to synchronize each fragment's toolbar with the materialdrawer, and the hamburger / arrow icon.
If I create the materialdrawer on the "oncreate" of the activity, I don't have any toolbar to pass to it (as I don't have yet any fragment to provide the toolbar), so I have to create the drawer without toolbar, and hence without ActionBarDrawerToggle. Once I have fragment intance and I have picked the toolbar, then I can set " getSupportActionBar().setDisplayHomeAsUpEnabled(true);" and i obtain the arrow, but as I don't have an ActionBarDrawerToggle I can't obtain the hamburguer.

What I would like to do is provide a new ActionBarDrawerToggle alongside the toolbar to the drawer, so I don't have to implement all the logic again. Something like "mSrawer.setActionBarDrawerToggle(ActionBarDrawerToggle)" similar to the withActionBarDrawerToggle of the drawer builder but avoiding to creating again the entire drawer.

I don't know if I'm over thinking the whole thing.
Thanks for the help ideas or suggestions
Gabriel

**Comment by mikepenz** [comment]
@gpulido great that you try to go with the second solution as it would be bad to have many fragments containing the drawer. it's just not efficient. 

Just looked at the code, and i think it's possible to add this method ;). Expect it in v4.0.0

**Comment by gpulido** [comment]
That would be awesome!
From my pow, the material design library tries to enforce that approach (to have the toolbar view on the fragments / views) but it also implies not having a God activity that contains all the "common" views that the fragment "would use", of course it is more efficient, but it also means refactor the entire application visualization logic.

In the mean time, I'm "duplicating" the creation of the actionbartoogle with this method:
```java
 ActionBarDrawerToggle mActionBarDrawerToggle;
    public void createActionBarDrawerToggle(Toolbar toolbar) {
        mActionBarDrawerToggle = new ActionBarDrawerToggle(mActivity, mDrawer.getDrawerLayout(), toolbar, R.string.drawer_open, R.string.drawer_close);
        mDrawer.getDrawerLayout().setDrawerListener(mActionBarDrawerToggle);
        mActionBarDrawerToggle.syncState();
    }
```
And, even if the hamburguer icon is show and opens the drawer in order to make it work I can't use
```java
setSupportActionBar(toolbar);
getSupportActionBar().setDisplayHomeAsUpEnabled(true);
getSupportActionBar().setHomeButtonEnabled(false);
```
on the activity

Now I'm trying to change the hamburguer to an arrow by demand (some fragments, should show the arrow instead of the hamburguer)

**Comment by mikepenz** [comment]
@gpulido you can pre test the latest v4.0.0 here:
https://github.com/mikepenz/MaterialDrawer/issues/487

it is a heavy refactor too ;)

**Comment by mikepenz** [comment]
Changing the hamburger to arrow and back is shown in the ComplexHeaderActivity

**Comment by gpulido** [comment]
I'm already using the 4.0.0 but rc1 as the Google icons stopped working, and as I'm involved on the refactor I didn't want to ask before I had more time to be sure that it wasn't my fault.
I hope that tomorrow I can update to rc7 and let you know if anything is missing. Thanks for the tip on the complexheaderActivity, I will take a look asap :)
Again, amazing. Thank you for the support

**Comment by mikepenz** [comment]
@gpulido with v4.0.0 rc2 i switched to the updated Android-Iconics which split up into core and main package. you just have to provide the android-iconics dependency which include the GoogleMaterial font ;)
https://github.com/mikepenz/Android-Iconics/tree/develop#include-in-your-project

**Comment by gpulido** [comment]
@mikepenz About the iconics, I figure out that had to be something like that :) thank you, I'm upgrading to rc7 now.

Regarding the Hamburguer and arrow, the code show on the ComplexHeaderActivity is the one to be used one the drawer and the toolbar are both on the activity, so you can use the setSupportActionBar(toolbar) once and pass the same toolbar instance to the drawer and then your can manipulate the icon (if you remember, we were searching for the solution together).
My problem now is that each fragment provides its own toolbar, so when the activity switch fragments from a container using the fragmentmanager, the "toolbar" used by the activity must change.
If I "setSupportActionBar(toolbar)" each time I change the fragment my problem is that the toolbar that is associated with the drawer and provided on the "withToolbar(toolbar)" has changed, so the drawer doesn't holds the right instance of the toolbar, and it doesn't work.
If I just not pass the toolbar, then I need to create my own ActionBarDrawerToggle for each toolbar (or anytime a fragment is changed) and link it manually to the underlying drawer wrapped to the materialdrawer. Also I have to provide the icon for the arrow. This link includes the  listeners, this is the code that I use:
```Java
   mActionBarDrawerToggle = new ActionBarDrawerToggle(mActivity, mDrawer.getDrawerLayout(), toolbar, R.string.drawer_open, R.string.drawer_close);
        mDrawer.getDrawerLayout().setDrawerListener(mActionBarDrawerToggle);
        mActionBarDrawerToggle.syncState();
        mActionBarDrawerToggle.setHomeAsUpIndicator(new IconicsDrawable(mActivity, GoogleMaterial.Icon.gmd_arrow_back).sizeDp(16).color(Color.WHITE));
        mActionBarDrawerToggle.setToolbarNavigationClickListener(v -> mActivity.onBackPressed());
```
And I have to manually activate / deactivate the hamburguer / arrow with:
```Java
 mActionBarDrawerToggle.setDrawerIndicatorEnabled(true);
```

I don't know if there is a better approach for the problem

**Comment by mdalikazi** [comment]
The way I did this, is I declared the drawer public static, built it without the toolbar, then accessed the drawer from my fragments and simply called `setToolbar()` on the drawer.
 
So my MainActivity has:
```
public static Drawer mDrawer = null;
.
.
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    mDrawer = new DrawerBuilder()
             .withActivity(this)
             .
             .
             .build();
}
```

My Fragments  have:
```
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    mToolbar = (Toolbar) fragmentView.findViewById(R.id.toolbar);
    ((AppCompatActivity) getActivity()).setSupportActionBar(mToolbar);
    ActionBar actionBar = ((AppCompatActivity) getActivity()).getSupportActionBar();
    actionBar.setHomeButtonEnabled(true);

    MainActivity.mDrawer.setToolbar(getActivity(), mToolbar);
}
```

It works fine, but I would like to know if this is bad for any reason.

**Comment by mikepenz** [comment]
@mdalikazi the main issue here is that it is not recommend to access activity methods or fields statically, because this could lead to `context` leaks. 

Otherwise the part with setting the toolbar is fine

**Comment by gpulido** [comment]
@percula 
At the end I'm just creating a toolbar in each fragment and on each inflate I manage the actionbar home button.
As I'm using now kotlin + MVVM + SimpleStack, using some base clases and interface default implementations to show arrow / hamburguer ended being just a flag on the screen for the simplestack.
