### ISSUE TITLE
Custom item

### ISSUE THREAD

**Issue by amouly** [mikepenz/MaterialDrawer#55]
Is there a way to set a custom "item layout"? Basically for the "primary item". My problem is that I need to add some view customizations to the items.

**Comment by mikepenz** [comment]
@amouly look at the source of the `PrimaryDrawerItem`. Just create your own implementation of the `IDrawerItem` interface and any interfaces which may fit your item. It's really easy. If your custom item is ready, just add it to the Drawer as you would with any other item.
