### ISSUE TITLE
Items not showing in android api 22

### ISSUE THREAD

**Issue by Reidy1994** [mikepenz/MaterialDrawer#551]
![material](https://cloud.githubusercontent.com/assets/9309350/9198910/05ba9d74-4048-11e5-96c8-8b92cd6bbf5d.png)

```java
drawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withTranslucentStatusBar(true)
                .withActionBarDrawerToggle(true)
                .withActionBarDrawerToggleAnimated(true)
                .withCloseOnClick(true)
                .withOnDrawerItemClickListener(this)
                .withHeader(R.layout.drawer_header)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.drawer_item_map).withIcon(FontAwesome.Icon.faw_home).withIdentifier(1),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_pons).withIcon(FontAwesome.Icon.faw_compass).withIdentifier(2),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_pois).withIcon(FontAwesome.Icon.faw_map_marker).withIdentifier(3),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_events).withIcon(FontAwesome.Icon.faw_comments).withIdentifier(4),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_logs).withIcon(FontAwesome.Icon.faw_bug).withIdentifier(5),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_info).withIcon(FontAwesome.Icon.faw_info_circle).withIdentifier(6)
                )
                .build();
```

```gradle
compile('com.mikepenz:materialdrawer:3.1.2@aar') {
        transitive = true
    }
```

**Comment by mikepenz** [comment]
For v4.0.0 it works. And i remember that it also worked vor v3.1.2. not sure what goes wrong for you. the same code runs on api 21?

<img width="570" alt="bildschirmfoto 2015-08-11 um 18 07 55" src="https://cloud.githubusercontent.com/assets/1476232/9202825/fb3f534c-4053-11e5-8dce-e5b427706a45.png">

**Comment by Reidy1994** [comment]
if build drawer with .withHeader(R.layout.drawer_header)

drawer_header.xml:
<ImageView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:adjustViewBounds="true"
    android:orientation="vertical"
    android:scaleType="fitCenter"
    android:src="@drawable/header"></ImageView>

and header.xml:
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape
            xmlns:android="http://schemas.android.com/apk/res/android"
            android:shape="rectangle">
            <solid android:color="#eeeeee"></solid>
            <size android:height="100dp"></size>

        </shape>
    </item>
</layer-list>

then items not visible in api 22

if remove .withHeader, all work fine

**Comment by mikepenz** [comment]
@Reidy1994 then the problem is that your header takes all the space. i would recommend that you define a fixed height for it

**Comment by Reidy1994** [comment]
thanks!
