### ISSUE TITLE
Expandable nav item

### ISSUE THREAD

**Issue by hishamBakr** [mikepenz/MaterialDrawer#552]
Thank you for great component. This is an enhancement. I would like to have an option to add expandable item.

I am building RSS app where you can subscribe to tons of channels. so it is better to add expandable categories to navigation drawer

**Comment by mikepenz** [comment]
There were already a few questions about it. see the previous answers: https://github.com/mikepenz/MaterialDrawer/issues?utf8=%E2%9C%93&q=expandable
