### ISSUE TITLE
Load facebook picture into Profile pic in the drawer

### ISSUE THREAD

**Issue by Watsonibm** [mikepenz/MaterialDrawer#553]
Hello,

How can i show profile picture of facebook account in the profile picture of the drawer?

Thanks

**Comment by mikepenz** [comment]
@Watsonibm facebook has nothing to do with this project. Here is the information what you have to do to load an image from a url into the AccountHeader's profile:

https://github.com/mikepenz/MaterialDrawer#load-images-via-url
