### ISSUE TITLE
Why this is happend?

### ISSUE THREAD

**Issue by dominicsavb** [mikepenz/MaterialDrawer#554]
![screenshots_2015-08-12-10-04-43](https://cloud.githubusercontent.com/assets/6405946/9216180/46289ae0-40df-11e5-89d1-3fc51ec7bbb6.png)

Why this is happend?

Thank youuuu

**Comment by mikepenz** [comment]
@dominicsavb you have set a sectionDrawerItem as first element which has a padding on top of the divider. you can either deactivate the divider for it. But the recommended solution is to remove this sectionDrawerItem as it is obsolete and the user already sees that he is within a menu
