### ISSUE TITLE
Drawer icons looks totally black

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/MaterialDrawer#556]
I've noticed that the material drawer icons look totally black when the light theme is set.

when in fact I see it must be like gray color right ?

in the demo example also shows me "black" while using the light theme...

everything else works perfect

**Comment by mikepenz** [comment]
@seba123neo i assume you use it with a pre api level 21 device. those versions are not able to display the (icon) font with transparency, so they display black. a workaround would be to set the normal icon color as grey not black with transparency. but for the default settings i kept it black as it will be correct on newer api levels

**Comment by seba123neo** [comment]
yes, api is pre 21, now I understand...
I realized that when I was testing an example of navigation drawer of the new "desing library" and even in pre 21 api, icons look good...

**Comment by mikepenz** [comment]
@seba123neo you can either define real icons (as the design library does) or you overwrite the default color of the icons to be a solid grey instead of black with alpha

**Comment by mikepenz** [comment]
@seba123neo there will be an improvement to the coloring in v4.0.0 of the MaterialDrawer

**Comment by seba123neo** [comment]
ok, thanks mike !!! you can close this issue

I hope very anxious the version 4, which will be spectacular.

**Comment by mikepenz** [comment]
you can try already: https://github.com/mikepenz/MaterialDrawer/tree/feature/refactoring
