### ISSUE TITLE
stack over flow when use Glide

### ISSUE THREAD

**Issue by hishamBakr** [mikepenz/MaterialDrawer#557]
Dear,
         Thank you for the great effort. I just face an issue when I want to load profile image via Uri, I use this code in Application class:

        DrawerImageLoader.init(new DrawerImageLoader.IDrawerImageLoader() {
            @Override
            public void set(ImageView imageView, Uri uri, Drawable placeholder) {
                Glide.with(imageView.getContext()).load(uri).placeholder(placeholder).into(imageView);
            }

            @Override
            public void cancel(ImageView imageView) {
                Glide.clear(imageView);
            }

            @Override
            public Drawable placeholder(Context ctx) {
                return null;
            }
        });

This code gives Stack over flow exception in this part (Glide.clear(imageView);)

when I remove this line of code, issue fixed. Please advise.

**Comment by mikepenz** [comment]
@hishamBakr this is a problem with glide and v3.1.2. It is fixed in v4.0.0 of the drawer. It's currently in beta https://github.com/mikepenz/MaterialDrawer/issues/487#issue-95296856

**Comment by Rainer-Lang** [comment]
@mikepenz Now we all could use Gilde? Is this tested?

**Comment by mikepenz** [comment]
Yes this is fixed now

**Comment by Rainer-Lang** [comment]
confirmed :-)
