### ISSUE TITLE
Header is not displayed on some phones.

### ISSUE THREAD

**Issue by asinel** [mikepenz/MaterialDrawer#558]
I use material drawer
```java
.withHeader(R.layout.drawer_header)
```
R.layout.drawer_header:
```xml
<?xml version="1.0" encoding="utf-8"?>
<ImageView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:adjustViewBounds="true"
    android:orientation="vertical"
    android:scaleType="fitCenter"
    android:src="@drawable/logo"/>
```
Usually it works: (Screen from samsung LG-L90)
![quickmemo _2015-08-14-20-09-34 1](https://cloud.githubusercontent.com/assets/11772185/9284859/7dd4dfb6-42e8-11e5-9822-990742fcd357.png)
But on some phones it doesn't works: (Screen from Samsung Galaxy S3)
![photo58236909_376189626](https://cloud.githubusercontent.com/assets/11772185/9284879/a94cc1ea-42e8-11e5-852a-e695914a0168.jpg)

**Comment by mikepenz** [comment]
@asinel seems to be an android issue. i think it should work if you put the ImageView inside a LinearLayout and give it a fixed height

**Comment by asinel** [comment]
Sorry I didn't answered how did I resolved this issue. Problem was in size of image. Some phones could not render it in time, and displayed white screen for preventing freeze of main thread. Downsampling resolved the issue.
