### ISSUE TITLE
Navigation icon to the right

### ISSUE THREAD

**Issue by TheLoyalCruel** [mikepenz/MaterialDrawer#561]
in multi drawer activity,
how to set the navigation drawer icon (hamburger icon) to the right side of toolbar!?
thanks...

**Comment by mikepenz** [comment]
@TheLoyalCruel the ActionBarDrawerToggle is by default on the left. This is System specific. It is only on the right if you have an RTL app. 

If you want a custom behavior. don't pass the `Toolbar` to the drawer and handle the open/close on your own with a normal `MenuItem`

**Comment by TheLoyalCruel** [comment]
thanks...
could you please help me to set a menuItem to open the drawer from the right side! something like this:
![screenshot_2015-08-22-11-16-24](https://cloud.githubusercontent.com/assets/10336613/9422922/aeab7d02-48bf-11e5-982c-e26f8da3ce21.png)

**Comment by mikepenz** [comment]
you can open the drawer with. `drawer.openDrawer()` and close it with `drawer.closeDrawer()` and check if it is open with `drawer.isDrawerOpen()` (probably a bit different named, i just write it without looking at the code)

the whole thing is nothing MaterialDrawer specific. Just normal Android + DrawerLayout ;)

**Comment by TheLoyalCruel** [comment]
Dear Mike
God bless you :)
special thanks...
