### ISSUE TITLE
SecondaryDrawerItem 

### ISSUE THREAD

**Issue by kathyfsouza** [mikepenz/MaterialDrawer#562]
Changing the background of SecondaryDrawerItem and color font as changed the way down and it did not work

```java
new SecondaryDrawerItem()
.withName(R.string.lbl_menu_sair)
.withIcon(R.drawable.mpm_ic_sair)
.withIdentifier(10).withCheckable(false)
.withBadgeBackgroundResource(R.color.cinza_sair)
.withBadgeTextColor(R.color.white)
```

**Comment by kathyfsouza** [comment]
já consegui.

Deverá ser alterado assim:

                        new SecondaryDrawerItem().withName(R.string.lbl_menu_sair).withIcon(R.drawable.mpm_ic_sair).withIdentifier(10).withCheckable(false).withSelectedColor(R.color.cinza_sair).withSelectedTextColorRes(R.color.white)

**Comment by mikepenz** [comment]
you try to pass a color to the background? You can only pass a drawable or a real drawable ressource as background for the badge

This will be improved in v4.0.0

**Comment by kathyfsouza** [comment]
I got it, thank you

2015-08-21 5:24 GMT-03:00 Mike Penz <notifications@github.com>:
