### ISSUE TITLE
Failed to resolve Gradle

### ISSUE THREAD

**Issue by manuelernesto** [mikepenz/MaterialDrawer#563]
When building project(sync gradle), appears this error:
Error: Failed to resolve: com.mikepenz.materialdrawer:3.1.2

**Comment by FabianTerhorst** [comment]
its not com.mikepenz.materialdrawer:3.1.2 its com.mikepenz:materialdrawer:3.1.2. Just replace the '.' with a ':'.

**Comment by manuelernesto** [comment]
@FabianTerhorst I replaced , but the error continues

**Comment by mikepenz** [comment]
@manuelernesto this is the correct gradle dependency:

```gradle
compile('com.mikepenz:materialdrawer:3.1.2@aar') {
    transitive = true
}
```

perhaps you have enabled offline mode in gradle? or you have other issues in your gradle which then fail with the MaterialDrawer dependency
