### ISSUE TITLE
Custom toggleDrawerItem

### ISSUE THREAD

**Issue by Igor-** [mikepenz/MaterialDrawer#564]
How I can set custom style for toggleDrawerItem? I can't find answer in Style the drawer section of official documentation.

**Comment by mikepenz** [comment]
@Igor- the best solution would be to create a CustomDrawerItem in your case. This will allow you to have more control about the behavior and look of your DrawerItem. 

Creating a CustomDrawerItem is really easy. In your case copy the `ToggleDrawerItem` and add it to your project. You can then modify how the item is created (Like in a normal Adapter)
