### ISSUE TITLE
Open drawer when swiping from edges.

### ISSUE THREAD

**Issue by ealarco1** [mikepenz/MaterialDrawer#565]
Is there a way to enable the option to open the drawer by swiping a finger from the left edge and not only by touching the icon in action bar? I don't know if it's disabled by default in your implementation or I am building it wrong.
```
leftDrawer = new Drawer().withActivity(this).withActionBarDrawerToggle(true).withToolbar(toolbar).
withAccountHeader(headerResult).withDrawerItems(drawerItems).withOnDrawerItemClickListener(this).build();
```
Thanks.

**Comment by FabianTerhorst** [comment]
@ealarco1 try to use the ```new DrawerBuilder()``` Object to build the drawer. 
```mBuilder = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(mToolbar)
                .withAccountHeader(mHeaderResult)
                .withSavedInstance(savedInstanceState);
                .build()
```

**Comment by ealarco1** [comment]
@FabianTerhorst It appears that I was using an old version (2.7.7) and the DrawerBuilder wasn't used back then. I upgraded my dependencies, and modified my code to use DrawerBuilder() instead as you suggested but it still doesn't let me open the drawer by swiping.

**Comment by FabianTerhorst** [comment]
you can enable it with mDrawer.getDrawerLayout().setDrawerLockMode(DrawerLayout.LOCK_MODE_UNLOCKED);

**Comment by ealarco1** [comment]
Solved it. Thanks.

**Comment by mikepenz** [comment]
@FabianTerhorst thanks for your help during my vacation ;)

@ealarco1 normally do you lock the drawer somewhere. By default it should be swipeable
