### ISSUE TITLE
Wrong toolbar position

### ISSUE THREAD

**Issue by electrolobzik** [mikepenz/MaterialDrawer#566]
In my app I came to an issue with position of toolbar. I use `MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus` theme. In my activity layout the root element has `android:fitsSystemWindows="true"`.

If I don't setup drawer immediately and add it only after some event. If I am using `.withTranslucentStatusBar(true)` it adds extra spacing between status bar and toolbar with height of status bar. So I am using `.withTranslucentStatusBar(false)` and everything works fine: drawer starts from screen top (under translucent status bar) and my toolbar is located exactly under status bar. But if I use the same code in onCreate method the toolbar is positioned on the screen top (under status bar).

Of cause I can use  `.withTranslucentStatusBar(false)` in first case and  `.withTranslucentStatusBar(true)` in second case and it solves the problem. But I wonder if I am using the library right way?

My sample project that reproduces the issue: [TestMaterialDrawer](https://github.com/electrolobzik/TestMaterialDrawer).

**Comment by electrolobzik** [comment]
What I get with `.withTranslucentStatusBar(true)` in first case (delayed setup): ![extra spacing](http://i.imgur.com/CREA8E2.png)
What I want to get in both cases and get with `.withTranslucentStatusBar(false)` in delayed case and with `.withTranslucentStatusBar(true)` in onCreate case: ![perfect](http://i.imgur.com/swqFa1q.png)
What I get with `.withTranslucentStatusBar(false)` in second case (setup during onCreate): ![wrong position](http://i.imgur.com/zca86LR.png)

**Comment by mikepenz** [comment]
@electrolobzik the MaterialDrawer should take the complexity out of the `StatusBar`, `Toolbar` positioning. So you do not have to use `android:fitsSystemWindows="true"` in your layouts. You can see samples of all different behaviors (tested on devices with API Level 10, 17, 19, 21, 22) in the sample app.

**Comment by electrolobzik** [comment]
In my case I need to get toolbar WITHOUT drawer. And only after some event initialize drawer. As I see all samples show cases only with drawer. How can I achieve the behaviour?

**Comment by mikepenz** [comment]
@electrolobzik i will take a look at your sample you posted. 

What you want is a bit problematic. as the MaterialDrawer inflates the DrawerLayout and also the ScrimInsetsFrameLayout to simplify everything for you. 

I would recommend that you create the Drawer on start of you application but you lock it so it can't be opened. You can then add and modify the items at a later time. But the MaterialDrawer would already simplify `StatusBar` behavior etc over all api levels for you?

**Comment by electrolobzik** [comment]
Your variant should work for me. How can I lock the drawer and remove the hamburger icon from the toolbar?

**Comment by mikepenz** [comment]
@electrolobzik just don't pass the `Toolbar` to the drawer via the builder. And to lock the Drawer. You can call something like. 

```java
mDrawer.getDrawerLayout().setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED);
```

**Comment by electrolobzik** [comment]
Perfect! Thank you a lot!
