### ISSUE TITLE
Disabling automatic "up navigation" after profile selection

### ISSUE THREAD

**Issue by adamgrieger** [mikepenz/MaterialDrawer#567]
Hi,

I have looked through documentation and the code to see if I could fix this myself, but I couldn't find a definite answer. Basically, what I want to do is add profiles, select profiles, etc. without being taken back to the "main" drawer items. I am not sure if there is a listener to override or something similar to disable automatic up navigation, so I thought I should ask. For reference, I am using the latest testing version of MaterialDrawer 4.X.X.

Thanks!

**Comment by mikepenz** [comment]
@adamgrieger you can control this via `withCloseDrawerOnProfileListClick` on pre v4.0.0. Starting with v4.0.0 (with the final version) you will be able to handle this also via the `onProfileChanged` listener by returning `true` if you have consumed the event, or false if you want the drawer continue with the functionality (closing the drawer)

**Comment by mikepenz** [comment]
ok just saw that this is not exactly what you need/want. i will improve it for v4.0.0

**Comment by mikepenz** [comment]
And i was wrong :D there is already a method for this too: `withResetDrawerOnProfileListClick`

**Comment by adamgrieger** [comment]
Great, exactly what I needed. Thanks!
