### ISSUE TITLE
Ability to add custom view in Drawer removed?

### ISSUE THREAD

**Issue by aeroperf** [mikepenz/MaterialDrawer#569]
I used to be able to add a custom (non list) view to a drawer. After updating to the latest version, it appears this is not possible anymore (still early....maybe I'm just missing it)?

**Comment by mikepenz** [comment]
@aeroperf from which version did you update? to v3.1.2?

**Comment by aeroperf** [comment]
2.8.1

**Comment by mikepenz** [comment]
`withCustomView` is not working for you?

**Comment by mikepenz** [comment]
@aeroperf just as a quick info. if you are currently updating. you probably should wait for v4.0.0 which will land today.

**Comment by aeroperf** [comment]
I swear I looked everywhere for something like that in the docs and did not find it... 8-/

Previously I was using .append(), which allowed setting a view within. Thanks!

**Comment by mikepenz** [comment]
@aeroperf i think this method is not shown in the docs as it is a really advanced usage. Always hoping for devs to check the source ;). But great that i was able to help. 

v4.0.0 will come with a RecyclerView, just in case you use this method for this. 

about `.append()` this is only used now to add a second slider on the other side

**Comment by aeroperf** [comment]
I was digging through the source when the email came across that you posted. Thanks again, great library!

**Comment by mikepenz** [comment]
@aeroperf thank you so much ;)
