### ISSUE TITLE
Drawer Styling Question

### ISSUE THREAD

**Issue by monakhv** [mikepenz/MaterialDrawer#57]
Hi!
This is not really issue. 
I did small test application using two variants of application theme as
MaterialDrawerTheme and MaterialDrawerTheme.Light. 
In both cases the Drawer background is Light!

Is it correct or I do something wrong?
Yes I can adjust colors by hand. Nevertheless  is there any possibility to make Drawer style according to application one?

**Comment by mikepenz** [comment]
@monakhv yeah it's not yet optimal, because those values should be theme specific. 

At the moment you should overwrite following color values 

```xml
    <!-- Material DEFAULT colors -->
    <color name="material_drawer_primary">#2196F3</color>
    <color name="material_drawer_primary_dark">#1976D2</color>
    <color name="material_drawer_primary_light">#BBDEFB</color>
    <color name="material_drawer_accent">#FF4081</color>
    <color name="material_drawer_window_background">#F9F9F9</color>
    <color name="material_drawer_background">#F9F9F9</color>
    <!-- Material DEFAULT text / items colors -->
    <color name="material_drawer_icons">#FFF</color>
    <color name="material_drawer_primary_text">#212121</color>
    <color name="material_drawer_secondary_text">#727272</color>
    <color name="material_drawer_hint_text">#B8B8B8</color>
    <color name="material_drawer_divider">#B6B6B6</color>
    <!-- Material DEFAULT drawer colors -->
    <color name="material_drawer_selected">#E8E8E8</color>
    <color name="material_drawer_selected_text">#2196F3</color>
```

**Comment by monakhv** [comment]
OK! Thank you for your explanation.

**Comment by mikepenz** [comment]
@monakhv no problem ;). 

But yeah making these values theme specific would be better :D

**Comment by mikepenz** [comment]
@monakhv just to inform you. the latest preview version of the drawer has fixed this.

you can find it here: https://github.com/mikepenz/MaterialDrawer/issues/36#issuecomment-76812120
