### ISSUE TITLE
Error while syncing...

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/MaterialDrawer#570]
![codice_mat](https://cloud.githubusercontent.com/assets/7190255/9417483/05406e66-484d-11e5-9739-8c8f39fa2307.png)
![grad](https://cloud.githubusercontent.com/assets/7190255/9417484/054420ce-484d-11e5-8cd7-66cba58dfdfe.png)

**Comment by mikepenz** [comment]
@EpsilonOrionis v4.0.0 uses the latest v23 of the support libs. If you use older support libs or any libs which target older version you should update (or exclude the older dependencies)
