### ISSUE TITLE
Error while syncing... (Again)

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/MaterialDrawer#571]
I thought that creating a clean project, I could find out the other third party library that was in conflict with yours, but...

![schermata del 2015-08-21 22 59 18](https://cloud.githubusercontent.com/assets/7190255/9419013/6bd5c706-4858-11e5-9699-afc5b627f8fb.png)
![schermata del 2015-08-21 22 59 55](https://cloud.githubusercontent.com/assets/7190255/9419014/6bfc6b90-4858-11e5-8184-b83e2b796c0d.png)

**Comment by mikepenz** [comment]
@EpsilonOrionis ah i think i know what's the problem. The latest support libs 23 also require the newest build tools 23 and target 23. And i'm not sure if it also requires the gradle build tools 1.3

**Comment by mikepenz** [comment]
```gradle
compileSdkVersion 23
buildToolsVersion "23"

//not sure if this one is required too
targetSdkVersion 23
```
