### ISSUE TITLE
Item Highlighting issue

### ISSUE THREAD

**Issue by zenix98** [mikepenz/MaterialDrawer#572]
Hey there is no such method which can highlight the items in the drawer programticall,
I am facing an issue if user selects an option from the menu drawer and moves to fragment 1, and without back press again he slide the menu drawer and selects another option which opens fragment 2 now he press back button (android os) when he slides the drawer option item 2 is selected although he is on first fragment.

please provide the way so that i can highlight the selected tab on back press.

**Comment by mikepenz** [comment]
Please read the Readme. There is an information about selection an item. Also look at the sample app.

**Comment by zenix98** [comment]
hey i have gone through the redme doc and found nothing regarding my query also i tested the applications using this library and found the same issue if some one press back it selects the first item even if he was on some other menu item selected.

**Comment by mikepenz** [comment]
Because I implemented this behavior. You can implement any other behavior. No limitations. 

The is a section on the Readme how you can select an item programmatically

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#selecting-an-item
