### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/MaterialDrawer#573]
Mike, your MaterialDrawer (and also your other wonderful, great and helpful libs) saved lot of work. Your libs are all on a very high level!
Thank you for your hard work and your ongoing development in your free time!

You know, I'm using your MaterialDrawer, Android-Iconics and AboutLibraries - for all other devs: have also a look to the other superb libs.

**Comment by mikepenz** [comment]
+1 :) 

Thank you for the nice words
