### ISSUE TITLE
Fullscreen activity without status bar

### ISSUE THREAD

**Issue by Null45** [mikepenz/MaterialDrawer#575]
Hi there! I tried to make fullscreen activity with the material drawer, but got a white status bar placeholder(white line at top). How fix it? 
![image]()
![image](https://cloud.githubusercontent.com/assets/201536/9425619/9167df70-4940-11e5-9e39-05813cefb84e.png)

My app theme:

    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:typeface">monospace</item>
        <item name="windowActionBar">false</item>
        <item name="android:windowContentOverlay">@null</item>
        <item name="android:windowFullscreen">true</item>
        <item name="drawerArrowStyle">@style/MaterialDrawer.DrawerArrowStyle</item>
    </style>

OnCreate also has:

        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
                WindowManager.LayoutParams.FLAG_FULLSCREEN);

and my material drawer code: 

        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        toolbar.setContentInsetsAbsolute(0, 0);
        Typeface typeFace = Typeface.createFromAsset(getAssets(), "fonts/font.ttf");
        PrimaryDrawerItem di = new PrimaryDrawerItem().withName(R.string.drawer_item_rate);
        di.setTypeface(typeFace);
        //Drawer
        new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withActionBarDrawerToggle(true)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.drawer_item_cabinet).withIdentifier('1'),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_help),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_about),
                        new DividerDrawerItem()
                ).addDrawerItems(di)
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(AdapterView<?> adapterView, View view, int i, long l, IDrawerItem iDrawerItem) {
                        Intent _menuIntent = null;
                        switch (i) {
                            case 0:
                                if (AppModel.INSTANCE.getRegData() == null)
                                    _menuIntent = new Intent(RootActivity.this,RegistrationActivity.class);
                                else _menuIntent = new Intent(RootActivity.this,AccountActivity.class);
                                break;
                            case 1: 
                                _menuIntent = new Intent(RootActivity.this,SupportActivity.class);
                                break;
                            default:
                                break;
                        }
                        if (_menuIntent != null)
                            startActivity(_menuIntent);
                        return false;
                    }
                })
                .build();

**Comment by mikepenz** [comment]
I am currently on vacation. So answering with my phone. 

No need for setting flags on your own. Everything working out of the box. Just use `withFullscreen(true)` with the drawer builder. Should do the job

**Comment by Null45** [comment]
Working! Bit thanks for your job! U're the best! :)

**Comment by try2bajed1** [comment]
helped me too, thanx Mike!!!
