### ISSUE TITLE
Badge size changes on DrawerItem click

### ISSUE THREAD

**Issue by echthard** [mikepenz/MaterialDrawer#576]
Hi, 

I've noticed that if I click a few times on an Item with a Badge, its size will increase. The Badge will grow bigger and bigger if you keep on clicking.

 If I then click on an other Item and then again on the one with the increased Badge, it will return to normal size. But if I click on even an other Item, the really big size is back again.

You can see it if you go to your Sample app and go to Embedded Drawer and then click on "ActionBar Drawer" a few times.

**Comment by singhdd93** [comment]
Yeah it happens. Nice find @echthard
