### ISSUE TITLE
Styling selected Item

### ISSUE THREAD

**Issue by echthard** [mikepenz/MaterialDrawer#577]
Hi Mike,

What do you think of the ability to change the selected Item some more?

My suggestion is to make the name BOLD and to change the Badge color for the selected Item.
Also I might like to disable the grey background color to indicate which Item is selected.

**Comment by mikepenz** [comment]
@echthard i have added a new method to do this. You can now provide some logic to modify the view of an item after it was created by the adapter. just provide an `OnPostBindViewListener`

```java
.withPostOnBindViewListener(new OnPostBindViewListener() {
                            @Override
                            public void onBindView(IDrawerItem drawerItem, View view) {
                                
                            }
                        })
```
