### ISSUE TITLE
Missing: .withDisplayBelowToolbar

### ISSUE THREAD

**Issue by R0ns3n** [mikepenz/MaterialDrawer#579]
Hey,

I just updated to version 4. Now I'm missing .withDisplayBelowToolbar. Is there another way to display the Drawer below the Toolbar or did you just removed it?

**Comment by FabianTerhorst** [comment]
@mikepenz wrote "this api was removed as it is not a good solution. if you really need a (custom) drawer which should be displayed below a toolbar there is a better way by defining a layout where the drawer should be set to. You can find a sample how to do this in the sample application.

See the CustomContainerAcitvity how you can achieve this: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java"

source: https://github.com/mikepenz/MaterialDrawer/issues/487

**Comment by mikepenz** [comment]
@R0ns3n as @FabianTerhorst already (correctly) mentioned. This was removed because it was a bad solution. If you want the Drawer below the toolbar. Follow the implementation of the `CustomContainerActivity`

**Comment by vasiledoe** [comment]
@mikepenz you already posted an answer on this subject here( https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_show_drawer_under_toolbar.md ) but there is a problem: Drawer is working ok if open/close it using toggle button but if try to open it swiping the screen beginning it appears just blank drawer

**Comment by vasiledoe** [comment]
what about expandable list item, is there such a posibility?

**Comment by mikepenz** [comment]
@vasiledoe no not at the moment https://github.com/mikepenz/MaterialDrawer/issues/372
