### ISSUE TITLE
Drawer position

### ISSUE THREAD

**Issue by alex-soft-r** [mikepenz/MaterialDrawer#58]
Its possible make two Drawers and place one at left and another at rigth side of layout?

**Comment by egor-n** [comment]
Yes, it is possible. See [sample](https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/MultiDrawerActivity.java).

**Comment by mikepenz** [comment]
@egor-n thanks

**Comment by alex-soft-r** [comment]
Thanks
