### ISSUE TITLE
String as identifier for profile - possible feature ?

### ISSUE THREAD

**Issue by Dokuzov** [mikepenz/MaterialDrawer#580]
Can we have withStringIdentifier() method added to ProfileDrawerItem builder and a 
String getStringIdentifier() to the IProfile interface?

Could be in a great use i believe , well to me at least :v:

**Comment by mikepenz** [comment]
@Dokuzov theoretically it is possible, but has big disadvantages. You would not be able to use a `switch` to handle the listeners and so on. also it is really hard to change the logic now, as everything (also the apps of others) depend on the identifier being an `int` 

What would be possible in your case is, give those items an identifier you can use to modify them later and define a `Tag`. You can choose any object as `Tag` and you can check this `Tag` in the callbacks then?

**Comment by Dokuzov** [comment]
Yes that is working thanks.

**Comment by mikepenz** [comment]
@Dokuzov great :+1:
