### ISSUE TITLE
Add badge color

### ISSUE THREAD

**Issue by javiersantos** [mikepenz/MaterialDrawer#581]
How can be added the badge background color as appears in the screenshot?

Thanks and awesome update!

![Badge color](https://raw.githubusercontent.com/mikepenz/MaterialDrawer/feature/refactoring/DEV/github/screenshots1.jpg)

**Comment by echthard** [comment]
Hi Javier,

You can find it in the sample app. But I'll explain it for you:

Define two colors; the backgroundColor you want and a pressedColor you'll see when you press the Item.

Then create a BadgeStyle:

BadgeStyle badgeStyle = new BadgeStyle(backgroundColor, pressedColor).withTextColor(Color.WHITE);

And then apply that badgeStyle to your Items. For example:

 new PrimaryDrawerItem().withBadgeStyle(badgeStyle).withBadge("10")

**Comment by mikepenz** [comment]
@echthard thanks for answering.

**Comment by javiersantos** [comment]
Nice! Thanks.
