### ISSUE TITLE
.withHeader(int headerViewRes) does not work

### ISSUE THREAD

**Issue by AngleV** [mikepenz/MaterialDrawer#582]
i am trying the following

```java
 result = new DrawerBuilder()
                .withActivity(this)
                .withHeader(R.layout.header)
```

but it does not display the header at all.
If i change it with  `.withStickyHeader`  it works fine
Any idea ?

**Comment by mikepenz** [comment]
@AngleV does your header layout have a defined height?

**Comment by AngleV** [comment]
Hello mike

Yes my header layout is a FrameLayout with layout_height set to 170dp. 
But no luck.

Also i found out that if i use builder with ".withHeader" and without .addDrawerItems  method i get a NullPointerException.
 
Attempt to invoke virtual method 'void com.mikepenz.materialdrawer.adapter.BaseDrawerAdapter.addHeaderDrawerItems(com.mikepenz.materialdrawer.model.interfaces.IDrawerItem[])' on a null object reference

That thing not happen if i use .withStickyHeader instead of .withHeader

**Comment by mikepenz** [comment]
@AngleV can you wrap it inside another layout (LinearLayout this can be match_parent, wrap_content). seems like the RecyclerView breaks the height

the StickyHeader and StickyFooter work different. They are not part of the RecyclerView. they are above and below.

**Comment by AngleV** [comment]
Wrap it inside LinearLayout with wrap_content.  Same thing :(

**Comment by mikepenz** [comment]
How does your layout you try to set as header look like?

**Comment by AngleV** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout 
              xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="wrap_content">

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:adjustViewBounds="true"
        android:orientation="vertical"
        android:scaleType="fitCenter">

        <ImageView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:src="@drawable/placeholder"/>

    </FrameLayout>
</LinearLayout>

**Comment by mikepenz** [comment]
try to change it to:

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout 
              xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="wrap_content">

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="170dp"
        android:adjustViewBounds="true"
        android:orientation="vertical"
        android:scaleType="fitCenter">

        <ImageView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:src="@drawable/placeholder"/>

    </FrameLayout>
</LinearLayout>
```

**Comment by AngleV** [comment]
No luck !!!

**Comment by mikepenz** [comment]
@AngleV with both variants? i use the second one in the sample app. and it works

**Comment by AngleV** [comment]
Yes with both variants and it does not work !!!!

code below

        result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withHeader(R.layout.header)
                .withHeaderDivider(false)
                .withSavedInstance(savedInstanceState)
                .addDrawerItems()
               .build();

**Comment by mikepenz** [comment]
@AngleV it breaks with `.withHeaderDivider(false)` just tried it. :/

**Comment by AngleV** [comment]
@mikepenz 

Yes Now it works like a charm !!!

Thank you for your time.
Awaiting for the release that fixes the header without addDrawerItems.

**Comment by mikepenz** [comment]
@AngleV just pushed v4.0.1 will take about 30 minutes to sync to maven central ;)

thanks for helping to fix this issue

**Comment by AngleV** [comment]
i thank you @mikepenz for your awesome lib 
Keep up coding !!!

**Comment by mikepenz** [comment]
thanks :)
