### ISSUE TITLE
Tapping Custom Header Layout triggers click on RecycleView behind it

### ISSUE THREAD

**Issue by AngleV** [mikepenz/MaterialDrawer#583]
I have a custom header layout and when i tap to it it triggers click event to my RecyclerView which is inside a Fragment.

**Comment by mikepenz** [comment]
@AngleV even if your layout has an onClickListener and is clickable?

**Comment by AngleV** [comment]
@mikepenz 
I use .withStickyHeader
My Layout is the layout that suggested at #582 
Just an ImageView

**Comment by mikepenz** [comment]
You have to make it clickable and set an onClickListener on it to catch the events. else they are passed to the below layout

**Comment by AngleV** [comment]
By setting android:clickable="true" to my xml layout it did the trick. 
No need to set a onClickListener.

You may close it.
Thanks a lot
