### ISSUE TITLE
BadgeStyle that supports LayerDrawable

### ISSUE THREAD

**Issue by AngleV** [mikepenz/MaterialDrawer#584]
What about add a BadgeStyle overload method that supports LayerDrawable also.

**Comment by mikepenz** [comment]
@AngleV not possible as i use a `StateListDrawable` internally, and the two states are defined as `GradientDrawable` would mean a lot of changes for this.

Any advantage for you?

**Comment by AngleV** [comment]
@mikepenz 

I see.

it would be great if i could use the following as background for my badges

<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:bottom="0.1dp"
        android:left="0.2dp"
        android:right="10dp"
        android:top="10dp">
        <shape xmlns:android="http://schemas.android.com/apk/res/android"
            android:shape="rectangle">
            <solid android:color="@color/actionbar" />
        </shape>
    </item>

    <item>
        <shape xmlns:android="http://schemas.android.com/apk/res/android"
            android:shape="oval">
            <solid android:color="@color/actionbar" />
            <size
                android:width="20dp"
                android:height="20dp" />
        </shape>
    </item>
</layer-list>
