### ISSUE TITLE
withFireOnInitialOnClick not working as expected

### ISSUE THREAD

**Issue by RubenGees** [mikepenz/MaterialDrawer#585]
Hi Mike, I recently started a new App and came across the following problem: It might have been asked before or came up with v4.0, I don't know.

When I set withFiroOnInitalOnClick to true, I expect the callback to be called when I start the Activity (Drawer Creation is in onCreate). That part is working. But when I do an orientation change and the Activity is recreated the callback is called again (which is not what to expect in my opinion). I save and restore the instance state of course.

This is the part where I create the drawer:
```java
drawer = new DrawerBuilder(this).withToolbar(toolbar)
                .withSavedInstance(savedInstanceState).withDrawerItems(generateDrawerItems())
                .withStickyDrawerItems(generateStickyDrawerItems())
                .withOnDrawerItemClickListener(onDrawerItemClickListener)
                .withFireOnInitialOnClick(true).build();
```

Here I save the instance state:
```java
@Override
protected void onSaveInstanceState(Bundle outState) {
     super.onSaveInstanceState(outState);

     drawer.saveInstanceState(outState);
 }
```

Am I donig something wrong or is this intended behaviour?

**Comment by RubenGees** [comment]
Sorry for the repost... :D

**Comment by mikepenz** [comment]
@RubenGees this is the correct behavior. a orientation change recreates the activity so it's also an initial launch :D

oO duplicate. where did you find the answer?

**Comment by mikepenz** [comment]
@RubenGees please talk here :D

**Comment by RubenGees** [comment]
Hmm, okay, so I have to manually set a flag or something to prevent the callback to be called twice? I do some loading in the callback, which I want to avoid to do twice and it is not very clean of course...
I thought savedInstanceStates are exactly for such purposes?

Sorry for the confusion :D

**Comment by mikepenz** [comment]
the thing is that everything specific to the ui is recreated when you turn the device. so i call the callback again so devs can also recreate selection specific stuff (like setting a fragment) 
if you do not want this in your case you have to remember that it was already called

**Comment by RubenGees** [comment]
Okay, makes sense. Thank you once again for your answer!
