### ISSUE TITLE
appcompat-v7:23 problem

### ISSUE THREAD

**Issue by stefandb** [mikepenz/MaterialDrawer#587]
Hi,

I get those errors when I add the Provide the gradle dependency code to my gradle file. 
```
-Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
-Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
In the next file \build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.0\res\values-v23\values-v23.xml
I get this errors in \build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.0\res\values-v23\values-v23.xml
``` 

stackoverflow says that I have to change my appcompat version to 22+ But I have this in my gradle file "compile 'com.android.support:appcompat-v7:21.0.3'". When I remove the MaterialDrawer from my gradle file. I can install the app successful on my android phone. 

What can I do the fix this problem?

(Sorry if my English is not correct)

**Comment by mikepenz** [comment]
@stefandb v4.0.0 uses the appcompat v23. you have to update to v23. Else you have to use a version prior v4.

**Comment by simonckenyon** [comment]
i would love to use v4 but appcompat v23 has problems with httpclient.
does the library depend on anything specific in v23 or will it work with v22?

**Comment by mikepenz** [comment]
@simonckenyon it will work with previous versions but you have to explicitly exclude the v23 support dependencies of the MaterialDrawer (and the sub libs)

**Comment by mikepenz** [comment]
```gradle
compile('com.mikepenz:materialdrawer:4.0.1@aar') {
        transitive = true
        exclude group: 'com.android.support'
}
```

i think something like this should do the job

**Comment by simonckenyon** [comment]
oh excellent. will try that now.

**Comment by stefandb** [comment]
Your solution works.
Thank you

**Comment by nazeer23** [comment]
Great Solution..Thank You
