### ISSUE TITLE
(Mini)Drawer width

### ISSUE THREAD

**Issue by jansallads** [mikepenz/MaterialDrawer#588]
Hi,

is there a quick way to change the width of the Drawer? Especially the MiniDrawer would be interesting to me, as I'd like to see it a bit slimmer for my use of it.

Thanks in advance & props for your awesome library!

**Comment by mikepenz** [comment]
@jansallads at the moment it has a fixed size. you will be only able to make it slimmer by overwriting the dimens attributes i have set

**Comment by jansallads** [comment]
I found the attribute, is there any way I can overwrite it on runtime or do I have to make a fork of your library for this and edit it there?

**Comment by mikepenz** [comment]
@jansallads you can define the dimen attributes in your project inside a dimens.xml and overwrite those values. (you can do the same for the layouts of the lib)

**Comment by jansallads** [comment]
Awesome, did not know of that, thanks!

**Comment by mikepenz** [comment]
@jansallads you will also have to modify the `material_drawer_item_mini.xml` and `material_drawer_item_mini_profile.xml` as those are also have the defined width

**Comment by jansallads** [comment]
Alright, also with creating files with the same name to overwrite the default values?

**Comment by mikepenz** [comment]
@jansallads correct ;). Also do not miss this one: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java#L149

**Comment by jansallads** [comment]
Perfect, thanks for your support! :-) :+1:

**Comment by mikepenz** [comment]
:+1: i try my best
