### ISSUE TITLE
Cannot resolve method withDisplayBelowToolbar(boolean):

### ISSUE THREAD

**Issue by JulienLeal** [mikepenz/MaterialDrawer#589]
Hi. I'm using your library currently.Although this method is in your documentation,  I can't find the method withDisplayBelowToolbar(boolean) in DrawerBuilder.class :
![aih3g0v](https://cloud.githubusercontent.com/assets/2480842/9476158/a9e698d6-4b41-11e5-859d-1250923aff3a.png)

Look my error :
![screenshot_1](https://cloud.githubusercontent.com/assets/2480842/9476256/0c3f302e-4b42-11e5-8a89-0b01489fe2f0.png)

I tried to find in your class path, but I didn't find it :/
![e9ok23f](https://cloud.githubusercontent.com/assets/2480842/9476231/f1157bf0-4b41-11e5-89e9-81ee4ca51757.png)

Do you have any idea about  what is my problem?? Thanks for your attention :)

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/579
