### ISSUE TITLE
Differences

### ISSUE THREAD

**Issue by Grozny** [mikepenz/MaterialDrawer#592]
Hi and thanks for the great library.

What are the differences between `withOnDrawerListener`, `withOnDrawerItemClickListener` and `withOnDrawerItemSelectedListener`, DrawerBuilder methods?
The wiki could be more specific and updated.

Thanks

**Comment by mikepenz** [comment]
`withOnDrawerListener`
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1185
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1229
* defines the callbacks for open/close/slide of the drawer (if you implement it the listener should speak by itself :D)

`withOnDrawerItemClickListener`
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1522
* Gets called when an item is clicked

`withOnDrawerItemSelectedListener`
is not used anymore. and i will delete it. totally forgot that one during the refactoring

**Comment by Grozny** [comment]
when i call result.setSelection(0/*identifier*/) will trigger any callback?

2015-08-26 11:02 GMT+01:00 Mike Penz <notifications@github.com>:

**Comment by mikepenz** [comment]
@Grozny no. just if you force it  https://github.com/mikepenz/MaterialDrawer#selecting-an-item
