### ISSUE TITLE
RTL support for minidrawer

### ISSUE THREAD

**Issue by ProgrammerBassam** [mikepenz/MaterialDrawer#594]
sorry for my bad English but I'm trying to set minidrawer in the right by using this command
`getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);`

but it doesn't appear

**Comment by mikepenz** [comment]
@ProgrammerBassam what do you want to achieve?

**Comment by ProgrammerBassam** [comment]
![screenshot_ - - - - -](https://cloud.githubusercontent.com/assets/7253737/9499818/60c68ed8-4c2a-11e5-8528-39c879f323b0.png)
My Activity Look like when I'm using minidrawer

**Comment by ProgrammerBassam** [comment]
![screenshot_ - - - - -](https://cloud.githubusercontent.com/assets/7253737/9499866/b0d52eac-4c2a-11e5-836b-c21949d27245.png)

**Comment by mikepenz** [comment]
@ProgrammerBassam i just published an update to the `Crossfader` library which is used to do the animation from mini to the normal drawer. it currently syncs to mavencentral so it will be available in the next 30 minutes. This update will improve the RTL feature. 

https://github.com/mikepenz/Crossfader/releases

**Comment by ProgrammerBassam** [comment]
Thanks A lot!!
But I'm using minidrawer, Is That update will work well with  minidrawer?
Sorry again for my bad English

**Comment by mikepenz** [comment]
@ProgrammerBassam as i understood your screenshorts correctly you use the MiniDrawer as shown in the `MiniDrawerActivity` (of the sample) this one uses the `Crossfader` library to do the crossfade effect.
