### ISSUE TITLE
Erro Error:Failed to resolve: Android-Iconics:iconics-core:unspecified

### ISSUE THREAD

**Issue by fernandodeveloper** [mikepenz/MaterialDrawer#595]
Hello,

Show erro ao use Iconics 

Error:Failed to resolve: Android-Iconics:iconics-core:unspecified

build.gradle is

```gradle
    compile 'com.mikepenz:iconics-core:1.7.4'
    compile 'com.mikepenz:materialdrawer:4.0.1'
 compile 'com.mikepenz:google-material-typeface:1.2.0.1'
    compile 'com.mikepenz:fontawesome-typeface:4.4.0.1'
```

**Comment by mikepenz** [comment]
@fernandodeveloper someone else already had the same issue. but i was not able to find out what's failing :/

https://github.com/mikepenz/MaterialDrawer/issues/574

**Comment by fernandodeveloper** [comment]
hehe, it's crazy!

@mikepenz  This is output complete

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find Android-Iconics:iconics-core:unspecified.
     Searched in the following locations:
         https://jcenter.bintray.com/Android-Iconics/iconics-core/unspecified/iconics-core-unspecified.pom
         https://jcenter.bintray.com/Android-Iconics/iconics-core/unspecified/iconics-core-unspecified.jar
         https://repo1.maven.org/maven2/Android-Iconics/iconics-core/unspecified/iconics-core-unspecified.pom
         https://repo1.maven.org/maven2/Android-Iconics/iconics-core/unspecified/iconics-core-unspecified.jar
         file:/C:/Users/PROGRAMACAO-WEB/AppData/Local/Android/android-studio/sdk/extras/android/m2repository/Android-Iconics/iconics-core/unspecified/iconics-core-unspecified.pom
         file:/C:/Users/PROGRAMACAO-WEB/AppData/Local/Android/android-studio/sdk/extras/android/m2repository/Android-Iconics/iconics-core/unspecified/iconics-core-unspecified.jar
         file:/C:/Users/PROGRAMACAO-WEB/AppData/Local/Android/android-studio/sdk/extras/google/m2repository/Android-Iconics/iconics-core/unspecified/iconics-core-unspecified.pom
         file:/C:/Users/PROGRAMACAO-WEB/AppData/Local/Android/android-studio/sdk/extras/google/m2repository/Android-Iconics/iconics-core/unspecified/iconics-core-unspecified.jar
     Required by:
         AFV:app:unspecified > com.mikepenz:fontawesome-typeface:4.4.0.1

**Comment by mikepenz** [comment]
@fernandodeveloper exact the same output. 
would it build with the GoogleMaterial dependency alone?

**Comment by mikepenz** [comment]
@fernandodeveloper found the issues. and now i know why it only happens for some people.

The difference between my gradle and dependencies and yours is that i always add `@aar` for Android libs. This (i believe) tells gradle to handle the dependency a bit different. (if i'm correct it sets `transitive: false` in the background) (so it is working for most people as it is also written with `@aar` in the readme)

So you now have to options. either you add `@aar` add the end of the typeface dependencies like this:
```gradle
compile('com.mikepenz:google-material-typeface:1.2.0.1@aar')
compile('com.mikepenz:fontawesome-typeface:4.4.0.1@aar')
```

or you add `transitive: false` like in this sample:
```gradle
compile('com.mikepenz:google-material-typeface:1.2.0.1') {
        transitive = false
}
compile('com.mikepenz:fontawesome-typeface:4.4.0.1') {
        transitive = false
}
```
