### ISSUE TITLE
BadgeStyle with custom font

### ISSUE THREAD

**Issue by AngleV** [mikepenz/MaterialDrawer#596]
is it possible ?

**Comment by mikepenz** [comment]
@AngleV if you really need this you can either implement your own CustomDrawerItem which supports this. Or you overwrite the layout of the PrimaryDrawerItem and define a font for your badge (https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_primary.xml#L67)

**Comment by AngleV** [comment]
@mikepenz 

Thanks.
Any short guide how to override the layout of PrimaryDrawerItem ???

**Comment by mikepenz** [comment]
copy and paste the layout and modify it to your needs (keep the name the same)
(if you do this, make sure to update it on your side if there are changes in the future)

**Comment by AngleV** [comment]
@mikepenz 

I am missing something here.
I am using your lib as package.
if i copy and paste the layout how it will work ?

**Comment by mikepenz** [comment]
@AngleV you still have access to the soruce via github. 

the build will then just use the layout of your project as it has the same ID

**Comment by AngleV** [comment]
@mikepenz 
Awesome !!!!!!!!!!!!!!

Did know that.
Many thanks for the tip
