### ISSUE TITLE
New Problem with RTL :)

### ISSUE THREAD

**Issue by ProgrammerBassam** [mikepenz/MaterialDrawer#597]
![screenshot_2015-08-26-21-16-10](https://cloud.githubusercontent.com/assets/7253737/9502103/df352268-4c37-11e5-87d2-51edabf4441e.png)
![screenshot_ - - - - -](https://cloud.githubusercontent.com/assets/7253737/9502102/df353276-4c37-11e5-8020-c94b165e9665.png)
I hope u understand the problem from the ScreenShots :)

**Comment by mikepenz** [comment]
@ProgrammerBassam no shadow :P

**Comment by ProgrammerBassam** [comment]
Yeap :)

**Comment by mikepenz** [comment]
@ProgrammerBassam there is now a new API on the MiniDrawer to enable RTL
