### ISSUE TITLE
[Question] Need help upgrading from a previous version

### ISSUE THREAD

**Issue by GYberkeley** [mikepenz/MaterialDrawer#598]
Hey Mike! I was previously on 3.1.2 and tried to upgrade to the new version and got this funny little bug when I changed the gradle to the latest:

http://imgur.com/rrWZiQ0

How can I fix this?

EDIT: Is it possible that the latest version of MaterialDrawer needs SDK 23?

**Comment by singhdd93** [comment]
Yes the latest version needs 23 as compileSDKVersion

**Comment by mikepenz** [comment]
@singhdd93 yeah it needs it because of the latest `appcompat` libs from google. Will add it

**Comment by mikepenz** [comment]
Added to the migration guide
