### ISSUE TITLE
How to use navigation Drawer with Activities?

### ISSUE THREAD

**Issue by rajazeeshanahmed** [mikepenz/MaterialDrawer#599]
I've settings and help activity not fragment which i want to open from the navigation drawer items click. Activity started with the simple startactivity method but does not close and restarted on back press time and again. Fragment transaction with the navigation drawer are working perfectly fine but I need a combined flavor of both activities and fragments. Please help.

**Comment by mikepenz** [comment]
what should be closed and restarted? 

i have activities in the sample?

**Comment by rajazeeshanahmed** [comment]
Let me write the complete scenario.

1) Main activity contains the navigation drawer
2) Select the logout button from the navigation drawer which close the main activity and start the login activity.
3) enter the login credentials and click login button, on successful login I finish the login activity and start the main activity but it again start the login activity without any reason.
4) If I close the app after logout and remove it from the recently used apps, it works perfectly fine.

Another scenario:

1) On navigation drawer item click open the setting activity using this code Intent ia = new Intent(MainActivity.this,SettingsFragment.class);
                startActivity(ia);

Then press back button to close the settings activity , but it never closes, I override the on back button press function and write the finish() in it but not fruitful. Hope this will help you to clearly understand the problem.

**Comment by mikepenz** [comment]
@rajazeeshanahmed this is nothing MaterialDrawer specific then. This is normal android activity / navigation handling

**Comment by rajazeeshanahmed** [comment]
It is due to material Drawer, as other activity are working fine which started without the navigation drawer items click. and only the main activity which has the navigation drawer is creating problem.
