### ISSUE TITLE
Sync scroll states/positions when using MiniDrawer

### ISSUE THREAD

**Issue by bohoffi** [mikepenz/MaterialDrawer#600]
I've noticed that the scroll states or let me say the scroll positions between mini mode and normal/expanded mode are not synced.
![screenshot_2015-08-27-09-38-58](https://cloud.githubusercontent.com/assets/9944566/9515135/a22e4fa8-4c9f-11e5-8e10-1b0369e3a410.png)
![screenshot_2015-08-27-09-39-10](https://cloud.githubusercontent.com/assets/9944566/9515134/a2298cac-4c9f-11e5-96d8-6ca11a367374.png)

When scrolling all the way down in mini mode and expanding the drawer you're still at the very top.

**Comment by mikepenz** [comment]
@bohoffi this can be done by the dev who's implementing it. the `MiniDrawer` and normal `Drawer` are not linked together very deep. Their connection happens via the public useable APIs and listeners. So if you would love this, use the RecyclerView of the `MiniDrawer` and the one from the `Drawer` and listen to the scroll. Make also sure that the height is different as the `MiniDrawer` just shows `PrimaryDrawerItems` and also has a different header.
