### ISSUE TITLE
Custom layout with PrimaryDrawerItem

### ISSUE THREAD

**Issue by NorbertSzydlowski** [mikepenz/MaterialDrawer#603]
Can you help me with custom layout with DrawerItem.

I did @Override
    public int getLayoutRes() {
        return R.layout.drawer_primary;
    }

on previous version.

**Comment by mikepenz** [comment]
@NorbertSzydlowski you can also just copy and paste the original xml (with the same name) into your project and it will use this one then (https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_item_primary.xml)

Or you implement a complete CustomDrawerItem 
The method is the same (https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/PrimaryDrawerItem.java#L103)
