### ISSUE TITLE
Margin on stickyFooterItem

### ISSUE THREAD

**Issue by mychaelgo** [mikepenz/MaterialDrawer#604]
I found some different view on app demo

on my android 5.0

![screenshot_2015-08-27-21-05-23](https://cloud.githubusercontent.com/assets/4651658/9522533/91a59b04-4cff-11e5-8083-9094ac1fb00a.png)

on my android 4.1.2

![screenshot_2015-08-27-21-03-52](https://cloud.githubusercontent.com/assets/4651658/9522552/a81aa8a2-4cff-11e5-8d52-f21fc6822ac4.png)

**Comment by mikepenz** [comment]
ah i hate this api level. it simply breaks the padding somehow. will look at it

**Comment by mychaelgo** [comment]
@mikepenz  but when i use the version 3.0.7 in my project, it work fine for footer item margin in different OS :)

**Comment by mikepenz** [comment]
@mychaelgo the layout was completely redone with v4.0.0 and yeah this is probably the root cause for this

**Comment by mikepenz** [comment]
@mychaelgo fixed in v4.0.3

**Comment by mychaelgo** [comment]
@mikepenz ok i will try
