### ISSUE TITLE
How do i inflate a layout for the Account header

### ISSUE THREAD

**Issue by ersen-osman** [mikepenz/MaterialDrawer#605]
Is ok to ask some questions here?

I would like to use my own layout for the Accout Header

My code is like this
``` java
AccountHeader profileHeader =  new AccountHeaderBuilder()
                    .withActivity(this)
                    .withAccountHeader(R.layout.material_drawer_header)
                    .build();
```

This is not working, however the documentation says to see drawer.xml but i cannot find it .

**Comment by mikepenz** [comment]
This is the layout for the header: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml

If you want a different layout it requires to have the same elements. so not all can be changed. if you want a completely different layout you will have to create your own header

**Comment by ersen-osman** [comment]
Hi, thank you for the quickly reply. So is it possible for me to remove material_drawer_account_header_text_switcher? I do not need it. Plus i wish to use a different library for the circle image view. 

Could you point me to where i may find out more about creating my own header?

**Comment by mikepenz** [comment]
@ersen-osman no this is not possible. 

This means you will have to create a completely own headerview. etc... this will require you to redo the whole logic done in the `AccountHeader` i assume that's not what you want.

**Comment by mikepenz** [comment]
Sorry that this can't easily be done.

You can hide the `material_drawer_account_header_text_switcher` but you can't change to a different circleImageView
