### ISSUE TITLE
BadgeStyle.withBadgeBackground issue

### ISSUE THREAD

**Issue by AngleV** [mikepenz/MaterialDrawer#607]
when i set it i get a strange issue.
See screenshot
![device-2015-08-27-212108](https://cloud.githubusercontent.com/assets/7430985/9529270/016604f4-4d02-11e5-86b3-854d9b710def.png)

**Comment by mikepenz** [comment]
@AngleV how does the image you set look like?

**Comment by AngleV** [comment]
i have override your material_drawer_item_primary.xml and instead of TextView i am using my custom TextView with custom TypeFace.

so good so far.

If all Badges have the same length it works good.
By the time a badge get a 3 digit length i got what you can see in the screenshot above.


the background of the Badge is the following.

![screenshot_2015-08-27_21-31-41](https://cloud.githubusercontent.com/assets/7430985/9529480/30022102-4d03-11e5-94b2-a3d47f2fe40e.png)

**Comment by AngleV** [comment]
Correct View. Notice that all badges got 2 digits length

![screenshot1](https://cloud.githubusercontent.com/assets/7430985/9529559/ab74152a-4d03-11e5-89f3-77c912c5eb77.png)

**Comment by mikepenz** [comment]
i assume that happens because you share the same drawable for all your badges. and if one is transformed wrong the others will too. i am sorry, but this isn't MaterialDrawer specific. i think this does not happen with the original Badge. which will also allow you to have it completely round.

**Comment by AngleV** [comment]
Yes with the original Badge it works fine !!
Thank you
