### ISSUE TITLE
.updateSmth(...) actually slow

### ISSUE THREAD

**Issue by AlpenDitrix** [mikepenz/MaterialDrawer#609]
Without introduction: I have a Drawer with a long items list and all of them have badges. And I need to update all the badges sometimes (I'm recieving a JSON with new values and setting them in foreach cycle using `updateBadge` method)

But I faced a problem, that it's pretty slow solution. That all about milliseconds of course, but I can see a lag on animation.
As I think there's two problem: 
1. We're invoking getPosition(id) twice: firstly while searching for item to add a new data to him (first line of every `.updateSmth` method) and, secondly, while seraching a `position` to pass it to `.updateItemAtPosition(item, pos)`. It's a bit odd I think. We already can have position value in upstream method `updateSmth` so we can straight invoke `updateItemAtPosition` instead `updateItem`.
2. Why do we need to fully reset an item in adapter instead just use trigger `adapted.notifyItemChanged(pos))`? Unfortanately I'm away from my PC and haven't a deep look on how you've binded views and models, so maybe full reset is really required, but would be nice if you'll answer before I'll get home.

So I think the following solution may be better, isnt it? 

    void updateT(int identifier, V newVal) {
        int position = getPosition(identifier);
        T item = ((T) getAdapter.getItem(position));
        if (item != null) {
            item.withT(newVal);
            getAdapter().notifyItemChanged(position);
        }
    }

And what do you think about creating some "sugar" methods for full-list updaters like `updateAllBadges(List<StringHolder>)` which will do an update in just one cycle without some overdoings? E.g. we could call `getAdapter.notifyDataChanged()` just once in the end.

**Comment by mikepenz** [comment]
@AlpenDitrix thanks for the detailed report. 

You mentioned you have to search for the position all the time. If you use the `identifier` which is highly recommend you can directly use `updateItem` and set the `IDrawerItem` which will do the following:
First it will get the position for this item, then it will make sure there is an item at this position, and if yes it will set the item to the adapter, which will then trigger a `notifyItemChanged` so no real overhead here. 

If you want to get to a bit lower level you can also just set the DrawerItem directly to the Adapter 
```
result.getAdapter().setDrawerItem(position, drawerItem);
```
this will eliminate the search for the position, the check if this item exists.

**Comment by AlpenDitrix** [comment]
Hmmm, yep. Don't know how did I missed "updateItem". 
Thanks for answer.
