### ISSUE TITLE
Smaller icons

### ISSUE THREAD

**Issue by jekopena** [mikepenz/MaterialDrawer#610]
Hi, is there any way to make the icons of a PrimaryDrawerItem smaller?

**Comment by mikepenz** [comment]
@jekopena you can either modify the dimensions used for the PrimaryDrawerItem, or pass an icon which has more padding, or you create your own CustomDrawerItem which has a different Icon size

**Comment by jekopena** [comment]
Cool, I'll try that, thanks!
