### ISSUE TITLE
drawerItem.getName() returns "null"

### ISSUE THREAD

**Issue by enginegl** [mikepenz/MaterialDrawer#611]
Hello!
When I tried to add a primary drawer item like
```new PrimaryDrawerItem() 
.withName(R.string.drawer_item_name_profile)```
drawer item name is displayed correctly, but .getName() always returns "null": http://take.ms/2NJsT

In case of
```new PrimaryDrawerItem() 
.withName(getString(R.string.drawer_item_name_catalog))```
everything is okay: http://take.ms/ds3dC

**Comment by mikepenz** [comment]
@enginegl open the `StringHolder` variable which is shown in your screenshot. You will see the identifier value inside is set. Just the `toString()` method displays null. the StringHolder has separat methods to get the text out again

**Comment by enginegl** [comment]
StringHolder.getText(ctx) works fine, thanks!

**Comment by mikepenz** [comment]
@enginegl the StringHolder is great because it does not need a context to define the text. only when you need it to set it on a view (and a view has a context)
