### ISSUE TITLE
Can I remove the arrow right of account email??

### ISSUE THREAD

**Issue by wayne1203** [mikepenz/MaterialDrawer#615]
Thank you for your awesome work.
It's work fine with my app but I have a question about the account header.

Can I remove the arrow (Account switcher) if user have one account only?

Thank you.

**Comment by mikepenz** [comment]
@wayne1203 yes you can. 

```java
withSelectionListEnabledForSingleProfile(false)
```

**Comment by Mayank1904** [comment]
I am getting always LOGIN selectable but i am already set the property withSeleactable(false). how to show unselectable LOGIN
![screenshot_2016-02-01-12-28-59](https://cloud.githubusercontent.com/assets/16149915/12710838/61818fac-c8e0-11e5-8d29-5480d174f8dc.png)

**Comment by mikepenz** [comment]
@Mayank1904 i assume you programmatically select the first position. This will overrule the `withSelectable(false)` 

Default selection is `-1`

https://github.com/mikepenz/MaterialDrawer#how-can-i-create-a-drawer-without-a-default-selection
