### ISSUE TITLE
SwitchDrawerItem can be clicked and selected

### ISSUE THREAD

**Issue by MatteCarra** [mikepenz/MaterialDrawer#616]
SwitchDrawerItem can be clicked and selected!
I think that this isn't normal.
![cattura](https://cloud.githubusercontent.com/assets/11074527/9567297/b9d7e47e-4f25-11e5-8b71-e2ba3ecd91ff.PNG)

**Comment by mikepenz** [comment]
@MatteCarra  you can disable this: `withSelectable(false)`
