### ISSUE TITLE
Is it possible to remove circle effect on account's image?

### ISSUE THREAD

**Issue by Namolem** [mikepenz/MaterialDrawer#617]

**Comment by mikepenz** [comment]
@Namolem as of the Material Design Guidelines they should be circle. 

You can overwrite the `material_drawer_circle_mask.xml` with a rectangle mask. This will overwrite the circle effect for all images. 

for rectangle:
```xml
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <solid android:color="#000" />
</shape>
```

**Comment by Namolem** [comment]
Thanks, but it still has round shadow..

**Comment by mikepenz** [comment]
@Namolem there is now a clean solution how to do this :D

You can define a global style which will define how the BezelImageView will look for the drawer (this is included starting with v4.0.4 (v4.0.5 is now available))

```xml
<style name="BezelImageView">
        <item name="biv_maskDrawable">@drawable/material_drawer_square_mask</item>
        <item name="biv_drawCircularShadow">false</item>
        <item name="biv_selectorOnPress">@color/material_drawer_primary</item>
</style>
```

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/values/styles.xml#L28

**Comment by Namolem** [comment]
Also have a requirement to add a "Logout" button to the right of account info.
Did it by forking and rewriting your lib. Seems dirty for me. Is there any other way? 

![c545gvzaa8pejyxt](https://cloud.githubusercontent.com/assets/3646265/9629340/95ba1876-517a-11e5-9caa-2c3852a00fa5.png)

**Comment by mikepenz** [comment]
@Namolem no other solution for this. if you want it in the header. sorry. 

Else i would highly recommend to don't place it in the header. look at apps like Gmail etc. place it either in the AccountSwitcher (with the arrow down) or you can also do a normal drawerItem (SecondaryDrawerItem) with this actionl. 

Seems wrong in the header.

**Comment by Namolem** [comment]
Yes, i know. But its customer will(
Thank you

**Comment by mikepenz** [comment]
@Namolem theoretically you can also just overwrite the header layout. (copy and paste this into your application: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml keep the name as the build will automatically overwrite the same named layout from the lib)

then modify this one to your needs and add this button. just make sure that you don't remove any views. you should also be carefully if you have to change the type of a view. if you have added the button you can then use the normal drawer build the header. 

then you just get the reference to the container view of the drawer from the `AccountHeader` and you search for the view you have added. So you can add an `onClickListener`
