### ISSUE TITLE
hangs the first time it is opened ?

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/MaterialDrawer#62]
Hi, I'm testing this library, which is very good...

however, testing, I saw that the first time you open the application, the navigation drawer hangs a second before opening completely.

but the following menu openings are fluid.

Why this happens ?

thx

**Comment by mikepenz** [comment]
@seba123neo thanks. 

What phone do you use?

I can't reproduce this on my Nexus 5 or HTC One S.

Cheers.

**Comment by seba123neo** [comment]
I use a samsung galaxy s3 with android 4.3, I tested also on a samsung galaxy Y pro with android 2.3 and the problem does not occur.

I'm using the "accountswitcher" version...

another problem is that the alignment is wrong, and not shows me the icons.

![screenshot_2015-03-04-10-26-42](https://cloud.githubusercontent.com/assets/9873666/6484372/1b265c0a-c25a-11e4-89d0-296ccb9eaecc.png)

**Comment by mikepenz** [comment]
@seba123neo the problem with the icons has to be something with your drawables because 2 are working? 

it's strange that the text under the header is aligned wrong. Do you have an RTL language?

**Comment by seba123neo** [comment]
i have spanish language (i am from argentina).

in the samsung galaxy y pro (2.3) the alignment is correct, and no hangs.

i have tested in another phone, a Motorola G (Moto G) with android 4.4.4 and works perfect, no hangs in the open, the alignment is correct, and very fluid and fast, but in my phone is another story...i don't know why...

**Comment by mikepenz** [comment]
@seba123neo can you retry with a clean install on your s3? do you have a custom rom or something? 

really strange that it works on all devices but yours

**Comment by seba123neo** [comment]
I found the problem of the alignment !!!

it is because the text (name and email) is aligned to the left of the "switcher" arrow, but the arrow icon did not appear, then the text runs to the left.

i donwloaded the icons of material design from https://github.com/google/material-design-icons

but where do I put them to work the example of the library?

**Comment by seba123neo** [comment]
no, the rom is the official from samsung, I have never installed a rom on my phone.

**Comment by mikepenz** [comment]
@seba123neo no you don't have to download the icons. those are included within the library itself. 

have you added the library with the transient statement?

**Comment by seba123neo** [comment]
ok, I've solved the problem of the icons, and the problem of alignment I've solved placing these 2 lines in the xml code of the layout file material_drawer_header.xml

android:layout_marginLeft = "@dimen/material_drawer_vertical_padding"
android:layout_marginStart = "@dimen/material_drawer_vertical_padding"

I copied these two lines from the "account_header_drawer_current" (the CircularImageView above).

I do not know why it does not work without it, apparently it's some kind of bug in the version of android, because apparently ignores the padding properties "start" and "left", it's super weird ...

![screenshot_2015-03-05-01-13-00](https://cloud.githubusercontent.com/assets/9873666/6499240/885b2bf8-c2d6-11e4-9625-40d258fbafae.png)

**Comment by seba123neo** [comment]
but the "lag" in the opening persist...and it's noticeable.

I will try to make a video so you can see, it's the only way.

thanks mike !!!

**Comment by mikepenz** [comment]
@seba123neo any news about this one. were you able to hunt it down? it seems kinda strange because the only idea i got for it to hang is that it processes something in the background. but nothing is done at this position in my code. have you added any processing?

**Comment by seba123neo** [comment]
I have not set any line, I have not added anything to the sample project.

I made this video, check please...

http://1drv.ms/1CD8t1C

You can see how it hangs for a second while opening...

**Comment by seba123neo** [comment]
6 years since I work as a developer of android in a company, and I see android phones all the time, and I find it strange what is happening, I do not believe it's my phone, hopefully someone with a galaxy S3 can try it too.

**Comment by mikepenz** [comment]
@seba123neo omg the lag is really bad :/ 

can you try to remove all items and the account header step by step and see when it stops to have such a lag?

i have no lag at all on my Nexus 5, Nexus 7 and just a tiny one on my HTC Desire S (which basically lags for everything xD)  
But the lag on the Galaxy S3 is to much...

I hope someone else can also test, and/or someone has the solution for this.

**Comment by mikepenz** [comment]
@seba123neo can you try the newest PREVIEW and try to remove the ActionBarDrawerToggle? (Which is in fact the only code running at this time (which is handled by me))

**Comment by seba123neo** [comment]
ok, now I'll try, I've tested on a Tablet Samsung Galaxy Tab 4 and works perfect, I can not believe it works on a mid-range phone as galaxy y pro, and not work on mine...

**Comment by seba123neo** [comment]
Well, finally I could try and see what is really causing the problem !!!

I downloaded the latest version PREVIEW an the Android-Iconics...

the alignment is now well, but the lag problem persist, then I started commenting lines of code to identify the problem.

i create a empty navigation drawer with this:

```javascript
result = new Drawer().withActivity(this).build();
```

with this, works perfect, no lag, no problem...

then i add the items:
```javascript
.addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.drawer_item_action_bar).withIcon(FontAwesome.Icon.faw_home).withIdentifier(1).withCheckable(false),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_multi_drawer).withIcon(FontAwesome.Icon.faw_gamepad).withIdentifier(2).withCheckable(false),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_non_translucent_status_drawer).withIcon(FontAwesome.Icon.faw_eye).withIdentifier(3).withCheckable(false),
                        new SectionDrawerItem().withName(R.string.drawer_item_section_header),
                        new SecondaryDrawerItem().withName(R.string.drawer_item_settings).withIcon(FontAwesome.Icon.faw_cog).withIdentifier(5).withTextColor(Color.RED),
                        new SecondaryDrawerItem().withName(R.string.drawer_item_help).withIcon(FontAwesome.Icon.faw_question).setEnabled(false),
                        new SecondaryDrawerItem().withName(R.string.drawer_item_open_source).withIcon(FontAwesome.Icon.faw_github).withIdentifier(4).withCheckable(false),
                        new SecondaryDrawerItem().withName(R.string.drawer_item_contact).withIcon(GoogleMaterial.Icon.gmd_format_color_fill).withTag("Bullhorn")
                )
```

with this works perfect too, no lag, fast and fluid...

and finally add the header with the line:

```javascript
.withAccountHeader(headerResult)
```

the lag APPEARS with this line !!!

and the lag is even more noticeable when opened after having selected a circularImageview, otherwise the lag disappears. is a redraw problem or something...

**Comment by seba123neo** [comment]
yes, definitely the problem occurs after you select a circularimageview, otherwise works perfectly !!!

**Comment by seba123neo** [comment]
i commented the click event in the activity for the header, "withOnAccountHeaderClickListener" an the lag dissapears completely !!!

**Comment by mikepenz** [comment]
@seba123neo i had the chance to test it on a Galaxy S3 in our company. It's definitely a SAMSUNG bug. 

I see following log entries (This is a single open and close cycle):
```
03-06 08:38:10.349  13559-13559/com.mikepenz.materialdrawer.app D/AbsListView﹕ onVisibilityChanged() is called, visibility : 0
03-06 08:38:10.349  13559-13559/com.mikepenz.materialdrawer.app D/AbsListView﹕ unregisterIRListener() is called
03-06 08:38:10.364  13559-13559/com.mikepenz.materialdrawer.app D/AbsListView﹕ unregisterIRListener() is called
03-06 08:38:15.004  13559-13559/com.mikepenz.materialdrawer.app I/CircularImageView﹕ Bitmap drawable!
03-06 08:38:15.004  13559-13559/com.mikepenz.materialdrawer.app I/CircularImageView﹕ Bitmap drawable!
03-06 08:38:15.004  13559-13559/com.mikepenz.materialdrawer.app I/CircularImageView﹕ Bitmap drawable!
03-06 08:38:15.019  13559-13559/com.mikepenz.materialdrawer.app D/AbsListView﹕ unregisterIRListener() is called
03-06 08:38:15.614  13559-13559/com.mikepenz.materialdrawer.app D/AbsListView﹕ onVisibilityChanged() is called, visibility : 4
03-06 08:38:15.614  13559-13559/com.mikepenz.materialdrawer.app D/AbsListView﹕ unregisterIRListener() is called
03-06 08:38:15.634  13559-13559/com.mikepenz.materialdrawer.app D/AbsListView﹕ unregisterIRListener() is called
```

The lag appears only if following log outputs are not yet shown
```
03-06 08:41:11.799  13559-13559/com.mikepenz.materialdrawer.app D/AbsListView﹕ onVisibilityChanged() is called, visibility : 4
03-06 08:41:11.799  13559-13559/com.mikepenz.materialdrawer.app D/AbsListView﹕ unregisterIRListener() is called
03-06 08:41:11.819  13559-13559/com.mikepenz.materialdrawer.app D/AbsListView﹕ unregisterIRListener() is called
```

If you try it on your device you will see that the lag does not appear if you wait 1-2 seconds before opening the drawer again.

**Comment by mikepenz** [comment]
@seba123neo i think i found the root cause. :D I don't know why this only happens on Samsung Devices with specific Factory Android versions but yeah. Just take it as is. 

In the sample app i use following `onProfileClick` method:
```java
@Override
public void onProfileClick(View view, IProfile profile) {
  Toast.makeText(SimpleDrawerActivity.this, profile.getName(), Toast.LENGTH_SHORT).show();
}
```

If you remove the Toast there will be no more lag
```java
@Override
public void onProfileClick(View view, IProfile profile) {
  
}
```

**Comment by seba123neo** [comment]
Excellent, now we know what the problem was, so easy ..

Thanks for your time !!!

**Comment by sweetdream0729** [comment]
Hi,

Great library.
But After I click profile image or select account multiple times, it is getting lags.
Side menu seems to get bad performance after click account multiple times.
Please help me with this issue.
Thanks.

**Comment by mikepenz** [comment]
@sweetdream0729 can you reproduce this with the sample?
