### ISSUE TITLE
Delay OnDrawerItemClickListener

### ISSUE THREAD

**Issue by MedoElkamaly** [mikepenz/MaterialDrawer#620]
First thanks so much for this great library.
My question is: is there is a way to close the drawer first then open the activity on an item click?

**Comment by echthard** [comment]
Or close the drawer smoothly, because sometimes when fragment loading takes some time or resources, not sure what the reason is at the moment. Then the drawer will close with .. uhhm .. "hik ups" (not smoothly).

**Comment by mikepenz** [comment]
@MedoElkamaly there is the implementation to delay the closing of the drawer. you can also define the delay. 

If you want it the other way around you should set the delay to 0 and then handle the delay on your own. with a handler or in a similar way

**Comment by sweetdream0729** [comment]
Thanks for this support.
In my app, fragment loading takes a bit delays, so closing drawer has been taking hang, so not smooth.
Please help me with this issue.
