### ISSUE TITLE
Documentation on how to implement MiniDrawer?

### ISSUE THREAD

**Issue by FWest98** [mikepenz/MaterialDrawer#621]
It would be nice to have some documentation on how to implement the MiniDrawer. At the moment the example code also uses some classes I don't have in my project because it's importing crossfader....
Also it doesn't show things like:
- Minidrawer only on tablets
- Hide on backpress
- Normal drawer still as overlay so content doesn't move
- Co-operation with actionbardrawertoggle

**Comment by mikepenz** [comment]
@FWest98 it requires the `Crossfader`

* Only on tablets that's up to you no limitation from my side.
* you can use the `Crossfader` and just crossfade
* Normal drawer still as overlay will require some custom code from your. it's possible but no default behavior
* working with ActionbarDrawerToggle is not required from my side as you can just hook in the methods via the normal `Drawer` by providing a custom listener.
