### ISSUE TITLE
Update profile doesn't work

### ISSUE THREAD

**Issue by Ne1c** [mikepenz/MaterialDrawer#622]
Update profile doen't work. I try change profile in this manner:
```java
mAccountHeader.getActiveProfile().withName("New name");
mAccountHeader.updateProfileByIdentifier(mAccountHeader.getActiveProfile());
```
And this:
```java
mAccountHeader.getProfiles().get(0).withName("New name");
mAccountHeader.updateProfileByIdentifier(mAccountHeader.getProfiles().get(0));
```

But it still does not work.

**Comment by mikepenz** [comment]
@Ne1c have you defined an identifier for the Profile? Just keep a reference to the object you pass to the AccountHeader and then change the name. and then update it via the identifier

**Comment by Ne1c** [comment]
I created `IProfile mMainProfile = new ProfileDrawerItem();`
And i try used method setActiveProfile(mMainProfile) and try change profile, but it doesn't work.

**Comment by mikepenz** [comment]
First you should define an identifier for the profile. and then you can set the profile as active profile. but you can't just set a new profile as active one. see the sample app for this.
