### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by simonckenyon** [mikepenz/MaterialDrawer#623]
this is *not* a criticism, it is an offer of help.

i look at every issue that is raised. about 80-90% of them could be resolved with some (dare i say it) better documentation. this is a very good piece of software, but i do think it is let down by the documentation.

for me, the best way to tackle something like this is to agree on the table of contents. with that in place, the structure could be implemented in the wiki, with a placeholder in each section saying what the section should contain. then people who want to contribute can place content in these sections.
furthermore, questions and answers that have already been provided can be used as a starting point.

now writing documentation is probably my least favourite thing to do. but i am willing to help.

**Comment by mikepenz** [comment]
@simonckenyon i know. and i see that the basic documentation only contains features/stuff which i would describe as "basic" functionality.

The bad thing about this is that i spend a lot of time already implementing and fixing and answering this library, creating and keeping a documentation up 2 date would require an additional huge amount of work. 
The main issue i do not understand is that people do not read code. I already provide a sample application which contains 70% of all features (or similar features which only differ by position or so) and people still do not try the sample app or do not read the sample app.
Additionally i tried to provide method names which describe what the method will do. So why don't devs just look for methods which are available? I always do this if i'm searching something. 
As a third thing. This is open source. People can just check the source itself. Which is never a bad thing. 


Yeah i know those things are no excuse that it would be easier to provide a complete documentation. But i prefer to provide a great library :D


and sorry. i know this is no real answer to the main suggestion :D and i'm really thankful that you would help with that.

**Comment by AngleV** [comment]
as @mikepenz  allready stated i prefer a great library as this one rather than a complete documentation for a lib with a lot of flaws.

@mikepenz  You can count me in for any help you might need to build up the documentation.
Just in case.
Also this is good change to give you my best compliments for this great lib of yours. But the most important thing its not the lib but your fast support even though its all about open source.
Well Done mate and keep coding  !!!

**Comment by RubenGees** [comment]
I would also like to help with this. It is a great library and I think there are many people (like me) who want to contribute something back for the amazing work you did here. 

I agree with @simonckenyon that we need to discuss some table of contents for the things which are not mentioned in the README, add a stubbed topic for them in the wiki and people could start to write Articles for it. 

Topics could be:

Methods of DrawerBuilder with like 2 lines of text, explaining what the method does, like I did in [my Library](https://github.com/RubenGees/Introduction/wiki/IntroductionBuilder) for example.

Same for Drawer items. maybe explain the differences between the types of DrawerItems with small images or something.

We could also prevent some questions I have seen with topics for them:

How to implement the onBackPressedListener?, How to use the identiefier to block double calls on the same DrawerItem, ...

So @mikepenz if you could come up with a small table of contents I and other could start to write! :D

**Comment by Anatidae-Project** [comment]
I'll lend a hand with docs and sample code too. I'm currently building out an interesting drawer injection using Dagger 2.0. I'd like to add that to the knowledgesphere for example.

**Comment by mikepenz** [comment]
I've set up a new site which will host some FAQs and other resources. this can be managed and improved by all of you just by creating pull requests

https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md

**Comment by Berlon** [comment]
Mike,
Sorry if this is not the right place to ask this. But, how do I change the description text properties for the drawer items. For example, color and size?

**Comment by mikepenz** [comment]
Colors: https://github.com/mikepenz/MaterialDrawer#custom-colors---colorsxml
Size: overwrite the dimension, or create a custom `DrawerItem`

**Comment by Berlon** [comment]
Thanks Mike. I was able to change the size. But was unable to get the color
chaned for the description on the primary drawer item.

**Comment by mikepenz** [comment]
@Berlon there is also a method to change the color of the description: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BasePrimaryDrawerItem.java#L37

**Comment by Berlon** [comment]
Thanks again Mike, this did help. However, when using the method for
withDescription, the text is considered primary text and all the text is
colored the same. I am hoping to change the text like this.

Some Primary Text <-- Title of action (normal white color)
Primary Text Description <-- Description of action (disabled gray)

Possibly, I can change the text color at the layout.

**Comment by mikepenz** [comment]
@Berlon the description color should only the description text. or what do you mean? can you add a screenshot?

**Comment by Berlon** [comment]
Thanks once again Mike for taking the time to assist me. Below is a screen
shot of what I am trying to accomplish.

[image: Inline image 1]

**Comment by mikepenz** [comment]
@Berlon image not working

**Comment by Berlon** [comment]
Try this Mike.

**Comment by mikepenz** [comment]
@Berlon i think you should answer via github not via e-mail

**Comment by Berlon** [comment]
Sure Thing Mike,
![mike penz screenshot](https://cloud.githubusercontent.com/assets/5912418/11376907/81dcafc8-92a0-11e5-9f36-64370d41749e.png)

**Comment by mikepenz** [comment]
@Berlon 
```java
.withDescriptionTextColor(Color.RED)
```
will only change the description color. 

![screenshot_20151124-205808](https://cloud.githubusercontent.com/assets/1476232/11378959/2c51b51e-92ee-11e5-8906-acd35de2ee93.png)

**Comment by justjanne** [comment]
Sorry to ask, but your samples don’t cover it, and there doesn’t seem to be any documentation on it: Is there a (simple) way to display a RecyclerView of expandable elements, which can change at runtime, in your drawer?

Effectively, I’d have a list of items, each having a list of children, both top-level and child-level items may be added or removed at runtime (and would trigger the notifyItemAdded etc), and the drawer would display them in a simple way?

**Comment by mikepenz** [comment]
@justjanne at the moment the only solution is the following:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L186
Dynamically add and remove the sub items. 

I am working on v5.0.0 right now which will switch to the `FastAdapter` (https://github.com/mikepenz/FastAdapter) as new `Adapter` which will provide `expandable` items by default. (the current beta doesn't include it yet).

**Comment by justjanne** [comment]
As I’m dealing with 1-10 top-level and up to a few hundred lower level items, the first option doesn’t seem very performant :/

Is there a rough ETA on when 5.0 is going to be in a workable state (A few weeks? Months? End of the year?)

**Comment by mikepenz** [comment]
@justjanne the first solution is performant. as the adapter will care about properly animating the new items. the v5.0.0 will more or less do the same. Telling the adapter that he has to animate the new items, which are the sub-level. The big advantage of this is that we depend on Android core apis which allow us to animate, cache items, ...

So v5.0.0 without the expandable items is already now in a workable state. (still in beta). My plan would be that i bring out a pretty stable version sometimes later this weekend. and a final version by the end of next week. Thats just an estimate though and i can't promise, if i can deliver if there are any problems i do not know about yet.

**Comment by justjanne** [comment]
@mikepenz Ah, okay. That time scale makes it easy enough that I can just wait for your library – I’ve been working on this project since November, and don’t have a deadline, so a few weeks more won’t be an issue.

Thank you a lot! :+1:

**Comment by mikepenz** [comment]
@justjanne the latest snapshot of the v5.0.0 now contains the collapsible functionality
you can test it here https://github.com/mikepenz/MaterialDrawer/issues/920

**Comment by justjanne** [comment]
@mikepenz That’s all very nice, but it doesn’t work that well for me: the constructor DrawerBuild() already sets mAdapter, so I can’t replace the mAdapter using withAdapter at any future point.

My aim was to supply my own adapter.

**Comment by mikepenz** [comment]
@justjanne why whould you need to use your adapter? many features only work because of the used adapter inside the `Drawer`

**Comment by justjanne** [comment]
@mikepenz Well, it’s probably going to work like this, too, it’s just not that nice. Anyway, currently I’ve found a bug: For the nth parent item, if you expand and collapse, it will copy the last item of the subitems n times.

**Comment by mikepenz** [comment]
@justjanne could you please provide the code snippet which "copies" the last item of the subitems n times?

**Comment by justjanne** [comment]
@mikepenz I moved it into its own issue, #926

**Comment by mikepenz** [comment]
Perhaps related to this issue. There is a service which allows you to automatically fetch the latest javadoc from the released library versions: http://www.javadoc.io/doc/com.mikepenz/materialdrawer/4.6.4 (just replace the later with the latest versoin)

**Comment by justjanne** [comment]
@mikepenz Another question, again.

If I wish to change the child elements of a ParentItem, what’d be the best way to do so (and notify the drawer about it)?

The solution other expandable-recyclerview implementations have is that each parentelement has a notifyChildItemInserted, notifyChildItemChanged, etc. Or should I just modify the list and do adapter.notifyItemChanged(idOfParentElementToWhichIAddedAChild)?

**Comment by justjanne** [comment]
Ah, that question resolved itself. Sorry.

**Comment by mikepenz** [comment]
Close as this is an always relevant topic.

**Comment by stoutj** [comment]
@mikepenz Maybe I am just missing it, but a link to the sample app at the top of your ReadMe would help out a lot.  I see you reference the sample app in a lot of your responses but where to find it?

**Comment by mikepenz** [comment]
In this repo :D in the folder `app` 
https://github.com/mikepenz/MaterialDrawer/tree/develop/app

I don't think there is a link needed :D

**Comment by stoutj** [comment]
Thanks for providing the link.  I wrongfully assumed that was the code for your library.
