### ISSUE TITLE
NavigationBar and Full Screen in landscape mode

### ISSUE THREAD

**Issue by bmelnychuk** [mikepenz/MaterialDrawer#624]
I want to hide status bar and navigation bar in my activity. Also I want to have drawer there. Everything works fine in portrait mode. But after rotation to landscape this blue line appears(see attached screenshot). I believe this is margin or padding. Do you have any ideas where it comes from?
And if I remove drawer everything works fine.
Thank you for great library!
![drawer_landscape](https://cloud.githubusercontent.com/assets/4201475/9698374/8dc36738-53bb-11e5-87c3-801dec99398b.png)

**Comment by mikepenz** [comment]
@bmelnychuk have you enabled fullscreen view like shown in the fullscreen activity?

**Comment by bmelnychuk** [comment]
yes, I enabled full screen. In your sample app navigation bar (the one on bottom) is transparent in portrait mode, in landscape mode (it appears on right side) it's just there. So I tried to hide it, and get this blue line instead. 
Thanks for quick response

**Comment by mikepenz** [comment]
@bmelnychuk there is now a new method to handle this

`withSystemUIHidden(true)`
