### ISSUE TITLE
MiniDrawer with 'animated hamburger to arrow'

### ISSUE THREAD

**Issue by jacobhub** [mikepenz/MaterialDrawer#629]
Hi , is it possible to use the MiniDrawer with an animated 'hamburger to arrow'  icon in action bar ?

**Comment by mikepenz** [comment]
@jacobhub you can do this. But you will have to handle the logic for the `ActionBarDrawerToggle` on your side.

**Comment by jacobhub** [comment]
ok, but how ?  I tried changing the MiniDrawer example to show an hamburger icon but with no luck. do you have an example somewhere ?
btw, great library .

**Comment by mikepenz** [comment]
You will have to add the `ActionBarDrawerToggle` to the toolbar and hook to it with listeners. I do not know exactly if this works because this is out of scope of this library.

**Comment by jacobhub** [comment]
I am trying to add ActionBarDrawerToggle but that requires a DrawerLayout but result.getDrawerLayout(); returns null, any idea how to solve this ?

**Comment by mikepenz** [comment]
@jacobhub makes sense that the `result.getDrawerLayout()` returns `null` as there is no `DrawerLayout` in this case. we only create the view and display it with the `Crossfader` 

I assume you have to go with something like this: https://github.com/balysv/material-menu
You are right `ActionBarDrawerToggle` is just used with a `DrawerLayout`
