### ISSUE TITLE
Problem with shadow transparency on devices with android < 5.0

### ISSUE THREAD

**Issue by wildfatduck** [mikepenz/MaterialDrawer#63]
When using MaterialDrawerTheme.* as parent in application style, shadows under context menus, dialogs is not transparent. This happens only on android < 5.0.
Example: https://www.dropbox.com/s/cpimmk2s9j5mlgn/device-2015-03-04-132811.png?dl=0

**Comment by mikepenz** [comment]
@wildfatduck do you use the version v1.0.2?
I've changed something regarding this in the preview v1.5.0 can you please test if it works there?

https://github.com/mikepenz/MaterialDrawer/issues/36#issuecomment-77055895

Thanks

**Comment by wildfatduck** [comment]
@mikepenz yes, I'am using 1.0.2
Tested preview v1.5.0 , progress dialog now wider, and looks like in Theme.AppCompat.*, but problem with shadows is not fixed

**Comment by mikepenz** [comment]
@wildfatduck thanks for testing. will try to test and reproduce it at home today.

**Comment by khammami** [comment]
@mikepenz same bug here on nexus s

**Comment by mikepenz** [comment]
Ok was able to reproduce it. Will be fixed in the next public version. I hope i can release it today or tomorrow.

**Comment by mikepenz** [comment]
@wildfatduck @khammami this one is fixed in the newest PREVIEW version. 
https://github.com/mikepenz/MaterialDrawer/issues/36#issuecomment-77248361

if there are no new issues i'll probably release it to the public tomorrow.

**Comment by wildfatduck** [comment]
@mikepenz tested PREVIEW.5, shadows issue fixed. Great!
Thanks for your awesome lib!

**Comment by mikepenz** [comment]
will be fixed in v2.0.0
