### ISSUE TITLE
Account header toggle state not saved

### ISSUE THREAD

**Issue by rabyunghwa** [mikepenz/MaterialDrawer#630]
If I have toggled the account list, which shows a drop down list of various accounts, and then I change the device orientation, the account list toggle state would not be properly restored, in which case, the account list is not collapsed. 
![device-2015-09-08-180605](https://cloud.githubusercontent.com/assets/7411385/9732262/0d1784a6-5655-11e5-8038-f44d91e52c5a.png)
![device-2015-09-08-180625](https://cloud.githubusercontent.com/assets/7411385/9732263/0ef44a2a-5655-11e5-8eeb-0b5d21f89530.png)

**Comment by mikepenz** [comment]
Ah i see the issue only happens if you rotate the screen but you had opened the account list

**Comment by rabyunghwa** [comment]
Yes dude. What I did was: first in AccountHeader class  of the library module, add a global constant value 'protected static final String BUNDLE_SELECTION_LIST_SHOWN = "bundle_section_list_shown"', and then down in the onSaveInstance(), save that value as well. 


public Bundle saveInstanceState(Bundle savedInstanceState) {
            if (savedInstanceState != null) {
            savedInstanceState.putInt(BUNDLE_SELECTION_HEADER, mAccountHeaderBuilder.getCurrentSelection());

            savedInstanceState.putBoolean(BUNDLE_SELECTION_LIST_SHOWN, mAccountHeaderBuilder.ismSelectionListShown());

            Log.i("Account Header", "saveInstanceState: selection list shown? " + mAccountHeaderBuilder.ismSelectionListShown());
        }
        return savedInstanceState;
    }
