### ISSUE TITLE
How to listen on profile image click?

### ISSUE THREAD

**Issue by biokys** [mikepenz/MaterialDrawer#631]

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#add-profiles-and-an-accountheader

This will be triggered when a new profile is selected

```java
.withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
        @Override
        public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
            return false;
        }
    })
```

**Comment by biokys** [comment]
But I meant how to find out, that user clicked on user image in navigation header. Not in list of profiles.

**Comment by biokys** [comment]
Sorry, it is working... my fault!

**Comment by mikepenz** [comment]
no problem ;)

**Comment by jerh-remy** [comment]
> Sorry, it is working... my fault!

How did you get it work please?
