### ISSUE TITLE
How use minidrawer ?

### ISSUE THREAD

**Issue by fernandodeveloper** [mikepenz/MaterialDrawer#632]
I try use with example, but this version of example is outdated

**Comment by mikepenz** [comment]
@fernandodeveloper the version of the example is never outdated :D as the sample app is kept in sync with the newest MaterialDrawer version.

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java

**Comment by fernandodeveloper** [comment]
I update again to 4.0.7 but required 23.0.1  (support, design, recycle...) ? You use preview channel?

**Comment by mikepenz** [comment]
@fernandodeveloper v23.0.1 is already on the stable version

**Comment by fernandodeveloper** [comment]
@mikepenz  in my ADT dont show to download 23.0.1 only 23.0.0 i, try download manualy.... 

Thanks for all, nice work!!

**Comment by mikepenz** [comment]
ok great
