### ISSUE TITLE
Disobedient icons.

### ISSUE THREAD

**Issue by Saime1942** [mikepenz/MaterialDrawer#638]
When icons are set through withIcon(int iconRes), they do not fade out when Item is disabled.
It works ok when set through withIcon(IIcon iicon).

**Comment by mikepenz** [comment]
@Saime1942 what do you mean with fade out? if you want drawables to be tinted you have to activate this with `withIconTintingEnabled(true)` or you provide a colored icon

**Comment by Saime1942** [comment]
@mikepenz I meant this:

![screenshot_2015-09-11-07-39-36](https://cloud.githubusercontent.com/assets/14172737/9806338/a49d77fe-5858-11e5-9ba1-78721689fcf1.png)

And yes, `withIconTintingEnabled(true)` fixed that.
Sorry for interruption.
