### ISSUE TITLE
customize header with withHeader() can not use my height size

### ISSUE THREAD

**Issue by mooncafes** [mikepenz/MaterialDrawer#639]
hi, when i use my height size in my custom header view and set it to drawer with withHeader() method,
i find a problem that the header view always with a fixed size.

**Comment by mikepenz** [comment]
@mooncafes you also have to provide the height to the header, otherwise it will calculate the correct height for a normal header.

you can use this method `withHeightDp`

**Comment by mooncafes** [comment]
i notice the withHeightDp method you metioned above only used in AccountHeaderBuilder and withAccountHeader(int layout) must requires the same structure as the drawer.xml, but i want to customize a view in DrawerBuilder with withStickyHeader method because of the diffirence between the structure of mine and yours.

It may be that I am not said clear on the above, in fact, I want to use withStickyHeader() method to customize a view with layout.xml in xx dp size.  However, the size of the inflated header view  in Drawer looks like used a constant size whatever i change the size.
