### ISSUE TITLE
setStatusBarColor() stop changing color when call build() method again

### ISSUE THREAD

**Issue by biokys** [mikepenz/MaterialDrawer#640]
If I call build() method on DrawerBuilder and than call setStatusBarColor() on result instance, status bar changes color. But when I call build() method again (because i need to redraw all the drawer content with different data), setStatusBarColor() don't work. Any help?

**Comment by mikepenz** [comment]
@biokys you must not call `.build()` more than once in an `activity`. just one time during creation of the view. afterwards you should modify the items of the `Drawer` object you retrieve from the `.build()` method. please see the README for more details
