### ISSUE TITLE
Question: Highlight selected row in recyclerview API 10

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/MaterialDrawer#641]
testing the new version, I realized that the list (recyclerview) is not highlighting when select a option in API 10, It is confusing because it means not known which option was selected.

in the same device, the options of the navigation drawer of google play app, highlighting well.

**Comment by mikepenz** [comment]
@seba123neo i know that this does not work, but the states which i use to keep the selection does not exist with API 10. As i am thinking of moving up to API 14+ it was fine for me ignoring this case as 10+ isn't as popular anymore. everything else is working. 

If you have an easy fix without breaking all the great things for 14+ let me know ;)
