### ISSUE TITLE
Drawer open lag

### ISSUE THREAD

**Issue by AngleV** [mikepenz/MaterialDrawer#642]
In a Samsung Galaxy S6 with 5.1.1 the first time drawer opens up has a small lag.The second time its smoothly as perfect.
Any idea?

**Comment by mikepenz** [comment]
@AngleV do you have any big ressources in your drawer or images?

**Comment by AngleV** [comment]
i got a custom header with a resource image of 53.7 kb ?

**Comment by mikepenz** [comment]
@AngleV no seems small enough

**Comment by AngleV** [comment]
@mikepenz 

Test it without the StickyHeader. The issue remains !!!

**Comment by mikepenz** [comment]
@AngleV yeah as mentiond the images is small enough. i will have to do some tests what could cause this on your side. You use Iconics Drawables or normal drawables?

**Comment by AngleV** [comment]
@mikepenz 

 .withIcon(FontAwesome.Icon.faw_star);

**Comment by mikepenz** [comment]
With some more debugging the only cause i've found for this is, when using many different types of DrawerItems so it can't use the ViewHolder pattern very effectively. The longer the list, the more different items the slower it will get on the first scroll as it has to create all different types of views. after this it can reuse those. 

So i can't do anything about this. the only thing i found which (perhaps) somehow improves is to call invalidate after creating the AccountHeader, but this won't resolve everything. 

What's your usecase? How many different (in terms of type (Primary, Secondary, Divider, ...) DrawerItems to you have?

**Comment by AngleV** [comment]
@mikepenz 

Report Feedback
with latest release the first opening lag has vanished.
Good job !

**Comment by mikepenz** [comment]
Thanks ;).

**Comment by mikepenz** [comment]
@AngleV i just updated to v4.1.1 please also update to this version.

the 
```java
setHasStableIds(true)
```

i added to the adapter is causing some troubles. i removed it again. the lag is still fixed with the cache.

**Comment by AngleV** [comment]
@mikepenz 
great !

**Comment by nalmada** [comment]
Hi, 
I'm in the same situation  : drawer is laggy at the first opening.
Removing the ```AccountHeaderBuilder.withHeaderBackground()``` call , make the first opening smooth again.
But my drawable is only 3 KB.

I'm on a Nexus 6 (5.1.1) and using the version 4.4.8 of the library

**Comment by mikepenz** [comment]
@nalmada what's the size (resolution) of that image? where do you load it from?

**Comment by nalmada** [comment]
@mikepenz It's a 797x797 .png file , loaded from res

**Comment by mikepenz** [comment]
@nalmada try to change to a .jpg. Loaded from res should be fine

**Comment by nalmada** [comment]
@mikepenz  changing the resolution worked
thanks
