### ISSUE TITLE
Beginner's problem about ActionBarDrawerToggle

### ISSUE THREAD

**Issue by TYZRPVX** [mikepenz/MaterialDrawer#643]
I want to get the effect "Switching between Back-Arrow or Hamburger-Icon", what I think is to new an `ActionBarDrawerToggle`, but new an `ActionBarDrawerToggle` requires `DrawerLayout`.
I write `mLayout = (DrawerLayout) findViewById(R.id.material_drawer_layout); `in `onCreate()`.
while this throw a NullPointerException, how to fix this problem?

**Comment by mikepenz** [comment]
I can't give support for the `ActionBarDrawerToggle` as this is android specific and not MaterialDrawer specific. but i think you should be able to find everything you need in the sample applicaitons -> `CustomContainerActivity`
