### ISSUE TITLE
Please Help!

### ISSUE THREAD

**Issue by RealFeeling** [mikepenz/MaterialDrawer#644]
Sorry, I really don't know how to use this code. Could you just tell me the every step . ths so much

**Comment by agungsijawir** [comment]
you can start by reading Setup section [here](https://github.com/mikepenz/MaterialDrawer#setup) and open sample application in `app` folder and learn some sample code from there.

**Comment by mikepenz** [comment]
http://developer.android.com/training/basics/firstapp/index.html
