### ISSUE TITLE
Drawer under ActionBar

### ISSUE THREAD

**Issue by zatziky** [mikepenz/MaterialDrawer#645]
Hello Mike,

great work u've done, thank you!

I have got one question though, is it possible to achieve something like this with your library?

![image](https://cloud.githubusercontent.com/assets/2794365/9833342/8a721ff6-5993-11e5-9952-378d0509652c.png)

I need to keep the actionbar visible. Is it possible? I also created a question on SO -http://stackoverflow.com/questions/32542766/visible-actionbar-with-opened-navdrawer

Thank you,
Zat

**Comment by mikepenz** [comment]
@zatziky you mean the drawer below the ActionBar / Toolbar?

See the sample application. There is the CustomContainerActivity

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java

**Comment by zatziky** [comment]
@mikepenz Maybe. I will try and let you know. Thx!

**Comment by mikepenz** [comment]
it will produce the following:

![screenshot_2015-09-12-21-28-22](https://cloud.githubusercontent.com/assets/1476232/9833403/94fdb136-5995-11e5-8e8a-fc4dc06a61eb.png)

**Comment by zatziky** [comment]
That was it. Now it is working. Thank you!
