### ISSUE TITLE
drawer item typeface?

### ISSUE THREAD

**Issue by TheLoyalCruel** [mikepenz/MaterialDrawer#647]
hi...
how to change drawer item text font (typeface)?
thanks :)

**Comment by mikepenz** [comment]
@TheLoyalCruel either you create your own custom DrawerItem, or you overwrite the xml layout (if it's just about the style) or you hook in an `OnPostBindView` listener to modify the created view via the `withPostOnBindViewListener` method.

**Comment by TheLoyalCruel** [comment]
thanks... but is there any sample on this?

**Comment by TheLoyalCruel** [comment]
I used this: 
.withTypeface(Typeface.createFromAsset(getAssets(),"fonts/sample_font"))
but I dont know how to work with "withPostOnBindViewListener" method!

another question is about text size?
