### ISSUE TITLE
/Users/dinus/Documents/workspace/AndroidDemo/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.1/res/values-v23/values-v23.xml

### ISSUE THREAD

**Issue by caixuejian** [mikepenz/MaterialDrawer#648]
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(1) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

**Comment by mikepenz** [comment]
http://stackoverflow.com/questions/32402939/error-in-resolving-dependecies-while-using-mikepenz-materialdrawer-library
