### ISSUE TITLE
Touch/ScaleGesture events interception

### ISSUE THREAD

**Issue by juaagugui** [mikepenz/MaterialDrawer#651]
I love this library, it's the easiest, most brilliant and the smartest way of implementing and using navigation drawer menus.

No problem until some hours ago. I have a a fullscreen application and I need to capture the scale gesture in order to be able to zoom a view.

When I attach the menu, it seems like the `DrawerLayout` intercepts the calls and "zoom event" is not called.

I put a break point in `onInterceptTouchEvent(MotionEvent ev)`  method of `DrawerLayout` and the execution stopped, what made me think I was right.

It could be interesting to have a way for writing custom listeners, or overriding this method in case we want (sorry if it's already done... I haven't found it).

I've made a workaround for my case. Due to I want to capture "zoom event", I need 2 pointers for making the gesture so I used this constraint for intercepting the event in the activity and, on the other cases (single pointer or more than 2), delegate to super implementation.

```java
@Override
public boolean dispatchTouchEvent(MotionEvent ev) {
   if(ev.getPointerCount ()==2){
    return myCustomZoomListenerMethod(ev);
   }else{
    return super.dispatchTouchEvent(ev);
   }
}
```

**Comment by mikepenz** [comment]
Thanks for the detailed report and description. The `MaterialDrawer` does not overwrite the `DrawerLayout` so it seems to be a `DrawerLayout` specific issue. 

Theoretically it's possible to pass your own `DrawerLayout` implementation to the `DrawerBuilder` and use this one. Note the provided layout must follow the same structure as the `MaterialDrawer` intern one.

**Comment by chteuchteu** [comment]
Hi @mikepenz! You said that 

> Theoretically it's possible to pass your own DrawerLayout implementation to the DrawerBuilder and use this one

Could you explain how to do it?
