### ISSUE TITLE
Drawer items view

### ISSUE THREAD

**Issue by ray1984** [mikepenz/MaterialDrawer#654]
How can I increase left padding of drawer items and space between items?

**Comment by ray1984** [comment]
Also, I need show some views in full width, but I can't (in screenshot it must be divider and red line)
![screenshot_2015-09-15-16-56-27](https://cloud.githubusercontent.com/assets/3238570/9876939/6ff4f140-5bc2-11e5-863f-6e2e2d2eda07.png)

**Comment by ray1984** [comment]
Ok, when I use sticky footer without sticky drawer items all is good. But when I add sticky items, sticky footer disappears
![screenshot_2015-09-16-10-41-34](https://cloud.githubusercontent.com/assets/3238570/9898035/7e6d39b8-5c57-11e5-815d-cbfc322fe139.png)
![screenshot_2015-09-16-10-42-34](https://cloud.githubusercontent.com/assets/3238570/9898036/83a557ee-5c57-11e5-89dc-dcd1867d3a41.png)

**Comment by ray1984** [comment]
I just override material_drawer_vertical_padding to 0dp and override drawer items

**Comment by mikepenz** [comment]
@ray1984 ok good that it's working for you now.
