### ISSUE TITLE
drawer item icon at right of text

### ISSUE THREAD

**Issue by softweng** [mikepenz/MaterialDrawer#656]
hi, tnx for great library, how to place drawer item icons at right of text? i use  this library in rtl language and icon must be at right of text.

**Comment by AngleV** [comment]
@softweng you can use a custom drawer item to achieve what you want !

**Comment by softweng** [comment]
@AngleV tnx , I am a beginner, how do customeit.

**Comment by mikepenz** [comment]
@softweng http://stackoverflow.com/a/31053201/325479
