### ISSUE TITLE
Text on Right side of Image Profile

### ISSUE THREAD

**Issue by yodeski** [mikepenz/MaterialDrawer#659]
It is possible to insert a TextView on the right side of Image Profile?
Like this: https://drive.google.com/file/d/0B9S-cMUlMxGvSVBuc1JTUEw3N2s/view?usp=sharing

**Comment by mikepenz** [comment]
@yodeski yes it is possible. and i think someone already did such a heavy modification. but it will require you to hook in a bit more deeply into the MaterialDrawer as this is not as defined by the Material Design Guidlines

**Comment by mikepenz** [comment]
@yodeski you can set to just show the selected (active) profile and overwrite the layout used for the header. then you get the reference to the header-view and set the `onClickListener` on that view

**Comment by yodeski** [comment]
Got it! Thanks
