### ISSUE TITLE
Load icon profile from URL picasso or glide

### ISSUE THREAD

**Issue by danzhu10** [mikepenz/MaterialDrawer#661]
How to load icon profile from url ? in ur documentation u suggest us to use CustomApplication.java, but i dont know how to implement it. Can you give me tutorial for this ?

**Comment by mikepenz** [comment]
@danzhu10 just take a look at the sample application:

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/AndroidManifest.xml#L7
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java

**Comment by danzhu10** [comment]
yeah i just finish it. thanx
