### ISSUE TITLE
Get reference to view which lives inside header ?

### ISSUE THREAD

**Issue by AngleV** [mikepenz/MaterialDrawer#665]
How can i access the view ?

**Comment by AngleV** [comment]
never mind. i figured it out 

        Myview = (TextView)result.getDrawerLayout().findViewById(R.id.header_subline);

**Comment by mikepenz** [comment]
@AngleV you should better use the reference of the header itself. so findViewById should be faster

```java
result.getHeader()
```

**Comment by AngleV** [comment]
@mikepenz 

Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference 

when i use result.getHeader()

**Comment by mikepenz** [comment]
hmmm do you have a sticky or a normal header? and custom header or AccountHeader?

**Comment by AngleV** [comment]
@mikepenz  custom simple header !

**Comment by mikepenz** [comment]
@AngleV ok in this case you can do a different trick. don't set it as `Header` but just use the `ContainerDrawerItem` and set this one as (first) DrawerItem. Then you can "simply" update this item by it's identifier as you would do with other items.

**Comment by AngleV** [comment]
@mikepenz 
Due to layout custom needs cant do that.
But i can tell you that result.getDrawerLayout().findViewById works perfectly !!!

**Comment by mikepenz** [comment]
@AngleV it only works if you can't scroll the header out of focus. keep in mind the recyclerView will remove this item if you scroll. 

perhaps you should create a CustomDrawerItem or CustomContainerItem which is your header? would be a more safe approach. 

as mentiond i think the `ContainerDrawerItem` should do the job as it will host a custom layout. And you can update this `ContainerDrawerItem` with the updated view. you can also keep the reference to the view (be careful with recycling again :D)

**Comment by AngleV** [comment]
@mikepenz 
I see what you mean. Since my header is sticky i would not have any issues.

**Comment by mikepenz** [comment]
ah with sticky header then this one should work:
```java
result.getStickyHeader()
```
