### ISSUE TITLE
Problem in scroll with many items

### ISSUE THREAD

**Issue by Codestudios** [mikepenz/MaterialDrawer#667]
In my drawer I have 16 items with account header, when I scroll down, some radom items duplicated.
![screenshot_2015-09-19-14-06-20](https://cloud.githubusercontent.com/assets/11913923/9977747/cb6337b8-5ed7-11e5-9dd4-580e082b0d04.png)

**Comment by mikepenz** [comment]
@Codestudios they duplicate just on scroll? do you have any logic which modifies the items or anything else?

**Comment by mikepenz** [comment]
@Codestudios thanks for the finding. i will bring out a new release in the next 30 minutes which fixes this. 

it is caused by

```java
.setHasStableIds(true)
```

i added in the latest version to the adapter
