### ISSUE TITLE
Padding parametrizable de icono mdf_arrow_drop_down y mdf_arrow_drop_up 

### ISSUE THREAD

**Issue by INHack20** [mikepenz/MaterialDrawer#668]
```java
mAccountSwitcherArrow.setImageDrawable(
new IconicsDrawable(mActivity, MaterialDrawerFont.Icon.mdf_arrow_drop_down).sizeDp(24).paddingDp(6).color(mTextColor)
);
```
to 

In my app the value of 5 in paddingDp is correct and i can see the icon, with paddingDp 6 i can not see.
```java
mAccountSwitcherArrow.setImageDrawable(
new IconicsDrawable(mActivity, MaterialDrawerFont.Icon.mdf_arrow_drop_down).sizeDp(24).paddingDp(5).color(mTextColor)
);
```
Proposal: put parameters in size to customize the settings in the application.

Like `@dimen/material_drawer_padding_arrow_icon`

Thanks.

**Comment by mikepenz** [comment]
@INHack20 what else have you changed. as the default value are 6dp padding for this icon, and this one is working.

**Comment by INHack20** [comment]
with the default, I can not see the arrow, check the code and probe 5 and if there is. so I recommend placing it as a parameter, so I can overwrite the value.

**Comment by mikepenz** [comment]
@INHack20 you do not see the arrow with default MaterialDrawer setup? Without any modifications? 
which phone do you use? i have tested it on the emulator starting with API 10 up to 22 and i see the arrow.

**Comment by INHack20** [comment]
Emulator API 16 You default example.
![captura de pantalla de 2015-09-20 09 27 37](https://cloud.githubusercontent.com/assets/1240646/9981033/e12f519c-5f79-11e5-9750-0ee9bd49b300.png)

With Emulator API 16 and padding 5
![captura de pantalla de 2015-09-20 09 29 06](https://cloud.githubusercontent.com/assets/1240646/9981039/1d4346d4-5f7a-11e5-865c-a437fa5e0d91.png)

**Comment by INHack20** [comment]
Thanks so much!!!
