### ISSUE TITLE
Adding an ActionBarDrawerToggle

### ISSUE THREAD

**Issue by barmonger** [mikepenz/MaterialDrawer#669]
Hi

I'm trying to add an ActionBarDrawerToggle to my MaterialDrawer, in order to trigger certain actions when the drawer is opened/closed (I'm upgrading an existing app to material design), but the constructor for the ActionBarDrawerToggle requires a DrawerLayout.
And the Drawer does not have a set method for adding the drawer toggle at a later time.

I cannot figure out how to get this working, is there something I'm missing?

**Comment by barmonger** [comment]
I just noticed that you had previously answered a similar question. I've replaced the drawer toggle with an OnDrawerListener :)

**Comment by mikepenz** [comment]
@barmonger ok great that you found the solution. perhaps you post the link to the other issue here so others find it easier

**Comment by barmonger** [comment]
I ended up using this https://github.com/mikepenz/MaterialDrawer/issues/511

**Comment by mikepenz** [comment]
Great thanks ;)
