### ISSUE TITLE
Changes to "getPositionFromIdentifier"

### ISSUE THREAD

**Issue by alex-soft-r** [mikepenz/MaterialDrawer#67]
Please make changes in line "if (identifier > 0) {" as " if (identifier >= 0) {"

**Comment by mikepenz** [comment]
@alex-soft-r you need an identifier equal to 0?
Please be so kind and add the line or .java class for this one

**Comment by alex-soft-r** [comment]
I aready changed the code in my project.
And propose to change the code in future releases of the library :)

**Comment by mikepenz** [comment]
Ok this will be in v2.0.0
