### ISSUE TITLE
mCloseOnClick = true but the drawer won't close...

### ISSUE THREAD

**Issue by ovestoerholt** [mikepenz/MaterialDrawer#670]
I am testing out your drawer for a project but unfortunately it won't close after clicking drawer item.
Version 4.2.5 (just upgraded to test, before I was using 4.0.8).
Her is my generation code:

    Drawer result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withAccountHeader(headerResult) //set the AccountHeader we created earlier for the header
                .addDrawerItems(
                        new PrimaryDrawerItem()
                                .withName(R.string.drawer_one)
                                .withIdentifier(1),
                        new PrimaryDrawerItem()
                                .withName(R.string.drawer_two)
                                .withIdentifier(2),
                        new PrimaryDrawerItem()
                                .withName(R.string.drawer_eleven)
                                .withIdentifier(11),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem()
                                .withName(R.string.drawer_item_settings)
                                .withIdentifier(20)
                ) // add the items we want to use with our Drawer
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        // do something with the clicked item :D
                        if (drawerItem != null) {

                            FragmentManager fm = getSupportFragmentManager();
                            FragmentTransaction ft = fm.beginTransaction();

                            switch (drawerItem.getIdentifier()) {
                                case 1:
                                    break;

                                case 2:
                                    break;

                                case 11:
                                    break;

                                case 20:
                                    break;
                            }
                            ft.commit();
                        }
                        return true;
                    }
                })
                .build();

Any ideas?

Thanks, Ove

**Comment by mikepenz** [comment]
@ovestoerholt just return `false` in the `onItemClick` methods. 

`true` means that the event was consumed and no further action needs to be done
`false` means that the event was **not** consumed and that the drawer finishes everything (close)

**Comment by ovestoerholt** [comment]
Lovely! Thanks!
