### ISSUE TITLE
Image URL in PrimaryDrawerItem

### ISSUE THREAD

**Issue by bkawakami** [mikepenz/MaterialDrawer#671]
I would like my menu icon was dynamic, coming from a url ... I tried that but it did not work :(

```kotlin
var image = DrawerImageLoader.init(object : DrawerImageLoader.IDrawerImageLoader {
                override fun set(imageView: ImageView?, p1: Uri?, p2: Drawable?) {
                    Picasso.with(imageView?.getContext()).load("http://image.com/img.png").into(imageView);
                }

                override fun cancel(imageView: ImageView?) {
                    Picasso.with(imageView?.getContext()).cancelRequest(imageView);
                }

                override fun placeholder(ctx: Context?): Drawable? {
                    return null
                }

            }).getImageLoader();

            listItens.add(PrimaryDrawerItem().withName("Try").withIcon(image.placeholder(ctx)))
```

Obs: This language is Kotlin :P

**Comment by mikepenz** [comment]
@bkawakami this is not possible with the default DrawerItems, as those require a `Drawable` to be set, as the `PrimaryDrawerItem` will process them and tint them on purpose. 
This is also a rare usecase as normally those icons are delivered with the app. If you still want to load those images via url you should implement a `CustomDrawerItem` You could use the `PrimaryDrawerItem` and the `BasePrimaryDrawerItem` as reference. 

Theoretically you just have to change those lines to set the icon via an ImageLoader 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BasePrimaryDrawerItem.java#L100

---------------------------------------

Ok :D to simplify this i've added such a `CustomDrawerItem` implementation which does exactly what you need to the sample application ;)
https://github.com/mikepenz/MaterialDrawer/commit/af32de6ee0dae72aadcc37a2f33307d013bbc190

It's used in the AdvancedActivity:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/AdvancedActivity.java

**Comment by schaal** [comment]
Could you reconsider adding support for this in PrimaryDrawerItems? It's e.g. not possible to use the custom DrawerItems in a MiniDrawer (without also subclassing MiniDrawer and MiniDrawerItem)

**Comment by mikepenz** [comment]
@schaal it is possible to use `CustomDrawerItems`. The suggested implementation is to create a `CustomMiniDrawer` which will overwrite `generateMiniDrawerItem` and `getMiniDrawerType` 

As shown here:
https://github.com/mikepenz/MaterialDrawer/commit/8deedf8470f19c74ed6b826fd5aadc4eaed506da

You can then provide any `CustomMiniDrawerItem` for any other `CustomDrawerItem`

**Comment by schaal** [comment]
Ok, thanks. It's just that this is quite a bit of code for something that could be solved by a couple of lines in BasePrimaryDrawerItem.

**Comment by mikepenz** [comment]
@schaal it requires you to write a few lines yes. but not to many ;).

There's even a sample which showcases this:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerItems/CustomUrlBasePrimaryDrawerItem.java
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerItems/CustomUrlPrimaryDrawerItem.java

**Comment by schaal** [comment]
Thanks for your quick responses!

I now solved it with this code:

```java
public class UrlPrimaryDrawerItem extends PrimaryDrawerItem {
    @Override
    protected void bindViewHelper(BaseViewHolder viewHolder) {
        super.bindViewHelper(viewHolder);

        if(icon.getUri() != null) {
            ImageView imageView = (ImageView) viewHolder.itemView.findViewById(com.mikepenz.materialdrawer.R.id.material_drawer_icon);
            imageView.setVisibility(View.VISIBLE);
            ImageHolder.applyTo(icon, imageView);
        }
    }

    public UrlPrimaryDrawerItem withIcon(String url) {
        icon = new ImageHolder(url);
        return this;
    }
}
```

and something similar for the MiniDrawer

**Comment by mikepenz** [comment]
great ;)
