### ISSUE TITLE
drawer below ActionBar

### ISSUE THREAD

**Issue by mariem16** [mikepenz/MaterialDrawer#673]
I'm using Toolbar as action bar 
and custum layout header for drawer 
i want set drawer below toolbar 
please can u help me ? thnnks

**Comment by mikepenz** [comment]
@mariem16 check out the CustomContainer activity of the sample app
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java
