### ISSUE TITLE
Add Draweritems using arraylist

### ISSUE THREAD

**Issue by KeizerDev** [mikepenz/MaterialDrawer#674]
Hi,

I want to do something like a check if a item has to be exist in the menu list, like:
```
        if (prefs.isAgenda()) {
            menuList.add("Agenda");
        }
        if (prefs.isCijfers()) {
            menuList.add("Cijfers");
        }
        if (prefs.isOpdrachten()) {
            menuList.add("Opdrachten");
        }
        if (prefs.isAbsentie()) {
            menuList.add("Absentie");
        }
```

Now am I wondering what the best way is to display them in the menu dynamically.

Thanks in advance,

KeizerDev

**Comment by mikepenz** [comment]
@KeizerDev not sure what you are trying to do but you can also pass a list or an array to the builder of the drawer. Or you can add items to the drawer at a later time via the result object:

https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

you can also remove and update items at a later time.

**Comment by KeizerDev** [comment]
So I was wondering if I could do something like: 
```
ArrayList<PrimaryDrawerItem> arrayList1 = new ArrayList<PrimaryDrawerItem>();

        arrayList1.add(new PrimaryDrawerItem().withName(R.string.abc_action_bar_home_description_format).withIcon(R.drawable.ic_agenda));

        result = new DrawerBuilder(this)
                .withRootView(R.id.drawer_layout)
                .withToolbar(toolbar)
                .addDrawerItems(arrayList1)
                .withSavedInstance(savedInstanceState)
                .build();
    }
```

**Comment by mikepenz** [comment]
yes you can. but you have to choose the method `withDrawerItems(...)`

**Comment by KeizerDev** [comment]
Thanks! :+1:

**Comment by mikepenz** [comment]
;) no problem.

**Comment by Fuzzyma** [comment]
Sorry for digging this out. I was wondering if you could use an adaptor which you can connect to the DrawerrList. If yes - how? :)

**Comment by mikepenz** [comment]
@Fuzzyma what do you want to do with a different adapter?

**Comment by Fuzzyma** [comment]
I admit I am new to this topic. I saw that you would normally do something like this:

```java
mPlanetTitles = getResources().getStringArray(R.array.navigation_drawer);
mDrawerList = (ListView) findViewById(R.id.left_drawer);
mDrawerList.setAdapter(new ArrayAdapter<String>(this, R.layout.drawer_list_item, mPlanetTitles));
```

So you can use an adapter to fill the drawe with items from a ressource array.
How is the approach with your lib?

**Comment by mikepenz** [comment]
@Fuzzyma no this is not possible. You can have a method which reads in the array and fills the drawer with items. no custom adapter is required for this. there are many tutorials on the web which show how to read in an string array ressource. then iterate over it and create `DrawerItems` afterwards you can simply  add them to the drawer.
