### ISSUE TITLE
Selected lag with mini-items RecyclerView

### ISSUE THREAD

**Issue by StNekroman** [mikepenz/MaterialDrawer#676]
Steps to reproduce:
1. Create & attach mini-drawer to the layout.
2. Set up first item as selected by default.
3. Launch the app.
4. Select second (another one) item as selected.

Expected result:
1. First item is not marked as selected.
2. Second item is marked as selected.

Actual result:
1. First item IS marked as selected too.
2. Second item is marked as selected.

**Comment by StNekroman** [comment]
I just found, that it works fine with:

.withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        return miniDrawer.onItemClick(drawerItem);
                    }
                })

**Comment by mikepenz** [comment]
@StNekroman this is the desired behavior at the moment. I really do not want to make both depending on the other in all areas so it's required to forward the event at the moment. 

This is shown in the sample app:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java#L140
and for the account header:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java#L104
