### ISSUE TITLE
Can a Profile not have an email?

### ISSUE THREAD

**Issue by deanezra** [mikepenz/MaterialDrawer#677]
My app profiles do not use emails (only names and descriptions). Is there a way that I can disabled the email showing in the Drawer profile?

Showing the name only would be great.

Regards

**Comment by mikepenz** [comment]
Just add 
```java
.withSelectionSecondLineShown(false)
```
to the `AccountHeaderBuilder` to hide the second line

**Comment by deanezra** [comment]
Thank you! Awesome library and very fast response.

**Comment by mikepenz** [comment]
@deanezra no problem ;)
