### ISSUE TITLE
Dark zone in the drawer item

### ISSUE THREAD

**Issue by laurent512** [mikepenz/MaterialDrawer#678]
Hi,

First of all, I would like to thank you because your library is really helpfull for me.

And here is my issue :  I would like to know how to make the last selected item in the drawer darker. I don't find how you enable that in your code :fearful: 
Because I copied all the code from  draweractivity and the selected item stay white instead of being "highlighted".

Like this for example : 
 http://i.stack.imgur.com/1yz93.png 
The inbox item is a little bit grey

Thanks !

**Comment by laurent512** [comment]
I used result.setSelection(1); and tried with "true/false" argument but nothing works :'(

**Comment by mikepenz** [comment]
@laurent512 i do not get what you mean. you mean that you want a selected state for a specific item?

`result.setSelection(1)` sets the selection to the item with `identifier` 1 so you have to define the identifier (as shown in the sample app). you can also use the method to set the selection at a specific position but this is not a good idea. 

About the selected state. i assume you have set `withSelectable(false)` ? this should be used if you launch activities as those items will never get selected. 

Just take a look at the sample app: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java

**Comment by laurent512** [comment]
Thanks for the quick reply ! 
I don't know what I changed but now it works :dancers: 
Thanks again ! <3

**Comment by mikepenz** [comment]
no problem ;) great that you got it working
