### ISSUE TITLE
On click listener for dynamic menu

### ISSUE THREAD

**Issue by KeizerDev** [mikepenz/MaterialDrawer#679]
Hi,

I have a created a dynamic menu list and now I want to have a onClicklistener on it and based on the menu title start the another activity. Is there a better way to do this?

Here some code:
```
drawerItems = new ArrayList<IDrawerItem>();

if (prefs.isAgenda()) {
         drawerItems.add(new PrimaryDrawerItem().withName(R.string.menu_agenda).withIconTintingEnabled(true).withIcon(R.drawable.ic_agenda));
}
if (prefs.isCijfers()) {
         drawerItems.add(new PrimaryDrawerItem().withName(R.string.menu_cijfers).withIconTintingEnabled(true).withIcon(R.drawable.ic_cijfers));
}
if (prefs.isOpdrachten()) {
         drawerItems.add(new PrimaryDrawerItem().withName(R.string.menu_opdrachten).withIconTintingEnabled(true).withIcon(R.drawable.ic_opdrachten));
}
if (prefs.isAbsentie()) {
         drawerItems.add(new PrimaryDrawerItem().withName(R.string.menu_absentie).withIconTintingEnabled(true).withIcon(R.drawable.ic_absentie));
}
```

**Comment by mikepenz** [comment]
@KeizerDev you should use the `identifier` to then detect which item was used. 

see the sample code how this is done:
an item with identifier: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L114

depending on the identifier it launches an activity
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L149

**Comment by KeizerDev** [comment]
Thanks!

**Comment by mikepenz** [comment]
;) no problem
