### ISSUE TITLE
Update to "updateIcon"

### ISSUE THREAD

**Issue by alex-soft-r** [mikepenz/MaterialDrawer#68]
Please add version of "updateIcon" like:
public void updateIcon(int iconRes, int position) {

**Comment by mikepenz** [comment]
@alex-soft-r can you please be a bit more specific what this one should do?

**Comment by alex-soft-r** [comment]
Now we can use "updateIcon" only with Drawable or IIcon .
It would be good to have the same opportunity to change the icon using the icon from resources (drawable) like "updateIcon(int iconRes, ..."

**Comment by mikepenz** [comment]
will be in v2.0.0
