### ISSUE TITLE
How to refresh profileDrawerItem

### ISSUE THREAD

**Issue by lectricas** [mikepenz/MaterialDrawer#680]
Hi. When I change my account, I have special AsyncTask class for handling http requests. This task give me some response after some time, but your drawer is already created in onCreate method. I tried to recreate it in onResume method and in onPostExecute but sometime it give me 
https://github.com/mikepenz/MaterialDrawer/issues/308 this error. 
How should I refresh the name?

**Comment by mikepenz** [comment]
@lectricas you have defined an identifier for the `ProfileDrawerItem`?

Then you can just use the reference of your `ProfileDrawerItem` to update it with the `updateProfile` method
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L188

**Comment by lectricas** [comment]
So, I've created new ProfileDrawerItem().
Then I'v passed it to my AccountHeader, but nothing happened.
It seems like I have  to attach AccountHeader to DrawerBuilder() and then .build it. 
Do you have an example of updating ProfileDrawerItem()

**Comment by mikepenz** [comment]
@lectricas you can build the header and drawer as shown here: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CompactHeaderDrawerActivity.java

And then you can use the result object you get from the `AccountHeaderBuilder` and update items at a later time. 

headerResult: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CompactHeaderDrawerActivity.java#L55 

at a later time you can use a profile you have set:

profile.withName("newName");
headerResult.updateProfile(profile);

(make sure your profile defines an identifier)

**Comment by mikepenz** [comment]
This one also shows how it's done: http://codeshare.io/Nc6rK (line 166)

**Comment by lectricas** [comment]
Thanks. It works. Had to update your library in dependencies.
