### ISSUE TITLE
Update Icon delayed

### ISSUE THREAD

**Issue by zatziky** [mikepenz/MaterialDrawer#681]
Hello Mike,

I need to change icon in my drawer. Scenario goes like this:

1. MainFragment with Drawer: default icon is set. I click the item and am forwarded to another fragment.
2. NewFragment: I set the new icon and go back.
3. MainFragment with Drawer: the icon is still the default one.
4. NewFragment and go back.
5. MainFragment with Drawer: the icon has updated.

I have call this in the MainFragment in onResume() method:

```java
item.withIcon(flagResId);
drawer.updateItem(item); // drawer is com.mikepenz.materialdrawer.Drawer
```

Am I missing something? Thanks for help.
Zat

**Comment by mikepenz** [comment]
@zatziky you want to change an icon of a `DrawerItem`? 
Only your MainFragment has the drawer? 

The code how you update the item is correct. Your item also has an `identifier` set?

**Comment by zatziky** [comment]
@mikepenz when I set the identifier it updates immediately. Thank you!
