### ISSUE TITLE
How do I disable the Navigation Drawer when inside fragments?

### ISSUE THREAD

**Issue by ovestoerholt** [mikepenz/MaterialDrawer#682]
I have implemented the drawer in an AppCompatActivity implementing OnBackStackChangedListener for fragment support, like this:

    public class ReceiptActivity extends AppCompatActivity implements OnBackStackChangedListener {

    // The drawer
    private Drawer result = null;
    FragmentManager fm = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_receipt);

        // Handle Toolbar
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        // Need to attach the omBackStackChangedListener to the activity
        fm = getSupportFragmentManager();
        fm.addOnBackStackChangedListener(this);

        //Create the drawer
        result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .addDrawerItems(
                        new PrimaryDrawerItem()
                                .withName(R.string.drawer_example_list)
                                .withIdentifier(1),
                ) // add the items we want to use with our Drawer
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        // do something with the clicked item :D
                        if (drawerItem != null) {

                            FragmentTransaction ft = fm.beginTransaction();

                            switch (drawerItem.getIdentifier()) {
                                case 1:
                                    ExampleList exampleList = new ExampleList();
                                    ft.replace(R.id.frame_container, exampleList);
                                    break;

                            }
                            ft.commit();

                        }
                        return false;
                    }
                })
                .build();
    }

I also have a method for OnBackPressed() as recommended:

    @Override
    public void onBackPressed() {
        if (result != null && result.isDrawerOpen()) {
            result.closeDrawer();
        } else {
            super.onBackPressed();
        }
    }

and the needed methods to implement the OnBackStackChangedListener.

    /**
     * Required call back for OnBackStackChangedListener
     */
    @Override
    public void onBackStackChanged() {
        Log.i("ReceiptActivity", "Backstack changed");
        shouldDisplayHomeUp();
        }

    public void shouldDisplayHomeUp(){
        //Enable Up button if there are entries in the back stack
        boolean canback = getSupportFragmentManager().getBackStackEntryCount() > 0;
        if (canback) {
            result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false);
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        } else {
            getSupportActionBar().setDisplayHomeAsUpEnabled(false);
            result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);
        }
    }

    @Override
    public boolean onSupportNavigateUp() {
        //This method is called when the up button is pressed. Just the pop back stack.
        getSupportFragmentManager().popBackStack();
        return true;
    }

This works very well. inside an 'elevated' fragment the arrow is shown. On base level the hamburger is shown.

What I cannot get my head around is that when in an 'elevated' fragment (and the arrow is shown) if I press the arrow the navigation drawer is displayed instead of popping the fragment off the stack and bring me back to base level.

Any suggestions is highly appreciated!
Best regards from Ove

**Comment by mikepenz** [comment]
Take a look at the `AdvancedActivity` of the sample app. This one allows you to programmatically switch between hamburger and arrow icon. When the arrow is shown it will navigate back from this activity. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/AdvancedActivity.java

**Comment by ovestoerholt** [comment]
The switching between icons do work. It just that when inside the elevated fragment the navigation drawer shows when pressing the back arrow (instead of just bringing be back).

**Comment by mikepenz** [comment]
@ovestoerholt yeah but the sample also navigates up (you could overwrite this) with the back arrow. Have you tried the sample on your device?

**Comment by ovestoerholt** [comment]
Yes I have, and now I see what you mean! Thanks!

**Comment by mikepenz** [comment]
No problem;) I hope it helps
