### ISSUE TITLE
Non-selectable items, how to avaoid selection ?

### ISSUE THREAD

**Issue by outlying** [mikepenz/MaterialDrawer#683]
What's the best way to avaoid selectable items ? In original NavigationView you had to remove ```checkableBehavior="single"``` from XML

    <group android:checkableBehavior="single">

**Comment by mikepenz** [comment]
@outlying if specific items are not selectable just set them as `withSelectable(false)`
Shown in the sample app:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L114

**Comment by outlying** [comment]
Right, thanks

**Comment by mikepenz** [comment]
Great ;)
