### ISSUE TITLE
Set Drawer bellow toolbar

### ISSUE THREAD

**Issue by ArcanusEternal** [mikepenz/MaterialDrawer#684]
How to set Drawer bellow toolbar? Not using custom container. I know, that it can be set bellow the actionbar, and the statusbar, but how to set bellow the toolbar?

**Comment by mikepenz** [comment]
@ArcanusEternal you can either do it as shown in the following sample activity:
This uses a different container, but is the preferred implementation for this use-case (normally this should not be done)
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java
(not sure why you don't want this?)

You can also go with an old `ActionBar` as this does not allow you to have the drawer on top of it:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/ActionBarActivity.java

You can also look at the sample which implements the drawer inside of fragments. This sample also has the drawer below the toolbar. (but it would also allow it to have it on top of it...)
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/FragmentActivity.java

**Comment by tachang** [comment]
With there was a "withDisplayBelowToolbar". Is using a custom container with padding top the best way?

**Comment by mikepenz** [comment]
@tachang this was removed because it was no good solution and had the dark tint when opening the drawer. 

the CustomContainerActivity will inflate the drawer at a different position. in the sample below the toolbar. this will fix the dark shadow problem when opening. and also no padding top required.
