### ISSUE TITLE
PopupMenu

### ISSUE THREAD

**Issue by TomasValenta** [mikepenz/MaterialDrawer#685]
Hello Mike,

is there a possibility to use the three dots option "PopupMenu" on every item in list? Something like this:

![ceiiy](https://cloud.githubusercontent.com/assets/4901251/10055217/4d891144-6235-11e5-892e-e2555d4bf518.jpg)

**Comment by mikepenz** [comment]
@TomasValenta not out of the box. you would have to implement a CustomDrawerItem providing this element. 

You can use an existing `DrawerItem` as base. 

Here's an info how you can do this:
http://stackoverflow.com/questions/31030595/how-to-customize-the-draweritem-using-the-lib-mikepenz-materialdrawer

**Comment by TomasValenta** [comment]
Thank you Mike!
