### ISSUE TITLE
Allow non-persistent drawer item selected state

### ISSUE THREAD

**Issue by chteuchteu** [mikepenz/MaterialDrawer#686]
Currently, when tapping on a drawer item, the previously selected item is made unselected in favor of the new item.
This can be a problem in this situation: let's say we have a drawer with two items:
- "Feed", redirects to the associated activity
- "Support", opens a mail intent

We're on the "Feed" activity. The associated PrimaryDrawerItem has been made selected using `builder.withSelectedItem()`. When hitting the "Support" drawer item, the feed one is made unselected and the "Support" one is now selected. Since we're still in the Feed activity, this is not the excepted behavior.

We could distinguish from whether or not we should change the currently selected menu item using the `onItemClick` return value:

	builder.withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
		@Override
		public boolean onItemClick(View view, int index, IDrawerItem iDrawerItem) {
			switch (iDrawerItem.getIdentifier()) {
				case 0: // Feed:
					// ...
					return true; // Yes, change the currently selected item
				case 1: // Support:
					// ...
					return false; // Nope, don't change it
				default:
					return true;
			}
		}
	});

If this feature is already developed, it isn't documented yet. Please let me know if it is the case!

**Comment by mikepenz** [comment]
I assume you are searching for the `withSelectable()` method you can set on an `DrawerItem` it is used in the sample application ;)

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L114

Best,
Mike

**Comment by chteuchteu** [comment]
Awesome, that's even better! Thank you for the help!
Should I create a pull request to update the documentation?

**Comment by mikepenz** [comment]
@chteuchteu it's shown in the sample application, but yeah you can also add it to the documentation ;)
