### ISSUE TITLE
Hamburger issue

### ISSUE THREAD

**Issue by bhagavathgeethan** [mikepenz/MaterialDrawer#689]
Hai,
U had a good  library...it was very use full to my project..but i had issue on hamburger icon.
if i use this code,
```
getSupportActionBar().setDisplayHomeAsUpEnabled(false);
result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);
```
I had a error like this,
```
Attempt to invoke virtual method 'void android.support.v7.app.ActionBarDrawerToggle.setDrawerIndicatorEnabled(boolean)' on a null object reference..
```
So please help me...??

**Comment by mikepenz** [comment]
@bhagavathgeethan you have to pass the `Toolbar` to the drawer builder

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L110

**Comment by bhagavathgeethan** [comment]
Yes,i got it...thank u very much.............bro
