### ISSUE TITLE
Imageloader for icons

### ISSUE THREAD

**Issue by alex-soft-r** [mikepenz/MaterialDrawer#69]
At now we can use "withIcon" only with local resources from "drawable" how can i add any external ImageLoader and load images from network?

**Comment by mikepenz** [comment]
ImageLoader can also create drawables. If you mean you want to set the imageloader onto a view this is not possible, because at the moment of creating the drawer (or later) there is no view yet. i also have to reuse those images over and over again. 

i can provide an additional method to set it via ressource, or via bitmap.

**Comment by mikepenz** [comment]
A different solution is using a placeholder image and as soon as the imageLoader has finished loading the drawable update the specific item. or profile

**Comment by alex-soft-r** [comment]
If possible - that my solution ;)

just add in "PrimaryDrawerItem" or/and "SecondaryDrawerItem"
    private URLLoaderCallback callback = null;

    public interface URLLoaderCallback {
        void callbackCall(String iconUrl, ImageView iconView);
    }
    public PrimaryDrawerItem withIcon(String iconUrl, URLLoaderCallback callback) {
        assert (callback!=null);
        this.iconUrl = iconUrl;
        this.callback = callback;
        return this;
    }
and in method "public View convertView(..." make changes
        if (callback == null && TextUtils.isEmpty(iconUrl)) {
            Drawable icon = null;
            Drawable selectedIcon = null;
...
        } else {
            callback.callbackCall(iconUrl, viewHolder.icon);//try load external image
        }

In your primary class add:
    PrimaryDrawerItem.URLLoaderCallback callback = new PrimaryDrawerItem.URLLoaderCallback(){
        @Override
        public void callbackCall(String iconUrl, ImageView iconView) {
            Constants.uilImageLoader.displayImage(!TextUtils.isEmpty(iconUrl)?iconUrl:"",
                    iconView,
                    Utils.isWiFiEnabled(MainActivity.this)?Constants.uilUserOptionsWifi:Constants.uilUserOptionsMobile);
        }
    };

and now we can load images like this:
                mDrawerRight.addItem(new PrimaryDrawerItem().withName(friend.getName()).withIcon(url, callback);

**Comment by mikepenz** [comment]
@alex-soft-r thanks for the code. There's problem with this one. To implement such methods i would have to include the library you are using as dependency. There are to many image loader on the market. 

You can easily create your custom implementation of the `ImageLoaderPrimaryDrawerItem` and create a GitHub project with these custom made DrawerItems. Others can then easily use them within their projects as "addon" :)

**Comment by alex-soft-r** [comment]
I specifically used the callback, so as not to tie the MaterialDrawer code to an external library (loader pictures).
This will require just add one function. :)
And yours magnificent library will be even better :)

**Comment by mikepenz** [comment]
@alex-soft-r so i took another look at the whole thing. for me it does not make much sense to include it within the default drawerItems. especially as those icons within the drawer are small ones. and in most cases colored on selection. 

I would recommend that you create a github gist with the code for your modified items and i'll just add a section to the readme about extensions or similiar things. 

Thank you!
