### ISSUE TITLE
add account within the app!

### ISSUE THREAD

**Issue by TheLoyalCruel** [mikepenz/MaterialDrawer#690]
is there any sample on how to add accounts in the app?
the add account buttons do not work!

**Comment by mikepenz** [comment]
@TheLoyalCruel there is. The `DrawerActivity` of the sample app shows how to add an account at a later time
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L90
