### ISSUE TITLE
Ability to disable account selector when only one account present

### ISSUE THREAD

**Issue by livotov** [mikepenz/MaterialDrawer#692]
Is there a possibility to disable useless account selector when one using AccountHeader with the only one account, e.g. no more accounts will be added or changed ?

Right now, when you tap below the current account details, selection popup appears, showing the same current account, which is useless.

Thanks!

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/615
https://github.com/mikepenz/MaterialDrawer/issues/454
https://github.com/mikepenz/MaterialDrawer/issues/443
https://github.com/mikepenz/MaterialDrawer/issues/350

**Comment by livotov** [comment]
Oh, thanks !
yeah, having documentation one day would be awesome ! :)

**Comment by mikepenz** [comment]
:D haha having documentation. or people use the search function in the issues section or on stackoverflow :D

**Comment by livotov** [comment]
:D yeah, I searched "single account" and it did not match that issue you mentioned. But actually it seems I was not enough attentive when scrolling AccountHeaderBuilder methods :))))  Must go get some rest.

Thanks again and have a nice day ! :)

**Comment by mikepenz** [comment]
@livotov haha no problem ;) i'm quick in answering :P

have a nice day ;)
