### ISSUE TITLE
Is it possible to bring drawer above status bar?

### ISSUE THREAD

**Issue by rajkshah14** [mikepenz/MaterialDrawer#695]
Dear Mike

I want that when drawer is opened, translucent status bar wont be visible. Drawer should be like full screen. I am using DrawerBuilder to build drawer. Is it possible to do so?

TIA :)

**Comment by mikepenz** [comment]
@rajkshah14 can you be a bit more specific? perhaps show some screenshots? i'm not quite sure what you mean

**Comment by mikepenz** [comment]
As there was no answer for a while i close this issue
