### ISSUE TITLE
how to change header layout gravity right to left?

### ISSUE THREAD

**Issue by softweng** [mikepenz/MaterialDrawer#696]
how to change header layout gravity right to left? I need profile icon and name be align to right for RTL language.

**Comment by mikepenz** [comment]
@softweng not possible. also not done in the google apps as far as i've found. you can provide a different layout for the header to overwrite the original layout if you need it

**Comment by mikepenz** [comment]
This is the original layout: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml

you can just add this to your project and modify it to fit your needs
