### ISSUE TITLE
Ability to remove the selection on MiniDrawer

### ISSUE THREAD

**Issue by timrae** [mikepenz/MaterialDrawer#697]
**Edit:** Actually it was a different problem than below that was causing my issues, due to trying to remove the selection on the MiniDrawer, which appears to be currently unsupported.

---------------------------------------------------------------------------------------------------------------

My navigation drawer items start new Activities, and in those new Activities I call `mDrawer.setSelection(itemId, false);`. This works fine for the ordinary drawer, but with the `MiniDrawer` it leads to the wrong item being highlighted.

Is this is a bug, or do I need to do something else to set the selected item in the MiniDrawer?

**Comment by mikepenz** [comment]
@timrae you have set it up as shown in the sample including the two listener hooks:

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java#L104

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java#L140

**Comment by timrae** [comment]
@mikepenz thanks, but I'm not talking about physical clicks, I want to programmatically set the selected item without triggering `onItemClick()`

**Comment by mikepenz** [comment]
@timrae if you want to select without firing the listener you should then "manually" update the selection for the miniDrawer. I made the decision to not automatically do all of those things within the drawer code, as this gives us more flexibility and the drawers can be used without the other one.

```java
miniResult.onItemClick(drawerItem)
```

**Comment by timrae** [comment]
Ah right thanks, I had thought that calling that was leading to to the main `onItemClick()` method getting called due to a bug in my code that appears to have been unrelated (I was allowing  `getDrawerItem(-1)` to be called)

**Comment by timrae** [comment]
On an unrelated note, is it possible to allow some or all of my `SecondaryDrawerItem`s to be included in the MiniDrawer?

**Comment by timrae** [comment]
> ... due to a bug in my code that appears to have been unrelated

Actually this is a bit of an issue. I need to be able to do the equivalent of `setSelection(-1)` on the MiniDrawer; is there a way to do this?

**Comment by mikepenz** [comment]
@timrae `SecondaryDrawerItems` are not yet supported. but may in the future.

removing the selection at all is also not possible at the moment. 

i can take a look at this. but can't tell you when i will release it with an update

**Comment by timrae** [comment]
Thanks, that would be great, it's quite necessary for my app as there are some Activities that have a drawer but don't have their own entries on the drawer. I'll keep an eye on this issue!
