### ISSUE TITLE
MaterialDrawer damage Collapsing Toolbar image

### ISSUE THREAD

**Issue by TomasValenta** [mikepenz/MaterialDrawer#698]
Hello again,

I have little problem with MaterialDrawer. I found that, when I simply turn MD on:

```java
new DrawerBuilder().withActivity(this).build();
```

then Collapsing Toolbar image stops overlapping statusbar. See screenshots:

Before
![device-2015-09-27-230426](https://cloud.githubusercontent.com/assets/4901251/10125220/4ca0f726-656c-11e5-99d1-869f08a002df.png)

After
![device-2015-09-27-230231](https://cloud.githubusercontent.com/assets/4901251/10125219/4c9d2fec-656c-11e5-8726-79f4808d034b.png)

Where could be the problem?

**Comment by mikepenz** [comment]
@TomasValenta this happens because the drawer will automatically add a `ScrimInsetsFrameLayout` which will add the toolbar padding so this must not be managed by devs themself. if you require your content to go up to the top you should take a look at the `FullscreenDrawerActivity` of the sample app

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/FullscreenDrawerActivity.java

**Comment by TomasValenta** [comment]
Ok,
I understand now. Thank you.

**Comment by mikepenz** [comment]
@TomasValenta were you able to solve your issue with this info?

**Comment by TomasValenta** [comment]
@mikepenz Basically yes, thank you for asking. I use parameter: **.withFullscreen(true)** and I added to the Toolbar **android:layout_marginTop="@dimen/tool_bar_top_padding"**. Then if AppBarLayout is expanded, behaviour is good:
![device-2015-09-28-100137](https://cloud.githubusercontent.com/assets/4901251/10130334/ffebb7f2-65c7-11e5-8566-6c51c9c010dc.png)

only one problem is now when AppBarLayout is collapsed:
![device-2015-09-28-095901](https://cloud.githubusercontent.com/assets/4901251/10130336/05811b3a-65c8-11e5-82a9-bf5e51652dd2.png)

Do you have any idea?

**Comment by TomasValenta** [comment]
One idea,
maybe instead of using **.withFullscreen(true)**, can be added method like **.doNotUseScrimInsetsFrameLayout(true)**? :-)

**Comment by mikepenz** [comment]
@TomasValenta about the collapsed AppBarLayout i have no idea sorry. 

To get just the translucent StatusBar and a normal NavigationBar you have to do the following:

Use one of the `TranslucentStatus` themes (or a child of it) for this activity
```xml
@style/MaterialDrawerTheme.Light.TranslucentStatus
```

And then build the drawer as shown here:

```java
    //Create the drawer
    result = new DrawerBuilder()
        .withActivity(this)
        .withFullscreen(true)
        .withTranslucentNavigationBarProgrammatically(false)
    //note that the translucentNavigationBarProgrammatically comes AFTER the withFullscreen method
```

This will result in an transparent **StatusBar** but with a black **NavigationBar**

**Comment by suleymanccelik** [comment]
Do you solve your issue with mike's last info @TomasValenta? I have same problem. Instead of creating sample project for my issue, I add materialdrawer library to chris banes' project ( https://github.com/chrisbanes/cheesesquare ). I reproduce same issues which you encountered

**Comment by mikepenz** [comment]
@suleymanccelik a `CollapsingToolbar` sample is also in the sample application.

**Comment by suleymanccelik** [comment]
Yes, I also reviewed CollapsingToolbar sample in your sample application. However color of status bar is not transparent when toolbar is expanded.

**Comment by TomasValenta** [comment]
@suleymanccelik No, in the end I use Navigation Drawer from Support Library.

**Comment by suleymanccelik** [comment]
Thanks for reply @TomasValenta. You gave me bad news :)

**Comment by TomasValenta** [comment]
@suleymanccelik Sorry for that. I spent a lot of  time with this issue and without success :(

**Comment by mikepenz** [comment]
@suleymanccelik you sent me an e-mail with the source right? i will take a look later today / or this week.

**Comment by suleymanccelik** [comment]
Yes I sent you source code because I reviewed documentation and sample project of materialdrawer project but I don't find a way to add materialdrawer to CheeseDetailActivty whose layout has collapsingtoolbar and parallax image. Thanks for help.

**Comment by suleymanccelik** [comment]
@mikepenz updated collapsingtoolbar sample for our issue and updated sample project works now. Take a look @TomasValenta, maybe you start to use materialdrawer lib on your applications again :)

Thanks a lot for help @mikepenz 

Commit url: https://github.com/mikepenz/MaterialDrawer/commit/d4c34a6a932b44595f63ac0f413913471e61e8b3

**Comment by TomasValenta** [comment]
Thank you for the information ;)

**Comment by markdwags** [comment]
Thanks for the info.  This solved my issue using a ``CollapsingToolbar`` with this library.
