### ISSUE TITLE
how not to show selected item? 

### ISSUE THREAD

**Issue by TheLoyalCruel** [mikepenz/MaterialDrawer#699]
I use "withSelectable(false)" and it work for all items except the first item! I mean the first item is always selected! how to remove selection for all items of Drawer list?
thanks...

**Comment by mikepenz** [comment]
@TheLoyalCruel you should not set the selection to the first one with the builder. just select a different one. 

`withSelectable(false)` does only prevent real clicks. you can still select those items via code. 

so basically you just need to define a different selected item via the buidler:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L196

**Comment by TheLoyalCruel** [comment]
Sorry but I mean... when I open the drawer the first item is selected! I dont want any item to be selected!

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#how-can-i-create-a-drawer-without-a-default-selection

**Comment by TheLoyalCruel** [comment]
thank you very much... :)
