### ISSUE TITLE
First menu item always selected 

### ISSUE THREAD

**Issue by Axxium** [mikepenz/MaterialDrawer#700]
Hi 

I'm sure this is an easy thing but i can't seem to find a solution to fix this issue i'm having , actually the first menu item is always selected event when i create a new menu and i set the selected item with the 
.withSetSelected(false) method 

I added a txt with some code in there mabye it could help you figure out what i'm doing wrong 

Thank you 
![cuserspc-martindesktopmenu txt - sublime text_4](https://cloud.githubusercontent.com/assets/7561038/10149436/9b5102d0-6607-11e5-82a2-eebc342f62b1.jpg)

**Comment by mikepenz** [comment]
Not sure if search of github is so bad. But there was exact the same question one issue before yours:

https://github.com/mikepenz/MaterialDrawer/issues/699

**Comment by Axxium** [comment]
Thank you very much an sorry about the duplicate post

**Comment by mikepenz** [comment]
@Axxium no problem. It was just funny as there was exact the same question one issue before :D
