### ISSUE TITLE
ItemSelection from a fragment 

### ISSUE THREAD

**Issue by laurent512** [mikepenz/MaterialDrawer#701]
Hello ! 

I would like to have your opinion about my issue :)
Each click on a drawer item replaces the actual fragment by another one.
When I press back, It goes to the previous fragment correctly using the popBackStack method. But obvisouly, it doesn't change the selected item ^^'.
What is the best solution to solve this for you? Try to select the item in the OnCreateView of a fragment or implement something in the function OnBackStackChangedListener() ?

Thanks for your advice :)

**Comment by mikepenz** [comment]
@laurent512 i would suggest that you react in the listener. As this should somehow provide you with the information which fragment will now be shown. Having it in the fragments `OnCreateView` is probably not the best idea.
