### ISSUE TITLE
Call other activities from the the drawer

### ISSUE THREAD

**Issue by IshanPunchihewa** [mikepenz/MaterialDrawer#703]
```java
.withCustomView(View.inflate(this, R.layout.dashboard_navigation_pannel, null))
.withDrawerWidthDp(300)
.withDisplayBelowToolbar(true)
.addDrawerItems(
                        new PrimaryDrawerItem().withBadgeBackgroundResource(R.id.dashboard_linearLayout),
                        new DividerDrawerItem(),
                        new SecondaryDrawerItem().withBadgeBackgroundResource(R.id.chat_linearLayout),
                        new DividerDrawerItem(),
```

i have used customized layouts for my navigation panel but i have having hard time figuring out how to call other activities from the navigation panel. please help me out

thanks in advance

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#add-items-and-adding-some-functionality

```java
.withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
        @Override
        public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
            // do something with the clicked item :D
        }
    })
```

**Comment by IshanPunchihewa** [comment]
First of thanks for getting back so soon... 

this is my issue i am using and older version com.mikepenz:materialdrawer:3.1.2@aar

i have to stay bellow sdk 23 coz i am using another library (loopj) for my server calls which doesnt work for 23.. so i am stuck in the middle.. is there any way i can use the older version and get this done

.withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(AdapterView<?> parent, View view, int position, long id, IDrawerItem drawerItem) {
                        // do something with the clicked item :D
                     

                        return true;
                    }
                })
                .build();

**Comment by mikepenz** [comment]
@IshanPunchihewa sorry no support for versions older than the latest. 

not sure why this code shouldn't work? 
https://github.com/mikepenz/LollipopShowcase/blob/master/app/src/main/java/com/mikepenz/lollipopshowcase/MainActivity.java#L88
