### ISSUE TITLE
don't show currently selected profile in profile selector list

### ISSUE THREAD

**Issue by adennie** [mikepenz/MaterialDrawer#704]
When clicking the down triangle in the account header, I'd like the displayed list of selectable profiles to exclude the already-selected one.  Is that configurable?

**Comment by mikepenz** [comment]
@adennie yes it is ;)
`withCurrentProfileHiddenInList(true)`

**Comment by adennie** [comment]
duh, sorry.  Need more coffee.

**Comment by mikepenz** [comment]
@adennie no problem :)
