### ISSUE TITLE
Open Header Drawer at Start 

### ISSUE THREAD

**Issue by Axxium** [mikepenz/MaterialDrawer#705]
Hi 

Is there a way to open the drawer with the header drawer (Accounts name / Add Account / Account Option) by code for exemple you start an activity an the drawer is already open at the profile drawer 

Thank you

**Comment by mikepenz** [comment]
this code should do the trick:

```java
result.openDrawer();
headerResult.toggleSelectionList(this);
```

**Comment by Axxium** [comment]
Thank you ;-)
