### ISSUE TITLE
Secondary Icon Color

### ISSUE THREAD

**Issue by RWiggers** [mikepenz/MaterialDrawer#706]
Hi!

I use your MaterialDrawer and I can't change the color of the secondary icon.
I realy can't change it or is there a way to do it?

Thanks for all your libraries!
Wiggers

**Comment by mikepenz** [comment]
@RWiggers can you be a bit more specific. You have a `SecondaryDrawerItem` with an `Drawable` icon? This will not tint? You have to enable tinting for those: `withIconTintingEnabled(true)`

**Comment by RWiggers** [comment]
I have: 
PrimaryDrawerItem().withIcon(GoogleMaterial.Icon.gmd_shopping_basket), SecondaryDrawerItem().withIcon(FontAwesome.Icon.faw_cog),

I change the colors of the icons with style on my xml file:
<color name="material_drawer_primary_icon">#212121</color>
and I tried this:
<color name="material_drawer_secondary_icon">#616161</color>

But the secondary icon doesn't change. The secondaries is with primary color

**Comment by mikepenz** [comment]
@RWiggers there's nothing like secondary-icon as google's guidelines state the same color for them. you can overwrite the color for a specific `DrawerItem` with 
```java
withIconColor()
```

**Comment by RWiggers** [comment]
thx
