### ISSUE TITLE
MaterialTheme not found

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [mikepenz/MaterialDrawer#707]
In file MaterialDrawer/library/src/main/res/values/styles.xml I get an error:

Error:(22, -1) android-apt-compiler: [materialDrawer] d:\pivot\MaterialDrawer\materialDrawer\res\values\styles.xml:22: error: Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme'.

See link for details: http://postimg.org/image/nibh34ejh

**Comment by mikepenz** [comment]
@dmitrykolesnikovich you do not use the maven dependency?

do you compile with sdk 23?
latest build tools?

**Comment by dmitrykolesnikovich** [comment]
No I do not. I add dependencies with hands in IntelliJ IDEA. AppCompat, aboutLibraries, AndroidIconics.

I use sdk version 21.

**Comment by mikepenz** [comment]
@dmitrykolesnikovich the latest project is always only compileable with the latest sdk version.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md#-v400

**Comment by dmitrykolesnikovich** [comment]
I updated to 23 version, but MaterialTheme still not found. Can you please provide me *.xml file where it is defined?

**Comment by mikepenz** [comment]
the whole repo can be imported into Android Studio and it will work. Probably you have set it up wrong and so it misses the sub dependencies like:
https://github.com/mikepenz/Materialize

**Comment by dmitrykolesnikovich** [comment]
Yes it helps me, thank you.
