### ISSUE TITLE
Can I change the color of the SwitchDrawerItem?

### ISSUE THREAD

**Issue by leijdekkers** [mikepenz/MaterialDrawer#708]
I want to change the color of the SwitchDrawerItem (the switch item on the right, not the icon on the left!) programmatically and tried the code below. I assumed (no documentation!) that the .withSelectedIconColor(..) would change the color of the switch. but it doesn't...

So is it possible and if so how?

```java
 drawer.addItem(new SwitchDrawerItem()
                .withName(R.string.voice_feedback)
                .withIcon(FontAwesome.Icon.faw_volume_up)
                .withChecked(true)
                .withSelectedIcon(icon)
                .withSelectedIconColor(getResources().getColor(R.color.green))
                .withIdentifier(ID_VOICE)
                .withOnCheckedChangeListener(this));
```

**Comment by mikepenz** [comment]
@leijdekkers the `withSelectedIconColor` will change the color of the selected icon as for all other drawer items. There is no method to do so via code. I think you can in general change the color of the switch via theme, else you can create a customDrawerItem, or you hook in with a `onPostBindView` listener and change it then.

**Comment by leijdekkers** [comment]
The issue is that i allow the user to change the colors of the toolbar etc. Sort of allowing them to change the theme but you cant change the primary and primaryDark colors programmatically as defined in the style.xml. Therefore i need to change the switch color programmatically. It would be great to have this feature  add the level of ".withSwitchColor(...)" Would you be able to add that?

**Comment by mikepenz** [comment]
@leijdekkers you can add it on your own. Just create your own `CustomDrawerItem` (`CustomSwitchDrawerItem`) and add this method. 

You can see a similar example here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerItems/CustomPrimaryDrawerItem.java

**Comment by leijdekkers** [comment]
Thanks but this ends up coloring the row not the switch widget. To be clear I want the switch, that is the small circle, to be colored.

**Comment by mikepenz** [comment]
@leijdekkers once again. the above is just a sample how you can create a `CustomDrawerItem` you will have to write 4 lines of code on your own for your purpose

**Comment by leijdekkers** [comment]
This is what I have. The issue is to get access to the SwitchWidget. Not sure how to do that.

public class CustomSwitchDrawerItem extends SwitchDrawerItem {

    private ColorHolder background;

    public CustomSwitchDrawerItem withBackgroundColor(int backgroundColor)
    {
        this.background = ColorHolder.fromColor(backgroundColor);
        return this;
    }

    public CustomSwitchDrawerItem withBackgroundRes(int backgroundRes)
    {
        this.background = ColorHolder.fromColorRes(backgroundRes);
        return this;
    }

    @Override
    public void bindView(RecyclerView.ViewHolder holder)
    {
        super.bindView(holder);

        if (background != null) {
            background.applyToBackground(holder.itemView);
        }
    }
}

**Comment by mikepenz** [comment]
```java
SwitchCompat switch = (SwitchCompat) holder.itemView.findViewById(R.id.material_drawer_switch)
```

**Comment by leijdekkers** [comment]
ok that will do it. thanks!
