### ISSUE TITLE
Add padding around background in MiniDrawer

### ISSUE THREAD

**Issue by timrae** [mikepenz/MaterialDrawer#710]
Thanks for your work on the MiniDrawer in the latest version!

One bug I've noticed is that the background of the selected item covers the shadow when I set `.withInnerShadow(true)`, whereas the gmail app seems to have a lot of padding around it so that doesn't happen.

![minidrawer](https://cloud.githubusercontent.com/assets/2818274/10251440/a893c3da-696b-11e5-9e7b-764d270cbbaa.png)

**Comment by mikepenz** [comment]
@timrae i will remove the selected background completely as shown in the following screenshot by google:

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7ZVZzVEhrbF9YWk0/patterns_navdrawer_behavior_persistent4.png

**Comment by timrae** [comment]
thanks that will be nice
