### ISSUE TITLE
@dimen/tool_bar_top_padding not found

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [mikepenz/MaterialDrawer#711]
I use latest version of android and build tool. 

@dimen/tool_bar_top_padding not found in file MaterialDrawer\materialDrawer\res\layout\material_drawer_slider.xml

Maybe I miss some module. Please help me to understand what exactly module I miss. Thanks in advance.

- Dmitry

**Comment by mikepenz** [comment]
I think you miss the sub dependencies. Have you set up everything as described in the readme:
https://github.com/mikepenz/MaterialDrawer#1-provide-the-gradle-dependency
