### ISSUE TITLE
setFullscreen(true) doesn't work

### ISSUE THREAD

**Issue by timrae** [mikepenz/MaterialDrawer#712]
I can get my Activity to work in Fullscreen immersive mode if I use `.withFullscreen(true)` in the builder, but if I try to do it programmatically via `setFullscreen(true)` directly on the drawer object I just see a white status bar (with white text!)

![fullscreen](https://cloud.githubusercontent.com/assets/2818274/10251989/a256c964-696f-11e5-8335-3073d976dc21.png)

**Comment by mikepenz** [comment]
@timrae `setFullscreen` won't bring the app in immersive mode. It will just remove the paddings and the `ScrimInsetsFrameLayout` functionality from the drawer. 

You can see what happens in the `FullscreenActivity`
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/FullscreenDrawerActivity.java

**Comment by timrae** [comment]
you're not changing it programmatically in that example though... as I said, `.withFullscreen()` works correctly

**Comment by mikepenz** [comment]
@timrae ah ok i see. providing the correct theme in addition is no option in your case?

**Comment by timrae** [comment]
Sorry I don't understand your question, what do you mean by the "correct theme"?

**Comment by timrae** [comment]
We have a preference that toggles fullscreen on and off in one specific activity, so we need programmatic access

**Comment by mikepenz** [comment]
ah sorry
now i get your issue

**Comment by mikepenz** [comment]
Not all functions work exact the same after building the drawer. especially if you try to switch from normal to fullscreen or so. those things should be done during the view creation and not at a later time.

**Comment by timrae** [comment]
OK, it should be possible with some refactoring, but maybe don't expose the method if it doesn't work though? :)

**Comment by mikepenz** [comment]
Can you recreate the activity so relaunch the activity if you switch that preference?

**Comment by timrae** [comment]
yeah I can do that, it will require a bit of work though

**Comment by timrae** [comment]
actually it was easier than I thought, it could be useful to hide that method though.

**Comment by timrae** [comment]
@mikepenz 

I'm having trouble with fullscreen immersive mode again when using MaterialDrawer. We set immersive fullscreen mode like this:

``` java
activity.getWindow().getDecorView().setSystemUiVisibility(
                        View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                        | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                        | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                        | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                        | View.SYSTEM_UI_FLAG_FULLSCREEN
                        | View.SYSTEM_UI_FLAG_LOW_PROFILE
                        | View.SYSTEM_UI_FLAG_IMMERSIVE);
activity.getWindow().decorView.setOnSystemUiVisibilityChangeListener
                (new View.OnSystemUiVisibilityChangeListener() {
                    @Override
                    public void onSystemUiVisibilityChange(int flags) {
                        boolean visible = (flags & View.SYSTEM_UI_FLAG_HIDE_NAVIGATION) == 0;
                        if (visible) {
                            activity.getSupportActionBar().show();
                        } else {
                            activity.getSupportActionBar().hide();
                        }
                    }
                });
```

but the action bar gets drawn underneath (overlapping with) the status bar. If I remove the `MaterialDrawer` build() call then this doesn't happen so presumably it's a missing `setFitsSystemWindows()` in the library somewhere. I've tried fiddling with a bunch of stuff but can't get it to work.

**Comment by timrae** [comment]
Hmm actually maybe it *is* our fault

**Comment by timrae** [comment]
I hacked together an [example](https://gist.github.com/timrae/178cdc310cfa36a2f91e) with the sample app working correctly in immersive mode. I still can't figure out what the problem is in our app though :-/ I'll report back when I figure out what the problem is

**Comment by mikepenz** [comment]
@timrae if the drawer builder has the fullscreen flag set it won't add the insets and so the toolbar will be on top. if you now get the toolbar to show the insets do not change because the drawer was set to ignore those. 

As i moved the ui stuff to the Materialize lib. Here's the ScrimInsetsFrameLayout, which will have the insets set to 0 if the SystemUI is not visible. 
https://github.com/mikepenz/Materialize/blob/develop/library/src/main/java/com/mikepenz/materialize/view/ScrimInsetsFrameLayout.java#L96

There is no listener which changes this. probably this is the issue?

**Comment by timrae** [comment]
That sounds about right... I finally figured out that in the sample app you have `android:layout_marginTop="@dimen/tool_bar_top_padding"` set in the toolbar and if I add this then I can basically get it to work, but it's quite hacky as I have to do it programatically.

Is it possible for you to provide an interface for us to tell the drawer when the system UI is and is not visible?

**Comment by mikepenz** [comment]
@timrae you can get a reference to the ScrimInsetsFrameLayout from the drawer. and this will allow you to do this:

```
drawer.getScrimInsetsFrameLayout()
```

**Comment by timrae** [comment]
@mikepenz 

Thanks, what do I need to do to the ScrimInsetsFrameLayout? Sorry I'm a bit slow today

**Comment by mikepenz** [comment]
this has a method to enable/disable the flag that the systemUI is hidden.

**Comment by timrae** [comment]
Hmmm calling `mDrawer.getScrimInsetsFrameLayout().setSystemUIVisible(true);` when I receive the `onSystemUiVisibilityChange` listener event doesn't appear to do anything.

**Comment by mikepenz** [comment]
@timrae then the insets probably don't change. sorry.
