### ISSUE TITLE
Mini drawer -> Persistent Drawer

### ISSUE THREAD

**Issue by timrae** [mikepenz/MaterialDrawer#713]
It could be really cool if we could do the persistent drawer in the material design spec. I tried using `.withDrawerLayout()` with a permanent DrawerLayout inside a LinearLayout in my XML, but that didn't work.

It would be even cooler if the mini drawer could automatically expand into a persistent drawer and vice-versa. Currently expanding the mini-drawer obscures some of the content.

![Like this](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7TEVnWVlVS3RXMzQ/patterns_navdrawer_behavior_persistent5.png)

**Comment by mikepenz** [comment]
@timrae you can use the normal drawer and add it somewhere in your layout like done here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/EmbeddedDrawerActivity.java

or you use the same mechanism shown with the MiniDrawer sample. this also does not move over the content.

**Comment by timrae** [comment]
> or you use the same mechanism shown with the MiniDrawer sample. this also does not move over the content.

hmm are you sure about that? I am using the same mechanism as the MiniDrawer example, and I just checked the sample app, which definitely moves the content (you can see that the text "embedded drawer" moves to the right and is no longer centered in the view when the drawer is open).

**Comment by timrae** [comment]
also the navigation icon in the action bar changes to a back button whereas in gmail it is a hamburger which expands the MiniDrawer into a proper nav. drawer.

**Comment by timrae** [comment]
The left caret at the top of the drawer which folds it into MiniDrawer (as in pic in first post) would be cool as well if I were to be greedy :)

**Comment by mikepenz** [comment]
@timrae i just published a new version of the `Crossfader` library which now allows you to disable the slide functionality, and which allows you to resize the content panel instead of moving it out of the screen.

The function of the `ActionBarDrawerToggle` can be managed by you, this is not limited or hardcoded by the drawer

**Comment by mikepenz** [comment]
@timrae i hope you like the new added persistent drawer sample: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/PersistentDrawerActivity.java

it showcases how to create a drawer like the one shown in the MaterialDesignGuidelines by using all the APIs the MaterialDrawer offers. It can even be used in RTL layout. 

At the moment there are two bugs (but as this is not part of the lib but custom behavior you can achieve with the drawer it is possible to fix them without depending on the library itself):
* on API 17 the header has a different height than the Toolbar (it is correct on API 10)
* on API 10 the arrow to close the extended drawer is directly on the right without the padding (which is applied on higher api levels)
