### ISSUE TITLE
Prevent Indicator from opening the drawer

### ISSUE THREAD

**Issue by Hawlitschek** [mikepenz/MaterialDrawer#714]
There are cases where we want the back indicator to work as back button.
But the button always opens the drawer.

I'm not sure if I am doing something wrong, but I fixed this error in one of my old projects bei injection a listener into the DrawerLayout.

Maybe I'm just missing something, but I am not able to get it to work with your library.

Best regards
Adrian

**Comment by mikepenz** [comment]
Check out the `AdvancedActivity` it showcases how to switch between hamburger icon and back arrow. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/AdvancedActivity.java

**Comment by Hawlitschek** [comment]
Thanks for the quick reply.
I looked into some of the sample classes, but missed this one :/
Shame on me :D

Maybe you can add this to the Help page, might help a lot of people.

Thanks!
Adrian
