### ISSUE TITLE
Disable swipe to open in content area of MiniDrawer

### ISSUE THREAD

**Issue by timrae** [mikepenz/MaterialDrawer#716]
I've setup the MiniDrawer as per the example app, but my view on the right-hand-side is a ViewPager which uses swipe gestures to navigate between the views. Right swipes are consumed by the drawer which breaks the view pager.

In another Activity we have a button in the action bar that enables / disables drawing with your finger, so we'd need a programmatic way to disable the mini drawer swiping.

**Comment by mikepenz** [comment]
@timrae v1.1.0 of the `Crossfader` library now allows you to disable the swipe

https://github.com/mikepenz/Crossfader
