### ISSUE TITLE
Transparent gravatar support

### ISSUE THREAD

**Issue by livotov** [mikepenz/MaterialDrawer#717]
Hi Mike !

We're going to add transparent gravatar support into our clone of your drawer. Would you be interested in committing this feature back to your branch ?

In case of positive answer, what the way implementing transparent gravatar support will fit the library api best ?

- ability to pass email instead of true url into the setIcon(String) method of ProfileDrawerItem (passed text will be checked for email pattern and replaced into the valid gravatar url)
- automatically generate and call setIcon with the generated gravatar url inside the withEmail(String) method of ProfileDrawerItem

Thanks,
Dmitri

P.S. or maybe I did not find the built-in gravatar support in the master branch :D

**Comment by mikepenz** [comment]
@livotov so you implement a helper which creates an **GravatarUrl** from an e-mail adress? How do you check if this e-mail has a gravatar?

**Comment by livotov** [comment]
Yeah, exactly. You can't check this, but in case e-mail does not exists in gravatar, a default (gravatar's one) picture will be returned, so this url will not be broken anyway.

For now it seems to me that both ways should be implemented - in case user sets e-mail only with the  setEmail("...") - an avatar from gravatar or gravatar's default icon will appear anyway, which is nicer than empty circle. If user will call setIcon after setEmail -  this will override the pre-constructed gravatars url and user's icon will appear as it should. And finally, if user explicitly passes an e-mail into the setIcon(url) method - it will be automatically replaces to a valid gravatar's  url.

p.s. maybe also a separate setGravatarEmail method should be added, as it is not too clear that setIcon(url) may also accept e-mail addresses :)

**Comment by mikepenz** [comment]
@livotov i think it is a better idea to make a separat module or addon, or probably util class instead of chaining it deeply into the `MaterialDrawer` as this is a really special use-case. So people can choose to have it, and it will only require a bit more code to write if they choose to. 

I don't think it's good to have it deeply integrated, but the idea of having a util which generates `Gravatar` urls for you is great

**Comment by livotov** [comment]
@mikepenz hm, that sounds reasonable too

**Comment by mikepenz** [comment]
@livotov but i still think this is a really great idea. It's up to you if you want to provide it as util and add a **pull request** or if you create a **standalone library** which can then be used for any project out there ;)
