### ISSUE TITLE
Primary vs. Secondary Drawer Item

### ISSUE THREAD

**Issue by nasser-souti** [mikepenz/MaterialDrawer#718]
Thank you for the great job.
I am touching the library for few hours, and I still could not recognize the main difference between Primary Drawer Items and Secondary ones.
Would you please clarify?
I would appreciate
Thanks

**Comment by mikepenz** [comment]
@nasser-souti the `SecondaryDrawerItem` has a different height, and a smaller icon. 

To be exact here are the dimensions of the `PrimaryDrawerItem`:
**height**: 48dp, **icon** 24dp
The dimensions of the `SecondaryDrawerItem`
**height**: 42dp, **icon** 18dp

Best, 
Mike

**Comment by nasser-souti** [comment]
Thanks millions for prompt response....

**Comment by mikepenz** [comment]
@nasser-souti no problem ;)
