### ISSUE TITLE
Remove the current and only ProfileDrawerItem

### ISSUE THREAD

**Issue by TroniPM** [mikepenz/MaterialDrawer#719]
When i remove the current and only  ProfileDrawerItem of a header, i "can" remove it (the object), but in the header still the ProfileDrawerItem data (the name and email). What can i do?

**Comment by TroniPM** [comment]
The profile inserted
![1](https://cloud.githubusercontent.com/assets/9244381/10307525/01ea3e36-6c06-11e5-9fd8-5eac4192e60a.png)

The profile removed
![2](https://cloud.githubusercontent.com/assets/9244381/10307540/1b945538-6c06-11e5-92da-86553b059368.png)

I'm removing the profile like that (inside a loop):
if (mHeader.getProfiles().get(i).getEmail().toString().equals(emailToCompare) {
     mHeader.removeProfile(mHeader.getProfiles().get(i));
}

**Comment by mikepenz** [comment]
@TroniPM thanks for the report. This is a bug and will be fixed in v4.3.3
