### ISSUE TITLE
Toolbar Title is really small in landscape

### ISSUE THREAD

**Issue by Fleker** [mikepenz/MaterialDrawer#72]
In portrait mode on my phone, calling `mToolbar.setTitle("My History");` will display the title as expected. However, in landscape the text is much smaller than expected.

The activity style is a derivative of `MaterialDrawerTheme.Light.TranslucentStatus`, with changes to colors.

In the xml, the `layout_height` is `wrap_content`, and the `minHeight` is `?attr/actionBarSize`

**Comment by mikepenz** [comment]
do you use your toolbar like this? including the relativeLayout (this will help with compatibility on different phones or tablets).
```java
<RelativeLayout
        android:id="@+id/activity_main_toolbar_container"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="?attr/colorPrimary"
        android:paddingTop="@dimen/tool_bar_top_padding">
        <android.support.v7.widget.Toolbar
            android:id="@+id/activity_main_toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            android:elevation="4dp"/>
    </RelativeLayout>
```

**Comment by Fleker** [comment]
Here's what I have in my layout

    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".Stream">
    
    <LinearLayout
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <android.support.v7.widget.Toolbar
            android:id="@+id/my_awesome_toolbar"
            android:layout_height="wrap_content"
            android:layout_width="match_parent"
            android:paddingTop="24dp"
            android:minHeight="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            />

**Comment by mikepenz** [comment]
@Fleker try using the layout i've posted for the toolbar.

**Comment by Fleker** [comment]
I'm still getting this issue with a relativelayout

**Comment by mikepenz** [comment]
@Fleker can you please add a screenshot?

**Comment by Fleker** [comment]
Here's screenshots from the app:
<img src="https://lh5.googleusercontent.com/-0bBPc8kscj4/VPtd5f9JN8I/AAAAAAAAekw/D6PqlHKSGdM/w500-h889-no/Screenshot_2015-03-07-15-20-56.png">

<img src="https://lh5.googleusercontent.com/-I0xxms5cKCs/VPtd5zCHhJI/AAAAAAAAek8/GiTKXLdboLk/w1280-h720-no/Screenshot_2015-03-07-15-21-04.png">

**Comment by mikepenz** [comment]
seems strange. have you copied the whole xml i posted or you've jsut added the relativelayout around your toolbar?

**Comment by Fleker** [comment]
I replaced the `FrameLayout` with `RelativeLayout` and moved the toolbar to be a direct child of the RelativeLayout. All the other layout information stayed the same.

**Comment by mikepenz** [comment]
please try to replace the toolbar (including all layoutparams) with the one i posted above. (just modify the id to fit your environmenT)

**Comment by Fleker** [comment]
I replace the layout to be the one you provided and I'm still seeing this issue:

<img src="https://lh3.googleusercontent.com/umLJ01WEp1PHXF-WHHte7UyaujytgmMoMcj5cKzgIBbd=w1280-h720-no">

**Comment by mikepenz** [comment]
It looks normal now.

**Comment by Fleker** [comment]
The font size hasn't changed on landscape

**Comment by mikepenz** [comment]
yeah but the font size ist lower on landscape. i also see this on a nexus 7 with other things not only my style. as long as it aligns correct.

**Comment by Fleker** [comment]
Ok. I suppose it's not a valid issue then.

**Comment by mikepenz** [comment]
@Fleker i'll close it now. 

if you find anything new regarding this thing let me know. i'll try to help as much as possible.
