### ISSUE TITLE
Soft keyboard problem.

### ISSUE THREAD

**Issue by ray1984** [mikepenz/MaterialDrawer#721]
I've already read https://github.com/mikepenz/MaterialDrawer/blob/master/README.md#i-have-problems-with-the-softkeyboard-how-can-i-fix-this and related issues, but it didn't help me. 
I disable translutentStatusBar in accountHeader
```java
AccountHeader accountHeader = new AccountHeaderBuilder()
                .withActivity(activity)
                ...
                .withTranslucentStatusBar(false)
                .build();
```
And enable it in drawerBuilder
```java
DrawerBuilder drawerBuilder = new DrawerBuilder()
                .withActivity(activity)
                .withToolbar(toolbar)
                ...
                .withTranslucentStatusBar(true)
                .withAccountHeader(accountHeader)
```
Of course, I enable keyboard support.
My app theme - windowTranslucentStatus is true:
```xml
<style name="AppTheme.Base" parent="MaterialDrawerTheme">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorAccent">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@null</item>
        <item name="windowActionBar">false</item>
        <item name="windowActionBarOverlay">true</item>
        <item name="android:windowActionBarOverlay">true</item>
        <item name="android:windowBackground">@color/window_background</item>
        <item name="android:windowActionModeOverlay">true</item>
        <item name="windowActionModeOverlay">true</item>
        <item name="material_drawer_background">@color/window_background</item>
        <item name="material_drawer_primary_text">@color/primary_text_color</item>
        <item name="material_drawer_selected">@color/window_background</item>
        <item name="material_drawer_selected_text">@color/curious_blue</item>
        <item name="android:windowAnimationStyle">@null</item>
        <item name="android:actionMenuTextAppearance">@style/ActionMenuTextAppearance</item>
        <item name="android:windowTranslucentStatus">true</item>
        <item name="android:actionOverflowButtonStyle">@style/overflow</item>
        <item name="actionOverflowButtonStyle">@style/overflow</item>
    </style>
```
But I even receive bad work of soft keyboard. When it is opened, I can't scroll content to bottom
![screenshot_2015-10-06-12-24-10](https://cloud.githubusercontent.com/assets/3238570/10303666/f2776a42-6c1d-11e5-89b8-882c294219ae.png)

**Comment by mikepenz** [comment]
@ray1984 ok if the `KeyboardUtil` does not help in your case, it seems the only solution is that you disable fullscreen (so translucent statusbar) at all. theme etc. and have a drawer which is below the `StatusBar` as the fullscreen flag causes this problem.

**Comment by mikepenz** [comment]
@ray1984 it would be great if you could provide a sample showcasing this issue. perhaps i can improve the `KeyboardUtil`

**Comment by ray1984** [comment]
Ok, I'll write demonstrate project. In addition, my problem exists only in tablets, and not only lollipop, but in android 4.0.3 too. Can it help you to find the cause?

**Comment by mikepenz** [comment]
@ray1984 the demonstration project would help me best. so i can reproduce it and test a few things why this could happen

**Comment by ray1984** [comment]
I find cause of error. In tablet I use Drawer Layout. You can see project https://github.com/ray1984/DrawerTestProject 
I try to make builder.withDrawerLayout(drawerLayout); but I'm getting that error
java.lang.OutOfMemoryError: Failed to allocate a 22504152 byte allocation with 16777216 free bytes and 19MB until OOM
            at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
            at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:125)
            at java.lang.StringBuffer.append(StringBuffer.java:278)
            at java.io.StringWriter.write(StringWriter.java:123)
            at com.android.internal.util.FastPrintWriter.flushLocked(FastPrintWriter.java:358)
            at com.android.internal.util.FastPrintWriter.appendLocked(FastPrintWriter.java:303)
            at com.android.internal.util.FastPrintWriter.write(FastPrintWriter.java:625)
            at com.android.internal.util.FastPrintWriter.append(FastPrintWriter.java:658)
            at java.io.PrintWriter.append(PrintWriter.java:691)
            at java.io.PrintWriter.append(PrintWriter.java:31)
            at java.lang.Throwable.printStackTrace(Throwable.java:324)
            at java.lang.Throwable.printStackTrace(Throwable.java:300)
            at android.util.Log.getStackTraceString(Log.java:340)
            at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:59)
            at com.android.internal.os.RuntimeInit.access$200(RuntimeInit.java:43)
            at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:85)
            at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
            at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

**Comment by mikepenz** [comment]
@ray1984 i don't think those two things are the same. i will take a look later

**Comment by ray1984** [comment]
You can reproduce error if you'll run app on tablet

**Comment by mikepenz** [comment]
@ray1984 I am not really sure what you want to show with your sample. why do you provide the `DrawerLayout` including the slide container and the drawer content for tablet, and not for the phone. what's the purpose of this?

**Comment by ray1984** [comment]
In my project I should show some content like this 
![drawer_usage](https://cloud.githubusercontent.com/assets/3238570/10359790/79814238-6da4-11e5-9318-5363b69e1b49.jpg)
And usage of Drawer Layout is appropriate for me

**Comment by ray1984** [comment]
In my sample I want to show you a StackOverflowError

**Comment by mikepenz** [comment]
@ray1984 but the `MaterialDrawer` already manages the `DrawerLayout` for you, so no need to add it to the xml?

The latest screenshot also looks like that you will need 2 different `DrawerLayouts` as the right drawer is fullscreen and the left one is below the `Toolbar``

**Comment by ray1984** [comment]
Finally, I remove my DrawerLayout and now I'm using material DrawerLayout - all work fine

**Comment by mikepenz** [comment]
@ray1984 yeah there are so many combinations on how to setup the drawer. :D it is very flexible and i can't prevent wrong usage in all areas :D

Great that you got it working ;)
