### ISSUE TITLE
Status bar colour

### ISSUE THREAD

**Issue by lalkrishna** [mikepenz/MaterialDrawer#724]
In android Studio's Design section, i can see a Perfectly working status bar. But when i'm trying to run my project it resulting the Status bar with NO Color. Do you have any idea about this issue?

![issue](https://cloud.githubusercontent.com/assets/2138976/10337527/de670746-6d1d-11e5-9f24-c6e3f3c82fa5.JPG)

My Style is:
```xml
<style name="AppTheme" parent="MaterialDrawerTheme.Light.DarkToolbar">
        <item name="colorPrimary">@color/material_drawer_primary</item>
        <item name="colorPrimaryDark">@color/material_drawer_primary_dark</item>
        <item name="colorAccent">@color/material_drawer_accent</item>
        <item name="material_drawer_background">@color/material_drawer_background</item>
        <item name="material_drawer_primary_text">@color/material_drawer_primary_text</item>
        <item name="material_drawer_primary_icon">@color/material_drawer_primary_icon</item>
        <item name="material_drawer_secondary_text">@color/material_drawer_secondary_text</item>
        <item name="material_drawer_hint_text">@color/material_drawer_hint_text</item>
        <item name="material_drawer_divider">@color/material_drawer_divider</item>
        <item name="material_drawer_selected">@color/material_drawer_selected</item>
        <item name="material_drawer_selected_text">@color/material_drawer_selected_text</item>
        <item name="material_drawer_header_selection_text">@color/material_drawer_header_selection_text</item>
    </style>
```

**Comment by mikepenz** [comment]
@lalkrishna i don't think the theme manager is a good reference on how it will look on the device as there happens enough stuff programmatically which can't be shown with the Design section in Android Studio. 

How have you set up your drawer? 

You can check and see a simple usage of the Drawer here: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java

You can also install the demo app which is available via the releases section:
https://github.com/mikepenz/MaterialDrawer/releases

**Comment by lalkrishna** [comment]
I got Drawer properly. Its really simple & cool to operate. I have only a Problem with ActionBar color. (Color PromaryDark) not Showing on ActionBar.
![issue_reply](https://cloud.githubusercontent.com/assets/2138976/10338493/f338366c-6d23-11e5-8af2-9bf520b73b44.JPG)

**Comment by mikepenz** [comment]
@lalkrishna do you have an `ActionBar` or `Toolbar`? 

Theme for `Toolbar` has to be applied separately as shown in the sample:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/activity_sample_dark_toolbar.xml#L12

**Comment by lalkrishna** [comment]
Toolbar. I have include Layout & Manifest File here.
I have referred your  LollyPopShowcase code.

LayoutFile:
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    >


    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        android:elevation="4dp"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
        android:transitionName="actionBar"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
        android:layout_alignParentTop="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true" />
    <RelativeLayout
        android:layout_width="wrap_content"
        android:layout_below="@+id/toolbar"
        android:paddingLeft="@dimen/activity_horizontal_margin"
        android:paddingRight="@dimen/activity_horizontal_margin"
        android:paddingTop="@dimen/activity_vertical_margin"
        android:paddingBottom="@dimen/activity_vertical_margin"
        android:layout_height="wrap_content"
        android:id="@+id/relativeLayout">

    </RelativeLayout>

</RelativeLayout>

Manifest File:

<application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:theme="@style/MaterialDrawerTheme.Light.DarkToolbar"
        android:label="@string/app_name" >
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:launchMode="singleTask" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name=".WizardActivity"
            android:label="Wizard"
            android:launchMode="singleTask"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar" >
        </activity>

**Comment by mikepenz** [comment]
Your actionBar uses the `android:background="?attr/colorPrimary"` color

**Comment by lalkrishna** [comment]
So? should I remove that line?

**Comment by mikepenz** [comment]
@lalkrishna as the `Toolbar` is nothing MaterialDrawer specific it's up to you. But with this line you set the color to the `colorPrimary` not to `colorPrimaryDark`
