### ISSUE TITLE
Actionbar fires a redirection to the first menu when goes from portrait to landscape

### ISSUE THREAD

**Issue by TroniPM** [mikepenz/MaterialDrawer#725]
When the device is in portrait and goes to landscape, the actionbar fires a 'redirection' to the first "menu" after the header, and vice versa (from landscape to portrait). Is this a default action? Where can i override this?

**Comment by TroniPM** [comment]
I figure it out. The onCreate() activity is called. Just try save the current state and restore after.

**Comment by mikepenz** [comment]
State save is shown in the sample app

**Comment by mikepenz** [comment]
see here:

withSavedInstance
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L190

onSaveInstance
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L224

**Comment by TroniPM** [comment]
Perfect!
