### ISSUE TITLE
I need to rename the current user, but it doesn't work properly

### ISSUE THREAD

**Issue by TroniPM** [mikepenz/MaterialDrawer#726]
When I use ```header.getActiveProfile().withName();``` It just changes the name in the List (users registered), but the Header doesn't change (like bug in #719). How can i reset the textview (or whatever it is) ?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/AdvancedActivity.java#L161

**Comment by TroniPM** [comment]
It's deprecated. Can i use this even so?

**Comment by mikepenz** [comment]
ok use this one
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L188

**Comment by TroniPM** [comment]
Perfect
