### ISSUE TITLE
Question: Animation in Profile

### ISSUE THREAD

**Issue by seba123neo** [mikepenz/MaterialDrawer#727]
Mike, I have updated the version of the library that is in google play, and now I see that by pressing the "arrow" to access profiles, now shows with "animation".

in my project, I updated the library but still the same, showing no animation in profiles

which it is the property to display the animation ?

Thanks.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L111

The animation will be shown trough the `DefaultItemAnimator` which is automatically set on the `RecyclerView` when the `RecyclerView` has the `setHasStableIds(true)` set. which can be done when you build the `MaterialDrawer` with `.withHasStableIds(true)`

**Comment by seba123neo** [comment]
thanks..now works !

**Comment by mikepenz** [comment]
:stuck_out_tongue:
