### ISSUE TITLE
how to remove badge?

### ISSUE THREAD

**Issue by dominicsavb** [mikepenz/MaterialDrawer#728]
How to remove this badge?

Now I'm using nav.updateBadge(identifier, "");

Thank you
![screenshots_2015-10-09-13-03-06](https://cloud.githubusercontent.com/assets/6405946/10386896/7425800a-6e86-11e5-953d-d857512217f1.png)

**Comment by mikepenz** [comment]
@dominicsavb set it to `null`

**Comment by dominicsavb** [comment]
solved!
Thank you

**Comment by msegmx** [comment]
Hi Mike,

I'm still having problems : set exactly what to null ?
withBadge(..) has 2 versions (String and StringHolder), setting it to null raises a compile time error.
and there's no update.. method.
Help, please.

**Comment by mikepenz** [comment]
can't you use `withBadge((String)null)`

**Comment by msegmx** [comment]
yeah, that would've worked too.
I used updateBadge on the drawer.

Anyway thanks for quick response.
