### ISSUE TITLE
how to change On/off image at ToggleDrawerItem

### ISSUE THREAD

**Issue by dominicsavb** [mikepenz/MaterialDrawer#729]
how to change ON/OFF image at ToggleDrawerItem? 

Thank you
![screenshot_2015-10-09-13-45-17](https://cloud.githubusercontent.com/assets/6405946/10387636/43688afa-6e8d-11e5-9868-69b6a3e25a99.png)

**Comment by mikepenz** [comment]
@dominicsavb you will have to implement a `CustomDrawerItem` (or you hook in with a `onPostBindView` listener and modify the view)

http://stackoverflow.com/a/32542999/325479
http://stackoverflow.com/a/32543209/325479

**Comment by dominicsavb** [comment]
any example for ToggleDrawerItem? 

Thank you

**Comment by mikepenz** [comment]
The source of the `ToggleDrawerItem` can be found here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ToggleDrawerItem.java

the easiest solution for you is to copy this. add it to your project and modify it to your needs

**Comment by dominicsavb** [comment]
What's wrong with this error?

java.lang.RuntimeException: Unable to start activity ComponentInfo{dominicus.bernardus.ekatolik/dominicus.bernardus.ekatolik.MainActivity}: java.lang.ClassCastException: dominicus.bernardus.ekatolik.helper.CustomToggleDrawerItem cannot be cast to com.mikepenz.materialdrawer.model.ToggleDrawerItem
