### ISSUE TITLE
Cancel currently selected item

### ISSUE THREAD

**Issue by cynephoba** [mikepenz/MaterialDrawer#732]
Hi,

I'm just wondering if there's a way to cancel the currently selected item. At the moment i'm using the `result.setSelectionByIdentifier()` method, however when they click on the AccountHeader i wish to have no item displayed as being selected in the drawer (as the accountheader click takes them to a new fragment which isn't listed again in the drawer). I have tried using `result.setSelection(-1)` inside `withOnAccountHeaderSelectionViewClickListener()` but i get a null pointer exception for that.

Also, you have the option `withProfileImagesClickable(bool)`. Just wondering if there is an onclick listener that we can define for this - as i'm wishing to have the ability to display the fragment whether they click on either the image or the header

**Comment by mikepenz** [comment]
@cynephoba the `NullPointerException` is not thrown by the library but your code. 
If you set the selection to `-1`, it will also trigger the `onDrawerItemClickListener` with position `-1` and as there is no `DrawerItem` with an `drawerItem` which is `null` so you should check for null there. 

There is the `OnAccountHeaderListener` on the header which will also fire when you click on a profile image. 

Best,
Mike

**Comment by cynephoba** [comment]
I knew the null pointer was from my code - i was trying to see if it worked the same as `.withSelectedItem(-1)` but apparently not. Is there another way to make no item highlighted on the fly? Because at the moment if i go from another menu item to clicking on the accountheader, the old item still stays highlighted.

**Comment by mikepenz** [comment]
@cynephoba just check if the `drawerItem` is not `null` in the listener and you are fine. calling `withSelectedItem(-1)` is correct. 

can you perhaps show what you mean with screenshots? i'm not really sure

**Comment by cynephoba** [comment]
![image](https://cloud.githubusercontent.com/assets/5505707/10419648/80b08910-70c9-11e5-9b4a-dc046d5492d1.png)

See how "Forums" is highlighted - currently it is displaying the fragment related to that menu option so it is highlighted. However if i then click on the header where it says "Not logged in", i have it set so it takes me to a new fragment - but the "Forums" stays highlighted as that was the last 'menu' option that the user visited. I'm wanting to be able to 'unhighlight' any other menu item when i click on the account header

**Comment by mikepenz** [comment]
As mentioned `withSelectedItem(-1)` will deselect the selection. just `null`-check inside the listener as it will fire it with a `null` drawerItem. 

In general items can be selecatable or not selectable by setting `withSelectable(true/false)` on them
