### ISSUE TITLE
Icons keep left in RTL

### ISSUE THREAD

**Issue by vd92** [mikepenz/MaterialDrawer#733]
Hi and thank you for this great library
It has solved my problem to make a rtl drawer but is think a tiny issue is there . when i make drawer rtl everything go right but icon's keep in left side of drawer . Can you please explain how to do this ?

**Comment by mikepenz** [comment]
@vd92 how did you make your drawer **RTL**? is your complete app in RTL mode?

**Comment by vd92** [comment]
Thank you for your light speed respond 
I just add .withDrawerGravity(Gravity.RIGHT) into DrawerBuilder

**Comment by mikepenz** [comment]
this will not set your app into `RTL` mode. That just moves the drawer to the right.

If you enable this line:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/AndroidManifest.xml#L11
And this line:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L54

The app is in real RTL mode

**Comment by vd92** [comment]
Thank you again . its work like a charm
isn't there any other way to do this ? because android:supportsRtl="true"  requires api 17

**Comment by mikepenz** [comment]
RTL support does not exist prior API 17

**Comment by vd92** [comment]
anyway, I wish You best's
