### ISSUE TITLE
Right To Left

### ISSUE THREAD

**Issue by SaeedDarvish** [mikepenz/MaterialDrawer#734]
hi...
at the first a have to say thank for for this...
can i put menu button on action bar at right of action bar.... ?
how can i do it .....  ?

**Comment by mikepenz** [comment]
@SaeedDarvish nothing **MaterialDrawer** specific. That's something android **RTL** specific. 

But this should help
https://github.com/mikepenz/MaterialDrawer/issues/733#issuecomment-147199204
