### ISSUE TITLE
Open DrawerBuilder by button

### ISSUE THREAD

**Issue by DaniloPolani** [mikepenz/MaterialDrawer#735]
Hello,
is there a way to open a DrawerBuilder (put on the right side) by clicking on a button?

Thanks in advance

**Comment by mikepenz** [comment]
@DaniloPolani after you built the drawer you will have a `Drawer` object and this has a method to open the specific drawer
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L114
