### ISSUE TITLE
Create a "section header"

### ISSUE THREAD

**Issue by DaniloPolani** [mikepenz/MaterialDrawer#737]
Hi,

I've a simple question: how can I make a "section header" like the screenshot? Is it a SecondaryDrawerItem with selectable and enabled to false or what?

Thank you.

**Comment by mikepenz** [comment]
@DaniloPolani you nearly had it with your question header ;)
It's called `SectionDrawerItem` showcased in the sample app:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L127

Best,
Mike
