### ISSUE TITLE
Non-selectable items don't fire OnDrawerItemClickListener() in MiniDrawer

### ISSUE THREAD

**Issue by tomredman** [mikepenz/MaterialDrawer#738]
The MiniDrawer only fires an `onClick` if the item being tapped is `selectable` (via `setSelected()`). Here's a potential solution that allows the implementing developer to act on their non-`selectable` `IDrawerItem` taps:

    this.mDrawerAdapter.setOnClickListener(new BaseDrawerAdapter.OnClickListener() {
            public void onClick(View v, int position, IDrawerItem item) {
                int type = MiniDrawer.this.getMiniDrawerType(item);
                if(type == ITEM) {
                    if(MiniDrawer.this.mDrawerAdapter != null) {
                        if (item.isSelectable()) {
                            MiniDrawer.this.mDrawer.setSelection(item, true);
                        }
                        else if (MiniDrawer.this.mDrawer.getOnDrawerItemClickListener() != null) {
                            MiniDrawer.this.mDrawer.getOnDrawerItemClickListener().onItemClick(v, position, item);
                        }
                    }
                } else if(type == PROFILE) {
                    if(MiniDrawer.this.mAccountHeader != null && !MiniDrawer.this.mAccountHeader.isSelectionListShown()) {
                        MiniDrawer.this.mAccountHeader.toggleSelectionList(v.getContext());
                    }

                    if(MiniDrawer.this.mCrossFader != null) {
                        MiniDrawer.this.mCrossFader.crossfade();
                    }
                }
            }
        });

**Comment by mikepenz** [comment]
@tomredman thanks for the report. You are right this is a bug. 

Thank you for your solution. It is correct, but misses a single point. If you return the `item` which is the `MiniDrawerItem` you will probably loose some information (as the name), and if you use it you will crash. 

So here's the code i will include in the next version:

```java
 //listener
        mDrawerAdapter.setOnClickListener(new BaseDrawerAdapter.OnClickListener() {
            @Override
            public void onClick(View v, int position, IDrawerItem item) {
                int type = getMiniDrawerType(item);
                if (type == ITEM) {
                    //fire the onClickListener also if the specific drawerItem is not Selectable
                    if (item.isSelectable()) {
                        mDrawer.setSelection(item, true);
                    } else if (mDrawer.getOnDrawerItemClickListener() != null) {
                        //get the original `DrawerItem` from the Drawer as this one will contain all information
                        mDrawer.getOnDrawerItemClickListener().onItemClick(v, position, mDrawer.getDrawerItem(item.getIdentifier()));
                    }
                } else if (type == PROFILE) {
                    if (mAccountHeader != null && !mAccountHeader.isSelectionListShown()) {
                        mAccountHeader.toggleSelectionList(v.getContext());
                    }
                    if (mCrossFader != null) {
                        mCrossFader.crossfade();
                    }
                }
            }
        });
```

**Comment by mikepenz** [comment]
@tomredman v4.3.5 pushed to maven central

**Comment by tomredman** [comment]
Awesome, thanks so much @mikepenz! This library is absolutely outstanding. We're using in our new [Buffer for Android](https://play.google.com/store/apps/details?id=org.buffer.android&hl=en) app, and will be sure to give credit!

**Comment by mikepenz** [comment]
@tomredman thank you so much! It's great that i am able to help many devs around the world with my libs ;). 

I'll add you to the Apps which use my libs section in the readme if it's ok for you?
