### ISSUE TITLE
Use account header icons to represent most recent profiles

### ISSUE THREAD

**Issue by fdorssers** [mikepenz/MaterialDrawer#74]
I think it would be nice to use the account icons at the top of the account header to represent the most recent accounts that were used.

For example if you have three account icons and you select the third one:

Accounts | Current result | New result
------------ | ----------------- | --------------
1 2 3 | 3 2 1 |  3 1 2

Or if you have a fourth item in the drawer and select that:

Accounts | Current result | New result
------------ | ----------------- | --------------
1 2 3 | 4 2 3 |  4 1 2

**Comment by mikepenz** [comment]
@fdorssers will be released with the next version

**Comment by fdorssers** [comment]
Awesome, thanks.
