### ISSUE TITLE
Custom Header in Drawer

### ISSUE THREAD

**Issue by patelakshay13890** [mikepenz/MaterialDrawer#740]
How can i have custom header in drawer with Expandable Layout but with Custom Layout ??
As in clicking compact header it shows profile, i want to show custom row in that list with custom layout and it should expand on clicking Compact Header which it self has a Custom Layout??

**Comment by mikepenz** [comment]
@patelakshay13890 to make sure i understand you correctly

You want a Header like the `AccountHeader` which also toggles the item shown in the drawer on click. 
It will then show new items which are no profile items? 

How many differences does this custom header have to the compact header?
How will those custom items look like?

**Comment by patelakshay13890** [comment]
Yes , I want a Header like the AccountHeader which also toggles the item
shown in the drawer on click and
It will then show new items which are no profile items..

**Comment by mikepenz** [comment]
@patelakshay13890 in fact those two methods are the most important for switching the drawer content:

```java
/**
     * onSelectionClickListener to notify the onClick on the checkbox
     */
    private View.OnClickListener onSelectionClickListener = new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            boolean consumed = false;
            if (mOnAccountHeaderSelectionViewClickListener != null) {
                consumed = mOnAccountHeaderSelectionViewClickListener.onClick(v, (IProfile) v.getTag(R.id.material_drawer_profile_header));
            }

            if (mAccountSwitcherArrow.getVisibility() == View.VISIBLE && !consumed) {
                toggleSelectionList(v.getContext());
            }
        }
    };

    /**
     * helper method to toggle the collection
     *
     * @param ctx
     */
    protected void toggleSelectionList(Context ctx) {
        if (mDrawer != null) {
            //if we already show the list. reset everything instead
            if (mDrawer.switchedDrawerContent()) {
                resetDrawerContent(ctx);
                mSelectionListShown = false;
            } else {
                //build and set the drawer selection list
                buildDrawerSelectionList();

                // update the arrow image within the drawer
                mAccountSwitcherArrow.setImageDrawable(new IconicsDrawable(ctx, MaterialDrawerFont.Icon.mdf_arrow_drop_up).sizeRes(R.dimen.material_drawer_account_header_dropdown).paddingRes(R.dimen.material_drawer_account_header_dropdown_padding).color(ColorHolder.color(mTextColor, ctx, R.attr.material_drawer_header_selection_text, R.color.material_drawer_header_selection_text)));
                mSelectionListShown = true;
            }
        }
    }
```

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L1163

**Comment by mikepenz** [comment]
@patelakshay13890 if you need more help let me know ;)

**Comment by patelakshay13890** [comment]
Yes I need your help
But I want Custom Layout for Header and it's Sliding Content

**Comment by mikepenz** [comment]
@patelakshay13890 custom layout for sliding content?

**Comment by patelakshay13890** [comment]
Yes, just like multiple Email add. instead there I want to have Custom Row
with Button & TextView.
So how can i achieve this ??

**Comment by mikepenz** [comment]
@patelakshay13890 please provide a screenshot or anything. 

Using a custom layout is shown here:

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/PersistentDrawerActivity.java#L69

It also has a custom action on a view which is inside this layout and not handled by the drawer:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/PersistentDrawerActivity.java#L125

**Comment by patelakshay13890** [comment]
Which view is used for toggle the  Email in sample app ?

**Comment by patelakshay13890** [comment]
I want to use that view but with TextView & Buttons for each email
address!!!

**Comment by mikepenz** [comment]
@patelakshay13890 your description is not clear enough. please post a wireframe or screenshot or design or anything which showcases what you want to achieve.

**Comment by patelakshay13890** [comment]
​

**Comment by mikepenz** [comment]
@patelakshay13890 i think your answer went wrong. no content

**Comment by patelakshay13890** [comment]
So how can I do this using MaterialDrawer lib. ??

**Comment by mikepenz** [comment]
@patelakshay13890 i have to repeat it one last time. I can't help you as long as i do not understand what you really want to achieve. 

Your descriptions were not clear enough (at least for me) 

Please provide a screenshot or design which shows what you want to achieve. 
Is it anything specified in the Material Design Guidelines?

**Comment by iplusMario** [comment]
Mike is it possible to use a custom header without the picture icon and without the events

![image](https://cloud.githubusercontent.com/assets/28944792/26626360/4dab528e-45f7-11e7-9cbf-16a73ea7df4a.png)

**Comment by iplusMario** [comment]
My question is can I put my own custom layout inside the header

**Comment by mikepenz** [comment]
@iplusMario read this thread. one of the answers exactly states what you can do

**Comment by pejmanghorbani** [comment]
@mikepenz  plz write a class and use objects instead of user slider with one user profile information...
thank u
