### ISSUE TITLE
Add DrawerItems dynamically

### ISSUE THREAD

**Issue by vasiledoe** [mikepenz/MaterialDrawer#741]
I' am trying to add items 'PrimaryDrawerItem' dinamicaly using a list ( ArrayList<PrimaryDrawerItem> listItems ) , and found the only aviable method withDrawerItems(ArrayList<IDrawerItem>) witch doesn't allow us to use 'PrimaryDrawerItem'  => error says:

![error](https://cloud.githubusercontent.com/assets/15106474/10480552/7c322776-7273-11e5-9fe8-ecb6a953efc0.jpg)

any ideas?

**Comment by mikepenz** [comment]
@vasiledoe you list should be an `ArrayList<IDrawerItem>` the `PrimaryDrawerItem` implements this interface.
