### ISSUE TITLE
Question about MaterialDrawer on Tablet.

### ISSUE THREAD

**Issue by Ks89** [mikepenz/MaterialDrawer#743]
Hi!
I want to use this library for smartphone...done, perfect and good work XD.

But, i also want to use the same library to show a fixed "drawer" into the layout on tablets. I.e. a Multi-pane layout.
How can i achieve this?

Thank you,
Stefano

**Comment by mikepenz** [comment]
@Ks89 hi

Depending on your needs you have a few possibilities. 

But i assume the best solution is that you create your drawer as you do currently. but you put the `.build()` within an `if`-statement. in the case when you are on a phone you build it as you currently do. in the other case you can then use the `.buildView()` method to only build the drawer but do not automatically inflate it. Then you can simply use the view and place it where you want it. This is showcased in the **EmbeddedDrawerActivity**

To be more specific here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/EmbeddedDrawerActivity.java#L134

**Comment by Ks89** [comment]
Thank you very much. It's working perfectly.

I've a suggestion:
can you add this answer (and an image like this http://i.stack.imgur.com/k1Cpx.png) directly in the FAQ? I think that can be very useful for a lot of people.

**Comment by mikepenz** [comment]
@Ks89 the FAQ should be more community driven :D so would really love for people doing pull request and add questions / answers they had ;).
