### ISSUE TITLE
 drawerBuilder.withCloseOnClick(true)

### ISSUE THREAD

**Issue by dab13491** [mikepenz/MaterialDrawer#744]
Hi mike

As i assume, my drawer will be closed when i click/select on any of it's items. but my drawer is not being closed.

**Comment by mikepenz** [comment]
@dab13491 you should return `false` in the `onDrawerItemClick` listener:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L190

Here's the description why:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L941

**Comment by dab13491** [comment]
Ohh yes ! thanks for extremly fast reply man !

**Comment by mikepenz** [comment]
@dab13491 no problem ;)
