### ISSUE TITLE
Question about account header's profile image

### ISSUE THREAD

**Issue by Ks89** [mikepenz/MaterialDrawer#745]
Hi Mike.
I've another question. Probably very stupid ;)
I want to add to the drawer an account (only one) with a profile image. 
But, i don't want to see "small down arrow" into the header, because i want only one account with an image. I don't want the default "click listener" on this "small arrow".
How can i achive this?

Or, there is another way to set a profile image (from a Bitmap) into the header's layout?
Because i acquire an image from the disk (as bitmap) and i want to set this image as imageview into the header's layout after the creation of the drawer. 

Thank u.
Stefano.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/454

About setting the bitmap. Just build the profile without an image. And after everything was built, just update the profile with the loaded bitmap ;)
