### ISSUE TITLE
Mini drawer hiding.

### ISSUE THREAD

**Issue by ashokslsk** [mikepenz/MaterialDrawer#746]
HI Great work and amazing library , 

How do i take the minidrawer out from the view but on swipe gesture i need only minidrawer to appear and allow user to trigger the events on clicking the items in the drawer. 
What exactly i mean is i want a mini variant navigation drawer feel, like mentioned in google documentation I believe you will defintely have a solution for this will be waiting for your help.
https://www.google.co.in/design/spec/patterns/navigation-drawer.html#navigation-drawer-behavior

**Comment by mikepenz** [comment]
@ashokslsk could you please link to the screenshot. As far as i know and found there is no `MiniDrawer` variant which can be hidden. Only a normal drawer which is transformed to a `MiniDrawer` on tablets.

**Comment by ashokslsk** [comment]
@mikepenz
Hi please check the below link and let me know can it be achieved like i want mini drawer to be opened only on swipe gesture with view badge on list items in case notification.

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7ZVZzVEhrbF9YWk0/patterns_navdrawer_behavior_persistent4.png

**Comment by mikepenz** [comment]
@ashokslsk the screenshot you linked shows a always visible `MiniDrawer` there's nothing in the Google Material Design Guidelines which specifies a drawer which is used like a normal drawer but in the style of a `MiniDrawer`. 

It is not supported within the **MaterialDrawer**. You will have to use the `MiniDrawer` and add it to a `DrawerLayout` on your own (so you can achieve something like this, but it requires you to write some more code and handle the `DrawerLayout` on your own too)


On a side note. The `PersistentDrawer` pattern (as shown in the linked screenshot) is possible with the **MaterialDrawer**. See the sample app for an implementation:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/PersistentDrawerActivity.java

**Comment by ashokslsk** [comment]
wow @mikepenz  thank you that make sense for my case.

**Comment by mikepenz** [comment]
If you go to use the `MiniDrawer` standalone wrapped in your own `DrawerLayout` keep the following in mind:
* the `MiniDrawer` requires a normal `Drawer` object as datasource
* setup a normal `DrawerBuilder` add your data and everything
* define the listener as shown in the `MiniDrawer` sample
* build the drawer with `.buildView()` (so it won't inflate the `Drawer` into your view)
* add the `Drawer` to your `MiniDrawer` 
* add the `MiniDrawer` view programmatically to your `DrawerLayout`
