### ISSUE TITLE
Add note about .withOnDrawerNavigationListener() to docs on back icon

### ISSUE THREAD

**Issue by timrae** [mikepenz/MaterialDrawer#747]
In the docs it says how to show the back icon:

```java
result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false);
getSupportActionBar().setDisplayHomeAsUpEnabled(true);
```

Actually this isn't enough to get the back icon behavior working... you also have to add the `.withOnDrawerNavigationListener()` part, otherwise the back icon opens the drawer. This isn't really obvious as normally the back icon clicks are handled by `onOptionsItemSelected()`... 

Embarrassingly it took me several hours of debugging to find out why the back button wasn't working, so to save a bit of grief how about mentioning it in the docs?  It would be even better if it could do the "obvious" thing and use the `onOptionsItemSelected()` method when a listener hasn't been set.

**Comment by mikepenz** [comment]
@timrae the back click is only handled via the `onOptionsItemSelected()` if there is no `ActionBarDrawerToggle` set. If you use this, the click will be handled through this one --> which is then passed forward to the `OnDrawerNavigationListener` 

Sorry that you had to search for the solution so long. Basically this is nothing `MaterialDrawer` specific. (Just indirect as i provide the handling of the `ActionBarDrawerToggle` for you)
