### ISSUE TITLE
ContainerDrawerItem.

### ISSUE THREAD

**Issue by Grozny** [mikepenz/MaterialDrawer#749]
How can i customize margin of a ContainerDrawerItem.
I want put in ContainerDrawerItem, a Cardview.
This is possible?

Thanks.

**Comment by mikepenz** [comment]
@Grozny the `ContainerDrawerItem` has no margins. Your content can have those or you create a `CustomContainerDrawerItem` 

Probably you do not need to use the `ContainerDrawerItem` and create a `CardViewDrawerItem`?
