### ISSUE TITLE
Account image overlaps

### ISSUE THREAD

**Issue by alorma** [mikepenz/MaterialDrawer#751]
The account image is above the username.

![image](https://camo.githubusercontent.com/7e238a8975378597eb0e456b85bf02ba949f8c03/687474703a2f2f692e696d67626f782e636f6d2f724c5972484643322e706e67)

**Comment by mikepenz** [comment]
@alorma what's the resolution of this device?

**Comment by alorma** [comment]
Related to gitskarios/Gitskarios#242.

@dikiaap can you provide more info?

**Comment by mikepenz** [comment]
Interesting. Just tried on an emulator with 240x320 and even on this device it's not overlapping. 

@dikiaap can you please also provide information if you have modified your density or anything else?

**Comment by dikiaap** [comment]
@mikepenz Device resolution is 4.5 inch 480 x 854 pixels and I don't modifiy anything.

This has been a long time, I think the latest update yesterday has been repaired.

**Comment by mikepenz** [comment]
@dikiaap so it is fixed now? It's really weird as i test it on devices with all the different resolutions, screen sizes and font sizes

**Comment by dikiaap** [comment]
@mikepenz in my device isn't fixed. this weird.

**Comment by dikiaap** [comment]
whether differences affect the os version?

**Comment by mikepenz** [comment]
i tested it down to API 10 with 480x800

**Comment by mikepenz** [comment]
I really do not know. everything seems really big in this screenshot. you are sure everything is stock? what's the phone you have?

**Comment by dikiaap** [comment]
I change the Roboto font, whyn't automatically resize

**Comment by mikepenz** [comment]
@dikiaap perhaps the font is not handled correct by the Android system.
