### ISSUE TITLE
MiniDrawer problem

### ISSUE THREAD

**Issue by ray1984** [mikepenz/MaterialDrawer#753]
Hello!
I try to implement MiniDrawer ui-pattern in my project with your library, but I receive some troubles. 
First of all, there is no hamburger navigation button in toolbar. How can I return it?

**Comment by mikepenz** [comment]
@ray1984 what do you try exactly? 
Sample code for this pattern can be found here: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java

**Comment by ray1984** [comment]
Your sample doesn't have havigation button too

**Comment by mikepenz** [comment]
@ray1984 the thing is that with a normal environment this is handled by an `ActionBarDrawerToggle` in combination with a `DrawerLayout` as in this setup there is no `DrawerLayout` this can't be used. 
You will have to set up the hamburger icon on your own. i think there are a few tutorials on Stackoverflow

**Comment by fergalmoran** [comment]
I'm struggling with this also - I have a MiniDrawer and can't get the hamburger displayed.
I'm using a Toolbar not an ActionBar, I would love some guidance on getting it working correctly?

**Comment by mikepenz** [comment]
@fergalmoran as mentioned above. The `ActionBarDrawerToggle` (so the animation) requires the `DrawerLayout` which does not exist with the `MiniDrawer`. If you do not need the animation. You can switch between arrow, and hamburger with the normal `Toolbar` settings. 

You have to use the following two methods to change the current state
```java
getSupportActionBar().setDisplayHomeAsUpEnabled(true);
getSupportActionBar().setHomeButtonEnabled(false);
```
and define a `navigationListener` 
This is independent from the library. 

There are many **Stackoverflow** questions regarding this topic:
http://stackoverflow.com/questions/26651602/display-back-arrow-on-toolbar-android
http://stackoverflow.com/questions/28071763/toolbar-navigation-hamburger-icon-missing
http://stackoverflow.com/questions/27230827/back-button-using-getsupportactionbar-and-appcompat-v7-toolbar

**Comment by fergalmoran** [comment]
Thanks for your quick response Mike. Adding the button and displaying it as a hamburger is not an issue for me. 

Where do I add the navigationListener though? Clearly there's a knowledge gap here as the same question has gone unanswered here https://github.com/mikepenz/MaterialDrawer/issues/629

Is there any chance you could update the MiniDrawer sample to include the hamburger menu, as the gmail application does? I think this would be very helpful to a lot of people.

**Comment by mikepenz** [comment]
@fergalmoran wie bei dieser Stackoverflow frage beantwortet wird der navigationListener auf die toolbar gesetzt:
http://stackoverflow.com/questions/26651602/display-back-arrow-on-toolbar-android

**Comment by fergalmoran** [comment]
Thanks for your help Mike.

**Comment by mikepenz** [comment]
@fergalmoran ok so it was the thing you were searching :). Great that it works now :). 

Regarding the question if i should adapt the sample app. I'm not sure, i think this is **standard** android stuff which should be independent of this library, and does not really fit into the sample, which should describe the `Drawer` ;)

**Comment by fergalmoran** [comment]
Well... no... unfortunately I didn't really get any help from here but managed to figure it through a lot of trial & error (and with the current gradle build times, trial & error is quite painful :) ).

I see where you're coming from and perhaps I missed something extremely obvious but I've >5 years experience developing for Android and it took me a lot of messing about to get this working. The mini-drawer with toolbar toggle is an extremely common use-case (it's exactly how the gmail app works) and I think it should be easier to get up and running with.

All that being said, this is one of the most impressive libraries I've used in a long time and has added a huge "wow" factor to our app, there's a real buzz in our office about our app's new UI and we can't wait to release it so thank you so much for this library and all your help!!!
