### ISSUE TITLE
How can I add the ripple effect to every menu item when I click it?

### ISSUE THREAD

**Issue by zhupengGitHub** [mikepenz/MaterialDrawer#754]
I found that you provide the reciprocal of the second image has the effect, how to implement
![image](https://cloud.githubusercontent.com/assets/11845222/10562357/ae424600-758a-11e5-954f-9dcb983dcb89.png)

**Comment by mikepenz** [comment]
@zhupengGitHub ripple effect is only available starting with API 21. It will also not show on a already selected item.
