### ISSUE TITLE
Custom setup for Drawer Items

### ISSUE THREAD

**Issue by Superiom** [mikepenz/MaterialDrawer#757]
I am using quite an old version of the library (0.9.9). It works as intended, however, whenever I use the .withHeader() method, my application misbehaves on orientation change. Either the toolbar title is wrong, on the user is redirected to a totally different activity/fragment. The issue is completely fixed by removing the .withHeader() method. Thus, I have tried to implement a modification of the PrimaryDrawerItem() method -> CustomDrawerHeaderItem(). It extends the PrimaryDrawerItem, and it is supposed to have the role of a Header in the Drawer, by inflating the actual header layout. It totally works, however, the height of the new CustomDrawerHeaderItem has the same value as the PrimaryDrawerItem. Is it possible to modify the styles of the CustomDrawerHeaderItem?

**Comment by mikepenz** [comment]
@Superiom sorry i can't give any support for older versions than the latest one. I highly suggest that you update to the latest one (i know it will require some changes but should be possible within 5 minutes)
