### ISSUE TITLE
Following the Google Material Design Guidelines

### ISSUE THREAD

**Issue by nicolausYes** [mikepenz/MaterialDrawer#758]
I was using an old version of the library (2.7.0) for a long time and now decided to update.

The first thing I've noticed that current version is not following Google Guidelines. According to [guidlines](http://www.google.com.ua/design/spec/patterns/navigation-drawer.html#navigation-drawer-specs) space between the opened drawer and the right side has to be 56dp (the height of the [toolbar](http://www.google.com.ua/design/spec/layout/metrics-keylines.html#metrics-keylines-baseline-grids)).

But current version (4.3.7) has only 48dp. 

![](https://dl.pushbulletusercontent.com/0Jkfe5oMTlkgQeHUln92IatKG8q33N76/Screenshot_2015-10-19-21-11-34.png)![](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3RFk3c3BjS1c1akE/patterns_navdrawer_metrics2.png)

**Comment by mikepenz** [comment]
Hi. 

The method to determine the drawer width is correct:
https://github.com/mikepenz/MaterialDrawer/blob/d94f12c3590a037d1f122d6bff0b00dab728b32a/library/src/main/java/com/mikepenz/materialdrawer/util/DrawerUIUtils.java#L125

I use the screen width - the actionBar height. What phone do you use? is it stock android? without any modifications? on some devices the actionBar width can't be determined correctly

**Comment by nicolausYes** [comment]
I'm using Nexus 5 running android 4.4.4 without modifications.

Here is 2.7.0 (on the top) vs 4.3.7 in my application.

![](https://dl.pushbulletusercontent.com/0wHk8qXmAyFhEBew6OKJNt8OWXvUIDoV/Screenshot_2015-10-19-17-38-26.png)

![](https://dl.pushbulletusercontent.com/Fus0AaIlQysFciw1HeVz0BG5rf1LRzey/Screenshot_2015-10-19-21-00-31.png)

**Comment by mikepenz** [comment]
@nicolausYes thanks for the screenshot. i'm currently testing and double check that i set the correct width

**Comment by mikepenz** [comment]
@nicolausYes can you please install https://play.google.com/store/apps/details?id=com.faizmalkani.keylines and test it with it too? set to "side nav" from the dropdown. On my nexus 5 with marshmallow it is correct.

**Comment by mikepenz** [comment]
![screenshot_20151019-213338](https://cloud.githubusercontent.com/assets/1476232/10588984/2eca6950-76a9-11e5-919a-c7736ae82b27.png)

**Comment by nicolausYes** [comment]
![](https://dl.pushbulletusercontent.com/om8cU7LrZHXzltsxSg7xfeI6OuSY1x9x/Screenshot_2015-10-19-22-39-02.png)

**Comment by mikepenz** [comment]
So android 4.4.4 returns the wrong `actionBarSize` 

Can you check (you have to convert to dp) what this method returns:

```java
public static int getActionBarHeight(Context context) {
        int actionBarHeight = UIUtils.getThemeAttributeDimensionSize(context, android.R.attr.actionBarSize);
        if (actionBarHeight == 0) {
            actionBarHeight = context.getResources().getDimensionPixelSize(R.dimen.abc_action_bar_default_height_material);
        }
        return actionBarHeight;
    }
```

**Comment by nicolausYes** [comment]
This part returning 48.
`int actionBarHeight = UIUtils.getThemeAttributeDimensionSize(this, android.R.attr.actionBarSize);`

**Comment by mikepenz** [comment]
so it seems the `actionBarSize` on devices with Android 4.4.4 is wrong.

**Comment by mikepenz** [comment]
from version 2.7.7 it was the exact same code:
```java
int possibleMinDrawerWidth = UIUtils.getScreenWidth(context) - UIUtils.getThemeAttributeDimensionSize(context, android.R.attr.actionBarSize);
```
https://github.com/mikepenz/MaterialDrawer/blob/v2.7.7/library/src/main/java/com/mikepenz/materialdrawer/util/UIUtils.java#L192

**Comment by mikepenz** [comment]
Just did some more testing. 

It's fine in API 17, it's fine in API 18, it's fine in API 21 

It is only wrong in API 17. I am not sure if it's acceptable to add a hack for API 17 to always return 56dp?

**Comment by nicolausYes** [comment]
I've found the reason why it is working on old version. By the way, I was writing I'm using 2.7.0, but I think the code is the same.

Lets look at this code.

    public static int getOptimalDrawerWidth(Context context) {
        int possibleMinDrawerWidth = UIUtils.getScreenWidth(context) - UIUtils.getThemeAttributeDimensionSize(context, android.R.attr.actionBarSize);
        int maxDrawerWidth = context.getResources().getDimensionPixelSize(R.dimen.material_drawer_width);
        return Math.min(possibleMinDrawerWidth, maxDrawerWidth);
    }

You are right, the code for getting toolbar height is the same and in this case it's returning 48dp too.

The key point is this line.
`int maxDrawerWidth = context.getResources().getDimensionPixelSize(R.dimen.material_drawer_width);`

In old version there are multiple resources. 

    dimens.xml
    <dimen name="material_drawer_width">320dp</dimen>

    sw360dp\dimens.xml
    <dimen name="material_drawer_width">304dp</dimen>

    sw384dp\dimens.xml
    <dimen name="material_drawer_width">320dp</dimen>

    sw600dp\dimens.xml
    <dimen name="material_drawer_width">400dp</dimen>`


And for nexus 5 with 360dp width maxDrawerWidth variable is 304dp. 360 - 304 = 56dp as it should be (by accident). But possibleMinDrawerWidth is wrong, 312dp.

**Comment by nicolausYes** [comment]
I'm targeting API 18.

**Comment by mikepenz** [comment]
@nicolausYes i think i probably found a solution.

```java
        int actionBarHeight = UIUtils.getThemeAttributeDimensionSize(context, R.attr.actionBarSize);
```

will return the correct height

**Comment by nicolausYes** [comment]
Yes, it's returning correct value in my case.

**Comment by mikepenz** [comment]
@nicolausYes i already modified it in the dependency. will be in the next release of the drawer. Thanks for helping

**Comment by nicolausYes** [comment]
Thanks for fast solving :)

**Comment by mikepenz** [comment]
no problem. will take a few more minutes for the new version to be available. currently waiting for the android-iconics dependency and materialize dependency to sync. so i can use the latest version of both

**Comment by mikepenz** [comment]
the new version with the fix should be available shortly
