### ISSUE TITLE
setNavigationOnClickListener avoids calling onOptionsItemSelect on drawers with toolbars

### ISSUE THREAD

**Issue by gpulido** [mikepenz/MaterialDrawer#76]
Hello,
On the last version the drawer handles the setNavigationOnclickListener by itself, the problem is that the "drawer open or closed" is called even if the setDrawerIndicatorEnabled is set to false. As the click on the navigation is "catched" then the onOptionsItemSelect on the activity is not called anymore.

The use case is an Activity that has a first Fragment A on which you want to show the drawertoggle and use the drawer, but when you change the Fragment for Fragment B, you only want to show the "back" button and catch its click to go back.

I'm trying to "know" that the toggle is inactive using this code:

```Java
this.mToolbar.setNavigationOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    //if the drawerToggle is disabled, fall off to the home button action
                    if (!mActionBarDrawerToggle.isDrawerIndicatorEnabled())
                    {
                          //WHAT TO PUT HERE?
                    }
                    else {
                        if (mDrawerLayout.isDrawerOpen(mSliderLayout)) {
                            mDrawerLayout.closeDrawer(mSliderLayout);
                        } else {
                            mDrawerLayout.openDrawer(mSliderLayout);
                        }
                    }

                }
            });
```
If I could find what to put on the if to "call the normal behavior without listener" would be great as this would not interfere with all the structure. But I don't know what to call there.

Any idea?

**Comment by mikepenz** [comment]
@gpulido if you don't want that the drawer handles the `setNavigationOnclickListener` simply don't pass the toolbar to the drawer. as an addition you can also disable the `ActionBarDrawerToggle` with `withActionBarDrawerToggle` this will allow you to handle the everything on your own. 

Then you can simple call `result.openDrawer()`

**Comment by gpulido** [comment]
@mikepenz I already have seen your examples. The problem if I don't pass the toolbar to the drawer (as in the nontranslucentStatusDrawerExample) the toogle button always goes back on click even if you doesn't setDisplayHomeUpAsEnabled. To reproduce just, comment in your nontranslucentStatusDrawerExample the lines 61 and 61 
```Java
//getSupportActionBar().setDisplayHomeAsUpEnabled(true);
//getSupportActionBar().setHomeButtonEnabled(false);
```
Then the activity shows the hamburger icon but when you press it, it goes back instead of showing the drawer (that can be showed by sliding from the left).

I know that I can just use my own toggle and reproduce the behavior to open / close the drawer, and checking if I want to show the back button and handle the onBack, but that would put "drawer inside" code outside the drawer, so it would be better if the drawer itself could handle it.

As I said on the previous post, the problem is that in the moment you subscribe the setNavigationOnClickListener it overrides all the functionality even if the toggledrawer is not enabled!
From my pov the cleanest and more "encapsulated" one solution is that the drawer itself could know that the toggle is not enabled and in that case "resume" normal behavior. That could be accomplish with the if I wrote before, but what I'm missing now is the way to "resume" normal behavior in that case.

**Comment by mikepenz** [comment]
@gpulido yeah i can probably test it later today. 

About the thing that implementing it on your own with a toggle will move drawer code to your application. that's not completely right because the developer is completely free to choose how to show and hide the drawer. even google has not added this to their drawer layout ;).
I'll still try to help you even if it's a main android issue here. nothing specific for the MaterialDrawer. 

I think this is not possible because setNavigationOnClickListener will overwrite the listener which is implemented within the ActionBarDrawerToggle. you can try to set it again for the toggle but i'm not sure if this would work

**Comment by gpulido** [comment]
@mikepenz You are right about Google not enforcing a unique way to do things, but at the end, there are just a few "normal" use cases that are more commonly used. What I really like of your library approach, is that you comply one of the best practices rules: "Makes normal behaviors easy, and not-normal feasible" (sorry for my english).
So, from my pov (please tell me if I'm wrong)  a "normal expected" behavior of the ToggleDrawer would be that if the hamburger icon is showed, a click on the icon would "open / close" the drawer, and if it is showing the back button, a click would call "back" (whatever the developer decides to mean "back")
So, if the MaterialDrawer allows just by configuring it (and not overriding anything) to show an hamburger icon that is not opening / closing the drawer, or a back icon that is not going back, that is confusing for me. That is why I thought about the possibility of "check if the" drawertoggle is enabled.

Maybe the only solution is just to define two drawers for the same activity and change the "active one" depending on the Fragment showed (ie, programmatically) so one Fragment would show the drawer with the hamburger icon that shows the drawer, and other shows just the back button. In this case, this should be done by the developer and not the MaterialDrawer, but it still feels a little patchy for me :(

About setting the listener on the toggle, I already test it, and it doesn't work, even worse, as the one defined on the drawer stopped to work.
What I suggested is to add the previous code inside your drawer code, but I still need to find the way to "resume" the normal behavior. Maybe throwing a new event with the "onclick" and the home item would solve the problem. What do you think?

**Comment by mikepenz** [comment]
@gpulido just a quick info i'm not at home right now. the hamburger icon or the icon within the toolbar is not linked to the drawer in any means. so you can implement it the way you want it to work. if you choose to use the included listener it will just do the show hide automatically. if you choose to use the ActionBarDrawerToggle this will do the same just with the toggle. so yeah. 

I also had a lot of issues because it is not clear how the hamburger or backarrow are shown. in my pov this is a really bad implementation by google. 

yeah you can only use one listener. so if you set your own listener this is the new one and the old one is gone. 

the normal behavior of the button just handling the show drawer and hide drawer is working correct. all extra behavior is a bit difficult to handle and to implement. i know this. but i'm not quite sure if the MaterialDrawer can handle these cases.

**Comment by mikepenz** [comment]
@gpulido  about this one: "So, from my pov (please tell me if I'm wrong) a "normal expected" behavior of the ToggleDrawer would be that if the hamburger icon is showed, a click on the icon would "open / close" the drawer, and if it is showing the back button, a click would call "back" (whatever the developer decides to mean "back")
So, if the MaterialDrawer allows just by configuring it (and not overriding anything) to show an hamburger icon that is not opening / closing the drawer, or a back icon that is not going back, that is confusing for me. That is why I thought about the possibility of "check if the" drawertoggle is enabled."

as a fact. if you implement the drawer as it's meant in the Material Design Guidelines it will never show the back arrow. There's only the burger which shows or hides the drawer. That's it. I think this behavior is in and working. 

In your case it's a special case and a very complex case. I hope you are still able to get it working for you.

**Comment by gpulido** [comment]
@mikepenz Thank you for the follow up.
Regarding not showing the back arrow, if that is right, Google itself is not complying with that rule. For example in the Gmail app: When you open the app the hamburger and drawer are shown, if you select a mail, it navigates to the "mail thread" and the back arrow is shown.

I know I can reproduce that behavior by using different activities one with the drawer and the other without it but my problem is that I'm trying to use the same activity to go through a same "flow" and just change the fragments inside. That means to be able to activate / deactivate the drawer that is already defined on the activity.
I don't think that my use case is very "strange" or not common, I can see it on a lot of applications that shows the drawer on a first "screen" and anytime you navigate to a "detail screen" the back arrow is shown.
Regarding the Material Drawer implementation, one of my concerns is that I can set it to a way where I'm showing the hamburger and the drawer is not being opened, or also I can see the back button and it opens the drawer instead of going back (or hitting onOptionsItem...) You are right that probably the problem is on the toggledrawer implementation by google, as even when you have disabled the "togglebutton" the click on it launches the navigationlistener!  That is the real problem or "bug" here.

**Comment by mikepenz** [comment]
@gpulido yeah if you refer to this behavior you are right. sorry that i forgot this point. 

I probably have to set up a sample activity to see how you have to use the toolbar / drawer to get it working the way it is done within gmail. 

I spent about 2 hours on the problem getting the ActionBarDrawerToggle and/or NavigationListener and/or Hamburger icon working. i have not found a real guide what's the perfect case for the whole thing, especially because a different dev had a problem if i set the listener to the drawer by default.

**Comment by gpulido** [comment]
@mikepenz Maybe I have found a solution, using a Interface that gives the posibility to the activity to handle the navigation. I'm going to make a pull request for you to review it.

**Comment by mikepenz** [comment]
@gpulido sounds interesting :)

**Comment by gpulido** [comment]
@mikepenz Hello again, I've taken a look to the change you made and I think there is needed a change. The idea is to allow the activity handle the navigation in case the toggledrawer is not enabled, as in that case. However, in case the toggledrawer is enabled I would fall on the behavior that you already had implemented (subscribe the navigationlistener to open / close the drawer).
So instead of:
```Java
if ((mActionBarDrawerToggle != null && !mActionBarDrawerToggle.isDrawerIndicatorEnabled()) || mOnDrawerNavigationListener != null) 
```
I would rather use this:
```Java
if (mOnDrawerNavigationListener != null && (mActionBarDrawerToggle != null && !mActionBarDrawerToggle.isDrawerIndicatorEnabled()) 
```
(Note the change of the || to the &&)  This way, the activity doesn't need to manage the logic of the navigation on the cases he doesn't care and are already managed by the drawer. With that change one could relay on the normal behavior, and if the activity sets the toggledrawer to not enabled at any moment (when showing Fragment B for example) then and only then the activity would handle the "navigation"

**Comment by mikepenz** [comment]
@gpulido oh i see. 

But then i would prefer to give you a boolean within the listener method which states if it's enabled or not. so your case will work. and users also get a callback each time.

**Comment by gpulido** [comment]
@mikepenz 
It is just a matter of how much of the implementation is let to the drawer and how much is on the dev side.
With your implementation in my use case (Activity with drawer that is shown on Fragment A and back on Fragment B) I need to register the listener using the callback we have just defined and ask for the toggle status:
```Java
 .withOnDrawerNavigationListener(new Drawer.OnDrawerNavigationListener() {
                    @Override
                    public boolean onNavigationClickListener(View view) {
                        if (!result.getActionBarDrawerToggle.isDrawerIndicatorEnabled())
                        {
                           onBackPressed();
                           return true;
                        }
                       else
                           return false;
                  }                    
                })
```
So the Activity needs to know if the drawerToggle is enabled, and decide what to do. With the change I've proposed it is just:
```Java
                .withOnDrawerNavigationListener(new Drawer.OnDrawerNavigationListener() {
                    @Override
                    public boolean onNavigationClickListener(View view) {
                        onBackPressed();
                        return false;
                    }
                })
```
But you are right that in this case, the activity has less control about the navigation, but maybe is the right thing as that is "handled" by the drawer.
I don't know both approach are similar but with slightly differences.

Regarding your current implementation, I would not remove the code, it is very helpful to have all encapsulated, and with your "callbacks" system, the developer could override almost all behaviors if he wants.

**Comment by gpulido** [comment]
@mikepenz  Sorry for reopen this issue, but with the last changes you have made, you had changed the way the actionBarDrawerToggle is created in case a toolbar is given. You are using the constructor with the toolbar:
```Java
actionBarDrawerToggle(mActivity, mDrawerLayout, mToolbar, R.string.drawer_open, R.string.drawer_close) 
```
This is a regression from https://github.com/mikepenz/MaterialDrawer/pull/66
If the toolbar is used that way, the navigation listeners stop working and the back button doesn't do anything.

**Comment by mikepenz** [comment]
@gpulido with the latest release of the appcompat library you have to set the mToolbar for the ActionBarDrawerToggle else the Toggle won't show up. 

So we have to set the NavigationListener on the ActionBarDrawerToggle (i think there's a method allowing this)

**Comment by gpulido** [comment]
@mikepenz I think there is something wrong somewhere. I'm reviewing the official doc:
https://developer.android.com/reference/android/support/v7/app/ActionBarDrawerToggle.html#ActionBarDrawerToggle(android.app.Activity, android.support.v4.widget.DrawerLayout, android.support.v7.widget.Toolbar, int, int)
and they are suggesting the same:

"Please use ActionBarDrawerToggle(Activity, DrawerLayout, int, int) if you are setting the Toolbar as the ActionBar of your activity."

This is consistent with the behavior I have found, if you use the toolbar on the constructor the navigationlistener stop working and the backbutton doesn't do anything.
Would you mind point me to the documentation where the need to set the toolbar is said?

**Comment by mikepenz** [comment]
@gpulido i read the official documentation, this does not state the issue. 

I'm in a developer group (which is not public) where they discussed this issue and the only solution was to set the toolbar with the ActionBarDrawerToggle. 




"figured it out. We were calling `setSupportActionBar` and passing in an instance of `ToolBar` in the activity. A few lines later we create an instance of `ActionBarDrawerToggle` which we weren't passing the instance of the `ToolBar` to. It seems that `ActionBarDrawerToggle` no longer automatically picks up on the `ToolBar` and you have to pass it in now."

**Comment by gpulido** [comment]
@mikepenz I guess that the problem only raises on pre lollipop devices isn't it? Because on my nexus 5 when the toggle is registered without the toolbar the drawer icon is showed without any problem.
Again this is a problem as now the backbutton doesn't work anymore( at least on lollipop devices) and the navigationlistener that is registered inside the drawer is also not being called.

**Comment by mikepenz** [comment]
@gpulido tried it on my Nexus 5 with Android 5.1 Ill try it again this evening. seems strange that it is working on your phone. :D

Sorry for recreating this issue. Will have a detailed look later today.

**Comment by gpulido** [comment]
@mikepenz Thank you for the last changes. I was able to make it work.
Just to document. If you have defined the drawer with a toolbar, the hambuger icon is shown (and the the drawer opens). 
In order to show the backbutton the following must be done:
```Java
result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false);
getSupportActionBar().setDisplayHomeAsUpEnabled(true);
getSupportActionBar().setDisplayShowHomeEnabled(true);

```
IMPORTANT: the order of the previous lines matters. If you disable the drawer after setting the displayhome, it doesn't show

To recover the hambuger the oposite must be done:
```Java
getSupportActionBar().setDisplayHomeAsUpEnabled(false);
getSupportActionBar().setDisplayShowHomeEnabled(false);
result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);
```
(Again the order matters)

Thank you for your awesome work and patience

**Comment by mikepenz** [comment]
@gpulido i'm glad that adding the listener to the ActionBarDrawerToggle worked :)

Thanks for the note about showing the BackArrow or HamurgerIcon. Will add this to the REAME.md

You are welcome. Thanks for your time and help :).

**Comment by mikepenz** [comment]
@gpulido ok i tried it but it seems i'm not able to get it working with this code snippet. 

Can you create a gist with a bit more code so i can check what's different?
