### ISSUE TITLE
Disable profile icon

### ISSUE THREAD

**Issue by TYZRPVX** [mikepenz/MaterialDrawer#760]
I don't want to show the icon in my app, could you tell me how to disable it ? Thanks in advance.

**Comment by mikepenz** [comment]
@TYZRPVX which icon? how should it look like?

**Comment by TYZRPVX** [comment]
the icon is in the header of the drawer, if I don't use `withIcon` method, the header set a default icon as  user‘s avatar. But I want to leave it blank.

**Comment by mikepenz** [comment]
@TYZRPVX you can overwrite the placeholder icon? Or you want no content in the accountheader at all?

**Comment by TYZRPVX** [comment]
@mikepenz  I only want a picture without other content

**Comment by mikepenz** [comment]
@TYZRPVX then just provide your own header? no need to use the `AccountHeader`

**Comment by TYZRPVX** [comment]
thanks, I will have a try

**Comment by TYZRPVX** [comment]
reminisces
