### ISSUE TITLE
Reference to IDrawerItem View.

### ISSUE THREAD

**Issue by localhostEU** [mikepenz/MaterialDrawer#761]
Any way i can get a reference to the View by identifier or tag?
(In my situation i use ShowCaseView which i should point to the View it should hightlight)

**Comment by mikepenz** [comment]
@localhostEU you mean to the view of a specific `DrawerItem`? 

No as the items and views are within a `RecyclerView` and the views are re-used. That means you there is no guarantee that a specific view is currently available, and not reused for a different `DrawerItem`

What do you need it for?

**Comment by localhostEU** [comment]
Updated my question.

**Comment by mikepenz** [comment]
@localhostEU haha :D

you still talk about `DrawerItems` right?

You can theoretically get the reference to the `RecyclerView` and then iterate over the child views of this `RecyclerView`. If the `DrawerItem`s were already added and are visible you will then get a few childs. Those have a `Tag` or `Identifier` set on their view. 

The code which sets the `Id`, and `Tag` on the `itemView` of the `DrawerItem` 
```
viewHolder.itemView.setId(getIdentifier());
viewHolder.itemView.setTag(this);
```
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BasePrimaryDrawerItem.java#L64

I just want to repeat it once again. It is a `RecyclerView` and this will **recycle** views ;). So if you scroll and the item you want to highlight moves out of focus it will be recycled and you will not be able to find it via the **child** view logic. And so there is no secure solution to **always** get the view via the `RecyclerView`  (also make sure that the items were initialized and are visible already)

The whole thing will probably work for a `Drawer` as this does not contain many items, and in most cases it is also not scrollable, but just keep the above in mind ;)

**Comment by localhostEU** [comment]
Thanks again for the reply. Got it working like 1 min before you posted :+1:

**Comment by mikepenz** [comment]
@localhostEU ok great ;)
