### ISSUE TITLE
DrawerItems are not shown as disabled after disabling them

### ISSUE THREAD

**Issue by grote** [mikepenz/MaterialDrawer#763]
I'm having a bunch of PrimaryDrawerItems and at some point in my activity, I want to disable one or more of those by calling item.withEnable(false). When doing this, the items are not shown as disabled (greyed out) automatically. I need to call drawer.setSelection() first to see an effect. Is this a bug?

**Comment by mikepenz** [comment]
@grote let me assume you have not notified the drawer about the updated item.

https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

**Comment by grote** [comment]
Wow you are amazingly responsive and you assume correctly ;) Sorry for the noise and thanks a lot for your great libraries! :)

**Comment by mikepenz** [comment]
@grote great :). thank you so much
