### ISSUE TITLE
setStickyFooterSelection(int identifier, boolean fireOnClick) dosen't  work as expected

### ISSUE THREAD

**Issue by GreenSkinMonster** [mikepenz/MaterialDrawer#764]
I think in file Drawer.java Line 456

https://github.com/mikepenz/MaterialDrawer/blob/d94f12c3590a037d1f122d6bff0b00dab728b32a/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L456

```java
    public void setStickyFooterSelection(int identifier, boolean fireOnClick) {
        setStickyFooterSelectionAtPosition(getPosition(identifier), fireOnClick);
    }
```

should be 

```java
    public void setStickyFooterSelection(int identifier, boolean fireOnClick) {
        setStickyFooterSelectionAtPosition(getStickyFooterPosition(identifier), fireOnClick);
    }
```

Thanks.

**Comment by mikepenz** [comment]
@GreenSkinMonster will test later today. But looking at the code you are right. Sorry for this issue

**Comment by mikepenz** [comment]
@GreenSkinMonster it is not yet released. will be in v4.4.0
