### ISSUE TITLE
Click on close behaviour reversed

### ISSUE THREAD

**Issue by clockworkant** [mikepenz/MaterialDrawer#765]
When using this method:
```
.withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        ...
                        return false;
                    }
                })
```

I must return false in order to get the drawer to close on item selected. This is probably wrong as the method onItemClick should return if the item was consumed.

Thoughts?

**Comment by mikepenz** [comment]
@clockworkant no it's correct. 

if you return `true` this means the event was consumed. so no further action is done. 
if you return `false` this means the event was not yet consumed. so it is still allowed to continue with the additional steps
