### ISSUE TITLE
How to dynamically change Header colors (background and text)

### ISSUE THREAD

**Issue by candeiasdan** [mikepenz/MaterialDrawer#766]
Im trying to adapt this library to my needs and im trying to slightly modify the library to support some of my needs. 
I have just starting to take a look at this library, but perhaps someone already worked on this issue.

**Once i change the profile i want also to change colors of Header -> text color and background color**

```java
mHeader = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(new ColorDrawable(0xFFFF0000))
                .withTextColor(Color.BLACK)
                .addProfiles(.....)
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean current) {
                        //need to see colors here!
                        returnn true;
                    }
                })
                .build();
```

As I can see I can only set the colors when I build the header, but later on I need to create a new header and then call build()

How can i achieve this? Thanks.

**Comment by mikepenz** [comment]
@candeiasdan you can get the reference to the header and modify the color. 

The `view` reference should be accessible via the `Drawer`:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L266

Or via the `AccountHeader`:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L39

**Comment by candeiasdan** [comment]
So you suggest iterate over the view, looking for TexViews and set color. Correct?

**Comment by mikepenz** [comment]
@candeiasdan you can find those two textviews by the following id's:
`material_drawer_account_header_name`
`material_drawer_account_header_email`

**Comment by candeiasdan** [comment]
Problem solved! :+1:
