### ISSUE TITLE
Drawer.setSelection() rely upon drawer item identifier

### ISSUE THREAD

**Issue by ivanovpv** [mikepenz/MaterialDrawer#768]
Bug related to following code in `class Drawer`:

    public boolean setSelection(IDrawerItem drawerItem, boolean fireOnClick) {
             return setSelection(getPositionFromIdentifier(drawerItem), fireOnClick);
    }

In case of dynamic adding drawer items through code like:

    IDrawerItem item = new PrimaryDrawerItem()
                    .withName("Hello")
                    .withIcon(icon)
    drawer.addItem(item, position);

i.e. without explicitly specified `.withIdentifier(id)` default identifier set to -1

As a result any attempt to select/fire drawer item produces  `drawerItem=null` in drawer item click listener:

     new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(AdapterView<?> parent, View view, int position, long id,   IDrawerItem drawerItem)  {
                    }

which is disaster.

As a quickfix I'm using adding of random and/or hashed identifier during declaration of drawer item.

**Comment by mikepenz** [comment]
@ivanovpv that is working correct as of the design of the `MaterialDrawer` there is a different method which allows to select items based on their position but this is not recommended.

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L486

**Comment by ivanovpv** [comment]
Thanx!
