### ISSUE TITLE
Updating sticky footer is bugged.

### ISSUE THREAD

**Issue by localhostEU** [mikepenz/MaterialDrawer#769]
- If i init drawer like this:
```java
.withStickyFooterDivider(true)
.withStickyFooterShadow(false)
```
After updateStickyFooterItem i get divider removed.

- With same initialization if add 1 sticky item (primary), updating it's name or whole item won't take any effect (debugger says DrawerUtils.getStickyFooterPositionByIdentifier() returns incorrect position (real position is incorrect minus 1).

**Comment by mikepenz** [comment]
can you provide some more code how i can reproduce this issue?

**Comment by localhostEU** [comment]
Sorry for the delay, will provide code in 1-2 hours.

**Comment by localhostEU** [comment]
http://pastebin.com/8FU0n4Gu

Checked again, it doesn't work only 1st time. 2nd+ update works fine.

**Comment by mikepenz** [comment]
@localhostEU thanks. will take a look later today

**Comment by mikepenz** [comment]
@localhostEU ok found the issue. it is a bug inside the MaterialDrawer. Will be fixed in the next version ;)
