### ISSUE TITLE
Can the avatar be reloadable? 

### ISSUE THREAD

**Issue by jiechu** [mikepenz/MaterialDrawer#77]
Could the drawer be like these?
1. When I click the avatar, I would like to open dialog to select image or take a photo, after that, maybe click the finish button from camera screen, then go back to the previous screen, then the profile avatar is reloaded.
2. When click the profile name, I would like to open a page to edit the name, after save, the profile name is reloaded.

Thanks & Regards,

**Comment by mikepenz** [comment]
You can modify and change the profile items at any point. Just use the `AccountHeader.Result` object you get with the `.build()` method and set new items or the updated items.

**Comment by jiechu** [comment]
You mean that after AccountHeader.Result has been created, the way to do this is to re-create the AccountHeader.Result. Right? Is there any callback method to draw the profile instead re-create the AccountHeader?

**Comment by mikepenz** [comment]
No. I mean you retrieve the AccountHeader.Result and then you can use its methods to modify the headers content. 

Right :)
