### ISSUE TITLE
rtl shadow bug

### ISSUE THREAD

**Issue by ProgrammerBassam** [mikepenz/MaterialDrawer#771]
![screenshot_ - - - - -](https://cloud.githubusercontent.com/assets/7253737/10719019/c6c6936e-7b90-11e5-8006-885e7d4ef1bc.png)

**Comment by mikepenz** [comment]
How do you init this? Have you provided the correct shadow?

**Comment by mikepenz** [comment]
Do you use the `MiniDrawer` as shown here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java#L167
?

**Comment by mikepenz** [comment]
if you use the shadow of the `MiniDrawer` there is the `withInRTL(true)` flag
