### ISSUE TITLE
Tablet bug (mini drawer)

### ISSUE THREAD

**Issue by localhostEU** [mikepenz/MaterialDrawer#772]
![nhwobzvcv24znfiqco-rv6embjphzwk88d5fi3nvmxy](https://cloud.githubusercontent.com/assets/6198017/10730232/c753a802-7bff-11e5-8b3e-b07487140160.png)

Samsung Tab S 10.5 - bugged (extra grey space above drawer)
Nexus 5 - normal drawer looks fine

**Comment by mikepenz** [comment]
you use the same code and layout for both?

**Comment by localhostEU** [comment]
@mikepenz Nop. For normal drawer i use mDrawer.build(), for mini drawer i use crossover stuff.

**Comment by mikepenz** [comment]
Then you should remove the fullscreen flag for tablet

**Comment by localhostEU** [comment]
@mikepenz i didn't set fullscreen flag. If i set it to true - grey space becomes white.

**Comment by mikepenz** [comment]
You should at it to false for the tablet variant. Also the translucent statusbar flag

**Comment by localhostEU** [comment]
@mikepenz same effect. White instead of grey.

**Comment by mikepenz** [comment]
Remove the fullscreen flag and just set the translucent statusbar to false

**Comment by localhostEU** [comment]
@mikepenz White instead of grey :)

**Comment by mikepenz** [comment]
Sorry I'm currently not on a pc just on my phone.

**Comment by localhostEU** [comment]
@mikepenz it's ok i will try something else xD

**Comment by mikepenz** [comment]
I will check at home. But i am sure it is a wrong flag set in the tablet. Because the additional padding is added to support the below the statusbar behavior

**Comment by mikepenz** [comment]
@localhostEU can you show how you init the drawer for the tablet?

**Comment by mikepenz** [comment]
i close it for now as i'm sure this is no bug :P i will still help you if you provide some more details within this issue.
