### ISSUE TITLE
iconfont icons bug - Kindle Fire HDX 8.9 Android 4.4.3

### ISSUE THREAD

**Issue by LelloBello** [mikepenz/MaterialDrawer#773]
![device-2015-10-28-121321](https://cloud.githubusercontent.com/assets/13051200/10787152/0458ebb6-7d6f-11e5-88eb-101219a32959.png)

**Comment by mikepenz** [comment]
@LelloBello can't reproduce it on any of my emulators :/ you start the sample project without any modifications? installed from the Google Play Store?

**Comment by mikepenz** [comment]
Have you rooted it so it runs Android? if not. I am sorry but i can't support different OS than Android.

**Comment by LelloBello** [comment]
No, device is not rooted. I'm starting the sample project from android studio without any modification... i'm testing it in other devices and it all works. 
It seems that every time you click on an drawer's item, icon is redrawn under the previous icon.

**Comment by mikepenz** [comment]
@LelloBello if you use the iconics icons it will use the following on devices < API 21 to properly handle the StateListDrawable:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/util/PressedEffectStateListDrawable.java

could you please try to add `.withIconTintingEnabled(false)` at the end of the line of each draweritem?
will it then work?

**Comment by LelloBello** [comment]
It doesn't work! I get the same result :/

**Comment by mikepenz** [comment]
and if you use normal icons and not the icon font?

**Comment by LelloBello** [comment]
resolved! :)
```java
new PrimaryDrawerItem().withName(R.string.drawer_item_home).withIcon(ContextCompat.getDrawable(getActivity(), R.drawable.icon_tray_home)).withIdentifier(1)                                 
```
thanks for your support Mike!

**Comment by mikepenz** [comment]
@LelloBello yeah so it seems to be IconFont related?

If you create a Drawable via the iconfont and set it. will it work?
