### ISSUE TITLE
Selected bug after profile click in MiniDrawer

### ISSUE THREAD

**Issue by androideveloper** [mikepenz/MaterialDrawer#775]
Steps to reproduce:
1.Open MiniDrawer
2.Click 3-rd option (it becomes selected)
3.Then click profile photo (drawer is opened with accounts)
4.Close drawer using SWIPE
5.The previous selected item is now Not selected.

Here is video attached.
https://youtu.be/WoAWCQTFRKc

It seems to be a bug, because profile photo in Minidrawer is the first item in recyclerview and takes away the selection from previous item

**Comment by androideveloper** [comment]
And is there a way to disable Profile click in Minidrawer?

**Comment by mikepenz** [comment]
@androideveloper not that easy. with the fix for the issue i'Ve also added a new api for this ;)

**Comment by androideveloper** [comment]
@mikepenz Awesome work! Super fast! Thanks a lot! I have some suggestions, will write them later. And one other issue with profile click.

I have set .withSelectionListEnabledForSingleProfile(false) in AccountHeader but clicking on profile in MiniDrawer opens selection list with only 1 profile, but I don't want to show selection list at all ((I want to just crossfade view, not show account selection list, because I have only one account in the list)).

There are 2 solutions for this.

1). Providing custom profile click in MiniDrawer 

Now I have found the way to do it, just setting adapter onclick listener

        // click listener
        miniResult.getDrawerAdapter().setOnClickListener(new BaseDrawerAdapter.OnClickListener() {
            @Override
            public void onClick(View v, int position, IDrawerItem item) {
                Drawer mDrawer = miniResult.getDrawer();
                int type = miniResult.getMiniDrawerType(item);
                if (type == MiniDrawer.ITEM) {
                    //fire the onClickListener also if the specific drawerItem is not Selectable
                    if (item.isSelectable()) {
                        mDrawer.setSelection(item, true);
                    } else if (mDrawer.getOnDrawerItemClickListener() != null) {
                        //get the original `DrawerItem` from the Drawer as this one will contain all information
                        mDrawer.getOnDrawerItemClickListener().onItemClick(v, position, mDrawer.getDrawerItem(item.getIdentifier()));
                    }
                } else if (type == MiniDrawer.PROFILE) {
                    if (crossFader != null) {
                        crossFader.crossFade();
                    }
                }
            }
        });


But this seems to be just a hack, just copied full click listener, but I needed only Profile case.

2). Fix the issue here

else if (type == PROFILE) {
                    if (mAccountHeader != null && !mAccountHeader.isSelectionListShown()) {
                        mAccountHeader.toggleSelectionList(v.getContext());
                    }
                    if (mCrossFader != null) {
                        mCrossFader.crossfade();
                    }
                }

Consider the case .withSelectionListEnabledForSingleProfile(false).

But providing both solutions will be great!

**Comment by mikepenz** [comment]
I've added a new simple method for this: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L89

**Comment by androideveloper** [comment]
This method just disables click. What I suggested is custom click. I want to just crossfade views on prfile click

**Comment by mikepenz** [comment]
@androideveloper ah i see. i will allow you to define a completely custom onClick behavior in the next version

**Comment by androideveloper** [comment]
@mikepenz ok, great!

**Comment by mikepenz** [comment]
@androideveloper https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L150

**Comment by androideveloper** [comment]
@mikepenz will try after version is released, thanks
