### ISSUE TITLE
Fullscreen drawer with transparent status bar

### ISSUE THREAD

**Issue by angelpinheiro** [mikepenz/MaterialDrawer#776]
Hi! I'm using this library, and I already have a full screen drawer working. Now I'm wondering if there is a way to get a completely transparent status bar working, removing the translucent black shadow.I thought it was related to the `ScrimInsetsFrameLayout` `insetForeground` so I tried overwriting the `siv_insetForeground color`, but I couldn't get it working. I have also tried all the methods in the `DrawerBuilder` that could be related to the status bar  appearance and nothing worked. I've spent a while inspecting the code of the library and also the code of Materialize, and I didn't found a solution.
Even this seems to have no effect: 
`drawer.getMaterialize().getScrimInsetsFrameLayout().getInsetForeground().setAlpha(0);` 

Help is appreciated!

<img src="https://lh6.ggpht.com/cUulyazfhJZVbmFsBMy7lEVaEAZ4u4568lZc-_ia9YztwzKHPUBVCTiLRAFzpbQb7Bc=h900" width="300">

**Comment by mikepenz** [comment]
@angelpinheiro if you want disable the managed padding on top and be able to manage this on your own look at this sample:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/FullscreenDrawerActivity.java

**Comment by angelpinheiro** [comment]
Thanks, it worked like a charm!

**Comment by mikepenz** [comment]
@angelpinheiro great ;)
