### ISSUE TITLE
MaterialDrawer badge text color

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/MaterialDrawer#777]
Is there a way to change the badge text color in the MaterialDrawer? I don't want to change the text color of the entire item, but just the badge text color. To make it remain the same even if it is selected.

**Comment by mikepenz** [comment]
This can be done by setting a `BadgeStyle` as done in the `DrawerActivity`
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L117
