### ISSUE TITLE
Hiding a badge

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/MaterialDrawer#778]
I would create an item that has a badge but it appears only when I want to update it. This works in the normal MaterialDrawer, but even if I update the item with a badge, it isn't showed in the MiniDrawer. Is there a way to make it work as I would?

**Comment by mikepenz** [comment]
@EpsilonOrionis you also have to notify the MiniDrawer that the specific item was updated.
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L262

I know that those calls could be eliminated if i would integrate the `MiniDrawer` into the `Drawer` itself, but i made the decision to keep both standalone without any links to the other, so both can be used without the other (the `MiniDrawer` only uses the `Drawer` as data source)

**Comment by EpsilonOrionis** [comment]
Mike, this is your library and it's perfect as it is. These aren't real problems.

**Comment by mikepenz** [comment]
So the above solved your problem? :stuck_out_tongue_closed_eyes:

**Comment by EpsilonOrionis** [comment]
Of course as always ;). I am not complaining, so ... :D

**Comment by mikepenz** [comment]
Haha. Just to make sure :D I remember that i had false answers already too :D

Have a nice evening. 

Best,
Mike
