### ISSUE TITLE
Swiping of MiniDrawer like in Gmail

### ISSUE THREAD

**Issue by androideveloper** [mikepenz/MaterialDrawer#779]
I've setup the MiniDrawer and my view on the right-hand-side is a ViewPager with TabLayout. Right swipes are consumed by the minidrawer(crossfader) which breaks the view pager.

Can crossfader library be updated to support swiping like in gmail?
(1).When drawer is closed, swiping area for opening is left-pane
(2).When drawer is opened, swiping area for closing is right-pane

I have selected swiping area in screenshots.

![screenshot_20151030-153046](https://cloud.githubusercontent.com/assets/1249919/10845184/1a593d38-7f1f-11e5-8364-f362a7a55ad4.png)
![screenshot_20151030-153423](https://cloud.githubusercontent.com/assets/1249919/10845185/1a789264-7f1f-11e5-9182-21cc8cc2912c.png)

P.S.
Now I can only disable swiping when drawer is closed, and enable swiping when opened. This way I achieve the (2). Crossfader disables full swiping, it would be great to have also methods like enable/disable ONLY second pane swiping.

**Comment by mikepenz** [comment]
@androideveloper this is no MaterialDrawer issue. It is the behavior of the `SlidingPaneLayout` which is used inside the `CrossFadeSlidingPaneLayout`

https://github.com/mikepenz/Crossfader/blob/develop/library/src/main/java/com/mikepenz/crossfader/view/CrossFadeSlidingPaneLayout.java

Please open the issue over there. Not yet sure if this can be easily achieved. as the touch event is consumed by the `SlidingPaneLayout` already

**Comment by androideveloper** [comment]
Ok, I just copied the issue there. Library will be more flexible with this. 
It seems that changes should be done here
  @Override
    public boolean onTouchEvent(MotionEvent ev) {
        return mCanSlide && super.onTouchEvent(ev);
    }
Based on touch region swipe should be enabled or disabled
