### ISSUE TITLE
Is it possible to get rid of the shadow at the bottom of the header?

### ISSUE THREAD

**Issue by timrae** [mikepenz/MaterialDrawer#780]
![header](https://cloud.githubusercontent.com/assets/2818274/10845781/3854814c-7f4e-11e5-8129-91202551432f.png)

I've been meaning to ask this for a while... In the design support library there was no line between the header and the drawer, whereas I guess you've set some elevation which is casting a shadow below. I originally designed the header image to be continuous with the drawer, so if possible I'd like to get rid of that line under the arrow in the attached image. Can this be easily achieved?

**Comment by mikepenz** [comment]
As of the Google Material Design Guidelines which are my book for everything :stuck_out_tongue: this line is defined there:
https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-specs

Interesting enough (as i've just checked) the line only is used for solid headers and not in addition to an image. 

will take a second look later today

**Comment by timrae** [comment]
By "this line is defined there" do you mean it's visible in the keylines and margins diagram? I couldn't see it defined in the actual content of the spec, so I suspect it's just used in the keylines diagram for demarcation. The line isn't present in any of the Google apps that I looked at, though that's not always a good indication.

**Comment by mikepenz** [comment]
@timrae you can disable this line with `withDividerBelowHeader(false)` on the header. will change the default to false, so people who use images (which is the most common) have the right design by default. 

thanks

**Comment by timrae** [comment]
Thank you thank you!

**Comment by timrae** [comment]
@mikepenz 
Unfortunately `withDividerBelowHeader(false)` also removes the space between the header and the first drawer item. There is still supposed to be space there (16dp according to my reading of the spec), as consistent with the gmail drawer.

**Comment by timrae** [comment]
Additionally, the line itself is still there
![header2](https://cloud.githubusercontent.com/assets/2818274/10860516/b1eefc5e-7fac-11e5-9a23-6090411bee03.png)

**Comment by timrae** [comment]
Just to be clear, I wasn't talking about the "white line" (i.e. the padding), but the grey line. I want the white in the header image to be continuous with the white in the drawer list items without any line between them. It looks like a shadow to me

**Comment by mikepenz** [comment]
@timrae oh sorry. i was not on my pc when answering. you are right this method is used to remove the padding. sorry. will add a new method so you can control both. padding and divider.

**Comment by mikepenz** [comment]
it's in v4.4.3 ;)

**Comment by timrae** [comment]
Thanks @mikepenz!! If I understand correctly, I need to call `withDividerBelowHeader(false)` manually to have padding without the line?

**Comment by mikepenz** [comment]
@timrae right

**Comment by timrae** [comment]
Excellent, thanks it's looking good.

**Comment by timrae** [comment]
Ah damn, it looks like you've updated the library to appcompat 23.1.0, which has a bug that breaks our app, so I'll have to wait for 23.1.1 before updating

**Comment by mikepenz** [comment]
@timrae you can do the following and exclude appcompat dependency from my lib:
https://github.com/mikepenz/MaterialDrawer/issues/587#issuecomment-135148406

**Comment by timrae** [comment]
Ah thanks, that's easier than I had thought
