### ISSUE TITLE
Custom header

### ISSUE THREAD

**Issue by afeozzz** [mikepenz/MaterialDrawer#781]
I noticed that if i want use background image in header, custom header height changes if image will not is same height as header.

example of my custom header

    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
                android:layout_width="match_parent"
                android:layout_height="190dp"
                android:background="@mipmap/blur_background"
                android:orientation="vertical">

    <de.hdodenhof.circleimageview.CircleImageView
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/profile_image"
        android:layout_width="56dp"
        android:layout_height="56dp"
        android:src="@mipmap/ic_user_avatar_default"
        app:border_color="#FF000000"
        android:layout_marginTop="96dp"
        android:layout_marginLeft="24dp"
        android:layout_marginStart="24dp"/>

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Akash Bangad"
        android:textSize="14sp"
        android:textColor="#FFF"
        android:textStyle="bold"
        android:gravity="left"
        android:layout_marginLeft="24dp"
        android:id="@+id/username"
        android:layout_marginTop="8dp"
        android:layout_marginBottom="8dp"/>
    </LinearLayout>

my background was 200&390 , so height of header specifies the height of the header image and it was wrong.

I hope you fix it

**Comment by mikepenz** [comment]
@afeozzz nothing i can fix. If you provide a custom header only the view you provide is used. 

If you set a layout as header it will be wrapped into a `ContainerDrawerItem` and added to the list on the first position so it will work as any list item.

**Comment by couchcrew-thomas** [comment]
I've stumbled across the same issue:

To reproduce just use a FrameLayout with height set to 150dp and a background image which exceeds this height (e.g. 200dp).
When adding the header via `withHeader(R.layout.header)` the resulting header view has the height of the brackground and not the static 150dp.

**Comment by mikepenz** [comment]
@couchcrew-thomas as mentioned in the previous answer. That's the way the `RecyclerView` from Android handles the items. If you wrap the whole thing in a `LinearLayout` with a specific `height` it should work

**Comment by multivoltage** [comment]
I open an issue about 10 minutes ago. After your last answer @mikepenz I tried to put an ImageView inside LInearLayout, and this Linear has 200 dp height. Solution doesn not work

**Comment by Kraahkan** [comment]
Note for anyone else trying to solve this problem, make sure you use drawer.setHeader(yourView, false). Without use of the second boolean, whatever settings you provided on drawer initialization are overrided, and the divider will be displayed anyways.
