### ISSUE TITLE
Remove shadow

### ISSUE THREAD

**Issue by Grountex** [mikepenz/MaterialDrawer#783]
Hello,
Is it possible to remove the shadow from circle image in AccountHeader and under AccountHeader?
Thank you!

**Comment by mikepenz** [comment]
@Grountex the shadow is as defined in the Google Material Design Guidelines. 

If you really want to remove it you will have to overwrite the layout. The easiest is to copy the layout over to your project (with the same name) and just remove the elevation from the headers. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml
