### ISSUE TITLE
Shadow under the status bar

### ISSUE THREAD

**Issue by mrneiverth** [mikepenz/MaterialDrawer#784]
I got a code with a small bug, using an old version. Being more specify it's this version 2.8.2@aar

Do you have an idea how can I fix it without making a new drawer ? 
![drawer](https://cloud.githubusercontent.com/assets/11544464/10864694/c2db4c30-7fdd-11e5-8304-bea4e674a833.jpg)
Obs: it's just happen in API greater than 20

By the way, you are doing a great job with your library :D

**Comment by mikepenz** [comment]
@mrneiverth what prevents you from updating to the latest version? i can help with migrating the code?

as of the "bug". i think back in this version there was already some method which contained `withFullscreen` or `withTranslucentStatusbar` disable those. or search for a similar method and set it to false, the shadow is added to mimic the statusbar shadow when using fullscreen. and as your drawer is not used in fullscreen this does not have to be set

**Comment by mrneiverth** [comment]
It's worked! It's an old (and bad) code not so easy to update.

Thank you @mikepenz!
I won't try to build more apps without your amazing lib =)

**Comment by mikepenz** [comment]
@mrneiverth great :D haha funny enough that i remember the methods back then :D

thanks ;)
