### ISSUE TITLE
Mini drawer activity with crossfader having actionBarToggleAnimated true

### ISSUE THREAD

**Issue by yuri4031** [mikepenz/MaterialDrawer#786]
Hi
I find your project very helpful for my app
I am currently using miniDrawerActivity having fixed crossfader and drawer
I want to use the animatedtogglebar which I did using

.withActionBarDrawerToggleAnimated(true)
.withActionBarDrawerToggle(true)

but there is no response of that.
I think crossfader is overriding this behaviour as it is already showing a part of drawer
Can u help me out in this regard

**Comment by mikepenz** [comment]
@yuri4031 the sample of the `MiniDrawer` does not use the `ActionBarDrawerToggle` as it does not use a `DrawerLayout` so those properties won't change anything in your case. 

This behavior is not defined within the `Drawer` and i have kept it open to be defined by devs who use this pattern. I think you will have to go with a third party lib which allows you to have the animated `NavigationIcon` without a `DrawerLayout`

**Comment by yuri4031** [comment]
Thanx anyways
I used my custom tool bar and integrated it you library to achieve the functionality.
:)

**Comment by mikepenz** [comment]
@yuri4031 great ;)
