### ISSUE TITLE
How to set Section Title for set of items

### ISSUE THREAD

**Issue by lalkrishna** [mikepenz/MaterialDrawer#787]
Could you please tell me, how to set Title for Set of items(Primary & secondary). 

EDIT
I didn't find .withSelectable function.

**Comment by mikepenz** [comment]
@lalkrishna there are no sets of items. If you have a section then just add a `SectionDrawerItem`
All default items are shown in the sample:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java
