### ISSUE TITLE
Text in AccountHeader

### ISSUE THREAD

**Issue by dmelechow** [mikepenz/MaterialDrawer#789]
Is it possible to add text to the AccountHeader and listen to it? Like on a picture. if possible, how? In Advance thank you!
![default](https://cloud.githubusercontent.com/assets/11187627/10895086/7741efda-81dc-11e5-8a90-28badf5c109d.jpg)

**Comment by mikepenz** [comment]
@dmelechow  you can use the `CompactHeader` and set the first and second line of it (it does not allow you to have multiple lines of the second smaller text) and then you can listend to the whole header for a click event

**Comment by dmelechow** [comment]
Please tell or point me how to use CompactHeader in app. Nowhere can't find information about it.

**Comment by mikepenz** [comment]
shown in the sample: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CompactHeaderDrawerActivity.java

**Comment by mikepenz** [comment]
closed as this is no real issue. you can continue asking questions here.
