### ISSUE TITLE
How can I make these things?

### ISSUE THREAD

**Issue by Gilb007** [mikepenz/MaterialDrawer#790]
Hi everyone!

I'm stumble to make next things:
1) How to make red notch like in picture?
2) How to add subheader (for category) particulary color like in picture?
3) How add footer like in picture?
![untitled](https://cloud.githubusercontent.com/assets/7489129/10905459/6aca96a4-822b-11e5-808e-271a69fd57c0.png)

Please, help me!

**Comment by mikepenz** [comment]
@Gilb007 
1.) You will have to create a `CustomDrawerItem` you can use an existing item as reference or base. 
2.) the SubHeader is called `SectionDrawerItem` as shown in the sample: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L129
3.) I do not see a footer there, i just see that there are no more items and that the list background is shown

**Comment by mikepenz** [comment]
@Gilb007 will close as it is no issue. 

we can continue the discussion here and i try to help ;)

**Comment by Gilb007** [comment]
@mikepenz 
1) May I see example CustomDrawerItem how to made red notch? I don't understand.
2) If SectionDrawerItem is subheader, but how to set color in background? I've found setting text color, but not subheader's background.

Thnx for answers.

**Comment by mikepenz** [comment]
@Gilb007 you have to implement it on your own. 
1.) There is no such element made yet as it does not follow the Material Design Guidelines. The MaterialDrawer allows you to use custom elements. 
So you can use an existing item as base and extend it and implement the things you need, or create a new one. 
2.) No background property on this one as it does not follow the Material Design Guidelines you would have to modify this one to and add the background functionality or hard code it for your case. 


A few custom `DrawerItems` are here: 
https://github.com/mikepenz/MaterialDrawer/tree/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerItems
The default ones are here:
https://github.com/mikepenz/MaterialDrawer/tree/develop/library/src/main/java/com/mikepenz/materialdrawer/model
And i also posted a description here:
http://stackoverflow.com/questions/31030595/how-to-customize-the-draweritem-using-the-lib-mikepenz-materialdrawer/32542999#32542999

**Comment by Gilb007** [comment]
@mikepenz thx a lot for answers, I'll figure it out and write back when handle it.
