### ISSUE TITLE
create drawer once use every where

### ISSUE THREAD

**Issue by vd92** [mikepenz/MaterialDrawer#792]
Hi
My app has more than 30 activity and i would like to use drawer in all of them . every thing is fine but write same code in all activity not sound's good and when i try to write code's in a helper class , i don't know how to point to activity in .withActivity() .

**Comment by mikepenz** [comment]
@vd92 create a helper class and pass the `activity` to this method?

```java
public Drawer createDrawer(Activity act) {
    ....
}
```

**Comment by vd92** [comment]
no I pass just Context to helper class

**Comment by mikepenz** [comment]
@vd92 you have to pass the activity else you can't provide it to the drawer builder :P

**Comment by vd92** [comment]
can you please tell have to pass activity ? I'm new to android and really confused

**Comment by mikepenz** [comment]
If you are in an activity then just pass `this` to the helper class.

**Comment by vd92** [comment]
thank you , it's work :smile_cat:
