### ISSUE TITLE
MiniDrawer not updated after main drawer update

### ISSUE THREAD

**Issue by androideveloper** [mikepenz/MaterialDrawer#793]
I have MiniDrawer. And also have an option in app to customize your menu in navigation drawer(what you want to see). 

So steps are folowwing:
1. Setup minidrawer
2. Click a button in action bar to customize menu list
3. Show a dialog to user to customize list
3. After callback
 ArrayList<IDrawerItem> newDrawerItems = getDrawerItems();
 result.setItems(newDrawerItems);

The main drawer i updated with new list, but the minidrawer is still in previous state.
I have tried to call miniResult.createItems(). this show new list, but it loose selection and also profile click

**Comment by mikepenz** [comment]
@androideveloper you have to call:
```java
miniResult.createItems()
```
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L363

This will use the selection from the `Drawer` and also the active profile from the `AccountHeader` so this one has to contain the correct selection already

**Comment by androideveloper** [comment]
I have mentioned that I am calling miniResult.createItems().
Now I have added result.setSelection(0); and it seems that selection now works.
But it seems that after selection, minidrawer drops click listener that was set initially?

**Comment by mikepenz** [comment]
@androideveloper what do you mean with it drops the click listener?

**Comment by androideveloper** [comment]
I have set custom click listener on minidrawer this way
miniResult.getDrawerAdapter().setOnClickListener() //// (NOTE that this is my own solution for custom click,since library api for custom click isn't released yet)

And after calling 

result.setItems(drawerItems);
miniResult.createItems();
result.setSelection(0);

minidrawer default click listener called instead of my custom click listener

**Comment by androideveloper** [comment]
May be this will not happen with custom click provided by you?

**Comment by mikepenz** [comment]
@androideveloper yeah this gets overwriten inside the `createItems` when using the new api it will work

**Comment by androideveloper** [comment]
@mikepenz it works! Thanks ;)
