### ISSUE TITLE
Customize drawer item's icon

### ISSUE THREAD

**Issue by vasiledoe** [mikepenz/MaterialDrawer#794]
I'd like to customize an heracity like in this screenshot:
![device-2015-11-04-185050](https://cloud.githubusercontent.com/assets/15106474/10945134/2d84dd36-8325-11e5-8e58-4dda529d6c87.png)

For padding I was just using some blank spaces ;) but I need icon to be right before the title, is there a way to do that? Desired result:

![device-2015-11-04-185050](https://cloud.githubusercontent.com/assets/15106474/10945427/0bc404d2-8326-11e5-9ec2-91b42d7c1017.png)

**Comment by mikepenz** [comment]
@vasiledoe if you want this behavior i suggest a custom `DrawerItem` in your case it would 

If you look at the source of the `PrimaryDrawerItem` you should be able to create a new modified version of the `PrimaryDrawerItem` (by overwriting it) and add more padding on the left via the `bindView ` method. 

There is already padding added in the `BasePrimaryDrawerItem` via the `bindViewHelper` method on for API 17 https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BasePrimaryDrawerItem.java#L105

Here's the source of the `PrimaryDrawerItem` (if you use this as base overwrite `bindView` and `getType`

**Comment by vasiledoe** [comment]
soved, thx for your response, for everybody the full code is: https://bitbucket.org/snippets/vracovita/y8o7G

**Comment by mikepenz** [comment]
@vasiledoe your answer is a bit late. in the meantime. there is now a feature to define a level of a drawerItem which will add more padding:

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L193

(used in the `DrawerActivity`)
