### ISSUE TITLE
Click on account's picture will close the drawer

### ISSUE THREAD

**Issue by alirezaaa** [mikepenz/MaterialDrawer#797]
Hi,

I correctly initialized my own MaterialDrawer but one thing I couldn't find. I pass `true` to `withProfileImagesClickable()` but my account profile picture only will close the drawer not call my implementation of `withOnAccountHeaderSelectionViewClickListener()`.

**Comment by mikepenz** [comment]
@alirezaaa if you click a profile image this won't call the `withOnAccountHeaderSelectionViewClickListener()` method, but the `withOnAccountHeaderListener`

**Comment by alirezaaa** [comment]
Thank you so much.
