### ISSUE TITLE
Use single account with no switcher

### ISSUE THREAD

**Issue by Coccoonx** [mikepenz/MaterialDrawer#798]
Hi Mike,

I highly appreciate your library. I really enjoy it and I like it.

But, I would like to know how to use the drawer with a single account without switcher.

Regards

**Comment by mikepenz** [comment]
Hi ;)

Thanks.

https://github.com/mikepenz/MaterialDrawer/issues/692
https://github.com/mikepenz/MaterialDrawer/issues/615
https://github.com/mikepenz/MaterialDrawer/issues/454
https://github.com/mikepenz/MaterialDrawer/issues/443
https://github.com/mikepenz/MaterialDrawer/issues/350

**Comment by Coccoonx** [comment]
Sorry but I get an exception at runtime : 
Caused by: java.lang.NullPointerException
            at com.mikepenz.materialdrawer.AccountHeaderBuilder.build(AccountHeaderBuilder.java:755)

*755 :         this.mAccountSwitcherArrow.setImageDrawable((new IconicsDrawable(this.mActivity, Icon.mdf_arrow_drop_down)).sizeRes(dimen.material_drawer_account_header_dropdown).paddingRes(dimen.material_drawer_account_header_dropdown_padding).color(textColor));


What I'm trying to achieve is presented that.
![drawer](h
![drawer](https://cloud.githubusercontent.com/assets/9346474/10999371/d889db88-849b-11e5-86c5-9a4f17def1e7.png)
ttps://cloud.githubusercontent.com/assets/9346474/10999316/935f597a-849b-11e5-84c8-890abaadcf77.png)

Please, how can I have it?

Thanks

**Comment by Coccoonx** [comment]
![drawer](https://cloud.githubusercontent.com/assets/9346474/10999400/00e1b678-849c-11e5-9982-e3c8c043d796.png)

Attached file

**Comment by mikepenz** [comment]
@Coccoonx how do you build the drawer? What'S the complete exception?

**Comment by Coccoonx** [comment]
Here is the code of header building : 

      AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withCompactStyle(true)
                .withTranslucentStatusBar(true)
                .withHeaderBackground(new ColorDrawable(Color.parseColor("#FDFDFD")))
                .withAccountHeader(R.layout.material_drawer_compact_persistent_header)
                .withSelectionListEnabledForSingleProfile(false)
                .withAlternativeProfileHeaderSwitching(false)
                .withSelectionSecondLineShown(true)
                .withTextColor(Color.BLACK)
                .addProfiles(profile)
                .build();

And here is the Drawer : 

 Darawer  drawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withAccountHeader(headerResult)
                .addDrawerItems(
                        item1,
                        new DividerDrawerItem(),
                        item2,
                        new SecondaryDrawerItem().withName("Section 5")
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        // do something with the clicked item :D
                        return false;
                    }
                })
                .build();

**Comment by mikepenz** [comment]
Have you modified the layout? Because the above exception seems weird

**Comment by Coccoonx** [comment]
Yes I do. 
I'm using this "material_drawer_compact_persistent_header" as layout

**Comment by mikepenz** [comment]
you probably removed a view from the original layout. This is not supported. You can only add new views. If you do not want a original view to be visible set it to 0dp height and width. and visiblity gone.

**Comment by Coccoonx** [comment]
It works now.

But the email address it is not displayed. How can I display it?

**Comment by mikepenz** [comment]
@Coccoonx does your account have an e-mail address? is the view visible in your custom layout?

**Comment by Coccoonx** [comment]
Yes, the account has an email address. And the view is visible in the layout. 
When I hard code the email address in the layout, it is displayed.

**Comment by mikepenz** [comment]
@Coccoonx and the view for the e-mail has the correct default id?

**Comment by Coccoonx** [comment]
yes

**Comment by mikepenz** [comment]
Can you debug it?

**Comment by vishal1337** [comment]
Can you share the layout for that header?

**Comment by vishal1337** [comment]
Can you share the layout for the custom drawer @Coccoonx
