### ISSUE TITLE
how can I add my Drawer after the toolbar?

### ISSUE THREAD

**Issue by alexsilvadoprado** [mikepenz/MaterialDrawer#799]
I'm using the latest version of MaterialDrawer, I'm trying to create my Drawer below the Toolbar, but I can't find the withDisplayBelowToolbar method in the DrawerBuilder instance... How can I add my Drawer after the toolbar?

**Comment by xzchaoo** [comment]
Hi, you can follow the guide here, https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_show_drawer_under_toolbar.md

**Comment by mikepenz** [comment]
@xzchaoo thanks for answering.
