### ISSUE TITLE
ActionBarDrawerToggle

### ISSUE THREAD

**Issue by yoavst** [mikepenz/MaterialDrawer#8]
How do I set on with custom callback if I can't get the drawer view?

**Comment by mikepenz** [comment]
Can you give a more detailed info about this?

**Comment by yoavst** [comment]
`withActionBarDrawerToggle` support adding `ActionBarDrawerToggle`, but since in its constructor it requires drawer, then it is kind of a problem if you would like to call paramaters in its methods. For example:
```kotlin
 override fun onDrawerClosed(drawerView: View?) {
                super.onDrawerClosed(drawerView)
                }
```

**Comment by mikepenz** [comment]
makes sense :D 

i'll add an option to auto-create a drawer without toolbar. 

I'll also add a method to get the drawerToggle itself back :D. so you should be able to set a listener on it. and i'll remove the withOnActionBarDrawerToggle method.

**Comment by mikepenz** [comment]
@yoavst oh sorry. just saw the ActionBarDrawerToggle requires the view of the DrawerLayout
