### ISSUE TITLE
Click SecundaryItem

### ISSUE THREAD

**Issue by NilakArgento** [mikepenz/MaterialDrawer#80]
I use this for clicks

      .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    // Обработка клика
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id, IDrawerItem drawerItem) {
                        if (drawerItem instanceof Nameable) {
                            Toast.makeText(MainActivity.this, MainActivity.this.getString(((Nameable) drawerItem).getNameRes()), Toast.LENGTH_SHORT).show();
                        }
                        if (drawerItem instanceof SecondaryDrawerItem) {
                            Toast.makeText(MainActivity.this,  MainActivity.this.getString(((SecondaryDrawerItem) drawerItem).getIdentifier()), Toast.LENGTH_SHORT).show();
                        }

                    }
                })

When i click when secundaryitem i get crash !
How to detect when I click in PrimaryItem and SecundaryItem ?!

**Comment by mikepenz** [comment]
@NilakArgento can you please add the crash?

You already add the check `drawerItem instanceof SecondaryDrawerItem``

**Comment by NilakArgento** [comment]
FATAL EXCEPTION: main
    android.content.res.Resources$NotFoundException: String resource ID #0xb
            at android.content.res.Resources.getText(Resources.java:230)
            at android.content.res.Resources.getString(Resources.java:314)
            at android.content.Context.getString(Context.java:327)
            at sevendays.ethnicmedia.us.seven.MainActivity$1.onItemClick(MainActivity.java:98)
            at com.mikepenz.materialdrawer.Drawer$3.onItemClick(Drawer.java:940)
            at android.widget.AdapterView.performItemClick(AdapterView.java:298)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1100)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:2749)
            at android.widget.AbsListView$1.run(AbsListView.java:3423)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mikepenz** [comment]
@NilakArgento do you use v2.0.2?

**Comment by NilakArgento** [comment]
@mikepenz v2.0.1 ! Now i will try the next version

**Comment by mikepenz** [comment]
@NilakArgento ok great update. 

Just as a fact why you had this issue:
https://github.com/mikepenz/MaterialDrawer#style-the-drawer

**Comment by NilakArgento** [comment]
Ok in Manifest i have this
       <application
        android:name="sevendays.ethnicmedia.us.seven.AppController"
        android:allowBackup="true"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >

in  \app\src\main\res\values\styles.xml i have this:
    <resources>

    
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        
        <item name="colorPrimary">#F1433C</item>
        <item name="colorPrimaryDark">#D03033</item>
        <item name="colorAccent">#02A8F3</item>

        
        <item name="material_drawer_window_background">@color/material_drawer_dark_window_background</item>
        <item name="material_drawer_background">@color/material_drawer_dark_background</item>
        <item name="material_drawer_icons">@color/material_drawer_dark_icons</item>
        <item name="material_drawer_primary_text">@color/material_drawer_dark_primary_text</item>
        <item name="material_drawer_secondary_text">@color/material_drawer_dark_secondary_text</item>
        <item name="material_drawer_hint_text">@color/material_drawer_dark_hint_text</item>
        <item name="material_drawer_divider">@color/material_drawer_dark_divider</item>
        <item name="material_drawer_selected">@color/material_drawer_dark_selected</item>
        <item name="material_drawer_selected_text">#F1433C</item>
        <item name="material_drawer_header_selection_text">@color/material_drawer_dark_primary_text</item>
    </style>

</resources>


and in colors.xml 


    <color name="material_drawer_dark_window_background">#303030</color>
    <color name="material_drawer_dark_background">#303030</color>
    
    <color name="material_drawer_dark_icons">#000</color>
    <color name="material_drawer_dark_primary_text">#FFF</color>
    <color name="material_drawer_dark_secondary_text">#DEDEDE</color>
    <color name="material_drawer_dark_hint_text">#ABABAB</color>
    <color name="material_drawer_dark_divider">#555555</color>
    
    <color name="material_drawer_dark_selected">#202020</color>
    <color name="material_drawer_dark_selected_text">@color/material_drawer_primary</color>

**Comment by mikepenz** [comment]
then it should work. 

Do you still get the error?

**Comment by NilakArgento** [comment]
Yes, error on this line

    Toast.makeText(MainActivity.this,  MainActivity.this.getString(((SecondaryDrawerItem) drawerItem).getIdentifier()), Toast.LENGTH_SHORT).show();

**Comment by mikepenz** [comment]
have you set a name as string or the name as ressource?

**Comment by NilakArgento** [comment]
I add items dynamicly
      drawerResult.addItem( new SecondaryDrawerItem().withName(news.getString("name")).withIdentifier(news.getInt("id")));

and now i modifed to this

     .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    // Обработка клика
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id, IDrawerItem drawerItem) {
                        if (drawerItem instanceof PrimaryDrawerItem) {
                            Toast.makeText(MainActivity.this,  MainActivity.this.getString(((PrimaryDrawerItem) drawerItem).getNameRes()), Toast.LENGTH_SHORT).show();
                        }
                       if (drawerItem instanceof SecondaryDrawerItem) {
                            Toast.makeText(MainActivity.this,  MainActivity.this.getString(((SecondaryDrawerItem) drawerItem).getNameRes()), Toast.LENGTH_SHORT).show();
                        }

                    }
                })

**Comment by mikepenz** [comment]
you set the name with the string `.withName()`so you have to get it again with `.getName()`, but in your code you try to get the name with the resource method (which would give you the resource identifier), you haven't set it so it will be null. 

Just change your code to:

```java
Toast.makeText(MainActivity.this, drawerItem.getName(), Toast.LENGTH_SHORT).show();
```
(the drawerItem is instanceof `nameable`)

**Comment by NilakArgento** [comment]
@mikepenz  now it's working, but how i can get the identifer ?! if i will use this getIdentifier i got some errors..

**Comment by mikepenz** [comment]
You can't get the identifier of a string value you set :D. 

either you set the values as String "sometext", or as resource R.string.somtext.

If you want to get the identifier that's something different. The Items allow you to set an identifier with `withIdentifier()` and you can get this one again with `getIdentifier()`

**Comment by phoenixstudio** [comment]
hi there, 
i also encountered this kind of problem.
how to get the position of secondaryitem?

```java
           .build();
        Drawer result = new DrawerBuilder()
                .withActivity(this)
                .withAccountHeader(headerResult)
                .withToolbar(toolbar)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("Home").withIcon(R.mipmap.ic_home_black),
                        new PrimaryDrawerItem().withName("Feed").withIcon(R.mipmap.ic_news),
                        new PrimaryDrawerItem().withName("Exercise").withIcon(R.mipmap.ic_directions_walk_black),
                        new PrimaryDrawerItem().withName("Reward").withIcon(R.mipmap.ic_trophy),//
                        new PrimaryDrawerItem().withName("Buy").withIcon(R.mipmap.ic_google_play),
                        new DividerDrawerItem(),
                        new SecondaryDrawerItem().withName("Settings").withIcon(R.mipmap.ic_settings_black),
                        new SecondaryDrawerItem().withName("Logout").withIcon(R.mipmap.ic_power_settings_black)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(AdapterView<?> adapterView, View view, int position, long l, IDrawerItem iDrawerItem) {

                        Fragment frag = fragmentManager.findFragmentByTag("fragment");
                        fragmentTransaction = fragmentManager.beginTransaction();

                        if(frag != null && frag.isVisible() ){

                        }
                        switch (position) {
                            case 0://home
                                if(frag != null && frag.isVisible() ){
                                    //fragmentTransaction.remove(frag);
                                    //or add to back stack
                                    Log.d("drawer","replace");
                                    fragmentTransaction.replace(R.id.fragment_container, new DashboardFragment(), "fragment");
                                    fragmentTransaction.commit();
                                }else{
                                    Log.d("drawer","add");
                                    fragmentTransaction.add(R.id.fragment_container, new DashboardFragment(), "fragment");
                                    fragmentTransaction.commit();
                                }
                                break;
                            case 1://feed
                                if(frag != null && frag.isVisible() ){
                                    //fragmentTransaction.remove(frag);
                                    //or add to back stack
                                    Log.d("drawer","replace");
                                    fragmentTransaction.replace(R.id.fragment_container, new FeedFragment(), "fragment");
                                    fragmentTransaction.commit();
                                }else{
                                    Log.d("drawer","add");
                                    fragmentTransaction.add(R.id.fragment_container, new FeedFragment(), "fragment");
                                    fragmentTransaction.commit();
                                }
                                break;
                            case 2://exercise
                                if(frag != null && frag.isVisible() ){
                                    //fragmentTransaction.remove(frag);
                                    //or add to back stack
                                    Log.d("drawer","replace");
                                    fragmentTransaction.replace(R.id.fragment_container, new ExerciseFragment(), "fragment");
                                    fragmentTransaction.commit();
                                }else{
                                    Log.d("drawer","add");
                                    fragmentTransaction.add(R.id.fragment_container, new ExerciseFragment(), "fragment");
                                    fragmentTransaction.commit();
                                }
                                break;
                            case 3://reward
                                if(frag != null && frag.isVisible() ){
                                    //fragmentTransaction.remove(frag);
                                    //or add to back stack
                                    Log.d("drawer","replace");
                                    fragmentTransaction.replace(R.id.fragment_container, new RewardFragment(), "fragment");
                                    fragmentTransaction.commit();
                                }else{
                                    Log.d("drawer","add");
                                    fragmentTransaction.add(R.id.fragment_container, new RewardFragment(), "fragment");
                                    fragmentTransaction.commit();
                                }
                                break;
                            case 4://buy
                                Toast.makeText(getApplicationContext(),"Go PRO",Toast.LENGTH_SHORT).show();
                                break;
                            case 5://settings
                                Toast.makeText(getApplicationContext(),"Settings",Toast.LENGTH_SHORT).show();
                                break;
                            case 6://logout
                                Toast.makeText(getApplicationContext(),"Logut",Toast.LENGTH_SHORT).show();
                                LoginManager.getInstance().logOut();
                                //clear shared pref.
                                //clear token
                                //set loggedIn = false
                                Intent main = new Intent(Dashboard.this,Main.class);
                                startActivity(main);
                                finish();

                                break;
                        }
                        Log.d("drawer", "clicked" + position);
                        return false;
                    }
                })

                .build();
```
The logout should be on the 6th button, however in this case when I clicked settings (5th button), the application logs out.

**Comment by phoenixstudio** [comment]
Just realized that case 5 would be the DividerDrawerItem().
Silly me.
It can't be click though, but never mind, I'll work as it is. Thanks :)
