### ISSUE TITLE
Folder names not consistent with package names

### ISSUE THREAD

**Issue by ykrapiva** [mikepenz/MaterialDrawer#800]
Hi Mike, 

Please check folder names DrawerItems and Fragments
MaterialDrawer/app/src/main/java/com/mikepenz/materialdrawer/app/
They are not consistent with package names specified in .java files (different case)
On Windows I cannot compile the project

**Comment by mikepenz** [comment]
@ykrapiva i have rename them to be lowercase. I'm not sure why it still does not name them lowercase. in some cases.

**Comment by mikepenz** [comment]
ok should be fixed now. had to rename them to `fragmentTemp` and then back to `fragment` to make sure those are lowercase
