### ISSUE TITLE
"MaterialTheme" not found

### ISSUE THREAD

**Issue by ykrapiva** [mikepenz/MaterialDrawer#801]
Having attached the library 4.4.6 to my project the compiler started complaining about missing theme "MaterialTheme"
Indeed it is referenced in lib/styles.xml, line 21 but not declared anywhere.
Please add a few words at wiki how to deal with this, if this is a feature of course

**Comment by mikepenz** [comment]
have you added the lib as written:
https://github.com/mikepenz/MaterialDrawer#1-provide-the-gradle-dependency

If not the MaterialTheme comes from a dependency which is the `Materialize` library
https://github.com/mikepenz/Materialize

**Comment by ykrapiva** [comment]
Not sure if this could be a issue for Gradle users but I use Maven on my project.

materialdrawer-4.4.6.pom contains this transitive dependency like this:
<dependency>
      <groupId>com.mikepenz</groupId>
      <artifactId>materialize</artifactId>
      <version>0.2.7</version>
      <scope>compile</scope>
    </dependency>

That is when type not specified - jar is used (not aar)
Hence I have to re-declare aar type dependency explicitly for my compiler be happy
See the lib/build.gradle file where some dependencies have no type specified.

**Comment by mikepenz** [comment]
@ykrapiva ok i will add the @aar annotation for a future update. 

Why don't you use the android default system including gradle?
