### ISSUE TITLE
How can i change the color of the navigation bar?

### ISSUE THREAD

**Issue by Shajeel-Afzal** [mikepenz/MaterialDrawer#803]
Hi, I want transparent navigation bar, can you please tell me how can i do that? Currently it uses primary colour for the navigation bar. 

<img width="480" alt="screen shot 2015-11-09 at 8 49 21 pm" src="https://cloud.githubusercontent.com/assets/3718283/11038201/925ac7e6-8723-11e5-95aa-c3fa4961b5b6.png">

**Comment by mikepenz** [comment]
@Shajeel-Afzal that doesn't seem to be a `MaterialDrawer` specific issue. That can be defined via  theme.

**Comment by mikepenz** [comment]
http://stackoverflow.com/questions/27348336/how-to-change-system-navigation-bar-color
