### ISSUE TITLE
Selectable SwitchDrawerItem?

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/MaterialDrawer#804]
Hi mike, I use the SwitchDrawerItem, and even if I set .withSelectable(false), it remains selectable, and when I click on it, the text and icon colors change, but I want to disable this behavior. Is it a bug?

**Comment by xzchaoo** [comment]
Hi, you can use withToggleEnabled instead.

**Comment by EpsilonOrionis** [comment]
Ok :D. I'll try it.

**Comment by mikepenz** [comment]
@EpsilonOrionis `withSelectable` will not disable the functionality to select a specific item via code.

**Comment by EpsilonOrionis** [comment]
How can I do that?

**Comment by mikepenz** [comment]
@EpsilonOrionis you can't if you programmatically select the item you can also programmatically check if the item is selectable :)

**Comment by mikepenz** [comment]
Perhaps you can provide more information so it is easier to understand why it should be a problem that it is still allowed to programmatically force a selection?

**Comment by EpsilonOrionis** [comment]
Because I just want to use the switch. Making the entire SwitchDrawerItem selectable has no sense (I think). I think that it should be selectable for those who want that functionality, and unselectable for those who don't need that functionality.

**Comment by mikepenz** [comment]
@EpsilonOrionis yeah and why does `withSelectable(false)` not work? this will then forward the click tho the `Switch`?
