### ISSUE TITLE
help

### ISSUE THREAD

**Issue by a3dh4m3d** [mikepenz/MaterialDrawer#805]
hi mike 
when i added 
compile('com.mikepenz:crossfadedrawerlayout:0.0.1-SNAPSHOT@aar') {
        transitive = true
    }
to build.gradle & sync it ,shows this Error : Failed to resolve: com.mikepenz:crossfadedrawerlayout:0.0.1-SNAPSHOT
why?and how i fix it??
tnx

**Comment by mikepenz** [comment]
https://github.com/mikepenz/CrossfadeDrawerLayout/issues/5
