### ISSUE TITLE
DrawerImageLoader not triggered for ACCOUNT_HEADER

### ISSUE THREAD

**Issue by fliespl** [mikepenz/MaterialDrawer#806]
Hi Mike,
probably (as most of the time) I am doing something wrong. I am trying to setup glide to be used for ACCOUNT_HEADER. I have setup that up as in CustomApplication. It's triggered properly for PROFILE, but not ACCOUNT_HEADER. Am I missing something here?

```
            @Override
            public void set(ImageView imageView, Uri uri, Drawable placeholder) {
                Glide.with(imageView.getContext()).load(uri).placeholder(placeholder).into(imageView);
            }

            @Override
            public Drawable placeholder(Context ctx, String tag) {
                if (DrawerImageLoader.Tags.PROFILE.name().equals(tag)) {
                    return new IconicsDrawable(ctx).icon(GoogleMaterial.Icon.gmd_account_circle).color(Color.WHITE);
                } else if (DrawerImageLoader.Tags.ACCOUNT_HEADER.name().equals(tag)) {
                    return new IconicsDrawable(ctx).iconText(" ").backgroundColorRes(R.color.md_grey_100).sizeDp(56);
                }
                return super.placeholder(ctx, tag);
            }
```

**Comment by mikepenz** [comment]
@fliespl where do you expect the two different types to show up?

**Comment by fliespl** [comment]
I assume that both ACCOUNT_HEADER and PROFILE images should trigger glide. In my case only profile image is loaded by glide. Header Background image is not - is that correct behaviour? Your example suggests that both images should trigger glide loader.

**Comment by mikepenz** [comment]
@fliespl if you set the header as url it should load via glide yes. perhaps this is an issue

**Comment by fliespl** [comment]
@mikepenz As always - thank you for your help. You are totally right - I traverse it into the code and the only way it loads via Glide is when using url. I will just set background header on my own. 

Probably it would be a nice feature to add to limit OOMs?

**Comment by mikepenz** [comment]
@fliespl you can get the reference to the header view and set it via glide then :D

**Comment by fliespl** [comment]
Yeah, that's what I have done now :) 

I am already using it for a few items (getting header view), but I didn't come up with an idea I could also do it with header imageview - that's what happens when you are totally exhausted ;)
