### ISSUE TITLE
Multiple selectable items

### ISSUE THREAD

**Issue by sinystr** [mikepenz/MaterialDrawer#807]
If in my app I have two sections:

Themes
- DARK
- LIGHT

Page
- HOME
- CONTACTS

How can I make Theme and Page sections independent selectable sections. 
For example, I'm in Home with Dark theme and I want them both selected, is it possible to do that?
Thanks in advance, your lib is awesome!

**Comment by mikepenz** [comment]
@sinystr sorry there is no multi selection possible. 

If you really would need something like this i would suggest that you change the background for the selected item.

**Comment by sinystr** [comment]
Thank you! But what do you mean by changing background?

**Comment by mikepenz** [comment]
You implement a `CustomDrawerItem` which allows you to define a different background. And depending on the state you set the background for the item and update it
