### ISSUE TITLE
Name with recent accounts

### ISSUE THREAD

**Issue by alhaythamapps** [mikepenz/MaterialDrawer#808]
How should I display the name under a recent account image?
Something like Mike's name in the attached image.
![untitled](https://cloud.githubusercontent.com/assets/14263880/11126727/baa538cc-8989-11e5-8f36-771dd486bd90.png)

**Comment by mikepenz** [comment]
@alhaythamapps this is not possible. and would require lot of custom handling on your side.

You would have to modify the layout, add the name below the image, hook into the account changed callback and always update this. 
Would be a lot of custom handling.

**Comment by alhaythamapps** [comment]
Can I share my customization with you to get your feedback?

**Comment by mikepenz** [comment]
You can :D but keep in mind this depends on a lot of custom handling on your side. :D This is nothing which is specified in the Material Design Guidelines, and seems to be a very special behavior :D

**Comment by alhaythamapps** [comment]
@mikepenz Here are my 3 steps:
1. Override the buildProfiles() method from AccountHeaderBuilder class:
2. Create a modified copy of your material_drawer_header.xml :D
3. Create an account header using the new layout:
        mAccountHeader = new AccountHeaderBuilderX()
                .withActivity(this)
                .withAccountHeader(R.layout.material_drawer_header_x)
                .build();

[material_drawer_header_x.txt](https://github.com/mikepenz/MaterialDrawer/files/33236/material_drawer_header_x.txt)

[AccountHeaderBuilderX.txt](https://github.com/mikepenz/MaterialDrawer/files/33234/AccountHeaderBuilderX.txt)

**Comment by mikepenz** [comment]
@alhaythamapps i haven't run it but the code seems ok. So does it work for you? 
There may be some problems with RTL layout so if you are going to have RTL languages you should check this too. 

And theoretically it should be possible to do it without overriding the AccountHeaderbuilder class just by hooking in the listeners, but it may cause some other problems. So your solutions seems to be a good idea ;).

**Comment by alhaythamapps** [comment]
I'm using v4.4.6, and my code works well. Thanks :)
But I noticed that the ```android:id``` attributes had different values in two different versions of the library. My code does not work with both.

**Comment by mikepenz** [comment]
@alhaythamapps which `id` do you mean?

**Comment by alhaythamapps** [comment]
@mikepenz I started with v3.1.0 and all the view ids in your ```material_drawer_header.xml``` are different in v4.4.6

**Comment by mikepenz** [comment]
@alhaythamapps yes with v4 i did some huge refactoring ;). sorry for this. but now they will stay like this ;). 

Thanks for your addition to the project!

**Comment by alhaythamapps** [comment]
Thanks to you :)
