### ISSUE TITLE
Custom header ?

### ISSUE THREAD

**Issue by korrio** [mikepenz/MaterialDrawer#81]
I want to implement OnClickListener and Update view of header.
How to accomplish this ?

All I know is that the view of header is fixed (R.layout.header) and can't be updated.

**Comment by mikepenz** [comment]
@korrio do you talk about the AccountHeader? If yes have you implemented it yet? You should check the AccountHeader.Result object which gives you references to all views within the header.

If you talk about the normal header for the Drawer there is also a Drawer.Result you get from the .build() method and this also contains methods to get the references to the views (like the headerView)

**Comment by korrio** [comment]
for example I want to add OnClickListener to the 2 buttons on header.
![screen shot 2015-03-11 at 5 44 23 pm](https://cloud.githubusercontent.com/assets/2325299/6594739/6c2240b2-c816-11e4-891d-b30c2f2e7aa1.png)

**Comment by mikepenz** [comment]
You can set the header by layout or by view (for the normal Drawer) this will disallow the AccountHeader but i don't think you need it. 

Then you can easily get the view of the header from the Result Object and just add the onClickListener to it. Should work.
