### ISSUE TITLE
Possibility to get DrawerLayout opened width

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/MaterialDrawer#810]
I want to scroll the content parallel to the drawers I have. Therefore I need to know the opened drawer width. Can I somehow get it?

I think you are using the material standards for it, so I can calculate it myself as well, but maybe there's a way to get it out of your library? Probably somewhere you have the function for anyways...

**Comment by mikepenz** [comment]
the drawer width is calculated with the following method:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/util/DrawerUIUtils.java#L125

**Comment by MFlisar** [comment]
It's public, perfect. Thank you very much.
