### ISSUE TITLE
CustomView and statusbar - gray bar

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/MaterialDrawer#811]
I try to setup a drawer with a custom view. If I display it below the statusbar, it shows a gray bar on top, if not, the custom view slips underneath the statusbar...

Here's how I use it:

	ViewGroup placeholder = new LinearLayout(this);
	placeholder.setId(R.id.placeholder);

	// right drawer
	mDrawerRight = new DrawerBuilder()
			.withActivity(this)
			.withDisplayBelowStatusBar(true)
			.withDrawerGravity(Gravity.RIGHT)
			.withCustomView(placeholder)
			.build();

**Comment by mikepenz** [comment]
@MFlisar can you please add a screenshot?

**Comment by MFlisar** [comment]
Sure

![screenshot_2015-11-13-18-11-59](https://cloud.githubusercontent.com/assets/2437726/11152319/153b0656-8a32-11e5-8d28-a3f1527dfe73.png)

**Comment by mikepenz** [comment]
this is caused by the following setting: `.withDisplayBelowStatusBar(true)`

The `NonTranslucentDrawerActivity` showcases what you are trying to achieve:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/NonTranslucentDrawerActivity.java#L38
