### ISSUE TITLE
How to disable RTL support in my drawer?

### ISSUE THREAD

**Issue by alirezaaa** [mikepenz/MaterialDrawer#812]
Hi,

I want to have texts always left-to-right (disabling RTL support) in my drawer. How can I do that? Thanks.

**Comment by mikepenz** [comment]
@alirezaaa you can't. layouts automatically show as RTL if an RTL language is present. not sure if this is possible at all. the only possibility would be that you overwrite the layouts and remove all RTL annotations. but it will still leave some things RTL on an RTL set phone. but this is android specific not library specific

**Comment by alirezaaa** [comment]
I found a good solution. If somebody wants to have always LTR text, adds ```\u200E``` character at the start of the text. Thanks anyway :)

**Comment by mikepenz** [comment]
@alirezaaa interesting tip ;). thanks for adding it. did not know that you can cheat for LTR text ;)

**Comment by copypastestd** [comment]
@alirezaaa I have tried to use your advise, with some herbew String city 
`new SecondaryDrawerItem().withLevel(2).withName("\u200e" + city)`
But Drawer itemtext still RTL.

**Comment by mikepenz** [comment]
@copypastestd your app is RTL compatible? targetSdk > 17?

**Comment by copypastestd** [comment]
@mikepenz       
minSdkVersion 16
targetSdkVersion 23

**Comment by mikepenz** [comment]
@copypastestd real RTL support was added in API 17. I am not sure how it handles this. You have to enable `RTL` support in the manifest too.
