### ISSUE TITLE
How to update account details on my drawer?

### ISSUE THREAD

**Issue by alirezaaa** [mikepenz/MaterialDrawer#813]
Hi again :)

How can I update my account details on my drawer? Thanks.

**Comment by mikepenz** [comment]
@alirezaaa you update the account as you would update a normal `drawerItem` 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L236

**Comment by alirezaaa** [comment]
@mikepenz Thanks for your response. That's what I'm looking; But now, I'm looking for a good solution to update my drawer on `onResume()`. What is your idea/solution for that? Thank you.
