### ISSUE TITLE
Selecting drawer items does not work with hw keys.

### ISSUE THREAD

**Issue by tagsoft** [mikepenz/MaterialDrawer#815]
I have recently updated my app to v4.4.6, and it seems the selection does not work with the hardware keys.(D-pad on a TV, or the cursor keys in the emulator)
I think this is because of the new RecyclerView implementation. In earlier versions it was possible to navigate with hw keys in the drawer.

**Comment by mikepenz** [comment]
@tagsoft that could be. i do not have a tv or d-pad to test with. I have a normal `RecyclerView` and `Adapter`. If the `RecyclerView` doesn't support it a am afraid i can't too

**Comment by mikepenz** [comment]
It seems this must be implemented manually when using a `RecyclerView`

http://stackoverflow.com/a/28838834/325479
