### ISSUE TITLE
Can the hamburger icon be changed?

### ISSUE THREAD

**Issue by Orbyt** [mikepenz/MaterialDrawer#816]
Just wondering if its possible to change the hamburger icon to a custom one. I found this issue: https://github.com/mikepenz/MaterialDrawer/issues/652 which made it sound like it was possible but didnt mention how.

**Comment by drinfernoo** [comment]
You can use any DrawerToggle you'd like, doesn't have to be the one from this library.

**Comment by Orbyt** [comment]
@drinfernoo what is a `DrawerToggle`?

I'm guessing you just mean the icon? If so, yes, thats what im asking about.

**Comment by drinfernoo** [comment]
http://developer.android.com/reference/android/support/v4/app/ActionBarDrawerToggle.html

**Comment by mikepenz** [comment]
@Orbyt if you don't provide a `Toolbar` to the `DrawerBuilder` you can use any `DrawerToggle` or any custom open/close logic for your drawer as you like to. That's then a android thing ;).

**Comment by Orbyt** [comment]
@mikepenz Again im only talking about the icon itself, not custom toggle functionality. Can the icon be changed?

**Comment by mikepenz** [comment]
@Orbyt as far as i know. the `ActionBarDrawerToggle` does not allow this. please use google or stackoverflow to look for this answer. The drawer allows you any custom logic to open/close. No need to use the default `ActionBarDrawerToggle` which has the defined style.
