### ISSUE TITLE
Can't add dependency :(

### ISSUE THREAD

**Issue by drinfernoo** [mikepenz/MaterialDrawer#817]
I cannot get this dependency to work :( My build.gradle is [here](http://pastebin.com/erpFmP90).

For some reason, I am getting an "Unknown dependency" error at compile-time. What am I doing wrong?

**Comment by mikepenz** [comment]
@drinfernoo probably your Android Studio / gradle is in offline mode? The library is on maven central so there are no issues

**Comment by mikepenz** [comment]
http://search.maven.org/#artifactdetails%7Ccom.mikepenz%7Cmaterialdrawer%7C4.4.6%7Caar
