### ISSUE TITLE
How do i prevent selection of item when its already selected?

### ISSUE THREAD

**Issue by raghunandankavi2010** [mikepenz/MaterialDrawer#818]
If item at position 2 is already selected clicking on the item should just close the drawer.

In my case i have a activity. So it opens twice. Any way to prevent this?

**Comment by mikepenz** [comment]
@raghunandankavi2010 it should not be selected if it opens an activity that makes no sense :D 
else you will have to check this on your own inside the click listener.

**Comment by raghunandankavi2010** [comment]
hmm. go it. close the issue
