### ISSUE TITLE
Spinner Drop Down Icon Missing on API 16

### ISSUE THREAD

**Issue by sdeff** [mikepenz/MaterialDrawer#82]
As you can see here in the AccountSwitcher Section:

![navdrawerissue](https://cloud.githubusercontent.com/assets/2885756/6571396/3e1ad4a4-c708-11e4-9e59-31d64d95dbb9.png)

(Atleast API 16 is affected by this.)

**Comment by mikepenz** [comment]
@sdeff what's the device and android version you use for pre lollipop?

**Comment by sdeff** [comment]
I first tested it with API 16 (Android Emulator Genymotion).

Also I just noticed that on API 17 it's working as supposed to. So it seems not all Pre-Lollipop devices are affected!

Btw.: Thanks for your great library! I've tried a lot of different Material Drawer libs and yours is the easiest to use and one of the few which takes Material Design seriously.

**Comment by mikepenz** [comment]
@sdeff thanks. 

I'll try to get it running on these devices too :D have none to test. but yeah i'm sure i'll find the solution.


thank you so much :)

**Comment by mikepenz** [comment]
@sdeff i've started it on a nexus 5 API Level 16 emulator and it works :/

**Comment by mikepenz** [comment]
@sdeff even on a Nexus 4 API Level 10 it's working. Did you use any special configuraiton? Just one profile? Or something like this?

**Comment by sdeff** [comment]
@mikepenz I'm sorry for my late response.

I've tested this on the Genymotion emulator (https://www.genymotion.com) with API 16 and no custom settings applied.

Maybe it's just an emulation problem? Even though the spinner icon was there on other APIs with the same emulator. Sadly I don't have a real API 16 device to test...

**Comment by mikepenz** [comment]
@sdeff yeah i also only have the chance to test it on the real Android emulator. It works even with API 10 (tested a lot of different API levels)

**Comment by sdeff** [comment]
I just tried to reproduce again it with the latest Genymotion version and the spinner icon was always there no matter which settings or API version I chose.

I don't know why it disappeared but I can tell you that my screenshot was not photoshopped! ;-)

It seems everything is working fine and I'm sorry if my issue report wasn't an issue at all...

**Comment by mikepenz** [comment]
@sdeff ok if it is working everything is fine :) Thanks for trying it.
