### ISSUE TITLE
Duplicate Toolbar on text selection

### ISSUE THREAD

**Issue by rubengees** [mikepenz/MaterialDrawer#820]
For some of the `TextViews` in my layout I enabled `android:textIsSelectable="true"`.
Now if I select some text the Toolbar with the selection is above the normal Toolbar, see the Screenshot:

![unbenannt](https://cloud.githubusercontent.com/assets/8021265/11177829/aaabb5d8-8c48-11e5-84e0-a6590c8a3724.png)

I don't know if this is an issue with this Lib, the Materialize lib or has nothing to do with this Lib at all, but I thought I might ask :)

**Comment by rubengees** [comment]
Okay, not a library issue, happens on a sample project without your lib, too.

**Comment by rubengees** [comment]
If anybody is experiencing the same: Set `<item name="windowActionModeOverlay">true</item>` in your theme.

**Comment by mikepenz** [comment]
@rubengees is in the sample app :D 
https://github.com/mikepenz/MaterialDrawer/blob/d94f12c3590a037d1f122d6bff0b00dab728b32a/app/src/main/res/values/styles.xml#L24

**Comment by rubengees** [comment]
Yes, didn't look into that... :D
