### ISSUE TITLE
Expandable list in drawer

### ISSUE THREAD

**Issue by swapthedude9423** [mikepenz/MaterialDrawer#822]
is there any way to add expandable item in Material Drawer??? if there any method, I cannot find it. Can you suggest me if any???

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/658
https://github.com/mikepenz/MaterialDrawer/issues/552
https://github.com/mikepenz/MaterialDrawer/issues/372
https://github.com/mikepenz/MaterialDrawer/issues/141
