### ISSUE TITLE
RemoveItem from drawer messes up selected item

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/MaterialDrawer#823]
I use a function like following:

	void onNetworkContactsLoaded()
	{
		int selectedIdentifier = mDrawer.getCurrentSelection();
		mDrawer.removeItem(ID_PROGRESS_LOADING_NETWORKS);

		mDrawer.getDrawerItem(ID_PROFILES).withSelectable(true);
		mDrawer.getAdapter().notifyItemChanged(mDrawer.getPosition(ID_PROFILES));

		mDrawer.setSelection(selectedIdentifier, false);
	}

With saving and restoring the selection, it seems to internally mess up the selection. I manually save the selected identifier and after restoring this identifier, I see it's one off after calling above function...

**Comment by mikepenz** [comment]
@MFlisar why do you remember the selection manually? this is already done by the drawer? 

For the above thing. Do you have a header? the position will be +1 if there is a header

**Comment by MFlisar** [comment]
I could see following behaviuor: rotating the device moves the selection down by one... And this is done on every turn.

I'm remembering it as I save it beyond application lifecycle - whenever the app is restarted I use my manually saved idenetifier to restore the last known position...

**Comment by mikepenz** [comment]
@MFlisar but why don't you just save the already remembered position from the drawer?
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L230

Here's the logic which saves the savedInstance:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L923

And here it's loaded again:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1699

**Comment by MFlisar** [comment]
I add/remove items and I do that asynchronous. Therefore I use the id. I save the last selected id in my preferences as well, as I said, I want to restore the last position on every app start again not only between an activity lifecycle...

**Comment by mikepenz** [comment]
@MFlisar the above was only reference how it's done internally. 

And you are sure your item's identifier stay the same? If you do not set the identifier the drawer provides a own unique identifier (which will may be different on a new launch)

The code itself seems ok

---------------
As a side note you should not update an item like this:
```java
    mDrawer.getDrawerItem(ID_PROFILES).withSelectable(true);
    mDrawer.getAdapter().notifyItemChanged(mDrawer.getPosition(ID_PROFILES));
```
there is the following method:
```java
   mDrawer.updateItem(mDrawer.getDrawerItem(ID_PROFILES))
```

**Comment by MFlisar** [comment]
Yes I am. I just updated an old version from 3.XX to the last version and I always needed IDs for being on the save side... I define all my ids like `final static int ID PROFILES = 1;` and use these constants then...

My workaround is working... Even if the ids would change (what they don't do), they don't change in the function I posted. I don't think it would solve the problem then to read the current selected identifier, delete the menu entry and set the selected identifier...

And I'll use the update method to selectively update menu items in the future, thanks for the hint

**Comment by mikepenz** [comment]
@MFlisar strange enough. I really do not see a point why it should mess up the selection somewhere.

**Comment by MFlisar** [comment]
I just saw that in the builder you save a selected position and a selected identifier... Didn't check that in detail as I'm not at home, but maybe the selected position should be decreased in the delete function if the deleted position is smaller than the currently selected position...

**Comment by mikepenz** [comment]
yeah but as far as you posted the code above you use the identifier. and set it again via identifier

**Comment by MFlisar** [comment]
I just checked it, I use ID based functions only. But nevertheless, mixing them should not make a problem...

But I see following:
* `mDrawer.getCurrentSelection` get's the ID based on the selected position
* `mDrawer.setSelection` set's the selected position!

So I assume, deleting an item should update the drawers selected position accordingly... As whenever I use `mDrawer.setSelection` internally the position is saved not the position independent id...

**Comment by mikepenz** [comment]
@MFlisar `setSelection` get's the position from an identifier. So it is also identifier based, which should be fine then :/

**Comment by MFlisar** [comment]
Correct, that's why my workaround works! If I don't set the old identifier with 
`setSelection` again the drawer will internally have saved the OLD position. After calling `setSelection` it will see "oh, this id is on a new position, because an item on a smaller index was deleted" and will correct the internal position.

But this should happen in the `removeItem` function of the `RecyclerView`...

Example:

* `setSelection(1)` will set index 10 as selected
* `removeItem(2)` => drawer will see, item with id 2 is at position 2, so it removes the `IDrawerItem` at position 2. This should lead to update the selected position to 10, as position 2 is smaller than the selected position, so the selected position should be set to 10 - 1...
* `setSelection(1)` again, will correct everything, as it will look up the position of id 1, which is now 9
