### ISSUE TITLE
Implement in App with several activities 

### ISSUE THREAD

**Issue by Amenocy** [mikepenz/MaterialDrawer#824]
hello
i want to use Your MaterialDrawer in my app with 3-4 activities , 
i created one "BaseActivity" class , implement Drawer here and add items and ...
Other activities extends BaseActivity and have a drawer , 
but my problem is there , i want to edit drawer and remover o add items from code , then my change only applied  to one instance of baseactivity (only to current activity for example MainActivity) . but i want apply to all activities ? 
how i can do ? implement Listeners ? Or other way ?

**Comment by mikepenz** [comment]
@Amenocy That's up to you. Nothing MaterialDrawer specific. 

Somewhere you have to keep track of the changes and in the onResume of the activities you update the drawer with the new details

Perhaps you could change your content areas to be fragments and not different activities.

**Comment by moslem-pc** [comment]
@Amenocy Amin i tried to to the same thing u did, but i cant even have the drawer on my activities!
Once i add the code on my BaseActivity class i get a runtime error which is:
`
Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
`
The sample code i use on onCreate method of BaseActivity:
```java
new DrawerBuilder()
                .withActivity(this)
                .addDrawerItems(
                        item1,
                        new DividerDrawerItem(),
                        item2,
                        new SecondaryDrawerItem().withName("Item 3")
                )
                .build();
```

**Comment by NoelChew** [comment]
you have to setContentLayout first before creating the drawer.
Try placing these codes in onResume of your BaseActivity.
