### ISSUE TITLE
Close drawer automatically after clicking on header account items while started activity is singleTop

### ISSUE THREAD

**Issue by alirezaaa** [mikepenz/MaterialDrawer#826]
Hi Mike,

I'm using the v4.4.6 and in this version (or maybe newer versions) after clicking on the header account profiles the drawer will not be closed automatically while the started activity is singleTop (with `Intent.REORDER_TO_FRONT` flag used).

There is no such bad behavior for clicking on the drawer items in this situation. In other words, clicking on the drawer items is what I suspect.

**Comment by mikepenz** [comment]
@alirezaaa i am sure that has nothing to do with the singleTop :D

Just an assumption. You return `true` in the listener.

**Comment by alirezaaa** [comment]
You're great @mikepenz <3
