### ISSUE TITLE
Unable to show another view behind the status bar

### ISSUE THREAD

**Issue by AkshayChordiya** [mikepenz/MaterialDrawer#829]
Hi @mikepenz this is an amazing library. 

Previously I was using my own implementation where my `Drawer` layout was behind the statusbar and I also have an layout which expands and which goes behind the status bar.
But with this library the Drawer is perfectly fine but the layout which expands is showing below status bar not behind.
I used this flag to show content behind the status bar:
```
getWindow().getDecorView().setSystemUiVisibility(
                        View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                                | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
```

I'm trying lots of combination of methods in this library like `withFullScreen()` etc, yet they haven't worked great and I'm trying.
Waiting for your response. Thank you.

**Comment by mikepenz** [comment]
Take a look at the sample activity. 

There is the `FullScreenDrawerActivtiy`
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/FullscreenDrawerActivity.java

and the `CollapsingToolbarActivity` both show content behind the satusbar
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CollapsingToolbarActivity.java

**Comment by AkshayChordiya** [comment]
@mikepenz
Thank you for fast response. But what I meant `Drawer` looks great and is behind the status bar. But I have another view with on swiping up also goes behind the status bar because I was using the `flag` which I mentioned above. Currently the swiped view is shown below the status bar which is colored and the swiped view.
I want to show both `Drawer` and the view after swiping behind the status bar. I''ll attach few screenshots.

**Comment by AkshayChordiya** [comment]
Check out the screenshots below. You'll get what I want to achieve with this library.

![drawer](https://cloud.githubusercontent.com/assets/3120052/11330023/289a207a-91ca-11e5-984e-39e433b40383.png)
![expanded panel](https://cloud.githubusercontent.com/assets/3120052/11330024/289e0528-91ca-11e5-9836-1c2b03cc192b.png)
![base ui](https://cloud.githubusercontent.com/assets/3120052/11330025/28a26e92-91ca-11e5-941e-b6f166792945.png)

**Comment by mikepenz** [comment]
@AkshayChordiya if your view needs to go up completely you will have to do the things mentioned above. for the `Toolbar` you have to provide the padding of the `StatusBar` as this is the only element which moves not below the statusbar

**Comment by AkshayChordiya** [comment]
@mikepenz I'll try it out and let you know about it.
Thank you so much.
