### ISSUE TITLE
Are there any option to set a Profile selected by default? 

### ISSUE THREAD

**Issue by Spiderbezno** [mikepenz/MaterialDrawer#83]
Something like setSelectionByIdentifier??

**Comment by mikepenz** [comment]
@Spiderbezno no there are no such methods for the AccountHeader yet. Will add them in the future.

**Comment by Spiderbezno** [comment]
Ok thank you very mutch

**Comment by salvolf** [comment]
News about this new "feature" ?

**Comment by mikepenz** [comment]
@salvolf there is `setActiveProfile()` on `AccountHeader` so you can use this one
