### ISSUE TITLE
Sticky header background is always overrided by R.color.material_drawer_background

### ISSUE THREAD

**Issue by AndrazP** [mikepenz/MaterialDrawer#830]
Hi @mikepenz!

I would like to use a sticky header with a different background than the rest of the drawer, but I have encountered a problem. 
Problem lies in DrawerUtils.java line 215:
```
 //set a background color or the elevation will not work
drawer.mStickyHeaderView.setBackgroundColor(UIUtils.getThemeColorFromAttrOrRes(drawer.mActivity, R.attr.material_drawer_background, R.color.material_drawer_background));
```
Background of sticky header layout is always overridden with R.color.material_drawer_background.

**Comment by mikepenz** [comment]
@AndrazP because this is the default as of the Material Design Guidelines. 

A quick solution would be that you get the reference to the view of the Sticky Header and change the color to any color which fits your needs.

**Comment by AndrazP** [comment]
Oh, I didn't know that. 
I have fixed it by surrounding the header layout with additional FrameLayout and setting background color on its child.
