### ISSUE TITLE
Can CrossfadeWrapper class be a part of the library?

### ISSUE THREAD

**Issue by androideveloper** [mikepenz/MaterialDrawer#831]
I use MiniDrawer and have to copy CrossfadeWrapper class to my project.

 mMiniDrawer.withCrossFader(new CrossfadeWrapper(mCrossFader));

Can it be moved to the library?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/Crossfader

**Comment by androideveloper** [comment]
Hi, Mike. Should i create issue there?

**Comment by mikepenz** [comment]
@androideveloper no it's no issue. it is simply a separat project. so if you want the `Crossfader` you just include the `Crossfader` dependency. and done. 

I have done this so i can update both separately

**Comment by androideveloper** [comment]
Yeah, i understand that. But my question is the following: 
mMiniDrawer.withCrossFader(new CrossfadeWrapper(mCrossFader));

We have to create and use CrossfadeWrapper. My question is can this class be part of this library? Or can architecture be changed so i can use
mMiniDrawer.withCrossFader(mCrossFader);

**Comment by mikepenz** [comment]
@androideveloper no this is not possible. Both libraries do not depend on each other, so this has to stay without the other. If you want it you just implement the `CrossfadeWrapper` and done.

**Comment by androideveloper** [comment]
Ok, thanks ;)
