### ISSUE TITLE
side shadow problem

### ISSUE THREAD

**Issue by arash-jahani** [mikepenz/MaterialDrawer#832]
![device-2015-11-24-113444](https://cloud.githubusercontent.com/assets/2876900/11361058/7f358458-929f-11e5-98c2-4f8613f1e88d.png)
hi guys,
i have shadow problem in left side of drawer,how solving this?(problem in android<5)

**Comment by mikepenz** [comment]
have you defined `GravityCompat.START` as gravity for RTL support?
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1533

**Comment by arash-jahani** [comment]
thanks, just needed to update.
