### ISSUE TITLE
No resource found that matches the given name 'MaterialTheme'.

### ISSUE THREAD

**Issue by shubhamgupta2901** [mikepenz/MaterialDrawer#833]
Hey Mike,
After adding the dependency to my project, When I am syncing the project with Gradle Files,Following Errors pop up:
Error retrieving parent for item:No resource found that matches the given name 'MaterialTheme', 
Error retrieving parent for item: No resource found that matches the given name 'MaterialTheme.ActionBar'.

And so on.

Whats the issue?

**Comment by mikepenz** [comment]
please follow the instructions in the readme:
https://github.com/mikepenz/MaterialDrawer#1-provide-the-gradle-dependency

if you do not add the sub dependencies it won't work
