### ISSUE TITLE
Initial Setup gradle build errors

### ISSUE THREAD

**Issue by royjavelosa** [mikepenz/MaterialDrawer#835]
I am new to this library and would like to try it but I encounter this error right after I added the dependency

    compile('com.mikepenz:materialdrawer:4.5.1@aar') {
        transitive = true
    }

The error is :+1: 

C:\Dev\AndroidWorkspace\NotBoringActionBar-master\App\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.1.1\res\values-ldltr-v21\values-ldltr-v21.xml
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Spinner.Underlined'.

**Comment by mikepenz** [comment]
@royjavelosa the error is not `MaterialDrawer` specific. Seems like you probably use old versions of the appcompat lib in your project, or that there are other issues inside your `build.gradle`
