### ISSUE TITLE
ProfileDrawerItem overlapping on small resolution 

### ISSUE THREAD

**Issue by AlexBrechmann** [mikepenz/MaterialDrawer#836]
First, thank you for developing this great drawer! 
I found a strange behavior on our current project.

If you add a profile withName and withIcon to an AccountHeader it is overlapping on a small resolution  e.g. hdpi (480x800).
I tried it with your application and it got the same behavior.
 
![screen shot 2015-11-26 at 15 47 59](https://cloud.githubusercontent.com/assets/15260035/11425632/80022180-9456-11e5-85a7-7de5173c42e3.png)

**Comment by AlexBrechmann** [comment]
Currently i'm using the following workaround:

        DisplayMetrics dm = new DisplayMetrics();
        getWindowManager().getDefaultDisplay().getMetrics(dm);
        int screenHeight = dm.heightPixels;

        AccountHeader accountHeader;
        if (screenHeight <= 854) {
            accountHeaderBuilder.withHeightDp(170);
        }

        accountHeader = accountHeaderBuilder.build();

**Comment by mikepenz** [comment]
@AlexBrechmann i tested this on even smaller devices / emulators on my pc and this issue did not happen. this only occurs when you have custom dp setting, which seems to break some internal spacings.

**Comment by AlexBrechmann** [comment]
Hey, thanks for your feedback. 
Thats kinda weird, because we don't use custom dp settings.

I tried it on some emulators with different API-levels & resolutions.
Everytime i used a pre-defined device (Nexus S, Nexus One) it's broken.
While i use a generic device (3.2" HVGA, 3.7" WVGA) everything is fine.
I think the problem belongs to those pre-defined devices, because on all of your real devices it works just fine. 

Here are some emulator-examples:

Nexus S
![nexus_s_480_800](https://cloud.githubusercontent.com/assets/15260035/11439585/c5c4df7c-94fc-11e5-9e90-62c35f54c86c.png)
Nexus One
![nexus_one_480_800](https://cloud.githubusercontent.com/assets/15260035/11439586/c5c63dfe-94fc-11e5-831f-cc4296bfabbb.png)
3.2" HVGA
![hvga_320_480](https://cloud.githubusercontent.com/assets/15260035/11439584/c5c43ae0-94fc-11e5-9ba3-f92ff43a9807.png)

**Comment by mikepenz** [comment]
@AlexBrechmann interesting. i tested all the android versions + resolutions with genymotion. perhaps the android emulators are a bit different. have to try

**Comment by AlexBrechmann** [comment]
@mikepenz I was using the Android Studio emulators. While testing i printed some log-messages with the current resolutions and they were correct on each emulator e.g. 480x800 / 320x480

**Comment by mikepenz** [comment]
@AlexBrechmann i added an additional check and algorithm for this behavior. If the height of the header is to low to fit all the components like current selection profile view, and the text selection, it will then change the height to the min required height. this will make those items in a different ratio than 16/9 but it will fit all elements. a different solution would be to change the size of the primary selected account, so we can stay with the 16/9 ratio of the header. 
both behaviours are not defined in the Material Design Guideliens
