### ISSUE TITLE
Example using Load images via URL

### ISSUE THREAD

**Issue by emilhamep** [mikepenz/MaterialDrawer#837]
I've tried to implement the example code that you have given(CustomApplication.java). But i don't know how to call it to my Activity and start to call image from URL. Could you give me an example in order to call CustomApplication.java for set header profile picture Drawer? more comprehensive please. Thanks in advance.

**Comment by mikepenz** [comment]
@emilhamep you do not have to call the `CustomApplication`. After you created the `ImageLoader` implementation you can simply start setting the icon via URL on the `DrawerItems`

**Comment by emilhamep** [comment]
Ok first of all thank you for your respons. I just wondering i.e with Picasso library. How to implement it to method: 
.withIcon(getResources().getDrawable(R.drawable.profile_picture))

Thank you again
