### ISSUE TITLE
StatusBar color cannot be changed

### ISSUE THREAD

**Issue by beta** [mikepenz/MaterialDrawer#839]
I'm using MaterialDrawer in a container activity for three fragments. Each fragment has its own style so I need to change the activity theme at runtime like:

```java
public class HomeFragment extends BaseFragment {
    
    ...
    
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        final Context contextThemeWrapper =
                new ContextThemeWrapper(this.getActivity(), R.style.HomeTheme);
        LayoutInflater themeInflater = inflater.cloneInContext(contextThemeWrapper);
        View view = themeInflater.inflate(R.layout.fragment_home, container, false);
        
        ...
    }
}
```

And here are the themes in `styles.xml`:

```xml
<style name="AppTheme" parent="MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus">
    <item name="colorPrimary">@color/indigo_500</item>
    <item name="colorPrimaryDark">@color/indigo_700</item>
    <item name="colorAccent">@color/pink_accent_200</item>
</style>

<style name="HomeTheme" parent="AppTheme">
    <item name="colorPrimary">@color/green_500</item>
    <item name="colorPrimaryDark">@color/green_700</item>
</style>

...
```

When running the app and switching to the fragment, the color of Toolbar (or app bar) can be changed correctly from indigo to green. But the color of StatusBar remains indigo and cannot be changed. Could anyone tell me why this problem occurs and how to solve it? Thank you.

**Comment by mikepenz** [comment]
@beta the color of the `StatusBar` gets set from the `ScrimInsetsFrameLayout` which comes with the drawer. there is a method which allows you to change the color: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L160

**Comment by beta** [comment]
@mikepenz Thanks Mike. This method works, though I need to write an extra line of code to set the color of status bar separately.

**Comment by mikepenz** [comment]
@beta yes. but this is required as the content moves below the `StatusBar` to allow the drawer to be full height.
