### ISSUE TITLE
Async profile images + 1 profile only (no other profiles menu)

### ISSUE THREAD

**Issue by yoavst** [mikepenz/MaterialDrawer#84]
What can I do in this case? I use Ion

**Comment by mikepenz** [comment]
There is no issue about having only 1 profile.

You can download the image at any point and update the item later.

**Comment by yoavst** [comment]
How do I update?

**Comment by yoavst** [comment]
Also, please add a small padding to profile view text.

**Comment by mikepenz** [comment]
@yoavst do you need more help with this?

**Comment by mikepenz** [comment]
you also wrote something about a padding at a profile view text. can you specify it a bit? probably with a screenshot?

**Comment by yoavst** [comment]
Well. After a small research I found out that the imageview for the main profile. So I used it. Using result.getProfiles().get(0).setIcon() does not work.

also add end (right) padding for the text. I'm using rtl text with non rtl layout.

**Comment by mikepenz** [comment]
i've added a new method to update a profile defined by the identifier
