### ISSUE TITLE
Removing a draw

### ISSUE THREAD

**Issue by outoftrun** [mikepenz/MaterialDrawer#840]
I am trying to create a two draw fragment, wherein one draw the right left one is constant accross all fragments the right one on the other hand is individualized for each fragment. I have created a two draw fragment that was easy, I am not yet sure yet how to replace the second fragment or exactly how to make the first one common. If you have any thoughts?

**Comment by mikepenz** [comment]
@outoftrun you want a left and right drawer? and the right drawer changes depending on the current selected fragment. 

you can just keep the reference to the right drawer and delete and re-add the items when you switch fragments

**Comment by carmas123** [comment]
Good news but if I want to remove completelly the Right Drawer?
