### ISSUE TITLE
Profiles - listen for long presses

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/MaterialDrawer#843]
I can't get this working in an easy way. I just want to listen to profile long presses and doing it in following way does not work, the long press handler is ever called... Seems like the profile click listener is comsuming all touch events...

I can use a custom `OnTouchListener` and handle the long press in there and store somewhere a temp. variable that stores if the last touch was handled by the `OnTouchListener` long press handler and ignore the click in the `OnAccountHeaderListener` or modify the `onTouch` return value of the `OnTouchListener` based on this temp. variable, but this seems not very clean.

This is how I build my header:
```java
	mAccountHeader = new AccountHeaderBuilder()
                .withActivity(this)
                .withCompactStyle(true)
                .withProfileImagesClickable(false)
                .withSelectionListEnabledForSingleProfile(false)
                .withHeaderBackground(header)
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean current) {
						// handle clicks
					})
                .addProfiles(profiles.toArray(new IProfile[profiles.size()]))
                .withSavedInstance(savedInstanceState)
                .build();
```				
And this how I create the profiles I want to handle long presses:
```java
	private ProfileDrawerItem createProfileDrawerItem(Pair<DataSource, String> source, int index)
    {
        String name = getString(source.first.getNameRes());
        String extra = source.second;

        ProfileDrawerItem item = new ProfileDrawerItem()
                .withIdentifier(ID_PROFILE_LOCAL + index + 1)
                .withName(name)
                .withNameShown(true)
                .withIcon(source.first.getIconRes());
        if (extra != null)
            item.withEmail(extra);

        item.withPostOnBindViewListener(new OnPostBindViewListener() {
            @Override
            public void onBindView(final IDrawerItem drawerItem, View view) {

                L.d(this, "onBind: " + drawerItem.getIdentifier());

                view.setLongClickable(true);
                view.setOnLongClickListener(new View.OnLongClickListener() {
                    @Override
                    public boolean onLongClick(View view) {

                       // handle long press
                        return true;
                    }
                });
            }
        });

        return item;
    }
```
Is there a clean way to do what I want? Why doesn't the `OnLongClickListener` work?

**Comment by MFlisar** [comment]
**Working solution - WORKAROUND**

This solution works but needs two temp. local variables... The solution probably explains the problem a little better

	mAccountHeader = new AccountHeaderBuilder()
		.withActivity(this)
		.withCompactStyle(true)
		.withProfileImagesClickable(false)
		.withSelectionListEnabledForSingleProfile(false)
		.withHeaderBackground(header)
		.withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
			@Override
			public boolean onProfileChanged(View view, IProfile profile, boolean current) {
				L.d(MainActivity.class, "Profile: " + profile.getName() + " | " + profile.getEmail() + " | " + current);

				// if it was a long press, restore previous selection and ignore click event
				if (mAccountClickIsLongPress)
				{
					mAccountClickIsLongPress = false;
					mAccountHeader.setActiveProfile(mSelectionBeforeLongPress);
					return true;

				}
				
				// handle header click...
				
				return true;
			}
		})
		.addProfiles(profiles.toArray(new IProfile[profiles.size()]))
		.withSavedInstance(savedInstanceState)
		.build();
		
And my create profile function:

    private ProfileDrawerItem createProfileDrawerItem(Pair<DataSource, String> source, int index)
    {
        String name = getString(source.first.getNameRes());
        String extra = source.second;

        ProfileDrawerItem item = new ProfileDrawerItem()
                .withIdentifier(ID_PROFILE_LOCAL + index + 1)
                .withName(name)
                .withNameShown(true)
                .withIcon(source.first.getIconRes());
        if (extra != null)
            item.withEmail(extra);

        item.withPostOnBindViewListener(new OnPostBindViewListener() {
            @Override
            public void onBindView(final IDrawerItem drawerItem, View view) {

                L.d(this, "onBind: " + drawerItem.getIdentifier());

                final GestureDetectorCompat mDetector = new GestureDetectorCompat(getApplicationContext(), new GestureDetector.SimpleOnGestureListener() {

                    @Override
                    public void onLongPress(MotionEvent e) {
                        mSelectionBeforeLongPress = mAccountHeader.getActiveProfile().getIdentifier();
                        mAccountClickIsLongPress = true;
                        Toast.makeText(getThis(), "LONG PRESS", Toast.LENGTH_SHORT).show();
                    }
                });
                view.setOnTouchListener(new View.OnTouchListener() {
                    @Override
                    public boolean onTouch(View v, MotionEvent event) {
                        return mDetector.onTouchEvent(event);
                    }
                });

            }
        });

        return item;
    }

I think, there's probably a better way to do it?

**Comment by mikepenz** [comment]
@MFlisar there was no better way to do this. but with v4.5.2 there will be a new listener you can define:

```java
                .withOnAccountHeaderItemLongClickListener(new AccountHeader.OnAccountHeaderItemLongClickListener() {
                    @Override
                    public boolean onProfileLongClick(View view, IProfile profile, boolean current) {
                        Toast.makeText(DrawerActivity.this, "Hugo" + profile.getName().getText(DrawerActivity.this), Toast.LENGTH_SHORT).show();
                        return false;
                    }
                })
```

**Comment by MFlisar** [comment]
Perfect. Library is constantly improved, sometimes I forget to upgrade before posting and recheck for new features.

This works without side effects, my solution had some side effects...

**Comment by mikepenz** [comment]
@MFlisar no no :D the feature was added for you as it made sense ;).

**Comment by MFlisar** [comment]
Even better :-). The fast improvement is probably a austrian bonus, as I'm from there as well ;-)

**Comment by mikepenz** [comment]
Austrian quality :D

**Comment by MFlisar** [comment]
:-)
