### ISSUE TITLE
big margin between profile image and name

### ISSUE THREAD

**Issue by LiuDeng** [mikepenz/MaterialDrawer#849]
* * improve header height calculation and make it more bullet proof for some emulators and some rare devices were the selected profile image was overlaping the selection text
FIX #836

the commit make the margin between profile image and name quit bigger than before and look not good

**Comment by LiuDeng** [comment]
the android version is 4.2.2

**Comment by mikepenz** [comment]
@LiuDeng can you please provide a screenshot + device + library version?

**Comment by LiuDeng** [comment]
@mikepenz  I have problem upload image to github and i you can see it herer http://note.youdao.com/share/web/file.html?id=04a99adce17724b9979bbe93e13dd2f9&type=note

**Comment by mikepenz** [comment]
@LiuDeng thanks will check later today. tried it on my machine with genymotion yesterday but there it worked

**Comment by mikepenz** [comment]
@LiuDeng you were right. this only happend on this device because 4px were missing :D i now added a buffer (i remove 8dp from the minimal height calculation) to prefer smaller headers instead of to many space. will be in the next version
