### ISSUE TITLE
result.setSelection(selectedItem, false);

### ISSUE THREAD

**Issue by daveeeh** [mikepenz/MaterialDrawer#85]
Doesn't seem to work when all the items are added after Build() using AddItems()

**Comment by mikepenz** [comment]
@daveeeh please try the method without the boolean param. it's used internally for the header.

**Comment by daveeeh** [comment]
hi @mikepenz great library and  thanks for the message but still nothing.  I'm sure it worked before I moved all the items to after the Build()... But can't quite remember and don't want to revert everything...

I just need a couple of draweritems which don't change the currently selected item... that's common right?  Only started looking at this today, so sorry if this is silly questons....

**Comment by daveeeh** [comment]
.withCheckable(false) :-D

**Comment by mikepenz** [comment]
@daveeeh was it working with setSelection now? if not i will take a look into it tomorrow. ;)

Oh great that you found the withCheckable option ;)
