### ISSUE TITLE
Hope custom for ProfileDrawerItem or can add option to delete a account

### ISSUE THREAD

**Issue by LiuDeng** [mikepenz/MaterialDrawer#850]
@mikepenz 
Hope custom for ProfileDrawerItem or can add option to delete a account.
As in your sample it  implement the "Add Account" section while the ”Manage Account“ section do nothing.
For the users , they need easy way to delete/unbind account, and for our developes we need easy way to listen user's delete action.
Forgive my poor English~
Thank you for your great job and realy hope to add this.
Best Wishes.

**Comment by LiuDeng** [comment]
the delete button some thing like this http://note.youdao.com/share/web/file.html?id=6352513ad12ac94f28eac401b6e92076&type=note

**Comment by mikepenz** [comment]
@LiuDeng all the listeners are available. You have to implement what to do if a specific item was clicked. Removing an account from the profiles is possible

**Comment by LiuDeng** [comment]
@mikepenz i know the listener was called when click the ProfileDrawerItem  but the point is  how hot let user know when she/he click the item will make delete account action , for most time click the ProfileDrawerItem  mean change current account.
