### ISSUE TITLE
 Could not find class 'com.mikepenz.materialdrawer.view.BezelImageView$CustomOutline', referenced from method com.mikepenz.materialdrawer.view.BezelImageView.onSizeChanged

### ISSUE THREAD

**Issue by LiuDeng** [mikepenz/MaterialDrawer#851]
Could not find class 'com.mikepenz.materialdrawer.view.BezelImageView$CustomOutline', referenced from method com.mikepenz.materialdrawer.view.BezelImageView.onSizeChanged

**Comment by mikepenz** [comment]
@LiuDeng that is a normal warning. Because the Outline can only be used on API > 21
