### ISSUE TITLE
How to disable a Drawer?

### ISSUE THREAD

**Issue by LiuDeng** [mikepenz/MaterialDrawer#852]
How to disable a Drawer? so it can not be slide out

**Comment by LiuDeng** [comment]
In secondary activity i need Materialize to material set my activity but do not want to show the drawer so i need to disable the drawer.

**Comment by LiuDeng** [comment]
sorry to trouble~ i find a way to do this  mNavigationDrawer.getDrawerLayout().setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/342

**Comment by stepanov-standy** [comment]
BTW, mentioned above setting will just lock the drawer from swipe action to open it. Home (hamburger) button will still work. Looks like the only way to fully disable the drawer is to use a combination of settings:

`mNavigationDrawer.getDrawerLayout().setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);
drawerResult.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false);`
