### ISSUE TITLE
Why my drawer icons look like this (image)?

### ISSUE THREAD

**Issue by JuanAlejandro** [mikepenz/MaterialDrawer#853]
![2015-12-01-15-39-22](https://cloud.githubusercontent.com/assets/11820379/11513616/2944a47c-9842-11e5-86e0-e99a844d3cf0.jpg)

**Comment by mikepenz** [comment]
@JuanAlejandro which icons do you use?

**Comment by JuanAlejandro** [comment]
True. My bad.
