### ISSUE TITLE
Profile image will not use Picasso with local file path

### ISSUE THREAD

**Issue by bolder5** [mikepenz/MaterialDrawer#854]
Picasso allows a file path per their docs with a prefix of "file:".  The problem is the ImageHolder applyTo() checks scheme for http or https and only uses the DrawerImageLoader if it is true.  Is there a reason only http schemes are allowed?  The problem when the image gets loaded without using the Picasso transormer I have set, the top and bottom of the circle are cut off in the drawer header.

**Comment by mikepenz** [comment]
@bolder5 yeah there is, because non urls can be normal resource uris which can be used without any additional lib. i will check if i can somehow allow both.
