### ISSUE TITLE
Minidrawer doesn't work, when profile list is shown.

### ISSUE THREAD

**Issue by StNekroman** [mikepenz/MaterialDrawer#858]
**Prerequisites:**
1. Have a two primary items in sidebar.
2. Have a two related items in minidrawer.
3. Click on each of minidrawer item invokes click on sidebar item.

**Steps to reproduce:**
1. Open sidebar.
2. Open profiles list
3. Close sidebar (leave profiles list open, as is)
4. Try clicking on each minidrawer items.

**Expected result:**
1. It should still invoke original sidebar's primary items onClick handler.

**Actual result:**
1. It fires profile change event.

**Comment by StNekroman** [comment]
Currently I use the next workaround:

~~~
 .withOnDrawerListener(new Drawer.OnDrawerListener() {
                @Override
                public void onDrawerOpened(View drawerView) {
                }
                @Override
                public void onDrawerClosed(View drawerView) {
                    sidebar.resetDrawerContent();
                }
                @Override
                public void onDrawerSlide(View drawerView, float slideOffset) {
                }
            })
~~~

But this isn't a real solution of this bug.

**Comment by mikepenz** [comment]
@StNekroman i've integrated a similar solution into the `MiniDrawer` and make sure that the selection happens on the correct list
