### ISSUE TITLE
is MaterialDrawer support RTL

### ISSUE THREAD

**Issue by MBehtemam** [mikepenz/MaterialDrawer#859]
hi, first thanks for this plugin. my question is is MaterialDrawer Support RTL and can it open in right side of screen? i know the material specification says drawer must open from left but in rtl it's better open from right. so can MaterialDrawer open from right side and if yes how?
thanks.

**Comment by mikepenz** [comment]
@MBehtemam if your application is in RTL mode and you let the drawer open from the right by setting the gravity to `GravityCompat.START` it will show up from the right.

**Comment by MBehtemam** [comment]
Hi, thanks for you answer @mikepenz  i try these : 

     <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:supportsRtl="true"


also in my layout is set : 

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layoutDirection="rtl"



and for my MaterialDrawer code i use : 

        setSupportActionBar(toolbar);
        AccountHeader navigationHeader = new AccountHeaderBuilder().withActivity(this).withHeaderBackground(R.drawable.navigation_drawer_background).build();
        new DrawerBuilder().withActivity(this).withToolbar(toolbar)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("Home").withIcon(GoogleMaterial.Icon.gmd_import_contacts).withIconColor(Color.BLACK)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        Toast.makeText(MainActivity.this,position + "",Toast.LENGTH_LONG);
                        return false;
                    }
                })
                .withAccountHeader(navigationHeader)
                .withDrawerGravity(GravityCompat.START)
                .build();




but the humberger icon is placed on the right but when click on icon material drawer open from the left and with drag it's only open from the left side.
