### ISSUE TITLE
in device with android version 21 i have set them to 

### ISSUE THREAD

**Issue by abuzuhri** [mikepenz/MaterialDrawer#86]
in device with android version 21 i have set them parent to MaterialDrawerTheme.Light.DarkToolbar , i have space under status bar .
between status bar and toolbar , space with same color .

please see image 
https://www.dropbox.com/s/o5d6zctqgax7tmv/Screenshot_2015-03-11-02-15-52.png?dl=0

**Comment by fdorssers** [comment]
There are two ways to solve that:

1. Use the `.TranslucentStatus` version of the style: `MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus`
2. Remove the the padding on the Toolbar (RelativeLayout) ViewGroup in your Activity, because I assume you've copied that from the sample app:
```XML
<RelativeLayout
    android:id="@+id/toolbar_container"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:background="?attr/colorPrimary"
    android:paddingTop="@dimen/tool_bar_top_padding"
    android:elevation="4dp">
    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        style="@style/ToolBarStyle"
        android:transitionName="actionBar"/>
</RelativeLayout>
```
The first one would be the best choice if you want the drawer visible behind the status bar.

**Comment by abuzuhri** [comment]
when i Use the .TranslucentStatus version of the style: MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus , i only get one color for both status bar and toolbar , how i can fix this problem ?

**Comment by mikepenz** [comment]
@abuzuhri with the translucentStatus it should show the statusbar with a bit darker color than the toolbar.  can you post a screenshot please?

**Comment by abuzuhri** [comment]
please see my app 
https://www.dropbox.com/s/9sb363yidwzertn/Screenshot_2015-03-11-13-40-28.png?dl=0
and your app 
https://www.dropbox.com/s/u1nom48rmu52tf0/Screenshot_2015-03-11-13-40-42.png?dl=0

i have Samsung note 4

the other app have dark status bar normal only my app and your app not have

**Comment by mikepenz** [comment]
@abuzuhri oh i see. really interesting. on a Nexus 5 with default Android it shows correctly :D So samsung did something different there too ^^. I'll see how i can improve this with the style.

**Comment by abuzuhri** [comment]
Ok , I wait you reply , because i use second solution (2- Remove the the padding on the Toolbar) it's work now , but but i got  another problem   .withTranslucentStatusBar(true) is not working .

**Comment by mikepenz** [comment]
@abuzuhri .withTranslucentStatusBar(true) will only work if you use it in addition of a theme supporting a translucent statusbar.

**Comment by abuzuhri** [comment]
ok wait your solution for the first part , TranslucentStatus

**Comment by mikepenz** [comment]
@abuzuhri can't really reproduce it on any of my phones (Nexus 7, Nexus 5, Nexus 6). So it seems it is a samsung bug. 

You should be able to change this by doing the following:

```xml
<RelativeLayout
        android:id="@+id/toolbar_container"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="?attr/colorPrimaryDark"
        android:paddingTop="@dimen/tool_bar_top_padding">
        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            android:elevation="4dp"
            android:transitionName="actionBar"/>
    </RelativeLayout>
```

See the colorPrimaryDark as background of the `RelativeLayout`
