### ISSUE TITLE
How to assign 2 different drawer to 2 different profile

### ISSUE THREAD

**Issue by deepakSP** [mikepenz/MaterialDrawer#860]
How to assign 2 different drawers to 2 different profile ?? .. I tried to search here n google but couldn't find any example.

and thank you for the awesome library

**Comment by mikepenz** [comment]
@deepakSP could you please describe your problem a bit better? I'm not quite sure what you want to achieve

**Comment by deepakSP** [comment]
@mikepenz 
I want to drawer one for popular categories
and 2nd for other categories

the first drawer will be visible to a user and they can open second drawer by tapping on 2nd profile

I hope u get it.. sry for my bad english

**Comment by deepakSP** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/11506967/11621656/61b2782e-9ce4-11e5-8d4c-f165bda4dedf.png)

something like then when max profile is open he will see different drawer items when ur is open u will see different

**Comment by mikepenz** [comment]
@deepakSP just update the drawer and set a new list of items?

**Comment by deepakSP** [comment]
I thought of that, but I thought there will be a feature where we can attach drawer to profile .

**Comment by mikepenz** [comment]
@deepakSP still not quite sure what you mean with attach drawer to profile. the list of drawerItems is independent of the list of accounts. they are two different sources of information

**Comment by deepakSP** [comment]
I mean drawer items to profile like in my case

Popular Categories ( Profile ) - > drawer item -> Love, Nature,Vector
Other Categories ( 2 nd Profile) -> drawer item -> Holidays, flowers, etc

Like ur wallsplash app has two profile "Unsplash" n "Jay Mantri"

Nevertheless I got it ..when u said " two different sources of information"

**Comment by mikepenz** [comment]
@deepakSP within wallsplash i do the same. depending on the profile someone selects i update the drawerItem list. 

You can set a list of new items with this method:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L713
