### ISSUE TITLE
Can't change status bar color in other activities?

### ISSUE THREAD

**Issue by drinfernoo** [mikepenz/MaterialDrawer#863]
It seems that if I'm using the one of the TranslucentStatus themes (specifically MaterialDrawerTheme.Light.TranslucentStatus), then other activities that I start in my app can't set the status bar color.

Here's my code:
```Java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
    Window window = getWindow();
    window.setStatusBarColor(p.getRgb());
}
```

and my style:
```XML
<style name="DrawerTheme" parent="MaterialDrawerTheme.Light.TranslucentStatus">
    <item name="android:windowDrawsSystemBarBackgrounds">true</item>
    <item name="android:windowContentTransitions">true</item>
</style>
```
Am I just missing something?

**Comment by mikepenz** [comment]
@drinfernoo the statusBar is managed by the drawer. you should use:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L160

**Comment by drinfernoo** [comment]
This is in an activity that doesn't have a Drawer, however.

**Comment by mikepenz** [comment]
@drinfernoo for activities without the drawer you can use a theme which does not make the statusbar translucent

```xml
MaterialDrawerTheme.Light
```

**Comment by drinfernoo** [comment]
Of course, thank you! That was a test ;)

**Comment by mikepenz** [comment]
haha :trophy:
