### ISSUE TITLE
collaspsable drawer item duplicating

### ISSUE THREAD

**Issue by sanalelevenstar11** [mikepenz/MaterialDrawer#864]
I am try to implement two collapsible drawer item. when i click those drawer items are keep duplicating .

**Comment by mikepenz** [comment]
@sanalelevenstar11 can you please provide some code? 

the sample application showcases some collapsing funcionality:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L184

**Comment by sanalelevenstar11** [comment]
.withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        //check if the drawerItem is set.
                        //there are different reasons for the drawerItem to be null
                        //--> click on the header
                        //--> click on the footer
                        //those items don't contain a drawerItem

                        if (drawerItem != null) {
                            Intent intent = null;
                            if (drawerItem.getIdentifier() == 1) {
                                if (opened) {
                                    //remove the items which are hidden
                                    result.removeItems(100, 101, 102, 103);

                                } else {

                                    int curPos = result.getPosition(drawerItem);

                                    result.addItemsAtPosition(
                                            curPos,
                                            new SecondaryDrawerItem().withName("Tara").withLevel(2).withIcon(R.mipmap.email).withIdentifier(100),
                                            new SecondaryDrawerItem().withName("Tamanna").withLevel(2).withIcon(R.mipmap.heart).withIdentifier(101),
                                            new SecondaryDrawerItem().withName("Tanvi").withLevel(2).withIcon(R.mipmap.email).withIdentifier(102),
                                            new SecondaryDrawerItem().withName("Aabhushan").withLevel(2).withIcon(R.mipmap.heart).withIdentifier(103)


                                    );
                                }
                                opened = !opened;


                                return false;
                            }else if (drawerItem.getIdentifier()==100){

                                intent = new Intent(MainActivity.this, Sanal.class);

                            }
                            if (drawerItem.getIdentifier() == 2) {
                                //showcase a simple collapsable functionality
                                if (opened) {
                                    //remove the items which are hidden
                                    result.removeItems(2000, 2001);
                                } else {
                                    int curPos1 = result.getPosition(drawerItem);
                                    result.addItemsAtPosition(
                                            curPos1,
                                            new SecondaryDrawerItem().withName("CollapsableItem").withLevel(2).withIcon(R.mipmap.email).withIdentifier(2000),
                                            new SecondaryDrawerItem().withName("CollapsableItem 2").withLevel(2).withIcon(R.mipmap.heart).withIdentifier(2001)


                                    );
                                }
                                opened = !opened;

                                return true;

**Comment by mikepenz** [comment]
@sanalelevenstar11 you should have different variables to remember the opened state :D

**Comment by sanalelevenstar11** [comment]
oh my bad I am totally new android ..can you please provide little bit more detail if possible..

**Comment by mikepenz** [comment]
@sanalelevenstar11 sorry i can't provide programming tips ;). Just one more hint. 
At the moment you use the same variable `opened` for all your collapseable items. so if one item is opened it changes this variable for all the other collapsable items too. you need a separate variable for each so the state is remembered independent of the other ;)

**Comment by sanalelevenstar11** [comment]
ok thannks ..now i got
