### ISSUE TITLE
Hello, I have custom view in .addHeader, and after I change some strings in this view, drawer don't updates

### ISSUE THREAD

**Issue by sough** [mikepenz/MaterialDrawer#865]
((TextView) drawerResult.getHeader().findViewById(R.id.string)).setText("test");

How to notify drawer about my changes?

**Comment by mikepenz** [comment]
@sough the easiest solution would be to re-set the header with 
```java
drawer.setHeader()
```

or you get the adapter from the drawer and notify that the first item was modified.

**Comment by sough** [comment]
I tried drawerResult.getAdapter().notifyItemChanged(0); and its not helped

**Comment by mikepenz** [comment]
@sough strange. and you are sure updating the text works? because when you got the reference to the view already. perhaps you could try to `invalidate()` the view?

**Comment by sough** [comment]
my bad, everything works!
