### ISSUE TITLE
withSliderBackgroundDrawableRes

### ISSUE THREAD

**Issue by RJFares** [mikepenz/MaterialDrawer#867]
Hi,
Great library man.
One thing bugging me though is the withSliderBackgroundDrawableRes(Drawable d)
I tried setting all kinds of photo sizes and extensions jpeg png and gif.
The result is a transparent slider (no photo showing).
Any ideas?
Thanks

**Comment by mikepenz** [comment]
Hi. 

Thanks.

What do you want to achieve? Or what is the desired result?

Best,
Mike

**Comment by RJFares** [comment]
I want to use an image as a background for the drawer. I used the mentioned method with a drawable I have to apply it, but the result is just a transparent drawer. 

withSliderBackgroundColor() works for colors, but withSliderBackgroundDrawableRes() for drawables doesn't.... or am I missing something

**Comment by mikepenz** [comment]
`withSliderBackgroundDrawableRes` takes a resource :D no `drawable`

you solved your issue?

**Comment by RJFares** [comment]
yes, i replaced .withSliderBackgroundDrawableRes(R.drawable.slider_bg)
with 				.withSliderBackgroundDrawable(ContextCompat.getDrawable(getApplicationContext(),R.drawable.slider_bg))
tx
