### ISSUE TITLE
Add a getItemForTag() for Drawer object

### ISSUE THREAD

**Issue by PsyGik** [mikepenz/MaterialDrawer#868]
We have `IDrawerItem<T> getTag();` currently.
Is it possible to have something like `getItemForTag()` to fetch a single drawer item directly using Tag?

Right now I'm writing code to iterate and get the required item

```java
     public <T> IDrawerItem getItemForTag(Class<T> tagClass,T tag) {
        for (IDrawerItem item : result.getDrawerItems())
            if (item.getTag() != null && item.getTag().getClass().isAssignableFrom(tagClass))
                if (item.getTag().equals(tag))
                    return item;
        return null;
    }
```
And use it like so
```java
    getItemForTag(MyClass.class,objOfMyClass);
```

**Comment by mikepenz** [comment]
@PsyGik what do you need the `tagClass` for? wouldn't it be enough if the `Tag` equals the `item.getTag()`?

**Comment by PsyGik** [comment]
@mikepenz Yes, I think that'd be sufficient.

**Comment by mikepenz** [comment]
then it's in v4.5.7

https://github.com/mikepenz/MaterialDrawer/commit/113b922a8efb31ed5f63459e990a98e3ea770a95

**Comment by PsyGik** [comment]
@mikepenz Thank you!
