### ISSUE TITLE
Icon not shown in ActionBar

### ISSUE THREAD

**Issue by cryo75** [mikepenz/MaterialDrawer#869]
I'm creating the drawer as follows:

        drawer = new DrawerBuilder()
                .withActivity(this)
                .withActionBarDrawerToggle(false)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.label_menu_settings),
                        new DividerDrawerItem(),
                        new SecondaryDrawerItem().withName(R.string.label_menu_about)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        //TODO
                        return false;
                    }
                })
                .withSelectedItem(-1)
                .build();

My activity extends Activity and I'm using the 'Theme.Holo.Light.DarkActionBar' theme. I have a menu that's being inflated but not toolbar attached to the activity. My min API is 16.

I would like to show the hamburger icon but it's not shown with the above code. 

When I added the following lines:

        getActionBar().setDisplayHomeAsUpEnabled(false);
        drawer.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);

The app crashes. getActionBarDrawerToggle() returns null.

So what is the correct way to show the icon?

**Comment by mikepenz** [comment]
@cryo75 if you have an `ActionBar` you can't use the `ActionBarDrawerToggle` from the `Drawer` you have to manage the Hamburger icon manually as you would with a normal `DrawerLayout`

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/ActionBarActivity.java#L50
