### ISSUE TITLE
Exception : The font for the given icon isn't registered 

### ISSUE THREAD

**Issue by patelakshay13890** [mikepenz/MaterialDrawer#87]
I got Exception on running sample 
" java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mikepenz.materialdrawer.app/com.mikepenz.materialdrawer.app.SimpleHeaderDrawerActivity}: java.lang.RuntimeException: The font for the given icon isn't registered! "

**Comment by mikepenz** [comment]
@patelakshay13890 running the application without any modifications?

**Comment by patelakshay13890** [comment]
yes..
So what is the Solution ??

**Comment by mikepenz** [comment]
@patelakshay13890 you've checked out the latest source, running it without modifications on which phone? 

I just did a clean checkout of the master (just in case i had any local differences) and started it within an emulator. no issues here.

**Comment by mikepenz** [comment]
@patelakshay13890  Have tried it on some additional pc's everywhere working. I have no clue why it shouldn't work for you. 


Please try to check everything out again, and try to run it without any modifications.
