### ISSUE TITLE
Remove current drawer and add another one

### ISSUE THREAD

**Issue by MohMah** [mikepenz/MaterialDrawer#873]
Hi, How can I remove the current drawer that is attached to the activity and add another one?
thanks.

**Comment by mikepenz** [comment]
@MohMah you should not remove a drawer. If it is deactivated for the current activity you can LOCK it. Else use the methods to update the drawers content.s

**Comment by MohMah** [comment]
sorry but i can't update the account header, can you please tell me how that can be done?

**Comment by mikepenz** [comment]
@MohMah what do you want to change?

After you created the `AccountHeader` you have the `AccountHeader` object which allows you to add / remove / modify profiles

**Comment by MohMah** [comment]
okay I got it now, I had a guest account and i wanted to update it after login, so now all i have to do is to remove the guest account and add the logged-in one, right?

**Comment by mikepenz** [comment]
@MohMah yes you can do this. Or you update the existing one. depending what fits your needs.
