### ISSUE TITLE
Remove AccountHeader

### ISSUE THREAD

**Issue by bingjiang** [mikepenz/MaterialDrawer#874]
How do I add/remove an AccountHeader by modifying the Drawer? I tried AccountHeader.clear(), removeProfile(), the empty header still stays there

**Comment by mikepenz** [comment]
@bingjiang you have to remove the header from the `Drawer` https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L317
