### ISSUE TITLE
Please add those apps to the showcase using MaterialDrawer

### ISSUE THREAD

**Issue by Florent1510** [mikepenz/MaterialDrawer#875]
Hey!

I absolutely love this library, it has helped me out from a few issues I had with my apps. The following of mine use MaterialDrawer, I'd be proud to see them showed on the using apps part:

https://play.google.com/store/apps/details?id=com.fa.touch
https://play.google.com/store/apps/details?id=com.fa.ve
https://play.google.com/store/apps/details?id=com.fa.sonatic.client
https://play.google.com/store/apps/details?id=com.fa.photos.app

Greetings!
Florent Anders

**Comment by mikepenz** [comment]
@Florent1510 thanks for the links. 

Please open a pull request and add it at the end of the list ;)

Best,
Mike
