### ISSUE TITLE
Please help me.  How do I change design of selected item like at the picture? In advance thank you.

### ISSUE THREAD

**Issue by dmelechow** [mikepenz/MaterialDrawer#876]
![secteditem](https://cloud.githubusercontent.com/assets/11187627/11766903/ea9cf76a-a1c4-11e5-9e55-ea0c29c1b978.jpg)

**Comment by mikepenz** [comment]
@dmelechow you will have to implement a `CustomDrawerItem` which allows you to set a `StateListDrawable` as background. This will have the default state without the yellow line, and a selected state with a drawable which contains that yellow line. 

Here's the line of code which sets a color for the normal `PrimaryDrawerItem`
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BasePrimaryDrawerItem.java#L82

**Comment by dmelechow** [comment]
Thanks for the answer and sorry me for my obtusity, but i don't understand how realize it in my code(  
Drawer result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withTranslucentStatusBar(true)
                .withActionBarDrawerToggle(true)
                .withAccountHeader(headerResult)
                .withSliderBackgroundColor(getResources().getColor(R.color.md_grey_900))
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.menu_item_chat).withIdentifier(1)
      )
.build();

**Comment by mikepenz** [comment]
There are Custom draweritems in the sample app:
https://github.com/mikepenz/MaterialDrawer/tree/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems

And there are also answers on stackoverflow regarding custom drawer items:
http://stackoverflow.com/questions/32066618/materialdrawer-customdraweritem
http://stackoverflow.com/questions/31030595/how-to-customize-the-draweritem-using-the-lib-mikepenz-materialdrawer/32542999#32542999
