### ISSUE TITLE
onclick for sticky footer items

### ISSUE THREAD

**Issue by 7ShaYaN7** [mikepenz/MaterialDrawer#878]
Tnx, for this great Library.

Is there onclick method for sticky footer items? I couldn't find any snippet code in the sample.

How to implement that?

**Comment by mikepenz** [comment]
@7ShaYaN7 the `StickyFooterItems` will also trigger the normal `onDrawerItemClick` listener. It is exactly the same, but it won't send a position with the request.

**Comment by 7ShaYaN7** [comment]
thumbs up, nice answer, I gotta go to handle with modifiers!

my problem with the positions.

**Comment by mikepenz** [comment]
@7ShaYaN7 you should always use the `identifiers` to identify specific `DrawerItem`s as it is also used to update them ;).

**Comment by 7ShaYaN7** [comment]
a typo! ;)
