### ISSUE TITLE
Programmatically change drawer selected text color

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/MaterialDrawer#881]
Can I somehow do that? I want to use custom theming in my whole app and therefore I need to override this value with my custom primary color...

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDrawerItem.java#L123

**Comment by MFlisar** [comment]
Thanks. I was looking for that in the `DrawerBuilder`...

**Comment by mikepenz** [comment]
@MFlisar no problem ;)

Small description:
the `DrawerBuilder` just knows about the `IDrawerItem` interface which defines a basic drawerItem. So the `DrawerBuilder` does not know about the different features of the drawerItems. Everything is really really flexible and can be easily extended for custom requirements ;)
