### ISSUE TITLE
Can not load url into HeaderBackground

### ISSUE THREAD

**Issue by viettanbkdn** [mikepenz/MaterialDrawer#882]
I create AccountHeader like this:
```java
AccountHeader accountHeader = new AccountHeaderBuilder()
                .withActivity(this)
                .addProfiles(profile)
                .build();
```
and load image from url using picasso:
```java
Picasso
                .with(this)
                .load("http://s.hswstatic.com/gif/landscape-photography-1.jpg")
                .into(accountHeader.getHeaderBackgroundView());
```
but it does not show image.

And I also create custom DrawerImageLoader in Application, but it still does not display image on avatar:
```java
DrawerImageLoader.init(new AbstractDrawerImageLoader() {
            @Override
            public void set(ImageView imageView, Uri uri, Drawable placeholder) {
                Picasso.with(imageView.getContext()).load(uri).placeholder(placeholder).into(imageView);
            }
            @Override
            public void cancel(ImageView imageView) {
                Picasso.with(imageView.getContext()).cancelRequest(imageView);
            }
        });

IProfile profile = new ProfileDrawerItem()
                .withName("testName")
                .withEmail("testMail@gmail.com")
                .withIcon("http://s.hswstatic.com/gif/landscape-photography-1.jpg");
```
I don't know why. And i still have some question:
- can i hidden 3 small user avatars, i want to switch account using switcher only to show list account.
(can do it now by using:    
```java
        accountHeader
                .getView()
                .findViewById(R.id.material_drawer_account_header_small_first)
                .setVisibility(View.GONE);
```
)
- can i show avatar on account header different with avatar on list account (and text also).
( can change text using:
```java
(TextView) accountHeader.getView().findViewById(R.id.material_drawer_account_header_name);
```
)
- can i show name and email on list accounts?, currently it shows only email

**Comment by mikepenz** [comment]
@viettanbkdn your application has internet permission?

* hide smal avatars:
There is a property to just show the primary account
```java
withOnlyMainProfileImageVisible()
```
* show other image in header:
No this is not possible

* also show name in account list 
```java
.withNameShown(true) //on the profile
```
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L92

**Comment by viettanbkdn** [comment]
Thanks so much, and i can show other image in header by using this:
```java
BezelImageView defaultImage = (BezelImageView) mAccountHeader.getView().findViewById(R.id.material_drawer_account_header_current);
```
But when i create PrimaryDrawerItem with .withSelectable(false), it still set selected when i click ProfileDrawerItem or click switcher.

**Comment by mikepenz** [comment]
@viettanbkdn `.withSelectable(false)` just makes the `RecyclerView` to not show the `selected` background. it will still fire the event.

**Comment by viettanbkdn** [comment]
@mikepenz RecyclerView still show the selected background. and always show the first item as selected.

And can i make some docs for your lib, it can help someone like me when we start using your lib

**Comment by mikepenz** [comment]
@viettanbkdn by default it selects the first item. you can remove the default selection via: https://github.com/mikepenz/MaterialDrawer#how-can-i-create-a-drawer-without-a-default-selection

Yes you can. There is already javaDocs inside the lib. Do you want to extend the README?

**Comment by viettanbkdn** [comment]
@mikepenz i can help to build the wiki page, like another lib do

**Comment by mikepenz** [comment]
@viettanbkdn i always add everything to the sample app, or answer questions inside the issues section here @github and mark them as **good to know**

**Comment by viettanbkdn** [comment]
@mikepenz Yes, thank you very much, i love your lib

**Comment by mikepenz** [comment]
Thanks
