### ISSUE TITLE
select color settings from Event

### ISSUE THREAD

**Issue by DemonStars** [mikepenz/MaterialDrawer#883]
Hello, Mike! Can u help me with my problem? 
In my project I receive color settings via EventBus, and after I must to change my Drawer. 
I mean, that I don't know which colors come, and when, but if it will happens - I will must to change colors on Drawer - <b>SliderBackground color, TextItemColor, SelectedItemsBackgroundColor. </b>
And I cannot use Builder, because the Drawer already defined and shows in the Activity.

For first attribute I found next way:
> Define Drawer as attribute:
<code>Drawer drawer; </code>
> Create it in Activity:
<code>drawer = new DrawerBuilder().withActivity(this).withToolbar(toolbar).build();</code>
> in Event method: 
<code>drawer.getSlider().setBackgroundColor(Color.parseColor(API.getStringBackgroundColor());</code>

What should I do in other cases?

**Comment by mikepenz** [comment]
@DemonStars just create a method which adds the `DrawerItems` to the drawer. On color update you just update all the added drawerItems with the new color.

**Comment by DemonStars** [comment]
thank you very much, Mike!
