### ISSUE TITLE
drawer with expandable listItem!

### ISSUE THREAD

**Issue by TheLoyalCruel** [mikepenz/MaterialDrawer#884]
hi
is there anyway to have expandable listitem in navigation drawer!?
Thank You in Advance...

**Comment by mikepenz** [comment]
@TheLoyalCruel yes you can do this by adding / removing items when on click. I implemented such a thing inside the sample acitvity. 
Inside the `onDrawerItemClickListener` do the following:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L184

-----------------------
Inside the listener do the following for the item which should expand / hide items.
```java
(opened) {
    //remove the items which are hidden
    result.removeItems(2000, 2001);
} else {
    int curPos = result.getPosition(drawerItem);
    result.addItemsAtPosition(
            curPos,
            new SecondaryDrawerItem().withName("CollapsableItem").withLevel(2).withIcon(GoogleMaterial.Icon.gmd_8tracks).withIdentifier(2000),
            new SecondaryDrawerItem().withName("CollapsableItem 2").withLevel(2).withIcon(GoogleMaterial.Icon.gmd_8tracks).withIdentifier(2001)
    );
}
opened = !opened;
```

**Comment by TheLoyalCruel** [comment]
thanks mike :)
