### ISSUE TITLE
how to add items that come from database and stored in List

### ISSUE THREAD

**Issue by MBehtemam** [mikepenz/MaterialDrawer#886]
Hi i ask this question on [StackOverflow](http://stackoverflow.com/questions/34379282/set-drawer-items-from-array-list-and-clicks-in-materialdrawer) and i don't know how to add items to drawer from my List.

in my android application i'm using greeDAO ORM for sqlite. so i retrive my category list : 

     List<ArticleCategory> categories = articleCategoryDao.queryBuilder().list(); 

each `ArcticleCategory` object has name and description property so i can use these for name and description of drawer items.my question is how to add this list to `myDrawer` items and how to manage their click's event. and this is my drawer codes : 

        Drawer myDrawer = new DrawerBuilder().withActivity(this).withToolbar(toolbar)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("Home").withIcon(GoogleMaterial.Icon.gmd_import_contacts).withIconColor(Color.BLACK)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        
                        return false;
                    }
                })
                .withAccountHeader(navigationHeader)
                .withDrawerGravity(GravityCompat.START)
                .build();

please keep in my mind i have some static items that i manually and items to drawer and some dynamic that come from database so click event is very important for me in this scenario.

**Comment by mikepenz** [comment]
@MBehtemam 

You have to create `DrawerItem`s for your Categories. Probably iterate over those items and create your DrawerItems. after that you add those items to the drawer. 

The onClick depends. If you have an id for your items you should use this one and set it as identifier. If not you can set the object as tag on your drawerItem and get that tag in the onClick. 
If you only need the name of such an object you can just get the name inside the onClick and do whatever you need. 

So in the onClick you react on the static items, and if it is none of those you can do the logic for the dynamic items.
