### ISSUE TITLE
Is it possible to change drawer item icon when clicked

### ISSUE THREAD

**Issue by akapuscinski** [mikepenz/MaterialDrawer#888]
Firstly, thanks Mike for great lib, I'm wondering is there a way to change SecondaryDrawerItem icon when clicking on it, I'm trying to implement something like section with "Quick Settings" and I'm using checkboxes tick as an icon and need to switch it on/off (switch it's icon). I don't want to use **withSelectedIcon()** method because I don't want this settings to be selectable (only fragments or activities are selectable in my app) only clickable.

Thanks for help in advance!

**Comment by mikepenz** [comment]
@akapuscinski i see multiple solutions here. 

1.) when you click on the drawerItem you update it and change it's icon
2.) you use a SwitchDrawerItem
3.) you implement a CustomDrawerItem which allows you to do this

**Comment by akapuscinski** [comment]
Thanks for quick answer mike, however what do you mean by updating it, calling again withIcon() method is not working

**Comment by mikepenz** [comment]
@akapuscinski you have to get the `DrawerItem` (or remember it somewhere). then you set the icon. And then you notify the drawer about the updated item (as you do on normal adapter elements):
https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

**Comment by akapuscinski** [comment]
It's in a readme file, sorry my bad :) and thanks for help!

**Comment by mikepenz** [comment]
@akapuscinski no problem ;). You are welcome
