### ISSUE TITLE
problem with header

### ISSUE THREAD

**Issue by ProgrammerBassam** [mikepenz/MaterialDrawer#892]
I'm sorry for my bad English but I will try to be my problem clear to you 
![device-2015-12-25-081801](https://cloud.githubusercontent.com/assets/7253737/12000113/94f58b36-aae0-11e5-839b-ad331043e38e.png)
after I opened the layout as above then close the drawer to choose any section from as below nothing happened!!!
![device-2015-12-25-081747](https://cloud.githubusercontent.com/assets/7253737/12000128/006ac78c-aae1-11e5-8f72-4e2f656e4fd2.png)

**Comment by mikepenz** [comment]
have you took a close look at the sample application, how to implement this? 
Seems like your activity is **fullscreen** even if iwth the current setup your drawer isn't

without any code i can't tell much. 

but check the sample:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java

and also make sure you are on the latest version v4.6.1

**Comment by ProgrammerBassam** [comment]
```
private void setupDrawer(Bundle savedInstanceState)
    {
        String name = sessionManagment.getKeyUserName();
        String email = sessionManagment.getKeyUserEmail();
        String imagePath = sessionManagment.getKeyUserProfileIamge();

        AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.header)
                .addProfiles(
                        new ProfileDrawerItem().withName(name).withEmail(email).withIcon(Uri.fromFile(new File(imagePath))),
                        new ProfileSettingDrawerItem().withName(getString(R.string.account_manager_string)).withIcon(GoogleMaterial.Icon.gmd_settings).withIdentifier(PROFILE_SETTING),
                        new ProfileSettingDrawerItem().withName(getString(R.string.account_logout_string)).withIcon(FontAwesome.Icon.faw_sign_out).withIdentifier(PROFILE_LOGOUT)
                )
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                        if (profile instanceof IDrawerItem && ((IDrawerItem) profile).getIdentifier() == PROFILE_SETTING) {
                            achieve(8, getString(R.string.account_manager_string), 0);
                        }
                        else if (profile instanceof IDrawerItem && ((IDrawerItem) profile).getIdentifier() == PROFILE_LOGOUT)
                        {
                            sessionManagment.setKeyUserId(0);
                            Intent mIntent = new Intent(MainActivity.this, LoginActivity.class);
                            startActivity(mIntent);
                            finish();
                        }

                        return false;
                    }
                })
                .build();

        DrawerBuilder builder = new DrawerBuilder()
                .withActivity(this)
                .withAccountHeader(headerResult)
                .withToolbar(toolbar)
                .withStickyFooter(R.layout.footer)
                .withTranslucentStatusBar(true)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.drawer_item_my_goals).withIcon(GoogleMaterial.Icon.gmd_tv).withIdentifier(1),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_categories).withIcon(GoogleMaterial.Icon.gmd_group).withIdentifier(2),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_notifications_of_today).withIcon(FontAwesome.Icon.faw_bell).withIdentifier(3),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_archive).withIcon(FontAwesome.Icon.faw_archive).withIdentifier(4),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_chart).withIcon(FontAwesome.Icon.faw_bar_chart).withIdentifier(5),
                        new SectionDrawerItem().withName(R.string.drawer__item_other_section),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_settings).withIcon(FontAwesome.Icon.faw_cog).withIdentifier(7).withSelectable(true),
                        new PrimaryDrawerItem().withName(R.string.drawer_item_about_us).withIcon(FontAwesome.Icon.faw_question).withIdentifier(8).withSelectable(true)

                ) // add the items we want to use with our Drawer
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        if (drawerItem != null && drawerItem instanceof Nameable) {
                            String name = ((Nameable) drawerItem).getName().getText(MainActivity.this);
                            achieve(position, name, 0);
                        }


                        return miniResult.onItemClick(drawerItem);
                    }
                })
                .withSavedInstance(savedInstanceState);

        // Embed only if orientation is Landscape (regular drawer in Portrait)
        result = builder.buildView();
        miniResult = new MiniDrawer().withDrawer(result).withInnerShadow(true);

        int first = (int) UIUtils.convertDpToPixel(300, this);
        int second = (int) UIUtils.convertDpToPixel(72, this);

        crossFader = new Crossfader()
                .withContent(findViewById(R.id.fragment_container))
                .withFirst(result.getSlider(), first)
                .withSecond(miniResult.build(this), second)
                .withSavedInstance(savedInstanceState)
                .build();

        miniResult.withCrossFader(new CrossfadeWrapper(crossFader));

        achieve(1, getString(R.string.drawer_item_my_goals), 0);

        setNotifications();
    }

setupdrawer function

```
public void achieve(int position , String name, int id)
    {
        Fragment fragment = null;
        boolean isFragment = false;


        switch (position) {
            case 1:
                isFragment = true;
                isHome = true;
                getSupportActionBar().setTitle(name);
                fragment = HomeFragment.newInstance(name);
                break;

            case 2:
                isFragment = true;
                isHome = false;
                getSupportActionBar().setTitle(name);
                nsame = name;
                fragment = CategoriesFragment.newInstance(name);
                break;

            case 3:
                isFragment = true;
                isHome = false;
                getSupportActionBar().setTitle(name);
                fragment = AlarmFragment.newInstance(name);
                break;

            case 4:
                isFragment = true;
                isHome = false;
                getSupportActionBar().setTitle(name);
                nsame1 = name;
                isArchive = true;
                fragment = FragmentArchieve.newInstance(name);
                break;

            case 5:
                isFragment = true;
                isHome = false;
                getSupportActionBar().setTitle(name);
                nsame1 = name;
                isArchive = false;
                fragment = new ChartFragment();
                break;

            case 7:
                isFragment = true;
                isHome = false;
                getSupportActionBar().setTitle(name);
                fragment = SettingsFragment.newInstance(name);
                break;

            case 8:
                isFragment = true;
                isHome = false;
                getSupportActionBar().setTitle(name);
                fragment = AboutUsFragment.newInstance(name);
                break;

            case 9:
                isFragment = true;
                isHome = false;
                getSupportActionBar().setTitle(name);
                fragment = AccountManagerFragment.newInstance(name);
                break;

            case 10:
                isFragment = true;
                isHome = false;
                getSupportActionBar().setTitle(name);
                nsame1 = name;
                isArchive = false;
                fragment = GoalsFragment.newInstance(name, id);
                break;
        }

        if (isFragment) {
            android.support.v4.app.FragmentManager fragmentManager = getSupportFragmentManager();
            android.support.v4.app.FragmentTransaction ft = fragmentManager.beginTransaction();
            ft.setCustomAnimations(R.anim.abc_popup_enter, R.anim.abc_popup_exit);

            ft.replace(R.id.fragment_container, fragment, name).commit();
        }
    }

this to change fragment and im sure that im using the last version

**Comment by mikepenz** [comment]
close as there is the other issue open
