### ISSUE TITLE
Customize drawer item padding between img and text

### ISSUE THREAD

**Issue by vasiledoe** [mikepenz/MaterialDrawer#893]
![device-2015-12-25-143853](https://cloud.githubusercontent.com/assets/15106474/12002927/54566ad8-ab16-11e5-890f-e8ba0543258b.png)

Is there a possibility to change space interval between image and text in PrimaryDrawerItem, I was changed whole element padding using setPadding(int left, int top, int right, int bottom) in your PrimaryDrawerItem class. And if I can change drawer width?

**Comment by mikepenz** [comment]
Drawer width can be defined here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L454

regarding the spacing between icon and text. This is defined with the `material_drawer_item_primary_icon_padding_right` dimension. You can theoretically just define a different value, in your dimens.xml file. (but this will change it for all drawerItems)
As an alternative i would suggest you that you create your own `CustomPrimaryDrawerItem` by extending the `PrimaryDrawerItem` and just define a different layout for it, which changes this value 
(just overwrite this method https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/OverflowMenuDrawerItem.java#L62)

**Comment by vasiledoe** [comment]
yep got it, thx!
