### ISSUE TITLE
Minor issue in CustomContainerActivity

### ISSUE THREAD

**Issue by outoftrun** [mikepenz/MaterialDrawer#897]
CustomContainerActivity the  "private Drawer result = null;" never seems to get assigned

Nick

**Comment by mikepenz** [comment]
@outoftrun just checked. It get's assigned, and it's also used ;)
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java#L30

used here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java#L52
and here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java#L59
