### ISSUE TITLE
Icons Don't Change Color On selection

### ISSUE THREAD

**Issue by technovadors** [mikepenz/MaterialDrawer#898]
@mikepenz 
In your previous version, the color of the icon use to get changed with the selected text!
in the latest build doesn't happen the same way !
II previously used simple png monocolor icons from www.icons8.com or www.flaticons.com no iconics or other things
They use to work fine..
Can you help me out there ?

Also , how do we add the counter across an item, like Messages 24..shown in the screenshots.

**Comment by mikepenz** [comment]
@technovadors from which version to which version did you update?
have you enabled icon tinting?
https://github.com/mikepenz/MaterialDrawer/blob/73b3a198bb7d7c9c3f464ce58fdcb1d63ba80d58/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDrawerItem.java#L180

What do you mean across an item? You can add a `badge` to an item. 
This item has a custom `BadgeStyle`
https://github.com/mikepenz/MaterialDrawer/blob/73b3a198bb7d7c9c3f464ce58fdcb1d63ba80d58/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L118
You can either directly apply an badge to an item. Or at a later time
https://github.com/mikepenz/MaterialDrawer/blob/73b3a198bb7d7c9c3f464ce58fdcb1d63ba80d58/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L230
