### ISSUE TITLE
Custom item selection

### ISSUE THREAD

**Issue by vasiledoe** [mikepenz/MaterialDrawer#899]
In docs, it's mentioned about possibility to ignore item to became selected by default, using 'withSelectable(false)' .
I am trying to use this behavior on PrimaryDrawerItem, with possibility to set selected item later by myself, using 'drawer.setSelection(position)'. Unfortunately it's not working, maybe because I disabled selection first and now elements can't have selected state?

**Comment by mikepenz** [comment]
@vasiledoe no `withSelectable(false)` only disable the user selection. You can still do it programmatically.

Does your items have an `identifier`? the `setSelection` method selects by `identifier` not `position`
https://github.com/mikepenz/MaterialDrawer/blob/73b3a198bb7d7c9c3f464ce58fdcb1d63ba80d58/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L444

**Comment by vasiledoe** [comment]
got it, I was missing element.withIdentifier(identifier). Thx
