### ISSUE TITLE
Deactivate all account header profiles

### ISSUE THREAD

**Issue by iLexiconn** [mikepenz/MaterialDrawer#900]
I tried doing `accountHeader.setActiveProfile(-1)`, but that didn't work. Is there another way to do this?

**Comment by mikepenz** [comment]
@iLexiconn there is no method to have no active profile. Do you want to remove all profiles or what is the use case?

**Comment by iLexiconn** [comment]
My app has multiple accounts, but you don't have to be signed into one. currently it just shows the first account in the list.

**Comment by mikepenz** [comment]
@iLexiconn if you set all profiles to `.withSelectable(false)` they won't be selected and won't show up in the header profile images list.

**Comment by iLexiconn** [comment]
That method only exists in the builder, and now in the result.

**Comment by mikepenz** [comment]
@iLexiconn this method exists on the `ProfileDrawerItem`s

**Comment by iLexiconn** [comment]
Oh whoops, my bad. I just tested the method, I don't know what it does, but it completely messes up the app. It also didn't fix the issue, I still see the first profile activated.

**Comment by mikepenz** [comment]
@iLexiconn that's interesting. if i set all `ProfileDrawerItem`s to `withSelectable(false)` none is selected and no icons are shown in the header. (As it doesn't make sense to show those icons in the header if no account can be selected) Also as no `Profile` can be selected it won't show the name of the profile for the dropdown (You can set this text manually)

**Comment by iLexiconn** [comment]
That's not exactly what I want. I still want all the accounts to be selectable, but I don't want any of them to be selected. I know this is possible for menu items, but for some reason not for the profiles.

**Comment by mikepenz** [comment]
@iLexiconn but making them `withSelectable(false)` will still trigger the event, but won't allow them to be selected. 

The profiles use the same logic as normal items. but this is managed by the `AccountHeader`, so the things work as required in most projects

**Comment by mikepenz** [comment]
@iLexiconn will your `Drawer` still show one selected account on top? So with the big profile image, and with the firstname and e-mail in the dropdown? If yes and the only thing you want to change is the **selected background** you could create your own `CustomProfileDrawerItem` by overwriting the existing one (or copying the code of this item to your project) and remove the selected background, so everything will be the same but there will be no selected item in the list

**Comment by iLexiconn** [comment]
No, I don't want it to show the 'big' picture. I wanted it to look something like this:
![naamloos](https://cloud.githubusercontent.com/assets/5201999/12025603/fe865738-adb0-11e5-8f6a-a6b83a940a27.png)

**Comment by mikepenz** [comment]
@iLexiconn i added a new method for you which allows you to only show the small images. 
as an addition i created a branch for you with a commit showcasing the changes required to get the result you have shown above. (as you also want no selected state in the list)

Here's the commit https://github.com/mikepenz/MaterialDrawer/commit/e3f41eff15406b20516348fadce544eab73cd66a

**Comment by iLexiconn** [comment]
Thank you very much! :)

**Comment by mikepenz** [comment]
@iLexiconn v4.6.2 will take a while to sync to maven central. i hope it is exactly as you expect it

**Comment by iLexiconn** [comment]
Yeah it is, thanks :)

**Comment by mikepenz** [comment]
Great :)
