### ISSUE TITLE
Please add a simple title header

### ISSUE THREAD

**Issue by jahirfiquitiva** [mikepenz/MaterialDrawer#901]
Similar to this from a Google app (which name I'm not sure, but you can download it here http://www.apkmirror.com/apk/google-inc/arts-culture/arts-culture-1-0-1-android-apk-download/ )

![2015-12-28](https://cloud.githubusercontent.com/assets/10360816/12023177/e6e29868-ad64-11e5-9b81-591f3069c332.png)

**Comment by mikepenz** [comment]
@jahirfiquitiva you can add this on your own. Just provide add a header to your drawer.
