### ISSUE TITLE
CrossFade item alignment

### ISSUE THREAD

**Issue by Mithrandir21** [mikepenz/MaterialDrawer#903]
First of all, awesome library! Truly great work, great documentation and helpful demo app.

Now to the issue.
I have been looking at the CrossFade example in the demo. (Awesome by the way.)
I'm basically looking to go from no-drawer to mini-drawer to full-drawer.

What I'm wondering is if it's possible to align the icons in the mini-drawer with the corresponding icons/drawer items in the full-drawer?
This way, the expansion to full-drawer would not have the icons moving to new positions.

**Comment by mikepenz** [comment]
@Mithrandir21 hmmm this is not really possible, as not only the header has a different height, but also the width (and padding to the left) of the items is a bit different. 

What theoretically can be done is to optimize it, and animate the height of the profile in the `MiniDrawer` to the height of the full drawer this would at least minimize the difference of the icons.

**Comment by mikepenz** [comment]
@Mithrandir21 ok just tried my idea. there are more than issues.

* You have to make sure both lists scrolling is in sync
* You have to animate the MiniProfile height to the one from the AccountHeader
* You have to animate the height of the MiniDrawerItems to the height of the normal drawer

I have added a small animation to the latest sample, but not sure if you mean something similar
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CrossfadeDrawerLayoutActvitiy.java#L142
