### ISSUE TITLE
Text direction problem in RTL and LTR text

### ISSUE THREAD

**Issue by MBehtemam** [mikepenz/MaterialDrawer#904]
In my drawer i have both rtl text that start from right and ltr text that starts from left but i need a way that ltr text is start from left so all the items start's from right. so i need a way to ltr is start from right like rtl text.
thanks.
![2015-12-29_20-55-35](https://cloud.githubusercontent.com/assets/1811124/12038585/b59f5358-ae6e-11e5-885b-3b4602a100d7.jpg)

**Comment by mikepenz** [comment]
@MBehtemam that's no `MaterialDrawer` specific issue. That's default android behavior that LTR text is displayed LTR. Please you StackOverflow or Google to find a possibility to solve this issue. If this requires a Layout modification (perhaps text gravity right) then you can either create a `CustomDrawerItem` or you overwrite the layout of the `PrimaryDrawerItem` or you hook in via the `onPostBindView` hook and modify the `TextView`

One dev had the opposite once: https://github.com/mikepenz/MaterialDrawer/issues/812#issuecomment-156514494
