### ISSUE TITLE
Shouldn't withPadding* be chainable?

### ISSUE THREAD

**Issue by uzegonemad** [mikepenz/MaterialDrawer#905]
I did a quick search but couldn't find an answer, so apologies if this has been asked before.

When adding a badge style, all of the padding methods return void but shouldn't they return the BadgeStyle object for chaining purposes?

I'm having to do this:

```java
BadgeStyle badgeStyle = new BadgeStyle()
        .withColorRes(R.color.badgeColor)
        .withTextColor(Color.WHITE)
        .withCornersDp(999);

badgeStyle.withPaddingLeftRightDp(3);
badgeStyle.withPaddingTopBottomDp(3);
```

But would prefer to do this:

```java
BadgeStyle badgeStyle = new BadgeStyle()
        .withColorRes(R.color.badgeColor)
        .withTextColor(Color.WHITE)
        .withCornersDp(999)
        .withPaddingLeftRightDp(3)
        .withPaddingTopBottomDp(3);
```

**Comment by mikepenz** [comment]
@uzegonemad yes you are right. will be in the next version. thanks

**Comment by uzegonemad** [comment]
Hey @mikepenz, thank you so much for the quick response!

And thanks for your incredible library as well. It saved me hours of countless head scratching trying to write my own solution.

**Comment by mikepenz** [comment]
@uzegonemad no problem :)

Thank you so much :)
