### ISSUE TITLE
Small swipe to mini-drawer, big swipe to normal drawer

### ISSUE THREAD

**Issue by PedroBarbosaPT** [mikepenz/MaterialDrawer#906]
Hi!
I have a question
Is there a way to have to make the drawer a mini drawer or a normal depending on the swipe?
I can be a little confusing, if don't you understand please say.

Newbie question
And how can i make the drawer go in front of the actionbar?
![smashi](https://cloud.githubusercontent.com/assets/13065435/12059889/2955fdfe-af5c-11e5-95c8-83504223f112.png)

**Comment by mikepenz** [comment]
@PedroBarbosaPT you have to use a `Toolbar` as the `Actionbar` does not allow to be overlapped by other views. 

Regarding your swipe question. I do not understand it. Perhaps check out the sample application. It showcases the `MiniDrawer`

**Comment by PedroBarbosaPT** [comment]
Like this exemple I made in sony vegas:
![ezgif-240450849](https://cloud.githubusercontent.com/assets/13065435/12061071/ce8c268c-af74-11e5-883c-f9afa4e20449.gif)

**Comment by mikepenz** [comment]
@PedroBarbosaPT that's the `CrossfadeDrawerLayout` the sample application contains a sample activity with this.
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CrossfadeDrawerLayoutActvitiy.java
