### ISSUE TITLE
Using MaterialDrawer and Calligraphy library causes the fonts to break in materialdrawer

### ISSUE THREAD

**Issue by MarsVard** [mikepenz/MaterialDrawer#907]
when I wrap my context with Callygraphy, the MaterialDrawer loses all custom fonts(no more bold anywhere)

**Comment by mikepenz** [comment]
@MarsVard the `MaterialDrawer` has no custom fonts be default. Font style is defined via the normal Android methods. Perhaps your provided font does not have a **bold** variant?

**Comment by MarsVard** [comment]
Sorry for the late reply, this was a font issue, the default font was being used as set by Callygraphy and it didn't have a bold variant buit in the ttf, instead they are seperate fonts for bold and regular

**Comment by mikepenz** [comment]
@MarsVard great that you were able to solve it
