### ISSUE TITLE
Update Badge

### ISSUE THREAD

**Issue by crysan** [mikepenz/MaterialDrawer#91]
When you open MaterialDrawer I need to upgrade withBadge in new count_all_author

i created:
```java
new PrimaryDrawerItem(). withName(R.string.drawer_autors_name). withIcon(FontAwesome.Icon.faw_home). withBadge(String.valueOf(count_all_author)). withIdentifier(10)
```

How can this be done? 
Thanks in advance!

**Comment by mikepenz** [comment]
@crysan 

If you create the `Drawer`with the `.build()` method it will return a `Drawer.Result` object. This object contains helper methods to update the badge for a specific item (identified by it's identifier)

**Comment by crysan** [comment]
Okay. 
But still I can not find the opening event MaterialDrawer.

**Comment by mikepenz** [comment]
@crysan do you need a listener to get notified as soon as the drawer gets opened?
Look here: 
https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/MultiDrawerActivity.java#L51

If you want to trigger the opening of the drawer just do this:

`Drawer.Result result = ...build()`
`result.openDrawer()`

**Comment by crysan** [comment]
Ty!
