### ISSUE TITLE
Drawer and MiniDrawer lists don't appear to be in synch.

### ISSUE THREAD

**Issue by prilling** [mikepenz/MaterialDrawer#910]
I have started using the Drawer/MiniDrawer concept.  Adding static list items to the drawer, then building the mini as in your example, works fine.  However, I wanted to dynamically add/remove drawer items based on context, so I added/removed from the Drawer object.  My item appears as expected, but then when I collapsed to the mini view, my item was not there.  My expectation would be that if I add an item to the Drawer, then the "mini" would also be updated as necessary.

My work around was to call drawer.getMiniDrawer().getDrawerAdatper().addDrawerItems(...) at the same time I am adding to the main Drawer.

Seems once the various components are build, they are disconnected.  Not sure if this is by design or a bug, but just thought I would mention it.  Nice component though.

**Comment by mikepenz** [comment]
@prilling you have to notify the `MiniDrawer` that there is a new item:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/MiniDrawer.java#L345

**Comment by sosite** [comment]
If anyone are interesting how to sync miniDrawer items with drawer items - just call `miniDrawer.createItems()`
