### ISSUE TITLE
Items text not vertically centred

### ISSUE THREAD

**Issue by mradzinski** [mikepenz/MaterialDrawer#912]
Hi @mikepenz, using the latest version (4.6.3) the drawer items text is not being vertically centred. Any idea what I might be doing wrong?

![wrongmenuitemsize](https://cloud.githubusercontent.com/assets/4214209/12075315/0d627e5a-b15b-11e5-9e49-7931bb15dc9d.png)

Cheers and thanks for your support!

**Comment by mikepenz** [comment]
@mradzinski can you please try and run the sample app. is it also wrong for you?

Any modifications on your side?

What android version? Which device?

**Comment by mradzinski** [comment]
Just tried the sample and it's perfectly centred. No modifications from my side whatsoever. I'm running everything on a Nexus 5, Android M.

Here's the code I'm using to instantiate the drawer:

```
        mDrawer = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(mToolbar)
                .withAccountHeader(buildAccountHeader(accountInfo), true)
                .withDrawerItems(drawerItemsList)
                .withStickyFooterDivider(true)
                .withStickyFooterShadow(false)
                .build();
```

Each drawer item is built like this and added to an ArrayList which is later passed to the drawer:

```
                    PrimaryDrawerItem item = new PrimaryDrawerItem()
                            .withSetSelected(false)
                            .withOnDrawerItemClickListener(listener)
                            .withTag("tag")
                            .withDescription("Item description");
```

My Activty Layout is pretty much simple, just a *FrameLayout*. I guess the account header has nothing to do with this, but if it may have something to do let me know and I put the code here.

Thanks again for your support!

**Comment by mikepenz** [comment]
@mradzinski and you do not overwrite the items layout? 
What'S strange is the code you posed just defines the description for the item but not a name?

**Comment by mradzinski** [comment]
***withName***, that was the problem. Alright, now let me dedicate this awesome meme to myself, I deserve it


![conttopotato](https://cloud.githubusercontent.com/assets/4214209/12075418/f0ef4d12-b15e-11e5-8c36-303e3456e96a.jpg)

Thank you! and have a great beginning of 2016!
