### ISSUE TITLE
Compile with Sdk Version: 22

### ISSUE THREAD

**Issue by Titannet** [mikepenz/MaterialDrawer#913]
Hello!

I need to compile my app with compileSdkVersion 22, because when I'm using 23 version - support library add some permissions to my app. I don't need this.

But last version of MaterialDriver with support v.22 - is v3.1.2. This version too old. 

Advise how to solve this problem. Thank you in advance.

**Comment by mikepenz** [comment]
@Titannet normally i do not give advice how to use old versions of the drawer, but in this case. 

The README tells you to include the drawer like this:
```gradle
compile('com.mikepenz:materialdrawer:4.6.3@aar') {
    transitive = true
}
```

the **transitive** will take care to include all sub dependencies, including the support libs. If you want to define those sub dependencies on your own you have to remove the transitive and add the sub dependencies manually, which will allow you to define the support lib version:

```greadle
    compile "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    compile "com.android.support:recyclerview-v7:${rootProject.ext.supportLibVersion}"
    compile "com.android.support:support-annotations:${rootProject.ext.supportLibVersion}"

    // the drawer itself
    compile 'com.mikepenz:materialdrawer:4.6.3@aar'

    // used to base on some backwards compatible themes
    // contains util classes to support various android versions, and clean up code
    // comes with the awesome "Holder"-Pattern
    // https://github.com/mikepenz/Materialize
    compile 'com.mikepenz:materialize:0.5.1@aar'

    // used to provide out of the box icon font support. simplifies development,
    // and provides scalable icons. the core is very very light
    // https://github.com/mikepenz/Android-Iconics
    compile 'com.mikepenz:iconics-core:2.5.3@aar'
```

**Comment by Titannet** [comment]
Thx! But:
materialize:0.5.1 library use method: ContextCompat.getColor(ctx, mColorRes);
this method present only in sdk version 23

**Comment by mikepenz** [comment]
@Titannet then i'm afraid there is no easy way to use an older version of the support libs. 

Which permission is added by the support lib? 

It is hihgly recommended to always go with the latest support libs as they fix a huge amount of bugs, from version to version

**Comment by Titannet** [comment]
I solved the problem, thanks a lot!

This line in *build.gradle* file:
*compile 'com.google.android.gms:play-services:8.4.0'*
add the **identity** permissions.

But my project require only this subprojects:
*compile 'com.google.android.gms:play-services-analytics:8.4.0'*
*compile 'com.google.android.gms:play-services-gcm:8.4.0'*
*compile 'com.google.android.gms:play-services-ads:8.4.0'*

When I'm using this lines, permission is disappeared. I thik, this permission add a Google Address API (*com.google.android.gms:play-services-identity:8.4.0*)

I'm sorry for having wasted your time!

**Comment by mikepenz** [comment]
@Titannet thanks for adding your detailed solution
