### ISSUE TITLE
Unable to change Hamburger icon color

### ISSUE THREAD

**Issue by roshu10** [mikepenz/MaterialDrawer#914]
Hi,

i've followed #176 and #177 

My theme:
 ```xml
    <style name="CustomTheme" parent="MaterialDrawerTheme.Light.DarkToolbar">
        <!--no action bar-->
        <item name="android:windowActionBar">false</item>
        <item name="android:windowFullscreen">false</item>
        <item name="colorPrimary">#F1433C</item>
        <item name="colorPrimaryDark">#01877e</item>
        <item name="colorAccent">#000000</item>
        <item name="material_drawer_secondary_text">@color/material_drawer_dark_secondary_text
        </item>
        <item name="material_drawer_background">#01877e</item>
        <item name="material_drawer_primary_text">#FFFFFF</item>
        <item name="material_drawer_secondary_text">#FFFFFF</item>
        <item name="material_drawer_hint_text">@color/material_drawer_dark_hint_text</item>
        <item name="material_drawer_divider">@color/material_drawer_dark_divider</item>
        <item name="material_drawer_selected">#03655e</item>
        <item name="material_drawer_selected_text">#FFFFFF</item>
        <item name="material_drawer_header_selection_text">
            @color/material_drawer_dark_primary_text
        </item>

        <!-- CAB :D -->
        <item name="windowActionModeOverlay">true</item>

        <item name="drawerArrowStyle">@style/MaterialDrawer.DrawerArrowStyle</item>
    </style>
    <style name="MaterialDrawer.DrawerArrowStyle" parent="Widget.AppCompat.DrawerArrowToggle">
        <item name="spinBars">false</item>
        <item name="color">@android:color/white</item>
    </style>
```

However, I'm unable to change the hamburg icon color to white.. 

i'm adding hamburg icon and back arrow

```java
        result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);

        getSupportActionBar().setDisplayHomeAsUpEnabled(false);
        result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);
```

Hamburg icon gets display even without writing the above code. May be theme itself display the Hamburg icon.

But my problem is i'm unable to change Hamburg icon color from black to whilte ?

**Comment by mikepenz** [comment]
@roshu10 which style to you set on the toolbar?

**Comment by roshu10** [comment]
@mikepenz 
my toolbar theme
    <style name="ToolBarStyle" parent="Theme.AppCompat">
           <item name="android:textColorPrimary">@android:color/black</item>
           <item name="android:textColorSecondary">@android:color/black</item>
           <item name="actionMenuTextColor">@android:color/black</item>
     </style>

**Comment by mikepenz** [comment]
you also set it?
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/activity_sample_dark_toolbar.xml#L12

**Comment by roshu10** [comment]
@mikepenz 
Thanks mike.
now it's working after i set this
    
      <item name="android:textColorSecondary">@android:color/white</item>

**Comment by roshu10** [comment]
@mikepenz 
is it possible to set the width of drawer ?
I want to set this width to size of a lengthy name in drawer

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L465

**Comment by roshu10** [comment]
@mikepenz 
Thx mikepenz.

Only doubt if i don't know how much dp or px then what can i do ??

Is it possible to set the width automatically according to the lengthiest name in drawer ?

**Comment by mikepenz** [comment]
@roshu10 no sorry no auto widht possible, as the drawer wouldn't know on which to depend the width on. I still highly recommend that you go with the automatically generated width as this follows the material design guidelines
