### ISSUE TITLE
Android 4.1.1 - NoClassDefFoundError

### ISSUE THREAD

**Issue by nightstorm99** [mikepenz/MaterialDrawer#915]
On Android 4.1.1 crash the MaterialDrawer:

FATAL EXCEPTION: main
                                                                                 java.lang.NoClassDefFoundError: com.mikepenz.materialdrawer.R$drawable
                                                                                     at com.mikepenz.materialdrawer.holder.BadgeStyle.<init>(BadgeStyle.java:19)
                                                                                     at com.mikepenz.materialdrawer.model.PrimaryDrawerItem.<init>(PrimaryDrawerItem.java:21)

MaterialDrawer 4.6.3

**Comment by mikepenz** [comment]
@nightstorm99 how do you add the library to your project? 

Seems like the `R` field is missing or does not contain the **material_drawer_badge**
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/holder/BadgeStyle.java#L19

Which is defined here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/drawable/material_drawer_badge.xml

**Comment by nightstorm99** [comment]
Yes, the library is added.
On all other devices, it also runs.

I test this in Genymotion "Custom Device 4.1.1". This is an emulator.
On the 5.1 Genymotion device it runs.

What is very strange also that MaterialDrawerSample all run.

What can I do wrong?

**Comment by mikepenz** [comment]
@nightstorm99 do you use proguard?

**Comment by slymnatkl** [comment]
I have encountered the same error. Maybe this link might be useful 
https://developer.android.com/tools/building/multidex.html

**Comment by mikepenz** [comment]
@nightstorm99 do you use `MultiDex` as @slymnatkl mentioned?

**Comment by nightstorm99** [comment]
Hello,

Yes I had used the Multidex, but I had
the following package is not in the build.gradle inside:
compile 'com.android.support:multidex:1.0.0'

I test it and report back.

**Comment by mikepenz** [comment]
@nightstorm99 were you able to solve it?

**Comment by nightstorm99** [comment]
Hello,

Yes, I have solved the problem.

It was not the MaterialDrawer! (sorry)
It was the Google Play Services. I had used the entire library.
Now I only used the small Lib for Google Drive.

MultiDex I have to continue to use, but there is so far no problems.

Thanks for the brilliant Lib

**Comment by swapnilsaha2010** [comment]
@nightstorm99 
Can you tell in details how did you solve the matter?

**Comment by nightstorm99** [comment]
> Can you tell in details how did you solve the matter?

use `compile 'com.android.support:multidex:1.0.1'`
in your build.gradle

**Comment by ttimz1313** [comment]
No don't know how it happened
