### ISSUE TITLE
custom header view

### ISSUE THREAD

**Issue by buaacloud** [mikepenz/MaterialDrawer#917]
first of all, thanks for this awesome library,i have a question: can i custom the account header view ?
![image](https://cloud.githubusercontent.com/assets/4462280/12115467/8ae2a7a8-b3ed-11e5-9ad4-e177cc0c2cc8.png)

**Comment by mikepenz** [comment]
@buaacloud you can do this with a lots of custom handling, but i can't give support for this. 

I assume that the best would be that you provide a `Header` to the drawer and handle it via this? Do you need the account switch functionality?

**Comment by buaacloud** [comment]
I do not need the account switch functionality,I find the method :DrawerBuilder withHeader(@NonNull View headerView) ,solve my all problem,thanks again!
