### ISSUE TITLE
is there any parameter for drawer panel opening delay

### ISSUE THREAD

**Issue by besharati-behzad** [mikepenz/MaterialDrawer#918]
Hi mike.
i wanna use .withActionBarDrawerToggleAnimated method.
but drawer will be open too fast.
and i don't see any animation.
i want to make 300 millisecond delay before opening.

any solution?

**Comment by mikepenz** [comment]
@besharati-behzad the **Material Design Guidelines** state that the animated toggle should only be shown in special sub hirachies. If your drawer is full height in the main activity, it shouldn't animate. 

There is no property you can set for this, i think you will have to overwrite the `Navigation` click behavior. You can trigger the open / close of the drawer manully if you don't provide the `Toolbar` to the drawer. Then you can have your own `NavigationClickListener`. 
You should google how you can do this. As this is highly custom behavior.
