### ISSUE TITLE
[Requirement] Primary drawer item load image from url

### ISSUE THREAD

**Issue by mahendranv** [mikepenz/MaterialDrawer#919]
Is there any option to load primary drawer item image from url?

**Comment by mikepenz** [comment]
@mahendranv the sample implements a `CustomDrawerItem` which does this. 

Look here:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomUrlPrimaryDrawerItem.java

Which implements the following `CustomBaseDrawerItem`:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomUrlBasePrimaryDrawerItem.java
