### ISSUE TITLE
Set selection color for item icon?

### ISSUE THREAD

**Issue by y2kshane** [mikepenz/MaterialDrawer#92]
How to set  selection color for item icon?

**Comment by y2kshane** [comment]
ohhh i think i have to use `withSelectedIcon()` function. It would be easier for users if they can just give the selection icon color using a function

eg.  `withSelectedIconColor(R.color.color_accent);`
I think you can achieve this using ColorFilters like this

`
Drawable mDrawable = context.getResources().getDrawable(R.drawable.balloons); 
mDrawable.setColorFilter(new 
PorterDuffColorFilter(0xffff00,PorterDuff.Mode.MULTIPLY));
`

also check this out
[Drawable#setColorFilter](http://developer.android.com/reference/android/graphics/drawable/Drawable.html#setColorFilter%28int,%20android.graphics.PorterDuff.Mode%29)

**Comment by mikepenz** [comment]
Fixed in v2.0.6

See following line:
https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/ComplexHeaderDrawerActivity.java#L103

you have to enable this behavior. I hope you like it.

**Comment by y2kshane** [comment]
Thanks for the extremely fast reply.
I enabled it but still the icon color doesn't change.

``` java
 Drawer.Result result = new Drawer()
                .withActivity(this)
                .withTranslucentStatusBar(true)
                .withToolbar(toolbar)
                .withActionBarDrawerToggleAnimated(true)
                .withAccountHeader(headerResult)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("Home").withIcon(R.drawable.ic_action_home).withTintSelectedIcon(true),
                        new PrimaryDrawerItem().withName("New").withIcon(R.drawable.ic_action_content_add).withTintSelectedIcon(true),
                        new PrimaryDrawerItem().withName("Library").withIcon(R.drawable.ic_action_map).withTintSelectedIcon(true).withBadge("99"),
                        new SecondaryDrawerItem().withName("Settings").withIcon(R.drawable.ic_action_settings).withTintSelectedIcon(true)

.......               
```

**Comment by mikepenz** [comment]
@y2kshane oh i think i found the issue already. Was a mistake on my side. just implemented this for the case the user sets the drawable as drawable, and not from resource. 

Sorry for this. will be in the next version.

**Comment by y2kshane** [comment]
Thanks for the reply and for the update.
Is this the correct way of implementing it? Bcoz still nothing changed 

```java

        Drawer.Result result = new Drawer()
                .withActivity(this)
                .withTranslucentStatusBar(true)
                .withToolbar(toolbar)
                .withActionBarDrawerToggleAnimated(true)
                .withAccountHeader(headerResult)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName("Home").withIcon(R.drawable.ic_action_home).withSelectedIconColor(R.color.color_accent),
                        new PrimaryDrawerItem().withName("New").withIcon(R.drawable.ic_action_content_add).withSelectedIconColor(R.color.color_accent),
                        new PrimaryDrawerItem().withName("Library").withIcon(R.drawable.ic_action_map).withSelectedIconColor(R.color.color_accent).withBadge("99"),
                        new SecondaryDrawerItem().withName("Settings").withIcon(R.drawable.ic_action_settings).withSelectedIconColor(R.color.color_accent)

                )
```

Custom theme
```

    <style name="CustomTheme" parent="MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus">
        <!-- ...and here we setting appcompat’s color theming attrs -->
        <item name="colorPrimary">@color/color_primary</item>
        <item name="colorPrimaryDark">@color/color_status</item>
        <item name="colorAccent">@color/color_accent</item>

        <!-- MaterialDrawer specific values -->
        <item name="material_drawer_window_background">@color/material_drawer_window_background</item>
        <item name="material_drawer_background">@color/material_drawer_background</item>
        <item name="material_drawer_icons">@color/color_accent</item>
        <item name="material_drawer_primary_text">@color/material_drawer_primary_text</item>
        <item name="material_drawer_secondary_text">@color/material_drawer_secondary_text</item>
        <item name="material_drawer_hint_text">@color/material_drawer_hint_text</item>
        <item name="material_drawer_divider">@color/material_drawer_divider</item>
        <item name="material_drawer_selected">@color/material_drawer_selected</item>
        <item name="material_drawer_selected_text">@color/color_accent</item>
        <item name="material_drawer_header_selection_text">@color/material_drawer_header_selection_text</item>
    </style>
```

**Comment by mikepenz** [comment]
For normal icons you have to enable it with this method `. withTintSelectedIcon(true)`

**Comment by drinfernoo** [comment]
@mikepenz, what do you mean by "normal" icons?

With 2.5.3, this still isn't coloring my icons on selection:
`PrimaryDrawerItem item = new PrimaryDrawerItem().with icon(R.drawable.ic_action_settings).withSelectedIconColorRes(R.color.colorBlueGrey).withTintSelectedIcon(true);

**Comment by marc-84** [comment]
It wasn't working for me either. I just set the .withSelectedIcon(R.drawable.drawable_with_color) instead and it works.

**Comment by drinfernoo** [comment]
@marc-84, does that mean you have to manually tint each icon you want to use?

**Comment by marc-84** [comment]
Yeah, it didn't take too long, I only had a few icons. Although it would have been much easier if .withSelectedIconColor(R.color.color_accent) and .withTintSelectedIcon(true) worked.

**Comment by mikepenz** [comment]
@drinfernoo @marc-84 seems strange. i just tried it again within the sample application if i do following:

```java
new SecondaryDrawerItem().withName(R.string.drawer_item_contact).withSelectedIconColor(Color.RED).withTintSelectedIcon(true).withIcon(new IconicsDrawable(this, GoogleMaterial.Icon.gmd_add).actionBarSize().paddingDp(5).colorRes(R.color.material_drawer_dark_primary_text)).withTag("Bullhorn")
```

the "plus" sign is red if the item is the current selected item.

**Comment by drinfernoo** [comment]
Could it be because you're using Iconics?

**Comment by mikepenz** [comment]
@drinfernoo in the above case i create a drawable with it so it should make no difference. But yeah have not tried a different created drawable.

**Comment by mikepenz** [comment]
@drinfernoo ok just tried it with a different drawable. it get's colored. the drawable should be white i think.

**Comment by drinfernoo** [comment]
I'm using icons from here: http://shreyasachar.github.io/AndroidAssetStudio/icons-actionbar.html

**Comment by mikepenz** [comment]
@drinfernoo those are the GoogleMaterialDesign icons. these are also included with the Android-Iconics project :D See the sample with `GoogleMaterial.Icon.gmd_add` so you can use them too :D

But i've tried a icon before and it is colored. but it had white parts so i don't think it can color icons in other colors.

**Comment by marc-84** [comment]
So that's why. I was using a grey drawable and tried to tint it teal and it
turned out purple. So the drawable must be white.

**Comment by mikepenz** [comment]
@marc-84 yeah i use following method to color the drawable
```java
super.setColorFilter(selectionColor, PorterDuff.Mode.MULTIPLY);
```

If you have a different filter which would also work for other colors let me know, but i think this would create other issues.
