### ISSUE TITLE
Drawer without AccountHeader and collapsable function

### ISSUE THREAD

**Issue by Floriansimmer** [mikepenz/MaterialDrawer#921]
Hi

I have an strange problem with the Drawer.

With an Accountheader the collapsable function works flawless, but without it does not order the DrawerItems correctly.

I have made some Screenshots : 
![screenshot_2016-01-06-20-40-18 1](https://cloud.githubusercontent.com/assets/8532323/12152895/46b9fef8-b4b7-11e5-8304-dae6b77b32f1.png)
![screenshot_2016-01-06-20-40-23 1](https://cloud.githubusercontent.com/assets/8532323/12152897/46c40dd0-b4b7-11e5-8d1c-0f37eedf39f4.png)
![sample app without accountheader](https://cloud.githubusercontent.com/assets/8532323/12152896/46bc34fc-b4b7-11e5-8e20-d5332f89c0fd.png)

My DrawerActivity(from Sample with commented AccountHeader) 

[app.zip](https://github.com/mikepenz/MaterialDrawer/files/80281/app.zip)

**Comment by mikepenz** [comment]
@Floriansimmer you have to take care of the offset of the `AccountHeader` the position returned inside the listener is the global position. So if you have an `AccountHeader` or `Header` you have to add the offset of 1, without the header you have to remove this count of 1.

**Comment by Floriansimmer** [comment]
Get it thanks :+1:
