### ISSUE TITLE
Profile text color change in account header

### ISSUE THREAD

**Issue by aeroperf** [mikepenz/MaterialDrawer#923]
In my profile list, I'm using a dark background and white text color. The selected profile item has a white selection background, resulting in the select profile item text to disappear. 

I cannot seam to find how I change the selected profile item text color to something else. I looked at the custom color setup, but all that deals (very well, I might add) with the drawer items, not the profile items.

**Comment by mikepenz** [comment]
@aeroperf yeah the `ProfileDrawerItem` has no method to set a different  color for the text in selection state. It only has the single text color. 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileDrawerItem.java#L183

And the `PrimaryDrawerItem` has also the option to provide a different selected text color. 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BasePrimaryDrawerItem.java#L89

Will add it for the next version

**Comment by aeroperf** [comment]
No worries and thanks for the consideration to add. Great library!

**Comment by mikepenz** [comment]
@aeroperf this will be in v5.0.0. currently available as snapshot ;)
https://github.com/mikepenz/MaterialDrawer/issues/920
