### ISSUE TITLE
Delaying the click event doesn't work properly

### ISSUE THREAD

**Issue by androideveloper** [mikepenz/MaterialDrawer#925]
Hey!
Happy new year!

It seems that withDelayDrawerClickEvent() doesn't work as intended. 
I have this code:

                           new Handler().postDelayed(new Runnable() {
                                @Override
                               public void run() {
                             
                                        getSupportActionBar().setTitle(primaryDrawerItem.getName().getTextRes());
                                        String tag = (String) primaryDrawerItem.getTag();
                                        // make a fragment transaction
                      
                                }
                            }, 250); 

And this worked properly, because drawer was closed immediately and after that transaction was made.
I changed this to .withDelayDrawerClickEvent(250) and removed postDelayed. But this way, drawer is closed after 250 ms and transaction is made then. It lags.

**Comment by mikepenz** [comment]
@androideveloper just tried it. works as planned

```java
.withDelayDrawerClickEvent(250)
.withDelayOnDrawerClose(0)
```

Closes the `drawer` instantly, and after 250ms calls the listener

**Comment by androideveloper** [comment]
@mikepenz I have recorded my sample.

.withDelayDrawerClickEvent(2250)
.withDelayOnDrawerClose(0)

Try this. The drawer closes after 2.25s as you can see on the video
https://youtu.be/ZZcnqmuWpA4

**Comment by mikepenz** [comment]
@androideveloper you didn't mention that you use the `MiniDrawer` that's a completely different case :P

**Comment by androideveloper** [comment]
okay :D both are from the same lib :P

**Comment by mikepenz** [comment]
@androideveloper with the `MiniDrawer` you can't use this method as the `MiniDrawer` is hooked together with the `Drawer` via the `click` listener. So when you click on the item it will wait the time until the event is triggerend which will resize the `Drawer`. 

Please keep the code you posted in the question as is basically the same i do for the normal event. 

Regarding the fact that both are from the same lib. yes that's true. but theoretically the `MiniDrawer` is not bound to the `Drawer` (just a few methods to minimize code).

**Comment by androideveloper** [comment]
@mikepenz ok. As I understand, this line
return mMiniDrawer.onItemClick(drawerItem);
closes the drawer. So it is done after 2.25s. 
Hope things will go better later. Thanks

**Comment by mikepenz** [comment]
@androideveloper as mentioned. just set the delays to 0ms and add the handler as you posted in the question above in your code. 

There is not much i can do about the behavior, as the "toggle" is done after event is called.

**Comment by androideveloper** [comment]
@mikepenz Ok :)
