### ISSUE TITLE
MiniDrawer

### ISSUE THREAD

**Issue by MecDuino** [mikepenz/MaterialDrawer#929]
I am newbie for android. I am trying to develop my first android application with MiniDrawer as below image. I tried to do it in various ways searching through the internet . but i couldn't do it. so please, tell me a way to do it by using simple code or step by step process.
thanks.

UPDATE:
I used this sample but it's not work for me.
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java

![480](https://cloud.githubusercontent.com/assets/16644919/12230594/9e24be9e-b877-11e5-869c-73efa281eaf6.png)

**Comment by mikepenz** [comment]
@MecDuino what does not work?

**Comment by MecDuino** [comment]
result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withActionBarDrawerToggleAnimated(true)
                .withDisplayBelowStatusBar(true)
                .withTranslucentNavigationBarProgrammatically(true)
                .addDrawerItems(
                        new PrimaryDrawerItem().withIcon(getResources().getDrawable(R.drawable.ic_account_circle)).withIdentifier(0),
                        new PrimaryDrawerItem().withName("About").withIdentifier(1)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        return false;
                    }
                })
                .withGenerateMiniDrawer(true)
                .build();

I used above code. it's generate noraml navigation drawer. but i need to create mini drawer. such as above image. also I need to know how can I change the icon size of withIcon() as above image?

**Comment by mikepenz** [comment]
@MecDuino the `MiniDrawer` sample already shows the whole code which is necessary to get it working. It is also commented to state what's happening where.

Regarding your screenshot. The default `MiniDrawer` (for which i can give support)  has the icons with the size defined in the **Material Design Guidelines**. If you need custom style it is possible, but will require more advanced android coding knowledge. Which might be a bit to complicated for a beginner.
