### ISSUE TITLE
How do i set a custom layout?

### ISSUE THREAD

**Issue by createS0ftware** [mikepenz/MaterialDrawer#93]
Is it possible to add a custom layout as a DividerItem or any other item?

Thanks

**Comment by mikepenz** [comment]
Yes. You can create and modify the items as you like. Just look at the implementation of the PrimaryDrawerItem or some similiar item, they all implement the IDrawerItem (and some other interfaces you can also use for improved features) and then you can simply add them ;)

https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/java/com/mikepenz/materialdrawer/model/PrimaryDrawerItem.java

https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/java/com/mikepenz/materialdrawer/model/DividerDrawerItem.java

Should be really simple. 

If you have any further questions. Just ask.

**Comment by createS0ftware** [comment]
Ok, I understand , Thanks
