### ISSUE TITLE
Should I Use Fragments or Activities When Clicking On the Nav Drawer?

### ISSUE THREAD

**Issue by troy21688** [mikepenz/MaterialDrawer#931]
I am new to Android programming and came across this library as an amazing, efficient, and easy solution for my development. However, I was curious as to whether I should use fragments or activities for this NavDrawer. Basically, I am thinking I would host one MainActivity, and then each fragment would be placed inside that MainActivity on the NavDrawer click.

Any advice is appreciated.

**Comment by mikepenz** [comment]
@troy21688 this drawer does not define this. You can choose what you prefer and what fits best in your application. 

Just implement the listener and react if the user clicks a drawer item

```java
.withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
        @Override
        public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
            // do something with the clicked item :D
        }
    })
```

**Comment by troy21688** [comment]
Thanks for the prompt response Mike! New to programming and the library
simplifies everything.

On Wed, Jan 13, 2016 at 4:51 PM, Mike Penz <notifications@github.com> wrote:

> @troy21688 <https://github.com/troy21688> this drawer does not define
> this. You can choose what you prefer and what fits best in your
> application.
>
> Just implement the listener and react if the user clicks a drawer item
>
> .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
>         @Override
>         public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
>             // do something with the clicked item :D
>         }
>     })
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikepenz/MaterialDrawer/issues/931#issuecomment-171462607>
> .
>



-- 
Troy Chuinard, CPA
