### ISSUE TITLE
NavDrawer Disappears on Screen Rotation

### ISSUE THREAD

**Issue by troy21688** [mikepenz/MaterialDrawer#932]
I am rotating my screen and noticing that the NavDrawer / Hamburger Icon disappears on screen rotation. I have overridden onSavedInstanceState() but not sure what else I am doing wrong:

```java
    public class MainActivity extends AppCompatActivity implements PollFragment.OnFragmentInteractionListener {

    Drawer result;
    AccountHeader headerResult;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.tool_bar);
        setSupportActionBar(toolbar);

        // Check that the activity is using the layout version with
        // the fragment_container FrameLayout
        if (findViewById(R.id.fragment_container) != null) {

            // However, if we're being restored from a previous state,
            // then we don't need to do anything and should return or else
            // we could end up with overlapping fragments.
            if (savedInstanceState != null) {
                return;
            }

            // Create a new Fragment to be placed in the activity layout
            PollFragment firstFragment = new PollFragment();

            // In case this activity was started with special instructions from an
            // Intent, pass the Intent's extras to the fragment as arguments
            firstFragment.setArguments(getIntent().getExtras());

            // Add the fragment to the 'fragment_container' FrameLayout
            getSupportFragmentManager().beginTransaction()
                    .add(R.id.fragment_container, firstFragment).commit();
        }


        new DrawerBuilder().withActivity(this).build();

        PrimaryDrawerItem item1 = new PrimaryDrawerItem().withName(R.string.drawer_item_home);
        SecondaryDrawerItem item2 = new SecondaryDrawerItem().withName(R.string.drawer_item_preferences);
        SecondaryDrawerItem item3 = new SecondaryDrawerItem().withName(R.string.drawer_item_request_poll);
        SecondaryDrawerItem item4 = new SecondaryDrawerItem().withName(R.string.drawer_item_suppport);
        SecondaryDrawerItem item5 = new SecondaryDrawerItem().withName(R.string.drawer_item_logut);

        headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.ic_facebook)
                .addProfiles(
                        new ProfileDrawerItem().withEmail(SignupActivity.getEmail()).withIcon(getResources().getDrawable(R.drawable.logo))
                )
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                        return false;
                    }
                })
                .withSavedInstance(savedInstanceState)
                .build();


        result = new DrawerBuilder()
                .withAccountHeader(headerResult)
                .withActivity(this)
                .withToolbar(toolbar)
                .addDrawerItems(
                        item1,
                        new DividerDrawerItem(),
                        item2,
                        item3,
                        item4,
                        item5
                )
                .withSavedInstance(savedInstanceState)
                .build();


    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        //add the values which need to be saved from the drawer to the bundle
        outState = result.saveInstanceState(outState);
        //add the values which need to be saved from the accountHeader to the bundle
        outState = headerResult.saveInstanceState(outState);
        super.onSaveInstanceState(outState);
    }

    @Override
    public void onFragmentInteraction(Uri uri) {

    }
}
```

**Comment by mikepenz** [comment]
@troy21688 you have 2 drawers in your activity?
remove this line
```java
new DrawerBuilder().withActivity(this).build();
```

**Comment by troy21688** [comment]
Mike -

Still not visible on landscape orientation after rotation. I removed the savedInstanceState() code to see if you could spot another reason:

    public class MainActivity extends AppCompatActivity implements PollFragment.OnFragmentInteractionListener, PreferencesFragment.OnFragmentInteractionListener {

    Drawer result;
    AccountHeader headerResult;
    PollFragment firstFragment;
    FragmentManager fm;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.tool_bar);
        setSupportActionBar(toolbar);
        fm = getSupportFragmentManager();

        // Check that the activity is using the layout version with
        // the fragment_container FrameLayout
        if (findViewById(R.id.fragment_container) != null) {

            // However, if we're being restored from a previous state,
            // then we don't need to do anything and should return or else
            // we could end up with overlapping fragments.
            if (savedInstanceState != null) {
                return;
            }

            // Create a new Fragment to be placed in the activity layout
            firstFragment = new PollFragment();

            // In case this activity was started with special instructions from an
            // Intent, pass the Intent's extras to the fragment as arguments
            firstFragment.setArguments(getIntent().getExtras());

            // Add the fragment to the 'fragment_container' FrameLayout
            fm.beginTransaction()
                    .add(R.id.fragment_container, firstFragment).commit();
        }


        PrimaryDrawerItem item1 = new PrimaryDrawerItem().withName(R.string.drawer_item_home).withIdentifier(1);
        SecondaryDrawerItem item2 = new SecondaryDrawerItem().withName(R.string.drawer_item_preferences).withIdentifier(2);
        SecondaryDrawerItem item3 = new SecondaryDrawerItem().withName(R.string.drawer_item_request_poll).withIdentifier(3);
        SecondaryDrawerItem item4 = new SecondaryDrawerItem().withName(R.string.drawer_item_suppport).withIdentifier(4);
        SecondaryDrawerItem item5 = new SecondaryDrawerItem().withName(R.string.drawer_item_logut).withIdentifier(5);

        headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.ic_facebook)
                .addProfiles(
                        new ProfileDrawerItem().withEmail(SignupActivity.getEmail()).withIcon(getResources().getDrawable(R.drawable.logo))
                )
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                        return false;
                    }
                })
                .build();


        result = new DrawerBuilder()
                .withAccountHeader(headerResult)
                .withActivity(this)
                .withToolbar(toolbar)
                .addDrawerItems(
                        item1,
                        new DividerDrawerItem(),
                        item2,
                        item3,
                        item4,
                        item5
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        switch (drawerItem.getIdentifier()) {
                            case 1:
                                fm.beginTransaction().replace(R.id.fragment_container,firstFragment).addToBackStack(null).commit();
                                break;
                            case 2:
                                Fragment prefsFragment = new PreferencesFragment();  //this is your new fragment.
                                fm.beginTransaction()
                                        .replace(R.id.fragment_container, prefsFragment)
                                        .addToBackStack(null)
                                        .commit();
                                break;
                        }

                        return false;
                    }
                })
                .build();


    }


    @Override
    public void onFragmentInteraction(Uri uri) {

    }

**Comment by mikepenz** [comment]
because you do not add the drawer anymore if the `savedInstanceState` is `!= null`

```java
    // Check that the activity is using the layout version with
    // the fragment_container FrameLayout
    if (findViewById(R.id.fragment_container) != null) {

        // However, if we're being restored from a previous state,
        // then we don't need to do anything and should return or else
        // we could end up with overlapping fragments.
        if (savedInstanceState != null) {
            return;
        }
```

**Comment by troy21688** [comment]
Much appreciated Mike. Realized that the return statement completely kills the method. I have encapsulated quite a bit and it all makes sense:

    public class MainActivity extends AppCompatActivity implements PollFragment.OnFragmentInteractionListener, PreferencesFragment.OnFragmentInteractionListener {

    Drawer result;
    AccountHeader headerResult;
    PollFragment firstFragment;
    FragmentManager fm;
    Toolbar toolbar;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        toolbar = (Toolbar) findViewById(R.id.tool_bar);
        setSupportActionBar(toolbar);
        fm = getSupportFragmentManager();

        // Check that the activity is using the layout version with
        // the fragment_container FrameLayout
        if (findViewById(R.id.fragment_container) != null) {

            // However, if we're being restored from a previous state,
            // then we don't need to do anything and should return or else
            // we could end up with overlapping fragments.
            if (savedInstanceState != null) {
                createNavDrawer();
                return;
            }

            // Create a new Fragment to be placed in the activity layout
            firstFragment = new PollFragment();

            // In case this activity was started with special instructions from an
            // Intent, pass the Intent's extras to the fragment as arguments
            firstFragment.setArguments(getIntent().getExtras());

            // Add the fragment to the 'fragment_container' FrameLayout
            fm.beginTransaction()
                    .add(R.id.fragment_container, firstFragment)
                    .commit();
        }

        createNavDrawer();
    }


    @Override
    public void onFragmentInteraction(Uri uri) {

    }

    public void createNavDrawer(){

        PrimaryDrawerItem item1 = new PrimaryDrawerItem().withName(R.string.drawer_item_home).withIdentifier(1);
        SecondaryDrawerItem item2 = new SecondaryDrawerItem().withName(R.string.drawer_item_preferences).withIdentifier(2);
        SecondaryDrawerItem item3 = new SecondaryDrawerItem().withName(R.string.drawer_item_request_poll).withIdentifier(3);
        SecondaryDrawerItem item4 = new SecondaryDrawerItem().withName(R.string.drawer_item_suppport).withIdentifier(4);
        SecondaryDrawerItem item5 = new SecondaryDrawerItem().withName(R.string.drawer_item_logut).withIdentifier(5);

        headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withHeaderBackground(R.drawable.ic_facebook)
                .addProfiles(
                        new ProfileDrawerItem().withEmail(SignupActivity.getEmail()).withIcon(getResources().getDrawable(R.drawable.logo))
                )
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                        return false;
                    }
                })
                .build();


        result = new DrawerBuilder()
                .withAccountHeader(headerResult)
                .withActivity(this)
                .withToolbar(toolbar)
                .addDrawerItems(
                        item1,
                        new DividerDrawerItem(),
                        item2,
                        item3,
                        item4,
                        item5
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        switch (drawerItem.getIdentifier()) {
                            case 1:
                                Fragment pollFragment = new PollFragment();
                                replaceFragment(pollFragment);
                                break;
                            case 2:
                                Fragment prefsFragment = new PreferencesFragment();
                                replaceFragment(prefsFragment);
                                break;
                        }

                        return false;
                    }
                })

                .build();

    }

    public void replaceFragment(Fragment fragmentToLoad){
        FragmentManager fm = getSupportFragmentManager();
        fragmentToLoad.setArguments(getIntent().getExtras());
        fm.beginTransaction()
                .replace(R.id.fragment_container, fragmentToLoad)
                .addToBackStack(null)
                .commit();

    }
}
