### ISSUE TITLE
Profile Icon not refresh after download 

### ISSUE THREAD

**Issue by Krashband** [mikepenz/MaterialDrawer#933]
Hello
I'm trying to download the profile image and update the header but it doesn't work to open the drawer. Instead if I close the app and open it again the image is updated. I have tried several ways to load or refresh image and everywhere is the same, so I think that is a bug in the library. Also I used the DrawerImageLoader and I have the same problem. I enclose my current code. Thanks a lot
 
       final AccountHeader headerResult = new AccountHeaderBuilder()
                .withActivity(this)
                .withSelectionListEnabledForSingleProfile(false)
                .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                        return false;
                    }
                })
                .build();

        result = new DrawerBuilder().withActivity(this).withTranslucentStatusBar(false)
                .withActionBarDrawerToggle(true).withAccountHeader(headerResult)
                .withSavedInstance(savedInstanceState).addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.abc_action_bar_home_description),
                        new SecondaryDrawerItem().withName(R.string.dgts__confirmation_error)
                )
                .withShowDrawerOnFirstLaunch(true)
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        if (drawerItem instanceof Nameable) {
                            Toast.makeText(ViewPagerActivity.this, ((Nameable) drawerItem).getName().getText(ViewPagerActivity.this), Toast.LENGTH_SHORT).show();
                        }

                        return false;
                    }
                }).withToolbar(toolbar).build();

        getSupportActionBar().setDisplayHomeAsUpEnabled(false);
        result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);

        Target target = new Target() {
            @Override
            public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {

                headerResult.addProfiles(
                        new ProfileDrawerItem().withName("test").
                                withEmail("@test").
                                withIcon(bitmap)

                );
            }

            @Override
            public void onBitmapFailed(Drawable errorDrawable) {

            }

            @Override
            public void onPrepareLoad(Drawable placeHolderDrawable) {

            }
        };

        Picasso.with(getBaseContext()).load(app.getUser().getOriginalProfileImageURL()).into(target);

**Comment by mikepenz** [comment]
@Krashband image loading is not part of the library. I just offer the api to do so. 

If you have you update any item of the drawer (profile, drawerItem, ...) you always have to notify the drawer or accountHeader about that change. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L235

If you define a profile image via url, and have defined the `ImageLoader` it will work automatically. If you change that profile image you also have to notify the accountHeader about that change.

**Comment by Krashband** [comment]
Hello
I've used the updateProfile method and it still does not update the header information. I've also tried creating the profile after downloading the image and not shown. The information is only displayed when I leave the application and go back inside, without killing the process.

**Comment by mikepenz** [comment]
@Krashband you use the `DrawerImageLoader` as shown in the sample application?

**Comment by Krashband** [comment]
Yes 
I use DrawerImageLoader. This is a example of mi code:

                 final AccountHeader headerResult = new AccountHeaderBuilder()
                   .withActivity(this)
                   .withSelectionListEnabledForSingleProfile(false)
                    .withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
                    @Override
                    public boolean onProfileChanged(View view, IProfile profile, boolean currentProfile) {
                        return false;
                    }
                })

                .build();

        result = new DrawerBuilder().withActivity(this).withTranslucentStatusBar(false)
                .withActionBarDrawerToggle(true).withAccountHeader(headerResult)
                .withSavedInstance(savedInstanceState).addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.abc_action_bar_home_description),
                        new SecondaryDrawerItem().withName(R.string.dgts__confirmation_error)
                )
                .withShowDrawerOnFirstLaunch(true)
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        if (drawerItem instanceof Nameable) {
                            Toast.makeText(ViewPagerActivity.this, ((Nameable) drawerItem).getName().getText(ViewPagerActivity.this), Toast.LENGTH_SHORT).show();
                        }

                        return false;
                    }
                }).withToolbar(toolbar).build();

        ProfileDrawerItem profile=new ProfileDrawerItem().withName("test").withEmail("@test").withIcon(app.getUser().getBiggerProfileImageURL());
        Picasso.with(getApplication()).load(app.getUser().getProfileBannerMobileRetinaURL()).transform(new BlurTransform(getApplicationContext()))
                .fit().centerCrop().into(headerResult.getHeaderBackgroundView());
        headerResult.setActiveProfile(profile);



        //initialize and create the image loader logic
        DrawerImageLoader.init(new AbstractDrawerImageLoader() {
            @Override
            public void set(ImageView imageView, Uri uri, Drawable placeholder) {
                Picasso.with(imageView.getContext()).load(uri).placeholder(placeholder).into(imageView);
            }

            @Override
            public void cancel(ImageView imageView) {
                Picasso.with(imageView.getContext()).cancelRequest(imageView);
            }


        }); 

Name, email and background image is load correctly, but profile image icon not load.If I leave the app and go back inside the profile icon will display correctly.

**Comment by mikepenz** [comment]
@Krashband just tried the following in the sample:

within the `onDrawerItemClickListener` (just to do this at a later point than starting the activity) i call the following:
```java
profile.withIcon("https://avatars1.githubusercontent.com/u/634243?v=3&s=96");
headerResult.updateProfile(profile);
```

which will update the profile with **identifier** 100 (`.withIdentifier(100)`)
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L63

and the image loading is done via glide. but should work the same with picasso
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java#L40
