### ISSUE TITLE
Understanding how the drawer overlaps the toolbar vs underneath the toolbar

### ISSUE THREAD

**Issue by tachang** [mikepenz/MaterialDrawer#936]
So I am having a hard time understanding how to make sure the drawer overlaps the toolbar vs is rendered underneath it.

I have the layout below the toolbar right now but I see in the example application this is also the case. However in the example app (activity_sample_dark_toolbar.xml) it is also below. Is it due to me using a LinearLayout instead of a RelativeLayout?

    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:orientation="vertical"
        android:layout_width="wrap_content"
        android:layout_height="match_parent">

        <android.support.v7.widget.Toolbar
            android:layout_width="fill_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            android:id="@+id/toolbar">

            <LinearLayout
                xmlns:android="http://schemas.android.com/apk/res/android"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="horizontal">

                <com.exampleapp.views.SlidingTabLayout
                    android:id="@+id/sliding_tabs"
                    android:layout_width="0dp"
                    android:layout_weight="1"
                    android:layout_height="wrap_content"
                    android:fillViewport="false" />

            </LinearLayout>

        </android.support.v7.widget.Toolbar>

        <FrameLayout
            android:layout_below="@id/toolbar"
            android:id="@+id/drawer_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            
            <FrameLayout
                android:id="@+id/frame_container"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <TextView
                    android:id="@+id/txtLabel"
                    android:layout_gravity="center"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="Test"
                    android:textSize="16sp" />

                <android.support.v4.view.ViewPager
                    android:id="@+id/viewpager"
                    android:layout_width="match_parent"
                    android:layout_height="fill_parent"
                    android:background="@android:color/white"/>
            </FrameLayout>
            
        </FrameLayout>

    </LinearLayout>

        PrimaryDrawerItem a = new PrimaryDrawerItem().withName(R.string.drawer_item_a);
        PrimaryDrawerItem b = new PrimaryDrawerItem().withName(R.string.drawer_item_b);

        Drawer drawer = new DrawerBuilder()
                .withActivity(this)
                .withRootView(R.id.drawer_container)
                .addDrawerItems(
                    a,
                    b
                )
                .withToolbar(toolbar)
                .withDisplayBelowStatusBar(false)
                .withActionBarDrawerToggleAnimated(true)
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        Log.i(Constants.APP_NAME, "Drawer item clicked: " + drawerItem.toString());
                        return false;
                    }
                })
                .build();

        getSupportActionBar().setDisplayHomeAsUpEnabled(false);
        drawer.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);

**Comment by tachang** [comment]
It looks like it was my understanding of what 

  withRootView(R.id.drawer_container)

does. Maybe just some clarification on that.

**Comment by mikepenz** [comment]
@tachang by default the `DrawerLayout` is inflatet directly in the root. (android.R.id.content) which is around your layout you provide. As it is in the root it will by default be full height. If you do not want this you have to inflate the drawer somewhere else, in this example inside the frame_container. Which is below the toolbar because it defines `android:layout_below="@id/toolbar"`
