### ISSUE TITLE
Bug: header name

### ISSUE THREAD

**Issue by TurKurT656** [mikepenz/MaterialDrawer#937]
hi @mikepenz , long time to see you again
tnQ for this amazin lib.
when i add a single accountHeader to drawer that have a RTL language name. the name appears in the right side of the drawer that looks ugly.

**Comment by mikepenz** [comment]
@TurKurT656 but that's how Android and RTL works. You can prevent to show this on text when you do the following:
https://github.com/mikepenz/MaterialDrawer/issues/812#issuecomment-156514494

otherwise you could disable it by overwriting the original layout

**Comment by TurKurT656** [comment]
Thnx man, good link,
and can i change the font size of the header text?
i want it a bit more big

**Comment by mikepenz** [comment]
@TurKurT656 define a custom dimension for `material_drawer_account_header_text`
