### ISSUE TITLE
Detecting interaction with Navigation Drawer

### ISSUE THREAD

**Issue by dmelechow** [mikepenz/MaterialDrawer#938]
I want to hide a keyboard of ediText, when i start interact with navigation drawer. How can I detect interaction? In advance thank you)

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1119

**Comment by dmelechow** [comment]
@mikepenz  thanks a lot))
