### ISSUE TITLE
Swiping of MiniDrawer like in Evernote

### ISSUE THREAD

**Issue by jurrick** [mikepenz/MaterialDrawer#939]
Is it possible to use MiniDrawer like in Evernote to overlaps the rest of area and don't move the area.

Example:
![1](https://cloud.githubusercontent.com/assets/6017015/12386922/e57a8c58-bdd9-11e5-9fae-e5aab5e4e8b5.png)
![2](https://cloud.githubusercontent.com/assets/6017015/12386921/e57a6822-bdd9-11e5-97bc-4e2a0bba66c8.png)

**Comment by mikepenz** [comment]
@jurrick hmmm the `MiniDrawer` with the `Crossfader` can't do this as the layout which holds the `Crossfader` is on the same "level" as the other content and we just resize the panels. 

There is one possible solutions for this use case. 
You implement a `FrameLayout` which hosts the `Crossfader` (including `MiniDrawer` and normal `Drawer` on top of the other views) and which adds the shadow. 

One other solution (not sure how the above implementation works in real live) is that you have a normal `Drawer` including the normal `DrawerLayout` in your application, and also add the `MiniDrawer` to the app (without the `Crossfader`) so the user sees the `MiniDrawer` which syncs with the `Drawer` if the user now swipes from the left edge the normal `Drawer` will overlap the `MiniDrawer` and the rest of the ui. (it will also be full height, which would look better)
