### ISSUE TITLE
Translucent Status Bar Problem

### ISSUE THREAD

**Issue by MFlisar** [mikepenz/MaterialDrawer#940]
I have a working activity with a translucent statusbar and a semi transparent toolbar on top, so the content is scrolling underneath it.

I enable this behaviour in code via a user setting, so I'm using the non translucent theme in my styles.

Now as soon as I add a drawer, it messes everything up... Code looks like following:
```java
	DrawerBuilder leftBuilder = new DrawerBuilder()
                .withActivity(this)
                .withAccountHeader(mAccountHeader)
                .withSelectedItem(selectedIdentifier)
                .addDrawerItems(
                        ...
                );
		
	// tried combinations of those values...
	//leftBuilder
	//    .withFullscreen(true)
	//	.withTranslucentStatusBar(true)
	//	.withTranslucentNavigationBar(true);

    mDrawerLeft = leftBuilder.build();
    // set correct status bar color
    mDrawerLeft.setStatusBarColor(ColorUtil.setTransparency(ThemeManager.getTheme().primaryColor(), 100))
```

As soon as I add a drawer, the toolbar get's solid again and the `fitsSystemWindows` flags of my layout's views don't work anymore... If I use `withFullscreen`, then the content is fully underneath the status bar, what I don't want... Toolbar should be under the statusbar only, not underneath...

**Comment by mikepenz** [comment]
@MFlisar take a look at the `FullScreenDrawer` example:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/FullscreenDrawerActivity.java

**Comment by MFlisar** [comment]
For me, I can only get this working if I manually add a padding to my toolbar afterwards... So that it is moved under the statusbar, otherwise the toolbar is overlapped by the statusbar

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/activity_sample_fullscreen_dark_toolbar.xml#L29

The thing is that the drawer manages the insets of the screen by default so the drawer is full height but the application isn't

**Comment by MFlisar** [comment]
So this is "by design"... I thought so anyway, but I did not see where you set the margin for the toolbar until now

**Comment by MFlisar** [comment]
Maybe you can answer follwing question as well:

I now use it the way you suggest, but have a small problem:

* I set the statusbar background to transparent
* I have following two layouts in my activity

    <include layout="@layout/view_main_toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:layout_marginTop="@dimen/tool_bar_top_padding"/>

    <View
        android:id="@+id/vStatusBarBackground"
        android:background="?attr/main_background_color"
        android:layout_width="match_parent"
        android:layout_height="@dimen/tool_bar_top_padding" />

I theme my activity like this:

    activity.getSupportActionBar().setBackgroundDrawable(new ColorDrawable(getTranslucentToolbarColor()));
    statusBarBackground.setBackgroundColor(getTranslucentToolbarColor());

The problem is, that the color of the toolbar differs from the color of the status bar. I tried to directly color the `ActionBar`, but this has the same effect... Directly coloring the `Toolbar` does not work... I get a visible cut between the status bar and the toolbar, although it's only hard to see, but it's there...

Any idea why this happens? When I don't use your library and use the `fitsSystemWindows` flags in the layout and remove the `statusBarBackground` view, the toolbar stretches and the statusbar does colorise with a slight gradient...

**Comment by MFlisar** [comment]
Nevermind... Had the problem the last days and as soon as I ask I saw the problem myself...

The elevation is causing this...

Still, the only solution I see now is setting it to `0dp` as setting the elevation of the `statusBarBackground` to `4dp` does not solve the problem...
