### ISSUE TITLE
Question - ItemClickListener

### ISSUE THREAD

**Issue by TurKurT656** [mikepenz/MaterialDrawer#941]
when i add this method:
```java
.withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
        @Override
        public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
            return false;
        }
    })
```
there is position value for finding drawerItems. but when i click on StickyDrawerItems all of them returns -1 as position. so how to select them?
I've added .withIdentifier(int position) to them but nothing changed. so what is Identifier exactly? :|

**Comment by mikepenz** [comment]
@TurKurT656 the items are selected automatically. Or what do you mean?

If you want to react on the click you should identify them via their identifier:
```java
drawerItem.getIdentifier()
```

`StickyDrawerItems` will always return position = `-1` as those are not part of the list and are managed independent of the rest of the items

**Comment by TurKurT656** [comment]
TnQ,
drawerItem.getIdentifier()   worked for Me.
