### ISSUE TITLE
Mini drawer selection shows two items highlighted 

### ISSUE THREAD

**Issue by Debjyotinath** [mikepenz/MaterialDrawer#944]
I am using a mini drawer. While selecting an item on the mini drawer,two items are shown highlighted
![screenshot_2016-01-20-10-59-38 1](https://cloud.githubusercontent.com/assets/16771926/12440748/09ec49a0-bf65-11e5-9d36-bc00858506d3.png)

As you can see two items are highlighted.
Steps to recreate this-
1.Go to the mini drawer fragment.
2.Select any item on the mini drawer
3.Open the drawer.
4.Select any PrimaryItem from the list.After this selection the drawer closes and the mini drawer is displayed.
5.From the mini drawer make another selection.You will notice the previous highlighted selection is not removed.

**Comment by mikepenz** [comment]
@Debjyotinath i can't reproduce this. Which version are you using? 
This one is also obsolete as soon as i release v5.0.0 which switches to the `FastAdapter`. the `FastAdapter` will be responsible for taking care of the selections afterwards

**Comment by Debjyotinath** [comment]
i have downloaded it from the playstore.
So when we expecting the 5.0.0 version?

**Comment by mikepenz** [comment]
@Debjyotinath ok that's weird. i can't reproduce it with the steps you mentioned. Tried it on my Nexus 5 and Nexus 6P :/ 

v5.0.0 is already available as SNAPSHOT in beta state. (really stable) 
Can't name a date for the stable release though

**Comment by Debjyotinath** [comment]
Can i use the SNAPSHOT? if yes, then can you provide me the gradle dependancy for the SNAPSHOT build(v5.0.0)?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/920

**Comment by Debjyotinath** [comment]
cool!!
thanx

**Comment by Debjyotinath** [comment]
The above case is working fine with the SNAPSHOT build.Thank you again.
