### ISSUE TITLE
Lack of depth

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/MaterialDrawer#945]
MiniDrawer and MaterialDrawer lack of depth when they are open, it seems that they are in the same level of the activity that hosts them. They should be more "elevated".

**Comment by mikepenz** [comment]
@EpsilonOrionis they are on the same level yes. you can enable the inner shadow for the `MiniDrawer`?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/Crossfader/blob/develop/app/src/main/java/com/mikepenz/crossfader/app/SimpleActivity.java#L137
