### ISSUE TITLE
How to select multiple items?

### ISSUE THREAD

**Issue by knezmilos13** [mikepenz/MaterialDrawer#947]
As the title states - is there a way to allow selection of multiple items in the list? I've set withCloseOnClick to false, and added my own click listener. 

Great library, btw :D

**Comment by knezmilos13** [comment]
Nvm, found it's not possible in older issues.

**Comment by mikepenz** [comment]
@knezmilos13 will be available in v5.0.0. You can already try out the SNAPSHOT:
https://github.com/mikepenz/MaterialDrawer/issues/920
