### ISSUE TITLE
White "padding" or "margin" at the bottom of the screen.

### ISSUE THREAD

**Issue by elod91** [mikepenz/MaterialDrawer#948]
![drawer_error](https://cloud.githubusercontent.com/assets/5939261/12482546/e66a415e-c058-11e5-8454-a0cbfa54b607.png)
As you can see in the screenshot, there's a small problem. I've checked my code and I didn't set any margin or padding.

**Comment by mikepenz** [comment]
@elod91 you can check out the sample app it doesn't include this space either. can you provide your layout and the code how you configure the drawer?

**Comment by elod91** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context="net.reea.meeting.activities.CalendarActivity">

    <include layout="@layout/toolbar" />
</LinearLayout>
This is my layout, it had a TextView, but I removed it (it was there just for testing).

And here's the java code:

drawer = new DrawerBuilder()
                .withActivity(this)
                .withActionBarDrawerToggle(false)
                .withToolbar(getToolbar())
                .withSelectedItem(-1)
                .withAccountHeader(generateAccountHeader(), true)
                .addDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.calendar_drawer_account),
                        new PrimaryDrawerItem().withName(R.string.calendar_drawer_settings),
                        new DividerDrawerItem(),
                        new PrimaryDrawerItem().withName(R.string.calendar_drawer_logout)
                )
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem) {
                        doDrawerAction(position);
                        return true;
                    }
                })
                .build();



I'll check out the sample app. This bug doesn't happen all the time. Just randomly, sometimes it works ok, othertimes it doesn't.

**Comment by elod91** [comment]
The layout is a LinearLayout with just the toolbar in it.

**Comment by mikepenz** [comment]
with the provided code everything is fine. so this does not cause the issue.

You are sure there is no margin or padding in any other part of your code or in the content layout?
What's the used theme? 

It seems you have exactly the height of the statusbar at the bottom.

**Comment by elod91** [comment]
Tried the sample application. It works well. The used theme is Theme.AppCompat.Light

**Comment by elod91** [comment]
with withTranslucentStatusBar(false) the white line disappears. But I want it to be translucent.

**Comment by elod91** [comment]
Tried changing the parent style to MaterialDrawerTheme, but still the same.

**Comment by elod91** [comment]
![drawer_ok](https://cloud.githubusercontent.com/assets/5939261/12484053/fe901ec2-c060-11e5-9e00-99a8ae07319e.png)

As you can see, sometimes it works ok.

**Comment by mikepenz** [comment]
if you use this theme `MaterialDrawerTheme.TranslucentStatus`?

**Comment by mikepenz** [comment]
do you have a `fitSystemWindows` somewhere in your layout?

**Comment by elod91** [comment]
Yes, I had. In my toolbar layout

**Comment by elod91** [comment]
removed it, but still not working

**Comment by mikepenz** [comment]
Never experienced it in any apps i did, nor someone else mentioned it. I really would love to debug it. could you provide a sample app which showcases the issue. with everything app related non public, non relevant removed?

**Comment by elod91** [comment]
If I have the time, I'll create a sample app and provide you with the code. Tomorrow I'll try something else and if it's fixed, I'll tell you the solution

**Comment by mikepenz** [comment]
thanks. the provided snippets seem fine so yeah. :/

**Comment by elod91** [comment]
Tomorrow I'll give you the code used in the toolbars layout

**Comment by elod91** [comment]
![drawer_style](https://cloud.githubusercontent.com/assets/5939261/12503792/66e9d7b8-c0e0-11e5-99b7-8f7ac45e4a32.png)

I've added the MaterialDrawerTheme.Light.TranslucentStatus theme and this was the result.

**Comment by elod91** [comment]
Here's the toolbars layout:

<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.Toolbar xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/meeting_toolbar"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_alignParentTop="true"
    android:background="?attr/colorPrimary"
    android:minHeight="?attr/actionBarSize">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:paddingRight="@dimen/activity_horizontal_margin">

        <TextView
            android:id="@+id/toolbar_title"
            android:layout_width="wrap_content"
            android:layout_height="?attr/actionBarSize"
            android:layout_toRightOf="@+id/toolbar_meeting_action"
            android:gravity="center"
            android:maxHeight="?attr/actionBarSize"
            android:text="Search"
            android:textColor="@color/text"
            android:textSize="20sp" />

        <ImageView
            android:id="@+id/toolbar_meeting_action"
            android:layout_width="wrap_content"
            android:layout_height="?attr/actionBarSize"
            android:layout_marginRight="@dimen/create_meeting_margin_right_x"
            android:src="@drawable/ic_clear" />

        <TextView
            android:id="@+id/toolbar_meeting_save"
            android:layout_width="wrap_content"
            android:layout_height="?attr/actionBarSize"
            android:layout_alignParentRight="true"
            android:gravity="center_vertical"
            android:text="SAVE"
            android:textColor="@android:color/white" />

        <TextView
            android:id="@+id/toolbar_meeting_list"
            android:layout_width="wrap_content"
            android:layout_height="?attr/actionBarSize"
            android:layout_alignParentRight="true"
            android:gravity="center_vertical"
            android:text="@string/toolbar_btn_meeting_list"
            android:textColor="@android:color/white" />

        <TextView
            android:id="@+id/toolbar_calendar_view"
            android:layout_width="wrap_content"
            android:layout_height="?attr/actionBarSize"
            android:layout_alignParentRight="true"
            android:gravity="center_vertical"
            android:text="@string/toolbar_btn_calendar_view"
            android:textColor="@android:color/white" />

        <EditText
            android:id="@+id/toolbar_meeting_title_input"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:layout_below="@+id/toolbar_title"
            android:background="@null"
            android:hint="Enter title..."
            android:textColor="@android:color/white"
            android:textColorHint="@android:color/white"
            android:textSize="20sp" />
    </RelativeLayout>
</android.support.v7.widget.Toolbar>

**Comment by elod91** [comment]
Found the cause of our little problem. I think. I needed to query the logged in user from the phones DB to get its name and email. This took a very short time, but it seems like it matters. Because if I don't query the users and automatically set up the drawer with dummy data, it works. So at the moment I set up the drawer 2 times. First time with dummy data, second time with real data. (I use the builder 2 times).

It would be nice if we could add an account header the the built drawer object and not just with the withAccountHeader method. This way I wouldn't need to build the drawer 2 times.

**Comment by mikepenz** [comment]
@elod91 oh you had two builders? ok you are only allowed to build a `Drawer` once per activity.

If you have to add the header at a later time. you could do this if you create your `AccountHeader` build it. then you can get the view of the header and set it to the `Drawer`
`drawer.withHeader(accountHeader. getView())` and you set the `Drawer` for the `AccountHeader` so it can toggle the items.. https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L47

**Comment by elod91** [comment]
I had only one builder. With one builder I had the problem. Which was that I didn't build the drawer as soon as the activity started. First I queried the logged in user and when I got the result I built the drawer.

**Comment by Surajsunkara2** [comment]
Is these problem is solved or not..?@elod91

**Comment by elod91** [comment]
@Surajsunkara2 yes, if you read every comment, you'll also find the solution.

**Comment by Surajsunkara2** [comment]
I'm not able to understand,Can u explain clearly......
