### ISSUE TITLE
ProfileDrawerItem couldn't load icon from Url

### ISSUE THREAD

**Issue by mdtuyen** [mikepenz/MaterialDrawer#949]
I try with facebook account, and load icon from Url but not successfull.

**Comment by mikepenz** [comment]
@mdtuyen have you defiend a `DrawerImageLoader`?
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java#L40
https://github.com/mikepenz/MaterialDrawer#load-images-via-url

**Comment by mdtuyen** [comment]
Thanks, I miss that code, And I want change header back ground with Url from cover photo facebook ? What should I do ?
