### ISSUE TITLE
NavigationDrawer below the toolbar

### ISSUE THREAD

**Issue by hemersonsilva** [mikepenz/MaterialDrawer#951]
How do I put the NavigationDrawer below the toolbar ?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_show_drawer_under_toolbar.md

**Comment by hemersonsilva** [comment]
Thanks brother.
