### ISSUE TITLE
Display content fragments

### ISSUE THREAD

**Issue by EnduroXPro** [mikepenz/MaterialDrawer#952]
I need to display fragments as content when I click on a menu element inside of the navigation drawer. 
When I implement it, I get an empty layout and I do not know how to solve it. 

Please see my stackoverflow post: 

http://stackoverflow.com/questions/34992081/navigationdrawer-does-not-show-fragment-pages

**Comment by FabianTerhorst** [comment]
@EnduroXPro are you sure you have to set  ```android:layout_weight="1"``` and when you use coordinatorlayouts every fragment should have its own coordinatorlayout.

**Comment by mikepenz** [comment]
@EnduroXPro if you just set the fragment without using any listeners or similiar of the drawer? willl it work? 
--> just move the fragment setting to the end of the onCreate method. 

If it does not work the issue is not materialDrawer related
