### ISSUE TITLE
Keyboard issue. Soft Input overlaps the edit text

### ISSUE THREAD

**Issue by vanniktech** [mikepenz/MaterialDrawer#953]
I've looked into all of the other issues and so far I can't figure out why it does not work.

```java
mDrawer = new DrawerBuilder()
    .withActivity(this)
    .withToolbar(toolbar)
    .withAccountHeader(mAccountHeader)
    .addDrawerItems(
        // Some Items
    )
    .withOnDrawerItemClickListener((view, position, drawerItem) -> {
        // Callback
    })
    .withSelectedItem(-1)
.build();

mDrawer.keyboardSupportEnabled(this, true);
mDrawer.setActionBarDrawerToggle(drawerToggle);
```

My root layout is a `RelativeLayout` without `android:fitsSystemWindows="true"`

My problem is that I have an EditText and the moment I click on it and want to type things in, I can't see it anymore since the Keyboard is hiding it. Hence the EditText does not move up.

I've tried both adding and removing `android:windowSoftInputMode="adjustResize"` from the Activity declaration in the AndroidManifest.

What am I missing?

**Comment by mikepenz** [comment]
`android:windowSoftInputMode="adjustResize"` does not work as soon as the activity has the `FULLSCREEN` flag which is required to draw the drawer below the `Toolbar`

Normally the `KeyboardUtil` helps a bit to fix the behavior, or get a similar behavior similar to the one "adjustResize" would create. 

Have you tried the `KeyboardUtil Drawer` sample?

**Comment by vanniktech** [comment]
Yup I did, that's also where I got the `result.keyboardSupportEnabled(this, true);` from. Though unfortunately it still does not work.

**Comment by vanniktech** [comment]
The interesting thing is that `adjustPan` does work without any special treatment. Like `result.keyboardSupportEnabled(this, true);` etc

**Comment by mikepenz** [comment]
@vanniktech yeah that's the thing like android treats it internally. there are pretty long issues regarding this topic. 

Does it work in the sample app for you? Any special keyboard you use?

**Comment by vanniktech** [comment]
Yes the sample app does work for me. No special keyboard in use. I have plain Android M on my phone.

Is anything regarding the theme important?

**Comment by mikepenz** [comment]
hmmm no the theme doesn't play a role here :/ 

If you look at the source of the `KeyboardUtil` you will see it does nothing else than detecting when the keyboard is shown, and will then resize your contentView which should cause the `EditText` to move into focus. But this only works if your view is something like a `ScrollView` or a `RecyclerView` or `ListView`

**Comment by vanniktech** [comment]
Hmm the view that should be moved up has a FrameLayout as it's root.

**Comment by mikepenz** [comment]
may there is not enough space that the `EditText` get's moved up far enough?

**Comment by vanniktech** [comment]
I found one solution that does 'work'. I can use the parent layout of the EditText and move the view up with `new KeyboardUtil(this, myParentLayoutOfEditText).enable();`

**Comment by mikepenz** [comment]
oh ok

**Comment by vanniktech** [comment]
@mikepenz I've just seen that you released 5.0.0 and I have a question about `fitsSystemWindows`, do I have to set that somewhere or does the library do that for me?

Also what about the `KeyboardUtil` is that still needed or do you think that we won't need that anymore?

**Comment by mikepenz** [comment]
@vanniktech it is automatically done for you :)

Should no longer be necessary as `adjustResize` should work now as expected

**Comment by vanniktech** [comment]
Oh awesome :)

I'm gonna test this out tomorrow and I'll let you know!

**Comment by vanniktech** [comment]
Okay I could not wait :D I tried it quickly out and does seem to work nicely (though I only tested it on one device etc).

I found one issue though. It seems like the `AccountHeader` does not properly update when I change the `ProfileDrawerItem` 

Related code:

```
mProfileItem.withName(accountModel.getName()).withEmail(accountModel.getPhone());
mAccountHeader.updateProfile(mProfileItem);
```

If you want, I can also go and create a new issue out of this.

**Comment by mikepenz** [comment]
@vanniktech your profile defines an `identifier`?

**Comment by vanniktech** [comment]
Okay I could not wait :D I tried it quickly out and does seem to work nicely (though I only tested it on one device etc).

I found one issue though. It seems like the `AccountHeader` does not properly update when I change the `ProfileDrawerItem` 

Related code:

```
mProfileItem.withName(accountModel.getName()).withEmail(accountModel.getPhone());
mAccountHeader.updateProfile(mProfileItem);
```

If you want, I can also go and create a new issue out of this.

**Comment by vanniktech** [comment]
@mikepenz Nope it does not

**Comment by mikepenz** [comment]
@vanniktech you have an identifier set for your profile? As mentioned I tried it in the sample, with the same code and it worked

**Comment by vanniktech** [comment]
Okay the missing identifier was an issue. In 4.6.4 I never even once set an identifier after setting it for every item it did work. Maybe this should be mentioned in the migration file?

**Comment by mikepenz** [comment]
@vanniktech will re-add the auto identifier applying in v5.0.1
https://github.com/mikepenz/MaterialDrawer/commit/81d9a48a8b773fa8cf243282829a655b863982f6

**Comment by vanniktech** [comment]
@mikepenz awesome thank you so much!
