### ISSUE TITLE
Translucent status bar

### ISSUE THREAD

**Issue by EpsilonOrionis** [mikepenz/MaterialDrawer#954]
How can I make the status bar translucent like in the sample app?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/AndroidManifest.xml#L15
just use a theme which makes the statusBar translucent

**Comment by EpsilonOrionis** [comment]
It doesn't work

**Comment by mikepenz** [comment]
@EpsilonOrionis you use the correct theme?

Then could you please add some more details? Which library version?

**Comment by EpsilonOrionis** [comment]
Ok, translucent status bar is working now, but the whole activity background turned its color from white to my primaryColor

**Comment by mikepenz** [comment]
@EpsilonOrionis could you please add some more details?

**Comment by EpsilonOrionis** [comment]
MaterialDrawerTheme.Light.DarkToolbar.TranslucentStatus this is the theme

**Comment by mikepenz** [comment]
@EpsilonOrionis how do you build the drawer?

**Comment by EpsilonOrionis** [comment]
// Create the drawer and remember the `Drawer` result object
        result = new DrawerBuilder()
                .withActivity(this)
                .withTranslucentStatusBar(true)
                .withDrawerLayout(crossfadeDrawerLayout)
                .withHasStableIds(true)
                .withDrawerWidthDp(72)
                .withAccountHeader(headerResult)
                .withToolbar(toolbar)

**Comment by mikepenz** [comment]
@EpsilonOrionis how do you build the drawer?

**Comment by EpsilonOrionis** [comment]
.withSelectedItem(-1)
                .withActionBarDrawerToggleAnimated(true)
                .build();

**Comment by mikepenz** [comment]
@EpsilonOrionis seems fine too. Can you double check again with the sample app?
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CrossfadeDrawerLayoutActvitiy.java

On which android version do you test it?

If you do not find anything it would be great if you can provide a small sample app to showcase the issue.

**Comment by EpsilonOrionis** [comment]
Android version L 5.0.2

**Comment by mikepenz** [comment]
@EpsilonOrionis i don't know. the sample doesn't show this behavior. So i only can assume that the layout may be different or that any other part of your code causes this

**Comment by EpsilonOrionis** [comment]
I figured out. To limit overdraw I was using: android:background="@null" in my layout...

**Comment by mikepenz** [comment]
but the original layout also does not define a background: https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/activity_sample_dark_toolbar.xml

**Comment by EpsilonOrionis** [comment]
Anyway I'm using withDelayOnDrawerClose(int delay), because when I click an item to open a different activity, the closing animation isn't smooth. But I don't see any difference even if I set a very long delay. How can I solve this?

**Comment by EpsilonOrionis** [comment]
Yes, but it wasn't @null

**Comment by mikepenz** [comment]
@EpsilonOrionis sorry this is a `MiniDrawer` specific limitation: https://github.com/mikepenz/MaterialDrawer/issues/925#issuecomment-170608570

**Comment by EpsilonOrionis** [comment]
No problem, thank you :)
