### ISSUE TITLE
NavigationView with different icon states

### ISSUE THREAD

**Issue by DavidMont** [mikepenz/MaterialDrawer#955]
first of all , thank you for this library.

I just wanna ask if this is possible.

http://stackoverflow.com/questions/34986313/navigationview-with-different-icon-states

thanks,
Dave

**Comment by mikepenz** [comment]
@DavidMont the short answer yes. 

The long answer. As this drawerItem is no default item you will have to create your own `CustomDrawerItem` which looks like the one in the image. 

In the sample app source code there are a few `CustomDrawerItems` 

Or there's also a description here:
http://stackoverflow.com/questions/31030595/how-to-customize-the-draweritem-using-the-lib-mikepenz-materialdrawer/32542999#32542999

Or you may check already asked questions:
https://github.com/mikepenz/MaterialDrawer/issues?utf8=%E2%9C%93&q=CustomDrawerItem
