### ISSUE TITLE
Drawer is below the view

### ISSUE THREAD

**Issue by ChoHyun-myung** [mikepenz/MaterialDrawer#956]
Hello, excuse to my poor ENG T_T.  Im using wonderful MaterialDrawer now. And that when using it, i found something i can't understand it. Im using drawer and mapAPI both. And there are some problems. When first run the app and open the Drawer, it is below to MapView.
![image](https://cloud.githubusercontent.com/assets/16913794/12606712/dcc71230-c512-11e5-9eb5-b26b6e3e3f6b.png)
and then, close the drawer and reopen the drawer it will work fine.
![image](https://cloud.githubusercontent.com/assets/16913794/12606728/f1bb22bc-c512-11e5-845f-7f1993d77fce.png)

Here is my code.
activiy_main.xml
```java
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:gravity="center"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        android:elevation="4dp"/>

    <FrameLayout
        android:layout_below="@+id/toolbar"
        android:id="@+id/fragment_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

</RelativeLayout>
```
MainActivity.java in onCreate()
```java
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Initialize mMapView
        mMapView = new MapView(this);
        mMapView.setDaumMapApiKey(API_KEY);

        // Enable Daum_Map use the cache
        MapView.setMapTilePersistentCacheEnabled(true);

        mapViewContainer = (ViewGroup) findViewById(R.id.fragment_container);
        mapViewContainer.addView(mMapView);

        // Handle Toolbar
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        // set the drawer toggle icon in the actionbar
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        // set the title in the actionbar
        getSupportActionBar().setTitle(R.string.app_name);

        // Create the drawer
        result = new DrawerBuilder()
                .withActivity(this)
                .withToolbar(toolbar)
                .withDisplayBelowStatusBar(true)
                .addDrawerItems(        // Add the items want to use with drawer
                        new PrimaryDrawerItem().withName("오늘의 할인").withIcon(R.drawable.ic_todayssale).withIdentifier(1),
                        new SectionDrawerItem().withName("오늘의 랭킹").withEnabled(false)
                )
                .addStickyDrawerItems(
                        new PrimaryDrawerItem().withName(R.string.drawer_item_setting).withIcon(R.drawable.ic_setting).withIdentifier(2).withEnabled(false),
                        new SecondaryDrawerItem().withName("Contact").withIdentifier(3).withSelectable(false)
                )
                .withSavedInstance(savedInstanceState)
                .build();
```

I changed Layout in .xml or wrap the layout with other layout, but i cant solve this problem.
Is there any ways to solve this problem??

**Comment by mikepenz** [comment]
@ChoHyun-myung seems to be a `DrawerLayout` and `MapView` issue. Have you googled if other people also have this issue? 

Perhaps you can move the MapView to the background?

**Comment by ChoHyun-myung** [comment]
I used MapView in Korea, and there is anybody use both your MaterialDrawer and MapView i use.

**Comment by mikepenz** [comment]
@ChoHyun-myung this has nothing to do with the `MaterialDrawer` but with the `DrawerLayout` which is from Android. 

That were just ideas. I know that a `FrameLayout` has a method `.bringToFront()` which may could help.

**Comment by ChoHyun-myung** [comment]
Thx to your kind reply. I just use in OnDrawerListener onDrawerSlide override method. In this method run the toolbar.bringToFront();.
I think this problem is cuz of DrawerLayout n MapView. But i should use this MapAPI for my App. So that although the foolish code(onDrawerSlide, toolbar.bringToFront()), I just use it.

**Comment by mikepenz** [comment]
@ChoHyun-myung ok cool thanks. 

Have a nice evening ;).
