### ISSUE TITLE
How do i add events like event bus in DrawerItems?

### ISSUE THREAD

**Issue by DavidMont** [mikepenz/MaterialDrawer#957]
_First off, this is my first time migrating from old way of drawer-menu to this library. Please be gentle_ :D

How do i add events like event bus in BaseDrawerItem or AbstractDrawerItem?

In my drawer items I have a specific design which has an icon states, My question is how can I know that RecyclerView is attach or detach? As to where I put my EventBus register/unregister.

Thanks,
Dave

**Comment by mikepenz** [comment]
Good morning @DavidMont 

If you just want to have events from the `RecyclerView` you can get the reference to this view via: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L262

Best,
Mike

**Comment by DavidMont** [comment]
Good day to you too @mikepenz 

Ah yes, Fortunately there is another way, Getting the drawer Item in `result.getDrawerItem(int identifier)` would solve my issue.
