### ISSUE TITLE
Multiple calls to oncreateview on orientation change

### ISSUE THREAD

**Issue by midhunQburst** [mikepenz/MaterialDrawer#959]
@mikepenz  I am facing this issue of getting multiple calls to oncreateview of fragment which is shown on the navigation drawer item click. The same issue is mentioned in this link http://blog.sqisland.com/2014/06/navigationdrawer-creates-fragment-twice.html. Is there any solution implemented in this library? Can you guide me on how to solve this issue.

**Comment by mikepenz** [comment]
@midhunQburst i am not really sure what you mean. 

Inside the click listener you can set the `fragment`. You can activate that as soon as the `Activity` is created the `click` event is fired once, so the event get's called with the fragment to select.

**Comment by midhunQburst** [comment]
I have added navigation drawer to my activity. I have few options like home, login, profile etc in my navigation drawer. When I click on any of the option I will show a fragment for the same. Until this everything works fine. Now when I change the orientation, activity gets recreated, fragment gets recreated as the case with Android. But the problem is fragments onCreateView method is called twice in this scenario.  with savedBundle  (that I saved on onSaveInstanceState) first  and with a null bundle second time. When I Googled I got the [link](http://blog.sqisland.com/2014/06/navigationdrawer-creates-fragment-twice.html). But I am confused, like how can I add this with the library or have you already added this fix.

**Comment by mikepenz** [comment]
@midhunQburst as the drawer does not manage fragments this has to be handled on your side. 

By default the `onDrawerItemClick` event is not fired upon launch. (You can enable this if you want to have your complete logic for switching fragments inside the listener). 

So you can just write the "fix" inside the click listener or whereever you have your fragment transaction logic.
