### ISSUE TITLE
Attribute has already been defined

### ISSUE THREAD

**Issue by nambv** [mikepenz/MaterialDrawer#96]
Hi @mikepenz.
Your lib is very useful but when import library, I got this error, can you tell me how to fix it :(
Thanks a lot for your help!!

```
D:\workspaces\quickref-android\app\build\intermediates\exploded-aar\com.mikepenz.materialdrawer\library\2.0.4\res\values\values.xml
Error:(1) Attribute "track" has already been defined
Error:(1) Attribute "thumbTextPadding" has already been defined
Error:(1) Attribute "switchTextAppearance" has already been defined
Error:(1) Attribute "switchMinWidth" has already been defined
Error:(1) Attribute "switchPadding" has already been defined
Error:(1) Attribute "switchStyle" has already been defined
```

**Comment by mikepenz** [comment]
@nambv hi which additional libraries are you using?

I'll search where my code could contain one of those attributes.

**Comment by mikepenz** [comment]
@nambv those values attributes come from the `android.support.v7.appcompat` library. Which version do you use? Normally gradle should be able to identify this. But i assume that it has some issues if there are different versions of the support librarry.

```javascript
compile "com.android.support:appcompat-v7:21.0.3"
```

**Comment by nambv** [comment]
Hi @mikepenz I find out the library conflict with MaterialDrawer is https://github.com/derekbrameyer/android-betterpickers

May be this lib using the same material attributes with your library?

**Comment by nambv** [comment]
I have update complie in `build.gradle` but It's not work, either

```
compile('com.mikepenz.materialdrawer:library:2.0.7@aar') {
        transitive = true
        exclude group: 'com.android.support', module: 'support-v4'
    }
```

**Comment by nambv** [comment]
Hi, @mikepenz.
Finally I can get It done by remove `exclude group: 'com.android.support', module: 'support-v4'` from the other lib

My `build.gradle` :

```
compile('com.mikepenz.materialdrawer:library:2.0.7@aar') {
        transitive = true
        exclude group: 'com.android.support', module: 'support-v4'
    }
compile 'org.jraf:android-switch-backport:1.4.0'
compile 'com.doomonafireball.betterpickers:library:1.5.4' 
```
Thank you very much for your assistant ^^

**Comment by mikepenz** [comment]
@nambv thanks for the info that you found a solution, but you should probably exclude the support library from the betterpickers because it is an older version, and they've added some fixes in the newer versions.
