### ISSUE TITLE
SecondaryDrawerItems in selected state do not display their description

### ISSUE THREAD

**Issue by justjanne** [mikepenz/MaterialDrawer#960]
How to replicate: Add a PrimaryDrawerItem, with a SecondaryDrawerItem as subitem, select the subitem in the drawer

Expected: SubItem’s description is readable, like in the default state

What happens: SubItem’s description is not displayed

Is this expected?

**Comment by mikepenz** [comment]
@justjanne with v5.0.0 beta?

**Comment by justjanne** [comment]
@mikepenz Yes, with v5.0.0

Is it just that the text color for the selected state is transparent? I haven’t really checked, just used defaults.

**Comment by mikepenz** [comment]
Just tried it. I can't reproduce it. 

<img width="442" alt="bildschirmfoto 2016-01-30 um 22 23 58" src="https://cloud.githubusercontent.com/assets/1476232/12698565/34a259e4-c7a0-11e5-9190-b9597f8d7efe.png">

**Comment by justjanne** [comment]
I'm talking about the description, not the title.

**Comment by mikepenz** [comment]
the two `collapsable` items do have a description **test**, and the second one **TestTestTest**. If you mean something else, could you please add a screenshot?

**Comment by justjanne** [comment]
BaseSecondaryDrawerItem.java

> ColorHolder.applyToOr(getDescriptionTextColor(), viewHolder.description, getTextColorStateList(getColor(ctx), getSelectedColor(ctx)));

The issue is in this line.

By default, the getDescriptionTextColor() returns null, so .applyToOr() will apply the currently selected color from the second state list.

but getSelectedColor(ctx) returns the background color, while getSelectedTextColor(ctx) returns the selected text color.

This means if no description text color is defined (using withDescriptionTextColor()), then it will set the text color of the description to the background color.

So, to replicate it:

Just select one of the Secondary items which have a description.

**Comment by mikepenz** [comment]
@justjanne oh ok i see. Fixed it in the b23 of the v5.0.0
https://github.com/mikepenz/MaterialDrawer/issues/920#issuecomment-177483238

Thanks again for the detailed report

**Comment by justjanne** [comment]
Sorry that I couldn't report it in detail earlier, didn't have much time then.

**Comment by mikepenz** [comment]
@justjanne don't worry. I should have seen it earlier :D sometimes I just search for the wrong thigns.

**Comment by justjanne** [comment]
It was just pretty noticeable in this use case: http://imgur.com/qBlU2VA

You ended up with only topics being transparent, except if they also had an mirc front color set.

Really weird.
