### ISSUE TITLE
Change orientation of Footer Item

### ISSUE THREAD

**Issue by ChoHyun-myung** [mikepenz/MaterialDrawer#961]
Good Evening! Thx for solving the previous request.
I want to ask that is it possible to make sticky item's orientation for horizontal.
It means, Generally DrawerItem's orientation is vertical like listview, but i want to change orientation for horizontal in sticky footer.
Like below one
![image](https://cloud.githubusercontent.com/assets/16913794/12675827/6375b0a2-c6d0-11e5-9107-ac4338a7ebca.png)
연세대, 즐겨찾기, 설정 is DrawerItem separtely and sticky footer.

**Comment by mikepenz** [comment]
@ChoHyun-myung you can use any view you like in the `StickyFooter` Just provide the view you want to set. 

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L768
