### ISSUE TITLE
Update Badge

### ISSUE THREAD

**Issue by darienalvarez** [mikepenz/MaterialDrawer#962]
How i can update the badge text at runtime?

**Comment by rubengees** [comment]
Use the `updateBadge` of your `Drawer` object.

```java
drawer.updateBadge(drawerItemId, new StringHolder(text));
```

**Comment by mikepenz** [comment]
Thanks @rubengees for answering. 

As @rubengees already correctly mentioned you can either use the `updateBadge` method. Or you just change the badge, and notify the `Drawer` about the updated item.

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L230

**Comment by rezafelegari** [comment]
i want to update badge after get data from server, however the Response of Retrofit call in mainThread and in block of OnResponse i write Command of update that you said in document but  Does not work.

**Comment by rezafelegari** [comment]
about that problem, i sloved it by change the version of library from 6.0.2 >6.0.6
