### ISSUE TITLE
DrawerItems with Different  background colors

### ISSUE THREAD

**Issue by denebchorny** [mikepenz/MaterialDrawer#964]
Hi sir, I have a doubt.
I would like to use a particular background for every item. Is it possible?

Let me show you an example what I want.

This is the original drawer when I open it: http://postimg.org/image/pyjelkeat/

When I select an item (principal one) it is highlighted with a color and it expands items. Then, this subitems have another background and I can select them and show another color on selected item.

http://postimg.org/image/ct3wfgkf9/

Thanks in advance

**Comment by mikepenz** [comment]
@denebchorny if the default `DrawerItem`s do not fit your needs, you can easily create `CustomDrawerItems` which do what you need. By default the `DrawerItems` just allow you to define the selected background color. As you need a different background color in common you may check one sample `CustomDrawerItem` which only alters the Background behavior of the default `DrawerItem`

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/drawerItems/CustomPrimaryDrawerItem.java

Regarding expandable items. It is possible with v4.x already, but v5.x will come with huge improvements in this area.
