### ISSUE TITLE
Add / Remove Draweritem without fade effect or change effect

### ISSUE THREAD

**Issue by denebchorny** [mikepenz/MaterialDrawer#965]
Lighter than the title,  impossible.
I wonder if I can change the effect when  an Item is added or deleted from the drawer.

And also I want to know if I can remove the fade effect. I just wnat the item to appear as fast as it can without any effect.

Thanks in advance

**Comment by mikepenz** [comment]
@denebchorny at the moment you could either define `withHasStableIds(false)` https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L112 or you get the `RecyclerView` after the `Drawer` was generated and set `null` as `RecyclerView.ItemAnimator`
