### ISSUE TITLE
how to update the header profile icon when user login from facebook?

### ISSUE THREAD

**Issue by Mayank1904** [mikepenz/MaterialDrawer#966]

**Comment by mikepenz** [comment]
```java
profile.withIcon("https://avatars1.githubusercontent.com/u/634243?v=3&s=96");
headerResult.updateProfile(profile);
```

**Comment by Mayank1904** [comment]
Thanks for the reply but i am getting blank image when i pass the URL of the image

         private AccountHeader headerResult = null;
         private Drawer result = null;
         IProfile profile = new   ProfileDrawerItem().withName(userName).withEmail(emailID).withIcon(R.drawable.icon).withIdentifier(2000);

        headerResult = new AccountHeaderBuilder().withActivity(this).withHeaderBackground(R.drawable.header).addProfiles(profile).withOnAccountHeaderListener(new AccountHeader.OnAccountHeaderListener() {
            @Override
            public boolean onProfileChanged(View view, IProfile profile, boolean current) {
                return false;
            }
        }).withSavedInstance(savedInstanceState)
                .build();
        item1 = new PrimaryDrawerItem().withName(R.string.login).withSelectable(false).withIdentifier(2001);
        item2 = new PrimaryDrawerItem().withName(R.string.logout_popup).withSelectable(false).withIdentifier(2002);
        item3 = new PrimaryDrawerItem().withName(R.string.my_quiz).withSelectable(false).withIdentifier(2003);
        item4 = new PrimaryDrawerItem().withName(R.string.register).withSelectable(false).withIdentifier(2004);
        item5 = new PrimaryDrawerItem().withName(R.string.Feedback).withSelectable(false).withIdentifier(2005);

        if (profilePic != null) {
        
            profile.withIcon(profilePic);
            headerResult.updateProfile(profile);

        }

**Comment by mikepenz** [comment]
@Mayank1904 you have defined a `DrawerImageLoader`? https://github.com/mikepenz/MaterialDrawer#load-images-via-url

**Comment by Mayank1904** [comment]
No sir I had not defined. Can you please tell me how to defined that loader in my code if profilePic contains the URL of the image

**Comment by mikepenz** [comment]
@Mayank1904 in the sample app this is done via the `CustomApplication` 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java

**Comment by Mayank1904** [comment]
but i did not know how to use this sample in my application

**Comment by Mayank1904** [comment]
ok sorry now i understand how to use this. Thanks for the help sir .Thank you very much for supporting me
