### ISSUE TITLE
Method saveInstanceState(saveInstanceState)/withSavedInstanceState(saveInstanceState) does not distinguish different drawers.

### ISSUE THREAD

**Issue by roughboy** [mikepenz/MaterialDrawer#969]
I have two drawers in my activity - one LEFT and one RIGHT. When I call saveInstanceState, the selected  position of one drawer is being overwritten by position of the other drawer. The code of methods saveInstanceState/withSavedInstanceState does not distinguish drawer's gravity.

**Comment by mikepenz** [comment]
@roughboy it does if you set up the first drawer, and append the second:
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/MultiDrawerActivity.java#L132
