### ISSUE TITLE
Additional shadow in RTL mode

### ISSUE THREAD

**Issue by Blaster-777** [mikepenz/MaterialDrawer#971]
how to remove extra shadow in RTL mode?

![untitled-1](https://cloud.githubusercontent.com/assets/6900291/12701772/6c0affce-c829-11e5-844e-e4d4443c6631.png)

**Comment by mikepenz** [comment]
@Blaster-777 is this a normal `Drawer` or `MiniDrawer`?

**Comment by mikepenz** [comment]
If you use the `MiniDrawer` see the following:
https://github.com/mikepenz/MaterialDrawer/blob/791ec2ea7c8f68ab7add77f3ff2a520713e3f14b/app/src/main/java/com/mikepenz/materialdrawer/app/MiniDrawerActivity.java#L164

**Comment by Blaster-777** [comment]
normal Drawer

**Comment by mikepenz** [comment]
@Blaster-777 which gravity have you set? 

Depending on the gravity i set the correct shadow on API < 21
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L1572

**Comment by Blaster-777** [comment]
i don't set any gravity

**Comment by PouyaDEON** [comment]
@mikepenz Hi Mike, I Have Same Issue With This Shadow
It Will happening when using `Gravity.LEFT` or if The Device Language is Farsi/Persian Or Any RTL else Languages...
It Won't Happen If You Use `Gravity.START` 

**

> Samsung Note II - API 19
> Normal Drawer
> 

*

**Comment by mikepenz** [comment]
As mentioned you should use `Gravity.START`
