### ISSUE TITLE
Integrating TreeView-like structure for secondaryMenu

### ISSUE THREAD

**Issue by DavidMont** [mikepenz/MaterialDrawer#973]
I finally integrate my app to this beautiful Drawer. but I just want to ask if this is possible to integrate in the existing secondaryMenu.

https://github.com/bmelnychuk/AndroidTreeView

Integrate above library or create for this library either one is fine.  Is it ok?

**Comment by mikepenz** [comment]
@DavidMont you can have something similar. Just add items with a different level 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L193

The whole subitems thing will get even easier in v5.0.0

**Comment by DavidMont** [comment]
@mikepenz oh I've already done that actually, I just want to have an indicator that the secondaryMenuDrawer is the child of primaryMenuDrawer.

anyway thanks.

**Comment by mikepenz** [comment]
@DavidMont if you want that `subItems` look different different background color, or test color, just provide those settings for the subItems. 

If you need a complete different look of those items, you can create a `CustomDrawerItem` (or many of them :D) which look like you need it. 

https://github.com/mikepenz/MaterialDrawer/issues/876#issuecomment-165237505
