### ISSUE TITLE
Disable SecondaryDrawerItem

### ISSUE THREAD

**Issue by qzaqza1818** [mikepenz/MaterialDrawer#974]
Hi, is there any way to disable a secondary drawer item?

**Comment by mikepenz** [comment]
@qzaqza1818 what do you mean with disable? 

Just not selectable?
Or not clickable?
Or greyed out?

**Comment by mikepenz** [comment]
But normally you would use `.withEnableD(false)`

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/AdvancedActivity.java#L86

**Comment by qzaqza1818** [comment]
Oh Thank you very much.
