### ISSUE TITLE
How can use collapse Icon.

### ISSUE THREAD

**Issue by atulgoswami21** [mikepenz/MaterialDrawer#977]
Hello,
How could i implement or use Icon in Collapse parent Item.

**Comment by mikepenz** [comment]
@atulgoswami21 could you please be a bit more specific?

**Comment by atulgoswami21** [comment]
Yes I need an arrow identifying that this item is expandable.

**Comment by mikepenz** [comment]
May you check out the `FastAdapter` (https://github.com/mikepenz/FastAdapter) sample where i created something similar. 

You can create a `CustomDrawerItem` for the drawer which does exactly the same

**Comment by atulgoswami21** [comment]
Thanks i will try.
But i feel it should be included by default in expendable items.
hoping for next version.
