### ISSUE TITLE
Set Right Drawer Width To Full Width of Screen

### ISSUE THREAD

**Issue by patelakshay13890** [mikepenz/MaterialDrawer#978]
How to Set Right Drawer Width To Full Width of Screen so that it look like a normal screen animated from Right Side ???

**Comment by mikepenz** [comment]
@patelakshay13890 i think the `DrawerLayout` doesn't allow this, but you can try and set the width.
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java#L455

and just pass the screenWidth

**Comment by patelakshay13890** [comment]
But instead of width in px or sp i want like Match_Parent

**Comment by mikepenz** [comment]
@patelakshay13890 not possible

**Comment by patelakshay13890** [comment]
What if I set width to larger width than Screen Width then what will happen ??

**Comment by mikepenz** [comment]
@patelakshay13890 it may will display it wrong. Why don't you just set the screen width? You can get the screen width from your Android device. 

That's no limitation of the `MaterialDrawer` that's just how the `DrawerLayout` works. A `Slider` so the thing you can drag in, has to define an exact width. 

(You can try to define the `Slider` width `MATCH_PARENT` but I don't know what will happen, just use `. withDrawerWidthPx(View.MATCH_PARENT)`)

**Comment by patelakshay13890** [comment]
Okay & How can I have HamburgerIcon and My App Icon same as in Flipkart
Android App..???

**Comment by mikepenz** [comment]
that has nothing to do with the drawer. Either you use the default `ActionBarDrawerToggle` and keep the default as defined in the `Material Design Guidelines` or you implement your custom behavior but then you have to open / close the drawer manually, and manually implement and find the logic how you can get that look
