### ISSUE TITLE
Question: can I add my account header directly using the Drawer (not builder)

### ISSUE THREAD

**Issue by aminabs** [mikepenz/MaterialDrawer#979]
Can I set an account header instance on the com.mikepenz.materialdrawer.Drawer without using the builder's withAccountHeader method?
Is it enough to call:
`myAccountHeader.setDrawer(drawer);`
 
or shall I append this:
`drawer.getMiniDrawer().withAccountHeader(mAccountHeader)` ?

(I need a simple account header, don't know much about MiniDrawer or what the above line does exactly)

Excuse me for answering a question without labeling it as 'question'. (I simply don't know how to)
Thanks in advance.

**Comment by mikepenz** [comment]
@aminabs if you can't create the `AccountHeader` during the creation of the `Drawer` you can also add an `AccountHeader` at a later time. 

To link them together, you have to tell the `AccountHeader` about the drawer, and add the `Header`-View to the drawer
```
//set the view to the result
result.setHeader(headerResult.getView());
//set the drawer to the header (so it will manage the profile list correctly)
headerResult.setDrawer(result);
```

In your app you also use the `MiniDrawer`?
So you also have to tell the `MiniDrawer` about the `AccountHeader`, and rebuild the view
```java
//hook together MiniDrawer and AccountHeader ( so it can display the selected profile )
drawer.getMiniDrawer().withAccountHeader(mAccountHeader);
//rebuild the view so the account is displayed
drawer.getMiniDrawer().createItems();
```
