### ISSUE TITLE
Drawer icon in right side

### ISSUE THREAD

**Issue by nemati456** [mikepenz/MaterialDrawer#980]
i use 
`withDrawerGravity(Gravity.END)`

but drawer icon is on the left side i want to right side what should i do?

Thanks a lot

**Comment by mikepenz** [comment]
@nemati456 this has nothing to do with the `MaterialDrawer` that's standard `Toolbar` android behavior. If you want it on the other side, your application has to be in RTL mode.

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/AndroidManifest.xml#L11

https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L55
