### ISSUE TITLE
Badge 

### ISSUE THREAD

**Issue by qzaqza1818** [mikepenz/MaterialDrawer#981]
I am able to use updateBadge function to update the badge for a drawer item with identifier. 
Here is the question, can it retrieve the value in badge first then update?

For example, the badge is 1 in a drawer item. Whenever I use updateBadge function, I want it to be able to retrieve the current value from the badge and add the value I appoint to it.

The badge at first is 1, when I use function updateBadge(1(identifier), 1(value to add), add(add or minus)) then the badge will become 2. Do you plan on implement this function? In conclusion, a updateBadge function for integer value only.

**Comment by justjanne** [comment]
You can get the draweritem by a position, like drawer.getDrawerItem(int position). Then you should be able to get the StringHolder for the Badge with getBadge(). Then you can do .getString() on the StringHolder to get its text. Then you can do Integer.parseInt() to get the text as integer.

(Sorry if the names of the functions don't match the actual ones exactly, I'm on mobile and can't really check right now)

**Comment by mikepenz** [comment]
@justjanne thanks for answering

**Comment by qzaqza1818** [comment]
thank you for your help
