### ISSUE TITLE
Badge on hamburger menu icon

### ISSUE THREAD

**Issue by bhartsock** [mikepenz/MaterialDrawer#984]
Hello,

I am implementing this Nav Drawer in my app and I have badges working great. My only question is how do I get the badge to appear on the hambuger menu icon when the Nav Drawer is collapsed? When an event happens in my app, I would like to update not only the DrawerItem with a badge count but also the hamburger menu icon if it happens to be collapsed. I would like similar functions like the Ebay app.

![wzzdc](https://cloud.githubusercontent.com/assets/10117412/12819279/799fd662-cb28-11e5-9a82-53f5924e86fd.png)

Is this possible?

Thanks!

**Comment by mikepenz** [comment]
@bhartsock that is independent of the `MaterialDrawer` the `ActionBarDrawerToggle` which can be managed by the `Drawer` doesn't allow you to do this. This will require a custom image for the toolbar, and then you will have to manually handle the open / close of the drawer.

**Comment by bhartsock** [comment]
Awesome,

I got it working. Thank you for your suggestion.

On Thu, Feb 4, 2016 at 11:19 AM, Mike Penz <notifications@github.com> wrote:

> @bhartsock <https://github.com/bhartsock> that is independent of the
> MaterialDrawer the ActionBarDrawerToggle which can be managed by the
> Drawer doesn't allow you to do this. This will require a custom image for
> the toolbar, and then you will have to manually handle the open / close of
> the drawer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikepenz/MaterialDrawer/issues/984#issuecomment-179926318>
> .
>



-- 
<http://www.gemr.com/>
Brian Hartsock | Android Developer
| *a.* 230 Commerce Way Ste 325 Portsmouth NH
| *m.* 603.531.0857
| *e.* brian@gemr.com
| *w.* www.gemr.com
<http://www.facebook.com/gemrsocial> <http://www.twitter.com/gemr>
<https://www.youtube.com/channel/UCuD4UbaSPjPV8sm78UdjF5A>
<http://www.instagram.com/gemrsocial>
<https://www.linkedin.com/company/5148026?trk=tyah&trkInfo=clickedVertical%3Acompany%2Cidx%3A2-1-6%2CtarId%3A1430418920434%2Ctas%3Agemr>

**Comment by mikepenz** [comment]
@bhartsock great :). It would be great if you could add your solution here so others can find it.

**Comment by bhartsock** [comment]
To all those who are interested, this is what I did.

Make sure that you remove the .withToolbar() when creating the DrawerBuilder. This will have to be managed manually.

In your toolbar layout, add the following:

![badge](https://cloud.githubusercontent.com/assets/10117412/12849461/ba15b1ba-cbed-11e5-9512-eef1b4daecc5.png)

Create this drawable to use as the background:

![drawable](https://cloud.githubusercontent.com/assets/10117412/12849483/d2b08768-cbed-11e5-81aa-211fc0efdab5.png)

You will have to hook up a click listener to the nav_drawer_menu to open the drawer. I put this code within my ToolbarFragment class:

![snipet](https://cloud.githubusercontent.com/assets/10117412/12849657/d51667ce-cbee-11e5-9671-4cff27d4c032.png)

As for the badge count, whenever you want to increment it I call this helper:

![untitled](https://cloud.githubusercontent.com/assets/10117412/12849730/3196e302-cbef-11e5-900d-4e58ccd3432b.png)

Here it is:

![final](https://cloud.githubusercontent.com/assets/10117412/12849923/19ce281a-cbf0-11e5-964b-169a9fe8350a.png)

**Comment by mikepenz** [comment]
@bhartsock awesome. thanks

**Comment by sbettal** [comment]
@bhartsock  please provide the complete code.
