### ISSUE TITLE
MaterialDrawer + Fragments issue.

### ISSUE THREAD

**Issue by vados60** [mikepenz/MaterialDrawer#985]
Hello, Mike!

Thx for such a great lib!

Now facing such issue: trying to combine Material Drawer (AdvancedActivity) with MaterialViewPager 
( https://github.com/florent37/MaterialViewPager )

From Drawer i replace fragments in Activity.

The problem is the following: can't place Hamburger icon. when do HomeUp arrow - everything is perfect, but can't set Hamburger icon(

so 
```java
if (showBackButton) {
            drawer.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false);
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        }else {
            getSupportActionBar().setDisplayHomeAsUpEnabled(false);
            drawer.getActionBarDrawerToggle().setDrawerIndicatorEnabled(true);
} 
```
doesn't work.

Screenshots attached:

http://joxi.ru/Vm6yaQ8cx3dEzr
http://joxi.ru/vAWDl3Psk3QLZr

Will appreciate any help!

Good Luck!

**Comment by mikepenz** [comment]
@vados60 i can't tell from the provided information what is causing your issue here. the `Toolbar` is part of the `Activities` layout, and you provide it to the `DrawerBuilder` ?

**Comment by vados60** [comment]
@mikepenz

No. I provided Toolbar from Fragment's layout via drawer.setToolbar()

**Comment by mikepenz** [comment]
i expect that the `getSupportActionBar()` (which comes from the activity, if you call it from the activity) does not correctly forward this to the `Toolbar` from the fragment

**Comment by dexion** [comment]
Answer is in https://github.com/mikepenz/MaterialDrawer/issues/967

In your `Fragment` use this:

```JAVA
Toolbar toolbar = (Toolbar) rootView.findViewById(R.id.toolbar);
        if (null != toolbar && null != ((MainActivity) getActivity()).getDrawer()) {
            ((AppCompatActivity) getActivity()).setSupportActionBar(toolbar);
            ActionBarDrawerToggle mActionBarDrawerToggle = new ActionBarDrawerToggle(getActivity(),  ((MainActivity) getActivity()).getDrawer().getDrawerLayout(), toolbar, R.string.drawer_open, R.string.drawer_close);
            mActionBarDrawerToggle.syncState();
            ((AppCompatActivity) getActivity()).getSupportActionBar().setDisplayHomeAsUpEnabled(false);
            mActionBarDrawerToggle.setDrawerIndicatorEnabled(true);

            ((MainActivity) getActivity()).getDrawer().setActionBarDrawerToggle(mActionBarDrawerToggle);
        }
```
