### ISSUE TITLE
Issue with background and convertView

### ISSUE THREAD

**Issue by Antilamer1709** [mikepenz/MaterialDrawer#987]
Hi! I have several issues, can you help me?
What for convertView and how i can with it change color of font, size of icon? How to remove Description and Badge if i don't need it? And how i can set a background color or image?

**Comment by mikepenz** [comment]
@Antilamer1709 could you please add some context? What are you trying to achieve. And what are you trying at the moment?

Most of the things you mentioned can be easily changed on a normal `DrawerItem` via the `with*` methods

**Comment by Antilamer1709** [comment]
@mikepenz Thank for you reply, but after 2 days working i realized that problem was in versions.
One more question: how i can insert an svg images?

**Comment by mikepenz** [comment]
@Antilamer1709 regarding the margin. can you please add a screenshot. the default margin inside the items is the one specified in the Material Design Guideliens and i highly recommend you stay with ith
