### ISSUE TITLE
getCurrentAccountHeader.

### ISSUE THREAD

**Issue by Grozny** [mikepenz/MaterialDrawer#99]
can you add getCurrentAccountSelection like getCurrentSelection() Drawer

**Comment by mikepenz** [comment]
@Grozny this method returns the position within the listView so it's a different case. 

To get the current account i would recommend to add a listener (`withOnAccountHeaderListener` and listen to the selection and remember the item) 

Perhaps there will be a method in the future to get the current selected items in their correct order.

**Comment by Grozny** [comment]
Why there is no getcurrentprofile method as getCurrentSelection in Drawer class.
I think it would be an added value.

**Comment by mikepenz** [comment]
Why not just manage it via the Identifier and update the list in the onProfileChanged listener?

**Comment by Grozny** [comment]
Because identifier i use to other function.
Em 29/05/2015 19:39, "Mike Penz" <notifications@github.com> escreveu:

**Comment by mikepenz** [comment]
@Grozny then i would recommend just keep track inside your activity with it. shouldn't be so much extra work
