### ISSUE TITLE
Adding/Removing subitems to an item and calling subitemsChanged does not properly update the list (5.0.0 Snapshot)

### ISSUE THREAD

**Issue by justjanne** [mikepenz/MaterialDrawer#991]
1. Create Primary Item with 3 subitems.
2. Expand.
3. Add 1 subitem
4. call itemchanged and subitemschanged.
5. Observe that the additional item is not added.
6. Collapse and Expand the item.
7. Observe that the additional item appears now.
8. Remove the subitem while expanded
9. call itemchanged and subitemschanged
10. Observe that the subitem is still there
11. Collapse and expand
12. Observe that the removed subitem is not collapsed properly.

**Comment by mikepenz** [comment]
This worked on my side:
Adding a subItem:
```java
((SecondaryDrawerItem) result.getDrawerItem(19)).getSubItems().add(new SecondaryDrawerItem().withName("CollapsableItem 2").withLevel(3).withIcon(GoogleMaterial.Icon.gmd_airline_seat_recline_normal).withIdentifier(2002));
result.getAdapter().notifyAdapterSubItemsChanged(result.getPosition(19));
```
Removing a subItem:
```java
((SecondaryDrawerItem) result.getDrawerItem(19)).getSubItems().remove(0);
result.getAdapter().notifyAdapterSubItemsChanged(result.getPosition(19));
```
