### ISSUE TITLE
Custom Header with Logout Button Right Corner

### ISSUE THREAD

**Issue by FranciscoMSM** [mikepenz/MaterialDrawer#992]
I'm trying to make something like this but with option of logout button in the right upper corner. I thought I can make via withHeader() but i loose all the previous features like arrow down to manage users functionality. What's the easiest to do it? If I've to do you with withHeader() method how can I manage to save your arrow down and manage users functionality?

Thanks :)

<img width="230" alt="captura de ecra 2016-02-08 as 12 42 32" src="https://cloud.githubusercontent.com/assets/5878425/12885950/e411b70e-ce61-11e5-9386-cbac2e01e1f1.png">

**Comment by mikepenz** [comment]
@FranciscoMSM the easiest way will be that you copy over the `material_drawer_header.xml` (you can overwrite the original if you keep the name else set it via `.withAccountHeader()`) 

Then you modify this layout and add your button. Make sure you don't remove any of the included views as otherwhise the `AccountHeader` will break. 
If you added your `Logout-Button` view. You create the `Drawer` and `AccountHeader` as you would normally do. After you created the header you can get the view of the `AccountHeader` and get the reference to your `Logout-Button` view.

```java
headerResult.getView().findViewById(R.id.your_logout_button)
//and your additional logic here...
```

**Comment by FranciscoMSM** [comment]
thank you it worked!

**Comment by gmikhail** [comment]
I think you need add this information (how add login/logout button via custom layout) in the README file. Many will find this information useful.

**Comment by mikepenz** [comment]
what do you want do achieve?
If you want to get a header which has nothing to do with the AccountHeader then just don't use the `AccountHeader` and simply add a normal header layout to the `Drawer` alone.

The AccountHeader has a very specific use case and as such a very specific layout and design (as of the guidelines)

**Comment by suarezu** [comment]
is there a guide to totally customize the header so that it only shows some of icon/name/email of a single profile without a drop-down and another logout button, and the custom header is also compatible with crossfade mini drawer? I think it also weird to show a drop-down with only 1 profile :D

**Comment by mikepenz** [comment]
If you want to totally customize it then simply don't use the `AccountHeader` define your layout you want to show, pass it as header to the drawer, and then handle actions manually. you can modify the layout as long as the main elements stay the same. but if you need something completely else which is not as defined in the guidelines then you might be better served by implementing your complete own drawer just by using the DrawerLayout, and not go with a library.

no they are not. only the AccountHeader's profiles will show up in the miniDraewr.

**Comment by mikepenz** [comment]
you can disable the dropdown via the API.

**Comment by suarezu** [comment]
my need satisfied by set **material_drawer_header_selection_text**, some choices of terms of this great library are quite personal 👍 thank you for this highly-customizable library
