### ISSUE TITLE
android:TextAppearance.Material.Widget.Button.Inverse  error

### ISSUE THREAD

**Issue by lectricas** [mikepenz/MaterialDrawer#995]
Hi. The thing is that new version 4.6.3 supports API 23 only. I don't want to make my compile version to 23, because I need to upgrade permissions for android 6.0
What should I do in this case?

**Comment by mikepenz** [comment]
@lectricas you mix up `targetSdkVersion` and `compileSdkVersion` 

The permissions will just jump in if you have `targetSdkVersion`. 

But for the latest support libraries you just have to be `compileSdkVersion` **23**. So you can update. 
It is also highly recommended to always be with the latest support libraries as those always fix a lot of bugs
