### ISSUE TITLE
Ability to centre drawer icons?

### ISSUE THREAD

**Issue by MiralDesai** [mikepenz/MaterialDrawer#996]
Am I missing something or is it not possible to centre the drawer icons within it's view. Mine are left aligned which means that the icons are not aligned with each other.

I tried searching the issues list but couldn't find a question relating to it. Is there a way to do this or do I have to create my own custom drawer layout?

Seems like it should be an easy thing to do. In the dev options if you have show layout bounds enabled and check out google photos, the icons are centred within the few. 

Anyway just wondering how I can achieve this, thanks. Love the library.

**Comment by or-dvir** [comment]
i am having the same issue.
i want to center the primary drawer items but i can't find how.

there is a function called withDrawerGravity(int gravity) but:
1) it doesn't say where these constants are coming from. is it from anroid.view.Gravity?
i tried Gravity.CENTER_HORIZONTAL but its not working.
2) the documentation says "sets the gravity for this drawer. START, LEFT | RIGHT, END".
does that mean the CENTER isn't supported?

**Comment by mikepenz** [comment]
@MiralDesai can you please add a screenshot showcasing what you want to achieve? I am not sure what you mean with the icons are left aligned. Or how you want to center them inside the normal drawer. 

@or-dvir you mix up some things. `DrawerGravity` means where the `Drawer` gets shown. there are 2 options. On the left edge, or on the right edge. No idea how the drawer slider should be displayed in the center ;). Or where it would slide too. 
You also might add some additional infos how the icons should be centered? You want a drawerItem without any text and just an icon? Which is in the center of the drawer?

**Comment by mikepenz** [comment]
@MiralDesai @or-dvir I have added an **Icon**-only (where the **Icon** is centered within the item) to the sample. This will only work with the **v5.0.0** of the `Drawer` (with some small modifications with previous versions too) You can check out the changes I did, to create a new `CustomDrawerItem`. Note it might looks more complicated than it is, because I kept this item very flexible allowing different colors etc. If you have a specific use case you might be able to remove many lines of this item. 

https://github.com/mikepenz/MaterialDrawer/commit/8c6c8f4b19efda23c3cd806ea274bc95f92c9718

**Comment by or-dvir** [comment]
sorry about getting the stuff mixed up.

what i mean is i want the text of each item to be in the center of the drawer (no icons).

this is the closest thing i could find to show what i mean:

see how the last item ("import" with blue arrow) is showing at the center of the drawer? (unlike the rest of the items which are aligned to the left).

https://www.google.co.il/url?sa=i&rct=j&q=&esrc=s&source=imgres&cd=&cad=rja&uact=8&ved=0ahUKEwiG8IaDiPLKAhUI7RQKHTHyC8cQjRwIBw&url=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F33152217%2Fandroid-navigation-view-align-menu-items&psig=AFQjCNFRzMrg92DML0AyH1FRvxemje9AnA&ust=1455360911400633

**Comment by mikepenz** [comment]
@or-dvir oh I see. That's even easier to achieve. See the following commit ;)

https://github.com/mikepenz/MaterialDrawer/commit/4151f0c7a2ab443748e5faa916d424009393baa5

**Comment by or-dvir** [comment]
@mikepenz thx for the reply mike, but  for some reason this doesn't work.
i added the java file for CustomCenteredPrimaryDrawerItem and the xml layout file but the item still aligns to the left and not the center.

i tried playing around with the xml file but no luck - always aligns to the left.
(also tried changing the size of the text BTW, and again this doesn't seem to work - text always remains the same size).


this is my code:
        drawerBuilder.addDrawerItems(new PrimaryDrawerItem().withName("Training #1").withSelectable(false).withTextColor(getResources().getColor(android.R.color.white)),
//                new PrimaryDrawerItem().withName("Exercise #1").withSelectable(false).withTextColor(getResources().getColor(android.R.color.white)),
               ** new CustomCenteredPrimaryDrawerItem().withName("Exercise #1").withSelectable(false).withTextColor(getResources().getColor(android.R.color.white)),**
                new PrimaryDrawerItem().withName("Exercise name").withSelectable(false).withTextColor(getResources().getColor(android.R.color.white)),
                new DividerDrawerItem(),
                new ContainerDrawerItem().withView(mDPexercise).withDivider(false).withViewPosition(ContainerDrawerItem.Position.NONE),
                new PrimaryDrawerItem().withName("Repetitions").withSelectable(false).withTextColor(getResources().getColor(android.R.color.white)),
                new DividerDrawerItem());



p.s.
there is an issue with the function "public int getType()" in the CustomCenteredPrimaryDrawerItem class: its telling me that the return type of this functions in fact needs to be a string and not an int.
what i did was simply comment that function out. could that have something to do with the item still aligning to the left?

i thought maybe this is a version issue so i tried changing the version from 4.6.4 to 5.0.0 in the build.gradle from this:
    compile('com.mikepenz:materialdrawer:**4.6.4**@aar') {
        transitive = true
    }

to this:
    compile('com.mikepenz:materialdrawer:**5.0.0**@aar') {
        transitive = true
    }

but im getting "Failed to resolve: com.mikepenz:materialdrawer:5.0.0"


am i missing something?

**Comment by mikepenz** [comment]
Because v5.0.0 is still in testing: https://github.com/mikepenz/MaterialDrawer/issues/920

**Comment by or-dvir** [comment]
alright... but what about the centered item not working?

**Comment by mikepenz** [comment]
@or-dvir I tested the centered item. It was definitely centered on my device. I think that happens because you have decommented the `getType()` function.

**Comment by or-dvir** [comment]
well how am i supposed to fix it? it says it requires a return type of String and not int like in the link you sent.

what string should i return?

**Comment by mikepenz** [comment]
@or-dvir if you use v5.0.0 it will work. As mentioned the samples I did for you were for v5.0.0

**Comment by MiralDesai** [comment]
Sorry I'm not replying. On holiday right now with terrible internet. Will update when I can.

Will add a screenshot now. If it uploads...

**Comment by MiralDesai** [comment]
http://imgur.com/80sKrjl

**Comment by MiralDesai** [comment]
Notice how the icons are centred in their views. Whereas with my drawer they are all aligned to the left.

The view is the same size from what I can tell. Sorry for mirror posts, this will be the last for a bit, internet is just crap here.

**Comment by mikepenz** [comment]
@MiralDesai ok. May also add a Screenshot + the exact device specifications where the icons are not centered within the bounds

**Comment by MiralDesai** [comment]
Device is a nexus 5, but I don't think it's device specific since it was the same on many of my test devices at the time I was still at work.

https://imgur.com/4AQvrZm

**Comment by mikepenz** [comment]
@MiralDesai oh I see. No that's correct. This allows me to properly display the items in RTL mode. It is also required as my items have the `Badge`. As an addition it also allowed me to have no overdraw. So it is correct.

**Comment by MiralDesai** [comment]
@mikepenz Isn't the badge at the end of the item though? The text of an item can remain where it is surely?

Is there anyway I can override this? I don't need RTL support. No overdraw is important but it looks so out of place. 

At the very least do you know how much space the icon bounds take up? I can get my designer to maybe add padding to the icons and centre them for me if I can't do it via code.

Thanks.

**Comment by mikepenz** [comment]
@MiralDesai yes it is, but in RTL mode it is in the opposite. 

You can overwrite this if you want. Just copy and paste the layout into your project and modify it to your needs. I do not really know why you think it is out of place. The paddings and spacings are exact as defined in the Material Design Guidelines. So the icon is perfectly positioned. It may look strange if you enable to see the view bounds. 

Here is the exact specification as of Google
https://www.google.com/design/spec/patterns/navigation-drawer.html

**Comment by MiralDesai** [comment]
Sorry, my icons are out of place, not the view bounds or anything like that. I noticed this when updating the design of my drawer. With the view bounds disabled, the 4th icon down looks like it isn't aligned with the others. Probably because of the + sign.

I'll try a few things when I get back from my holiday as you suggest. I'll most likely grab the layout and modify it. Thanks for the advice.
