### ISSUE TITLE
Modify Badge at Runtime

### ISSUE THREAD

**Issue by Fillini** [mikepenz/MaterialDrawer#998]
Hello, thanks fo you awesome lib.  How i can change badge style runtime? Or how show/hide badge runtime

**Comment by mikepenz** [comment]
Changing a `Badge` works exactly as updating a `DrawerItem` at runtime. 
https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

Modify and change the `DrawerItem`. And notify the `Drawer` about the updated `DrawerItem`. As the `Badge` is part of the `DrawerItem` this will work exactly the same.

**Comment by Fiks33** [comment]
@mikepenz can you explain more how to modify a drawer item and remove the badge, where do i put .withBadge((StringHolder) null) if i need to remove badge on draweritem Click

**Comment by mikepenz** [comment]
@Fiks33 on the `item`.
Shown here: https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

**Comment by Fiks33** [comment]
Now it worked, thanks Sir for very cool library
