### ISSUE TITLE
How do I make the drawer items act as buttons?

### ISSUE THREAD

**Issue by Nxt3** [mikepenz/MaterialDrawer#999]
#For example, I have "Dashboard", "Profile", and "Settings" drawer items.

When I press "Profile", I want it to open a new activity--no problem. However, upon returning to the MainActivity (where the drawer is), I don't want the _Profile_ drawer item selected.

My first thought is to override `onPause()` and put in `navDrawer.setSelection(navDrawer.getDrawerItem(DASHBOARD));`, but I wanted to make sure there wasn't a way with your library that I'm just not seeing.

Also, what would be the best way to close the drawer when leaving the current activity? It tends to be janky upon loading a new activity (I've put a `navDrawer.close();` call in `onResume()`).

Thank you!

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer#selecting-an-item

Just set the following on your `DrawerItem`
```java
withSelectable(false)
```
